var _ = `schinese`,
  _ = `管理本地化`,
  _ = `导出并导入本地化文件，以管理您整个活动字符串的翻译。`,
  _ = `导出和导入本地化文件，以管理您整个页面字符串的翻译。`,
  _ = `登录`,
  _ = `想要将此项目添加至您的愿望单、关注它或标记为已忽略，请先登录。点击“确定”将跳转至登录页面。`,
  _ = `登录或在 Steam 应用中打开此页面即可关注、购买游戏，或是将其加入愿望单。`,
  _ = `%1$s 已在 Steam Deck 上%2$s`,
  _ = `通过验证`,
  _ = `这款游戏及其他更多游戏已经经过完全测试，且%1$s。`,
  _ = `非常适合 Deck`,
  _ = `通过验证标志`,
  _ = `Steam Deck OLED`,
  _ = `Steam Deck 横幅：您的游戏，随身携带`,
  _ = `宣传片不一定代表实际的 Steam Deck 游戏体验`,
  _ = `%1$s 已找到（%2$s）`,
  _ = `未找到（%1$s）`,
  _ = `评测的应用`,
  _ = `其 Steam 评测在此栏目中显示的应用，以及顾客撰写了评测的应用。`,
  _ = `%1$s URL 已接受`,
  _ = `错误：URL 未指向 Steam 页面（商店/社区）`,
  _ = `无效输入`,
  _ = `标识词颜色`,
  _ = `背景渐变（顶部）`,
  _ = `背景渐变（底部）`,
  _ = `加入名单`,
  _ = `在下方选择型号报名 - 符合条件的顾客最多可以为 %1$s 个型号报名。`,
  _ = `您已在下列选定型号的名单中`,
  _ = `您已在下方所选型号的名单中 - 符合条件的顾客最多可以为 %1$s 个型号报名。`,
  _ = `是否退出名单？`,
  _ = `退出名单即意味着您不会被包含在此型号的随机名单中。您确定要离开吗？`,
  _ = `我已阅读并接受<1>条款和条件</1>。`,
  _ = `请查看下方的条款和条件`,
  _ = `登录以加入名单`,
  _ = `登录 Steam 以加入名单。选择“确定”以进入登录页面。`,
  _ = `%1$s前可随时加入名单。名单会在当天关闭并随机排序，而您将会在一天内收到含有结果的电子邮件。`,
  _ = `在下方选择一个型号以加入候补名单。`,
  _ = `名单已关闭并正在随机排序。您将在一天内收到含有结果的电子邮件。`,
  _ = `名单已关闭并正在随机排序。如果您错过了报名，仍然可以加入一个型号的候补名单并排到队列末尾。`,
  _ = `在下方选择型号报名。符合条件的顾客只能为 1 个型号报名。`,
  _ = `您已在 %1$s 的名单中`,
  _ = `您已在名单中`,
  _ = `是否更换型号？`,
  _ = `更换型号即意味着您将退出 %1$s 的名单。`,
  _ = `您将加入 %1$s 的名单。`,
  _ = `加入候补名单`,
  _ = `是否退出候补名单？`,
  _ = `退出候补名单即意味着放弃您在其中的位置。重新加入候补名单会将您移至名单末位。`,
  _ = `是否更换候补名单？`,
  _ = `更换候补名单即意味着您将退出 %1$s 的候补名单，并放弃您在该队列中的位置。`,
  _ = `您将加入 %1$s 的候补名单。`,
  _ = `自 %2$s起便在候补名单中`,
  _ = `自 %2$s起便在 %1$s 的候补名单中`,
  _ = `在候补名单中`,
  _ = `您已在 %1$s 的候补名单中`,
  _ = `如果有货，我们会通过电子邮件通知您。`,
  _ = `请加入候补名单，您会在有货时收到通知。`,
  _ = `请加入候补名单，您会在有货时收到通知。此操作会取消您的预订。`,
  _ = `登录以加入候补名单`,
  _ = `登录 Steam 以加入候补名单。选择“确定”以进入登录页面。`,
  _ = `您已在 %1$s 的预订队列中`,
  _ = `适用<1>条款和条件</1>。`,
  _ = `dummy`,
  _ = `正常价格`,
  _ = `30 天最低价格`,
  _ = `当前价格`,
  _ = `dummy`,
  _ = {
    language: _,
    EventEditor_Loc_Title: _,
    EventEditor_Loc_Overview: _,
    EventEditor_Loc_Overview_Page: _,
    LoginRedirect_Dialog_Title: _,
    LoginRedirect_Dialog_Description: _,
    Wishlist_NotSignedIn: _,
    VerifiedProgram_DeckTitle: _,
    VerifiedProgram_DeckTitle_Verified: _,
    VerifiedProgram_DeckSubTitle: _,
    VerifiedProgram_GreatOnDeck: _,
    VerifiedProgram_DeckAlt: _,
    VerifiedProgram_DeckDeviceAlt: _,
    VerifiedProgram_DeckShopBannerAlt: _,
    VerifiedProgram_DeckDisclaimer: _,
    StoreItemFound: _,
    StoreItemNotFound: _,
    SteamReviewSection_AppID: _,
    SteamReviewSection_AppID_ttip: _,
    SteamURLAccepted: _,
    SteamURLInvalid: _,
    AnchorHashInputInvalid: _,
    Sale_Section_Label_Color: _,
    Sale_Section_Background_Top: _,
    Sale_Section_Background_Bottom: _,
    Reservation_JoinPool: _,
    Reserationn_NoListJoined: _,
    Reservation_InPool: _,
    Reservation_InPool_NoDate: _,
    Reservation_Cancel_Pool: _,
    Reservation_Cancel_Pool_Desc: _,
    Reservation_JoinPool_Terms: _,
    Reservation_JoinPool_ClickTerms: _,
    Reservation_Pool_NotSignedIn: _,
    Reservation_Pool_NotSignedIn_Desc: _,
    Reservation_InPool_Message_Date: _,
    Reservation_Pool_Closed: _,
    Reservation_Pool_InProgress_Joined: _,
    Reservation_Pool_InProgress_NotJoined: _,
    Reservation_NoListJoined_OneModel: _,
    Reservation_InPool_WithName: _,
    Reservation_InPool_NoName: _,
    Reservation_Change_Pool: _,
    Reservation_Change_Pool_Desc1: _,
    Reservation_Change_Pool_Desc2: _,
    Reservation_JoinWaitList: _,
    Reservation_Cancel_Waitlist: _,
    Reservation_Cancel_Waitlist_Desc: _,
    Reservation_Change_WaitList: _,
    Reservation_Change_WaitList_Desc1: _,
    Reservation_Change_WaitList_Desc2: _,
    Reservation_In_Waitlist: _,
    Reservation_In_Waitlist_WithName: _,
    Reservation_In_Waitlist_NoDate: _,
    Reservation_In_Waitlist_WithName_NoDate: _,
    Reservation_In_Waitlist_Message: _,
    Reservation_In_Waitlist_Message_NotJoin: _,
    Reservation_Join_Waitlist_Cancel_Reservation: _,
    Reservation_Waitlist_NotSignedIn: _,
    Reservation_Waitlist_NotSignedIn_Desc: _,
    Reservation_OnRegularReserveForModel: _,
    Reservation_PostShuffle_TAndC: _,
    machine_dummy: _,
    PriceGrid_NormalPrice: _,
    PriceGrid_RecentPrice: _,
    PriceGrid_CurrentPrice: _,
    Dummy: _,
  };
export {
  _ as AnchorHashInputInvalid,
  _ as Dummy,
  _ as EventEditor_Loc_Overview,
  _ as EventEditor_Loc_Overview_Page,
  _ as EventEditor_Loc_Title,
  _ as LoginRedirect_Dialog_Description,
  _ as LoginRedirect_Dialog_Title,
  _ as PriceGrid_CurrentPrice,
  _ as PriceGrid_NormalPrice,
  _ as PriceGrid_RecentPrice,
  _ as Reserationn_NoListJoined,
  _ as Reservation_Cancel_Pool,
  _ as Reservation_Cancel_Pool_Desc,
  _ as Reservation_Cancel_Waitlist,
  _ as Reservation_Cancel_Waitlist_Desc,
  _ as Reservation_Change_Pool,
  _ as Reservation_Change_Pool_Desc1,
  _ as Reservation_Change_Pool_Desc2,
  _ as Reservation_Change_WaitList,
  _ as Reservation_Change_WaitList_Desc1,
  _ as Reservation_Change_WaitList_Desc2,
  _ as Reservation_InPool,
  _ as Reservation_InPool_Message_Date,
  _ as Reservation_InPool_NoDate,
  _ as Reservation_InPool_NoName,
  _ as Reservation_InPool_WithName,
  _ as Reservation_In_Waitlist,
  _ as Reservation_In_Waitlist_Message,
  _ as Reservation_In_Waitlist_Message_NotJoin,
  _ as Reservation_In_Waitlist_NoDate,
  _ as Reservation_In_Waitlist_WithName,
  _ as Reservation_In_Waitlist_WithName_NoDate,
  _ as Reservation_JoinPool,
  _ as Reservation_JoinPool_ClickTerms,
  _ as Reservation_JoinPool_Terms,
  _ as Reservation_JoinWaitList,
  _ as Reservation_Join_Waitlist_Cancel_Reservation,
  _ as Reservation_NoListJoined_OneModel,
  _ as Reservation_OnRegularReserveForModel,
  _ as Reservation_Pool_Closed,
  _ as Reservation_Pool_InProgress_Joined,
  _ as Reservation_Pool_InProgress_NotJoined,
  _ as Reservation_Pool_NotSignedIn,
  _ as Reservation_Pool_NotSignedIn_Desc,
  _ as Reservation_PostShuffle_TAndC,
  _ as Reservation_Waitlist_NotSignedIn,
  _ as Reservation_Waitlist_NotSignedIn_Desc,
  _ as Sale_Section_Background_Bottom,
  _ as Sale_Section_Background_Top,
  _ as Sale_Section_Label_Color,
  _ as SteamReviewSection_AppID,
  _ as SteamReviewSection_AppID_ttip,
  _ as SteamURLAccepted,
  _ as SteamURLInvalid,
  _ as StoreItemFound,
  _ as StoreItemNotFound,
  _ as VerifiedProgram_DeckAlt,
  _ as VerifiedProgram_DeckDeviceAlt,
  _ as VerifiedProgram_DeckDisclaimer,
  _ as VerifiedProgram_DeckShopBannerAlt,
  _ as VerifiedProgram_DeckSubTitle,
  _ as VerifiedProgram_DeckTitle,
  _ as VerifiedProgram_DeckTitle_Verified,
  _ as VerifiedProgram_GreatOnDeck,
  _ as Wishlist_NotSignedIn,
  _ as default,
  _ as language,
  _ as machine_dummy,
};
