var _ = `turkish`,
  _ = `Yerelleştirmeyi Yönet`,
  _ = `Etkinliğinize ait dizgelerin yerelleştirmesini yönetmek için yerelleştirme dosyalarını dışa ve içe aktarın.`,
  _ = `Sayfanıza ait dizgelerin yerelleştirmesini yönetmek için yerelleştirme dosyalarını dışa ve içe aktarın.`,
  _ = `Giriş Yap`,
  _ = `Bu öğeyi istek listenize eklemek, takip etmek veya yok sayıldı olarak işaretlemek için giriş yapın. Tamam'a tıklamak sizi giriş yapma sayfasına yönlendirecektir.`,
  _ = `Giriş yaparak veya bu sayfayı Steam uygulamasında açarak istek listenize ekleyin, takip edin veya satın alın.`,
  _ = `%1$s, Steam Deck'te %2$s`,
  _ = `Onaylandı`,
  _ = `Bu oyunun ve çok daha fazlasının %1$s çalıştığı test edilmiştir.`,
  _ = `Deck'te Mükemmel`,
  _ = `Onaylandı İşareti`,
  _ = `Steam Deck OLED`,
  _ = `Steam Deck Afişi: "Oyunlarınız Her Yerde"`,
  _ = `Fragman, Steam Deck'teki gerçek oynanışı yansıtmayabilir.`,
  _ = `%1$s Bulundu (%2$s)`,
  _ = `Bulunamadı (%1$s)`,
  _ = `Uygulama İncelemeleri`,
  _ = `Bu bölümde Steam incelemeleri gösterilen uygulama ve bir müşteri incelemesi yazılan uygulama.`,
  _ = `%1$s URL'i Kabul Edildi`,
  _ = `Hata: URL bir Steam varlığı değil (mağaza/topluluk)`,
  _ = `Geçersiz Girdi`,
  _ = `Etiket Rengi`,
  _ = `Arka Plan Gradyanı (Üst)`,
  _ = `Arka Plan Gradyanı (Alt)`,
  _ = `Listeye Katıl`,
  _ = `Kaydolmak için aşağıdaki modellerden birini seçin. Uygun müşteriler en fazla %1$s model için kaydolabilir.`,
  _ = `Aşağıdaki seçilen modeller için listeye girdiniz.`,
  _ = `Aşağıdaki seçilen modeller için listeye girdiniz. Uygun müşteriler en fazla %1$s model için kaydolabilir.`,
  _ = `Listeden ayrılmak istiyor musunuz?`,
  _ = `Listeden ayrıldığınızda bu model için rastgele sıralamaya dâhil edilmeyeceksiniz. Emin misiniz?`,
  _ = `<1>Şartları ve koşulları</1>  okudum ve kabul ediyorum.`,
  _ = `Lütfen aşağıdaki şartları ve koşulları okuyun.`,
  _ = `Listeye katılmak için giriş yapın.`,
  _ = `Listeye katılmak için Steam'e giriş yapın. Giriş sayfasına gitmek için Tamam'ı seçin.`,
  _ = `%1$s tarihinden önce listeye dilediğiniz zaman katılabilirsiniz. Bu tarihte liste kapatılıp rastgele sıralanacak ve bir gün içinde size sonuçları içeren bir e-posta gönderilecektir.`,
  _ = `Bekleme listesine katılmak için aşağıdaki modellerden birini seçin.`,
  _ = `Liste kapatıldı ve şu anda rastgele sıralama yapılıyor. Sonuçlar bir gün içinde size e-postayla bildirilecektir.`,
  _ = `Liste kapatıldı ve şu anda rastgele sıralama yapılıyor. Vaktinde kayıt olmadıysanız, yine de bir model için bekleme listesinin sonuna eklenebilirsiniz.`,
  _ = `Kaydolmak için aşağıdaki modellerden birini seçin. Uygun müşteriler yalnızca bir model için kaydolabilir.`,
  _ = `%1$s listesindesiniz`,
  _ = `Listedesiniz`,
  _ = `Model değiştirmek ister misiniz?`,
  _ = `Model değiştirerek %1$s listesinden çıkmış olursunuz.`,
  _ = `%1$s listesine katılıyorsunuz.`,
  _ = `Bekleme Listesine Katıl`,
  _ = `Bekleme listesinden ayrılmak istiyor musunuz?`,
  _ = `Bekleme listesinden ayrılırsanız bekleme listesindeki yerinizi kaybedersiniz. Bekleme listesine tekrar katılmak sizi sıranın sonuna alır.`,
  _ = `Bekleme listelerini değiştirmek istiyor musunuz?`,
  _ = `Bekleme listenizi değiştirirseniz, %1$s bekleme listesinden çıkmış ve sıradaki yerinizi kaybetmiş olursunuz.`,
  _ = `%1$s için bekleme listesine katılıyorsunuz.`,
  _ = `%2$s tarihinden beri bekleme listesinde`,
  _ = `%2$s tarihinden beri %1$s bekleme listesinde`,
  _ = `Bekleme listesinde`,
  _ = `%1$s için bekleme listesindesiniz`,
  _ = `Ürün stoğa girerse size e-posta ile bildireceğiz.`,
  _ = `Bekleme listesine katılın, ürünler stoğa girerse bilgilendirileceksiniz.`,
  _ = `Bekleme listesine katılın, ürünler stoğa girerse bilgilendirileceksiniz. Bu işlem rezervasyonunuzu iptal edecektir.`,
  _ = `Bekleme listesine katılmak için giriş yapın.`,
  _ = `Bekleme listesine katılmak için Steam'e giriş yapın. Giriş sayfasına gitmek için Tamam'ı seçin.`,
  _ = `%1$s için rezervasyon sırasındasınız.`,
  _ = `<1>Şartlar ve koşullar</1> geçerlidir.`,
  _ = `dummy`,
  _ = `NORMALDE`,
  _ = `SON 30 GÜNDE EN DÜŞÜK FİYAT`,
  _ = `ŞİMDİ`,
  _ = `dummy`,
  _ = {
    language: _,
    EventEditor_Loc_Title: _,
    EventEditor_Loc_Overview: _,
    EventEditor_Loc_Overview_Page: _,
    LoginRedirect_Dialog_Title: _,
    LoginRedirect_Dialog_Description: _,
    Wishlist_NotSignedIn: _,
    VerifiedProgram_DeckTitle: _,
    VerifiedProgram_DeckTitle_Verified: _,
    VerifiedProgram_DeckSubTitle: _,
    VerifiedProgram_GreatOnDeck: _,
    VerifiedProgram_DeckAlt: _,
    VerifiedProgram_DeckDeviceAlt: _,
    VerifiedProgram_DeckShopBannerAlt: _,
    VerifiedProgram_DeckDisclaimer: _,
    StoreItemFound: _,
    StoreItemNotFound: _,
    SteamReviewSection_AppID: _,
    SteamReviewSection_AppID_ttip: _,
    SteamURLAccepted: _,
    SteamURLInvalid: _,
    AnchorHashInputInvalid: _,
    Sale_Section_Label_Color: _,
    Sale_Section_Background_Top: _,
    Sale_Section_Background_Bottom: _,
    Reservation_JoinPool: _,
    Reserationn_NoListJoined: _,
    Reservation_InPool: _,
    Reservation_InPool_NoDate: _,
    Reservation_Cancel_Pool: _,
    Reservation_Cancel_Pool_Desc: _,
    Reservation_JoinPool_Terms: _,
    Reservation_JoinPool_ClickTerms: _,
    Reservation_Pool_NotSignedIn: _,
    Reservation_Pool_NotSignedIn_Desc: _,
    Reservation_InPool_Message_Date: _,
    Reservation_Pool_Closed: _,
    Reservation_Pool_InProgress_Joined: _,
    Reservation_Pool_InProgress_NotJoined: _,
    Reservation_NoListJoined_OneModel: _,
    Reservation_InPool_WithName: _,
    Reservation_InPool_NoName: _,
    Reservation_Change_Pool: _,
    Reservation_Change_Pool_Desc1: _,
    Reservation_Change_Pool_Desc2: _,
    Reservation_JoinWaitList: _,
    Reservation_Cancel_Waitlist: _,
    Reservation_Cancel_Waitlist_Desc: _,
    Reservation_Change_WaitList: _,
    Reservation_Change_WaitList_Desc1: _,
    Reservation_Change_WaitList_Desc2: _,
    Reservation_In_Waitlist: _,
    Reservation_In_Waitlist_WithName: _,
    Reservation_In_Waitlist_NoDate: _,
    Reservation_In_Waitlist_WithName_NoDate: _,
    Reservation_In_Waitlist_Message: _,
    Reservation_In_Waitlist_Message_NotJoin: _,
    Reservation_Join_Waitlist_Cancel_Reservation: _,
    Reservation_Waitlist_NotSignedIn: _,
    Reservation_Waitlist_NotSignedIn_Desc: _,
    Reservation_OnRegularReserveForModel: _,
    Reservation_PostShuffle_TAndC: _,
    machine_dummy: _,
    PriceGrid_NormalPrice: _,
    PriceGrid_RecentPrice: _,
    PriceGrid_CurrentPrice: _,
    Dummy: _,
  };
export {
  _ as AnchorHashInputInvalid,
  _ as Dummy,
  _ as EventEditor_Loc_Overview,
  _ as EventEditor_Loc_Overview_Page,
  _ as EventEditor_Loc_Title,
  _ as LoginRedirect_Dialog_Description,
  _ as LoginRedirect_Dialog_Title,
  _ as PriceGrid_CurrentPrice,
  _ as PriceGrid_NormalPrice,
  _ as PriceGrid_RecentPrice,
  _ as Reserationn_NoListJoined,
  _ as Reservation_Cancel_Pool,
  _ as Reservation_Cancel_Pool_Desc,
  _ as Reservation_Cancel_Waitlist,
  _ as Reservation_Cancel_Waitlist_Desc,
  _ as Reservation_Change_Pool,
  _ as Reservation_Change_Pool_Desc1,
  _ as Reservation_Change_Pool_Desc2,
  _ as Reservation_Change_WaitList,
  _ as Reservation_Change_WaitList_Desc1,
  _ as Reservation_Change_WaitList_Desc2,
  _ as Reservation_InPool,
  _ as Reservation_InPool_Message_Date,
  _ as Reservation_InPool_NoDate,
  _ as Reservation_InPool_NoName,
  _ as Reservation_InPool_WithName,
  _ as Reservation_In_Waitlist,
  _ as Reservation_In_Waitlist_Message,
  _ as Reservation_In_Waitlist_Message_NotJoin,
  _ as Reservation_In_Waitlist_NoDate,
  _ as Reservation_In_Waitlist_WithName,
  _ as Reservation_In_Waitlist_WithName_NoDate,
  _ as Reservation_JoinPool,
  _ as Reservation_JoinPool_ClickTerms,
  _ as Reservation_JoinPool_Terms,
  _ as Reservation_JoinWaitList,
  _ as Reservation_Join_Waitlist_Cancel_Reservation,
  _ as Reservation_NoListJoined_OneModel,
  _ as Reservation_OnRegularReserveForModel,
  _ as Reservation_Pool_Closed,
  _ as Reservation_Pool_InProgress_Joined,
  _ as Reservation_Pool_InProgress_NotJoined,
  _ as Reservation_Pool_NotSignedIn,
  _ as Reservation_Pool_NotSignedIn_Desc,
  _ as Reservation_PostShuffle_TAndC,
  _ as Reservation_Waitlist_NotSignedIn,
  _ as Reservation_Waitlist_NotSignedIn_Desc,
  _ as Sale_Section_Background_Bottom,
  _ as Sale_Section_Background_Top,
  _ as Sale_Section_Label_Color,
  _ as SteamReviewSection_AppID,
  _ as SteamReviewSection_AppID_ttip,
  _ as SteamURLAccepted,
  _ as SteamURLInvalid,
  _ as StoreItemFound,
  _ as StoreItemNotFound,
  _ as VerifiedProgram_DeckAlt,
  _ as VerifiedProgram_DeckDeviceAlt,
  _ as VerifiedProgram_DeckDisclaimer,
  _ as VerifiedProgram_DeckShopBannerAlt,
  _ as VerifiedProgram_DeckSubTitle,
  _ as VerifiedProgram_DeckTitle,
  _ as VerifiedProgram_DeckTitle_Verified,
  _ as VerifiedProgram_GreatOnDeck,
  _ as Wishlist_NotSignedIn,
  _ as default,
  _ as language,
  _ as machine_dummy,
};
