var _ = `© %1$s Valve Corporation. All rights reserved. 모든 상표는 미국 및 기타 국가에서 해당 소유자의 재산입니다.<br>해당하는 경우 모든 가격에 부가가치세가 포함되어 있습니다.`,
  _ = `STEAM`,
  _ = `VALVE`,
  _ = `법적 고지`,
  _ = `더 보기`,
  _ = `Steam 정보`,
  _ = `Steam 이용 약관`,
  _ = `Steamworks`,
  _ = `Steam 배포`,
  _ = `기프트 카드`,
  _ = `Valve 소개`,
  _ = `채용 정보`,
  _ = `하드웨어`,
  _ = `재활용`,
  _ = `개인정보 처리방침`,
  _ = `접근성`,
  _ = `고지 및 정책`,
  _ = `쿠키`,
  _ = `환불`,
  _ = `Steam 다운로드`,
  _ = `모바일 앱 다운로드`,
  _ = `Steam 고객지원`,
  _ = `내 계정`,
  _ = `모바일 웹사이트 보기`,
  _ = {
    footer_legal_notice: _,
    footer_link_header_steam: _,
    footer_link_header_valve: _,
    footer_link_header_legal: _,
    footer_link_header_more: _,
    footer_link_about_steam: _,
    footer_link_steam_ssa: _,
    footer_link_steamworks: _,
    footer_link_steam_distribution: _,
    footer_link_gift_cards: _,
    footer_link_about_valve: _,
    footer_link_jobs: _,
    footer_link_hardware: _,
    footer_link_recycling: _,
    footer_link_privacy: _,
    footer_link_accessibility: _,
    footer_link_notices_and_policies: _,
    footer_link_cookies: _,
    footer_link_refunds: _,
    footer_link_get_steam: _,
    footer_link_get_mobile_apps: _,
    footer_link_get_support: _,
    footer_link_my_account: _,
    footer_view_mobile_website: _,
  };
export {
  _ as default,
  _ as footer_legal_notice,
  _ as footer_link_about_steam,
  _ as footer_link_about_valve,
  _ as footer_link_accessibility,
  _ as footer_link_cookies,
  _ as footer_link_get_mobile_apps,
  _ as footer_link_get_steam,
  _ as footer_link_get_support,
  _ as footer_link_gift_cards,
  _ as footer_link_hardware,
  _ as footer_link_header_legal,
  _ as footer_link_header_more,
  _ as footer_link_header_steam,
  _ as footer_link_header_valve,
  _ as footer_link_jobs,
  _ as footer_link_my_account,
  _ as footer_link_notices_and_policies,
  _ as footer_link_privacy,
  _ as footer_link_recycling,
  _ as footer_link_refunds,
  _ as footer_link_steam_distribution,
  _ as footer_link_steam_ssa,
  _ as footer_link_steamworks,
  _ as footer_view_mobile_website,
};
