var _ = `russian`,
  _ = `Управление локализацией`,
  _ = `Экспорт и импорт файлов локализации для управления переводом строк для всего события.`,
  _ = `Экспорт и импорт файлов локализации для управления переводом строк для всей страницы.`,
  _ = `Войдите в аккаунт`,
  _ = `Войдите, чтобы добавить этот продукт в список желаемого или скрыть его. Нажав OK, вы попадёте на страницу входа.`,
  _ = `Войдите в аккаунт или откройте эту страницу в приложении Steam, чтобы купить продукт, добавить его в желаемое или подписаться на него.`,
  _ = `%1$s %2$s со Steam Deck`,
  _ = `полностью совместима`,
  _ = `Эта игра, как и многие другие, проверена и %1$s.`,
  _ = `отлично работает на Steam Deck`,
  _ = `Полностью совместима`,
  _ = `Steam Deck OLED`,
  _ = `Баннер Steam Deck: «Ваши игры всегда с вами»`,
  _ = `Трейлер может не отражать реальный геймплей на Steam Deck`,
  _ = `Найдено %1$s (%2$s)`,
  _ = `Не найдено (%1$s)`,
  _ = `Обзоры приложения`,
  _ = `Приложение, обзоры которого отображаются в этом разделе. На него же написан обзор пользователя.`,
  _ = `%1$s Ссылка принята`,
  _ = `Ошибка: ссылка не ведёт на страницу в Steam (в магазине или сообществе)`,
  _ = `Недействительный ввод`,
  _ = `Цвет пометки`,
  _ = `Градиент фона (вверху)`,
  _ = `Градиент фона (внизу)`,
  _ = `Присоединиться к списку`,
  _ = `Выберите модель ниже, чтобы записаться. Пользователи с соответствующими критериям аккаунтами могут зарегистрироваться в списках для нескольких (до %1$s) моделей.`,
  _ = `Вы находитесь в списке бронирования выбранных ниже моделей`,
  _ = `Вы находитесь в списке бронирования выбранных ниже моделей. Пользователи с соответствующими критериям аккаунтами могут зарегистрироваться в списках для нескольких (до %1$s) моделей.`,
  _ = `Покинуть список?`,
  _ = `При отмене регистрации вы не будете включены в рандомизированный список бронирования этой модели. Вы уверены?`,
  _ = `Я прочитал(а) и принимаю <1>условия использования</1>.`,
  _ = `Ознакомьтесь с условиями использования ниже.`,
  _ = `Войдите в аккаунт, чтобы присоединиться к списку`,
  _ = `Войдите в Steam, чтобы присоединиться к списку. Нажмите ОК, чтобы перейти на страницу входа.`,
  _ = `Присоединитесь к списку в любое время до %1$s. После этого возможность присоединиться будет закрыта, а список сформируется случайным образом, и в течение суток вы получите электронное письмо с результатами.`,
  _ = `Выберите модель ниже, чтобы присоединиться к списку ожидания.`,
  _ = `Регистрация закрыта, и теперь происходит рандомизация списка. В течение суток вы получите электронное письмо с результатами.`,
  _ = `Регистрация закрыта, и теперь происходит рандомизация списка. Если вы не успели записаться, то всё ещё можете присоединиться к списку ожидания для одной модели в конце очереди.`,
  _ = `Выберите модель ниже, чтобы записаться. Пользователи с соответствующими критериям аккаунтами могут зарегистрироваться в списке только для одной модели.`,
  _ = `Вы находитесь в списке бронирования %1$s`,
  _ = `Вы находитесь в списке бронирования`,
  _ = `Изменить модель?`,
  _ = `Выбрав другую модель, вы покинете список бронирования %1$s.`,
  _ = `Вы присоединяетесь к списку бронирования %1$s.`,
  _ = `Присоединиться к списку ожидания`,
  _ = `Покинуть список ожидания?`,
  _ = `Покинув список ожидания, вы потеряете место в нём. При повторном вступлении вы окажетесь в конце списка.`,
  _ = `Поменять список ожидания?`,
  _ = `Переходя в другой список ожидания, вы покидаете список ожидания для бронирования %1$s и отказываетесь от своего места в очереди.`,
  _ = `Вы присоединяетесь к списку ожидания %1$s.`,
  _ = `В списке ожидания с %2$s`,
  _ = `В списке ожидания %1$s с %2$s`,
  _ = `В списке ожидания`,
  _ = `Вы находитесь в списке ожидания %1$s`,
  _ = `Вы получите уведомление по электронной почте, если устройство можно будет приобрести.`,
  _ = `Присоединитесь к списку ожидания, и вы получите уведомление, если устройства можно будет приобрести.`,
  _ = `Присоединитесь к списку ожидания, чтобы получить уведомление, когда устройство будет доступно. Это отменит ваше бронирование.`,
  _ = `Войдите в аккаунт, чтобы присоединиться к списку ожидания`,
  _ = `Войдите в Steam, чтобы присоединиться к списку ожидания. Нажмите ОК, чтобы перейти на страницу входа.`,
  _ = `Вы находитесь в очереди бронирования %1$s`,
  _ = `Действуют <1>условия использования</1>.`,
  _ = `dummy`,
  _ = `Цена для вас:`,
  _ = `ОБЫЧНАЯ`,
  _ = `МИН. ЗА 30 ДНЕЙ`,
  _ = `СЕЙЧАС`,
  _ = `dummy`,
  _ = {
    language: _,
    EventEditor_Loc_Title: _,
    EventEditor_Loc_Overview: _,
    EventEditor_Loc_Overview_Page: _,
    LoginRedirect_Dialog_Title: _,
    LoginRedirect_Dialog_Description: _,
    Wishlist_NotSignedIn: _,
    VerifiedProgram_DeckTitle: _,
    VerifiedProgram_DeckTitle_Verified: _,
    VerifiedProgram_DeckSubTitle: _,
    VerifiedProgram_GreatOnDeck: _,
    VerifiedProgram_DeckAlt: _,
    VerifiedProgram_DeckDeviceAlt: _,
    VerifiedProgram_DeckShopBannerAlt: _,
    VerifiedProgram_DeckDisclaimer: _,
    StoreItemFound: _,
    StoreItemNotFound: _,
    SteamReviewSection_AppID: _,
    SteamReviewSection_AppID_ttip: _,
    SteamURLAccepted: _,
    SteamURLInvalid: _,
    AnchorHashInputInvalid: _,
    Sale_Section_Label_Color: _,
    Sale_Section_Background_Top: _,
    Sale_Section_Background_Bottom: _,
    Reservation_JoinPool: _,
    Reserationn_NoListJoined: _,
    Reservation_InPool: _,
    Reservation_InPool_NoDate: _,
    Reservation_Cancel_Pool: _,
    Reservation_Cancel_Pool_Desc: _,
    Reservation_JoinPool_Terms: _,
    Reservation_JoinPool_ClickTerms: _,
    Reservation_Pool_NotSignedIn: _,
    Reservation_Pool_NotSignedIn_Desc: _,
    Reservation_InPool_Message_Date: _,
    Reservation_Pool_Closed: _,
    Reservation_Pool_InProgress_Joined: _,
    Reservation_Pool_InProgress_NotJoined: _,
    Reservation_NoListJoined_OneModel: _,
    Reservation_InPool_WithName: _,
    Reservation_InPool_NoName: _,
    Reservation_Change_Pool: _,
    Reservation_Change_Pool_Desc1: _,
    Reservation_Change_Pool_Desc2: _,
    Reservation_JoinWaitList: _,
    Reservation_Cancel_Waitlist: _,
    Reservation_Cancel_Waitlist_Desc: _,
    Reservation_Change_WaitList: _,
    Reservation_Change_WaitList_Desc1: _,
    Reservation_Change_WaitList_Desc2: _,
    Reservation_In_Waitlist: _,
    Reservation_In_Waitlist_WithName: _,
    Reservation_In_Waitlist_NoDate: _,
    Reservation_In_Waitlist_WithName_NoDate: _,
    Reservation_In_Waitlist_Message: _,
    Reservation_In_Waitlist_Message_NotJoin: _,
    Reservation_Join_Waitlist_Cancel_Reservation: _,
    Reservation_Waitlist_NotSignedIn: _,
    Reservation_Waitlist_NotSignedIn_Desc: _,
    Reservation_OnRegularReserveForModel: _,
    Reservation_PostShuffle_TAndC: _,
    machine_dummy: _,
    PriceDisplay_YourPrice: _,
    PriceGrid_NormalPrice: _,
    PriceGrid_RecentPrice: _,
    PriceGrid_CurrentPrice: _,
    Dummy: _,
  };
export {
  _ as AnchorHashInputInvalid,
  _ as Dummy,
  _ as EventEditor_Loc_Overview,
  _ as EventEditor_Loc_Overview_Page,
  _ as EventEditor_Loc_Title,
  _ as LoginRedirect_Dialog_Description,
  _ as LoginRedirect_Dialog_Title,
  _ as PriceDisplay_YourPrice,
  _ as PriceGrid_CurrentPrice,
  _ as PriceGrid_NormalPrice,
  _ as PriceGrid_RecentPrice,
  _ as Reserationn_NoListJoined,
  _ as Reservation_Cancel_Pool,
  _ as Reservation_Cancel_Pool_Desc,
  _ as Reservation_Cancel_Waitlist,
  _ as Reservation_Cancel_Waitlist_Desc,
  _ as Reservation_Change_Pool,
  _ as Reservation_Change_Pool_Desc1,
  _ as Reservation_Change_Pool_Desc2,
  _ as Reservation_Change_WaitList,
  _ as Reservation_Change_WaitList_Desc1,
  _ as Reservation_Change_WaitList_Desc2,
  _ as Reservation_InPool,
  _ as Reservation_InPool_Message_Date,
  _ as Reservation_InPool_NoDate,
  _ as Reservation_InPool_NoName,
  _ as Reservation_InPool_WithName,
  _ as Reservation_In_Waitlist,
  _ as Reservation_In_Waitlist_Message,
  _ as Reservation_In_Waitlist_Message_NotJoin,
  _ as Reservation_In_Waitlist_NoDate,
  _ as Reservation_In_Waitlist_WithName,
  _ as Reservation_In_Waitlist_WithName_NoDate,
  _ as Reservation_JoinPool,
  _ as Reservation_JoinPool_ClickTerms,
  _ as Reservation_JoinPool_Terms,
  _ as Reservation_JoinWaitList,
  _ as Reservation_Join_Waitlist_Cancel_Reservation,
  _ as Reservation_NoListJoined_OneModel,
  _ as Reservation_OnRegularReserveForModel,
  _ as Reservation_Pool_Closed,
  _ as Reservation_Pool_InProgress_Joined,
  _ as Reservation_Pool_InProgress_NotJoined,
  _ as Reservation_Pool_NotSignedIn,
  _ as Reservation_Pool_NotSignedIn_Desc,
  _ as Reservation_PostShuffle_TAndC,
  _ as Reservation_Waitlist_NotSignedIn,
  _ as Reservation_Waitlist_NotSignedIn_Desc,
  _ as Sale_Section_Background_Bottom,
  _ as Sale_Section_Background_Top,
  _ as Sale_Section_Label_Color,
  _ as SteamReviewSection_AppID,
  _ as SteamReviewSection_AppID_ttip,
  _ as SteamURLAccepted,
  _ as SteamURLInvalid,
  _ as StoreItemFound,
  _ as StoreItemNotFound,
  _ as VerifiedProgram_DeckAlt,
  _ as VerifiedProgram_DeckDeviceAlt,
  _ as VerifiedProgram_DeckDisclaimer,
  _ as VerifiedProgram_DeckShopBannerAlt,
  _ as VerifiedProgram_DeckSubTitle,
  _ as VerifiedProgram_DeckTitle,
  _ as VerifiedProgram_DeckTitle_Verified,
  _ as VerifiedProgram_GreatOnDeck,
  _ as Wishlist_NotSignedIn,
  _ as default,
  _ as language,
  _ as machine_dummy,
};
