var _ = `tchinese`,
  _ = `移除`,
  _ = `新增`,
  _ = `驗證年齡`,
  _ = `移除所有項目`,
  _ = `編輯`,
  _ = `數量： %1$s`,
  _ = `您的購物車`,
  _ = `您的購物車（%1$s 個項目）`,
  _ = `您的購物車（%1$s 個項目）`,
  _ = `估計總額`,
  _ = `銷售稅將於結帳時計算`,
  _ = `購買`,
  _ = `此購買包含一份禮物`,
  _ = `首頁`,
  _ = `這是份禮物嗎？`,
  _ = `包含 %1$s 個項目`,
  _ = `包含 %1$s 個項目`,
  _ = `選擇收件人`,
  _ = `輸入電子郵件`,
  _ = `編輯禮物收件人…`,
  _ = `禮物收件人：`,
  _ = `禮物收件人的電子信箱：`,
  _ = `配送：`,
  _ = `重設`,
  _ = `盡快（透過電子郵件和 Steam 用戶端）`,
  _ = `排定時間：`,
  _ = `安排寄送日期`,
  _ = `來自：`,
  _ = `您的簽名：`,
  _ = `新增自訂簽名`,
  _ = `送禮訊息 (上限為 160 個字元，還剩 %1$s 個)：`,
  _ = `透過電子郵件傳送的禮物若未被加入 Steam 帳戶中，則將於 30 天後自動退款。`,
  _ = `透過電子郵件傳送的禮物僅可被與購買者同一地區的 Steam 帳戶所接受（%1$s）。`,
  _ = `贈送給您 Steam 親友群組中的孩童成員的禮物會自動加入他們的帳戶和允許遊玩的遊戲。`,
  _ = `選擇禮物收件人`,
  _ = `編輯傳送方式`,
  _ = `儲存`,
  _ = `依好友名稱搜尋…`,
  _ = `已經擁有此項目`,
  _ = `於願望清單內`,
  _ = `已經擁有 %1$s`,
  _ = `希望擁有 %1$s`,
  _ = `禮物選項`,
  _ = `載入符合資格的禮物收件人時發生問題，請稍後再試一次。`,
  _ = `繼續前往付款`,
  _ = `繼續前往禮物選項`,
  _ = `登入以購買`,
  _ = `拒絕請求`,
  _ = `自己帳戶使用`,
  _ = `這是份禮物`,
  _ = `這是贈送給 %1$s 的禮物`,
  _ = `自己帳戶使用：私人`,
  _ = `購物車（%1$s）`,
  _ = `已加入您的購物車！`,
  _ = `已更新您的購物車！`,
  _ = `繼續購物`,
  _ = `發售日期：%1$s`,
  _ = `檢視我的購物車（%1$s）`,
  _ = `請求購買`,
  _ = `您的 Steam 親友群組中的成人成員將收到您的購買請求通知`,
  _ = `無法請求購買，因為此購物車內的項目並非全部都可用於贈禮`,
  _ = `變更 / 移除優惠券`,
  _ = `新增優惠券`,
  _ = `您有適用於此項目的優惠券`,
  _ = `您有 %1$s 張適用於此項目的優惠券`,
  _ = `目前套用於此項目`,
  _ = `目前套用於另一項產品`,
  _ = `選擇一張套用於 %1$s 的優惠券`,
  _ = `預計配送日期：%1$s`,
  _ = `%1$s - %2$s 個工作天`,
  _ = `預計配送時間：6 - 10 個工作天`,
  _ = `預計配送時間：3 - 5 個工作天`,
  _ = `在您可以繼續付款之前：`,
  _ = `請注意：`,
  _ = `需要先採取行動才能繼續付款`,
  _ = `請注意：`,
  _ = `請注意：%1$s`,
  _ = `您的帳戶已經擁有以上其中一些項目，所以您無法再次購買它們。您可以購買這些項目作為禮物，或是調整您購物車的內容以繼續。`,
  _ = `您已經擁有此遊戲`,
  _ = `您已擁有此組合包中的所有項目`,
  _ = `禮物收件人已擁有此遊戲`,
  _ = `禮物收件人已擁有此組合包中的所有內容`,
  _ = `禮物收件人已擁有以上其中一些項目，所以您無法再次購買它們。您可以購買這些項目作為不同帳戶的禮物，或是調整您購物車的內容以繼續。`,
  _ = `您的購物車中似乎有重複的組合包。請移除購物車中重複的組合包再結帳。`,
  _ = `已在您的購物車內： `,
  _ = `您的購物車中包含一個無法在您的國家 / 地區購買的組合包。請從購物車中移除該組合包再結帳。`,
  _ = `您所在的國家 / 地區無法購買`,
  _ = `在允許購買成人色情內容前，Valve 需要驗證您已年滿 18 歲。`,
  _ = `在您驗證年齡前無法購買。`,
  _ = `您的購物車中包含也可透過您的有效訂閱之一取得的內容。`,
  _ = `該內容可透過此訂閱取得：`,
  _ = `這張優惠券不能與其它折扣一起使用。`,
  _ = `這張優惠劵無效或已經過期。`,
  _ = `這張優惠劵不能套用於此項目。`,
  _ = `您購物車內此商品的數量已超過可購上限。`,
  _ = `您的購物車包含一件無法購買的項目。`,
  _ = `無法購買`,
  _ = `The selected reipcient cannot receive this gift purchased from your region.`,
  _ = `購買此項目前須先擁有下列項目：`,
  _ = `贈送此項目前收禮者須先擁有下列項目：`,
  _ = `您的帳戶並未擁有購買您購物車項目所需的一些項目。您可將缺失的項目加入購物車內，或修改您的購物車內容以繼續結帳。`,
  _ = `收禮者並未擁有購買您購物車項目所需的一些項目。您可將缺失的項目加入購物車內，或修改您的購物車內容以繼續結帳。`,
  _ = `您已訂閱此項目。`,
  _ = `您的帳戶已訂閱上述部分項目。請在您的帳戶詳細資料中檢視訂閱設定。`,
  _ = `若買來自用，您將不會額外收到一份可用於贈禮的：`,
  _ = `若買來自用，您將會額外收到一份可用於贈禮的：`,
  _ = `以下一個或多個項目的價格自從您上次加入購物車後已經變更`,
  _ = `此項目的價格已變更`,
  _ = `由於此產品包含消耗性內容，因此無法退款。`,
  _ = `The gift recipient you have selected is in a higher price region.  The cost of this item has been updated to match their region to allow it to be gifted to them.`,
  _ = `此項目在 %1$s 組合包中可用較低的價格購買。`,
  _ = `禮物的收件人<b>不在</b>您的 Steam 好友名單中。`,
  _ = `請注意：%1$s 不在您的 Steam 好友名單中。`,
  _ = `如要傳送禮物給 Steam 好友，請<1>登入</1>帳戶以確認該收件人是否在您的好友名單中。`,
  _ = `您最近查看了 %1$s 的願望清單。要贈送這些項目給對方嗎？`,
  _ = `每 %2$s 秒收取 %1$s 訂閱費用。`,
  _ = `每 %2$s 分鐘收取 %1$s 訂閱費用。`,
  _ = `每 %2$s 小時收取 %1$s 訂閱費用。`,
  _ = `每 %2$s 天收取 %1$s 訂閱費用。`,
  _ = `每 %2$s 週收取 %1$s 訂閱費用。`,
  _ = `每 %2$s 個月收取 %1$s 訂閱費用。`,
  _ = `每 %2$s 年收取 %1$s 訂閱費用。`,
  _ = `每個授權每 %2$s 秒收取 %1$s 訂閱費用。`,
  _ = `每個授權每 %2$s 分鐘收取 %1$s 訂閱費用。`,
  _ = `每個授權每 %2$s 小時收取 %1$s 訂閱費用。`,
  _ = `每個授權每 %2$s 天收取 %1$s 訂閱費用。`,
  _ = `每個授權每 %2$s 週收取 %1$s 訂閱費用。`,
  _ = `每個授權每 %2$s 個月收取 %1$s 訂閱費用。`,
  _ = `每個授權每 %2$s 年收取 %1$s 訂閱費用。`,
  _ = `每 %2$s 秒收取 %1$s 訂閱費用或依據您的遊戲帳戶設定收款。`,
  _ = `每 %2$s 分鐘收取 %1$s 訂閱費用或依據您的遊戲帳戶設定收款。`,
  _ = `每 %2$s 小時收取 %1$s 訂閱費用或依據您的遊戲帳戶設定收款。`,
  _ = `每 %2$s 天收取 %1$s 訂閱費用或依據您的遊戲帳戶設定收款。`,
  _ = `每 %2$s 週收取 %1$s 訂閱費用或依據您的遊戲帳戶設定收款。`,
  _ = `每 %2$s 個月收取 %1$s 訂閱費用或依據您的遊戲帳戶設定收款。`,
  _ = `每 %2$s 年收取 %1$s 訂閱費用或依據您的遊戲帳戶設定收款。`,
  _ = `您結帳時會被收取 %1$s。<br/>您同意每 %3$s 秒自動支出 %2$s 的費用。`,
  _ = `您結帳時會被收取 %1$s。<br/>您同意每 %3$s 分鐘自動支出 %2$s 的費用。`,
  _ = `您結帳時會被收取 %1$s。<br/>您同意每 %3$s 小時自動支出 %2$s 的費用。`,
  _ = `您結帳時會被收取 %1$s。<br/>您同意每 %3$s 天自動支出 %2$s 的費用。`,
  _ = `您結帳時會被收取 %1$s。<br/>您同意每 %3$s 週自動支出 %2$s 的費用。`,
  _ = `您結帳時會被收取 %1$s。<br/>您同意每 %3$s 個月自動支出 %2$s 的費用。`,
  _ = `您結帳時會被收取 %1$s。<br/>您同意每 %3$s 年自動支出 %2$s 的費用。`,
  _ = `您結帳時會被收取 %1$s 元。<br/>您授權此遊戲可以每 %3$s 秒支出最多 %2$s 元的費用。`,
  _ = `您結帳時被收取 %1$s 元。<br/>您授權此遊戲可以每 %3$s 分鐘支出最多 %2$s 元的費用。`,
  _ = `您結帳時會被收取 %1$s 元。<br/>您授權此遊戲可以每 %3$s 小時支出最多 %2$s 元的費用。`,
  _ = `您結帳時會被收取 %1$s 元。<br/>您授權此遊戲可以每 %3$s 天支出最多 %2$s 元的費用。`,
  _ = `您結帳時會被收取 %1$s 元。<br/>您授權此遊戲可以每 %3$s 個星期支出最多 %2$s 元的費用。`,
  _ = `您結帳時會被收取 %1$s 元。<br/>您授權此遊戲可以每 %3$s 個月支出最多 %2$s 元的費用。`,
  _ = `您結帳時會被收取 %1$s 元。<br/>您授權此遊戲可以每 %3$s 年支出最多 %2$s 元的費用。`,
  _ = `結帳時支付 %1$s，之後每 %3$s 秒自動續約 %2$s。`,
  _ = `結帳時支付 %1$s，之後每 %3$s 分鐘自動續約 %2$s。`,
  _ = `結帳時支付 %1$s，之後每 %3$s 小時自動續約 %2$s。`,
  _ = `結帳時支付 %1$s，之後每 %3$s 天自動續約 %2$s。`,
  _ = `結帳時支付 %1$s，之後每 %3$s 週自動續約 %2$s。`,
  _ = `結帳時支付 %1$s，之後每 %3$s 個月自動續約 %2$s。`,
  _ = `結帳時支付 %1$s，之後每 %3$s 年自動續約 %2$s。`,
  _ = `首次購買享 %4$s% 折扣，結帳時支付 %1$s，之後每 %3$s 秒以 %2$s 的價格自動續約。`,
  _ = `首次購買享 %4$s% 折扣，結帳時支付 %1$s，之後每 %3$s 分鐘以 %2$s 的價格自動續約。`,
  _ = `首次購買享 %4$s% 折扣，結帳時支付 %1$s，之後每 %3$s 小時以 %2$s 的價格自動續約。`,
  _ = `首次購買享 %4$s% 折扣，結帳時支付 %1$s，之後每 %3$s 天以 %2$s 的價格自動續約。`,
  _ = `首次購買享 %4$s% 折扣，結帳時支付 %1$s，之後每 %3$s 週以 %2$s 的價格自動續約。`,
  _ = `首次購買享 %4$s% 折扣，結帳時支付 %1$s，之後每 %3$s 個月以 %2$s 的價格自動續約。`,
  _ = `首次購買享 %4$s% 折扣，結帳時支付 %1$s，之後每 %3$s 年以 %2$s 的價格自動續約。`,
  _ = `結帳時支付 %1$s，之後每 %3$s 秒依據您的遊戲帳戶設定自動續約 %2$s。`,
  _ = `結帳時支付 %1$s，之後每 %3$s 分鐘依據您的遊戲帳戶設定自動續約 %2$s。`,
  _ = `結帳時支付 %1$s，之後每 %3$s 小時依據您的遊戲帳戶設定自動續約 %2$s。`,
  _ = `結帳時支付 %1$s，之後每 %3$s 天依據您的遊戲帳戶設定自動續約 %2$s。`,
  _ = `結帳時支付 %1$s，之後每 %3$s 週依據您的遊戲帳戶設定自動續約 %2$s。`,
  _ = `結帳時支付 %1$s，之後每 %3$s 個月依據您的遊戲帳戶設定自動續約 %2$s。`,
  _ = `結帳時支付 %1$s，之後每 %3$s 年依據您的遊戲帳戶設定自動續約 %2$s。`,
  _ = `結帳時支付 %1$s，之後每個授權每 %3$s 秒以 %2$s 的價格自動續約。`,
  _ = `結帳時支付 %1$s，之後每個授權每 %3$s 分鐘以 %2$s 的價格自動續約。`,
  _ = `結帳時支付 %1$s，之後每個授權每 %3$s 小時以 %2$s 的價格自動續約。`,
  _ = `結帳時支付 %1$s，之後每個授權每 %3$s 天以 %2$s 的價格自動續約。`,
  _ = `結帳時支付 %1$s，之後每個授權每 %3$s 週以 %2$s 的價格自動續約。`,
  _ = `結帳時支付 %1$s，之後每個授權每 %3$s 個月以 %2$s 的價格自動續約。`,
  _ = `結帳時支付 %1$s，之後每個授權每 %3$s 年以 %2$s 的價格自動續約。`,
  _ = `首次購買享 %4$s% 折扣，結帳時支付 %1$s，之後每份授權每 %3$s 秒以 %2$s 的價格自動續約。`,
  _ = `首次購買享 %4$s% 折扣，結帳時支付 %1$s，之後每份授權每 %3$s 分鐘以 %2$s 的價格自動續約。`,
  _ = `首次購買享 %4$s% 折扣，結帳時支付 %1$s，之後每份授權每 %3$s 小時以 %2$s 的價格自動續約。`,
  _ = `首次購買享 %4$s% 折扣，結帳時支付 %1$s，之後每份授權每 %3$s 天以 %2$s 的價格自動續約。`,
  _ = `首次購買享 %4$s% 折扣，結帳時支付 %1$s，之後每份授權每 %3$s 週以 %2$s 的價格自動續約。`,
  _ = `首次購買享 %4$s% 折扣，結帳時支付 %1$s，之後每份授權每 %3$s 個月以 %2$s 的價格自動續約。`,
  _ = `首次購買享 %4$s% 折扣，結帳時支付 %1$s，之後每份授權每 %3$s 年以 %2$s 的價格自動續約。`,
  _ = `您的購物車是空的。`,
  _ = `這些項目中有部分已標記為私人。如選擇繼續，會維持私人狀態：`,
  _ = `將遊戲標記為私人會使其於各處隱藏，僅顯示於您的收藏庫內。您的擁有狀態、遊戲內狀態、遊戲時數和動態都不會顯示給其他人。`,
  _ = `因為您參與了 Steam 用戶端測試，您正看到的是新版的購物車。歡迎<1>留下意見回饋或回報程式錯誤</1>`,
  _ = `我們正在測試這個新版本的購物車。<1>請留下意見回饋或回報程式錯誤</1>`,
  _ = `您不能將禮物贈與時間設在這麼久遠的日期。`,
  _ = `請輸入一個有效的日期與時間。`,
  _ = `顯示此項目時發生問題`,
  _ = `您將能透過本次購買獲得 %1$s 張 %2$s 交換卡片。`,
  _ = `您將能透過本次購買獲得 %1$s 張 %2$s 交換卡片。`,
  _ = `在特賣期間於 Steam 商店消費將可獲得 %1$s 交換卡片。`,
  _ = `購買為禮物也一樣能獲得卡片。`,
  _ = `距離獲得下一張卡片的進度`,
  _ = `大約每 %1$s 獲得一張卡片`,
  _ = `備註：預購項目不符合獲得 %1$s 交易卡片獎勵的資格。下列項目將無法獲得交易卡片獎勵：`,
  _ = `%1$s 的購買請求`,
  _ = `購買項目的接受者：`,
  _ = `購買項目的受禮者：%1$s`,
  _ = `多加一份此項目到您的購物車中`,
  _ = `英國 PSTI 法規遵循聲明`,
  _ = `更新您的購物車時發生問題。`,
  _ = `錯誤代碼：%1$s`,
  _ = `國家 / 地區`,
  _ = `已保存的購物車`,
  _ = `此為已保存的購物車。您上次嘗試結帳時發生錯誤，因此我們幫您把整台購物車（包含折扣）保存 %1$s 小時。您可以在保存期間內再度嘗試結帳。`,
  _ = `由此複製禮物選項：`,
  _ = `<1>登入</1>以選擇 Steam 好友`,
  _ = {
    language: _,
    Cart_Remove: _,
    Cart_Add: _,
    Cart_Verify: _,
    Cart_RemoveAll: _,
    Cart_Edit: _,
    Cart_Quantity: _,
    Cart_YourShoppingCart: _,
    Cart_YourShoppingCartLineItems: _,
    Cart_YourShoppingCartLineItems_Plural: _,
    Cart_EstimatedTotal: _,
    Cart_Note_SalesTax: _,
    Cart_PurchaseBtn: _,
    Cart_ContainsGiftCheckbox: _,
    Cart_Bradcrumb_Home: _,
    Cart_LineItemGift_Checkbox: _,
    Cart_IncludesItems: _,
    Cart_IncludesItems_Plural: _,
    Cart_SelectRecipient: _,
    Cart_EnterRecipientEmail: _,
    Cart_ChangeGiftRecipient: _,
    Cart_GiftRecipient_Label: _,
    Cart_GiftRecipientEmail_Label: _,
    Cart_GiftDelivery_Label: _,
    Cart_GiftDelivery_Reset: _,
    Cart_GiftDelivery_Now: _,
    Cart_GiftDelivery_Scheduled: _,
    Cart_GiftDelivery_ScheduleDelivery: _,
    Cart_GiftDelivery_From: _,
    Cart_GiftDelivery_Signature: _,
    Cart_GiftDelivery_AddSignature: _,
    Cart_GiftDelivery_Body: _,
    Cart_GiftDeliveryEmail_Warning1: _,
    Cart_GiftDeliveryEmail_Warning2: _,
    Cart_FamilyGift_Notice: _,
    Cart_GiftRecipientModal_Title: _,
    Cart_EditGiftDelivery: _,
    Cart_GiftRecipientModal_Save: _,
    Cart_GiftRecipientModal_Placeholder: _,
    Cart_GiftRecipientModal_OwnsGameLabel: _,
    Cart_GiftRecipientModal_OnWishlist: _,
    Cart_GiftRecipientModal_PartialOwnsLabel: _,
    Cart_GiftRecipientModal_PartialWishlistLabel: _,
    Cart_GiftOptions: _,
    Cart_GiftRecipientModal_IssueLoading: _,
    Cart_ContinueButton_Payment: _,
    Cart_ContinueButton_Gifts: _,
    Cart_ContinueButton_Login: _,
    Cart_DeclinePurchaseRequest: _,
    Cart_LineItemOptions_Myself: _,
    Cart_LineItemOptions_Gift: _,
    Cart_LineItemOptions_GiftForPersona: _,
    Cart_LineItemOptions_Privately: _,
    Cart_CountWidget: _,
    Cart_AddedToYourCart: _,
    Cart_UpdatedYourCart: _,
    Cart_ContinueShopping: _,
    Cart_ComingSoon: _,
    Cart_ViewMyCart: _,
    Cart_RequestPurchase: _,
    Cart_RequestPurchaseExplanation: _,
    Cart_RequestPurchaseNonGiftableItems: _,
    Cart_CouponModify_Change: _,
    Cart_CouponModify_Add: _,
    Cart_CouponAvailability: _,
    Cart_CouponAvailability_Plural: _,
    Cart_Coupons_Applied: _,
    Cart_Coupons_InUse: _,
    Cart_SelectCouponToApply: _,
    Cart_ShippingEstimate_DeliveryDate: _,
    Cart_ShippingEstimate_Range: _,
    Cart_ShippingEstimate_Delayed: _,
    Cart_ShippingEstimate_Standard: _,
    Cart_FooterNoticeHeader_MustFix: _,
    Cart_FooterNoticeHeader_Warning: _,
    Cart_CartLevelErrorNotice: _,
    Cart_CartLevelErrorMultiple: _,
    Cart_CartLevelErrorFormat: _,
    Cart_Error_AlreadyOwned_FootNote: _,
    Cart_Error_AlreadyOwned_LineItem_Game: _,
    Cart_Error_AlreadyOwned_LineItem: _,
    Cart_Error_AlreadyOwned_GiftLineItem_Game: _,
    Cart_Error_AlreadyOwned_GiftLineItem: _,
    Cart_Error_AlreadyOwned_GiftFootNote: _,
    Cart_Error_DuplicateApps_FootNote: _,
    Cart_Error_DuplicateApps_LineItem: _,
    Cart_Error_UnavailableCountry_FootNote: _,
    Cart_Error_UnavailableCountry_LineItem: _,
    Cart_Error_AdultContentRestricted_FootNote: _,
    Cart_Error_AdultContentRestricted_LineItem: _,
    Cart_Error_MasterSubscription_FootNote: _,
    Cart_Error_MasterSubscription_LineItem: _,
    Cart_Error_CouponIsExclusivePromo: _,
    Cart_Error_CouponIsInvalid: _,
    Cart_Error_CouponIsInvalidForItem: _,
    Cart_Error_TooManyInCart: _,
    Cart_Error_CommercialLicenseRestricted_FootNote: _,
    Cart_Error_CommercialLicenseRestricted_LineItem: _,
    Cart_Error_GiftRecipientInvalid: _,
    Cart_Error_MissingMustOwnApps_LineItem: _,
    Cart_Error_MissingMustOwnApps_GiftLineItem: _,
    Cart_Error_MissingMustOwnApps_FootNote: _,
    Cart_Error_MissingMustOwnApps_FootNoteGift: _,
    Cart_Error_ExistingBillingAgreement: _,
    Cart_Error_ExistingBillingAgreement_FootNote: _,
    Cart_Warning_AlreadyOwned_LineItem: _,
    Cart_Warning_ExtraCopies_LineItem: _,
    Cart_Warning_PriceChange_FootNote: _,
    Cart_Warning_PriceChange_LineItem: _,
    Cart_Warning_NoRefund_LineItem: _,
    Cart_Warning_RecipientHigherPrice: _,
    Cart_Warning_AvailableAtALowerPrice: _,
    Cart_Warning_GiftToNonFriend: _,
    Cart_Warning_GiftToNonFriend_Named: _,
    Cart_Warning_GiftToAccount_LoggedOut_Actionable: _,
    Cart_GifteeHint_Wishlist: _,
    PackageIncludesSubscriptionBySecond: _,
    PackageIncludesSubscriptionByMinute: _,
    PackageIncludesSubscriptionByHour: _,
    PackageIncludesSubscriptionByDay: _,
    PackageIncludesSubscriptionByWeek: _,
    PackageIncludesSubscriptionByMonth: _,
    PackageIncludesSubscriptionByYear: _,
    MultiLicenseIncludesSubscriptionBySecond: _,
    MultiLicenseIncludesSubscriptionByMinute: _,
    MultiLicenseIncludesSubscriptionByHour: _,
    MultiLicenseIncludesSubscriptionByDay: _,
    MultiLicenseIncludesSubscriptionByWeek: _,
    MultiLicenseIncludesSubscriptionByMonth: _,
    MultiLicenseeIncludesSubscriptionByYear: _,
    GameBillingPackageIncludesSubscriptionBySecond: _,
    GameBillingPackageIncludesSubscriptionByMinute: _,
    GameBillingPackageIncludesSubscriptionByHour: _,
    GameBillingPackageIncludesSubscriptionByDay: _,
    GameBillingPackageIncludesSubscriptionByWeek: _,
    GameBillingPackageIncludesSubscriptionByMonth: _,
    GameBillingPackageIncludesSubscriptionByYear: _,
    MicroTxnSubscriptionCostBySecond: _,
    MicroTxnSubscriptionCostByMinute: _,
    MicroTxnSubscriptionCostByHour: _,
    MicroTxnSubscriptionCostByDay: _,
    MicroTxnSubscriptionCostByWeek: _,
    MicroTxnSubscriptionCostByMonth: _,
    MicroTxnSubscriptionCostByYear: _,
    GameBillingAuthorizeSubscriptionBySecond: _,
    GameBillingAuthorizeSubscriptionByMinute: _,
    GameBillingAuthorizeSubscriptionByHour: _,
    GameBillingAuthorizeSubscriptionByDay: _,
    GameBillingAuthorizeSubscriptionByWeek: _,
    GameBillingAuthorizeSubscriptionByMonth: _,
    GameBillingAuthorizeSubscriptionByYear: _,
    PackageCostIncludesSubscriptionBySecond: _,
    PackageCostIncludesSubscriptionByMinute: _,
    PackageCostIncludesSubscriptionByHour: _,
    PackageCostIncludesSubscriptionByDay: _,
    PackageCostIncludesSubscriptionByWeek: _,
    PackageCostIncludesSubscriptionByMonth: _,
    PackageCostIncludesSubscriptionByYear: _,
    PackageWithDiscountCostIncludesSubscriptionBySecond: _,
    PackageWithDiscountCostIncludesSubscriptionByMinute: _,
    PackageWithDiscountCostIncludesSubscriptionByHour: _,
    PackageWithDiscountCostIncludesSubscriptionByDay: _,
    PackageWithDiscountCostIncludesSubscriptionByWeek: _,
    PackageWithDiscountCostIncludesSubscriptionByMonth: _,
    PackageWithDiscountCostIncludesSubscriptionByYear: _,
    GameBillingPackageCostIncludesSubscriptionBySecond: _,
    GameBillingPackageCostIncludesSubscriptionByMinute: _,
    GameBillingPackageCostIncludesSubscriptionByHour: _,
    GameBillingPackageCostIncludesSubscriptionByDay: _,
    GameBillingPackageCostIncludesSubscriptionByWeek: _,
    GameBillingPackageCostIncludesSubscriptionByMonth: _,
    GameBillingPackageCostIncludesSubscriptionByYear: _,
    MultiLicenseCostIncludesSubscriptionBySecond: _,
    MultiLicenseCostIncludesSubscriptionByMinute: _,
    MultiLicenseCostIncludesSubscriptionByHour: _,
    MultiLicenseCostIncludesSubscriptionByDay: _,
    MultiLicenseCostIncludesSubscriptionByWeek: _,
    MultiLicenseCostIncludesSubscriptionByMonth: _,
    MultiLicenseCostIncludesSubscriptionByYear: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionBySecond: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMinute: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByHour: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByDay: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByWeek: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMonth: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByYear: _,
    Cart_Empty: _,
    Cart_Notice_SomeAppsPrivate: _,
    Cart_LineItemOptions_PrivateTooltip: _,
    Cart_BetaNotice: _,
    Cart_GenericBetaNotice: _,
    Cart_GiftScheduleError_TooFar: _,
    Cart_GiftScheduleError_InvalidDate: _,
    Cart_LineItem_ErrorBoundary: _,
    Cart_SaleCardDrops_EarnedMessage: _,
    Cart_SaleCardDrops_EarnedMessage_Plural: _,
    Cart_SaleCardDrops_Explanation: _,
    Cart_SaleCardDrops_Explanation_Gifts: _,
    Cart_SaleCardDrops_ProgressLabel: _,
    Cart_SaleCardDrops_CardCost: _,
    Cart_SaleCardDrops_PrepurchaseIneligible: _,
    Cart_PurchaseRequestTitle: _,
    Cart_PurchaseFor_Label: _,
    Cart_GiftForNotice: _,
    Cart_LineItem_Add_Tooltip: _,
    Cart_LineItem_Hardware_Compliance_Label: _,
    Cart_ErrorUpdating: _,
    Cart_ErrorCode: _,
    Cart_UserCountrySelector: _,
    Cart_Replay_SavedCart: _,
    Cart_Replay_Instructions: _,
    Cart_Gifting_CopyGiftOptionsFrom: _,
    Cart_Gifting_SignInToSelectFriends: _,
  };
export {
  _ as Cart_Add,
  _ as Cart_AddedToYourCart,
  _ as Cart_BetaNotice,
  _ as Cart_Bradcrumb_Home,
  _ as Cart_CartLevelErrorFormat,
  _ as Cart_CartLevelErrorMultiple,
  _ as Cart_CartLevelErrorNotice,
  _ as Cart_ChangeGiftRecipient,
  _ as Cart_ComingSoon,
  _ as Cart_ContainsGiftCheckbox,
  _ as Cart_ContinueButton_Gifts,
  _ as Cart_ContinueButton_Login,
  _ as Cart_ContinueButton_Payment,
  _ as Cart_ContinueShopping,
  _ as Cart_CountWidget,
  _ as Cart_CouponAvailability,
  _ as Cart_CouponAvailability_Plural,
  _ as Cart_CouponModify_Add,
  _ as Cart_CouponModify_Change,
  _ as Cart_Coupons_Applied,
  _ as Cart_Coupons_InUse,
  _ as Cart_DeclinePurchaseRequest,
  _ as Cart_Edit,
  _ as Cart_EditGiftDelivery,
  _ as Cart_Empty,
  _ as Cart_EnterRecipientEmail,
  _ as Cart_ErrorCode,
  _ as Cart_ErrorUpdating,
  _ as Cart_Error_AdultContentRestricted_FootNote,
  _ as Cart_Error_AdultContentRestricted_LineItem,
  _ as Cart_Error_AlreadyOwned_FootNote,
  _ as Cart_Error_AlreadyOwned_GiftFootNote,
  _ as Cart_Error_AlreadyOwned_GiftLineItem,
  _ as Cart_Error_AlreadyOwned_GiftLineItem_Game,
  _ as Cart_Error_AlreadyOwned_LineItem,
  _ as Cart_Error_AlreadyOwned_LineItem_Game,
  _ as Cart_Error_CommercialLicenseRestricted_FootNote,
  _ as Cart_Error_CommercialLicenseRestricted_LineItem,
  _ as Cart_Error_CouponIsExclusivePromo,
  _ as Cart_Error_CouponIsInvalid,
  _ as Cart_Error_CouponIsInvalidForItem,
  _ as Cart_Error_DuplicateApps_FootNote,
  _ as Cart_Error_DuplicateApps_LineItem,
  _ as Cart_Error_ExistingBillingAgreement,
  _ as Cart_Error_ExistingBillingAgreement_FootNote,
  _ as Cart_Error_GiftRecipientInvalid,
  _ as Cart_Error_MasterSubscription_FootNote,
  _ as Cart_Error_MasterSubscription_LineItem,
  _ as Cart_Error_MissingMustOwnApps_FootNote,
  _ as Cart_Error_MissingMustOwnApps_FootNoteGift,
  _ as Cart_Error_MissingMustOwnApps_GiftLineItem,
  _ as Cart_Error_MissingMustOwnApps_LineItem,
  _ as Cart_Error_TooManyInCart,
  _ as Cart_Error_UnavailableCountry_FootNote,
  _ as Cart_Error_UnavailableCountry_LineItem,
  _ as Cart_EstimatedTotal,
  _ as Cart_FamilyGift_Notice,
  _ as Cart_FooterNoticeHeader_MustFix,
  _ as Cart_FooterNoticeHeader_Warning,
  _ as Cart_GenericBetaNotice,
  _ as Cart_GiftDeliveryEmail_Warning1,
  _ as Cart_GiftDeliveryEmail_Warning2,
  _ as Cart_GiftDelivery_AddSignature,
  _ as Cart_GiftDelivery_Body,
  _ as Cart_GiftDelivery_From,
  _ as Cart_GiftDelivery_Label,
  _ as Cart_GiftDelivery_Now,
  _ as Cart_GiftDelivery_Reset,
  _ as Cart_GiftDelivery_ScheduleDelivery,
  _ as Cart_GiftDelivery_Scheduled,
  _ as Cart_GiftDelivery_Signature,
  _ as Cart_GiftForNotice,
  _ as Cart_GiftOptions,
  _ as Cart_GiftRecipientEmail_Label,
  _ as Cart_GiftRecipientModal_IssueLoading,
  _ as Cart_GiftRecipientModal_OnWishlist,
  _ as Cart_GiftRecipientModal_OwnsGameLabel,
  _ as Cart_GiftRecipientModal_PartialOwnsLabel,
  _ as Cart_GiftRecipientModal_PartialWishlistLabel,
  _ as Cart_GiftRecipientModal_Placeholder,
  _ as Cart_GiftRecipientModal_Save,
  _ as Cart_GiftRecipientModal_Title,
  _ as Cart_GiftRecipient_Label,
  _ as Cart_GiftScheduleError_InvalidDate,
  _ as Cart_GiftScheduleError_TooFar,
  _ as Cart_GifteeHint_Wishlist,
  _ as Cart_Gifting_CopyGiftOptionsFrom,
  _ as Cart_Gifting_SignInToSelectFriends,
  _ as Cart_IncludesItems,
  _ as Cart_IncludesItems_Plural,
  _ as Cart_LineItemGift_Checkbox,
  _ as Cart_LineItemOptions_Gift,
  _ as Cart_LineItemOptions_GiftForPersona,
  _ as Cart_LineItemOptions_Myself,
  _ as Cart_LineItemOptions_PrivateTooltip,
  _ as Cart_LineItemOptions_Privately,
  _ as Cart_LineItem_Add_Tooltip,
  _ as Cart_LineItem_ErrorBoundary,
  _ as Cart_LineItem_Hardware_Compliance_Label,
  _ as Cart_Note_SalesTax,
  _ as Cart_Notice_SomeAppsPrivate,
  _ as Cart_PurchaseBtn,
  _ as Cart_PurchaseFor_Label,
  _ as Cart_PurchaseRequestTitle,
  _ as Cart_Quantity,
  _ as Cart_Remove,
  _ as Cart_RemoveAll,
  _ as Cart_Replay_Instructions,
  _ as Cart_Replay_SavedCart,
  _ as Cart_RequestPurchase,
  _ as Cart_RequestPurchaseExplanation,
  _ as Cart_RequestPurchaseNonGiftableItems,
  _ as Cart_SaleCardDrops_CardCost,
  _ as Cart_SaleCardDrops_EarnedMessage,
  _ as Cart_SaleCardDrops_EarnedMessage_Plural,
  _ as Cart_SaleCardDrops_Explanation,
  _ as Cart_SaleCardDrops_Explanation_Gifts,
  _ as Cart_SaleCardDrops_PrepurchaseIneligible,
  _ as Cart_SaleCardDrops_ProgressLabel,
  _ as Cart_SelectCouponToApply,
  _ as Cart_SelectRecipient,
  _ as Cart_ShippingEstimate_Delayed,
  _ as Cart_ShippingEstimate_DeliveryDate,
  _ as Cart_ShippingEstimate_Range,
  _ as Cart_ShippingEstimate_Standard,
  _ as Cart_UpdatedYourCart,
  _ as Cart_UserCountrySelector,
  _ as Cart_Verify,
  _ as Cart_ViewMyCart,
  _ as Cart_Warning_AlreadyOwned_LineItem,
  _ as Cart_Warning_AvailableAtALowerPrice,
  _ as Cart_Warning_ExtraCopies_LineItem,
  _ as Cart_Warning_GiftToAccount_LoggedOut_Actionable,
  _ as Cart_Warning_GiftToNonFriend,
  _ as Cart_Warning_GiftToNonFriend_Named,
  _ as Cart_Warning_NoRefund_LineItem,
  _ as Cart_Warning_PriceChange_FootNote,
  _ as Cart_Warning_PriceChange_LineItem,
  _ as Cart_Warning_RecipientHigherPrice,
  _ as Cart_YourShoppingCart,
  _ as Cart_YourShoppingCartLineItems,
  _ as Cart_YourShoppingCartLineItems_Plural,
  _ as GameBillingAuthorizeSubscriptionByDay,
  _ as GameBillingAuthorizeSubscriptionByHour,
  _ as GameBillingAuthorizeSubscriptionByMinute,
  _ as GameBillingAuthorizeSubscriptionByMonth,
  _ as GameBillingAuthorizeSubscriptionBySecond,
  _ as GameBillingAuthorizeSubscriptionByWeek,
  _ as GameBillingAuthorizeSubscriptionByYear,
  _ as GameBillingPackageCostIncludesSubscriptionByDay,
  _ as GameBillingPackageCostIncludesSubscriptionByHour,
  _ as GameBillingPackageCostIncludesSubscriptionByMinute,
  _ as GameBillingPackageCostIncludesSubscriptionByMonth,
  _ as GameBillingPackageCostIncludesSubscriptionBySecond,
  _ as GameBillingPackageCostIncludesSubscriptionByWeek,
  _ as GameBillingPackageCostIncludesSubscriptionByYear,
  _ as GameBillingPackageIncludesSubscriptionByDay,
  _ as GameBillingPackageIncludesSubscriptionByHour,
  _ as GameBillingPackageIncludesSubscriptionByMinute,
  _ as GameBillingPackageIncludesSubscriptionByMonth,
  _ as GameBillingPackageIncludesSubscriptionBySecond,
  _ as GameBillingPackageIncludesSubscriptionByWeek,
  _ as GameBillingPackageIncludesSubscriptionByYear,
  _ as MicroTxnSubscriptionCostByDay,
  _ as MicroTxnSubscriptionCostByHour,
  _ as MicroTxnSubscriptionCostByMinute,
  _ as MicroTxnSubscriptionCostByMonth,
  _ as MicroTxnSubscriptionCostBySecond,
  _ as MicroTxnSubscriptionCostByWeek,
  _ as MicroTxnSubscriptionCostByYear,
  _ as MultiLicenseCostIncludesSubscriptionByDay,
  _ as MultiLicenseCostIncludesSubscriptionByHour,
  _ as MultiLicenseCostIncludesSubscriptionByMinute,
  _ as MultiLicenseCostIncludesSubscriptionByMonth,
  _ as MultiLicenseCostIncludesSubscriptionBySecond,
  _ as MultiLicenseCostIncludesSubscriptionByWeek,
  _ as MultiLicenseCostIncludesSubscriptionByYear,
  _ as MultiLicenseIncludesSubscriptionByDay,
  _ as MultiLicenseIncludesSubscriptionByHour,
  _ as MultiLicenseIncludesSubscriptionByMinute,
  _ as MultiLicenseIncludesSubscriptionByMonth,
  _ as MultiLicenseIncludesSubscriptionBySecond,
  _ as MultiLicenseIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByDay,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByHour,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMinute,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMonth,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionBySecond,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByYear,
  _ as MultiLicenseeIncludesSubscriptionByYear,
  _ as PackageCostIncludesSubscriptionByDay,
  _ as PackageCostIncludesSubscriptionByHour,
  _ as PackageCostIncludesSubscriptionByMinute,
  _ as PackageCostIncludesSubscriptionByMonth,
  _ as PackageCostIncludesSubscriptionBySecond,
  _ as PackageCostIncludesSubscriptionByWeek,
  _ as PackageCostIncludesSubscriptionByYear,
  _ as PackageIncludesSubscriptionByDay,
  _ as PackageIncludesSubscriptionByHour,
  _ as PackageIncludesSubscriptionByMinute,
  _ as PackageIncludesSubscriptionByMonth,
  _ as PackageIncludesSubscriptionBySecond,
  _ as PackageIncludesSubscriptionByWeek,
  _ as PackageIncludesSubscriptionByYear,
  _ as PackageWithDiscountCostIncludesSubscriptionByDay,
  _ as PackageWithDiscountCostIncludesSubscriptionByHour,
  _ as PackageWithDiscountCostIncludesSubscriptionByMinute,
  _ as PackageWithDiscountCostIncludesSubscriptionByMonth,
  _ as PackageWithDiscountCostIncludesSubscriptionBySecond,
  _ as PackageWithDiscountCostIncludesSubscriptionByWeek,
  _ as PackageWithDiscountCostIncludesSubscriptionByYear,
  _ as default,
  _ as language,
};
