var _ = `vietnamese`,
  _ = `Gỡ bỏ`,
  _ = `Thêm`,
  _ = `Xác minh độ tuổi`,
  _ = `Gỡ bỏ tất cả sản phẩm`,
  _ = `Sửa`,
  _ = `Số lượng: %1$s`,
  _ = `Giỏ hàng của bạn`,
  _ = `Giỏ hàng của bạn (%1$s sản phẩm)`,
  _ = `Giỏ hàng của bạn (%1$s sản phẩm)`,
  _ = `Tổng ước tính`,
  _ = `Thuế tiêu thụ sẽ được tính trong quá trình thanh toán nếu có`,
  _ = `Mua hàng`,
  _ = `Đơn hàng này có chứa một món quà`,
  _ = `Trang chủ`,
  _ = `Đây là một món quà?`,
  _ = `Bao gồm %1$s sản phẩm`,
  _ = `Bao gồm %1$s sản phẩm`,
  _ = `Chọn người nhận`,
  _ = `Nhập email`,
  _ = `Sửa người nhận quà...`,
  _ = `Người nhận quà:`,
  _ = `Email người nhận quà:`,
  _ = `Giao hàng:`,
  _ = `Đặt lại`,
  _ = `Sớm nhất có thể (qua email và qua phần mềm Steam)`,
  _ = `Có lịch:`,
  _ = `Lên lịch chuyển quà`,
  _ = `Từ:`,
  _ = `Chữ ký của bạn:`,
  _ = `Thêm chữ ký tùy chỉnh`,
  _ = `Tin nhắn quà tặng (tối đa 160 ký tự, còn lại %1$s ký tự):`,
  _ = `Quà tặng được gửi qua email sẽ tự động hoàn tiền sau 30 ngày nếu không được thêm vào tài khoản Steam.`,
  _ = `Chỉ các tài khoản Steam trong cùng khu vực với người mua mới có thể chấp nhận quà tặng gửi qua email (%1$s).`,
  _ = `Quà gửi tới trẻ nhỏ trong nhóm gia đình Steam sẽ tự động thêm vào tài khoản và danh sách sản phẩm được phép chơi của trẻ.`,
  _ = `Chọn người nhận quà`,
  _ = `Chỉnh sửa phương thức giao hàng`,
  _ = `Lưu`,
  _ = `Tìm theo tên bạn bè...`,
  _ = `Đã sở hữu món này`,
  _ = `Trong danh sách ước`,
  _ = `Đã sở hữu %1$s`,
  _ = `%1$s trong danh sách ước`,
  _ = `Tùy chọn quà tặng`,
  _ = `Xảy ra vấn đề khi tải người nhận quà hợp lệ. Xin vui lòng thử lại sau.`,
  _ = `Tiếp tục tới bước thanh toán`,
  _ = `Tiếp tục tới tùy chọn quà tặng`,
  _ = `Đăng nhập để mua`,
  _ = `Từ chối yêu cầu`,
  _ = `Cho tài khoản của tôi`,
  _ = `Đây là một món quà`,
  _ = `Đây là quà tặng cho %1$s`,
  _ = `Cho tài khoản của tôi: riêng tư`,
  _ = `Giỏ hàng (%1$s)`,
  _ = `Đã thêm vào giỏ hàng!`,
  _ = `Đã cập nhật giỏ hàng của bạn!`,
  _ = `Tiếp tục mua sắm`,
  _ = `Ra mắt %1$s`,
  _ = `Xem giỏ hàng (%1$s)`,
  _ = `Yêu cầu mua hàng`,
  _ = `Người lớn trong nhóm gia đình Steam sẽ được báo về yêu cầu mua hàng của bạn`,
  _ = `Không thể yêu cầu mua vì không phải tất cả sản phẩm trong giỏ hàng đều tặng được`,
  _ = `Thay / Bỏ phiếu giảm giá`,
  _ = `Thêm phiếu giảm giá`,
  _ = `Bạn có một phiếu giảm giá cho vật phẩm này`,
  _ = `Bạn có %1$s phiếu giảm giá cho vật phẩm này`,
  _ = `Đã được dùng`,
  _ = `Đã được dùng cho sản phẩm khác`,
  _ = `Chọn một phiếu giảm giá để áp dụng cho %1$s`,
  _ = `Giao hàng dự kiến: %1$s`,
  _ = `%1$s-%2$s ngày làm việc`,
  _ = `Ngày giao dự kiến: 6-10 ngày làm việc`,
  _ = `Ngày giao dự kiến: 3-5 ngày làm việc`,
  _ = `Trước khi có thể tiếp tục thanh toán:`,
  _ = `Lưu ý:`,
  _ = `Bạn cần thực hiện một số thao tác trước khi có thể tiếp tục thanh toán`,
  _ = `Lưu ý:`,
  _ = `Ghi chú: %1$s`,
  _ = `Tài khoản của bạn đã sở hữu một trong số các sản phẩm trên, vì vậy bạn không thể thêm lần nữa. Bạn có thể mua chúng làm quà hoặc thay đổi sản phẩm trong giỏ hàng để tiếp tục.`,
  _ = `Bạn đã sở hữu trò chơi này`,
  _ = `Bạn đã sở hữu tất cả nội dung trong gói này`,
  _ = `Người được tặng quà đã sở hữu trò chơi này`,
  _ = `Người được tặng quà đã sở hữu mọi thứ trong bộ này`,
  _ = `Người được tặng quà đã sở hữu một vài trong số các sản phẩm trên, vì vậy bạn không thể mua nữa. Bạn có thể mua làm quà cho tài khoản khác hoặc thay đổi sản phẩm trong giỏ hàng để tiếp tục.`,
  _ = `Có vẻ bạn đang có các gói trùng nhau trong giỏ hàng. Bạn cần bỏ những gói thừa ra khỏi giỏ trước khi tiến hành thanh toán.`,
  _ = `Đã có trong giỏ hàng: `,
  _ = `Giỏ hàng chứa một gói không được bán tại quốc gia của bạn. Bạn cần bỏ gói đó ra khỏi giỏ trước khi tiến hành thanh toán.`,
  _ = `Không được bán tại quốc gia của bạn`,
  _ = `Valve bắt buộc xác minh bạn từ 18 tuổi trở lên để mua nội dung khiêu dâm mang yếu tố trưởng thành.`,
  _ = `Không thể mua cho đến khi xác minh độ tuổi.`,
  _ = `Giỏ hàng chứa nội dung cũng có thể truy cập qua một trong các gói đăng ký hiện tại.`,
  _ = `Đã có thông qua gói đăng ký:`,
  _ = `Phiếu giảm giá này không thể được dùng cùng lúc với giảm giá khác.`,
  _ = `Phiếu giảm giá này không hợp lệ hoặc hết hạn.`,
  _ = `Không thể dùng phiếu giảm giá cho vật phẩm này.`,
  _ = `Bạn đã vượt quá số lượng tối đa cho phép của sản phẩm này trong giỏ hàng.`,
  _ = `Giỏ hàng của bạn chứa một sản phẩm không thể mua.`,
  _ = `Không thể mua`,
  _ = `Người nhận bạn chọn không thể nhận món quà được mua từ khu vực của bạn.`,
  _ = `Mua sản phẩm này cần bạn có các sản phẩm sau:`,
  _ = `Sản phẩm này cần người nhận quà có các sản phẩm sau:`,
  _ = `Tài khoản của bạn chưa sở hữu một số sản phẩm cần thiết để mua những món trong giỏ hàng. Bạn có thể thêm sản phẩm bị thiếu hoặc thay đổi sản phẩm trong giỏ hàng để tiếp tục.`,
  _ = `Người nhận quà chưa sở hữu một số sản phẩm cần thiết để mua những món trong giỏ hàng. Bạn có thể thêm sản phẩm bị thiếu hoặc thay đổi sản phẩm trong giỏ hàng để tiếp tục.`,
  _ = `Bạn đã có gói đăng ký cho sản phẩm này.`,
  _ = `Tài khoản của bạn đã có gói đăng ký cho một số sản phẩm nêu trên.  Xem thiết lập gói đăng ký trong trang chi tiết tài khoản.`,
  _ = `Nếu mua cho bản thân, bạn sẽ không nhận thêm một bản sao của:`,
  _ = `Nếu mua cho bản thân, bạn sẽ nhận thêm một bản sao (có thể gửi tặng) của:`,
  _ = `Một hoặc nhiều sản phẩm dưới đây đã thay đổi giá kể từ khi bạn thêm vào giỏ hàng.`,
  _ = `Giá sản phẩm này đã thay đổi`,
  _ = `Sản phẩm này chứa nội dung có thể tiêu thụ. Điều này khiến nó không đủ điều kiện hoàn tiền.`,
  _ = `Người nhận quà bạn chọn thuộc khu vực có giá bán cao hơn. Giá của sản phẩm này đã được cập nhật cho phù hợp với khu vực của họ để bạn có thể tặng quà cho họ.`,
  _ = `Sản phẩm này có thể mua với mức giá thấp hơn do thuộc %1$s.`,
  _ = `Người nhận quà KHÔNG có trong danh sách bạn bè trên Steam.`,
  _ = `LƯU Ý: %1$s KHÔNG có trong danh sách bạn bè Steam của bạn.`,
  _ = `Nếu bạn gửi quà cho bạn bè trên Steam, vui lòng <1>đăng nhập</1> để xác nhận người nhận có trong danh sách bạn bè.`,
  _ = `Bạn gần đây xem qua danh sách ước của %1$s. Tặng các món này cho họ?`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s giây.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s phút.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s giờ.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s ngày.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s tuần.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s tháng`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s năm.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s giây cho một giấy phép.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s phút cho một giấy phép.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s giờ cho một giấy phép.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s ngày cho một giấy phép.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s tuần cho mỗi giấy phép.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s tháng cho một giấy phép.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s năm cho một giấy phép.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s giây hoặc xác định bởi tài khoản trò chơi của bạn.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s phút hoặc xác định bởi tài khoản trò chơi của bạn.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s giờ hoặc xác định bởi tài khoản trò chơi của bạn.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s ngày hoặc xác định bởi tài khoản trò chơi của bạn.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s tuần hoặc xác định bởi tài khoản trò chơi của bạn.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s tháng hoặc xác định bởi tài khoản trò chơi của bạn.`,
  _ = `Phí đăng ký được tính là %1$s mỗi %2$s năm hoặc xác định bởi tài khoản trò chơi của bạn.`,
  _ = `Bạn sẽ trả %1$s lúc thanh toán.<br/>Bạn đồng ý tự động trả %2$s mỗi %3$s giây.`,
  _ = `Bạn sẽ trả %1$s lúc thanh toán.<br/>Bạn đồng ý tự động trả %2$s mỗi %3$s phút.`,
  _ = `Bạn sẽ trả %1$s lúc thanh toán.<br/>Bạn đồng ý tự động trả %2$s mỗi %3$s giờ.`,
  _ = `Bạn sẽ trả %1$s lúc thanh toán.<br/>Bạn đồng ý tự động trả %2$s mỗi %3$s ngày.`,
  _ = `Bạn sẽ trả %1$s lúc thanh toán.<br/>Bạn đồng ý tự động trả %2$s mỗi %3$s tuần.`,
  _ = `Bạn sẽ trả %1$s lúc thanh toán.<br/>Bạn đồng ý tự động trả %2$s mỗi %3$s tháng.`,
  _ = `Bạn sẽ trả %1$s lúc thanh toán.<br/>Bạn đồng ý tự động trả %2$s mỗi %3$s năm.`,
  _ = `Bạn sẽ trả %1$s lúc thanh toán.<br/>Bạn ủy quyền cho trò chơi tính thêm phí tới %2$s mỗi %3$s giây.`,
  _ = `Bạn sẽ trả %1$s lúc thanh toán.<br/>Bạn ủy quyền cho trò chơi tính thêm phí tới %2$s mỗi %3$s phút.`,
  _ = `Bạn sẽ trả %1$s lúc thanh toán.<br/>Bạn ủy quyền cho trò chơi tính thêm phí tới %2$s mỗi %3$s giờ.`,
  _ = `Bạn sẽ trả %1$s lúc thanh toán.<br/>Bạn ủy quyền cho trò chơi tính thêm phí tới %2$s mỗi %3$s ngày.`,
  _ = `Bạn sẽ trả %1$s lúc thanh toán.<br/>Bạn ủy quyền cho trò chơi tính thêm phí tới %2$s mỗi %3$s tuần.`,
  _ = `Bạn sẽ trả %1$s lúc thanh toán.<br/>Bạn ủy quyền cho trò chơi tính thêm phí tới %2$s mỗi %3$s tháng.`,
  _ = `Bạn sẽ trả %1$s lúc thanh toán.<br/>Bạn ủy quyền cho trò chơi tính thêm phí tới %2$s mỗi %3$s năm.`,
  _ = `%1$s lúc thanh toán, cứ %3$s giây tự động gia hạn với giá %2$s.`,
  _ = `%1$s lúc thanh toán, cứ %3$s phút tự động gia hạn với giá %2$s.`,
  _ = `%1$s lúc thanh toán, cứ %3$s tiếng tự động gia hạn với giá %2$s.`,
  _ = `%1$s lúc thanh toán, cứ %3$s ngày tự động gia hạn với giá %2$s.`,
  _ = `%1$s lúc thanh toán, cứ %3$s tuần tự động gia hạn với giá %2$s.`,
  _ = `%1$s lúc thanh toán, cứ %3$s tháng tự động gia hạn với giá %2$s.`,
  _ = `%1$s lúc thanh toán, cứ %3$s năm tự động gia hạn với giá %2$s.`,
  _ = `Lần mua hàng đầu tiên có giá %1$s (được giảm %4$s%), cứ %3$s giây tự động gia hạn với giá %2$s.`,
  _ = `Lần mua hàng đầu tiên có giá %1$s (được giảm %4$s%), cứ %3$s phút tự động gia hạn với giá %2$s.`,
  _ = `Lần mua hàng đầu tiên có giá %1$s (được giảm %4$s%), cứ %3$s giờ tự động gia hạn với giá %2$s.`,
  _ = `Lần mua hàng đầu tiên có giá %1$s (được giảm %4$s%), cứ %3$s ngày tự động gia hạn với giá %2$s.`,
  _ = `Lần mua hàng đầu tiên có giá %1$s (được giảm %4$s%), cứ %3$s tuần tự động gia hạn với giá %2$s.`,
  _ = `Lần mua hàng đầu tiên có giá %1$s (được giảm %4$s%), cứ %3$s tháng tự động gia hạn với giá %2$s.`,
  _ = `Lần mua hàng đầu tiên có giá %1$s (được giảm %4$s%), cứ %3$s năm tự động gia hạn với giá %2$s.`,
  _ = `%1$s lúc thanh toán, cứ %3$s giây tự động gia hạn với giá %2$s như đã định bởi tài khoản trò chơi của bạn.`,
  _ = `%1$s lúc thanh toán, cứ %3$s phút tự động gia hạn với giá %2$s như đã định bởi tài khoản trò chơi của bạn.`,
  _ = `%1$s lúc thanh toán, cứ %3$s tiếng tự động gia hạn với giá %2$s như đã định bởi tài khoản trò chơi của bạn.`,
  _ = `%1$s lúc thanh toán, cứ %3$s ngày tự động gia hạn với giá %2$s như đã định bởi tài khoản trò chơi của bạn.`,
  _ = `%1$s lúc thanh toán, cứ %3$s tuần tự động gia hạn với giá %2$s như đã định bởi tài khoản trò chơi của bạn.`,
  _ = `%1$s lúc thanh toán, cứ %3$s tháng tự động gia hạn với giá %2$s như đã định bởi tài khoản trò chơi của bạn.`,
  _ = `%1$s lúc thanh toán, cứ %3$s năm tự động gia hạn với giá %2$s như đã định bởi tài khoản trò chơi của bạn.`,
  _ = `%1$s lúc thanh toán, cứ %3$s giây tự động gia hạn với giá %2$s cho mỗi giấy phép.`,
  _ = `%1$s lúc thanh toán, cứ %3$s phút tự động gia hạn với giá %2$s cho mỗi giấy phép.`,
  _ = `%1$s lúc thanh toán, cứ %3$s tiếng tự động gia hạn với giá %2$s cho mỗi giấy phép.`,
  _ = `%1$s lúc thanh toán, cứ %3$s ngày tự động gia hạn với giá %2$s cho mỗi giấy phép.`,
  _ = `%1$s lúc thanh toán, cứ %3$s tuần tự động gia hạn với giá %2$s cho mỗi giấy phép.`,
  _ = `%1$s lúc thanh toán, cứ %3$s tháng tự động gia hạn với giá %2$s cho mỗi giấy phép.`,
  _ = `%1$s lúc thanh toán, cứ %3$s năm tự động gia hạn với giá %2$s cho mỗi giấy phép.`,
  _ = `Lần mua hàng đầu tiên có giá %1$s (được giảm %4$s%), cứ %3$s giây tự động gia hạn với giá %2$s cho mỗi giấy phép.`,
  _ = `Lần mua hàng đầu tiên có giá %1$s (được giảm %4$s%), cứ %3$s phút tự động gia hạn với giá %2$s cho mỗi giấy phép.`,
  _ = `Lần mua hàng đầu tiên có giá %1$s (được giảm %4$s%), cứ %3$s giờ tự động gia hạn với giá %2$s cho mỗi giấy phép.`,
  _ = `Lần mua hàng đầu tiên có giá %1$s (được giảm %4$s%), cứ %3$s ngày tự động gia hạn với giá %2$s cho mỗi giấy phép.`,
  _ = `Lần mua hàng đầu tiên có giá %1$s (được giảm %4$s%), cứ %3$s tuần tự động gia hạn với giá %2$s cho mỗi giấy phép.`,
  _ = `Lần mua hàng đầu tiên có giá %1$s (được giảm %4$s%), cứ %3$s tháng tự động gia hạn với giá %2$s cho mỗi giấy phép.`,
  _ = `Lần mua hàng đầu tiên có giá %1$s (được giảm %4$s%), cứ %3$s năm tự động gia hạn với giá %2$s cho mỗi giấy phép.`,
  _ = `Giỏ hàng của bạn đang trống.`,
  _ = `Một số sản phẩm trong này đã được đánh dấu riêng tư. Chúng sẽ giữ nguyên trạng thái nếu bạn tiếp tục:`,
  _ = `Đánh dấu riêng tư sẽ ẩn trò chơi khỏi mọi nơi khác bên ngoài thư viện của bạn. Thông tin về quyền sở hữu, trạng thái trong trò chơi, thời gian chơi, và hoạt động sẽ không hiển thị cho người khác.`,
  _ = `Bạn thấy phiên bản mới của giỏ hàng vì đang tham gia Beta phần mềm Steam. <1>Để lại phản hồi hoặc báo cáo lỗi</1>`,
  _ = `Chúng tôi đang thử nghiệm phiên bản mới của giỏ hàng. <1>Để lại phản hồi hoặc báo cáo lỗi</1>`,
  _ = `Bạn không thể lên lịch tặng quà cho thời điểm quá xa trong tương lai.`,
  _ = `Vui lòng nhập ngày giờ hợp lệ.`,
  _ = `Có vấn đề khi hiển thị sản phẩm này`,
  _ = `Việc mua hàng này sẽ cho bạn %1$s thẻ trao đổi %2$s.`,
  _ = `Việc mua hàng này sẽ cho bạn %1$s thẻ trao đổi %2$s.`,
  _ = `Mua trên cửa hàng Steam trong đợt giảm giá sẽ cho bạn thẻ trao đổi %1$s.`,
  _ = `Bạn sẽ nhận được thẻ cho dù nó được mua để làm quà tặng.`,
  _ = `Quá trình tới thẻ tiếp theo`,
  _ = `khoảng %1$s mỗi thẻ`,
  _ = `Lưu ý: Sản phẩm đặt mua trước không đủ điều kiện nhận phần thưởng thẻ trao đổi %1$s. Sản phẩm sau sẽ không nhận được phần thưởng thẻ trao đổi:`,
  _ = `Yêu cầu mua hàng từ %1$s`,
  _ = `Đơn hàng cho:`,
  _ = `Mua để làm quà: %1$s`,
  _ = `Thêm vào giỏ hàng một bản sao nữa của sản phẩm`,
  _ = `Tuyên bố tuân thủ PSTI của Vương quốc Anh`,
  _ = `Đã có vấn đề phát sinh khi cập nhật giỏ hàng.`,
  _ = `Mã lỗi: %1$s`,
  _ = `Quốc gia`,
  _ = `Giỏ hàng đã lưu`,
  _ = `Đây là một giỏ hàng đã được lưu. Đã có lỗi xảy ra trong lần mua hàng gần đây nhất của bạn, nên chúng tôi đã lưu lại giỏ hàng (bao gồm cả giảm giá) trong vòng %1$s giờ để bạn có thể thử mua lại một lần nữa.`,
  _ = `Sao chép tùy chọn quà tặng từ`,
  _ = `<1>Đăng nhập</1> để chọn bạn bè Steam`,
  _ = {
    language: _,
    Cart_Remove: _,
    Cart_Add: _,
    Cart_Verify: _,
    Cart_RemoveAll: _,
    Cart_Edit: _,
    Cart_Quantity: _,
    Cart_YourShoppingCart: _,
    Cart_YourShoppingCartLineItems: _,
    Cart_YourShoppingCartLineItems_Plural: _,
    Cart_EstimatedTotal: _,
    Cart_Note_SalesTax: _,
    Cart_PurchaseBtn: _,
    Cart_ContainsGiftCheckbox: _,
    Cart_Bradcrumb_Home: _,
    Cart_LineItemGift_Checkbox: _,
    Cart_IncludesItems: _,
    Cart_IncludesItems_Plural: _,
    Cart_SelectRecipient: _,
    Cart_EnterRecipientEmail: _,
    Cart_ChangeGiftRecipient: _,
    Cart_GiftRecipient_Label: _,
    Cart_GiftRecipientEmail_Label: _,
    Cart_GiftDelivery_Label: _,
    Cart_GiftDelivery_Reset: _,
    Cart_GiftDelivery_Now: _,
    Cart_GiftDelivery_Scheduled: _,
    Cart_GiftDelivery_ScheduleDelivery: _,
    Cart_GiftDelivery_From: _,
    Cart_GiftDelivery_Signature: _,
    Cart_GiftDelivery_AddSignature: _,
    Cart_GiftDelivery_Body: _,
    Cart_GiftDeliveryEmail_Warning1: _,
    Cart_GiftDeliveryEmail_Warning2: _,
    Cart_FamilyGift_Notice: _,
    Cart_GiftRecipientModal_Title: _,
    Cart_EditGiftDelivery: _,
    Cart_GiftRecipientModal_Save: _,
    Cart_GiftRecipientModal_Placeholder: _,
    Cart_GiftRecipientModal_OwnsGameLabel: _,
    Cart_GiftRecipientModal_OnWishlist: _,
    Cart_GiftRecipientModal_PartialOwnsLabel: _,
    Cart_GiftRecipientModal_PartialWishlistLabel: _,
    Cart_GiftOptions: _,
    Cart_GiftRecipientModal_IssueLoading: _,
    Cart_ContinueButton_Payment: _,
    Cart_ContinueButton_Gifts: _,
    Cart_ContinueButton_Login: _,
    Cart_DeclinePurchaseRequest: _,
    Cart_LineItemOptions_Myself: _,
    Cart_LineItemOptions_Gift: _,
    Cart_LineItemOptions_GiftForPersona: _,
    Cart_LineItemOptions_Privately: _,
    Cart_CountWidget: _,
    Cart_AddedToYourCart: _,
    Cart_UpdatedYourCart: _,
    Cart_ContinueShopping: _,
    Cart_ComingSoon: _,
    Cart_ViewMyCart: _,
    Cart_RequestPurchase: _,
    Cart_RequestPurchaseExplanation: _,
    Cart_RequestPurchaseNonGiftableItems: _,
    Cart_CouponModify_Change: _,
    Cart_CouponModify_Add: _,
    Cart_CouponAvailability: _,
    Cart_CouponAvailability_Plural: _,
    Cart_Coupons_Applied: _,
    Cart_Coupons_InUse: _,
    Cart_SelectCouponToApply: _,
    Cart_ShippingEstimate_DeliveryDate: _,
    Cart_ShippingEstimate_Range: _,
    Cart_ShippingEstimate_Delayed: _,
    Cart_ShippingEstimate_Standard: _,
    Cart_FooterNoticeHeader_MustFix: _,
    Cart_FooterNoticeHeader_Warning: _,
    Cart_CartLevelErrorNotice: _,
    Cart_CartLevelErrorMultiple: _,
    Cart_CartLevelErrorFormat: _,
    Cart_Error_AlreadyOwned_FootNote: _,
    Cart_Error_AlreadyOwned_LineItem_Game: _,
    Cart_Error_AlreadyOwned_LineItem: _,
    Cart_Error_AlreadyOwned_GiftLineItem_Game: _,
    Cart_Error_AlreadyOwned_GiftLineItem: _,
    Cart_Error_AlreadyOwned_GiftFootNote: _,
    Cart_Error_DuplicateApps_FootNote: _,
    Cart_Error_DuplicateApps_LineItem: _,
    Cart_Error_UnavailableCountry_FootNote: _,
    Cart_Error_UnavailableCountry_LineItem: _,
    Cart_Error_AdultContentRestricted_FootNote: _,
    Cart_Error_AdultContentRestricted_LineItem: _,
    Cart_Error_MasterSubscription_FootNote: _,
    Cart_Error_MasterSubscription_LineItem: _,
    Cart_Error_CouponIsExclusivePromo: _,
    Cart_Error_CouponIsInvalid: _,
    Cart_Error_CouponIsInvalidForItem: _,
    Cart_Error_TooManyInCart: _,
    Cart_Error_CommercialLicenseRestricted_FootNote: _,
    Cart_Error_CommercialLicenseRestricted_LineItem: _,
    Cart_Error_GiftRecipientInvalid: _,
    Cart_Error_MissingMustOwnApps_LineItem: _,
    Cart_Error_MissingMustOwnApps_GiftLineItem: _,
    Cart_Error_MissingMustOwnApps_FootNote: _,
    Cart_Error_MissingMustOwnApps_FootNoteGift: _,
    Cart_Error_ExistingBillingAgreement: _,
    Cart_Error_ExistingBillingAgreement_FootNote: _,
    Cart_Warning_AlreadyOwned_LineItem: _,
    Cart_Warning_ExtraCopies_LineItem: _,
    Cart_Warning_PriceChange_FootNote: _,
    Cart_Warning_PriceChange_LineItem: _,
    Cart_Warning_NoRefund_LineItem: _,
    Cart_Warning_RecipientHigherPrice: _,
    Cart_Warning_AvailableAtALowerPrice: _,
    Cart_Warning_GiftToNonFriend: _,
    Cart_Warning_GiftToNonFriend_Named: _,
    Cart_Warning_GiftToAccount_LoggedOut_Actionable: _,
    Cart_GifteeHint_Wishlist: _,
    PackageIncludesSubscriptionBySecond: _,
    PackageIncludesSubscriptionByMinute: _,
    PackageIncludesSubscriptionByHour: _,
    PackageIncludesSubscriptionByDay: _,
    PackageIncludesSubscriptionByWeek: _,
    PackageIncludesSubscriptionByMonth: _,
    PackageIncludesSubscriptionByYear: _,
    MultiLicenseIncludesSubscriptionBySecond: _,
    MultiLicenseIncludesSubscriptionByMinute: _,
    MultiLicenseIncludesSubscriptionByHour: _,
    MultiLicenseIncludesSubscriptionByDay: _,
    MultiLicenseIncludesSubscriptionByWeek: _,
    MultiLicenseIncludesSubscriptionByMonth: _,
    MultiLicenseeIncludesSubscriptionByYear: _,
    GameBillingPackageIncludesSubscriptionBySecond: _,
    GameBillingPackageIncludesSubscriptionByMinute: _,
    GameBillingPackageIncludesSubscriptionByHour: _,
    GameBillingPackageIncludesSubscriptionByDay: _,
    GameBillingPackageIncludesSubscriptionByWeek: _,
    GameBillingPackageIncludesSubscriptionByMonth: _,
    GameBillingPackageIncludesSubscriptionByYear: _,
    MicroTxnSubscriptionCostBySecond: _,
    MicroTxnSubscriptionCostByMinute: _,
    MicroTxnSubscriptionCostByHour: _,
    MicroTxnSubscriptionCostByDay: _,
    MicroTxnSubscriptionCostByWeek: _,
    MicroTxnSubscriptionCostByMonth: _,
    MicroTxnSubscriptionCostByYear: _,
    GameBillingAuthorizeSubscriptionBySecond: _,
    GameBillingAuthorizeSubscriptionByMinute: _,
    GameBillingAuthorizeSubscriptionByHour: _,
    GameBillingAuthorizeSubscriptionByDay: _,
    GameBillingAuthorizeSubscriptionByWeek: _,
    GameBillingAuthorizeSubscriptionByMonth: _,
    GameBillingAuthorizeSubscriptionByYear: _,
    PackageCostIncludesSubscriptionBySecond: _,
    PackageCostIncludesSubscriptionByMinute: _,
    PackageCostIncludesSubscriptionByHour: _,
    PackageCostIncludesSubscriptionByDay: _,
    PackageCostIncludesSubscriptionByWeek: _,
    PackageCostIncludesSubscriptionByMonth: _,
    PackageCostIncludesSubscriptionByYear: _,
    PackageWithDiscountCostIncludesSubscriptionBySecond: _,
    PackageWithDiscountCostIncludesSubscriptionByMinute: _,
    PackageWithDiscountCostIncludesSubscriptionByHour: _,
    PackageWithDiscountCostIncludesSubscriptionByDay: _,
    PackageWithDiscountCostIncludesSubscriptionByWeek: _,
    PackageWithDiscountCostIncludesSubscriptionByMonth: _,
    PackageWithDiscountCostIncludesSubscriptionByYear: _,
    GameBillingPackageCostIncludesSubscriptionBySecond: _,
    GameBillingPackageCostIncludesSubscriptionByMinute: _,
    GameBillingPackageCostIncludesSubscriptionByHour: _,
    GameBillingPackageCostIncludesSubscriptionByDay: _,
    GameBillingPackageCostIncludesSubscriptionByWeek: _,
    GameBillingPackageCostIncludesSubscriptionByMonth: _,
    GameBillingPackageCostIncludesSubscriptionByYear: _,
    MultiLicenseCostIncludesSubscriptionBySecond: _,
    MultiLicenseCostIncludesSubscriptionByMinute: _,
    MultiLicenseCostIncludesSubscriptionByHour: _,
    MultiLicenseCostIncludesSubscriptionByDay: _,
    MultiLicenseCostIncludesSubscriptionByWeek: _,
    MultiLicenseCostIncludesSubscriptionByMonth: _,
    MultiLicenseCostIncludesSubscriptionByYear: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionBySecond: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMinute: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByHour: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByDay: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByWeek: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMonth: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByYear: _,
    Cart_Empty: _,
    Cart_Notice_SomeAppsPrivate: _,
    Cart_LineItemOptions_PrivateTooltip: _,
    Cart_BetaNotice: _,
    Cart_GenericBetaNotice: _,
    Cart_GiftScheduleError_TooFar: _,
    Cart_GiftScheduleError_InvalidDate: _,
    Cart_LineItem_ErrorBoundary: _,
    Cart_SaleCardDrops_EarnedMessage: _,
    Cart_SaleCardDrops_EarnedMessage_Plural: _,
    Cart_SaleCardDrops_Explanation: _,
    Cart_SaleCardDrops_Explanation_Gifts: _,
    Cart_SaleCardDrops_ProgressLabel: _,
    Cart_SaleCardDrops_CardCost: _,
    Cart_SaleCardDrops_PrepurchaseIneligible: _,
    Cart_PurchaseRequestTitle: _,
    Cart_PurchaseFor_Label: _,
    Cart_GiftForNotice: _,
    Cart_LineItem_Add_Tooltip: _,
    Cart_LineItem_Hardware_Compliance_Label: _,
    Cart_ErrorUpdating: _,
    Cart_ErrorCode: _,
    Cart_UserCountrySelector: _,
    Cart_Replay_SavedCart: _,
    Cart_Replay_Instructions: _,
    Cart_Gifting_CopyGiftOptionsFrom: _,
    Cart_Gifting_SignInToSelectFriends: _,
  };
export {
  _ as Cart_Add,
  _ as Cart_AddedToYourCart,
  _ as Cart_BetaNotice,
  _ as Cart_Bradcrumb_Home,
  _ as Cart_CartLevelErrorFormat,
  _ as Cart_CartLevelErrorMultiple,
  _ as Cart_CartLevelErrorNotice,
  _ as Cart_ChangeGiftRecipient,
  _ as Cart_ComingSoon,
  _ as Cart_ContainsGiftCheckbox,
  _ as Cart_ContinueButton_Gifts,
  _ as Cart_ContinueButton_Login,
  _ as Cart_ContinueButton_Payment,
  _ as Cart_ContinueShopping,
  _ as Cart_CountWidget,
  _ as Cart_CouponAvailability,
  _ as Cart_CouponAvailability_Plural,
  _ as Cart_CouponModify_Add,
  _ as Cart_CouponModify_Change,
  _ as Cart_Coupons_Applied,
  _ as Cart_Coupons_InUse,
  _ as Cart_DeclinePurchaseRequest,
  _ as Cart_Edit,
  _ as Cart_EditGiftDelivery,
  _ as Cart_Empty,
  _ as Cart_EnterRecipientEmail,
  _ as Cart_ErrorCode,
  _ as Cart_ErrorUpdating,
  _ as Cart_Error_AdultContentRestricted_FootNote,
  _ as Cart_Error_AdultContentRestricted_LineItem,
  _ as Cart_Error_AlreadyOwned_FootNote,
  _ as Cart_Error_AlreadyOwned_GiftFootNote,
  _ as Cart_Error_AlreadyOwned_GiftLineItem,
  _ as Cart_Error_AlreadyOwned_GiftLineItem_Game,
  _ as Cart_Error_AlreadyOwned_LineItem,
  _ as Cart_Error_AlreadyOwned_LineItem_Game,
  _ as Cart_Error_CommercialLicenseRestricted_FootNote,
  _ as Cart_Error_CommercialLicenseRestricted_LineItem,
  _ as Cart_Error_CouponIsExclusivePromo,
  _ as Cart_Error_CouponIsInvalid,
  _ as Cart_Error_CouponIsInvalidForItem,
  _ as Cart_Error_DuplicateApps_FootNote,
  _ as Cart_Error_DuplicateApps_LineItem,
  _ as Cart_Error_ExistingBillingAgreement,
  _ as Cart_Error_ExistingBillingAgreement_FootNote,
  _ as Cart_Error_GiftRecipientInvalid,
  _ as Cart_Error_MasterSubscription_FootNote,
  _ as Cart_Error_MasterSubscription_LineItem,
  _ as Cart_Error_MissingMustOwnApps_FootNote,
  _ as Cart_Error_MissingMustOwnApps_FootNoteGift,
  _ as Cart_Error_MissingMustOwnApps_GiftLineItem,
  _ as Cart_Error_MissingMustOwnApps_LineItem,
  _ as Cart_Error_TooManyInCart,
  _ as Cart_Error_UnavailableCountry_FootNote,
  _ as Cart_Error_UnavailableCountry_LineItem,
  _ as Cart_EstimatedTotal,
  _ as Cart_FamilyGift_Notice,
  _ as Cart_FooterNoticeHeader_MustFix,
  _ as Cart_FooterNoticeHeader_Warning,
  _ as Cart_GenericBetaNotice,
  _ as Cart_GiftDeliveryEmail_Warning1,
  _ as Cart_GiftDeliveryEmail_Warning2,
  _ as Cart_GiftDelivery_AddSignature,
  _ as Cart_GiftDelivery_Body,
  _ as Cart_GiftDelivery_From,
  _ as Cart_GiftDelivery_Label,
  _ as Cart_GiftDelivery_Now,
  _ as Cart_GiftDelivery_Reset,
  _ as Cart_GiftDelivery_ScheduleDelivery,
  _ as Cart_GiftDelivery_Scheduled,
  _ as Cart_GiftDelivery_Signature,
  _ as Cart_GiftForNotice,
  _ as Cart_GiftOptions,
  _ as Cart_GiftRecipientEmail_Label,
  _ as Cart_GiftRecipientModal_IssueLoading,
  _ as Cart_GiftRecipientModal_OnWishlist,
  _ as Cart_GiftRecipientModal_OwnsGameLabel,
  _ as Cart_GiftRecipientModal_PartialOwnsLabel,
  _ as Cart_GiftRecipientModal_PartialWishlistLabel,
  _ as Cart_GiftRecipientModal_Placeholder,
  _ as Cart_GiftRecipientModal_Save,
  _ as Cart_GiftRecipientModal_Title,
  _ as Cart_GiftRecipient_Label,
  _ as Cart_GiftScheduleError_InvalidDate,
  _ as Cart_GiftScheduleError_TooFar,
  _ as Cart_GifteeHint_Wishlist,
  _ as Cart_Gifting_CopyGiftOptionsFrom,
  _ as Cart_Gifting_SignInToSelectFriends,
  _ as Cart_IncludesItems,
  _ as Cart_IncludesItems_Plural,
  _ as Cart_LineItemGift_Checkbox,
  _ as Cart_LineItemOptions_Gift,
  _ as Cart_LineItemOptions_GiftForPersona,
  _ as Cart_LineItemOptions_Myself,
  _ as Cart_LineItemOptions_PrivateTooltip,
  _ as Cart_LineItemOptions_Privately,
  _ as Cart_LineItem_Add_Tooltip,
  _ as Cart_LineItem_ErrorBoundary,
  _ as Cart_LineItem_Hardware_Compliance_Label,
  _ as Cart_Note_SalesTax,
  _ as Cart_Notice_SomeAppsPrivate,
  _ as Cart_PurchaseBtn,
  _ as Cart_PurchaseFor_Label,
  _ as Cart_PurchaseRequestTitle,
  _ as Cart_Quantity,
  _ as Cart_Remove,
  _ as Cart_RemoveAll,
  _ as Cart_Replay_Instructions,
  _ as Cart_Replay_SavedCart,
  _ as Cart_RequestPurchase,
  _ as Cart_RequestPurchaseExplanation,
  _ as Cart_RequestPurchaseNonGiftableItems,
  _ as Cart_SaleCardDrops_CardCost,
  _ as Cart_SaleCardDrops_EarnedMessage,
  _ as Cart_SaleCardDrops_EarnedMessage_Plural,
  _ as Cart_SaleCardDrops_Explanation,
  _ as Cart_SaleCardDrops_Explanation_Gifts,
  _ as Cart_SaleCardDrops_PrepurchaseIneligible,
  _ as Cart_SaleCardDrops_ProgressLabel,
  _ as Cart_SelectCouponToApply,
  _ as Cart_SelectRecipient,
  _ as Cart_ShippingEstimate_Delayed,
  _ as Cart_ShippingEstimate_DeliveryDate,
  _ as Cart_ShippingEstimate_Range,
  _ as Cart_ShippingEstimate_Standard,
  _ as Cart_UpdatedYourCart,
  _ as Cart_UserCountrySelector,
  _ as Cart_Verify,
  _ as Cart_ViewMyCart,
  _ as Cart_Warning_AlreadyOwned_LineItem,
  _ as Cart_Warning_AvailableAtALowerPrice,
  _ as Cart_Warning_ExtraCopies_LineItem,
  _ as Cart_Warning_GiftToAccount_LoggedOut_Actionable,
  _ as Cart_Warning_GiftToNonFriend,
  _ as Cart_Warning_GiftToNonFriend_Named,
  _ as Cart_Warning_NoRefund_LineItem,
  _ as Cart_Warning_PriceChange_FootNote,
  _ as Cart_Warning_PriceChange_LineItem,
  _ as Cart_Warning_RecipientHigherPrice,
  _ as Cart_YourShoppingCart,
  _ as Cart_YourShoppingCartLineItems,
  _ as Cart_YourShoppingCartLineItems_Plural,
  _ as GameBillingAuthorizeSubscriptionByDay,
  _ as GameBillingAuthorizeSubscriptionByHour,
  _ as GameBillingAuthorizeSubscriptionByMinute,
  _ as GameBillingAuthorizeSubscriptionByMonth,
  _ as GameBillingAuthorizeSubscriptionBySecond,
  _ as GameBillingAuthorizeSubscriptionByWeek,
  _ as GameBillingAuthorizeSubscriptionByYear,
  _ as GameBillingPackageCostIncludesSubscriptionByDay,
  _ as GameBillingPackageCostIncludesSubscriptionByHour,
  _ as GameBillingPackageCostIncludesSubscriptionByMinute,
  _ as GameBillingPackageCostIncludesSubscriptionByMonth,
  _ as GameBillingPackageCostIncludesSubscriptionBySecond,
  _ as GameBillingPackageCostIncludesSubscriptionByWeek,
  _ as GameBillingPackageCostIncludesSubscriptionByYear,
  _ as GameBillingPackageIncludesSubscriptionByDay,
  _ as GameBillingPackageIncludesSubscriptionByHour,
  _ as GameBillingPackageIncludesSubscriptionByMinute,
  _ as GameBillingPackageIncludesSubscriptionByMonth,
  _ as GameBillingPackageIncludesSubscriptionBySecond,
  _ as GameBillingPackageIncludesSubscriptionByWeek,
  _ as GameBillingPackageIncludesSubscriptionByYear,
  _ as MicroTxnSubscriptionCostByDay,
  _ as MicroTxnSubscriptionCostByHour,
  _ as MicroTxnSubscriptionCostByMinute,
  _ as MicroTxnSubscriptionCostByMonth,
  _ as MicroTxnSubscriptionCostBySecond,
  _ as MicroTxnSubscriptionCostByWeek,
  _ as MicroTxnSubscriptionCostByYear,
  _ as MultiLicenseCostIncludesSubscriptionByDay,
  _ as MultiLicenseCostIncludesSubscriptionByHour,
  _ as MultiLicenseCostIncludesSubscriptionByMinute,
  _ as MultiLicenseCostIncludesSubscriptionByMonth,
  _ as MultiLicenseCostIncludesSubscriptionBySecond,
  _ as MultiLicenseCostIncludesSubscriptionByWeek,
  _ as MultiLicenseCostIncludesSubscriptionByYear,
  _ as MultiLicenseIncludesSubscriptionByDay,
  _ as MultiLicenseIncludesSubscriptionByHour,
  _ as MultiLicenseIncludesSubscriptionByMinute,
  _ as MultiLicenseIncludesSubscriptionByMonth,
  _ as MultiLicenseIncludesSubscriptionBySecond,
  _ as MultiLicenseIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByDay,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByHour,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMinute,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMonth,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionBySecond,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByYear,
  _ as MultiLicenseeIncludesSubscriptionByYear,
  _ as PackageCostIncludesSubscriptionByDay,
  _ as PackageCostIncludesSubscriptionByHour,
  _ as PackageCostIncludesSubscriptionByMinute,
  _ as PackageCostIncludesSubscriptionByMonth,
  _ as PackageCostIncludesSubscriptionBySecond,
  _ as PackageCostIncludesSubscriptionByWeek,
  _ as PackageCostIncludesSubscriptionByYear,
  _ as PackageIncludesSubscriptionByDay,
  _ as PackageIncludesSubscriptionByHour,
  _ as PackageIncludesSubscriptionByMinute,
  _ as PackageIncludesSubscriptionByMonth,
  _ as PackageIncludesSubscriptionBySecond,
  _ as PackageIncludesSubscriptionByWeek,
  _ as PackageIncludesSubscriptionByYear,
  _ as PackageWithDiscountCostIncludesSubscriptionByDay,
  _ as PackageWithDiscountCostIncludesSubscriptionByHour,
  _ as PackageWithDiscountCostIncludesSubscriptionByMinute,
  _ as PackageWithDiscountCostIncludesSubscriptionByMonth,
  _ as PackageWithDiscountCostIncludesSubscriptionBySecond,
  _ as PackageWithDiscountCostIncludesSubscriptionByWeek,
  _ as PackageWithDiscountCostIncludesSubscriptionByYear,
  _ as default,
  _ as language,
};
