var _ = `spanish`,
  _ = `Eliminar`,
  _ = `Añadir`,
  _ = `Verificar edad`,
  _ = `Eliminar todos los artículos`,
  _ = `Modificar`,
  _ = `Cantidad: %1$s`,
  _ = `Tu carro de la compra`,
  _ = `Tu carro de la compra (%1$s\xA0artículo)`,
  _ = `Tu carro de la compra (%1$s\xA0artículos)`,
  _ = `Total estimado`,
  _ = `Los impuestos de venta se calcularán durante el pago (si es aplicable)`,
  _ = `Comprar`,
  _ = `Esta compra incluye un regalo`,
  _ = `Inicio`,
  _ = `¿Esto es un regalo?`,
  _ = `Incluye %1$s artículo`,
  _ = `Incluye %1$s artículos`,
  _ = `Elegir el destinatario`,
  _ = `Introducir correo electrónico`,
  _ = `Modificar el destinatario del regalo...`,
  _ = `Destinatario del regalo:`,
  _ = `Correo electrónico del destinatario del regalo:`,
  _ = `Entrega:`,
  _ = `Restablecer`,
  _ = `Lo antes posible (por correo electrónico y a través del cliente de Steam)`,
  _ = `Programado:`,
  _ = `Programar entrega`,
  _ = `De:`,
  _ = `Tu firma:`,
  _ = `Añadir una firma personalizada`,
  _ = `Mensaje del regalo (máximo 160\xA0caracteres, quedan %1$s):`,
  _ = `Los regalos enviados por correo electrónico se reembolsarán automáticamente al cabo de 30\xA0días si no se han añadido a una cuenta de Steam.`,
  _ = `Los regalos enviados por correo electrónico solo pueden aceptarlos las cuentas de Steam de la misma región que la del comprador (%1$s).`,
  _ = `Los regalos que envíes a los menores de tu grupo familiar de Steam se añadirán automáticamente a su cuenta y a sus juegos permitidos.`,
  _ = `Selecciona el destinatario del regalo`,
  _ = `Modificar el método de entrega`,
  _ = `Guardar`,
  _ = `Buscar por nombre de amigo...`,
  _ = `Ya tiene este artículo`,
  _ = `En la lista de deseados`,
  _ = `Ya tiene «%1$s»`,
  _ = `Desea tener «%1$s»`,
  _ = `Opciones de regalo`,
  _ = `Se ha producido un problema al cargar los posibles destinatarios del regalo. Vuelve a intentarlo más tarde.`,
  _ = `Continuar al pago`,
  _ = `Continuar a las opciones de regalo`,
  _ = `Inicia sesión para comprar`,
  _ = `Rechazar solicitud`,
  _ = `Para mi cuenta`,
  _ = `Esto es un regalo`,
  _ = `Esto es un regalo para %1$s`,
  _ = `Para mi cuenta: privado`,
  _ = `Carro (%1$s)`,
  _ = `¡Añadido a tu carro!`,
  _ = `¡Tu carro se ha actualizado!`,
  _ = `Seguir comprando`,
  _ = `Disponible: %1$s`,
  _ = `Ver mi carro (%1$s)`,
  _ = `Solicitar compra`,
  _ = `Los adultos de tu grupo familiar de Steam recibirán una notificación sobre tu solicitud de compra.`,
  _ = `No se puede solicitar la compra porque el carro contiene artículos que no se pueden regalar`,
  _ = `Cambiar o eliminar cupón`,
  _ = `Añadir cupón`,
  _ = `Tienes 1\xA0cupón disponible para este artículo`,
  _ = `Tienes %1$s\xA0cupones disponibles para este artículo`,
  _ = `Aplicado actualmente`,
  _ = `Aplicado actualmente a otro producto`,
  _ = `Selecciona un cupón para aplicar a %1$s`,
  _ = `Entrega aproximada: %1$s`,
  _ = `de %1$s a %2$s\xA0días hábiles`,
  _ = `Entrega aproximada: de 6 a 10\xA0días laborables`,
  _ = `Entrega aproximada: de 3 a 5\xA0días laborables`,
  _ = `Antes de poder continuar al pago:`,
  _ = `Notas:`,
  _ = `Debes realizar una acción antes de poder continuar al pago.`,
  _ = `Notas:`,
  _ = `Nota: %1$s`,
  _ = `Tu cuenta ya tiene algunos de los artículos de arriba, por lo que no puedes volver a comprarlos. Puedes adquirirlos como regalos o bien modificar el contenido del carro para continuar.`,
  _ = `Ya tienes este juego`,
  _ = `Ya tienes todo lo que se incluye en este paquete`,
  _ = `El destinatario del regalo ya tiene este juego`,
  _ = `El destinatario del regalo ya tiene todo lo que contiene este paquete`,
  _ = `El destinatario del regalo ya tiene algunos de los artículos de arriba, por lo que no puedes volver a comprarlos. Puedes adquirirlos para otra cuenta o bien modificar el contenido del carro para continuar.`,
  _ = `El carro contiene paquetes que se solapan. Para poder pagar, antes debes eliminar los paquetes redundantes del carro.`,
  _ = `Ya en el carro: `,
  _ = `El carro contiene un paquete que no está disponible en tu país. Para poder pagar, antes debes eliminar ese paquete del carro.`,
  _ = `No disponible en tu país`,
  _ = `Valve necesita confirmar que eres mayor de edad para permitir la compra de contenido sexual para adultos.`,
  _ = `No está disponible para su compra hasta que verifiques tu edad.`,
  _ = `El carro incluye contenido que también está disponible a través de una de tus suscripciones activas.`,
  _ = `Disponible a través de tu suscripción de:`,
  _ = `Este cupón no se puede utilizar junto con otro descuento.`,
  _ = `Este cupón no es válido o ha caducado.`,
  _ = `Este cupón no se puede aplicar a este artículo.`,
  _ = `Has superado la cantidad máxima de este artículo que puedes añadir a tu carro.`,
  _ = `Tu carro incluye un artículo que no está disponible para su compra.`,
  _ = `No disponible para su compra`,
  _ = `El destinatario seleccionado no puede recibir este regalo comprado en tu región.`,
  _ = `Para comprar este artículo, necesitas los siguientes: `,
  _ = `Para comprar este artículo, el destinatario del regalo necesita los siguientes:`,
  _ = `A tu cuenta le faltan algunos artículos necesarios para comprar los que se encuentran en tu carro. Puedes añadir los artículos que faltan o modificar el contenido del carro para continuar.`,
  _ = `Al destinatario del regalo le faltan algunos artículos necesarios para comprar los que se encuentran en tu carro. Puedes añadir los artículos que faltan o modificar el contenido del carro para continuar.`,
  _ = `Ya tienes una suscripción a este artículo.`,
  _ = `Tu cuenta ya tiene una suscripción para algunos de los artículos de arriba. Consulta los detalles de tus suscripciones en los parámetros de la cuenta.`,
  _ = `Si lo estás comprando para ti, no recibirás una copia extra de: `,
  _ = `Si lo estás comprando para ti, recibirás una copia extra para regalar de:`,
  _ = `Uno o más de los artículos de abajo han cambiado de precio desde que los añadiste al carro.`,
  _ = `El precio de este artículo ha cambiado`,
  _ = `Este producto incluye contenido consumible que lo hace no reembolsable.`,
  _ = `El destinatario del regalo que has seleccionado se encuentra en una región con precios más elevados. El precio de este artículo se ha actualizado para ajustarlo a su región y que puedas regalárselo.`,
  _ = `Este artículo está disponible a un precio más bajo como parte de «%1$s».`,
  _ = `El destinatario del regalo NO está en tu lista de amigos de Steam.`,
  _ = `NOTA: %1$s NO está en tu lista de amigos de Steam.`,
  _ = `Si estás enviando un regalo a un amigo de Steam, <1>inicia sesión</1> para verificar que el destinatario está en tu lista de amigos.`,
  _ = `Visitaste hace poco la lista de deseados de %1$s. ¿Quieres regalarle estos artículos?`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s segundo(s).`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s minuto(s).`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s hora(s).`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s día(s).`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s semana(s).`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s mes(es).`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s año(s).`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s\xA0segundo(s) por licencia.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s\xA0minuto(s) por licencia.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s\xA0hora(s) por licencia.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s\xA0día(s) por licencia.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s\xA0semana(s) por licencia.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s\xA0mes(es) por licencia.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s\xA0año(s) por licencia.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s segundo(s) o según lo determinado por tu cuenta del juego.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s minuto(s) o según lo determinado por tu cuenta del juego.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s hora(s) o según lo determinado por tu cuenta del juego.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s día(s) o según lo determinado por tu cuenta del juego.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s semana(s) o según lo determinado por tu cuenta del juego.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s mes(es) o según lo determinado por tu cuenta del juego.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s año(s) o según lo determinado por tu cuenta del juego.`,
  _ = `Se te cobrará un importe de %1$s al finalizar la compra.<br/>Aceptas recibir un cargo automático de %2$s cada %3$s segundo(s).`,
  _ = `Se te cobrará un importe de %1$s al finalizar la compra.<br/>Aceptas recibir un cargo automático de %2$s cada %3$s minuto(s).`,
  _ = `Se te cobrará un importe de %1$s al finalizar la compra.<br/>Aceptas recibir un cargo automático de %2$s cada %3$s hora(s).`,
  _ = `Se te cobrará un importe de %1$s al finalizar la compra.<br/>Aceptas recibir un cargo automático de %2$s cada %3$s día(s).`,
  _ = `Se te cobrará un importe de %1$s al finalizar la compra.<br/>Aceptas recibir un cargo automático de %2$s cada %3$s semana(s).`,
  _ = `Se te cobrará un importe de %1$s al finalizar la compra.<br/>Aceptas recibir un cargo automático de %2$s cada %3$s mes(es).`,
  _ = `Se te cobrará un importe de %1$s al finalizar la compra.<br/>Aceptas recibir un cargo automático de %2$s cada %3$s año(s).`,
  _ = `Se te cobrarán %1$s a la hora de realizar el pago.<br/>Autorizas a este juego a realizar cobros adicionales de hasta %2$s cada %3$s segundo(s).`,
  _ = `Se te cobrarán %1$s a la hora de realizar el pago.<br/>Autorizas a este juego a realizar cobros adicionales de hasta %2$s cada %3$s minuto(s).`,
  _ = `Se te cobrarán %1$s a la hora de realizar el pago.<br/>Autorizas a este juego a realizar cobros adicionales de hasta %2$s cada %3$s hora(s).`,
  _ = `Se te cobrarán %1$s a la hora de realizar el pago.<br/>Autorizas a este juego a realizar cobros adicionales de hasta %2$s cada %3$s día(s).`,
  _ = `Se te cobrarán %1$s a la hora de realizar el pago.<br/>Autorizas a este juego a realizar cobros adicionales de hasta %2$s cada %3$s semana(s).`,
  _ = `Se te cobrarán %1$s a la hora de realizar el pago.<br/>Autorizas a este juego a realizar cobros adicionales de hasta %2$s cada %3$s mes(es).`,
  _ = `Se te cobrarán %1$s a la hora de realizar el pago.<br/>Autorizas a este juego a realizar cobros adicionales de hasta %2$s cada %3$s año(s).`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s segundo(s) por %2$s.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s minuto(s) por %2$s.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s hora(s) por %2$s.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s día(s) por %2$s.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s semana(s) por %2$s.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s mes(es) por %2$s.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s año(s) por %2$s.`,
  _ = `Pago inicial de %1$s (con un %4$s\xA0% de descuento para primeras compras), renovación automática cada %3$s\xA0s por\xA0%2$s.`,
  _ = `Pago inicial de %1$s (con un %4$s\xA0% de descuento para primeras compras), renovación automática cada %3$s\xA0min por\xA0%2$s.`,
  _ = `Pago inicial de %1$s (con un %4$s\xA0% de descuento para primeras compras), renovación automática cada %3$s\xA0h por\xA0%2$s.`,
  _ = `Pago inicial de %1$s (con un %4$s\xA0% de descuento para primeras compras), renovación automática cada%3$s\xA0día(s) por\xA0%2$s.`,
  _ = `Pago inicial de %1$s (con un %4$s\xA0% de descuento para primeras compras), renovación automática cada %3$s\xA0semana(s) por\xA0%2$s.`,
  _ = `Pago inicial de %1$s (con un %4$s\xA0% de descuento para primeras compras), renovación automática cada %3$s\xA0mes(es) por\xA0%2$s.`,
  _ = `Pago inicial de %1$s (con un %4$s\xA0% de descuento para primeras compras), renovación automática cada %3$s\xA0año(s) por\xA0%2$s.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s segundo(s) por %2$s según lo determinado por tu cuenta del juego.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s minuto(s) por %2$s según lo determinado por tu cuenta del juego.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s hora(s) por %2$s según lo determinado por tu cuenta del juego.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s día(s) por %2$s según lo determinado por tu cuenta del juego.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s semana(s) por %2$s según lo determinado por tu cuenta del juego.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s mes(es) por %2$s según lo determinado por tu cuenta del juego.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s año(s) por %2$s según lo determinado por tu cuenta del juego.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s segundo(s) a %2$s por licencia.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s minuto(s) a %2$s por licencia.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s hora(s) a %2$s por licencia.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s día(s) a %2$s por licencia.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s semana(s) a %2$s por licencia.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s mes(es) a %2$s por licencia.`,
  _ = `Pago inicial de %1$s, renovación automática cada %3$s año(s) a %2$s por licencia.`,
  _ = `Pago inicial de %1$s (con un %4$s\xA0% de descuento para primeras compras), renovación automática cada %3$s\xA0s por\xA0%2$s por licencia.`,
  _ = `Pago inicial de %1$s (con un %4$s\xA0% de descuento para primeras compras), renovación automática cada %3$s\xA0min por\xA0%2$s por licencia.`,
  _ = `Pago inicial de %1$s (con un %4$s\xA0% de descuento para primeras compras), renovación automática cada %3$s\xA0h por\xA0%2$s por licencia.`,
  _ = `Pago inicial de %1$s (con un %4$s\xA0% de descuento para primeras compras), renovación automática cada %3$s\xA0día(s) por\xA0%2$s por licencia.`,
  _ = `Pago inicial de %1$s (con un %4$s\xA0% de descuento para primeras compras), renovación automática cada %3$s\xA0semana(s) por\xA0%2$s por licencia.`,
  _ = `Pago inicial de %1$s (con un %4$s\xA0% de descuento para primeras compras), renovación automática cada %3$s\xA0mes(es) por\xA0%2$s por licencia.`,
  _ = `Pago inicial de %1$s (con un %4$s\xA0% de descuento para primeras compras), renovación automática cada %3$s\xA0año(s) por\xA0%2$s por licencia.`,
  _ = `Tu carro está vacío.`,
  _ = `Algunos de estos artículos ya están marcados como privados y seguirán siendo privados si continúas.`,
  _ = `Al marcar un juego como privado, se ocultará en todas partes fuera de tu biblioteca. Nadie podrá ver que lo tienes, cuándo estás jugando, el tiempo de juego o tu actividad en él.`,
  _ = `Estás viendo una versión nueva del carro de la compra porque participas en la beta del cliente de Steam. <1>Deja comentarios o informa sobre errores</1>.`,
  _ = `Esta nueva versión del carro está en fase de prueba beta. <1>Dejar un comentario o informar de errores</1>`,
  _ = `No puedes programar un regalo con tanta antelación.`,
  _ = `Por favor, introduce una fecha y una hora válidas.`,
  _ = `Ha habido un problema al mostrar este artículo`,
  _ = `Obtendrás %1$s cromo de %2$s con esta compra.`,
  _ = `Obtendrás %1$s cromos de %2$s con esta compra.`,
  _ = `Con las compras que realices durante las rebajas obtendrás cromos de %1$s.`,
  _ = `Recibirás los cromos ganados aunque esta compra sea un regalo.`,
  _ = `Progreso hasta el siguiente cromo`,
  _ = `aproximadamente %1$s por cromo`,
  _ = `Nota: Los artículos precomprados no reúnen los requisitos para recibir cromos de %1$s como recompensa. Los siguientes artículos no otorgan cromos como recompensa:`,
  _ = `Solicitud de compra de %1$s`,
  _ = `Compra para:`,
  _ = `Comprar como regalo: %1$s`,
  _ = `Añadir otra copia de este artículo a tu carro`,
  _ = `Declaración de cumplimiento de la Ley PSTI del Reino\xA0Unido`,
  _ = `Ha habido un problema al actualizar tu carro.`,
  _ = `Código de error: %1$s`,
  _ = `País`,
  _ = `Carro guardado`,
  _ = `Este carro de la compra es antiguo. La última vez que intentaste comprar el contenido de este carro, se produjo un error, así que lo guardamos (incluyendo los descuentos) durante %1$s\xA0horas para que puedas intentar realizar la compra de nuevo.`,
  _ = `Copiar las opciones de regalo de`,
  _ = `<1>Inicia sesión</1> para seleccionar amigos de Steam.`,
  _ = {
    language: _,
    Cart_Remove: _,
    Cart_Add: _,
    Cart_Verify: _,
    Cart_RemoveAll: _,
    Cart_Edit: _,
    Cart_Quantity: _,
    Cart_YourShoppingCart: _,
    Cart_YourShoppingCartLineItems: _,
    Cart_YourShoppingCartLineItems_Plural: _,
    Cart_EstimatedTotal: _,
    Cart_Note_SalesTax: _,
    Cart_PurchaseBtn: _,
    Cart_ContainsGiftCheckbox: _,
    Cart_Bradcrumb_Home: _,
    Cart_LineItemGift_Checkbox: _,
    Cart_IncludesItems: _,
    Cart_IncludesItems_Plural: _,
    Cart_SelectRecipient: _,
    Cart_EnterRecipientEmail: _,
    Cart_ChangeGiftRecipient: _,
    Cart_GiftRecipient_Label: _,
    Cart_GiftRecipientEmail_Label: _,
    Cart_GiftDelivery_Label: _,
    Cart_GiftDelivery_Reset: _,
    Cart_GiftDelivery_Now: _,
    Cart_GiftDelivery_Scheduled: _,
    Cart_GiftDelivery_ScheduleDelivery: _,
    Cart_GiftDelivery_From: `De:`,
    Cart_GiftDelivery_Signature: _,
    Cart_GiftDelivery_AddSignature: _,
    Cart_GiftDelivery_Body: _,
    Cart_GiftDeliveryEmail_Warning1: _,
    Cart_GiftDeliveryEmail_Warning2: _,
    Cart_FamilyGift_Notice: _,
    Cart_GiftRecipientModal_Title: _,
    Cart_EditGiftDelivery: _,
    Cart_GiftRecipientModal_Save: _,
    Cart_GiftRecipientModal_Placeholder: _,
    Cart_GiftRecipientModal_OwnsGameLabel: _,
    Cart_GiftRecipientModal_OnWishlist: _,
    Cart_GiftRecipientModal_PartialOwnsLabel: _,
    Cart_GiftRecipientModal_PartialWishlistLabel: _,
    Cart_GiftOptions: _,
    Cart_GiftRecipientModal_IssueLoading: _,
    Cart_ContinueButton_Payment: _,
    Cart_ContinueButton_Gifts: _,
    Cart_ContinueButton_Login: _,
    Cart_DeclinePurchaseRequest: _,
    Cart_LineItemOptions_Myself: _,
    Cart_LineItemOptions_Gift: _,
    Cart_LineItemOptions_GiftForPersona: _,
    Cart_LineItemOptions_Privately: _,
    Cart_CountWidget: _,
    Cart_AddedToYourCart: _,
    Cart_UpdatedYourCart: _,
    Cart_ContinueShopping: _,
    Cart_ComingSoon: _,
    Cart_ViewMyCart: _,
    Cart_RequestPurchase: _,
    Cart_RequestPurchaseExplanation: _,
    Cart_RequestPurchaseNonGiftableItems: _,
    Cart_CouponModify_Change: _,
    Cart_CouponModify_Add: _,
    Cart_CouponAvailability: _,
    Cart_CouponAvailability_Plural: _,
    Cart_Coupons_Applied: _,
    Cart_Coupons_InUse: _,
    Cart_SelectCouponToApply: _,
    Cart_ShippingEstimate_DeliveryDate: _,
    Cart_ShippingEstimate_Range: _,
    Cart_ShippingEstimate_Delayed: _,
    Cart_ShippingEstimate_Standard: _,
    Cart_FooterNoticeHeader_MustFix: _,
    Cart_FooterNoticeHeader_Warning: _,
    Cart_CartLevelErrorNotice: _,
    Cart_CartLevelErrorMultiple: _,
    Cart_CartLevelErrorFormat: _,
    Cart_Error_AlreadyOwned_FootNote: _,
    Cart_Error_AlreadyOwned_LineItem_Game: _,
    Cart_Error_AlreadyOwned_LineItem: _,
    Cart_Error_AlreadyOwned_GiftLineItem_Game: _,
    Cart_Error_AlreadyOwned_GiftLineItem: _,
    Cart_Error_AlreadyOwned_GiftFootNote: _,
    Cart_Error_DuplicateApps_FootNote: _,
    Cart_Error_DuplicateApps_LineItem: _,
    Cart_Error_UnavailableCountry_FootNote: _,
    Cart_Error_UnavailableCountry_LineItem: _,
    Cart_Error_AdultContentRestricted_FootNote: _,
    Cart_Error_AdultContentRestricted_LineItem: _,
    Cart_Error_MasterSubscription_FootNote: _,
    Cart_Error_MasterSubscription_LineItem: _,
    Cart_Error_CouponIsExclusivePromo: _,
    Cart_Error_CouponIsInvalid: _,
    Cart_Error_CouponIsInvalidForItem: _,
    Cart_Error_TooManyInCart: _,
    Cart_Error_CommercialLicenseRestricted_FootNote: _,
    Cart_Error_CommercialLicenseRestricted_LineItem: _,
    Cart_Error_GiftRecipientInvalid: _,
    Cart_Error_MissingMustOwnApps_LineItem: _,
    Cart_Error_MissingMustOwnApps_GiftLineItem: _,
    Cart_Error_MissingMustOwnApps_FootNote: _,
    Cart_Error_MissingMustOwnApps_FootNoteGift: _,
    Cart_Error_ExistingBillingAgreement: _,
    Cart_Error_ExistingBillingAgreement_FootNote: _,
    Cart_Warning_AlreadyOwned_LineItem: _,
    Cart_Warning_ExtraCopies_LineItem: _,
    Cart_Warning_PriceChange_FootNote: _,
    Cart_Warning_PriceChange_LineItem: _,
    Cart_Warning_NoRefund_LineItem: _,
    Cart_Warning_RecipientHigherPrice: _,
    Cart_Warning_AvailableAtALowerPrice: _,
    Cart_Warning_GiftToNonFriend: _,
    Cart_Warning_GiftToNonFriend_Named: _,
    Cart_Warning_GiftToAccount_LoggedOut_Actionable: _,
    Cart_GifteeHint_Wishlist: _,
    PackageIncludesSubscriptionBySecond: _,
    PackageIncludesSubscriptionByMinute: _,
    PackageIncludesSubscriptionByHour: _,
    PackageIncludesSubscriptionByDay: _,
    PackageIncludesSubscriptionByWeek: _,
    PackageIncludesSubscriptionByMonth: _,
    PackageIncludesSubscriptionByYear: _,
    MultiLicenseIncludesSubscriptionBySecond: _,
    MultiLicenseIncludesSubscriptionByMinute: _,
    MultiLicenseIncludesSubscriptionByHour: _,
    MultiLicenseIncludesSubscriptionByDay: _,
    MultiLicenseIncludesSubscriptionByWeek: _,
    MultiLicenseIncludesSubscriptionByMonth: _,
    MultiLicenseeIncludesSubscriptionByYear: _,
    GameBillingPackageIncludesSubscriptionBySecond: _,
    GameBillingPackageIncludesSubscriptionByMinute: _,
    GameBillingPackageIncludesSubscriptionByHour: _,
    GameBillingPackageIncludesSubscriptionByDay: _,
    GameBillingPackageIncludesSubscriptionByWeek: _,
    GameBillingPackageIncludesSubscriptionByMonth: _,
    GameBillingPackageIncludesSubscriptionByYear: _,
    MicroTxnSubscriptionCostBySecond: _,
    MicroTxnSubscriptionCostByMinute: _,
    MicroTxnSubscriptionCostByHour: _,
    MicroTxnSubscriptionCostByDay: _,
    MicroTxnSubscriptionCostByWeek: _,
    MicroTxnSubscriptionCostByMonth: _,
    MicroTxnSubscriptionCostByYear: _,
    GameBillingAuthorizeSubscriptionBySecond: _,
    GameBillingAuthorizeSubscriptionByMinute: _,
    GameBillingAuthorizeSubscriptionByHour: _,
    GameBillingAuthorizeSubscriptionByDay: _,
    GameBillingAuthorizeSubscriptionByWeek: _,
    GameBillingAuthorizeSubscriptionByMonth: _,
    GameBillingAuthorizeSubscriptionByYear: _,
    PackageCostIncludesSubscriptionBySecond: _,
    PackageCostIncludesSubscriptionByMinute: _,
    PackageCostIncludesSubscriptionByHour: _,
    PackageCostIncludesSubscriptionByDay: _,
    PackageCostIncludesSubscriptionByWeek: _,
    PackageCostIncludesSubscriptionByMonth: _,
    PackageCostIncludesSubscriptionByYear: _,
    PackageWithDiscountCostIncludesSubscriptionBySecond: _,
    PackageWithDiscountCostIncludesSubscriptionByMinute: _,
    PackageWithDiscountCostIncludesSubscriptionByHour: _,
    PackageWithDiscountCostIncludesSubscriptionByDay: _,
    PackageWithDiscountCostIncludesSubscriptionByWeek: _,
    PackageWithDiscountCostIncludesSubscriptionByMonth: _,
    PackageWithDiscountCostIncludesSubscriptionByYear: _,
    GameBillingPackageCostIncludesSubscriptionBySecond: _,
    GameBillingPackageCostIncludesSubscriptionByMinute: _,
    GameBillingPackageCostIncludesSubscriptionByHour: _,
    GameBillingPackageCostIncludesSubscriptionByDay: _,
    GameBillingPackageCostIncludesSubscriptionByWeek: _,
    GameBillingPackageCostIncludesSubscriptionByMonth: _,
    GameBillingPackageCostIncludesSubscriptionByYear: _,
    MultiLicenseCostIncludesSubscriptionBySecond: _,
    MultiLicenseCostIncludesSubscriptionByMinute: _,
    MultiLicenseCostIncludesSubscriptionByHour: _,
    MultiLicenseCostIncludesSubscriptionByDay: _,
    MultiLicenseCostIncludesSubscriptionByWeek: _,
    MultiLicenseCostIncludesSubscriptionByMonth: _,
    MultiLicenseCostIncludesSubscriptionByYear: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionBySecond: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMinute: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByHour: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByDay: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByWeek: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMonth: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByYear: _,
    Cart_Empty: _,
    Cart_Notice_SomeAppsPrivate: _,
    Cart_LineItemOptions_PrivateTooltip: _,
    Cart_BetaNotice: _,
    Cart_GenericBetaNotice: _,
    Cart_GiftScheduleError_TooFar: _,
    Cart_GiftScheduleError_InvalidDate: _,
    Cart_LineItem_ErrorBoundary: _,
    Cart_SaleCardDrops_EarnedMessage: _,
    Cart_SaleCardDrops_EarnedMessage_Plural: _,
    Cart_SaleCardDrops_Explanation: _,
    Cart_SaleCardDrops_Explanation_Gifts: _,
    Cart_SaleCardDrops_ProgressLabel: _,
    Cart_SaleCardDrops_CardCost: _,
    Cart_SaleCardDrops_PrepurchaseIneligible: _,
    Cart_PurchaseRequestTitle: _,
    Cart_PurchaseFor_Label: _,
    Cart_GiftForNotice: _,
    Cart_LineItem_Add_Tooltip: _,
    Cart_LineItem_Hardware_Compliance_Label: _,
    Cart_ErrorUpdating: _,
    Cart_ErrorCode: _,
    Cart_UserCountrySelector: _,
    Cart_Replay_SavedCart: _,
    Cart_Replay_Instructions: _,
    Cart_Gifting_CopyGiftOptionsFrom: _,
    Cart_Gifting_SignInToSelectFriends: _,
  };
export {
  _ as Cart_Add,
  _ as Cart_AddedToYourCart,
  _ as Cart_BetaNotice,
  _ as Cart_Bradcrumb_Home,
  _ as Cart_CartLevelErrorFormat,
  _ as Cart_CartLevelErrorMultiple,
  _ as Cart_CartLevelErrorNotice,
  _ as Cart_ChangeGiftRecipient,
  _ as Cart_ComingSoon,
  _ as Cart_ContainsGiftCheckbox,
  _ as Cart_ContinueButton_Gifts,
  _ as Cart_ContinueButton_Login,
  _ as Cart_ContinueButton_Payment,
  _ as Cart_ContinueShopping,
  _ as Cart_CountWidget,
  _ as Cart_CouponAvailability,
  _ as Cart_CouponAvailability_Plural,
  _ as Cart_CouponModify_Add,
  _ as Cart_CouponModify_Change,
  _ as Cart_Coupons_Applied,
  _ as Cart_Coupons_InUse,
  _ as Cart_DeclinePurchaseRequest,
  _ as Cart_Edit,
  _ as Cart_EditGiftDelivery,
  _ as Cart_Empty,
  _ as Cart_EnterRecipientEmail,
  _ as Cart_ErrorCode,
  _ as Cart_ErrorUpdating,
  _ as Cart_Error_AdultContentRestricted_FootNote,
  _ as Cart_Error_AdultContentRestricted_LineItem,
  _ as Cart_Error_AlreadyOwned_FootNote,
  _ as Cart_Error_AlreadyOwned_GiftFootNote,
  _ as Cart_Error_AlreadyOwned_GiftLineItem,
  _ as Cart_Error_AlreadyOwned_GiftLineItem_Game,
  _ as Cart_Error_AlreadyOwned_LineItem,
  _ as Cart_Error_AlreadyOwned_LineItem_Game,
  _ as Cart_Error_CommercialLicenseRestricted_FootNote,
  _ as Cart_Error_CommercialLicenseRestricted_LineItem,
  _ as Cart_Error_CouponIsExclusivePromo,
  _ as Cart_Error_CouponIsInvalid,
  _ as Cart_Error_CouponIsInvalidForItem,
  _ as Cart_Error_DuplicateApps_FootNote,
  _ as Cart_Error_DuplicateApps_LineItem,
  _ as Cart_Error_ExistingBillingAgreement,
  _ as Cart_Error_ExistingBillingAgreement_FootNote,
  _ as Cart_Error_GiftRecipientInvalid,
  _ as Cart_Error_MasterSubscription_FootNote,
  _ as Cart_Error_MasterSubscription_LineItem,
  _ as Cart_Error_MissingMustOwnApps_FootNote,
  _ as Cart_Error_MissingMustOwnApps_FootNoteGift,
  _ as Cart_Error_MissingMustOwnApps_GiftLineItem,
  _ as Cart_Error_MissingMustOwnApps_LineItem,
  _ as Cart_Error_TooManyInCart,
  _ as Cart_Error_UnavailableCountry_FootNote,
  _ as Cart_Error_UnavailableCountry_LineItem,
  _ as Cart_EstimatedTotal,
  _ as Cart_FamilyGift_Notice,
  _ as Cart_FooterNoticeHeader_MustFix,
  _ as Cart_FooterNoticeHeader_Warning,
  _ as Cart_GenericBetaNotice,
  _ as Cart_GiftDeliveryEmail_Warning1,
  _ as Cart_GiftDeliveryEmail_Warning2,
  _ as Cart_GiftDelivery_AddSignature,
  _ as Cart_GiftDelivery_Body,
  _ as Cart_GiftDelivery_From,
  _ as Cart_GiftDelivery_Label,
  _ as Cart_GiftDelivery_Now,
  _ as Cart_GiftDelivery_Reset,
  _ as Cart_GiftDelivery_ScheduleDelivery,
  _ as Cart_GiftDelivery_Scheduled,
  _ as Cart_GiftDelivery_Signature,
  _ as Cart_GiftForNotice,
  _ as Cart_GiftOptions,
  _ as Cart_GiftRecipientEmail_Label,
  _ as Cart_GiftRecipientModal_IssueLoading,
  _ as Cart_GiftRecipientModal_OnWishlist,
  _ as Cart_GiftRecipientModal_OwnsGameLabel,
  _ as Cart_GiftRecipientModal_PartialOwnsLabel,
  _ as Cart_GiftRecipientModal_PartialWishlistLabel,
  _ as Cart_GiftRecipientModal_Placeholder,
  _ as Cart_GiftRecipientModal_Save,
  _ as Cart_GiftRecipientModal_Title,
  _ as Cart_GiftRecipient_Label,
  _ as Cart_GiftScheduleError_InvalidDate,
  _ as Cart_GiftScheduleError_TooFar,
  _ as Cart_GifteeHint_Wishlist,
  _ as Cart_Gifting_CopyGiftOptionsFrom,
  _ as Cart_Gifting_SignInToSelectFriends,
  _ as Cart_IncludesItems,
  _ as Cart_IncludesItems_Plural,
  _ as Cart_LineItemGift_Checkbox,
  _ as Cart_LineItemOptions_Gift,
  _ as Cart_LineItemOptions_GiftForPersona,
  _ as Cart_LineItemOptions_Myself,
  _ as Cart_LineItemOptions_PrivateTooltip,
  _ as Cart_LineItemOptions_Privately,
  _ as Cart_LineItem_Add_Tooltip,
  _ as Cart_LineItem_ErrorBoundary,
  _ as Cart_LineItem_Hardware_Compliance_Label,
  _ as Cart_Note_SalesTax,
  _ as Cart_Notice_SomeAppsPrivate,
  _ as Cart_PurchaseBtn,
  _ as Cart_PurchaseFor_Label,
  _ as Cart_PurchaseRequestTitle,
  _ as Cart_Quantity,
  _ as Cart_Remove,
  _ as Cart_RemoveAll,
  _ as Cart_Replay_Instructions,
  _ as Cart_Replay_SavedCart,
  _ as Cart_RequestPurchase,
  _ as Cart_RequestPurchaseExplanation,
  _ as Cart_RequestPurchaseNonGiftableItems,
  _ as Cart_SaleCardDrops_CardCost,
  _ as Cart_SaleCardDrops_EarnedMessage,
  _ as Cart_SaleCardDrops_EarnedMessage_Plural,
  _ as Cart_SaleCardDrops_Explanation,
  _ as Cart_SaleCardDrops_Explanation_Gifts,
  _ as Cart_SaleCardDrops_PrepurchaseIneligible,
  _ as Cart_SaleCardDrops_ProgressLabel,
  _ as Cart_SelectCouponToApply,
  _ as Cart_SelectRecipient,
  _ as Cart_ShippingEstimate_Delayed,
  _ as Cart_ShippingEstimate_DeliveryDate,
  _ as Cart_ShippingEstimate_Range,
  _ as Cart_ShippingEstimate_Standard,
  _ as Cart_UpdatedYourCart,
  _ as Cart_UserCountrySelector,
  _ as Cart_Verify,
  _ as Cart_ViewMyCart,
  _ as Cart_Warning_AlreadyOwned_LineItem,
  _ as Cart_Warning_AvailableAtALowerPrice,
  _ as Cart_Warning_ExtraCopies_LineItem,
  _ as Cart_Warning_GiftToAccount_LoggedOut_Actionable,
  _ as Cart_Warning_GiftToNonFriend,
  _ as Cart_Warning_GiftToNonFriend_Named,
  _ as Cart_Warning_NoRefund_LineItem,
  _ as Cart_Warning_PriceChange_FootNote,
  _ as Cart_Warning_PriceChange_LineItem,
  _ as Cart_Warning_RecipientHigherPrice,
  _ as Cart_YourShoppingCart,
  _ as Cart_YourShoppingCartLineItems,
  _ as Cart_YourShoppingCartLineItems_Plural,
  _ as GameBillingAuthorizeSubscriptionByDay,
  _ as GameBillingAuthorizeSubscriptionByHour,
  _ as GameBillingAuthorizeSubscriptionByMinute,
  _ as GameBillingAuthorizeSubscriptionByMonth,
  _ as GameBillingAuthorizeSubscriptionBySecond,
  _ as GameBillingAuthorizeSubscriptionByWeek,
  _ as GameBillingAuthorizeSubscriptionByYear,
  _ as GameBillingPackageCostIncludesSubscriptionByDay,
  _ as GameBillingPackageCostIncludesSubscriptionByHour,
  _ as GameBillingPackageCostIncludesSubscriptionByMinute,
  _ as GameBillingPackageCostIncludesSubscriptionByMonth,
  _ as GameBillingPackageCostIncludesSubscriptionBySecond,
  _ as GameBillingPackageCostIncludesSubscriptionByWeek,
  _ as GameBillingPackageCostIncludesSubscriptionByYear,
  _ as GameBillingPackageIncludesSubscriptionByDay,
  _ as GameBillingPackageIncludesSubscriptionByHour,
  _ as GameBillingPackageIncludesSubscriptionByMinute,
  _ as GameBillingPackageIncludesSubscriptionByMonth,
  _ as GameBillingPackageIncludesSubscriptionBySecond,
  _ as GameBillingPackageIncludesSubscriptionByWeek,
  _ as GameBillingPackageIncludesSubscriptionByYear,
  _ as MicroTxnSubscriptionCostByDay,
  _ as MicroTxnSubscriptionCostByHour,
  _ as MicroTxnSubscriptionCostByMinute,
  _ as MicroTxnSubscriptionCostByMonth,
  _ as MicroTxnSubscriptionCostBySecond,
  _ as MicroTxnSubscriptionCostByWeek,
  _ as MicroTxnSubscriptionCostByYear,
  _ as MultiLicenseCostIncludesSubscriptionByDay,
  _ as MultiLicenseCostIncludesSubscriptionByHour,
  _ as MultiLicenseCostIncludesSubscriptionByMinute,
  _ as MultiLicenseCostIncludesSubscriptionByMonth,
  _ as MultiLicenseCostIncludesSubscriptionBySecond,
  _ as MultiLicenseCostIncludesSubscriptionByWeek,
  _ as MultiLicenseCostIncludesSubscriptionByYear,
  _ as MultiLicenseIncludesSubscriptionByDay,
  _ as MultiLicenseIncludesSubscriptionByHour,
  _ as MultiLicenseIncludesSubscriptionByMinute,
  _ as MultiLicenseIncludesSubscriptionByMonth,
  _ as MultiLicenseIncludesSubscriptionBySecond,
  _ as MultiLicenseIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByDay,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByHour,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMinute,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMonth,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionBySecond,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByYear,
  _ as MultiLicenseeIncludesSubscriptionByYear,
  _ as PackageCostIncludesSubscriptionByDay,
  _ as PackageCostIncludesSubscriptionByHour,
  _ as PackageCostIncludesSubscriptionByMinute,
  _ as PackageCostIncludesSubscriptionByMonth,
  _ as PackageCostIncludesSubscriptionBySecond,
  _ as PackageCostIncludesSubscriptionByWeek,
  _ as PackageCostIncludesSubscriptionByYear,
  _ as PackageIncludesSubscriptionByDay,
  _ as PackageIncludesSubscriptionByHour,
  _ as PackageIncludesSubscriptionByMinute,
  _ as PackageIncludesSubscriptionByMonth,
  _ as PackageIncludesSubscriptionBySecond,
  _ as PackageIncludesSubscriptionByWeek,
  _ as PackageIncludesSubscriptionByYear,
  _ as PackageWithDiscountCostIncludesSubscriptionByDay,
  _ as PackageWithDiscountCostIncludesSubscriptionByHour,
  _ as PackageWithDiscountCostIncludesSubscriptionByMinute,
  _ as PackageWithDiscountCostIncludesSubscriptionByMonth,
  _ as PackageWithDiscountCostIncludesSubscriptionBySecond,
  _ as PackageWithDiscountCostIncludesSubscriptionByWeek,
  _ as PackageWithDiscountCostIncludesSubscriptionByYear,
  _ as default,
  _ as language,
};
