var _ = `korean`,
  _ = `Steam 홈페이지 링크`,
  _ = `Steam 설치`,
  _ = `로그인`,
  _ = `로그인`,
  _ = `프로필 보기`,
  _ = `계정 정보`,
  _ = `계정 정보: <1>%1$s</1>`,
  _ = `상점 환경 설정`,
  _ = `언어 변경`,
  _ = `언어`,
  _ = `계정에서 로그아웃...`,
  _ = `지갑 보기`,
  _ = `지갑 보기: <1>%1$s</1>`,
  _ = `새 기능`,
  _ = `장바구니(%1$s)`,
  _ = `지갑(%1$s)`,
  _ = `© Valve Corporation. All rights reserved. All trademarks are property of their respective owners in the US and other countries.`,
  _ = `개인정보 처리방침`,
  _ = `법적 고지`,
  _ = `Steam 이용 약관`,
  _ = `환불`,
  _ = `PC 웹사이트 보기`,
  _ = `모바일 웹사이트 보기`,
  _ = `Steam 모바일 앱 다운로드`,
  _ = `사용자 변경`,
  _ = `알림`,
  _ = `내비게이션`,
  _ = `베타`,
  _ = {
    language: _,
    Aria_Steam_Home_Link: _,
    global_menu_install_steam: _,
    global_menu_login: _,
    global_menu_login_caps: _,
    global_menu_view_profile: _,
    global_menu_account_details: _,
    global_menu_account_details_accountname: _,
    global_menu_account_preferences: _,
    global_menu_change_language: _,
    global_menu_language: _,
    global_menu_sign_out: _,
    global_menu_view_wallet: _,
    global_menu_view_wallet_with_amount: _,
    m_ext_new: _,
    Cart_CountWidget: _,
    responsive_menu_wallet_balance: _,
    responsive_footer_copyright: _,
    Common_Footer_PrivacyPolicy: _,
    Common_Footer_Legal: _,
    Common_Footer_SSA: _,
    Common_Footer_Refunds: _,
    global_menu_view_desktop_website: _,
    global_menu_view_mobile_website: _,
    global_menu_getmobileapp: _,
    global_menu_change_user: _,
    SuperNav_Notifications: _,
    Aria_Navigation: _,
    beta_tag: _,
  };
export {
  _ as Aria_Navigation,
  _ as Aria_Steam_Home_Link,
  _ as Cart_CountWidget,
  _ as Common_Footer_Legal,
  _ as Common_Footer_PrivacyPolicy,
  _ as Common_Footer_Refunds,
  _ as Common_Footer_SSA,
  _ as SuperNav_Notifications,
  _ as beta_tag,
  _ as default,
  _ as global_menu_account_details,
  _ as global_menu_account_details_accountname,
  _ as global_menu_account_preferences,
  _ as global_menu_change_language,
  _ as global_menu_change_user,
  _ as global_menu_getmobileapp,
  _ as global_menu_install_steam,
  _ as global_menu_language,
  _ as global_menu_login,
  _ as global_menu_login_caps,
  _ as global_menu_sign_out,
  _ as global_menu_view_desktop_website,
  _ as global_menu_view_mobile_website,
  _ as global_menu_view_profile,
  _ as global_menu_view_wallet,
  _ as global_menu_view_wallet_with_amount,
  _ as language,
  _ as m_ext_new,
  _ as responsive_footer_copyright,
  _ as responsive_menu_wallet_balance,
};
