var _ = `brazilian`,
  _ = `Remover`,
  _ = `Adicionar`,
  _ = `Verificar idade`,
  _ = `Remover todos os itens`,
  _ = `Editar`,
  _ = `Qtd.: %1$s`,
  _ = `Carrinho de compras`,
  _ = `Carrinho de compras (%1$s item)`,
  _ = `Carrinho de compras (%1$s itens)`,
  _ = `Total estimado`,
  _ = `O imposto sobre vendas será calculado durante a finalização do pedido quando aplicável`,
  _ = `Comprar`,
  _ = `Esta compra contém um presente`,
  _ = `Página inicial`,
  _ = `Isto é um presente?`,
  _ = `Inclui %1$s item`,
  _ = `Inclui %1$s itens`,
  _ = `Selecionar destinatário`,
  _ = `Informar e-mail`,
  _ = `Editar destinatário...`,
  _ = `Destinatário do presente:`,
  _ = `E-mail do destinatário do presente:`,
  _ = `Entrega:`,
  _ = `Redefinir`,
  _ = `Assim que possível (por e-mail e cliente Steam)`,
  _ = `Agendado:`,
  _ = `Agendar entrega`,
  _ = `De:`,
  _ = `Sua assinatura:`,
  _ = `Adicionar assinatura personalizada`,
  _ = `Mensagem do presente (%1$s/160 caracteres):`,
  _ = `Presentes enviados por e-mail serão reembolsados automaticamente após 30 dias se não forem adicionados a uma conta Steam.`,
  _ = `Presentes enviados por e-mail só podem ser aceitos por contas Steam na mesma região do comprador (%1$s).`,
  _ = `Os presentes enviados às crianças da Família Steam serão adicionados automaticamente à respectiva conta e aos jogos permitidos.`,
  _ = `Escolher destinatário`,
  _ = `Editar forma de entrega`,
  _ = `Salvar`,
  _ = `Buscar pelo nome...`,
  _ = `Já possui o item`,
  _ = `Na lista de desejos`,
  _ = `Já possui %1$s`,
  _ = `%1$s na lista de desejos`,
  _ = `Opções do presente`,
  _ = `Houve um problema ao carregar os possíveis destinatários do presente. Tente novamente mais tarde.`,
  _ = `Continuar para o pagamento`,
  _ = `Continuar para as opções de presente`,
  _ = `Inicie a sessão para comprar`,
  _ = `Recusar pedido`,
  _ = `Para a minha conta`,
  _ = `Para presente`,
  _ = `Isto é um presente para %1$s`,
  _ = `Para a minha conta (privado)`,
  _ = `Carrinho (%1$s)`,
  _ = `Adicionado ao carrinho!`,
  _ = `Carrinho atualizado!`,
  _ = `Continuar comprando`,
  _ = `Disponível em %1$s`,
  _ = `Ver o meu carrinho (%1$s)`,
  _ = `Pedir para comprar`,
  _ = `Os adultos da sua Família Steam serão notificados do seu pedido de compra.`,
  _ = `Não foi possível enviar o pedido de compra porque nem todos os itens no carrinho são presenteáveis.`,
  _ = `Alterar ou remover cupom`,
  _ = `Aplicar cupom`,
  _ = `Você tem um cupom disponível para este item`,
  _ = `Você tem %1$s cupons disponíveis para este item`,
  _ = `Atualmente aplicado`,
  _ = `Atualmente aplicado a outro item`,
  _ = `Escolha um cupom para aplicar a %1$s`,
  _ = `Data estimada de entrega: %1$s`,
  _ = `%1$s a %2$s dias úteis`,
  _ = `Data estimada de entrega: 6 a 10 dias úteis`,
  _ = `Data estimada de entrega: 3 a 5 dias úteis`,
  _ = `Antes de prosseguir para o pagamento:`,
  _ = `Avisos:`,
  _ = `Ação necessária antes de prosseguir para o pagamento.`,
  _ = `Avisos:`,
  _ = `Aviso: %1$s`,
  _ = `A sua conta já possui alguns dos itens acima. Você pode comprá-los para presente ou ajustar o conteúdo do seu carrinho para continuar.`,
  _ = `Você já tem este jogo`,
  _ = `Você já tem tudo deste pacote`,
  _ = `O destinatário já possui esse jogo`,
  _ = `O destinatário já possui tudo do conjunto`,
  _ = `O destinatário já possui alguns dos produtos acima, não sendo possível comprá-los novamente. Escolha outro destinatário ou ajuste o conteúdo do carrinho para continuar.`,
  _ = `Parece que há pacotes no carrinho que se sobrepõem. Remova os pacotes redundantes para finalizar o pedido.`,
  _ = `Já adicionado ao carrinho: `,
  _ = `O carrinho contém um pacote indisponível no seu país. Remova-o para finalizar o pedido.`,
  _ = `Indisponível no seu país`,
  _ = `A Valve é obrigada a verificar que você tem 18 anos ou mais antes de permitir a compra de conteúdo sexual para adultos.`,
  _ = `Indisponível para compra até que você verifique a sua idade.`,
  _ = `Há conteúdos no carrinho que também estão disponíveis por uma das suas assinaturas ativas.`,
  _ = `Disponível pela sua assinatura de:`,
  _ = `Este cupom não é cumulativo com outros descontos.`,
  _ = `Este cupom é inválido ou está vencido.`,
  _ = `Este cupom não pode ser aplicado a esse item.`,
  _ = `Você excedeu a quantidade máxima permitida de unidades deste item no carrinho.`,
  _ = `O seu carrinho contém um item indisponível para compra.`,
  _ = `Indisponível para compra`,
  _ = `O destinatário selecionado não pode receber este presente comprado na sua região.`,
  _ = `A compra deste item exige que você tenha os seguintes itens:`,
  _ = `Este item exige que o destinatário tenha os seguintes itens:`,
  _ = `A sua conta não possui alguns dos itens necessários para comprar os itens no seu carrinho. Você pode adicionar os itens faltantes ou ajustar o conteúdo do seu carrinho para continuar.`,
  _ = `O destinatário do presente não possui alguns dos itens necessários para finalizar a compra dos itens no seu carrinho. Você pode adicionar os itens faltantes ou ajustar o conteúdo do seu carrinho para continuar.`,
  _ = `Você já tem uma assinatura desse item.`,
  _ = `A sua conta já tem uma assinatura para alguns dos itens acima. Consulte as suas assinaturas na página de detalhes da conta.`,
  _ = `Caso esteja comprando para a sua conta, você não receberá uma cópia extra de:`,
  _ = `Caso esteja comprando para a sua conta, você receberá uma cópia extra presenteável de:`,
  _ = `um ou mais itens abaixo sofreram uma alteração no preço desde a adição ao carrinho.`,
  _ = `O preço deste item sofreu alteração`,
  _ = `Este item não pode ser reembolsado por conter conteúdo consumível.`,
  _ = `O preço do presente é maior na região do destinatário selecionado. O preço deste item foi atualizado para corresponder ao preço da região e permitir que presenteie o destinatário.`,
  _ = `Este item está disponível a um preço mais baixo como parte de %1$s.`,
  _ = `O destinatário do presente NÃO está na sua lista de amigos do Steam.`,
  _ = `AVISO: %1$s NÃO está na sua lista de amigos do Steam.`,
  _ = `Caso esteja enviando um presente para alguém na sua lista de amigos do Steam, <1>inicie a sessão</1> para verificar se o destinatário está na lista de amigos.`,
  _ = `Você viu a lista de desejos de %1$s recentemente. Deseja presentear essa pessoa com estes itens?`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s segundo(s).`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s minuto(s).`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s hora(s).`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s dia(s).`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s semana(s).`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s mês(es).`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s ano(s).`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s segundo(s) por licença.`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s minuto(s) por licença.`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s hora(s) por licença.`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s dia(s) por licença.`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s semana(s) por licença.`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s mês(es) por licença.`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s ano(s) por licença.`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s segundo(s) ou como determinado pela sua conta no jogo.`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s minuto(s) ou como determinado pela sua conta no jogo.`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s hora(s) ou como determinado pela sua conta no jogo.`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s dia(s) ou como determinado pela sua conta no jogo.`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s semana(s) ou como determinado pela sua conta no jogo.`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s mês(es) ou como determinado pela sua conta no jogo.`,
  _ = `Assinatura no valor de %1$s cobrada a cada %2$s ano(s) ou como determinado pela sua conta no jogo.`,
  _ = `%1$s serão cobrados ao finalizar o pedido.<br/>Você aceita a cobrança automática de %2$s a cada %3$s segundo(s).`,
  _ = `%1$s serão cobrados ao finalizar o pedido.<br/>Você aceita a cobrança automática de %2$s a cada %3$s minuto(s).`,
  _ = `%1$s serão cobrados ao finalizar o pedido.<br/>Você aceita a cobrança automática de %2$s a cada %3$s hora(s).`,
  _ = `%1$s serão cobrados ao finalizar o pedido.<br/>Você aceita a cobrança automática de %2$s a cada %3$s dia(s).`,
  _ = `%1$s serão cobrados ao finalizar o pedido.<br/>Você aceita a cobrança automática de %2$s a cada %3$s semana(s).`,
  _ = `%1$s serão cobrados ao finalizar o pedido.<br/>Você aceita a cobrança automática de %2$s a cada %3$s mês(es).`,
  _ = `%1$s serão cobrados ao finalizar o pedido.<br/>Você aceita a cobrança automática de %2$s a cada %3$s ano(s).`,
  _ = `%1$s serão cobrados ao finalizar o pedido.<br/>Você autoriza este jogo a realizar cobranças adicionais de até %2$s a cada %3$s segundo(s).`,
  _ = `%1$s serão cobrados ao finalizar o pedido.<br/>Você autoriza este jogo a realizar cobranças adicionais de até %2$s a cada %3$s minuto(s).`,
  _ = `%1$s serão cobrados ao finalizar o pedido.<br/>Você autoriza este jogo a realizar cobranças adicionais de até %2$s a cada %3$s hora(s).`,
  _ = `%1$s serão cobrados ao finalizar o pedido.<br/>Você autoriza este jogo a realizar cobranças adicionais de até %2$s a cada %3$s dia(s).`,
  _ = `%1$s serão cobrados ao finalizar o pedido.<br/>Você autoriza este jogo a realizar cobranças adicionais de até %2$s a cada %3$s semana(s).`,
  _ = `%1$s serão cobrados ao finalizar o pedido.<br/>Você autoriza este jogo a realizar cobranças adicionais de até %2$s a cada %3$s mês(es).`,
  _ = `%1$s serão cobrados ao finalizar o pedido.<br/>Você autoriza este jogo a realizar cobranças adicionais de até %2$s a cada %3$s ano(s).`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s segundo(s).`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s minuto(s).`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s hora(s).`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s dia(s).`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s semana(s).`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s mês(es).`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s ano(s).`,
  _ = `%1$s ao finalizar o pedido (%4$s% de desconto para a primeira compra), com assinatura no valor de %2$s renovada automaticamente a cada %3$s segundo(s).`,
  _ = `%1$s ao finalizar o pedido (%4$s% de desconto para a primeira compra), com assinatura no valor de %2$s renovada automaticamente a cada %3$s minuto(s).`,
  _ = `%1$s ao finalizar o pedido (%4$s% de desconto para a primeira compra), com assinatura no valor de %2$s renovada automaticamente a cada %3$s hora(s).`,
  _ = `%1$s ao finalizar o pedido (%4$s% de desconto para a primeira compra), com assinatura no valor de %2$s renovada automaticamente a cada %3$s dia(s).`,
  _ = `%1$s ao finalizar o pedido (%4$s% de desconto para a primeira compra), com assinatura no valor de %2$s renovada automaticamente a cada %3$s semana(s).`,
  _ = `%1$s ao finalizar o pedido (%4$s% de desconto para a primeira compra), com assinatura no valor de %2$s renovada automaticamente a cada %3$s mês(es).`,
  _ = `%1$s ao finalizar o pedido (%4$s% de desconto para a primeira compra), com assinatura no valor de %2$s renovada automaticamente a cada %3$s ano(s).`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s segundo(s) como determinado pela sua conta no jogo.`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s minuto(s) como determinado pela sua conta no jogo.`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s hora(s) como determinado pela sua conta no jogo.`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s dia(s) como determinado pela sua conta no jogo.`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s semana(s) como determinado pela sua conta no jogo.`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s mês(es) como determinado pela sua conta no jogo.`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s ano(s) como determinado pela sua conta no jogo.`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s segundo(s) por licença.`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s minuto(s) por licença.`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s hora(s) por licença.`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s dia(s) por licença.`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s semana(s) por licença.`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s mês(es) por licença.`,
  _ = `%1$s ao finalizar o pedido, com assinatura no valor de %2$s renovada automaticamente a cada %3$s ano(s) por licença.`,
  _ = `%1$s ao finalizar o pedido (%4$s% de desconto para a primeira compra), com assinatura no valor de %2$s (por licença) renovada automaticamente a cada %3$s segundo(s).`,
  _ = `%1$s ao finalizar o pedido (%4$s% de desconto para a primeira compra), com assinatura no valor de %2$s (por licença) renovada automaticamente a cada %3$s minuto(s).`,
  _ = `%1$s ao finalizar o pedido (%4$s% de desconto para a primeira compra), com assinatura no valor de %2$s (por licença) renovada automaticamente a cada %3$s hora(s).`,
  _ = `%1$s ao finalizar o pedido (%4$s% de desconto para a primeira compra), com assinatura no valor de %2$s (por licença) renovada automaticamente a cada %3$s dia(s).`,
  _ = `%1$s ao finalizar o pedido (%4$s% de desconto para a primeira compra), com assinatura no valor de %2$s (por licença) renovada automaticamente a cada %3$s semana(s).`,
  _ = `%1$s ao finalizar o pedido (%4$s% de desconto para a primeira compra), com assinatura no valor de %2$s (por licença) renovada automaticamente a cada %3$s mês(es).`,
  _ = `%1$s ao finalizar o pedido (%4$s% de desconto para a primeira compra), com assinatura no valor de %2$s (por licença) renovada automaticamente a cada %3$s ano(s).`,
  _ = `O carrinho está vazio.`,
  _ = `Alguns dos itens já estão marcados como privados. Eles permanecerão assim se você continuar:`,
  _ = `Marcar um jogo como privado irá ocultá-lo em todos os lugares fora da sua biblioteca. Os dados sobre a posse, estado, tempo de jogo e atividade nele não serão visíveis para outras pessoas.`,
  _ = `Você está vendo uma nova versão do carrinho de compras porque está participando do beta do cliente Steam. <1>Deixe um comentário ou relate erros</1>`,
  _ = `Este é um teste beta da nova versão do carrinho. <1>Deixe um comentário ou relate erros</1>`,
  _ = `Não é possível agendar a entrega de um presente tão antecipadamente.`,
  _ = `Informe uma data e hora válidas.`,
  _ = `Houve um problema ao exibir este item.`,
  _ = `Esta compra renderá a você %1$s carta da coleção "%2$s".`,
  _ = `Esta compra renderá a você %1$s cartas da coleção "%2$s".`,
  _ = `Compras feitas na Loja Steam durante a promoção renderão a você cartas da coleção "%1$s".`,
  _ = `Você receberá as devidas cartas mesmo que a compra tenha sido para presente.`,
  _ = `Progresso para a próxima carta`,
  _ = `aproximadamente %1$s por carta`,
  _ = `Obs.: produtos em pré-venda não valem para receber cartas da %1$s. Os seguintes itens não renderão cartas:`,
  _ = `Pedido de compra de %1$s`,
  _ = `Compra para:`,
  _ = `Comprar como presente: %1$s`,
  _ = `Adicionar outra cópia deste item ao seu carrinho.`,
  _ = `Declaração de conformidade com a PTSI do Reino Unido`,
  _ = `Houve um problema ao atualizar o seu carrinho.`,
  _ = `Código do erro: %1$s`,
  _ = `País`,
  _ = `Carrinho salvo`,
  _ = `Este é um carrinho de compras salvo. Houve um erro durante a última tentativa de compra deste produto, então salvamos o seu carrinho (incluindo descontos) por %1$s horas para que você possa tentar efetuar a sua compra novamente.`,
  _ = `Copiar opções de presente de`,
  _ = `<1>Inicie a sessão</1> para selecionar alguém da sua lista de amigos do Steam.`,
  _ = {
    language: _,
    Cart_Remove: _,
    Cart_Add: _,
    Cart_Verify: _,
    Cart_RemoveAll: _,
    Cart_Edit: _,
    Cart_Quantity: _,
    Cart_YourShoppingCart: _,
    Cart_YourShoppingCartLineItems: _,
    Cart_YourShoppingCartLineItems_Plural: _,
    Cart_EstimatedTotal: _,
    Cart_Note_SalesTax: _,
    Cart_PurchaseBtn: _,
    Cart_ContainsGiftCheckbox: _,
    Cart_Bradcrumb_Home: _,
    Cart_LineItemGift_Checkbox: _,
    Cart_IncludesItems: _,
    Cart_IncludesItems_Plural: _,
    Cart_SelectRecipient: _,
    Cart_EnterRecipientEmail: _,
    Cart_ChangeGiftRecipient: _,
    Cart_GiftRecipient_Label: _,
    Cart_GiftRecipientEmail_Label: _,
    Cart_GiftDelivery_Label: _,
    Cart_GiftDelivery_Reset: _,
    Cart_GiftDelivery_Now: _,
    Cart_GiftDelivery_Scheduled: _,
    Cart_GiftDelivery_ScheduleDelivery: _,
    Cart_GiftDelivery_From: `De:`,
    Cart_GiftDelivery_Signature: _,
    Cart_GiftDelivery_AddSignature: _,
    Cart_GiftDelivery_Body: _,
    Cart_GiftDeliveryEmail_Warning1: _,
    Cart_GiftDeliveryEmail_Warning2: _,
    Cart_FamilyGift_Notice: _,
    Cart_GiftRecipientModal_Title: _,
    Cart_EditGiftDelivery: _,
    Cart_GiftRecipientModal_Save: _,
    Cart_GiftRecipientModal_Placeholder: _,
    Cart_GiftRecipientModal_OwnsGameLabel: _,
    Cart_GiftRecipientModal_OnWishlist: _,
    Cart_GiftRecipientModal_PartialOwnsLabel: _,
    Cart_GiftRecipientModal_PartialWishlistLabel: _,
    Cart_GiftOptions: _,
    Cart_GiftRecipientModal_IssueLoading: _,
    Cart_ContinueButton_Payment: _,
    Cart_ContinueButton_Gifts: _,
    Cart_ContinueButton_Login: _,
    Cart_DeclinePurchaseRequest: _,
    Cart_LineItemOptions_Myself: _,
    Cart_LineItemOptions_Gift: _,
    Cart_LineItemOptions_GiftForPersona: _,
    Cart_LineItemOptions_Privately: _,
    Cart_CountWidget: _,
    Cart_AddedToYourCart: _,
    Cart_UpdatedYourCart: _,
    Cart_ContinueShopping: _,
    Cart_ComingSoon: _,
    Cart_ViewMyCart: _,
    Cart_RequestPurchase: _,
    Cart_RequestPurchaseExplanation: _,
    Cart_RequestPurchaseNonGiftableItems: _,
    Cart_CouponModify_Change: _,
    Cart_CouponModify_Add: _,
    Cart_CouponAvailability: _,
    Cart_CouponAvailability_Plural: _,
    Cart_Coupons_Applied: _,
    Cart_Coupons_InUse: _,
    Cart_SelectCouponToApply: _,
    Cart_ShippingEstimate_DeliveryDate: _,
    Cart_ShippingEstimate_Range: _,
    Cart_ShippingEstimate_Delayed: _,
    Cart_ShippingEstimate_Standard: _,
    Cart_FooterNoticeHeader_MustFix: _,
    Cart_FooterNoticeHeader_Warning: _,
    Cart_CartLevelErrorNotice: _,
    Cart_CartLevelErrorMultiple: _,
    Cart_CartLevelErrorFormat: _,
    Cart_Error_AlreadyOwned_FootNote: _,
    Cart_Error_AlreadyOwned_LineItem_Game: _,
    Cart_Error_AlreadyOwned_LineItem: _,
    Cart_Error_AlreadyOwned_GiftLineItem_Game: _,
    Cart_Error_AlreadyOwned_GiftLineItem: _,
    Cart_Error_AlreadyOwned_GiftFootNote: _,
    Cart_Error_DuplicateApps_FootNote: _,
    Cart_Error_DuplicateApps_LineItem: _,
    Cart_Error_UnavailableCountry_FootNote: _,
    Cart_Error_UnavailableCountry_LineItem: _,
    Cart_Error_AdultContentRestricted_FootNote: _,
    Cart_Error_AdultContentRestricted_LineItem: _,
    Cart_Error_MasterSubscription_FootNote: _,
    Cart_Error_MasterSubscription_LineItem: _,
    Cart_Error_CouponIsExclusivePromo: _,
    Cart_Error_CouponIsInvalid: _,
    Cart_Error_CouponIsInvalidForItem: _,
    Cart_Error_TooManyInCart: _,
    Cart_Error_CommercialLicenseRestricted_FootNote: _,
    Cart_Error_CommercialLicenseRestricted_LineItem: _,
    Cart_Error_GiftRecipientInvalid: _,
    Cart_Error_MissingMustOwnApps_LineItem: _,
    Cart_Error_MissingMustOwnApps_GiftLineItem: _,
    Cart_Error_MissingMustOwnApps_FootNote: _,
    Cart_Error_MissingMustOwnApps_FootNoteGift: _,
    Cart_Error_ExistingBillingAgreement: _,
    Cart_Error_ExistingBillingAgreement_FootNote: _,
    Cart_Warning_AlreadyOwned_LineItem: _,
    Cart_Warning_ExtraCopies_LineItem: _,
    Cart_Warning_PriceChange_FootNote: _,
    Cart_Warning_PriceChange_LineItem: _,
    Cart_Warning_NoRefund_LineItem: _,
    Cart_Warning_RecipientHigherPrice: _,
    Cart_Warning_AvailableAtALowerPrice: _,
    Cart_Warning_GiftToNonFriend: _,
    Cart_Warning_GiftToNonFriend_Named: _,
    Cart_Warning_GiftToAccount_LoggedOut_Actionable: _,
    Cart_GifteeHint_Wishlist: _,
    PackageIncludesSubscriptionBySecond: _,
    PackageIncludesSubscriptionByMinute: _,
    PackageIncludesSubscriptionByHour: _,
    PackageIncludesSubscriptionByDay: _,
    PackageIncludesSubscriptionByWeek: _,
    PackageIncludesSubscriptionByMonth: _,
    PackageIncludesSubscriptionByYear: _,
    MultiLicenseIncludesSubscriptionBySecond: _,
    MultiLicenseIncludesSubscriptionByMinute: _,
    MultiLicenseIncludesSubscriptionByHour: _,
    MultiLicenseIncludesSubscriptionByDay: _,
    MultiLicenseIncludesSubscriptionByWeek: _,
    MultiLicenseIncludesSubscriptionByMonth: _,
    MultiLicenseeIncludesSubscriptionByYear: _,
    GameBillingPackageIncludesSubscriptionBySecond: _,
    GameBillingPackageIncludesSubscriptionByMinute: _,
    GameBillingPackageIncludesSubscriptionByHour: _,
    GameBillingPackageIncludesSubscriptionByDay: _,
    GameBillingPackageIncludesSubscriptionByWeek: _,
    GameBillingPackageIncludesSubscriptionByMonth: _,
    GameBillingPackageIncludesSubscriptionByYear: _,
    MicroTxnSubscriptionCostBySecond: _,
    MicroTxnSubscriptionCostByMinute: _,
    MicroTxnSubscriptionCostByHour: _,
    MicroTxnSubscriptionCostByDay: _,
    MicroTxnSubscriptionCostByWeek: _,
    MicroTxnSubscriptionCostByMonth: _,
    MicroTxnSubscriptionCostByYear: _,
    GameBillingAuthorizeSubscriptionBySecond: _,
    GameBillingAuthorizeSubscriptionByMinute: _,
    GameBillingAuthorizeSubscriptionByHour: _,
    GameBillingAuthorizeSubscriptionByDay: _,
    GameBillingAuthorizeSubscriptionByWeek: _,
    GameBillingAuthorizeSubscriptionByMonth: _,
    GameBillingAuthorizeSubscriptionByYear: _,
    PackageCostIncludesSubscriptionBySecond: _,
    PackageCostIncludesSubscriptionByMinute: _,
    PackageCostIncludesSubscriptionByHour: _,
    PackageCostIncludesSubscriptionByDay: _,
    PackageCostIncludesSubscriptionByWeek: _,
    PackageCostIncludesSubscriptionByMonth: _,
    PackageCostIncludesSubscriptionByYear: _,
    PackageWithDiscountCostIncludesSubscriptionBySecond: _,
    PackageWithDiscountCostIncludesSubscriptionByMinute: _,
    PackageWithDiscountCostIncludesSubscriptionByHour: _,
    PackageWithDiscountCostIncludesSubscriptionByDay: _,
    PackageWithDiscountCostIncludesSubscriptionByWeek: _,
    PackageWithDiscountCostIncludesSubscriptionByMonth: _,
    PackageWithDiscountCostIncludesSubscriptionByYear: _,
    GameBillingPackageCostIncludesSubscriptionBySecond: _,
    GameBillingPackageCostIncludesSubscriptionByMinute: _,
    GameBillingPackageCostIncludesSubscriptionByHour: _,
    GameBillingPackageCostIncludesSubscriptionByDay: _,
    GameBillingPackageCostIncludesSubscriptionByWeek: _,
    GameBillingPackageCostIncludesSubscriptionByMonth: _,
    GameBillingPackageCostIncludesSubscriptionByYear: _,
    MultiLicenseCostIncludesSubscriptionBySecond: _,
    MultiLicenseCostIncludesSubscriptionByMinute: _,
    MultiLicenseCostIncludesSubscriptionByHour: _,
    MultiLicenseCostIncludesSubscriptionByDay: _,
    MultiLicenseCostIncludesSubscriptionByWeek: _,
    MultiLicenseCostIncludesSubscriptionByMonth: _,
    MultiLicenseCostIncludesSubscriptionByYear: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionBySecond: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMinute: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByHour: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByDay: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByWeek: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMonth: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByYear: _,
    Cart_Empty: _,
    Cart_Notice_SomeAppsPrivate: _,
    Cart_LineItemOptions_PrivateTooltip: _,
    Cart_BetaNotice: _,
    Cart_GenericBetaNotice: _,
    Cart_GiftScheduleError_TooFar: _,
    Cart_GiftScheduleError_InvalidDate: _,
    Cart_LineItem_ErrorBoundary: _,
    Cart_SaleCardDrops_EarnedMessage: _,
    Cart_SaleCardDrops_EarnedMessage_Plural: _,
    Cart_SaleCardDrops_Explanation: _,
    Cart_SaleCardDrops_Explanation_Gifts: _,
    Cart_SaleCardDrops_ProgressLabel: _,
    Cart_SaleCardDrops_CardCost: _,
    Cart_SaleCardDrops_PrepurchaseIneligible: _,
    Cart_PurchaseRequestTitle: _,
    Cart_PurchaseFor_Label: _,
    Cart_GiftForNotice: _,
    Cart_LineItem_Add_Tooltip: _,
    Cart_LineItem_Hardware_Compliance_Label: _,
    Cart_ErrorUpdating: _,
    Cart_ErrorCode: _,
    Cart_UserCountrySelector: _,
    Cart_Replay_SavedCart: _,
    Cart_Replay_Instructions: _,
    Cart_Gifting_CopyGiftOptionsFrom: _,
    Cart_Gifting_SignInToSelectFriends: _,
  };
export {
  _ as Cart_Add,
  _ as Cart_AddedToYourCart,
  _ as Cart_BetaNotice,
  _ as Cart_Bradcrumb_Home,
  _ as Cart_CartLevelErrorFormat,
  _ as Cart_CartLevelErrorMultiple,
  _ as Cart_CartLevelErrorNotice,
  _ as Cart_ChangeGiftRecipient,
  _ as Cart_ComingSoon,
  _ as Cart_ContainsGiftCheckbox,
  _ as Cart_ContinueButton_Gifts,
  _ as Cart_ContinueButton_Login,
  _ as Cart_ContinueButton_Payment,
  _ as Cart_ContinueShopping,
  _ as Cart_CountWidget,
  _ as Cart_CouponAvailability,
  _ as Cart_CouponAvailability_Plural,
  _ as Cart_CouponModify_Add,
  _ as Cart_CouponModify_Change,
  _ as Cart_Coupons_Applied,
  _ as Cart_Coupons_InUse,
  _ as Cart_DeclinePurchaseRequest,
  _ as Cart_Edit,
  _ as Cart_EditGiftDelivery,
  _ as Cart_Empty,
  _ as Cart_EnterRecipientEmail,
  _ as Cart_ErrorCode,
  _ as Cart_ErrorUpdating,
  _ as Cart_Error_AdultContentRestricted_FootNote,
  _ as Cart_Error_AdultContentRestricted_LineItem,
  _ as Cart_Error_AlreadyOwned_FootNote,
  _ as Cart_Error_AlreadyOwned_GiftFootNote,
  _ as Cart_Error_AlreadyOwned_GiftLineItem,
  _ as Cart_Error_AlreadyOwned_GiftLineItem_Game,
  _ as Cart_Error_AlreadyOwned_LineItem,
  _ as Cart_Error_AlreadyOwned_LineItem_Game,
  _ as Cart_Error_CommercialLicenseRestricted_FootNote,
  _ as Cart_Error_CommercialLicenseRestricted_LineItem,
  _ as Cart_Error_CouponIsExclusivePromo,
  _ as Cart_Error_CouponIsInvalid,
  _ as Cart_Error_CouponIsInvalidForItem,
  _ as Cart_Error_DuplicateApps_FootNote,
  _ as Cart_Error_DuplicateApps_LineItem,
  _ as Cart_Error_ExistingBillingAgreement,
  _ as Cart_Error_ExistingBillingAgreement_FootNote,
  _ as Cart_Error_GiftRecipientInvalid,
  _ as Cart_Error_MasterSubscription_FootNote,
  _ as Cart_Error_MasterSubscription_LineItem,
  _ as Cart_Error_MissingMustOwnApps_FootNote,
  _ as Cart_Error_MissingMustOwnApps_FootNoteGift,
  _ as Cart_Error_MissingMustOwnApps_GiftLineItem,
  _ as Cart_Error_MissingMustOwnApps_LineItem,
  _ as Cart_Error_TooManyInCart,
  _ as Cart_Error_UnavailableCountry_FootNote,
  _ as Cart_Error_UnavailableCountry_LineItem,
  _ as Cart_EstimatedTotal,
  _ as Cart_FamilyGift_Notice,
  _ as Cart_FooterNoticeHeader_MustFix,
  _ as Cart_FooterNoticeHeader_Warning,
  _ as Cart_GenericBetaNotice,
  _ as Cart_GiftDeliveryEmail_Warning1,
  _ as Cart_GiftDeliveryEmail_Warning2,
  _ as Cart_GiftDelivery_AddSignature,
  _ as Cart_GiftDelivery_Body,
  _ as Cart_GiftDelivery_From,
  _ as Cart_GiftDelivery_Label,
  _ as Cart_GiftDelivery_Now,
  _ as Cart_GiftDelivery_Reset,
  _ as Cart_GiftDelivery_ScheduleDelivery,
  _ as Cart_GiftDelivery_Scheduled,
  _ as Cart_GiftDelivery_Signature,
  _ as Cart_GiftForNotice,
  _ as Cart_GiftOptions,
  _ as Cart_GiftRecipientEmail_Label,
  _ as Cart_GiftRecipientModal_IssueLoading,
  _ as Cart_GiftRecipientModal_OnWishlist,
  _ as Cart_GiftRecipientModal_OwnsGameLabel,
  _ as Cart_GiftRecipientModal_PartialOwnsLabel,
  _ as Cart_GiftRecipientModal_PartialWishlistLabel,
  _ as Cart_GiftRecipientModal_Placeholder,
  _ as Cart_GiftRecipientModal_Save,
  _ as Cart_GiftRecipientModal_Title,
  _ as Cart_GiftRecipient_Label,
  _ as Cart_GiftScheduleError_InvalidDate,
  _ as Cart_GiftScheduleError_TooFar,
  _ as Cart_GifteeHint_Wishlist,
  _ as Cart_Gifting_CopyGiftOptionsFrom,
  _ as Cart_Gifting_SignInToSelectFriends,
  _ as Cart_IncludesItems,
  _ as Cart_IncludesItems_Plural,
  _ as Cart_LineItemGift_Checkbox,
  _ as Cart_LineItemOptions_Gift,
  _ as Cart_LineItemOptions_GiftForPersona,
  _ as Cart_LineItemOptions_Myself,
  _ as Cart_LineItemOptions_PrivateTooltip,
  _ as Cart_LineItemOptions_Privately,
  _ as Cart_LineItem_Add_Tooltip,
  _ as Cart_LineItem_ErrorBoundary,
  _ as Cart_LineItem_Hardware_Compliance_Label,
  _ as Cart_Note_SalesTax,
  _ as Cart_Notice_SomeAppsPrivate,
  _ as Cart_PurchaseBtn,
  _ as Cart_PurchaseFor_Label,
  _ as Cart_PurchaseRequestTitle,
  _ as Cart_Quantity,
  _ as Cart_Remove,
  _ as Cart_RemoveAll,
  _ as Cart_Replay_Instructions,
  _ as Cart_Replay_SavedCart,
  _ as Cart_RequestPurchase,
  _ as Cart_RequestPurchaseExplanation,
  _ as Cart_RequestPurchaseNonGiftableItems,
  _ as Cart_SaleCardDrops_CardCost,
  _ as Cart_SaleCardDrops_EarnedMessage,
  _ as Cart_SaleCardDrops_EarnedMessage_Plural,
  _ as Cart_SaleCardDrops_Explanation,
  _ as Cart_SaleCardDrops_Explanation_Gifts,
  _ as Cart_SaleCardDrops_PrepurchaseIneligible,
  _ as Cart_SaleCardDrops_ProgressLabel,
  _ as Cart_SelectCouponToApply,
  _ as Cart_SelectRecipient,
  _ as Cart_ShippingEstimate_Delayed,
  _ as Cart_ShippingEstimate_DeliveryDate,
  _ as Cart_ShippingEstimate_Range,
  _ as Cart_ShippingEstimate_Standard,
  _ as Cart_UpdatedYourCart,
  _ as Cart_UserCountrySelector,
  _ as Cart_Verify,
  _ as Cart_ViewMyCart,
  _ as Cart_Warning_AlreadyOwned_LineItem,
  _ as Cart_Warning_AvailableAtALowerPrice,
  _ as Cart_Warning_ExtraCopies_LineItem,
  _ as Cart_Warning_GiftToAccount_LoggedOut_Actionable,
  _ as Cart_Warning_GiftToNonFriend,
  _ as Cart_Warning_GiftToNonFriend_Named,
  _ as Cart_Warning_NoRefund_LineItem,
  _ as Cart_Warning_PriceChange_FootNote,
  _ as Cart_Warning_PriceChange_LineItem,
  _ as Cart_Warning_RecipientHigherPrice,
  _ as Cart_YourShoppingCart,
  _ as Cart_YourShoppingCartLineItems,
  _ as Cart_YourShoppingCartLineItems_Plural,
  _ as GameBillingAuthorizeSubscriptionByDay,
  _ as GameBillingAuthorizeSubscriptionByHour,
  _ as GameBillingAuthorizeSubscriptionByMinute,
  _ as GameBillingAuthorizeSubscriptionByMonth,
  _ as GameBillingAuthorizeSubscriptionBySecond,
  _ as GameBillingAuthorizeSubscriptionByWeek,
  _ as GameBillingAuthorizeSubscriptionByYear,
  _ as GameBillingPackageCostIncludesSubscriptionByDay,
  _ as GameBillingPackageCostIncludesSubscriptionByHour,
  _ as GameBillingPackageCostIncludesSubscriptionByMinute,
  _ as GameBillingPackageCostIncludesSubscriptionByMonth,
  _ as GameBillingPackageCostIncludesSubscriptionBySecond,
  _ as GameBillingPackageCostIncludesSubscriptionByWeek,
  _ as GameBillingPackageCostIncludesSubscriptionByYear,
  _ as GameBillingPackageIncludesSubscriptionByDay,
  _ as GameBillingPackageIncludesSubscriptionByHour,
  _ as GameBillingPackageIncludesSubscriptionByMinute,
  _ as GameBillingPackageIncludesSubscriptionByMonth,
  _ as GameBillingPackageIncludesSubscriptionBySecond,
  _ as GameBillingPackageIncludesSubscriptionByWeek,
  _ as GameBillingPackageIncludesSubscriptionByYear,
  _ as MicroTxnSubscriptionCostByDay,
  _ as MicroTxnSubscriptionCostByHour,
  _ as MicroTxnSubscriptionCostByMinute,
  _ as MicroTxnSubscriptionCostByMonth,
  _ as MicroTxnSubscriptionCostBySecond,
  _ as MicroTxnSubscriptionCostByWeek,
  _ as MicroTxnSubscriptionCostByYear,
  _ as MultiLicenseCostIncludesSubscriptionByDay,
  _ as MultiLicenseCostIncludesSubscriptionByHour,
  _ as MultiLicenseCostIncludesSubscriptionByMinute,
  _ as MultiLicenseCostIncludesSubscriptionByMonth,
  _ as MultiLicenseCostIncludesSubscriptionBySecond,
  _ as MultiLicenseCostIncludesSubscriptionByWeek,
  _ as MultiLicenseCostIncludesSubscriptionByYear,
  _ as MultiLicenseIncludesSubscriptionByDay,
  _ as MultiLicenseIncludesSubscriptionByHour,
  _ as MultiLicenseIncludesSubscriptionByMinute,
  _ as MultiLicenseIncludesSubscriptionByMonth,
  _ as MultiLicenseIncludesSubscriptionBySecond,
  _ as MultiLicenseIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByDay,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByHour,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMinute,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMonth,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionBySecond,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByYear,
  _ as MultiLicenseeIncludesSubscriptionByYear,
  _ as PackageCostIncludesSubscriptionByDay,
  _ as PackageCostIncludesSubscriptionByHour,
  _ as PackageCostIncludesSubscriptionByMinute,
  _ as PackageCostIncludesSubscriptionByMonth,
  _ as PackageCostIncludesSubscriptionBySecond,
  _ as PackageCostIncludesSubscriptionByWeek,
  _ as PackageCostIncludesSubscriptionByYear,
  _ as PackageIncludesSubscriptionByDay,
  _ as PackageIncludesSubscriptionByHour,
  _ as PackageIncludesSubscriptionByMinute,
  _ as PackageIncludesSubscriptionByMonth,
  _ as PackageIncludesSubscriptionBySecond,
  _ as PackageIncludesSubscriptionByWeek,
  _ as PackageIncludesSubscriptionByYear,
  _ as PackageWithDiscountCostIncludesSubscriptionByDay,
  _ as PackageWithDiscountCostIncludesSubscriptionByHour,
  _ as PackageWithDiscountCostIncludesSubscriptionByMinute,
  _ as PackageWithDiscountCostIncludesSubscriptionByMonth,
  _ as PackageWithDiscountCostIncludesSubscriptionBySecond,
  _ as PackageWithDiscountCostIncludesSubscriptionByWeek,
  _ as PackageWithDiscountCostIncludesSubscriptionByYear,
  _ as default,
  _ as language,
};
