var _ = `greek`,
  _ = `Αφαίρεση`,
  _ = `Προσθήκη`,
  _ = `Επαλήθευση ηλικίας`,
  _ = `Αφαίρεση όλων των αντικειμένων`,
  _ = `Επεξεργασία`,
  _ = `Ποσότητα: %1$s`,
  _ = `Το καλάθι αγορών σας`,
  _ = `Το καλάθι αγορών σας (%1$s προϊόν)`,
  _ = `Το καλάθι αγορών σας (%1$s προϊόντα)`,
  _ = `Εκτιμώμενο σύνολο`,
  _ = `Ο φόρος πωλήσεων θα υπολογιστεί όπου ισχύει, κατά την ολοκλήρωση της αγοράς.`,
  _ = `Αγορά`,
  _ = `Αυτή η αγορά περιέχει ένα δώρο`,
  _ = `Αρχική`,
  _ = `Είναι δώρο;`,
  _ = `Περιλαμβάνει %1$s αντικείμενο`,
  _ = `Περιλαμβάνει %1$s αντικείμενα`,
  _ = `Επιλογή παραλήπτη`,
  _ = `Εισαγάγετε email`,
  _ = `Επεξεργασία παραλήπτη δώρου…`,
  _ = `Παραλήπτης δώρου:`,
  _ = `Email παραλήπτη δώρου:`,
  _ = `Παράδοση:`,
  _ = `Επαναφορά`,
  _ = `Το συντομότερο δυνατό (μέσω email και εφαρμογής Steam)`,
  _ = `Προγραμματίστηκε:`,
  _ = `Προγραμματισμός παράδοσης`,
  _ = `Από:`,
  _ = `Η υπογραφή σας:`,
  _ = `Προσθήκη προσαρμοσμένης υπογραφής`,
  _ = `Μήνυμα δώρου (όριο 160 χαρακτήρες, απομένουν %1$s):`,
  _ = `Για δώρα που στέλνονται μέσω email, θα γίνεται αυτόματα επιστροφή χρημάτων 30 μέρες αργότερα σε περίπτωση που δεν έχουν προστεθεί σε κάποιον λογαριασμό Steam.`,
  _ = `Τα δώρα που αποστέλλονται μέσω email μπορούν να γίνονται αποδεκτά μόνο από λογαριασμούς Steam στην ίδια περιοχή με τον αγοραστή (%1$s).`,
  _ = `Τα δώρα που στέλνονται σε παιδιά της Οικογένειας Steam σας θα προστίθενται αυτόματα στον λογαριασμό τους και στα επιτρεπόμενα παιχνίδια τους.`,
  _ = `Επιλογή παραλήπτη δώρου`,
  _ = `Επεξεργασία τρόπου παράδοσης`,
  _ = `Αποθήκευση`,
  _ = `Αναζήτηση ανά όνομα φίλου…`,
  _ = `Έχει ήδη αυτό το αντικείμενο`,
  _ = `Σε Λίστα Επιθυμιών`,
  _ = `Έχει ήδη το «%1$s»`,
  _ = `Θέλει να έχει το «%1$s»`,
  _ = `Επιλογές δώρου`,
  _ = `Παρουσιάστηκε πρόβλημα κατά τη φόρτωση των κατάλληλων παραληπτών δώρων. Δοκιμάστε ξανά αργότερα.`,
  _ = `Συνέχεια στην πληρωμή`,
  _ = `Συνέχεια στις επιλογές δώρου`,
  _ = `Συνδεθείτε για αγορά`,
  _ = `Απόρριψη αιτήματος`,
  _ = `Για τον λογαριασμό μου`,
  _ = `Είναι δώρο`,
  _ = `Αυτό είναι ένα δώρο για: %1$s`,
  _ = `Για τον λογαριασμό μου: ιδιωτικό`,
  _ = `Καλάθι (%1$s)`,
  _ = `Προστέθηκε στο καλάθι σας!`,
  _ = `Το καλάθι σας ενημερώθηκε!`,
  _ = `Συνέχεια αγορών`,
  _ = `Διαθέσιμο %1$s`,
  _ = `Προβολή καλαθιού (%1$s)`,
  _ = `Αίτημα αγοράς`,
  _ = `Οι ενήλικες στην Οικογένεια Steam σας θα ειδοποιηθούν για το αίτημα αγοράς σας`,
  _ = `Δεν είναι δυνατή η αίτηση αγοράς, επειδή δεν έχουν όλα τα αντικείμενα στο καλάθι δυνατότητα δώρου.`,
  _ = `Αλλαγή ή αφαίρεση κουπονιού`,
  _ = `Προσθήκη κουπονιού`,
  _ = `Έχετε ένα διαθέσιμο κουπόνι για αυτό το αντικείμενο`,
  _ = `Έχετε %1$s διαθέσιμα κουπόνια για αυτό το αντικείμενο`,
  _ = `Έχει εφαρμοστεί`,
  _ = `Έχει εφαρμοστεί σε άλλο προϊόν`,
  _ = `Επιλέξτε ένα κουπόνι για εφαρμογή σε %1$s`,
  _ = `Εκτιμώμενη παράδοση: %1$s`,
  _ = `%1$s–%2$s εργάσιμες ημέρες`,
  _ = `Εκτιμώμενη παράδοση: 6 – 10 εργάσιμες ημέρες`,
  _ = `Εκτιμώμενη παράδοση: 3 – 5 εργάσιμες ημέρες`,
  _ = `Πριν μπορέσετε να συνεχίσετε στην πληρωμή:`,
  _ = `Σημειώσεις:`,
  _ = `Απαιτείται ενέργεια πριν μπορέσετε να συνεχίσετε στην πληρωμή`,
  _ = `Σημειώσεις:`,
  _ = `Σημείωση: %1$s`,
  _ = `Έχετε ήδη στον λογαριασμό σας μερικά από τα παραπάνω αντικείμενα, οπότε δεν μπορείτε να τα αγοράσετε ξανά. Μπορείτε να αγοράσετε αυτά τα αντικείμενα ως δώρα ή να προσαρμόσετε τα περιεχόμενα του καλαθιού σας για να συνεχίσετε.`,
  _ = `Το έχετε ήδη`,
  _ = `Έχετε ήδη τα πάντα σε αυτό το πακέτο`,
  _ = `Ο παραλήπτης του δώρου έχει ήδη αυτό το παιχνίδι`,
  _ = `Ο παραλήπτης του δώρου έχει ήδη ό,τι υπάρχει σε αυτό το πακέτο`,
  _ = `Ο παραλήπτης του δώρου έχει ήδη μερικά από τα παραπάνω αντικείμενα, οπότε δεν μπορείτε να τα αγοράσετε ξανά. Μπορείτε να τα αγοράσετε για κάποιον άλλο λογαριασμό ή να προσαρμόσετε το περιεχόμενο του καλαθιού σας και να συνεχίσετε.`,
  _ = `Φαίνεται πως έχετε πακέτα που περιέχουν το ίδιο προϊόν στο καλάθι αγορών σας. Θα χρειαστεί να αφαιρέσετε τα περιττά πακέτα από το καλάθι σας πριν συνεχίσετε.`,
  _ = `Είναι ήδη στο καλάθι σας: `,
  _ = `Το καλάθι σας περιέχει ένα πακέτο που δεν είναι διαθέσιμο στη χώρα σας. Θα χρειαστεί να αφαιρέσετε το πακέτο από το καλάθι σας για να ολοκληρώσετε την αγορά σας.`,
  _ = `Δεν είναι διαθέσιμο στη χώρα σας`,
  _ = `Απαιτείται από τη Valve να επαληθεύσει ότι είστε 18 ετών ή άνω, πριν την παραχώρηση της δυνατότητας αγοράς σεξουαλικού περιεχομένου για ώριμο κοινό.`,
  _ = `Δεν είναι διαθέσιμο για αγορά μέχρι να επαληθεύσετε την ηλικία σας.`,
  _ = `Στο καλάθι σας υπάρχει περιεχόμενο που είναι επίσης διαθέσιμο μέσω κάποιας από τις ενεργές συνδρομές σας.`,
  _ = `Διαθέσιμο μέσω της συνδρομής σας:`,
  _ = `Αυτό το κουπόνι δεν μπορεί να χρησιμοποιηθεί σε συνδυασμό με άλλες εκπτώσεις.`,
  _ = `Αυτό το κουπόνι δεν ισχύει ή έχει λήξει.`,
  _ = `Αυτό το κουπόνι δεν μπορεί να εφαρμοστεί σε αυτό το αντικείμενο.`,
  _ = `Έχετε υπερβεί τη μέγιστη επιτρεπόμενη ποσότητα αυτού του αντικειμένου στο καλάθι σας.`,
  _ = `Το καλάθι σας περιέχει ένα αντικείμενο που δεν είναι διαθέσιμο για αγορά.`,
  _ = `Μη διαθέσιμο για αγορά`,
  _ = `Ο επιλεγμένος παραλήπτης δεν μπορεί να λάβει αυτό το δώρο που έχει αγοραστεί από την περιοχή σας.`,
  _ = `Για την αγορά αυτού του αντικειμένου, πρέπει να έχετε τα ακόλουθα αντικείμενα:`,
  _ = `Για αυτό το αντικείμενο, ο παραλήπτης του δώρου πρέπει να έχει τα ακόλουθα αντικείμενα:`,
  _ = `Ο λογαριασμός σας δεν έχει μερικά αντικείμενα που είναι απαραίτητα για την αγορά των αντικειμένων στο καλάθι σας. Μπορείτε να προσθέσετε τα αντικείμενα που λείπουν ή να προσαρμόσετε το περιεχόμενο του καλαθιού σας, για να συνεχίσετε.`,
  _ = `Ο παραλήπτης του δώρου σας δεν έχει μερικά αντικείμενα που είναι απαραίτητα για την αγορά των αντικειμένων στο καλάθι σας. Μπορείτε να προσθέσετε τα αντικείμενα που λείπουν ή να προσαρμόσετε το περιεχόμενο του καλαθιού σας, για να συνεχίσετε.`,
  _ = `Έχετε ήδη μια συνδρομή για αυτό το αντικείμενο.`,
  _ = `Ο λογαριασμός σας έχει ήδη συνδρομή για μερικά από τα παραπάνω αντικείμενα. Δείτε τις ρυθμίσεις συνδρομών σας στη σελίδα λεπτομερειών του λογαριασμού σας.`,
  _ = `Αν το αγοράζετε για εσάς, δεν θα λάβετε επιπλέον αντίγραφο του:`,
  _ = `Αν το αγοράζετε για εσάς, θα λάβετε ένα επιπλέον αντίγραφο που μπορείτε να δώσετε ως δώρο, για το:`,
  _ = `Ένα ή περισσότερα από τα παρακάτω προϊόντα άλλαξαν τιμή από τη στιγμή που τα προσθέσατε στο καλάθι σας.`,
  _ = `Η τιμή αυτού του αντικειμένου άλλαξε`,
  _ = `Αυτό το προϊόν περιλαμβάνει αναλώσιμο περιεχόμενο και δεν επιδέχεται επιστροφή χρημάτων.`,
  _ = `Ο παραλήπτης δώρου που έχετε επιλέξει βρίσκεται σε περιοχή με υψηλότερες τιμές. Το κόστος αυτού του προϊόντος έχει ενημερωθεί για να ταιριάζει με την περιοχή του παραλήπτη ώστε να επιτραπεί η προσφορά του δώρου.`,
  _ = `Αυτό το στοιχείο είναι διαθέσιμο σε χαμηλότερη τιμή ως μέρος του «%1$s».`,
  _ = `Ο παραλήπτης του δώρου ΔΕΝ βρίσκεται στη λίστα φίλων σας στο Steam.`,
  _ = `ΣΗΜΕΙΩΣΗ: Ο χρήστης %1$s ΔΕΝ βρίσκεται στη λίστα φίλων σας στο Steam.`,
  _ = `Εάν στέλνετε ένα δώρο σε κάποιον φίλο εντός του Steam, <1>συνδεθείτε</1> για να επιβεβαιώσετε ότι ο παραλήπτης βρίσκεται στη λίστα φίλων σας.`,
  _ = `Είδατε πρόσφατα τη Λίστα Επιθυμιών του χρήστη %1$s. Θέλετε να του κάνετε δώρο αυτά τα στοιχεία;`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s δευτερόλεπτα.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s λεπτά.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s ώρες.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s ημέρες.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s εβδομάδες.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s μήνες.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s χρόνια.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s δευτερόλεπτα ανά άδεια.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s λεπτά ανά άδεια.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s ώρες ανά άδεια.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s ημέρες ανά άδεια.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s εβδομάδες ανά άδεια.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s μήνες ανά άδεια.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s χρόνια ανά άδεια.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s δευτερόλεπτα ή όπως ορίζεται από τον λογαριασμό παιχνιδιού σας.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s λεπτά ή όπως ορίζεται από τον λογαριασμό παιχνιδιού σας.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s ώρες ή όπως ορίζεται από τον λογαριασμό παιχνιδιού σας.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s ημέρες ή όπως ορίζεται από τον λογαριασμό παιχνιδιού σας.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s εβδομάδες ή όπως ορίζεται από τον λογαριασμό παιχνιδιού σας.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s μήνες ή όπως ορίζεται από τον λογαριασμό παιχνιδιού σας.`,
  _ = `Χρέωση συνδρομής %1$s κάθε %2$s χρόνια ή όπως ορίζεται από τον λογαριασμό παιχνιδιού σας.`,
  _ = `Θα χρεωθείτε %1$s κατά την ολοκλήρωση της αγοράς.<br/>Συμφωνείτε να χρεώνεστε αυτόματα %2$s κάθε %3$s δευτερόλεπτα.`,
  _ = `Θα χρεωθείτε %1$s κατά την ολοκλήρωση της αγοράς.<br/>Συμφωνείτε να χρεώνεστε αυτόματα %2$s κάθε %3$s λεπτά.`,
  _ = `Θα χρεωθείτε %1$s κατά την ολοκλήρωση της αγοράς.<br/>Συμφωνείτε να χρεώνεστε αυτόματα %2$s κάθε %3$s ώρες.`,
  _ = `Θα χρεωθείτε %1$s κατά την ολοκλήρωση της αγοράς.<br/>Συμφωνείτε να χρεώνεστε αυτόματα %2$s κάθε %3$s ημέρες.`,
  _ = `Θα χρεωθείτε %1$s κατά την ολοκλήρωση της αγοράς.<br/>Συμφωνείτε να χρεώνεστε αυτόματα %2$s κάθε %3$s εβδομάδες.`,
  _ = `Θα χρεωθείτε %1$s κατά την ολοκλήρωση της αγοράς.<br/>Συμφωνείτε να χρεώνεστε αυτόματα %2$s κάθε %3$s μήνες.`,
  _ = `Θα χρεωθείτε %1$s κατά την ολοκλήρωση της αγοράς.<br/>Συμφωνείτε να χρεώνεστε αυτόματα %2$s κάθε %3$s χρόνια.`,
  _ = `Θα χρεωθείτε %1$s κατά την ολοκλήρωση της αγοράς.<br/>Επιτρέπετε σε αυτό το παιχνίδι να πραγματοποιεί περαιτέρω χρεώσεις έως %2$s κάθε %3$s δευτερόλεπτα.`,
  _ = `Θα χρεωθείτε %1$s κατά την ολοκλήρωση της αγοράς.<br/>Επιτρέπετε σε αυτό το παιχνίδι να πραγματοποιεί περαιτέρω χρεώσεις έως %2$s κάθε %3$s λεπτά.`,
  _ = `Θα χρεωθείτε %1$s κατά την ολοκλήρωση της αγοράς.<br/>Επιτρέπετε σε αυτό το παιχνίδι να πραγματοποιεί περαιτέρω χρεώσεις έως %2$s κάθε %3$s ώρες.`,
  _ = `Θα χρεωθείτε %1$s κατά την ολοκλήρωση της αγοράς.<br/>Επιτρέπετε σε αυτό το παιχνίδι να πραγματοποιεί περαιτέρω χρεώσεις έως %2$s κάθε %3$s ημέρες.`,
  _ = `Θα χρεωθείτε %1$s κατά την ολοκλήρωση της αγοράς.<br/>Επιτρέπετε σε αυτό το παιχνίδι να πραγματοποιεί περαιτέρω χρεώσεις έως %2$s κάθε %3$s εβδομάδες.`,
  _ = `Θα χρεωθείτε %1$s κατά την ολοκλήρωση της αγοράς.<br/>Επιτρέπετε σε αυτό το παιχνίδι να πραγματοποιεί περαιτέρω χρεώσεις έως %2$s κάθε %3$s μήνες.`,
  _ = `Θα χρεωθείτε %1$s κατά την ολοκλήρωση της αγοράς.<br/>Επιτρέπετε σε αυτό το παιχνίδι να πραγματοποιεί περαιτέρω χρεώσεις έως %2$s κάθε %3$s χρόνια.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s κάθε %3$s δευτερόλεπτα.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s κάθε %3$s λεπτά.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s κάθε %3$s ώρες.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s κάθε %3$s ημέρες.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s κάθε %3$s εβδομάδες.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s κάθε %3$s μήνες.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s κάθε %3$s χρόνια.`,
  _ = `Κατά την ολοκλήρωση της αγοράς, η τελική τιμή %1$s έχει έκπτωση %4$s% για αγορές πρώτης φοράς και ανανεώνεται αυτόματα κάθε %3$s δευτερόλεπτα με %2$s.`,
  _ = `Κατά την ολοκλήρωση της αγοράς, η τελική τιμή %1$s έχει έκπτωση %4$s% για αγορές πρώτης φοράς και ανανεώνεται αυτόματα κάθε %3$s λεπτά με %2$s.`,
  _ = `Κατά την ολοκλήρωση της αγοράς, η τελική τιμή %1$s έχει έκπτωση %4$s% για αγορές πρώτης φοράς και ανανεώνεται αυτόματα κάθε %3$s ώρες με %2$s.`,
  _ = `Κατά την ολοκλήρωση της αγοράς, η τελική τιμή %1$s έχει έκπτωση %4$s% για αγορές πρώτης φοράς και ανανεώνεται αυτόματα κάθε %3$s ημέρες με %2$s.`,
  _ = `Κατά την ολοκλήρωση της αγοράς, η τελική τιμή %1$s έχει έκπτωση %4$s% για αγορές πρώτης φοράς και ανανεώνεται αυτόματα κάθε %3$s εβδομάδες με %2$s.`,
  _ = `Κατά την ολοκλήρωση της αγοράς, η τελική τιμή %1$s έχει έκπτωση %4$s% για αγορές πρώτης φοράς και ανανεώνεται αυτόματα κάθε %3$s μήνες με %2$s.`,
  _ = `Κατά την ολοκλήρωση της αγοράς, η τελική τιμή %1$s έχει έκπτωση %4$s% για αγορές πρώτης φοράς και ανανεώνεται αυτόματα κάθε %3$s χρόνια με %2$s.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση αγοράς και αυτόματη ανανέωση συνδρομής %2$s κάθε %3$s δευτερόλεπτα όπως ορίζεται από τον λογαριασμό παιχνιδιού σας.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s κάθε %3$s λεπτά όπως ορίζεται από τον λογαριασμό παιχνιδιού σας.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s κάθε %3$s ώρες όπως ορίζεται από τον λογαριασμό παιχνιδιού σας.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s κάθε %3$s ημέρες όπως ορίζεται από τον λογαριασμό παιχνιδιού σας.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s κάθε %3$s εβδομάδες όπως ορίζεται από τον λογαριασμό παιχνιδιού σας.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s κάθε %3$s μήνες όπως ορίζεται από τον λογαριασμό παιχνιδιού σας.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s κάθε %3$s χρόνια όπως ορίζεται από τον λογαριασμό παιχνιδιού σας.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s ανά άδεια κάθε %3$s δευτερόλεπτα.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s ανά άδεια κάθε %3$s λεπτά.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s ανά άδεια κάθε %3$s ώρες.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s ανά άδεια κάθε %3$s ημέρες.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s ανά άδεια κάθε %3$s εβδομάδες.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s ανά άδεια κάθε %3$s μήνες.`,
  _ = `Χρέωση %1$s κατά την ολοκλήρωση της αγοράς και αυτόματη ανανέωση συνδρομής %2$s ανά άδεια κάθε %3$s χρόνια.`,
  _ = `Κατά την ολοκλήρωση της αγοράς, η τελική τιμή %1$s έχει έκπτωση %4$s% για αγορές πρώτης φοράς και ανανεώνεται αυτόματα κάθε %3$s δευτερόλεπτα με %2$s ανά άδεια.`,
  _ = `Κατά την ολοκλήρωση της αγοράς, η τελική τιμή %1$s έχει έκπτωση %4$s% για αγορές πρώτης φοράς και ανανεώνεται αυτόματα κάθε %3$s λεπτά με %2$s ανά άδεια.`,
  _ = `Κατά την ολοκλήρωση της αγοράς, η τελική τιμή %1$s έχει έκπτωση %4$s% για αγορές πρώτης φοράς και ανανεώνεται αυτόματα κάθε %3$s ώρες με %2$s ανά άδεια.`,
  _ = `Κατά την ολοκλήρωση της αγοράς, η τελική τιμή %1$s έχει έκπτωση %4$s% για αγορές πρώτης φοράς και ανανεώνεται αυτόματα κάθε %3$s ημέρες με %2$s ανά άδεια.`,
  _ = `Κατά την ολοκλήρωση της αγοράς, η τελική τιμή %1$s έχει έκπτωση %4$s% για αγορές πρώτης φοράς και ανανεώνεται αυτόματα κάθε %3$s εβδομάδες με %2$s ανά άδεια.`,
  _ = `Κατά την ολοκλήρωση της αγοράς, η τελική τιμή %1$s έχει έκπτωση %4$s% για αγορές πρώτης φοράς και ανανεώνεται αυτόματα κάθε %3$s μήνες με %2$s ανά άδεια.`,
  _ = `Κατά την ολοκλήρωση της αγοράς, η τελική τιμή %1$s έχει έκπτωση %4$s% για αγορές πρώτης φοράς και ανανεώνεται αυτόματα κάθε %3$s χρόνια με %2$s ανά άδεια.`,
  _ = `Το καλάθι σας είναι άδειο.`,
  _ = `Μερικά από αυτά τα αντικείμενα έχουν ήδη επισημανθεί ως ιδιωτικά. Θα παραμείνουν ιδιωτικά αν συνεχίσετε:`,
  _ = `Η επισήμανση ενός παιχνιδιού ως ιδιωτικό θα το αποκρύψει παντού εκτός από τη Συλλογή σας. Άλλα άτομα δεν θα μπορούν να δουν ότι έχετε το παιχνίδι, την κατάσταση σας εντός παιχνιδιού, τον χρόνο παιχνιδιού και τη δραστηριότητά σας.`,
  _ = `Βλέπετε μια νέα έκδοση του καλαθιού αγορών επειδή συμμετέχετε στην έκδοση βήτα της εφαρμογής Steam. <1>Αφήστε σχόλια και παρατηρήσεις ή αναφέρετε σφάλματα</1>`,
  _ = `Κάνουμε δοκιμές για τη νέα έκδοση βήτα του καλαθιού αγορών. <1>Αφήστε σχόλια και παρατηρήσεις ή αναφέρετε σφάλματα</1>`,
  _ = `Δεν μπορείτε να προγραμματίσετε ένα δώρο για μια τόσο μακρινή ημερομηνία.`,
  _ = `Εισαγάγετε μια έγκυρη ημερομηνία και ώρα.`,
  _ = `Παρουσιάστηκε πρόβλημα κατά την εμφάνιση αυτού του αντικειμένου.`,
  _ = `Με αυτήν την αγορά θα κερδίσετε %1$s Κάρτα Ανταλλαγής %2$s.`,
  _ = `Με αυτήν την αγορά θα κερδίσετε %1$s Κάρτες Ανταλλαγής %2$s.`,
  _ = `Αγοράζοντας προϊόντα από το Κατάστημα Steam κατά τη διάρκεια των εκπτώσεων, θα κερδίσετε Κάρτες Ανταλλαγής %1$s.`,
  _ = `Θα λάβετε τις Κάρτες ακόμα και αν το αγοράσετε ως δώρο.`,
  _ = `Συνέχεια στην επόμενη κάρτα`,
  _ = `περίπου %1$s ανά κάρτα`,
  _ = `Σημείωση: Οι προπαραγγελίες δεν μπορούν να λάβουν ανταμοιβές Καρτών Ανταλλαγής %1$s. Τα ακόλουθα αντικείμενα δεν θα κερδίσουν καμία ανταμοιβή Καρτών Ανταλλαγής:`,
  _ = `Αίτημα αγοράς από %1$s`,
  _ = `Μια αγορά για:`,
  _ = `Αγορά ως δώρο: %1$s`,
  _ = `Προσθέστε ένα ακόμα αντίγραφο αυτού του αντικειμένου στο καλάθι σας`,
  _ = `UK PSTI – Δήλωση Συμμόρφωσης`,
  _ = `Παρουσιάστηκε πρόβλημα κατά την ενημέρωση του καλαθιού σας.`,
  _ = `Κωδικός σφάλματος: %1$s`,
  _ = `Χώρα`,
  _ = `Αποθηκευμένο καλάθι αγορών`,
  _ = `Αυτό είναι ένα αποθηκευμένο καλάθι αγορών. Την τελευταία φορά που προσπαθήσατε να αγοράσετε τα προϊόντα σε αυτό το καλάθι παρουσιάστηκε σφάλμα, οπότε αποθηκεύσαμε το καλάθι σας (μαζί με τις εκπτώσεις) για %1$s ώρες ώστε να επαναλάβετε την αγορά.`,
  _ = `Αντιγραφή επιλογών δώρου από:`,
  _ = `<1>Συνδεθείτε</1> για να επιλέξετε φίλους Steam`,
  _ = {
    language: _,
    Cart_Remove: _,
    Cart_Add: _,
    Cart_Verify: _,
    Cart_RemoveAll: _,
    Cart_Edit: _,
    Cart_Quantity: _,
    Cart_YourShoppingCart: _,
    Cart_YourShoppingCartLineItems: _,
    Cart_YourShoppingCartLineItems_Plural: _,
    Cart_EstimatedTotal: _,
    Cart_Note_SalesTax: _,
    Cart_PurchaseBtn: _,
    Cart_ContainsGiftCheckbox: _,
    Cart_Bradcrumb_Home: _,
    Cart_LineItemGift_Checkbox: _,
    Cart_IncludesItems: _,
    Cart_IncludesItems_Plural: _,
    Cart_SelectRecipient: _,
    Cart_EnterRecipientEmail: _,
    Cart_ChangeGiftRecipient: _,
    Cart_GiftRecipient_Label: _,
    Cart_GiftRecipientEmail_Label: _,
    Cart_GiftDelivery_Label: _,
    Cart_GiftDelivery_Reset: _,
    Cart_GiftDelivery_Now: _,
    Cart_GiftDelivery_Scheduled: _,
    Cart_GiftDelivery_ScheduleDelivery: _,
    Cart_GiftDelivery_From: _,
    Cart_GiftDelivery_Signature: _,
    Cart_GiftDelivery_AddSignature: _,
    Cart_GiftDelivery_Body: _,
    Cart_GiftDeliveryEmail_Warning1: _,
    Cart_GiftDeliveryEmail_Warning2: _,
    Cart_FamilyGift_Notice: _,
    Cart_GiftRecipientModal_Title: _,
    Cart_EditGiftDelivery: _,
    Cart_GiftRecipientModal_Save: _,
    Cart_GiftRecipientModal_Placeholder: _,
    Cart_GiftRecipientModal_OwnsGameLabel: _,
    Cart_GiftRecipientModal_OnWishlist: _,
    Cart_GiftRecipientModal_PartialOwnsLabel: _,
    Cart_GiftRecipientModal_PartialWishlistLabel: _,
    Cart_GiftOptions: _,
    Cart_GiftRecipientModal_IssueLoading: _,
    Cart_ContinueButton_Payment: _,
    Cart_ContinueButton_Gifts: _,
    Cart_ContinueButton_Login: _,
    Cart_DeclinePurchaseRequest: _,
    Cart_LineItemOptions_Myself: _,
    Cart_LineItemOptions_Gift: _,
    Cart_LineItemOptions_GiftForPersona: _,
    Cart_LineItemOptions_Privately: _,
    Cart_CountWidget: _,
    Cart_AddedToYourCart: _,
    Cart_UpdatedYourCart: _,
    Cart_ContinueShopping: _,
    Cart_ComingSoon: _,
    Cart_ViewMyCart: _,
    Cart_RequestPurchase: _,
    Cart_RequestPurchaseExplanation: _,
    Cart_RequestPurchaseNonGiftableItems: _,
    Cart_CouponModify_Change: _,
    Cart_CouponModify_Add: _,
    Cart_CouponAvailability: _,
    Cart_CouponAvailability_Plural: _,
    Cart_Coupons_Applied: _,
    Cart_Coupons_InUse: _,
    Cart_SelectCouponToApply: _,
    Cart_ShippingEstimate_DeliveryDate: _,
    Cart_ShippingEstimate_Range: _,
    Cart_ShippingEstimate_Delayed: _,
    Cart_ShippingEstimate_Standard: _,
    Cart_FooterNoticeHeader_MustFix: _,
    Cart_FooterNoticeHeader_Warning: _,
    Cart_CartLevelErrorNotice: _,
    Cart_CartLevelErrorMultiple: _,
    Cart_CartLevelErrorFormat: _,
    Cart_Error_AlreadyOwned_FootNote: _,
    Cart_Error_AlreadyOwned_LineItem_Game: _,
    Cart_Error_AlreadyOwned_LineItem: _,
    Cart_Error_AlreadyOwned_GiftLineItem_Game: _,
    Cart_Error_AlreadyOwned_GiftLineItem: _,
    Cart_Error_AlreadyOwned_GiftFootNote: _,
    Cart_Error_DuplicateApps_FootNote: _,
    Cart_Error_DuplicateApps_LineItem: _,
    Cart_Error_UnavailableCountry_FootNote: _,
    Cart_Error_UnavailableCountry_LineItem: _,
    Cart_Error_AdultContentRestricted_FootNote: _,
    Cart_Error_AdultContentRestricted_LineItem: _,
    Cart_Error_MasterSubscription_FootNote: _,
    Cart_Error_MasterSubscription_LineItem: _,
    Cart_Error_CouponIsExclusivePromo: _,
    Cart_Error_CouponIsInvalid: _,
    Cart_Error_CouponIsInvalidForItem: _,
    Cart_Error_TooManyInCart: _,
    Cart_Error_CommercialLicenseRestricted_FootNote: _,
    Cart_Error_CommercialLicenseRestricted_LineItem: _,
    Cart_Error_GiftRecipientInvalid: _,
    Cart_Error_MissingMustOwnApps_LineItem: _,
    Cart_Error_MissingMustOwnApps_GiftLineItem: _,
    Cart_Error_MissingMustOwnApps_FootNote: _,
    Cart_Error_MissingMustOwnApps_FootNoteGift: _,
    Cart_Error_ExistingBillingAgreement: _,
    Cart_Error_ExistingBillingAgreement_FootNote: _,
    Cart_Warning_AlreadyOwned_LineItem: _,
    Cart_Warning_ExtraCopies_LineItem: _,
    Cart_Warning_PriceChange_FootNote: _,
    Cart_Warning_PriceChange_LineItem: _,
    Cart_Warning_NoRefund_LineItem: _,
    Cart_Warning_RecipientHigherPrice: _,
    Cart_Warning_AvailableAtALowerPrice: _,
    Cart_Warning_GiftToNonFriend: _,
    Cart_Warning_GiftToNonFriend_Named: _,
    Cart_Warning_GiftToAccount_LoggedOut_Actionable: _,
    Cart_GifteeHint_Wishlist: _,
    PackageIncludesSubscriptionBySecond: _,
    PackageIncludesSubscriptionByMinute: _,
    PackageIncludesSubscriptionByHour: _,
    PackageIncludesSubscriptionByDay: _,
    PackageIncludesSubscriptionByWeek: _,
    PackageIncludesSubscriptionByMonth: _,
    PackageIncludesSubscriptionByYear: _,
    MultiLicenseIncludesSubscriptionBySecond: _,
    MultiLicenseIncludesSubscriptionByMinute: _,
    MultiLicenseIncludesSubscriptionByHour: _,
    MultiLicenseIncludesSubscriptionByDay: _,
    MultiLicenseIncludesSubscriptionByWeek: _,
    MultiLicenseIncludesSubscriptionByMonth: _,
    MultiLicenseeIncludesSubscriptionByYear: _,
    GameBillingPackageIncludesSubscriptionBySecond: _,
    GameBillingPackageIncludesSubscriptionByMinute: _,
    GameBillingPackageIncludesSubscriptionByHour: _,
    GameBillingPackageIncludesSubscriptionByDay: _,
    GameBillingPackageIncludesSubscriptionByWeek: _,
    GameBillingPackageIncludesSubscriptionByMonth: _,
    GameBillingPackageIncludesSubscriptionByYear: _,
    MicroTxnSubscriptionCostBySecond: _,
    MicroTxnSubscriptionCostByMinute: _,
    MicroTxnSubscriptionCostByHour: _,
    MicroTxnSubscriptionCostByDay: _,
    MicroTxnSubscriptionCostByWeek: _,
    MicroTxnSubscriptionCostByMonth: _,
    MicroTxnSubscriptionCostByYear: _,
    GameBillingAuthorizeSubscriptionBySecond: _,
    GameBillingAuthorizeSubscriptionByMinute: _,
    GameBillingAuthorizeSubscriptionByHour: _,
    GameBillingAuthorizeSubscriptionByDay: _,
    GameBillingAuthorizeSubscriptionByWeek: _,
    GameBillingAuthorizeSubscriptionByMonth: _,
    GameBillingAuthorizeSubscriptionByYear: _,
    PackageCostIncludesSubscriptionBySecond: _,
    PackageCostIncludesSubscriptionByMinute: _,
    PackageCostIncludesSubscriptionByHour: _,
    PackageCostIncludesSubscriptionByDay: _,
    PackageCostIncludesSubscriptionByWeek: _,
    PackageCostIncludesSubscriptionByMonth: _,
    PackageCostIncludesSubscriptionByYear: _,
    PackageWithDiscountCostIncludesSubscriptionBySecond: _,
    PackageWithDiscountCostIncludesSubscriptionByMinute: _,
    PackageWithDiscountCostIncludesSubscriptionByHour: _,
    PackageWithDiscountCostIncludesSubscriptionByDay: _,
    PackageWithDiscountCostIncludesSubscriptionByWeek: _,
    PackageWithDiscountCostIncludesSubscriptionByMonth: _,
    PackageWithDiscountCostIncludesSubscriptionByYear: _,
    GameBillingPackageCostIncludesSubscriptionBySecond: _,
    GameBillingPackageCostIncludesSubscriptionByMinute: _,
    GameBillingPackageCostIncludesSubscriptionByHour: _,
    GameBillingPackageCostIncludesSubscriptionByDay: _,
    GameBillingPackageCostIncludesSubscriptionByWeek: _,
    GameBillingPackageCostIncludesSubscriptionByMonth: _,
    GameBillingPackageCostIncludesSubscriptionByYear: _,
    MultiLicenseCostIncludesSubscriptionBySecond: _,
    MultiLicenseCostIncludesSubscriptionByMinute: _,
    MultiLicenseCostIncludesSubscriptionByHour: _,
    MultiLicenseCostIncludesSubscriptionByDay: _,
    MultiLicenseCostIncludesSubscriptionByWeek: _,
    MultiLicenseCostIncludesSubscriptionByMonth: _,
    MultiLicenseCostIncludesSubscriptionByYear: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionBySecond: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMinute: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByHour: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByDay: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByWeek: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMonth: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByYear: _,
    Cart_Empty: _,
    Cart_Notice_SomeAppsPrivate: _,
    Cart_LineItemOptions_PrivateTooltip: _,
    Cart_BetaNotice: _,
    Cart_GenericBetaNotice: _,
    Cart_GiftScheduleError_TooFar: _,
    Cart_GiftScheduleError_InvalidDate: _,
    Cart_LineItem_ErrorBoundary: _,
    Cart_SaleCardDrops_EarnedMessage: _,
    Cart_SaleCardDrops_EarnedMessage_Plural: _,
    Cart_SaleCardDrops_Explanation: _,
    Cart_SaleCardDrops_Explanation_Gifts: _,
    Cart_SaleCardDrops_ProgressLabel: _,
    Cart_SaleCardDrops_CardCost: _,
    Cart_SaleCardDrops_PrepurchaseIneligible: _,
    Cart_PurchaseRequestTitle: _,
    Cart_PurchaseFor_Label: _,
    Cart_GiftForNotice: _,
    Cart_LineItem_Add_Tooltip: _,
    Cart_LineItem_Hardware_Compliance_Label: _,
    Cart_ErrorUpdating: _,
    Cart_ErrorCode: _,
    Cart_UserCountrySelector: _,
    Cart_Replay_SavedCart: _,
    Cart_Replay_Instructions: _,
    Cart_Gifting_CopyGiftOptionsFrom: _,
    Cart_Gifting_SignInToSelectFriends: _,
  };
export {
  _ as Cart_Add,
  _ as Cart_AddedToYourCart,
  _ as Cart_BetaNotice,
  _ as Cart_Bradcrumb_Home,
  _ as Cart_CartLevelErrorFormat,
  _ as Cart_CartLevelErrorMultiple,
  _ as Cart_CartLevelErrorNotice,
  _ as Cart_ChangeGiftRecipient,
  _ as Cart_ComingSoon,
  _ as Cart_ContainsGiftCheckbox,
  _ as Cart_ContinueButton_Gifts,
  _ as Cart_ContinueButton_Login,
  _ as Cart_ContinueButton_Payment,
  _ as Cart_ContinueShopping,
  _ as Cart_CountWidget,
  _ as Cart_CouponAvailability,
  _ as Cart_CouponAvailability_Plural,
  _ as Cart_CouponModify_Add,
  _ as Cart_CouponModify_Change,
  _ as Cart_Coupons_Applied,
  _ as Cart_Coupons_InUse,
  _ as Cart_DeclinePurchaseRequest,
  _ as Cart_Edit,
  _ as Cart_EditGiftDelivery,
  _ as Cart_Empty,
  _ as Cart_EnterRecipientEmail,
  _ as Cart_ErrorCode,
  _ as Cart_ErrorUpdating,
  _ as Cart_Error_AdultContentRestricted_FootNote,
  _ as Cart_Error_AdultContentRestricted_LineItem,
  _ as Cart_Error_AlreadyOwned_FootNote,
  _ as Cart_Error_AlreadyOwned_GiftFootNote,
  _ as Cart_Error_AlreadyOwned_GiftLineItem,
  _ as Cart_Error_AlreadyOwned_GiftLineItem_Game,
  _ as Cart_Error_AlreadyOwned_LineItem,
  _ as Cart_Error_AlreadyOwned_LineItem_Game,
  _ as Cart_Error_CommercialLicenseRestricted_FootNote,
  _ as Cart_Error_CommercialLicenseRestricted_LineItem,
  _ as Cart_Error_CouponIsExclusivePromo,
  _ as Cart_Error_CouponIsInvalid,
  _ as Cart_Error_CouponIsInvalidForItem,
  _ as Cart_Error_DuplicateApps_FootNote,
  _ as Cart_Error_DuplicateApps_LineItem,
  _ as Cart_Error_ExistingBillingAgreement,
  _ as Cart_Error_ExistingBillingAgreement_FootNote,
  _ as Cart_Error_GiftRecipientInvalid,
  _ as Cart_Error_MasterSubscription_FootNote,
  _ as Cart_Error_MasterSubscription_LineItem,
  _ as Cart_Error_MissingMustOwnApps_FootNote,
  _ as Cart_Error_MissingMustOwnApps_FootNoteGift,
  _ as Cart_Error_MissingMustOwnApps_GiftLineItem,
  _ as Cart_Error_MissingMustOwnApps_LineItem,
  _ as Cart_Error_TooManyInCart,
  _ as Cart_Error_UnavailableCountry_FootNote,
  _ as Cart_Error_UnavailableCountry_LineItem,
  _ as Cart_EstimatedTotal,
  _ as Cart_FamilyGift_Notice,
  _ as Cart_FooterNoticeHeader_MustFix,
  _ as Cart_FooterNoticeHeader_Warning,
  _ as Cart_GenericBetaNotice,
  _ as Cart_GiftDeliveryEmail_Warning1,
  _ as Cart_GiftDeliveryEmail_Warning2,
  _ as Cart_GiftDelivery_AddSignature,
  _ as Cart_GiftDelivery_Body,
  _ as Cart_GiftDelivery_From,
  _ as Cart_GiftDelivery_Label,
  _ as Cart_GiftDelivery_Now,
  _ as Cart_GiftDelivery_Reset,
  _ as Cart_GiftDelivery_ScheduleDelivery,
  _ as Cart_GiftDelivery_Scheduled,
  _ as Cart_GiftDelivery_Signature,
  _ as Cart_GiftForNotice,
  _ as Cart_GiftOptions,
  _ as Cart_GiftRecipientEmail_Label,
  _ as Cart_GiftRecipientModal_IssueLoading,
  _ as Cart_GiftRecipientModal_OnWishlist,
  _ as Cart_GiftRecipientModal_OwnsGameLabel,
  _ as Cart_GiftRecipientModal_PartialOwnsLabel,
  _ as Cart_GiftRecipientModal_PartialWishlistLabel,
  _ as Cart_GiftRecipientModal_Placeholder,
  _ as Cart_GiftRecipientModal_Save,
  _ as Cart_GiftRecipientModal_Title,
  _ as Cart_GiftRecipient_Label,
  _ as Cart_GiftScheduleError_InvalidDate,
  _ as Cart_GiftScheduleError_TooFar,
  _ as Cart_GifteeHint_Wishlist,
  _ as Cart_Gifting_CopyGiftOptionsFrom,
  _ as Cart_Gifting_SignInToSelectFriends,
  _ as Cart_IncludesItems,
  _ as Cart_IncludesItems_Plural,
  _ as Cart_LineItemGift_Checkbox,
  _ as Cart_LineItemOptions_Gift,
  _ as Cart_LineItemOptions_GiftForPersona,
  _ as Cart_LineItemOptions_Myself,
  _ as Cart_LineItemOptions_PrivateTooltip,
  _ as Cart_LineItemOptions_Privately,
  _ as Cart_LineItem_Add_Tooltip,
  _ as Cart_LineItem_ErrorBoundary,
  _ as Cart_LineItem_Hardware_Compliance_Label,
  _ as Cart_Note_SalesTax,
  _ as Cart_Notice_SomeAppsPrivate,
  _ as Cart_PurchaseBtn,
  _ as Cart_PurchaseFor_Label,
  _ as Cart_PurchaseRequestTitle,
  _ as Cart_Quantity,
  _ as Cart_Remove,
  _ as Cart_RemoveAll,
  _ as Cart_Replay_Instructions,
  _ as Cart_Replay_SavedCart,
  _ as Cart_RequestPurchase,
  _ as Cart_RequestPurchaseExplanation,
  _ as Cart_RequestPurchaseNonGiftableItems,
  _ as Cart_SaleCardDrops_CardCost,
  _ as Cart_SaleCardDrops_EarnedMessage,
  _ as Cart_SaleCardDrops_EarnedMessage_Plural,
  _ as Cart_SaleCardDrops_Explanation,
  _ as Cart_SaleCardDrops_Explanation_Gifts,
  _ as Cart_SaleCardDrops_PrepurchaseIneligible,
  _ as Cart_SaleCardDrops_ProgressLabel,
  _ as Cart_SelectCouponToApply,
  _ as Cart_SelectRecipient,
  _ as Cart_ShippingEstimate_Delayed,
  _ as Cart_ShippingEstimate_DeliveryDate,
  _ as Cart_ShippingEstimate_Range,
  _ as Cart_ShippingEstimate_Standard,
  _ as Cart_UpdatedYourCart,
  _ as Cart_UserCountrySelector,
  _ as Cart_Verify,
  _ as Cart_ViewMyCart,
  _ as Cart_Warning_AlreadyOwned_LineItem,
  _ as Cart_Warning_AvailableAtALowerPrice,
  _ as Cart_Warning_ExtraCopies_LineItem,
  _ as Cart_Warning_GiftToAccount_LoggedOut_Actionable,
  _ as Cart_Warning_GiftToNonFriend,
  _ as Cart_Warning_GiftToNonFriend_Named,
  _ as Cart_Warning_NoRefund_LineItem,
  _ as Cart_Warning_PriceChange_FootNote,
  _ as Cart_Warning_PriceChange_LineItem,
  _ as Cart_Warning_RecipientHigherPrice,
  _ as Cart_YourShoppingCart,
  _ as Cart_YourShoppingCartLineItems,
  _ as Cart_YourShoppingCartLineItems_Plural,
  _ as GameBillingAuthorizeSubscriptionByDay,
  _ as GameBillingAuthorizeSubscriptionByHour,
  _ as GameBillingAuthorizeSubscriptionByMinute,
  _ as GameBillingAuthorizeSubscriptionByMonth,
  _ as GameBillingAuthorizeSubscriptionBySecond,
  _ as GameBillingAuthorizeSubscriptionByWeek,
  _ as GameBillingAuthorizeSubscriptionByYear,
  _ as GameBillingPackageCostIncludesSubscriptionByDay,
  _ as GameBillingPackageCostIncludesSubscriptionByHour,
  _ as GameBillingPackageCostIncludesSubscriptionByMinute,
  _ as GameBillingPackageCostIncludesSubscriptionByMonth,
  _ as GameBillingPackageCostIncludesSubscriptionBySecond,
  _ as GameBillingPackageCostIncludesSubscriptionByWeek,
  _ as GameBillingPackageCostIncludesSubscriptionByYear,
  _ as GameBillingPackageIncludesSubscriptionByDay,
  _ as GameBillingPackageIncludesSubscriptionByHour,
  _ as GameBillingPackageIncludesSubscriptionByMinute,
  _ as GameBillingPackageIncludesSubscriptionByMonth,
  _ as GameBillingPackageIncludesSubscriptionBySecond,
  _ as GameBillingPackageIncludesSubscriptionByWeek,
  _ as GameBillingPackageIncludesSubscriptionByYear,
  _ as MicroTxnSubscriptionCostByDay,
  _ as MicroTxnSubscriptionCostByHour,
  _ as MicroTxnSubscriptionCostByMinute,
  _ as MicroTxnSubscriptionCostByMonth,
  _ as MicroTxnSubscriptionCostBySecond,
  _ as MicroTxnSubscriptionCostByWeek,
  _ as MicroTxnSubscriptionCostByYear,
  _ as MultiLicenseCostIncludesSubscriptionByDay,
  _ as MultiLicenseCostIncludesSubscriptionByHour,
  _ as MultiLicenseCostIncludesSubscriptionByMinute,
  _ as MultiLicenseCostIncludesSubscriptionByMonth,
  _ as MultiLicenseCostIncludesSubscriptionBySecond,
  _ as MultiLicenseCostIncludesSubscriptionByWeek,
  _ as MultiLicenseCostIncludesSubscriptionByYear,
  _ as MultiLicenseIncludesSubscriptionByDay,
  _ as MultiLicenseIncludesSubscriptionByHour,
  _ as MultiLicenseIncludesSubscriptionByMinute,
  _ as MultiLicenseIncludesSubscriptionByMonth,
  _ as MultiLicenseIncludesSubscriptionBySecond,
  _ as MultiLicenseIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByDay,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByHour,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMinute,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMonth,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionBySecond,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByYear,
  _ as MultiLicenseeIncludesSubscriptionByYear,
  _ as PackageCostIncludesSubscriptionByDay,
  _ as PackageCostIncludesSubscriptionByHour,
  _ as PackageCostIncludesSubscriptionByMinute,
  _ as PackageCostIncludesSubscriptionByMonth,
  _ as PackageCostIncludesSubscriptionBySecond,
  _ as PackageCostIncludesSubscriptionByWeek,
  _ as PackageCostIncludesSubscriptionByYear,
  _ as PackageIncludesSubscriptionByDay,
  _ as PackageIncludesSubscriptionByHour,
  _ as PackageIncludesSubscriptionByMinute,
  _ as PackageIncludesSubscriptionByMonth,
  _ as PackageIncludesSubscriptionBySecond,
  _ as PackageIncludesSubscriptionByWeek,
  _ as PackageIncludesSubscriptionByYear,
  _ as PackageWithDiscountCostIncludesSubscriptionByDay,
  _ as PackageWithDiscountCostIncludesSubscriptionByHour,
  _ as PackageWithDiscountCostIncludesSubscriptionByMinute,
  _ as PackageWithDiscountCostIncludesSubscriptionByMonth,
  _ as PackageWithDiscountCostIncludesSubscriptionBySecond,
  _ as PackageWithDiscountCostIncludesSubscriptionByWeek,
  _ as PackageWithDiscountCostIncludesSubscriptionByYear,
  _ as default,
  _ as language,
};
