var _ = `hungarian`,
  _ = `Eltávolítás`,
  _ = `Hozzáadás`,
  _ = `Életkor ellenőrzése`,
  _ = `Összes tétel eltávolítása`,
  _ = `Szerkesztés`,
  _ = `Mennyiség: %1$s`,
  _ = `Bevásárlókosarad`,
  _ = `Bevásárlókosarad (%1$s tétel)`,
  _ = `Bevásárlókosarad (%1$s tétel)`,
  _ = `Becsült teljes összeg`,
  _ = `A forgalmi adó a kasszánál kerül kiszámításra, ahol alkalmazandó.`,
  _ = `Vásárlás`,
  _ = `Ez a vásárlás ajándékot tartalmaz`,
  _ = `Kezdőoldal`,
  _ = `Ajándék lesz?`,
  _ = `%1$s elemet tartalmaz`,
  _ = `%1$s elemet tartalmaz`,
  _ = `Címzett kiválasztása`,
  _ = `E-mail megadása`,
  _ = `Ajándékozott módosítása...`,
  _ = `Ajándékozott:`,
  _ = `Ajándékozott e-mailje:`,
  _ = `Kézbesítés:`,
  _ = `Alaphelyzet`,
  _ = `A lehető leghamarabb (e-mailben és Steam kliensen keresztül).`,
  _ = `Időzítve:`,
  _ = `Kézbesítés időzítése`,
  _ = `Tőle:`,
  _ = `Aláírásod:`,
  _ = `Egyedi aláírás hozzáadása`,
  _ = `Ajándéküzenet (legfeljebb 160 karakter, még %1$s maradt):`,
  _ = `Az e-mailben küldött ajándékok 30 nap után automatikusan vissza lesznek térítve, ha nem lettek Steam fiókhoz adva.`,
  _ = `E-mailben küldött ajándékokat csak a vásárlóéval megegyező régióban (%1$s) levő Steam fiókok fogadhatnak el.`,
  _ = `A Steam családodban levő gyermekeknek küldött ajándékok automatikusan hozzá lesznek adva a fiókjukhoz és az engedélyezett játékaikhoz.`,
  _ = `Ajándékozott kiválasztása`,
  _ = `Küldési mód szerkesztése`,
  _ = `Mentés`,
  _ = `Keresés barátnévre...`,
  _ = `Már megvan neki ez a tétel`,
  _ = `Kívánságlistán`,
  _ = `Már megvan neki a(z) %1$s.`,
  _ = `Szeretné a(z) %1$s játékot.`,
  _ = `Ajándékbeállítás`,
  _ = `Probléma adódott a jogosult ajándékcímzettek betöltésekor. Próbáld újra később.`,
  _ = `Tovább a fizetéshez`,
  _ = `Tovább az ajándékbeállításhoz`,
  _ = `Vásárláshoz lépj be`,
  _ = `Kérés elutasítása`,
  _ = `A saját fiókomra`,
  _ = `Ajándék lesz`,
  _ = `Ez ajándék %1$s számára`,
  _ = `A saját fiókomra + privát`,
  _ = `Kosár (%1$s)`,
  _ = `A kosaradhoz adva!`,
  _ = `Frissült a kosarad!`,
  _ = `Vásárlás folytatása`,
  _ = `Elérhető: %1$s`,
  _ = `Kosaram megnézése (%1$s)`,
  _ = `Vásárlás kérése`,
  _ = `A Steam családod felnőtt tagjai értesítést fognak kapni a vásárlási kérésedről.`,
  _ = `Nem lehet kérni a vásárlást, mert a kosárban nem minden tétel ajándékozható.`,
  _ = `Kupon eltávolítása / cseréje`,
  _ = `Kupon hozzáadása`,
  _ = `Ehhez a tételhez rendelkezel kuponnal`,
  _ = `Ehhez a tételhez rendelkezel %1$s kuponnal`,
  _ = `Jelenleg alkalmazott`,
  _ = `Jelenleg egy másik termékre van alkalmazva`,
  _ = `Válaszd ki a(z) %1$s termékre alkalmazandó kupont`,
  _ = `Becsült kiszállítás: %1$s`,
  _ = `%1$s–%2$s munkanap`,
  _ = `Becsült szállítás: 6–10 munkanap`,
  _ = `Becsült szállítás: 3–5 munkanap`,
  _ = `Mielőtt továbbléphetnél a fizetéshez:`,
  _ = `Megjegyzések:`,
  _ = `Teendőd van a fizetéshez továbblépés előtt`,
  _ = `Megjegyzések:`,
  _ = `Megjegyzés: %1$s`,
  _ = `Fiókodon már megvan a fentiek némelyike, így nem veheted meg azokat újra. A folytatáshoz megveheted e tételeket ajándékként, vagy módosíthatod kosarad tartalmát.`,
  _ = `Már megvan neked ez a játék.`,
  _ = `Már minden megvan neked ebből a csomagból.`,
  _ = `Az ajándék címzettjének már megvan ez a játék.`,
  _ = `Az ajándék címzettjének már minden megvan ebből a csomagból.`,
  _ = `Az ajándék címzettjének már megvan néhány a fenti tételekből, így nem tudod újra megvásárolni azokat. A folytatáshoz megvásárolhatod azokat egy másik fióknak, vagy módosíthatsz kosarad tartalmán.`,
  _ = `A kosaradban lévő csomagok között átfedések vannak. Mielőtt továbbléphetnél a kasszához, el kell távolítanod az átfedő csomagokat a kosaradból.`,
  _ = `Már a kosaradban van: `,
  _ = `A kosarad olyan csomagot tartalmaz, amely nem érhető el az országodban. Mielőtt továbbléphetnél a kasszához, el kell távolítanod a csomagot a kosaradból.`,
  _ = `Nem érhető el az országodban`,
  _ = `Felnőtt szexuális tartalom mevásárlásának engedélyezése előtt a Valve köteles ellenőrizni, hogy elmúltál-e 18 éves.`,
  _ = `Életkorod ellenőrzéséig nem vásárolható meg.`,
  _ = `A kosaradban olyan tartalom van, amely egy aktív előfizetésed részeként is elérhető.`,
  _ = `Ezen az előfizetéseden keresztül érhető el:`,
  _ = `Ez a kupon nem használható másik kedvezménnyel együtt.`,
  _ = `Ez a kupon érvénytelen vagy lejárt.`,
  _ = `Ez a kupon nem alkalmazható erre a tételre.`,
  _ = `Túllépted a kosaradban megengedett maximális mennyiséget e termékből.`,
  _ = `A kosarad olyan tételt tartalmaz, amely nem vásárolható meg.`,
  _ = `Nem vásárolható meg`,
  _ = `A kiválasztott címzett nem kaphatja meg ezt a te régiódban vásárolt ajándékot.`,
  _ = `E tétel megvásárlásához rendelkezned kell a következő tételekkel:`,
  _ = `E tételhez a megajándékozottnak rendelkeznie kell a következő tételekkel:`,
  _ = `Fiókod nem rendelkezik azon tételek némelyikével, melyek szükségesek a kosaradban levő tételek megvásárlásához. Hozzá tudod adni a hiányzó tételeket, vagy módosíthatod a kosarad tartalmát a folytatáshoz.`,
  _ = `A megajándékozott nem rendelkezik azon tételek némelyikével, melyek szükségesek a kosaradban levő tételek megvásárlásához. Hozzá tudod adni a hiányzó tételeket, vagy módosíthatod a kosarad tartalmát a folytatáshoz.`,
  _ = `Már van előfizetésed erre a termékre.`,
  _ = `Fiókodnak már van előfizetése a fenti termékek némelyikére. Nézd meg előfizetési beállításaidat a fiókod részleteinél.`,
  _ = `Ha magadnak vásárolsz, ezekből nem fogsz plusz példányt kapni:`,
  _ = `Ha magadnak vásárolsz, ezekből fogsz elajándékozható plusz példányt kapni:`,
  _ = `Egy vagy több alábbi tétel ára megváltozott, mióta hozzáadtad a kosaradhoz.`,
  _ = `E tétel ára megváltozott`,
  _ = `Ez a termék egyszer használatos tartalmat tartalmaz, ami miatt nem jogosult visszatérítésre.`,
  _ = `Az ajándék általad kiválasztott címzettje egy magasabb árú régióban van. A tétel ára frissítve lett, hogy illeszkedjen az ő régiójához, lehetővé téve a neki ajándékozást.`,
  _ = `Ez a termék a(z) %1$s részeként alacsonyabb áron kapható.`,
  _ = `Az ajándék címzettje NINCS a Steames barátlistádon.`,
  _ = `MEGJEGYZÉS: %1$s NINCS a Steames barátlistádon.`,
  _ = `Ha Steames barátnak küldesz ajándékot, <1>jelentkezz be</1> annak ellenőrzésére, hogy a címzett a barátlistádon van-e.`,
  _ = `Nemrég megnézted %1$s kívánságlistáját. Odaajándékozod neki ezeket a tételeket?`,
  _ = `A fizetendő előfizetés %1$s %2$s másodpercenként.`,
  _ = `A fizetendő előfizetés %1$s %2$s percenként.`,
  _ = `A fizetendő előfizetés %1$s %2$s óránként.`,
  _ = `A fizetendő előfizetés %1$s %2$s naponta.`,
  _ = `A fizetendő előfizetés %1$s %2$s hetente.`,
  _ = `A fizetendő előfizetés %1$s %2$s havonta.`,
  _ = `A fizetendő előfizetés %1$s %2$s évente.`,
  _ = `A fizetendő előfizetés licencenként %1$s %2$s másodpercenként.`,
  _ = `A fizetendő előfizetés licencenként %1$s %2$s percenként.`,
  _ = `A fizetendő előfizetés licencenként %1$s %2$s óránként.`,
  _ = `A fizetendő előfizetés licencenként %1$s %2$s naponta.`,
  _ = `A fizetendő előfizetés licencenként %1$s %2$s hetente.`,
  _ = `A fizetendő előfizetés licencenként %1$s %2$s havonta.`,
  _ = `A fizetendő előfizetés licencenként %1$s %2$s évente.`,
  _ = `Az előfizetési összeg %1$s %2$s másodpercenként, vagy ahogyan játékfiókod meghatározza.`,
  _ = `Az előfizetési összeg %1$s %2$s percenként, vagy ahogyan játékfiókod meghatározza.`,
  _ = `Az előfizetési összeg %1$s %2$s óránként, vagy ahogyan játékfiókod meghatározza.`,
  _ = `Az előfizetési összeg %1$s %2$s naponta, vagy ahogyan játékfiókod meghatározza.`,
  _ = `Az előfizetési összeg %1$s %2$s hetente, vagy ahogyan játékfiókod meghatározza.`,
  _ = `Az előfizetési összeg %1$s %2$s havonta, vagy ahogyan játékfiókod meghatározza.`,
  _ = `Az előfizetési összeg %1$s %2$s évente, vagy ahogyan játékfiókod meghatározza.`,
  _ = `%1$s összeget fogsz fizetni a kasszánál.<br/>Elfogadod, hogy automatikusan %2$s összeget fogsz fizetni %3$s másodpercenként.`,
  _ = `%1$s összeget fogsz fizetni a kasszánál.<br/>Elfogadod, hogy automatikusan %2$s összeget fogsz fizetni %3$s percenként.`,
  _ = `%1$s összeget fogsz fizetni a kasszánál.<br/>Elfogadod, hogy automatikusan %2$s összeget fogsz fizetni %3$s óránként.`,
  _ = `%1$s összeget fogsz fizetni a kasszánál.<br/>Elfogadod, hogy automatikusan %2$s összeget fogsz fizetni %3$s naponta.`,
  _ = `%1$s összeget fogsz fizetni a kasszánál.<br/>Elfogadod, hogy automatikusan %2$s összeget fogsz fizetni %3$s hetente.`,
  _ = `%1$s összeget fogsz fizetni a kasszánál.<br/>Elfogadod, hogy automatikusan %2$s összeget fogsz fizetni %3$s havonta.`,
  _ = `%1$s összeget fogsz fizetni a kasszánál.<br/>Elfogadod, hogy automatikusan %2$s összeget fogsz fizetni %3$s évente.`,
  _ = `%1$s összeg kerül levonásra a kasszánál.<br/>Engedélyezed, hogy ez a játék ezt követően legfeljebb %2$s összeget levonjon %3$s másodpercenként.`,
  _ = `%1$s összeg kerül levonásra a kasszánál.<br/>Engedélyezed, hogy ez a játék ezt követően legfeljebb %2$s összeget levonjon %3$s percenként.`,
  _ = `%1$s összeg kerül levonásra a kasszánál.<br/>Engedélyezed, hogy ez a játék ezt követően legfeljebb %2$s összeget levonjon %3$s óránként.`,
  _ = `%1$s összeg kerül levonásra a kasszánál.<br/>Engedélyezed, hogy ez a játék ezt követően legfeljebb %2$s összeget levonjon %3$s naponta.`,
  _ = `%1$s összeg kerül levonásra a kasszánál.<br/>Engedélyezed, hogy ez a játék ezt követően legfeljebb %2$s összeget levonjon %3$s hetente.`,
  _ = `%1$s összeg kerül levonásra a kasszánál.<br/>Engedélyezed, hogy ez a játék ezt követően legfeljebb %2$s összeget levonjon %3$s havonta.`,
  _ = `%1$s összeg kerül levonásra a kasszánál.<br/>Engedélyezed, hogy ez a játék ezt követően legfeljebb %2$s összeget levonjon %3$s évente.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul %2$s összegért %3$s másodpercenként.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul %2$s összegért %3$s percenként.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul %2$s összegért %3$s óránként.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul %2$s összegért %3$s naponta.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul %2$s összegért %3$s hetente.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul %2$s összegért %3$s havonta.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul %2$s összegért %3$s évente.`,
  _ = `%1$s a kasszánál (%4$s% kedvezménnyel az első vásárlásra), majd automatikusan megújul %2$s összegért %3$s másodpercenként.`,
  _ = `%1$s a kasszánál (%4$s% kedvezménnyel az első vásárlásra), majd automatikusan megújul %2$s összegért %3$s percenként.`,
  _ = `%1$s a kasszánál (%4$s% kedvezménnyel az első vásárlásra), majd automatikusan megújul %2$s összegért %3$s óránként.`,
  _ = `%1$s a kasszánál (%4$s% kedvezménnyel az első vásárlásra), majd automatikusan megújul %2$s összegért %3$s naponta.`,
  _ = `%1$s a kasszánál (%4$s% kedvezménnyel az első vásárlásra), majd automatikusan megújul %2$s összegért %3$s hetente.`,
  _ = `%1$s a kasszánál (%4$s% kedvezménnyel az első vásárlásra), majd automatikusan megújul %2$s összegért %3$s havonta.`,
  _ = `%1$s a kasszánál (%4$s% kedvezménnyel az első vásárlásra), majd automatikusan megújul %2$s összegért %3$s évente.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul %2$s összegért %3$s másodpercenként, ahogyan játékfiókod meghatározza.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul %2$s összegért %3$s percenként, ahogyan játékfiókod meghatározza.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul %2$s összegért %3$s óránként, ahogyan játékfiókod meghatározza.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul %2$s összegért %3$s naponta, ahogyan játékfiókod meghatározza.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul %2$s összegért %3$s hetente, ahogyan játékfiókod meghatározza.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul %2$s összegért %3$s havonta, ahogyan játékfiókod meghatározza.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul %2$s összegért %3$s évente, ahogyan játékfiókod meghatározza.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul licencenként %2$s összegért %3$s másodpercenként.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul licencenként %2$s összegért %3$s percenként.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul licencenként %2$s összegért %3$s óránként.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul licencenként %2$s összegért %3$s naponta.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul licencenként %2$s összegért %3$s hetente.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul licencenként %2$s összegért %3$s havonta.`,
  _ = `%1$s a kasszánál, majd automatikusan megújul licencenként %2$s összegért %3$s évente.`,
  _ = `%1$s a kasszánál (%4$s% kedvezménnyel az első vásárlásra), majd %3$s másodpercenként automatikusan megújul %2$s licencenkénti összegért.`,
  _ = `%1$s a kasszánál (%4$s% kedvezménnyel az első vásárlásra), majd %3$s percenként automatikusan megújul %2$s licencenkénti összegért.`,
  _ = `%1$s a kasszánál (%4$s% kedvezménnyel az első vásárlásra), majd %3$s óránként automatikusan megújul %2$s licencenkénti összegért.`,
  _ = `%1$s a kasszánál (%4$s% kedvezménnyel az első vásárlásra), majd %3$s naponta automatikusan megújul %2$s licencenkénti összegért.`,
  _ = `%1$s a kasszánál (%4$s% kedvezménnyel az első vásárlásra), majd %3$s hetente automatikusan megújul %2$s licencenkénti összegért.`,
  _ = `%1$s a kasszánál (%4$s% kedvezménnyel az első vásárlásra), majd %3$s havonta automatikusan megújul %2$s licencenkénti összegért.`,
  _ = `%1$s a kasszánál (%4$s% kedvezménnyel az első vásárlásra), majd %3$s évente automatikusan megújul %2$s licencenkénti összegért.`,
  _ = `A kosarad üres.`,
  _ = `E tételek némelyike már privátként van megjelölve. Ha folytatod, privátak maradnak:`,
  _ = `Egy játék privátként megjelölése mindenhol el fogja rejteni azt a Könyvtáradon kívül. A birtoklás, játékbeli állapotod, játékidőd és -tevékenységed nem lesz látható másoknak.`,
  _ = `A bevásárlókosár új verzióját látod, mert részt veszel a Steam kliens bétában. <1>Küldj visszajelzést vagy jelents hibákat.</1>`,
  _ = `A bevásárlókosár ezen új verziójának bétatesztelését végezzük. <1>Küldj visszajelzést vagy jelents hibákat.</1>`,
  _ = `Nem ütemezheted az ajándékot ilyen messzire a jövőbe.`,
  _ = `Adj meg érvényes dátumot és időpontot.`,
  _ = `Probléma adódott e tétel megjelenítésekor.`,
  _ = `Ezzel a vásárlással %1$s %2$s játékkártyát fogsz kapni.`,
  _ = `Ezzel a vásárlással %1$s %2$s játékkártyát fogsz kapni.`,
  _ = `A vásár idején a Steam Áruházban vásárolva %1$s játékkártyákat kapsz.`,
  _ = `A kártyákat akkor is megkapod, ha ez a vásárlás ajándék lesz.`,
  _ = `Haladás a következő kártyáig`,
  _ = `körülbelül %1$s kártyánként`,
  _ = `Megjegyzés: Az elővételben megvett tételek nem jogosítanak %1$s játékkártya-jutalomra. Az alábbi tételek után nem fogsz játékkártya-jutalmat kapni:`,
  _ = `%1$s vásárlási kérelme`,
  _ = `Vásárlás neki:`,
  _ = `Ajándékba vásárlás %1$s számára`,
  _ = `E tétel még egy példányának hozzáadása a kosaradhoz.`,
  _ = `UK PSTI Statement of Compliance`,
  _ = `Probléma adódott a kosarad frissítésekor.`,
  _ = `Hibakód: %1$s`,
  _ = `Ország`,
  _ = `Mentett kosár`,
  _ = `Ez egy elmentett bevásárlókosár. Legutóbb, amikor megpróbáltad megvásárolni ezt a kosarat, hiba történt, ezért %1$s órára elmentettük a kosaradat (a kedvezményekkel együtt), hogy újra meg tudd próbálni a vásárlást.`,
  _ = `Ajándékbeállítások másolása innen:`,
  _ = `Steames barátok kiválasztásához <1>jelentkezz be</1>.`,
  _ = {
    language: _,
    Cart_Remove: _,
    Cart_Add: _,
    Cart_Verify: _,
    Cart_RemoveAll: _,
    Cart_Edit: _,
    Cart_Quantity: _,
    Cart_YourShoppingCart: _,
    Cart_YourShoppingCartLineItems: _,
    Cart_YourShoppingCartLineItems_Plural: _,
    Cart_EstimatedTotal: _,
    Cart_Note_SalesTax: _,
    Cart_PurchaseBtn: _,
    Cart_ContainsGiftCheckbox: _,
    Cart_Bradcrumb_Home: _,
    Cart_LineItemGift_Checkbox: _,
    Cart_IncludesItems: _,
    Cart_IncludesItems_Plural: _,
    Cart_SelectRecipient: _,
    Cart_EnterRecipientEmail: _,
    Cart_ChangeGiftRecipient: _,
    Cart_GiftRecipient_Label: _,
    Cart_GiftRecipientEmail_Label: _,
    Cart_GiftDelivery_Label: _,
    Cart_GiftDelivery_Reset: _,
    Cart_GiftDelivery_Now: _,
    Cart_GiftDelivery_Scheduled: _,
    Cart_GiftDelivery_ScheduleDelivery: _,
    Cart_GiftDelivery_From: _,
    Cart_GiftDelivery_Signature: _,
    Cart_GiftDelivery_AddSignature: _,
    Cart_GiftDelivery_Body: _,
    Cart_GiftDeliveryEmail_Warning1: _,
    Cart_GiftDeliveryEmail_Warning2: _,
    Cart_FamilyGift_Notice: _,
    Cart_GiftRecipientModal_Title: _,
    Cart_EditGiftDelivery: _,
    Cart_GiftRecipientModal_Save: _,
    Cart_GiftRecipientModal_Placeholder: _,
    Cart_GiftRecipientModal_OwnsGameLabel: _,
    Cart_GiftRecipientModal_OnWishlist: _,
    Cart_GiftRecipientModal_PartialOwnsLabel: _,
    Cart_GiftRecipientModal_PartialWishlistLabel: _,
    Cart_GiftOptions: _,
    Cart_GiftRecipientModal_IssueLoading: _,
    Cart_ContinueButton_Payment: _,
    Cart_ContinueButton_Gifts: _,
    Cart_ContinueButton_Login: _,
    Cart_DeclinePurchaseRequest: _,
    Cart_LineItemOptions_Myself: _,
    Cart_LineItemOptions_Gift: _,
    Cart_LineItemOptions_GiftForPersona: _,
    Cart_LineItemOptions_Privately: _,
    Cart_CountWidget: _,
    Cart_AddedToYourCart: _,
    Cart_UpdatedYourCart: _,
    Cart_ContinueShopping: _,
    Cart_ComingSoon: _,
    Cart_ViewMyCart: _,
    Cart_RequestPurchase: _,
    Cart_RequestPurchaseExplanation: _,
    Cart_RequestPurchaseNonGiftableItems: _,
    Cart_CouponModify_Change: _,
    Cart_CouponModify_Add: _,
    Cart_CouponAvailability: _,
    Cart_CouponAvailability_Plural: _,
    Cart_Coupons_Applied: _,
    Cart_Coupons_InUse: _,
    Cart_SelectCouponToApply: _,
    Cart_ShippingEstimate_DeliveryDate: _,
    Cart_ShippingEstimate_Range: _,
    Cart_ShippingEstimate_Delayed: _,
    Cart_ShippingEstimate_Standard: _,
    Cart_FooterNoticeHeader_MustFix: _,
    Cart_FooterNoticeHeader_Warning: _,
    Cart_CartLevelErrorNotice: _,
    Cart_CartLevelErrorMultiple: _,
    Cart_CartLevelErrorFormat: _,
    Cart_Error_AlreadyOwned_FootNote: _,
    Cart_Error_AlreadyOwned_LineItem_Game: _,
    Cart_Error_AlreadyOwned_LineItem: _,
    Cart_Error_AlreadyOwned_GiftLineItem_Game: _,
    Cart_Error_AlreadyOwned_GiftLineItem: _,
    Cart_Error_AlreadyOwned_GiftFootNote: _,
    Cart_Error_DuplicateApps_FootNote: _,
    Cart_Error_DuplicateApps_LineItem: _,
    Cart_Error_UnavailableCountry_FootNote: _,
    Cart_Error_UnavailableCountry_LineItem: _,
    Cart_Error_AdultContentRestricted_FootNote: _,
    Cart_Error_AdultContentRestricted_LineItem: _,
    Cart_Error_MasterSubscription_FootNote: _,
    Cart_Error_MasterSubscription_LineItem: _,
    Cart_Error_CouponIsExclusivePromo: _,
    Cart_Error_CouponIsInvalid: _,
    Cart_Error_CouponIsInvalidForItem: _,
    Cart_Error_TooManyInCart: _,
    Cart_Error_CommercialLicenseRestricted_FootNote: _,
    Cart_Error_CommercialLicenseRestricted_LineItem: _,
    Cart_Error_GiftRecipientInvalid: _,
    Cart_Error_MissingMustOwnApps_LineItem: _,
    Cart_Error_MissingMustOwnApps_GiftLineItem: _,
    Cart_Error_MissingMustOwnApps_FootNote: _,
    Cart_Error_MissingMustOwnApps_FootNoteGift: _,
    Cart_Error_ExistingBillingAgreement: _,
    Cart_Error_ExistingBillingAgreement_FootNote: _,
    Cart_Warning_AlreadyOwned_LineItem: _,
    Cart_Warning_ExtraCopies_LineItem: _,
    Cart_Warning_PriceChange_FootNote: _,
    Cart_Warning_PriceChange_LineItem: _,
    Cart_Warning_NoRefund_LineItem: _,
    Cart_Warning_RecipientHigherPrice: _,
    Cart_Warning_AvailableAtALowerPrice: _,
    Cart_Warning_GiftToNonFriend: _,
    Cart_Warning_GiftToNonFriend_Named: _,
    Cart_Warning_GiftToAccount_LoggedOut_Actionable: _,
    Cart_GifteeHint_Wishlist: _,
    PackageIncludesSubscriptionBySecond: _,
    PackageIncludesSubscriptionByMinute: _,
    PackageIncludesSubscriptionByHour: _,
    PackageIncludesSubscriptionByDay: _,
    PackageIncludesSubscriptionByWeek: _,
    PackageIncludesSubscriptionByMonth: _,
    PackageIncludesSubscriptionByYear: _,
    MultiLicenseIncludesSubscriptionBySecond: _,
    MultiLicenseIncludesSubscriptionByMinute: _,
    MultiLicenseIncludesSubscriptionByHour: _,
    MultiLicenseIncludesSubscriptionByDay: _,
    MultiLicenseIncludesSubscriptionByWeek: _,
    MultiLicenseIncludesSubscriptionByMonth: _,
    MultiLicenseeIncludesSubscriptionByYear: _,
    GameBillingPackageIncludesSubscriptionBySecond: _,
    GameBillingPackageIncludesSubscriptionByMinute: _,
    GameBillingPackageIncludesSubscriptionByHour: _,
    GameBillingPackageIncludesSubscriptionByDay: _,
    GameBillingPackageIncludesSubscriptionByWeek: _,
    GameBillingPackageIncludesSubscriptionByMonth: _,
    GameBillingPackageIncludesSubscriptionByYear: _,
    MicroTxnSubscriptionCostBySecond: _,
    MicroTxnSubscriptionCostByMinute: _,
    MicroTxnSubscriptionCostByHour: _,
    MicroTxnSubscriptionCostByDay: _,
    MicroTxnSubscriptionCostByWeek: _,
    MicroTxnSubscriptionCostByMonth: _,
    MicroTxnSubscriptionCostByYear: _,
    GameBillingAuthorizeSubscriptionBySecond: _,
    GameBillingAuthorizeSubscriptionByMinute: _,
    GameBillingAuthorizeSubscriptionByHour: _,
    GameBillingAuthorizeSubscriptionByDay: _,
    GameBillingAuthorizeSubscriptionByWeek: _,
    GameBillingAuthorizeSubscriptionByMonth: _,
    GameBillingAuthorizeSubscriptionByYear: _,
    PackageCostIncludesSubscriptionBySecond: _,
    PackageCostIncludesSubscriptionByMinute: _,
    PackageCostIncludesSubscriptionByHour: _,
    PackageCostIncludesSubscriptionByDay: _,
    PackageCostIncludesSubscriptionByWeek: _,
    PackageCostIncludesSubscriptionByMonth: _,
    PackageCostIncludesSubscriptionByYear: _,
    PackageWithDiscountCostIncludesSubscriptionBySecond: _,
    PackageWithDiscountCostIncludesSubscriptionByMinute: _,
    PackageWithDiscountCostIncludesSubscriptionByHour: _,
    PackageWithDiscountCostIncludesSubscriptionByDay: _,
    PackageWithDiscountCostIncludesSubscriptionByWeek: _,
    PackageWithDiscountCostIncludesSubscriptionByMonth: _,
    PackageWithDiscountCostIncludesSubscriptionByYear: _,
    GameBillingPackageCostIncludesSubscriptionBySecond: _,
    GameBillingPackageCostIncludesSubscriptionByMinute: _,
    GameBillingPackageCostIncludesSubscriptionByHour: _,
    GameBillingPackageCostIncludesSubscriptionByDay: _,
    GameBillingPackageCostIncludesSubscriptionByWeek: _,
    GameBillingPackageCostIncludesSubscriptionByMonth: _,
    GameBillingPackageCostIncludesSubscriptionByYear: _,
    MultiLicenseCostIncludesSubscriptionBySecond: _,
    MultiLicenseCostIncludesSubscriptionByMinute: _,
    MultiLicenseCostIncludesSubscriptionByHour: _,
    MultiLicenseCostIncludesSubscriptionByDay: _,
    MultiLicenseCostIncludesSubscriptionByWeek: _,
    MultiLicenseCostIncludesSubscriptionByMonth: _,
    MultiLicenseCostIncludesSubscriptionByYear: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionBySecond: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMinute: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByHour: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByDay: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByWeek: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMonth: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByYear: _,
    Cart_Empty: _,
    Cart_Notice_SomeAppsPrivate: _,
    Cart_LineItemOptions_PrivateTooltip: _,
    Cart_BetaNotice: _,
    Cart_GenericBetaNotice: _,
    Cart_GiftScheduleError_TooFar: _,
    Cart_GiftScheduleError_InvalidDate: _,
    Cart_LineItem_ErrorBoundary: _,
    Cart_SaleCardDrops_EarnedMessage: _,
    Cart_SaleCardDrops_EarnedMessage_Plural: _,
    Cart_SaleCardDrops_Explanation: _,
    Cart_SaleCardDrops_Explanation_Gifts: _,
    Cart_SaleCardDrops_ProgressLabel: _,
    Cart_SaleCardDrops_CardCost: _,
    Cart_SaleCardDrops_PrepurchaseIneligible: _,
    Cart_PurchaseRequestTitle: _,
    Cart_PurchaseFor_Label: _,
    Cart_GiftForNotice: _,
    Cart_LineItem_Add_Tooltip: _,
    Cart_LineItem_Hardware_Compliance_Label: _,
    Cart_ErrorUpdating: _,
    Cart_ErrorCode: _,
    Cart_UserCountrySelector: _,
    Cart_Replay_SavedCart: _,
    Cart_Replay_Instructions: _,
    Cart_Gifting_CopyGiftOptionsFrom: _,
    Cart_Gifting_SignInToSelectFriends: _,
  };
export {
  _ as Cart_Add,
  _ as Cart_AddedToYourCart,
  _ as Cart_BetaNotice,
  _ as Cart_Bradcrumb_Home,
  _ as Cart_CartLevelErrorFormat,
  _ as Cart_CartLevelErrorMultiple,
  _ as Cart_CartLevelErrorNotice,
  _ as Cart_ChangeGiftRecipient,
  _ as Cart_ComingSoon,
  _ as Cart_ContainsGiftCheckbox,
  _ as Cart_ContinueButton_Gifts,
  _ as Cart_ContinueButton_Login,
  _ as Cart_ContinueButton_Payment,
  _ as Cart_ContinueShopping,
  _ as Cart_CountWidget,
  _ as Cart_CouponAvailability,
  _ as Cart_CouponAvailability_Plural,
  _ as Cart_CouponModify_Add,
  _ as Cart_CouponModify_Change,
  _ as Cart_Coupons_Applied,
  _ as Cart_Coupons_InUse,
  _ as Cart_DeclinePurchaseRequest,
  _ as Cart_Edit,
  _ as Cart_EditGiftDelivery,
  _ as Cart_Empty,
  _ as Cart_EnterRecipientEmail,
  _ as Cart_ErrorCode,
  _ as Cart_ErrorUpdating,
  _ as Cart_Error_AdultContentRestricted_FootNote,
  _ as Cart_Error_AdultContentRestricted_LineItem,
  _ as Cart_Error_AlreadyOwned_FootNote,
  _ as Cart_Error_AlreadyOwned_GiftFootNote,
  _ as Cart_Error_AlreadyOwned_GiftLineItem,
  _ as Cart_Error_AlreadyOwned_GiftLineItem_Game,
  _ as Cart_Error_AlreadyOwned_LineItem,
  _ as Cart_Error_AlreadyOwned_LineItem_Game,
  _ as Cart_Error_CommercialLicenseRestricted_FootNote,
  _ as Cart_Error_CommercialLicenseRestricted_LineItem,
  _ as Cart_Error_CouponIsExclusivePromo,
  _ as Cart_Error_CouponIsInvalid,
  _ as Cart_Error_CouponIsInvalidForItem,
  _ as Cart_Error_DuplicateApps_FootNote,
  _ as Cart_Error_DuplicateApps_LineItem,
  _ as Cart_Error_ExistingBillingAgreement,
  _ as Cart_Error_ExistingBillingAgreement_FootNote,
  _ as Cart_Error_GiftRecipientInvalid,
  _ as Cart_Error_MasterSubscription_FootNote,
  _ as Cart_Error_MasterSubscription_LineItem,
  _ as Cart_Error_MissingMustOwnApps_FootNote,
  _ as Cart_Error_MissingMustOwnApps_FootNoteGift,
  _ as Cart_Error_MissingMustOwnApps_GiftLineItem,
  _ as Cart_Error_MissingMustOwnApps_LineItem,
  _ as Cart_Error_TooManyInCart,
  _ as Cart_Error_UnavailableCountry_FootNote,
  _ as Cart_Error_UnavailableCountry_LineItem,
  _ as Cart_EstimatedTotal,
  _ as Cart_FamilyGift_Notice,
  _ as Cart_FooterNoticeHeader_MustFix,
  _ as Cart_FooterNoticeHeader_Warning,
  _ as Cart_GenericBetaNotice,
  _ as Cart_GiftDeliveryEmail_Warning1,
  _ as Cart_GiftDeliveryEmail_Warning2,
  _ as Cart_GiftDelivery_AddSignature,
  _ as Cart_GiftDelivery_Body,
  _ as Cart_GiftDelivery_From,
  _ as Cart_GiftDelivery_Label,
  _ as Cart_GiftDelivery_Now,
  _ as Cart_GiftDelivery_Reset,
  _ as Cart_GiftDelivery_ScheduleDelivery,
  _ as Cart_GiftDelivery_Scheduled,
  _ as Cart_GiftDelivery_Signature,
  _ as Cart_GiftForNotice,
  _ as Cart_GiftOptions,
  _ as Cart_GiftRecipientEmail_Label,
  _ as Cart_GiftRecipientModal_IssueLoading,
  _ as Cart_GiftRecipientModal_OnWishlist,
  _ as Cart_GiftRecipientModal_OwnsGameLabel,
  _ as Cart_GiftRecipientModal_PartialOwnsLabel,
  _ as Cart_GiftRecipientModal_PartialWishlistLabel,
  _ as Cart_GiftRecipientModal_Placeholder,
  _ as Cart_GiftRecipientModal_Save,
  _ as Cart_GiftRecipientModal_Title,
  _ as Cart_GiftRecipient_Label,
  _ as Cart_GiftScheduleError_InvalidDate,
  _ as Cart_GiftScheduleError_TooFar,
  _ as Cart_GifteeHint_Wishlist,
  _ as Cart_Gifting_CopyGiftOptionsFrom,
  _ as Cart_Gifting_SignInToSelectFriends,
  _ as Cart_IncludesItems,
  _ as Cart_IncludesItems_Plural,
  _ as Cart_LineItemGift_Checkbox,
  _ as Cart_LineItemOptions_Gift,
  _ as Cart_LineItemOptions_GiftForPersona,
  _ as Cart_LineItemOptions_Myself,
  _ as Cart_LineItemOptions_PrivateTooltip,
  _ as Cart_LineItemOptions_Privately,
  _ as Cart_LineItem_Add_Tooltip,
  _ as Cart_LineItem_ErrorBoundary,
  _ as Cart_LineItem_Hardware_Compliance_Label,
  _ as Cart_Note_SalesTax,
  _ as Cart_Notice_SomeAppsPrivate,
  _ as Cart_PurchaseBtn,
  _ as Cart_PurchaseFor_Label,
  _ as Cart_PurchaseRequestTitle,
  _ as Cart_Quantity,
  _ as Cart_Remove,
  _ as Cart_RemoveAll,
  _ as Cart_Replay_Instructions,
  _ as Cart_Replay_SavedCart,
  _ as Cart_RequestPurchase,
  _ as Cart_RequestPurchaseExplanation,
  _ as Cart_RequestPurchaseNonGiftableItems,
  _ as Cart_SaleCardDrops_CardCost,
  _ as Cart_SaleCardDrops_EarnedMessage,
  _ as Cart_SaleCardDrops_EarnedMessage_Plural,
  _ as Cart_SaleCardDrops_Explanation,
  _ as Cart_SaleCardDrops_Explanation_Gifts,
  _ as Cart_SaleCardDrops_PrepurchaseIneligible,
  _ as Cart_SaleCardDrops_ProgressLabel,
  _ as Cart_SelectCouponToApply,
  _ as Cart_SelectRecipient,
  _ as Cart_ShippingEstimate_Delayed,
  _ as Cart_ShippingEstimate_DeliveryDate,
  _ as Cart_ShippingEstimate_Range,
  _ as Cart_ShippingEstimate_Standard,
  _ as Cart_UpdatedYourCart,
  _ as Cart_UserCountrySelector,
  _ as Cart_Verify,
  _ as Cart_ViewMyCart,
  _ as Cart_Warning_AlreadyOwned_LineItem,
  _ as Cart_Warning_AvailableAtALowerPrice,
  _ as Cart_Warning_ExtraCopies_LineItem,
  _ as Cart_Warning_GiftToAccount_LoggedOut_Actionable,
  _ as Cart_Warning_GiftToNonFriend,
  _ as Cart_Warning_GiftToNonFriend_Named,
  _ as Cart_Warning_NoRefund_LineItem,
  _ as Cart_Warning_PriceChange_FootNote,
  _ as Cart_Warning_PriceChange_LineItem,
  _ as Cart_Warning_RecipientHigherPrice,
  _ as Cart_YourShoppingCart,
  _ as Cart_YourShoppingCartLineItems,
  _ as Cart_YourShoppingCartLineItems_Plural,
  _ as GameBillingAuthorizeSubscriptionByDay,
  _ as GameBillingAuthorizeSubscriptionByHour,
  _ as GameBillingAuthorizeSubscriptionByMinute,
  _ as GameBillingAuthorizeSubscriptionByMonth,
  _ as GameBillingAuthorizeSubscriptionBySecond,
  _ as GameBillingAuthorizeSubscriptionByWeek,
  _ as GameBillingAuthorizeSubscriptionByYear,
  _ as GameBillingPackageCostIncludesSubscriptionByDay,
  _ as GameBillingPackageCostIncludesSubscriptionByHour,
  _ as GameBillingPackageCostIncludesSubscriptionByMinute,
  _ as GameBillingPackageCostIncludesSubscriptionByMonth,
  _ as GameBillingPackageCostIncludesSubscriptionBySecond,
  _ as GameBillingPackageCostIncludesSubscriptionByWeek,
  _ as GameBillingPackageCostIncludesSubscriptionByYear,
  _ as GameBillingPackageIncludesSubscriptionByDay,
  _ as GameBillingPackageIncludesSubscriptionByHour,
  _ as GameBillingPackageIncludesSubscriptionByMinute,
  _ as GameBillingPackageIncludesSubscriptionByMonth,
  _ as GameBillingPackageIncludesSubscriptionBySecond,
  _ as GameBillingPackageIncludesSubscriptionByWeek,
  _ as GameBillingPackageIncludesSubscriptionByYear,
  _ as MicroTxnSubscriptionCostByDay,
  _ as MicroTxnSubscriptionCostByHour,
  _ as MicroTxnSubscriptionCostByMinute,
  _ as MicroTxnSubscriptionCostByMonth,
  _ as MicroTxnSubscriptionCostBySecond,
  _ as MicroTxnSubscriptionCostByWeek,
  _ as MicroTxnSubscriptionCostByYear,
  _ as MultiLicenseCostIncludesSubscriptionByDay,
  _ as MultiLicenseCostIncludesSubscriptionByHour,
  _ as MultiLicenseCostIncludesSubscriptionByMinute,
  _ as MultiLicenseCostIncludesSubscriptionByMonth,
  _ as MultiLicenseCostIncludesSubscriptionBySecond,
  _ as MultiLicenseCostIncludesSubscriptionByWeek,
  _ as MultiLicenseCostIncludesSubscriptionByYear,
  _ as MultiLicenseIncludesSubscriptionByDay,
  _ as MultiLicenseIncludesSubscriptionByHour,
  _ as MultiLicenseIncludesSubscriptionByMinute,
  _ as MultiLicenseIncludesSubscriptionByMonth,
  _ as MultiLicenseIncludesSubscriptionBySecond,
  _ as MultiLicenseIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByDay,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByHour,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMinute,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMonth,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionBySecond,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByYear,
  _ as MultiLicenseeIncludesSubscriptionByYear,
  _ as PackageCostIncludesSubscriptionByDay,
  _ as PackageCostIncludesSubscriptionByHour,
  _ as PackageCostIncludesSubscriptionByMinute,
  _ as PackageCostIncludesSubscriptionByMonth,
  _ as PackageCostIncludesSubscriptionBySecond,
  _ as PackageCostIncludesSubscriptionByWeek,
  _ as PackageCostIncludesSubscriptionByYear,
  _ as PackageIncludesSubscriptionByDay,
  _ as PackageIncludesSubscriptionByHour,
  _ as PackageIncludesSubscriptionByMinute,
  _ as PackageIncludesSubscriptionByMonth,
  _ as PackageIncludesSubscriptionBySecond,
  _ as PackageIncludesSubscriptionByWeek,
  _ as PackageIncludesSubscriptionByYear,
  _ as PackageWithDiscountCostIncludesSubscriptionByDay,
  _ as PackageWithDiscountCostIncludesSubscriptionByHour,
  _ as PackageWithDiscountCostIncludesSubscriptionByMinute,
  _ as PackageWithDiscountCostIncludesSubscriptionByMonth,
  _ as PackageWithDiscountCostIncludesSubscriptionBySecond,
  _ as PackageWithDiscountCostIncludesSubscriptionByWeek,
  _ as PackageWithDiscountCostIncludesSubscriptionByYear,
  _ as default,
  _ as language,
};
