var _ = `dutch`,
  _ = `Verwijderen`,
  _ = `Toevoegen`,
  _ = `Leeftijd verifiëren`,
  _ = `Alle artikelen verwijderen`,
  _ = `Wijzigen`,
  _ = `Aantal: %1$s`,
  _ = `Jouw winkelwagen`,
  _ = `Jouw winkelwagen (%1$s artikel)`,
  _ = `Jouw winkelwagen (%1$s artikelen)`,
  _ = `Geschat totaal`,
  _ = `Zo nodig wordt er btw berekend bij het afrekenen`,
  _ = `Aankoop`,
  _ = `Deze aankoop bevat een geschenk`,
  _ = `Startpagina`,
  _ = `Is dit een geschenk?`,
  _ = `Bevat %1$s artikel`,
  _ = `Bevat %1$s artikelen`,
  _ = `Ontvanger selecteren`,
  _ = `E-mailadres invoeren`,
  _ = `Ontvanger van het geschenk bewerken...`,
  _ = `Ontvanger van het geschenk:`,
  _ = `E-mailadres van ontvanger van het geschenk:`,
  _ = `Levering:`,
  _ = `Opnieuw instellen`,
  _ = `Zo snel mogelijk (via e-mail en Steam-client)`,
  _ = `Gepland:`,
  _ = `Levering inplannen`,
  _ = `Van:`,
  _ = `Je handtekening:`,
  _ = `Gepersonaliseerde handtekening toevoegen`,
  _ = `Boodschap bij geschenk (maximaal 160 tekens; %1$s over):`,
  _ = `Geschenken die per e-mail zijn verzonden, worden na 30 dagen automatisch terugbetaald als ze niet aan een Steam-account zijn toegevoegd.`,
  _ = `Geschenken die per e-mail zijn verzonden, kunnen alleen worden geaccepteerd door Steam-accounts in dezelfde regio als de koper (%1$s).`,
  _ = `Geschenken die naar kinderen in je Steam-gezin worden verzonden, worden automatisch toegevoegd aan hun account en hun toegestane spellen.`,
  _ = `Ontvanger van het geschenk selecteren`,
  _ = `Bezorgmethode bewerken`,
  _ = `Opslaan`,
  _ = `Op naam van vriend zoeken...`,
  _ = `Heeft dit artikel al`,
  _ = `Op de verlanglijst`,
  _ = `Heeft %1$s al`,
  _ = `Wil %1$s graag hebben`,
  _ = `Geschenkopties`,
  _ = `Er is een probleem opgetreden bij het laden van mogelijke ontvangers van dit geschenk. Probeer het later opnieuw.`,
  _ = `Doorgaan naar betaling`,
  _ = `Doorgaan naar geschenkopties`,
  _ = `Inloggen om te kopen`,
  _ = `Aanvraag weigeren`,
  _ = `Voor mijn account`,
  _ = `Dit is een geschenk`,
  _ = `Dit is een geschenk voor %1$s`,
  _ = `Voor mijn account: privé`,
  _ = `Winkelwagen (%1$s)`,
  _ = `Toegevoegd aan je winkelwagen!`,
  _ = `Winkelwagen bijgewerkt!`,
  _ = `Doorgaan met winkelen`,
  _ = `Beschikbaar %1$s`,
  _ = `Mijn winkelwagen bekijken (%1$s)`,
  _ = `Aankoop aanvragen`,
  _ = `We brengen de volwassenen in je Steam-gezin op de hoogte van je aankoopaanvraag.`,
  _ = `Kan geen aankoop aanvragen omdat niet alle artikelen in je winkelwagen als geschenk gekocht kunnen worden`,
  _ = `Coupon wijzigen/verwijderen`,
  _ = `Coupon toevoegen`,
  _ = `Je hebt een beschikbare coupon voor dit artikel`,
  _ = `Je hebt %1$s beschikbare coupons voor dit artikel`,
  _ = `Momenteel toegepast`,
  _ = `Momenteel toegepast op een ander product`,
  _ = `Selecteer een coupon om voor %1$s te gebruiken`,
  _ = `Verwachte levering: %1$s`,
  _ = `%1$s-%2$s werkdagen`,
  _ = `Verwachte levertijd: 6-10 werkdagen`,
  _ = `Verwachte levertijd: 3-5 werkdagen`,
  _ = `Voordat je kunt doorgaan naar betaling:`,
  _ = `Let op:`,
  _ = `Actie vereist voordat je kunt doorgaan naar betaling`,
  _ = `Let op:`,
  _ = `Let op: %1$s`,
  _ = `Je account bezit al een paar van de bovenstaande artikelen, dus je kunt ze niet opnieuw kopen. Je kunt deze artikelen als geschenk kopen of de inhoud van je winkelwagen aanpassen om verder te gaan.`,
  _ = `Je hebt dit spel al`,
  _ = `Je hebt alles al van dit pakket`,
  _ = `De ontvanger van dit geschenk heeft dit spel al`,
  _ = `De ontvanger van dit geschenk heeft alles al van dit pakket`,
  _ = `De ontvanger van dit geschenk heeft een paar van de bovenstaande artikelen al, dus je kunt ze niet opnieuw kopen. Je kunt deze artikelen aan iemand anders geven of de inhoud van je winkelwagen aanpassen om verder te gaan.`,
  _ = `Je hebt een aantal pakketten in je winkelwagen die elkaar overlappen. Je moet de overlappende pakketten uit je winkelwagen halen voordat je naar de kassa kunt gaan.`,
  _ = `Al in je winkelwagen: `,
  _ = `Je winkelwagen bevat een pakket dat niet beschikbaar is in jouw land. Je moet het pakket uit je winkelwagen verwijderen voordat je kunt afrekenen.`,
  _ = `Niet beschikbaar in je land`,
  _ = `Valve is verplicht om te controleren of je 18 jaar of ouder bent voordat je seksuele inhoud voor volwassenen mag kopen.`,
  _ = `Kan niet gekocht worden voor je je leeftijd hebt geverifieerd.`,
  _ = `Je winkelwagen bevat inhoud die ook beschikbaar is via een van je actieve abonnementen.`,
  _ = `Beschikbaar via je abonnement op:`,
  _ = `Deze coupon kan niet worden gebruikt in combinatie met andere kortingen.`,
  _ = `Deze coupon is ongeldig of verlopen.`,
  _ = `Deze coupon kan niet op dit artikel worden toegepast.`,
  _ = `Je hebt het maximaal toegestane aantal voor dit artikel overschreden.`,
  _ = `Je winkelwagen bevat een artikel dat niet kan worden gekocht.`,
  _ = `Kan niet worden gekocht`,
  _ = `De geselecteerde ontvanger kan dit geschenk niet ontvangen, omdat het in jouw regio is gekocht.`,
  _ = `Als je dit artikel wilt kopen, moet je de volgende artikelen bezitten:`,
  _ = `Dit artikel vereist dat de ontvanger van het geschenk de volgende artikelen bezit:`,
  _ = `Je account beschikt niet over bepaalde artikelen die vereist zijn om de artikelen in je winkelwagen te kopen. Je kunt de ontbrekende artikelen toevoegen of de inhoud van je winkelwagen aanpassen om verder te gaan.`,
  _ = `De ontvanger van het geschenk beschikt niet over bepaalde artikelen die vereist zijn om de artikelen in je winkelwagen te kopen. Je kunt de ontbrekende artikelen toevoegen of de inhoud van je winkelwagen aanpassen om verder te gaan.`,
  _ = `Je hebt al een abonnement op dit artikel.`,
  _ = `Je account is al geabonneerd op een aantal van de bovenstaande artikelen. Bekijk je instellingen voor abonnementen in je accountgegevens.`,
  _ = `Indien je dit voor jezelf koopt, ontvang je geen extra kopie van:`,
  _ = `Indien je dit voor jezelf koopt, ontvang je een extra kopie om als geschenk te geven van:`,
  _ = `Een of meer artikelen hieronder zijn van prijs veranderd sinds je ze aan je winkelwagen hebt toegevoegd.`,
  _ = `De prijs van dit artikel is veranderd`,
  _ = `Dit product bevat verbruikbare inhoud waardoor een terugbetaling niet mogelijk is.`,
  _ = `De ontvanger die je hebt geselecteerd, woont in een regio met hogere prijzen. De prijs van het artikel is aangepast aan de regio waar je geschenk naartoe gaat, zodat je het aan deze ontvanger cadeau kunt doen.`,
  _ = `Dit artikel is beschikbaar voor een lagere prijs als onderdeel van %1$s.`,
  _ = `De ontvanger van je geschenk staat NIET op je Steam-vriendenlijst.`,
  _ = `LET OP: %1$s staat niet op je Steam-vriendenlijst.`,
  _ = `Als je een geschenk naar een Steam-vriend wilt sturen, <1>log dan eerst in</1> om te controleren of de ontvanger op je vriendenlijst staat.`,
  _ = `Je hebt onlangs de verlanglijst van %1$s bekeken. Wil je deze artikelen cadeau doen?`,
  _ = `Abonnement wordt elke %2$s seconde(n) voor %1$s gefactureerd.`,
  _ = `Abonnement wordt elke %2$s minuut/minuten voor %1$s gefactureerd.`,
  _ = `Abonnement wordt elk(e) %2$s uur voor %1$s gefactureerd.`,
  _ = `Abonnement wordt elke %2$s dag(en) voor %1$s gefactureerd.`,
  _ = `Abonnement wordt elke %2$s week/weken voor %1$s gefactureerd.`,
  _ = `Abonnement wordt elke %2$s maand(en) voor %1$s gefactureerd.`,
  _ = `Abonnement wordt elk(e) %2$s jaar voor %1$s gefactureerd.`,
  _ = `Abonnement wordt per licentie elke %2$s seconde(n) voor %1$s gefactureerd.`,
  _ = `Abonnement wordt per licentie elke %2$s minuut/minuten voor %1$s gefactureerd.`,
  _ = `Abonnement wordt per licentie elk(e) %2$s uur voor %1$s gefactureerd.`,
  _ = `Abonnement wordt per licentie elke %2$s dag(en) voor %1$s gefactureerd.`,
  _ = `Abonnement wordt per licentie elke %2$s week/weken voor %1$s gefactureerd.`,
  _ = `Abonnement wordt per licentie elke %2$s maand(en) voor %1$s gefactureerd.`,
  _ = `Abonnement wordt per licentie elk(e) %2$s jaar voor %1$s gefactureerd.`,
  _ = `Abonnement wordt elke %2$s seconde(n) voor %1$s gefactureerd, of zoals opgegeven door je spelaccount.`,
  _ = `Abonnement wordt elke %2$s minuut/minuten voor %1$s gefactureerd, of zoals opgegeven door je spelaccount.`,
  _ = `Abonnement wordt elk(e) %2$s uur voor %1$s gefactureerd, of zoals opgegeven door je spelaccount.`,
  _ = `Abonnement wordt elke %2$s dag(en) voor %1$s gefactureerd, of zoals opgegeven door je spelaccount.`,
  _ = `Abonnement wordt elke %2$s week/weken voor %1$s gefactureerd, of zoals opgegeven door je spelaccount.`,
  _ = `Abonnement wordt elke %2$s maand(en) voor %1$s gefactureerd, of zoals opgegeven door je spelaccount.`,
  _ = `Abonnement wordt elk(e) %2$s jaar voor %1$s gefactureerd, of zoals opgegeven door je spelaccount.`,
  _ = `Er wordt %1$s in rekening gebracht bij het afrekenen.<br/>Je gaat ermee akkoord dat er elke %3$s second(en) %2$s in rekening wordt gebracht.`,
  _ = `Er wordt %1$s in rekening gebracht bij het afrekenen.<br/>Je gaat ermee akkoord dat er elke %3$s minuten %2$s in rekening wordt gebracht.`,
  _ = `Er wordt %1$s in rekening gebracht bij het afrekenen.<br/>Je gaat ermee akkoord dat er elke %3$s uur %2$s in rekening wordt gebracht.`,
  _ = `Er wordt %1$s in rekening gebracht bij het afrekenen.<br/>Je gaat ermee akkoord dat er elke %3$s dag(en) %2$s in rekening wordt gebracht.`,
  _ = `Er wordt %1$s in rekening gebracht bij het afrekenen.<br/>Je gaat ermee akkoord dat er elke %3$s week/weken %2$s in rekening wordt gebracht.`,
  _ = `Er wordt %1$s in rekening gebracht bij het afrekenen.<br/>Je gaat ermee akkoord dat er elke %3$s maand(en) %2$s in rekening wordt gebracht.`,
  _ = `Bij het afrekenen zal %1$s in rekening worden gebracht.<br/>Je stemt in met automatische afschrijving van %2$s per %3$s jaar.`,
  _ = `Bij het afrekenen zal %1$s in rekening worden gebracht.<br/>Je stemt in met vervolgafschrijvingen tot maximaal %2$s per %3$s seconde(n).`,
  _ = `Bij het afrekenen zal %1$s in rekening worden gebracht.<br/>Je stemt in met vervolgafschrijvingen tot maximaal %2$s per %3$s minuut/minuten.`,
  _ = `Bij het afrekenen zal %1$s in rekening worden gebracht.<br/>Je stemt in met vervolgafschrijvingen tot maximaal %2$s per %3$s uur.`,
  _ = `Bij het afrekenen zal %1$s in rekening worden gebracht.<br/>Je stemt in met vervolgafschrijvingen tot maximaal %2$s per %3$s dag(en).`,
  _ = `Bij het afrekenen zal %1$s in rekening worden gebracht.<br/>Je stemt in met vervolgafschrijvingen tot maximaal %2$s per %3$s week/weken.`,
  _ = `Bij het afrekenen zal %1$s in rekening worden gebracht.<br/>Je autoriseert dit spel voor vervolgafschrijvingen tot maximaal %2$s per %3$s maand(en).`,
  _ = `Bij het afrekenen zal %1$s in rekening worden gebracht.<br/>Je autoriseert dit spel voor vervolgafschrijvingen tot maximaal %2$s per %3$s jaar.`,
  _ = `%1$s bij afrekening, wordt elke %3$s seconde(n) automatisch verlengd voor %2$s.`,
  _ = `%1$s bij afrekening, wordt elke %3$s minuut/minuten automatisch verlengd voor %2$s.`,
  _ = `%1$s bij afrekening, wordt elk(e) %3$s uur automatisch verlengd voor %2$s.`,
  _ = `%1$s bij afrekening, wordt elke %3$s dag(en) automatisch verlengd voor %2$s.`,
  _ = `%1$s bij afrekening, wordt elke %3$s week/weken automatisch verlengd voor %2$s.`,
  _ = `%1$s bij afrekening, wordt elke %3$s maand(en) automatisch verlengd voor %2$s.`,
  _ = `%1$s bij afrekening, wordt elk(e) %3$s jaar automatisch verlengd voor %2$s.`,
  _ = `Bij de eerste aankoop krijg je %4$s% korting en betaal je dus %1$s. Vervolgens wordt het abonnement elke %3$s seconde(n) automatisch verlengd voor %2$s.`,
  _ = `Bij de eerste aankoop krijg je %4$s% korting en betaal je dus %1$s. Vervolgens wordt het abonnement elke %3$s minuut/minuten automatisch verlengd voor %2$s.`,
  _ = `Bij de eerste aankoop krijg je %4$s% korting en betaal je dus %1$s. Vervolgens wordt het abonnement elk(e) %3$s uur automatisch verlengd voor %2$s.`,
  _ = `Bij de eerste aankoop krijg je %4$s% korting en betaal je dus %1$s. Vervolgens wordt het abonnement elke %3$s dag(en) automatisch verlengd voor %2$s.`,
  _ = `Bij de eerste aankoop krijg je %4$s% korting en betaal je dus %1$s. Vervolgens wordt het abonnement elke %3$s week/weken automatisch verlengd voor %2$s.`,
  _ = `Bij de eerste aankoop krijg je %4$s% korting en betaal je dus %1$s. Vervolgens wordt het abonnement elke %3$s maand(en) automatisch verlengd voor %2$s.`,
  _ = `Bij de eerste aankoop krijg je %4$s% korting en betaal je dus %1$s. Vervolgens wordt het abonnement elk(e) %3$s jaar automatisch verlengd voor %2$s.`,
  _ = `%1$s bij afrekening, wordt elke %3$s seconde(n) automatisch verlengd voor %2$s, zoals opgegeven door je spelaccount.`,
  _ = `%1$s bij afrekening, wordt elke %3$s minuut/minuten automatisch verlengd voor %2$s, zoals opgegeven door je spelaccount.`,
  _ = `%1$s bij afrekening, wordt elk(e) %3$s uur automatisch verlengd voor %2$s, zoals opgegeven door je spelaccount.`,
  _ = `%1$s bij afrekening, wordt elke %3$s dag(en) automatisch verlengd voor %2$s, zoals opgegeven door je spelaccount.`,
  _ = `%1$s bij afrekening, wordt elke %3$s week/weken automatisch verlengd voor %2$s, zoals opgegeven door je spelaccount.`,
  _ = `%1$s bij afrekening, wordt elke %3$s maand(en) automatisch verlengd voor %2$s, zoals opgegeven door je spelaccount.`,
  _ = `%1$s bij afrekening, wordt elk(e) %3$s jaar automatisch verlengd voor %2$s, zoals opgegeven door je spelaccount.`,
  _ = `%1$s bij afrekening, wordt per licentie elke %3$s seconde(n) automatisch verlengd voor %2$s.`,
  _ = `%1$s bij afrekening, wordt elke %3$s minuut/minuten automatisch verlengd voor %2$s per licentie.`,
  _ = `%1$s bij afrekening, wordt elk(e) %3$s uur automatisch verlengd voor %2$s per licentie.`,
  _ = `%1$s bij afrekening, wordt elke %3$s dag(en) automatisch verlengd voor %2$s per licentie.`,
  _ = `%1$s bij afrekening, wordt elke %3$s week/weken automatisch verlengd voor %2$s per licentie.`,
  _ = `%1$s bij afrekening, wordt elke %3$s maand(en) automatisch verlengd voor %2$s per licentie.`,
  _ = `%1$s bij afrekening, wordt elk(e) %3$s jaar automatisch verlengd voor %2$s per licentie.`,
  _ = `Bij de eerste aankoop krijg je %4$s% korting en betaal je dus %1$s. Vervolgens wordt het abonnement elke %3$s seconde(n) automatisch verlengd voor %2$s per licentie.`,
  _ = `Bij de eerste aankoop krijg je %4$s% korting en betaal je dus %1$s. Vervolgens wordt het abonnement elke %3$s minuut/minuten automatisch verlengd voor %2$s per licentie.`,
  _ = `Bij de eerste aankoop krijg je %4$s% korting en betaal je dus %1$s. Vervolgens wordt het abonnement elk(e) %3$s uur automatisch verlengd voor %2$s per licentie.`,
  _ = `Bij de eerste aankoop krijg je %4$s% korting en betaal je dus %1$s. Vervolgens wordt het abonnement elke %3$s dag(en) automatisch verlengd voor %2$s per licentie.`,
  _ = `Bij de eerste aankoop krijg je %4$s% korting en betaal je dus %1$s. Vervolgens wordt het abonnement elke %3$s week/weken automatisch verlengd voor %2$s per licentie.`,
  _ = `Bij de eerste aankoop krijg je %4$s% korting en betaal je dus %1$s. Vervolgens wordt het abonnement elke %3$s maand(en) automatisch verlengd voor %2$s per licentie.`,
  _ = `Bij de eerste aankoop krijg je %4$s% korting en betaal je dus %1$s. Vervolgens wordt het abonnement elk(e) %3$s jaar automatisch verlengd voor %2$s per licentie.`,
  _ = `Je winkelwagen is leeg.`,
  _ = `Sommige artikelen zijn al als privé gemarkeerd. Ze blijven privé als je doorgaat:`,
  _ = `Als je een spel markeert als privé wordt het overal verborgen, behalve in je bibliotheek. Je eigenaarschap, je status in het spel, je speeltijd en alle andere spelactiviteiten zijn niet zichtbaar voor anderen.`,
  _ = `Je ziet een nieuwe versie van de winkelwagen omdat je deelneemt aan de bètaversie van de Steam-client. <1>Feedback geven of bugs melden</1>`,
  _ = `Dit is de bètaversie van onze nieuwe winkelwagen. <1>Je kunt feedback geven of bugs melden</1>`,
  _ = `Je kunt een geschenk niet zo ver vooruit plannen.`,
  _ = `Voer een geldige datum en tijd in.`,
  _ = `Er is een probleem opgetreden bij het weergeven van dit artikel.`,
  _ = `Met deze aankoop verdien je %1$s %2$s-ruilkaart.`,
  _ = `Met deze aankoop verdien je %1$s %2$s-ruilkaarten.`,
  _ = `Aankopen gedaan in the Steam-winkel tijdens de uitverkoop leveren je %1$s-ruilkaarten op.`,
  _ = `Je krijgt de verdiende kaarten zelfs als je dit als geschenk koopt.`,
  _ = `Voortgang tot volgende kaart`,
  _ = `ongeveer %1$s per kaart`,
  _ = `Let op: Artikelen uit de voorverkoop tellen niet mee voor %1$s-ruilkaartbeloningen. Je krijgt geen ruilkaartbeloningen voor de volgende artikelen:`,
  _ = `Aankoopaanvraag voor %1$s`,
  _ = `Een aankoop voor:`,
  _ = `Als geschenk kopen: %1$s`,
  _ = `Nog een exemplaar van dit artikel toevoegen aan je winkelwagen`,
  _ = `Conformiteitsverklaring PSTI-wet (VK)`,
  _ = `Er is een probleem met het bijwerken van je winkelwagen.`,
  _ = `Foutcode: %1$s`,
  _ = `Land`,
  _ = `Opgeslagen winkelwagen`,
  _ = `Dit is een opgeslagen winkelwagen. De laatste keer dat je hebt geprobeerd de artikelen in deze winkelwagen te kopen, is er iets fout gegaan. Daarom hebben we je winkelwagen (inclusief kortingen) voor %1$s uur opgeslagen, zodat je het nog eens kunt proberen.`,
  _ = `Geschenkopties kopiëren van`,
  _ = `<1>Log in</1> om Steam-vrienden te selecteren`,
  _ = {
    language: _,
    Cart_Remove: _,
    Cart_Add: _,
    Cart_Verify: _,
    Cart_RemoveAll: _,
    Cart_Edit: _,
    Cart_Quantity: _,
    Cart_YourShoppingCart: _,
    Cart_YourShoppingCartLineItems: _,
    Cart_YourShoppingCartLineItems_Plural: _,
    Cart_EstimatedTotal: _,
    Cart_Note_SalesTax: _,
    Cart_PurchaseBtn: _,
    Cart_ContainsGiftCheckbox: _,
    Cart_Bradcrumb_Home: _,
    Cart_LineItemGift_Checkbox: _,
    Cart_IncludesItems: _,
    Cart_IncludesItems_Plural: _,
    Cart_SelectRecipient: _,
    Cart_EnterRecipientEmail: _,
    Cart_ChangeGiftRecipient: _,
    Cart_GiftRecipient_Label: _,
    Cart_GiftRecipientEmail_Label: _,
    Cart_GiftDelivery_Label: _,
    Cart_GiftDelivery_Reset: _,
    Cart_GiftDelivery_Now: _,
    Cart_GiftDelivery_Scheduled: _,
    Cart_GiftDelivery_ScheduleDelivery: _,
    Cart_GiftDelivery_From: _,
    Cart_GiftDelivery_Signature: _,
    Cart_GiftDelivery_AddSignature: _,
    Cart_GiftDelivery_Body: _,
    Cart_GiftDeliveryEmail_Warning1: _,
    Cart_GiftDeliveryEmail_Warning2: _,
    Cart_FamilyGift_Notice: _,
    Cart_GiftRecipientModal_Title: _,
    Cart_EditGiftDelivery: _,
    Cart_GiftRecipientModal_Save: _,
    Cart_GiftRecipientModal_Placeholder: _,
    Cart_GiftRecipientModal_OwnsGameLabel: _,
    Cart_GiftRecipientModal_OnWishlist: _,
    Cart_GiftRecipientModal_PartialOwnsLabel: _,
    Cart_GiftRecipientModal_PartialWishlistLabel: _,
    Cart_GiftOptions: _,
    Cart_GiftRecipientModal_IssueLoading: _,
    Cart_ContinueButton_Payment: _,
    Cart_ContinueButton_Gifts: _,
    Cart_ContinueButton_Login: _,
    Cart_DeclinePurchaseRequest: _,
    Cart_LineItemOptions_Myself: _,
    Cart_LineItemOptions_Gift: _,
    Cart_LineItemOptions_GiftForPersona: _,
    Cart_LineItemOptions_Privately: _,
    Cart_CountWidget: _,
    Cart_AddedToYourCart: _,
    Cart_UpdatedYourCart: _,
    Cart_ContinueShopping: _,
    Cart_ComingSoon: _,
    Cart_ViewMyCart: _,
    Cart_RequestPurchase: _,
    Cart_RequestPurchaseExplanation: _,
    Cart_RequestPurchaseNonGiftableItems: _,
    Cart_CouponModify_Change: _,
    Cart_CouponModify_Add: _,
    Cart_CouponAvailability: _,
    Cart_CouponAvailability_Plural: _,
    Cart_Coupons_Applied: _,
    Cart_Coupons_InUse: _,
    Cart_SelectCouponToApply: _,
    Cart_ShippingEstimate_DeliveryDate: _,
    Cart_ShippingEstimate_Range: _,
    Cart_ShippingEstimate_Delayed: _,
    Cart_ShippingEstimate_Standard: _,
    Cart_FooterNoticeHeader_MustFix: _,
    Cart_FooterNoticeHeader_Warning: _,
    Cart_CartLevelErrorNotice: _,
    Cart_CartLevelErrorMultiple: _,
    Cart_CartLevelErrorFormat: _,
    Cart_Error_AlreadyOwned_FootNote: _,
    Cart_Error_AlreadyOwned_LineItem_Game: _,
    Cart_Error_AlreadyOwned_LineItem: _,
    Cart_Error_AlreadyOwned_GiftLineItem_Game: _,
    Cart_Error_AlreadyOwned_GiftLineItem: _,
    Cart_Error_AlreadyOwned_GiftFootNote: _,
    Cart_Error_DuplicateApps_FootNote: _,
    Cart_Error_DuplicateApps_LineItem: _,
    Cart_Error_UnavailableCountry_FootNote: _,
    Cart_Error_UnavailableCountry_LineItem: _,
    Cart_Error_AdultContentRestricted_FootNote: _,
    Cart_Error_AdultContentRestricted_LineItem: _,
    Cart_Error_MasterSubscription_FootNote: _,
    Cart_Error_MasterSubscription_LineItem: _,
    Cart_Error_CouponIsExclusivePromo: _,
    Cart_Error_CouponIsInvalid: _,
    Cart_Error_CouponIsInvalidForItem: _,
    Cart_Error_TooManyInCart: _,
    Cart_Error_CommercialLicenseRestricted_FootNote: _,
    Cart_Error_CommercialLicenseRestricted_LineItem: _,
    Cart_Error_GiftRecipientInvalid: _,
    Cart_Error_MissingMustOwnApps_LineItem: _,
    Cart_Error_MissingMustOwnApps_GiftLineItem: _,
    Cart_Error_MissingMustOwnApps_FootNote: _,
    Cart_Error_MissingMustOwnApps_FootNoteGift: _,
    Cart_Error_ExistingBillingAgreement: _,
    Cart_Error_ExistingBillingAgreement_FootNote: _,
    Cart_Warning_AlreadyOwned_LineItem: _,
    Cart_Warning_ExtraCopies_LineItem: _,
    Cart_Warning_PriceChange_FootNote: _,
    Cart_Warning_PriceChange_LineItem: _,
    Cart_Warning_NoRefund_LineItem: _,
    Cart_Warning_RecipientHigherPrice: _,
    Cart_Warning_AvailableAtALowerPrice: _,
    Cart_Warning_GiftToNonFriend: _,
    Cart_Warning_GiftToNonFriend_Named: _,
    Cart_Warning_GiftToAccount_LoggedOut_Actionable: _,
    Cart_GifteeHint_Wishlist: _,
    PackageIncludesSubscriptionBySecond: _,
    PackageIncludesSubscriptionByMinute: _,
    PackageIncludesSubscriptionByHour: _,
    PackageIncludesSubscriptionByDay: _,
    PackageIncludesSubscriptionByWeek: _,
    PackageIncludesSubscriptionByMonth: _,
    PackageIncludesSubscriptionByYear: _,
    MultiLicenseIncludesSubscriptionBySecond: _,
    MultiLicenseIncludesSubscriptionByMinute: _,
    MultiLicenseIncludesSubscriptionByHour: _,
    MultiLicenseIncludesSubscriptionByDay: _,
    MultiLicenseIncludesSubscriptionByWeek: _,
    MultiLicenseIncludesSubscriptionByMonth: _,
    MultiLicenseeIncludesSubscriptionByYear: _,
    GameBillingPackageIncludesSubscriptionBySecond: _,
    GameBillingPackageIncludesSubscriptionByMinute: _,
    GameBillingPackageIncludesSubscriptionByHour: _,
    GameBillingPackageIncludesSubscriptionByDay: _,
    GameBillingPackageIncludesSubscriptionByWeek: _,
    GameBillingPackageIncludesSubscriptionByMonth: _,
    GameBillingPackageIncludesSubscriptionByYear: _,
    MicroTxnSubscriptionCostBySecond: _,
    MicroTxnSubscriptionCostByMinute: _,
    MicroTxnSubscriptionCostByHour: _,
    MicroTxnSubscriptionCostByDay: _,
    MicroTxnSubscriptionCostByWeek: _,
    MicroTxnSubscriptionCostByMonth: _,
    MicroTxnSubscriptionCostByYear: _,
    GameBillingAuthorizeSubscriptionBySecond: _,
    GameBillingAuthorizeSubscriptionByMinute: _,
    GameBillingAuthorizeSubscriptionByHour: _,
    GameBillingAuthorizeSubscriptionByDay: _,
    GameBillingAuthorizeSubscriptionByWeek: _,
    GameBillingAuthorizeSubscriptionByMonth: _,
    GameBillingAuthorizeSubscriptionByYear: _,
    PackageCostIncludesSubscriptionBySecond: _,
    PackageCostIncludesSubscriptionByMinute: _,
    PackageCostIncludesSubscriptionByHour: _,
    PackageCostIncludesSubscriptionByDay: _,
    PackageCostIncludesSubscriptionByWeek: _,
    PackageCostIncludesSubscriptionByMonth: _,
    PackageCostIncludesSubscriptionByYear: _,
    PackageWithDiscountCostIncludesSubscriptionBySecond: _,
    PackageWithDiscountCostIncludesSubscriptionByMinute: _,
    PackageWithDiscountCostIncludesSubscriptionByHour: _,
    PackageWithDiscountCostIncludesSubscriptionByDay: _,
    PackageWithDiscountCostIncludesSubscriptionByWeek: _,
    PackageWithDiscountCostIncludesSubscriptionByMonth: _,
    PackageWithDiscountCostIncludesSubscriptionByYear: _,
    GameBillingPackageCostIncludesSubscriptionBySecond: _,
    GameBillingPackageCostIncludesSubscriptionByMinute: _,
    GameBillingPackageCostIncludesSubscriptionByHour: _,
    GameBillingPackageCostIncludesSubscriptionByDay: _,
    GameBillingPackageCostIncludesSubscriptionByWeek: _,
    GameBillingPackageCostIncludesSubscriptionByMonth: _,
    GameBillingPackageCostIncludesSubscriptionByYear: _,
    MultiLicenseCostIncludesSubscriptionBySecond: _,
    MultiLicenseCostIncludesSubscriptionByMinute: _,
    MultiLicenseCostIncludesSubscriptionByHour: _,
    MultiLicenseCostIncludesSubscriptionByDay: _,
    MultiLicenseCostIncludesSubscriptionByWeek: _,
    MultiLicenseCostIncludesSubscriptionByMonth: _,
    MultiLicenseCostIncludesSubscriptionByYear: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionBySecond: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMinute: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByHour: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByDay: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByWeek: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMonth: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByYear: _,
    Cart_Empty: _,
    Cart_Notice_SomeAppsPrivate: _,
    Cart_LineItemOptions_PrivateTooltip: _,
    Cart_BetaNotice: _,
    Cart_GenericBetaNotice: _,
    Cart_GiftScheduleError_TooFar: _,
    Cart_GiftScheduleError_InvalidDate: _,
    Cart_LineItem_ErrorBoundary: _,
    Cart_SaleCardDrops_EarnedMessage: _,
    Cart_SaleCardDrops_EarnedMessage_Plural: _,
    Cart_SaleCardDrops_Explanation: _,
    Cart_SaleCardDrops_Explanation_Gifts: _,
    Cart_SaleCardDrops_ProgressLabel: _,
    Cart_SaleCardDrops_CardCost: _,
    Cart_SaleCardDrops_PrepurchaseIneligible: _,
    Cart_PurchaseRequestTitle: _,
    Cart_PurchaseFor_Label: _,
    Cart_GiftForNotice: _,
    Cart_LineItem_Add_Tooltip: _,
    Cart_LineItem_Hardware_Compliance_Label: _,
    Cart_ErrorUpdating: _,
    Cart_ErrorCode: _,
    Cart_UserCountrySelector: _,
    Cart_Replay_SavedCart: _,
    Cart_Replay_Instructions: _,
    Cart_Gifting_CopyGiftOptionsFrom: _,
    Cart_Gifting_SignInToSelectFriends: _,
  };
export {
  _ as Cart_Add,
  _ as Cart_AddedToYourCart,
  _ as Cart_BetaNotice,
  _ as Cart_Bradcrumb_Home,
  _ as Cart_CartLevelErrorFormat,
  _ as Cart_CartLevelErrorMultiple,
  _ as Cart_CartLevelErrorNotice,
  _ as Cart_ChangeGiftRecipient,
  _ as Cart_ComingSoon,
  _ as Cart_ContainsGiftCheckbox,
  _ as Cart_ContinueButton_Gifts,
  _ as Cart_ContinueButton_Login,
  _ as Cart_ContinueButton_Payment,
  _ as Cart_ContinueShopping,
  _ as Cart_CountWidget,
  _ as Cart_CouponAvailability,
  _ as Cart_CouponAvailability_Plural,
  _ as Cart_CouponModify_Add,
  _ as Cart_CouponModify_Change,
  _ as Cart_Coupons_Applied,
  _ as Cart_Coupons_InUse,
  _ as Cart_DeclinePurchaseRequest,
  _ as Cart_Edit,
  _ as Cart_EditGiftDelivery,
  _ as Cart_Empty,
  _ as Cart_EnterRecipientEmail,
  _ as Cart_ErrorCode,
  _ as Cart_ErrorUpdating,
  _ as Cart_Error_AdultContentRestricted_FootNote,
  _ as Cart_Error_AdultContentRestricted_LineItem,
  _ as Cart_Error_AlreadyOwned_FootNote,
  _ as Cart_Error_AlreadyOwned_GiftFootNote,
  _ as Cart_Error_AlreadyOwned_GiftLineItem,
  _ as Cart_Error_AlreadyOwned_GiftLineItem_Game,
  _ as Cart_Error_AlreadyOwned_LineItem,
  _ as Cart_Error_AlreadyOwned_LineItem_Game,
  _ as Cart_Error_CommercialLicenseRestricted_FootNote,
  _ as Cart_Error_CommercialLicenseRestricted_LineItem,
  _ as Cart_Error_CouponIsExclusivePromo,
  _ as Cart_Error_CouponIsInvalid,
  _ as Cart_Error_CouponIsInvalidForItem,
  _ as Cart_Error_DuplicateApps_FootNote,
  _ as Cart_Error_DuplicateApps_LineItem,
  _ as Cart_Error_ExistingBillingAgreement,
  _ as Cart_Error_ExistingBillingAgreement_FootNote,
  _ as Cart_Error_GiftRecipientInvalid,
  _ as Cart_Error_MasterSubscription_FootNote,
  _ as Cart_Error_MasterSubscription_LineItem,
  _ as Cart_Error_MissingMustOwnApps_FootNote,
  _ as Cart_Error_MissingMustOwnApps_FootNoteGift,
  _ as Cart_Error_MissingMustOwnApps_GiftLineItem,
  _ as Cart_Error_MissingMustOwnApps_LineItem,
  _ as Cart_Error_TooManyInCart,
  _ as Cart_Error_UnavailableCountry_FootNote,
  _ as Cart_Error_UnavailableCountry_LineItem,
  _ as Cart_EstimatedTotal,
  _ as Cart_FamilyGift_Notice,
  _ as Cart_FooterNoticeHeader_MustFix,
  _ as Cart_FooterNoticeHeader_Warning,
  _ as Cart_GenericBetaNotice,
  _ as Cart_GiftDeliveryEmail_Warning1,
  _ as Cart_GiftDeliveryEmail_Warning2,
  _ as Cart_GiftDelivery_AddSignature,
  _ as Cart_GiftDelivery_Body,
  _ as Cart_GiftDelivery_From,
  _ as Cart_GiftDelivery_Label,
  _ as Cart_GiftDelivery_Now,
  _ as Cart_GiftDelivery_Reset,
  _ as Cart_GiftDelivery_ScheduleDelivery,
  _ as Cart_GiftDelivery_Scheduled,
  _ as Cart_GiftDelivery_Signature,
  _ as Cart_GiftForNotice,
  _ as Cart_GiftOptions,
  _ as Cart_GiftRecipientEmail_Label,
  _ as Cart_GiftRecipientModal_IssueLoading,
  _ as Cart_GiftRecipientModal_OnWishlist,
  _ as Cart_GiftRecipientModal_OwnsGameLabel,
  _ as Cart_GiftRecipientModal_PartialOwnsLabel,
  _ as Cart_GiftRecipientModal_PartialWishlistLabel,
  _ as Cart_GiftRecipientModal_Placeholder,
  _ as Cart_GiftRecipientModal_Save,
  _ as Cart_GiftRecipientModal_Title,
  _ as Cart_GiftRecipient_Label,
  _ as Cart_GiftScheduleError_InvalidDate,
  _ as Cart_GiftScheduleError_TooFar,
  _ as Cart_GifteeHint_Wishlist,
  _ as Cart_Gifting_CopyGiftOptionsFrom,
  _ as Cart_Gifting_SignInToSelectFriends,
  _ as Cart_IncludesItems,
  _ as Cart_IncludesItems_Plural,
  _ as Cart_LineItemGift_Checkbox,
  _ as Cart_LineItemOptions_Gift,
  _ as Cart_LineItemOptions_GiftForPersona,
  _ as Cart_LineItemOptions_Myself,
  _ as Cart_LineItemOptions_PrivateTooltip,
  _ as Cart_LineItemOptions_Privately,
  _ as Cart_LineItem_Add_Tooltip,
  _ as Cart_LineItem_ErrorBoundary,
  _ as Cart_LineItem_Hardware_Compliance_Label,
  _ as Cart_Note_SalesTax,
  _ as Cart_Notice_SomeAppsPrivate,
  _ as Cart_PurchaseBtn,
  _ as Cart_PurchaseFor_Label,
  _ as Cart_PurchaseRequestTitle,
  _ as Cart_Quantity,
  _ as Cart_Remove,
  _ as Cart_RemoveAll,
  _ as Cart_Replay_Instructions,
  _ as Cart_Replay_SavedCart,
  _ as Cart_RequestPurchase,
  _ as Cart_RequestPurchaseExplanation,
  _ as Cart_RequestPurchaseNonGiftableItems,
  _ as Cart_SaleCardDrops_CardCost,
  _ as Cart_SaleCardDrops_EarnedMessage,
  _ as Cart_SaleCardDrops_EarnedMessage_Plural,
  _ as Cart_SaleCardDrops_Explanation,
  _ as Cart_SaleCardDrops_Explanation_Gifts,
  _ as Cart_SaleCardDrops_PrepurchaseIneligible,
  _ as Cart_SaleCardDrops_ProgressLabel,
  _ as Cart_SelectCouponToApply,
  _ as Cart_SelectRecipient,
  _ as Cart_ShippingEstimate_Delayed,
  _ as Cart_ShippingEstimate_DeliveryDate,
  _ as Cart_ShippingEstimate_Range,
  _ as Cart_ShippingEstimate_Standard,
  _ as Cart_UpdatedYourCart,
  _ as Cart_UserCountrySelector,
  _ as Cart_Verify,
  _ as Cart_ViewMyCart,
  _ as Cart_Warning_AlreadyOwned_LineItem,
  _ as Cart_Warning_AvailableAtALowerPrice,
  _ as Cart_Warning_ExtraCopies_LineItem,
  _ as Cart_Warning_GiftToAccount_LoggedOut_Actionable,
  _ as Cart_Warning_GiftToNonFriend,
  _ as Cart_Warning_GiftToNonFriend_Named,
  _ as Cart_Warning_NoRefund_LineItem,
  _ as Cart_Warning_PriceChange_FootNote,
  _ as Cart_Warning_PriceChange_LineItem,
  _ as Cart_Warning_RecipientHigherPrice,
  _ as Cart_YourShoppingCart,
  _ as Cart_YourShoppingCartLineItems,
  _ as Cart_YourShoppingCartLineItems_Plural,
  _ as GameBillingAuthorizeSubscriptionByDay,
  _ as GameBillingAuthorizeSubscriptionByHour,
  _ as GameBillingAuthorizeSubscriptionByMinute,
  _ as GameBillingAuthorizeSubscriptionByMonth,
  _ as GameBillingAuthorizeSubscriptionBySecond,
  _ as GameBillingAuthorizeSubscriptionByWeek,
  _ as GameBillingAuthorizeSubscriptionByYear,
  _ as GameBillingPackageCostIncludesSubscriptionByDay,
  _ as GameBillingPackageCostIncludesSubscriptionByHour,
  _ as GameBillingPackageCostIncludesSubscriptionByMinute,
  _ as GameBillingPackageCostIncludesSubscriptionByMonth,
  _ as GameBillingPackageCostIncludesSubscriptionBySecond,
  _ as GameBillingPackageCostIncludesSubscriptionByWeek,
  _ as GameBillingPackageCostIncludesSubscriptionByYear,
  _ as GameBillingPackageIncludesSubscriptionByDay,
  _ as GameBillingPackageIncludesSubscriptionByHour,
  _ as GameBillingPackageIncludesSubscriptionByMinute,
  _ as GameBillingPackageIncludesSubscriptionByMonth,
  _ as GameBillingPackageIncludesSubscriptionBySecond,
  _ as GameBillingPackageIncludesSubscriptionByWeek,
  _ as GameBillingPackageIncludesSubscriptionByYear,
  _ as MicroTxnSubscriptionCostByDay,
  _ as MicroTxnSubscriptionCostByHour,
  _ as MicroTxnSubscriptionCostByMinute,
  _ as MicroTxnSubscriptionCostByMonth,
  _ as MicroTxnSubscriptionCostBySecond,
  _ as MicroTxnSubscriptionCostByWeek,
  _ as MicroTxnSubscriptionCostByYear,
  _ as MultiLicenseCostIncludesSubscriptionByDay,
  _ as MultiLicenseCostIncludesSubscriptionByHour,
  _ as MultiLicenseCostIncludesSubscriptionByMinute,
  _ as MultiLicenseCostIncludesSubscriptionByMonth,
  _ as MultiLicenseCostIncludesSubscriptionBySecond,
  _ as MultiLicenseCostIncludesSubscriptionByWeek,
  _ as MultiLicenseCostIncludesSubscriptionByYear,
  _ as MultiLicenseIncludesSubscriptionByDay,
  _ as MultiLicenseIncludesSubscriptionByHour,
  _ as MultiLicenseIncludesSubscriptionByMinute,
  _ as MultiLicenseIncludesSubscriptionByMonth,
  _ as MultiLicenseIncludesSubscriptionBySecond,
  _ as MultiLicenseIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByDay,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByHour,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMinute,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMonth,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionBySecond,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByYear,
  _ as MultiLicenseeIncludesSubscriptionByYear,
  _ as PackageCostIncludesSubscriptionByDay,
  _ as PackageCostIncludesSubscriptionByHour,
  _ as PackageCostIncludesSubscriptionByMinute,
  _ as PackageCostIncludesSubscriptionByMonth,
  _ as PackageCostIncludesSubscriptionBySecond,
  _ as PackageCostIncludesSubscriptionByWeek,
  _ as PackageCostIncludesSubscriptionByYear,
  _ as PackageIncludesSubscriptionByDay,
  _ as PackageIncludesSubscriptionByHour,
  _ as PackageIncludesSubscriptionByMinute,
  _ as PackageIncludesSubscriptionByMonth,
  _ as PackageIncludesSubscriptionBySecond,
  _ as PackageIncludesSubscriptionByWeek,
  _ as PackageIncludesSubscriptionByYear,
  _ as PackageWithDiscountCostIncludesSubscriptionByDay,
  _ as PackageWithDiscountCostIncludesSubscriptionByHour,
  _ as PackageWithDiscountCostIncludesSubscriptionByMinute,
  _ as PackageWithDiscountCostIncludesSubscriptionByMonth,
  _ as PackageWithDiscountCostIncludesSubscriptionBySecond,
  _ as PackageWithDiscountCostIncludesSubscriptionByWeek,
  _ as PackageWithDiscountCostIncludesSubscriptionByYear,
  _ as default,
  _ as language,
};
