var _ = `latam`,
  _ = `Eliminar`,
  _ = `Agregar`,
  _ = `Verificar edad`,
  _ = `Eliminar todos los artículos`,
  _ = `Editar`,
  _ = `Cantidad: %1$s`,
  _ = `Tu carrito de compra`,
  _ = `Tu carrito de compra (%1$s\xA0artículo)`,
  _ = `Tu carrito de compra (%1$s\xA0artículos)`,
  _ = `Total estimado`,
  _ = `Los impuestos de venta se calcularán durante el pago (si es aplicable).`,
  _ = `Comprar`,
  _ = `Esta compra incluye un regalo`,
  _ = `Inicio`,
  _ = `¿Esto es un regalo?`,
  _ = `Incluye %1$s artículos`,
  _ = `Incluye %1$s artículos`,
  _ = `Selecciona el destinatario`,
  _ = `Ingresar correo electrónico`,
  _ = `Editar destinatario del regalo...`,
  _ = `Destinatario del regalo:`,
  _ = `Correo electrónico del destinatario del regalo:`,
  _ = `Entrega:`,
  _ = `Restablecer`,
  _ = `Lo antes posible (por correo electrónico y cliente de Steam)`,
  _ = `Programado:`,
  _ = `Programar entrega`,
  _ = `De:`,
  _ = `Tu firma:`,
  _ = `Agregar firma personalizada`,
  _ = `Mensaje para el regalo (límite de 160 caracteres; quedan %1$s):`,
  _ = `Los regalos enviados por correo electrónico se reembolsarán automáticamente al cabo de 30\xA0días si no se han agregado a una cuenta de Steam.`,
  _ = `Los regalos enviados por correo electrónico solo pueden aceptarlos las cuentas de Steam de la misma región que la del comprador (%1$s).`,
  _ = `Los regalos que envíes a los menores de tu grupo familiar de Steam se agregarán automáticamente a su cuenta y a sus juegos permitidos.`,
  _ = `Selecciona el destinatario del regalo`,
  _ = `Modificar el método de entrega`,
  _ = `Guardar`,
  _ = `Buscar por nombre de amigo...`,
  _ = `Ya tiene este artículo`,
  _ = `En lista de deseados`,
  _ = `Ya tiene %1$s`,
  _ = `Desea tener %1$s`,
  _ = `Opciones de regalo`,
  _ = `Se produjo un problema al cargar los usuarios a los que puedes regalar el artículo. Vuelve a intentarlo más tarde.`,
  _ = `Continuar con el pago`,
  _ = `Continuar con las opciones de regalo`,
  _ = `Iniciar sesión para comprar`,
  _ = `Rechazar solicitud`,
  _ = `Para mi cuenta`,
  _ = `Esto es un regalo`,
  _ = `Este regalo es para %1$s`,
  _ = `Para mi cuenta: privado`,
  _ = `Carrito (%1$s)`,
  _ = `¡Agregado a tu carrito!`,
  _ = `¡Se actualizó tu carrito!`,
  _ = `Seguir comprando`,
  _ = `Disponible: %1$s`,
  _ = `Ver mi carrito (%1$s)`,
  _ = `Solicitar compra`,
  _ = `Se notificará a los adultos de tu grupo familiar sobre tu solicitud de compra`,
  _ = `No se puede solicitar la compra porque no todos los artículos del carrito se pueden regalar.`,
  _ = `Cambiar o eliminar cupón`,
  _ = `Agregar cupón`,
  _ = `Tienes un cupón disponible para este artículo`,
  _ = `Tienes %1$s cupones disponibles para este artículo`,
  _ = `Aplicado actualmente`,
  _ = `Aplicado actualmente a otro producto`,
  _ = `Selecciona un cupón para aplicar a %1$s`,
  _ = `Entrega estimada: %1$s`,
  _ = `De %1$s a %2$s días laborables`,
  _ = `Entrega aproximada: de 6 a 10\xA0días laborables`,
  _ = `Entrega aproximada: de 3 a 5\xA0días laborables`,
  _ = `Antes de poder continuar con el pago:`,
  _ = `Notas:`,
  _ = `Debes hacer algo antes de poder continuar con el pago`,
  _ = `Notas:`,
  _ = `Nota: %1$s`,
  _ = `Ya tienes algunos de los artículos anteriores en tu cuenta, de modo que no puedes comprarlos otra vez. Puedes adquirirlos como regalos o bien modificar los contenidos del carrito para continuar.`,
  _ = `Ya tienes este juego`,
  _ = `Ya tienes todo lo que se incluye en este lote.`,
  _ = `El destinatario del regalo ya tiene este juego`,
  _ = `El destinatario del regalo ya tiene todo lo que se incluye en este paquete`,
  _ = `El destinatario del regalo ya tiene algunos de los artículos anteriores, de modo que no puede comprarlos otra vez. Puedes adquirirlos como regalos o bien modificar los contenidos del carrito para continuar.`,
  _ = `Parece que el contenido de algunos de los lotes es igual al de los otros. Debes eliminar los lotes redundantes del carrito antes de que puedas proceder al pago.`,
  _ = `Ya en tu carrito: `,
  _ = `Tu carrito contiene un lote que no está disponible en tu país. Debes eliminar el paquete de tu carrito antes de poder hacer el pago.`,
  _ = `No disponible en tu país`,
  _ = `Valve está obligado a verificar que eres mayor de 18 años antes de permitirte comprar contenido sexual para adultos.`,
  _ = `No está disponible para la compra hasta que verifiques tu edad.`,
  _ = `Tu carrito incluye contenido que también está disponible a través de una de tus suscripciones activas.`,
  _ = `Disponible a través de tu suscripción de:`,
  _ = `Este cupón no se puede utilizar junto con otro descuento.`,
  _ = `Este cupón no es válido o ha caducado.`,
  _ = `Este cupón no se puede aplicar a este artículo.`,
  _ = `Has superado la cantidad máxima de este artículo permitida en tu carrito.`,
  _ = `Tu carrito contiene un artículo que no está disponible para su compra.`,
  _ = `No disponible para su compra`,
  _ = `El destinatario seleccionado no puede recibir este regalo comprado en tu región.`,
  _ = `Para comprar este artículo, necesitas los siguientes artículos:`,
  _ = `Para comprar este artículo, el destinatario del regalo necesita los siguientes artículos:`,
  _ = `A tu cuenta le faltan algunos artículos necesarios para comprar los que se encuentran en tu carrito. Puedes agregar los artículos que faltan o modificar el contenido del carrito para continuar.`,
  _ = `Al destinatario del regalo le faltan algunos artículos necesarios para comprar los que se encuentran en tu carrito. Puedes agregar los artículos que faltan o modificar el contenido del carrito para continuar.`,
  _ = `Ya tienes una suscripción para este artículo.`,
  _ = `Tu cuenta ya tiene una suscripción para algunos de los artículos anteriores. Revisa tus suscripciones en el cliente de Steam > "Configuraciones" > "Cuenta" > "Detalles de la cuenta".`,
  _ = `Si lo estás comprando para ti, no recibirás una copia extra de:`,
  _ = `Si lo compras para ti, recibirás una copia extra para regalar de:`,
  _ = `Uno o más de los artículos a continuación cambiaron de precio después de que los agregaste al carrito.`,
  _ = `El precio de este artículo cambió.`,
  _ = `Este producto incluye contenido consumible que lo hace no reembolsable.`,
  _ = `El destinatario del regalo que has seleccionado está en una región con precios más elevados. El precio de este artículo se ha actualizado para ajustarse a su región y así poder regalárselo.`,
  _ = `Este artículo está disponible a un precio más bajo como parte de %1$s.`,
  _ = `El destinatario del regalo NO está en tu lista de amigos de Steam.`,
  _ = `NOTA: %1$s NO está en tu lista de amigos de Steam.`,
  _ = `Si estás enviando un regalo a un amigo de Steam, <1>inicia sesión</1> para verificar que el destinatario está en tu lista de amigos.`,
  _ = `Recientemente viste la lista de deseados de %1$s. ¿Le quieres regalar estos artículos?`,
  _ = `La cuota de suscripción de %1$s te será facturada cada %2$s segundo(s).`,
  _ = `La cuota de suscripción de %1$s te será facturada cada %2$s minuto(s).`,
  _ = `La cuota de suscripción de %1$s te será facturada cada %2$s hora(s).`,
  _ = `La cuota de suscripción de %1$s te será facturada cada %2$s día(s).`,
  _ = `La cuota de suscripción de %1$s te será facturada cada %2$s semana(s).`,
  _ = `La cuota de suscripción de %1$s te será facturada cada %2$s mes(es).`,
  _ = `La cuota de suscripción de %1$s te será facturada cada %2$s año(s).`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s segundo(s) por licencia.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s minuto(s) por licencia.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s hora(s) por licencia.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s día(s) por licencia.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s semana(s) por licencia.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s mes(es) por licencia.`,
  _ = `La cuota de suscripción de %1$s se facturará cada %2$s año(s) por licencia.`,
  _ = `La cuota de suscripción de %1$s te será facturada cada %2$s segundo(s) o como se determine en tu cuenta del juego.`,
  _ = `La cuota de suscripción de %1$s te será facturada cada %2$s minuto(s) o como se determine en tu cuenta del juego.`,
  _ = `La cuota de suscripción de %1$s te será facturada cada %2$s hora(s) o como se determine en tu cuenta del juego.`,
  _ = `La cuota de suscripción de %1$s te será facturada cada %2$s día(s) o como se determine en tu cuenta del juego.`,
  _ = `La cuota de suscripción de %1$s te será facturada cada %2$s semana(s) o como se determine en tu cuenta del juego.`,
  _ = `La cuota de suscripción de %1$s te será facturada cada %2$s mes(es) o como se determine en tu cuenta del juego.`,
  _ = `La cuota de suscripción de %1$s te será facturada cada %2$s año(s) o como se determine en tu cuenta del juego.`,
  _ = `Se te cobrarán %1$s a la hora de hacer el pago.<br/>Confirmas que estás de acuerdo a que se realicen cargos automáticos de %2$s a tu tarjeta de crédito cada %3$s segundo(s).`,
  _ = `Se te cobrarán %1$s a la hora de hacer el pago.<br/>Confirmas que estás de acuerdo a que se realicen cargos automáticos de %2$s a tu tarjeta de crédito cada %3$s minuto(s).`,
  _ = `Se te cobrarán %1$s a la hora de hacer el pago.<br/>Confirmas que estás de acuerdo a que se realicen cargos automáticos de %2$s a tu tarjeta de crédito cada %3$s hora(s).`,
  _ = `Se te cobrarán %1$s a la hora de hacer el pago.<br/>Confirmas que estás de acuerdo a que se realicen cargos automáticos de %2$s a tu tarjeta de crédito cada %3$s día(s).`,
  _ = `Se te cobrarán %1$s a la hora de hacer el pago.<br/>Confirmas que estás de acuerdo a que se realicen cargos automáticos de %2$s a tu tarjeta de crédito cada %3$s semana(s).`,
  _ = `Se te cobrarán %1$s a la hora de hacer el pago.<br/>Confirmas que estás de acuerdo a que se realicen cargos automáticos de %2$s a tu tarjeta de crédito cada %3$s mes(es).`,
  _ = `Se te cobrarán %1$s a la hora de hacer el pago.<br/>Confirmas que estás de acuerdo a que se realicen cargos automáticos de %2$s a tu tarjeta de crédito cada %3$s año(s).`,
  _ = `Se te cobrarán %1$s a la hora de hacer el pago.<br/>Autorizas a este juego a hacer cobros adicionales de hasta %2$s cada %3$s segundo(s).`,
  _ = `Se te cobrarán %1$s a la hora de hacer el pago.<br/>Autorizas a este juego a hacer cobros adicionales de hasta %2$s cada %3$s minuto(s).`,
  _ = `Se te cobrarán %1$s a la hora de hacer el pago.<br/>Autorizas a este juego a hacer cobros adicionales de hasta %2$s cada %3$s hora(s).`,
  _ = `Se te cobrarán %1$s a la hora de hacer el pago.<br/>Autorizas a este juego a hacer cobros adicionales de hasta %2$s cada %3$s día(s).`,
  _ = `Se te cobrarán %1$s a la hora de hacer el pago.<br/>Autorizas a este juego a hacer cobros adicionales de hasta %2$s cada %3$s semana(s).`,
  _ = `Se te cobrarán %1$s a la hora de hacer el pago.<br/>Autorizas a este juego a hacer cobros adicionales de hasta %2$s cada %3$s mes(es).`,
  _ = `Se te cobrarán %1$s a la hora de hacer el pago.<br/>Autorizas a este juego a hacer cobros adicionales de hasta %2$s cada %3$s año(s).`,
  _ = `%1$s como cuota inicial, que se renovará automáticamente cada %3$s segundo(s) por %2$s.`,
  _ = `%1$s como cuota inicial, que se renovará automáticamente cada %3$s minuto(s) por %2$s.`,
  _ = `%1$s como cuota inicial, que se renovará automáticamente cada %3$s hora(s) por %2$s.`,
  _ = `%1$s como cuota inicial, que se renovará automáticamente cada %3$s día(s) por %2$s.`,
  _ = `%1$s como cuota inicial, que se renovará automáticamente cada %3$s semana(s) por %2$s.`,
  _ = `%1$s como cuota inicial, que se renovará automáticamente cada %3$s mes(es) por %2$s.`,
  _ = `%1$s como cuota inicial, que se renovará automáticamente cada %3$s año(s) por %2$s.`,
  _ = `Pago inicial de %1$s (con un %4$s %% de descuento para primeras compras), renovación automática cada %3$s segundo(s) por %2$s.`,
  _ = `Pago inicial de %1$s (con un %4$s %% de descuento para primeras compras), renovación automática cada %3$s minuto(s) por %2$s.`,
  _ = `Pago inicial de %1$s (con un %4$s %% de descuento para primeras compras), renovación automática cada %3$s hora(s) por %2$s.`,
  _ = `Pago inicial de %1$s (con un %4$s %% de descuento para primeras compras), renovación automática cada %3$s día(s) por %2$s.`,
  _ = `Pago inicial de %1$s (con un %4$s %% de descuento para primeras compras), renovación automática cada %3$s semana(s) por %2$s.`,
  _ = `Pago inicial de %1$s (con un %4$s %% de descuento para primeras compras), renovación automática cada %3$s mes(es) por %2$s.`,
  _ = `Pago inicial de %1$s (con un %4$s %% de descuento para primeras compras), renovación automática cada %3$s año(s) por %2$s.`,
  _ = `%1$s como cuota inicial, que se renovará automáticamente cada %3$s segundo(s) por %2$s tal y como se determina en tu cuenta del juego.`,
  _ = `%1$s como cuota inicial, que se renovará automáticamente cada %3$s minuto(s) por %2$s tal y como se determina en tu cuenta del juego.`,
  _ = `%1$s como cuota inicial, que se renovará automáticamente cada %3$s hora(s) por %2$s tal y como se determina en tu cuenta del juego.`,
  _ = `%1$s como cuota inicial, que se renovará automáticamente cada %3$s día(s) por %2$s tal y como se determina en tu cuenta del juego.`,
  _ = `%1$s como cuota inicial, que se renovará automáticamente cada %3$s semana(s) por %2$s tal y como se determina en tu cuenta del juego.`,
  _ = `%1$s como cuota inicial, que se renovará automáticamente cada %3$s mes(es) por %2$s tal y como se determina en tu cuenta del juego.`,
  _ = `%1$s como cuota inicial, que se renovará automáticamente cada %3$s año(s) por %2$s tal y como se determina en tu cuenta del juego.`,
  _ = `%1$s en el momento de la compra, renovado automáticamente cada %3$s segundo(s) a %2$s por licencia.`,
  _ = `%1$s en el momento de la compra, renovado automáticamente cada %3$s minuto(s) a %2$s por licencia.`,
  _ = `%1$s en el momento de la compra, renovado automáticamente cada %3$s hora(s) a %2$s por licencia.`,
  _ = `%1$s en el momento de la compra, renovado automáticamente cada %3$s día(s) a %2$s por licencia.`,
  _ = `%1$s en el momento de la compra, renovado automáticamente cada %3$s semana(s) a %2$s por licencia.`,
  _ = `%1$s en el momento de la compra, renovado automáticamente cada %3$s mes(es) a %2$s por licencia.`,
  _ = `%1$s en el momento de la compra, renovado automáticamente cada %3$s año(s) a %2$s por licencia.`,
  _ = `Pago inicial de %1$s (con un %4$s %% de descuento para primeras compras), renovación automática cada %3$s segundo(s) por %2$s por licencia.`,
  _ = `Pago inicial de %1$s (con un %4$s %% de descuento para primeras compras), renovación automática cada %3$s minuto(s) por %2$s por licencia.`,
  _ = `Pago inicial de %1$s (con un %4$s %% de descuento para primeras compras), renovación automática cada %3$s hora(s) por %2$s por licencia.`,
  _ = `Pago inicial de %1$s (con un %4$s %% de descuento para primeras compras), renovación automática cada %3$s día(s) por %2$s por licencia.`,
  _ = `Pago inicial de %1$s (con un %4$s %% de descuento para primeras compras), renovación automática cada %3$s semana(s) por %2$s por licencia.`,
  _ = `Pago inicial de %1$s (con un %4$s %% de descuento para primeras compras), renovación automática cada %3$s mes(es) por %2$s por licencia.`,
  _ = `Pago inicial de %1$s (con un %4$s %% de descuento para primeras compras), renovación automática cada %3$s año(s) por %2$s por licencia.`,
  _ = `Tu carrito está vacío.`,
  _ = `Algunos de estos artículos ya fueron marcados como privados. Se mantendrán como privados si continúas:`,
  _ = `Marcar un juego como privado lo ocultará en todas partes fuera de tu biblioteca. Tu propiedad, estado en el juego, tiempo de juego y actividad no serán visibles para las demás personas.`,
  _ = `Estás viendo una versión nueva del carrito de compra debido a que participas en la beta del cliente de Steam. <1>Deja comentarios o informa sobre errores</1>.`,
  _ = `Esta nueva versión del carrito está en fase de prueba beta. <1>Deja un comentario o informa de errores</1>`,
  _ = `No puedes programar un regalo con tanta anticipación.`,
  _ = `Ingresa una fecha y hora válidas.`,
  _ = `Se produjo un problema al mostrar este artículo`,
  _ = `Obtendrás %1$s tarjeta de %2$s con esta compra.`,
  _ = `Obtendrás %1$s tarjetas de %2$s con esta compra.`,
  _ = `Con las compras que realices durante las rebajas obtendrás tarjetas de %1$s.`,
  _ = `Recibirás las tarjetas correspondientes aunque esta compra sea un regalo.`,
  _ = `Progreso hasta la siguiente tarjeta`,
  _ = `aproximadamente %1$s por tarjeta`,
  _ = `Nota: Los artículos precomprados no reúnen los requisitos para recibir tarjetas de %1$s como recompensa. Los siguientes artículos no otorgan tarjetas como recompensa:`,
  _ = `Solicitud de compra de %1$s`,
  _ = `Una compra para:`,
  _ = `Comprar como regalo: %1$s`,
  _ = `Agregar otra copia de este artículo a tu carro`,
  _ = `Declaración de cumplimiento de la Ley PSTI del Reino\xA0Unido`,
  _ = `Hubo un problema al actualizar tu carrito.`,
  _ = `Código de error: %1$s`,
  _ = `País`,
  _ = `Carrito guardado`,
  _ = `Este es un carrito de compra guardado. La última vez que intentaste comprar el contenido de este carrito se produjo un error, así que te lo guardaremos (incluyendo los descuentos) durante %1$s horas para que puedas intentar realizar la compra de nuevo.`,
  _ = `Copiar las opciones de regalo de`,
  _ = `<1>Inicia sesión</1> para seleccionar amigos en Steam.`,
  _ = {
    language: _,
    Cart_Remove: _,
    Cart_Add: _,
    Cart_Verify: _,
    Cart_RemoveAll: _,
    Cart_Edit: _,
    Cart_Quantity: _,
    Cart_YourShoppingCart: _,
    Cart_YourShoppingCartLineItems: _,
    Cart_YourShoppingCartLineItems_Plural: _,
    Cart_EstimatedTotal: _,
    Cart_Note_SalesTax: _,
    Cart_PurchaseBtn: _,
    Cart_ContainsGiftCheckbox: _,
    Cart_Bradcrumb_Home: _,
    Cart_LineItemGift_Checkbox: _,
    Cart_IncludesItems: _,
    Cart_IncludesItems_Plural: _,
    Cart_SelectRecipient: _,
    Cart_EnterRecipientEmail: _,
    Cart_ChangeGiftRecipient: _,
    Cart_GiftRecipient_Label: _,
    Cart_GiftRecipientEmail_Label: _,
    Cart_GiftDelivery_Label: _,
    Cart_GiftDelivery_Reset: _,
    Cart_GiftDelivery_Now: _,
    Cart_GiftDelivery_Scheduled: _,
    Cart_GiftDelivery_ScheduleDelivery: _,
    Cart_GiftDelivery_From: `De:`,
    Cart_GiftDelivery_Signature: _,
    Cart_GiftDelivery_AddSignature: _,
    Cart_GiftDelivery_Body: _,
    Cart_GiftDeliveryEmail_Warning1: _,
    Cart_GiftDeliveryEmail_Warning2: _,
    Cart_FamilyGift_Notice: _,
    Cart_GiftRecipientModal_Title: _,
    Cart_EditGiftDelivery: _,
    Cart_GiftRecipientModal_Save: _,
    Cart_GiftRecipientModal_Placeholder: _,
    Cart_GiftRecipientModal_OwnsGameLabel: _,
    Cart_GiftRecipientModal_OnWishlist: _,
    Cart_GiftRecipientModal_PartialOwnsLabel: _,
    Cart_GiftRecipientModal_PartialWishlistLabel: _,
    Cart_GiftOptions: _,
    Cart_GiftRecipientModal_IssueLoading: _,
    Cart_ContinueButton_Payment: _,
    Cart_ContinueButton_Gifts: _,
    Cart_ContinueButton_Login: _,
    Cart_DeclinePurchaseRequest: _,
    Cart_LineItemOptions_Myself: _,
    Cart_LineItemOptions_Gift: _,
    Cart_LineItemOptions_GiftForPersona: _,
    Cart_LineItemOptions_Privately: _,
    Cart_CountWidget: _,
    Cart_AddedToYourCart: _,
    Cart_UpdatedYourCart: _,
    Cart_ContinueShopping: _,
    Cart_ComingSoon: _,
    Cart_ViewMyCart: _,
    Cart_RequestPurchase: _,
    Cart_RequestPurchaseExplanation: _,
    Cart_RequestPurchaseNonGiftableItems: _,
    Cart_CouponModify_Change: _,
    Cart_CouponModify_Add: _,
    Cart_CouponAvailability: _,
    Cart_CouponAvailability_Plural: _,
    Cart_Coupons_Applied: _,
    Cart_Coupons_InUse: _,
    Cart_SelectCouponToApply: _,
    Cart_ShippingEstimate_DeliveryDate: _,
    Cart_ShippingEstimate_Range: _,
    Cart_ShippingEstimate_Delayed: _,
    Cart_ShippingEstimate_Standard: _,
    Cart_FooterNoticeHeader_MustFix: _,
    Cart_FooterNoticeHeader_Warning: _,
    Cart_CartLevelErrorNotice: _,
    Cart_CartLevelErrorMultiple: _,
    Cart_CartLevelErrorFormat: _,
    Cart_Error_AlreadyOwned_FootNote: _,
    Cart_Error_AlreadyOwned_LineItem_Game: _,
    Cart_Error_AlreadyOwned_LineItem: _,
    Cart_Error_AlreadyOwned_GiftLineItem_Game: _,
    Cart_Error_AlreadyOwned_GiftLineItem: _,
    Cart_Error_AlreadyOwned_GiftFootNote: _,
    Cart_Error_DuplicateApps_FootNote: _,
    Cart_Error_DuplicateApps_LineItem: _,
    Cart_Error_UnavailableCountry_FootNote: _,
    Cart_Error_UnavailableCountry_LineItem: _,
    Cart_Error_AdultContentRestricted_FootNote: _,
    Cart_Error_AdultContentRestricted_LineItem: _,
    Cart_Error_MasterSubscription_FootNote: _,
    Cart_Error_MasterSubscription_LineItem: _,
    Cart_Error_CouponIsExclusivePromo: _,
    Cart_Error_CouponIsInvalid: _,
    Cart_Error_CouponIsInvalidForItem: _,
    Cart_Error_TooManyInCart: _,
    Cart_Error_CommercialLicenseRestricted_FootNote: _,
    Cart_Error_CommercialLicenseRestricted_LineItem: _,
    Cart_Error_GiftRecipientInvalid: _,
    Cart_Error_MissingMustOwnApps_LineItem: _,
    Cart_Error_MissingMustOwnApps_GiftLineItem: _,
    Cart_Error_MissingMustOwnApps_FootNote: _,
    Cart_Error_MissingMustOwnApps_FootNoteGift: _,
    Cart_Error_ExistingBillingAgreement: _,
    Cart_Error_ExistingBillingAgreement_FootNote: _,
    Cart_Warning_AlreadyOwned_LineItem: _,
    Cart_Warning_ExtraCopies_LineItem: _,
    Cart_Warning_PriceChange_FootNote: _,
    Cart_Warning_PriceChange_LineItem: _,
    Cart_Warning_NoRefund_LineItem: _,
    Cart_Warning_RecipientHigherPrice: _,
    Cart_Warning_AvailableAtALowerPrice: _,
    Cart_Warning_GiftToNonFriend: _,
    Cart_Warning_GiftToNonFriend_Named: _,
    Cart_Warning_GiftToAccount_LoggedOut_Actionable: _,
    Cart_GifteeHint_Wishlist: _,
    PackageIncludesSubscriptionBySecond: _,
    PackageIncludesSubscriptionByMinute: _,
    PackageIncludesSubscriptionByHour: _,
    PackageIncludesSubscriptionByDay: _,
    PackageIncludesSubscriptionByWeek: _,
    PackageIncludesSubscriptionByMonth: _,
    PackageIncludesSubscriptionByYear: _,
    MultiLicenseIncludesSubscriptionBySecond: _,
    MultiLicenseIncludesSubscriptionByMinute: _,
    MultiLicenseIncludesSubscriptionByHour: _,
    MultiLicenseIncludesSubscriptionByDay: _,
    MultiLicenseIncludesSubscriptionByWeek: _,
    MultiLicenseIncludesSubscriptionByMonth: _,
    MultiLicenseeIncludesSubscriptionByYear: _,
    GameBillingPackageIncludesSubscriptionBySecond: _,
    GameBillingPackageIncludesSubscriptionByMinute: _,
    GameBillingPackageIncludesSubscriptionByHour: _,
    GameBillingPackageIncludesSubscriptionByDay: _,
    GameBillingPackageIncludesSubscriptionByWeek: _,
    GameBillingPackageIncludesSubscriptionByMonth: _,
    GameBillingPackageIncludesSubscriptionByYear: _,
    MicroTxnSubscriptionCostBySecond: _,
    MicroTxnSubscriptionCostByMinute: _,
    MicroTxnSubscriptionCostByHour: _,
    MicroTxnSubscriptionCostByDay: _,
    MicroTxnSubscriptionCostByWeek: _,
    MicroTxnSubscriptionCostByMonth: _,
    MicroTxnSubscriptionCostByYear: _,
    GameBillingAuthorizeSubscriptionBySecond: _,
    GameBillingAuthorizeSubscriptionByMinute: _,
    GameBillingAuthorizeSubscriptionByHour: _,
    GameBillingAuthorizeSubscriptionByDay: _,
    GameBillingAuthorizeSubscriptionByWeek: _,
    GameBillingAuthorizeSubscriptionByMonth: _,
    GameBillingAuthorizeSubscriptionByYear: _,
    PackageCostIncludesSubscriptionBySecond: _,
    PackageCostIncludesSubscriptionByMinute: _,
    PackageCostIncludesSubscriptionByHour: _,
    PackageCostIncludesSubscriptionByDay: _,
    PackageCostIncludesSubscriptionByWeek: _,
    PackageCostIncludesSubscriptionByMonth: _,
    PackageCostIncludesSubscriptionByYear: _,
    PackageWithDiscountCostIncludesSubscriptionBySecond: _,
    PackageWithDiscountCostIncludesSubscriptionByMinute: _,
    PackageWithDiscountCostIncludesSubscriptionByHour: _,
    PackageWithDiscountCostIncludesSubscriptionByDay: _,
    PackageWithDiscountCostIncludesSubscriptionByWeek: _,
    PackageWithDiscountCostIncludesSubscriptionByMonth: _,
    PackageWithDiscountCostIncludesSubscriptionByYear: _,
    GameBillingPackageCostIncludesSubscriptionBySecond: _,
    GameBillingPackageCostIncludesSubscriptionByMinute: _,
    GameBillingPackageCostIncludesSubscriptionByHour: _,
    GameBillingPackageCostIncludesSubscriptionByDay: _,
    GameBillingPackageCostIncludesSubscriptionByWeek: _,
    GameBillingPackageCostIncludesSubscriptionByMonth: _,
    GameBillingPackageCostIncludesSubscriptionByYear: _,
    MultiLicenseCostIncludesSubscriptionBySecond: _,
    MultiLicenseCostIncludesSubscriptionByMinute: _,
    MultiLicenseCostIncludesSubscriptionByHour: _,
    MultiLicenseCostIncludesSubscriptionByDay: _,
    MultiLicenseCostIncludesSubscriptionByWeek: _,
    MultiLicenseCostIncludesSubscriptionByMonth: _,
    MultiLicenseCostIncludesSubscriptionByYear: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionBySecond: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMinute: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByHour: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByDay: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByWeek: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMonth: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByYear: _,
    Cart_Empty: _,
    Cart_Notice_SomeAppsPrivate: _,
    Cart_LineItemOptions_PrivateTooltip: _,
    Cart_BetaNotice: _,
    Cart_GenericBetaNotice: _,
    Cart_GiftScheduleError_TooFar: _,
    Cart_GiftScheduleError_InvalidDate: _,
    Cart_LineItem_ErrorBoundary: _,
    Cart_SaleCardDrops_EarnedMessage: _,
    Cart_SaleCardDrops_EarnedMessage_Plural: _,
    Cart_SaleCardDrops_Explanation: _,
    Cart_SaleCardDrops_Explanation_Gifts: _,
    Cart_SaleCardDrops_ProgressLabel: _,
    Cart_SaleCardDrops_CardCost: _,
    Cart_SaleCardDrops_PrepurchaseIneligible: _,
    Cart_PurchaseRequestTitle: _,
    Cart_PurchaseFor_Label: _,
    Cart_GiftForNotice: _,
    Cart_LineItem_Add_Tooltip: _,
    Cart_LineItem_Hardware_Compliance_Label: _,
    Cart_ErrorUpdating: _,
    Cart_ErrorCode: _,
    Cart_UserCountrySelector: _,
    Cart_Replay_SavedCart: _,
    Cart_Replay_Instructions: _,
    Cart_Gifting_CopyGiftOptionsFrom: _,
    Cart_Gifting_SignInToSelectFriends: _,
  };
export {
  _ as Cart_Add,
  _ as Cart_AddedToYourCart,
  _ as Cart_BetaNotice,
  _ as Cart_Bradcrumb_Home,
  _ as Cart_CartLevelErrorFormat,
  _ as Cart_CartLevelErrorMultiple,
  _ as Cart_CartLevelErrorNotice,
  _ as Cart_ChangeGiftRecipient,
  _ as Cart_ComingSoon,
  _ as Cart_ContainsGiftCheckbox,
  _ as Cart_ContinueButton_Gifts,
  _ as Cart_ContinueButton_Login,
  _ as Cart_ContinueButton_Payment,
  _ as Cart_ContinueShopping,
  _ as Cart_CountWidget,
  _ as Cart_CouponAvailability,
  _ as Cart_CouponAvailability_Plural,
  _ as Cart_CouponModify_Add,
  _ as Cart_CouponModify_Change,
  _ as Cart_Coupons_Applied,
  _ as Cart_Coupons_InUse,
  _ as Cart_DeclinePurchaseRequest,
  _ as Cart_Edit,
  _ as Cart_EditGiftDelivery,
  _ as Cart_Empty,
  _ as Cart_EnterRecipientEmail,
  _ as Cart_ErrorCode,
  _ as Cart_ErrorUpdating,
  _ as Cart_Error_AdultContentRestricted_FootNote,
  _ as Cart_Error_AdultContentRestricted_LineItem,
  _ as Cart_Error_AlreadyOwned_FootNote,
  _ as Cart_Error_AlreadyOwned_GiftFootNote,
  _ as Cart_Error_AlreadyOwned_GiftLineItem,
  _ as Cart_Error_AlreadyOwned_GiftLineItem_Game,
  _ as Cart_Error_AlreadyOwned_LineItem,
  _ as Cart_Error_AlreadyOwned_LineItem_Game,
  _ as Cart_Error_CommercialLicenseRestricted_FootNote,
  _ as Cart_Error_CommercialLicenseRestricted_LineItem,
  _ as Cart_Error_CouponIsExclusivePromo,
  _ as Cart_Error_CouponIsInvalid,
  _ as Cart_Error_CouponIsInvalidForItem,
  _ as Cart_Error_DuplicateApps_FootNote,
  _ as Cart_Error_DuplicateApps_LineItem,
  _ as Cart_Error_ExistingBillingAgreement,
  _ as Cart_Error_ExistingBillingAgreement_FootNote,
  _ as Cart_Error_GiftRecipientInvalid,
  _ as Cart_Error_MasterSubscription_FootNote,
  _ as Cart_Error_MasterSubscription_LineItem,
  _ as Cart_Error_MissingMustOwnApps_FootNote,
  _ as Cart_Error_MissingMustOwnApps_FootNoteGift,
  _ as Cart_Error_MissingMustOwnApps_GiftLineItem,
  _ as Cart_Error_MissingMustOwnApps_LineItem,
  _ as Cart_Error_TooManyInCart,
  _ as Cart_Error_UnavailableCountry_FootNote,
  _ as Cart_Error_UnavailableCountry_LineItem,
  _ as Cart_EstimatedTotal,
  _ as Cart_FamilyGift_Notice,
  _ as Cart_FooterNoticeHeader_MustFix,
  _ as Cart_FooterNoticeHeader_Warning,
  _ as Cart_GenericBetaNotice,
  _ as Cart_GiftDeliveryEmail_Warning1,
  _ as Cart_GiftDeliveryEmail_Warning2,
  _ as Cart_GiftDelivery_AddSignature,
  _ as Cart_GiftDelivery_Body,
  _ as Cart_GiftDelivery_From,
  _ as Cart_GiftDelivery_Label,
  _ as Cart_GiftDelivery_Now,
  _ as Cart_GiftDelivery_Reset,
  _ as Cart_GiftDelivery_ScheduleDelivery,
  _ as Cart_GiftDelivery_Scheduled,
  _ as Cart_GiftDelivery_Signature,
  _ as Cart_GiftForNotice,
  _ as Cart_GiftOptions,
  _ as Cart_GiftRecipientEmail_Label,
  _ as Cart_GiftRecipientModal_IssueLoading,
  _ as Cart_GiftRecipientModal_OnWishlist,
  _ as Cart_GiftRecipientModal_OwnsGameLabel,
  _ as Cart_GiftRecipientModal_PartialOwnsLabel,
  _ as Cart_GiftRecipientModal_PartialWishlistLabel,
  _ as Cart_GiftRecipientModal_Placeholder,
  _ as Cart_GiftRecipientModal_Save,
  _ as Cart_GiftRecipientModal_Title,
  _ as Cart_GiftRecipient_Label,
  _ as Cart_GiftScheduleError_InvalidDate,
  _ as Cart_GiftScheduleError_TooFar,
  _ as Cart_GifteeHint_Wishlist,
  _ as Cart_Gifting_CopyGiftOptionsFrom,
  _ as Cart_Gifting_SignInToSelectFriends,
  _ as Cart_IncludesItems,
  _ as Cart_IncludesItems_Plural,
  _ as Cart_LineItemGift_Checkbox,
  _ as Cart_LineItemOptions_Gift,
  _ as Cart_LineItemOptions_GiftForPersona,
  _ as Cart_LineItemOptions_Myself,
  _ as Cart_LineItemOptions_PrivateTooltip,
  _ as Cart_LineItemOptions_Privately,
  _ as Cart_LineItem_Add_Tooltip,
  _ as Cart_LineItem_ErrorBoundary,
  _ as Cart_LineItem_Hardware_Compliance_Label,
  _ as Cart_Note_SalesTax,
  _ as Cart_Notice_SomeAppsPrivate,
  _ as Cart_PurchaseBtn,
  _ as Cart_PurchaseFor_Label,
  _ as Cart_PurchaseRequestTitle,
  _ as Cart_Quantity,
  _ as Cart_Remove,
  _ as Cart_RemoveAll,
  _ as Cart_Replay_Instructions,
  _ as Cart_Replay_SavedCart,
  _ as Cart_RequestPurchase,
  _ as Cart_RequestPurchaseExplanation,
  _ as Cart_RequestPurchaseNonGiftableItems,
  _ as Cart_SaleCardDrops_CardCost,
  _ as Cart_SaleCardDrops_EarnedMessage,
  _ as Cart_SaleCardDrops_EarnedMessage_Plural,
  _ as Cart_SaleCardDrops_Explanation,
  _ as Cart_SaleCardDrops_Explanation_Gifts,
  _ as Cart_SaleCardDrops_PrepurchaseIneligible,
  _ as Cart_SaleCardDrops_ProgressLabel,
  _ as Cart_SelectCouponToApply,
  _ as Cart_SelectRecipient,
  _ as Cart_ShippingEstimate_Delayed,
  _ as Cart_ShippingEstimate_DeliveryDate,
  _ as Cart_ShippingEstimate_Range,
  _ as Cart_ShippingEstimate_Standard,
  _ as Cart_UpdatedYourCart,
  _ as Cart_UserCountrySelector,
  _ as Cart_Verify,
  _ as Cart_ViewMyCart,
  _ as Cart_Warning_AlreadyOwned_LineItem,
  _ as Cart_Warning_AvailableAtALowerPrice,
  _ as Cart_Warning_ExtraCopies_LineItem,
  _ as Cart_Warning_GiftToAccount_LoggedOut_Actionable,
  _ as Cart_Warning_GiftToNonFriend,
  _ as Cart_Warning_GiftToNonFriend_Named,
  _ as Cart_Warning_NoRefund_LineItem,
  _ as Cart_Warning_PriceChange_FootNote,
  _ as Cart_Warning_PriceChange_LineItem,
  _ as Cart_Warning_RecipientHigherPrice,
  _ as Cart_YourShoppingCart,
  _ as Cart_YourShoppingCartLineItems,
  _ as Cart_YourShoppingCartLineItems_Plural,
  _ as GameBillingAuthorizeSubscriptionByDay,
  _ as GameBillingAuthorizeSubscriptionByHour,
  _ as GameBillingAuthorizeSubscriptionByMinute,
  _ as GameBillingAuthorizeSubscriptionByMonth,
  _ as GameBillingAuthorizeSubscriptionBySecond,
  _ as GameBillingAuthorizeSubscriptionByWeek,
  _ as GameBillingAuthorizeSubscriptionByYear,
  _ as GameBillingPackageCostIncludesSubscriptionByDay,
  _ as GameBillingPackageCostIncludesSubscriptionByHour,
  _ as GameBillingPackageCostIncludesSubscriptionByMinute,
  _ as GameBillingPackageCostIncludesSubscriptionByMonth,
  _ as GameBillingPackageCostIncludesSubscriptionBySecond,
  _ as GameBillingPackageCostIncludesSubscriptionByWeek,
  _ as GameBillingPackageCostIncludesSubscriptionByYear,
  _ as GameBillingPackageIncludesSubscriptionByDay,
  _ as GameBillingPackageIncludesSubscriptionByHour,
  _ as GameBillingPackageIncludesSubscriptionByMinute,
  _ as GameBillingPackageIncludesSubscriptionByMonth,
  _ as GameBillingPackageIncludesSubscriptionBySecond,
  _ as GameBillingPackageIncludesSubscriptionByWeek,
  _ as GameBillingPackageIncludesSubscriptionByYear,
  _ as MicroTxnSubscriptionCostByDay,
  _ as MicroTxnSubscriptionCostByHour,
  _ as MicroTxnSubscriptionCostByMinute,
  _ as MicroTxnSubscriptionCostByMonth,
  _ as MicroTxnSubscriptionCostBySecond,
  _ as MicroTxnSubscriptionCostByWeek,
  _ as MicroTxnSubscriptionCostByYear,
  _ as MultiLicenseCostIncludesSubscriptionByDay,
  _ as MultiLicenseCostIncludesSubscriptionByHour,
  _ as MultiLicenseCostIncludesSubscriptionByMinute,
  _ as MultiLicenseCostIncludesSubscriptionByMonth,
  _ as MultiLicenseCostIncludesSubscriptionBySecond,
  _ as MultiLicenseCostIncludesSubscriptionByWeek,
  _ as MultiLicenseCostIncludesSubscriptionByYear,
  _ as MultiLicenseIncludesSubscriptionByDay,
  _ as MultiLicenseIncludesSubscriptionByHour,
  _ as MultiLicenseIncludesSubscriptionByMinute,
  _ as MultiLicenseIncludesSubscriptionByMonth,
  _ as MultiLicenseIncludesSubscriptionBySecond,
  _ as MultiLicenseIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByDay,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByHour,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMinute,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMonth,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionBySecond,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByYear,
  _ as MultiLicenseeIncludesSubscriptionByYear,
  _ as PackageCostIncludesSubscriptionByDay,
  _ as PackageCostIncludesSubscriptionByHour,
  _ as PackageCostIncludesSubscriptionByMinute,
  _ as PackageCostIncludesSubscriptionByMonth,
  _ as PackageCostIncludesSubscriptionBySecond,
  _ as PackageCostIncludesSubscriptionByWeek,
  _ as PackageCostIncludesSubscriptionByYear,
  _ as PackageIncludesSubscriptionByDay,
  _ as PackageIncludesSubscriptionByHour,
  _ as PackageIncludesSubscriptionByMinute,
  _ as PackageIncludesSubscriptionByMonth,
  _ as PackageIncludesSubscriptionBySecond,
  _ as PackageIncludesSubscriptionByWeek,
  _ as PackageIncludesSubscriptionByYear,
  _ as PackageWithDiscountCostIncludesSubscriptionByDay,
  _ as PackageWithDiscountCostIncludesSubscriptionByHour,
  _ as PackageWithDiscountCostIncludesSubscriptionByMinute,
  _ as PackageWithDiscountCostIncludesSubscriptionByMonth,
  _ as PackageWithDiscountCostIncludesSubscriptionBySecond,
  _ as PackageWithDiscountCostIncludesSubscriptionByWeek,
  _ as PackageWithDiscountCostIncludesSubscriptionByYear,
  _ as default,
  _ as language,
};
