var _ = `finnish`,
  _ = `Poista`,
  _ = `Lisää`,
  _ = `Vahvista ikä`,
  _ = `Poista kaikki tuotteet`,
  _ = `Muokkaa`,
  _ = `%1$s kpl`,
  _ = `Ostoskori`,
  _ = `Ostoskori (%1$s tuote)`,
  _ = `Ostoskori (%1$s tuotetta)`,
  _ = `Arvioitu kokonaishinta`,
  _ = `Liikevaihtovero lasketaan tarvittaessa kassalla`,
  _ = `Osta`,
  _ = `Tämä ostos sisältää lahjan`,
  _ = `Aloitussivu`,
  _ = `Onko tämä lahja?`,
  _ = `Sisältää %1$s tuotteen`,
  _ = `Sisältää %1$s tuotetta`,
  _ = `Valitse vastaanottaja`,
  _ = `Syötä sähköpostiosoite`,
  _ = `Muokkaa lahjan saajaa`,
  _ = `Lahjan saaja:`,
  _ = `Lahjan saajan sähköpostiosoite:`,
  _ = `Toimitus:`,
  _ = `Nollaa`,
  _ = `Mahdollisimman pian (sähköpostilla ja Steam-asiakasohjelman kautta)`,
  _ = `Aikataulutettu:`,
  _ = `Valitse toimitusajankohta`,
  _ = `Käyttäjältä:`,
  _ = `Allekirjoitus:`,
  _ = `Lisää mukautettu allekirjoitus`,
  _ = `Lahjan viesti (korkeintaan 160 merkkiä, %1$s jäljellä):`,
  _ = `Sähköpostitse lähetetyt lahjat hyvitetään automaattisesti 30 päivän kuluttua, jos niitä ei ole lisätty Steam-tilille.`,
  _ = `Sähköpostitse lähetetyt lahjat voidaan lisätä tileille vain samalla alueella, jossa myös lahjanostaja sijaitsee.`,
  _ = `Steam-perheen lapsille lähetetyt lahjat lisätään automaattisesti heidän tileilleen ja heille sallittuihin peleihin.`,
  _ = `Valitse lahjan saaja`,
  _ = `Muokkaa toimitustapaa`,
  _ = `Tallenna`,
  _ = `Hae kaverin nimellä`,
  _ = `Omistaa jo tämän tuotteen`,
  _ = `Toivelistalla`,
  _ = `Omistaa jo tuotteen %1$s`,
  _ = `Toivoo tuotetta %1$s`,
  _ = `Lahjavaihtoehdot`,
  _ = `Lahjan mahdollisia vastaanottajia ei pystytty lataamaan. Yritä myöhemmin uudelleen.`,
  _ = `Jatka maksuun`,
  _ = `Jatka lahjavaihtoehtoihin`,
  _ = `Kirjaudu sisään ostaaksesi`,
  _ = `Hylkää pyyntö`,
  _ = `Omalle tilille`,
  _ = `Lahjaksi jollekulle`,
  _ = `Lahja käyttäjälle %1$s`,
  _ = `Omalle tilille, mutta yksityisenä`,
  _ = `Ostoskori (%1$s)`,
  _ = `Lisätty ostoskoriin!`,
  _ = `Ostoskorisi on päivitetty.`,
  _ = `Jatka ostosten tekemistä`,
  _ = `Saatavilla %1$s`,
  _ = `Näytä ostoskori (%1$s)`,
  _ = `Pyydä lupaa ostokseen`,
  _ = `Steam-perheesi aikuiset saavat ilmoituksen ostopyynnöstäsi.`,
  _ = `Ostosta ei voi pyytää, koska ostoskorin kaikkia tuotteita ei voi lahjoittaa`,
  _ = `Vaihda tai poista kuponki`,
  _ = `Lisää kuponki`,
  _ = `Sinulla on kuponki tälle tuotteelle`,
  _ = `Sinulla on %1$s kuponkia tälle tuotteelle`,
  _ = `Tällä hetkellä käytössä`,
  _ = `Kuponki käytössä toiseen tuotteeseen`,
  _ = `Valitse kuponki tuotteelle %1$s`,
  _ = `Arvioitu toimitusaika: %1$s`,
  _ = `%1$s–%2$s arkipäivää`,
  _ = `Arvioitu toimitusaika: 6–10 arkipäivää`,
  _ = `Arvioitu toimitusaika: 3–5 arkipäivää`,
  _ = `Ennen kuin voit jatkaa maksamista:`,
  _ = `Lisätiedot:`,
  _ = `Maksamisen jatkamiseksi vaaditaan toimenpiteitä`,
  _ = `Lisätiedot:`,
  _ = `Huomaa! %1$s`,
  _ = `Tilisi omistaa jo osan yllä olevista tuotteista, joten et voi ostaa niitä uudelleen. Voit ostaa tuotteet lahjoina tai muuttaa ostoskorin sisältöä jatkaaksesi.`,
  _ = `Omistat jo tämän pelin`,
  _ = `Omistat jo tämän paketin koko sisällön`,
  _ = `Lahjan vastaanottaja omistaa jo pelin`,
  _ = `Lahjan vastaanottaja omistaa jo paketin koko sisällön`,
  _ = `Lahjan vastaanottaja omistaa jo osan yllä olevista tuotteista, joten et voi ostaa niitä uudelleen. Voit jatkaa muuttamalla tiliä, jolle tuotteet ostetaan tai muuttamalla ostoskorin sisältöä.`,
  _ = `Ostoskorissasi on paketteja, joissa on samoja tuotteita. Ylimääräiset paketit on poistettava korista, ennen kuin voit jatkaa kassalle.`,
  _ = `Jo ostoskorissa: `,
  _ = `Ostoskorisi sisältää paketin, joka ei ole saatavilla maassasi. Poista paketti ostoskorista, ennen kuin voit jatkaa kassalle.`,
  _ = `Ei saatavilla maassasi`,
  _ = `Ennen kuin voit ostaa aikuisille suunnattua seksuaalista sisältöä, Valven on vahvistettava, että olet vähintään 18-vuotias.`,
  _ = `Ostamiseen vaaditaan iän vahvistus.`,
  _ = `Ostoskorissasi on sisältöä, joka on saatavilla myös aktiivisen tilauksesi kautta.`,
  _ = `Saatavilla tilauksesi kautta:`,
  _ = `Kuponkia ei voi käyttää yhdessä muun alennuksen kanssa.`,
  _ = `Kuponki ei kelpaa tai se on vanhentunut.`,
  _ = `Kuponkia ei voi käyttää tähän tuotteeseen.`,
  _ = `Olet lisännyt ostoskoriin liian monta kappaletta samaa tuotetta.`,
  _ = `Ostoskorisi sisältää tuotteen, joka ei ole saatavilla.`,
  _ = `Ei ostettavissa`,
  _ = `Valittu vastaanottaja ei voi vastaanottaa alueeltasi ostettua lahjaa.`,
  _ = `Voit ostaa esineen vain, jos omistat seuraavat esineet:`,
  _ = `Vaatimuksena on, että lahjansaaja omistaa seuraavat esineet:`,
  _ = `Sinulla ei ole esineitä, joita vaaditaan ostoskorin esineiden ostamiseen. Voit lisätä puuttuvat esineet tai muokata ostoskorin sisältöä jatkaaksesi.`,
  _ = `Lahjan saajalla ei ole esineitä, joita vaaditaan ostoskorin esineiden ostamiseen. Voit lisätä puuttuvat esineet tai muokata ostoskorin sisältöä jatkaaksesi.`,
  _ = `Sinulla on jo tilaus, joka sisältää tämän tuotteen.`,
  _ = `Tililläsi on jo tilaus, joka sisältää joitakin valitsemistasi tuotteista. Tarkista tilauksesi asetukset tilitiedoista.`,
  _ = `Jos ostat itsellesi, et saa ylimääräistä kopiota tuotteesta`,
  _ = `Jos ostat itsellesi, saat ylimääräisen lahjoituskelpoisen kopion tuotteesta:`,
  _ = `Yhden tai useamman tuotteen hinta on muuttunut ostoskoriin lisäämisen jälkeen.`,
  _ = `Tuotteen hinta on muuttunut`,
  _ = `Tuotteessa on kulutustavaratyyppistä sisältöä, joten se ei ole hyvityskelpoinen.`,
  _ = `Lahjalle valitsemasi vastaanottaja on alueella, jonka hinnat ovat korkeampia. Tuotteen hinta on päivitetty vastaamaan hintaa vastaanottajan alueella, jotta sen voisi antaa lahjaksi.`,
  _ = `Tämä tuote on saatavilla halvempaan hintaan myyntipaketissa %1$s.`,
  _ = `Lahjan vastaanottaja EI ole Steam-kaverilistallasi.`,
  _ = `Huomaa! %1$s ei ole Steam-kaverilistallasi.`,
  _ = `Jos lähetät lahjan Steam-kaverille, <1>kirjaudu sisään</1> vahvistaaksesi, että kyseinen käyttäjä on kaverilistallasi.`,
  _ = `Katselit äskettäin käyttäjän %1$s toivelistaa. Haluatko lahjoittaa nämä tuotteet hänelle?`,
  _ = `Tilausta veloitetaan %1$s %2$s sekunnin välein.`,
  _ = `Tilausta laskutetaan %1$s %2$s minuutin välein.`,
  _ = `Tilausta laskutetaan %1$s %2$s tunnin välein.`,
  _ = `Tilausta laskutetaan %1$s %2$s päivän välein.`,
  _ = `Tilausta laskutetaan %1$s %2$s viikon välein.`,
  _ = `Tilausta laskutetaan %1$s %2$s kuukauden välein.`,
  _ = `Tilausta laskutetaan %1$s %2$s vuoden välein.`,
  _ = `Tilausta veloitetaan %1$s %2$s sekunnin välein lisenssiä kohti.`,
  _ = `Tilausta veloitetaan %1$s %2$s minuutin välein lisenssiä kohti.`,
  _ = `Tilausta veloitetaan %1$s %2$s tunnin välein lisenssiä kohti.`,
  _ = `Tilausta veloitetaan %1$s %2$s päivän välein lisenssiä kohti.`,
  _ = `Tilausta veloitetaan %1$s %2$s viikon välein lisenssiä kohti.`,
  _ = `Tilausta veloitetaan %1$s %2$s kuukauden välein lisenssiä kohti.`,
  _ = `Tilausta veloitetaan %1$s %2$s vuoden välein lisenssiä kohti.`,
  _ = `Tilausta veloitetaan %1$s %2$s sekunnin välein tai pelitilisi määritysten mukaisesti.`,
  _ = `Tilausta veloitetaan %1$s %2$s minuutin välein tai pelitilisi määritysten mukaisesti.`,
  _ = `Tilausta veloitetaan %1$s %2$s tunnin välein tai pelitilisi määritysten mukaisesti.`,
  _ = `Tilausta veloitetaan %1$s %2$s päivän välein tai pelitilisi määritysten mukaisesti.`,
  _ = `Tilausta veloitetaan %1$s %2$s viikon välein tai pelitilisi määritysten mukaisesti.`,
  _ = `Tilausta veloitetaan %1$s %2$s kuukauden välein tai pelitilisi määritysten mukaisesti.`,
  _ = `Tilausta veloitetaan %1$s %2$s vuoden välein tai pelitilisi määritysten mukaisesti.`,
  _ = `Sinulta veloitetaan kassalla %1$s.<br/>Valtuutat myös nämä automaattiset maksut: %2$s joka %3$s. sekunti.`,
  _ = `Sinulta veloitetaan kassalla %1$s.<br/>Valtuutat myös nämä automaattiset maksut: %2$s joka %3$s. minuutti.`,
  _ = `Sinulta veloitetaan kassalla %1$s.<br/>Valtuutat myös nämä automaattiset maksut: %2$s joka %3$s. tunti.`,
  _ = `Sinulta veloitetaan kassalla %1$s.<br/>Valtuutat myös nämä automaattiset maksut: %2$s joka %3$s. päivä.`,
  _ = `Sinulta veloitetaan kassalla %1$s.<br/>Valtuutat myös nämä automaattiset maksut: %2$s joka %3$s. viikko.`,
  _ = `Sinulta veloitetaan kassalla %1$s.<br/>Valtuutat myös nämä automaattiset maksut: %2$s joka %3$s. kuukausi.`,
  _ = `Sinulta veloitetaan kassalla %1$s.<br/>Valtuutat myös nämä automaattiset maksut: %2$s joka %3$s. vuosi.`,
  _ = `Sinulta veloitetaan kassalla %1$s.<br/>Valtuutat samalla pelin veloittamaan suoraan jopa %2$s joka %3$s. sekunti.`,
  _ = `Sinulta veloitetaan kassalla %1$s.<br/>Valtuutat samalla pelin veloittamaan suoraan jopa %2$s joka %3$s. minuutti.`,
  _ = `Sinulta veloitetaan kassalla %1$s.<br/>Valtuutat samalla pelin veloittamaan suoraan jopa %2$s joka %3$s. tunti.`,
  _ = `Sinulta veloitetaan kassalla %1$s.<br/>Valtuutat samalla pelin veloittamaan suoraan jopa %2$s joka %3$s. päivä.`,
  _ = `Sinulta veloitetaan kassalla %1$s.<br/>Valtuutat samalla pelin veloittamaan suoraan jopa %2$s joka %3$s. viikko.`,
  _ = `Sinulta veloitetaan kassalla %1$s.<br/>Valtuutat samalla pelin veloittamaan suoraan jopa %2$s joka %3$s. kuukausi.`,
  _ = `Sinulta veloitetaan kassalla %1$s.<br/>Valtuutat samalla pelin veloittamaan suoraan jopa %2$s joka %3$s. vuosi.`,
  _ = `%1$s veloitetaan nyt, tilaus uusitaan automaattisesti %3$s sekunnin välein hintaan %2$s.`,
  _ = `%1$s veloitetaan nyt, tilaus uusitaan automaattisesti %3$s minuutin välein hintaan %2$s.`,
  _ = `%1$s veloitetaan nyt, tilaus uusitaan automaattisesti %3$s tunnin välein hintaan %2$s.`,
  _ = `%1$s veloitetaan nyt, tilaus uusitaan automaattisesti %3$s päivän välein hintaan %2$s.`,
  _ = `%1$s veloitetaan nyt, tilaus uusitaan automaattisesti %3$s viikon välein hintaan %2$s.`,
  _ = `%1$s veloitetaan nyt, tilaus uusitaan automaattisesti %3$s kuukauden välein hintaan %2$s.`,
  _ = `%1$s veloitetaan nyt, tilaus uusitaan automaattisesti %3$s vuoden välein hintaan %2$s.`,
  _ = `%1$s hinnasta saa %4$s %:n alennuksen, jos hankit tilauksen ensimmäistä kertaa. Tilaus uusiutuu automaattisesti %3$s sekunnin välein hintaan %2$s.`,
  _ = `%1$s hinnasta saa %4$s %:n alennuksen, jos hankit tilauksen ensimmäistä kertaa. Tilaus uusiutuu automaattisesti %3$s minuutin välein hintaan %2$s.`,
  _ = `%1$s hinnasta saa %4$s %:n alennuksen, jos hankit tilauksen ensimmäistä kertaa. Tilaus uusiutuu automaattisesti %3$s tunnin välein hintaan %2$s.`,
  _ = `%1$s hinnasta saa %4$s %:n alennuksen, jos hankit tilauksen ensimmäistä kertaa. Tilaus uusiutuu automaattisesti %3$s päivän välein hintaan %2$s.`,
  _ = `%1$s hinnasta saa %4$s %:n alennuksen, jos hankit tilauksen ensimmäistä kertaa. Tilaus uusiutuu automaattisesti %3$s viikon välein hintaan %2$s.`,
  _ = `%1$s hinnasta saa %4$s %:n alennuksen, jos hankit tilauksen ensimmäistä kertaa. Tilaus uusiutuu automaattisesti %3$s kuukauden välein hintaan %2$s.`,
  _ = `%1$s hinnasta saa %4$s %:n alennuksen, jos hankit tilauksen ensimmäistä kertaa. Tilaus uusiutuu automaattisesti %3$s vuoden välein hintaan %2$s.`,
  _ = `%1$s veloitetaan nyt, tilaus uusitaan automaattisesti %3$s sekunnin välein hintaan %2$s pelitilisi määritysten mukaisesti.`,
  _ = `%1$s veloitetaan nyt, tilaus uusitaan automaattisesti %3$s minuutin välein hintaan %2$s pelitilisi määritysten mukaisesti.`,
  _ = `%1$s veloitetaan nyt, tilaus uusitaan automaattisesti %3$s tunnin välein hintaan %2$s pelitilisi määritysten mukaisesti.`,
  _ = `%1$s veloitetaan nyt, tilaus uusitaan automaattisesti %3$s päivän välein hintaan %2$s pelitilisi määritysten mukaisesti.`,
  _ = `%1$s veloitetaan nyt, tilaus uusitaan automaattisesti %3$s viikon välein hintaan %2$s pelitilisi määritysten mukaisesti.`,
  _ = `%1$s veloitetaan nyt, tilaus uusitaan automaattisesti %3$s kuukauden välein hintaan %2$s pelitilisi määritysten mukaisesti.`,
  _ = `%1$s veloitetaan nyt, tilaus uusitaan automaattisesti %3$s vuoden välein hintaan %2$s pelitilisi määritysten mukaisesti.`,
  _ = `Kassalla %1$s, ja sen jälkeen automaattisesti %3$s sekunnin välein %2$s/lisenssi.`,
  _ = `Kassalla %1$s, ja sen jälkeen automaattisesti %3$s minuutin välein %2$s/lisenssi.`,
  _ = `Kassalla %1$s, ja sen jälkeen automaattisesti %3$s tunnin välein %2$s/lisenssi.`,
  _ = `Kassalla %1$s, ja sen jälkeen automaattisesti %3$s päivän välein %2$s/lisenssi.`,
  _ = `Kassalla %1$s, ja sen jälkeen automaattisesti %3$s viikon välein %2$s/lisenssi.`,
  _ = `Kassalla %1$s, ja sen jälkeen automaattisesti %3$s kuukauden välein %2$s/lisenssi.`,
  _ = `Kassalla %1$s, ja sen jälkeen automaattisesti %3$s vuoden välein %2$s/lisenssi.`,
  _ = `%1$s hinnasta saa %4$s %:n alennuksen, jos hankit tilauksen ensimmäistä kertaa. Tilaus uusiutuu automaattisesti %3$s sekunnin välein hintaan %2$s lisenssiä kohti.`,
  _ = `%1$s hinnasta saa %4$s %:n alennuksen, jos hankit tilauksen ensimmäistä kertaa. Tilaus uusiutuu automaattisesti %3$s minuutin välein hintaan %2$s lisenssiä kohti.`,
  _ = `%1$s hinnasta saa %4$s %:n alennuksen, jos hankit tilauksen ensimmäistä kertaa. Tilaus uusiutuu automaattisesti %3$s tunnin välein hintaan %2$s lisenssiä kohti.`,
  _ = `%1$s hinnasta saa %4$s %:n alennuksen, jos hankit tilauksen ensimmäistä kertaa. Tilaus uusiutuu automaattisesti %3$s päivän välein hintaan %2$s lisenssiä kohti.`,
  _ = `%1$s hinnasta saa %4$s %:n alennuksen, jos hankit tilauksen ensimmäistä kertaa. Tilaus uusiutuu automaattisesti %3$s viikon välein hintaan %2$s lisenssiä kohti.`,
  _ = `%1$s hinnasta saa %4$s %:n alennuksen, jos hankit tilauksen ensimmäistä kertaa. Tilaus uusiutuu automaattisesti %3$s kuukauden välein hintaan %2$s lisenssiä kohti.`,
  _ = `%1$s hinnasta saa %4$s %:n alennuksen, jos hankit tilauksen ensimmäistä kertaa. Tilaus uusiutuu automaattisesti %3$s vuoden välein hintaan %2$s lisenssiä kohti.`,
  _ = `Ostoskori on tyhjä.`,
  _ = `Jotkut näistä kohteista on merkitty yksityisiksi. Ne pysyvät yksityisinä, jos jatkat:`,
  _ = `Pelin merkitseminen yksityiseksi piilottaa sen kaikkialla kirjastosi ulkopuolella. Pelin omistaminen, pelin tila, peliaika ja -toiminta eivät näy muille käyttäjille.`,
  _ = `Näet uudenlaisen version ostoskorista, koska käytät Steam-asiakasohjelman betaversiota. <1>Anna palautetta tai ilmoita virheistä</1>`,
  _ = `Uuden ostoskorin betatesti on vielä kesken. <1>Jätä palautetta tai ilmoita virheistä.</1>`,
  _ = `Lahjaa ei voi aikatauluttaa noin kauas tulevaisuuteen.`,
  _ = `Anna kelvollinen päivämäärä ja kellonaika.`,
  _ = `Tuotteen esittelykuvaa ei voida näyttää`,
  _ = `Ansaitset %1$s %2$s -keräilykortin tästä ostoksesta.`,
  _ = `Ansaitset %1$s %2$s -keräilykorttia tästä ostoksesta.`,
  _ = `Ansaitset %1$s -keräilykortteja alennusmyynnin aikana tehdyistä ostoksista.`,
  _ = `Saat ansaitut kortit, vaikka ostoksesi olisikin lahja.`,
  _ = `Edistyminen seuraavaan korttiin`,
  _ = `noin %1$s korttia kohden`,
  _ = `Huomaa! Seuraavista ennakkoon ostetuista esineistä ei saa palkinnoksi pelin %1$s keräilykortteja:`,
  _ = `Ostopyyntö käyttäjältä %1$s`,
  _ = `Ostos käyttäjälle:`,
  _ = `Osta lahjaksi: %1$s`,
  _ = `Lisää toinen kappale samasta tuotteesta ostoskoriin`,
  _ = `Yhdistyneen kuningaskunnan PSTI-vaatimustenmukaisuuslausunto`,
  _ = `Ostoskorin päivittämisessä tapahtui virhe.`,
  _ = `Virhekoodi: %1$s`,
  _ = `Maa`,
  _ = `Tallennettu ostoskori`,
  _ = `Tämä on tallennettu ostoskori. Viime kerralla ostoksen suorittamisessa tapahtui virhe, joten ostoskorisi tallennettiin (alennukset mukaan lukien) %1$s tunniksi, jotta sinulla olisi tilaisuus suorittaa maksutapahtuma loppuun.`,
  _ = `Kopioi lahjavaihtoehdot kohteesta`,
  _ = `Valitse Steam-kavereita <1>kirjautumalla sisään</1>`,
  _ = {
    language: _,
    Cart_Remove: _,
    Cart_Add: _,
    Cart_Verify: _,
    Cart_RemoveAll: _,
    Cart_Edit: _,
    Cart_Quantity: _,
    Cart_YourShoppingCart: _,
    Cart_YourShoppingCartLineItems: _,
    Cart_YourShoppingCartLineItems_Plural: _,
    Cart_EstimatedTotal: _,
    Cart_Note_SalesTax: _,
    Cart_PurchaseBtn: _,
    Cart_ContainsGiftCheckbox: _,
    Cart_Bradcrumb_Home: _,
    Cart_LineItemGift_Checkbox: _,
    Cart_IncludesItems: _,
    Cart_IncludesItems_Plural: _,
    Cart_SelectRecipient: _,
    Cart_EnterRecipientEmail: _,
    Cart_ChangeGiftRecipient: _,
    Cart_GiftRecipient_Label: _,
    Cart_GiftRecipientEmail_Label: _,
    Cart_GiftDelivery_Label: _,
    Cart_GiftDelivery_Reset: _,
    Cart_GiftDelivery_Now: _,
    Cart_GiftDelivery_Scheduled: _,
    Cart_GiftDelivery_ScheduleDelivery: _,
    Cart_GiftDelivery_From: _,
    Cart_GiftDelivery_Signature: _,
    Cart_GiftDelivery_AddSignature: _,
    Cart_GiftDelivery_Body: _,
    Cart_GiftDeliveryEmail_Warning1: _,
    Cart_GiftDeliveryEmail_Warning2: _,
    Cart_FamilyGift_Notice: _,
    Cart_GiftRecipientModal_Title: _,
    Cart_EditGiftDelivery: _,
    Cart_GiftRecipientModal_Save: _,
    Cart_GiftRecipientModal_Placeholder: _,
    Cart_GiftRecipientModal_OwnsGameLabel: _,
    Cart_GiftRecipientModal_OnWishlist: _,
    Cart_GiftRecipientModal_PartialOwnsLabel: _,
    Cart_GiftRecipientModal_PartialWishlistLabel: _,
    Cart_GiftOptions: _,
    Cart_GiftRecipientModal_IssueLoading: _,
    Cart_ContinueButton_Payment: _,
    Cart_ContinueButton_Gifts: _,
    Cart_ContinueButton_Login: _,
    Cart_DeclinePurchaseRequest: _,
    Cart_LineItemOptions_Myself: _,
    Cart_LineItemOptions_Gift: _,
    Cart_LineItemOptions_GiftForPersona: _,
    Cart_LineItemOptions_Privately: _,
    Cart_CountWidget: _,
    Cart_AddedToYourCart: _,
    Cart_UpdatedYourCart: _,
    Cart_ContinueShopping: _,
    Cart_ComingSoon: _,
    Cart_ViewMyCart: _,
    Cart_RequestPurchase: _,
    Cart_RequestPurchaseExplanation: _,
    Cart_RequestPurchaseNonGiftableItems: _,
    Cart_CouponModify_Change: _,
    Cart_CouponModify_Add: _,
    Cart_CouponAvailability: _,
    Cart_CouponAvailability_Plural: _,
    Cart_Coupons_Applied: _,
    Cart_Coupons_InUse: _,
    Cart_SelectCouponToApply: _,
    Cart_ShippingEstimate_DeliveryDate: _,
    Cart_ShippingEstimate_Range: _,
    Cart_ShippingEstimate_Delayed: _,
    Cart_ShippingEstimate_Standard: _,
    Cart_FooterNoticeHeader_MustFix: _,
    Cart_FooterNoticeHeader_Warning: _,
    Cart_CartLevelErrorNotice: _,
    Cart_CartLevelErrorMultiple: _,
    Cart_CartLevelErrorFormat: _,
    Cart_Error_AlreadyOwned_FootNote: _,
    Cart_Error_AlreadyOwned_LineItem_Game: _,
    Cart_Error_AlreadyOwned_LineItem: _,
    Cart_Error_AlreadyOwned_GiftLineItem_Game: _,
    Cart_Error_AlreadyOwned_GiftLineItem: _,
    Cart_Error_AlreadyOwned_GiftFootNote: _,
    Cart_Error_DuplicateApps_FootNote: _,
    Cart_Error_DuplicateApps_LineItem: _,
    Cart_Error_UnavailableCountry_FootNote: _,
    Cart_Error_UnavailableCountry_LineItem: _,
    Cart_Error_AdultContentRestricted_FootNote: _,
    Cart_Error_AdultContentRestricted_LineItem: _,
    Cart_Error_MasterSubscription_FootNote: _,
    Cart_Error_MasterSubscription_LineItem: _,
    Cart_Error_CouponIsExclusivePromo: _,
    Cart_Error_CouponIsInvalid: _,
    Cart_Error_CouponIsInvalidForItem: _,
    Cart_Error_TooManyInCart: _,
    Cart_Error_CommercialLicenseRestricted_FootNote: _,
    Cart_Error_CommercialLicenseRestricted_LineItem: _,
    Cart_Error_GiftRecipientInvalid: _,
    Cart_Error_MissingMustOwnApps_LineItem: _,
    Cart_Error_MissingMustOwnApps_GiftLineItem: _,
    Cart_Error_MissingMustOwnApps_FootNote: _,
    Cart_Error_MissingMustOwnApps_FootNoteGift: _,
    Cart_Error_ExistingBillingAgreement: _,
    Cart_Error_ExistingBillingAgreement_FootNote: _,
    Cart_Warning_AlreadyOwned_LineItem: _,
    Cart_Warning_ExtraCopies_LineItem: _,
    Cart_Warning_PriceChange_FootNote: _,
    Cart_Warning_PriceChange_LineItem: _,
    Cart_Warning_NoRefund_LineItem: _,
    Cart_Warning_RecipientHigherPrice: _,
    Cart_Warning_AvailableAtALowerPrice: _,
    Cart_Warning_GiftToNonFriend: _,
    Cart_Warning_GiftToNonFriend_Named: _,
    Cart_Warning_GiftToAccount_LoggedOut_Actionable: _,
    Cart_GifteeHint_Wishlist: _,
    PackageIncludesSubscriptionBySecond: _,
    PackageIncludesSubscriptionByMinute: _,
    PackageIncludesSubscriptionByHour: _,
    PackageIncludesSubscriptionByDay: _,
    PackageIncludesSubscriptionByWeek: _,
    PackageIncludesSubscriptionByMonth: _,
    PackageIncludesSubscriptionByYear: _,
    MultiLicenseIncludesSubscriptionBySecond: _,
    MultiLicenseIncludesSubscriptionByMinute: _,
    MultiLicenseIncludesSubscriptionByHour: _,
    MultiLicenseIncludesSubscriptionByDay: _,
    MultiLicenseIncludesSubscriptionByWeek: _,
    MultiLicenseIncludesSubscriptionByMonth: _,
    MultiLicenseeIncludesSubscriptionByYear: _,
    GameBillingPackageIncludesSubscriptionBySecond: _,
    GameBillingPackageIncludesSubscriptionByMinute: _,
    GameBillingPackageIncludesSubscriptionByHour: _,
    GameBillingPackageIncludesSubscriptionByDay: _,
    GameBillingPackageIncludesSubscriptionByWeek: _,
    GameBillingPackageIncludesSubscriptionByMonth: _,
    GameBillingPackageIncludesSubscriptionByYear: _,
    MicroTxnSubscriptionCostBySecond: _,
    MicroTxnSubscriptionCostByMinute: _,
    MicroTxnSubscriptionCostByHour: _,
    MicroTxnSubscriptionCostByDay: _,
    MicroTxnSubscriptionCostByWeek: _,
    MicroTxnSubscriptionCostByMonth: _,
    MicroTxnSubscriptionCostByYear: _,
    GameBillingAuthorizeSubscriptionBySecond: _,
    GameBillingAuthorizeSubscriptionByMinute: _,
    GameBillingAuthorizeSubscriptionByHour: _,
    GameBillingAuthorizeSubscriptionByDay: _,
    GameBillingAuthorizeSubscriptionByWeek: _,
    GameBillingAuthorizeSubscriptionByMonth: _,
    GameBillingAuthorizeSubscriptionByYear: _,
    PackageCostIncludesSubscriptionBySecond: _,
    PackageCostIncludesSubscriptionByMinute: _,
    PackageCostIncludesSubscriptionByHour: _,
    PackageCostIncludesSubscriptionByDay: _,
    PackageCostIncludesSubscriptionByWeek: _,
    PackageCostIncludesSubscriptionByMonth: _,
    PackageCostIncludesSubscriptionByYear: _,
    PackageWithDiscountCostIncludesSubscriptionBySecond: _,
    PackageWithDiscountCostIncludesSubscriptionByMinute: _,
    PackageWithDiscountCostIncludesSubscriptionByHour: _,
    PackageWithDiscountCostIncludesSubscriptionByDay: _,
    PackageWithDiscountCostIncludesSubscriptionByWeek: _,
    PackageWithDiscountCostIncludesSubscriptionByMonth: _,
    PackageWithDiscountCostIncludesSubscriptionByYear: _,
    GameBillingPackageCostIncludesSubscriptionBySecond: _,
    GameBillingPackageCostIncludesSubscriptionByMinute: _,
    GameBillingPackageCostIncludesSubscriptionByHour: _,
    GameBillingPackageCostIncludesSubscriptionByDay: _,
    GameBillingPackageCostIncludesSubscriptionByWeek: _,
    GameBillingPackageCostIncludesSubscriptionByMonth: _,
    GameBillingPackageCostIncludesSubscriptionByYear: _,
    MultiLicenseCostIncludesSubscriptionBySecond: _,
    MultiLicenseCostIncludesSubscriptionByMinute: _,
    MultiLicenseCostIncludesSubscriptionByHour: _,
    MultiLicenseCostIncludesSubscriptionByDay: _,
    MultiLicenseCostIncludesSubscriptionByWeek: _,
    MultiLicenseCostIncludesSubscriptionByMonth: _,
    MultiLicenseCostIncludesSubscriptionByYear: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionBySecond: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMinute: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByHour: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByDay: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByWeek: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMonth: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByYear: _,
    Cart_Empty: _,
    Cart_Notice_SomeAppsPrivate: _,
    Cart_LineItemOptions_PrivateTooltip: _,
    Cart_BetaNotice: _,
    Cart_GenericBetaNotice: _,
    Cart_GiftScheduleError_TooFar: _,
    Cart_GiftScheduleError_InvalidDate: _,
    Cart_LineItem_ErrorBoundary: _,
    Cart_SaleCardDrops_EarnedMessage: _,
    Cart_SaleCardDrops_EarnedMessage_Plural: _,
    Cart_SaleCardDrops_Explanation: _,
    Cart_SaleCardDrops_Explanation_Gifts: _,
    Cart_SaleCardDrops_ProgressLabel: _,
    Cart_SaleCardDrops_CardCost: _,
    Cart_SaleCardDrops_PrepurchaseIneligible: _,
    Cart_PurchaseRequestTitle: _,
    Cart_PurchaseFor_Label: _,
    Cart_GiftForNotice: _,
    Cart_LineItem_Add_Tooltip: _,
    Cart_LineItem_Hardware_Compliance_Label: _,
    Cart_ErrorUpdating: _,
    Cart_ErrorCode: _,
    Cart_UserCountrySelector: `Maa`,
    Cart_Replay_SavedCart: _,
    Cart_Replay_Instructions: _,
    Cart_Gifting_CopyGiftOptionsFrom: _,
    Cart_Gifting_SignInToSelectFriends: _,
  };
export {
  _ as Cart_Add,
  _ as Cart_AddedToYourCart,
  _ as Cart_BetaNotice,
  _ as Cart_Bradcrumb_Home,
  _ as Cart_CartLevelErrorFormat,
  _ as Cart_CartLevelErrorMultiple,
  _ as Cart_CartLevelErrorNotice,
  _ as Cart_ChangeGiftRecipient,
  _ as Cart_ComingSoon,
  _ as Cart_ContainsGiftCheckbox,
  _ as Cart_ContinueButton_Gifts,
  _ as Cart_ContinueButton_Login,
  _ as Cart_ContinueButton_Payment,
  _ as Cart_ContinueShopping,
  _ as Cart_CountWidget,
  _ as Cart_CouponAvailability,
  _ as Cart_CouponAvailability_Plural,
  _ as Cart_CouponModify_Add,
  _ as Cart_CouponModify_Change,
  _ as Cart_Coupons_Applied,
  _ as Cart_Coupons_InUse,
  _ as Cart_DeclinePurchaseRequest,
  _ as Cart_Edit,
  _ as Cart_EditGiftDelivery,
  _ as Cart_Empty,
  _ as Cart_EnterRecipientEmail,
  _ as Cart_ErrorCode,
  _ as Cart_ErrorUpdating,
  _ as Cart_Error_AdultContentRestricted_FootNote,
  _ as Cart_Error_AdultContentRestricted_LineItem,
  _ as Cart_Error_AlreadyOwned_FootNote,
  _ as Cart_Error_AlreadyOwned_GiftFootNote,
  _ as Cart_Error_AlreadyOwned_GiftLineItem,
  _ as Cart_Error_AlreadyOwned_GiftLineItem_Game,
  _ as Cart_Error_AlreadyOwned_LineItem,
  _ as Cart_Error_AlreadyOwned_LineItem_Game,
  _ as Cart_Error_CommercialLicenseRestricted_FootNote,
  _ as Cart_Error_CommercialLicenseRestricted_LineItem,
  _ as Cart_Error_CouponIsExclusivePromo,
  _ as Cart_Error_CouponIsInvalid,
  _ as Cart_Error_CouponIsInvalidForItem,
  _ as Cart_Error_DuplicateApps_FootNote,
  _ as Cart_Error_DuplicateApps_LineItem,
  _ as Cart_Error_ExistingBillingAgreement,
  _ as Cart_Error_ExistingBillingAgreement_FootNote,
  _ as Cart_Error_GiftRecipientInvalid,
  _ as Cart_Error_MasterSubscription_FootNote,
  _ as Cart_Error_MasterSubscription_LineItem,
  _ as Cart_Error_MissingMustOwnApps_FootNote,
  _ as Cart_Error_MissingMustOwnApps_FootNoteGift,
  _ as Cart_Error_MissingMustOwnApps_GiftLineItem,
  _ as Cart_Error_MissingMustOwnApps_LineItem,
  _ as Cart_Error_TooManyInCart,
  _ as Cart_Error_UnavailableCountry_FootNote,
  _ as Cart_Error_UnavailableCountry_LineItem,
  _ as Cart_EstimatedTotal,
  _ as Cart_FamilyGift_Notice,
  _ as Cart_FooterNoticeHeader_MustFix,
  _ as Cart_FooterNoticeHeader_Warning,
  _ as Cart_GenericBetaNotice,
  _ as Cart_GiftDeliveryEmail_Warning1,
  _ as Cart_GiftDeliveryEmail_Warning2,
  _ as Cart_GiftDelivery_AddSignature,
  _ as Cart_GiftDelivery_Body,
  _ as Cart_GiftDelivery_From,
  _ as Cart_GiftDelivery_Label,
  _ as Cart_GiftDelivery_Now,
  _ as Cart_GiftDelivery_Reset,
  _ as Cart_GiftDelivery_ScheduleDelivery,
  _ as Cart_GiftDelivery_Scheduled,
  _ as Cart_GiftDelivery_Signature,
  _ as Cart_GiftForNotice,
  _ as Cart_GiftOptions,
  _ as Cart_GiftRecipientEmail_Label,
  _ as Cart_GiftRecipientModal_IssueLoading,
  _ as Cart_GiftRecipientModal_OnWishlist,
  _ as Cart_GiftRecipientModal_OwnsGameLabel,
  _ as Cart_GiftRecipientModal_PartialOwnsLabel,
  _ as Cart_GiftRecipientModal_PartialWishlistLabel,
  _ as Cart_GiftRecipientModal_Placeholder,
  _ as Cart_GiftRecipientModal_Save,
  _ as Cart_GiftRecipientModal_Title,
  _ as Cart_GiftRecipient_Label,
  _ as Cart_GiftScheduleError_InvalidDate,
  _ as Cart_GiftScheduleError_TooFar,
  _ as Cart_GifteeHint_Wishlist,
  _ as Cart_Gifting_CopyGiftOptionsFrom,
  _ as Cart_Gifting_SignInToSelectFriends,
  _ as Cart_IncludesItems,
  _ as Cart_IncludesItems_Plural,
  _ as Cart_LineItemGift_Checkbox,
  _ as Cart_LineItemOptions_Gift,
  _ as Cart_LineItemOptions_GiftForPersona,
  _ as Cart_LineItemOptions_Myself,
  _ as Cart_LineItemOptions_PrivateTooltip,
  _ as Cart_LineItemOptions_Privately,
  _ as Cart_LineItem_Add_Tooltip,
  _ as Cart_LineItem_ErrorBoundary,
  _ as Cart_LineItem_Hardware_Compliance_Label,
  _ as Cart_Note_SalesTax,
  _ as Cart_Notice_SomeAppsPrivate,
  _ as Cart_PurchaseBtn,
  _ as Cart_PurchaseFor_Label,
  _ as Cart_PurchaseRequestTitle,
  _ as Cart_Quantity,
  _ as Cart_Remove,
  _ as Cart_RemoveAll,
  _ as Cart_Replay_Instructions,
  _ as Cart_Replay_SavedCart,
  _ as Cart_RequestPurchase,
  _ as Cart_RequestPurchaseExplanation,
  _ as Cart_RequestPurchaseNonGiftableItems,
  _ as Cart_SaleCardDrops_CardCost,
  _ as Cart_SaleCardDrops_EarnedMessage,
  _ as Cart_SaleCardDrops_EarnedMessage_Plural,
  _ as Cart_SaleCardDrops_Explanation,
  _ as Cart_SaleCardDrops_Explanation_Gifts,
  _ as Cart_SaleCardDrops_PrepurchaseIneligible,
  _ as Cart_SaleCardDrops_ProgressLabel,
  _ as Cart_SelectCouponToApply,
  _ as Cart_SelectRecipient,
  _ as Cart_ShippingEstimate_Delayed,
  _ as Cart_ShippingEstimate_DeliveryDate,
  _ as Cart_ShippingEstimate_Range,
  _ as Cart_ShippingEstimate_Standard,
  _ as Cart_UpdatedYourCart,
  _ as Cart_UserCountrySelector,
  _ as Cart_Verify,
  _ as Cart_ViewMyCart,
  _ as Cart_Warning_AlreadyOwned_LineItem,
  _ as Cart_Warning_AvailableAtALowerPrice,
  _ as Cart_Warning_ExtraCopies_LineItem,
  _ as Cart_Warning_GiftToAccount_LoggedOut_Actionable,
  _ as Cart_Warning_GiftToNonFriend,
  _ as Cart_Warning_GiftToNonFriend_Named,
  _ as Cart_Warning_NoRefund_LineItem,
  _ as Cart_Warning_PriceChange_FootNote,
  _ as Cart_Warning_PriceChange_LineItem,
  _ as Cart_Warning_RecipientHigherPrice,
  _ as Cart_YourShoppingCart,
  _ as Cart_YourShoppingCartLineItems,
  _ as Cart_YourShoppingCartLineItems_Plural,
  _ as GameBillingAuthorizeSubscriptionByDay,
  _ as GameBillingAuthorizeSubscriptionByHour,
  _ as GameBillingAuthorizeSubscriptionByMinute,
  _ as GameBillingAuthorizeSubscriptionByMonth,
  _ as GameBillingAuthorizeSubscriptionBySecond,
  _ as GameBillingAuthorizeSubscriptionByWeek,
  _ as GameBillingAuthorizeSubscriptionByYear,
  _ as GameBillingPackageCostIncludesSubscriptionByDay,
  _ as GameBillingPackageCostIncludesSubscriptionByHour,
  _ as GameBillingPackageCostIncludesSubscriptionByMinute,
  _ as GameBillingPackageCostIncludesSubscriptionByMonth,
  _ as GameBillingPackageCostIncludesSubscriptionBySecond,
  _ as GameBillingPackageCostIncludesSubscriptionByWeek,
  _ as GameBillingPackageCostIncludesSubscriptionByYear,
  _ as GameBillingPackageIncludesSubscriptionByDay,
  _ as GameBillingPackageIncludesSubscriptionByHour,
  _ as GameBillingPackageIncludesSubscriptionByMinute,
  _ as GameBillingPackageIncludesSubscriptionByMonth,
  _ as GameBillingPackageIncludesSubscriptionBySecond,
  _ as GameBillingPackageIncludesSubscriptionByWeek,
  _ as GameBillingPackageIncludesSubscriptionByYear,
  _ as MicroTxnSubscriptionCostByDay,
  _ as MicroTxnSubscriptionCostByHour,
  _ as MicroTxnSubscriptionCostByMinute,
  _ as MicroTxnSubscriptionCostByMonth,
  _ as MicroTxnSubscriptionCostBySecond,
  _ as MicroTxnSubscriptionCostByWeek,
  _ as MicroTxnSubscriptionCostByYear,
  _ as MultiLicenseCostIncludesSubscriptionByDay,
  _ as MultiLicenseCostIncludesSubscriptionByHour,
  _ as MultiLicenseCostIncludesSubscriptionByMinute,
  _ as MultiLicenseCostIncludesSubscriptionByMonth,
  _ as MultiLicenseCostIncludesSubscriptionBySecond,
  _ as MultiLicenseCostIncludesSubscriptionByWeek,
  _ as MultiLicenseCostIncludesSubscriptionByYear,
  _ as MultiLicenseIncludesSubscriptionByDay,
  _ as MultiLicenseIncludesSubscriptionByHour,
  _ as MultiLicenseIncludesSubscriptionByMinute,
  _ as MultiLicenseIncludesSubscriptionByMonth,
  _ as MultiLicenseIncludesSubscriptionBySecond,
  _ as MultiLicenseIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByDay,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByHour,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMinute,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMonth,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionBySecond,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByYear,
  _ as MultiLicenseeIncludesSubscriptionByYear,
  _ as PackageCostIncludesSubscriptionByDay,
  _ as PackageCostIncludesSubscriptionByHour,
  _ as PackageCostIncludesSubscriptionByMinute,
  _ as PackageCostIncludesSubscriptionByMonth,
  _ as PackageCostIncludesSubscriptionBySecond,
  _ as PackageCostIncludesSubscriptionByWeek,
  _ as PackageCostIncludesSubscriptionByYear,
  _ as PackageIncludesSubscriptionByDay,
  _ as PackageIncludesSubscriptionByHour,
  _ as PackageIncludesSubscriptionByMinute,
  _ as PackageIncludesSubscriptionByMonth,
  _ as PackageIncludesSubscriptionBySecond,
  _ as PackageIncludesSubscriptionByWeek,
  _ as PackageIncludesSubscriptionByYear,
  _ as PackageWithDiscountCostIncludesSubscriptionByDay,
  _ as PackageWithDiscountCostIncludesSubscriptionByHour,
  _ as PackageWithDiscountCostIncludesSubscriptionByMinute,
  _ as PackageWithDiscountCostIncludesSubscriptionByMonth,
  _ as PackageWithDiscountCostIncludesSubscriptionBySecond,
  _ as PackageWithDiscountCostIncludesSubscriptionByWeek,
  _ as PackageWithDiscountCostIncludesSubscriptionByYear,
  _ as default,
  _ as language,
};
