var _ = `german`,
  _ = `Lokalisierung verwalten`,
  _ = `Exportieren und importieren Sie Lokalisierungsdateien, um die Übersetzung von Strings für Ihr gesamtes Event zu verwalten.`,
  _ = `Exportieren und importieren Sie Lokalisierungsdateien, um die Übersetzung von Strings für Ihre gesamte Seite zu verwalten.`,
  _ = `Anmelden`,
  _ = `Melden Sie sich an, um dieses Produkt Ihrer Wunschliste hinzuzufügen, ihm zu folgen oder es als ignoriert zu markieren. Mit einem Klick auf „OK“ werden Sie zur Anmeldeseite weitergeleitet.`,
  _ = `Melden Sie sich an oder öffnen Sie diese Seite in der Steam-Desktopanwendung, um Ihre Wunschliste zu ergänzen, ein Follower zu werden und Käufe zu tätigen.`,
  _ = `%1$s ist %2$s für das Steam Deck`,
  _ = `verifiziert`,
  _ = `Dieses und viele weitere Spiele wurden getestet und sind %1$s.`,
  _ = `für das Steam Deck optimiert`,
  _ = `Verifiziert-Häkchen`,
  _ = `Steam Deck OLED`,
  _ = `Steam-Deck-Banner: Ihre Spiele, überall`,
  _ = `Der Trailer entspricht möglicherweise nicht dem tatsächlichen Gameplay auf dem Steam Deck.`,
  _ = `%1$s gefunden (%2$s)`,
  _ = `Nicht gefunden (%1$s)`,
  _ = `Rezensionen dieser Anwendung`,
  _ = `Die Anwendung, deren Steam-Rezensionen in diesem Abschnitt angezeigt werden, und die Anwendung, für die eine Nutzerrezension hinterlassen wurde.`,
  _ = `%1$s URL wurde akzeptiert`,
  _ = `Fehler: URL verweist nicht auf eine Steam-Seite (Shop/Community).`,
  _ = `Ungültige Eingabe`,
  _ = `Kennzeichnungsfarbe`,
  _ = `Hintergrundfarbverlauf (oben)`,
  _ = `Hintergrundfarbverlauf (unten)`,
  _ = `Platz auf der Liste sichern`,
  _ = `Wählen Sie unten ein Modell aus, um sich zu registrieren. Berechtigte Kunden können sich für bis zu %1$s Modelle registrieren.`,
  _ = `Sie haben sich für die unten ausgewählten Modelle in die Liste eingetragen.`,
  _ = `Sie befinden sich auf der Liste für die unten ausgewählten Modelle. Berechtigte Kunden können sich für bis zu %1$s Modelle registrieren.`,
  _ = `Liste verlassen?`,
  _ = `Wenn Sie die Liste für dieses Modell verlassen, wird Ihr Name vor der Zufallsauswahl entfernt. Möchten Sie die Liste wirklich verlassen?`,
  _ = `Ich habe die <1>allgemeinen Geschäftsbedingungen</1> gelesen und stimme diesen zu.`,
  _ = `Bitte lesen Sie unten die allgemeinen Geschäftsbedingungen.`,
  _ = `Melden Sie sich an, um sich in die Liste einzutragen`,
  _ = `Melden Sie sich bei Steam an, um sich in die Liste einzutragen. Mit einem Klick auf „OK“ werden Sie zur Anmeldeseite weitergeleitet.`,
  _ = `Tragen Sie sich bis zum %1$s in die Liste ein. Alle Einträge werden nach Ablauf der Frist per Zufallsgenerator gemischt. Das Ergebnis wird Ihnen innerhalb eines Tages per E-Mail mitgeteilt. Eine Teilnahme nach Ablauf der oben genannten Frist ist nicht möglich.`,
  _ = `Wählen Sie unten ein Modell aus, um sich für die Warteliste zu registrieren.`,
  _ = `Die Liste ist geschlossen und die Reihenfolge der Ergebnisse wird nun zufallsgeneriert. Sie erhalten Ihre Ergebnisse innerhalb eines Tages per E-Mail.`,
  _ = `Die Liste ist geschlossen und die Reihenfolge der Ergebnisse wird nun zufallsgeneriert. Falls Sie sich nicht rechtzeitig registrieren konnten, haben Sie dennoch die Möglichkeit, sich für ein Modell zu entscheiden und an das Ende der jeweiligen Warteliste zu rücken.`,
  _ = `Wählen Sie unten ein Modell aus, um sich zu registrieren. Berechtigte Kunden können sich jeweils nur für ein Modell registrieren.`,
  _ = `Sie befinden sich auf der Liste für: %1$s.`,
  _ = `Sie befinden sich auf der Liste.`,
  _ = `Modell ändern?`,
  _ = `Durch das Wechseln des Modells, verlieren Sie Ihren aktuellen Platz auf der Liste für %1$s.`,
  _ = `Sie haben sich in die Liste für %1$s eingetragen.`,
  _ = `Platz auf der Warteliste sichern`,
  _ = `Warteliste verlassen?`,
  _ = `Wenn Sie die Warteliste verlassen, verlieren Sie Ihren aktuellen Platz. Sollten Sie sich erneut in die Warteliste eintragen, werden Sie am Ende der Liste platziert.`,
  _ = `Warteliste wechseln?`,
  _ = `Wenn Sie die Warteliste wechseln, verlieren Sie Ihren aktuellen Platz auf der Warteliste für: %1$s`,
  _ = `Sie haben sich in die Warteliste eingetragen für: %1$s`,
  _ = `Auf der Warteliste seit: %2$s`,
  _ = `Seit %2$s auf der Warteliste für: %1$s`,
  _ = `Auf der Warteliste`,
  _ = `Sie stehen auf der Warteliste für: %1$s`,
  _ = `Wir benachrichtigen Sie per E-Mail, falls ein Gerät verfügbar ist.`,
  _ = `Tragen Sie sich in die Warteliste ein, um benachrichtigt zu werden, falls ein Gerät verfügbar ist.`,
  _ = `Tragen Sie sich in die Warteliste ein. Sie werden benachrichtigt, sobald weitere Geräte verfügbar sind. Ihre Reservierung wird dadurch storniert.`,
  _ = `Melden Sie sich an, um sich in die Warteliste einzutragen`,
  _ = `Melden Sie sich an, um sich in die Warteliste einzutragen. Mit einem Klick auf „OK“ werden Sie zur Anmeldeseite weitergeleitet.`,
  _ = `Sie befinden sich in der Reservierungswarteschlange für: %1$s`,
  _ = `Es gelten die <1>Allgemeinen Geschäftsbedingungen</1>.`,
  _ = `dummy`,
  _ = `Ihr Preis:`,
  _ = `STANDARD`,
  _ = `30-TAGE-TIEF`,
  _ = `AKTUELL`,
  _ = `dummy`,
  _ = {
    language: _,
    EventEditor_Loc_Title: _,
    EventEditor_Loc_Overview: _,
    EventEditor_Loc_Overview_Page: _,
    LoginRedirect_Dialog_Title: _,
    LoginRedirect_Dialog_Description: _,
    Wishlist_NotSignedIn: _,
    VerifiedProgram_DeckTitle: _,
    VerifiedProgram_DeckTitle_Verified: _,
    VerifiedProgram_DeckSubTitle: _,
    VerifiedProgram_GreatOnDeck: _,
    VerifiedProgram_DeckAlt: _,
    VerifiedProgram_DeckDeviceAlt: _,
    VerifiedProgram_DeckShopBannerAlt: _,
    VerifiedProgram_DeckDisclaimer: _,
    StoreItemFound: _,
    StoreItemNotFound: _,
    SteamReviewSection_AppID: _,
    SteamReviewSection_AppID_ttip: _,
    SteamURLAccepted: _,
    SteamURLInvalid: _,
    AnchorHashInputInvalid: _,
    Sale_Section_Label_Color: _,
    Sale_Section_Background_Top: _,
    Sale_Section_Background_Bottom: _,
    Reservation_JoinPool: _,
    Reserationn_NoListJoined: _,
    Reservation_InPool: _,
    Reservation_InPool_NoDate: _,
    Reservation_Cancel_Pool: _,
    Reservation_Cancel_Pool_Desc: _,
    Reservation_JoinPool_Terms: _,
    Reservation_JoinPool_ClickTerms: _,
    Reservation_Pool_NotSignedIn: _,
    Reservation_Pool_NotSignedIn_Desc: _,
    Reservation_InPool_Message_Date: _,
    Reservation_Pool_Closed: _,
    Reservation_Pool_InProgress_Joined: _,
    Reservation_Pool_InProgress_NotJoined: _,
    Reservation_NoListJoined_OneModel: _,
    Reservation_InPool_WithName: _,
    Reservation_InPool_NoName: _,
    Reservation_Change_Pool: _,
    Reservation_Change_Pool_Desc1: _,
    Reservation_Change_Pool_Desc2: _,
    Reservation_JoinWaitList: _,
    Reservation_Cancel_Waitlist: _,
    Reservation_Cancel_Waitlist_Desc: _,
    Reservation_Change_WaitList: _,
    Reservation_Change_WaitList_Desc1: _,
    Reservation_Change_WaitList_Desc2: _,
    Reservation_In_Waitlist: _,
    Reservation_In_Waitlist_WithName: _,
    Reservation_In_Waitlist_NoDate: _,
    Reservation_In_Waitlist_WithName_NoDate: _,
    Reservation_In_Waitlist_Message: _,
    Reservation_In_Waitlist_Message_NotJoin: _,
    Reservation_Join_Waitlist_Cancel_Reservation: _,
    Reservation_Waitlist_NotSignedIn: _,
    Reservation_Waitlist_NotSignedIn_Desc: _,
    Reservation_OnRegularReserveForModel: _,
    Reservation_PostShuffle_TAndC: _,
    machine_dummy: _,
    PriceDisplay_YourPrice: _,
    PriceGrid_NormalPrice: _,
    PriceGrid_RecentPrice: _,
    PriceGrid_CurrentPrice: _,
    Dummy: _,
  };
export {
  _ as AnchorHashInputInvalid,
  _ as Dummy,
  _ as EventEditor_Loc_Overview,
  _ as EventEditor_Loc_Overview_Page,
  _ as EventEditor_Loc_Title,
  _ as LoginRedirect_Dialog_Description,
  _ as LoginRedirect_Dialog_Title,
  _ as PriceDisplay_YourPrice,
  _ as PriceGrid_CurrentPrice,
  _ as PriceGrid_NormalPrice,
  _ as PriceGrid_RecentPrice,
  _ as Reserationn_NoListJoined,
  _ as Reservation_Cancel_Pool,
  _ as Reservation_Cancel_Pool_Desc,
  _ as Reservation_Cancel_Waitlist,
  _ as Reservation_Cancel_Waitlist_Desc,
  _ as Reservation_Change_Pool,
  _ as Reservation_Change_Pool_Desc1,
  _ as Reservation_Change_Pool_Desc2,
  _ as Reservation_Change_WaitList,
  _ as Reservation_Change_WaitList_Desc1,
  _ as Reservation_Change_WaitList_Desc2,
  _ as Reservation_InPool,
  _ as Reservation_InPool_Message_Date,
  _ as Reservation_InPool_NoDate,
  _ as Reservation_InPool_NoName,
  _ as Reservation_InPool_WithName,
  _ as Reservation_In_Waitlist,
  _ as Reservation_In_Waitlist_Message,
  _ as Reservation_In_Waitlist_Message_NotJoin,
  _ as Reservation_In_Waitlist_NoDate,
  _ as Reservation_In_Waitlist_WithName,
  _ as Reservation_In_Waitlist_WithName_NoDate,
  _ as Reservation_JoinPool,
  _ as Reservation_JoinPool_ClickTerms,
  _ as Reservation_JoinPool_Terms,
  _ as Reservation_JoinWaitList,
  _ as Reservation_Join_Waitlist_Cancel_Reservation,
  _ as Reservation_NoListJoined_OneModel,
  _ as Reservation_OnRegularReserveForModel,
  _ as Reservation_Pool_Closed,
  _ as Reservation_Pool_InProgress_Joined,
  _ as Reservation_Pool_InProgress_NotJoined,
  _ as Reservation_Pool_NotSignedIn,
  _ as Reservation_Pool_NotSignedIn_Desc,
  _ as Reservation_PostShuffle_TAndC,
  _ as Reservation_Waitlist_NotSignedIn,
  _ as Reservation_Waitlist_NotSignedIn_Desc,
  _ as Sale_Section_Background_Bottom,
  _ as Sale_Section_Background_Top,
  _ as Sale_Section_Label_Color,
  _ as SteamReviewSection_AppID,
  _ as SteamReviewSection_AppID_ttip,
  _ as SteamURLAccepted,
  _ as SteamURLInvalid,
  _ as StoreItemFound,
  _ as StoreItemNotFound,
  _ as VerifiedProgram_DeckAlt,
  _ as VerifiedProgram_DeckDeviceAlt,
  _ as VerifiedProgram_DeckDisclaimer,
  _ as VerifiedProgram_DeckShopBannerAlt,
  _ as VerifiedProgram_DeckSubTitle,
  _ as VerifiedProgram_DeckTitle,
  _ as VerifiedProgram_DeckTitle_Verified,
  _ as VerifiedProgram_GreatOnDeck,
  _ as Wishlist_NotSignedIn,
  _ as default,
  _ as language,
  _ as machine_dummy,
};
