var _ = `%1$s år`,
  _ = `1 år och %1$s månader`,
  _ = `1 år`,
  _ = `%1$s månader`,
  _ = `1 månad`,
  _ = `1 månad och %1$s dagar`,
  _ = `%1$s veckor`,
  _ = `1 vecka`,
  _ = `%1$s dagar`,
  _ = `1 dag`,
  _ = `1 dag och %1$s timmar`,
  _ = `%1$s timmar`,
  _ = `1 timme`,
  _ = `1 timme och %1$s minuter`,
  _ = `mindre än en timme`,
  _ = `%1$s minuter`,
  _ = `%1$s minuter och %2$s sekunder`,
  _ = `%1$s minuter och 1 sekund`,
  _ = `1 minut`,
  _ = `1 minut och %1$s sekunder`,
  _ = `1 minut och 1 sekund`,
  _ = `mindre än en minut`,
  _ = `%1$s sekunder`,
  _ = `1 sekund`,
  _ = `%1$s år sedan`,
  _ = `1 år och %1$s månader sedan`,
  _ = `1 år sedan`,
  _ = `%1$s månader sedan`,
  _ = `1 månad sedan`,
  _ = `1 månad och %1$s dagar sedan`,
  _ = `%1$s veckor sedan`,
  _ = `1 vecka sedan`,
  _ = `%1$s dagar sedan`,
  _ = `1 dag sedan`,
  _ = `1 dag och %1$s timmar sedan`,
  _ = `%1$s timmar sedan`,
  _ = `1 timme sedan`,
  _ = `1 timme och %1$s minuter sedan`,
  _ = `mindre än en timme sedan`,
  _ = `%1$s minuter sedan`,
  _ = `för %1$s minuter och %2$s sekunder sen`,
  _ = `för %1$s minuter och 1 sekund sen`,
  _ = `1 minut sedan`,
  _ = `för 1 minut och %1$s sekunder sen`,
  _ = `för 1 minut och 1 sekund sen`,
  _ = `mindre än en minut sedan`,
  _ = `för %1$s sekunder sen`,
  _ = `för 1 sekund sen`,
  _ = `Denna vecka`,
  _ = `%1$s år återstår`,
  _ = `1 år och %1$s månader återstår`,
  _ = `1 år återstår`,
  _ = `%1$s månader återstår`,
  _ = `1 månad återstår`,
  _ = `1 månad och %1$s dagar återstår`,
  _ = `%1$s veckor återstår`,
  _ = `1 vecka återstår`,
  _ = `%1$s dagar återstår`,
  _ = `1 dag återstår`,
  _ = `1 dag och %1$s timmar återstår`,
  _ = `%1$s timmar återstår`,
  _ = `1 timme återstår`,
  _ = `1 timme och %1$s minuter återstår`,
  _ = `mindre än en timme återstår`,
  _ = `%1$s minuter återstår`,
  _ = `%1$s minuter och %2$s sekunder återstår`,
  _ = `%1$s minuter och 1 sekund återstår`,
  _ = `1 minut återstår`,
  _ = `1 minut och %1$s sekunder återstår`,
  _ = `1 minut och 1 sekund återstår`,
  _ = `mindre än en minut återstår`,
  _ = `%1$s sekunder återstår`,
  _ = `1 sekund återstår`,
  _ = `Denna vecka`,
  _ = `> 1 år`,
  _ = `%1$s m %2$s d`,
  _ = `%1$s d %2$s:%3$s`,
  _ = `%1$s:%2$s:%3$s`,
  _ = `%1$s:%2$s`,
  _ = `Live nu`,
  _ = `Strax`,
  _ = `Idag`,
  _ = `Imorgon`,
  _ = `Igår`,
  _ = `Det senaste`,
  _ = `Idag kl. %1$s`,
  _ = `Igår kl. %1$s`,
  _ = `%1$s kl. %2$s`,
  _ = `1:a kvartalet %1$s`,
  _ = `2:a kvartalet %1$s`,
  _ = `3:e kvartalet %1$s`,
  _ = `4:e kvartalet %1$s`,
  _ = `Januari–mars %1$s`,
  _ = `April–juni %1$s`,
  _ = `Juli–september %1$s`,
  _ = `Oktober–december %1$s`,
  _ = `%1$s:%2$s:%3$s,%4$s`,
  _ = `%1$s:%2$s,%3$s`,
  _ = `%1$s:%2$s:%3$s`,
  _ = `%1$s:%2$s`,
  _ = `%1$s h %2$s m %3$s s %4$s ms`,
  _ = `%1$s m %2$s s %3$s ms`,
  _ = `%1$s s %2$s ms`,
  _ = `%1$s h %2$s m %3$s s`,
  _ = `%1$s m %2$s s`,
  _ = `%1$s s`,
  _ = `%1$s sedan`,
  _ = `%1$s månader`,
  _ = `en månad`,
  _ = `%1$s dagar`,
  _ = `%1$s timmar`,
  _ = `%1$s minuter`,
  _ = `en minut`,
  _ = `mindre än en minut`,
  _ = {
    TimeInterval_XYears: _,
    TimeInterval_1YearXMonths: _,
    TimeInterval_1Year: _,
    TimeInterval_XMonths: _,
    TimeInterval_1Month: _,
    TimeInterval_1MonthX: _,
    TimeInterval_XWeeks: _,
    TimeInterval_1Week: _,
    TimeInterval_XDays: _,
    TimeInterval_1Day: _,
    TimeInterval_1DayXHours: _,
    TimeInterval_XHours: _,
    TimeInterval_1Hour: _,
    TimeInterval_1HourXMinutes: _,
    TimeInterval_LessThanAnHour: _,
    TimeInterval_XMinutes: _,
    TimeInterval_XMinutesXSeconds: _,
    TimeInterval_XMinutes1Second: _,
    TimeInterval_1Minute: _,
    TimeInterval_1MinuteXSeconds: _,
    TimeInterval_1Minute1Second: _,
    TimeInterval_LessThanAMinute: _,
    TimeInterval_XSeconds: _,
    TimeInterval_1Second: _,
    TimeSince_XYears: _,
    TimeSince_1YearXMonths: _,
    TimeSince_1Year: _,
    TimeSince_XMonths: _,
    TimeSince_1Month: _,
    TimeSince_1MonthXDays: _,
    TimeSince_XWeeks: _,
    TimeSince_1Week: _,
    TimeSince_XDays: _,
    TimeSince_1Day: _,
    TimeSince_1DayXHours: _,
    TimeSince_XHours: _,
    TimeSince_1Hour: _,
    TimeSince_1HourXMinutes: _,
    TimeSince_LessThanAnHour: _,
    TimeSince_XMinutes: _,
    TimeSince_XMinutesXSeconds: _,
    TimeSince_XMinutes1Second: _,
    TimeSince_1Minute: _,
    TimeSince_1MinuteXSeconds: _,
    TimeSince_1Minute1Second: _,
    TimeSince_LessThanAMinute: _,
    TimeSince_XSeconds: _,
    TimeSince_1Second: _,
    TimeSince_ThisWeek: _,
    TimeRemaining_XYears: _,
    TimeRemaining_1YearXMonths: _,
    TimeRemaining_1Year: _,
    TimeRemaining_XMonths: _,
    TimeRemaining_1Month: _,
    TimeRemaining_1MonthXDays: _,
    TimeRemaining_XWeeks: _,
    TimeRemaining_1Week: _,
    TimeRemaining_XDays: _,
    TimeRemaining_1Day: _,
    TimeRemaining_1DayXHours: _,
    TimeRemaining_XHours: _,
    TimeRemaining_1Hour: _,
    TimeRemaining_1HourXMinutes: _,
    TimeRemaining_LessThanAnHour: _,
    TimeRemaining_XMinutes: _,
    TimeRemaining_XMinutesXSeconds: _,
    TimeRemaining_XMinutes1Second: _,
    TimeRemaining_1Minute: _,
    TimeRemaining_1MinuteXSeconds: _,
    TimeRemaining_1Minute1Second: _,
    TimeRemaining_LessThanAMinute: _,
    TimeRemaining_XSeconds: _,
    TimeRemaining_1Second: _,
    TimeRemaining_ThisWeek: _,
    TimeRemaining_MoreThanOneYear: _,
    TimeRemaining_MonthsDays: _,
    TimeRemaining_DaysHoursMinutes: _,
    TimeRemaining_HoursMinutesSeconds: _,
    TimeRemaining_MinutesSeconds: _,
    Time_Now: _,
    Time_UpNext: _,
    Time_Today: _,
    Time_Tomorrow: _,
    Time_Yesterday: _,
    Time_Recent: _,
    Time_Today_At: _,
    Time_Yesterday_At: _,
    Time_Past_At: _,
    Time_QuarterOfYear_Q1: _,
    Time_QuarterOfYear_Q2: _,
    Time_QuarterOfYear_Q3: _,
    Time_QuarterOfYear_Q4: _,
    Time_QuarterOfYear_Expanded_Q1: _,
    Time_QuarterOfYear_Expanded_Q2: _,
    Time_QuarterOfYear_Expanded_Q3: _,
    Time_QuarterOfYear_Expanded_Q4: _,
    Duration_HourMinuteSecondMillisecond: _,
    Duration_MinuteSecondMillisecond: _,
    Duration_HourMinuteSecond: _,
    Duration_MinuteSecond: _,
    Duration_Abbreviation_HourMinuteSecondMillisecond: _,
    Duration_Abbreviation_MinuteSecondMillisecond: _,
    Duration_Abbreviation_SecondMillisecond: _,
    Duration_Abbreviation_HourMinuteSecond: _,
    Duration_Abbreviation_MinuteSecond: _,
    Duration_Abbreviation_Second: _,
    Duration_WrittenNegation: _,
    ReadableDuration_Months: _,
    ReadableDuration_OneMonth: _,
    ReadableDuration_Days: _,
    ReadableDuration_Hours: _,
    ReadableDuration_Minutes: _,
    ReadableDuration_OneMinute: _,
    ReadableDuration_LessThanOneMinute: _,
  };
export {
  _ as Duration_Abbreviation_HourMinuteSecond,
  _ as Duration_Abbreviation_HourMinuteSecondMillisecond,
  _ as Duration_Abbreviation_MinuteSecond,
  _ as Duration_Abbreviation_MinuteSecondMillisecond,
  _ as Duration_Abbreviation_Second,
  _ as Duration_Abbreviation_SecondMillisecond,
  _ as Duration_HourMinuteSecond,
  _ as Duration_HourMinuteSecondMillisecond,
  _ as Duration_MinuteSecond,
  _ as Duration_MinuteSecondMillisecond,
  _ as Duration_WrittenNegation,
  _ as ReadableDuration_Days,
  _ as ReadableDuration_Hours,
  _ as ReadableDuration_LessThanOneMinute,
  _ as ReadableDuration_Minutes,
  _ as ReadableDuration_Months,
  _ as ReadableDuration_OneMinute,
  _ as ReadableDuration_OneMonth,
  _ as TimeInterval_1Day,
  _ as TimeInterval_1DayXHours,
  _ as TimeInterval_1Hour,
  _ as TimeInterval_1HourXMinutes,
  _ as TimeInterval_1Minute,
  _ as TimeInterval_1Minute1Second,
  _ as TimeInterval_1MinuteXSeconds,
  _ as TimeInterval_1Month,
  _ as TimeInterval_1MonthX,
  _ as TimeInterval_1Second,
  _ as TimeInterval_1Week,
  _ as TimeInterval_1Year,
  _ as TimeInterval_1YearXMonths,
  _ as TimeInterval_LessThanAMinute,
  _ as TimeInterval_LessThanAnHour,
  _ as TimeInterval_XDays,
  _ as TimeInterval_XHours,
  _ as TimeInterval_XMinutes,
  _ as TimeInterval_XMinutes1Second,
  _ as TimeInterval_XMinutesXSeconds,
  _ as TimeInterval_XMonths,
  _ as TimeInterval_XSeconds,
  _ as TimeInterval_XWeeks,
  _ as TimeInterval_XYears,
  _ as TimeRemaining_1Day,
  _ as TimeRemaining_1DayXHours,
  _ as TimeRemaining_1Hour,
  _ as TimeRemaining_1HourXMinutes,
  _ as TimeRemaining_1Minute,
  _ as TimeRemaining_1Minute1Second,
  _ as TimeRemaining_1MinuteXSeconds,
  _ as TimeRemaining_1Month,
  _ as TimeRemaining_1MonthXDays,
  _ as TimeRemaining_1Second,
  _ as TimeRemaining_1Week,
  _ as TimeRemaining_1Year,
  _ as TimeRemaining_1YearXMonths,
  _ as TimeRemaining_DaysHoursMinutes,
  _ as TimeRemaining_HoursMinutesSeconds,
  _ as TimeRemaining_LessThanAMinute,
  _ as TimeRemaining_LessThanAnHour,
  _ as TimeRemaining_MinutesSeconds,
  _ as TimeRemaining_MonthsDays,
  _ as TimeRemaining_MoreThanOneYear,
  _ as TimeRemaining_ThisWeek,
  _ as TimeRemaining_XDays,
  _ as TimeRemaining_XHours,
  _ as TimeRemaining_XMinutes,
  _ as TimeRemaining_XMinutes1Second,
  _ as TimeRemaining_XMinutesXSeconds,
  _ as TimeRemaining_XMonths,
  _ as TimeRemaining_XSeconds,
  _ as TimeRemaining_XWeeks,
  _ as TimeRemaining_XYears,
  _ as TimeSince_1Day,
  _ as TimeSince_1DayXHours,
  _ as TimeSince_1Hour,
  _ as TimeSince_1HourXMinutes,
  _ as TimeSince_1Minute,
  _ as TimeSince_1Minute1Second,
  _ as TimeSince_1MinuteXSeconds,
  _ as TimeSince_1Month,
  _ as TimeSince_1MonthXDays,
  _ as TimeSince_1Second,
  _ as TimeSince_1Week,
  _ as TimeSince_1Year,
  _ as TimeSince_1YearXMonths,
  _ as TimeSince_LessThanAMinute,
  _ as TimeSince_LessThanAnHour,
  _ as TimeSince_ThisWeek,
  _ as TimeSince_XDays,
  _ as TimeSince_XHours,
  _ as TimeSince_XMinutes,
  _ as TimeSince_XMinutes1Second,
  _ as TimeSince_XMinutesXSeconds,
  _ as TimeSince_XMonths,
  _ as TimeSince_XSeconds,
  _ as TimeSince_XWeeks,
  _ as TimeSince_XYears,
  _ as Time_Now,
  _ as Time_Past_At,
  _ as Time_QuarterOfYear_Expanded_Q1,
  _ as Time_QuarterOfYear_Expanded_Q2,
  _ as Time_QuarterOfYear_Expanded_Q3,
  _ as Time_QuarterOfYear_Expanded_Q4,
  _ as Time_QuarterOfYear_Q1,
  _ as Time_QuarterOfYear_Q2,
  _ as Time_QuarterOfYear_Q3,
  _ as Time_QuarterOfYear_Q4,
  _ as Time_Recent,
  _ as Time_Today,
  _ as Time_Today_At,
  _ as Time_Tomorrow,
  _ as Time_UpNext,
  _ as Time_Yesterday,
  _ as Time_Yesterday_At,
  _ as default,
};
