var _ = `polish`,
  _ = `Usuń`,
  _ = `Dodaj`,
  _ = `Zweryfikuj wiek`,
  _ = `Usuń wszystkie produkty`,
  _ = `Edytuj`,
  _ = `Liczba: %1$s`,
  _ = `Twój koszyk zakupów`,
  _ = `Twój koszyk z zakupami (produkty: %1$s)`,
  _ = `Twój koszyk z zakupami (produkty: %1$s)`,
  _ = `Szacowana suma`,
  _ = `Podatek od sprzedaży zostanie obliczony po przejściu do kasy (jeśli ma zastosowanie).`,
  _ = `Kup`,
  _ = `Ten zakup zawiera prezent`,
  _ = `Strona główna`,
  _ = `Czy to prezent?`,
  _ = `Zawiera %1$s produkt`,
  _ = `Zawiera zbiór %1$s produktów`,
  _ = `Wybierz odbiorcę`,
  _ = `Wprowadź e-mail`,
  _ = `Edytuj odbiorcę prezentu…`,
  _ = `Odbiorca prezentu:`,
  _ = `E-mail odbiorcy prezentu:`,
  _ = `Dostarczenie:`,
  _ = `Zresetuj`,
  _ = `Jak najszybciej (poprzez e-mail i klienta Steam)`,
  _ = `Zaplanowane:`,
  _ = `Zaplanuj dostarczenie`,
  _ = `Od:`,
  _ = `Twój podpis:`,
  _ = `Dodaj niestandardowy podpis`,
  _ = `Wiadomość dołączona do prezentu (maks. 160\xA0znaków, pozostało %1$s):`,
  _ = `Prezenty wysyłane przez e-mail zostaną automatycznie zwrócone po 30 dniach, jeśli nie zostaną dodane do konta Steam.`,
  _ = `Prezenty wysyłane przez e-mail mogą zostać zaakceptowane tylko przez konta Steam w tym samym regionie co kupujący (%1$s).`,
  _ = `Prezenty wysyłane do dzieci z twojej rodziny na Steam zostaną automatycznie dodane do ich konta i dozwolonych gier.`,
  _ = `Wybierz odbiorcę prezentu`,
  _ = `Zmień sposób dostawy`,
  _ = `Zapisz`,
  _ = `Szukaj według pseudonimu znajomego…`,
  _ = `Użytkownik już ma tę grę`,
  _ = `Na liście życzeń`,
  _ = `Posiada już produkt %1$s`,
  _ = `Ma na liście życzeń produkt %1$s`,
  _ = `Opcje prezentu`,
  _ = `Wystąpił problem podczas wczytywania odbiorców uprawnionych do otrzymania prezentu. Spróbuj ponownie później.`,
  _ = `Przejdź do płatności`,
  _ = `Przejdź do opcji prezentu`,
  _ = `Zaloguj się, by kupić`,
  _ = `Odrzuć prośbę`,
  _ = `Dla mojego konta`,
  _ = `To jest prezent`,
  _ = `To prezent dla użytkownika %1$s`,
  _ = `Dla mojego konta: zakup prywatny`,
  _ = `Koszyk (%1$s)`,
  _ = `Dodano do twojego koszyka!`,
  _ = `Twój koszyk został zaktualizowany!`,
  _ = `Kontynuuj zakupy`,
  _ = `Dostępne od %1$s`,
  _ = `Pokaż mój koszyk (%1$s)`,
  _ = `Poproś o zakup`,
  _ = `Dorośli w twojej rodzinie na Steam zostaną powiadomieni o twojej prośbie o zakup`,
  _ = `Nie można poprosić o zakup, ponieważ nie wszystkie produkty w koszyku można podarować.`,
  _ = `Zmień/usuń kupon`,
  _ = `Dodaj kupon`,
  _ = `Masz 1 dostępny kupon dla tego produktu`,
  _ = `Masz %1$s dostępne kupony dla tego produktu`,
  _ = `Obecnie zastosowane`,
  _ = `Obecnie zastosowane dla innego produktu`,
  _ = `Wybierz kupon, by zastosować go dla %1$s`,
  _ = `Przewidywana data dostawy: %1$s`,
  _ = `%1$s – %2$s dni roboczych`,
  _ = `Oczekiwany czas dostawy: 6 – 10 dni roboczych`,
  _ = `Oczekiwany czas dostawy: 3 – 5 dni roboczych`,
  _ = `Zanim będziesz mógł przejść do płatności:`,
  _ = `Uwagi:`,
  _ = `Przed przejściem do płatności konieczne jest działanie`,
  _ = `Uwagi:`,
  _ = `Uwaga: %1$s`,
  _ = `Twoje konto Steam ma już niektóre z powyższych produktów, więc nie możesz zakupić ich ponownie. Aby kontynuować, zakup je jako prezent lub zmień zawartość koszyka.`,
  _ = `Już masz tę grę.`,
  _ = `Już masz wszystkie produkty z tego pakietu.`,
  _ = `Odbiorca prezentu posiada już tę grę.`,
  _ = `Odbiorca prezentu posiada już wszystkie produkty z tego zestawu.`,
  _ = `Odbiorca prezentu posiada już niektóre z powyższych produktów, więc nie możesz zakupić ich ponownie. Aby kontynuować zakup, kup je z innego konta lub zmień zawartość koszyka.`,
  _ = `W koszyku znajdują się pakiety, których zawartość się powtarza. Musisz usunąć niepotrzebne pakiety z koszyka, by móc przejść do kasy.`,
  _ = `Produkt już w koszyku: `,
  _ = `Twój koszyk obejmuje zawartość, która jest niedostępna w twoim kraju. Musisz usunąć ten pakiet ze swojego koszyka, by móc przejść do kasy.`,
  _ = `Niedostępne w twoim kraju.`,
  _ = `Valve jest zobowiązane do weryfikacji, czy masz co najmniej 18 lat przed umożliwieniem zakupu treści seksualnych dla dorosłych.`,
  _ = `Nie można zakupić, dopóki nie zweryfikujesz swojego wieku.`,
  _ = `Twój koszyk zawiera treści, które są już dostępne poprzez jedną z twoich aktywnych subskrypcji.`,
  _ = `Dostępne przez twoją subskrypcję:`,
  _ = `Tego kuponu nie można użyć w połączeniu z inną zniżką.`,
  _ = `Ten kupon jest nieprawidłowy lub jego ważność wygasła.`,
  _ = `Nie można zastosować kuponu dla tego produktu.`,
  _ = `Maksymalna dozwolona liczba egzemplarzy tego produktu w twoim koszyku została przekroczona.`,
  _ = `Twój koszyk zawiera produkt, którego nie można kupić.`,
  _ = `Niedostępne w sprzedaży`,
  _ = `Wybrany odbiorca nie może otrzymać tego prezentu zakupionego w twoim regionie.`,
  _ = `Do zakupu tego produktu jest wymagane posiadanie następujących produktów:`,
  _ = `Do zakupu tego produktu jest wymagane posiadanie przez odbiorcę prezentu następujących produktów:`,
  _ = `Na twoim koncie nie ma pewnych produktów wymaganych do zakupu produktów znajdujących się w twoim koszyku. Możesz dodać brakujące produkty lub zmienić zawartość koszyka, by kontynuować.`,
  _ = `Na koncie odbiorcy prezentu nie ma pewnych produktów wymaganych do zakupu produktów znajdujących się w twoim koszyku. Możesz dodać brakujące produkty lub zmienić zawartość koszyka, by kontynuować.`,
  _ = `Subskrybujesz już ten produkt.`,
  _ = `Na twoim koncie znajduje się już subskrypcja części powyższych produktów. Sprawdź swoje ustawienia subskrypcji w ustawieniach swojego konta.`,
  _ = `Jeśli dokonujesz zakupu dla siebie, nie otrzymasz dodatkowej kopii:`,
  _ = `Jeśli dokonujesz zakupu dla siebie, otrzymasz dodatkową kopię, którą możesz wysłać jako prezent:`,
  _ = `Cena jednego lub kilku produktów niżej zmieniła się od momentu dodania do twojego koszyka.`,
  _ = `Cena tego produktu uległa zmianie`,
  _ = `Ten produkt obejmuje zawartość jednorazowego użytku, która nie kwalifikuje się do zwrotu pieniędzy.`,
  _ = `Wybrany odbiorca prezentu znajduje się w regionie o wyższych cenach. Koszt tego produktu został zaktualizowany na dopasowany do jego regionu, aby umożliwić podarowanie mu go.`,
  _ = `Ten produkt jest dostępny w niższej cenie jako część zestawu %1$s.`,
  _ = `Odbiorca prezentu NIE znajduje się na twojej liście znajomych na Steam.`,
  _ = `UWAGA: użytkownik %1$s NIE znajduje się na twojej liście znajomych na Steam.`,
  _ = `Jeśli wysyłasz prezent znajomemu na Steam, <1>zaloguj się</1>, aby sprawdzić, czy odbiorca znajduje się na twojej liście znajomych.`,
  _ = `Niedawno przeglądałeś listę życzeń użytkownika %1$s. Czy podarować mu te produkty?`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s s.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s min.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s godz.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s dni.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s tydz./tyg.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s mies.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s rok/lat(a).`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s s za każdą licencję.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s min za każdą licencję.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s godz. za każdą licencję.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s dzień/dni za każdą licencję.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s tyg./tydz. za każdą licencję.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s mies. za każdą licencję.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s rok/lat(a) za każdą licencję.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s s lub jak określono przez twoje konto gry.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s min lub jak określono przez twoje konto gry.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s godz. lub jak określono przez twoje konto gry.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s dni lub jak określono przez twoje konto gry.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s tydz./tyg. lub jak określono przez twoje konto gry.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s mies. lub jak określono przez twoje konto gry.`,
  _ = `Subskrypcja będzie naliczać %1$s co %2$s rok/lat(a) lub jak określono przez twoje konto gry.`,
  _ = `Zapłacisz %1$s przy kasie.<br/>Zgadzasz się na automatyczne obciążanie karty kwotą %2$s co %3$s s.`,
  _ = `Zapłacisz %1$s przy kasie.<br/>Zgadzasz się na automatyczne obciążanie karty kwotą %2$s co %3$s min.`,
  _ = `Zapłacisz %1$s przy kasie.<br/>Zgadzasz się na automatyczne obciążanie karty kwotą %2$s co %3$s godz.`,
  _ = `Zapłacisz %1$s przy kasie.<br/>Zgadzasz się na automatyczne obciążanie karty kwotą %2$s co %3$s dzień/dni.`,
  _ = `Zapłacisz %1$s przy kasie.<br/>Zgadzasz się na automatyczne obciążanie karty kwotą %2$s co %3$s tydz./tyg.`,
  _ = `Zapłacisz %1$s przy kasie.<br/>Zgadzasz się na automatyczne obciążanie karty kwotą %2$s co %3$s mies.`,
  _ = `Zapłacisz %1$s przy kasie.<br/>Zgadzasz się na automatyczne obciążanie karty kwotą %2$s co %3$s rok/lat(a).`,
  _ = `Zapłacisz %1$s przy kasie.<br/>Zezwalasz tej grze na pobieranie dodatkowych opłat w wysokości maks. %2$s co %3$s sekund(y).`,
  _ = `Zapłacisz %1$s przy kasie.<br/>Zezwalasz tej grze na pobieranie dodatkowych opłat w wysokości maks. %2$s co %3$s min.`,
  _ = `Zapłacisz %1$s przy kasie.<br/>Zezwalasz tej grze na pobieranie dodatkowych opłat w wysokości maks. %2$s co %3$s godz.`,
  _ = `Zapłacisz %1$s przy kasie.<br/>Zezwalasz tej grze na pobieranie dodatkowych opłat w wysokości maks. %2$s co %3$s dni.`,
  _ = `Zapłacisz %1$s przy kasie.<br/>Zezwalasz tej grze na pobieranie dodatkowych opłat w wysokości maks. %2$s co %3$s tyg.`,
  _ = `Zapłacisz %1$s przy kasie.<br/>Zezwalasz tej grze na pobieranie dodatkowych opłat w wysokości maks. %2$s co %3$s mies.`,
  _ = `Zapłacisz %1$s przy kasie.<br/>Zezwalasz tej grze na pobieranie dodatkowych opłat w wysokości maks. %2$s co %3$s lat(a).`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s s.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s min.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s godz.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s dni.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s tydz./tyg.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s mies.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s rok/lat(a).`,
  _ = `%1$s w chwili nabycia ze zniżką %4$s% za pierwszy zakup, a następnie automatyczne odnowienie za %2$s co %3$s s.`,
  _ = `%1$s w chwili nabycia ze zniżką %4$s% za pierwszy zakup, a następnie automatyczne odnowienie za %2$s co %3$s min.`,
  _ = `%1$s w chwili nabycia ze zniżką %4$s% za pierwszy zakup, a następnie automatyczne odnowienie za %2$s co %3$s godz.`,
  _ = `%1$s w chwili nabycia ze zniżką %4$s% za pierwszy zakup, a następnie automatyczne odnowienie za %2$s co %3$s dni.`,
  _ = `%1$s w chwili nabycia ze zniżką %4$s% za pierwszy zakup, a następnie automatyczne odnowienie za %2$s co %3$s tydz./tyg.`,
  _ = `%1$s w chwili nabycia ze zniżką %4$s% za pierwszy zakup, a następnie automatyczne odnowienie za %2$s co %3$s mies.`,
  _ = `%1$s w chwili nabycia ze zniżką %4$s% za pierwszy zakup, a następnie automatyczne odnowienie za %2$s co %3$s rok/lat(a).`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s s, jak określono przez twoje konto gry.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s min, jak określono przez twoje konto gry.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s godz., jak określono przez twoje konto gry.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s dni, jak określono przez twoje konto gry.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s tydz./tyg., jak określono przez twoje konto gry.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s mies., jak określono przez twoje konto gry.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s rok/lat(a), jak określono przez twoje konto gry.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s s za każdą licencję.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s min za każdą licencję.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s godz. za każdą licencję.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s dzień/dni za każdą licencję.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s tydz./tyg. za każdą licencję.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s mies. za każdą licencję.`,
  _ = `%1$s w chwili nabycia, a następnie automatyczne odnowienie za %2$s co %3$s rok/lat(a) za każdą licencję.`,
  _ = `%1$s w chwili nabycia ze zniżką %4$s% za pierwszy zakup, a następnie automatyczne odnowienie za %2$s co %3$s s za każdą licencję.`,
  _ = `%1$s w chwili nabycia ze zniżką %4$s% za pierwszy zakup, a następnie automatyczne odnowienie za %2$s co %3$s min za każdą licencję.`,
  _ = `%1$s w chwili nabycia ze zniżką %4$s% za pierwszy zakup, a następnie automatyczne odnowienie za %2$s co %3$s godz. za każdą licencję.`,
  _ = `%1$s w chwili nabycia ze zniżką %4$s% za pierwszy zakup, a następnie automatyczne odnowienie za %2$s co %3$s dzień/dni za każdą licencję.`,
  _ = `%1$s w chwili nabycia ze zniżką %4$s% za pierwszy zakup, a następnie automatyczne odnowienie za %2$s co %3$s tydz./tyg. za każdą licencję.`,
  _ = `%1$s w chwili nabycia ze zniżką %4$s% za pierwszy zakup, a następnie automatyczne odnowienie za %2$s co %3$s mies. za każdą licencję.`,
  _ = `%1$s w chwili nabycia ze zniżką %4$s% za pierwszy zakup, a następnie automatyczne odnowienie za %2$s co %3$s rok/lat(a) za każdą licencję.`,
  _ = `Twój koszyk jest pusty.`,
  _ = `Niektóre z tych produktów są już oznaczone jako prywatne. Pozostaną one prywatne, jeśli przejdziesz dalej:`,
  _ = `Oznaczenie gry jako prywatnej ukryje ją ze wszystkich miejsc poza twoją biblioteką. Informacje o tym, że ją posiadasz, twój status gry, czas gry i aktywność nie będą widoczne dla innych osób.`,
  _ = `Widzisz nową wersję koszyka, ponieważ uczestniczysz w testach beta klienta Steam. <1>Podziel się opinią lub zgłoś błędy.</1>`,
  _ = `Przeprowadzamy testy beta tej nowej wersji koszyka. <1>Podziel się opinią lub zgłoś błędy</1>.`,
  _ = `Nie możesz zaplanować przesłania prezentu tak bardzo do przodu.`,
  _ = `Wprowadź poprawną datę i godzinę.`,
  _ = `Wystąpił problem podczas wyświetlania tego przedmiotu.`,
  _ = `Za ten zakup otrzymasz %1$s kartę wydarzenia %2$s.`,
  _ = `Za ten zakup otrzymasz %1$s kart(y) wydarzenia %2$s.`,
  _ = `Za zakupy dokonane w Sklepie Steam podczas wyprzedaży otrzymasz karty wydarzenia %1$s.`,
  _ = `Otrzymasz karty, nawet jeśli ten zakup jest prezentem.`,
  _ = `Postęp do następnej karty`,
  _ = `około %1$s za każdą kartę`,
  _ = `Uwaga: zakupy gier w przedsprzedaży nie wliczają się na potrzeby kart kolekcjonerskich wydarzenia %1$s. Nie otrzymasz kart kolekcjonerskich za następujące produkty:`,
  _ = `Prośba o zakup od: %1$s`,
  _ = `Zakup dla:`,
  _ = `Kup jako prezent dla użytkownika %1$s`,
  _ = `Dodaj kolejną kopię tego produktu do swojego koszyka.`,
  _ = `Deklaracja zgodności z brytyjskimi przepisami PSTI (o bezpieczeństwie produktów i infrastrukturze telekomunikacyjnej)`,
  _ = `Wystąpił problem podczas aktualizowania twojego koszyka.`,
  _ = `Kod błędu: %1$s`,
  _ = `Kraj`,
  _ = `Zapisany koszyk`,
  _ = `Oto zapisany koszyk. Przy ostatniej próbie zakupu zawartości tego koszyka wystąpił błąd, dlatego zapisaliśmy go (razem ze zniżkami) na %1$s godz. w celu umożliwienia ponownego zakupu.`,
  _ = `Skopiuj opcje prezentów z`,
  _ = `<1>Zaloguj się</1>, by wybrać znajomych na Steam`,
  _ = {
    language: _,
    Cart_Remove: _,
    Cart_Add: _,
    Cart_Verify: _,
    Cart_RemoveAll: _,
    Cart_Edit: _,
    Cart_Quantity: _,
    Cart_YourShoppingCart: _,
    Cart_YourShoppingCartLineItems: _,
    Cart_YourShoppingCartLineItems_Plural: _,
    Cart_EstimatedTotal: _,
    Cart_Note_SalesTax: _,
    Cart_PurchaseBtn: `Kup`,
    Cart_ContainsGiftCheckbox: _,
    Cart_Bradcrumb_Home: _,
    Cart_LineItemGift_Checkbox: _,
    Cart_IncludesItems: _,
    Cart_IncludesItems_Plural: _,
    Cart_SelectRecipient: _,
    Cart_EnterRecipientEmail: _,
    Cart_ChangeGiftRecipient: _,
    Cart_GiftRecipient_Label: _,
    Cart_GiftRecipientEmail_Label: _,
    Cart_GiftDelivery_Label: _,
    Cart_GiftDelivery_Reset: _,
    Cart_GiftDelivery_Now: _,
    Cart_GiftDelivery_Scheduled: _,
    Cart_GiftDelivery_ScheduleDelivery: _,
    Cart_GiftDelivery_From: `Od:`,
    Cart_GiftDelivery_Signature: _,
    Cart_GiftDelivery_AddSignature: _,
    Cart_GiftDelivery_Body: _,
    Cart_GiftDeliveryEmail_Warning1: _,
    Cart_GiftDeliveryEmail_Warning2: _,
    Cart_FamilyGift_Notice: _,
    Cart_GiftRecipientModal_Title: _,
    Cart_EditGiftDelivery: _,
    Cart_GiftRecipientModal_Save: _,
    Cart_GiftRecipientModal_Placeholder: _,
    Cart_GiftRecipientModal_OwnsGameLabel: _,
    Cart_GiftRecipientModal_OnWishlist: _,
    Cart_GiftRecipientModal_PartialOwnsLabel: _,
    Cart_GiftRecipientModal_PartialWishlistLabel: _,
    Cart_GiftOptions: _,
    Cart_GiftRecipientModal_IssueLoading: _,
    Cart_ContinueButton_Payment: _,
    Cart_ContinueButton_Gifts: _,
    Cart_ContinueButton_Login: _,
    Cart_DeclinePurchaseRequest: _,
    Cart_LineItemOptions_Myself: _,
    Cart_LineItemOptions_Gift: _,
    Cart_LineItemOptions_GiftForPersona: _,
    Cart_LineItemOptions_Privately: _,
    Cart_CountWidget: _,
    Cart_AddedToYourCart: _,
    Cart_UpdatedYourCart: _,
    Cart_ContinueShopping: _,
    Cart_ComingSoon: _,
    Cart_ViewMyCart: _,
    Cart_RequestPurchase: _,
    Cart_RequestPurchaseExplanation: _,
    Cart_RequestPurchaseNonGiftableItems: _,
    Cart_CouponModify_Change: _,
    Cart_CouponModify_Add: _,
    Cart_CouponAvailability: _,
    Cart_CouponAvailability_Plural: _,
    Cart_Coupons_Applied: _,
    Cart_Coupons_InUse: _,
    Cart_SelectCouponToApply: _,
    Cart_ShippingEstimate_DeliveryDate: _,
    Cart_ShippingEstimate_Range: _,
    Cart_ShippingEstimate_Delayed: _,
    Cart_ShippingEstimate_Standard: _,
    Cart_FooterNoticeHeader_MustFix: _,
    Cart_FooterNoticeHeader_Warning: _,
    Cart_CartLevelErrorNotice: _,
    Cart_CartLevelErrorMultiple: _,
    Cart_CartLevelErrorFormat: _,
    Cart_Error_AlreadyOwned_FootNote: _,
    Cart_Error_AlreadyOwned_LineItem_Game: _,
    Cart_Error_AlreadyOwned_LineItem: _,
    Cart_Error_AlreadyOwned_GiftLineItem_Game: _,
    Cart_Error_AlreadyOwned_GiftLineItem: _,
    Cart_Error_AlreadyOwned_GiftFootNote: _,
    Cart_Error_DuplicateApps_FootNote: _,
    Cart_Error_DuplicateApps_LineItem: _,
    Cart_Error_UnavailableCountry_FootNote: _,
    Cart_Error_UnavailableCountry_LineItem: _,
    Cart_Error_AdultContentRestricted_FootNote: _,
    Cart_Error_AdultContentRestricted_LineItem: _,
    Cart_Error_MasterSubscription_FootNote: _,
    Cart_Error_MasterSubscription_LineItem: _,
    Cart_Error_CouponIsExclusivePromo: _,
    Cart_Error_CouponIsInvalid: _,
    Cart_Error_CouponIsInvalidForItem: _,
    Cart_Error_TooManyInCart: _,
    Cart_Error_CommercialLicenseRestricted_FootNote: _,
    Cart_Error_CommercialLicenseRestricted_LineItem: _,
    Cart_Error_GiftRecipientInvalid: _,
    Cart_Error_MissingMustOwnApps_LineItem: _,
    Cart_Error_MissingMustOwnApps_GiftLineItem: _,
    Cart_Error_MissingMustOwnApps_FootNote: _,
    Cart_Error_MissingMustOwnApps_FootNoteGift: _,
    Cart_Error_ExistingBillingAgreement: _,
    Cart_Error_ExistingBillingAgreement_FootNote: _,
    Cart_Warning_AlreadyOwned_LineItem: _,
    Cart_Warning_ExtraCopies_LineItem: _,
    Cart_Warning_PriceChange_FootNote: _,
    Cart_Warning_PriceChange_LineItem: _,
    Cart_Warning_NoRefund_LineItem: _,
    Cart_Warning_RecipientHigherPrice: _,
    Cart_Warning_AvailableAtALowerPrice: _,
    Cart_Warning_GiftToNonFriend: _,
    Cart_Warning_GiftToNonFriend_Named: _,
    Cart_Warning_GiftToAccount_LoggedOut_Actionable: _,
    Cart_GifteeHint_Wishlist: _,
    PackageIncludesSubscriptionBySecond: _,
    PackageIncludesSubscriptionByMinute: _,
    PackageIncludesSubscriptionByHour: _,
    PackageIncludesSubscriptionByDay: _,
    PackageIncludesSubscriptionByWeek: _,
    PackageIncludesSubscriptionByMonth: _,
    PackageIncludesSubscriptionByYear: _,
    MultiLicenseIncludesSubscriptionBySecond: _,
    MultiLicenseIncludesSubscriptionByMinute: _,
    MultiLicenseIncludesSubscriptionByHour: _,
    MultiLicenseIncludesSubscriptionByDay: _,
    MultiLicenseIncludesSubscriptionByWeek: _,
    MultiLicenseIncludesSubscriptionByMonth: _,
    MultiLicenseeIncludesSubscriptionByYear: _,
    GameBillingPackageIncludesSubscriptionBySecond: _,
    GameBillingPackageIncludesSubscriptionByMinute: _,
    GameBillingPackageIncludesSubscriptionByHour: _,
    GameBillingPackageIncludesSubscriptionByDay: _,
    GameBillingPackageIncludesSubscriptionByWeek: _,
    GameBillingPackageIncludesSubscriptionByMonth: _,
    GameBillingPackageIncludesSubscriptionByYear: _,
    MicroTxnSubscriptionCostBySecond: _,
    MicroTxnSubscriptionCostByMinute: _,
    MicroTxnSubscriptionCostByHour: _,
    MicroTxnSubscriptionCostByDay: _,
    MicroTxnSubscriptionCostByWeek: _,
    MicroTxnSubscriptionCostByMonth: _,
    MicroTxnSubscriptionCostByYear: _,
    GameBillingAuthorizeSubscriptionBySecond: _,
    GameBillingAuthorizeSubscriptionByMinute: _,
    GameBillingAuthorizeSubscriptionByHour: _,
    GameBillingAuthorizeSubscriptionByDay: _,
    GameBillingAuthorizeSubscriptionByWeek: _,
    GameBillingAuthorizeSubscriptionByMonth: _,
    GameBillingAuthorizeSubscriptionByYear: _,
    PackageCostIncludesSubscriptionBySecond: _,
    PackageCostIncludesSubscriptionByMinute: _,
    PackageCostIncludesSubscriptionByHour: _,
    PackageCostIncludesSubscriptionByDay: _,
    PackageCostIncludesSubscriptionByWeek: _,
    PackageCostIncludesSubscriptionByMonth: _,
    PackageCostIncludesSubscriptionByYear: _,
    PackageWithDiscountCostIncludesSubscriptionBySecond: _,
    PackageWithDiscountCostIncludesSubscriptionByMinute: _,
    PackageWithDiscountCostIncludesSubscriptionByHour: _,
    PackageWithDiscountCostIncludesSubscriptionByDay: _,
    PackageWithDiscountCostIncludesSubscriptionByWeek: _,
    PackageWithDiscountCostIncludesSubscriptionByMonth: _,
    PackageWithDiscountCostIncludesSubscriptionByYear: _,
    GameBillingPackageCostIncludesSubscriptionBySecond: _,
    GameBillingPackageCostIncludesSubscriptionByMinute: _,
    GameBillingPackageCostIncludesSubscriptionByHour: _,
    GameBillingPackageCostIncludesSubscriptionByDay: _,
    GameBillingPackageCostIncludesSubscriptionByWeek: _,
    GameBillingPackageCostIncludesSubscriptionByMonth: _,
    GameBillingPackageCostIncludesSubscriptionByYear: _,
    MultiLicenseCostIncludesSubscriptionBySecond: _,
    MultiLicenseCostIncludesSubscriptionByMinute: _,
    MultiLicenseCostIncludesSubscriptionByHour: _,
    MultiLicenseCostIncludesSubscriptionByDay: _,
    MultiLicenseCostIncludesSubscriptionByWeek: _,
    MultiLicenseCostIncludesSubscriptionByMonth: _,
    MultiLicenseCostIncludesSubscriptionByYear: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionBySecond: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMinute: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByHour: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByDay: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByWeek: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMonth: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByYear: _,
    Cart_Empty: _,
    Cart_Notice_SomeAppsPrivate: _,
    Cart_LineItemOptions_PrivateTooltip: _,
    Cart_BetaNotice: _,
    Cart_GenericBetaNotice: _,
    Cart_GiftScheduleError_TooFar: _,
    Cart_GiftScheduleError_InvalidDate: _,
    Cart_LineItem_ErrorBoundary: _,
    Cart_SaleCardDrops_EarnedMessage: _,
    Cart_SaleCardDrops_EarnedMessage_Plural: _,
    Cart_SaleCardDrops_Explanation: _,
    Cart_SaleCardDrops_Explanation_Gifts: _,
    Cart_SaleCardDrops_ProgressLabel: _,
    Cart_SaleCardDrops_CardCost: _,
    Cart_SaleCardDrops_PrepurchaseIneligible: _,
    Cart_PurchaseRequestTitle: _,
    Cart_PurchaseFor_Label: _,
    Cart_GiftForNotice: _,
    Cart_LineItem_Add_Tooltip: _,
    Cart_LineItem_Hardware_Compliance_Label: _,
    Cart_ErrorUpdating: _,
    Cart_ErrorCode: _,
    Cart_UserCountrySelector: _,
    Cart_Replay_SavedCart: _,
    Cart_Replay_Instructions: _,
    Cart_Gifting_CopyGiftOptionsFrom: _,
    Cart_Gifting_SignInToSelectFriends: _,
  };
export {
  _ as Cart_Add,
  _ as Cart_AddedToYourCart,
  _ as Cart_BetaNotice,
  _ as Cart_Bradcrumb_Home,
  _ as Cart_CartLevelErrorFormat,
  _ as Cart_CartLevelErrorMultiple,
  _ as Cart_CartLevelErrorNotice,
  _ as Cart_ChangeGiftRecipient,
  _ as Cart_ComingSoon,
  _ as Cart_ContainsGiftCheckbox,
  _ as Cart_ContinueButton_Gifts,
  _ as Cart_ContinueButton_Login,
  _ as Cart_ContinueButton_Payment,
  _ as Cart_ContinueShopping,
  _ as Cart_CountWidget,
  _ as Cart_CouponAvailability,
  _ as Cart_CouponAvailability_Plural,
  _ as Cart_CouponModify_Add,
  _ as Cart_CouponModify_Change,
  _ as Cart_Coupons_Applied,
  _ as Cart_Coupons_InUse,
  _ as Cart_DeclinePurchaseRequest,
  _ as Cart_Edit,
  _ as Cart_EditGiftDelivery,
  _ as Cart_Empty,
  _ as Cart_EnterRecipientEmail,
  _ as Cart_ErrorCode,
  _ as Cart_ErrorUpdating,
  _ as Cart_Error_AdultContentRestricted_FootNote,
  _ as Cart_Error_AdultContentRestricted_LineItem,
  _ as Cart_Error_AlreadyOwned_FootNote,
  _ as Cart_Error_AlreadyOwned_GiftFootNote,
  _ as Cart_Error_AlreadyOwned_GiftLineItem,
  _ as Cart_Error_AlreadyOwned_GiftLineItem_Game,
  _ as Cart_Error_AlreadyOwned_LineItem,
  _ as Cart_Error_AlreadyOwned_LineItem_Game,
  _ as Cart_Error_CommercialLicenseRestricted_FootNote,
  _ as Cart_Error_CommercialLicenseRestricted_LineItem,
  _ as Cart_Error_CouponIsExclusivePromo,
  _ as Cart_Error_CouponIsInvalid,
  _ as Cart_Error_CouponIsInvalidForItem,
  _ as Cart_Error_DuplicateApps_FootNote,
  _ as Cart_Error_DuplicateApps_LineItem,
  _ as Cart_Error_ExistingBillingAgreement,
  _ as Cart_Error_ExistingBillingAgreement_FootNote,
  _ as Cart_Error_GiftRecipientInvalid,
  _ as Cart_Error_MasterSubscription_FootNote,
  _ as Cart_Error_MasterSubscription_LineItem,
  _ as Cart_Error_MissingMustOwnApps_FootNote,
  _ as Cart_Error_MissingMustOwnApps_FootNoteGift,
  _ as Cart_Error_MissingMustOwnApps_GiftLineItem,
  _ as Cart_Error_MissingMustOwnApps_LineItem,
  _ as Cart_Error_TooManyInCart,
  _ as Cart_Error_UnavailableCountry_FootNote,
  _ as Cart_Error_UnavailableCountry_LineItem,
  _ as Cart_EstimatedTotal,
  _ as Cart_FamilyGift_Notice,
  _ as Cart_FooterNoticeHeader_MustFix,
  _ as Cart_FooterNoticeHeader_Warning,
  _ as Cart_GenericBetaNotice,
  _ as Cart_GiftDeliveryEmail_Warning1,
  _ as Cart_GiftDeliveryEmail_Warning2,
  _ as Cart_GiftDelivery_AddSignature,
  _ as Cart_GiftDelivery_Body,
  _ as Cart_GiftDelivery_From,
  _ as Cart_GiftDelivery_Label,
  _ as Cart_GiftDelivery_Now,
  _ as Cart_GiftDelivery_Reset,
  _ as Cart_GiftDelivery_ScheduleDelivery,
  _ as Cart_GiftDelivery_Scheduled,
  _ as Cart_GiftDelivery_Signature,
  _ as Cart_GiftForNotice,
  _ as Cart_GiftOptions,
  _ as Cart_GiftRecipientEmail_Label,
  _ as Cart_GiftRecipientModal_IssueLoading,
  _ as Cart_GiftRecipientModal_OnWishlist,
  _ as Cart_GiftRecipientModal_OwnsGameLabel,
  _ as Cart_GiftRecipientModal_PartialOwnsLabel,
  _ as Cart_GiftRecipientModal_PartialWishlistLabel,
  _ as Cart_GiftRecipientModal_Placeholder,
  _ as Cart_GiftRecipientModal_Save,
  _ as Cart_GiftRecipientModal_Title,
  _ as Cart_GiftRecipient_Label,
  _ as Cart_GiftScheduleError_InvalidDate,
  _ as Cart_GiftScheduleError_TooFar,
  _ as Cart_GifteeHint_Wishlist,
  _ as Cart_Gifting_CopyGiftOptionsFrom,
  _ as Cart_Gifting_SignInToSelectFriends,
  _ as Cart_IncludesItems,
  _ as Cart_IncludesItems_Plural,
  _ as Cart_LineItemGift_Checkbox,
  _ as Cart_LineItemOptions_Gift,
  _ as Cart_LineItemOptions_GiftForPersona,
  _ as Cart_LineItemOptions_Myself,
  _ as Cart_LineItemOptions_PrivateTooltip,
  _ as Cart_LineItemOptions_Privately,
  _ as Cart_LineItem_Add_Tooltip,
  _ as Cart_LineItem_ErrorBoundary,
  _ as Cart_LineItem_Hardware_Compliance_Label,
  _ as Cart_Note_SalesTax,
  _ as Cart_Notice_SomeAppsPrivate,
  _ as Cart_PurchaseBtn,
  _ as Cart_PurchaseFor_Label,
  _ as Cart_PurchaseRequestTitle,
  _ as Cart_Quantity,
  _ as Cart_Remove,
  _ as Cart_RemoveAll,
  _ as Cart_Replay_Instructions,
  _ as Cart_Replay_SavedCart,
  _ as Cart_RequestPurchase,
  _ as Cart_RequestPurchaseExplanation,
  _ as Cart_RequestPurchaseNonGiftableItems,
  _ as Cart_SaleCardDrops_CardCost,
  _ as Cart_SaleCardDrops_EarnedMessage,
  _ as Cart_SaleCardDrops_EarnedMessage_Plural,
  _ as Cart_SaleCardDrops_Explanation,
  _ as Cart_SaleCardDrops_Explanation_Gifts,
  _ as Cart_SaleCardDrops_PrepurchaseIneligible,
  _ as Cart_SaleCardDrops_ProgressLabel,
  _ as Cart_SelectCouponToApply,
  _ as Cart_SelectRecipient,
  _ as Cart_ShippingEstimate_Delayed,
  _ as Cart_ShippingEstimate_DeliveryDate,
  _ as Cart_ShippingEstimate_Range,
  _ as Cart_ShippingEstimate_Standard,
  _ as Cart_UpdatedYourCart,
  _ as Cart_UserCountrySelector,
  _ as Cart_Verify,
  _ as Cart_ViewMyCart,
  _ as Cart_Warning_AlreadyOwned_LineItem,
  _ as Cart_Warning_AvailableAtALowerPrice,
  _ as Cart_Warning_ExtraCopies_LineItem,
  _ as Cart_Warning_GiftToAccount_LoggedOut_Actionable,
  _ as Cart_Warning_GiftToNonFriend,
  _ as Cart_Warning_GiftToNonFriend_Named,
  _ as Cart_Warning_NoRefund_LineItem,
  _ as Cart_Warning_PriceChange_FootNote,
  _ as Cart_Warning_PriceChange_LineItem,
  _ as Cart_Warning_RecipientHigherPrice,
  _ as Cart_YourShoppingCart,
  _ as Cart_YourShoppingCartLineItems,
  _ as Cart_YourShoppingCartLineItems_Plural,
  _ as GameBillingAuthorizeSubscriptionByDay,
  _ as GameBillingAuthorizeSubscriptionByHour,
  _ as GameBillingAuthorizeSubscriptionByMinute,
  _ as GameBillingAuthorizeSubscriptionByMonth,
  _ as GameBillingAuthorizeSubscriptionBySecond,
  _ as GameBillingAuthorizeSubscriptionByWeek,
  _ as GameBillingAuthorizeSubscriptionByYear,
  _ as GameBillingPackageCostIncludesSubscriptionByDay,
  _ as GameBillingPackageCostIncludesSubscriptionByHour,
  _ as GameBillingPackageCostIncludesSubscriptionByMinute,
  _ as GameBillingPackageCostIncludesSubscriptionByMonth,
  _ as GameBillingPackageCostIncludesSubscriptionBySecond,
  _ as GameBillingPackageCostIncludesSubscriptionByWeek,
  _ as GameBillingPackageCostIncludesSubscriptionByYear,
  _ as GameBillingPackageIncludesSubscriptionByDay,
  _ as GameBillingPackageIncludesSubscriptionByHour,
  _ as GameBillingPackageIncludesSubscriptionByMinute,
  _ as GameBillingPackageIncludesSubscriptionByMonth,
  _ as GameBillingPackageIncludesSubscriptionBySecond,
  _ as GameBillingPackageIncludesSubscriptionByWeek,
  _ as GameBillingPackageIncludesSubscriptionByYear,
  _ as MicroTxnSubscriptionCostByDay,
  _ as MicroTxnSubscriptionCostByHour,
  _ as MicroTxnSubscriptionCostByMinute,
  _ as MicroTxnSubscriptionCostByMonth,
  _ as MicroTxnSubscriptionCostBySecond,
  _ as MicroTxnSubscriptionCostByWeek,
  _ as MicroTxnSubscriptionCostByYear,
  _ as MultiLicenseCostIncludesSubscriptionByDay,
  _ as MultiLicenseCostIncludesSubscriptionByHour,
  _ as MultiLicenseCostIncludesSubscriptionByMinute,
  _ as MultiLicenseCostIncludesSubscriptionByMonth,
  _ as MultiLicenseCostIncludesSubscriptionBySecond,
  _ as MultiLicenseCostIncludesSubscriptionByWeek,
  _ as MultiLicenseCostIncludesSubscriptionByYear,
  _ as MultiLicenseIncludesSubscriptionByDay,
  _ as MultiLicenseIncludesSubscriptionByHour,
  _ as MultiLicenseIncludesSubscriptionByMinute,
  _ as MultiLicenseIncludesSubscriptionByMonth,
  _ as MultiLicenseIncludesSubscriptionBySecond,
  _ as MultiLicenseIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByDay,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByHour,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMinute,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMonth,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionBySecond,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByYear,
  _ as MultiLicenseeIncludesSubscriptionByYear,
  _ as PackageCostIncludesSubscriptionByDay,
  _ as PackageCostIncludesSubscriptionByHour,
  _ as PackageCostIncludesSubscriptionByMinute,
  _ as PackageCostIncludesSubscriptionByMonth,
  _ as PackageCostIncludesSubscriptionBySecond,
  _ as PackageCostIncludesSubscriptionByWeek,
  _ as PackageCostIncludesSubscriptionByYear,
  _ as PackageIncludesSubscriptionByDay,
  _ as PackageIncludesSubscriptionByHour,
  _ as PackageIncludesSubscriptionByMinute,
  _ as PackageIncludesSubscriptionByMonth,
  _ as PackageIncludesSubscriptionBySecond,
  _ as PackageIncludesSubscriptionByWeek,
  _ as PackageIncludesSubscriptionByYear,
  _ as PackageWithDiscountCostIncludesSubscriptionByDay,
  _ as PackageWithDiscountCostIncludesSubscriptionByHour,
  _ as PackageWithDiscountCostIncludesSubscriptionByMinute,
  _ as PackageWithDiscountCostIncludesSubscriptionByMonth,
  _ as PackageWithDiscountCostIncludesSubscriptionBySecond,
  _ as PackageWithDiscountCostIncludesSubscriptionByWeek,
  _ as PackageWithDiscountCostIncludesSubscriptionByYear,
  _ as default,
  _ as language,
};
