var _ = `الإنجليزية`,
  _ = `إدارة التوطين`,
  _ = `صدّر واستورد ملفات التوطين للتحكم بترجمة فعاليتك بأكملها.`,
  _ = `صدّر واستورد ملفات التوطين للتحكم بترجمة صفحتك بأكملها.`,
  _ = `تسجيل الدخول`,
  _ = `سجّل الدخول لإضافة هذا العنصر إلى قائمة أمنياتك، أو لمتابعته، أو لتجاهله. سيؤدي النقر على "موافق" إلى إعادة توجيهك إلى صفحة تسجيل الدخول.`,
  _ = `سجل الدخول أو افتح هذه الصفحة في Steam لإضافة العنصر إلى قائمة الأمنيات أو متابعته أو شرائه.`,
  _ = `%1$s تُعد %2$s على Steam Deck`,
  _ = `تم التحقق منه`,
  _ = `خضعت هذه اللعبة وألعاب أخرى عديدة لاختبارات كاملة وتعمل %1$s.`,
  _ = `تعمل جيدًا على Deck`,
  _ = `علامة التحقق`,
  _ = `Steam Deck OLED`,
  _ = `لافتة Steam Deck: "ألعابك، معك في كل مكان"`,
  _ = `قد لا يمثّل المقطع الترويجي طريقة اللعب الفعلية على Steam Deck`,
  _ = `تم العثور على %1$s (%2$s)`,
  _ = `لم يتم العثور عليه (%1$s)`,
  _ = `المراجعات من التطبيق`,
  _ = `التطبيق الذي تظهر مراجعات Steam الخاصة به في هذا القسم، والتطبيق الذي كُتبت مراجعة العميل بشأنه.`,
  _ = `تم قبول رابط %1$s`,
  _ = `ثمة خطأ، فالرابط لا يشير إلى أحد مواقع Steam (المتجر أو المجتمع)`,
  _ = `المدخلات غير صحيحة`,
  _ = `لون التسمية`,
  _ = `تدرج الخلفية (أعلى)`,
  _ = `تدرج الخلفية (أسفل)`,
  _ = `الانضمام إلى القائمة`,
  _ = `اختر أحد النماذج أدناه للتسجيل، يمكن للعملاء المؤهلين التسجيل في ما يصل إلى %1$s من النماذج.`,
  _ = `أنت مدرج في القائمة الخاصة بالنماذج المحددة أدناه`,
  _ = `أنت مدرج في القائمة الخاصة بالنماذج المحددة أدناه، يمكن للعملاء المؤهلين التسجيل في ما يصل إلى %1$s من النماذج.`,
  _ = `هل تود مغادرة القائمة؟`,
  _ = `إذا غادرت القائمة، فسيتم استبعادك من القائمة العشوائية لهذا النموذج. هل ترغب بالمتابعة؟`,
  _ = `لقد قرأت <1>الشروط والأحكام</1> وأوافق عليها.`,
  _ = `يُرجى الاطلاع على الشروط والأحكام الواردة أدناه`,
  _ = `سجّل الدخول للانضمام إلى القائمة`,
  _ = `سجّل الدخول إلى Steam للانضمام إلى القائمة. اضغط على موافق للانتقال إلى صفحة تسجيل الدخول.`,
  _ = `اختر نموذجًا أدناه للانضمام إلى قائمة الانتظار.`,
  _ = `أُغلقت القائمة ويُجرى ترتيبها بشكل عشوائي الآن. ستتلقى بريدًا إلكترونيًا بالنتائج في غضون يوم واحد.`,
  _ = `أُغلقت القائمة ويُجرى ترتيبها بشكل عشوائي الآن. إذا لم تسجّل في الوقت المحدد، فما زال يمكنك الانضمام إلى نهاية قائمة الانتظار لنموذج واحد.`,
  _ = `الانضمام إلى قائمة الانتظار`,
  _ = `هل تود مغادرة قائمة الانتظار؟`,
  _ = `إذا غادرت قائمة الانتظار، فستفقد مكانك فيها. وفي حال قررت الانضمام مجددًا فسيتم إدراج اسمك في آخر القائمة.`,
  _ = `هل تود تبديل قائمة الانتظار؟`,
  _ = `إذا انتقلت إلى قائمة انتظار أخرى، فستغادر قائمة انتظار %1$s وتتنازل عن مكانك فيها.`,
  _ = `جارٍ إضافتك إلى قائمة انتظار %1$s.`,
  _ = `مُدرج في قائمة الانتظار منذ %2$s`,
  _ = `مُدرج في قائمة انتظار %1$s منذ %2$s`,
  _ = `مُدرج بقائمة الانتظار`,
  _ = `أنت مُدرج في قائمة انتظار %1$s`,
  _ = `سنرسل إليك بريدًا إلكترونيًا فور توفر أي وحدة.`,
  _ = `انضم إلى قائمة الانتظار لتلقي إشعار فور توفر أي وحدات.`,
  _ = `انضم إلى قائمة الانتظار، وستتلقى إشعارًا في حال توفر الوحدات. سيؤدي هذا إلى إلغاء حجزك.`,
  _ = `سجّل الدخول للانضمام إلى قائمة الانتظار`,
  _ = `سجّل الدخول إلى Steam للانضمام إلى قائمة الانتظار. اضغط على موافق للانتقال إلى صفحة تسجيل الدخول.`,
  _ = `تم إدراجك في قائمة حجز %1$s`,
  _ = `تُطبق <1>الشروط والأحكام</1>.`,
  _ = `صوري`,
  _ = `عادةً`,
  _ = `أقل سعر له خلال 30 يومًا`,
  _ = `الآن`,
  _ = `dummy`,
  _ = {
    language: _,
    EventEditor_Loc_Title: _,
    EventEditor_Loc_Overview: _,
    EventEditor_Loc_Overview_Page: _,
    LoginRedirect_Dialog_Title: _,
    LoginRedirect_Dialog_Description: _,
    Wishlist_NotSignedIn: _,
    VerifiedProgram_DeckTitle: _,
    VerifiedProgram_DeckTitle_Verified: _,
    VerifiedProgram_DeckSubTitle: _,
    VerifiedProgram_GreatOnDeck: _,
    VerifiedProgram_DeckAlt: _,
    VerifiedProgram_DeckDeviceAlt: _,
    VerifiedProgram_DeckShopBannerAlt: _,
    VerifiedProgram_DeckDisclaimer: _,
    StoreItemFound: _,
    StoreItemNotFound: _,
    SteamReviewSection_AppID: _,
    SteamReviewSection_AppID_ttip: _,
    SteamURLAccepted: _,
    SteamURLInvalid: _,
    AnchorHashInputInvalid: _,
    Sale_Section_Label_Color: _,
    Sale_Section_Background_Top: _,
    Sale_Section_Background_Bottom: _,
    Reservation_JoinPool: _,
    Reserationn_NoListJoined: _,
    Reservation_InPool: _,
    Reservation_InPool_NoDate: _,
    Reservation_Cancel_Pool: _,
    Reservation_Cancel_Pool_Desc: _,
    Reservation_JoinPool_Terms: _,
    Reservation_JoinPool_ClickTerms: _,
    Reservation_Pool_NotSignedIn: _,
    Reservation_Pool_NotSignedIn_Desc: _,
    Reservation_Pool_Closed: _,
    Reservation_Pool_InProgress_Joined: _,
    Reservation_Pool_InProgress_NotJoined: _,
    Reservation_JoinWaitList: _,
    Reservation_Cancel_Waitlist: _,
    Reservation_Cancel_Waitlist_Desc: _,
    Reservation_Change_WaitList: _,
    Reservation_Change_WaitList_Desc1: _,
    Reservation_Change_WaitList_Desc2: _,
    Reservation_In_Waitlist: _,
    Reservation_In_Waitlist_WithName: _,
    Reservation_In_Waitlist_NoDate: _,
    Reservation_In_Waitlist_WithName_NoDate: _,
    Reservation_In_Waitlist_Message: _,
    Reservation_In_Waitlist_Message_NotJoin: _,
    Reservation_Join_Waitlist_Cancel_Reservation: _,
    Reservation_Waitlist_NotSignedIn: _,
    Reservation_Waitlist_NotSignedIn_Desc: _,
    Reservation_OnRegularReserveForModel: _,
    Reservation_PostShuffle_TAndC: _,
    machine_dummy: _,
    PriceGrid_NormalPrice: _,
    PriceGrid_RecentPrice: _,
    PriceGrid_CurrentPrice: _,
    Dummy: _,
  };
export {
  _ as AnchorHashInputInvalid,
  _ as Dummy,
  _ as EventEditor_Loc_Overview,
  _ as EventEditor_Loc_Overview_Page,
  _ as EventEditor_Loc_Title,
  _ as LoginRedirect_Dialog_Description,
  _ as LoginRedirect_Dialog_Title,
  _ as PriceGrid_CurrentPrice,
  _ as PriceGrid_NormalPrice,
  _ as PriceGrid_RecentPrice,
  _ as Reserationn_NoListJoined,
  _ as Reservation_Cancel_Pool,
  _ as Reservation_Cancel_Pool_Desc,
  _ as Reservation_Cancel_Waitlist,
  _ as Reservation_Cancel_Waitlist_Desc,
  _ as Reservation_Change_WaitList,
  _ as Reservation_Change_WaitList_Desc1,
  _ as Reservation_Change_WaitList_Desc2,
  _ as Reservation_InPool,
  _ as Reservation_InPool_NoDate,
  _ as Reservation_In_Waitlist,
  _ as Reservation_In_Waitlist_Message,
  _ as Reservation_In_Waitlist_Message_NotJoin,
  _ as Reservation_In_Waitlist_NoDate,
  _ as Reservation_In_Waitlist_WithName,
  _ as Reservation_In_Waitlist_WithName_NoDate,
  _ as Reservation_JoinPool,
  _ as Reservation_JoinPool_ClickTerms,
  _ as Reservation_JoinPool_Terms,
  _ as Reservation_JoinWaitList,
  _ as Reservation_Join_Waitlist_Cancel_Reservation,
  _ as Reservation_OnRegularReserveForModel,
  _ as Reservation_Pool_Closed,
  _ as Reservation_Pool_InProgress_Joined,
  _ as Reservation_Pool_InProgress_NotJoined,
  _ as Reservation_Pool_NotSignedIn,
  _ as Reservation_Pool_NotSignedIn_Desc,
  _ as Reservation_PostShuffle_TAndC,
  _ as Reservation_Waitlist_NotSignedIn,
  _ as Reservation_Waitlist_NotSignedIn_Desc,
  _ as Sale_Section_Background_Bottom,
  _ as Sale_Section_Background_Top,
  _ as Sale_Section_Label_Color,
  _ as SteamReviewSection_AppID,
  _ as SteamReviewSection_AppID_ttip,
  _ as SteamURLAccepted,
  _ as SteamURLInvalid,
  _ as StoreItemFound,
  _ as StoreItemNotFound,
  _ as VerifiedProgram_DeckAlt,
  _ as VerifiedProgram_DeckDeviceAlt,
  _ as VerifiedProgram_DeckDisclaimer,
  _ as VerifiedProgram_DeckShopBannerAlt,
  _ as VerifiedProgram_DeckSubTitle,
  _ as VerifiedProgram_DeckTitle,
  _ as VerifiedProgram_DeckTitle_Verified,
  _ as VerifiedProgram_GreatOnDeck,
  _ as Wishlist_NotSignedIn,
  _ as default,
  _ as language,
  _ as machine_dummy,
};
