var _ = `french`,
  _ = `Gérer la localisation`,
  _ = `Exportez et importez des fichiers de localisation pour gérer les versions multilingues de vos textes pendant toute la durée de votre évènement.`,
  _ = `Exportez et importez des fichiers de traduction pour gérer les versions multilingues de vos textes pour toute la page.`,
  _ = `Se connecter`,
  _ = `Connectez-vous pour ajouter cet article à votre liste de souhaits, le suivre ou l'ignorer. Cliquez sur OK pour ouvrir la page de connexion.`,
  _ = `Connectez-vous ou ouvrez cette page dans l'application\xA0Steam pour ajouter l'article à votre liste de souhaits, le suivre ou l'acheter.`,
  _ = `%1$s est %2$s avec Steam\xA0Deck.`,
  _ = `compatible`,
  _ = `Ce jeu et beaucoup d'autres ont été minutieusement testés et sont %1$s.`,
  _ = `parfaits pour Steam\xA0Deck`,
  _ = `certifié`,
  _ = `Steam\xA0Deck\xA0OLED`,
  _ = `Bannière Steam\xA0Deck\xA0: «\xA0Vos jeux, partout avec vous\xA0»`,
  _ = `La bande-annonce peut ne pas représenter l'expérience de jeu réelle sur Steam\xA0Deck`,
  _ = `%1$s\xA0trouvé(s) (%2$s)`,
  _ = `Introuvable(s) (%1$s)`,
  _ = `Évaluations provenant de l'application`,
  _ = `L'application dont les évaluations Steam s'affichent dans cette section, et concernant laquelle une évaluation est rédigée.`,
  _ = `%1$s URL acceptée`,
  _ = `Erreur\xA0: l'URL ne redirige pas vers un article du magasin ou de la communauté\xA0Steam.`,
  _ = `Entrée non valide`,
  _ = `Couleur du texte`,
  _ = `Dégradé de l'arrière-plan (haut)`,
  _ = `Dégradé de l'arrière-plan (bas)`,
  _ = `Rejoindre la liste`,
  _ = `Sélectionnez un modèle ci-dessous pour vous inscrire. Les personnes satisfaisant aux critères peuvent s'inscrire pour un maximum de %1$s\xA0modèles.`,
  _ = `Vous êtes sur la liste pour les modèles sélectionnés ci-dessous`,
  _ = `Vous êtes sur la liste d'inscription des modèles et bundles sélectionnés ci-dessous. Les personnes satisfaisant aux critères peuvent s'inscrire pour un maximum de %1$s\xA0modèles.`,
  _ = `Quitter la liste\xA0?`,
  _ = `Si vous quittez la liste, vous ne ferez pas partie de la répartition aléatoire de celle-ci pour ce modèle. Voulez-vous continuer\xA0?`,
  _ = `J'ai lu et accepté les <1>Conditions d'utilisation</1>.`,
  _ = `Veuillez consulter les conditions d'utilisation ci-dessus.`,
  _ = `Connectez-vous pour rejoindre la liste`,
  _ = `Connectez-vous sur Steam pour rejoindre la liste. Cliquez sur «\xA0OK\xA0» pour accéder à la page de connexion.`,
  _ = `Inscrivez-vous à la liste avant le %1$s, date à laquelle les inscriptions seront fermées et la répartition aléatoire sera effectuée. Les résultats vous seront envoyés par e-mail sous 24\xA0heures.`,
  _ = `Choisissez un modèle ou bundle ci-dessous pour prendre votre place dans la file d'attente.`,
  _ = `Les inscriptions sont désormais closes et la répartition aléatoire est en cours. Vous recevrez un e-mail dans les 24\xA0heures avec vos résultats.`,
  _ = `Les inscriptions sont désormais closes et la liste aléatoire est en cours de génération. Si vous n'avez pas pu faire votre demande à temps, vous pouvez rejoindre la fin de la file d'attente pour l'un des modèles ou bundles.`,
  _ = `Sélectionnez un modèle ci-dessous pour vous inscrire. Les personnes satisfaisant aux critères peuvent s'inscrire pour un seul modèle.`,
  _ = `Vous êtes sur la liste pour %1$s`,
  _ = `Vous êtes sur la liste`,
  _ = `Vous souhaitez changer de modèle\xA0?`,
  _ = `En changeant de modèle, vous quitterez la liste pour %1$s.`,
  _ = `Vous vous inscrivez sur la liste pour %1$s.`,
  _ = `S'inscrire à la file d'attente`,
  _ = `Quitter la file d'attente\xA0?`,
  _ = `En quittant la file d'attente, vous abandonnez votre place dans la file. Si vous souhaitez vous réinscrire à la file d'attente, votre place sera en bout de file.`,
  _ = `Changer de file d'attente\xA0?`,
  _ = `En changeant de file d'attente, vous quittez la file pour %1$s et renoncez à votre place dans la file.`,
  _ = `Vous vous inscrivez sur la file d'attente pour\xA0%1$s.`,
  _ = `Dans la file d'attente depuis le %2$s`,
  _ = `Dans la file d'attente pour %1$s depuis le %2$s`,
  _ = `Dans la file d'attente`,
  _ = `Vous êtes dans la file d'attente pour %1$s`,
  _ = `Nous vous enverrons un e-mail si un appareil devient disponible.`,
  _ = `Rejoignez la file d'attente, et nous vous avertirons si un appareil devient disponible.`,
  _ = `Inscrivez-vous à la file d'attente et vous serez averti si davantage d'unités deviennent disponibles. Cela annulera votre réservation actuelle.`,
  _ = `Connectez-vous pour rejoindre la file d'attente`,
  _ = `Connectez-vous sur Steam pour rejoindre la file d'attente. Cliquez sur «\xA0OK\xA0» pour accéder à la page de connexion.`,
  _ = `Vous êtes dans la liste de réservations pour %1$s`,
  _ = `Sous réserve des <1>conditions d'utilisation</1>.`,
  _ = `dummy`,
  _ = `NORMALEMENT`,
  _ = `PLUS BAS (30 DER. JOURS)`,
  _ = `ACTUELLEMENT`,
  _ = `dummy`,
  _ = {
    language: _,
    EventEditor_Loc_Title: _,
    EventEditor_Loc_Overview: _,
    EventEditor_Loc_Overview_Page: _,
    LoginRedirect_Dialog_Title: _,
    LoginRedirect_Dialog_Description: _,
    Wishlist_NotSignedIn: _,
    VerifiedProgram_DeckTitle: _,
    VerifiedProgram_DeckTitle_Verified: _,
    VerifiedProgram_DeckSubTitle: _,
    VerifiedProgram_GreatOnDeck: _,
    VerifiedProgram_DeckAlt: _,
    VerifiedProgram_DeckDeviceAlt: _,
    VerifiedProgram_DeckShopBannerAlt: _,
    VerifiedProgram_DeckDisclaimer: _,
    StoreItemFound: _,
    StoreItemNotFound: _,
    SteamReviewSection_AppID: _,
    SteamReviewSection_AppID_ttip: _,
    SteamURLAccepted: _,
    SteamURLInvalid: _,
    AnchorHashInputInvalid: _,
    Sale_Section_Label_Color: _,
    Sale_Section_Background_Top: _,
    Sale_Section_Background_Bottom: _,
    Reservation_JoinPool: _,
    Reserationn_NoListJoined: _,
    Reservation_InPool: _,
    Reservation_InPool_NoDate: _,
    Reservation_Cancel_Pool: _,
    Reservation_Cancel_Pool_Desc: _,
    Reservation_JoinPool_Terms: _,
    Reservation_JoinPool_ClickTerms: _,
    Reservation_Pool_NotSignedIn: _,
    Reservation_Pool_NotSignedIn_Desc: _,
    Reservation_InPool_Message_Date: _,
    Reservation_Pool_Closed: _,
    Reservation_Pool_InProgress_Joined: _,
    Reservation_Pool_InProgress_NotJoined: _,
    Reservation_NoListJoined_OneModel: _,
    Reservation_InPool_WithName: _,
    Reservation_InPool_NoName: _,
    Reservation_Change_Pool: _,
    Reservation_Change_Pool_Desc1: _,
    Reservation_Change_Pool_Desc2: _,
    Reservation_JoinWaitList: _,
    Reservation_Cancel_Waitlist: _,
    Reservation_Cancel_Waitlist_Desc: _,
    Reservation_Change_WaitList: _,
    Reservation_Change_WaitList_Desc1: _,
    Reservation_Change_WaitList_Desc2: _,
    Reservation_In_Waitlist: _,
    Reservation_In_Waitlist_WithName: _,
    Reservation_In_Waitlist_NoDate: _,
    Reservation_In_Waitlist_WithName_NoDate: _,
    Reservation_In_Waitlist_Message: _,
    Reservation_In_Waitlist_Message_NotJoin: _,
    Reservation_Join_Waitlist_Cancel_Reservation: _,
    Reservation_Waitlist_NotSignedIn: _,
    Reservation_Waitlist_NotSignedIn_Desc: _,
    Reservation_OnRegularReserveForModel: _,
    Reservation_PostShuffle_TAndC: _,
    machine_dummy: _,
    PriceGrid_NormalPrice: _,
    PriceGrid_RecentPrice: _,
    PriceGrid_CurrentPrice: _,
    Dummy: _,
  };
export {
  _ as AnchorHashInputInvalid,
  _ as Dummy,
  _ as EventEditor_Loc_Overview,
  _ as EventEditor_Loc_Overview_Page,
  _ as EventEditor_Loc_Title,
  _ as LoginRedirect_Dialog_Description,
  _ as LoginRedirect_Dialog_Title,
  _ as PriceGrid_CurrentPrice,
  _ as PriceGrid_NormalPrice,
  _ as PriceGrid_RecentPrice,
  _ as Reserationn_NoListJoined,
  _ as Reservation_Cancel_Pool,
  _ as Reservation_Cancel_Pool_Desc,
  _ as Reservation_Cancel_Waitlist,
  _ as Reservation_Cancel_Waitlist_Desc,
  _ as Reservation_Change_Pool,
  _ as Reservation_Change_Pool_Desc1,
  _ as Reservation_Change_Pool_Desc2,
  _ as Reservation_Change_WaitList,
  _ as Reservation_Change_WaitList_Desc1,
  _ as Reservation_Change_WaitList_Desc2,
  _ as Reservation_InPool,
  _ as Reservation_InPool_Message_Date,
  _ as Reservation_InPool_NoDate,
  _ as Reservation_InPool_NoName,
  _ as Reservation_InPool_WithName,
  _ as Reservation_In_Waitlist,
  _ as Reservation_In_Waitlist_Message,
  _ as Reservation_In_Waitlist_Message_NotJoin,
  _ as Reservation_In_Waitlist_NoDate,
  _ as Reservation_In_Waitlist_WithName,
  _ as Reservation_In_Waitlist_WithName_NoDate,
  _ as Reservation_JoinPool,
  _ as Reservation_JoinPool_ClickTerms,
  _ as Reservation_JoinPool_Terms,
  _ as Reservation_JoinWaitList,
  _ as Reservation_Join_Waitlist_Cancel_Reservation,
  _ as Reservation_NoListJoined_OneModel,
  _ as Reservation_OnRegularReserveForModel,
  _ as Reservation_Pool_Closed,
  _ as Reservation_Pool_InProgress_Joined,
  _ as Reservation_Pool_InProgress_NotJoined,
  _ as Reservation_Pool_NotSignedIn,
  _ as Reservation_Pool_NotSignedIn_Desc,
  _ as Reservation_PostShuffle_TAndC,
  _ as Reservation_Waitlist_NotSignedIn,
  _ as Reservation_Waitlist_NotSignedIn_Desc,
  _ as Sale_Section_Background_Bottom,
  _ as Sale_Section_Background_Top,
  _ as Sale_Section_Label_Color,
  _ as SteamReviewSection_AppID,
  _ as SteamReviewSection_AppID_ttip,
  _ as SteamURLAccepted,
  _ as SteamURLInvalid,
  _ as StoreItemFound,
  _ as StoreItemNotFound,
  _ as VerifiedProgram_DeckAlt,
  _ as VerifiedProgram_DeckDeviceAlt,
  _ as VerifiedProgram_DeckDisclaimer,
  _ as VerifiedProgram_DeckShopBannerAlt,
  _ as VerifiedProgram_DeckSubTitle,
  _ as VerifiedProgram_DeckTitle,
  _ as VerifiedProgram_DeckTitle_Verified,
  _ as VerifiedProgram_GreatOnDeck,
  _ as Wishlist_NotSignedIn,
  _ as default,
  _ as language,
  _ as machine_dummy,
};
