var _ = `© %1$s Valve Corporation. Minden jog fenntartva. A védjegyek jogos tulajdonosaiké az Egyesült Államokban és más országokban.<br>Minden ár tartalmazza az áfát, ahol az érvényben van.`,
  _ = `STEAM`,
  _ = `VALVE`,
  _ = `JOGI INFORMÁCIÓK`,
  _ = `EGYEBEK`,
  _ = `A Steamről`,
  _ = `Steam előfizetői szerződés`,
  _ = `Steamworks`,
  _ = `Steam Terjesztés`,
  _ = `Ajándékkártyák`,
  _ = `A Valve-ről`,
  _ = `Munkalehetőségek`,
  _ = `Hardverek`,
  _ = `Újrahasznosítás`,
  _ = `Adatvédelem`,
  _ = `Kisegítő lehetőségek`,
  _ = `Közlemények és irányelvek`,
  _ = `Sütik`,
  _ = `Visszatérítések`,
  _ = `A Steam beszerzése`,
  _ = `Mobilalkalmazások beszerzése`,
  _ = `Támogatás`,
  _ = `Fiókom`,
  _ = `Mobil weboldalra váltás`,
  _ = {
    footer_legal_notice: _,
    footer_link_header_steam: _,
    footer_link_header_valve: _,
    footer_link_header_legal: _,
    footer_link_header_more: _,
    footer_link_about_steam: _,
    footer_link_steam_ssa: _,
    footer_link_steamworks: _,
    footer_link_steam_distribution: _,
    footer_link_gift_cards: _,
    footer_link_about_valve: _,
    footer_link_jobs: _,
    footer_link_hardware: _,
    footer_link_recycling: _,
    footer_link_privacy: _,
    footer_link_accessibility: _,
    footer_link_notices_and_policies: _,
    footer_link_cookies: _,
    footer_link_refunds: _,
    footer_link_get_steam: _,
    footer_link_get_mobile_apps: _,
    footer_link_get_support: _,
    footer_link_my_account: _,
    footer_view_mobile_website: _,
  };
export {
  _ as default,
  _ as footer_legal_notice,
  _ as footer_link_about_steam,
  _ as footer_link_about_valve,
  _ as footer_link_accessibility,
  _ as footer_link_cookies,
  _ as footer_link_get_mobile_apps,
  _ as footer_link_get_steam,
  _ as footer_link_get_support,
  _ as footer_link_gift_cards,
  _ as footer_link_hardware,
  _ as footer_link_header_legal,
  _ as footer_link_header_more,
  _ as footer_link_header_steam,
  _ as footer_link_header_valve,
  _ as footer_link_jobs,
  _ as footer_link_my_account,
  _ as footer_link_notices_and_policies,
  _ as footer_link_privacy,
  _ as footer_link_recycling,
  _ as footer_link_refunds,
  _ as footer_link_steam_distribution,
  _ as footer_link_steam_ssa,
  _ as footer_link_steamworks,
  _ as footer_view_mobile_website,
};
