var _ = `italian`,
  _ = `Rimuovi`,
  _ = `Aggiungi`,
  _ = `Verifica dell'età`,
  _ = `Rimuovi tutti gli articoli`,
  _ = `Modifica`,
  _ = `Quantità: %1$s`,
  _ = `Il tuo carrello`,
  _ = `Il tuo carrello (%1$s articolo)`,
  _ = `Il tuo carrello (%1$s articoli)`,
  _ = `Totale stimato`,
  _ = `L'imposta sulle vendite verrà calcolata al momento del pagamento, ove applicabile.`,
  _ = `Acquista`,
  _ = `Questo acquisto contiene un regalo`,
  _ = `Pagina principale`,
  _ = `Questo è un dono?`,
  _ = `Include %1$s articolo`,
  _ = `Include %1$s articoli`,
  _ = `Seleziona il destinatario`,
  _ = `Inserisci e-mail`,
  _ = `Modifica il destinatario del dono...`,
  _ = `Destinatario del dono:`,
  _ = `E-mail del destinatario del dono:`,
  _ = `Consegna:`,
  _ = `Ripristina`,
  _ = `Il prima possibile (via e-mail e client di Steam)`,
  _ = `Pianificata:`,
  _ = `Pianifica consegna`,
  _ = `Da:`,
  _ = `La tua firma:`,
  _ = `Aggiungi firma personalizzata`,
  _ = `Messaggio del dono (limite di 160 caratteri, %1$s rimanenti):`,
  _ = `I doni inviati via e-mail verranno rimborsati automaticamente dopo 30 giorni se non sono stati aggiunti a un account di Steam.`,
  _ = `I doni inviati via e-mail possono essere accettati solo dagli account di Steam nella stessa regione dell'acquirente (%1$s).`,
  _ = `I doni inviati ai bambini della tua condivisione familiare di Steam verranno aggiunti automaticamente al loro account e ai loro giochi consentiti.`,
  _ = `Seleziona il destinatario del dono`,
  _ = `Modifica il metodo di consegna`,
  _ = `Salva`,
  _ = `Salva per nome amico...`,
  _ = `Possiede già questo articolo`,
  _ = `Nella Lista dei desideri`,
  _ = `Possiede già %1$s`,
  _ = `Ha %1$s nella Lista dei desideri`,
  _ = `Opzioni del dono`,
  _ = `Si è verificato un problema durante il caricamento dei destinatari idonei del dono. Riprova più tardi.`,
  _ = `Procedi al pagamento`,
  _ = `Continua con le opzioni del dono`,
  _ = `Accedi per acquistare`,
  _ = `Rifiuta richiesta`,
  _ = `Per il mio account`,
  _ = `Questo è un dono`,
  _ = `Questo è un dono per %1$s`,
  _ = `Per il mio account: privato`,
  _ = `Carrello (%1$s)`,
  _ = `Aggiunto al tuo carrello!`,
  _ = `Carrello aggiornato!`,
  _ = `Fai altri acquisti`,
  _ = `Disponibile in data %1$s`,
  _ = `Visualizza il mio carrello (%1$s)`,
  _ = `Richiedi acquisto`,
  _ = `La richiesta di acquisto verrà notificata agli adulti della tua condivisione familiare di Steam.`,
  _ = `Impossibile richiedere l'acquisto perché non tutti gli articoli nel carrello sono regalabili`,
  _ = `Cambia/Rimuovi coupon`,
  _ = `Aggiungi coupon`,
  _ = `È disponibile un coupon per questo articolo`,
  _ = `Hai %1$s coupon disponibili per questo articolo`,
  _ = `Applicato attualmente`,
  _ = `Applicato attualmente a un altro prodotto`,
  _ = `Seleziona un coupon da applicare a %1$s`,
  _ = `Consegna stimata: %1$s`,
  _ = `%1$s-%2$s giorni lavorativi`,
  _ = `Tempo di consegna stimato: 6-10 giorni lavorativi`,
  _ = `Tempo di consegna stimato: 3-5 giorni lavorativi`,
  _ = `Prima di poter procedere al pagamento:`,
  _ = `Note:`,
  _ = `È necessaria un'azione prima di poter procedere al pagamento`,
  _ = `Note:`,
  _ = `Nota: %1$s`,
  _ = `Il tuo account possiede già alcuni degli articoli qui sopra, pertanto non puoi riacquistarli. Per procedere puoi acquistare questi articoli come doni o modificare il contenuto del carrello.`,
  _ = `Possiedi già questo gioco`,
  _ = `Possiedi già tutti i contenuti di questo pacchetto`,
  _ = `Il destinatario del dono possiede già questo gioco`,
  _ = `Il destinatario del dono possiede già tutto il contenuto di questo pacchetto`,
  _ = `Il destinatario del dono possiede già alcuni degli articoli qui sopra, pertanto non puoi riacquistarli. Per procedere, puoi acquistare questi articoli per un account diverso o modificare il contenuto del carrello.`,
  _ = `Nel tuo carrello ci sono pacchetti che si sovrappongono. Prima di procedere alla cassa devi rimuovere i pacchetti ridondanti.`,
  _ = `Già nel carrello: `,
  _ = `Il carrello contiene un pacchetto che non è disponibile nel tuo paese. Devi rimuovere il pacchetto dal carrello prima di poter procedere alla cassa.`,
  _ = `Non disponibile nel tuo Paese`,
  _ = `Valve è tenuta a verificare che tu abbia almeno 18 anni prima di consentire l'acquisto di contenuti sessuali per adulti.`,
  _ = `Non disponibile per l'acquisto finché non confermi la tua età.`,
  _ = `Il carrello include contenuti disponibili anche attraverso uno dei tuoi abbonamenti attivi.`,
  _ = `Disponibile tramite l'abbonamento di:`,
  _ = `Questo coupon non può essere usato insieme a un altro sconto.`,
  _ = `Questo coupon non è valido o è scaduto.`,
  _ = `Questo coupon non può essere applicato a questo articolo.`,
  _ = `Hai superato la quantità massima consentita nel carrello per questo articolo.`,
  _ = `Il tuo carrello contiene un articolo che non è disponibile per l'acquisto.`,
  _ = `Non disponibile per l'acquisto`,
  _ = `Il destinatario selezionato non può ricevere questo dono acquistato nella tua regione.`,
  _ = `L'acquisto di questo articolo richiede il possesso dei seguenti articoli:`,
  _ = `Questo articolo richiede che il destinatario del dono possieda i seguenti articoli:`,
  _ = `Il tuo account non possiede alcuni articoli necessari per l'acquisto degli articoli nel carrello. È possibile aggiungere gli articoli mancanti o modificare il contenuto del carrello per continuare.`,
  _ = `Il destinatario del dono non possiede alcuni articoli necessari per l'acquisto degli articoli nel carrello. È possibile aggiungere gli articoli mancanti o modificare il contenuto del carrello per continuare.`,
  _ = `Hai già un abbonamento per questo articolo.`,
  _ = `Il tuo account ha già un abbonamento per alcuni degli articoli sopra indicati. Visualizza le impostazioni dell'abbonamento nei dettagli del tuo account.`,
  _ = `Se l'acquisto è per te, non riceverai copie extra di:`,
  _ = `Se l'acquisto è per te, riceverai una copia extra inviabile in dono di:`,
  _ = `Il prezzo di uno o più articoli presenti nel tuo carrello è cambiato.`,
  _ = `Il prezzo di questo articolo è cambiato`,
  _ = `Questo prodotto contiene contenuti consumabili e non può essere rimborsato.`,
  _ = `Il destinatario del dono che hai selezionato si trova in una regione con prezzi più alti. Il costo di questo articolo è stato aggiornato in modo da corrispondere alla sua regione per consentire al destinatario di ricevere il dono.`,
  _ = `Questo articolo è disponibile a un prezzo più basso come parte di: %1$s.`,
  _ = `Il destinatario del dono NON è nella tua lista amici di Steam.`,
  _ = `NOTA: %1$s NON è nella tua lista amici di Steam.`,
  _ = `Se stai inviando un regalo a un amico di Steam, <1>accedi</1> per verificare che il destinatario sia presente nella tua lista amici.`,
  _ = `Di recente hai visualizzato la Lista dei desideri di %1$s. Vuoi regalare questi articoli a questo utente?`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s secondo/i.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s minuto/i.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s ora/e.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s giorno/i.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s settimana/e.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s mese/i.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s anno/i.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s secondo/i per licenza.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s minuto/i per licenza.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s ora/e per licenza.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s giorno/i per licenza.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s settimana/e per licenza.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s mese/i per licenza.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s anno/i per licenza.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s secondo/i o come stabilito dal tuo account del gioco.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s minuto/i o come stabilito dal tuo account del gioco.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s ora/e o come stabilito dal tuo account del gioco.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s giorno/i o come stabilito dal tuo account del gioco.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s settimana/e o come stabilito dal tuo account del gioco.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s mese/i o come stabilito dal tuo account del gioco.`,
  _ = `Sottoscrizione che addebita %1$s ogni %2$s anno/i o come stabilito dal tuo account del gioco.`,
  _ = `Ti verranno addebitati %1$s alla cassa.<br/>Accetti inoltre l'addebito automatico di %2$s ogni %3$s secondo/i.`,
  _ = `Ti verranno addebitati %1$s alla cassa.<br/>Accetti inoltre l'addebito automatico di %2$s ogni %3$s minuto/i.`,
  _ = `Ti verranno addebitati %1$s alla cassa.<br/>Accetti inoltre l'addebito automatico di %2$s ogni %3$s ora/e.`,
  _ = `Ti verranno addebitati %1$s alla cassa.<br/>Accetti inoltre l'addebito automatico di %2$s ogni %3$s giorno/i.`,
  _ = `Ti verranno addebitati %1$s alla cassa.<br/>Accetti inoltre l'addebito automatico di %2$s ogni %3$s settimana/e.`,
  _ = `Ti verranno addebitati %1$s alla cassa.<br/>Accetti inoltre l'addebito automatico di %2$s ogni %3$s mese/i.`,
  _ = `Ti verranno addebitati %1$s alla cassa.<br/>Accetti inoltre l'addebito automatico di %2$s ogni %3$s anno/i.`,
  _ = `Ti verranno addebitati %1$s alla cassa.<br/>Autorizzi inoltre il gioco ad effettuare ulteriori addebiti del valore massimo di %2$s ogni %3$s secondo/i.`,
  _ = `Ti verranno addebitati %1$s alla cassa.<br/>Autorizzi inoltre il gioco ad effettuare ulteriori addebiti del valore massimo di %2$s ogni %3$s minuto/i.`,
  _ = `Ti verranno addebitati %1$s alla cassa.<br/>Autorizzi inoltre il gioco ad effettuare ulteriori addebiti del valore massimo di %2$s ogni %3$s ora/e.`,
  _ = `Ti verranno addebitati %1$s alla cassa.<br/>Autorizzi inoltre il gioco ad effettuare ulteriori addebiti del valore massimo di %2$s ogni %3$s giorno/i.`,
  _ = `Ti verranno addebitati %1$s alla cassa.<br/>Autorizzi inoltre il gioco ad effettuare ulteriori addebiti del valore massimo di %2$s ogni %3$s settimana/e.`,
  _ = `Ti verranno addebitati %1$s alla cassa.<br/>Autorizzi inoltre il gioco ad effettuare ulteriori addebiti del valore massimo di %2$s ogni %3$s mese/i.`,
  _ = `Ti verranno addebitati %1$s alla cassa.<br/>Autorizzi inoltre il gioco ad effettuare ulteriori addebiti del valore massimo di %2$s ogni %3$s anno/i.`,
  _ = `%1$s alla cassa, con il rinnovo automatico di %2$s ogni %3$s secondo/i.`,
  _ = `%1$s alla cassa, con il rinnovo automatico di %2$s ogni %3$s minuto/i.`,
  _ = `%1$s alla cassa, con il rinnovo automatico di %2$s ogni %3$s ora/e.`,
  _ = `%1$s alla cassa, con il rinnovo automatico di %2$s ogni %3$s giorno/i.`,
  _ = `%1$s alla cassa, con il rinnovo automatico di %2$s ogni %3$s settimana/e.`,
  _ = `%1$s alla cassa, con il rinnovo automatico di %2$s ogni %3$s mese/i.`,
  _ = `%1$s alla cassa, con il rinnovo automatico di %2$s ogni %3$s anno/i.`,
  _ = `Al momento del pagamento, viene applicato uno sconto del %4$s% rispetto al prezzo di %1$s per il primo acquisto. Si rinnova automaticamente ogni %3$s secondo/i a %2$s.`,
  _ = `Al momento del pagamento, viene applicato uno sconto del %4$s% rispetto al prezzo di %1$s per il primo acquisto. Si rinnova automaticamente ogni %3$s minuto/i a %2$s.`,
  _ = `Al momento del pagamento, viene applicato uno sconto del %4$s% rispetto al prezzo di %1$s per il primo acquisto. Si rinnova automaticamente ogni %3$s ora/e a %2$s.`,
  _ = `Al momento del pagamento, viene applicato uno sconto del %4$s% rispetto al prezzo di %1$s per il primo acquisto. Si rinnova automaticamente ogni %3$s giorno/i a %2$s.`,
  _ = `Al momento del pagamento, viene applicato uno sconto del %4$s% rispetto al prezzo di %1$s per il primo acquisto. Si rinnova automaticamente ogni %3$s settimana/e a %2$s.`,
  _ = `Al momento del pagamento, viene applicato uno sconto del %4$s% rispetto al prezzo di %1$s per il primo acquisto. Si rinnova automaticamente ogni %3$s mese/i a %2$s.`,
  _ = `Al momento del pagamento, viene applicato uno sconto del %4$s% rispetto al prezzo di %1$s per il primo acquisto. Si rinnova automaticamente ogni %3$s anno/i a %2$s.`,
  _ = `%1$s alla cassa, con il rinnovo automatico di %2$s ogni %3$s secondo/i come stabilito dal tuo account del gioco.`,
  _ = `%1$s alla cassa, con il rinnovo automatico di %2$s ogni %3$s minuto/i come stabilito dal tuo account del gioco.`,
  _ = `%1$s alla cassa, con il rinnovo automatico di %2$s ogni %3$s ora/e come stabilito dal tuo account del gioco.`,
  _ = `%1$s alla cassa, con il rinnovo automatico di %2$s ogni %3$s giorno/i come stabilito dal tuo account del gioco.`,
  _ = `%1$s alla cassa, con il rinnovo automatico di %2$s ogni %3$s settimana/e come stabilito dal tuo account del gioco.`,
  _ = `%1$s alla cassa, con il rinnovo automatico di %2$s ogni %3$s mese/i come stabilito dal tuo account del gioco.`,
  _ = `%1$s alla cassa, con il rinnovo automatico di %2$s ogni %3$s anno/i come stabilito dal tuo account del gioco.`,
  _ = `%1$s alla cassa, rinnovato automaticamente ogni %3$s secondo/i a %2$s per licenza.`,
  _ = `%1$s alla cassa, rinnovato automaticamente ogni %3$s minuto/i a %2$s per licenza.`,
  _ = `%1$s alla cassa, rinnovato automaticamente ogni %3$s ora/e a %2$s per licenza.`,
  _ = `%1$s alla cassa, rinnovato automaticamente ogni %3$s giorno/i a %2$s per licenza.`,
  _ = `%1$s alla cassa, rinnovato automaticamente ogni %3$s settimana/e a %2$s per licenza.`,
  _ = `%1$s alla cassa, rinnovato automaticamente ogni %3$s mese/i a %2$s per licenza.`,
  _ = `%1$s alla cassa, rinnovato automaticamente ogni %3$s anno/i a %2$s per licenza.`,
  _ = `Al momento del pagamento, viene applicato uno sconto del %4$s% rispetto al prezzo di %1$s per il primo acquisto. Si rinnova automaticamente ogni %3$s secondo/i a %2$s per licenza.`,
  _ = `Al momento del pagamento, viene applicato uno sconto del %4$s% rispetto al prezzo di %1$s per il primo acquisto. Si rinnova automaticamente ogni %3$s minuto/i a %2$s per licenza.`,
  _ = `Al momento del pagamento, viene applicato uno sconto del %4$s% rispetto al prezzo di %1$s per il primo acquisto. Si rinnova automaticamente ogni %3$s ora/e a %2$s per licenza.`,
  _ = `Al momento del pagamento, viene applicato uno sconto del %4$s% rispetto al prezzo di %1$s per il primo acquisto. Si rinnova automaticamente ogni %3$s giorno/i a %2$s per licenza.`,
  _ = `Al momento del pagamento, viene applicato uno sconto del %4$s% rispetto al prezzo di %1$s per il primo acquisto. Si rinnova automaticamente ogni %3$s settimana/e a %2$s per licenza.`,
  _ = `Al momento del pagamento, viene applicato uno sconto del %4$s% rispetto al prezzo di %1$s per il primo acquisto. Si rinnova automaticamente ogni %3$s mese/i a %2$s per licenza.`,
  _ = `Al momento del pagamento, viene applicato uno sconto del %4$s% rispetto al prezzo di %1$s per il primo acquisto. Si rinnova automaticamente ogni %3$s anno/i a %2$s per licenza.`,
  _ = `Il tuo carrello è vuoto.`,
  _ = `Alcuni di questi articoli sono già contrassegnati come privati. Rimarranno privati se continui:`,
  _ = `Contrassegnando un gioco come privato, lo si nasconde ovunque al di fuori della propria Libreria. La proprietà, lo stato del gioco, il tempo di gioco e le attività non saranno visibili ad altre persone.`,
  _ = `Stai visualizzando una nuova versione del carrello degli acquisti perché stai partecipando alla versione beta del client di Steam. <1>Lascia un feedback o segnala bug</1>`,
  _ = `Stiamo testando in versione beta questa nuova versione del carrello. <1>Lascia un feedback o segnala un bug</1>`,
  _ = `Non puoi programmare un dono così lontano nel tempo.`,
  _ = `Inserisci una data e ora valide.`,
  _ = `Si è verificato un problema durante la visualizzazione di questo articolo.`,
  _ = `Questo acquisto ti farà guadagnare %1$s carta collezionabile dell'evento "%2$s".`,
  _ = `Questo acquisto ti farà guadagnare %1$s carte collezionabili dell'evento "%2$s".`,
  _ = `Gli acquisti effettuati nel Negozio di Steam durante i saldi ti faranno ottenere le carte collezionabili dell'evento "%1$s".`,
  _ = `Riceverai le carte guadagnate anche se l'acquisto effettuato è un dono.`,
  _ = `Progresso per la prossima carta`,
  _ = `circa %1$s per carta`,
  _ = `Nota: gli articoli preacquistati non sono idonei a ricevere le ricompense delle carte collezionabili "%1$s". I seguenti articoli non danno diritto alle ricompense delle carte collezionabili:`,
  _ = `Richiesta di acquisto da %1$s`,
  _ = `Un acquisto per:`,
  _ = `Acquista come dono: %1$s`,
  _ = `Aggiungi un'altra copia di questo articolo al carrello`,
  _ = `Dichiarazione di conformità PSTI del Regno Unito`,
  _ = `Si è verificato un problema nell'aggiornamento del tuo carrello.`,
  _ = `Codice di errore: %1$s`,
  _ = `Paese`,
  _ = `Carrello salvato`,
  _ = `Questo è un carrello salvato. Si è verificato un errore durante il tuo ultimo tentativo di acquisto del carrello, quindi il tuo carrello (sconti inclusi) sarà salvato per %1$s ore mentre tenti di effettuare nuovamente il tuo acquisto.`,
  _ = `Copia opzioni dei doni da`,
  _ = `<1>Accedi</1> per selezionare amici di Steam`,
  _ = {
    language: _,
    Cart_Remove: _,
    Cart_Add: _,
    Cart_Verify: _,
    Cart_RemoveAll: _,
    Cart_Edit: _,
    Cart_Quantity: _,
    Cart_YourShoppingCart: _,
    Cart_YourShoppingCartLineItems: _,
    Cart_YourShoppingCartLineItems_Plural: _,
    Cart_EstimatedTotal: _,
    Cart_Note_SalesTax: _,
    Cart_PurchaseBtn: _,
    Cart_ContainsGiftCheckbox: _,
    Cart_Bradcrumb_Home: _,
    Cart_LineItemGift_Checkbox: _,
    Cart_IncludesItems: _,
    Cart_IncludesItems_Plural: _,
    Cart_SelectRecipient: _,
    Cart_EnterRecipientEmail: _,
    Cart_ChangeGiftRecipient: _,
    Cart_GiftRecipient_Label: _,
    Cart_GiftRecipientEmail_Label: _,
    Cart_GiftDelivery_Label: _,
    Cart_GiftDelivery_Reset: _,
    Cart_GiftDelivery_Now: _,
    Cart_GiftDelivery_Scheduled: _,
    Cart_GiftDelivery_ScheduleDelivery: _,
    Cart_GiftDelivery_From: `Da:`,
    Cart_GiftDelivery_Signature: _,
    Cart_GiftDelivery_AddSignature: _,
    Cart_GiftDelivery_Body: _,
    Cart_GiftDeliveryEmail_Warning1: _,
    Cart_GiftDeliveryEmail_Warning2: _,
    Cart_FamilyGift_Notice: _,
    Cart_GiftRecipientModal_Title: _,
    Cart_EditGiftDelivery: _,
    Cart_GiftRecipientModal_Save: _,
    Cart_GiftRecipientModal_Placeholder: _,
    Cart_GiftRecipientModal_OwnsGameLabel: _,
    Cart_GiftRecipientModal_OnWishlist: _,
    Cart_GiftRecipientModal_PartialOwnsLabel: _,
    Cart_GiftRecipientModal_PartialWishlistLabel: _,
    Cart_GiftOptions: _,
    Cart_GiftRecipientModal_IssueLoading: _,
    Cart_ContinueButton_Payment: _,
    Cart_ContinueButton_Gifts: _,
    Cart_ContinueButton_Login: _,
    Cart_DeclinePurchaseRequest: _,
    Cart_LineItemOptions_Myself: _,
    Cart_LineItemOptions_Gift: _,
    Cart_LineItemOptions_GiftForPersona: _,
    Cart_LineItemOptions_Privately: _,
    Cart_CountWidget: _,
    Cart_AddedToYourCart: _,
    Cart_UpdatedYourCart: _,
    Cart_ContinueShopping: _,
    Cart_ComingSoon: _,
    Cart_ViewMyCart: _,
    Cart_RequestPurchase: _,
    Cart_RequestPurchaseExplanation: _,
    Cart_RequestPurchaseNonGiftableItems: _,
    Cart_CouponModify_Change: _,
    Cart_CouponModify_Add: _,
    Cart_CouponAvailability: _,
    Cart_CouponAvailability_Plural: _,
    Cart_Coupons_Applied: _,
    Cart_Coupons_InUse: _,
    Cart_SelectCouponToApply: _,
    Cart_ShippingEstimate_DeliveryDate: _,
    Cart_ShippingEstimate_Range: _,
    Cart_ShippingEstimate_Delayed: _,
    Cart_ShippingEstimate_Standard: _,
    Cart_FooterNoticeHeader_MustFix: _,
    Cart_FooterNoticeHeader_Warning: _,
    Cart_CartLevelErrorNotice: _,
    Cart_CartLevelErrorMultiple: _,
    Cart_CartLevelErrorFormat: _,
    Cart_Error_AlreadyOwned_FootNote: _,
    Cart_Error_AlreadyOwned_LineItem_Game: _,
    Cart_Error_AlreadyOwned_LineItem: _,
    Cart_Error_AlreadyOwned_GiftLineItem_Game: _,
    Cart_Error_AlreadyOwned_GiftLineItem: _,
    Cart_Error_AlreadyOwned_GiftFootNote: _,
    Cart_Error_DuplicateApps_FootNote: _,
    Cart_Error_DuplicateApps_LineItem: _,
    Cart_Error_UnavailableCountry_FootNote: _,
    Cart_Error_UnavailableCountry_LineItem: _,
    Cart_Error_AdultContentRestricted_FootNote: _,
    Cart_Error_AdultContentRestricted_LineItem: _,
    Cart_Error_MasterSubscription_FootNote: _,
    Cart_Error_MasterSubscription_LineItem: _,
    Cart_Error_CouponIsExclusivePromo: _,
    Cart_Error_CouponIsInvalid: _,
    Cart_Error_CouponIsInvalidForItem: _,
    Cart_Error_TooManyInCart: _,
    Cart_Error_CommercialLicenseRestricted_FootNote: _,
    Cart_Error_CommercialLicenseRestricted_LineItem: _,
    Cart_Error_GiftRecipientInvalid: _,
    Cart_Error_MissingMustOwnApps_LineItem: _,
    Cart_Error_MissingMustOwnApps_GiftLineItem: _,
    Cart_Error_MissingMustOwnApps_FootNote: _,
    Cart_Error_MissingMustOwnApps_FootNoteGift: _,
    Cart_Error_ExistingBillingAgreement: _,
    Cart_Error_ExistingBillingAgreement_FootNote: _,
    Cart_Warning_AlreadyOwned_LineItem: _,
    Cart_Warning_ExtraCopies_LineItem: _,
    Cart_Warning_PriceChange_FootNote: _,
    Cart_Warning_PriceChange_LineItem: _,
    Cart_Warning_NoRefund_LineItem: _,
    Cart_Warning_RecipientHigherPrice: _,
    Cart_Warning_AvailableAtALowerPrice: _,
    Cart_Warning_GiftToNonFriend: _,
    Cart_Warning_GiftToNonFriend_Named: _,
    Cart_Warning_GiftToAccount_LoggedOut_Actionable: _,
    Cart_GifteeHint_Wishlist: _,
    PackageIncludesSubscriptionBySecond: _,
    PackageIncludesSubscriptionByMinute: _,
    PackageIncludesSubscriptionByHour: _,
    PackageIncludesSubscriptionByDay: _,
    PackageIncludesSubscriptionByWeek: _,
    PackageIncludesSubscriptionByMonth: _,
    PackageIncludesSubscriptionByYear: _,
    MultiLicenseIncludesSubscriptionBySecond: _,
    MultiLicenseIncludesSubscriptionByMinute: _,
    MultiLicenseIncludesSubscriptionByHour: _,
    MultiLicenseIncludesSubscriptionByDay: _,
    MultiLicenseIncludesSubscriptionByWeek: _,
    MultiLicenseIncludesSubscriptionByMonth: _,
    MultiLicenseeIncludesSubscriptionByYear: _,
    GameBillingPackageIncludesSubscriptionBySecond: _,
    GameBillingPackageIncludesSubscriptionByMinute: _,
    GameBillingPackageIncludesSubscriptionByHour: _,
    GameBillingPackageIncludesSubscriptionByDay: _,
    GameBillingPackageIncludesSubscriptionByWeek: _,
    GameBillingPackageIncludesSubscriptionByMonth: _,
    GameBillingPackageIncludesSubscriptionByYear: _,
    MicroTxnSubscriptionCostBySecond: _,
    MicroTxnSubscriptionCostByMinute: _,
    MicroTxnSubscriptionCostByHour: _,
    MicroTxnSubscriptionCostByDay: _,
    MicroTxnSubscriptionCostByWeek: _,
    MicroTxnSubscriptionCostByMonth: _,
    MicroTxnSubscriptionCostByYear: _,
    GameBillingAuthorizeSubscriptionBySecond: _,
    GameBillingAuthorizeSubscriptionByMinute: _,
    GameBillingAuthorizeSubscriptionByHour: _,
    GameBillingAuthorizeSubscriptionByDay: _,
    GameBillingAuthorizeSubscriptionByWeek: _,
    GameBillingAuthorizeSubscriptionByMonth: _,
    GameBillingAuthorizeSubscriptionByYear: _,
    PackageCostIncludesSubscriptionBySecond: _,
    PackageCostIncludesSubscriptionByMinute: _,
    PackageCostIncludesSubscriptionByHour: _,
    PackageCostIncludesSubscriptionByDay: _,
    PackageCostIncludesSubscriptionByWeek: _,
    PackageCostIncludesSubscriptionByMonth: _,
    PackageCostIncludesSubscriptionByYear: _,
    PackageWithDiscountCostIncludesSubscriptionBySecond: _,
    PackageWithDiscountCostIncludesSubscriptionByMinute: _,
    PackageWithDiscountCostIncludesSubscriptionByHour: _,
    PackageWithDiscountCostIncludesSubscriptionByDay: _,
    PackageWithDiscountCostIncludesSubscriptionByWeek: _,
    PackageWithDiscountCostIncludesSubscriptionByMonth: _,
    PackageWithDiscountCostIncludesSubscriptionByYear: _,
    GameBillingPackageCostIncludesSubscriptionBySecond: _,
    GameBillingPackageCostIncludesSubscriptionByMinute: _,
    GameBillingPackageCostIncludesSubscriptionByHour: _,
    GameBillingPackageCostIncludesSubscriptionByDay: _,
    GameBillingPackageCostIncludesSubscriptionByWeek: _,
    GameBillingPackageCostIncludesSubscriptionByMonth: _,
    GameBillingPackageCostIncludesSubscriptionByYear: _,
    MultiLicenseCostIncludesSubscriptionBySecond: _,
    MultiLicenseCostIncludesSubscriptionByMinute: _,
    MultiLicenseCostIncludesSubscriptionByHour: _,
    MultiLicenseCostIncludesSubscriptionByDay: _,
    MultiLicenseCostIncludesSubscriptionByWeek: _,
    MultiLicenseCostIncludesSubscriptionByMonth: _,
    MultiLicenseCostIncludesSubscriptionByYear: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionBySecond: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMinute: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByHour: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByDay: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByWeek: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByMonth: _,
    MultiLicenseWithDiscountCostIncludesSubscriptionByYear: _,
    Cart_Empty: _,
    Cart_Notice_SomeAppsPrivate: _,
    Cart_LineItemOptions_PrivateTooltip: _,
    Cart_BetaNotice: _,
    Cart_GenericBetaNotice: _,
    Cart_GiftScheduleError_TooFar: _,
    Cart_GiftScheduleError_InvalidDate: _,
    Cart_LineItem_ErrorBoundary: _,
    Cart_SaleCardDrops_EarnedMessage: _,
    Cart_SaleCardDrops_EarnedMessage_Plural: _,
    Cart_SaleCardDrops_Explanation: _,
    Cart_SaleCardDrops_Explanation_Gifts: _,
    Cart_SaleCardDrops_ProgressLabel: _,
    Cart_SaleCardDrops_CardCost: _,
    Cart_SaleCardDrops_PrepurchaseIneligible: _,
    Cart_PurchaseRequestTitle: _,
    Cart_PurchaseFor_Label: _,
    Cart_GiftForNotice: _,
    Cart_LineItem_Add_Tooltip: _,
    Cart_LineItem_Hardware_Compliance_Label: _,
    Cart_ErrorUpdating: _,
    Cart_ErrorCode: _,
    Cart_UserCountrySelector: _,
    Cart_Replay_SavedCart: _,
    Cart_Replay_Instructions: _,
    Cart_Gifting_CopyGiftOptionsFrom: _,
    Cart_Gifting_SignInToSelectFriends: _,
  };
export {
  _ as Cart_Add,
  _ as Cart_AddedToYourCart,
  _ as Cart_BetaNotice,
  _ as Cart_Bradcrumb_Home,
  _ as Cart_CartLevelErrorFormat,
  _ as Cart_CartLevelErrorMultiple,
  _ as Cart_CartLevelErrorNotice,
  _ as Cart_ChangeGiftRecipient,
  _ as Cart_ComingSoon,
  _ as Cart_ContainsGiftCheckbox,
  _ as Cart_ContinueButton_Gifts,
  _ as Cart_ContinueButton_Login,
  _ as Cart_ContinueButton_Payment,
  _ as Cart_ContinueShopping,
  _ as Cart_CountWidget,
  _ as Cart_CouponAvailability,
  _ as Cart_CouponAvailability_Plural,
  _ as Cart_CouponModify_Add,
  _ as Cart_CouponModify_Change,
  _ as Cart_Coupons_Applied,
  _ as Cart_Coupons_InUse,
  _ as Cart_DeclinePurchaseRequest,
  _ as Cart_Edit,
  _ as Cart_EditGiftDelivery,
  _ as Cart_Empty,
  _ as Cart_EnterRecipientEmail,
  _ as Cart_ErrorCode,
  _ as Cart_ErrorUpdating,
  _ as Cart_Error_AdultContentRestricted_FootNote,
  _ as Cart_Error_AdultContentRestricted_LineItem,
  _ as Cart_Error_AlreadyOwned_FootNote,
  _ as Cart_Error_AlreadyOwned_GiftFootNote,
  _ as Cart_Error_AlreadyOwned_GiftLineItem,
  _ as Cart_Error_AlreadyOwned_GiftLineItem_Game,
  _ as Cart_Error_AlreadyOwned_LineItem,
  _ as Cart_Error_AlreadyOwned_LineItem_Game,
  _ as Cart_Error_CommercialLicenseRestricted_FootNote,
  _ as Cart_Error_CommercialLicenseRestricted_LineItem,
  _ as Cart_Error_CouponIsExclusivePromo,
  _ as Cart_Error_CouponIsInvalid,
  _ as Cart_Error_CouponIsInvalidForItem,
  _ as Cart_Error_DuplicateApps_FootNote,
  _ as Cart_Error_DuplicateApps_LineItem,
  _ as Cart_Error_ExistingBillingAgreement,
  _ as Cart_Error_ExistingBillingAgreement_FootNote,
  _ as Cart_Error_GiftRecipientInvalid,
  _ as Cart_Error_MasterSubscription_FootNote,
  _ as Cart_Error_MasterSubscription_LineItem,
  _ as Cart_Error_MissingMustOwnApps_FootNote,
  _ as Cart_Error_MissingMustOwnApps_FootNoteGift,
  _ as Cart_Error_MissingMustOwnApps_GiftLineItem,
  _ as Cart_Error_MissingMustOwnApps_LineItem,
  _ as Cart_Error_TooManyInCart,
  _ as Cart_Error_UnavailableCountry_FootNote,
  _ as Cart_Error_UnavailableCountry_LineItem,
  _ as Cart_EstimatedTotal,
  _ as Cart_FamilyGift_Notice,
  _ as Cart_FooterNoticeHeader_MustFix,
  _ as Cart_FooterNoticeHeader_Warning,
  _ as Cart_GenericBetaNotice,
  _ as Cart_GiftDeliveryEmail_Warning1,
  _ as Cart_GiftDeliveryEmail_Warning2,
  _ as Cart_GiftDelivery_AddSignature,
  _ as Cart_GiftDelivery_Body,
  _ as Cart_GiftDelivery_From,
  _ as Cart_GiftDelivery_Label,
  _ as Cart_GiftDelivery_Now,
  _ as Cart_GiftDelivery_Reset,
  _ as Cart_GiftDelivery_ScheduleDelivery,
  _ as Cart_GiftDelivery_Scheduled,
  _ as Cart_GiftDelivery_Signature,
  _ as Cart_GiftForNotice,
  _ as Cart_GiftOptions,
  _ as Cart_GiftRecipientEmail_Label,
  _ as Cart_GiftRecipientModal_IssueLoading,
  _ as Cart_GiftRecipientModal_OnWishlist,
  _ as Cart_GiftRecipientModal_OwnsGameLabel,
  _ as Cart_GiftRecipientModal_PartialOwnsLabel,
  _ as Cart_GiftRecipientModal_PartialWishlistLabel,
  _ as Cart_GiftRecipientModal_Placeholder,
  _ as Cart_GiftRecipientModal_Save,
  _ as Cart_GiftRecipientModal_Title,
  _ as Cart_GiftRecipient_Label,
  _ as Cart_GiftScheduleError_InvalidDate,
  _ as Cart_GiftScheduleError_TooFar,
  _ as Cart_GifteeHint_Wishlist,
  _ as Cart_Gifting_CopyGiftOptionsFrom,
  _ as Cart_Gifting_SignInToSelectFriends,
  _ as Cart_IncludesItems,
  _ as Cart_IncludesItems_Plural,
  _ as Cart_LineItemGift_Checkbox,
  _ as Cart_LineItemOptions_Gift,
  _ as Cart_LineItemOptions_GiftForPersona,
  _ as Cart_LineItemOptions_Myself,
  _ as Cart_LineItemOptions_PrivateTooltip,
  _ as Cart_LineItemOptions_Privately,
  _ as Cart_LineItem_Add_Tooltip,
  _ as Cart_LineItem_ErrorBoundary,
  _ as Cart_LineItem_Hardware_Compliance_Label,
  _ as Cart_Note_SalesTax,
  _ as Cart_Notice_SomeAppsPrivate,
  _ as Cart_PurchaseBtn,
  _ as Cart_PurchaseFor_Label,
  _ as Cart_PurchaseRequestTitle,
  _ as Cart_Quantity,
  _ as Cart_Remove,
  _ as Cart_RemoveAll,
  _ as Cart_Replay_Instructions,
  _ as Cart_Replay_SavedCart,
  _ as Cart_RequestPurchase,
  _ as Cart_RequestPurchaseExplanation,
  _ as Cart_RequestPurchaseNonGiftableItems,
  _ as Cart_SaleCardDrops_CardCost,
  _ as Cart_SaleCardDrops_EarnedMessage,
  _ as Cart_SaleCardDrops_EarnedMessage_Plural,
  _ as Cart_SaleCardDrops_Explanation,
  _ as Cart_SaleCardDrops_Explanation_Gifts,
  _ as Cart_SaleCardDrops_PrepurchaseIneligible,
  _ as Cart_SaleCardDrops_ProgressLabel,
  _ as Cart_SelectCouponToApply,
  _ as Cart_SelectRecipient,
  _ as Cart_ShippingEstimate_Delayed,
  _ as Cart_ShippingEstimate_DeliveryDate,
  _ as Cart_ShippingEstimate_Range,
  _ as Cart_ShippingEstimate_Standard,
  _ as Cart_UpdatedYourCart,
  _ as Cart_UserCountrySelector,
  _ as Cart_Verify,
  _ as Cart_ViewMyCart,
  _ as Cart_Warning_AlreadyOwned_LineItem,
  _ as Cart_Warning_AvailableAtALowerPrice,
  _ as Cart_Warning_ExtraCopies_LineItem,
  _ as Cart_Warning_GiftToAccount_LoggedOut_Actionable,
  _ as Cart_Warning_GiftToNonFriend,
  _ as Cart_Warning_GiftToNonFriend_Named,
  _ as Cart_Warning_NoRefund_LineItem,
  _ as Cart_Warning_PriceChange_FootNote,
  _ as Cart_Warning_PriceChange_LineItem,
  _ as Cart_Warning_RecipientHigherPrice,
  _ as Cart_YourShoppingCart,
  _ as Cart_YourShoppingCartLineItems,
  _ as Cart_YourShoppingCartLineItems_Plural,
  _ as GameBillingAuthorizeSubscriptionByDay,
  _ as GameBillingAuthorizeSubscriptionByHour,
  _ as GameBillingAuthorizeSubscriptionByMinute,
  _ as GameBillingAuthorizeSubscriptionByMonth,
  _ as GameBillingAuthorizeSubscriptionBySecond,
  _ as GameBillingAuthorizeSubscriptionByWeek,
  _ as GameBillingAuthorizeSubscriptionByYear,
  _ as GameBillingPackageCostIncludesSubscriptionByDay,
  _ as GameBillingPackageCostIncludesSubscriptionByHour,
  _ as GameBillingPackageCostIncludesSubscriptionByMinute,
  _ as GameBillingPackageCostIncludesSubscriptionByMonth,
  _ as GameBillingPackageCostIncludesSubscriptionBySecond,
  _ as GameBillingPackageCostIncludesSubscriptionByWeek,
  _ as GameBillingPackageCostIncludesSubscriptionByYear,
  _ as GameBillingPackageIncludesSubscriptionByDay,
  _ as GameBillingPackageIncludesSubscriptionByHour,
  _ as GameBillingPackageIncludesSubscriptionByMinute,
  _ as GameBillingPackageIncludesSubscriptionByMonth,
  _ as GameBillingPackageIncludesSubscriptionBySecond,
  _ as GameBillingPackageIncludesSubscriptionByWeek,
  _ as GameBillingPackageIncludesSubscriptionByYear,
  _ as MicroTxnSubscriptionCostByDay,
  _ as MicroTxnSubscriptionCostByHour,
  _ as MicroTxnSubscriptionCostByMinute,
  _ as MicroTxnSubscriptionCostByMonth,
  _ as MicroTxnSubscriptionCostBySecond,
  _ as MicroTxnSubscriptionCostByWeek,
  _ as MicroTxnSubscriptionCostByYear,
  _ as MultiLicenseCostIncludesSubscriptionByDay,
  _ as MultiLicenseCostIncludesSubscriptionByHour,
  _ as MultiLicenseCostIncludesSubscriptionByMinute,
  _ as MultiLicenseCostIncludesSubscriptionByMonth,
  _ as MultiLicenseCostIncludesSubscriptionBySecond,
  _ as MultiLicenseCostIncludesSubscriptionByWeek,
  _ as MultiLicenseCostIncludesSubscriptionByYear,
  _ as MultiLicenseIncludesSubscriptionByDay,
  _ as MultiLicenseIncludesSubscriptionByHour,
  _ as MultiLicenseIncludesSubscriptionByMinute,
  _ as MultiLicenseIncludesSubscriptionByMonth,
  _ as MultiLicenseIncludesSubscriptionBySecond,
  _ as MultiLicenseIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByDay,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByHour,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMinute,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByMonth,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionBySecond,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByWeek,
  _ as MultiLicenseWithDiscountCostIncludesSubscriptionByYear,
  _ as MultiLicenseeIncludesSubscriptionByYear,
  _ as PackageCostIncludesSubscriptionByDay,
  _ as PackageCostIncludesSubscriptionByHour,
  _ as PackageCostIncludesSubscriptionByMinute,
  _ as PackageCostIncludesSubscriptionByMonth,
  _ as PackageCostIncludesSubscriptionBySecond,
  _ as PackageCostIncludesSubscriptionByWeek,
  _ as PackageCostIncludesSubscriptionByYear,
  _ as PackageIncludesSubscriptionByDay,
  _ as PackageIncludesSubscriptionByHour,
  _ as PackageIncludesSubscriptionByMinute,
  _ as PackageIncludesSubscriptionByMonth,
  _ as PackageIncludesSubscriptionBySecond,
  _ as PackageIncludesSubscriptionByWeek,
  _ as PackageIncludesSubscriptionByYear,
  _ as PackageWithDiscountCostIncludesSubscriptionByDay,
  _ as PackageWithDiscountCostIncludesSubscriptionByHour,
  _ as PackageWithDiscountCostIncludesSubscriptionByMinute,
  _ as PackageWithDiscountCostIncludesSubscriptionByMonth,
  _ as PackageWithDiscountCostIncludesSubscriptionBySecond,
  _ as PackageWithDiscountCostIncludesSubscriptionByWeek,
  _ as PackageWithDiscountCostIncludesSubscriptionByYear,
  _ as default,
  _ as language,
};
