var _ = `© %1$s Valve Corporation. Kaikki oikeudet pidätetään. Kaikki tavaramerkit ovat omistajiensa omaisuutta Yhdysvalloissa ja kaikkialla maailmassa.<br>Kaikki hinnat sisältävät asiaankuuluvan arvonlisäveron.`,
  _ = `STEAM`,
  _ = `VALVE`,
  _ = `JURIDISET TIEDOT`,
  _ = `LISÄTIETOA`,
  _ = `Tietoa Steamistä`,
  _ = `Steam-tilaussopimus`,
  _ = `Steamworks`,
  _ = `Steam-jakelu`,
  _ = `Lahjakortit`,
  _ = `Tietoa Valvesta`,
  _ = `Työpaikat`,
  _ = `Laitteisto`,
  _ = `Kierrätys`,
  _ = `Yksityisyys`,
  _ = `Helppokäyttötoiminnot`,
  _ = `Ilmoitukset ja käytännöt`,
  _ = `Evästeet`,
  _ = `Hyvitykset`,
  _ = `Hanki Steam`,
  _ = `Mobiilisovellukset`,
  _ = `Asiakastuki`,
  _ = `Oma tili`,
  _ = `Näytä mobiilisivusto`,
  _ = {
    footer_legal_notice: _,
    footer_link_header_steam: _,
    footer_link_header_valve: _,
    footer_link_header_legal: _,
    footer_link_header_more: _,
    footer_link_about_steam: _,
    footer_link_steam_ssa: _,
    footer_link_steamworks: _,
    footer_link_steam_distribution: _,
    footer_link_gift_cards: _,
    footer_link_about_valve: _,
    footer_link_jobs: _,
    footer_link_hardware: _,
    footer_link_recycling: _,
    footer_link_privacy: _,
    footer_link_accessibility: _,
    footer_link_notices_and_policies: _,
    footer_link_cookies: _,
    footer_link_refunds: _,
    footer_link_get_steam: _,
    footer_link_get_mobile_apps: _,
    footer_link_get_support: _,
    footer_link_my_account: _,
    footer_view_mobile_website: _,
  };
export {
  _ as default,
  _ as footer_legal_notice,
  _ as footer_link_about_steam,
  _ as footer_link_about_valve,
  _ as footer_link_accessibility,
  _ as footer_link_cookies,
  _ as footer_link_get_mobile_apps,
  _ as footer_link_get_steam,
  _ as footer_link_get_support,
  _ as footer_link_gift_cards,
  _ as footer_link_hardware,
  _ as footer_link_header_legal,
  _ as footer_link_header_more,
  _ as footer_link_header_steam,
  _ as footer_link_header_valve,
  _ as footer_link_jobs,
  _ as footer_link_my_account,
  _ as footer_link_notices_and_policies,
  _ as footer_link_privacy,
  _ as footer_link_recycling,
  _ as footer_link_refunds,
  _ as footer_link_steam_distribution,
  _ as footer_link_steam_ssa,
  _ as footer_link_steamworks,
  _ as footer_view_mobile_website,
};
