var _ = `论坛帖子`,
  _ = `综合讨论`,
  _ = `已举报的帖子`,
  _ = `创意工坊讨论`,
  _ = `交易`,
  _ = `活动和公告`,
  _ = `1 个举报`,
  _ = `%1$s 个举报`,
  _ = `1 个对象`,
  _ = `%1$s 个对象`,
  _ = `关于 %2$s的 %1$s`,
  _ = `主题中针对 %2$s的 %1$s：%3$s`,
  _ = `1 个举报`,
  _ = `%1$s 个举报`,
  _ = `1 个对象`,
  _ = `%1$s 个对象`,
  _ = `Steam 社区`,
  _ = `Steam 社区 :: 错误`,
  _ = `错误`,
  _ = `未知错误`,
  _ = `游戏`,
  _ = `Steam 社区 :: %1$s :: 游戏`,
  _ = `搜索 - Steam 社区市场`,
  _ = `%1$s - Steam 社区市场`,
  _ = `市场物品 - Steam 社区市场`,
  _ = `Steam 社区市场`,
  _ = `找不到个人资料`,
  _ = `载入用户愿望单失败`,
  _ = `您最近作出的请求太多了。请稍候，然后再重试您的请求。`,
  _ = `正在载入`,
  _ = `已完成 %1$s%`,
  _ = `已暂停 - 已完成 %1$s%`,
  _ = `已下载 %1$s / %2$s`,
  _ = `成就`,
  _ = `估计剩余时间：%1$s`,
  _ = `%1$s/%2$s`,
  _ = `正在卸载`,
  _ = `更新`,
  _ = `卸载`,
  _ = `下载`,
  _ = `暂停`,
  _ = `继续`,
  _ = `正在卸载`,
  _ = `取消`,
  _ = `查看我对此内容的隐私设置`,
  _ = `寻找游戏`,
  _ = `仅显示双方都拥有的游戏`,
  _ = `游戏时间`,
  _ = `名称`,
  _ = `成就完成情况`,
  _ = `总游戏时间`,
  _ = `最后运行日期`,
  _ = `过去两周`,
  _ = `游戏信息及相关链接`,
  _ = `远程下载`,
  _ = `远程下载至：%1$s`,
  _ = `远程下载状态：%1$s`,
  _ = `无法访问您的 PC`,
  _ = `要想远程下载游戏至您的 Steam 客户端，您的 PC 必须处于唤醒状态并连接至互联网，且您必须已登录。`,
  _ = `阅读常见问题。`,
  _ = `%1$s%2$s`,
  _ = `了解更多`,
  _ = `远程下载不可用`,
  _ = `您希望卸载 %1$s 吗？该游戏仍然在您的游戏库中，但未来进行游戏前，首先需要重新下载其所有内容。`,
  _ = `%1$s |“%2$s”`,
  _ = `最近玩过 %1$s`,
  _ = `所有游戏 %1$s`,
  _ = `完美通关游戏 %1$s`,
  _ = `评测 %1$s`,
  _ = `已关注 %1$s`,
  _ = `愿望单`,
  _ = `获得了所有可能的成就`,
  _ = `在这里，您将找到自己的“完美通关游戏”，也就是您获得了所有成就的游戏。`,
  _ = `%1$s% 的玩家拥有此成就`,
  _ = `商店页面`,
  _ = `论坛`,
  _ = `组`,
  _ = `官方网站`,
  _ = `新闻`,
  _ = `我的成就`,
  _ = `%1$s 的成就`,
  _ = `%1$s 的统计数据`,
  _ = `%1$s 的个人游戏数据`,
  _ = `我的排行榜`,
  _ = `%1$s 的排行榜`,
  _ = `全球成就`,
  _ = `全球排行榜`,
  _ = `游戏统计数据`,
  _ = `游戏内容`,
  _ = `我的游戏统计数据`,
  _ = `我的游戏内容`,
  _ = `游戏链接`,
  _ = `我的截图 %1$s`,
  _ = `%1$s 的截图 %2$s`,
  _ = `玩此游戏的好友 %1$s`,
  _ = `我的集换式卡牌 %1$s`,
  _ = `我的评测`,
  _ = `%1$s 的评测`,
  _ = `社区中心`,
  _ = `我的笔记`,
  _ = `%1$s 小时`,
  _ = `%1$s 分钟`,
  _ = `标记为私密`,
  _ = `取消私密标记`,
  _ = `将此游戏标记为私密，并向我的好友隐藏`,
  _ = `© Valve Corporation。保留所有权利。所有商标均为其在美国及其他国家/地区的各自持有者所有。`,
  _ = `本网站上的部分地理空间数据由 %1$s 提供。`,
  _ = `隐私政策`,
  _ = `法律信息`,
  _ = `Steam 订户协议`,
  _ = `退款`,
  _ = `Cookie`,
  _ = `无障碍`,
  _ = `当前封禁`,
  _ = `社区消息`,
  _ = `已举报的内容`,
  _ = `已被管理员处理的内容`,
  _ = `以下是您举报的 Steam 上违反 Steam 指引的内容`,
  _ = `以下是您在 Steam 上发布且已被管理员处理的内容的列表。`,
  _ = `最后更新于 %1$s`,
  _ = `下载`,
  _ = `公开留言（%1$s）`,
  _ = `开发者留言（%1$s）`,
  _ = `这是一个仅对此项目贡献者和游戏开发者可见的私密讨论串。`,
  _ = `注意：与游戏开发者（比如 Valve）沟通不能保证您提交的内容会被选中。`,
  _ = `尺寸`,
  _ = `查看所有截图`,
  _ = `查看所有艺术作品`,
  _ = `查看所有视频`,
  _ = `说明`,
  _ = `编辑说明`,
  _ = `添加剧透标签`,
  _ = `移除剧透标签`,
  _ = `剧透标签可以让您的好友以及社区选择不查看此内容，以避免游戏剧透。`,
  _ = `（剧透标签将于四个星期后失效。）`,
  _ = `此截图中的用户：`,
  _ = `此截图中的创意工坊项目：`,
  _ = `将您的被标记状态从此截图中移除`,
  _ = `地址`,
  _ = `标签：`,
  _ = `正在载入指南`,
  _ = `订阅后就能在 %1$s 中使用此指南`,
  _ = `指南索引`,
  _ = `总览`,
  _ = `留言`,
  _ = `编辑`,
  _ = `{链接已删除}`,
  _ = `此处链接的 URL 已被我们的过滤器移除，这通常是为了防止网络钓鱼和恶意软件攻击。`,
  _ = `指南内容`,
  _ = `定义您的指南框架及指南中的章节名称。您可以拖动章节以重新排序。`,
  _ = `必须完成此章节才能发布指南。`,
  _ = `创建您的目录`,
  _ = `添加一个章节`,
  _ = `（新章节，尚未起标题）`,
  _ = `编辑此章节`,
  _ = `删除此章节`,
  _ = `您确定要移除此章节吗？此操作无法撤消。`,
  _ = `图片`,
  _ = `选择并上传您希望在指南中用作参考的图片。在此上传所有必要的图片，它们将在您编辑指南的各个章节时供您轻松选择。`,
  _ = `为您的指南上传图片`,
  _ = `添加贡献者`,
  _ = `在这里，您可以添加好友为贡献者，授予他们编辑您指南的权限。`,
  _ = `添加好友为贡献者`,
  _ = `添加一名贡献者`,
  _ = `预览指南`,
  _ = `编辑指南章节`,
  _ = `章节标题`,
  _ = `章节内容`,
  _ = `编辑`,
  _ = `预览`,
  _ = `查看差异`,
  _ = `自从上次保存之后所做的文本变更将这样显示：`,
  _ = `这样显示的文本是新增的`,
  _ = `这样显示的文本是被删除的`,
  _ = `对此章节所做的变更尚未保存。`,
  _ = `对此章节所做的变更尚未保存。您确定要放弃这些变更吗？`,
  _ = `最后保存于 `,
  _ = `保存`,
  _ = `取消 `,
  _ = `截图`,
  _ = `视频`,
  _ = `点击下方的图片以将其添加至您的指南中`,
  _ = `点击下方的截图以将其添加至您的指南中`,
  _ = `点击下方的视频以将其添加至您的指南中`,
  _ = `图片插入选项`,
  _ = `尺寸`,
  _ = `半宽`,
  _ = `全宽`,
  _ = `原尺寸`,
  _ = `对齐方式`,
  _ = `左对齐`,
  _ = `右对齐`,
  _ = `内嵌`,
  _ = `左对齐`,
  _ = `右对齐`,
  _ = `全宽`,
  _ = `插入`,
  _ = `插入 YouTube™ 视频`,
  _ = `输入 YouTube™ 视频 URL`,
  _ = `引用文本`,
  _ = `防剧透文本`,
  _ = `请输入标题`,
  _ = `前往您的指南`,
  _ = ``,
  _ = `创意工坊项目：`,
  _ = `以及其他 %1$s 个`,
  _ = `查看留言与详情`,
  _ = `查看 %1$s 条留言及详情`,
  _ = `截图`,
  _ = `艺术作品`,
  _ = `视频`,
  _ = `创意工坊项目`,
  _ = `周边产品`,
  _ = `合集`,
  _ = `指南`,
  _ = `创意工坊项目`,
  _ = `创意工坊合集`,
  _ = `指南`,
  _ = `收藏`,
  _ = `已订阅项目`,
  _ = `曾玩过`,
  _ = `按游戏筛选`,
  _ = `所有游戏`,
  _ = `选择一款游戏`,
  _ = `项目`,
  _ = `已收藏`,
  _ = `已订阅项目`,
  _ = `创建日期`,
  _ = `依字母顺序`,
  _ = `更新日期`,
  _ = `订阅日期`,
  _ = `收藏日期`,
  _ = `显示带有以下全部已选标签的项目：`,
  _ = `作者：`,
  _ = `正在显示第 %1$s - %2$s 项，共 %3$s 项条目`,
  _ = `未找到符合 %1$s 的文件。`,
  _ = `正在显示第 %1$s - %2$s 项，共 %3$s 项条目`,
  _ = `最后更新时间 %1$s`,
  _ = `添加于 %1$s`,
  _ = `此项目已从您的收藏列表中移除：`,
  _ = `订阅时间 %1$s`,
  _ = `您已取消订阅下列项目：`,
  _ = `万岁！您在 Steam 创意工坊中的部分内容被选用了！`,
  _ = `在出去庆祝之前，请输入您的<a href="%1$s">支付信息</a>，以便我们知道该支付给谁！`,
  _ = `尝试验证您的支付信息时出现问题。请审核您的<a href="%1$s">支付信息</a>并相应更新。`,
  _ = `您已被标记为以下 Steam 创意工坊项目的贡献者`,
  _ = `请审核并接受以下项目的作者署名`,
  _ = `百分比：`,
  _ = `您的创意工坊`,
  _ = `关注此用户即可看到其在 Steam 创意工坊发布的新 Steam 指南、创建的新合集或发布的项目。`,
  _ = `关注您的 Steam 用户可以看到您在 Steam 创意工坊发布的新 Steam 指南、创建的新合集或发布的项目。`,
  _ = `名关注者`,
  _ = `名关注者`,
  _ = `关注 %1$s`,
  _ = `正在关注 %1$s`,
  _ = `取消关注 %1$s`,
  _ = `查看您的收入`,
  _ = `来自您创意工坊项目的销售收入`,
  _ = `输入或更新您的支付信息`,
  _ = `查看法律协议`,
  _ = `取消全部订阅`,
  _ = `要取消全部订阅吗？`,
  _ = `您确定要移除全部订阅吗？<br><br>此操作无法撤销！`,
  _ = `您确定要移除有关 %1$s 的全部订阅吗？<br><br>此操作无法撤销！`,
  _ = `保存至合集`,
  _ = `将订阅保存至合集`,
  _ = `您想将自己的订阅保存至新的合集还是已有合集？`,
  _ = `新合集`,
  _ = `请输入此合集的名称：`,
  _ = `已有合集`,
  _ = `选择要覆盖的合集：`,
  _ = `您没有任何合集。是否创建新的合集？`,
  _ = `管理员标签`,
  _ = `Steam 指南`,
  _ = `集成式指南`,
  _ = `英雄出装`,
  _ = `经过专门集成的指南，让您边学边玩`,
  _ = `专门与 %1$s 集成的指南`,
  _ = `热门类别`,
  _ = `集成式指南`,
  _ = `您的收藏`,
  _ = `热门的 Steam 指南`,
  _ = `书面指南、参考以及攻略`,
  _ = `查看全部（%1$s）`,
  _ = `%1$s 篇指南`,
  _ = `%1$s 篇指南`,
  _ = `您撰写的指南`,
  _ = `关于指南的更多信息`,
  _ = `点击这里来了解更多关于 Steam 指南的信息`,
  _ = `浏览：`,
  _ = `主页`,
  _ = `创建指南`,
  _ = `如果您希望创建指南，首先需要购买 %1$s。`,
  _ = `成为给本游戏创作指南的第一人！`,
  _ = `展现您的专业技能，或是帮助那些可能无法通关的玩家。`,
  _ = `创建一份攻略、揭开游戏秘密，或是针对特定地图提出最佳战略。`,
  _ = `浏览玩家为此游戏创作的指南并为其评分。也可以创建您自己的指南，和社区分享您的诀窍。`,
  _ = `创建自己的指南`,
  _ = `截图`,
  _ = `艺术作品`,
  _ = `视频`,
  _ = `显示第 %1$s - %2$s 页，共 %3$s 页`,
  _ = `返回顶部`,
  _ = `正在查看`,
  _ = `图片墙`,
  _ = `网格视图`,
  _ = `最热门`,
  _ = `最新文件优先`,
  _ = `最旧文件优先`,
  _ = `您所有的截图`,
  _ = `您的公开截图`,
  _ = `您的仅限好友截图`,
  _ = `您的私密截图`,
  _ = `您的非公开截图`,
  _ = `您所有的艺术作品`,
  _ = `您的公开艺术作品`,
  _ = `您的仅限好友艺术作品`,
  _ = `您的私密艺术作品`,
  _ = `您的非公开艺术作品`,
  _ = `您所有的视频`,
  _ = `您的公开视频`,
  _ = `您的仅限好友视频`,
  _ = `您的私密视频`,
  _ = `您的非公开视频`,
  _ = `管理截图`,
  _ = `管理艺术作品`,
  _ = `管理视频`,
  _ = `请选择您想要进行操作的截图。`,
  _ = `请在下面选择您想要进行操作的艺术作品。`,
  _ = `请选择您想要进行操作的视频。`,
  _ = `取消`,
  _ = `从 YouTube 添加视频`,
  _ = `链接 YouTube 帐户`,
  _ = `取消链接 YouTube 帐户`,
  _ = `取消链接`,
  _ = `您确定要取消链接您的 YouTube 帐户吗？`,
  _ = `Steam 将如何使用我的 YouTube 数据？`,
  _ = `将您的 YouTube 帐户链接到 Steam 将使用 YouTube API 服务。使用 YouTube 并将您的 YouTube 帐户链接到您的 Steam 个人资料即表明您同意接受 %1$s和 %2$s的约束。`,
  _ = `Steam 使用 YouTube API 服务来验证您的 YouTube 帐户并访问您已发布到 YouTube 的视频的列表。当您将 YouTube 帐户链接到 Steam 时，Steam 会在您的浏览器或 Steam 客户端中放置 cookie，其中包含您帐户的 YouTube 验证令牌。此 cookie 会在 30 天后过期。当 Steam 访问您 YouTube 帐户中已发布视频的列表时，这些数据仅用于在 Steam 中向您显示该列表。`,
  _ = `当您将自己 YouTube 帐户中的视频发布到 Steam 时，Steam 将仅存储在 Steam 上显示视频所需的信息，包括视频 ID 和视频的 YouTube 帐户 ID。这些数据将仅用于在 Steam 上显示视频以及在 Steam 上进行内容管理。`,
  _ = `您可用通过 %2$s撤销 Steam 对您%1$s的访问权限。`,
  _ = `YouTube 服务条款`,
  _ = `Google 隐私权政策`,
  _ = `已授权数据`,
  _ = `Google 安全设置页面`,
  _ = `您的视频。在 Steam 上分享。`,
  _ = `与您的好分享您最棒的游戏时刻。上传由您创作的精彩高光片段、见解深刻的评测、大有助益的教程点拨亦或是由游戏激发灵感的优秀杰作。`,
  _ = `1. 将您的 YouTube™ 帐户链接至自己的 Steam 个人资料。`,
  _ = `2. 选择您想要添加进您个人资料的视频。`,
  _ = `3. 与您的 Steam 好友分享，让他们赞叹不已。`,
  _ = `访问您的 YouTube 视频`,
  _ = `您当前已链接至 YouTube 帐户 %1$s。`,
  _ = `取消此帐户的链接即可链接另一个帐户。`,
  _ = `取消此帐户的链接`,
  _ = `继续使用这个帐户`,
  _ = `已成功链接您的 YouTube 帐户`,
  _ = `已成功添加 1 个视频`,
  _ = `已成功添加 %1$s 个视频`,
  _ = `您的 YouTube 合集中没有任何视频可供选择。`,
  _ = `您只能添加可见性为公开并允许嵌入的 YouTube 视频，且视频要在用您的用户名进行搜索时出现。如果您刚刚把一个视频设置为公开以便链接您的帐户，YouTube 可能需要一段时间来编排索引才能让它显示在搜索结果中。`,
  _ = `您当前已将 YouTube 帐户 %1$s 链接至 Steam。`,
  _ = `点击此处来更换 YouTube 帐户`,
  _ = `更换帐户`,
  _ = `1. 选择要添加的视频。`,
  _ = `帐户 %1$s 中有 1 个可用视频`,
  _ = `显示以下帐户最新的 %1$s 个可用视频：%2$s`,
  _ = `2. 将视频与游戏关联。`,
  _ = `在您从左边选取视频之后。（可选）`,
  _ = `- 无 / 其他（在下面详细说明）-`,
  _ = `其他 / 非公开`,
  _ = `3. 将其添加至您的个人资料。`,
  _ = `添加视频`,
  _ = `注意：如果要从您的 YouTube 帐户添加视频，其可见性必须被设置为公开并且允许嵌入。如果您刚刚添加了一个视频到您的 YouTube 帐户但没有在列表中看到，请尝试点击下面的按钮刷新。`,
  _ = `刷新 YouTube 视频列表`,
  _ = `4. 完成。`,
  _ = `完成后，请点击“完成”，即可在您的个人资料页面看到视频。`,
  _ = `完成`,
  _ = `访问视频源时出现问题，请重试。`,
  _ = `上传艺术作品`,
  _ = `上传截图…`,
  _ = `变更为公开`,
  _ = `变更为仅限好友`,
  _ = `变更为私密`,
  _ = `变更为不公开`,
  _ = `删除`,
  _ = `全选`,
  _ = `完成`,
  _ = `是否删除这些截图？`,
  _ = `更新隐私设置`,
  _ = `这将从 Steam 云中删除 %1$s。您要继续吗？`,
  _ = `此操作将会把 %1$s的可见性更新为“%2$s”。您要继续吗？`,
  _ = `继续`,
  _ = `取消`,
  _ = `哎呀！`,
  _ = `没有被选中的截图。`,
  _ = `勾选缩略图一角的复选框选择要删除的项目。`,
  _ = `确定`,
  _ = `可见性更新失败`,
  _ = `您尝试把可见性设置为“公开”或“仅限好友”的一张或多张截图无法更新。在 Steam 社区上未公开推出的游戏的截图不能与别人分享，仅能供自己查看。`,
  _ = `可能包含剧透。`,
  _ = `在此悬停鼠标即可显示图片。`,
  _ = `未找到符合条件的截图。`,
  _ = `%1$s 没有截图可供您查看。`,
  _ = `您未收藏任何截图。`,
  _ = `%1$s 没有收藏截图可供您查看。`,
  _ = `您当前没有艺术作品存储在 Steam 云中。想要上传艺术作品，进入相关游戏中心的“艺术作品”选项卡，可以在右上角找到“上传艺术作品”按钮。或者点击下方的“上传艺术作品”按钮。`,
  _ = `%1$s 没有艺术作品可供您查看。`,
  _ = `您未收藏任何艺术作品。`,
  _ = `%1$s 没有收藏艺术作品可供您查看。`,
  _ = `未找到符合条件的视频。`,
  _ = `%1$s 没有视频可供您查看。`,
  _ = `您未收藏任何视频。`,
  _ = `%1$s 没有收藏视频可供您查看。`,
  _ = `您尚未有设置为此可见性的截图。`,
  _ = `Steam 使得截取和分享您喜爱游戏的截图变得更容易。`,
  _ = `在游玩任何运行 Steam 叠加界面的游戏时，按下热键（默认 F12）即可截图。然后把它们发布到您的 Steam 社区个人资料页面，或者在 Facebook、Twitter 和 Reddit 上将它们分享给您的好友。`,
  _ = `有了 1GB 的 Steam 云个人储存空间，您可以上传数以千计的截图来向好友展示自己的最佳时刻。如果您更希望独自欣赏，也可以把它们设置为私密。`,
  _ = `由 %s 共享`,
  _ = `%1$s 的收藏`,
  _ = {
    Moderation_SubjectTypeName_ForumPost: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    moderation_claim_report_count: _,
    moderation_claim_report_count_Plural: _,
    moderation_claim_subject_count: _,
    moderation_claim_subject_count_Plural: _,
    moderation_claim_n_reports_on_m_subjects: _,
    moderation_forumpost_summary: _,
    moderation_forumpost_summary_reports_fragment: _,
    moderation_forumpost_summary_reports_fragment_Plural: _,
    moderation_forumpost_summary_subjects_fragment: _,
    moderation_forumpost_summary_subjects_fragment_Plural: _,
    community_title: _,
    community_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    profile_games_list: _,
    profile_games_list_title: _,
    Market_Search_Title: _,
    Market_Item_Title: _,
    Market_Item_GenericTitle: _,
    Market_GenericTitle: _,
    profile_error_profilenotfound: _,
    profile_games_list_error_loadfailed: _,
    Error_RateLimited: _,
    Loading: _,
    GamesList_Header_Downloading: _,
    GamesList_Header_Paused: _,
    GamesList_Header_DownloadBytes: _,
    GamesList_Header_Achievements: _,
    GamesList_TimeRemaining: _,
    GamesList_Achievement_Fraction: _,
    GamesList_Uninstalling: _,
    GamesList_Button_UpdateRequired: _,
    GamesList_Button_Uninstall: _,
    GamesList_Button_Download: _,
    GamesList_Button_Pause: _,
    GamesList_Button_Resume: _,
    GamesList_Button_Uninstalling: _,
    GamesList_Button_Cancel: _,
    GamesList_PrivacySettings_Tooltip: _,
    GamesList_Filter_Placeholder: _,
    GamesList_Filter_BothOwned: _,
    GamesList_Sort_HoursPlayed: _,
    GamesList_Sort_Name: _,
    GamesList_Sort_AchievementCompletion: _,
    GamesList_Header_TotalPlayed: _,
    GamesList_Header_LastPlayed: _,
    GamesList_Header_TwoWeeks: _,
    GamesList_MenuLabel_GameInfo: _,
    GamesList_MenuLabel_RemoteDownload: _,
    GamesList_Header_RemoteDownload: _,
    GamesList_Header_RemoteDownloadStatus: _,
    GamesList_RemoteDownload_NoConnection: _,
    GamesList_RemoteDownload_Help: _,
    GamesList_RemoteDownload_ReadTheFAQ: _,
    GamesList_RemoteDownload_Info: _,
    GamesList_RemoteDownload_LearnMore: _,
    GamesList_RemoteDownload_NoRemoteControl: _,
    GamesList_RemoteDownload_UninstallConfirm: _,
    GamesList_Client_Indicator: _,
    GamesList_Tab_RecentlyPlayed: _,
    GamesList_Tab_AllGames: _,
    GamesList_Tab_PerfectGames: _,
    GamesList_Tab_Reviews: _,
    GamesList_Tab_Followed: _,
    GamesList_Tab_Wishlist: _,
    Perfect_Game_Description: _,
    GamesList_PerfectGames_Description: _,
    GamesList_Achievement_Unlock_Percentage: _,
    Community_StorePage: _,
    Community_Forums: _,
    Community_Groups: `组`,
    Community_OfficialWebsite: _,
    Community_News: _,
    Community_UsersAchievementsFirstPerson: _,
    Community_UsersAchievements: _,
    Community_UsersStats: _,
    Community_GamePersonalData: _,
    Community_UsersLeaderboardsFirstPerson: _,
    Community_UsersLeaderboards: _,
    Community_GlobalAchievements: _,
    Community_GlobalLeaderboards: _,
    Community_GameStats: _,
    Community_GameContent: _,
    Community_GameStatsFirstPerson: _,
    Community_GameContentFirstPerson: _,
    Community_GameLinks: _,
    Community_ScreenshotsMenuItemFirstPerson: _,
    Community_ScreenshotsMenuItemThirdPerson: _,
    Community_FriendsWhoPlayMenuItemFirstPerson: _,
    Community_TradingCardsMenuItemFirstPerson: _,
    Community_ReviewMenuItemFirstPerson: _,
    Community_ReviewMenuItemThirdPerson: _,
    Community_GameHubMenuItem: _,
    Community_GameNotesFirstPerson: _,
    Playtime_Hours: _,
    Playtime_Minutes: _,
    AppPrivacy_MarkAsPrivate: _,
    AppPrivacy_UnmarkAsPrivate: _,
    AppPrivacy_Explanation: _,
    footer_legal_notice: _,
    footer_geodata_notice: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_accessibility: _,
    profiletabs_currentbans: _,
    profiletabs_communitymessages: _,
    profiletabs_reportedcontent: _,
    profiletabs_moderatedcontent: _,
    reportedcontent_description: _,
    moderatedcontent_description: _,
    reportedcontent_lastupdated: _,
    SharedFiles_ItemDownload: _,
    SharedFiles_PublicComments: _,
    SharedFiles_DeveloperComments: _,
    Workshop_DeveloperThreadDesc: _,
    Workshop_DeveloperThreadDisclaimerText: _,
    Workshop_ImageSize: _,
    SharedFiles_Media_ViewAppScreenshots: _,
    SharedFiles_Media_ViewAppFanArt: _,
    SharedFiles_Media_ViewAppVideos: _,
    SharedFiles_ItemEditText_Text_Caption: _,
    SharedFiles_OwnerControl_EditCaption: _,
    SharedFiles_AddSpoilerTag: _,
    SharedFiles_RemoveSpoilerTag: _,
    SharedFiles_SpoilerTagInstructions: _,
    SharedFiles_SpoilerTagsExpire: _,
    SharedFiles_Stats_TaggedUsers: _,
    SharedFiles_Stats_TaggedWorkshopItems: _,
    SharedFiles_RemoveSelfTag_Tooltip: _,
    Screenshots_Location: _,
    SharedFiles_Tags: _,
    SharedFiles_WaitingForIntegratedGuide: _,
    Workshop_Subscribe_IntegratedGuide: _,
    SharedFiles_Guide_Index: _,
    SharedFiles_Guide_Overview: _,
    SharedFiles_Guide_Comments: _,
    SharedFiles_Item_Edit_Link: _,
    Community_RemoveLink_BeWary: _,
    Community_RemoveLink_Tooltip: _,
    SharedFiles_ManageGuide_Contents: _,
    SharedFiles_ManageGuide_Contents_Desc: _,
    SharedFiles_ManageGuide_Required: _,
    SharedFiles_ManageGuide_NoSubSections: _,
    SharedFiles_ManageGuide_AddSection: _,
    SharedFiles_ManageGuide_NoSectionTitle: _,
    SharedFiles_ManageGuide_EditThisSection: _,
    SharedFiles_ManageGuide_DeleteThisSection: _,
    SharedFiles_ManageGuide_RemoveSectionConfirm: _,
    SharedFiles_ManageGuide_Images: _,
    SharedFiles_ManageGuide_Images_Desc: _,
    SharedFiles_ManageGuide_NoPreviewImages: _,
    SharedFiles_ManageGuide_Contributors: _,
    SharedFiles_ManageGuide_Contributors_Desc: _,
    SharedFiles_ManageGuide_NoContributors: _,
    SharedFiles_ManageGuide_AddContributor: _,
    SharedFiles_ManageGuide_Preview: _,
    SharedFiles_ManageGuide_EditSubSection: _,
    SharedFiles_ManageGuide_SubSectionTitle: _,
    SharedFiles_ManageGuide_SubSectionContents: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Edit: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Preview: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Changes: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Desc: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Insert: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Delete: _,
    SharedFiles_ManageGuide_SubSectionContentChanged: _,
    SharedFiles_ManageGuide_SubSectionContentChanged_CancelConfirm: _,
    SharedFiles_ManageGuide_SubSectionContentSaved: _,
    SharedFiles_ManageGuide_Save: _,
    SharedFiles_ManageGuide_Cancel: _,
    SharedFiles_ManageGuide_Screenshots: _,
    SharedFiles_ManageGuide_Videos: _,
    SharedFiles_ManageGuide_SubImages: _,
    SharedFiles_ManageGuide_SubScreenshots: _,
    SharedFiles_ManageGuide_SubVideos: _,
    SharedFiles_ManageGuide_ImageInsertionOptions: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_Size: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeThumb: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeFull: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeOriginal: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_Layout: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutLeft: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutRight: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutInline: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Left: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Right: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Full: _,
    SharedFiles_ManageGuide_InsertImage: _,
    SharedFiles_ManageGuide_InsertYouTubeVideo: _,
    SharedFiles_ManageGuide_PromptYouTubeUrl: _,
    Discussions_FormattingHelp_Quote: _,
    Discussions_FormattingHelp_Spoiler: _,
    SharedFiles_ItemEditText_ErrorNoTitle: _,
    SharedFiles_OwnerControl_BackGuide: _,
    empty_no_comma_following: ``,
    SharedFiles_WorkshopItemsTagged: _,
    SharedFiles_And_N_More: _,
    Workshop_ItemModalViewDetails: _,
    Workshop_ItemModalViewCountDetails: _,
    Profile_Screenshots: _,
    Profile_Images: _,
    Profile_Videos: _,
    Profile_Workshop_Items: _,
    SharedFiles_Tab_Merchandise: _,
    Profile_Collections: _,
    Profile_Guides: _,
    SharedFiles_SharedFiles_Items: _,
    SharedFiles_SharedFiles_Collections: _,
    SharedFiles_SharedFiles_Guides: _,
    SharedFiles_Favorites: _,
    SharedFiles_Subscriptions: _,
    SharedFiles_Browse_MyFiles_Played: _,
    SharedFiles_FilterByGame: _,
    Profile_SharedFiles_AllGames: _,
    Profile_SharedFiles_SelectAGame: _,
    SharedFiles_Browse_MyFiles_Items: _,
    SharedFiles_Browse_MyFiles_Favorites: _,
    SharedFiles_Browse_MyFiles_Subscriptions: _,
    SharedFiles_Browse_MyFiles_Sort_CreationOrder: _,
    SharedFiles_Browse_MyFiles_Sort_Alpha: _,
    SharedFiles_Browse_MyFiles_Sort_LastUpdated: _,
    SharedFiles_Browse_MyFiles_Sort_Subscribed: _,
    SharedFiles_Browse_MyFiles_Sort_Favorited: _,
    SharedFiles_TagsSearch: _,
    SharedFiles_ByAuthor: _,
    Workshop_BrowsePaging: _,
    Workshop_NoItems: _,
    SharedFiles_UserList_BrowsePaging: _,
    SharedFiles_UserList_LastUpdated: _,
    SharedFiles_Favorites_Subscribed: _,
    SharedFiles_Favorites_NowUnsubscribed: _,
    SharedFiles_Subscription_Subscribed: _,
    SharedFiles_Subscription_NowUnsubscribed: _,
    Workshop_HasLinkedItems: _,
    Workshop_PaymentInfo_NotCreated: _,
    Workshop_PaymentInfo_Rejected: _,
    Workshop_SplitsAcceptTheseDesc1: _,
    Workshop_SplitsAcceptTheseDesc2: _,
    Workshop_SplitsPercentage: _,
    Profile_YourWorkshop: _,
    CommunityFollower_Description: _,
    CommunityFollower_Description_Yours: _,
    CommunityFollower_One_Follower: _,
    CommunityFollower_NumFollowers: _,
    CommunityFollower_FollowUser: _,
    CommunityFollower_FollowingUser: _,
    CommunityFollower_UnfollowUser: _,
    Workshop_ViewYourRevenue: _,
    Workshop_ViewYourRevenue_desc: _,
    Workshop_Link_PaymentInfo: _,
    Workshop_Link_LegalAgreement: _,
    SharedFiles_UnsubscribeAll_Btn: _,
    SharedFiles_UnsubscribeAll_Confirm_Title: _,
    SharedFiles_UnsubscribeAll_Confirm_Desc: _,
    SharedFiles_UnsubscribeAll_Confirm_App_Desc: _,
    SharedFiles_SaveSubscribedToCollection_Btn: _,
    SharedFiles_SaveSubscribedToCollection_Title: _,
    SharedFiles_SaveSubscribedToCollection_Desc: _,
    SharedFiles_SaveSubscribedToCollection_New: _,
    SharedFiles_SaveSubscribedToCollection_NewDesc: _,
    SharedFiles_SaveSubscribedToCollection_Existing: _,
    SharedFiles_SaveSubscribedToCollection_ExistingDesc: _,
    SharedFiles_SaveSubscribedToCollection_NoExistingCollections: _,
    SharedFiles_AdminTags: _,
    SharedFiles_SearchedForFileType_WebGuide: _,
    SharedFiles_SearchedForFileType_IntegratedGuide: _,
    SharedFiles_Dota2_IntegratedGuide: _,
    SharedFiles_Dota2_IntegratedGuide_Desc: _,
    AppHub_Guides_IntegratedGuides_Desc: _,
    AppHub_Guides_PopularCategories: _,
    AppHub_Guides_IntegratedGuides: _,
    AppHub_Guides_YourFavorites: _,
    AppHub_Guides_MostPopularThisWeek: _,
    AppHub_Guides_MostPopularThisWeek_Desc: _,
    AppHub_Guides_ViewAll: _,
    AppHub_Guides_NumGuides_Singular: _,
    AppHub_Guides_NumGuides_Plural: _,
    AppHub_Guides_GuidesYouHaveMade: _,
    AppHub_Guides_MoreInfo_Title: _,
    AppHub_Guides_MoreInfo_button: _,
    Workshop_BrowseBy: _,
    SharedFiles_Browse_GuideHome: _,
    SharedFiles_CreateGuide: _,
    SharedFiles_MustOwnAppToCreateGuide: _,
    SharedFiles_NoGuides_Title: _,
    SharedFiles_NoGuides_Desc1: _,
    SharedFiles_NoGuides_Desc2: _,
    SharedFiles_BrowseGuide_subtitle_nolink: _,
    SharedFiles_BrowseGuide_createNewBtnLabel: _,
    Community_Screenshots: _,
    Community_Images: _,
    Community_Videos: _,
    Paging_ShowingXtoYofZ: _,
    AppHubHome_BackToTop: _,
    Screenshots_Viewing: _,
    Profile_SharedFiles_ImageWallView: _,
    Profile_SharedFiles_GridView: _,
    Profile_SharedFiles_MostPopular: _,
    Profile_SharedFiles_NewestFirst: _,
    Profile_SharedFiles_OldestFirst: _,
    Screenshots_AllYourScreenshots: _,
    Screenshots_YourPublicScreenshots: _,
    Screenshots_YourFriendsOnlyScreenshots: _,
    Screenshots_YourPrivateScreenshots: _,
    Screenshots_YourUnlistedScreenshots: _,
    Images_AllYourImages: _,
    Images_YourPublicImages: _,
    Images_YourFriendsOnlyImages: _,
    Images_YourPrivateImages: _,
    Images_YourUnlistedImages: _,
    Videos_AllYourVideos: _,
    Videos_YourPublicVideos: _,
    Videos_YourFriendsOnlyVideos: _,
    Videos_YourPrivateVideos: _,
    Videos_YourUnlistedVideos: _,
    Screenshots_Manage: _,
    Images_Manage: _,
    Videos_Manage: _,
    Screenshots_SelectScreenshots: _,
    Images_SelectImages: _,
    Videos_SelectVideos: _,
    Videos_Cancel: _,
    Videos_AddFromYouTube: _,
    Videos_LinkYouTubeAcct: _,
    Videos_UnlinkYouTubeAcct: _,
    Videos_UnlinkButton: _,
    Videos_UnlinkConfirmText: _,
    Videos_Privacy: _,
    Videos_YoutubeTerms_1: _,
    Videos_YoutubeTerms_2: _,
    Videos_YoutubeTerms_3: _,
    Videos_YoutubeTerms_4: _,
    Videos_YoutubeTermsLink_TermsOfService: _,
    Videos_YoutubeTermsLink_PrivacyPolicy: _,
    Videos_YoutubeTermsLink_AuthorizedData: _,
    Videos_YoutubeTermsLink_SecuritySettings: _,
    Videos_NowOnSteam: _,
    Videos_ShareDescription: _,
    Videos_Desc1: _,
    Videos_Desc2: _,
    Videos_Desc3: _,
    Videos_AccessYourYouTubeVideos: _,
    Videos_CurrentlyLinkedTo: _,
    Videos_UnlinkToAddAnother: _,
    Videos_UnlinkAcct: _,
    Videos_ContinueWithAcct: _,
    Videos_SuccessfullyLinkedYouTube: _,
    Videos_SuccessfullyAddedSingular: _,
    Videos_SuccessfullyAddedPlural: _,
    Videos_NoVideosMsg1: _,
    Videos_NoVideosMsg2: _,
    Videos_CurrentlyLinkedMsg: _,
    Videos_ClickHereToChange: _,
    Videos_ChangeAccount: _,
    Videos_AddStep1: _,
    Videos_AvailCountSingular: _,
    Videos_AvailCountPlural: _,
    Videos_AddStep2: _,
    Videos_AddStep2Note: _,
    Videos_OptionNoneOther: _,
    Videos_OtherUnlisted: _,
    Videos_AddStep3: _,
    Videos_AddVideo: _,
    Videos_AddNote2: _,
    Videos_Refresh: _,
    Videos_AddStep4: _,
    Videos_AddNote4: _,
    Videos_AddDone: _,
    Videos_IssuesAccessing: _,
    Images_Upload: _,
    Screenshots_Upload: _,
    Screenshots_MakePublic: _,
    Screenshots_MakeFriendsOnly: _,
    Screenshots_MakePrivate: _,
    Screenshots_MakeUnlisted: _,
    Screenshots_Delete: _,
    Screenshots_SelectAll: _,
    Screenshots_Done: _,
    Screenshots_DeleteScreenshots: _,
    Screenshots_UpdatePrivacy: _,
    Screenshots_AreYouSureDelete: _,
    Screenshots_AreYouSurePrivacyChange: _,
    Screenshots_Continue: _,
    Screenshots_Cancel: _,
    Screenshots_Oops: _,
    Screenshots_NoneSelected: _,
    Screenshots_SelectScreenshotsToDelete: _,
    Screenshots_OK: _,
    Screenshots_VisUpdateFailed: _,
    Screenshots_VisUpdateFailedMessage: _,
    Blotter_PotentialSpoilers: _,
    Blotter_RevealImage: _,
    Profile_SharedFiles_NoScreenshotsSelf: _,
    Profile_SharedFiles_NoScreenshotsForYou: _,
    Profile_SharedFiles_NoScreenshotsFavoritesSelf: _,
    Profile_SharedFiles_NoScreenshotsFavoritesForYou: _,
    Profile_SharedFiles_NoImagesSelf: _,
    Profile_SharedFiles_NoImagesForYou: _,
    Profile_SharedFiles_NoImagesFavoritesSelf: _,
    Profile_SharedFiles_NoImagesFavoritesForYou: _,
    Profile_SharedFiles_NoVideosSelf: _,
    Profile_SharedFiles_NoVideosForYou: _,
    Profile_SharedFiles_NoVideosFavoritesSelf: _,
    Profile_SharedFiles_NoVideosFavoritesForYou: _,
    Profile_SharedFiles_NoScreenshotsThisVisibility: _,
    Screenshots_SteamHasThem: _,
    Screenshots_Instructions1: _,
    Screenshots_Instructions2: _,
    Profile_SharedFiles_By: _,
    Profile_SharedFiles_FavoritedBy: _,
  };
export {
  _ as AppHubHome_BackToTop,
  _ as AppHub_Guides_GuidesYouHaveMade,
  _ as AppHub_Guides_IntegratedGuides,
  _ as AppHub_Guides_IntegratedGuides_Desc,
  _ as AppHub_Guides_MoreInfo_Title,
  _ as AppHub_Guides_MoreInfo_button,
  _ as AppHub_Guides_MostPopularThisWeek,
  _ as AppHub_Guides_MostPopularThisWeek_Desc,
  _ as AppHub_Guides_NumGuides_Plural,
  _ as AppHub_Guides_NumGuides_Singular,
  _ as AppHub_Guides_PopularCategories,
  _ as AppHub_Guides_ViewAll,
  _ as AppHub_Guides_YourFavorites,
  _ as AppPrivacy_Explanation,
  _ as AppPrivacy_MarkAsPrivate,
  _ as AppPrivacy_UnmarkAsPrivate,
  _ as Blotter_PotentialSpoilers,
  _ as Blotter_RevealImage,
  _ as CommunityFollower_Description,
  _ as CommunityFollower_Description_Yours,
  _ as CommunityFollower_FollowUser,
  _ as CommunityFollower_FollowingUser,
  _ as CommunityFollower_NumFollowers,
  _ as CommunityFollower_One_Follower,
  _ as CommunityFollower_UnfollowUser,
  _ as Community_Forums,
  _ as Community_FriendsWhoPlayMenuItemFirstPerson,
  _ as Community_GameContent,
  _ as Community_GameContentFirstPerson,
  _ as Community_GameHubMenuItem,
  _ as Community_GameLinks,
  _ as Community_GameNotesFirstPerson,
  _ as Community_GamePersonalData,
  _ as Community_GameStats,
  _ as Community_GameStatsFirstPerson,
  _ as Community_GlobalAchievements,
  _ as Community_GlobalLeaderboards,
  _ as Community_Groups,
  _ as Community_Images,
  _ as Community_News,
  _ as Community_OfficialWebsite,
  _ as Community_RemoveLink_BeWary,
  _ as Community_RemoveLink_Tooltip,
  _ as Community_ReviewMenuItemFirstPerson,
  _ as Community_ReviewMenuItemThirdPerson,
  _ as Community_Screenshots,
  _ as Community_ScreenshotsMenuItemFirstPerson,
  _ as Community_ScreenshotsMenuItemThirdPerson,
  _ as Community_StorePage,
  _ as Community_TradingCardsMenuItemFirstPerson,
  _ as Community_UsersAchievements,
  _ as Community_UsersAchievementsFirstPerson,
  _ as Community_UsersLeaderboards,
  _ as Community_UsersLeaderboardsFirstPerson,
  _ as Community_UsersStats,
  _ as Community_Videos,
  _ as Discussions_FormattingHelp_Quote,
  _ as Discussions_FormattingHelp_Spoiler,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as GamesList_Achievement_Fraction,
  _ as GamesList_Achievement_Unlock_Percentage,
  _ as GamesList_Button_Cancel,
  _ as GamesList_Button_Download,
  _ as GamesList_Button_Pause,
  _ as GamesList_Button_Resume,
  _ as GamesList_Button_Uninstall,
  _ as GamesList_Button_Uninstalling,
  _ as GamesList_Button_UpdateRequired,
  _ as GamesList_Client_Indicator,
  _ as GamesList_Filter_BothOwned,
  _ as GamesList_Filter_Placeholder,
  _ as GamesList_Header_Achievements,
  _ as GamesList_Header_DownloadBytes,
  _ as GamesList_Header_Downloading,
  _ as GamesList_Header_LastPlayed,
  _ as GamesList_Header_Paused,
  _ as GamesList_Header_RemoteDownload,
  _ as GamesList_Header_RemoteDownloadStatus,
  _ as GamesList_Header_TotalPlayed,
  _ as GamesList_Header_TwoWeeks,
  _ as GamesList_MenuLabel_GameInfo,
  _ as GamesList_MenuLabel_RemoteDownload,
  _ as GamesList_PerfectGames_Description,
  _ as GamesList_PrivacySettings_Tooltip,
  _ as GamesList_RemoteDownload_Help,
  _ as GamesList_RemoteDownload_Info,
  _ as GamesList_RemoteDownload_LearnMore,
  _ as GamesList_RemoteDownload_NoConnection,
  _ as GamesList_RemoteDownload_NoRemoteControl,
  _ as GamesList_RemoteDownload_ReadTheFAQ,
  _ as GamesList_RemoteDownload_UninstallConfirm,
  _ as GamesList_Sort_AchievementCompletion,
  _ as GamesList_Sort_HoursPlayed,
  _ as GamesList_Sort_Name,
  _ as GamesList_Tab_AllGames,
  _ as GamesList_Tab_Followed,
  _ as GamesList_Tab_PerfectGames,
  _ as GamesList_Tab_RecentlyPlayed,
  _ as GamesList_Tab_Reviews,
  _ as GamesList_Tab_Wishlist,
  _ as GamesList_TimeRemaining,
  _ as GamesList_Uninstalling,
  _ as Images_AllYourImages,
  _ as Images_Manage,
  _ as Images_SelectImages,
  _ as Images_Upload,
  _ as Images_YourFriendsOnlyImages,
  _ as Images_YourPrivateImages,
  _ as Images_YourPublicImages,
  _ as Images_YourUnlistedImages,
  _ as Loading,
  _ as Market_GenericTitle,
  _ as Market_Item_GenericTitle,
  _ as Market_Item_Title,
  _ as Market_Search_Title,
  _ as Moderation_SubjectTypeName_ForumPost,
  _ as Paging_ShowingXtoYofZ,
  _ as Perfect_Game_Description,
  _ as Playtime_Hours,
  _ as Playtime_Minutes,
  _ as Profile_Collections,
  _ as Profile_Guides,
  _ as Profile_Images,
  _ as Profile_Screenshots,
  _ as Profile_SharedFiles_AllGames,
  _ as Profile_SharedFiles_By,
  _ as Profile_SharedFiles_FavoritedBy,
  _ as Profile_SharedFiles_GridView,
  _ as Profile_SharedFiles_ImageWallView,
  _ as Profile_SharedFiles_MostPopular,
  _ as Profile_SharedFiles_NewestFirst,
  _ as Profile_SharedFiles_NoImagesFavoritesForYou,
  _ as Profile_SharedFiles_NoImagesFavoritesSelf,
  _ as Profile_SharedFiles_NoImagesForYou,
  _ as Profile_SharedFiles_NoImagesSelf,
  _ as Profile_SharedFiles_NoScreenshotsFavoritesForYou,
  _ as Profile_SharedFiles_NoScreenshotsFavoritesSelf,
  _ as Profile_SharedFiles_NoScreenshotsForYou,
  _ as Profile_SharedFiles_NoScreenshotsSelf,
  _ as Profile_SharedFiles_NoScreenshotsThisVisibility,
  _ as Profile_SharedFiles_NoVideosFavoritesForYou,
  _ as Profile_SharedFiles_NoVideosFavoritesSelf,
  _ as Profile_SharedFiles_NoVideosForYou,
  _ as Profile_SharedFiles_NoVideosSelf,
  _ as Profile_SharedFiles_OldestFirst,
  _ as Profile_SharedFiles_SelectAGame,
  _ as Profile_Videos,
  _ as Profile_Workshop_Items,
  _ as Profile_YourWorkshop,
  _ as Screenshots_AllYourScreenshots,
  _ as Screenshots_AreYouSureDelete,
  _ as Screenshots_AreYouSurePrivacyChange,
  _ as Screenshots_Cancel,
  _ as Screenshots_Continue,
  _ as Screenshots_Delete,
  _ as Screenshots_DeleteScreenshots,
  _ as Screenshots_Done,
  _ as Screenshots_Instructions1,
  _ as Screenshots_Instructions2,
  _ as Screenshots_Location,
  _ as Screenshots_MakeFriendsOnly,
  _ as Screenshots_MakePrivate,
  _ as Screenshots_MakePublic,
  _ as Screenshots_MakeUnlisted,
  _ as Screenshots_Manage,
  _ as Screenshots_NoneSelected,
  _ as Screenshots_OK,
  _ as Screenshots_Oops,
  _ as Screenshots_SelectAll,
  _ as Screenshots_SelectScreenshots,
  _ as Screenshots_SelectScreenshotsToDelete,
  _ as Screenshots_SteamHasThem,
  _ as Screenshots_UpdatePrivacy,
  _ as Screenshots_Upload,
  _ as Screenshots_Viewing,
  _ as Screenshots_VisUpdateFailed,
  _ as Screenshots_VisUpdateFailedMessage,
  _ as Screenshots_YourFriendsOnlyScreenshots,
  _ as Screenshots_YourPrivateScreenshots,
  _ as Screenshots_YourPublicScreenshots,
  _ as Screenshots_YourUnlistedScreenshots,
  _ as SharedFiles_AddSpoilerTag,
  _ as SharedFiles_AdminTags,
  _ as SharedFiles_And_N_More,
  _ as SharedFiles_BrowseGuide_createNewBtnLabel,
  _ as SharedFiles_BrowseGuide_subtitle_nolink,
  _ as SharedFiles_Browse_GuideHome,
  _ as SharedFiles_Browse_MyFiles_Favorites,
  _ as SharedFiles_Browse_MyFiles_Items,
  _ as SharedFiles_Browse_MyFiles_Played,
  _ as SharedFiles_Browse_MyFiles_Sort_Alpha,
  _ as SharedFiles_Browse_MyFiles_Sort_CreationOrder,
  _ as SharedFiles_Browse_MyFiles_Sort_Favorited,
  _ as SharedFiles_Browse_MyFiles_Sort_LastUpdated,
  _ as SharedFiles_Browse_MyFiles_Sort_Subscribed,
  _ as SharedFiles_Browse_MyFiles_Subscriptions,
  _ as SharedFiles_ByAuthor,
  _ as SharedFiles_CreateGuide,
  _ as SharedFiles_DeveloperComments,
  _ as SharedFiles_Dota2_IntegratedGuide,
  _ as SharedFiles_Dota2_IntegratedGuide_Desc,
  _ as SharedFiles_Favorites,
  _ as SharedFiles_Favorites_NowUnsubscribed,
  _ as SharedFiles_Favorites_Subscribed,
  _ as SharedFiles_FilterByGame,
  _ as SharedFiles_Guide_Comments,
  _ as SharedFiles_Guide_Index,
  _ as SharedFiles_Guide_Overview,
  _ as SharedFiles_ItemDownload,
  _ as SharedFiles_ItemEditText_ErrorNoTitle,
  _ as SharedFiles_ItemEditText_Text_Caption,
  _ as SharedFiles_Item_Edit_Link,
  _ as SharedFiles_ManageGuide_AddContributor,
  _ as SharedFiles_ManageGuide_AddSection,
  _ as SharedFiles_ManageGuide_Cancel,
  _ as SharedFiles_ManageGuide_Contents,
  _ as SharedFiles_ManageGuide_Contents_Desc,
  _ as SharedFiles_ManageGuide_Contributors,
  _ as SharedFiles_ManageGuide_Contributors_Desc,
  _ as SharedFiles_ManageGuide_DeleteThisSection,
  _ as SharedFiles_ManageGuide_EditSubSection,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Delete,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Desc,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Insert,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Changes,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Edit,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Preview,
  _ as SharedFiles_ManageGuide_EditThisSection,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_Layout,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutInline,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutLeft,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutRight,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_Size,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeFull,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeOriginal,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeThumb,
  _ as SharedFiles_ManageGuide_Images,
  _ as SharedFiles_ManageGuide_Images_Desc,
  _ as SharedFiles_ManageGuide_InsertImage,
  _ as SharedFiles_ManageGuide_InsertYouTubeVideo,
  _ as SharedFiles_ManageGuide_NoContributors,
  _ as SharedFiles_ManageGuide_NoPreviewImages,
  _ as SharedFiles_ManageGuide_NoSectionTitle,
  _ as SharedFiles_ManageGuide_NoSubSections,
  _ as SharedFiles_ManageGuide_Preview,
  _ as SharedFiles_ManageGuide_PromptYouTubeUrl,
  _ as SharedFiles_ManageGuide_RemoveSectionConfirm,
  _ as SharedFiles_ManageGuide_Required,
  _ as SharedFiles_ManageGuide_Save,
  _ as SharedFiles_ManageGuide_Screenshots,
  _ as SharedFiles_ManageGuide_SubImages,
  _ as SharedFiles_ManageGuide_SubScreenshots,
  _ as SharedFiles_ManageGuide_SubSectionContentChanged,
  _ as SharedFiles_ManageGuide_SubSectionContentChanged_CancelConfirm,
  _ as SharedFiles_ManageGuide_SubSectionContentSaved,
  _ as SharedFiles_ManageGuide_SubSectionContents,
  _ as SharedFiles_ManageGuide_SubSectionTitle,
  _ as SharedFiles_ManageGuide_SubVideos,
  _ as SharedFiles_ManageGuide_Videos,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Full,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Left,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Right,
  _ as SharedFiles_Media_ViewAppFanArt,
  _ as SharedFiles_Media_ViewAppScreenshots,
  _ as SharedFiles_Media_ViewAppVideos,
  _ as SharedFiles_MustOwnAppToCreateGuide,
  _ as SharedFiles_NoGuides_Desc1,
  _ as SharedFiles_NoGuides_Desc2,
  _ as SharedFiles_NoGuides_Title,
  _ as SharedFiles_OwnerControl_BackGuide,
  _ as SharedFiles_OwnerControl_EditCaption,
  _ as SharedFiles_PublicComments,
  _ as SharedFiles_RemoveSelfTag_Tooltip,
  _ as SharedFiles_RemoveSpoilerTag,
  _ as SharedFiles_SaveSubscribedToCollection_Btn,
  _ as SharedFiles_SaveSubscribedToCollection_Desc,
  _ as SharedFiles_SaveSubscribedToCollection_Existing,
  _ as SharedFiles_SaveSubscribedToCollection_ExistingDesc,
  _ as SharedFiles_SaveSubscribedToCollection_New,
  _ as SharedFiles_SaveSubscribedToCollection_NewDesc,
  _ as SharedFiles_SaveSubscribedToCollection_NoExistingCollections,
  _ as SharedFiles_SaveSubscribedToCollection_Title,
  _ as SharedFiles_SearchedForFileType_IntegratedGuide,
  _ as SharedFiles_SearchedForFileType_WebGuide,
  _ as SharedFiles_SharedFiles_Collections,
  _ as SharedFiles_SharedFiles_Guides,
  _ as SharedFiles_SharedFiles_Items,
  _ as SharedFiles_SpoilerTagInstructions,
  _ as SharedFiles_SpoilerTagsExpire,
  _ as SharedFiles_Stats_TaggedUsers,
  _ as SharedFiles_Stats_TaggedWorkshopItems,
  _ as SharedFiles_Subscription_NowUnsubscribed,
  _ as SharedFiles_Subscription_Subscribed,
  _ as SharedFiles_Subscriptions,
  _ as SharedFiles_Tab_Merchandise,
  _ as SharedFiles_Tags,
  _ as SharedFiles_TagsSearch,
  _ as SharedFiles_UnsubscribeAll_Btn,
  _ as SharedFiles_UnsubscribeAll_Confirm_App_Desc,
  _ as SharedFiles_UnsubscribeAll_Confirm_Desc,
  _ as SharedFiles_UnsubscribeAll_Confirm_Title,
  _ as SharedFiles_UserList_BrowsePaging,
  _ as SharedFiles_UserList_LastUpdated,
  _ as SharedFiles_WaitingForIntegratedGuide,
  _ as SharedFiles_WorkshopItemsTagged,
  _ as Videos_AccessYourYouTubeVideos,
  _ as Videos_AddDone,
  _ as Videos_AddFromYouTube,
  _ as Videos_AddNote2,
  _ as Videos_AddNote4,
  _ as Videos_AddStep1,
  _ as Videos_AddStep2,
  _ as Videos_AddStep2Note,
  _ as Videos_AddStep3,
  _ as Videos_AddStep4,
  _ as Videos_AddVideo,
  _ as Videos_AllYourVideos,
  _ as Videos_AvailCountPlural,
  _ as Videos_AvailCountSingular,
  _ as Videos_Cancel,
  _ as Videos_ChangeAccount,
  _ as Videos_ClickHereToChange,
  _ as Videos_ContinueWithAcct,
  _ as Videos_CurrentlyLinkedMsg,
  _ as Videos_CurrentlyLinkedTo,
  _ as Videos_Desc1,
  _ as Videos_Desc2,
  _ as Videos_Desc3,
  _ as Videos_IssuesAccessing,
  _ as Videos_LinkYouTubeAcct,
  _ as Videos_Manage,
  _ as Videos_NoVideosMsg1,
  _ as Videos_NoVideosMsg2,
  _ as Videos_NowOnSteam,
  _ as Videos_OptionNoneOther,
  _ as Videos_OtherUnlisted,
  _ as Videos_Privacy,
  _ as Videos_Refresh,
  _ as Videos_SelectVideos,
  _ as Videos_ShareDescription,
  _ as Videos_SuccessfullyAddedPlural,
  _ as Videos_SuccessfullyAddedSingular,
  _ as Videos_SuccessfullyLinkedYouTube,
  _ as Videos_UnlinkAcct,
  _ as Videos_UnlinkButton,
  _ as Videos_UnlinkConfirmText,
  _ as Videos_UnlinkToAddAnother,
  _ as Videos_UnlinkYouTubeAcct,
  _ as Videos_YourFriendsOnlyVideos,
  _ as Videos_YourPrivateVideos,
  _ as Videos_YourPublicVideos,
  _ as Videos_YourUnlistedVideos,
  _ as Videos_YoutubeTermsLink_AuthorizedData,
  _ as Videos_YoutubeTermsLink_PrivacyPolicy,
  _ as Videos_YoutubeTermsLink_SecuritySettings,
  _ as Videos_YoutubeTermsLink_TermsOfService,
  _ as Videos_YoutubeTerms_1,
  _ as Videos_YoutubeTerms_2,
  _ as Videos_YoutubeTerms_3,
  _ as Videos_YoutubeTerms_4,
  _ as Workshop_BrowseBy,
  _ as Workshop_BrowsePaging,
  _ as Workshop_DeveloperThreadDesc,
  _ as Workshop_DeveloperThreadDisclaimerText,
  _ as Workshop_HasLinkedItems,
  _ as Workshop_ImageSize,
  _ as Workshop_ItemModalViewCountDetails,
  _ as Workshop_ItemModalViewDetails,
  _ as Workshop_Link_LegalAgreement,
  _ as Workshop_Link_PaymentInfo,
  _ as Workshop_NoItems,
  _ as Workshop_PaymentInfo_NotCreated,
  _ as Workshop_PaymentInfo_Rejected,
  _ as Workshop_SplitsAcceptTheseDesc1,
  _ as Workshop_SplitsAcceptTheseDesc2,
  _ as Workshop_SplitsPercentage,
  _ as Workshop_Subscribe_IntegratedGuide,
  _ as Workshop_ViewYourRevenue,
  _ as Workshop_ViewYourRevenue_desc,
  _ as community_errorpage_title,
  _ as community_title,
  _ as default,
  _ as empty_no_comma_following,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_accessibility,
  _ as footer_cookies,
  _ as footer_geodata_notice,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_privacy_policy,
  _ as footer_refunds,
  _ as footer_ssa,
  _ as moderatedcontent_description,
  _ as moderation_claim_n_reports_on_m_subjects,
  _ as moderation_claim_report_count,
  _ as moderation_claim_report_count_Plural,
  _ as moderation_claim_subject_count,
  _ as moderation_claim_subject_count_Plural,
  _ as moderation_forumpost_summary,
  _ as moderation_forumpost_summary_reports_fragment,
  _ as moderation_forumpost_summary_reports_fragment_Plural,
  _ as moderation_forumpost_summary_subjects_fragment,
  _ as moderation_forumpost_summary_subjects_fragment_Plural,
  _ as profile_error_profilenotfound,
  _ as profile_games_list,
  _ as profile_games_list_error_loadfailed,
  _ as profile_games_list_title,
  _ as profiletabs_communitymessages,
  _ as profiletabs_currentbans,
  _ as profiletabs_moderatedcontent,
  _ as profiletabs_reportedcontent,
  _ as reportedcontent_description,
  _ as reportedcontent_lastupdated,
};
