var _ = `포럼 게시물`,
  _ = `일반 토론`,
  _ = `신고된 게시물`,
  _ = `창작마당 토론`,
  _ = `거래`,
  _ = `이벤트 및 공지`,
  _ = `신고 1개`,
  _ = `신고 %1$s개`,
  _ = `조정 대상 1개`,
  _ = `조정 대상 %1$s개`,
  _ = `%2$s 관련 %1$s`,
  _ = `%3$s 주제 관련 %2$s에 대한 %1$s`,
  _ = `신고 1개`,
  _ = `신고 %1$s개`,
  _ = `조정 대상 1개`,
  _ = `조정 대상 %1$s개`,
  _ = `Steam 커뮤니티`,
  _ = `Steam 커뮤니티 :: 오류`,
  _ = `오류`,
  _ = `알 수 없는 오류`,
  _ = `게임`,
  _ = `Steam 커뮤니티 :: %1$s :: 게임`,
  _ = `검색 - Steam 장터`,
  _ = `%1$s - Steam 장터`,
  _ = `장터 아이템 - Steam 장터`,
  _ = `Steam 장터`,
  _ = `프로필을 찾을 수 없습니다.`,
  _ = `찜 목록을 불러오지 못했습니다.`,
  _ = `너무 많은 요청을 보냈습니다. 잠시 기다렸다가 나중에 다시 시도하세요.`,
  _ = `불러오는 중`,
  _ = `%1$s% 완료`,
  _ = `일시 정지 - %1$s% 완료`,
  _ = `%1$s/%2$s 다운로드`,
  _ = `도전 과제`,
  _ = `남은 예상 시간: %1$s`,
  _ = `%1$s/%2$s`,
  _ = `제거 중`,
  _ = `업데이트`,
  _ = `제거`,
  _ = `다운로드`,
  _ = `일시 정지`,
  _ = `다시 시작`,
  _ = `제거 중`,
  _ = `취소`,
  _ = `이 콘텐츠에 대한 공개 설정을 확인합니다.`,
  _ = `게임 찾기`,
  _ = `함께 소유하고 있는 게임으로 필터링`,
  _ = `플레이 시간`,
  _ = `이름`,
  _ = `도전 과제 달성 완료`,
  _ = `전체 플레이 시간`,
  _ = `최근 플레이`,
  _ = `지난 2주간 전체 플레이 시간`,
  _ = `게임 정보 및 링크`,
  _ = `원격 다운로드`,
  _ = `원격 다운로드 위치: %1$s`,
  _ = `원격 다운로드 상태: %1$s`,
  _ = `PC에 연결 불가`,
  _ = `Steam 클라이언트에 원격으로 게임을 다운로드하려면 PC의 전원이 켜진 상태로 인터넷에 연결되어 있어야 하며 로그인이 필요합니다.`,
  _ = `자주 하는 질문을 확인하세요.`,
  _ = `%1$s. %2$s`,
  _ = `더 알아보기`,
  _ = `원격 다운로드 사용 불가`,
  _ = `%1$s 게임을 제거할까요? 설치 제거 시, 게임은 라이브러리에 그대로 남아 있지만 나중에 다시 플레이하려면 먼저 모든 콘텐츠를 다시 다운로드해야 합니다.`,
  _ = `%1$s | '%2$s'`,
  _ = `최근 플레이한 게임%1$s`,
  _ = `모든 게임%1$s`,
  _ = `완전 정복한 게임%1$s`,
  _ = `작성한 평가%1$s`,
  _ = `팔로우한 게임%1$s`,
  _ = `찜 목록`,
  _ = `모든 도전 과제를 달성한 게임입니다.`,
  _ = `플레이를 완료한 게임 또는 모든 도전 과제를 달성한 게임을 확인할 수 있습니다.`,
  _ = `전체 플레이어 중 %1$s%가 이 도전 과제 달성`,
  _ = `상점 페이지`,
  _ = `포럼`,
  _ = `그룹`,
  _ = `공식 웹사이트`,
  _ = `뉴스`,
  _ = `도전 과제`,
  _ = `%1$s 님의 도전 과제`,
  _ = `%1$s 님의 통계`,
  _ = `%1$s 님의 개인 게임 데이터`,
  _ = `내 순위표`,
  _ = `%1$s 님의 순위표`,
  _ = `전 세계 도전 과제`,
  _ = `전 세계 순위표`,
  _ = `게임 통계`,
  _ = `게임 콘텐츠`,
  _ = `내 게임 통계`,
  _ = `내 게임 콘텐츠`,
  _ = `게임 링크`,
  _ = `내 스크린샷%1$s`,
  _ = `%1$s 님의 스크린샷%2$s`,
  _ = `게임을 플레이하는 친구%1$s`,
  _ = `내 트레이딩 카드%1$s`,
  _ = `내 평가`,
  _ = `%1$s 님의 평가`,
  _ = `커뮤니티 허브`,
  _ = `내 노트`,
  _ = `%1$s시간`,
  _ = `%1$s분`,
  _ = `비공개`,
  _ = `공개`,
  _ = `이 게임을 비공개로 설정하고 친구들에게 숨깁니다.`,
  _ = `© Valve Corporation. All rights reserved. 모든 상표는 미국 및 기타 국가에서 해당 소유자의 재산입니다.`,
  _ = `이 웹사이트의 일부 지역 정보 데이터는 %1$s에서 제공합니다.`,
  _ = `개인정보 처리방침`,
  _ = `법적 고지`,
  _ = `Steam 이용 약관`,
  _ = `환불`,
  _ = `쿠키`,
  _ = `접근성`,
  _ = `현재 차단`,
  _ = `커뮤니티 메시지`,
  _ = `신고된 콘텐츠`,
  _ = `조정된 콘텐츠`,
  _ = `Steam에 있는 콘텐츠 중 Steam 가이드라인 위반으로 신고한 콘텐츠입니다.`,
  _ = `사용자가 Steam에 게시한 콘텐츠 중 조정된 콘텐츠의 목록입니다.`,
  _ = `마지막 업데이트: %1$s`,
  _ = `다운로드`,
  _ = `공개 댓글(%1$s)`,
  _ = `개발자 댓글(%1$s)`,
  _ = `비공개 글타래입니다. 이 글타래는 해당 콘텐츠의 기여자와 게임 개발자만 읽을 수 있습니다.`,
  _ = `참고: 게임 개발사(예: Valve)와 소통했더라도 제출한 콘텐츠가 선정된다는 보장은 없습니다.`,
  _ = `크기`,
  _ = `전체 스크린샷 보기`,
  _ = `모든 아트워크 보기`,
  _ = `모든 동영상 보기`,
  _ = `설명`,
  _ = `설명 편집`,
  _ = `스포일러 태그 추가`,
  _ = `스포일러 태그 제거`,
  _ = `스포일러 태그를 사용하면 친구와 커뮤니티 멤버가 게임 스포일러를 피하기 위해 이 콘텐츠를 보지 않도록 선택할 수 있습니다.`,
  _ = `(스포일러 태그는 4주 후에 만료됩니다.)`,
  _ = `이 스크린샷에 태그된 사용자:`,
  _ = `이 스크린샷에 태그된 창작마당 콘텐츠: `,
  _ = `이 스크린샷에 태그된 내 계정 제거`,
  _ = `위치`,
  _ = `태그:`,
  _ = `가이드 불러오는 중`,
  _ = `이 가이드를 %1$s 내에서 사용하려면 구독하세요.`,
  _ = `가이드 색인`,
  _ = `개요`,
  _ = `댓글`,
  _ = `편집`,
  _ = `{링크 제거됨}`,
  _ = `여기에 연결된 URL은 필터에 의해 제거되었습니다. 이는 주로 피싱 사기나 맬웨어 공격을 방지하기 위한 조치입니다.`,
  _ = `가이드 내용`,
  _ = `가이드의 구성과 가이드 내 섹션의 이름을 정의하세요. 섹션을 끌어다 놓아 순서를 다시 정렬할 수 있습니다.`,
  _ = `가이드를 게시하려면 이 섹션을 작성해야 합니다.`,
  _ = `나만의 목차 만들기`,
  _ = `섹션 추가`,
  _ = `(아직 제목이 없는 새 섹션)`,
  _ = `이 섹션 편집`,
  _ = `이 섹션 삭제`,
  _ = `정말 이 섹션을 삭제할까요? 다시 복구할 수 없습니다.`,
  _ = `이미지`,
  _ = `가이드에서 참고 자료로 사용할 이미지를 선택하고 업로드하세요. 여기에서 필요한 이미지를 모두 업로드하면 가이드의 개별 섹션을 편집할 때 이미지를 쉽게 선택할 수 있습니다.`,
  _ = `가이드에 사용할 이미지 업로드`,
  _ = `기여자 추가`,
  _ = `여기에서 친구를 기여자로 추가하여 가이드 편집 권한을 부여할 수 있습니다.`,
  _ = `친구를 기여자로 추가`,
  _ = `기여자 추가`,
  _ = `가이드 미리 보기`,
  _ = `가이드 섹션 편집`,
  _ = `섹션 이름`,
  _ = `섹션 콘텐츠`,
  _ = `편집`,
  _ = `미리 보기`,
  _ = `변경 사항 보기`,
  _ = `마지막 저장 이후 변경된 텍스트는 다음과 같이 표시됩니다.`,
  _ = `추가된 텍스트`,
  _ = `제거된 텍스트`,
  _ = `이 섹션에 아직 저장되지 않은 변경 사항이 있습니다.`,
  _ = `이 섹션에 대한 변경 사항이 저장되지 않았습니다. 정말로 변경 사항을 취소할까요?`,
  _ = `마지막 저장 `,
  _ = `저장`,
  _ = `취소`,
  _ = `스크린샷`,
  _ = `동영상`,
  _ = `아래의 이미지를 클릭하여 가이드에 추가하세요.`,
  _ = `아래의 스크린샷을 클릭하여 가이드에 추가하세요.`,
  _ = `아래의 동영상을 클릭하여 가이드에 추가하세요.`,
  _ = `이미지 삽입 옵션`,
  _ = `크기`,
  _ = `절반 너비`,
  _ = `전체 너비`,
  _ = `원본 크기`,
  _ = `정렬`,
  _ = `왼쪽`,
  _ = `오른쪽`,
  _ = `인라인`,
  _ = `왼쪽 정렬`,
  _ = `오른쪽 정렬`,
  _ = `전체 너비`,
  _ = `삽입`,
  _ = `YouTube™ 동영상 삽입`,
  _ = `YouTube™ 동영상 URL 입력`,
  _ = `인용`,
  _ = `스포일러 텍스트`,
  _ = `제목을 입력하세요.`,
  _ = `내 가이드로 이동`,
  _ = ``,
  _ = `창작마당 콘텐츠:`,
  _ = `외 %1$s개`,
  _ = `댓글 및 자세한 내용 보기`,
  _ = `댓글 %1$s개 및 세부 정보 보기`,
  _ = `스크린샷`,
  _ = `아트워크`,
  _ = `동영상`,
  _ = `창작마당 콘텐츠`,
  _ = `상품`,
  _ = `모음집`,
  _ = `가이드`,
  _ = `창작마당 콘텐츠`,
  _ = `창작마당 모음집`,
  _ = `가이드`,
  _ = `즐겨찾기`,
  _ = `구독한 콘텐츠`,
  _ = `플레이함`,
  _ = `게임으로 필터링`,
  _ = `모든 게임`,
  _ = `게임 선택`,
  _ = `콘텐츠`,
  _ = `즐겨찾기에 추가됨`,
  _ = `구독한 콘텐츠`,
  _ = `생성 날짜`,
  _ = `알파벳순`,
  _ = `업데이트 날짜`,
  _ = `구독 날짜`,
  _ = `즐겨찾기된 날짜`,
  _ = `선택한 단어가 태그된 콘텐츠 표시:`,
  _ = `작성자`,
  _ = `%3$s개 중 %1$s~%2$s개 표시 중`,
  _ = `%1$s 님의 콘텐츠를 찾을 수 없습니다.`,
  _ = `%3$s개 중 %1$s~%2$s개 표시 중`,
  _ = `마지막 업데이트: %1$s`,
  _ = `추가한 날짜: %1$s`,
  _ = `이 콘텐츠는 즐겨찾기 목록에서 제거되었습니다.`,
  _ = `구독한 날짜: %1$s`,
  _ = `다음 항목을 구독 취소했습니다:`,
  _ = `축하합니다! 제출한 Steam 창작마당 콘텐츠 중 일부가 게임 내 사용 대상으로 선정되었습니다!`,
  _ = `기쁨을 만끽하기 전에, 수익금을 지급할 수 있도록 <a href="%1$s">지급 정보</a>를 입력해 주세요.`,
  _ = `지급 정보를 확인하는 중에 문제가 발생했습니다. <a href="%1$s">지급 정보</a>를 검토하고 업데이트하세요.`,
  _ = `다음 콘텐츠의 기여자로 표시되었습니다.`,
  _ = `다음 콘텐츠에 대한 기여자 이름을 검토하고 수락하세요.`,
  _ = `분배율:`,
  _ = `내 창작마당`,
  _ = `이 사용자가 새로운 Steam 가이드를 게시하거나 모음집을 만들거나 Steam 창작마당에 콘텐츠를 게시했을 때 알림을 받으려면 팔로우하세요.`,
  _ = `사용자를 팔로우하는 다른 모든 Steam 사용자는 새 Steam 가이드를 게시하거나, 새 모음집을 만들거나, Steam 창작마당에 콘텐츠를 게시하면 알림을 받을 수 있습니다.`,
  _ = `팔로워`,
  _ = `팔로워`,
  _ = `%1$s 님 팔로우`,
  _ = `%1$s 님 팔로우 중`,
  _ = `%1$s 님 팔로우 취소`,
  _ = `수익 보기`,
  _ = `창작마당 콘텐츠 판매 수익`,
  _ = `지급 정보 입력 또는 업데이트`,
  _ = `이용 약관 보기`,
  _ = `모든 구독 취소`,
  _ = `모든 구독을 취소할까요?`,
  _ = `정말로 모든 구독 항목을 제거할까요?<br><br>이 작업은 되돌릴 수 없습니다!`,
  _ = `정말로 %1$s의 모든 구독 항목을 제거할까요?<br><br>이 작업은 되돌릴 수 없습니다!`,
  _ = `모음집에 저장`,
  _ = `모음집에 구독 저장`,
  _ = `구독을 새 모음집 또는 기존 모음집에 저장할까요?`,
  _ = `새 모음집`,
  _ = `모음집 이름을 입력하세요.`,
  _ = `기존 모음집`,
  _ = `덮어쓸 모음집을 선택하세요. `,
  _ = `기존 모음집이 없습니다. 새로 만들까요?`,
  _ = `관리자 태그`,
  _ = `Steam 가이드`,
  _ = `통합형 가이드`,
  _ = `영웅 빌드`,
  _ = `플레이하면서 배울 수 있도록 특별히 통합된 가이드`,
  _ = `%1$s 항목과 특별히 통합된 가이드입니다.`,
  _ = `인기 종류`,
  _ = `통합형 가이드`,
  _ = `즐겨찾기`,
  _ = `인기 Steam 가이드`,
  _ = `가이드, 참고 자료 및 공략을 확인해 보세요.`,
  _ = `모두 보기(%1$s)`,
  _ = `%1$s개의 가이드`,
  _ = `%1$s개의 가이드`,
  _ = `내가 만든 가이드`,
  _ = `가이드에 대해 더 알아보기`,
  _ = `Steam 가이드에 대해 더 자세히 알아보려면 여기를 클릭하세요.`,
  _ = `검색 기준:`,
  _ = `홈`,
  _ = `가이드 만들기`,
  _ = `가이드를 작성하려면 먼저 %1$s 항목을 가지고 있어야 합니다.`,
  _ = `이 게임의 첫 번째 가이드를 만들어 주세요!`,
  _ = `여러분의 전문 지식을 선보이거나 게임을 하다 막힌 사람들을 도와주세요.`,
  _ = `공략집을 만들거나, 게임에 숨겨진 비밀을 밝히거나, 특정 맵에 대한 최적의 전략을 제안하세요.`,
  _ = `플레이어가 만든 이 게임의 가이드를 검색하고 평가해 보세요. 직접 가이드를 만들어 커뮤니티와 팁을 공유할 수도 있습니다.`,
  _ = `내 가이드 만들기`,
  _ = `스크린샷`,
  _ = `아트워크`,
  _ = `동영상`,
  _ = `%3$s개 중 %1$s~%2$s개 표시 중`,
  _ = `맨 위로`,
  _ = `표시 중`,
  _ = `이미지 담벼락`,
  _ = `격자`,
  _ = `인기순`,
  _ = `최근 날짜순`,
  _ = `과거 날짜순`,
  _ = `모든 스크린샷`,
  _ = `전체 공개 스크린샷`,
  _ = `친구 공개 스크린샷`,
  _ = `비공개 스크린샷`,
  _ = `미등록 스크린샷`,
  _ = `모든 아트워크`,
  _ = `공개 아트워크`,
  _ = `친구 공개 아트워크`,
  _ = `비공개 아트워크`,
  _ = `미등록 아트워크`,
  _ = `모든 동영상`,
  _ = `공개 동영상`,
  _ = `친구 공개 동영상`,
  _ = `비공개 동영상`,
  _ = `미등록 동영상`,
  _ = `스크린샷 관리`,
  _ = `아트워크 관리`,
  _ = `동영상 관리`,
  _ = `작업하려는 스크린샷을 선택하세요.`,
  _ = `작업하려는 아트워크를 선택하세요.`,
  _ = `작업하려는 동영상을 선택하세요.`,
  _ = `취소`,
  _ = `YouTube 동영상 추가`,
  _ = `YouTube 계정 연동`,
  _ = `YouTube 계정 연동 해제`,
  _ = `연동 해제`,
  _ = `정말로 YouTube 계정 연동을 해제할까요?`,
  _ = `Steam은 YouTube에서 가져온 사용자 데이터를 어떻게 사용하나요?`,
  _ = `YouTube 계정을 Steam에 연동하면 YouTube API 서비스가 사용됩니다. YouTube를 사용하고 YouTube 계정과 Steam 프로필을 연동하는 경우 %1$s 및 %2$s에 동의하는 것으로 간주됩니다.`,
  _ = `Steam은 YouTube API 서비스를 사용하여 사용자의 YouTube 계정을 인증하고 사용자가 YouTube에 게시한 동영상 목록에 접근합니다. YouTube 계정을 Steam에 연동하면 Steam은 사용자의 YouTube 계정 인증 토큰이 포함된 쿠키를 브라우저나 Steam 클라이언트에 저장합니다. 이 쿠키는 30일 후에 만료됩니다. Steam이 사용자의 YouTube 계정에 게시된 동영상 목록에 접근하는 경우, 이 데이터는 Steam에서 사용자에게 해당 목록을 표시하는 용도로만 사용됩니다.`,
  _ = `YouTube 계정에서 Steam으로 동영상을 게시하면 Steam은 동영상 ID와 동영상의 YouTube 계정 ID를 포함하여 Steam에 동영상을 표시하는 데 필요한 정보만 저장합니다. 이 데이터는 Steam에서 비디오를 표시하고 Steam에서 콘텐츠를 조정하는 용도로만 사용됩니다.`,
  _ = `%1$s에 대한 Steam의 접근 권한은 %2$s에서 취소할 수 있습니다.`,
  _ = `YouTube 서비스 약관`,
  _ = `Google 개인정보 처리방침`,
  _ = `승인된 데이터`,
  _ = `Google 보안 설정 페이지`,
  _ = `귀하의 동영상을 이제 Steam에서도.`,
  _ = `게임을 하면서 겪은 최고의 순간을 친구들과 공유해 보세요. 놀라운 순간, 정곡을 찌르는 평가, 도움을 주는 튜토리얼, 그리고 게임을 하면서 영감을 받아 직접 만든 작품을 업로드해 보세요.`,
  _ = `1. YouTube™ 계정을 Steam 프로필과 연동하세요.`,
  _ = `2. 프로필에 추가할 동영상을 선택하세요.`,
  _ = `3. Steam 친구들과 공유하고 자랑해 보세요.`,
  _ = `귀하의 YouTube 동영상에 접근`,
  _ = `귀하의 Steam 계정은 현재 %1$s YouTube 계정과 연동되어 있습니다.`,
  _ = `다른 계정과 연동하려면 먼저 이 계정의 연동을 해제하세요.`,
  _ = `연동 해제`,
  _ = `이 계정으로 계속하기`,
  _ = `YouTube 계정 연동 성공`,
  _ = `동영상 1개를 성공적으로 추가했습니다.`,
  _ = `동영상 %1$s개를 성공적으로 추가했습니다.`,
  _ = `YouTube 모음집에서 선택 가능한 동영상을 찾을 수 없었습니다.`,
  _ = `공개 상태로 설정되어 있고, 임베드를 허용하며, 사용자 이름으로 검색했을 때 표시되는 YouTube 동영상만 추가할 수 있습니다. 계정 연동을 위해 방금 동영상을 공개 상태로 변경했다면, 해당 동영상이 YouTube 검색 결과에 표시되기까지 다소의 시간이 소요될 수 있습니다.`,
  _ = `현재 Steam과 연동된 YouTube 계정은 %1$s 입니다.`,
  _ = `YouTube 계정을 변경하려면 여기를 클릭하세요.`,
  _ = `계정 변경`,
  _ = `1. 추가할 동영상을 선택하세요.`,
  _ = `%1$s 계정에서 추가할 수 있는 동영상 1개`,
  _ = `%2$s 계정에 있는 가장 최근 동영상 %1$s개 보기`,
  _ = `2. 동영상과 연관된 게임을 고르세요.`,
  _ = `먼저 왼쪽에서 동영상을 골라주세요(선택 사항).`,
  _ = `- 없음 / 그 외 (아래에 써주세요) -`,
  _ = `기타 또는 미등록`,
  _ = `3. 프로필에 추가하세요.`,
  _ = `동영상 추가`,
  _ = `참고: YouTube 계정의 동영상을 추가하려면 해당 동영상이 공개 상태로 설정되어 있어야 하며, 임베드를 허용해야 합니다. YouTube 계정에 방금 추가한 동영상이 목록에 표시되지 않는 경우, 아래 버튼을 클릭해 새로 고침하세요.`,
  _ = `YouTube 동영상 목록 다시 불러오기`,
  _ = `4. 완료`,
  _ = `완료했다면 '완료' 버튼을 클릭하고 프로필 페이지에 동영상이 표시되는지 확인하세요.`,
  _ = `등록 완료`,
  _ = `동영상 피드에 접근할 수 없습니다. 다시 시도해 주세요.`,
  _ = `아트워크 업로드`,
  _ = `스크린샷 업로드...`,
  _ = `전체 공개`,
  _ = `친구 공개`,
  _ = `비공개`,
  _ = `미등록`,
  _ = `삭제`,
  _ = `모두 선택`,
  _ = `등록 완료`,
  _ = `이 항목들을 삭제할까요?`,
  _ = `공개여부 변경`,
  _ = `%1$s 스크린샷이 Steam Cloud에서 삭제됩니다. 계속할까요?`,
  _ = `%1$s의 공개 여부를 %2$s로 변경합니다. 계속할까요?`,
  _ = `계속`,
  _ = `취소`,
  _ = `이런!`,
  _ = `선택된 항목이 없습니다.`,
  _ = `각 미리 보기의 모서리에 있는 확인란을 사용해 삭제할 항목을 선택하세요.`,
  _ = `확인`,
  _ = `공개 설정 업데이트 실패`,
  _ = `'전체 공개' 또는 '친구 공개'로 설정한 스크린샷 중 1개 이상을 업데이트하지 못했습니다. 비공개로 설정된 게임 스크린샷은 Steam 커뮤니티에 공유할 수 없으며 본인만 볼 수 있습니다.`,
  _ = `스포일러가 포함되었을 수 있습니다.`,
  _ = `이미지를 보려면 마우스를 올려보세요.`,
  _ = `일치하는 스크린샷이 없습니다.`,
  _ = `%1$s 님이 공개한 스크린샷이 없습니다.`,
  _ = `즐겨찾기한 스크린샷이 없습니다.`,
  _ = `%1$s 님이 공개한 즐겨찾기 스크린샷이 없습니다.`,
  _ = `Steam Cloud에 저장한 아트워크가 없습니다. 아트워크를 업로드하려면 관련 게임 허브의 아트워크 탭에서 오른쪽 상단의 '아트워크 업로드' 버튼을 클릭하거나 아래에 있는 '아트워크 업로드' 버튼을 클릭하세요.`,
  _ = `%1$s 님이 공개한 아트워크가 없습니다.`,
  _ = `즐겨찾기한 아트워크가 없습니다.`,
  _ = `%1$s 님의 공개한 즐겨찾기 아트워크가 없습니다.`,
  _ = `일치하는 동영상이 없습니다.`,
  _ = `%1$s 님이 공개한 동영상이 없습니다.`,
  _ = `즐겨찾기한 동영상이 없습니다.`,
  _ = `%1$s 님이 공개한 즐겨찾기 동영상이 없습니다.`,
  _ = `이 공개 상태로 설정된 스크린샷이 없습니다.`,
  _ = `Steam은 여러분이 좋아하는 게임의 스크린샷을 찍고 공유하기가 더욱 쉽도록 만들었습니다.`,
  _ = `Steam 오버레이를 지원하는 게임에서 단축키(기본 설정: F12)를 눌러 스크린샷을 찍으세요. 그런 다음 Steam 커뮤니티 프로필에 게시하거나 Facebook, Twitter, Reddit에 공유하여 친구들과 함께 즐길 수 있습니다.`,
  _ = `1GB의 개인 Steam Cloud 저장 공간을 통해 수천 장의 스크린샷을 업로드하여 최고의 순간을 친구들과 공유할 수 있습니다. 혼자 간직하고 싶다면 비공개로 설정할 수도 있습니다.`,
  _ = `%1$s 님의 콘텐츠`,
  _ = `%1$s 님의 즐겨찾기`,
  _ = {
    Moderation_SubjectTypeName_ForumPost: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    moderation_claim_report_count: _,
    moderation_claim_report_count_Plural: _,
    moderation_claim_subject_count: _,
    moderation_claim_subject_count_Plural: _,
    moderation_claim_n_reports_on_m_subjects: _,
    moderation_forumpost_summary: _,
    moderation_forumpost_summary_reports_fragment: _,
    moderation_forumpost_summary_reports_fragment_Plural: _,
    moderation_forumpost_summary_subjects_fragment: _,
    moderation_forumpost_summary_subjects_fragment_Plural: _,
    community_title: _,
    community_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    profile_games_list: _,
    profile_games_list_title: _,
    Market_Search_Title: _,
    Market_Item_Title: _,
    Market_Item_GenericTitle: _,
    Market_GenericTitle: _,
    profile_error_profilenotfound: _,
    profile_games_list_error_loadfailed: _,
    Error_RateLimited: _,
    Loading: _,
    GamesList_Header_Downloading: _,
    GamesList_Header_Paused: _,
    GamesList_Header_DownloadBytes: _,
    GamesList_Header_Achievements: _,
    GamesList_TimeRemaining: _,
    GamesList_Achievement_Fraction: _,
    GamesList_Uninstalling: _,
    GamesList_Button_UpdateRequired: _,
    GamesList_Button_Uninstall: _,
    GamesList_Button_Download: _,
    GamesList_Button_Pause: _,
    GamesList_Button_Resume: _,
    GamesList_Button_Uninstalling: _,
    GamesList_Button_Cancel: _,
    GamesList_PrivacySettings_Tooltip: _,
    GamesList_Filter_Placeholder: _,
    GamesList_Filter_BothOwned: _,
    GamesList_Sort_HoursPlayed: _,
    GamesList_Sort_Name: _,
    GamesList_Sort_AchievementCompletion: _,
    GamesList_Header_TotalPlayed: _,
    GamesList_Header_LastPlayed: _,
    GamesList_Header_TwoWeeks: _,
    GamesList_MenuLabel_GameInfo: _,
    GamesList_MenuLabel_RemoteDownload: _,
    GamesList_Header_RemoteDownload: _,
    GamesList_Header_RemoteDownloadStatus: _,
    GamesList_RemoteDownload_NoConnection: _,
    GamesList_RemoteDownload_Help: _,
    GamesList_RemoteDownload_ReadTheFAQ: _,
    GamesList_RemoteDownload_Info: _,
    GamesList_RemoteDownload_LearnMore: _,
    GamesList_RemoteDownload_NoRemoteControl: _,
    GamesList_RemoteDownload_UninstallConfirm: _,
    GamesList_Client_Indicator: _,
    GamesList_Tab_RecentlyPlayed: _,
    GamesList_Tab_AllGames: _,
    GamesList_Tab_PerfectGames: _,
    GamesList_Tab_Reviews: _,
    GamesList_Tab_Followed: _,
    GamesList_Tab_Wishlist: _,
    Perfect_Game_Description: _,
    GamesList_PerfectGames_Description: _,
    GamesList_Achievement_Unlock_Percentage: _,
    Community_StorePage: _,
    Community_Forums: _,
    Community_Groups: _,
    Community_OfficialWebsite: _,
    Community_News: _,
    Community_UsersAchievementsFirstPerson: _,
    Community_UsersAchievements: _,
    Community_UsersStats: _,
    Community_GamePersonalData: _,
    Community_UsersLeaderboardsFirstPerson: _,
    Community_UsersLeaderboards: _,
    Community_GlobalAchievements: _,
    Community_GlobalLeaderboards: _,
    Community_GameStats: _,
    Community_GameContent: _,
    Community_GameStatsFirstPerson: _,
    Community_GameContentFirstPerson: _,
    Community_GameLinks: _,
    Community_ScreenshotsMenuItemFirstPerson: _,
    Community_ScreenshotsMenuItemThirdPerson: _,
    Community_FriendsWhoPlayMenuItemFirstPerson: _,
    Community_TradingCardsMenuItemFirstPerson: _,
    Community_ReviewMenuItemFirstPerson: _,
    Community_ReviewMenuItemThirdPerson: _,
    Community_GameHubMenuItem: _,
    Community_GameNotesFirstPerson: _,
    Playtime_Hours: _,
    Playtime_Minutes: _,
    AppPrivacy_MarkAsPrivate: _,
    AppPrivacy_UnmarkAsPrivate: _,
    AppPrivacy_Explanation: _,
    footer_legal_notice: _,
    footer_geodata_notice: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_accessibility: _,
    profiletabs_currentbans: _,
    profiletabs_communitymessages: _,
    profiletabs_reportedcontent: _,
    profiletabs_moderatedcontent: _,
    reportedcontent_description: _,
    moderatedcontent_description: _,
    reportedcontent_lastupdated: _,
    SharedFiles_ItemDownload: _,
    SharedFiles_PublicComments: _,
    SharedFiles_DeveloperComments: _,
    Workshop_DeveloperThreadDesc: _,
    Workshop_DeveloperThreadDisclaimerText: _,
    Workshop_ImageSize: _,
    SharedFiles_Media_ViewAppScreenshots: _,
    SharedFiles_Media_ViewAppFanArt: _,
    SharedFiles_Media_ViewAppVideos: _,
    SharedFiles_ItemEditText_Text_Caption: _,
    SharedFiles_OwnerControl_EditCaption: _,
    SharedFiles_AddSpoilerTag: _,
    SharedFiles_RemoveSpoilerTag: _,
    SharedFiles_SpoilerTagInstructions: _,
    SharedFiles_SpoilerTagsExpire: _,
    SharedFiles_Stats_TaggedUsers: _,
    SharedFiles_Stats_TaggedWorkshopItems: _,
    SharedFiles_RemoveSelfTag_Tooltip: _,
    Screenshots_Location: _,
    SharedFiles_Tags: _,
    SharedFiles_WaitingForIntegratedGuide: _,
    Workshop_Subscribe_IntegratedGuide: _,
    SharedFiles_Guide_Index: _,
    SharedFiles_Guide_Overview: _,
    SharedFiles_Guide_Comments: _,
    SharedFiles_Item_Edit_Link: _,
    Community_RemoveLink_BeWary: _,
    Community_RemoveLink_Tooltip: _,
    SharedFiles_ManageGuide_Contents: _,
    SharedFiles_ManageGuide_Contents_Desc: _,
    SharedFiles_ManageGuide_Required: _,
    SharedFiles_ManageGuide_NoSubSections: _,
    SharedFiles_ManageGuide_AddSection: _,
    SharedFiles_ManageGuide_NoSectionTitle: _,
    SharedFiles_ManageGuide_EditThisSection: _,
    SharedFiles_ManageGuide_DeleteThisSection: _,
    SharedFiles_ManageGuide_RemoveSectionConfirm: _,
    SharedFiles_ManageGuide_Images: _,
    SharedFiles_ManageGuide_Images_Desc: _,
    SharedFiles_ManageGuide_NoPreviewImages: _,
    SharedFiles_ManageGuide_Contributors: _,
    SharedFiles_ManageGuide_Contributors_Desc: _,
    SharedFiles_ManageGuide_NoContributors: _,
    SharedFiles_ManageGuide_AddContributor: _,
    SharedFiles_ManageGuide_Preview: _,
    SharedFiles_ManageGuide_EditSubSection: _,
    SharedFiles_ManageGuide_SubSectionTitle: _,
    SharedFiles_ManageGuide_SubSectionContents: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Edit: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Preview: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Changes: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Desc: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Insert: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Delete: _,
    SharedFiles_ManageGuide_SubSectionContentChanged: _,
    SharedFiles_ManageGuide_SubSectionContentChanged_CancelConfirm: _,
    SharedFiles_ManageGuide_SubSectionContentSaved: _,
    SharedFiles_ManageGuide_Save: _,
    SharedFiles_ManageGuide_Cancel: _,
    SharedFiles_ManageGuide_Screenshots: _,
    SharedFiles_ManageGuide_Videos: _,
    SharedFiles_ManageGuide_SubImages: _,
    SharedFiles_ManageGuide_SubScreenshots: _,
    SharedFiles_ManageGuide_SubVideos: _,
    SharedFiles_ManageGuide_ImageInsertionOptions: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_Size: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeThumb: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeFull: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeOriginal: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_Layout: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutLeft: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutRight: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutInline: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Left: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Right: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Full: _,
    SharedFiles_ManageGuide_InsertImage: _,
    SharedFiles_ManageGuide_InsertYouTubeVideo: _,
    SharedFiles_ManageGuide_PromptYouTubeUrl: _,
    Discussions_FormattingHelp_Quote: _,
    Discussions_FormattingHelp_Spoiler: _,
    SharedFiles_ItemEditText_ErrorNoTitle: _,
    SharedFiles_OwnerControl_BackGuide: _,
    empty_no_comma_following: ``,
    SharedFiles_WorkshopItemsTagged: _,
    SharedFiles_And_N_More: _,
    Workshop_ItemModalViewDetails: _,
    Workshop_ItemModalViewCountDetails: _,
    Profile_Screenshots: _,
    Profile_Images: _,
    Profile_Videos: _,
    Profile_Workshop_Items: _,
    SharedFiles_Tab_Merchandise: _,
    Profile_Collections: _,
    Profile_Guides: _,
    SharedFiles_SharedFiles_Items: _,
    SharedFiles_SharedFiles_Collections: _,
    SharedFiles_SharedFiles_Guides: _,
    SharedFiles_Favorites: _,
    SharedFiles_Subscriptions: _,
    SharedFiles_Browse_MyFiles_Played: _,
    SharedFiles_FilterByGame: _,
    Profile_SharedFiles_AllGames: _,
    Profile_SharedFiles_SelectAGame: _,
    SharedFiles_Browse_MyFiles_Items: _,
    SharedFiles_Browse_MyFiles_Favorites: _,
    SharedFiles_Browse_MyFiles_Subscriptions: _,
    SharedFiles_Browse_MyFiles_Sort_CreationOrder: _,
    SharedFiles_Browse_MyFiles_Sort_Alpha: _,
    SharedFiles_Browse_MyFiles_Sort_LastUpdated: _,
    SharedFiles_Browse_MyFiles_Sort_Subscribed: _,
    SharedFiles_Browse_MyFiles_Sort_Favorited: _,
    SharedFiles_TagsSearch: _,
    SharedFiles_ByAuthor: _,
    Workshop_BrowsePaging: _,
    Workshop_NoItems: _,
    SharedFiles_UserList_BrowsePaging: _,
    SharedFiles_UserList_LastUpdated: _,
    SharedFiles_Favorites_Subscribed: _,
    SharedFiles_Favorites_NowUnsubscribed: _,
    SharedFiles_Subscription_Subscribed: _,
    SharedFiles_Subscription_NowUnsubscribed: _,
    Workshop_HasLinkedItems: _,
    Workshop_PaymentInfo_NotCreated: _,
    Workshop_PaymentInfo_Rejected: _,
    Workshop_SplitsAcceptTheseDesc1: _,
    Workshop_SplitsAcceptTheseDesc2: _,
    Workshop_SplitsPercentage: _,
    Profile_YourWorkshop: _,
    CommunityFollower_Description: _,
    CommunityFollower_Description_Yours: _,
    CommunityFollower_One_Follower: _,
    CommunityFollower_NumFollowers: _,
    CommunityFollower_FollowUser: _,
    CommunityFollower_FollowingUser: _,
    CommunityFollower_UnfollowUser: _,
    Workshop_ViewYourRevenue: _,
    Workshop_ViewYourRevenue_desc: _,
    Workshop_Link_PaymentInfo: _,
    Workshop_Link_LegalAgreement: _,
    SharedFiles_UnsubscribeAll_Btn: _,
    SharedFiles_UnsubscribeAll_Confirm_Title: _,
    SharedFiles_UnsubscribeAll_Confirm_Desc: _,
    SharedFiles_UnsubscribeAll_Confirm_App_Desc: _,
    SharedFiles_SaveSubscribedToCollection_Btn: _,
    SharedFiles_SaveSubscribedToCollection_Title: _,
    SharedFiles_SaveSubscribedToCollection_Desc: _,
    SharedFiles_SaveSubscribedToCollection_New: _,
    SharedFiles_SaveSubscribedToCollection_NewDesc: _,
    SharedFiles_SaveSubscribedToCollection_Existing: _,
    SharedFiles_SaveSubscribedToCollection_ExistingDesc: _,
    SharedFiles_SaveSubscribedToCollection_NoExistingCollections: _,
    SharedFiles_AdminTags: _,
    SharedFiles_SearchedForFileType_WebGuide: _,
    SharedFiles_SearchedForFileType_IntegratedGuide: _,
    SharedFiles_Dota2_IntegratedGuide: _,
    SharedFiles_Dota2_IntegratedGuide_Desc: _,
    AppHub_Guides_IntegratedGuides_Desc: _,
    AppHub_Guides_PopularCategories: _,
    AppHub_Guides_IntegratedGuides: _,
    AppHub_Guides_YourFavorites: _,
    AppHub_Guides_MostPopularThisWeek: _,
    AppHub_Guides_MostPopularThisWeek_Desc: _,
    AppHub_Guides_ViewAll: _,
    AppHub_Guides_NumGuides_Singular: _,
    AppHub_Guides_NumGuides_Plural: _,
    AppHub_Guides_GuidesYouHaveMade: _,
    AppHub_Guides_MoreInfo_Title: _,
    AppHub_Guides_MoreInfo_button: _,
    Workshop_BrowseBy: _,
    SharedFiles_Browse_GuideHome: `홈`,
    SharedFiles_CreateGuide: _,
    SharedFiles_MustOwnAppToCreateGuide: _,
    SharedFiles_NoGuides_Title: _,
    SharedFiles_NoGuides_Desc1: _,
    SharedFiles_NoGuides_Desc2: _,
    SharedFiles_BrowseGuide_subtitle_nolink: _,
    SharedFiles_BrowseGuide_createNewBtnLabel: _,
    Community_Screenshots: _,
    Community_Images: _,
    Community_Videos: _,
    Paging_ShowingXtoYofZ: _,
    AppHubHome_BackToTop: _,
    Screenshots_Viewing: _,
    Profile_SharedFiles_ImageWallView: _,
    Profile_SharedFiles_GridView: _,
    Profile_SharedFiles_MostPopular: _,
    Profile_SharedFiles_NewestFirst: _,
    Profile_SharedFiles_OldestFirst: _,
    Screenshots_AllYourScreenshots: _,
    Screenshots_YourPublicScreenshots: _,
    Screenshots_YourFriendsOnlyScreenshots: _,
    Screenshots_YourPrivateScreenshots: _,
    Screenshots_YourUnlistedScreenshots: _,
    Images_AllYourImages: _,
    Images_YourPublicImages: _,
    Images_YourFriendsOnlyImages: _,
    Images_YourPrivateImages: _,
    Images_YourUnlistedImages: _,
    Videos_AllYourVideos: _,
    Videos_YourPublicVideos: _,
    Videos_YourFriendsOnlyVideos: _,
    Videos_YourPrivateVideos: _,
    Videos_YourUnlistedVideos: _,
    Screenshots_Manage: _,
    Images_Manage: _,
    Videos_Manage: _,
    Screenshots_SelectScreenshots: _,
    Images_SelectImages: _,
    Videos_SelectVideos: _,
    Videos_Cancel: _,
    Videos_AddFromYouTube: _,
    Videos_LinkYouTubeAcct: _,
    Videos_UnlinkYouTubeAcct: _,
    Videos_UnlinkButton: _,
    Videos_UnlinkConfirmText: _,
    Videos_Privacy: _,
    Videos_YoutubeTerms_1: _,
    Videos_YoutubeTerms_2: _,
    Videos_YoutubeTerms_3: _,
    Videos_YoutubeTerms_4: _,
    Videos_YoutubeTermsLink_TermsOfService: _,
    Videos_YoutubeTermsLink_PrivacyPolicy: _,
    Videos_YoutubeTermsLink_AuthorizedData: _,
    Videos_YoutubeTermsLink_SecuritySettings: _,
    Videos_NowOnSteam: _,
    Videos_ShareDescription: _,
    Videos_Desc1: _,
    Videos_Desc2: _,
    Videos_Desc3: _,
    Videos_AccessYourYouTubeVideos: _,
    Videos_CurrentlyLinkedTo: _,
    Videos_UnlinkToAddAnother: _,
    Videos_UnlinkAcct: _,
    Videos_ContinueWithAcct: _,
    Videos_SuccessfullyLinkedYouTube: _,
    Videos_SuccessfullyAddedSingular: _,
    Videos_SuccessfullyAddedPlural: _,
    Videos_NoVideosMsg1: _,
    Videos_NoVideosMsg2: _,
    Videos_CurrentlyLinkedMsg: _,
    Videos_ClickHereToChange: _,
    Videos_ChangeAccount: _,
    Videos_AddStep1: _,
    Videos_AvailCountSingular: _,
    Videos_AvailCountPlural: _,
    Videos_AddStep2: _,
    Videos_AddStep2Note: _,
    Videos_OptionNoneOther: _,
    Videos_OtherUnlisted: _,
    Videos_AddStep3: _,
    Videos_AddVideo: _,
    Videos_AddNote2: _,
    Videos_Refresh: _,
    Videos_AddStep4: _,
    Videos_AddNote4: _,
    Videos_AddDone: _,
    Videos_IssuesAccessing: _,
    Images_Upload: _,
    Screenshots_Upload: _,
    Screenshots_MakePublic: _,
    Screenshots_MakeFriendsOnly: _,
    Screenshots_MakePrivate: _,
    Screenshots_MakeUnlisted: _,
    Screenshots_Delete: _,
    Screenshots_SelectAll: _,
    Screenshots_Done: _,
    Screenshots_DeleteScreenshots: _,
    Screenshots_UpdatePrivacy: _,
    Screenshots_AreYouSureDelete: _,
    Screenshots_AreYouSurePrivacyChange: _,
    Screenshots_Continue: _,
    Screenshots_Cancel: _,
    Screenshots_Oops: _,
    Screenshots_NoneSelected: _,
    Screenshots_SelectScreenshotsToDelete: _,
    Screenshots_OK: _,
    Screenshots_VisUpdateFailed: _,
    Screenshots_VisUpdateFailedMessage: _,
    Blotter_PotentialSpoilers: _,
    Blotter_RevealImage: _,
    Profile_SharedFiles_NoScreenshotsSelf: _,
    Profile_SharedFiles_NoScreenshotsForYou: _,
    Profile_SharedFiles_NoScreenshotsFavoritesSelf: _,
    Profile_SharedFiles_NoScreenshotsFavoritesForYou: _,
    Profile_SharedFiles_NoImagesSelf: _,
    Profile_SharedFiles_NoImagesForYou: _,
    Profile_SharedFiles_NoImagesFavoritesSelf: _,
    Profile_SharedFiles_NoImagesFavoritesForYou: _,
    Profile_SharedFiles_NoVideosSelf: _,
    Profile_SharedFiles_NoVideosForYou: _,
    Profile_SharedFiles_NoVideosFavoritesSelf: _,
    Profile_SharedFiles_NoVideosFavoritesForYou: _,
    Profile_SharedFiles_NoScreenshotsThisVisibility: _,
    Screenshots_SteamHasThem: _,
    Screenshots_Instructions1: _,
    Screenshots_Instructions2: _,
    Profile_SharedFiles_By: _,
    Profile_SharedFiles_FavoritedBy: _,
  };
export {
  _ as AppHubHome_BackToTop,
  _ as AppHub_Guides_GuidesYouHaveMade,
  _ as AppHub_Guides_IntegratedGuides,
  _ as AppHub_Guides_IntegratedGuides_Desc,
  _ as AppHub_Guides_MoreInfo_Title,
  _ as AppHub_Guides_MoreInfo_button,
  _ as AppHub_Guides_MostPopularThisWeek,
  _ as AppHub_Guides_MostPopularThisWeek_Desc,
  _ as AppHub_Guides_NumGuides_Plural,
  _ as AppHub_Guides_NumGuides_Singular,
  _ as AppHub_Guides_PopularCategories,
  _ as AppHub_Guides_ViewAll,
  _ as AppHub_Guides_YourFavorites,
  _ as AppPrivacy_Explanation,
  _ as AppPrivacy_MarkAsPrivate,
  _ as AppPrivacy_UnmarkAsPrivate,
  _ as Blotter_PotentialSpoilers,
  _ as Blotter_RevealImage,
  _ as CommunityFollower_Description,
  _ as CommunityFollower_Description_Yours,
  _ as CommunityFollower_FollowUser,
  _ as CommunityFollower_FollowingUser,
  _ as CommunityFollower_NumFollowers,
  _ as CommunityFollower_One_Follower,
  _ as CommunityFollower_UnfollowUser,
  _ as Community_Forums,
  _ as Community_FriendsWhoPlayMenuItemFirstPerson,
  _ as Community_GameContent,
  _ as Community_GameContentFirstPerson,
  _ as Community_GameHubMenuItem,
  _ as Community_GameLinks,
  _ as Community_GameNotesFirstPerson,
  _ as Community_GamePersonalData,
  _ as Community_GameStats,
  _ as Community_GameStatsFirstPerson,
  _ as Community_GlobalAchievements,
  _ as Community_GlobalLeaderboards,
  _ as Community_Groups,
  _ as Community_Images,
  _ as Community_News,
  _ as Community_OfficialWebsite,
  _ as Community_RemoveLink_BeWary,
  _ as Community_RemoveLink_Tooltip,
  _ as Community_ReviewMenuItemFirstPerson,
  _ as Community_ReviewMenuItemThirdPerson,
  _ as Community_Screenshots,
  _ as Community_ScreenshotsMenuItemFirstPerson,
  _ as Community_ScreenshotsMenuItemThirdPerson,
  _ as Community_StorePage,
  _ as Community_TradingCardsMenuItemFirstPerson,
  _ as Community_UsersAchievements,
  _ as Community_UsersAchievementsFirstPerson,
  _ as Community_UsersLeaderboards,
  _ as Community_UsersLeaderboardsFirstPerson,
  _ as Community_UsersStats,
  _ as Community_Videos,
  _ as Discussions_FormattingHelp_Quote,
  _ as Discussions_FormattingHelp_Spoiler,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as GamesList_Achievement_Fraction,
  _ as GamesList_Achievement_Unlock_Percentage,
  _ as GamesList_Button_Cancel,
  _ as GamesList_Button_Download,
  _ as GamesList_Button_Pause,
  _ as GamesList_Button_Resume,
  _ as GamesList_Button_Uninstall,
  _ as GamesList_Button_Uninstalling,
  _ as GamesList_Button_UpdateRequired,
  _ as GamesList_Client_Indicator,
  _ as GamesList_Filter_BothOwned,
  _ as GamesList_Filter_Placeholder,
  _ as GamesList_Header_Achievements,
  _ as GamesList_Header_DownloadBytes,
  _ as GamesList_Header_Downloading,
  _ as GamesList_Header_LastPlayed,
  _ as GamesList_Header_Paused,
  _ as GamesList_Header_RemoteDownload,
  _ as GamesList_Header_RemoteDownloadStatus,
  _ as GamesList_Header_TotalPlayed,
  _ as GamesList_Header_TwoWeeks,
  _ as GamesList_MenuLabel_GameInfo,
  _ as GamesList_MenuLabel_RemoteDownload,
  _ as GamesList_PerfectGames_Description,
  _ as GamesList_PrivacySettings_Tooltip,
  _ as GamesList_RemoteDownload_Help,
  _ as GamesList_RemoteDownload_Info,
  _ as GamesList_RemoteDownload_LearnMore,
  _ as GamesList_RemoteDownload_NoConnection,
  _ as GamesList_RemoteDownload_NoRemoteControl,
  _ as GamesList_RemoteDownload_ReadTheFAQ,
  _ as GamesList_RemoteDownload_UninstallConfirm,
  _ as GamesList_Sort_AchievementCompletion,
  _ as GamesList_Sort_HoursPlayed,
  _ as GamesList_Sort_Name,
  _ as GamesList_Tab_AllGames,
  _ as GamesList_Tab_Followed,
  _ as GamesList_Tab_PerfectGames,
  _ as GamesList_Tab_RecentlyPlayed,
  _ as GamesList_Tab_Reviews,
  _ as GamesList_Tab_Wishlist,
  _ as GamesList_TimeRemaining,
  _ as GamesList_Uninstalling,
  _ as Images_AllYourImages,
  _ as Images_Manage,
  _ as Images_SelectImages,
  _ as Images_Upload,
  _ as Images_YourFriendsOnlyImages,
  _ as Images_YourPrivateImages,
  _ as Images_YourPublicImages,
  _ as Images_YourUnlistedImages,
  _ as Loading,
  _ as Market_GenericTitle,
  _ as Market_Item_GenericTitle,
  _ as Market_Item_Title,
  _ as Market_Search_Title,
  _ as Moderation_SubjectTypeName_ForumPost,
  _ as Paging_ShowingXtoYofZ,
  _ as Perfect_Game_Description,
  _ as Playtime_Hours,
  _ as Playtime_Minutes,
  _ as Profile_Collections,
  _ as Profile_Guides,
  _ as Profile_Images,
  _ as Profile_Screenshots,
  _ as Profile_SharedFiles_AllGames,
  _ as Profile_SharedFiles_By,
  _ as Profile_SharedFiles_FavoritedBy,
  _ as Profile_SharedFiles_GridView,
  _ as Profile_SharedFiles_ImageWallView,
  _ as Profile_SharedFiles_MostPopular,
  _ as Profile_SharedFiles_NewestFirst,
  _ as Profile_SharedFiles_NoImagesFavoritesForYou,
  _ as Profile_SharedFiles_NoImagesFavoritesSelf,
  _ as Profile_SharedFiles_NoImagesForYou,
  _ as Profile_SharedFiles_NoImagesSelf,
  _ as Profile_SharedFiles_NoScreenshotsFavoritesForYou,
  _ as Profile_SharedFiles_NoScreenshotsFavoritesSelf,
  _ as Profile_SharedFiles_NoScreenshotsForYou,
  _ as Profile_SharedFiles_NoScreenshotsSelf,
  _ as Profile_SharedFiles_NoScreenshotsThisVisibility,
  _ as Profile_SharedFiles_NoVideosFavoritesForYou,
  _ as Profile_SharedFiles_NoVideosFavoritesSelf,
  _ as Profile_SharedFiles_NoVideosForYou,
  _ as Profile_SharedFiles_NoVideosSelf,
  _ as Profile_SharedFiles_OldestFirst,
  _ as Profile_SharedFiles_SelectAGame,
  _ as Profile_Videos,
  _ as Profile_Workshop_Items,
  _ as Profile_YourWorkshop,
  _ as Screenshots_AllYourScreenshots,
  _ as Screenshots_AreYouSureDelete,
  _ as Screenshots_AreYouSurePrivacyChange,
  _ as Screenshots_Cancel,
  _ as Screenshots_Continue,
  _ as Screenshots_Delete,
  _ as Screenshots_DeleteScreenshots,
  _ as Screenshots_Done,
  _ as Screenshots_Instructions1,
  _ as Screenshots_Instructions2,
  _ as Screenshots_Location,
  _ as Screenshots_MakeFriendsOnly,
  _ as Screenshots_MakePrivate,
  _ as Screenshots_MakePublic,
  _ as Screenshots_MakeUnlisted,
  _ as Screenshots_Manage,
  _ as Screenshots_NoneSelected,
  _ as Screenshots_OK,
  _ as Screenshots_Oops,
  _ as Screenshots_SelectAll,
  _ as Screenshots_SelectScreenshots,
  _ as Screenshots_SelectScreenshotsToDelete,
  _ as Screenshots_SteamHasThem,
  _ as Screenshots_UpdatePrivacy,
  _ as Screenshots_Upload,
  _ as Screenshots_Viewing,
  _ as Screenshots_VisUpdateFailed,
  _ as Screenshots_VisUpdateFailedMessage,
  _ as Screenshots_YourFriendsOnlyScreenshots,
  _ as Screenshots_YourPrivateScreenshots,
  _ as Screenshots_YourPublicScreenshots,
  _ as Screenshots_YourUnlistedScreenshots,
  _ as SharedFiles_AddSpoilerTag,
  _ as SharedFiles_AdminTags,
  _ as SharedFiles_And_N_More,
  _ as SharedFiles_BrowseGuide_createNewBtnLabel,
  _ as SharedFiles_BrowseGuide_subtitle_nolink,
  _ as SharedFiles_Browse_GuideHome,
  _ as SharedFiles_Browse_MyFiles_Favorites,
  _ as SharedFiles_Browse_MyFiles_Items,
  _ as SharedFiles_Browse_MyFiles_Played,
  _ as SharedFiles_Browse_MyFiles_Sort_Alpha,
  _ as SharedFiles_Browse_MyFiles_Sort_CreationOrder,
  _ as SharedFiles_Browse_MyFiles_Sort_Favorited,
  _ as SharedFiles_Browse_MyFiles_Sort_LastUpdated,
  _ as SharedFiles_Browse_MyFiles_Sort_Subscribed,
  _ as SharedFiles_Browse_MyFiles_Subscriptions,
  _ as SharedFiles_ByAuthor,
  _ as SharedFiles_CreateGuide,
  _ as SharedFiles_DeveloperComments,
  _ as SharedFiles_Dota2_IntegratedGuide,
  _ as SharedFiles_Dota2_IntegratedGuide_Desc,
  _ as SharedFiles_Favorites,
  _ as SharedFiles_Favorites_NowUnsubscribed,
  _ as SharedFiles_Favorites_Subscribed,
  _ as SharedFiles_FilterByGame,
  _ as SharedFiles_Guide_Comments,
  _ as SharedFiles_Guide_Index,
  _ as SharedFiles_Guide_Overview,
  _ as SharedFiles_ItemDownload,
  _ as SharedFiles_ItemEditText_ErrorNoTitle,
  _ as SharedFiles_ItemEditText_Text_Caption,
  _ as SharedFiles_Item_Edit_Link,
  _ as SharedFiles_ManageGuide_AddContributor,
  _ as SharedFiles_ManageGuide_AddSection,
  _ as SharedFiles_ManageGuide_Cancel,
  _ as SharedFiles_ManageGuide_Contents,
  _ as SharedFiles_ManageGuide_Contents_Desc,
  _ as SharedFiles_ManageGuide_Contributors,
  _ as SharedFiles_ManageGuide_Contributors_Desc,
  _ as SharedFiles_ManageGuide_DeleteThisSection,
  _ as SharedFiles_ManageGuide_EditSubSection,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Delete,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Desc,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Insert,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Changes,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Edit,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Preview,
  _ as SharedFiles_ManageGuide_EditThisSection,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_Layout,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutInline,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutLeft,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutRight,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_Size,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeFull,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeOriginal,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeThumb,
  _ as SharedFiles_ManageGuide_Images,
  _ as SharedFiles_ManageGuide_Images_Desc,
  _ as SharedFiles_ManageGuide_InsertImage,
  _ as SharedFiles_ManageGuide_InsertYouTubeVideo,
  _ as SharedFiles_ManageGuide_NoContributors,
  _ as SharedFiles_ManageGuide_NoPreviewImages,
  _ as SharedFiles_ManageGuide_NoSectionTitle,
  _ as SharedFiles_ManageGuide_NoSubSections,
  _ as SharedFiles_ManageGuide_Preview,
  _ as SharedFiles_ManageGuide_PromptYouTubeUrl,
  _ as SharedFiles_ManageGuide_RemoveSectionConfirm,
  _ as SharedFiles_ManageGuide_Required,
  _ as SharedFiles_ManageGuide_Save,
  _ as SharedFiles_ManageGuide_Screenshots,
  _ as SharedFiles_ManageGuide_SubImages,
  _ as SharedFiles_ManageGuide_SubScreenshots,
  _ as SharedFiles_ManageGuide_SubSectionContentChanged,
  _ as SharedFiles_ManageGuide_SubSectionContentChanged_CancelConfirm,
  _ as SharedFiles_ManageGuide_SubSectionContentSaved,
  _ as SharedFiles_ManageGuide_SubSectionContents,
  _ as SharedFiles_ManageGuide_SubSectionTitle,
  _ as SharedFiles_ManageGuide_SubVideos,
  _ as SharedFiles_ManageGuide_Videos,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Full,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Left,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Right,
  _ as SharedFiles_Media_ViewAppFanArt,
  _ as SharedFiles_Media_ViewAppScreenshots,
  _ as SharedFiles_Media_ViewAppVideos,
  _ as SharedFiles_MustOwnAppToCreateGuide,
  _ as SharedFiles_NoGuides_Desc1,
  _ as SharedFiles_NoGuides_Desc2,
  _ as SharedFiles_NoGuides_Title,
  _ as SharedFiles_OwnerControl_BackGuide,
  _ as SharedFiles_OwnerControl_EditCaption,
  _ as SharedFiles_PublicComments,
  _ as SharedFiles_RemoveSelfTag_Tooltip,
  _ as SharedFiles_RemoveSpoilerTag,
  _ as SharedFiles_SaveSubscribedToCollection_Btn,
  _ as SharedFiles_SaveSubscribedToCollection_Desc,
  _ as SharedFiles_SaveSubscribedToCollection_Existing,
  _ as SharedFiles_SaveSubscribedToCollection_ExistingDesc,
  _ as SharedFiles_SaveSubscribedToCollection_New,
  _ as SharedFiles_SaveSubscribedToCollection_NewDesc,
  _ as SharedFiles_SaveSubscribedToCollection_NoExistingCollections,
  _ as SharedFiles_SaveSubscribedToCollection_Title,
  _ as SharedFiles_SearchedForFileType_IntegratedGuide,
  _ as SharedFiles_SearchedForFileType_WebGuide,
  _ as SharedFiles_SharedFiles_Collections,
  _ as SharedFiles_SharedFiles_Guides,
  _ as SharedFiles_SharedFiles_Items,
  _ as SharedFiles_SpoilerTagInstructions,
  _ as SharedFiles_SpoilerTagsExpire,
  _ as SharedFiles_Stats_TaggedUsers,
  _ as SharedFiles_Stats_TaggedWorkshopItems,
  _ as SharedFiles_Subscription_NowUnsubscribed,
  _ as SharedFiles_Subscription_Subscribed,
  _ as SharedFiles_Subscriptions,
  _ as SharedFiles_Tab_Merchandise,
  _ as SharedFiles_Tags,
  _ as SharedFiles_TagsSearch,
  _ as SharedFiles_UnsubscribeAll_Btn,
  _ as SharedFiles_UnsubscribeAll_Confirm_App_Desc,
  _ as SharedFiles_UnsubscribeAll_Confirm_Desc,
  _ as SharedFiles_UnsubscribeAll_Confirm_Title,
  _ as SharedFiles_UserList_BrowsePaging,
  _ as SharedFiles_UserList_LastUpdated,
  _ as SharedFiles_WaitingForIntegratedGuide,
  _ as SharedFiles_WorkshopItemsTagged,
  _ as Videos_AccessYourYouTubeVideos,
  _ as Videos_AddDone,
  _ as Videos_AddFromYouTube,
  _ as Videos_AddNote2,
  _ as Videos_AddNote4,
  _ as Videos_AddStep1,
  _ as Videos_AddStep2,
  _ as Videos_AddStep2Note,
  _ as Videos_AddStep3,
  _ as Videos_AddStep4,
  _ as Videos_AddVideo,
  _ as Videos_AllYourVideos,
  _ as Videos_AvailCountPlural,
  _ as Videos_AvailCountSingular,
  _ as Videos_Cancel,
  _ as Videos_ChangeAccount,
  _ as Videos_ClickHereToChange,
  _ as Videos_ContinueWithAcct,
  _ as Videos_CurrentlyLinkedMsg,
  _ as Videos_CurrentlyLinkedTo,
  _ as Videos_Desc1,
  _ as Videos_Desc2,
  _ as Videos_Desc3,
  _ as Videos_IssuesAccessing,
  _ as Videos_LinkYouTubeAcct,
  _ as Videos_Manage,
  _ as Videos_NoVideosMsg1,
  _ as Videos_NoVideosMsg2,
  _ as Videos_NowOnSteam,
  _ as Videos_OptionNoneOther,
  _ as Videos_OtherUnlisted,
  _ as Videos_Privacy,
  _ as Videos_Refresh,
  _ as Videos_SelectVideos,
  _ as Videos_ShareDescription,
  _ as Videos_SuccessfullyAddedPlural,
  _ as Videos_SuccessfullyAddedSingular,
  _ as Videos_SuccessfullyLinkedYouTube,
  _ as Videos_UnlinkAcct,
  _ as Videos_UnlinkButton,
  _ as Videos_UnlinkConfirmText,
  _ as Videos_UnlinkToAddAnother,
  _ as Videos_UnlinkYouTubeAcct,
  _ as Videos_YourFriendsOnlyVideos,
  _ as Videos_YourPrivateVideos,
  _ as Videos_YourPublicVideos,
  _ as Videos_YourUnlistedVideos,
  _ as Videos_YoutubeTermsLink_AuthorizedData,
  _ as Videos_YoutubeTermsLink_PrivacyPolicy,
  _ as Videos_YoutubeTermsLink_SecuritySettings,
  _ as Videos_YoutubeTermsLink_TermsOfService,
  _ as Videos_YoutubeTerms_1,
  _ as Videos_YoutubeTerms_2,
  _ as Videos_YoutubeTerms_3,
  _ as Videos_YoutubeTerms_4,
  _ as Workshop_BrowseBy,
  _ as Workshop_BrowsePaging,
  _ as Workshop_DeveloperThreadDesc,
  _ as Workshop_DeveloperThreadDisclaimerText,
  _ as Workshop_HasLinkedItems,
  _ as Workshop_ImageSize,
  _ as Workshop_ItemModalViewCountDetails,
  _ as Workshop_ItemModalViewDetails,
  _ as Workshop_Link_LegalAgreement,
  _ as Workshop_Link_PaymentInfo,
  _ as Workshop_NoItems,
  _ as Workshop_PaymentInfo_NotCreated,
  _ as Workshop_PaymentInfo_Rejected,
  _ as Workshop_SplitsAcceptTheseDesc1,
  _ as Workshop_SplitsAcceptTheseDesc2,
  _ as Workshop_SplitsPercentage,
  _ as Workshop_Subscribe_IntegratedGuide,
  _ as Workshop_ViewYourRevenue,
  _ as Workshop_ViewYourRevenue_desc,
  _ as community_errorpage_title,
  _ as community_title,
  _ as default,
  _ as empty_no_comma_following,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_accessibility,
  _ as footer_cookies,
  _ as footer_geodata_notice,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_privacy_policy,
  _ as footer_refunds,
  _ as footer_ssa,
  _ as moderatedcontent_description,
  _ as moderation_claim_n_reports_on_m_subjects,
  _ as moderation_claim_report_count,
  _ as moderation_claim_report_count_Plural,
  _ as moderation_claim_subject_count,
  _ as moderation_claim_subject_count_Plural,
  _ as moderation_forumpost_summary,
  _ as moderation_forumpost_summary_reports_fragment,
  _ as moderation_forumpost_summary_reports_fragment_Plural,
  _ as moderation_forumpost_summary_subjects_fragment,
  _ as moderation_forumpost_summary_subjects_fragment_Plural,
  _ as profile_error_profilenotfound,
  _ as profile_games_list,
  _ as profile_games_list_error_loadfailed,
  _ as profile_games_list_title,
  _ as profiletabs_communitymessages,
  _ as profiletabs_currentbans,
  _ as profiletabs_moderatedcontent,
  _ as profiletabs_reportedcontent,
  _ as reportedcontent_description,
  _ as reportedcontent_lastupdated,
};
