var _ = `البحث في سوق المجتمع`,
  _ = `إعادة تعيين عامل التصفية`,
  _ = `بحث`,
  _ = `تحديد لعبة...`,
  _ = `الألعاب التي لعبتها مؤخراً وتحتوي على عناصر`,
  _ = `ألعاب مشهورة تحتوي على عناصر`,
  _ = `مسح التحديد`,
  _ = `البحث...`,
  _ = `ابحث في %1$s...`,
  _ = `عناصر داخل اللعبة`,
  _ = `عناصر Steam`,
  _ = `نوع العنصر`,
  _ = `لا تحتوي هذه اللعبة على عوامل تصفية للسوق.`,
  _ = `انقر فوق"بحث" لعرض العناصر المتاحة.`,
  _ = `حدث خطأ أثناء تحميل عوامل التصفية الخاصة بهذه اللعبة.`,
  _ = `السعر`,
  _ = `الحد الأدنى للسعر`,
  _ = `الحد الأقصى للسعر`,
  _ = `الجميع`,
  _ = `أخرى`,
  _ = `التصفية...`,
  _ = `التصفية حسب اللعبة...`,
  _ = `ميزة تجريبية - أعطِ ملاحظاتك`,
  _ = `ابحث في أسماء العناصر في السوق...`,
  _ = `حقائب الأسلحة، وكبسولات الملصقات، وحزم الهدايا التذكارية، وما إلى ذلك`,
  _ = `سوق مجتمع Steam`,
  _ = `شراء وبيع العناصر مع أعضاء المجتمع للحصول على أموال لمحفظة Steam`,
  _ = `اعرف أكثر`,
  _ = `البحث في السوق`,
  _ = `بحث جديد...`,
  _ = `عامل التصفية`,
  _ = `الخروج من النسخة التجريبية للسوق`,
  _ = `إرسال ملاحظات`,
  _ = `هذا العنصر سلعة عامة، حيث أن جميع العناصر الفردية متطابقة فعلياً. لا يمكن الوصول إلى عروض المنتجات الفردية؛ بدلاً من ذلك، يمكنك إصدار أوامر شراء بسعر محدد، حيث يتم مطابقة أرخص عرض تلقائياً مع أعلى طلب شراء.`,
  _ = `تم العثور على %1$s من النتائج`,
  _ = `تم العثور على %1$s من النتائج`,
  _ = `تم العثور على %1$s من النتائج لـ:`,
  _ = `تم العثور على %1$s من النتائج لـ:`,
  _ = `نتائج لـ:`,
  _ = `تم العثور على %2$s من عروض البيع`,
  _ = `تم العثور على %2$s من عروض البيع`,
  _ = `الشعبية`,
  _ = `الاسم (من الألف إلى الياء)`,
  _ = `الاسم (من الياء إلى الألف)`,
  _ = `السعر (من الأدنى إلى الأعلى)`,
  _ = `السعر (من الأعلى إلى الأدنى)`,
  _ = `الكمية (من الأدنى إلى الأعلى)`,
  _ = `الكمية (من الأعلى إلى الأدنى)`,
  _ = `%1$s (من الأدنى إلى الأعلى)`,
  _ = `%1$s (من الأعلى إلى الأدنى)`,
  _ = `التصنيف حسب:`,
  _ = `بحث`,
  _ = `البحث...`,
  _ = `شراء`,
  _ = `بيع`,
  _ = `اشترِ الآن`,
  _ = `تقديم طلب شراء...`,
  _ = `إجراء الطلب:`,
  _ = `إغلاق`,
  _ = `الكمية المعروضة للبيع: %1$s`,
  _ = `الكمية: %1$s`,
  _ = `من %1$s`,
  _ = `المرفق %1$s`,
  _ = `تصفية النتائج...`,
  _ = `بحث متقدم`,
  _ = `بحث متقدم`,
  _ = `البحث عن عنصر...`,
  _ = `الصفحة الرئيسية للسوق`,
  _ = `الألعاب الرائجة`,
  _ = `أضف أوصافًا في البحث`,
  _ = `تستخدم بعض العناصر القديمة أوصافًا نصية لخصائصها المهمة التي لا يمكن الوصول إليها باستخدام عوامل التصفية أدناه. يتيح لك هذا الخيار مطابقة نص البحث مع نص الوصف الكامل بدلاً من اسم العنصر فقط.`,
  _ = `عامل التصفية`,
  _ = `إعادة ضبط البحث`,
  _ = `أدخل نص التصفية المخصص...`,
  _ = `بعد الشراء، هذا العنصر:`,
  _ = `لن يكون قابلًا للمقايضة ليوم واحد`,
  _ = `لن يكون قابلًا للمقايضة لأسبوع واحد`,
  _ = `لن يكون قابلًا للمقايضة لمدة %1$s من الأيام`,
  _ = `لن يكون قابلًا للمقايضة`,
  _ = `لا يمكن إدراجه في سوق مجتمع Steam لمدة يوم واحد`,
  _ = `لا يمكن إدراجه في سوق مجتمع Steam لمدة أسبوع واحد`,
  _ = `لا يمكن إدراجه في سوق مجتمع Steam لمدة %1$s من الأيام`,
  _ = `يمكن إعادة بيعه على الفور في سوق مجتمع Steam`,
  _ = `%1$s: %2$s - %3$s`,
  _ = `%1$s: "%2$s"`,
  _ = `شراء العنصر`,
  _ = `الاسم`,
  _ = `السعر`,
  _ = `الإجمالي الفرعي:`,
  _ = `%1$s رسوم (%2$s%):`,
  _ = `رسوم اللعبة (%1$s%):`,
  _ = `رسوم عملية البيع في Steam (%1$s%):`,
  _ = `ضريبة المبيعات المحلية(%1$s):`,
  _ = `الإجمالي:`,
  _ = `طريقة الدفع:`,
  _ = `محفظة Steam`,
  _ = `حساب Steam:`,
  _ = `عنوان دفع الفواتير:`,
  _ = `الاسم الأول`,
  _ = `اسم العائلة`,
  _ = `عنوان دفع الفواتير`,
  _ = `السطر 2 لعنوان دفع الفواتير`,
  _ = `المدينة`,
  _ = `الولاية / المقاطعة`,
  _ = `الرمز البريدي`,
  _ = `الدولة`,
  _ = `احفظ عنواني لتسهيل عملية الشراء في المرة المقبلة`,
  _ = `إضافة رصيد`,
  _ = `شراء`,
  _ = `أوافق على شروط %1$s (آخر تحديث %2$s)`,
  _ = `اتفاقية مشترك Steam`,
  _ = `يجب أن توافق على شروط اتفاقية مشترك Steam لإتمام هذه المعاملة.`,
  _ = `بالنقر على "شراء"، فإنك توافق على أنه سيتم تزويدك بإمكانية الوصول الفوري إلى هذا المحتوى الرقمي، وبالتالي تنتهي أي إمكانية للتراجع عن هذا الشراء - الشراء نهائي.`,
  _ = `حدثت مشكلة أثناء عملية شراء العنصر. ربما تم حذف العنصر من القائمة. يرجى تحديث الصفحة والمحاولة مرة أخرى.`,
  _ = `حدثت مشكلة أثناء عملية شراء العنصر. حدث خطأ ما أثناء انتظار تأكيدك لهذه العملية. يُرجى تحديث الصفحة والمحاولة مرة أخرى.`,
  _ = `الحقول التالية مطلوبة:`,
  _ = `يرجى إدخال عنوان عسكري صالح`,
  _ = `يُرجى إدخال رمز بريدي صحيح`,
  _ = `تهانينا على الشراء! يمكنك عرض عنصرك الجديد في <1>مخزونك</1>.`,
  _ = `عرض المخزون`,
  _ = `تحتاج إلى تأكيد إضافي`,
  _ = `بانتظار تأكيدك لعملية الشراء هذه...`,
  _ = `تتطلب بعض عمليات الشراء إجراءات أمان إضافية عبر تطبيق Steam Mobile.`,
  _ = `تتطلب بعض عمليات الشراء إجراءات أمان إضافية عبر البريد الإلكتروني لـSteam Guard.`,
  _ = `تتطلب بعض عمليات الشراء إجراءات أمان إضافية عبر تطبيق Steam Mobile أو بريدك الإلكتروني`,
  _ = `قم بالتأكيد عبر تطبيق Steam Mobile لإتمام عملية الشراء...`,
  _ = `قم بالتأكيد عبر البريد الإلكتروني لإتمام عملية الشراء...`,
  _ = `قم بالتأكيد عبر تطبيق Steam Mobile أو البريد الإلكتروني لإتمام عملية الشراء...`,
  _ = `تمت عملية الشراء بنجاح`,
  _ = `إغلاق`,
  _ = `عرض المخزون`,
  _ = `احفظ عنواني لتكون عملية الشراء أسرع في المرة المقبلة`,
  _ = `لم يعد هذا العرض متاحًا`,
  _ = `غير متاح`,
  _ = `لم يعد هذا العرض متاحًا للشراء.`,
  _ = `اشترِ - %1$s`,
  _ = `تقديم طلب شراء`,
  _ = `أي نوع من العناصر ترغب في شرائه؟`,
  _ = `اختر عنصرًا...`,
  _ = `ما السعر الذي تريد دفعه:`,
  _ = `(لكل عنصر)`,
  _ = `كم عدد العناصر التي ترغب في شرائها:`,
  _ = `الحد الأقصى للسعر %1$s:`,
  _ = `هذا هو الحد الأقصى الذي قد تنفقه نتيجةً لطلب الشراء هذا. سيتم شراء عناصر بأرخص سعر متاح، لذا قد تكون تكلفة الطلب النهائية أقل من هذا المبلغ.`,
  _ = `العثور على عروض العناصر المطابقة بالسعر الذي ترغب به...`,
  _ = `تمت عملية الشراء بنجاح! أصبح العنصر الآن في مخزونك، وتم إرسال إيصال الشراء إليك عبر البريد الإلكتروني.`,
  _ = `تم بنجاح! تم تقديم طلب الشراء الخاص بك.`,
  _ = `سيتم إعلامك تلقائيًا عن طريق البريد الإلكتروني عند اكتمال الشراء. يمكنك إلغاء طلب الشراء هذا من أعلى هذه الصفحة، أو من الصفحة الرئيسية للسوق.`,
  _ = `عذراً! واجهنا مشكلة في تلقي رد من خوادم Steam بخصوص طلبك. يرجى التأكد من إنشاء طلبك أو تنفيذه. إذا لم يتم ذلك، فيرجى المحاولة مرة أخرى لاحقاً.`,
  _ = `الحد الأدنى لسعر الوحدة هو %1$s`,
  _ = `%1$s أو أقل`,
  _ = `%1$s أو أكثر`,
  _ = `السعر`,
  _ = `الكمية`,
  _ = `%1$s للبيع ابتداءً من %2$s`,
  _ = `لا توجد عروض نشطة لهذا العنصر`,
  _ = `طلب %1$s الشراء بسعر %2$s أو أقل`,
  _ = `لا توجد طلبات شراء نشطة لهذا العنصر.`,
  _ = `اختر التبويب أعلاه للاطلاع على معلومات طلب الشراء`,
  _ = `لا ترى العنصر أو السعر الذي تريده؟`,
  _ = `لا ترى سعراً يناسبك؟`,
  _ = `طلبات البيع والشراء (التراكمية)`,
  _ = `طلب شراء واحد بـ %2$s أو أعلى`,
  _ = `%1$s طلبات شراء بـ %2$s أو أعلى`,
  _ = `طلب بيع واحد بـ %2$s أو أقل`,
  _ = `%1$s طلبات بيع بـ %2$s أو أقل`,
  _ = `طلب بيع واحد بـ <1>%2$s</1>`,
  _ = `طلب %3$s الشراء بسعر<1> %2$s أو أقل</1>`,
  _ = `متوسط ​​أسعار البيع`,
  _ = `أسبوع`,
  _ = `شهر`,
  _ = `سنة`,
  _ = `المدة الزمنية`,
  _ = `%1$s تم بيعه`,
  _ = `السعر`,
  _ = `الكمية`,
  _ = `لا توجد بيانات لهذه الفترة الزمنية`,
  _ = `لا توجد بيانات شراء`,
  _ = `غير متاح`,
  _ = `الاسم`,
  _ = `السعر`,
  _ = `الكمية`,
  _ = `عُرض في`,
  _ = `إلغاء`,
  _ = `حذف`,
  _ = `طلباتي النشطة`,
  _ = `طلبات البيع`,
  _ = `طلبات الشراء`,
  _ = `الشراء - العروض الخاص بي`,
  _ = `البيع- عروض البيع الخاص بي`,
  _ = `حدثت مشكلة أثناء تحميل بيانات الطلب لهذا العنصر.`,
  _ = `لا توجد لديك طلبات نشطة لهذا العنصر.`,
  _ = `لا توجد لديك طلبات شراء نشطة لهذا العنصر.`,
  _ = `أنت لا تبيع أيًا من هذا النوع من العناصر. قم ببيع عناصر من مخزونك، أو انقر على زر "بيع" في هذه الصفحة.`,
  _ = `الكمية: %1$s`,
  _ = `رؤية جميع الـ%1$s`,
  _ = `حدثت مشكلة في أثناء إلغاء طلبك. يُرجى إعادة المحاولة لاحقًا.`,
  _ = `حدثت مشكلة أثناء حذف العرض الخاص بك، يُرجى المحاولة مرة أخرى لاحقًا.`,
  _ = `حذف عرض البيع`,
  _ = `هل ترغب في حذف عرض بيع %1$s وإعادة العنصر إلى مخزونك؟`,
  _ = `هل ترغب في حذف عرض البيع هذا وإعادة العنصر إلى مخزونك؟`,
  _ = `نعم، احذف عرض البيع هذا`,
  _ = `لا`,
  _ = `تم حذف عرض البيع الخاص بك بنجاح`,
  _ = `اختر عنصرًا من مخزونك`,
  _ = `ما هو طلب الشراء؟`,
  _ = `حدد السعر الذي تفضله، وسيتم إتمام عملية الشراء تلقائيًا عندما يصبح العنصر متاحًا بهذا السعر.`,
  _ = `سيضمن لك Steam الحصول على أفضل سعر متاح.`,
  _ = `بالنسبة لهذا العنصر، سيتم مطابقة طلبات الشراء مع الخيار الأرخص للشراء بغض النظر عن أي خصائص فريدة.`,
  _ = `%1$s وما فوق`,
  _ = `عذرًا!`,
  _ = `حدث خطأ في أثناء معالجة طلبك:`,
  _ = `لقد أرسلت عددًا كبيرًا من الطلبات مؤخرًا. يرجى الانتظار ومحاولة إرسال طلبك في وقت لاحق.`,
  _ = `المحتويات المحتملة:`,
  _ = `كانت هناك مشكلة خلال تحميل هذا المحتوى`,
  _ = `قد لا يكون العنصر الذي طلبته موجودًا، أو قد تكون هناك مشكلة مؤقتة تمنع تحميله. يرجى المحاولة مرة أخرى لاحقًا.`,
  _ = `تصفية عروض البيع`,
  _ = `لم يتم العثور على أية عروض`,
  _ = `المزيد من الخيارات...`,
  _ = `عامل التصفية...`,
  _ = `المعلومات`,
  _ = `الرسم البياني للمبيعات`,
  _ = `طلبات الشراء`,
  _ = `عوامل التصفية`,
  _ = `دقيقة`,
  _ = `الحد الأقصى`,
  _ = `الملحقات`,
  _ = `أي منها`,
  _ = `لا شيء`,
  _ = `%1$s:%2$s`,
  _ = `لا يمكنك شراء هذا العنصر لأن شراء وبيع هذا النوع من العناصر معطل في بلدك.`,
  _ = `لا يمكنك شراء هذا العنصر لأن شراء وبيع هذا النوع من العناصر معطل في بلدك.`,
  _ = `لا يحتوي هذا العرض حاليًا على صور فريدة أو محسّنة. قد تختلف الصورة المعروضة هنا قليلاً عن العنصر المدرج.`,
  _ = `عرض الخلفية`,
  _ = `حدث خطأ أثناء محاولة إظهار هذا العرض`,
  _ = `لا يمكنك شراء أو بيع العناصر في السوق للسبب التالي:`,
  _ = `لا يمكنك شراء أو بيع العناصر في السوق للأسباب التالية:`,
  _ = `عرض النتائج`,
  _ = `عرض كشبكة`,
  _ = `عرض كقائمة`,
  _ = `أنت تحاول مشاهد عنصر خاص بلعبة جديدة على Steam لم تلعبها من قبل. توخَّ الحذر عند التعامل مع هذا العنصر.`,
  _ = `انقر هنا لعرض هذا العنصر على أي حال`,
  _ = `التصفية حسب اللعبة`,
  _ = `عرض جميع الألعاب`,
  _ = `حسابك مُقفل حاليًا.`,
  _ = `يمكنك العثور على معلومات حول هذا القفل بالنقر على الشريط الأحمر الظاهر في الزاوية العلوية اليمنى أثناء تسجيل الدخول إلى برنامج تشغيل Steam. لمزيد من المعلومات، يُرجى التواصل مع دعم Steam.`,
  _ = `حسابك مقفل حاليًا. يمكنك الاطلاع على معلومات حول هذا الإقفال بالنقر على الشريط الأحمر الموجود في الزاوية العلوية اليمنى أثناء تسجيل الدخول إلى برنامج Steam.`,
  _ = `لإزالة هذا القيد...`,
  _ = `حسابك محظور من المقايضة حاليًا.`,
  _ = `لا يمكن لهذا الحساب حاليًا استخدام سوق مجتمع Steam.`,
  _ = `قد تتراوح مدة حظر المقايضة من مؤقتة إلى دائمة. لمعرفة تاريخ انتهاء هذا الحظر، يُرجى النقر على الشريط الأحمر الظاهر في الزاوية العلوية اليمنى أثناء تسجيل الدخول إلى برنامج تشغيل Steam.`,
  _ = `تم حظر حسابك من المقايضة. لمعرفة تاريخ انتهاء هذا الحظر، يرجى النقر على الشريط الأحمر الموجود في الزاوية العلوية اليمنى أثناء تسجيل الدخول إلى برنامج Steam.`,
  _ = `معلومات أكثر...`,
  _ = `يجب أن يكون لديك عملية شراء صالحة على منصة Steam تتراوح أعمارها بين %1$s يوم وسنة واحدة، دون أي عمليات استرداد أو نزاع على الدفع حديثة.`,
  _ = `يرجى إتمام عملية الشراء من متجر Steam. رصيد المحفظة والألعاب والـ DLCs صالحة للشراء. أما مفاتيح التفعيل والهدايا فلا تُقبل. لا يمكن لفريق دعم Steam إزالة هذا التقييد.`,
  _ = `يجب أن يكون لديك عملية شراء عبر منصة Steam مضى عليها ما بين %1$s يوم وسنة، دون أي عمليات استرداد أو نزاعات دفع حديثة. لا يمكن لفريق دعم Steam إزالة هذا الشرط.`,
  _ = `يبدو أنك أجريت عملية شراء صحيحة على متجر Steam، ولكنها لم بمر عليها %1$s يوم بعد.`,
  _ = `نشترط أن يكون الشراء عبر Steam قد تم خلال فترة تتراوح بين %1$s يوم وسنة، دون وجود أي عمليات استرداد أو نزاعات حديثة متعلقة بالدفع. يبدو أنك قد قمت بعملية شراء، ولكنها لم يمض عليها %1$s يومًا بعد. لا يمكن لفريق دعم Steam إزالة هذا التقييد.`,
  _ = `تمت إعادة تعيين كلمة مرور حسابك مؤخرًا.`,
  _ = `ستتم إزالة هذا التقييد تلقائيًا بعد %1$s أيام من آخر عملية إعادة تعيين لكلمة مرور الحساب. في حال عدم استخدام الحساب لفترة طويلة، قد يستمر هذا التقييد لمدة تصل إلى %2$s أيام. يُطبق هذا التقييد فقط عند إعادة تعيين كلمة المرور. لن ينتج عن تغيير كلمة مرور حسابك ببساطة تطبيق أي قيود. لا يمكن لفريق دعم Steam إزالة أي قيود.`,
  _ = `تمت إعادة تعيين كلمة مرور حسابك على Steam مؤخرًا. ولحماية المستخدمين الذين قد اُخترِقت حسابات بريدهم الإلكتروني أو حساباتهم الأخرى، نقوم بتقييد الوصول إلى سوق المجتمع لمدة %1$s أيام بعد إعادة تعيين كلمة المرور.`,
  _ = `لقد قمت مؤخرًا بإضافة المال إلى محفظة Steam الخاصة بك باستخدام بطاقة ائتمان غير موثقة شهدت زيادة في الاستخدام مؤخرًا. يمكنك محاولة <1>توثيق الأموال الآن</1> أو انتظر حتى تتم إزالة القيد تلقائيًا.

ملاحظة: قد لا تنجح عملية التحقق من الأموال مع جميع البنوك أو بطاقات الائتمان. إذا لم تتمكن من التحقق من بطاقتك، فيجب عليك الانتظار ريثما يتم التحقق من طريقة الدفع مع Steam. لا يمكن لدعم Steam توفير أو تحويل رسوم التحقق، ولا يمكنه إزالة هذا القيد.`,
  _ = `لقد أضفت رصيدًا إلى محفظتك على Steam مؤخرًا باستخدام PayPal أو وسيلة دفع غير مُوثقة ازداد استخدامها مؤخرًا. لن تتمكن من استخدام السوق لبضعة أيام حتى يتم التحقق من الأموال.`,
  _ = `لقد أضفت رصيدًا إلى محفظتك على Steam مؤخرًا باستخدام حساب PayPal جديد أو وسيلة دفع غير مُوثقة ازداد استخدامها مؤخرًا. لن تتمكن من استخدام السوق لبضعة أيام حتى يتم التحقق من الأموال.`,
  _ = `قمت مؤخراً بقبول بطاقة هدايا رقمية من صديق.`,
  _ = `لقد قبلت مؤخرًا بطاقة هدايا رقمية من صديق. لن تتمكن من استخدام سوق مجتمع Steam لمدة %1$s يومًا بعد شراء صديقك لبطاقة الهدايا.`,
  _ = `يواجه Steam مشكلة في استخدام ملفات تعريف الارتباط الخاصة بمتصفحك.`,
  _ = `يبدو أن ملف تعريف الارتباط الخاص بك غير صالح. يُرجى محاولة تسجيل الخروج ثم تسجيل الدخول مرة أخرى إلى Steam. بالإضافة إلى ذلك، يُرجى التأكد من تفعيل ملفات تعريف الارتباط في المتصفح بشكل صحيح، ومن عدم وجود إضافات للمتصفح تتعارض مع ملف تعريف الارتباط الخاص بـ Steam.`,
  _ = `قد لا تكون ملفات تعريف الارتباط مُفعّلة في متصفحك. تأكد من السماح بجميع ملفات تعريف الارتباط في متصفحك، وحاول تسجيل الخروج ثم تسجيل الدخول ثانيةً.`,
  _ = `أنت تسجل الدخول إلى السوق من جهاز غير محمي بـ Steam Guard لمدة %1$s أيام.`,
  _ = `إذا كان لديك جهاز تم التحقق منه مسبقًا، يمكنك الاستمرار باستخدام تطبيق The Market عليه. وإلا، فعليك الانتظار حتى نتحقق من جهازك قبل استخدام The Market.`,
  _ = `سجّلت الدخول من جهاز جديد أو متصفح جديد. لحماية العناصر الموجودة في مخزونك، لن تتمكن من استخدام السوق من هذا الجهاز لمدة %1$s من الأيام.`,
  _ = `لقد قمت مؤخراً برد مبلغ من إحدى المعاملات إلى محفظة Steam.`,
  _ = `لن تتمكن من استخدام السوق لمدة %1$s يومًا بعد آخر عملية استرداد ذاتي. لا يمكن لدعم Steam إزالة أي قيود.`,
  _ = `لقد قمت مؤخرًا برد مبلغ معاملة إلى محفظة Steam الخاصة بك. لن تتمكن من استخدام السوق لمدة %1$s أيام بعد آخر عملية استرداد ذاتي قمت بها.`,
  _ = `حسابك محدود.`,
  _ = `حسابك محدود ولا يمكنه الوصول إلى بعض ميزات Steam بما في ذلك سوق مجتمع Steam.`,
  _ = `حسابك محدود ولا يمكنه الوصول إلى بعض ميزات Steam بما في ذلك سوق مجتمع Steam.`,
  _ = `إذا قمت مؤخرًا بإعادة ضبط أو تفعيل Steam Guard، يجب عليك الانتظار %1$s يومًا بعد تفعيل Steam Guard.`,
  _ = `يجب عليك الانتظار حتي يمضي 15 يومًا على تفعيل خدمة Steam Guard على حسابك. لا يمكن لفريق دعم Steam إزالة هذا التقييد.`,
  _ = `يجب أن يكون حسابك محمي بواسطة Steam Guard لمدة لا تقل عن %1$s يوم.`,
  _ = `يجب عليك تفعيل خدمة Steam Guard في حسابك. يُرجى التأكد من تفعيل بريدك الإلكتروني وتسجيل دخولك إلى حسابك مرتين بعد تفعيل خدمة Steam Guard.`,
  _ = `يجب أن يكون حسابك محمي بواسطة Steam Guard لمدة لا تقل عن %1$s يوم.`,
  _ = `إذا لم يحدث أي شيء آخر يقيد وصولك إلى سوق المجتمع، سيكون بإمكانك استخدامه في %1$s`,
  _ = `حسابك في حالة توقف مؤقت عن استخدام ميزات المقايضة والسوق.`,
  _ = {
    AdvancedSearch_Heading: _,
    AdvancedSearch_Reset: _,
    AdvancedSearch_Search: _,
    AdvancedSearch_AppSelect_Placeholder: _,
    AdvancedSearch_AppSelect_YourGames: _,
    AdvancedSearch_AppSelect_PopularGames: _,
    AdvancedSearch_AppSelect_Clear: _,
    AdvancedSearch_TextSearch_Placeholder: _,
    AdvancedSearch_TextSearch_PlaceholderWithApp: _,
    AdvancedSearch_TypeSwitch_InGame: _,
    AdvancedSearch_TypeSwitch_SteamItems: _,
    AdvancedSearch_SteamItems_TypeLabel: _,
    AdvancedSearch_NoFacets: _,
    AdvancedSearch_NoFacetsSearch: _,
    AdvancedSearch_FacetLoadError: _,
    AdvancedSearch_PriceFieldLabel: _,
    AdvancedSearch_MinPricePlaceholder: _,
    AdvancedSearch_MaxPricePlaceholder: _,
    AdvancedSearch_CustomFilter_All: _,
    AdvancedSearch_CustomFilter_Other: _,
    AdvancedSearch_FilterGeneric_Placeholder: _,
    AdvancedSearch_AppSelect_FilterPlaceholder: _,
    AdvancedSearch_BetaTag: _,
    AdvancedSearch_TextSearch_Tooltip: _,
    AdvancedSearch_CSContainers_Tooltip: _,
    Header_MarketTitle: _,
    Header_MarketDescription: _,
    Header_LearnMore: _,
    Header_Search_Placeholder: _,
    Header_Search_PlaceholderNew: _,
    Header_Search_Filters: _,
    Header_OptOut: _,
    Header_GiveFeedback: _,
    CommodityExplanation: _,
    Search_AmountFound: _,
    Search_AmountFound_Plural: _,
    Search_AmountFoundFor: _,
    Search_AmountFoundFor_Plural: _,
    Search_ResultsFoundFor: _,
    Search_ListingsFound: _,
    Search_ListingsFound_Plural: _,
    SortBy_Popularity: _,
    SortBy_Name_Asc: _,
    SortBy_Name_Desc: _,
    SortBy_Price_Asc: _,
    SortBy_Price_Desc: _,
    SortBy_Quantity_Asc: _,
    SortBy_Quantity_Desc: _,
    SortBy_AssetProperty_Asc: _,
    SortBy_AssetProperty_Desc: _,
    SortBy_Label: _,
    Search_Button: _,
    Search_Placeholder: _,
    Button_Buy: _,
    Button_Sell: _,
    Button_BuyNow: _,
    Button_BuyOrder: _,
    BuyOrder_PlaceOrderHeader: _,
    Button_Close: _,
    Search_ListingQuantity: _,
    Search_ListingQuantity_Abbreviation: _,
    Bucket_PriceFrom: _,
    AccessorySearch_AttachedAccessoryType: _,
    FilterResults_Placeholder: _,
    AdvancedSearch_Header: _,
    AdvancedSearch_Link: _,
    MarketSearch_Placeholder: _,
    Breadcrumbs_Home: _,
    MarketHome_PopularApps: _,
    AdvancedSearch_IncludeDescriptions: _,
    AdvancedSearch_IncludeDescriptions_Tooltip: _,
    MarketSearch_FilterColumn_Header: _,
    MarketSearch_Reset: _,
    Listings_TextFilter_Placeholder: _,
    Economy_Market_Purchase_Restrictions: _,
    Economy_Market_Purchase_TradableRestriction_1Day: _,
    Economy_Market_Purchase_TradableRestriction_7Days: _,
    Economy_Market_Purchase_TradableRestriction_NDays: _,
    Economy_Market_Purchase_TradableRestriction_Permanent: _,
    Economy_Market_Purchase_MarketableRestriction_1Day: _,
    Economy_Market_Purchase_MarketableRestriction_7Days: _,
    Economy_Market_Purchase_MarketableRestriction_NDays: _,
    Economy_Market_Purchase_MarketableRestriction_None: _,
    AssetPropertyNumberFilterRange: _,
    AssetPropertyStringFilter: _,
    PurchaseDialog_Header: _,
    PurchaseDialog_Details_Column_Name: _,
    PurchaseDialog_Details_Column_Price: _,
    PurchaseDialog_Subtotal_Label: _,
    PurchaseDialog_PublisherFee_Label: _,
    PurchaseDialog_PublisherFee_Label_Generic: _,
    PurchaseDialog_SteamFee_Label: _,
    PurchaseDialog_LocalTax_Label: _,
    PurchaseDialog_Total_Label: _,
    PurchaseDialog_PaymentMethod_Label: _,
    PurchaseDialog_PaymentMethod_Wallet: _,
    PurchaseDialog_SteamAccount_Label: _,
    PurchaseDialog_BillingInfo_Label: _,
    PurchaseDialog_BillingInfo_FirstName: _,
    PurchaseDialog_BillingInfo_LastName: _,
    PurchaseDialog_BillingInfo_Address: _,
    PurchaseDialog_BillingInfo_AddressLine2: _,
    PurchaseDialog_BillingInfo_City: _,
    PurchaseDialog_BillingInfo_StateProvince: _,
    PurchaseDialog_BillingInfo_ZipPostal: _,
    PurchaseDialog_BillingInfo_Country: _,
    PurchaseDialog_BillingInfo_SaveInfo: _,
    PurchaseDialog_Action_AddFunds: _,
    PurchaseDialog_Action_Purchase: _,
    PurchaseDialog_SSA_Link: _,
    PurchaseDialog_SSA_Link_Title: _,
    PurchaseDialog_SSA_Fail: _,
    PurchaseDialog_EU_SSA: _,
    PurchaseDialog_Error_ServerGeneric: _,
    PurchaseDialog_Error_NoConfirmation: _,
    PurchaseDialog_Error_MissingRequired: _,
    PurchaseDialog_Error_InvalidMilitaryCity: _,
    PurchaseDialog_Error_InvalidPostal: _,
    PurchaseDialog_PurchaseComplete: _,
    PurchaseDialog_Button_ViewInventory: _,
    PurchaseDialog_Confirmation_Title: _,
    PurchaseDialog_Confirmation_Title_Wait: _,
    PurchaseDialog_Confirmation_Body_Mobile: _,
    PurchaseDialog_Confirmation_Body_Email: _,
    PurchaseDialog_Confirmation_Body_Unknown: _,
    PurchaseDialog_Confirmation_Description_Mobile: _,
    PurchaseDialog_Confirmation_Description_Email: _,
    PurchaseDialog_Confirmation_Description_Unknown: _,
    PurchaseDialog_Purchase_Successful: _,
    PurchaseDialog_Close: _,
    PurchaseDialog_ViewInventory: _,
    PurhcaseDialog_SaveMyAddress: _,
    Listing_NotAvailable: _,
    Listing_NotAvailable_Short: _,
    Listing_NotAvailable_Long: _,
    BuyOrderDialog_Header: _,
    BuyOrderDialog_Header_NoItem: _,
    BuyOrderDialog_BucketPicker_Label: _,
    BuyOrderDialog_BucketPicker_Placeholder: _,
    BuyOrderDialog_PriceField: _,
    BuyOrderDialog_PriceField_Suffix: _,
    BuyOrderDialog_QuantityField: _,
    BuyOrderDialog_MaxPrice: _,
    BuyOrderDialog_MaxPrice_Tip: _,
    BuyOrderDialog_Status_Pending: _,
    BuyOrderDialog_Status_Filled: _,
    BuyOrderDialog_Status_Settled: _,
    BuyOrderDialog_Status_Settled_Note: _,
    BuyOrderDialog_Status_GenericError: _,
    BuyOrderDialog_MinPriceError: _,
    OrderBook_Table_PriceOrLess: _,
    OrderBook_Table_PriceOrMore: _,
    OrderBook_Table_Price: _,
    OrderBook_Table_Quantity: _,
    OrderBook_SellOrder_Description: _,
    OrderBook_SellOrder_Description_None: _,
    OrderBook_BuyOrder_Description: _,
    OrderBook_BuyOrder_Description_None: _,
    OrderBook_BuyOrder_NeedBucket: _,
    OrderBook_BuyOrder_Explanation_Unique: _,
    OrderBook_BuyOrder_Explanation_Commodity: _,
    OrderBook_Graph_Title: _,
    OrderBook_Graph_BuyTooltip: _,
    OrderBook_Graph_BuyTooltip_Plural: _,
    OrderBook_Graph_SellTooltip: _,
    OrderBook_Graph_SellTooltip_Plural: _,
    OrderBook_PlaceOrder_BuyRequests: _,
    OrderBook_PlaceOrder_BuyRequests_Plural: _,
    MedianSalePrice_Graph_Title: _,
    Graph_TimeScale_Week: _,
    Graph_TimeScale_Month: _,
    Graph_TimeScale_Year: _,
    Graph_TimeScale_Lifetime: _,
    Graph_NumberSold: _,
    Graph_Label_Price: _,
    Graph_Label_Volume: _,
    Graph_NoData: _,
    Graph_Tooltip_NoPurchaseData: _,
    Graph_Tooltip_NA: _,
    MyOrders_GridHeader_Name: _,
    MyOrders_GridHeader_Price: _,
    MyOrders_GridHeader_Quantity: _,
    MyOrders_GridHeader_DateListed: _,
    MyOrders_Cancel: _,
    MyOrders_Remove: _,
    MyOrders_Heading: _,
    MyOrders_Heading_Sell: _,
    MyOrders_Heading_Buy: _,
    MyOrders_Heading_MyPurchaseOffers: _,
    MyOrders_Heading_MyListings: _,
    MyOrders_FailedToLoad: _,
    MyOrders_NoActiveOrders_Item: _,
    MyOrders_NoBuyOrders_Item: _,
    MyOrders_NoSellOrders_Item: _,
    MyOrders_QuantityWithValue: _,
    MyOrders_SeeAllN: _,
    CancelBuyOrder_GenericError: _,
    CancelListing_GenericError: _,
    CancelListing_Dialog_Header: _,
    CancelListing_Dialog_Prompt: _,
    CancelListing_Dialog_Prompt_Generic: _,
    CancelListing_Dialog_Yes: _,
    CancelListing_Dialog_No: _,
    CancelListing_Dialog_Success: _,
    SellDialog_Frame_Title: _,
    UniqueBuyOrder_Explanation_Header: _,
    UniqueBuyOrder_Explanation_1: _,
    UniqueBuyOrder_Explanation_2: _,
    UniqueBuyOrder_Explanation_3: _,
    PriceFilter_ValueAndUp: _,
    Error_Sorry: _,
    Error_Encountered: _,
    Error_TooManyRequests_Description: _,
    Container_ContentsLabel: _,
    Error_LoadingContent: _,
    Error_LoadingMarketItem: _,
    ListingFilter_Title: _,
    Listings_NoneFound: _,
    ItemBucketPicker_Overflow_Placeholder: _,
    ItemBucketPicker_Overflow_FilterPlaceholder: _,
    Mobile_InfoSection: _,
    Mobile_GraphSection: _,
    Mobile_BuyOrderSection: _,
    Mobile_FiltersButton: _,
    AssetProperty_Range_MinPlaceholder: _,
    AssetProperty_Range_MaxPlaceholder: _,
    Accessories_FieldSectionLabel: _,
    Accessories_AnyFilter: _,
    Accessories_NoneFilter: _,
    Accessories_TypeAndValue_Breadcrumb: _,
    Item_CountryBuySellRestricted: _,
    Item_CountryBuyRestricted: _,
    Listing_EnhancedAppearance_Missing: _,
    Listing_EnhancedAppearance_ShowBackground: _,
    Listing_SomethingWentWrong: _,
    Unavailable_Header: _,
    Unavailable_Header_Plural: _,
    Filter_ViewResults: _,
    Results_GridView_Tooltip: _,
    Results_ListView_Tooltip: _,
    Market_AppUnplayedAndUnvetted: _,
    Market_AppUnplayedAndUnvetted_Dismiss: _,
    Home_GamePicker_Label: _,
    Home_GamePicker_ViewAll: _,
    Economy_Market_TopLevelReason_AccountLocked: _,
    Economy_Market_TopLevelTooltip_AccountLocked: _,
    Economy_Market_HeaderTip_AccountLocked: _,
    Economy_Market_TopLevelTooltip_RemoveRestrictionLink: _,
    Economy_Market_TopLevelReason_AccountTradeBanned: _,
    Economy_Market_TopLevelReason_Unknown: _,
    Economy_Market_TopLevelTooltip_AccountTradeBanned: _,
    Economy_Market_HeaderTip_AccountTradeBanned: _,
    Economy_Market_TopLevelTooltip_MoreInfoLink: _,
    Economy_Market_TopLevelReason_AccountNotTrusted: _,
    Economy_Market_TopLevelTooltip_AccountNotTrusted: _,
    Economy_Market_HeaderTip_AccountNotTrusted: _,
    Economy_Market_TopLevelReason_AccountNotTrusted_Waiting: _,
    Economy_Market_TTopLevelTooltip_AccountNotTrusted_Waiting: _,
    Economy_Market_TopLevelReason_AccountPasswordRecentlyReset: _,
    Economy_Market_TopLevelTooltip_AccountPasswordRecentlyReset: _,
    Economy_Market_HeaderTip_AccountPasswordRecentlyReset: _,
    Economy_Market_HeaderTip_NewPaymentMethod_NoDate: _,
    Economy_Market_HeaderTip_AccountHasNewPaymentMethod: _,
    Economy_Market_TopLevelReason_AccountHasNewPaymentMethod: _,
    Economy_Market_TopLevelReason_AcceptedWalletGift: _,
    Economy_Market_HeaderTip_AcceptedWalletGift: _,
    Economy_Market_TopLevelReason_InvalidCookie: _,
    Economy_Market_TopLevelTooltip_InvalidCookie: _,
    Economy_Market_HeaderTip_InvalidCookie: _,
    Economy_Market_TopLevelReason_NewDevice: _,
    Economy_Market_TopLevelTooltip_NewDevice: _,
    Economy_Market_HeaderTip_NewDevice: _,
    Economy_Market_TopLevelReason_SelfRefund: _,
    Economy_Market_TopLevelTooltip_SelfRefund: _,
    Economy_Market_HeaderTip_SelfRefund: _,
    Economy_Market_TopLevelReason_LimitedUser: _,
    Economy_Market_TopLevelTooltip_LimitedUser: _,
    Economy_Market_HeaderTip_LimitedUser: _,
    Economy_Market_HeaderTip_SteamGuardOnlyRecentlyEnabled: _,
    Economy_Market_TopLevelTooltip_SteamGuardRecentlyEnabled: _,
    Economy_Market_TopLevelReason_NoSteamGuard: _,
    Economy_Market_TopLevelTooltip_SteamGuardDisabled: _,
    Economy_Market_HeaderTip_NoSteamGuard: _,
    Economy_Market_HeaderTip_TimeCanUse: _,
    Economy_Market_TopLevelReason_TradeCooldown: _,
  };
export {
  _ as Accessories_AnyFilter,
  _ as Accessories_FieldSectionLabel,
  _ as Accessories_NoneFilter,
  _ as Accessories_TypeAndValue_Breadcrumb,
  _ as AccessorySearch_AttachedAccessoryType,
  _ as AdvancedSearch_AppSelect_Clear,
  _ as AdvancedSearch_AppSelect_FilterPlaceholder,
  _ as AdvancedSearch_AppSelect_Placeholder,
  _ as AdvancedSearch_AppSelect_PopularGames,
  _ as AdvancedSearch_AppSelect_YourGames,
  _ as AdvancedSearch_BetaTag,
  _ as AdvancedSearch_CSContainers_Tooltip,
  _ as AdvancedSearch_CustomFilter_All,
  _ as AdvancedSearch_CustomFilter_Other,
  _ as AdvancedSearch_FacetLoadError,
  _ as AdvancedSearch_FilterGeneric_Placeholder,
  _ as AdvancedSearch_Header,
  _ as AdvancedSearch_Heading,
  _ as AdvancedSearch_IncludeDescriptions,
  _ as AdvancedSearch_IncludeDescriptions_Tooltip,
  _ as AdvancedSearch_Link,
  _ as AdvancedSearch_MaxPricePlaceholder,
  _ as AdvancedSearch_MinPricePlaceholder,
  _ as AdvancedSearch_NoFacets,
  _ as AdvancedSearch_NoFacetsSearch,
  _ as AdvancedSearch_PriceFieldLabel,
  _ as AdvancedSearch_Reset,
  _ as AdvancedSearch_Search,
  _ as AdvancedSearch_SteamItems_TypeLabel,
  _ as AdvancedSearch_TextSearch_Placeholder,
  _ as AdvancedSearch_TextSearch_PlaceholderWithApp,
  _ as AdvancedSearch_TextSearch_Tooltip,
  _ as AdvancedSearch_TypeSwitch_InGame,
  _ as AdvancedSearch_TypeSwitch_SteamItems,
  _ as AssetPropertyNumberFilterRange,
  _ as AssetPropertyStringFilter,
  _ as AssetProperty_Range_MaxPlaceholder,
  _ as AssetProperty_Range_MinPlaceholder,
  _ as Breadcrumbs_Home,
  _ as Bucket_PriceFrom,
  _ as Button_Buy,
  _ as Button_BuyNow,
  _ as Button_BuyOrder,
  _ as Button_Close,
  _ as Button_Sell,
  _ as BuyOrderDialog_BucketPicker_Label,
  _ as BuyOrderDialog_BucketPicker_Placeholder,
  _ as BuyOrderDialog_Header,
  _ as BuyOrderDialog_Header_NoItem,
  _ as BuyOrderDialog_MaxPrice,
  _ as BuyOrderDialog_MaxPrice_Tip,
  _ as BuyOrderDialog_MinPriceError,
  _ as BuyOrderDialog_PriceField,
  _ as BuyOrderDialog_PriceField_Suffix,
  _ as BuyOrderDialog_QuantityField,
  _ as BuyOrderDialog_Status_Filled,
  _ as BuyOrderDialog_Status_GenericError,
  _ as BuyOrderDialog_Status_Pending,
  _ as BuyOrderDialog_Status_Settled,
  _ as BuyOrderDialog_Status_Settled_Note,
  _ as BuyOrder_PlaceOrderHeader,
  _ as CancelBuyOrder_GenericError,
  _ as CancelListing_Dialog_Header,
  _ as CancelListing_Dialog_No,
  _ as CancelListing_Dialog_Prompt,
  _ as CancelListing_Dialog_Prompt_Generic,
  _ as CancelListing_Dialog_Success,
  _ as CancelListing_Dialog_Yes,
  _ as CancelListing_GenericError,
  _ as CommodityExplanation,
  _ as Container_ContentsLabel,
  _ as Economy_Market_HeaderTip_AcceptedWalletGift,
  _ as Economy_Market_HeaderTip_AccountHasNewPaymentMethod,
  _ as Economy_Market_HeaderTip_AccountLocked,
  _ as Economy_Market_HeaderTip_AccountNotTrusted,
  _ as Economy_Market_HeaderTip_AccountPasswordRecentlyReset,
  _ as Economy_Market_HeaderTip_AccountTradeBanned,
  _ as Economy_Market_HeaderTip_InvalidCookie,
  _ as Economy_Market_HeaderTip_LimitedUser,
  _ as Economy_Market_HeaderTip_NewDevice,
  _ as Economy_Market_HeaderTip_NewPaymentMethod_NoDate,
  _ as Economy_Market_HeaderTip_NoSteamGuard,
  _ as Economy_Market_HeaderTip_SelfRefund,
  _ as Economy_Market_HeaderTip_SteamGuardOnlyRecentlyEnabled,
  _ as Economy_Market_HeaderTip_TimeCanUse,
  _ as Economy_Market_Purchase_MarketableRestriction_1Day,
  _ as Economy_Market_Purchase_MarketableRestriction_7Days,
  _ as Economy_Market_Purchase_MarketableRestriction_NDays,
  _ as Economy_Market_Purchase_MarketableRestriction_None,
  _ as Economy_Market_Purchase_Restrictions,
  _ as Economy_Market_Purchase_TradableRestriction_1Day,
  _ as Economy_Market_Purchase_TradableRestriction_7Days,
  _ as Economy_Market_Purchase_TradableRestriction_NDays,
  _ as Economy_Market_Purchase_TradableRestriction_Permanent,
  _ as Economy_Market_TTopLevelTooltip_AccountNotTrusted_Waiting,
  _ as Economy_Market_TopLevelReason_AcceptedWalletGift,
  _ as Economy_Market_TopLevelReason_AccountHasNewPaymentMethod,
  _ as Economy_Market_TopLevelReason_AccountLocked,
  _ as Economy_Market_TopLevelReason_AccountNotTrusted,
  _ as Economy_Market_TopLevelReason_AccountNotTrusted_Waiting,
  _ as Economy_Market_TopLevelReason_AccountPasswordRecentlyReset,
  _ as Economy_Market_TopLevelReason_AccountTradeBanned,
  _ as Economy_Market_TopLevelReason_InvalidCookie,
  _ as Economy_Market_TopLevelReason_LimitedUser,
  _ as Economy_Market_TopLevelReason_NewDevice,
  _ as Economy_Market_TopLevelReason_NoSteamGuard,
  _ as Economy_Market_TopLevelReason_SelfRefund,
  _ as Economy_Market_TopLevelReason_TradeCooldown,
  _ as Economy_Market_TopLevelReason_Unknown,
  _ as Economy_Market_TopLevelTooltip_AccountLocked,
  _ as Economy_Market_TopLevelTooltip_AccountNotTrusted,
  _ as Economy_Market_TopLevelTooltip_AccountPasswordRecentlyReset,
  _ as Economy_Market_TopLevelTooltip_AccountTradeBanned,
  _ as Economy_Market_TopLevelTooltip_InvalidCookie,
  _ as Economy_Market_TopLevelTooltip_LimitedUser,
  _ as Economy_Market_TopLevelTooltip_MoreInfoLink,
  _ as Economy_Market_TopLevelTooltip_NewDevice,
  _ as Economy_Market_TopLevelTooltip_RemoveRestrictionLink,
  _ as Economy_Market_TopLevelTooltip_SelfRefund,
  _ as Economy_Market_TopLevelTooltip_SteamGuardDisabled,
  _ as Economy_Market_TopLevelTooltip_SteamGuardRecentlyEnabled,
  _ as Error_Encountered,
  _ as Error_LoadingContent,
  _ as Error_LoadingMarketItem,
  _ as Error_Sorry,
  _ as Error_TooManyRequests_Description,
  _ as FilterResults_Placeholder,
  _ as Filter_ViewResults,
  _ as Graph_Label_Price,
  _ as Graph_Label_Volume,
  _ as Graph_NoData,
  _ as Graph_NumberSold,
  _ as Graph_TimeScale_Lifetime,
  _ as Graph_TimeScale_Month,
  _ as Graph_TimeScale_Week,
  _ as Graph_TimeScale_Year,
  _ as Graph_Tooltip_NA,
  _ as Graph_Tooltip_NoPurchaseData,
  _ as Header_GiveFeedback,
  _ as Header_LearnMore,
  _ as Header_MarketDescription,
  _ as Header_MarketTitle,
  _ as Header_OptOut,
  _ as Header_Search_Filters,
  _ as Header_Search_Placeholder,
  _ as Header_Search_PlaceholderNew,
  _ as Home_GamePicker_Label,
  _ as Home_GamePicker_ViewAll,
  _ as ItemBucketPicker_Overflow_FilterPlaceholder,
  _ as ItemBucketPicker_Overflow_Placeholder,
  _ as Item_CountryBuyRestricted,
  _ as Item_CountryBuySellRestricted,
  _ as ListingFilter_Title,
  _ as Listing_EnhancedAppearance_Missing,
  _ as Listing_EnhancedAppearance_ShowBackground,
  _ as Listing_NotAvailable,
  _ as Listing_NotAvailable_Long,
  _ as Listing_NotAvailable_Short,
  _ as Listing_SomethingWentWrong,
  _ as Listings_NoneFound,
  _ as Listings_TextFilter_Placeholder,
  _ as MarketHome_PopularApps,
  _ as MarketSearch_FilterColumn_Header,
  _ as MarketSearch_Placeholder,
  _ as MarketSearch_Reset,
  _ as Market_AppUnplayedAndUnvetted,
  _ as Market_AppUnplayedAndUnvetted_Dismiss,
  _ as MedianSalePrice_Graph_Title,
  _ as Mobile_BuyOrderSection,
  _ as Mobile_FiltersButton,
  _ as Mobile_GraphSection,
  _ as Mobile_InfoSection,
  _ as MyOrders_Cancel,
  _ as MyOrders_FailedToLoad,
  _ as MyOrders_GridHeader_DateListed,
  _ as MyOrders_GridHeader_Name,
  _ as MyOrders_GridHeader_Price,
  _ as MyOrders_GridHeader_Quantity,
  _ as MyOrders_Heading,
  _ as MyOrders_Heading_Buy,
  _ as MyOrders_Heading_MyListings,
  _ as MyOrders_Heading_MyPurchaseOffers,
  _ as MyOrders_Heading_Sell,
  _ as MyOrders_NoActiveOrders_Item,
  _ as MyOrders_NoBuyOrders_Item,
  _ as MyOrders_NoSellOrders_Item,
  _ as MyOrders_QuantityWithValue,
  _ as MyOrders_Remove,
  _ as MyOrders_SeeAllN,
  _ as OrderBook_BuyOrder_Description,
  _ as OrderBook_BuyOrder_Description_None,
  _ as OrderBook_BuyOrder_Explanation_Commodity,
  _ as OrderBook_BuyOrder_Explanation_Unique,
  _ as OrderBook_BuyOrder_NeedBucket,
  _ as OrderBook_Graph_BuyTooltip,
  _ as OrderBook_Graph_BuyTooltip_Plural,
  _ as OrderBook_Graph_SellTooltip,
  _ as OrderBook_Graph_SellTooltip_Plural,
  _ as OrderBook_Graph_Title,
  _ as OrderBook_PlaceOrder_BuyRequests,
  _ as OrderBook_PlaceOrder_BuyRequests_Plural,
  _ as OrderBook_SellOrder_Description,
  _ as OrderBook_SellOrder_Description_None,
  _ as OrderBook_Table_Price,
  _ as OrderBook_Table_PriceOrLess,
  _ as OrderBook_Table_PriceOrMore,
  _ as OrderBook_Table_Quantity,
  _ as PriceFilter_ValueAndUp,
  _ as PurchaseDialog_Action_AddFunds,
  _ as PurchaseDialog_Action_Purchase,
  _ as PurchaseDialog_BillingInfo_Address,
  _ as PurchaseDialog_BillingInfo_AddressLine2,
  _ as PurchaseDialog_BillingInfo_City,
  _ as PurchaseDialog_BillingInfo_Country,
  _ as PurchaseDialog_BillingInfo_FirstName,
  _ as PurchaseDialog_BillingInfo_Label,
  _ as PurchaseDialog_BillingInfo_LastName,
  _ as PurchaseDialog_BillingInfo_SaveInfo,
  _ as PurchaseDialog_BillingInfo_StateProvince,
  _ as PurchaseDialog_BillingInfo_ZipPostal,
  _ as PurchaseDialog_Button_ViewInventory,
  _ as PurchaseDialog_Close,
  _ as PurchaseDialog_Confirmation_Body_Email,
  _ as PurchaseDialog_Confirmation_Body_Mobile,
  _ as PurchaseDialog_Confirmation_Body_Unknown,
  _ as PurchaseDialog_Confirmation_Description_Email,
  _ as PurchaseDialog_Confirmation_Description_Mobile,
  _ as PurchaseDialog_Confirmation_Description_Unknown,
  _ as PurchaseDialog_Confirmation_Title,
  _ as PurchaseDialog_Confirmation_Title_Wait,
  _ as PurchaseDialog_Details_Column_Name,
  _ as PurchaseDialog_Details_Column_Price,
  _ as PurchaseDialog_EU_SSA,
  _ as PurchaseDialog_Error_InvalidMilitaryCity,
  _ as PurchaseDialog_Error_InvalidPostal,
  _ as PurchaseDialog_Error_MissingRequired,
  _ as PurchaseDialog_Error_NoConfirmation,
  _ as PurchaseDialog_Error_ServerGeneric,
  _ as PurchaseDialog_Header,
  _ as PurchaseDialog_LocalTax_Label,
  _ as PurchaseDialog_PaymentMethod_Label,
  _ as PurchaseDialog_PaymentMethod_Wallet,
  _ as PurchaseDialog_PublisherFee_Label,
  _ as PurchaseDialog_PublisherFee_Label_Generic,
  _ as PurchaseDialog_PurchaseComplete,
  _ as PurchaseDialog_Purchase_Successful,
  _ as PurchaseDialog_SSA_Fail,
  _ as PurchaseDialog_SSA_Link,
  _ as PurchaseDialog_SSA_Link_Title,
  _ as PurchaseDialog_SteamAccount_Label,
  _ as PurchaseDialog_SteamFee_Label,
  _ as PurchaseDialog_Subtotal_Label,
  _ as PurchaseDialog_Total_Label,
  _ as PurchaseDialog_ViewInventory,
  _ as PurhcaseDialog_SaveMyAddress,
  _ as Results_GridView_Tooltip,
  _ as Results_ListView_Tooltip,
  _ as Search_AmountFound,
  _ as Search_AmountFoundFor,
  _ as Search_AmountFoundFor_Plural,
  _ as Search_AmountFound_Plural,
  _ as Search_Button,
  _ as Search_ListingQuantity,
  _ as Search_ListingQuantity_Abbreviation,
  _ as Search_ListingsFound,
  _ as Search_ListingsFound_Plural,
  _ as Search_Placeholder,
  _ as Search_ResultsFoundFor,
  _ as SellDialog_Frame_Title,
  _ as SortBy_AssetProperty_Asc,
  _ as SortBy_AssetProperty_Desc,
  _ as SortBy_Label,
  _ as SortBy_Name_Asc,
  _ as SortBy_Name_Desc,
  _ as SortBy_Popularity,
  _ as SortBy_Price_Asc,
  _ as SortBy_Price_Desc,
  _ as SortBy_Quantity_Asc,
  _ as SortBy_Quantity_Desc,
  _ as Unavailable_Header,
  _ as Unavailable_Header_Plural,
  _ as UniqueBuyOrder_Explanation_1,
  _ as UniqueBuyOrder_Explanation_2,
  _ as UniqueBuyOrder_Explanation_3,
  _ as UniqueBuyOrder_Explanation_Header,
  _ as default,
};
