var _ = `italian`,
  _ = `Messaggio originale di %1$s:`,
  _ = `{LINK RIMOSSO}`,
  _ = `L'URL qui collegato è stato rimosso dai nostri filtri, per evitare possibili attacchi tramite phishing e malware.`,
  _ = `(Solo Valve/mod) Clicca per mostrare il link`,
  _ = `%1$s commenti`,
  _ = `Visualizzazione di %1$s-%2$s commenti su %3$s`,
  _ = `Aggiungi un commento`,
  _ = `Pubblica commento`,
  _ = `Aiuto con la formattazione`,
  _ = `Inserisci emoticon`,
  _ = `Emoticon di %1$s`,
  _ = `Cerca`,
  _ = `Usate di recente`,
  _ = `Tutte le emoticon`,
  _ = `Nessuna emoticon corrisponde alla tua ricerca.`,
  _ = `Non possiedi ancora nessuna emoticon.`,
  _ = `Formattazione del testo`,
  _ = `Questi tag di markup ti consentono di aggiungere della formattazione al testo dei tuoi commenti e messaggi, analogamente all'HTML.`,
  _ = `Sintassi`,
  _ = `Esempio`,
  _ = `Testo in grassetto`,
  _ = `Testo sottolineato`,
  _ = `Testo in corsivo`,
  _ = `Testo sbarrato`,
  _ = `Testo spoiler`,
  _ = `Non interpreta i [b]tag[/b] `,
  _ = `Link a sito web`,
  _ = `Testo citato`,
  _ = `Testo a larghezza fissa
con spaziatura originale`,
  _ = `Testo dell'intestazione`,
  _ = `Testo dell'intestazione`,
  _ = `Testo dell'intestazione`,
  _ = `Elenco puntato`,
  _ = `Lista ordinata`,
  _ = `Segui discussione`,
  _ = `Smetti di seguire discussione`,
  _ = `Iscriviti a una discussione per ricevere notifiche quando qualcuno pubblica un nuovo commento.`,
  _ = `Riceverai automaticamente notifiche per questa discussione perché è associata al tuo profilo di Steam.`,
  _ = `Non siamo riusciti ad aggiornare la tua iscrizione. Riprova più tardi.`,
  _ = `Elimina`,
  _ = `Nascondi e segnala questo commento`,
  _ = `Contrassegna come sospetto`,
  _ = `Rimuovi il contrassegno di contenuto passibile di ban: %1$s`,
  _ = `Non analizzato`,
  _ = `Ripristina`,
  _ = `Verifica necessaria`,
  _ = `Molto improbabile`,
  _ = `Improbabile`,
  _ = `Possibile`,
  _ = `Probabile`,
  _ = `Molto probabile`,
  _ = `Sconosciuto (%1$s)`,
  _ = `Apri nello strumento di moderazione`,
  _ = `Hai segnalato questo commento`,
  _ = `Hai bloccato questo giocatore`,
  _ = `Annulla`,
  _ = `visualizza questo commento`,
  _ = `Le tue autorizzazioni di supporto/moderatore ti consentono di vederlo.`,
  _ = `Questo commento non è stato ancora analizzato dal nostro sistema di controllo automatico dei contenuti. Verrà nascosto temporaneamente finché non verificheremo che non abbia contenuti dannosi (ad esempio, link a siti web che tentano di rubare informazioni).`,
  _ = `Questo commento è stato automaticamente contrassegnato a causa del contenuto potenzialmente dannoso, e di conseguenza, è stato nascosto.`,
  _ = `Normalmente non avresti il permesso di pubblicare un commento qui, ma possiedi dei privilegi aggiuntivi che te lo consentono.`,
  _ = `Questo commento è stato eliminato.`,
  _ = `Il tuo commento è troppo breve.`,
  _ = `Il tuo commento è troppo lungo. La lunghezza massima è di %1$s caratteri.`,
  _ = `Non hai l'autorizzazione per pubblicare un commento qui.`,
  _ = `Devi aver effettuato l'accesso per pubblicare un commento.`,
  _ = `Devi possedere questo gioco per commentare su questo articolo.`,
  _ = `Devi aver giocato per almeno un'ora prima di poter pubblicare un commento.`,
  _ = `I commenti sono disattivati per questo articolo.`,
  _ = `Non ci sono ancora commenti.`,
  _ = {
    language: _,
    CommentThread_QuoteBlock_Author: _,
    CommentThread_RemovedLink: _,
    CommentThread_RemovedLink_Tooltip: _,
    CommentThread_RemovedLink_Reveal: _,
    CommentThread_NumberOfComments: _,
    CommentThread_ShowingXToYOfTotal: _,
    CommentThread_AddAComment: _,
    CommentThread_PostComment: _,
    CommentThread_FormattingHelp: _,
    CommentThread_InsertEmoticon: _,
    CommentThread_EmoticonHoverApp: _,
    CommentThread_EmoticonSearch: _,
    CommentThread_EmoticonRecentlyUsed: _,
    CommentThread_EmoticonAll: _,
    CommentThread_EmoticonNoResults: _,
    CommentThread_EmoticonNoneOwned: _,
    CommentThread_FormattingHelpHeader: _,
    Discussions_FormattingHelp_Description: _,
    Discussions_FormattingHelp_ColumnSyntax: _,
    Discussions_FormattingHelp_ColumnExample: _,
    Discussions_FormattingHelp_Bold: _,
    Discussions_FormattingHelp_Underline: _,
    Discussions_FormattingHelp_Italic: _,
    Discussions_FormattingHelp_Strike: _,
    Discussions_FormattingHelp_Spoiler: _,
    Discussions_FormattingHelp_Noparse: _,
    Discussions_FormattingHelp_Link: _,
    Discussions_FormattingHelp_Quote: _,
    Discussions_FormattingHelp_Code: _,
    Discussions_FormattingHelp_H1: _,
    Discussions_FormattingHelp_H2: _,
    Discussions_FormattingHelp_H3: _,
    Discussions_FormattingHelp_List: _,
    Discussions_FormattingHelp_OList: _,
    CommentThread_Subscribe: _,
    CommentThread_Unsubscribe: _,
    CommentThread_SubscribeHint: _,
    CommentThread_SubscribeHintOwnThread: _,
    CommentThread_SubscribeError: _,
    CommentThread_DeleteComment: _,
    CommentThread_HideComment: _,
    CommentThread_MarkSpam: _,
    CommentThread_ClearContentCheck: _,
    BanContentCheckResult_NotScanned: _,
    BanContentCheckResult_Reset: _,
    BanContentCheckResult_NeedsChecking: _,
    BanContentCheckResult_VeryUnlikely: _,
    BanContentCheckResult_Unlikely: _,
    BanContentCheckResult_Possible: _,
    BanContentCheckResult_Likely: _,
    BanContentCheckResult_VeryLikely: _,
    BanContentCheckResult_Unknown: _,
    CommentThread_ModerationTool: _,
    CommentThread_HiddenByUser: _,
    CommentThread_HiddenByBlocked: _,
    CommentThread_HiddenUndo: _,
    CommentThread_HiddenViewComment: _,
    CommentThread_ModeratorViewContent: _,
    CommentThread_NeedsContentCheck: _,
    CommentThread_FailedContentCheck: _,
    CommentThread_PermissionOverride: _,
    CommentThread_Deleted: _,
    CommentThread_PostError_TooShort: _,
    CommentThread_PostError_TooLong: _,
    CommentThread_PostError_NotAllowed: _,
    CommentThread_PostError_NotLoggedIn: _,
    CommentThread_PostError_MustOwnApp: _,
    CommentThread_PostError_LimitedUser: _,
    CommentThread_CommentsDisabled: _,
    CommentThread_NoComments: _,
  };
export {
  _ as BanContentCheckResult_Likely,
  _ as BanContentCheckResult_NeedsChecking,
  _ as BanContentCheckResult_NotScanned,
  _ as BanContentCheckResult_Possible,
  _ as BanContentCheckResult_Reset,
  _ as BanContentCheckResult_Unknown,
  _ as BanContentCheckResult_Unlikely,
  _ as BanContentCheckResult_VeryLikely,
  _ as BanContentCheckResult_VeryUnlikely,
  _ as CommentThread_AddAComment,
  _ as CommentThread_ClearContentCheck,
  _ as CommentThread_CommentsDisabled,
  _ as CommentThread_DeleteComment,
  _ as CommentThread_Deleted,
  _ as CommentThread_EmoticonAll,
  _ as CommentThread_EmoticonHoverApp,
  _ as CommentThread_EmoticonNoResults,
  _ as CommentThread_EmoticonNoneOwned,
  _ as CommentThread_EmoticonRecentlyUsed,
  _ as CommentThread_EmoticonSearch,
  _ as CommentThread_FailedContentCheck,
  _ as CommentThread_FormattingHelp,
  _ as CommentThread_FormattingHelpHeader,
  _ as CommentThread_HiddenByBlocked,
  _ as CommentThread_HiddenByUser,
  _ as CommentThread_HiddenUndo,
  _ as CommentThread_HiddenViewComment,
  _ as CommentThread_HideComment,
  _ as CommentThread_InsertEmoticon,
  _ as CommentThread_MarkSpam,
  _ as CommentThread_ModerationTool,
  _ as CommentThread_ModeratorViewContent,
  _ as CommentThread_NeedsContentCheck,
  _ as CommentThread_NoComments,
  _ as CommentThread_NumberOfComments,
  _ as CommentThread_PermissionOverride,
  _ as CommentThread_PostComment,
  _ as CommentThread_PostError_LimitedUser,
  _ as CommentThread_PostError_MustOwnApp,
  _ as CommentThread_PostError_NotAllowed,
  _ as CommentThread_PostError_NotLoggedIn,
  _ as CommentThread_PostError_TooLong,
  _ as CommentThread_PostError_TooShort,
  _ as CommentThread_QuoteBlock_Author,
  _ as CommentThread_RemovedLink,
  _ as CommentThread_RemovedLink_Reveal,
  _ as CommentThread_RemovedLink_Tooltip,
  _ as CommentThread_ShowingXToYOfTotal,
  _ as CommentThread_Subscribe,
  _ as CommentThread_SubscribeError,
  _ as CommentThread_SubscribeHint,
  _ as CommentThread_SubscribeHintOwnThread,
  _ as CommentThread_Unsubscribe,
  _ as Discussions_FormattingHelp_Bold,
  _ as Discussions_FormattingHelp_Code,
  _ as Discussions_FormattingHelp_ColumnExample,
  _ as Discussions_FormattingHelp_ColumnSyntax,
  _ as Discussions_FormattingHelp_Description,
  _ as Discussions_FormattingHelp_H1,
  _ as Discussions_FormattingHelp_H2,
  _ as Discussions_FormattingHelp_H3,
  _ as Discussions_FormattingHelp_Italic,
  _ as Discussions_FormattingHelp_Link,
  _ as Discussions_FormattingHelp_List,
  _ as Discussions_FormattingHelp_Noparse,
  _ as Discussions_FormattingHelp_OList,
  _ as Discussions_FormattingHelp_Quote,
  _ as Discussions_FormattingHelp_Spoiler,
  _ as Discussions_FormattingHelp_Strike,
  _ as Discussions_FormattingHelp_Underline,
  _ as default,
  _ as language,
};
