var _ = `Mensagens no fórum`,
  _ = `Discussões gerais`,
  _ = `Mensagens denunciadas`,
  _ = `Discussões da Oficina`,
  _ = `Trocas`,
  _ = `Eventos e anúncios`,
  _ = `1 denúncia`,
  _ = `%1$s denúncias`,
  _ = `1 assunto`,
  _ = `%1$s assuntos`,
  _ = `%1$s sobre %2$s`,
  _ = `%1$s sobre %2$s no tópico: %3$s`,
  _ = `1 denúncia`,
  _ = `%1$s denúncias`,
  _ = `1 assunto`,
  _ = `%1$s assuntos`,
  _ = `Comunidade Steam`,
  _ = `Comunidade Steam :: Erro`,
  _ = `Erro`,
  _ = `Erro desconhecido`,
  _ = `Jogos`,
  _ = `Comunidade Steam :: %1$s :: Jogos`,
  _ = `Buscar — Mercado da Comunidade Steam`,
  _ = `%1$s — Mercado da Comunidade Steam`,
  _ = `Item do Mercado — Mercado da Comunidade Steam`,
  _ = `Mercado da Comunidade Steam`,
  _ = `Perfil não encontrado`,
  _ = `Falha ao carregar a lista de desejos do usuário.`,
  _ = `Você realizou solicitações demais recentemente. Aguarde e tente realizar a sua solicitação novamente mais tarde.`,
  _ = `Carregando`,
  _ = `PROGRESSO: %1$s%`,
  _ = `PAUSADO — PROGRESSO: %1$s%`,
  _ = `BAIXADO: %1$s/%2$s`,
  _ = `CONQUISTAS`,
  _ = `Tempo restante estimado: %1$s`,
  _ = `%1$s/%2$s`,
  _ = `DESINSTALANDO`,
  _ = `ATUALIZAR`,
  _ = `DESINSTALAR`,
  _ = `BAIXAR`,
  _ = `PAUSAR`,
  _ = `RETOMAR`,
  _ = `DESINSTALANDO`,
  _ = `CANCELAR`,
  _ = `Ver as minhas configurações de privacidade para esse conteúdo.`,
  _ = `Buscar um jogo`,
  _ = `Exibir somente os jogos que ambos possuam`,
  _ = `Tempo de jogo`,
  _ = `A–Z`,
  _ = `Conquistas alcançadas`,
  _ = `TEMPO DE JOGO`,
  _ = `ÚLTIMA SESSÃO`,
  _ = `ÚLTIMAS DUAS SEMANAS`,
  _ = `Dados e links do jogo`,
  _ = `Downloads remotos`,
  _ = `BAIXAR EM: %1$s`,
  _ = `ESTADO DO DOWNLOAD REMOTO: %1$s`,
  _ = `Sem acesso ao computador`,
  _ = `Para baixar jogos remotamente no seu cliente Steam, o computador deve estar ativo, conectado à internet e com a sessão iniciada`,
  _ = `Leia as perguntas frequentes`,
  _ = `%1$s. %2$s`,
  _ = `Saiba mais`,
  _ = `DOWNLOAD REMOTO INDISPONÍVEL`,
  _ = `Deseja desinstalar %1$s? %1$s continuará presente na sua biblioteca de jogos, mas para jogar novamente no futuro será preciso baixar todo o conteúdo novamente.`,
  _ = `%1$s | "%2$s"`,
  _ = `Recém-jogados %1$s`,
  _ = `Todos os jogos %1$s`,
  _ = `Jogos perfeitos %1$s`,
  _ = `Análises %1$s`,
  _ = `Seguidos %1$s`,
  _ = `Lista de desejos`,
  _ = `Alcançou todas as conquistas possíveis.`,
  _ = `Nesta lista, você poderá encontrar os seus "Jogos perfeitos" — aqueles em que alcançou todas as conquistas possíveis.`,
  _ = `Alcançada por %1$s% dos jogadores`,
  _ = `Página na loja`,
  _ = `Fóruns`,
  _ = `Grupos`,
  _ = `Site oficial`,
  _ = `Notícias`,
  _ = `Minhas conquistas`,
  _ = `Conquistas de %1$s`,
  _ = `Estatísticas de %1$s`,
  _ = `Dados pessoais de %1$s`,
  _ = `Minhas classificações`,
  _ = `Classificações de %1$s`,
  _ = `Conquistas globais`,
  _ = `Classificações globais`,
  _ = `Estatísticas do jogo`,
  _ = `Conteúdo do jogo`,
  _ = `Minhas estatísticas no jogo`,
  _ = `Meu conteúdo do jogo`,
  _ = `Links do jogo`,
  _ = `Minhas capturas de tela %1$s`,
  _ = `Capturas de tela de %1$s %2$s`,
  _ = `Amigos que jogam %1$s`,
  _ = `Minhas cartas colecionáveis %1$s`,
  _ = `Minha análise`,
  _ = `Análise de %1$s`,
  _ = `Central da Comunidade`,
  _ = `Minhas anotações`,
  _ = `%1$s horas`,
  _ = `%1$s minutos`,
  _ = `Marcar como privado`,
  _ = `Desmarcar como privado`,
  _ = `Marcar este jogo como privado e ocultá-lo dos meus amigos`,
  _ = `© Valve Corporation. Todos os direitos reservados. Todas as marcas registradas são propriedade dos seus respectivos donos nos EUA e em outros países.`,
  _ = `Alguns dados geoespaciais neste site são fornecidos por %1$s.`,
  _ = `Política de Privacidade`,
  _ = `Termos Legais`,
  _ = `Acordo de Assinatura do Steam`,
  _ = `Reembolsos`,
  _ = `Cookies`,
  _ = `Acessibilidade`,
  _ = `Banimentos atuais`,
  _ = `Mensagens da comunidade`,
  _ = `Conteúdo denunciado`,
  _ = `Conteúdo moderado`,
  _ = `Estes são os conteúdos publicados no Steam que você denunciou por violar as diretrizes do Steam.`,
  _ = `Estes são os conteúdos que você publicou no Steam e sofreram uma ação da moderação.`,
  _ = `Atualizado em: %1$s`,
  _ = ``,
  _ = {
    Moderation_SubjectTypeName_ForumPost: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    moderation_claim_report_count: _,
    moderation_claim_report_count_Plural: _,
    moderation_claim_subject_count: _,
    moderation_claim_subject_count_Plural: _,
    moderation_claim_n_reports_on_m_subjects: _,
    moderation_forumpost_summary: _,
    moderation_forumpost_summary_reports_fragment: _,
    moderation_forumpost_summary_reports_fragment_Plural: _,
    moderation_forumpost_summary_subjects_fragment: _,
    moderation_forumpost_summary_subjects_fragment_Plural: _,
    community_title: _,
    community_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    profile_games_list: _,
    profile_games_list_title: _,
    Market_Search_Title: _,
    Market_Item_Title: _,
    Market_Item_GenericTitle: _,
    Market_GenericTitle: _,
    profile_error_profilenotfound: _,
    profile_games_list_error_loadfailed: _,
    Error_RateLimited: _,
    Loading: _,
    GamesList_Header_Downloading: _,
    GamesList_Header_Paused: _,
    GamesList_Header_DownloadBytes: _,
    GamesList_Header_Achievements: _,
    GamesList_TimeRemaining: _,
    GamesList_Achievement_Fraction: _,
    GamesList_Uninstalling: _,
    GamesList_Button_UpdateRequired: _,
    GamesList_Button_Uninstall: _,
    GamesList_Button_Download: _,
    GamesList_Button_Pause: _,
    GamesList_Button_Resume: _,
    GamesList_Button_Uninstalling: _,
    GamesList_Button_Cancel: _,
    GamesList_PrivacySettings_Tooltip: _,
    GamesList_Filter_Placeholder: _,
    GamesList_Filter_BothOwned: _,
    GamesList_Sort_HoursPlayed: _,
    GamesList_Sort_Name: _,
    GamesList_Sort_AchievementCompletion: _,
    GamesList_Header_TotalPlayed: _,
    GamesList_Header_LastPlayed: _,
    GamesList_Header_TwoWeeks: _,
    GamesList_MenuLabel_GameInfo: _,
    GamesList_MenuLabel_RemoteDownload: _,
    GamesList_Header_RemoteDownload: _,
    GamesList_Header_RemoteDownloadStatus: _,
    GamesList_RemoteDownload_NoConnection: _,
    GamesList_RemoteDownload_Help: _,
    GamesList_RemoteDownload_ReadTheFAQ: _,
    GamesList_RemoteDownload_Info: _,
    GamesList_RemoteDownload_LearnMore: _,
    GamesList_RemoteDownload_NoRemoteControl: _,
    GamesList_RemoteDownload_UninstallConfirm: _,
    GamesList_Client_Indicator: _,
    GamesList_Tab_RecentlyPlayed: _,
    GamesList_Tab_AllGames: _,
    GamesList_Tab_PerfectGames: _,
    GamesList_Tab_Reviews: _,
    GamesList_Tab_Followed: _,
    GamesList_Tab_Wishlist: _,
    Perfect_Game_Description: _,
    GamesList_PerfectGames_Description: _,
    GamesList_Achievement_Unlock_Percentage: _,
    Community_StorePage: _,
    Community_Forums: _,
    Community_Groups: _,
    Community_OfficialWebsite: _,
    Community_News: _,
    Community_UsersAchievementsFirstPerson: _,
    Community_UsersAchievements: _,
    Community_UsersStats: _,
    Community_GamePersonalData: _,
    Community_UsersLeaderboardsFirstPerson: _,
    Community_UsersLeaderboards: _,
    Community_GlobalAchievements: _,
    Community_GlobalLeaderboards: _,
    Community_GameStats: _,
    Community_GameContent: _,
    Community_GameStatsFirstPerson: _,
    Community_GameContentFirstPerson: _,
    Community_GameLinks: _,
    Community_ScreenshotsMenuItemFirstPerson: _,
    Community_ScreenshotsMenuItemThirdPerson: _,
    Community_FriendsWhoPlayMenuItemFirstPerson: _,
    Community_TradingCardsMenuItemFirstPerson: _,
    Community_ReviewMenuItemFirstPerson: _,
    Community_ReviewMenuItemThirdPerson: _,
    Community_GameHubMenuItem: _,
    Community_GameNotesFirstPerson: _,
    Playtime_Hours: _,
    Playtime_Minutes: _,
    AppPrivacy_MarkAsPrivate: _,
    AppPrivacy_UnmarkAsPrivate: _,
    AppPrivacy_Explanation: _,
    footer_legal_notice: _,
    footer_geodata_notice: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_accessibility: _,
    profiletabs_currentbans: _,
    profiletabs_communitymessages: _,
    profiletabs_reportedcontent: _,
    profiletabs_moderatedcontent: _,
    reportedcontent_description: _,
    moderatedcontent_description: _,
    reportedcontent_lastupdated: _,
    empty_no_comma_following: ``,
  };
export {
  _ as AppPrivacy_Explanation,
  _ as AppPrivacy_MarkAsPrivate,
  _ as AppPrivacy_UnmarkAsPrivate,
  _ as Community_Forums,
  _ as Community_FriendsWhoPlayMenuItemFirstPerson,
  _ as Community_GameContent,
  _ as Community_GameContentFirstPerson,
  _ as Community_GameHubMenuItem,
  _ as Community_GameLinks,
  _ as Community_GameNotesFirstPerson,
  _ as Community_GamePersonalData,
  _ as Community_GameStats,
  _ as Community_GameStatsFirstPerson,
  _ as Community_GlobalAchievements,
  _ as Community_GlobalLeaderboards,
  _ as Community_Groups,
  _ as Community_News,
  _ as Community_OfficialWebsite,
  _ as Community_ReviewMenuItemFirstPerson,
  _ as Community_ReviewMenuItemThirdPerson,
  _ as Community_ScreenshotsMenuItemFirstPerson,
  _ as Community_ScreenshotsMenuItemThirdPerson,
  _ as Community_StorePage,
  _ as Community_TradingCardsMenuItemFirstPerson,
  _ as Community_UsersAchievements,
  _ as Community_UsersAchievementsFirstPerson,
  _ as Community_UsersLeaderboards,
  _ as Community_UsersLeaderboardsFirstPerson,
  _ as Community_UsersStats,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as GamesList_Achievement_Fraction,
  _ as GamesList_Achievement_Unlock_Percentage,
  _ as GamesList_Button_Cancel,
  _ as GamesList_Button_Download,
  _ as GamesList_Button_Pause,
  _ as GamesList_Button_Resume,
  _ as GamesList_Button_Uninstall,
  _ as GamesList_Button_Uninstalling,
  _ as GamesList_Button_UpdateRequired,
  _ as GamesList_Client_Indicator,
  _ as GamesList_Filter_BothOwned,
  _ as GamesList_Filter_Placeholder,
  _ as GamesList_Header_Achievements,
  _ as GamesList_Header_DownloadBytes,
  _ as GamesList_Header_Downloading,
  _ as GamesList_Header_LastPlayed,
  _ as GamesList_Header_Paused,
  _ as GamesList_Header_RemoteDownload,
  _ as GamesList_Header_RemoteDownloadStatus,
  _ as GamesList_Header_TotalPlayed,
  _ as GamesList_Header_TwoWeeks,
  _ as GamesList_MenuLabel_GameInfo,
  _ as GamesList_MenuLabel_RemoteDownload,
  _ as GamesList_PerfectGames_Description,
  _ as GamesList_PrivacySettings_Tooltip,
  _ as GamesList_RemoteDownload_Help,
  _ as GamesList_RemoteDownload_Info,
  _ as GamesList_RemoteDownload_LearnMore,
  _ as GamesList_RemoteDownload_NoConnection,
  _ as GamesList_RemoteDownload_NoRemoteControl,
  _ as GamesList_RemoteDownload_ReadTheFAQ,
  _ as GamesList_RemoteDownload_UninstallConfirm,
  _ as GamesList_Sort_AchievementCompletion,
  _ as GamesList_Sort_HoursPlayed,
  _ as GamesList_Sort_Name,
  _ as GamesList_Tab_AllGames,
  _ as GamesList_Tab_Followed,
  _ as GamesList_Tab_PerfectGames,
  _ as GamesList_Tab_RecentlyPlayed,
  _ as GamesList_Tab_Reviews,
  _ as GamesList_Tab_Wishlist,
  _ as GamesList_TimeRemaining,
  _ as GamesList_Uninstalling,
  _ as Loading,
  _ as Market_GenericTitle,
  _ as Market_Item_GenericTitle,
  _ as Market_Item_Title,
  _ as Market_Search_Title,
  _ as Moderation_SubjectTypeName_ForumPost,
  _ as Perfect_Game_Description,
  _ as Playtime_Hours,
  _ as Playtime_Minutes,
  _ as community_errorpage_title,
  _ as community_title,
  _ as default,
  _ as empty_no_comma_following,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_accessibility,
  _ as footer_cookies,
  _ as footer_geodata_notice,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_privacy_policy,
  _ as footer_refunds,
  _ as footer_ssa,
  _ as moderatedcontent_description,
  _ as moderation_claim_n_reports_on_m_subjects,
  _ as moderation_claim_report_count,
  _ as moderation_claim_report_count_Plural,
  _ as moderation_claim_subject_count,
  _ as moderation_claim_subject_count_Plural,
  _ as moderation_forumpost_summary,
  _ as moderation_forumpost_summary_reports_fragment,
  _ as moderation_forumpost_summary_reports_fragment_Plural,
  _ as moderation_forumpost_summary_subjects_fragment,
  _ as moderation_forumpost_summary_subjects_fragment_Plural,
  _ as profile_error_profilenotfound,
  _ as profile_games_list,
  _ as profile_games_list_error_loadfailed,
  _ as profile_games_list_title,
  _ as profiletabs_communitymessages,
  _ as profiletabs_currentbans,
  _ as profiletabs_moderatedcontent,
  _ as profiletabs_reportedcontent,
  _ as reportedcontent_description,
  _ as reportedcontent_lastupdated,
};
