var _ = `Messages dans le forum`,
  _ = `Discussions générales`,
  _ = `Messages signalés`,
  _ = `Discussions du Workshop`,
  _ = `Échanges`,
  _ = `Évènements et annonces`,
  _ = `1\xA0signalement`,
  _ = `%1$s\xA0signalements`,
  _ = `1\xA0sujet`,
  _ = `%1$s\xA0sujets`,
  _ = `%1$s sur %2$s`,
  _ = `%1$s de %2$s sur le sujet\xA0: %3$s`,
  _ = `1\xA0signalement`,
  _ = `%1$s\xA0signalements`,
  _ = `1\xA0sujet`,
  _ = `%1$s\xA0sujets`,
  _ = `Communauté Steam`,
  _ = `Communauté\xA0Steam\xA0::\xA0Erreur`,
  _ = `Erreur`,
  _ = `Erreur inconnue`,
  _ = `Jeux`,
  _ = `Communauté\xA0Steam\xA0::\xA0%1$s\xA0::\xA0Jeux`,
  _ = `Recherche – Marché de la communauté\xA0Steam`,
  _ = `%1$s – Marché de la communauté\xA0Steam`,
  _ = `Item du marché\xA0– Marché de la communauté\xA0Steam`,
  _ = `Marché de la communauté Steam`,
  _ = `Profil introuvable`,
  _ = `Impossible de charger la liste de souhaits de cette personne.`,
  _ = `Vous avez récemment fait trop de demandes. Veuillez patienter et réitérer votre demande ultérieurement.`,
  _ = `Chargement`,
  _ = `PROGRESSION\xA0: %1$s\xA0%`,
  _ = `EN PAUSE – PROGRESSION\xA0: %1$s\xA0%`,
  _ = `TÉLÉCHARGEMENT\xA0: %1$s / %2$s`,
  _ = `SUCCÈS`,
  _ = `Temps restant estimé\xA0: %1$s`,
  _ = `%1$s/%2$s`,
  _ = `DÉSINSTALLATION EN COURS`,
  _ = `METTRE À JOUR`,
  _ = `DÉSINSTALLER`,
  _ = `TÉLÉCHARGER`,
  _ = `PAUSE`,
  _ = `REPRENDRE`,
  _ = `DÉSINSTALLATION EN COURS`,
  _ = `ANNULER`,
  _ = `Consulter mes paramètres de confidentialité pour ce contenu`,
  _ = `Trouver un jeu`,
  _ = `Afficher les jeux en commun`,
  _ = `Temps de jeu\xA0`,
  _ = `Nom`,
  _ = `Progression des succès`,
  _ = `TEMPS DE JEU TOTAL`,
  _ = `DERNIER LANCEMENT`,
  _ = `CES DEUX DERNIÈRES SEMAINES`,
  _ = `Liens et informations sur le jeu`,
  _ = `Téléchargement à distance`,
  _ = `TÉLÉCHARGEMENT À DISTANCE VERS\xA0: %1$s`,
  _ = `ÉTAT DU TÉLÉCHARGEMENT À DISTANCE\xA0: %1$s`,
  _ = `Communication avec votre PC impossible`,
  _ = `Pour télécharger des jeux à distance, votre PC doit être hors du mode veille et connecté à Internet, et une session doit avoir été ouverte.`,
  _ = `Lire la FAQ`,
  _ = `%1$s. %2$s`,
  _ = `En savoir plus`,
  _ = `TÉLÉCHARGEMENT À DISTANCE NON DISPONIBLE`,
  _ = `Voulez-vous vraiment désinstaller %1$s\xA0? Le produit s'affichera toujours dans votre bibliothèque, mais vous devrez le télécharger à nouveau pour l'utiliser.`,
  _ = `%1$s\xA0: «\xA0%2$s\xA0»`,
  _ = `Lancés récemment %1$s`,
  _ = `Tous les jeux %1$s`,
  _ = `Jeux terminés à 100\xA0% %1$s`,
  _ = `Évaluations %1$s`,
  _ = `Jeux suivis %1$s`,
  _ = `Liste de souhaits`,
  _ = `Vous avez obtenu tous les succès.`,
  _ = `Vous trouverez ici vos jeux terminés à 100\xA0% ou les jeux pour lesquels vous avez gagné tous les succès possibles.`,
  _ = `%1$s\xA0% des joueurs et joueuses ont débloqué ce succès`,
  _ = `Page du magasin`,
  _ = `Forums`,
  _ = `Groupes`,
  _ = `Site officiel`,
  _ = `Actualités`,
  _ = `Mes succès`,
  _ = `Succès de %1$s`,
  _ = `Statistiques de %1$s`,
  _ = `Données de jeu personnelles de %1$s`,
  _ = `Mes classements`,
  _ = `Classements de %1$s`,
  _ = `Succès globaux`,
  _ = `Classements globaux`,
  _ = `Stats de jeu`,
  _ = `Contenu du jeu`,
  _ = `Mes stats de jeu`,
  _ = `Mon contenu de jeu`,
  _ = `Liens connexes`,
  _ = `Mes captures d'écran %1$s`,
  _ = `Captures d'écran de %1$s %2$s`,
  _ = `Contacts qui y jouent %1$s`,
  _ = `Mes cartes à échanger %1$s`,
  _ = `Mon évaluation`,
  _ = `Évaluation de %1$s`,
  _ = `Hub de la communauté`,
  _ = `Mes notes`,
  _ = `%1$s\xA0heures`,
  _ = `%1$s\xA0minutes`,
  _ = `Définir comme privé`,
  _ = `Ne plus définir comme privé`,
  _ = `Rendre ce jeu privé et le masquer de mes contacts`,
  _ = `© Valve Corporation. Tous droits réservés. Toutes les marques sont la propriété de leurs propriétaires respectifs aux USA et autres pays.`,
  _ = `Certaines données géographiques de ce site sont fournies par %1$s.`,
  _ = `Politique de protection de la vie privée`,
  _ = `Mentions légales`,
  _ = `Accord de souscription Steam`,
  _ = `Remboursements`,
  _ = `Cookies`,
  _ = `Accessibilité`,
  _ = `Bannissements en vigueur`,
  _ = `Messages de la communauté`,
  _ = `Contenu signalé`,
  _ = `Contenu modéré`,
  _ = `Voici une liste du contenu que vous avez signalé pour avoir enfreint les directives de Steam.`,
  _ = `Voici une liste du contenu que vous avez publié sur Steam et qui a été modéré.`,
  _ = `Dernière mise à jour\xA0:\xA0%1$s`,
  _ = `Télécharger`,
  _ = `Commentaires publics (%1$s)`,
  _ = `Commentaires des équipes de développement (%1$s)`,
  _ = `Ceci est un sujet privé visible uniquement par les contributeurs et contributrices de cet article et par l'équipe de développement du jeu.`,
  _ = `Avertissement\xA0: des échanges avec l'équipe de développement du jeu (Valve, par exemple) ne garantissent pas forcément le choix de votre création pour une intégration en jeu.`,
  _ = `Taille`,
  _ = `Voir toutes les captures d'écran`,
  _ = `Afficher toutes les créations`,
  _ = `Voir toutes les vidéos`,
  _ = `Légende`,
  _ = `Modifier la légende`,
  _ = `Ajouter la mention «\xA0divulgâcheur\xA0»`,
  _ = `Supprimer la mention «\xA0divulgâcheur\xA0»`,
  _ = `La mention «\xA0divulgâcheur\xA0» permet à vos contacts et à l'ensemble de la communauté d'éviter de voir ce contenu, qui pourrait leur dévoiler une partie du jeu à leur insu.`,
  _ = `(Cette mention est automatiquement supprimée au bout de quatre semaines.)`,
  _ = `Comptes sur cette capture d'écran\xA0:`,
  _ = `Articles du Workshop présents sur cette capture d'écran\xA0: `,
  _ = `Supprimez votre identification de cette capture d'écran`,
  _ = `Lieu`,
  _ = `Mots-clés\xA0:`,
  _ = `Chargement du guide`,
  _ = `Abonnez-vous pour utiliser ce guide depuis %1$s`,
  _ = `Index du guide`,
  _ = `Vue d'ensemble`,
  _ = `Commentaires`,
  _ = `Modifier`,
  _ = `{LIEN SUPPRIMÉ}`,
  _ = `L'adresse URL qui était renseignée ici a été retirée par nos filtres. Généralement, cette suppression a pour but d'empêcher le hameçonnage (phishing) et les attaques de logiciels malveillants (malware).`,
  _ = `Table des matières du guide`,
  _ = `Définissez l'organisation et le nom des sections de votre guide. Vous pouvez faire glisser les sections pour les réorganiser.`,
  _ = `Cette section doit être remplie pour publier le guide.`,
  _ = `Créez une table des matières`,
  _ = `Ajouter une section`,
  _ = `(nouvelle section, pas encore de titre)`,
  _ = `Modifier cette section`,
  _ = `Supprimer cette section`,
  _ = `Voulez-vous vraiment supprimer cette section\xA0? Cette action est irréversible.`,
  _ = `Images`,
  _ = `Sélectionnez et mettez en ligne les images que vous souhaitez référencer dans votre guide. Mettez en ligne toutes les images nécessaires ici afin que celles-ci soient facilement sélectionnables lors de votre travail sur les sections individuelles de votre guide.`,
  _ = `Ajoutez des images à votre guide`,
  _ = `Ajouter des contributeurs et contributrices`,
  _ = `Ici, vous pouvez donner le statut de contributeur ou contributrice à des contacts afin de leur donner accès à l'édition de votre guide.`,
  _ = `Invitez des contacts à contribuer`,
  _ = `Ajouter une personne contributrice`,
  _ = `Prévisualiser le guide`,
  _ = `Modifier la section du guide`,
  _ = `Titre de la section`,
  _ = `Contenu de la section`,
  _ = `Modifier`,
  _ = `Prévisualiser`,
  _ = `Voir les différences`,
  _ = `Tout changement apporté à votre texte depuis la dernière sauvegarde apparaitra ainsi\xA0:`,
  _ = `Le texte affiché comme cela a été ajouté`,
  _ = `Le texte affiché comme cela a été supprimé`,
  _ = `Des modifications non enregistrées ont été apportées à cette section.`,
  _ = `Des modifications non enregistrées ont été apportées à cette section. Voulez-vous vraiment annuler ces changements\xA0?`,
  _ = `Dernier enregistrement le`,
  _ = `Enregistrer`,
  _ = `Annuler`,
  _ = `Captures d'écran`,
  _ = `Vidéos`,
  _ = `Cliquez sur une image ci-dessous pour l'ajouter à votre guide`,
  _ = `Cliquez sur une capture d'écran ci-dessous pour l'ajouter à votre guide`,
  _ = `Cliquez sur une vidéo ci-dessous pour l'ajouter à votre guide`,
  _ = `Options d'insertion des images`,
  _ = `Dimensions`,
  _ = `demi-largeur`,
  _ = `pleine largeur`,
  _ = `taille d'origine`,
  _ = `Position`,
  _ = `gauche`,
  _ = `droite`,
  _ = `alignée`,
  _ = `Alignée à gauche`,
  _ = `Alignée à droite`,
  _ = `Pleine largeur`,
  _ = `Insérer`,
  _ = `Insérer une vidéo YouTube™`,
  _ = `Saisissez l'URL de la vidéo YouTube™`,
  _ = `Citation`,
  _ = `Divulgâcheur`,
  _ = `Veuillez saisir un titre`,
  _ = `Accéder à votre guide`,
  _ = ``,
  _ = `Articles du Workshop\xA0:`,
  _ = `et %1$s de plus`,
  _ = `Voir les commentaires et les détails`,
  _ = `Voir les %1$s\xA0commentaires et détails`,
  _ = `Captures d'écran`,
  _ = `Illustrations`,
  _ = `Vidéos`,
  _ = `Articles du Workshop`,
  _ = `Produit dérivé`,
  _ = `Collections`,
  _ = `Guides`,
  _ = `Articles du Workshop`,
  _ = `Collections du Workshop`,
  _ = `Guides`,
  _ = `Favoris`,
  _ = `Abonnements`,
  _ = `Joué`,
  _ = `Filtrer par jeu\xA0`,
  _ = `Tous les jeux`,
  _ = `Sélectionnez un jeu`,
  _ = `Articles`,
  _ = `Favoris`,
  _ = `Abonnements aux articles`,
  _ = `Date de création`,
  _ = `Alphabétique`,
  _ = `Date de mise à jour`,
  _ = `Date d'abonnement`,
  _ = `Date d'ajout`,
  _ = `Afficher les articles correspondant à tous les termes choisis\xA0:`,
  _ = `par`,
  _ = `Affichage des entrées %1$s à %2$s sur %3$s`,
  _ = `Aucun fichier correspondant n'a été trouvé pour %1$s.`,
  _ = `Affichage des entrées %1$s à %2$s sur %3$s`,
  _ = `Dernière mise à jour le %1$s`,
  _ = `Ajouté le %1$s`,
  _ = `Cet article a été retiré de votre liste de favoris\xA0:`,
  _ = `Abonné(e) le %1$s`,
  _ = `Vous êtes maintenant désabonné(e) de\xA0:`,
  _ = `Hourra\xA0! Certaines de vos contributions au Workshop Steam ont été sélectionnées pour intégration\xA0!`,
  _ = `Avant de partir fêter cette bonne nouvelle, veuillez saisir vos <a href="%1$s">informations de paiement</a> pour que nous sachions qui rémunérer\xA0!`,
  _ = `Un problème s'est produit lors de la tentative de vérification de vos informations de paiement. Veuillez vérifier vos <a href="%1$s">informations de paiement</a> et les mettre à jour.`,
  _ = `Vous avez été ajouté(e) à l'équipe de contribution des articles suivants`,
  _ = `Veuillez consulter et accepter la mention de paternité des articles suivants`,
  _ = `Pourcentage\xA0:`,
  _ = `Votre Workshop`,
  _ = `Suivez cette personne pour voir lorsqu'elle publie de nouveaux guides Steam, crée de nouvelles collections ou propose des articles sur le Workshop\xA0Steam.`,
  _ = `Les personnes qui vous suivent voient lorsque vous publiez de nouveaux guides Steam, créez de nouvelles collections ou proposez des articles sur le Workshop\xA0Steam.`,
  _ = `abonné(e)`,
  _ = `abonné(e)s`,
  _ = `Suivre %1$s`,
  _ = `Suit %1$s`,
  _ = `Ne plus suivre %1$s`,
  _ = `Voir les revenus`,
  _ = `Des ventes de vos articles du Workshop`,
  _ = `Saisir ou mettre à jour vos informations de paiement`,
  _ = `Consulter les mentions légales`,
  _ = `Annuler tous les abonnements`,
  _ = `Annuler tous les abonnements\xA0?`,
  _ = `Voulez-vous vraiment annuler tous vos abonnements\xA0?<br><br>Cette action est irréversible.`,
  _ = `Voulez-vous vraiment annuler tous vos abonnements à %1$s\xA0?<br><br>Cette action est irréversible.`,
  _ = `Enregistrer dans une collection`,
  _ = `Enregistrer des abonnements dans une collection`,
  _ = `Souhaitez-vous enregistrer vos abonnements dans une nouvelle collection ou dans une collection existante\xA0?`,
  _ = `Nouvelle collection`,
  _ = `Nommez cette collection\xA0:`,
  _ = `Collection existante`,
  _ = `Sélectionnez une collection à remplacer\xA0: `,
  _ = `Vous n'avez aucune collection existante. En créer une nouvelle\xA0?`,
  _ = `Tags d'administration`,
  _ = `Guides Steam`,
  _ = `Guides intégrés`,
  _ = `Builds de héros`,
  _ = `Guides intégrés spécialement afin de vous apprendre à jouer`,
  _ = `Guides spécialement intégrés avec %1$s`,
  _ = `Catégories populaires`,
  _ = `Guides intégrés`,
  _ = `Vos favoris`,
  _ = `Guides Steam populaires`,
  _ = `Guides rédigés, références et soluces`,
  _ = `Tout voir (%1$s)`,
  _ = `%1$s\xA0guide`,
  _ = `%1$s\xA0guides`,
  _ = `Guides que vous avez créés`,
  _ = `Plus d'infos sur les guides`,
  _ = `Cliquez ici pour en apprendre plus à propos des guides Steam`,
  _ = `Parcourir par\xA0:`,
  _ = `Première page`,
  _ = `Créer un guide`,
  _ = `Si vous voulez créer un guide, vous devez d'abord acheter %1$s.`,
  _ = `Soyez la première personne à créer un guide pour ce jeu\xA0!`,
  _ = `Démontrez votre expertise ou aidez simplement d'autres joueuses et joueurs qui pourraient être bloqués.`,
  _ = `Créez une soluce, révélez des secrets ou proposez des tactiques optimales pour certaines cartes.`,
  _ = `Parcourez et évaluez les guides réalisés par la communauté pour ce jeu, ou créez le vôtre pour partager vos astuces.`,
  _ = `Créez le vôtre`,
  _ = `Captures d'écran`,
  _ = `Illustrations`,
  _ = `Vidéos`,
  _ = `Affichage de %1$s à %2$s sur %3$s`,
  _ = `Haut de la page`,
  _ = `Vue actuelle`,
  _ = `Mur d'images`,
  _ = `Grille`,
  _ = `Les plus populaires`,
  _ = `Les plus récents`,
  _ = `Les plus anciens`,
  _ = `Toutes vos captures d'écran`,
  _ = `Vos captures d'écran publiques`,
  _ = `Captures d'écran visibles uniquement par vos contacts`,
  _ = `Vos captures d'écran privées`,
  _ = `Vos captures d'écran non répertoriées`,
  _ = `Toutes vos créations`,
  _ = `Vos créations publiques`,
  _ = `Vos créations visibles uniquement par vos contacts`,
  _ = `Vos créations privées`,
  _ = `Vos créations non classées`,
  _ = `Toutes vos vidéos`,
  _ = `Vos vidéos publiques`,
  _ = `Vos vidéos visibles uniquement par vos contacts`,
  _ = `Vos vidéos privées`,
  _ = `Vos vidéos non répertoriées`,
  _ = `Gérer les captures d'écran`,
  _ = `Gérer les créations`,
  _ = `Gérer les vidéos`,
  _ = `Sélectionnez les captures d'écran sur lesquelles vous souhaitez agir.`,
  _ = `Sélectionnez ci-dessous les créations sur lesquelles vous souhaitez agir.`,
  _ = `Sélectionnez les vidéos sur lesquelles vous souhaitez agir.`,
  _ = `Annuler`,
  _ = `Ajouter des vidéos YouTube`,
  _ = `Associer un compte YouTube`,
  _ = `Retirer l'association avec le compte YouTube`,
  _ = `Retirer l'association`,
  _ = `Voulez-vous vraiment retirer l'association avec votre compte YouTube\xA0?`,
  _ = `Comment les données de mon compte\xA0YouTube sont-elles utilisées par Steam\xA0?`,
  _ = `L'association d'un compte YouTube à Steam utilise les services d'API\xA0YouTube. En utilisant YouTube et en associant votre compte YouTube à un profil Steam, vous acceptez les %1$s et les %2$s.`,
  _ = `Steam utilise les services\xA0d'API YouTube pour authentifier votre compte\xA0YouTube et accéder à la liste des vidéos que vous avez publiées sur YouTube. Lorsque vous associez votre compte\xA0YouTube à Steam, Steam installe un cookie dans votre navigateur ou dans le client\xA0Steam qui détient les jetons d'authentification de votre compte pour YouTube. Ce cookie expire au bout de 30\xA0jours. Ces données sont utilisées uniquement pour permettre à Steam de vous montrer la liste des vidéos publiées sur votre compte\xA0YouTube.`,
  _ = `Lorsque vous publiez une vidéo sur Steam depuis votre compte\xA0YouTube, Steam ne stocke que les informations nécessaires à l'affichage de la vidéo sur Steam, y compris l'identifiant de la vidéo et l'identifiant du compte\xA0YouTube auquel elle appartient. Ces données seront utilisées uniquement pour afficher la vidéo sur Steam et à des fins de modération du contenu sur Steam.`,
  _ = `Vous pouvez révoquer l'accès de Steam à vos %1$s sur la %2$s.`,
  _ = `Conditions d'utilisation de YouTube`,
  _ = `Règles de confidentialité Google`,
  _ = `Données autorisées`,
  _ = `page des paramètres de sécurité de Google`,
  _ = `Vos vidéos, maintenant sur Steam.`,
  _ = `Partagez vos meilleurs moments de jeu avec vos contacts. Publiez vos exploits, vos progrès, vos tutoriels et toutes les créations que vous inspirent vos jeux favoris.`,
  _ = `1. Associez votre compte YouTube™ à votre profil Steam.`,
  _ = `2. Sélectionnez les vidéos que vous souhaitez ajouter à votre profil.`,
  _ = `3. Partagez-les avec vos contacts Steam pour leur en mettre plein la vue.`,
  _ = `Accéder à vos vidéos YouTube`,
  _ = `Votre profil Steam est actuellement associé au compte YouTube %1$s.`,
  _ = `Pour l'associer à un autre compte, vous devez retirer l'association du compte actuel.`,
  _ = `Retirer l'association de ce compte`,
  _ = `Continuer avec ce compte`,
  _ = `Votre compte YouTube a été associé avec succès`,
  _ = `1\xA0vidéo a été ajoutée avec succès`,
  _ = `%1$s\xA0vidéos ont été ajoutées avec succès`,
  _ = `Aucune vidéo n'a été trouvée dans votre collection YouTube.`,
  _ = `Vous ne pouvez ajouter que les vidéos YouTube dont la visibilité est paramétrée sur publique, pour lesquelles l'intégration est autorisée, et qui sont visibles dans les résultats d'une recherche sur votre nom d'utilisateur. Si vous venez de paramétrer une vidéo sur "publique" afin d'associer votre compte, l'indexation de votre vidéo par YouTube peut prendre un moment.`,
  _ = `Le compte YouTube %1$s est actuellement lié à votre compte Steam.`,
  _ = `Cliquez ici pour changer de compte YouTube`,
  _ = `modifier le compte`,
  _ = `1. Sélectionnez la/les vidéo(s) à ajouter.`,
  _ = `1\xA0vidéo disponible pour le compte %1$s`,
  _ = `Affichage des %1$s\xA0vidéos les plus récentes disponibles pour le compte\xA0: %2$s`,
  _ = `2. Associez la/les vidéo(s) à un jeu.`,
  _ = `Dès que vous aurez choisi des vidéos à gauche. (Facultatif)`,
  _ = `-\xA0aucun/autre (précisez ci-dessous)\xA0-`,
  _ = `Autre/non listé`,
  _ = `3. Ajoutez-la/les à votre profil.`,
  _ = `Ajouter une vidéo`,
  _ = `Remarque\xA0: Afin de pouvoir ajouter des vidéos depuis votre compte YouTube, leur visibilité doit avoir été paramétrée sur Publique, et l'intégration doit être autorisée.Si vous venez d'ajouter une vidéo sur votre compte YouTube et ne la voyez pas dans la liste ci-contre, essayez de la rafraîchir en cliquant sur le bouton ci-dessous.`,
  _ = `Rafraichir la liste des vidéos YouTube`,
  _ = `4. Finissez.`,
  _ = `Lorsque vous avez fini, cliquez sur Terminé pour voir les vidéos sur votre page de profil.`,
  _ = `Terminer`,
  _ = `Un problème est survenu lors de l'accès à votre flux de vidéos. Veuillez réessayer.`,
  _ = `Mettre en ligne une création`,
  _ = `Mettre en ligne des captures d'écran…`,
  _ = `Visibilité\xA0: publique`,
  _ = `Visibilité\xA0: contacts uniquement`,
  _ = `Visibilité\xA0: privée`,
  _ = `Ne pas répertorier`,
  _ = `Supprimer`,
  _ = `Tout sélectionner`,
  _ = `Terminé`,
  _ = `Supprimer ces captures\xA0?`,
  _ = `Modifier la visibilité`,
  _ = `Cette opération va supprimer %1$s du Steam Cloud. Voulez-vous continuer\xA0?`,
  _ = `Cela modifiera la visibilité de %1$s en %2$s. Voulez-vous vraiment continuer\xA0?`,
  _ = `Continuer`,
  _ = `Annuler`,
  _ = `Oups\xA0!`,
  _ = `Aucune capture sélectionnée.`,
  _ = `Sélectionnez les éléments à supprimer en cochant la case au coin de chaque miniature.`,
  _ = `OK`,
  _ = `La mise à jour de la visibilité a échoué`,
  _ = `Une ou plusieurs captures d'écran que vous avez essayé de mettre en visibilité Publique ou Contacts seulement n'ont pas pu être mises à jour. Les captures d'écran des jeux non disponibles pour tous sur la communauté Steam ne peuvent pas être partagées et ne sont donc visibles que par vous.`,
  _ = `Contenu potentiellement divulgâcheur.`,
  _ = `Survolez l'image pour la révéler.`,
  _ = `Aucune capture d'écran correspondante n'a été trouvée.`,
  _ = `%1$s n'a aucune capture d'écran que vous puissiez voir.`,
  _ = `Vous n'avez mis aucune capture d'écran en favori.`,
  _ = `%1$s n'a aucune capture d'écran mise dans ses favoris que vous puissiez voir.`,
  _ = `Vous n'avez actuellement aucune création dans Steam Cloud. Pour ajouter une création, vous devez vous rendre sur l'onglet «\xA0Créations de fans\xA0» du hub d'un produit et cliquer sur le bouton «\xA0Mettre en ligne une création\xA0» dans le coin supérieur droit de la page. Ou cliquez sur le bouton «\xA0Mettre en ligne une création\xA0» ci-dessous.`,
  _ = `%1$s n'a aucune création que vous puissiez voir.`,
  _ = `Vous n'avez aucune création dans vos favoris.`,
  _ = `%1$s n'a aucune création dans ses favoris que vous puissiez voir.`,
  _ = `Aucune vidéo correspondante n'a été trouvée.`,
  _ = `%1$s n'a aucune vidéo que vous puissiez regarder.`,
  _ = `Vous n'avez mis aucune vidéo en favori.`,
  _ = `%1$s n'a aucune vidéo mise dans ses favoris que vous puissiez regarder.`,
  _ = `Ce critère de visibilité ne concerne aucune de vos captures d'écran.`,
  _ = `Steam a simplifié la prise et le partage de captures d'écran de vos jeux favoris.`,
  _ = `Appuyez sur votre touche de raccourci (F12 par défaut) lorsque vous êtes dans un jeu utilisant l'overlay Steam pour prendre des captures d'écran. Publiez-les ensuite sur votre profil de la communauté Steam ainsi que sur Facebook, Twitter ou Reddit afin de les partager avec vos contacts.`,
  _ = `Avec 1\xA0Go d'espace disponible sur Steam Cloud, vous pouvez transférer des milliers de captures d'écran afin de montrer vos meilleurs moments à vos contacts. Vous pouvez aussi les rendre privées si vous préférez plutôt les garder pour vous.`,
  _ = `Par\xA0%1$s`,
  _ = `Favoris de %1$s`,
  _ = {
    Moderation_SubjectTypeName_ForumPost: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    moderation_claim_report_count: _,
    moderation_claim_report_count_Plural: _,
    moderation_claim_subject_count: _,
    moderation_claim_subject_count_Plural: _,
    moderation_claim_n_reports_on_m_subjects: _,
    moderation_forumpost_summary: _,
    moderation_forumpost_summary_reports_fragment: _,
    moderation_forumpost_summary_reports_fragment_Plural: _,
    moderation_forumpost_summary_subjects_fragment: _,
    moderation_forumpost_summary_subjects_fragment_Plural: _,
    community_title: _,
    community_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    profile_games_list: _,
    profile_games_list_title: _,
    Market_Search_Title: _,
    Market_Item_Title: _,
    Market_Item_GenericTitle: _,
    Market_GenericTitle: _,
    profile_error_profilenotfound: _,
    profile_games_list_error_loadfailed: _,
    Error_RateLimited: _,
    Loading: _,
    GamesList_Header_Downloading: _,
    GamesList_Header_Paused: _,
    GamesList_Header_DownloadBytes: _,
    GamesList_Header_Achievements: _,
    GamesList_TimeRemaining: _,
    GamesList_Achievement_Fraction: _,
    GamesList_Uninstalling: _,
    GamesList_Button_UpdateRequired: _,
    GamesList_Button_Uninstall: _,
    GamesList_Button_Download: _,
    GamesList_Button_Pause: _,
    GamesList_Button_Resume: _,
    GamesList_Button_Uninstalling: _,
    GamesList_Button_Cancel: _,
    GamesList_PrivacySettings_Tooltip: _,
    GamesList_Filter_Placeholder: _,
    GamesList_Filter_BothOwned: _,
    GamesList_Sort_HoursPlayed: _,
    GamesList_Sort_Name: `Nom`,
    GamesList_Sort_AchievementCompletion: _,
    GamesList_Header_TotalPlayed: _,
    GamesList_Header_LastPlayed: _,
    GamesList_Header_TwoWeeks: _,
    GamesList_MenuLabel_GameInfo: _,
    GamesList_MenuLabel_RemoteDownload: _,
    GamesList_Header_RemoteDownload: _,
    GamesList_Header_RemoteDownloadStatus: _,
    GamesList_RemoteDownload_NoConnection: _,
    GamesList_RemoteDownload_Help: _,
    GamesList_RemoteDownload_ReadTheFAQ: _,
    GamesList_RemoteDownload_Info: _,
    GamesList_RemoteDownload_LearnMore: _,
    GamesList_RemoteDownload_NoRemoteControl: _,
    GamesList_RemoteDownload_UninstallConfirm: _,
    GamesList_Client_Indicator: _,
    GamesList_Tab_RecentlyPlayed: _,
    GamesList_Tab_AllGames: _,
    GamesList_Tab_PerfectGames: _,
    GamesList_Tab_Reviews: _,
    GamesList_Tab_Followed: _,
    GamesList_Tab_Wishlist: _,
    Perfect_Game_Description: _,
    GamesList_PerfectGames_Description: _,
    GamesList_Achievement_Unlock_Percentage: _,
    Community_StorePage: _,
    Community_Forums: _,
    Community_Groups: _,
    Community_OfficialWebsite: _,
    Community_News: _,
    Community_UsersAchievementsFirstPerson: _,
    Community_UsersAchievements: _,
    Community_UsersStats: _,
    Community_GamePersonalData: _,
    Community_UsersLeaderboardsFirstPerson: _,
    Community_UsersLeaderboards: _,
    Community_GlobalAchievements: _,
    Community_GlobalLeaderboards: _,
    Community_GameStats: _,
    Community_GameContent: _,
    Community_GameStatsFirstPerson: _,
    Community_GameContentFirstPerson: _,
    Community_GameLinks: _,
    Community_ScreenshotsMenuItemFirstPerson: _,
    Community_ScreenshotsMenuItemThirdPerson: _,
    Community_FriendsWhoPlayMenuItemFirstPerson: _,
    Community_TradingCardsMenuItemFirstPerson: _,
    Community_ReviewMenuItemFirstPerson: _,
    Community_ReviewMenuItemThirdPerson: _,
    Community_GameHubMenuItem: _,
    Community_GameNotesFirstPerson: _,
    Playtime_Hours: _,
    Playtime_Minutes: _,
    AppPrivacy_MarkAsPrivate: _,
    AppPrivacy_UnmarkAsPrivate: _,
    AppPrivacy_Explanation: _,
    footer_legal_notice: _,
    footer_geodata_notice: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_accessibility: _,
    profiletabs_currentbans: _,
    profiletabs_communitymessages: _,
    profiletabs_reportedcontent: _,
    profiletabs_moderatedcontent: _,
    reportedcontent_description: _,
    moderatedcontent_description: _,
    reportedcontent_lastupdated: _,
    SharedFiles_ItemDownload: _,
    SharedFiles_PublicComments: _,
    SharedFiles_DeveloperComments: _,
    Workshop_DeveloperThreadDesc: _,
    Workshop_DeveloperThreadDisclaimerText: _,
    Workshop_ImageSize: _,
    SharedFiles_Media_ViewAppScreenshots: _,
    SharedFiles_Media_ViewAppFanArt: _,
    SharedFiles_Media_ViewAppVideos: _,
    SharedFiles_ItemEditText_Text_Caption: _,
    SharedFiles_OwnerControl_EditCaption: _,
    SharedFiles_AddSpoilerTag: _,
    SharedFiles_RemoveSpoilerTag: _,
    SharedFiles_SpoilerTagInstructions: _,
    SharedFiles_SpoilerTagsExpire: _,
    SharedFiles_Stats_TaggedUsers: _,
    SharedFiles_Stats_TaggedWorkshopItems: _,
    SharedFiles_RemoveSelfTag_Tooltip: _,
    Screenshots_Location: _,
    SharedFiles_Tags: _,
    SharedFiles_WaitingForIntegratedGuide: _,
    Workshop_Subscribe_IntegratedGuide: _,
    SharedFiles_Guide_Index: _,
    SharedFiles_Guide_Overview: _,
    SharedFiles_Guide_Comments: _,
    SharedFiles_Item_Edit_Link: _,
    Community_RemoveLink_BeWary: _,
    Community_RemoveLink_Tooltip: _,
    SharedFiles_ManageGuide_Contents: _,
    SharedFiles_ManageGuide_Contents_Desc: _,
    SharedFiles_ManageGuide_Required: _,
    SharedFiles_ManageGuide_NoSubSections: _,
    SharedFiles_ManageGuide_AddSection: _,
    SharedFiles_ManageGuide_NoSectionTitle: _,
    SharedFiles_ManageGuide_EditThisSection: _,
    SharedFiles_ManageGuide_DeleteThisSection: _,
    SharedFiles_ManageGuide_RemoveSectionConfirm: _,
    SharedFiles_ManageGuide_Images: _,
    SharedFiles_ManageGuide_Images_Desc: _,
    SharedFiles_ManageGuide_NoPreviewImages: _,
    SharedFiles_ManageGuide_Contributors: _,
    SharedFiles_ManageGuide_Contributors_Desc: _,
    SharedFiles_ManageGuide_NoContributors: _,
    SharedFiles_ManageGuide_AddContributor: _,
    SharedFiles_ManageGuide_Preview: _,
    SharedFiles_ManageGuide_EditSubSection: _,
    SharedFiles_ManageGuide_SubSectionTitle: _,
    SharedFiles_ManageGuide_SubSectionContents: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Edit: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Preview: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Changes: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Desc: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Insert: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Delete: _,
    SharedFiles_ManageGuide_SubSectionContentChanged: _,
    SharedFiles_ManageGuide_SubSectionContentChanged_CancelConfirm: _,
    SharedFiles_ManageGuide_SubSectionContentSaved: _,
    SharedFiles_ManageGuide_Save: _,
    SharedFiles_ManageGuide_Cancel: _,
    SharedFiles_ManageGuide_Screenshots: _,
    SharedFiles_ManageGuide_Videos: _,
    SharedFiles_ManageGuide_SubImages: _,
    SharedFiles_ManageGuide_SubScreenshots: _,
    SharedFiles_ManageGuide_SubVideos: _,
    SharedFiles_ManageGuide_ImageInsertionOptions: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_Size: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeThumb: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeFull: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeOriginal: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_Layout: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutLeft: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutRight: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutInline: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Left: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Right: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Full: _,
    SharedFiles_ManageGuide_InsertImage: _,
    SharedFiles_ManageGuide_InsertYouTubeVideo: _,
    SharedFiles_ManageGuide_PromptYouTubeUrl: _,
    Discussions_FormattingHelp_Quote: _,
    Discussions_FormattingHelp_Spoiler: _,
    SharedFiles_ItemEditText_ErrorNoTitle: _,
    SharedFiles_OwnerControl_BackGuide: _,
    empty_no_comma_following: ``,
    SharedFiles_WorkshopItemsTagged: _,
    SharedFiles_And_N_More: _,
    Workshop_ItemModalViewDetails: _,
    Workshop_ItemModalViewCountDetails: _,
    Profile_Screenshots: _,
    Profile_Images: _,
    Profile_Videos: _,
    Profile_Workshop_Items: _,
    SharedFiles_Tab_Merchandise: _,
    Profile_Collections: _,
    Profile_Guides: _,
    SharedFiles_SharedFiles_Items: _,
    SharedFiles_SharedFiles_Collections: _,
    SharedFiles_SharedFiles_Guides: _,
    SharedFiles_Favorites: _,
    SharedFiles_Subscriptions: _,
    SharedFiles_Browse_MyFiles_Played: _,
    SharedFiles_FilterByGame: _,
    Profile_SharedFiles_AllGames: _,
    Profile_SharedFiles_SelectAGame: _,
    SharedFiles_Browse_MyFiles_Items: _,
    SharedFiles_Browse_MyFiles_Favorites: _,
    SharedFiles_Browse_MyFiles_Subscriptions: _,
    SharedFiles_Browse_MyFiles_Sort_CreationOrder: _,
    SharedFiles_Browse_MyFiles_Sort_Alpha: _,
    SharedFiles_Browse_MyFiles_Sort_LastUpdated: _,
    SharedFiles_Browse_MyFiles_Sort_Subscribed: _,
    SharedFiles_Browse_MyFiles_Sort_Favorited: _,
    SharedFiles_TagsSearch: _,
    SharedFiles_ByAuthor: `par`,
    Workshop_BrowsePaging: _,
    Workshop_NoItems: _,
    SharedFiles_UserList_BrowsePaging: _,
    SharedFiles_UserList_LastUpdated: _,
    SharedFiles_Favorites_Subscribed: _,
    SharedFiles_Favorites_NowUnsubscribed: _,
    SharedFiles_Subscription_Subscribed: _,
    SharedFiles_Subscription_NowUnsubscribed: _,
    Workshop_HasLinkedItems: _,
    Workshop_PaymentInfo_NotCreated: _,
    Workshop_PaymentInfo_Rejected: _,
    Workshop_SplitsAcceptTheseDesc1: _,
    Workshop_SplitsAcceptTheseDesc2: _,
    Workshop_SplitsPercentage: _,
    Profile_YourWorkshop: _,
    CommunityFollower_Description: _,
    CommunityFollower_Description_Yours: _,
    CommunityFollower_One_Follower: _,
    CommunityFollower_NumFollowers: _,
    CommunityFollower_FollowUser: _,
    CommunityFollower_FollowingUser: _,
    CommunityFollower_UnfollowUser: _,
    Workshop_ViewYourRevenue: _,
    Workshop_ViewYourRevenue_desc: _,
    Workshop_Link_PaymentInfo: _,
    Workshop_Link_LegalAgreement: _,
    SharedFiles_UnsubscribeAll_Btn: _,
    SharedFiles_UnsubscribeAll_Confirm_Title: _,
    SharedFiles_UnsubscribeAll_Confirm_Desc: _,
    SharedFiles_UnsubscribeAll_Confirm_App_Desc: _,
    SharedFiles_SaveSubscribedToCollection_Btn: _,
    SharedFiles_SaveSubscribedToCollection_Title: _,
    SharedFiles_SaveSubscribedToCollection_Desc: _,
    SharedFiles_SaveSubscribedToCollection_New: _,
    SharedFiles_SaveSubscribedToCollection_NewDesc: _,
    SharedFiles_SaveSubscribedToCollection_Existing: _,
    SharedFiles_SaveSubscribedToCollection_ExistingDesc: _,
    SharedFiles_SaveSubscribedToCollection_NoExistingCollections: _,
    SharedFiles_AdminTags: _,
    SharedFiles_SearchedForFileType_WebGuide: _,
    SharedFiles_SearchedForFileType_IntegratedGuide: _,
    SharedFiles_Dota2_IntegratedGuide: _,
    SharedFiles_Dota2_IntegratedGuide_Desc: _,
    AppHub_Guides_IntegratedGuides_Desc: _,
    AppHub_Guides_PopularCategories: _,
    AppHub_Guides_IntegratedGuides: _,
    AppHub_Guides_YourFavorites: _,
    AppHub_Guides_MostPopularThisWeek: _,
    AppHub_Guides_MostPopularThisWeek_Desc: _,
    AppHub_Guides_ViewAll: _,
    AppHub_Guides_NumGuides_Singular: _,
    AppHub_Guides_NumGuides_Plural: _,
    AppHub_Guides_GuidesYouHaveMade: _,
    AppHub_Guides_MoreInfo_Title: _,
    AppHub_Guides_MoreInfo_button: _,
    Workshop_BrowseBy: _,
    SharedFiles_Browse_GuideHome: _,
    SharedFiles_CreateGuide: _,
    SharedFiles_MustOwnAppToCreateGuide: _,
    SharedFiles_NoGuides_Title: _,
    SharedFiles_NoGuides_Desc1: _,
    SharedFiles_NoGuides_Desc2: _,
    SharedFiles_BrowseGuide_subtitle_nolink: _,
    SharedFiles_BrowseGuide_createNewBtnLabel: _,
    Community_Screenshots: _,
    Community_Images: _,
    Community_Videos: _,
    Paging_ShowingXtoYofZ: _,
    AppHubHome_BackToTop: _,
    Screenshots_Viewing: _,
    Profile_SharedFiles_ImageWallView: _,
    Profile_SharedFiles_GridView: _,
    Profile_SharedFiles_MostPopular: _,
    Profile_SharedFiles_NewestFirst: _,
    Profile_SharedFiles_OldestFirst: _,
    Screenshots_AllYourScreenshots: _,
    Screenshots_YourPublicScreenshots: _,
    Screenshots_YourFriendsOnlyScreenshots: _,
    Screenshots_YourPrivateScreenshots: _,
    Screenshots_YourUnlistedScreenshots: _,
    Images_AllYourImages: _,
    Images_YourPublicImages: _,
    Images_YourFriendsOnlyImages: _,
    Images_YourPrivateImages: _,
    Images_YourUnlistedImages: _,
    Videos_AllYourVideos: _,
    Videos_YourPublicVideos: _,
    Videos_YourFriendsOnlyVideos: _,
    Videos_YourPrivateVideos: _,
    Videos_YourUnlistedVideos: _,
    Screenshots_Manage: _,
    Images_Manage: _,
    Videos_Manage: _,
    Screenshots_SelectScreenshots: _,
    Images_SelectImages: _,
    Videos_SelectVideos: _,
    Videos_Cancel: _,
    Videos_AddFromYouTube: _,
    Videos_LinkYouTubeAcct: _,
    Videos_UnlinkYouTubeAcct: _,
    Videos_UnlinkButton: _,
    Videos_UnlinkConfirmText: _,
    Videos_Privacy: _,
    Videos_YoutubeTerms_1: _,
    Videos_YoutubeTerms_2: _,
    Videos_YoutubeTerms_3: _,
    Videos_YoutubeTerms_4: _,
    Videos_YoutubeTermsLink_TermsOfService: _,
    Videos_YoutubeTermsLink_PrivacyPolicy: _,
    Videos_YoutubeTermsLink_AuthorizedData: _,
    Videos_YoutubeTermsLink_SecuritySettings: _,
    Videos_NowOnSteam: _,
    Videos_ShareDescription: _,
    Videos_Desc1: _,
    Videos_Desc2: _,
    Videos_Desc3: _,
    Videos_AccessYourYouTubeVideos: _,
    Videos_CurrentlyLinkedTo: _,
    Videos_UnlinkToAddAnother: _,
    Videos_UnlinkAcct: _,
    Videos_ContinueWithAcct: _,
    Videos_SuccessfullyLinkedYouTube: _,
    Videos_SuccessfullyAddedSingular: _,
    Videos_SuccessfullyAddedPlural: _,
    Videos_NoVideosMsg1: _,
    Videos_NoVideosMsg2: _,
    Videos_CurrentlyLinkedMsg: _,
    Videos_ClickHereToChange: _,
    Videos_ChangeAccount: _,
    Videos_AddStep1: _,
    Videos_AvailCountSingular: _,
    Videos_AvailCountPlural: _,
    Videos_AddStep2: _,
    Videos_AddStep2Note: _,
    Videos_OptionNoneOther: _,
    Videos_OtherUnlisted: _,
    Videos_AddStep3: _,
    Videos_AddVideo: _,
    Videos_AddNote2: _,
    Videos_Refresh: _,
    Videos_AddStep4: _,
    Videos_AddNote4: _,
    Videos_AddDone: _,
    Videos_IssuesAccessing: _,
    Images_Upload: _,
    Screenshots_Upload: _,
    Screenshots_MakePublic: _,
    Screenshots_MakeFriendsOnly: _,
    Screenshots_MakePrivate: _,
    Screenshots_MakeUnlisted: _,
    Screenshots_Delete: _,
    Screenshots_SelectAll: _,
    Screenshots_Done: _,
    Screenshots_DeleteScreenshots: _,
    Screenshots_UpdatePrivacy: _,
    Screenshots_AreYouSureDelete: _,
    Screenshots_AreYouSurePrivacyChange: _,
    Screenshots_Continue: _,
    Screenshots_Cancel: _,
    Screenshots_Oops: _,
    Screenshots_NoneSelected: _,
    Screenshots_SelectScreenshotsToDelete: _,
    Screenshots_OK: `OK`,
    Screenshots_VisUpdateFailed: _,
    Screenshots_VisUpdateFailedMessage: _,
    Blotter_PotentialSpoilers: _,
    Blotter_RevealImage: _,
    Profile_SharedFiles_NoScreenshotsSelf: _,
    Profile_SharedFiles_NoScreenshotsForYou: _,
    Profile_SharedFiles_NoScreenshotsFavoritesSelf: _,
    Profile_SharedFiles_NoScreenshotsFavoritesForYou: _,
    Profile_SharedFiles_NoImagesSelf: _,
    Profile_SharedFiles_NoImagesForYou: _,
    Profile_SharedFiles_NoImagesFavoritesSelf: _,
    Profile_SharedFiles_NoImagesFavoritesForYou: _,
    Profile_SharedFiles_NoVideosSelf: _,
    Profile_SharedFiles_NoVideosForYou: _,
    Profile_SharedFiles_NoVideosFavoritesSelf: _,
    Profile_SharedFiles_NoVideosFavoritesForYou: _,
    Profile_SharedFiles_NoScreenshotsThisVisibility: _,
    Screenshots_SteamHasThem: _,
    Screenshots_Instructions1: _,
    Screenshots_Instructions2: _,
    Profile_SharedFiles_By: _,
    Profile_SharedFiles_FavoritedBy: _,
  };
export {
  _ as AppHubHome_BackToTop,
  _ as AppHub_Guides_GuidesYouHaveMade,
  _ as AppHub_Guides_IntegratedGuides,
  _ as AppHub_Guides_IntegratedGuides_Desc,
  _ as AppHub_Guides_MoreInfo_Title,
  _ as AppHub_Guides_MoreInfo_button,
  _ as AppHub_Guides_MostPopularThisWeek,
  _ as AppHub_Guides_MostPopularThisWeek_Desc,
  _ as AppHub_Guides_NumGuides_Plural,
  _ as AppHub_Guides_NumGuides_Singular,
  _ as AppHub_Guides_PopularCategories,
  _ as AppHub_Guides_ViewAll,
  _ as AppHub_Guides_YourFavorites,
  _ as AppPrivacy_Explanation,
  _ as AppPrivacy_MarkAsPrivate,
  _ as AppPrivacy_UnmarkAsPrivate,
  _ as Blotter_PotentialSpoilers,
  _ as Blotter_RevealImage,
  _ as CommunityFollower_Description,
  _ as CommunityFollower_Description_Yours,
  _ as CommunityFollower_FollowUser,
  _ as CommunityFollower_FollowingUser,
  _ as CommunityFollower_NumFollowers,
  _ as CommunityFollower_One_Follower,
  _ as CommunityFollower_UnfollowUser,
  _ as Community_Forums,
  _ as Community_FriendsWhoPlayMenuItemFirstPerson,
  _ as Community_GameContent,
  _ as Community_GameContentFirstPerson,
  _ as Community_GameHubMenuItem,
  _ as Community_GameLinks,
  _ as Community_GameNotesFirstPerson,
  _ as Community_GamePersonalData,
  _ as Community_GameStats,
  _ as Community_GameStatsFirstPerson,
  _ as Community_GlobalAchievements,
  _ as Community_GlobalLeaderboards,
  _ as Community_Groups,
  _ as Community_Images,
  _ as Community_News,
  _ as Community_OfficialWebsite,
  _ as Community_RemoveLink_BeWary,
  _ as Community_RemoveLink_Tooltip,
  _ as Community_ReviewMenuItemFirstPerson,
  _ as Community_ReviewMenuItemThirdPerson,
  _ as Community_Screenshots,
  _ as Community_ScreenshotsMenuItemFirstPerson,
  _ as Community_ScreenshotsMenuItemThirdPerson,
  _ as Community_StorePage,
  _ as Community_TradingCardsMenuItemFirstPerson,
  _ as Community_UsersAchievements,
  _ as Community_UsersAchievementsFirstPerson,
  _ as Community_UsersLeaderboards,
  _ as Community_UsersLeaderboardsFirstPerson,
  _ as Community_UsersStats,
  _ as Community_Videos,
  _ as Discussions_FormattingHelp_Quote,
  _ as Discussions_FormattingHelp_Spoiler,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as GamesList_Achievement_Fraction,
  _ as GamesList_Achievement_Unlock_Percentage,
  _ as GamesList_Button_Cancel,
  _ as GamesList_Button_Download,
  _ as GamesList_Button_Pause,
  _ as GamesList_Button_Resume,
  _ as GamesList_Button_Uninstall,
  _ as GamesList_Button_Uninstalling,
  _ as GamesList_Button_UpdateRequired,
  _ as GamesList_Client_Indicator,
  _ as GamesList_Filter_BothOwned,
  _ as GamesList_Filter_Placeholder,
  _ as GamesList_Header_Achievements,
  _ as GamesList_Header_DownloadBytes,
  _ as GamesList_Header_Downloading,
  _ as GamesList_Header_LastPlayed,
  _ as GamesList_Header_Paused,
  _ as GamesList_Header_RemoteDownload,
  _ as GamesList_Header_RemoteDownloadStatus,
  _ as GamesList_Header_TotalPlayed,
  _ as GamesList_Header_TwoWeeks,
  _ as GamesList_MenuLabel_GameInfo,
  _ as GamesList_MenuLabel_RemoteDownload,
  _ as GamesList_PerfectGames_Description,
  _ as GamesList_PrivacySettings_Tooltip,
  _ as GamesList_RemoteDownload_Help,
  _ as GamesList_RemoteDownload_Info,
  _ as GamesList_RemoteDownload_LearnMore,
  _ as GamesList_RemoteDownload_NoConnection,
  _ as GamesList_RemoteDownload_NoRemoteControl,
  _ as GamesList_RemoteDownload_ReadTheFAQ,
  _ as GamesList_RemoteDownload_UninstallConfirm,
  _ as GamesList_Sort_AchievementCompletion,
  _ as GamesList_Sort_HoursPlayed,
  _ as GamesList_Sort_Name,
  _ as GamesList_Tab_AllGames,
  _ as GamesList_Tab_Followed,
  _ as GamesList_Tab_PerfectGames,
  _ as GamesList_Tab_RecentlyPlayed,
  _ as GamesList_Tab_Reviews,
  _ as GamesList_Tab_Wishlist,
  _ as GamesList_TimeRemaining,
  _ as GamesList_Uninstalling,
  _ as Images_AllYourImages,
  _ as Images_Manage,
  _ as Images_SelectImages,
  _ as Images_Upload,
  _ as Images_YourFriendsOnlyImages,
  _ as Images_YourPrivateImages,
  _ as Images_YourPublicImages,
  _ as Images_YourUnlistedImages,
  _ as Loading,
  _ as Market_GenericTitle,
  _ as Market_Item_GenericTitle,
  _ as Market_Item_Title,
  _ as Market_Search_Title,
  _ as Moderation_SubjectTypeName_ForumPost,
  _ as Paging_ShowingXtoYofZ,
  _ as Perfect_Game_Description,
  _ as Playtime_Hours,
  _ as Playtime_Minutes,
  _ as Profile_Collections,
  _ as Profile_Guides,
  _ as Profile_Images,
  _ as Profile_Screenshots,
  _ as Profile_SharedFiles_AllGames,
  _ as Profile_SharedFiles_By,
  _ as Profile_SharedFiles_FavoritedBy,
  _ as Profile_SharedFiles_GridView,
  _ as Profile_SharedFiles_ImageWallView,
  _ as Profile_SharedFiles_MostPopular,
  _ as Profile_SharedFiles_NewestFirst,
  _ as Profile_SharedFiles_NoImagesFavoritesForYou,
  _ as Profile_SharedFiles_NoImagesFavoritesSelf,
  _ as Profile_SharedFiles_NoImagesForYou,
  _ as Profile_SharedFiles_NoImagesSelf,
  _ as Profile_SharedFiles_NoScreenshotsFavoritesForYou,
  _ as Profile_SharedFiles_NoScreenshotsFavoritesSelf,
  _ as Profile_SharedFiles_NoScreenshotsForYou,
  _ as Profile_SharedFiles_NoScreenshotsSelf,
  _ as Profile_SharedFiles_NoScreenshotsThisVisibility,
  _ as Profile_SharedFiles_NoVideosFavoritesForYou,
  _ as Profile_SharedFiles_NoVideosFavoritesSelf,
  _ as Profile_SharedFiles_NoVideosForYou,
  _ as Profile_SharedFiles_NoVideosSelf,
  _ as Profile_SharedFiles_OldestFirst,
  _ as Profile_SharedFiles_SelectAGame,
  _ as Profile_Videos,
  _ as Profile_Workshop_Items,
  _ as Profile_YourWorkshop,
  _ as Screenshots_AllYourScreenshots,
  _ as Screenshots_AreYouSureDelete,
  _ as Screenshots_AreYouSurePrivacyChange,
  _ as Screenshots_Cancel,
  _ as Screenshots_Continue,
  _ as Screenshots_Delete,
  _ as Screenshots_DeleteScreenshots,
  _ as Screenshots_Done,
  _ as Screenshots_Instructions1,
  _ as Screenshots_Instructions2,
  _ as Screenshots_Location,
  _ as Screenshots_MakeFriendsOnly,
  _ as Screenshots_MakePrivate,
  _ as Screenshots_MakePublic,
  _ as Screenshots_MakeUnlisted,
  _ as Screenshots_Manage,
  _ as Screenshots_NoneSelected,
  _ as Screenshots_OK,
  _ as Screenshots_Oops,
  _ as Screenshots_SelectAll,
  _ as Screenshots_SelectScreenshots,
  _ as Screenshots_SelectScreenshotsToDelete,
  _ as Screenshots_SteamHasThem,
  _ as Screenshots_UpdatePrivacy,
  _ as Screenshots_Upload,
  _ as Screenshots_Viewing,
  _ as Screenshots_VisUpdateFailed,
  _ as Screenshots_VisUpdateFailedMessage,
  _ as Screenshots_YourFriendsOnlyScreenshots,
  _ as Screenshots_YourPrivateScreenshots,
  _ as Screenshots_YourPublicScreenshots,
  _ as Screenshots_YourUnlistedScreenshots,
  _ as SharedFiles_AddSpoilerTag,
  _ as SharedFiles_AdminTags,
  _ as SharedFiles_And_N_More,
  _ as SharedFiles_BrowseGuide_createNewBtnLabel,
  _ as SharedFiles_BrowseGuide_subtitle_nolink,
  _ as SharedFiles_Browse_GuideHome,
  _ as SharedFiles_Browse_MyFiles_Favorites,
  _ as SharedFiles_Browse_MyFiles_Items,
  _ as SharedFiles_Browse_MyFiles_Played,
  _ as SharedFiles_Browse_MyFiles_Sort_Alpha,
  _ as SharedFiles_Browse_MyFiles_Sort_CreationOrder,
  _ as SharedFiles_Browse_MyFiles_Sort_Favorited,
  _ as SharedFiles_Browse_MyFiles_Sort_LastUpdated,
  _ as SharedFiles_Browse_MyFiles_Sort_Subscribed,
  _ as SharedFiles_Browse_MyFiles_Subscriptions,
  _ as SharedFiles_ByAuthor,
  _ as SharedFiles_CreateGuide,
  _ as SharedFiles_DeveloperComments,
  _ as SharedFiles_Dota2_IntegratedGuide,
  _ as SharedFiles_Dota2_IntegratedGuide_Desc,
  _ as SharedFiles_Favorites,
  _ as SharedFiles_Favorites_NowUnsubscribed,
  _ as SharedFiles_Favorites_Subscribed,
  _ as SharedFiles_FilterByGame,
  _ as SharedFiles_Guide_Comments,
  _ as SharedFiles_Guide_Index,
  _ as SharedFiles_Guide_Overview,
  _ as SharedFiles_ItemDownload,
  _ as SharedFiles_ItemEditText_ErrorNoTitle,
  _ as SharedFiles_ItemEditText_Text_Caption,
  _ as SharedFiles_Item_Edit_Link,
  _ as SharedFiles_ManageGuide_AddContributor,
  _ as SharedFiles_ManageGuide_AddSection,
  _ as SharedFiles_ManageGuide_Cancel,
  _ as SharedFiles_ManageGuide_Contents,
  _ as SharedFiles_ManageGuide_Contents_Desc,
  _ as SharedFiles_ManageGuide_Contributors,
  _ as SharedFiles_ManageGuide_Contributors_Desc,
  _ as SharedFiles_ManageGuide_DeleteThisSection,
  _ as SharedFiles_ManageGuide_EditSubSection,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Delete,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Desc,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Insert,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Changes,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Edit,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Preview,
  _ as SharedFiles_ManageGuide_EditThisSection,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_Layout,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutInline,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutLeft,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutRight,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_Size,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeFull,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeOriginal,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeThumb,
  _ as SharedFiles_ManageGuide_Images,
  _ as SharedFiles_ManageGuide_Images_Desc,
  _ as SharedFiles_ManageGuide_InsertImage,
  _ as SharedFiles_ManageGuide_InsertYouTubeVideo,
  _ as SharedFiles_ManageGuide_NoContributors,
  _ as SharedFiles_ManageGuide_NoPreviewImages,
  _ as SharedFiles_ManageGuide_NoSectionTitle,
  _ as SharedFiles_ManageGuide_NoSubSections,
  _ as SharedFiles_ManageGuide_Preview,
  _ as SharedFiles_ManageGuide_PromptYouTubeUrl,
  _ as SharedFiles_ManageGuide_RemoveSectionConfirm,
  _ as SharedFiles_ManageGuide_Required,
  _ as SharedFiles_ManageGuide_Save,
  _ as SharedFiles_ManageGuide_Screenshots,
  _ as SharedFiles_ManageGuide_SubImages,
  _ as SharedFiles_ManageGuide_SubScreenshots,
  _ as SharedFiles_ManageGuide_SubSectionContentChanged,
  _ as SharedFiles_ManageGuide_SubSectionContentChanged_CancelConfirm,
  _ as SharedFiles_ManageGuide_SubSectionContentSaved,
  _ as SharedFiles_ManageGuide_SubSectionContents,
  _ as SharedFiles_ManageGuide_SubSectionTitle,
  _ as SharedFiles_ManageGuide_SubVideos,
  _ as SharedFiles_ManageGuide_Videos,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Full,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Left,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Right,
  _ as SharedFiles_Media_ViewAppFanArt,
  _ as SharedFiles_Media_ViewAppScreenshots,
  _ as SharedFiles_Media_ViewAppVideos,
  _ as SharedFiles_MustOwnAppToCreateGuide,
  _ as SharedFiles_NoGuides_Desc1,
  _ as SharedFiles_NoGuides_Desc2,
  _ as SharedFiles_NoGuides_Title,
  _ as SharedFiles_OwnerControl_BackGuide,
  _ as SharedFiles_OwnerControl_EditCaption,
  _ as SharedFiles_PublicComments,
  _ as SharedFiles_RemoveSelfTag_Tooltip,
  _ as SharedFiles_RemoveSpoilerTag,
  _ as SharedFiles_SaveSubscribedToCollection_Btn,
  _ as SharedFiles_SaveSubscribedToCollection_Desc,
  _ as SharedFiles_SaveSubscribedToCollection_Existing,
  _ as SharedFiles_SaveSubscribedToCollection_ExistingDesc,
  _ as SharedFiles_SaveSubscribedToCollection_New,
  _ as SharedFiles_SaveSubscribedToCollection_NewDesc,
  _ as SharedFiles_SaveSubscribedToCollection_NoExistingCollections,
  _ as SharedFiles_SaveSubscribedToCollection_Title,
  _ as SharedFiles_SearchedForFileType_IntegratedGuide,
  _ as SharedFiles_SearchedForFileType_WebGuide,
  _ as SharedFiles_SharedFiles_Collections,
  _ as SharedFiles_SharedFiles_Guides,
  _ as SharedFiles_SharedFiles_Items,
  _ as SharedFiles_SpoilerTagInstructions,
  _ as SharedFiles_SpoilerTagsExpire,
  _ as SharedFiles_Stats_TaggedUsers,
  _ as SharedFiles_Stats_TaggedWorkshopItems,
  _ as SharedFiles_Subscription_NowUnsubscribed,
  _ as SharedFiles_Subscription_Subscribed,
  _ as SharedFiles_Subscriptions,
  _ as SharedFiles_Tab_Merchandise,
  _ as SharedFiles_Tags,
  _ as SharedFiles_TagsSearch,
  _ as SharedFiles_UnsubscribeAll_Btn,
  _ as SharedFiles_UnsubscribeAll_Confirm_App_Desc,
  _ as SharedFiles_UnsubscribeAll_Confirm_Desc,
  _ as SharedFiles_UnsubscribeAll_Confirm_Title,
  _ as SharedFiles_UserList_BrowsePaging,
  _ as SharedFiles_UserList_LastUpdated,
  _ as SharedFiles_WaitingForIntegratedGuide,
  _ as SharedFiles_WorkshopItemsTagged,
  _ as Videos_AccessYourYouTubeVideos,
  _ as Videos_AddDone,
  _ as Videos_AddFromYouTube,
  _ as Videos_AddNote2,
  _ as Videos_AddNote4,
  _ as Videos_AddStep1,
  _ as Videos_AddStep2,
  _ as Videos_AddStep2Note,
  _ as Videos_AddStep3,
  _ as Videos_AddStep4,
  _ as Videos_AddVideo,
  _ as Videos_AllYourVideos,
  _ as Videos_AvailCountPlural,
  _ as Videos_AvailCountSingular,
  _ as Videos_Cancel,
  _ as Videos_ChangeAccount,
  _ as Videos_ClickHereToChange,
  _ as Videos_ContinueWithAcct,
  _ as Videos_CurrentlyLinkedMsg,
  _ as Videos_CurrentlyLinkedTo,
  _ as Videos_Desc1,
  _ as Videos_Desc2,
  _ as Videos_Desc3,
  _ as Videos_IssuesAccessing,
  _ as Videos_LinkYouTubeAcct,
  _ as Videos_Manage,
  _ as Videos_NoVideosMsg1,
  _ as Videos_NoVideosMsg2,
  _ as Videos_NowOnSteam,
  _ as Videos_OptionNoneOther,
  _ as Videos_OtherUnlisted,
  _ as Videos_Privacy,
  _ as Videos_Refresh,
  _ as Videos_SelectVideos,
  _ as Videos_ShareDescription,
  _ as Videos_SuccessfullyAddedPlural,
  _ as Videos_SuccessfullyAddedSingular,
  _ as Videos_SuccessfullyLinkedYouTube,
  _ as Videos_UnlinkAcct,
  _ as Videos_UnlinkButton,
  _ as Videos_UnlinkConfirmText,
  _ as Videos_UnlinkToAddAnother,
  _ as Videos_UnlinkYouTubeAcct,
  _ as Videos_YourFriendsOnlyVideos,
  _ as Videos_YourPrivateVideos,
  _ as Videos_YourPublicVideos,
  _ as Videos_YourUnlistedVideos,
  _ as Videos_YoutubeTermsLink_AuthorizedData,
  _ as Videos_YoutubeTermsLink_PrivacyPolicy,
  _ as Videos_YoutubeTermsLink_SecuritySettings,
  _ as Videos_YoutubeTermsLink_TermsOfService,
  _ as Videos_YoutubeTerms_1,
  _ as Videos_YoutubeTerms_2,
  _ as Videos_YoutubeTerms_3,
  _ as Videos_YoutubeTerms_4,
  _ as Workshop_BrowseBy,
  _ as Workshop_BrowsePaging,
  _ as Workshop_DeveloperThreadDesc,
  _ as Workshop_DeveloperThreadDisclaimerText,
  _ as Workshop_HasLinkedItems,
  _ as Workshop_ImageSize,
  _ as Workshop_ItemModalViewCountDetails,
  _ as Workshop_ItemModalViewDetails,
  _ as Workshop_Link_LegalAgreement,
  _ as Workshop_Link_PaymentInfo,
  _ as Workshop_NoItems,
  _ as Workshop_PaymentInfo_NotCreated,
  _ as Workshop_PaymentInfo_Rejected,
  _ as Workshop_SplitsAcceptTheseDesc1,
  _ as Workshop_SplitsAcceptTheseDesc2,
  _ as Workshop_SplitsPercentage,
  _ as Workshop_Subscribe_IntegratedGuide,
  _ as Workshop_ViewYourRevenue,
  _ as Workshop_ViewYourRevenue_desc,
  _ as community_errorpage_title,
  _ as community_title,
  _ as default,
  _ as empty_no_comma_following,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_accessibility,
  _ as footer_cookies,
  _ as footer_geodata_notice,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_privacy_policy,
  _ as footer_refunds,
  _ as footer_ssa,
  _ as moderatedcontent_description,
  _ as moderation_claim_n_reports_on_m_subjects,
  _ as moderation_claim_report_count,
  _ as moderation_claim_report_count_Plural,
  _ as moderation_claim_subject_count,
  _ as moderation_claim_subject_count_Plural,
  _ as moderation_forumpost_summary,
  _ as moderation_forumpost_summary_reports_fragment,
  _ as moderation_forumpost_summary_reports_fragment_Plural,
  _ as moderation_forumpost_summary_subjects_fragment,
  _ as moderation_forumpost_summary_subjects_fragment_Plural,
  _ as profile_error_profilenotfound,
  _ as profile_games_list,
  _ as profile_games_list_error_loadfailed,
  _ as profile_games_list_title,
  _ as profiletabs_communitymessages,
  _ as profiletabs_currentbans,
  _ as profiletabs_moderatedcontent,
  _ as profiletabs_reportedcontent,
  _ as reportedcontent_description,
  _ as reportedcontent_lastupdated,
};
