var _ = `Forumindlæg`,
  _ = `Generelle diskussioner`,
  _ = `Rapporterede indlæg`,
  _ = `Værkstedsdiskussioner`,
  _ = `Byttehandel`,
  _ = `Begivenheder og meddelelser`,
  _ = `1 rapportering`,
  _ = `%1$s rapporteringer`,
  _ = `1 emne`,
  _ = `%1$s emner`,
  _ = `%1$s på %2$s`,
  _ = `%1$s på %2$s i: %3$s`,
  _ = `1 rapportering`,
  _ = `%1$s rapporteringer`,
  _ = `1 emne`,
  _ = `%1$s emner`,
  _ = `Steam-fællesskabet`,
  _ = `Steam-fællesskabet :: Fejl`,
  _ = `Fejl`,
  _ = `Ukendt fejl`,
  _ = `Spil`,
  _ = `Steam-fællesskabet :: %1$s :: Spil`,
  _ = `Søg – Steam-fællesskabsmarked`,
  _ = `%1$s – Steam-fællesskabsmarked`,
  _ = `Markedsgenstand – Steam-fællesskabsmarked`,
  _ = `Steam-fællesskabsmarked`,
  _ = `Profil ikke fundet`,
  _ = `Kunne ikke indlæse brugerens ønskeliste.`,
  _ = `Du har sendt for mange anmodninger for nylig. Vent venligst, og prøv at indsende din anmodning igen senere.`,
  _ = `Indlæser`,
  _ = `%1$s% FULDFØRT`,
  _ = `SAT PÅ PAUSE – %1$s% FULDFØRT`,
  _ = `%1$s/%2$s DOWNLOADET`,
  _ = `PRÆSTATIONER`,
  _ = `%1$s tilbage (anslået)`,
  _ = `%1$s/%2$s`,
  _ = `AFINSTALLERER`,
  _ = `OPDATER`,
  _ = `AFINSTALLER`,
  _ = `DOWNLOAD`,
  _ = `PAUSE`,
  _ = `GENOPTAG`,
  _ = `AFINSTALLERER`,
  _ = `ANNULLER`,
  _ = `Se mine synlighedsindstillinger for dette indhold`,
  _ = `Find et spil`,
  _ = `Filtrer efter spil, I begge ejer`,
  _ = `Spilletid`,
  _ = `Navn`,
  _ = `Fuldførte præstationer`,
  _ = `SPILLET I ALT`,
  _ = `SIDST SPILLET`,
  _ = `SENESTE TO UGER`,
  _ = `Spilinfo og links`,
  _ = `Fjerndownload`,
  _ = `FJERNDOWNLOAD TIL: %1$s`,
  _ = `STATUS PÅ FJERNDOWNLOAD: %1$s`,
  _ = `Kunne ikke oprette forbindelse til din PC`,
  _ = `Din PC skal være tændt med en internetforbindelse, og du skal være logget på, for at fjerndownloade spil til din Steam-klient`,
  _ = `Læs de ofte stillede spørgsmål`,
  _ = `%1$s. %2$s.`,
  _ = `Læs mere`,
  _ = `FJERNDOWNLOAD UTILGÆNGELIG`,
  _ = `Vil du afinstallere %1$s? Det vil stadig være i dit spilbibliotek, men for at spille det i fremtiden skal du først downloade alt indholdet igen.`,
  _ = `%1$s | "%2$s"`,
  _ = `Spillet for nylig %1$s`,
  _ = `Alle spil %1$s`,
  _ = `100% gennemførte spil %1$s`,
  _ = `Anmeldelser %1$s`,
  _ = `Følges %1$s`,
  _ = `Ønskeliste`,
  _ = `Optjente alle de mulige præstationer`,
  _ = `Her finder du 100% gennemførte spil eller spil, hvor du har optjent alle de mulige præstationer.`,
  _ = `%1$s% af spillere har denne præstation`,
  _ = `Butiksside`,
  _ = `Forummer`,
  _ = `Grupper`,
  _ = `Officiel hjemmeside`,
  _ = `Nyheder`,
  _ = `Mine præstationer`,
  _ = `%1$s's præstationer`,
  _ = `%1$s's statistikker`,
  _ = `%1$s's personlige spildata`,
  _ = `Mine førertavler`,
  _ = `%1$s's førertavler`,
  _ = `Globale præstationer`,
  _ = `Globale førertavler`,
  _ = `Spilstatistikker`,
  _ = `Spilindhold`,
  _ = `Min spilstatistik`,
  _ = `Mit spilindhold`,
  _ = `Spillinks`,
  _ = `Mine skærmbilleder %1$s`,
  _ = `%1$s's skærmbilleder %2$s`,
  _ = `Mine venner, som spiller %1$s`,
  _ = `Mine byttekort %1$s`,
  _ = `Min anmeldelse`,
  _ = `%1$s's anmeldelse`,
  _ = `Fællesskabshub`,
  _ = `Mine noter`,
  _ = `%1$s timer`,
  _ = `%1$s minutter`,
  _ = `Markér som privat`,
  _ = `Fjern markering som privat`,
  _ = `Markér dette spil som privat, og skjul det for mine venner`,
  _ = `© Valve Corporation. Alle rettigheder forbeholdes. Alle varemærker tilhører deres respektive indehavere i USA og andre lande.`,
  _ = `Visse geodata på dette websted stilles til rådighed af %1$s.`,
  _ = `Fortrolighedspolitik`,
  _ = `Juridisk`,
  _ = `Steam-abonnentaftale`,
  _ = `Refunderinger`,
  _ = `Cookies`,
  _ = `Tilgængelighed`,
  _ = `Nuværende udelukkelser`,
  _ = `Fællesskabsmeddelelser`,
  _ = `Rapporteret indhold`,
  _ = `Modereret indhold`,
  _ = `Dette er ting på Steam, som du har rapporteret for overtrædelse af Steams retningslinjer.`,
  _ = `Dette er en liste over indhold, som du har slået op på Steam, som er blevet modereret.`,
  _ = `Sidst opdateret: %1$s`,
  _ = `Download`,
  _ = `Offentlige kommentarer (%1$s)`,
  _ = `Udviklerkommentarer (%1$s)`,
  _ = `Dette er en privat tråd, som kan ses af denne genstands bidragydere og spillets udviklere.`,
  _ = `Bemærk: Korrespondance med spillets udviklere (f.eks. Valve) garanterer ikke, at din indsendelse vil blive valgt.`,
  _ = `Størrelse:`,
  _ = `Vis alle skærmbilleder`,
  _ = `Vis alle illustrationer`,
  _ = `Vis alle videoer`,
  _ = `Tekst`,
  _ = `Rediger tekst`,
  _ = `Tilføj spoilertag`,
  _ = `Fjern spoilertag`,
  _ = `Et spoilertag lader dine venner og fællesskabet vælge, om de vil se dette indhold, så de kan undgå spilspoilers.`,
  _ = `(Spoilertags udløber efter fire uger).`,
  _ = `Brugere på dette skærmbillede:`,
  _ = `Værkstedsgenstande i dette skærmbillede:`,
  _ = `Fjern dig selv fra at være tagget i dette skærmbillede`,
  _ = `Placering`,
  _ = `Tags:`,
  _ = `Indlæser guide`,
  _ = `Abonner for at bruge denne guide i %1$s`,
  _ = `Guideindeks`,
  _ = `Oversigt`,
  _ = `Kommentarer`,
  _ = `Rediger`,
  _ = `{LINK FJERNET}`,
  _ = `URL'en, der blev linket herfra, er blevet fjernet af vores filtre. Normalt sker dette for at beskytte mod phishing og malwareangreb.`,
  _ = `Guideindhold`,
  _ = `Definer, hvordan din guide er organiseret, og navnet på sektionerne inden i guiden. Du kan trække sektioner for at omorganisere dem.`,
  _ = `Denne sektion er påkrævet, før guiden kan udgives.`,
  _ = `Opret din indholdsfortegnelse`,
  _ = `Tilføj en sektion`,
  _ = `(ny sektion, ingen titel endnu)`,
  _ = `Rediger denne sektion`,
  _ = `Slet denne sektion`,
  _ = `Er du sikker på, at du vil fjerne denne sektion? Dette kan ikke fortrydes.`,
  _ = `Billeder`,
  _ = `Vælg og upload billeder, du gerne vil referere til i din guide. Upload alle de nødvendige billeder her, og de vil nemt kunne vælges, når du redigerer individuelle sektioner i din guide.`,
  _ = `Upload billeder til din guide`,
  _ = `Tilføj bidragydere`,
  _ = `Her kan du tilføje venner som bidragydere for at give dem lov til at redigere din guide.`,
  _ = `Tilføj venner som bidragydere`,
  _ = `Tilføj en bidragyder`,
  _ = `Forhåndsvis guide`,
  _ = `Rediger guidesektion`,
  _ = `Sektionstitel`,
  _ = `Sektionsindhold`,
  _ = `Rediger`,
  _ = `Forhåndsvis`,
  _ = `Vis forskelle`,
  _ = `Enhver ændring af din tekst, siden du sidst gemte den, vil blive vist sådan her:`,
  _ = `Tekst vist som dette blev tilføjet`,
  _ = `Tekst vist som dette blev fjernet`,
  _ = `Der er foretaget ændringer i denne sektion, som endnu ikke er gemt.\xA0`,
  _ = `Der er foretaget ændringer i denne sektion, som endnu ikke er gemt. Er du sikker på, at du vil kassere disse ændringer?`,
  _ = `Sidst gemt`,
  _ = `Gem`,
  _ = `Annuller`,
  _ = `Skærmbilleder`,
  _ = `Videoer`,
  _ = `Klik på et billede nedenfor for at føje det til din guide`,
  _ = `Klik på et skærmbillede nedenfor for at føje det til din guide`,
  _ = `Klik på en video nedenfor for at føje den til din guide`,
  _ = `Billedindsættelsesindstillinger`,
  _ = `Størrelse`,
  _ = `halv bredde`,
  _ = `fuld bredde`,
  _ = `original størrelse`,
  _ = `Justering`,
  _ = `venstre`,
  _ = `højre`,
  _ = `indlejret`,
  _ = `Venstrejusteret`,
  _ = `Højrejusteret`,
  _ = `Fuld bredde`,
  _ = `Indsæt`,
  _ = `Indsæt YouTube™-video`,
  _ = `Indtast URL til YouTube™-video`,
  _ = `Citeret tekst`,
  _ = `Spoilertekst`,
  _ = `Indtast en titel`,
  _ = `Gå til din guide`,
  _ = ``,
  _ = `Værkstedsgenstande:`,
  _ = `og %1$s andre`,
  _ = `Vis kommentarer og detaljer`,
  _ = `Vis %1$s kommentarer og detaljer`,
  _ = `Skærmbilleder`,
  _ = `Illustrationer`,
  _ = `Videoer`,
  _ = `Værkstedsgenstande`,
  _ = `Merchandise`,
  _ = `Samlinger`,
  _ = `Guider`,
  _ = `Værkstedsgenstande`,
  _ = `Værkstedssamlinger`,
  _ = `Guider`,
  _ = `Favoritter`,
  _ = `Abonnerede emner`,
  _ = `Spillet`,
  _ = `Filtrer efter spil`,
  _ = `Alle spil`,
  _ = `Vælg et spil`,
  _ = `Genstande`,
  _ = `Føjet til foretrukne`,
  _ = `Abonnerede genstande`,
  _ = `Oprettelsesdato`,
  _ = `Alfabetisk`,
  _ = `Opdateringsdato`,
  _ = `Abonnementsdato`,
  _ = `Tilføjelsesdato`,
  _ = `Vis genstande tagget med alle følgende valgte termer:`,
  _ = `af`,
  _ = `Viser %1$s-%2$s af %3$s forekomster`,
  _ = `Der blev ikke fundet nogen filer, der matchede %1$s.`,
  _ = `Viser %1$s-%2$s af %3$s forekomster`,
  _ = `Sidst opdateret: %1$s`,
  _ = `Tilføjet: %1$s`,
  _ = `Denne genstand er blevet fjernet fra din liste over foretrukne:`,
  _ = `Abonneret: %1$s`,
  _ = `Du har nu opsagt dit abonnement fra:`,
  _ = `Hurra! Nogle af dine indsendte Steam-værkstedsgenstande er blevet udvalgt til brug!`,
  _ = `Før du giver dig til at fejre det, bedes du indtaste dine <a href="%1$s">betalingsoplysninger</a>, så vi ved, hvem indtægterne skal udbetales til!`,
  _ = `Der var et problem med at godkende dine betalingsoplysninger. Gennemse venligst dine <a href="%1$s">betalingsoplysninger</a> og opdater dem.`,
  _ = `Du er blevet noteret som bidragyder på følgende genstande`,
  _ = `Gennemse og accepter designerstatus for de følgende genstande`,
  _ = `Procentdel:`,
  _ = `Dit værksted`,
  _ = `Følg denne bruger for at se, når vedkommende slår nye Steam-guider op, skaber nye samlinger eller slår genstande op i Steam-værkstedet.`,
  _ = `Steam-brugere, som følger dig, kan se, når du slår nye Steam-guider op, skaber nye samlinger eller slår genstande op i Steam-værkstedet.`,
  _ = `følger`,
  _ = `følgere`,
  _ = `Følg %1$s`,
  _ = `Følger %1$s`,
  _ = `Hold op med at følge %1$s`,
  _ = `Se din indtægt`,
  _ = `Fra salg af dine værkstedsgenstande`,
  _ = `Indtast eller opdater dine betalingsoplysninger`,
  _ = `Se juridisk aftale`,
  _ = `Afmeld alle abonnementer`,
  _ = `Afmeld alle abonnementer?`,
  _ = `Er du sikker på, at du vil afmelde alle dine abonnementer?<br><br>Dette kan ikke fortrydes!`,
  _ = `Er du sikker på, at du vil afmelde alle dine abonnementer for %1$s?<br><br>Dette kan ikke fortrydes!`,
  _ = `Gem i samling`,
  _ = `Gem abonnementer i samling`,
  _ = `Vil du gemme dine abonnementer i en ny samling eller i en eksisterende samling?`,
  _ = `Ny samling`,
  _ = `Indtast et navn til denne samling:`,
  _ = `Eksisterende samling`,
  _ = `Vælg en samling, der skal overskrives: `,
  _ = `Du har ikke nogen eksisterende samlinger. Vil du oprette en?`,
  _ = `Administratortags`,
  _ = `Steam-guider`,
  _ = `Integrerede guider`,
  _ = `Helte-builds`,
  _ = `Specielt integrerede guider, som oplærer dig, mens du spiller.`,
  _ = `Guider, der er blevet særligt integreret med %1$s`,
  _ = `Populære kategorier`,
  _ = `Integrerede guider`,
  _ = `Dine foretrukne`,
  _ = `Populære Steam-guider`,
  _ = `Skrevne guider, referencer og walkthroughs`,
  _ = `Vis alle (%1$s)`,
  _ = `%1$s guide`,
  _ = `%1$s guider`,
  _ = `Guider, du har lavet`,
  _ = `Mere om guider`,
  _ = `Klik her for at lære mere om Steam-guider`,
  _ = `Søg efter:`,
  _ = `Startside`,
  _ = `Opret guide`,
  _ = `Hvis du gerne vil lave en guide, skal du først købe %1$s.`,
  _ = `Vær den første til at oprette en guide til dette spil!`,
  _ = `Demonstrer din ekspertise, eller hjælp andre, der sidder fast.`,
  _ = `Opret en walkthrough, afslør spilhemmeligheder eller anbefal optimale strategier til bestemte baner.`,
  _ = `Gennemse og vurder spillerskabte guider til dette spil. Eller opret din egen og del dine tips med fællesskabet.`,
  _ = `Opret din egen`,
  _ = `Skærmbilleder`,
  _ = `Illustrationer`,
  _ = `Videoer`,
  _ = `Viser %1$s-%2$s af %3$s`,
  _ = `Tilbage til toppen`,
  _ = `Viser:`,
  _ = `Billedmur`,
  _ = `Gittervisning`,
  _ = `Mest populære`,
  _ = `Nyeste først`,
  _ = `Ældste først`,
  _ = `Alle dine skærmbilleder`,
  _ = `Dine offentlige skærmbilleder`,
  _ = `Dine skærmbilleder kun for venner`,
  _ = `Dine private skærmbilleder`,
  _ = `Dine skærmbilleder, som ikke er opførte`,
  _ = `Alle dine illustrationer`,
  _ = `Dine offentlige illustrationer`,
  _ = `Dine illustrationer, som kun er for venner`,
  _ = `Dine private illustrationer`,
  _ = `Dine illustrationer, som ikke er opførte`,
  _ = `Alle dine videoer`,
  _ = `Dine offentlige videoer`,
  _ = `Dine videoer kun for venner`,
  _ = `Dine private videoer`,
  _ = `Dine videoer, som ikke er opførte`,
  _ = `Administrer skærmbilleder`,
  _ = `Administrer illustrationer`,
  _ = `Administrer videoer`,
  _ = `Vælg de skærmbilleder, du gerne vil gøre noget med.`,
  _ = `Vælg de illustrationer nedenfor, du gerne vil gøre noget med.`,
  _ = `Vælg de videoer, du gerne vil gøre noget med.`,
  _ = `Annuller`,
  _ = `Tilføj videoer fra YouTube`,
  _ = `Tilknyt YouTube-konto`,
  _ = `Fjern tilknytning til YouTube-konto`,
  _ = `Fjern tilknytning`,
  _ = `Er du sikker på, at du vil fjerne tilknytningen til din YouTube-konto?`,
  _ = `Hvordan bruger Steam mine data fra YouTube?`,
  _ = `Når du tilknytter din YouTube-konto til Steam, bruges YouTubes API-tjenester. Når du bruger YouTube og tilknytter din YouTube-konto til din Steam-profil, accepterer du at være bundet af %1$s og %2$s.`,
  _ = `Steam bruger YouTubes API-tjeneste til at godkende din YouTube-konto og til at få adgang til listen over videoer, som du har slået op på YouTube. Når du tilknytter din YouTube-konto til Steam, placerer Steam en cookie i din browser eller Steam-klienten, som indeholder din kontos godkendelsestokens til YouTube. Denne cookie udløber efter 30 dage. Når Steam har adgang til listen over videoer, du har slået op på din YouTube-konto, bruges disse data udelukkende til at vise denne liste på Steam.`,
  _ = `Når du slår en video op fra din YouTube-konto på Steam, gemmer Steam kun de oplysninger, som er nødvendige for at vise videoen på Steam, herunder video-ID og videoens YouTube-konto-ID. Disse data bruges kun til at vise videoen på Steam og til indholdsmoderation på Steam.`,
  _ = `Du kan tilbagekalde Steams adgang til dine %1$s via %2$s.`,
  _ = `YouTubes servicevilkår`,
  _ = `Googles privatlivspolitik`,
  _ = `godkendte data`,
  _ = `Googles side med sikkerhedsindstillinger`,
  _ = `Dine videoer. Nu på Steam.`,
  _ = `Del dine fineste spiløjeblikke med dine venner. Upload fantastiske højdepunkter, indsigtsfulde anmeldelser, hjælpsomme instruktioner og andre spilinspirerede perler skabt af dig.`,
  _ = `1. Tilknyt din YouTube™-konto til din Steam-profil.`,
  _ = `2. Vælg de videoer, du vil føje til din profil.`,
  _ = `3. Del med dine Steam-venner, så de kan beundre dem.`,
  _ = `Få adgang til dine YouTube-videoer`,
  _ = `Du er i øjeblikket knyttet til YouTube-kontoen %1$s.`,
  _ = `Fjern tilknytningen til denne konto for at tilføje en anden.`,
  _ = `Fjern tilknytning til denne konto`,
  _ = `Fortsæt med denne konto`,
  _ = `Din YouTube-konto er blevet tilknyttet`,
  _ = `1 video tilføjet`,
  _ = `%1$s videoer tilføjet`,
  _ = `Der blev ikke fundet nogen videoer at vælge imellem i din YouTube-samling.`,
  _ = `Du kan kun tilføje YouTube-videoer, som er offentligt synlige, tillader indlejring, og som vises ved en brugernavnssøgning på dit brugernavn. Hvis du lige har sat en video til at være offentlig for at kunne tilknytte din konto, kan det tage noget tid for YouTube at indeksere den, før den bliver vist i søgeresultater.`,
  _ = `Du har i øjeblikket YouTube-kontoen %1$s tilknyttet til Steam.`,
  _ = `Klik her for at skifte YouTube-konto`,
  _ = `skift konto`,
  _ = `1. Vælg videoer, der skal tilføjes.`,
  _ = `1 tilgængelig video for kontoen %1$s`,
  _ = `Viser de seneste %1$s tilgængelige videoer for kontoen: %2$s`,
  _ = `2. Tilknyt videoerne til et spil.`,
  _ = `Efter du har valgt videoerne til venstre. (Valgfrit)`,
  _ = `- ingen / andre (angiv nedenfor) -`,
  _ = `Andre/ikke opført`,
  _ = `3. Tilføj den til din profil.`,
  _ = `Tilføj video`,
  _ = `Bemærk: For at tilføje videoer fra din YouTube-konto skal de være offentligt synlige og tillade indlejring. Hvis du lige har føjet en video til din YouTube-konto og ikke kan se den på listen, skal du opdatere den ved at klikke på nedenstående knap.`,
  _ = `Opdater YouTube-videoliste`,
  _ = `4. Afslut.`,
  _ = `Når du er færdig, kan du klikke på "Færdig" for at se videoerne på din profilside.`,
  _ = `Færdig`,
  _ = `Der opstod et problem med at tilgå din video. Prøv igen.`,
  _ = `Upload illustrationer`,
  _ = `Upload skærmbilleder...`,
  _ = `Gør offentlig`,
  _ = `Gør til "Kun venner"`,
  _ = `Gør privat`,
  _ = `Opfør ikke`,
  _ = `Slet`,
  _ = `Vælg alle`,
  _ = `Færdig`,
  _ = `Slet disse emner?`,
  _ = `Opdater synlighed`,
  _ = `Dette vil slette %1$s fra Steam Cloud. Ønsker du at fortsætte?`,
  _ = `Dette vil opdatere synligheden for %1$s til %2$s. Ønsker du at fortsætte?`,
  _ = `Fortsæt`,
  _ = `Annuller`,
  _ = `Ups!`,
  _ = `Ingen emner valgt.`,
  _ = `Vælg emner, du vil slette ved at bruge afkrydsningsfeltet i hjørnet af hvert af de små billeder.`,
  _ = `OK`,
  _ = `Synlighedsopdatering mislykkedes`,
  _ = `Et eller flere af de skærmbilleder, hvor du forsøgte at indstille synligheden til "Offentlig" eller "Kun venner", kunne ikke opdateres. Skærmbilleder fra spil, som ikke er offentligt tilgængelige i Steam-fællesskabet, kan ikke deles og kan kun ses af dig.`,
  _ = `Potentielle spoilers.`,
  _ = `Hold musen over for at vise billede.`,
  _ = `Ingen matchende skærmbilleder blev fundet.`,
  _ = `%1$s har ingen skærmbilleder, som du kan se.`,
  _ = `Du har ikke tilføjet nogen skærmbilleder til foretrukne.`,
  _ = `%1$s har ingen foretrukne skærmbilleder, du kan se.`,
  _ = `Du har i øjeblikket ikke gemt nogen illustrationer i Steam Cloud. For at uploade illustrationer skal du gå til den relaterede spilhubs "Illustrationer"-fane og klikke på knappen "Upload illustrationer" øverst til højre. Eller klik på knappen "Upload illustrationer" herunder.`,
  _ = `%1$s har ingen illustrationer, som du kan se.`,
  _ = `Du har ikke tilføjet nogen illustrationer til foretrukne.`,
  _ = `%1$s har ingen foretrukne illustrationer, som du kan se.`,
  _ = `Ingen matchende videoer blev fundet.`,
  _ = `%1$s har ingen videoer, som du kan se.`,
  _ = `Du har ikke tilføjet nogen videoer til foretrukne.`,
  _ = `%1$s har ingen foretrukne videoer, som du kan se.`,
  _ = `Du har ikke nogen skærmbilleder sat til denne synlighed.`,
  _ = `Steam har gjort det nemmere at tage og dele skærmbilleder af dine favoritspil.`,
  _ = `Tryk på din genvejstast (F12 som standard), imens du er i et hvilket som helst spil, som understøtter Steam-overlayet, for at tage skærmbilleder. Dernæst kan du offentliggøre dem både på din Steam-fællesskabsprofil såvel som på Facebook, Twitter eller Reddit for at dele dem med dine venner.`,
  _ = `Med 1 GB personlig lagerplads i Steam Cloud kan du uploade tusindvis af skærmbilleder for at vise dine bedste øjeblikke frem, så alle dine venner kan se dem. Du kan også gøre dem private, hvis du hellere vil holde dem for dig selv.`,
  _ = `Af %1$s`,
  _ = `%1$s's foretrukne`,
  _ = {
    Moderation_SubjectTypeName_ForumPost: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    moderation_claim_report_count: _,
    moderation_claim_report_count_Plural: _,
    moderation_claim_subject_count: _,
    moderation_claim_subject_count_Plural: _,
    moderation_claim_n_reports_on_m_subjects: _,
    moderation_forumpost_summary: _,
    moderation_forumpost_summary_reports_fragment: _,
    moderation_forumpost_summary_reports_fragment_Plural: _,
    moderation_forumpost_summary_subjects_fragment: _,
    moderation_forumpost_summary_subjects_fragment_Plural: _,
    community_title: _,
    community_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    profile_games_list: _,
    profile_games_list_title: _,
    Market_Search_Title: _,
    Market_Item_Title: _,
    Market_Item_GenericTitle: _,
    Market_GenericTitle: _,
    profile_error_profilenotfound: _,
    profile_games_list_error_loadfailed: _,
    Error_RateLimited: _,
    Loading: _,
    GamesList_Header_Downloading: _,
    GamesList_Header_Paused: _,
    GamesList_Header_DownloadBytes: _,
    GamesList_Header_Achievements: _,
    GamesList_TimeRemaining: _,
    GamesList_Achievement_Fraction: _,
    GamesList_Uninstalling: _,
    GamesList_Button_UpdateRequired: _,
    GamesList_Button_Uninstall: _,
    GamesList_Button_Download: _,
    GamesList_Button_Pause: _,
    GamesList_Button_Resume: _,
    GamesList_Button_Uninstalling: _,
    GamesList_Button_Cancel: _,
    GamesList_PrivacySettings_Tooltip: _,
    GamesList_Filter_Placeholder: _,
    GamesList_Filter_BothOwned: _,
    GamesList_Sort_HoursPlayed: _,
    GamesList_Sort_Name: _,
    GamesList_Sort_AchievementCompletion: _,
    GamesList_Header_TotalPlayed: _,
    GamesList_Header_LastPlayed: _,
    GamesList_Header_TwoWeeks: _,
    GamesList_MenuLabel_GameInfo: _,
    GamesList_MenuLabel_RemoteDownload: _,
    GamesList_Header_RemoteDownload: _,
    GamesList_Header_RemoteDownloadStatus: _,
    GamesList_RemoteDownload_NoConnection: _,
    GamesList_RemoteDownload_Help: _,
    GamesList_RemoteDownload_ReadTheFAQ: _,
    GamesList_RemoteDownload_Info: _,
    GamesList_RemoteDownload_LearnMore: _,
    GamesList_RemoteDownload_NoRemoteControl: _,
    GamesList_RemoteDownload_UninstallConfirm: _,
    GamesList_Client_Indicator: _,
    GamesList_Tab_RecentlyPlayed: _,
    GamesList_Tab_AllGames: _,
    GamesList_Tab_PerfectGames: _,
    GamesList_Tab_Reviews: _,
    GamesList_Tab_Followed: _,
    GamesList_Tab_Wishlist: _,
    Perfect_Game_Description: _,
    GamesList_PerfectGames_Description: _,
    GamesList_Achievement_Unlock_Percentage: _,
    Community_StorePage: _,
    Community_Forums: _,
    Community_Groups: _,
    Community_OfficialWebsite: _,
    Community_News: _,
    Community_UsersAchievementsFirstPerson: _,
    Community_UsersAchievements: _,
    Community_UsersStats: _,
    Community_GamePersonalData: _,
    Community_UsersLeaderboardsFirstPerson: _,
    Community_UsersLeaderboards: _,
    Community_GlobalAchievements: _,
    Community_GlobalLeaderboards: _,
    Community_GameStats: _,
    Community_GameContent: _,
    Community_GameStatsFirstPerson: _,
    Community_GameContentFirstPerson: _,
    Community_GameLinks: _,
    Community_ScreenshotsMenuItemFirstPerson: _,
    Community_ScreenshotsMenuItemThirdPerson: _,
    Community_FriendsWhoPlayMenuItemFirstPerson: _,
    Community_TradingCardsMenuItemFirstPerson: _,
    Community_ReviewMenuItemFirstPerson: _,
    Community_ReviewMenuItemThirdPerson: _,
    Community_GameHubMenuItem: _,
    Community_GameNotesFirstPerson: _,
    Playtime_Hours: _,
    Playtime_Minutes: _,
    AppPrivacy_MarkAsPrivate: _,
    AppPrivacy_UnmarkAsPrivate: _,
    AppPrivacy_Explanation: _,
    footer_legal_notice: _,
    footer_geodata_notice: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_accessibility: _,
    profiletabs_currentbans: _,
    profiletabs_communitymessages: _,
    profiletabs_reportedcontent: _,
    profiletabs_moderatedcontent: _,
    reportedcontent_description: _,
    moderatedcontent_description: _,
    reportedcontent_lastupdated: _,
    SharedFiles_ItemDownload: _,
    SharedFiles_PublicComments: _,
    SharedFiles_DeveloperComments: _,
    Workshop_DeveloperThreadDesc: _,
    Workshop_DeveloperThreadDisclaimerText: _,
    Workshop_ImageSize: _,
    SharedFiles_Media_ViewAppScreenshots: _,
    SharedFiles_Media_ViewAppFanArt: _,
    SharedFiles_Media_ViewAppVideos: _,
    SharedFiles_ItemEditText_Text_Caption: _,
    SharedFiles_OwnerControl_EditCaption: _,
    SharedFiles_AddSpoilerTag: _,
    SharedFiles_RemoveSpoilerTag: _,
    SharedFiles_SpoilerTagInstructions: _,
    SharedFiles_SpoilerTagsExpire: _,
    SharedFiles_Stats_TaggedUsers: _,
    SharedFiles_Stats_TaggedWorkshopItems: _,
    SharedFiles_RemoveSelfTag_Tooltip: _,
    Screenshots_Location: _,
    SharedFiles_Tags: _,
    SharedFiles_WaitingForIntegratedGuide: _,
    Workshop_Subscribe_IntegratedGuide: _,
    SharedFiles_Guide_Index: _,
    SharedFiles_Guide_Overview: _,
    SharedFiles_Guide_Comments: _,
    SharedFiles_Item_Edit_Link: _,
    Community_RemoveLink_BeWary: _,
    Community_RemoveLink_Tooltip: _,
    SharedFiles_ManageGuide_Contents: _,
    SharedFiles_ManageGuide_Contents_Desc: _,
    SharedFiles_ManageGuide_Required: _,
    SharedFiles_ManageGuide_NoSubSections: _,
    SharedFiles_ManageGuide_AddSection: _,
    SharedFiles_ManageGuide_NoSectionTitle: _,
    SharedFiles_ManageGuide_EditThisSection: _,
    SharedFiles_ManageGuide_DeleteThisSection: _,
    SharedFiles_ManageGuide_RemoveSectionConfirm: _,
    SharedFiles_ManageGuide_Images: _,
    SharedFiles_ManageGuide_Images_Desc: _,
    SharedFiles_ManageGuide_NoPreviewImages: _,
    SharedFiles_ManageGuide_Contributors: _,
    SharedFiles_ManageGuide_Contributors_Desc: _,
    SharedFiles_ManageGuide_NoContributors: _,
    SharedFiles_ManageGuide_AddContributor: _,
    SharedFiles_ManageGuide_Preview: _,
    SharedFiles_ManageGuide_EditSubSection: _,
    SharedFiles_ManageGuide_SubSectionTitle: _,
    SharedFiles_ManageGuide_SubSectionContents: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Edit: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Preview: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Changes: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Desc: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Insert: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Delete: _,
    SharedFiles_ManageGuide_SubSectionContentChanged: _,
    SharedFiles_ManageGuide_SubSectionContentChanged_CancelConfirm: _,
    SharedFiles_ManageGuide_SubSectionContentSaved: _,
    SharedFiles_ManageGuide_Save: `Gem`,
    SharedFiles_ManageGuide_Cancel: _,
    SharedFiles_ManageGuide_Screenshots: _,
    SharedFiles_ManageGuide_Videos: _,
    SharedFiles_ManageGuide_SubImages: _,
    SharedFiles_ManageGuide_SubScreenshots: _,
    SharedFiles_ManageGuide_SubVideos: _,
    SharedFiles_ManageGuide_ImageInsertionOptions: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_Size: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeThumb: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeFull: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeOriginal: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_Layout: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutLeft: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutRight: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutInline: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Left: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Right: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Full: _,
    SharedFiles_ManageGuide_InsertImage: _,
    SharedFiles_ManageGuide_InsertYouTubeVideo: _,
    SharedFiles_ManageGuide_PromptYouTubeUrl: _,
    Discussions_FormattingHelp_Quote: _,
    Discussions_FormattingHelp_Spoiler: _,
    SharedFiles_ItemEditText_ErrorNoTitle: _,
    SharedFiles_OwnerControl_BackGuide: _,
    empty_no_comma_following: ``,
    SharedFiles_WorkshopItemsTagged: _,
    SharedFiles_And_N_More: _,
    Workshop_ItemModalViewDetails: _,
    Workshop_ItemModalViewCountDetails: _,
    Profile_Screenshots: _,
    Profile_Images: _,
    Profile_Videos: _,
    Profile_Workshop_Items: _,
    SharedFiles_Tab_Merchandise: _,
    Profile_Collections: _,
    Profile_Guides: _,
    SharedFiles_SharedFiles_Items: _,
    SharedFiles_SharedFiles_Collections: _,
    SharedFiles_SharedFiles_Guides: _,
    SharedFiles_Favorites: _,
    SharedFiles_Subscriptions: _,
    SharedFiles_Browse_MyFiles_Played: _,
    SharedFiles_FilterByGame: _,
    Profile_SharedFiles_AllGames: _,
    Profile_SharedFiles_SelectAGame: _,
    SharedFiles_Browse_MyFiles_Items: _,
    SharedFiles_Browse_MyFiles_Favorites: _,
    SharedFiles_Browse_MyFiles_Subscriptions: _,
    SharedFiles_Browse_MyFiles_Sort_CreationOrder: _,
    SharedFiles_Browse_MyFiles_Sort_Alpha: _,
    SharedFiles_Browse_MyFiles_Sort_LastUpdated: _,
    SharedFiles_Browse_MyFiles_Sort_Subscribed: _,
    SharedFiles_Browse_MyFiles_Sort_Favorited: _,
    SharedFiles_TagsSearch: _,
    SharedFiles_ByAuthor: `af`,
    Workshop_BrowsePaging: _,
    Workshop_NoItems: _,
    SharedFiles_UserList_BrowsePaging: _,
    SharedFiles_UserList_LastUpdated: _,
    SharedFiles_Favorites_Subscribed: _,
    SharedFiles_Favorites_NowUnsubscribed: _,
    SharedFiles_Subscription_Subscribed: _,
    SharedFiles_Subscription_NowUnsubscribed: _,
    Workshop_HasLinkedItems: _,
    Workshop_PaymentInfo_NotCreated: _,
    Workshop_PaymentInfo_Rejected: _,
    Workshop_SplitsAcceptTheseDesc1: _,
    Workshop_SplitsAcceptTheseDesc2: _,
    Workshop_SplitsPercentage: _,
    Profile_YourWorkshop: _,
    CommunityFollower_Description: _,
    CommunityFollower_Description_Yours: _,
    CommunityFollower_One_Follower: _,
    CommunityFollower_NumFollowers: _,
    CommunityFollower_FollowUser: _,
    CommunityFollower_FollowingUser: _,
    CommunityFollower_UnfollowUser: _,
    Workshop_ViewYourRevenue: _,
    Workshop_ViewYourRevenue_desc: _,
    Workshop_Link_PaymentInfo: _,
    Workshop_Link_LegalAgreement: _,
    SharedFiles_UnsubscribeAll_Btn: _,
    SharedFiles_UnsubscribeAll_Confirm_Title: _,
    SharedFiles_UnsubscribeAll_Confirm_Desc: _,
    SharedFiles_UnsubscribeAll_Confirm_App_Desc: _,
    SharedFiles_SaveSubscribedToCollection_Btn: _,
    SharedFiles_SaveSubscribedToCollection_Title: _,
    SharedFiles_SaveSubscribedToCollection_Desc: _,
    SharedFiles_SaveSubscribedToCollection_New: _,
    SharedFiles_SaveSubscribedToCollection_NewDesc: _,
    SharedFiles_SaveSubscribedToCollection_Existing: _,
    SharedFiles_SaveSubscribedToCollection_ExistingDesc: _,
    SharedFiles_SaveSubscribedToCollection_NoExistingCollections: _,
    SharedFiles_AdminTags: _,
    SharedFiles_SearchedForFileType_WebGuide: _,
    SharedFiles_SearchedForFileType_IntegratedGuide: _,
    SharedFiles_Dota2_IntegratedGuide: _,
    SharedFiles_Dota2_IntegratedGuide_Desc: _,
    AppHub_Guides_IntegratedGuides_Desc: _,
    AppHub_Guides_PopularCategories: _,
    AppHub_Guides_IntegratedGuides: _,
    AppHub_Guides_YourFavorites: _,
    AppHub_Guides_MostPopularThisWeek: _,
    AppHub_Guides_MostPopularThisWeek_Desc: _,
    AppHub_Guides_ViewAll: _,
    AppHub_Guides_NumGuides_Singular: _,
    AppHub_Guides_NumGuides_Plural: _,
    AppHub_Guides_GuidesYouHaveMade: _,
    AppHub_Guides_MoreInfo_Title: _,
    AppHub_Guides_MoreInfo_button: _,
    Workshop_BrowseBy: _,
    SharedFiles_Browse_GuideHome: _,
    SharedFiles_CreateGuide: _,
    SharedFiles_MustOwnAppToCreateGuide: _,
    SharedFiles_NoGuides_Title: _,
    SharedFiles_NoGuides_Desc1: _,
    SharedFiles_NoGuides_Desc2: _,
    SharedFiles_BrowseGuide_subtitle_nolink: _,
    SharedFiles_BrowseGuide_createNewBtnLabel: _,
    Community_Screenshots: _,
    Community_Images: _,
    Community_Videos: _,
    Paging_ShowingXtoYofZ: _,
    AppHubHome_BackToTop: _,
    Screenshots_Viewing: _,
    Profile_SharedFiles_ImageWallView: _,
    Profile_SharedFiles_GridView: _,
    Profile_SharedFiles_MostPopular: _,
    Profile_SharedFiles_NewestFirst: _,
    Profile_SharedFiles_OldestFirst: _,
    Screenshots_AllYourScreenshots: _,
    Screenshots_YourPublicScreenshots: _,
    Screenshots_YourFriendsOnlyScreenshots: _,
    Screenshots_YourPrivateScreenshots: _,
    Screenshots_YourUnlistedScreenshots: _,
    Images_AllYourImages: _,
    Images_YourPublicImages: _,
    Images_YourFriendsOnlyImages: _,
    Images_YourPrivateImages: _,
    Images_YourUnlistedImages: _,
    Videos_AllYourVideos: _,
    Videos_YourPublicVideos: _,
    Videos_YourFriendsOnlyVideos: _,
    Videos_YourPrivateVideos: _,
    Videos_YourUnlistedVideos: _,
    Screenshots_Manage: _,
    Images_Manage: _,
    Videos_Manage: _,
    Screenshots_SelectScreenshots: _,
    Images_SelectImages: _,
    Videos_SelectVideos: _,
    Videos_Cancel: _,
    Videos_AddFromYouTube: _,
    Videos_LinkYouTubeAcct: _,
    Videos_UnlinkYouTubeAcct: _,
    Videos_UnlinkButton: _,
    Videos_UnlinkConfirmText: _,
    Videos_Privacy: _,
    Videos_YoutubeTerms_1: _,
    Videos_YoutubeTerms_2: _,
    Videos_YoutubeTerms_3: _,
    Videos_YoutubeTerms_4: _,
    Videos_YoutubeTermsLink_TermsOfService: _,
    Videos_YoutubeTermsLink_PrivacyPolicy: _,
    Videos_YoutubeTermsLink_AuthorizedData: _,
    Videos_YoutubeTermsLink_SecuritySettings: _,
    Videos_NowOnSteam: _,
    Videos_ShareDescription: _,
    Videos_Desc1: _,
    Videos_Desc2: _,
    Videos_Desc3: _,
    Videos_AccessYourYouTubeVideos: _,
    Videos_CurrentlyLinkedTo: _,
    Videos_UnlinkToAddAnother: _,
    Videos_UnlinkAcct: _,
    Videos_ContinueWithAcct: _,
    Videos_SuccessfullyLinkedYouTube: _,
    Videos_SuccessfullyAddedSingular: _,
    Videos_SuccessfullyAddedPlural: _,
    Videos_NoVideosMsg1: _,
    Videos_NoVideosMsg2: _,
    Videos_CurrentlyLinkedMsg: _,
    Videos_ClickHereToChange: _,
    Videos_ChangeAccount: _,
    Videos_AddStep1: _,
    Videos_AvailCountSingular: _,
    Videos_AvailCountPlural: _,
    Videos_AddStep2: _,
    Videos_AddStep2Note: _,
    Videos_OptionNoneOther: _,
    Videos_OtherUnlisted: _,
    Videos_AddStep3: _,
    Videos_AddVideo: _,
    Videos_AddNote2: _,
    Videos_Refresh: _,
    Videos_AddStep4: _,
    Videos_AddNote4: _,
    Videos_AddDone: _,
    Videos_IssuesAccessing: _,
    Images_Upload: _,
    Screenshots_Upload: _,
    Screenshots_MakePublic: _,
    Screenshots_MakeFriendsOnly: _,
    Screenshots_MakePrivate: _,
    Screenshots_MakeUnlisted: _,
    Screenshots_Delete: _,
    Screenshots_SelectAll: _,
    Screenshots_Done: _,
    Screenshots_DeleteScreenshots: _,
    Screenshots_UpdatePrivacy: _,
    Screenshots_AreYouSureDelete: _,
    Screenshots_AreYouSurePrivacyChange: _,
    Screenshots_Continue: _,
    Screenshots_Cancel: _,
    Screenshots_Oops: _,
    Screenshots_NoneSelected: _,
    Screenshots_SelectScreenshotsToDelete: _,
    Screenshots_OK: `OK`,
    Screenshots_VisUpdateFailed: _,
    Screenshots_VisUpdateFailedMessage: _,
    Blotter_PotentialSpoilers: _,
    Blotter_RevealImage: _,
    Profile_SharedFiles_NoScreenshotsSelf: _,
    Profile_SharedFiles_NoScreenshotsForYou: _,
    Profile_SharedFiles_NoScreenshotsFavoritesSelf: _,
    Profile_SharedFiles_NoScreenshotsFavoritesForYou: _,
    Profile_SharedFiles_NoImagesSelf: _,
    Profile_SharedFiles_NoImagesForYou: _,
    Profile_SharedFiles_NoImagesFavoritesSelf: _,
    Profile_SharedFiles_NoImagesFavoritesForYou: _,
    Profile_SharedFiles_NoVideosSelf: _,
    Profile_SharedFiles_NoVideosForYou: _,
    Profile_SharedFiles_NoVideosFavoritesSelf: _,
    Profile_SharedFiles_NoVideosFavoritesForYou: _,
    Profile_SharedFiles_NoScreenshotsThisVisibility: _,
    Screenshots_SteamHasThem: _,
    Screenshots_Instructions1: _,
    Screenshots_Instructions2: _,
    Profile_SharedFiles_By: _,
    Profile_SharedFiles_FavoritedBy: _,
  };
export {
  _ as AppHubHome_BackToTop,
  _ as AppHub_Guides_GuidesYouHaveMade,
  _ as AppHub_Guides_IntegratedGuides,
  _ as AppHub_Guides_IntegratedGuides_Desc,
  _ as AppHub_Guides_MoreInfo_Title,
  _ as AppHub_Guides_MoreInfo_button,
  _ as AppHub_Guides_MostPopularThisWeek,
  _ as AppHub_Guides_MostPopularThisWeek_Desc,
  _ as AppHub_Guides_NumGuides_Plural,
  _ as AppHub_Guides_NumGuides_Singular,
  _ as AppHub_Guides_PopularCategories,
  _ as AppHub_Guides_ViewAll,
  _ as AppHub_Guides_YourFavorites,
  _ as AppPrivacy_Explanation,
  _ as AppPrivacy_MarkAsPrivate,
  _ as AppPrivacy_UnmarkAsPrivate,
  _ as Blotter_PotentialSpoilers,
  _ as Blotter_RevealImage,
  _ as CommunityFollower_Description,
  _ as CommunityFollower_Description_Yours,
  _ as CommunityFollower_FollowUser,
  _ as CommunityFollower_FollowingUser,
  _ as CommunityFollower_NumFollowers,
  _ as CommunityFollower_One_Follower,
  _ as CommunityFollower_UnfollowUser,
  _ as Community_Forums,
  _ as Community_FriendsWhoPlayMenuItemFirstPerson,
  _ as Community_GameContent,
  _ as Community_GameContentFirstPerson,
  _ as Community_GameHubMenuItem,
  _ as Community_GameLinks,
  _ as Community_GameNotesFirstPerson,
  _ as Community_GamePersonalData,
  _ as Community_GameStats,
  _ as Community_GameStatsFirstPerson,
  _ as Community_GlobalAchievements,
  _ as Community_GlobalLeaderboards,
  _ as Community_Groups,
  _ as Community_Images,
  _ as Community_News,
  _ as Community_OfficialWebsite,
  _ as Community_RemoveLink_BeWary,
  _ as Community_RemoveLink_Tooltip,
  _ as Community_ReviewMenuItemFirstPerson,
  _ as Community_ReviewMenuItemThirdPerson,
  _ as Community_Screenshots,
  _ as Community_ScreenshotsMenuItemFirstPerson,
  _ as Community_ScreenshotsMenuItemThirdPerson,
  _ as Community_StorePage,
  _ as Community_TradingCardsMenuItemFirstPerson,
  _ as Community_UsersAchievements,
  _ as Community_UsersAchievementsFirstPerson,
  _ as Community_UsersLeaderboards,
  _ as Community_UsersLeaderboardsFirstPerson,
  _ as Community_UsersStats,
  _ as Community_Videos,
  _ as Discussions_FormattingHelp_Quote,
  _ as Discussions_FormattingHelp_Spoiler,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as GamesList_Achievement_Fraction,
  _ as GamesList_Achievement_Unlock_Percentage,
  _ as GamesList_Button_Cancel,
  _ as GamesList_Button_Download,
  _ as GamesList_Button_Pause,
  _ as GamesList_Button_Resume,
  _ as GamesList_Button_Uninstall,
  _ as GamesList_Button_Uninstalling,
  _ as GamesList_Button_UpdateRequired,
  _ as GamesList_Client_Indicator,
  _ as GamesList_Filter_BothOwned,
  _ as GamesList_Filter_Placeholder,
  _ as GamesList_Header_Achievements,
  _ as GamesList_Header_DownloadBytes,
  _ as GamesList_Header_Downloading,
  _ as GamesList_Header_LastPlayed,
  _ as GamesList_Header_Paused,
  _ as GamesList_Header_RemoteDownload,
  _ as GamesList_Header_RemoteDownloadStatus,
  _ as GamesList_Header_TotalPlayed,
  _ as GamesList_Header_TwoWeeks,
  _ as GamesList_MenuLabel_GameInfo,
  _ as GamesList_MenuLabel_RemoteDownload,
  _ as GamesList_PerfectGames_Description,
  _ as GamesList_PrivacySettings_Tooltip,
  _ as GamesList_RemoteDownload_Help,
  _ as GamesList_RemoteDownload_Info,
  _ as GamesList_RemoteDownload_LearnMore,
  _ as GamesList_RemoteDownload_NoConnection,
  _ as GamesList_RemoteDownload_NoRemoteControl,
  _ as GamesList_RemoteDownload_ReadTheFAQ,
  _ as GamesList_RemoteDownload_UninstallConfirm,
  _ as GamesList_Sort_AchievementCompletion,
  _ as GamesList_Sort_HoursPlayed,
  _ as GamesList_Sort_Name,
  _ as GamesList_Tab_AllGames,
  _ as GamesList_Tab_Followed,
  _ as GamesList_Tab_PerfectGames,
  _ as GamesList_Tab_RecentlyPlayed,
  _ as GamesList_Tab_Reviews,
  _ as GamesList_Tab_Wishlist,
  _ as GamesList_TimeRemaining,
  _ as GamesList_Uninstalling,
  _ as Images_AllYourImages,
  _ as Images_Manage,
  _ as Images_SelectImages,
  _ as Images_Upload,
  _ as Images_YourFriendsOnlyImages,
  _ as Images_YourPrivateImages,
  _ as Images_YourPublicImages,
  _ as Images_YourUnlistedImages,
  _ as Loading,
  _ as Market_GenericTitle,
  _ as Market_Item_GenericTitle,
  _ as Market_Item_Title,
  _ as Market_Search_Title,
  _ as Moderation_SubjectTypeName_ForumPost,
  _ as Paging_ShowingXtoYofZ,
  _ as Perfect_Game_Description,
  _ as Playtime_Hours,
  _ as Playtime_Minutes,
  _ as Profile_Collections,
  _ as Profile_Guides,
  _ as Profile_Images,
  _ as Profile_Screenshots,
  _ as Profile_SharedFiles_AllGames,
  _ as Profile_SharedFiles_By,
  _ as Profile_SharedFiles_FavoritedBy,
  _ as Profile_SharedFiles_GridView,
  _ as Profile_SharedFiles_ImageWallView,
  _ as Profile_SharedFiles_MostPopular,
  _ as Profile_SharedFiles_NewestFirst,
  _ as Profile_SharedFiles_NoImagesFavoritesForYou,
  _ as Profile_SharedFiles_NoImagesFavoritesSelf,
  _ as Profile_SharedFiles_NoImagesForYou,
  _ as Profile_SharedFiles_NoImagesSelf,
  _ as Profile_SharedFiles_NoScreenshotsFavoritesForYou,
  _ as Profile_SharedFiles_NoScreenshotsFavoritesSelf,
  _ as Profile_SharedFiles_NoScreenshotsForYou,
  _ as Profile_SharedFiles_NoScreenshotsSelf,
  _ as Profile_SharedFiles_NoScreenshotsThisVisibility,
  _ as Profile_SharedFiles_NoVideosFavoritesForYou,
  _ as Profile_SharedFiles_NoVideosFavoritesSelf,
  _ as Profile_SharedFiles_NoVideosForYou,
  _ as Profile_SharedFiles_NoVideosSelf,
  _ as Profile_SharedFiles_OldestFirst,
  _ as Profile_SharedFiles_SelectAGame,
  _ as Profile_Videos,
  _ as Profile_Workshop_Items,
  _ as Profile_YourWorkshop,
  _ as Screenshots_AllYourScreenshots,
  _ as Screenshots_AreYouSureDelete,
  _ as Screenshots_AreYouSurePrivacyChange,
  _ as Screenshots_Cancel,
  _ as Screenshots_Continue,
  _ as Screenshots_Delete,
  _ as Screenshots_DeleteScreenshots,
  _ as Screenshots_Done,
  _ as Screenshots_Instructions1,
  _ as Screenshots_Instructions2,
  _ as Screenshots_Location,
  _ as Screenshots_MakeFriendsOnly,
  _ as Screenshots_MakePrivate,
  _ as Screenshots_MakePublic,
  _ as Screenshots_MakeUnlisted,
  _ as Screenshots_Manage,
  _ as Screenshots_NoneSelected,
  _ as Screenshots_OK,
  _ as Screenshots_Oops,
  _ as Screenshots_SelectAll,
  _ as Screenshots_SelectScreenshots,
  _ as Screenshots_SelectScreenshotsToDelete,
  _ as Screenshots_SteamHasThem,
  _ as Screenshots_UpdatePrivacy,
  _ as Screenshots_Upload,
  _ as Screenshots_Viewing,
  _ as Screenshots_VisUpdateFailed,
  _ as Screenshots_VisUpdateFailedMessage,
  _ as Screenshots_YourFriendsOnlyScreenshots,
  _ as Screenshots_YourPrivateScreenshots,
  _ as Screenshots_YourPublicScreenshots,
  _ as Screenshots_YourUnlistedScreenshots,
  _ as SharedFiles_AddSpoilerTag,
  _ as SharedFiles_AdminTags,
  _ as SharedFiles_And_N_More,
  _ as SharedFiles_BrowseGuide_createNewBtnLabel,
  _ as SharedFiles_BrowseGuide_subtitle_nolink,
  _ as SharedFiles_Browse_GuideHome,
  _ as SharedFiles_Browse_MyFiles_Favorites,
  _ as SharedFiles_Browse_MyFiles_Items,
  _ as SharedFiles_Browse_MyFiles_Played,
  _ as SharedFiles_Browse_MyFiles_Sort_Alpha,
  _ as SharedFiles_Browse_MyFiles_Sort_CreationOrder,
  _ as SharedFiles_Browse_MyFiles_Sort_Favorited,
  _ as SharedFiles_Browse_MyFiles_Sort_LastUpdated,
  _ as SharedFiles_Browse_MyFiles_Sort_Subscribed,
  _ as SharedFiles_Browse_MyFiles_Subscriptions,
  _ as SharedFiles_ByAuthor,
  _ as SharedFiles_CreateGuide,
  _ as SharedFiles_DeveloperComments,
  _ as SharedFiles_Dota2_IntegratedGuide,
  _ as SharedFiles_Dota2_IntegratedGuide_Desc,
  _ as SharedFiles_Favorites,
  _ as SharedFiles_Favorites_NowUnsubscribed,
  _ as SharedFiles_Favorites_Subscribed,
  _ as SharedFiles_FilterByGame,
  _ as SharedFiles_Guide_Comments,
  _ as SharedFiles_Guide_Index,
  _ as SharedFiles_Guide_Overview,
  _ as SharedFiles_ItemDownload,
  _ as SharedFiles_ItemEditText_ErrorNoTitle,
  _ as SharedFiles_ItemEditText_Text_Caption,
  _ as SharedFiles_Item_Edit_Link,
  _ as SharedFiles_ManageGuide_AddContributor,
  _ as SharedFiles_ManageGuide_AddSection,
  _ as SharedFiles_ManageGuide_Cancel,
  _ as SharedFiles_ManageGuide_Contents,
  _ as SharedFiles_ManageGuide_Contents_Desc,
  _ as SharedFiles_ManageGuide_Contributors,
  _ as SharedFiles_ManageGuide_Contributors_Desc,
  _ as SharedFiles_ManageGuide_DeleteThisSection,
  _ as SharedFiles_ManageGuide_EditSubSection,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Delete,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Desc,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Insert,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Changes,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Edit,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Preview,
  _ as SharedFiles_ManageGuide_EditThisSection,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_Layout,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutInline,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutLeft,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutRight,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_Size,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeFull,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeOriginal,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeThumb,
  _ as SharedFiles_ManageGuide_Images,
  _ as SharedFiles_ManageGuide_Images_Desc,
  _ as SharedFiles_ManageGuide_InsertImage,
  _ as SharedFiles_ManageGuide_InsertYouTubeVideo,
  _ as SharedFiles_ManageGuide_NoContributors,
  _ as SharedFiles_ManageGuide_NoPreviewImages,
  _ as SharedFiles_ManageGuide_NoSectionTitle,
  _ as SharedFiles_ManageGuide_NoSubSections,
  _ as SharedFiles_ManageGuide_Preview,
  _ as SharedFiles_ManageGuide_PromptYouTubeUrl,
  _ as SharedFiles_ManageGuide_RemoveSectionConfirm,
  _ as SharedFiles_ManageGuide_Required,
  _ as SharedFiles_ManageGuide_Save,
  _ as SharedFiles_ManageGuide_Screenshots,
  _ as SharedFiles_ManageGuide_SubImages,
  _ as SharedFiles_ManageGuide_SubScreenshots,
  _ as SharedFiles_ManageGuide_SubSectionContentChanged,
  _ as SharedFiles_ManageGuide_SubSectionContentChanged_CancelConfirm,
  _ as SharedFiles_ManageGuide_SubSectionContentSaved,
  _ as SharedFiles_ManageGuide_SubSectionContents,
  _ as SharedFiles_ManageGuide_SubSectionTitle,
  _ as SharedFiles_ManageGuide_SubVideos,
  _ as SharedFiles_ManageGuide_Videos,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Full,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Left,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Right,
  _ as SharedFiles_Media_ViewAppFanArt,
  _ as SharedFiles_Media_ViewAppScreenshots,
  _ as SharedFiles_Media_ViewAppVideos,
  _ as SharedFiles_MustOwnAppToCreateGuide,
  _ as SharedFiles_NoGuides_Desc1,
  _ as SharedFiles_NoGuides_Desc2,
  _ as SharedFiles_NoGuides_Title,
  _ as SharedFiles_OwnerControl_BackGuide,
  _ as SharedFiles_OwnerControl_EditCaption,
  _ as SharedFiles_PublicComments,
  _ as SharedFiles_RemoveSelfTag_Tooltip,
  _ as SharedFiles_RemoveSpoilerTag,
  _ as SharedFiles_SaveSubscribedToCollection_Btn,
  _ as SharedFiles_SaveSubscribedToCollection_Desc,
  _ as SharedFiles_SaveSubscribedToCollection_Existing,
  _ as SharedFiles_SaveSubscribedToCollection_ExistingDesc,
  _ as SharedFiles_SaveSubscribedToCollection_New,
  _ as SharedFiles_SaveSubscribedToCollection_NewDesc,
  _ as SharedFiles_SaveSubscribedToCollection_NoExistingCollections,
  _ as SharedFiles_SaveSubscribedToCollection_Title,
  _ as SharedFiles_SearchedForFileType_IntegratedGuide,
  _ as SharedFiles_SearchedForFileType_WebGuide,
  _ as SharedFiles_SharedFiles_Collections,
  _ as SharedFiles_SharedFiles_Guides,
  _ as SharedFiles_SharedFiles_Items,
  _ as SharedFiles_SpoilerTagInstructions,
  _ as SharedFiles_SpoilerTagsExpire,
  _ as SharedFiles_Stats_TaggedUsers,
  _ as SharedFiles_Stats_TaggedWorkshopItems,
  _ as SharedFiles_Subscription_NowUnsubscribed,
  _ as SharedFiles_Subscription_Subscribed,
  _ as SharedFiles_Subscriptions,
  _ as SharedFiles_Tab_Merchandise,
  _ as SharedFiles_Tags,
  _ as SharedFiles_TagsSearch,
  _ as SharedFiles_UnsubscribeAll_Btn,
  _ as SharedFiles_UnsubscribeAll_Confirm_App_Desc,
  _ as SharedFiles_UnsubscribeAll_Confirm_Desc,
  _ as SharedFiles_UnsubscribeAll_Confirm_Title,
  _ as SharedFiles_UserList_BrowsePaging,
  _ as SharedFiles_UserList_LastUpdated,
  _ as SharedFiles_WaitingForIntegratedGuide,
  _ as SharedFiles_WorkshopItemsTagged,
  _ as Videos_AccessYourYouTubeVideos,
  _ as Videos_AddDone,
  _ as Videos_AddFromYouTube,
  _ as Videos_AddNote2,
  _ as Videos_AddNote4,
  _ as Videos_AddStep1,
  _ as Videos_AddStep2,
  _ as Videos_AddStep2Note,
  _ as Videos_AddStep3,
  _ as Videos_AddStep4,
  _ as Videos_AddVideo,
  _ as Videos_AllYourVideos,
  _ as Videos_AvailCountPlural,
  _ as Videos_AvailCountSingular,
  _ as Videos_Cancel,
  _ as Videos_ChangeAccount,
  _ as Videos_ClickHereToChange,
  _ as Videos_ContinueWithAcct,
  _ as Videos_CurrentlyLinkedMsg,
  _ as Videos_CurrentlyLinkedTo,
  _ as Videos_Desc1,
  _ as Videos_Desc2,
  _ as Videos_Desc3,
  _ as Videos_IssuesAccessing,
  _ as Videos_LinkYouTubeAcct,
  _ as Videos_Manage,
  _ as Videos_NoVideosMsg1,
  _ as Videos_NoVideosMsg2,
  _ as Videos_NowOnSteam,
  _ as Videos_OptionNoneOther,
  _ as Videos_OtherUnlisted,
  _ as Videos_Privacy,
  _ as Videos_Refresh,
  _ as Videos_SelectVideos,
  _ as Videos_ShareDescription,
  _ as Videos_SuccessfullyAddedPlural,
  _ as Videos_SuccessfullyAddedSingular,
  _ as Videos_SuccessfullyLinkedYouTube,
  _ as Videos_UnlinkAcct,
  _ as Videos_UnlinkButton,
  _ as Videos_UnlinkConfirmText,
  _ as Videos_UnlinkToAddAnother,
  _ as Videos_UnlinkYouTubeAcct,
  _ as Videos_YourFriendsOnlyVideos,
  _ as Videos_YourPrivateVideos,
  _ as Videos_YourPublicVideos,
  _ as Videos_YourUnlistedVideos,
  _ as Videos_YoutubeTermsLink_AuthorizedData,
  _ as Videos_YoutubeTermsLink_PrivacyPolicy,
  _ as Videos_YoutubeTermsLink_SecuritySettings,
  _ as Videos_YoutubeTermsLink_TermsOfService,
  _ as Videos_YoutubeTerms_1,
  _ as Videos_YoutubeTerms_2,
  _ as Videos_YoutubeTerms_3,
  _ as Videos_YoutubeTerms_4,
  _ as Workshop_BrowseBy,
  _ as Workshop_BrowsePaging,
  _ as Workshop_DeveloperThreadDesc,
  _ as Workshop_DeveloperThreadDisclaimerText,
  _ as Workshop_HasLinkedItems,
  _ as Workshop_ImageSize,
  _ as Workshop_ItemModalViewCountDetails,
  _ as Workshop_ItemModalViewDetails,
  _ as Workshop_Link_LegalAgreement,
  _ as Workshop_Link_PaymentInfo,
  _ as Workshop_NoItems,
  _ as Workshop_PaymentInfo_NotCreated,
  _ as Workshop_PaymentInfo_Rejected,
  _ as Workshop_SplitsAcceptTheseDesc1,
  _ as Workshop_SplitsAcceptTheseDesc2,
  _ as Workshop_SplitsPercentage,
  _ as Workshop_Subscribe_IntegratedGuide,
  _ as Workshop_ViewYourRevenue,
  _ as Workshop_ViewYourRevenue_desc,
  _ as community_errorpage_title,
  _ as community_title,
  _ as default,
  _ as empty_no_comma_following,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_accessibility,
  _ as footer_cookies,
  _ as footer_geodata_notice,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_privacy_policy,
  _ as footer_refunds,
  _ as footer_ssa,
  _ as moderatedcontent_description,
  _ as moderation_claim_n_reports_on_m_subjects,
  _ as moderation_claim_report_count,
  _ as moderation_claim_report_count_Plural,
  _ as moderation_claim_subject_count,
  _ as moderation_claim_subject_count_Plural,
  _ as moderation_forumpost_summary,
  _ as moderation_forumpost_summary_reports_fragment,
  _ as moderation_forumpost_summary_reports_fragment_Plural,
  _ as moderation_forumpost_summary_subjects_fragment,
  _ as moderation_forumpost_summary_subjects_fragment_Plural,
  _ as profile_error_profilenotfound,
  _ as profile_games_list,
  _ as profile_games_list_error_loadfailed,
  _ as profile_games_list_title,
  _ as profiletabs_communitymessages,
  _ as profiletabs_currentbans,
  _ as profiletabs_moderatedcontent,
  _ as profiletabs_reportedcontent,
  _ as reportedcontent_description,
  _ as reportedcontent_lastupdated,
};
