var _ = `dutch`,
  _ = `Op communitymarkt bekijken`,
  _ = `Mijn vermelding bekijken`,
  _ = `Vanaf: %1$s`,
  _ = `Volume: %1$s verkocht in de afgelopen 24 uur`,
  _ = `Verkopen`,
  _ = `Tags: `,
  _ = `Ruilbescherming van kracht`,
  _ = `Voorwerpen met ruilbescherming kun je niet aanpassen, verbruiken of overdragen.`,
  _ = `%1$s: %2$s`,
  _ = `Op de markt`,
  _ = `Zolang dit voorwerp te koop wordt aangeboden, kun je het niet aanpassen of verbruiken.`,
  _ = `Dit voorwerp is waard: %1$s`,
  _ = `%1$s edelstenen`,
  _ = `In edelstenen omzetten ...`,
  _ = `Dit voorwerp kan in edelstenen worden omgezet om booster packs mee te maken. <1>Meer informatie</1>.`,
  _ = `Accessoires`,
  _ = {
    language: _,
    SellOnMarket_View: _,
    SellOnMarket_ViewListing: _,
    SellOnMarket_LowestPrice: _,
    SellOnMarket_Volume: _,
    SellOnMarket_SellThisItem: _,
    ItemDescription_Tags: _,
    ItemDescription_TradeProtected: _,
    ItemDescription_TradeProtectedTooltip: _,
    ItemDescription_AssetPropertyLabelColonValue: _,
    ItemDescription_ListedItem: _,
    ItemDescription_ListedItemTooltip: _,
    ItemDescription_ThisItemIsWorthGems: _,
    ItemDescription_XGems: _,
    ItemDescription_TurnIntoGemsButton: _,
    ItemDescription_GemDescription: _,
    ItemDescription_AccessoriesList_Title: _,
  };
export {
  _ as ItemDescription_AccessoriesList_Title,
  _ as ItemDescription_AssetPropertyLabelColonValue,
  _ as ItemDescription_GemDescription,
  _ as ItemDescription_ListedItem,
  _ as ItemDescription_ListedItemTooltip,
  _ as ItemDescription_Tags,
  _ as ItemDescription_ThisItemIsWorthGems,
  _ as ItemDescription_TradeProtected,
  _ as ItemDescription_TradeProtectedTooltip,
  _ as ItemDescription_TurnIntoGemsButton,
  _ as ItemDescription_XGems,
  _ as SellOnMarket_LowestPrice,
  _ as SellOnMarket_SellThisItem,
  _ as SellOnMarket_View,
  _ as SellOnMarket_ViewListing,
  _ as SellOnMarket_Volume,
  _ as default,
  _ as language,
};
