var _ = `Moderator`,
  _ = `Veileder`,
  _ = `Valve-admin`,
  _ = `Ukjent`,
  _ = `Statistikk`,
  _ = `Metadataen for denne samtalerapporten kunne ikke hentes (feil: %1$s)`,
  _ = `i %1$s`,
  _ = `Venner:`,
  _ = `Samtalevarighet før rapportering:`,
  _ = `Senderens IP:`,
  _ = `Første samtalemelding (anslått):`,
  _ = `Rapportert melding`,
  _ = `Veksle BBCode`,
  _ = `Bilde fjernet`,
  _ = `Synlig når man holder over`,
  _ = `Rapportert:`,
  _ = `Internettleverandør først brukt i denne samtalen for %1$s siden`,
  _ = `Nylige samtalerom:`,
  _ = `Gruppenavn:`,
  _ = `Romnavn:`,
  _ = `Nylige samtalepartnere:`,
  _ = `Rapporterte meldinger sendt av %1$s`,
  _ = `Rapporterte gruppemeldinger sendt av %1$s`,
  _ = `Standard`,
  _ = `Rapporter for samtalegruppen %1$s`,
  _ = `Medlemmer:`,
  _ = `Rom:`,
  _ = `DEAKTIVERT`,
  _ = `Slagord:`,
  _ = `Gruppetype:`,
  _ = `Eier:`,
  _ = `Privat ad hoc (gruppe-ID %1$s)`,
  _ = `Applikasjon opprettet (app-ID %1$s)`,
  _ = `Offisiell samfunnsgruppe for applikasjon (klan-ID %1$s)`,
  _ = `Offentlig – klan: %1$s (klan-ID %2$s)`,
  _ = `Privat – klan: %1$s (klan-ID %2$s)`,
  _ = `%1$s valgt`,
  _ = `Alle uløste`,
  _ = `Ingen`,
  _ = `Frikjenn`,
  _ = `Frikjenn (%1$s)`,
  _ = `Sanksjoner …`,
  _ = `Sanksjoner … (%1$s)`,
  _ = `Eskaler …`,
  _ = `Eskaler … (%1$s)`,
  _ = `Bekreft sanksjon`,
  _ = `Bekreft sanksjon (%1$s)`,
  _ = `Lås tråd`,
  _ = `Lås tråd (%1$s)`,
  _ = `Lås opp tråd`,
  _ = `Lås opp tråd (%1$s)`,
  _ = `Oppretthold moderering`,
  _ = `Oppretthold moderering (%1$s)`,
  _ = `Marker som mistenkelig`,
  _ = `Marker som mistenkelig (%1$s)`,
  _ = `Ukjent`,
  _ = `Ditt moderatornivå: %1$s`,
  _ = `Ta saker`,
  _ = `Ta på deg flere?`,
  _ = `Du har ikke flere rapporter å løse. Vil du ta på deg flere?`,
  _ = `Ta parti med høyeste prioritet:`,
  _ = `Ta (%1$s)`,
  _ = `Ta eskalerte (%1$s)`,
  _ = `Ta kun for Valve (%1$s)`,
  _ = `Ta …`,
  _ = `Slipp alle`,
  _ = `Neste`,
  _ = `Moderer`,
  _ = `OK`,
  _ = `Velg nivå å eskalere til:`,
  _ = `Eskaler %1$s sak`,
  _ = `Eskaler %1$s saker`,
  _ = `Velg eskaleringsårsak`,
  _ = `Årsak:`,
  _ = `Eskaler`,
  _ = `Enhver moderator`,
  _ = `Veileder`,
  _ = `Valve`,
  _ = `Kun Valve`,
  _ = `Veileder kreves`,
  _ = `Eskaleringsmerknad:`,
  _ = `Metadataen knyttet til denne samtalerapporten er blitt slettet på grunn av alder. Den beholdes kun i omtrent 21 dager.`,
  _ = `Denne samtaleloggen kan utvides med ytterligere meldinger sendt etter rapporten i %1$s`,
  _ = `Fjern rapportert innhold`,
  _ = `Ommerk det rapporterte innholdet`,
  _ = `Lås kontoen fra å legge ut mistenkelig innhold`,
  _ = `Legg til trakasseringsanmerkning`,
  _ = `Ukjent (%1$s)`,
  _ = `Fjern og advar bruker`,
  _ = `Fjern og utesteng fra sentral`,
  _ = `Fjern og kast ut av gruppe`,
  _ = `Sanksjonert`,
  _ = `Frikjent`,
  _ = `%1$s rapporterer på %2$s meldinger fra «%3$s»`,
  _ = `%1$s rapporterer på %2$s meldinger i «%3$s»`,
  _ = `(1 sak)`,
  _ = `(%1$s saker)`,
  _ = `Alle innlegg slettet`,
  _ = `Innlegg i de siste %1$s dagene slettet`,
  _ = `Permanent utestengt fra samfunnet`,
  _ = `Utestengt fra samfunnet i %1$s dager`,
  _ = `Rapportert innhold slettet`,
  _ = `Permanent utestengt fra sentralen`,
  _ = `Utestengt fra sentralen i %1$s dager`,
  _ = `Markert som mistenkelig`,
  _ = `Ommerket`,
  _ = `Permanent utestengt fra byttehandel`,
  _ = `Utestengt fra byttehandel i %1$s dager`,
  _ = `Kastet ut fra gruppe`,
  _ = `Ukjent`,
  _ = `Oppgi sakskoden fra TicketMaster som denne brukeren sendte inn.`,
  _ = `Sakskode:`,
  _ = `Klag`,
  _ = `Avbryt`,
  _ = `Lagre`,
  _ = `Sakskode: `,
  _ = `Frikjent ved første moderering`,
  _ = `Sanksjonert ved første moderering`,
  _ = `Dette emnet har et vedlagt byttetilbud`,
  _ = `Ingen oppføringer`,
  _ = `Feil: Kunne ikke laste revisjonslogg.`,
  _ = `Årsaker:`,
  _ = `%1$s (%2$s)`,
  _ = `Ingen rapporter`,
  _ = `Frikjent %1$s`,
  _ = `Løst %1$s`,
  _ = `Bestridt %1$s`,
  _ = `Bestridelse løst %1$s`,
  _ = `Trykk for å velge …`,
  _ = `Moderer`,
  _ = `Rapporterte saker`,
  _ = `Allerede bestridt`,
  _ = `Alle sakstyper`,
  _ = `%1$s uløst, %1$s bestridt`,
  _ = ``,
  _ = {
    moderation_moderatorlevel_any: _,
    moderation_moderatorlevel_supervisor: _,
    moderation_moderatorlevel_valveadmin: _,
    moderation_moderatorlevel_unknown: _,
    moderation_statistics: _,
    moderation_chatmetadataerror: _,
    moderation_friendsforduration: _,
    moderation_friends_label: _,
    moderation_chatduration_label: _,
    moderation_senderip_label: _,
    moderation_firstchatted_label: _,
    moderation_reported_message: _,
    moderation_toggle_bbcode: _,
    moderation_image_removed: _,
    moderation_image_obscured: _,
    moderation_reported_time_label: _,
    moderation_network_firstused_time: _,
    moderation_recentchatrooms_label: _,
    moderation_groupname_label: _,
    moderation_roomname_label: _,
    moderation_recentchatpartners_label: _,
    moderation_chat_reportedmessagesfrom: _,
    moderation_chatgroup_reportedmessagesfrom: _,
    moderation_chatgroup_defaultroom: _,
    moderation_chatgroup_reports: _,
    moderation_chatgroup_membercount: _,
    moderation_chatgroup_chatrooms: _,
    moderation_chatgroup_disabled: _,
    moderation_chatgroup_tagline: _,
    moderation_chatgroup_type: _,
    moderation_chatgroup_owner: _,
    moderation_chatgroup_type_privateadhoc: _,
    moderation_chatgroup_type_app: _,
    moderation_chatgroup_type_clanapp: _,
    moderation_chatgroup_type_clanpublic: _,
    moderation_chatgroup_type_clanprivate: _,
    moderation_num_selected: _,
    moderation_select_all_unresolved: _,
    moderation_select_none: _,
    moderation_actions_acquit: _,
    moderation_actions_acquit_multiple: _,
    moderation_actions_sanction: _,
    moderation_actions_sanction_multiple: _,
    moderation_actions_escalate: _,
    moderation_actions_escalate_multiple: _,
    moderation_actions_confirmsanction: _,
    moderation_actions_confirmsanction_multiple: _,
    moderation_actions_lockthread: _,
    moderation_actions_lockthread_multiple: _,
    moderation_actions_unlockthread: _,
    moderation_actions_unlockthread_multiple: _,
    moderation_actions_sustain: _,
    moderation_actions_sustain_multiple: _,
    moderation_actions_suspicious: _,
    moderation_actions_suspicious_multiple: _,
    moderation_actions_unknown: _,
    moderation_moderator_level: _,
    moderation_claim_subjects: _,
    moderation_claim_more: _,
    moderation_claim_more_desc: _,
    moderation_claim_batch_desc: _,
    moderation_claim_amount: _,
    moderation_claim_escalated_amount: _,
    moderation_claim_valve_amount: _,
    moderation_claim_reports: _,
    moderation_release_reports: _,
    moderation_moderatoractions_next: _,
    moderation_moderatoractions_moderate: _,
    moderation_moderatoractions_ok: `OK`,
    moderation_escalation_description: _,
    moderation_escalation_title: _,
    moderation_escalation_title_Plural: _,
    moderation_escalation_reason_select: _,
    moderation_escalation_reason_label: _,
    moderation_escalation_escalate: _,
    moderation_escalationlevel_any: _,
    moderation_escalationlevel_supervisor: _,
    moderation_escalationlevel_valve: _,
    moderation_escalationlevel_valve_desc: _,
    moderation_escalationlevel_supervisor_desc: _,
    moderation_escalation_escalationnote: _,
    moderation_chatmetadata_deleted: _,
    moderation_chatmetadata_futurelogcollection: _,
    moderation_resolutionaction_removed: _,
    moderation_resolutionaction_relabelled: _,
    moderation_resolutionaction_suspicious: _,
    moderation_resolutionaction_harassmentstrike: _,
    moderation_resolutionaction_unknownvalue: _,
    moderation_resolutionaction_removeandwarn: _,
    moderation_resolutionaction_removeandban: _,
    moderation_resolutionaction_removeandkick: _,
    moderation_resolutionstatus_sanctioned: _,
    moderation_resolutionstatus_acquitted: _,
    moderation_subjectgroupsummary_chatmsg: _,
    moderation_subjectgroupsummary_chatgroup: _,
    subject_count: _,
    subject_count_Plural: _,
    moderation_sanction_commenthistorydeleted_forever: _,
    moderation_sanction_commenthistorydeleted: _,
    moderation_sanction_communitybanned_forever: _,
    moderation_sanction_communitybanned: _,
    moderation_sanction_deleted: _,
    moderation_sanction_hubbanned_forever: _,
    moderation_sanction_hubbanned: _,
    moderation_sanction_markassuspicious: _,
    moderation_sanction_relabelled: _,
    moderation_sanction_tradebanned_forever: _,
    moderation_sanction_tradebanned: _,
    moderation_sanction_kickedfromgroup: _,
    moderation_sanction_unknown: _,
    moderation_ownerdispute_description: _,
    moderation_ownerdispute_ticketmastercode: _,
    moderation_ownerdispute_dispute: _,
    moderation_ownerdispute_cancel: _,
    moderation_editownerdisputedetails_save: _,
    moderation_editownerdisputedetails_label: _,
    originalresolution_acquitted: _,
    originalresolution_sanctioned: _,
    has_trade_offer: _,
    subjectauditlog_noentries: _,
    subjectauditlog_error: _,
    reasonlist_title: _,
    reasonlist_reasonwithcount: _,
    contentreportslist_noreports: _,
    contentreportslist_acquitted_at: _,
    contentreportslist_resolved_at: _,
    contentreportslist_disputed_at: _,
    contentreportslist_dispute_resolved_at: _,
    commentsanctiondialog_selectreason: _,
    commentsanctiondialog_moderate: _,
    reportedsubjectlist_header: _,
    moderation_already_owner_disputed: _,
    moderationstats_alltypes: _,
    forumsubjectlist_subjectreportsummary: _,
    empty_no_trailing_comma: ``,
  };
export {
  _ as commentsanctiondialog_moderate,
  _ as commentsanctiondialog_selectreason,
  _ as contentreportslist_acquitted_at,
  _ as contentreportslist_dispute_resolved_at,
  _ as contentreportslist_disputed_at,
  _ as contentreportslist_noreports,
  _ as contentreportslist_resolved_at,
  _ as default,
  _ as empty_no_trailing_comma,
  _ as forumsubjectlist_subjectreportsummary,
  _ as has_trade_offer,
  _ as moderation_actions_acquit,
  _ as moderation_actions_acquit_multiple,
  _ as moderation_actions_confirmsanction,
  _ as moderation_actions_confirmsanction_multiple,
  _ as moderation_actions_escalate,
  _ as moderation_actions_escalate_multiple,
  _ as moderation_actions_lockthread,
  _ as moderation_actions_lockthread_multiple,
  _ as moderation_actions_sanction,
  _ as moderation_actions_sanction_multiple,
  _ as moderation_actions_suspicious,
  _ as moderation_actions_suspicious_multiple,
  _ as moderation_actions_sustain,
  _ as moderation_actions_sustain_multiple,
  _ as moderation_actions_unknown,
  _ as moderation_actions_unlockthread,
  _ as moderation_actions_unlockthread_multiple,
  _ as moderation_already_owner_disputed,
  _ as moderation_chat_reportedmessagesfrom,
  _ as moderation_chatduration_label,
  _ as moderation_chatgroup_chatrooms,
  _ as moderation_chatgroup_defaultroom,
  _ as moderation_chatgroup_disabled,
  _ as moderation_chatgroup_membercount,
  _ as moderation_chatgroup_owner,
  _ as moderation_chatgroup_reportedmessagesfrom,
  _ as moderation_chatgroup_reports,
  _ as moderation_chatgroup_tagline,
  _ as moderation_chatgroup_type,
  _ as moderation_chatgroup_type_app,
  _ as moderation_chatgroup_type_clanapp,
  _ as moderation_chatgroup_type_clanprivate,
  _ as moderation_chatgroup_type_clanpublic,
  _ as moderation_chatgroup_type_privateadhoc,
  _ as moderation_chatmetadata_deleted,
  _ as moderation_chatmetadata_futurelogcollection,
  _ as moderation_chatmetadataerror,
  _ as moderation_claim_amount,
  _ as moderation_claim_batch_desc,
  _ as moderation_claim_escalated_amount,
  _ as moderation_claim_more,
  _ as moderation_claim_more_desc,
  _ as moderation_claim_reports,
  _ as moderation_claim_subjects,
  _ as moderation_claim_valve_amount,
  _ as moderation_editownerdisputedetails_label,
  _ as moderation_editownerdisputedetails_save,
  _ as moderation_escalation_description,
  _ as moderation_escalation_escalate,
  _ as moderation_escalation_escalationnote,
  _ as moderation_escalation_reason_label,
  _ as moderation_escalation_reason_select,
  _ as moderation_escalation_title,
  _ as moderation_escalation_title_Plural,
  _ as moderation_escalationlevel_any,
  _ as moderation_escalationlevel_supervisor,
  _ as moderation_escalationlevel_supervisor_desc,
  _ as moderation_escalationlevel_valve,
  _ as moderation_escalationlevel_valve_desc,
  _ as moderation_firstchatted_label,
  _ as moderation_friends_label,
  _ as moderation_friendsforduration,
  _ as moderation_groupname_label,
  _ as moderation_image_obscured,
  _ as moderation_image_removed,
  _ as moderation_moderator_level,
  _ as moderation_moderatoractions_moderate,
  _ as moderation_moderatoractions_next,
  _ as moderation_moderatoractions_ok,
  _ as moderation_moderatorlevel_any,
  _ as moderation_moderatorlevel_supervisor,
  _ as moderation_moderatorlevel_unknown,
  _ as moderation_moderatorlevel_valveadmin,
  _ as moderation_network_firstused_time,
  _ as moderation_num_selected,
  _ as moderation_ownerdispute_cancel,
  _ as moderation_ownerdispute_description,
  _ as moderation_ownerdispute_dispute,
  _ as moderation_ownerdispute_ticketmastercode,
  _ as moderation_recentchatpartners_label,
  _ as moderation_recentchatrooms_label,
  _ as moderation_release_reports,
  _ as moderation_reported_message,
  _ as moderation_reported_time_label,
  _ as moderation_resolutionaction_harassmentstrike,
  _ as moderation_resolutionaction_relabelled,
  _ as moderation_resolutionaction_removeandban,
  _ as moderation_resolutionaction_removeandkick,
  _ as moderation_resolutionaction_removeandwarn,
  _ as moderation_resolutionaction_removed,
  _ as moderation_resolutionaction_suspicious,
  _ as moderation_resolutionaction_unknownvalue,
  _ as moderation_resolutionstatus_acquitted,
  _ as moderation_resolutionstatus_sanctioned,
  _ as moderation_roomname_label,
  _ as moderation_sanction_commenthistorydeleted,
  _ as moderation_sanction_commenthistorydeleted_forever,
  _ as moderation_sanction_communitybanned,
  _ as moderation_sanction_communitybanned_forever,
  _ as moderation_sanction_deleted,
  _ as moderation_sanction_hubbanned,
  _ as moderation_sanction_hubbanned_forever,
  _ as moderation_sanction_kickedfromgroup,
  _ as moderation_sanction_markassuspicious,
  _ as moderation_sanction_relabelled,
  _ as moderation_sanction_tradebanned,
  _ as moderation_sanction_tradebanned_forever,
  _ as moderation_sanction_unknown,
  _ as moderation_select_all_unresolved,
  _ as moderation_select_none,
  _ as moderation_senderip_label,
  _ as moderation_statistics,
  _ as moderation_subjectgroupsummary_chatgroup,
  _ as moderation_subjectgroupsummary_chatmsg,
  _ as moderation_toggle_bbcode,
  _ as moderationstats_alltypes,
  _ as originalresolution_acquitted,
  _ as originalresolution_sanctioned,
  _ as reasonlist_reasonwithcount,
  _ as reasonlist_title,
  _ as reportedsubjectlist_header,
  _ as subject_count,
  _ as subject_count_Plural,
  _ as subjectauditlog_error,
  _ as subjectauditlog_noentries,
};
