var _ = `schinese`,
  _ = `在社区市场中查看`,
  _ = `查看我的上架物品`,
  _ = `起始价格：%1$s`,
  _ = `数量：在过去 24 小时内卖出了 %1$s 件`,
  _ = `出售`,
  _ = `标签：`,
  _ = `受到交易保护`,
  _ = `处于交易保护状态的物品无法被修改、消耗或转移。`,
  _ = `%1$s：%2$s`,
  _ = `在市场中`,
  _ = `此物品上架出售期间，您无法对其进行修改或使用。`,
  _ = `此物品价值：%1$s`,
  _ = `%1$s 颗宝石`,
  _ = `转换成宝石…`,
  _ = `此物品可以分解成用于制作补充包的宝石。<1>点击此处了解更多</1>`,
  _ = `配件`,
  _ = {
    language: _,
    SellOnMarket_View: _,
    SellOnMarket_ViewListing: _,
    SellOnMarket_LowestPrice: _,
    SellOnMarket_Volume: _,
    SellOnMarket_SellThisItem: _,
    ItemDescription_Tags: _,
    ItemDescription_TradeProtected: _,
    ItemDescription_TradeProtectedTooltip: _,
    ItemDescription_AssetPropertyLabelColonValue: _,
    ItemDescription_ListedItem: _,
    ItemDescription_ListedItemTooltip: _,
    ItemDescription_ThisItemIsWorthGems: _,
    ItemDescription_XGems: _,
    ItemDescription_TurnIntoGemsButton: _,
    ItemDescription_GemDescription: _,
    ItemDescription_AccessoriesList_Title: _,
  };
export {
  _ as ItemDescription_AccessoriesList_Title,
  _ as ItemDescription_AssetPropertyLabelColonValue,
  _ as ItemDescription_GemDescription,
  _ as ItemDescription_ListedItem,
  _ as ItemDescription_ListedItemTooltip,
  _ as ItemDescription_Tags,
  _ as ItemDescription_ThisItemIsWorthGems,
  _ as ItemDescription_TradeProtected,
  _ as ItemDescription_TradeProtectedTooltip,
  _ as ItemDescription_TurnIntoGemsButton,
  _ as ItemDescription_XGems,
  _ as SellOnMarket_LowestPrice,
  _ as SellOnMarket_SellThisItem,
  _ as SellOnMarket_View,
  _ as SellOnMarket_ViewListing,
  _ as SellOnMarket_Volume,
  _ as default,
  _ as language,
};
