var _ = `Tartalomjelentések`,
  _ = `Általad beküldve`,
  _ = `A tartalmaddal kapcsolatban`,
  _ = `Ez a tartalom nem tűnik illegálisnak, vagy a Steam szolgáltatási feltételeit megsértőnek.`,
  _ = `Ha úgy gondolod, hogy tévedés történt, vitathatod ezt a döntést.`,
  _ = `Vitatott: moderálásra vár`,
  _ = `Kommunikáció blokkolva`,
  _ = `%1$s – %2$s`,
  _ = `Indoklás`,
  _ = `Láthatósági korlátozás`,
  _ = `A döntés meghozatalakor figyelembe vett tények és körülmények`,
  _ = `A döntés alapja`,
  _ = `Figyelembe vett jogalap`,
  _ = `Hivatkozás szerződéses okokra`,
  _ = `Annak magyarázata, hogy a tartalom miért tekinthető illegálisnak ezen okok miatt`,
  _ = `Tartalomtípus`,
  _ = `Információforrás`,
  _ = `Automatizált eszközökkel észlelték/azonosították a tartalmat?`,
  _ = `A döntést automatizált eszközök segítségével hozták meg?`,
  _ = `Illegális tartalom`,
  _ = `A Steamen nem engedélyezett olyan tartalom, amely jogellenes, bűncselekménynek minősülő magatartást valósít meg, polgári jogi felelősséget von maga után, vagy bármilyen törvényt sért.`,
  _ = `A tartalom nem egyeztethető össze az általános szerződési feltételekkel`,
  _ = `A Steamen található tartalmaknak meg kell felelniük a %1$s és a %2$s feltételeinek.`,
  _ = `Steam online viselkedési szabályzat`,
  _ = `Steam előfizetői szerződés`,
  _ = `Felhasználói jelentés`,
  _ = `Egyik sem`,
  _ = `Igen`,
  _ = `Teljesen automatizált`,
  _ = `Részben automatizált`,
  _ = `Tartalom elrejtve`,
  _ = `Tartalommal vagy fiókokkal kapcsolatos döntések meghozatalakor figyelembe vesszük a kérdéses tartalmat, a kapcsolódó fiókadatokat, a jelentési mechanizmusokon keresztül megadott információkat, valamint a saját vizsgálatunkat.`,
  _ = `(peren kívüli egyezséggel kapcsolatos információk helye)`,
  _ = `Igen`,
  _ = `Nem`,
  _ = `Beküldés`,
  _ = `Mégse`,
  _ = `Moderálás vitatása`,
  _ = `Mellékeld a vitatásodat alátámasztó összes információt:`,
  _ = `A vitatásod alapja`,
  _ = `A %1$s gombra kattintva igazolod, hogy legjobb tudomásod szerint az itt található összes információ pontos.`,
  _ = `Rendezés dátuma: %1$s`,
  _ = `Rendezés dátuma: %1$s, tulajdonosi vitatás dátuma: %2$s`,
  _ = `Rendezés dátuma: %1$s, tulajdonosi vitatás dátuma: %2$s, vitarendezés dátuma: %3$s`,
  _ = `Jelentés dátuma: %1$s`,
  _ = `Jelentés dátuma: %1$s, megoldás dátuma: %2$s`,
  _ = `Jelentés dátuma: %1$s, rendezés dátuma: %2$s, vitatás dátuma: %3$s`,
  _ = `Jelentés dátuma: %1$s, rendezés dátuma: %2$s, vitatás dátuma: %3$s, vitarendezés dátuma: %4$s`,
  _ = `%2$s dátummal %1$s felhasználó által küldött csevegésüzenet`,
  _ = `%2$s dátummal %1$s felhasználó által küldött csoportos csevegésüzenet`,
  _ = `%1$s azonosító jelentése`,
  _ = `hozzászólásszál`,
  _ = `Tartalom jelentése`,
  _ = `Ez csak spam, hirdetés, illegális tartalom és problémás bejegyzések (zaklatás, veszekedés vagy gorombaság) jelentésére használandó.`,
  _ = `Milyen típusú problémát jelentesz?`,
  _ = `Jelentés beküldése`,
  _ = `Jelentés oka:`,
  _ = `Vissza`,
  _ = `Adj meg a jelentésedhez kapcsolódó bármilyen további információt. E jelentés beküldésével igazolod, hogy annak tartalma legjobb tudomásod szerint valós és pontos.`,
  _ = `Adj meg itt bármilyen további információt.`,
  _ = `Szerzőijog-sértés`,
  _ = `Védjegypanasz`,
  _ = `Neved (elhagyható)`,
  _ = `Sértő`,
  _ = `Kereskedelmi tevékenység`,
  _ = `Fogyasztói információk megsértése`,
  _ = `Kiskorú kihasználása`,
  _ = `Zavaró`,
  _ = `Zaklatás`,
  _ = `Beleegyezés nélküli tartalom`,
  _ = `Meztelenség vagy szexuális tartalom`,
  _ = `Témaidegen`,
  _ = `Adatvédelem és személyiségi jog megsértése`,
  _ = `Nem hiteles/manipulált értékelés`,
  _ = `Átverés és lopás`,
  _ = `Terrorizmus`,
  _ = `Erőszak és önbántalmazás`,
  _ = `Polgári közbeszéd és választások`,
  _ = `Gyanús tartalom`,
  _ = `Sértő tartalom`,
  _ = `Egyéb`,
  _ = `Adathalászat, átverések, barátok vagy a Steam Támogatás megszemélyesítése`,
  _ = `Zaklatás, spammelés, nem helyénvaló képek`,
  _ = `(Ismeretlen)`,
  _ = `(Ismeretlen)`,
  _ = `(Ismeretlen)`,
  _ = `Zaklatás`,
  _ = `Zaklatás és megfélemlítés`,
  _ = `Követés`,
  _ = `Doxxolás`,
  _ = `Egyéb zaklatás`,
  _ = `Erőszakra buzdítás`,
  _ = `Önbántalmazásról való beszélgetés vagy arra ösztönzés`,
  _ = `Öngyilkosságról való beszélgetés vagy arra ösztönzés`,
  _ = `Egyéb erőszak vagy önbántalmazás`,
  _ = `Hihető erőszakkal való fenyegetés`,
  _ = `Moderált tartalom idézése`,
  _ = `Adathalászat vagy fióklopás`,
  _ = `Választások vagy a közvélemény manipulálása`,
  _ = `Átverési kísérlet`,
  _ = `Hivatkozás rosszindulatú tartalomra`,
  _ = `Megszemélyesítés`,
  _ = `Egyéb átverés vagy lopás`,
  _ = `Terrorizmusra buzdítás`,
  _ = `Terrorizmus szervezése`,
  _ = `Terrorizmussal kapcsolatos egyéb`,
  _ = `Célzott sértő viselkedés`,
  _ = `Gúnyolódás és megszégyenítés`,
  _ = `Diszkrimináció`,
  _ = `Egyéb visszaélés`,
  _ = `Trollkodás`,
  _ = `Beetetés`,
  _ = `Elterelés`,
  _ = `Egyéb bomlasztó viselkedés`,
  _ = `Spammelés`,
  _ = `Kéregetés`,
  _ = `Tartalom újbóli közzététele`,
  _ = `Egyéb témaidegen`,
  _ = `Kiskorúval kapcsolatos szexuális tartalom`,
  _ = `Kiskorú megkörnyékezése vagy elcsábítása`,
  _ = `Kiskorú egyéb kihasználása`,
  _ = `Meztelenség vagy szexuális tartalom`,
  _ = `Beleegyezés nélküli tartalom`,
  _ = `Reklámozás`,
  _ = `Ajánlói hivatkozások`,
  _ = `Szerencsejáték`,
  _ = `Sorsolások`,
  _ = `Egyéb kereskedelmi tevékenység`,
  _ = `Nem hiteles vagy manipulált értékelés`,
  _ = `Rejtett hirdetések vagy kereskedelmi kommunikáció`,
  _ = `Félrevezető információk az áruk és szolgáltatások jellemzőiről`,
  _ = `Félrevezető információk a fogyasztó jogairól`,
  _ = `Árképzési szabályozások be nem tartása`,
  _ = `Személyes adatok törléséhez való jog`,
  _ = `Hiányzó adatfeldolgozási alap`,
  _ = `Egyéb adatvédelmi vagy személyiségi jog megsértése`,
  _ = `Nőkkel szembeni zaklatás`,
  _ = `Nőkkel szembeni megfélemlítés`,
  _ = `Nők követése`,
  _ = `Nők doxxolása`,
  _ = `Nőkkel szembeni egyéb zaklatás`,
  _ = `Nőkkel szembeni erőszakra buzdítás`,
  _ = `Nőkkel szembeni célzott sértő viselkedés`,
  _ = `Kiskorúval kapcsolatos mélyhamisított szexuális tartalom`,
  _ = `Nőkkel szembeni beleegyezés nélküli tartalom`,
  _ = `Nőkkel szembeni mélyhamisított, beleegyezés nélküli tartalom`,
  _ = `Mélyhamisított beleegyezés nélküli tartalom`,
  _ = `Nőket célzó`,
  _ = `Mélyhamisítás`,
  _ = `Kalózkodás`,
  _ = `Sérti a Steam felhasználási feltételeit`,
  _ = `Rosszul kategorizált`,
  _ = `Káromkodásszűrő megkerülése`,
  _ = `Jelentés beküldve`,
  _ = `Köszönjük, hogy beküldted a jelentésedet. Továbbítva lett moderálásra.`,
  _ = `Köszönjük, hogy beküldted a jelentésedet. Összegyűjtöttük a csevegésnapló egy kis részét, és elküldtük moderálásra. Nem kell semmilyen további lépést tenned.`,
  _ = `Hiba a jelentés beküldésekor`,
  _ = `Hiba történt a jelentésed beküldésekor. Kérjük, próbáld újra később.`,
  _ = `Ideiglenesen el vagy tiltva a tartalomjelentéstől.`,
  _ = `További lépéseket tehetsz a jövőbeli üzenetek elkerülésére:`,
  _ = `E felhasználó automatikusan blokkolva lett. Mostantól nem fogsz üzeneteket kapni tőle.`,
  _ = `Blokkolás visszavonása`,
  _ = `Barát törlése`,
  _ = `E felhasználó még a barátlistádon van; dönthetsz úgy, hogy törlöd a barátlistádról. Csendben el fogsz tűnni a barátlistájáról.`,
  _ = `Barát törölve`,
  _ = `Tudj meg többet a kifogásolható viselkedés kezeléséről a Steamen.`,
  _ = `Fórumszál`,
  _ = `Hozzászólásszál`,
  _ = `Barát csevegésüzenet`,
  _ = `Csevegőszoba-üzenet`,
  _ = `Csevegőcsoport`,
  _ = `Felhasználók készítette képek`,
  _ = `(Ismeretlen)`,
  _ = `Megoldás intézkedés nélkül`,
  _ = `Moderálásra vár`,
  _ = `Felülvizsgálva: nincs szükség intézkedésre`,
  _ = `Tartalom azonnal törölve`,
  _ = `Tartalom eltávolítva`,
  _ = `Tartalom átcímkézve`,
  _ = `Fiók gyanús tartalom miatt zárolva`,
  _ = `Steam közösségi jogosultságok felfüggesztve`,
  _ = `Eltávolítva és figyelmeztetve`,
  _ = `Eltávolítva és kitiltva a központból`,
  _ = `Eltávolítva és kirúgva a csoportból`,
  _ = `Szankcionálva`,
  _ = `Ismeretlen`,
  _ = `Felmentve`,
  _ = `Legutóbb megnyitott jelentés törölve`,
  _ = `Határozat vitatva`,
  _ = `Eszkalálva`,
  _ = `Szankcionálva`,
  _ = `Moderálás fenntartva`,
  _ = `Az eset megoldatlanná vált`,
  _ = `Eset részletei frissítve`,
  _ = `Zárolva`,
  _ = `Feloldva`,
  _ = `Törölve`,
  _ = `Figyelmeztetés kiadva`,
  _ = `Tartalomközpontból kitiltva`,
  _ = `Steam Közösségből kitiltva`,
  _ = `Cserekitiltott`,
  _ = `Tartalom gyanúsként jelölve`,
  _ = `Szerző tartalmai nullázva`,
  _ = `Eszkalálva a Valve-nek szexuális gyermekbántalmazás miatt`,
  _ = `Eszkalálva a Valve-nek terrorizmus miatt`,
  _ = `Lefoglalva`,
  _ = `Felszabadítva`,
  _ = `Privát üzenet küldve`,
  _ = `Ismeretlen művelet`,
  _ = `Tulajdonos által vitatott moderálás`,
  _ = `Megjegyzések: %1$s`,
  _ = `Figyelmeztetések: %1$s`,
  _ = `Kitiltások: %1$s`,
  _ = `Tartalom-eltávolítási értesítések: %1$s`,
  _ = `Átverés, adathalászat és lopás`,
  _ = `Adathalászat, lopás, átverés, rosszindulatú tartalomra hivatkozás, hamis személyazonosság létrehozása mások félrevezetése céljából`,
  _ = `Adatvédelem`,
  _ = `Doxolás, követés, gúnyolódás és megszégyenítés, intim képek beleegyezés nélküli terjesztése`,
  _ = `Gyermekbiztonság`,
  _ = `Kiskorúak kizsákmányolása, gyermekek szexuális bántalmazása, kiskorúak megkörnyékezése, gyermekbántalmazás`,
  _ = `Erőszakra buzdítás`,
  _ = `Való világbeli erőszakra, önbántalmazásra, öngyilkosságra, ártalommal való fenyegetésre, terrorizmusra bátorítás vagy annak elősegítése`,
  _ = `Zaklatás, megfélemlítés és bomlasztó viselkedés`,
  _ = `A fórumot zavaró viselkedés, beleértve a trollkodást, sértő nyelvezetet, spammelést, illetve lezárt vagy törölt tartalom újbóli közzétételét`,
  _ = `Érzékeny vagy felkavaró`,
  _ = `Valós emberek meztelen vagy nyíltan szexuális tartalmú képei, nem megfelelően jelölt és korhatárosított felnőtt tartalom, erőszak vagy vér valós vagy felkavaró ábrázolása`,
  _ = `Reklámozás és kereskedelmi tevékenység`,
  _ = `Ajánlói hivatkozások, versenyek, sorsolások, szerencsejáték, Steam fiókok adásvétele`,
  _ = `Csalás és kalózkodás`,
  _ = `Csalások, kihasználhatóságok és játékkalózkodás megvitatása vagy népszerűsítése`,
  _ = `Egyéb`,
  _ = `E tartalom illegális vagy nem helyénvaló egy itt nem szereplő ok miatt`,
  _ = `Szellemi tulajdon`,
  _ = `Szerzői jog vagy védjegy megsértése, illetve licenckorlátozások megkerülése`,
  _ = `Tartalom jelentésének oka: %1$s`,
  _ = `Elhagyni készülsz ezt az oldalt, hogy a Steam szerzői jog jelentési űrlapjához lépj.`,
  _ = `Elhagyni készülsz ezt az oldalt, hogy a Steam védjegyjelentési űrlapjához lépj.`,
  _ = `Megkaptuk a jelentésedet`,
  _ = `Ezt jelentetted: %1$s`,
  _ = `Jelentésed megoldásra került`,
  _ = `Nem történt intézkedés a(z) %1$s kapcsán`,
  _ = `Jelentésed megoldásra került`,
  _ = `Intézkedés történt a(z) %1$s kapcsán`,
  _ = `Megkaptuk a vitatásodat`,
  _ = `Vitattad a(z) %1$s moderálását`,
  _ = `Vitatásod megoldásra került`,
  _ = `Nem történt intézkedés a(z) %1$s kapcsán`,
  _ = `Vitatásod megoldásra került`,
  _ = `Intézkedés történt a(z) %1$s kapcsán`,
  _ = `Ezt jelentetted: %1$s`,
  _ = `A Steam moderátorai ki fogják értékelni a tartalmat, és lépéseket tesznek a Steam %1$s szerint. A jelentés megoldásakor Steames értesítést fogsz kapni.`,
  _ = `közösségi szabályok és irányelvek`,
  _ = `Azt is javasoljuk, hogy tekintsd át az információkat itt: %1$s.`,
  _ = `Megoldottuk a jelentésedet`,
  _ = `%1$s általi kiértékelés után a tartalom nem bizonyult a Steam %2$s megsértésének.`,
  _ = `Jogodban áll az is, hogy hitelesített, bíróságon kívüli vitarendezési testületen keresztül keress megoldást, vagy egy illetékes bíróságon kérj bírósági jogorvoslatot.`,
  _ = `Ha nem értesz egyet ezzel a döntéssel, benyújthatsz egy %1$s.`,
  _ = `vitatást`,
  _ = `Visszaélés, zaklatás és más kifogásolható viselkedés kezelése a Steamen`,
  _ = `Vitatás beküldése`,
  _ = `Kérjük, adj meg minden információt arról, miért véled úgy, hogy a Steam döntése e tartalom kapcsán téves volt.`,
  _ = `Értesítést fogsz kapni, amikor a vitatásod megoldásra került.`,
  _ = `Hiba történt. Kérjük, próbáld újra később.`,
  _ = `Lépéseket tettünk a jelentésed alapján`,
  _ = `%1$s általi kiértékelés után a tartalom a Steam\xA0%2$s megsértésének bizonyult.`,
  _ = `Köszönjük, hogy segítesz biztonságos környezetet fenntartanunk a Steamen.`,
  _ = `egy moderátor`,
  _ = `az automatizált tartalom-ellenőrző rendszerünk`,
  _ = `egy moderátor automatizált segítséggel`,
  _ = `Megkaptuk a vitatásodat`,
  _ = `A Steam vitatásokat felülvizsgáló csapata újból ki fogja értékelni a tartalmat.`,
  _ = `Értesítést fogsz kapni itt, amikor a felülvizsgálat befejeződött.`,
  _ = `Befejeztük a felülvizsgálatunkat`,
  _ = `A Steam vitatásokat felülvizsgáló csapata általi kiértékelés után a tartalom nem bizonyult a Steam %1$s megsértésének.`,
  _ = `Ha úgy véled, ez helytelen, jogodban áll hitelesített, bíróságon kívüli vitarendező testületen keresztül megoldást keresni, vagy illetékes bíróságon kérni bírósági jogorvoslatot.`,
  _ = `Befejeztük a felülvizsgálatunkat`,
  _ = `A Steam vitatásokat felülvizsgáló csapata általi kiértékelés után az általad jelentett tartalom a Steam\xA0%1$s megsértésének bizonyult.`,
  _ = `Köszönjük, hogy segítesz biztonságos környezetet fenntartanunk a Steamen.`,
  _ = `Jelentés részletei`,
  _ = `Ezt írtad:`,
  _ = `fórumbejegyzés`,
  _ = `%3$s közösségközpontban, „%2$s” témában tett %1$s`,
  _ = `%2$s a(z) %1$s központban`,
  _ = `E tartalom jelentése`,
  _ = `Nem helyénvaló vagy jogsértő tartalom jelentéséhez jelentkezz be a Steam Közösségbe.`,
  _ = `Ha nem tudsz bejelentkezni, <1>küldhetsz névtelen jelentést</1>.`,
  _ = `küldhetsz névtelen jelentést`,
  _ = `Bejelentkezés`,
  _ = `csatlakozás a Steamhez`,
  _ = `Fiók létrehozása`,
  _ = `%1$s vagy %2$s`,
  _ = `Jelenlegi várakoztatási idő betöltése`,
  _ = `Hiba a jelenlegi várakoztatási idő betöltésekor!`,
  _ = `A jelentésvárakoztatás %1$s időpontban jár le.`,
  _ = `Jelenleg nincs várakoztatási idő.`,
  _ = `nap`,
  _ = `Új várakoztatás e felhasználónak:`,
  _ = `Várakoztatás törlése`,
  _ = `(%1$s nap)`,
  _ = `Jelentésvárakoztatás beállítása`,
  _ = `Eltilt egy felhasználót a tartalomjelentéstől és moderálásvitatástól, amikor visszaél a rendszerrel.`,
  _ = `Várakoztatás beállítása`,
  _ = `E felhasználó megoldatlan jelentéseinek törlése`,
  _ = `%1$s/%2$s jelentés felmentve, %3$s/%4$s a múlt héten.`,
  _ = ``,
  _ = {
    moderation_contentreports_title: _,
    moderation_submittedbyyou_title: _,
    moderation_onyourcontent_title: _,
    moderation_acquitted_description: _,
    moderation_maydispute_description: _,
    moderation_state_disputed: _,
    moderation_state_communicationblocked: _,
    moderation_sanctioned_for_reason: _,
    moderation_statementofreasons_header: _,
    moderation_statementofreasons_visibilityrestriction: _,
    moderation_statementofreasons_factsandcircumstances: _,
    moderation_statementofreasons_decisionground: _,
    moderation_statementofreasons_legalground: _,
    moderation_statementofreasons_contractualground: _,
    moderation_statementofreasons_explanationwhy: _,
    moderation_statementofreasons_contenttype: _,
    moderation_statementofreasons_informationsource: _,
    moderation_statementofreasons_automatedidentification: _,
    moderation_statementofreasons_automateddecision: _,
    moderation_statementofreasons_decisionground_legal: _,
    moderation_statementofreasons_explanation_legal: _,
    moderation_statementofreasons_decisionground_genericcontractual: _,
    moderation_statementofreasons_explanation_genericcontractual: _,
    moderation_statementofreasons_explanation_genericcontractual_steam_online_conduct_rules:
      _,
    moderation_statementofreasons_explanation_genericcontractual_steam_subscriber_agreement:
      _,
    moderation_statementofreasons_informationsource_report: _,
    moderation_none: _,
    moderation_automateddetection: _,
    moderation_fullyautomatedresolution: _,
    moderation_partiallyautomatedresolution: _,
    moderation_statementofreasons_visibilityrestriction_removed: _,
    moderation_statementofreasons_factsandcircumstances_text: _,
    moderation_outofcourtsettlement: _,
    moderation_yes: _,
    moderation_no: `Nem`,
    moderation_submit: _,
    moderation_cancel: _,
    moderation_dispute_title: _,
    moderation_dispute_description: _,
    moderation_detailsplaceholder: _,
    moderation_attestation: _,
    moderation_subjectreportedandresolved: _,
    moderation_subjectreporteddisputed: _,
    moderation_subjectdisputeresolved: _,
    moderation_reportedon: _,
    moderation_reportedandresolvedon: _,
    moderation_reportedanddisputed: _,
    moderation_reporteddisputeresolved: _,
    moderation_chatreport_desc: _,
    moderation_chatgroupmsgreport_desc: _,
    moderation_reportid: _,
    moderation_commentthread_desc: _,
    ReportContent_Title: _,
    ReportContent_Description: _,
    ReportContent_PickAReason: _,
    ReportContent_ReportButton: _,
    ReportContent_ReportAs: _,
    ReportContent_Back: _,
    ReportContent_Attestation: _,
    ReportContent_DetailsPlaceholder: _,
    ReportContent_CopyrightInfringement: _,
    ReportContent_TrademarkComplaint: _,
    ReportContent_YourNamePlaceholder: _,
    ContentReportReasonCategory_Abusive: _,
    ContentReportReasonCategory_Commercial: _,
    ContentReportReasonCategory_ConsumerInformation: _,
    ContentReportReasonCategory_CSAM: _,
    ContentReportReasonCategory_Disruptive: _,
    ContentReportReasonCategory_Harassment: _,
    ContentReportReasonCategory_Nonconsensual: _,
    ContentReportReasonCategory_NudityOrSexualContent: _,
    ContentReportReasonCategory_Offtopic: _,
    ContentReportReasonCategory_Privacy: _,
    ContentReportReasonCategory_ReviewManipulation: _,
    ContentReportReasonCategory_ScamsAndTheft: _,
    ContentReportReasonCategory_Terrorism: _,
    ContentReportReasonCategory_ViolenceAndSelfHarm: _,
    ContentReportReasonCategory_CivicDiscourse: _,
    ContentReportReasonCategory_Suspicious: _,
    ContentReportReasonCategory_Inappropriate: _,
    ContentReportReasonCategory_Other: _,
    ContentReportReasonCategoryDesc_Suspicious: _,
    ContentReportReasonCategoryDesc_Inappropriate: _,
    ContentReportReason_Invalid: _,
    ContentReportReason_None: _,
    ContentReportReason_Unknown: _,
    ContentReportReason_Harassment: _,
    ContentReportReason_BullyingAndIntimidation: _,
    ContentReportReason_Stalking: _,
    ContentReportReason_Doxxing: _,
    ContentReportReason_OtherHarassment: _,
    ContentReportReason_EncouragingViolence: _,
    ContentReportReason_EncouragingSelfHarm: _,
    ContentReportReason_EncouragingSuicide: _,
    ContentReportReason_OtherViolenceOrSelfHarm: _,
    ContentReportReason_CredibleThreatOfViolence: _,
    ContentReportReason_QuotesModeratedContent: _,
    ContentReportReason_PhishingOrAccountTheft: _,
    ContentReportReason_NegativeEffectonDiscourseOrElections: _,
    ContentReportReason_AttemptedScamming: _,
    ContentReportReason_LinkingToMaliciousContent: _,
    ContentReportReason_Impersonation: _,
    ContentReportReason_OtherScamsAndTheft: _,
    ContentReportReason_EncouragingTerrorism: _,
    ContentReportReason_OrganizingTerrorism: _,
    ContentReportReason_OtherTerrorism: _,
    ContentReportReason_TargetedAbuse: _,
    ContentReportReason_NamingAndShaming: _,
    ContentReportReason_Discrimination: _,
    ContentReportReason_OtherAbuse: _,
    ContentReportReason_Trolling: _,
    ContentReportReason_Baiting: _,
    ContentReportReason_Derailing: _,
    ContentReportReason_OtherDisruptive: _,
    ContentReportReason_Spam: _,
    ContentReportReason_Begging: _,
    ContentReportReason_Reposting: _,
    ContentReportReason_OtherOffTopic: _,
    ContentReportReason_CSAMSexualContent: _,
    ContentReportReason_CSAMGroomingOrEnticement: _,
    ContentReportReason_CSAMOther: _,
    ContentReportReason_NudityOrSexualContent: _,
    ContentReportReason_NonConsensualMaterial: _,
    ContentReportReason_Advertising: _,
    ContentReportReason_ReferralLinks: _,
    ContentReportReason_Gambling: _,
    ContentReportReason_Raffles: _,
    ContentReportReason_OtherCommercialActivity: _,
    ContentReportReason_InauthenticReview: _,
    ContentReportReason_HiddenAdvertisementOrCommercialCommunication: _,
    ContentReportReason_MisleadingInformationAboutGoodsOrServices: _,
    ContentReportReason_MisleadingInformationAboutConsumerRights: _,
    ContentReportReason_NoncomplianceWithPricingRegulations: _,
    ContentReportReason_RightToBeForgottenViolation: _,
    ContentReportReason_MissingProcessingGroundForData: _,
    ContentReportReason_OtherDataProtectionAndPrivacyViolation: _,
    ContentReportReason_GenderedHarassment: _,
    ContentReportReason_GenderedBullyingAndIntimidation: _,
    ContentReportReason_GenderedStalking: _,
    ContentReportReason_GenderedDoxxing: _,
    ContentReportReason_GenderedOtherHarassment: _,
    ContentReportReason_GenderedEncouragingViolence: _,
    ContentReportReason_GenderedTargetedAbuse: _,
    ContentReportReason_CSAMFakedSexualContent: _,
    ContentReportReason_GenderedNonConsensualMaterial: _,
    ContentReportReason_FakedGenderedNonConsensualMaterial: _,
    ContentReportReason_FakedNonConsensualMaterial: _,
    ContentReportReason_Gendered: _,
    ContentReportReason_Deepfake: _,
    ContentReportReason_Piracy: _,
    ContentReportReason_ToSViolation: _,
    ContentReportReason_Miscategorized: _,
    ContentReportReason_BypassingProfanityFilter: _,
    ContentReportSubmitted_Title: _,
    ContentReportSubmitted_Description: _,
    ContentReportSubmitted_Chat_Description: _,
    ContentReportSubmissionError_Title: _,
    ContentReportSubmissionError_Description: _,
    ContentReportSubmissionOnCooldown_Description: _,
    ContentReport_FriendOptions_CallToAction: _,
    ContentReport_FriendOptions_BlockedDesc: _,
    ContentReport_FriendOptions_Unblock: _,
    ContentReport_FriendOptions_Remove: _,
    ContentReport_FriendOptions_RemoveDesc: _,
    ContentReport_FriendOptions_RemoveSuccess: _,
    ContentReport_LearnMore_Misconduct: _,
    moderation_subjecttype_forumpost: _,
    moderation_subjecttype_commentthread: _,
    moderation_subjecttype_friendchatmsg: _,
    moderation_subjecttype_chatroommsg: _,
    moderation_subjecttype_chatgroup: _,
    moderation_subjettype_ugcfile: _,
    moderation_subjecttype_unknown: _,
    moderation_resolvewithnoaction: _,
    moderation_resolutionstatus_pending: _,
    moderation_resolutionstatus_acquitted: _,
    moderation_resolutionstatus_purged: _,
    moderation_resolutionstatus_removed: _,
    moderation_resolutionstatus_relabelled: _,
    moderation_resolutionstatus_suspicious: _,
    moderation_resolutionstatus_harassmentstrike: _,
    moderation_resolutionstatus_removeandwarn: _,
    moderation_resolutionstatus_removeandban: _,
    moderation_resolutionstatus_removeandkick: _,
    moderation_resolutionstatus_sanctioned: _,
    moderation_resolutionstatus_unknown: _,
    moderationaction_acquitted: _,
    moderationaction_cancelled: _,
    moderationaction_disputed: _,
    moderationaction_escalated: _,
    moderationaction_sanctioned: _,
    moderationaction_sustained: _,
    moderationaction_unresolved: _,
    moderationaction_updated: _,
    moderationaction_locked: _,
    moderationaction_unlocked: _,
    moderationaction_deleted: _,
    moderationaction_warned: _,
    moderationaction_banned_from_hub: _,
    moderationaction_banned_from_community: _,
    moderationaction_trade_banned: _,
    moderationaction_marked_as_suspicious: _,
    moderationaction_reset_content: _,
    moderationaction_escalated_for_csam: _,
    moderationaction_escalated_for_terrorism: _,
    moderationaction_claimed: _,
    moderationaction_released: _,
    moderationaction_privatemessaged: _,
    moderationaction_unknown: _,
    moderationaction_ownerdisputed: _,
    moderatormessage_count_note: _,
    moderatormessage_count_warning: _,
    moderatormessage_count_bannotice: _,
    moderatormessage_count_contentremoval: _,
    reportforumpost_reason_scams: _,
    reportforumpost_description_scams: _,
    reportforumpost_reason_privacy: _,
    reportforumpost_description_privacy: _,
    reportforumpost_reason_childsafety: _,
    reportforumpost_description_childsafety: _,
    reportforumpost_reason_promotingviolence: _,
    reportforumpost_description_promotingviolence: _,
    reportforumpost_reason_disruptive: _,
    reportforumpost_description_disruptive: _,
    reportforumpost_reason_sensitiveordisturbing: _,
    reportforumpost_description_sensitiveordisturbing: _,
    reportforumpost_reason_advertising: _,
    reportforumpost_description_advertising: _,
    reportforumpost_reason_cheating: _,
    reportforumpost_description_cheating: _,
    reportforumpost_reason_notfound: _,
    reportforumpost_description_notfound: _,
    reportforumpost_reason_intellectualproperty: _,
    reportforumpost_description_intellectualproperty: _,
    reportforumpost_reasonforreport: _,
    WarnBeforeNavigatingToCopyrightReportForm: _,
    WarnBeforeNavigatingToTrademarkReportForm: _,
    reportedcontentlist_unresolved_title: _,
    reportedcontentlist_unresolved_body: _,
    reportedcontentlist_acquitted_title: _,
    reportedcontentlist_acquitted_body: _,
    reportedcontentlist_sanctioned_title: _,
    reportedcontentlist_sanctioned_body: _,
    reportedcontentlist_disputed_title: _,
    reportedcontentlist_disputed_body: _,
    reportedcontentlist_disputedenied_title: _,
    reportedcontentlist_disputedenied_body: _,
    reportedcontentlist_disputesanctioned_title: _,
    reportedcontentlist_disputesanctioned_body: _,
    reportedcontent_unresolved_1: _,
    reportedcontent_unresolved_2: _,
    reportedcontent_community_guidelines: _,
    reportedcontent_unresolved_3: _,
    reportedcontent_acquitted_1: _,
    reportedcontent_acquitted_2: _,
    reportedcontent_acquitted_2_eu_addendum: _,
    reportedcontent_dispute_submit_dispute: _,
    reportedcontent_dispute_acquittal: _,
    reportedcontent_harassment_guidance: _,
    reportedcontent_submit_dispute_title: _,
    reportedcontent_submit_dispute_description: _,
    reportedcontent_dispute_acknowledged: _,
    reportedcontent_error: _,
    reportedcontent_sanctioned_1: _,
    reportedcontent_sanctioned_2: _,
    reportedcontent_sanctioned_3: _,
    reportedcontent_moderatedby_human: _,
    reportedcontent_moderatedby_machine: _,
    reportedcontent_moderatedby_assistedhuman: _,
    reportedcontent_disputed_1: _,
    reportedcontent_disputed_2: _,
    reportedcontent_disputed_3: _,
    reportedcontent_disputedenied_1: _,
    reportedcontent_disputedenied_2: _,
    reportedcontent_disputedenied_eu_addendum: _,
    reportedcontent_disputesanctioned_1: _,
    reportedcontent_disputesanctioned_2: _,
    reportedcontent_disputesanctioned_3: _,
    reportedcontent_content_report_breadcrumb: _,
    reportedcontent_you_wrote: _,
    reportedcontent_summary_forumpost: _,
    reportedcontent_summary_forumpost_on: _,
    reportedcontent_summary_forumtopic_in: _,
    anonymousreport_title: _,
    anonymousreport_description: _,
    anonymousreport_footer: _,
    anonymousreport_footer_action: _,
    anonymousreport_signin: _,
    anonymousreport_join: _,
    anonymousreport_createaccount: _,
    anonymousreport_signin_or_join: _,
    setcooldown_loading: _,
    setcooldown_errorloading: _,
    setcooldown_expireson: _,
    setcooldown_nocooldown: _,
    setcooldown_days: `nap`,
    setcooldown_newcooldownlabel: _,
    setcooldown_clearcooldown: _,
    setcooldown_cooldownsummary: _,
    setcooldown_dialogtitle: _,
    setcooldown_dialogdescription: _,
    setcooldown_setbutton: _,
    setcooldown_clearopenreports: _,
    setcooldown_statssummary: _,
    nocomma: ``,
  };
export {
  _ as ContentReportReasonCategoryDesc_Inappropriate,
  _ as ContentReportReasonCategoryDesc_Suspicious,
  _ as ContentReportReasonCategory_Abusive,
  _ as ContentReportReasonCategory_CSAM,
  _ as ContentReportReasonCategory_CivicDiscourse,
  _ as ContentReportReasonCategory_Commercial,
  _ as ContentReportReasonCategory_ConsumerInformation,
  _ as ContentReportReasonCategory_Disruptive,
  _ as ContentReportReasonCategory_Harassment,
  _ as ContentReportReasonCategory_Inappropriate,
  _ as ContentReportReasonCategory_Nonconsensual,
  _ as ContentReportReasonCategory_NudityOrSexualContent,
  _ as ContentReportReasonCategory_Offtopic,
  _ as ContentReportReasonCategory_Other,
  _ as ContentReportReasonCategory_Privacy,
  _ as ContentReportReasonCategory_ReviewManipulation,
  _ as ContentReportReasonCategory_ScamsAndTheft,
  _ as ContentReportReasonCategory_Suspicious,
  _ as ContentReportReasonCategory_Terrorism,
  _ as ContentReportReasonCategory_ViolenceAndSelfHarm,
  _ as ContentReportReason_Advertising,
  _ as ContentReportReason_AttemptedScamming,
  _ as ContentReportReason_Baiting,
  _ as ContentReportReason_Begging,
  _ as ContentReportReason_BullyingAndIntimidation,
  _ as ContentReportReason_BypassingProfanityFilter,
  _ as ContentReportReason_CSAMFakedSexualContent,
  _ as ContentReportReason_CSAMGroomingOrEnticement,
  _ as ContentReportReason_CSAMOther,
  _ as ContentReportReason_CSAMSexualContent,
  _ as ContentReportReason_CredibleThreatOfViolence,
  _ as ContentReportReason_Deepfake,
  _ as ContentReportReason_Derailing,
  _ as ContentReportReason_Discrimination,
  _ as ContentReportReason_Doxxing,
  _ as ContentReportReason_EncouragingSelfHarm,
  _ as ContentReportReason_EncouragingSuicide,
  _ as ContentReportReason_EncouragingTerrorism,
  _ as ContentReportReason_EncouragingViolence,
  _ as ContentReportReason_FakedGenderedNonConsensualMaterial,
  _ as ContentReportReason_FakedNonConsensualMaterial,
  _ as ContentReportReason_Gambling,
  _ as ContentReportReason_Gendered,
  _ as ContentReportReason_GenderedBullyingAndIntimidation,
  _ as ContentReportReason_GenderedDoxxing,
  _ as ContentReportReason_GenderedEncouragingViolence,
  _ as ContentReportReason_GenderedHarassment,
  _ as ContentReportReason_GenderedNonConsensualMaterial,
  _ as ContentReportReason_GenderedOtherHarassment,
  _ as ContentReportReason_GenderedStalking,
  _ as ContentReportReason_GenderedTargetedAbuse,
  _ as ContentReportReason_Harassment,
  _ as ContentReportReason_HiddenAdvertisementOrCommercialCommunication,
  _ as ContentReportReason_Impersonation,
  _ as ContentReportReason_InauthenticReview,
  _ as ContentReportReason_Invalid,
  _ as ContentReportReason_LinkingToMaliciousContent,
  _ as ContentReportReason_Miscategorized,
  _ as ContentReportReason_MisleadingInformationAboutConsumerRights,
  _ as ContentReportReason_MisleadingInformationAboutGoodsOrServices,
  _ as ContentReportReason_MissingProcessingGroundForData,
  _ as ContentReportReason_NamingAndShaming,
  _ as ContentReportReason_NegativeEffectonDiscourseOrElections,
  _ as ContentReportReason_NonConsensualMaterial,
  _ as ContentReportReason_NoncomplianceWithPricingRegulations,
  _ as ContentReportReason_None,
  _ as ContentReportReason_NudityOrSexualContent,
  _ as ContentReportReason_OrganizingTerrorism,
  _ as ContentReportReason_OtherAbuse,
  _ as ContentReportReason_OtherCommercialActivity,
  _ as ContentReportReason_OtherDataProtectionAndPrivacyViolation,
  _ as ContentReportReason_OtherDisruptive,
  _ as ContentReportReason_OtherHarassment,
  _ as ContentReportReason_OtherOffTopic,
  _ as ContentReportReason_OtherScamsAndTheft,
  _ as ContentReportReason_OtherTerrorism,
  _ as ContentReportReason_OtherViolenceOrSelfHarm,
  _ as ContentReportReason_PhishingOrAccountTheft,
  _ as ContentReportReason_Piracy,
  _ as ContentReportReason_QuotesModeratedContent,
  _ as ContentReportReason_Raffles,
  _ as ContentReportReason_ReferralLinks,
  _ as ContentReportReason_Reposting,
  _ as ContentReportReason_RightToBeForgottenViolation,
  _ as ContentReportReason_Spam,
  _ as ContentReportReason_Stalking,
  _ as ContentReportReason_TargetedAbuse,
  _ as ContentReportReason_ToSViolation,
  _ as ContentReportReason_Trolling,
  _ as ContentReportReason_Unknown,
  _ as ContentReportSubmissionError_Description,
  _ as ContentReportSubmissionError_Title,
  _ as ContentReportSubmissionOnCooldown_Description,
  _ as ContentReportSubmitted_Chat_Description,
  _ as ContentReportSubmitted_Description,
  _ as ContentReportSubmitted_Title,
  _ as ContentReport_FriendOptions_BlockedDesc,
  _ as ContentReport_FriendOptions_CallToAction,
  _ as ContentReport_FriendOptions_Remove,
  _ as ContentReport_FriendOptions_RemoveDesc,
  _ as ContentReport_FriendOptions_RemoveSuccess,
  _ as ContentReport_FriendOptions_Unblock,
  _ as ContentReport_LearnMore_Misconduct,
  _ as ReportContent_Attestation,
  _ as ReportContent_Back,
  _ as ReportContent_CopyrightInfringement,
  _ as ReportContent_Description,
  _ as ReportContent_DetailsPlaceholder,
  _ as ReportContent_PickAReason,
  _ as ReportContent_ReportAs,
  _ as ReportContent_ReportButton,
  _ as ReportContent_Title,
  _ as ReportContent_TrademarkComplaint,
  _ as ReportContent_YourNamePlaceholder,
  _ as WarnBeforeNavigatingToCopyrightReportForm,
  _ as WarnBeforeNavigatingToTrademarkReportForm,
  _ as anonymousreport_createaccount,
  _ as anonymousreport_description,
  _ as anonymousreport_footer,
  _ as anonymousreport_footer_action,
  _ as anonymousreport_join,
  _ as anonymousreport_signin,
  _ as anonymousreport_signin_or_join,
  _ as anonymousreport_title,
  _ as default,
  _ as moderation_acquitted_description,
  _ as moderation_attestation,
  _ as moderation_automateddetection,
  _ as moderation_cancel,
  _ as moderation_chatgroupmsgreport_desc,
  _ as moderation_chatreport_desc,
  _ as moderation_commentthread_desc,
  _ as moderation_contentreports_title,
  _ as moderation_detailsplaceholder,
  _ as moderation_dispute_description,
  _ as moderation_dispute_title,
  _ as moderation_fullyautomatedresolution,
  _ as moderation_maydispute_description,
  _ as moderation_no,
  _ as moderation_none,
  _ as moderation_onyourcontent_title,
  _ as moderation_outofcourtsettlement,
  _ as moderation_partiallyautomatedresolution,
  _ as moderation_reportedanddisputed,
  _ as moderation_reportedandresolvedon,
  _ as moderation_reporteddisputeresolved,
  _ as moderation_reportedon,
  _ as moderation_reportid,
  _ as moderation_resolutionstatus_acquitted,
  _ as moderation_resolutionstatus_harassmentstrike,
  _ as moderation_resolutionstatus_pending,
  _ as moderation_resolutionstatus_purged,
  _ as moderation_resolutionstatus_relabelled,
  _ as moderation_resolutionstatus_removeandban,
  _ as moderation_resolutionstatus_removeandkick,
  _ as moderation_resolutionstatus_removeandwarn,
  _ as moderation_resolutionstatus_removed,
  _ as moderation_resolutionstatus_sanctioned,
  _ as moderation_resolutionstatus_suspicious,
  _ as moderation_resolutionstatus_unknown,
  _ as moderation_resolvewithnoaction,
  _ as moderation_sanctioned_for_reason,
  _ as moderation_state_communicationblocked,
  _ as moderation_state_disputed,
  _ as moderation_statementofreasons_automateddecision,
  _ as moderation_statementofreasons_automatedidentification,
  _ as moderation_statementofreasons_contenttype,
  _ as moderation_statementofreasons_contractualground,
  _ as moderation_statementofreasons_decisionground,
  _ as moderation_statementofreasons_decisionground_genericcontractual,
  _ as moderation_statementofreasons_decisionground_legal,
  _ as moderation_statementofreasons_explanation_genericcontractual,
  _ as moderation_statementofreasons_explanation_genericcontractual_steam_online_conduct_rules,
  _ as moderation_statementofreasons_explanation_genericcontractual_steam_subscriber_agreement,
  _ as moderation_statementofreasons_explanation_legal,
  _ as moderation_statementofreasons_explanationwhy,
  _ as moderation_statementofreasons_factsandcircumstances,
  _ as moderation_statementofreasons_factsandcircumstances_text,
  _ as moderation_statementofreasons_header,
  _ as moderation_statementofreasons_informationsource,
  _ as moderation_statementofreasons_informationsource_report,
  _ as moderation_statementofreasons_legalground,
  _ as moderation_statementofreasons_visibilityrestriction,
  _ as moderation_statementofreasons_visibilityrestriction_removed,
  _ as moderation_subjectdisputeresolved,
  _ as moderation_subjectreportedandresolved,
  _ as moderation_subjectreporteddisputed,
  _ as moderation_subjecttype_chatgroup,
  _ as moderation_subjecttype_chatroommsg,
  _ as moderation_subjecttype_commentthread,
  _ as moderation_subjecttype_forumpost,
  _ as moderation_subjecttype_friendchatmsg,
  _ as moderation_subjecttype_unknown,
  _ as moderation_subjettype_ugcfile,
  _ as moderation_submit,
  _ as moderation_submittedbyyou_title,
  _ as moderation_yes,
  _ as moderationaction_acquitted,
  _ as moderationaction_banned_from_community,
  _ as moderationaction_banned_from_hub,
  _ as moderationaction_cancelled,
  _ as moderationaction_claimed,
  _ as moderationaction_deleted,
  _ as moderationaction_disputed,
  _ as moderationaction_escalated,
  _ as moderationaction_escalated_for_csam,
  _ as moderationaction_escalated_for_terrorism,
  _ as moderationaction_locked,
  _ as moderationaction_marked_as_suspicious,
  _ as moderationaction_ownerdisputed,
  _ as moderationaction_privatemessaged,
  _ as moderationaction_released,
  _ as moderationaction_reset_content,
  _ as moderationaction_sanctioned,
  _ as moderationaction_sustained,
  _ as moderationaction_trade_banned,
  _ as moderationaction_unknown,
  _ as moderationaction_unlocked,
  _ as moderationaction_unresolved,
  _ as moderationaction_updated,
  _ as moderationaction_warned,
  _ as moderatormessage_count_bannotice,
  _ as moderatormessage_count_contentremoval,
  _ as moderatormessage_count_note,
  _ as moderatormessage_count_warning,
  _ as nocomma,
  _ as reportedcontent_acquitted_1,
  _ as reportedcontent_acquitted_2,
  _ as reportedcontent_acquitted_2_eu_addendum,
  _ as reportedcontent_community_guidelines,
  _ as reportedcontent_content_report_breadcrumb,
  _ as reportedcontent_dispute_acknowledged,
  _ as reportedcontent_dispute_acquittal,
  _ as reportedcontent_dispute_submit_dispute,
  _ as reportedcontent_disputed_1,
  _ as reportedcontent_disputed_2,
  _ as reportedcontent_disputed_3,
  _ as reportedcontent_disputedenied_1,
  _ as reportedcontent_disputedenied_2,
  _ as reportedcontent_disputedenied_eu_addendum,
  _ as reportedcontent_disputesanctioned_1,
  _ as reportedcontent_disputesanctioned_2,
  _ as reportedcontent_disputesanctioned_3,
  _ as reportedcontent_error,
  _ as reportedcontent_harassment_guidance,
  _ as reportedcontent_moderatedby_assistedhuman,
  _ as reportedcontent_moderatedby_human,
  _ as reportedcontent_moderatedby_machine,
  _ as reportedcontent_sanctioned_1,
  _ as reportedcontent_sanctioned_2,
  _ as reportedcontent_sanctioned_3,
  _ as reportedcontent_submit_dispute_description,
  _ as reportedcontent_submit_dispute_title,
  _ as reportedcontent_summary_forumpost,
  _ as reportedcontent_summary_forumpost_on,
  _ as reportedcontent_summary_forumtopic_in,
  _ as reportedcontent_unresolved_1,
  _ as reportedcontent_unresolved_2,
  _ as reportedcontent_unresolved_3,
  _ as reportedcontent_you_wrote,
  _ as reportedcontentlist_acquitted_body,
  _ as reportedcontentlist_acquitted_title,
  _ as reportedcontentlist_disputed_body,
  _ as reportedcontentlist_disputed_title,
  _ as reportedcontentlist_disputedenied_body,
  _ as reportedcontentlist_disputedenied_title,
  _ as reportedcontentlist_disputesanctioned_body,
  _ as reportedcontentlist_disputesanctioned_title,
  _ as reportedcontentlist_sanctioned_body,
  _ as reportedcontentlist_sanctioned_title,
  _ as reportedcontentlist_unresolved_body,
  _ as reportedcontentlist_unresolved_title,
  _ as reportforumpost_description_advertising,
  _ as reportforumpost_description_cheating,
  _ as reportforumpost_description_childsafety,
  _ as reportforumpost_description_disruptive,
  _ as reportforumpost_description_intellectualproperty,
  _ as reportforumpost_description_notfound,
  _ as reportforumpost_description_privacy,
  _ as reportforumpost_description_promotingviolence,
  _ as reportforumpost_description_scams,
  _ as reportforumpost_description_sensitiveordisturbing,
  _ as reportforumpost_reason_advertising,
  _ as reportforumpost_reason_cheating,
  _ as reportforumpost_reason_childsafety,
  _ as reportforumpost_reason_disruptive,
  _ as reportforumpost_reason_intellectualproperty,
  _ as reportforumpost_reason_notfound,
  _ as reportforumpost_reason_privacy,
  _ as reportforumpost_reason_promotingviolence,
  _ as reportforumpost_reason_scams,
  _ as reportforumpost_reason_sensitiveordisturbing,
  _ as reportforumpost_reasonforreport,
  _ as setcooldown_clearcooldown,
  _ as setcooldown_clearopenreports,
  _ as setcooldown_cooldownsummary,
  _ as setcooldown_days,
  _ as setcooldown_dialogdescription,
  _ as setcooldown_dialogtitle,
  _ as setcooldown_errorloading,
  _ as setcooldown_expireson,
  _ as setcooldown_loading,
  _ as setcooldown_newcooldownlabel,
  _ as setcooldown_nocooldown,
  _ as setcooldown_setbutton,
  _ as setcooldown_statssummary,
};
