var _ = `malay`,
  _ = `Steam Workshop`,
  _ = `Steam Workshop untuk %1$s`,
  _ = `Masalah telah berlaku semasa memuatkan statistik permainan. Sila cuba lagi nanti.`,
  _ = `Ralat`,
  _ = `Masalah telah berlaku semasa melakukan tindakan tersebut. Sila cuba lagi kemudian. (%1$s)`,
  _ = `Maaf!`,
  _ = `Ralat telah berlaku semasa memproses permintaan anda:`,
  _ = `Anda telah membuat terlalu banyak permintaan. Sila tunggu sebentar dan cuba permintaan anda semula nanti.`,
  _ = `(Pentadbir Sahaja) Lihat Workshop Lama`,
  _ = `Melayari: %1$s`,
  _ = `(Undi untuk Kegemaran Anda)`,
  _ = `(Langgan untuk tambah ke dalam permainan anda)`,
  _ = `(Undi untuk Kegemaran Anda)`,
  _ = `Diterima untuk Permainan`,
  _ = `Diterima`,
  _ = `Kandungan Rasmi`,
  _ = `Oleh %1$s`,
  _ = `Item`,
  _ = `Item`,
  _ = `Koleksi`,
  _ = `Barang Niaga`,
  _ = `Video`,
  _ = `Pertanyaan yang Disimpan`,
  _ = `Simpan Pertanyaan Carian ini`,
  _ = `Masukkan nama untuk carian anda`,
  _ = `Simpan penapis carian semasa anda dan susun pilihan untuk digunakan semula dengan cepat pada masa akan datang. Anda boleh menemuinya di bawah 'Item Anda'.`,
  _ = `Simpan sebagai pertanyaan carian baharu atau pilih pertanyaan carian yang disimpan sebelum ini untuk dikemas kini`,
  _ = `<New Saved Search>`,
  _ = `Simpan`,
  _ = `Padam Carian Disimpan`,
  _ = `Adakah anda pasti mahu padamkan carian disimpan anda '%1$s'?`,
  _ = `Padam`,
  _ = `Ketahui Lebih Lanjut`,
  _ = `Kosongkan Carian`,
  _ = `Steam Workshop untuk %1$s`,
  _ = `Susunan`,
  _ = `Tempoh Masa`,
  _ = `Hari ini`,
  _ = `Satu Minggu`,
  _ = `Tiga Puluh Hari`,
  _ = `Tiga Bulan`,
  _ = `Enam Bulan`,
  _ = `Satu Tahun`,
  _ = `Sepanjang Masa`,
  _ = `%1$s (%2$s)`,
  _ = `Paling Terkini`,
  _ = `Paling Popular`,
  _ = `Rating Terbaik Sepanjang Masa`,
  _ = `Kemas Kini Terakhir`,
  _ = `Berat Laporan`,
  _ = `(Pentadbir) %1$s`,
  _ = `Paling Diperlukan oleh Item Lain`,
  _ = `Dalam Kebanyakan Koleksi`,
  _ = `(Pentadbir) Baris Gilir Kelulusan`,
  _ = `Belum Diberikan Rating`,
  _ = `Jumlah Pelanggan Unik`,
  _ = `Total Votes`,
  _ = `Most Up Votes`,
  _ = `Carian Berkaitan`,
  _ = `Masa Bermain Terkini`,
  _ = `Masa Bermain Seumur Hidup`,
  _ = `Purata Masa Bermain Terkini`,
  _ = `Purata Masa Bermain Seumur Hidup`,
  _ = `Sesi Main`,
  _ = `Sesi Main Sepanjang Hidup`,
  _ = `Inappropriate Score`,
  _ = `Ban Content Check`,
  _ = `Curated Admin`,
  _ = `Calon`,
  _ = `Rating dari Anda`,
  _ = `Tarikh Diterima`,
  _ = `Penapis Istimewa: `,
  _ = `Tiada`,
  _ = `Diterima untuk Permainan`,
  _ = `Dicipta oleh Rakan`,
  _ = `Dicipta oleh Pengikut`,
  _ = `Digemari oleh Rakan`,
  _ = `Dilaporkan (Pentadbir Sahaja)`,
  _ = `Diperlukan oleh Item Lain`,
  _ = `Dalam Koleksi`,
  _ = `Utama`,
  _ = `Layari`,
  _ = `Item Anda`,
  _ = `Perbincangan`,
  _ = `Tentang`,
  _ = `Cari %1$s`,
  _ = `Item yang anda telah siarkan (%1$s)`,
  _ = `Kegemaran anda (%1$s)`,
  _ = `Item Langganan (%1$s)`,
  _ = `Item Dimainkan (%1$s)`,
  _ = `Koleksi anda (%1$s)`,
  _ = `Giliran undian anda`,
  _ = `Maklumat Pembayaran Anda`,
  _ = `Lihat Hasil Anda`,
  _ = `(dari penjualan item Workshop anda)`,
  _ = `Lihat Perjanjian Undang-Undang`,
  _ = `Baris Gilir Undian`,
  _ = `Gunakan penapis`,
  _ = `Susun mengikut: %1$s`,
  _ = `<none selected>`,
  _ = `DLC Diperlukan`,
  _ = `DLC Diperlukan: %1$s`,
  _ = `Memerlukan DLC yang anda miliki`,
  _ = `Kecualikan item yang memerlukan DLC yang tidak dimiliki oleh anda`,
  _ = `Anda tidak memiliki sebarang DLC`,
  _ = `Anda memiliki semua DLC yang tersedia`,
  _ = `(%1$s item lagi)`,
  _ = `Termasuk Yang Dimiliki`,
  _ = `Kecualikan Tidak Dimilki`,
  _ = `Tapis mengikut Nama`,
  _ = `Tunjukkan item yang tidak serasi`,
  _ = `Sesetengah item tidak dapat dimasukkan ke dalam permainan. Anda masih boleh mencarinya jika memilih kotak ini.`,
  _ = `Lihat Items Tersembunyi & Hanya Untuk Rakan`,
  _ = `Keputusan untuk: "%1$s"`,
  _ = `Keputusan untuk: "%1$s" (tajuk sahaja)`,
  _ = `Keputusan untuk: "%1$s" (penerangan sahaja)`,
  _ = `Mengandungi item: "%1$s"`,
  _ = `Memerlukan "%1$s" untuk berfungsi dengan betul`,
  _ = `%1$s: %2$s`,
  _ = `%1$s: %2$s`,
  _ = `Tag: Item tidak serasi`,
  _ = `Tag: Item yang diterima`,
  _ = `Nyatakan medan teks item yang ingin anda cari:`,
  _ = `Tajuk & Penerangan`,
  _ = `Tajuk Sahaja`,
  _ = `Penerangan Sahaja`,
  _ = `Anda boleh membina carian yang lebih kompleks menggunakan operator %1$s, %2$s dan %3$s (mesti ditulis dengan huruf besar). Secara alternatif, anda boleh menggunakan aksara %4$s dan %5$s sebagai singkatan untuk %1$s dan %3$s.`,
  _ = `%1$s mencari item dengan kedua-dua '%2$s' dan '%3$s' dalam teks carian`,
  _ = `%1$s mencari item dengan '%2$s' atau '%3$s' dalam teks carian`,
  _ = `%1$s mencari item dengan '%2$s' tetapi bukan '%3$s' dalam teks carian`,
  _ = `merah`,
  _ = `biru`,
  _ = `hijau`,
  _ = `bilik`,
  _ = `Menggabungkan istilah carian dengan kurungan membolehkan anda membina beberapa carian yang sangat spesifik.`,
  _ = `%1$s mencari item yang mengandungi '%2$s', dipadankan dengan '%3$s' atau '%4$s' dalam teks carian.`,
  _ = `%1$s mencari item dengan '%2$s' dan '%3$s' atau '%4$s', tetapi bukan '%5$s' dalam teks carian.`,
  _ = `Kedudukan dikehendaki untuk penapis:`,
  _ = `Sebelah Kiri`,
  _ = `Sebelah Kanan`,
  _ = `Diruntuhkan`,
  _ = `Malapkan item ini:`,
  _ = `Dilaporkan oleh anda`,
  _ = `Dicipta oleh pengguna yang telah anda sekat`,
  _ = `Diundi positif oleh anda`,
  _ = `Diundi negatif oleh anda`,
  _ = `Dalam senarai langganan anda`,
  _ = `Tapis mengikut Tarikh`,
  _ = `Tarikh Siaran`,
  _ = `Disiarkan selepas %1$s`,
  _ = `Disiarkan sebelum %1$s`,
  _ = `Disiarkan antara %1$s dan %2$s`,
  _ = `Tarikh Terakhir Dikemas Kini`,
  _ = `Dikemas kini selepas %1$s`,
  _ = `Dikemas kini sebelum %1$s`,
  _ = `Dikemas kini antara %1$s dan %2$s`,
  _ = `Antara`,
  _ = `Dan`,
  _ = `1 entri yang sepadan dengan penapis`,
  _ = `%2$s entri yang sepadan dengan penapis`,
  _ = `Setiap halaman:`,
  _ = `%1$s / %2$s`,
  _ = `Cipta Koleksi`,
  _ = `Hantar rekaan anda`,
  _ = `Paparan Pantas`,
  _ = `Lihat Lagi`,
  _ = `Anda melanggan item ini`,
  _ = `Item ini berada dalam senarai Kegemaran anda`,
  _ = `Anda telah bermain item ini`,
  _ = `Item ini telah diterima untuk digunakan dalam permainan ini!`,
  _ = `Item ini telah ditandakan sebagai tidak serasi untuk permainan ini.`,
  _ = `Anda memberi item ini rating Suka.`,
  _ = `Anda memberi item ini rating Tidak Suka.`,
  _ = `Anda telah melaporkan item ini kerana melanggar Garis Panduan Komuniti Steam.`,
  _ = `Anda telah menyekat pengguna ini.`,
  _ = `Penerangan`,
  _ = `Perbincangan`,
  _ = `Komen: (%1$s)`,
  _ = `Pengumuman`,
  _ = `Statistik Item`,
  _ = `Nota Perubahan (%1$s)`,
  _ = `Steam Workshop :: %1$s`,
  _ = `Dicipta oleh: `,
  _ = `Rating %2$s`,
  _ = `%2$s rating`,
  _ = `Rating tidak mencukupi`,
  _ = `%1$s @ %2$s`,
  _ = `Disiarkan:`,
  _ = `Dikemas kini:`,
  _ = `Langgan`,
  _ = `Dilanggan`,
  _ = `Berhenti Melanggan`,
  _ = `Kegemaran`,
  _ = `Digemari`,
  _ = `Tidak Digemari`,
  _ = `Lihat Item Bergantung`,
  _ = `Tambah ke Koleksi`,
  _ = `Simpan ke Koleksi`,
  _ = `Sila log masuk untuk mengambil tindakan ini`,
  _ = `Langgan untuk memuat turun`,
  _ = `Berhenti melanggan untuk mengalih keluar item ini dari permainan anda`,
  _ = `Cari item ini dengan mudah kemudian`,
  _ = `Lihat semua item %1$s yang bergantung pada item ini untuk berfungsi dengan betul. Ambil perhatian bahawa sesetengahnya mungkin ditanda tersembunyi atau hanya untuk rakan.`,
  _ = `Laporkan item ini kerana melanggar Peraturan Tingkah Laku Dalam Talian Steam`,
  _ = `Anugerah`,
  _ = `Tambah ke salah satu koleksi anda`,
  _ = `Saiz Fail:`,
  _ = `Pelawat:`,
  _ = `Pelanggan:`,
  _ = `Kegemaran:`,
  _ = `Jumlah Kegemaran Unik:`,
  _ = `Jumlah Pelanggan Unik:`,
  _ = `Jumlah Sesi Permainan:`,
  _ = `Memerlukan item berikut: `,
  _ = `Memerlukan DLC berikut: `,
  _ = `Langgan semua`,
  _ = `Berhenti langgan semua`,
  _ = `Simpan ke Koleksi`,
  _ = `Kembangkan semua Anugerah Komuniti`,
  _ = `%1$s Anugerah Komuniti`,
  _ = `%1$s Anugerah Komuniti`,
  _ = `TAG`,
  _ = `KATEGORI`,
  _ = `PENERANGAN`,
  _ = `Diperlukan Oleh:`,
  _ = `Dalam Koleksi %1$s`,
  _ = `Dalam Koleksi %1$s oleh %2$s`,
  _ = `Ralat`,
  _ = `Anda tidak mempunyai kebenaran untuk membuat tindakan tersebut.`,
  _ = `Masalah telah berlaku semasa menghubungi Steam. Sila cuba lagi nanti.`,
  _ = `Anda telah cuba melakukan terlalu banyak tindakan dalam tempoh masa yang singkat. Sila tunggu sebentar sebelum mencuba lagi.`,
  _ = `Masalah telah berlaku semasa cuba melaksanakan tindakan itu. Sila cuba lagi nanti.`,
  _ = `Langgan Semua`,
  _ = `Adakah anda ingin menambah item dalam koleksi ini pada langganan anda, atau menggantikan langganan anda untuk hanya mengandungi item daripada koleksi ini?`,
  _ = `Tambah Sahaja`,
  _ = `Gantikan Langganan Saya`,
  _ = `Item Tambahan Diperlukan`,
  _ = `Item ini memerlukan semua item yang berikut supaya dapat berfungsi dengan betul.`,
  _ = `<1>%1$s</1> memerlukan semua item lain yang berikut untuk berfungsi dengan betul.`,
  _ = `Anda boleh klik pada setiap satu di sini untuk mengetahui lebih lanjut dan melanggan item sebelum meneruskan.`,
  _ = `Anda juga boleh memilih untuk melanggan semua item yang diperlukan (dan semua item yang mereka perlukan), tetapi dengan amaran bahawa ini mungkin termasuk banyak lagi item lain.`,
  _ = `Langgan Item Ini Sahaja`,
  _ = `Langgan Semua`,
  _ = `Laporkan item ini`,
  _ = `Sekarang, sila jelaskan bagaimana item ini melanggar Syarat Perkhidmatan Steam. Sila sertakan sebarang maklumat atau pautan yang berkaitan. Laporan yang difailkan tidak boleh dibatalkan.`,
  _ = `Sebab: "%1$s"`,
  _ = `Pertama, pilih sebab mengapa anda melaporkan item ini:`,
  _ = `Jika anda ingin melaporkan Pelanggaran Hak Cipta dan anda merupakan pemilik hak cipta, sila teruskan ke borang notis pelanggaran hak cipta kami yang mematuhi DMCA %1$s.`,
  _ = `Jika anda ingin membuat aduan Tanda Dagangan, sila failkan satu %1$s.`,
  _ = `di sini`,
  _ = `Tambah ke Koleksi`,
  _ = `'%1$s' akan ditambah ke dalam koleksi pilihan di bawah:`,
  _ = `Anda tiada koleksi yang disimpan. Anda boleh mencipta koleksi baharu dengan memasukkan nama untuknya di bawah.`,
  _ = `Tambah ke Koleksi Pilihan`,
  _ = `Cipta Koleksi Baharu`,
  _ = `Gantikan Koleksi`,
  _ = `Adakah anda ingin menyimpan koleksi ini ke koleksi baharu atau menggantikan koleksi sedia ada?`,
  _ = `Koleksi Baharu`,
  _ = `Koleksi Sedia Ada`,
  _ = `Masukkan nama untuk koleksi ini:`,
  _ = `Pilih koleksi untuk gantikan:`,
  _ = `Mengandungi %2$s item`,
  _ = `Mengandungi %2$s item`,
  _ = `Mempunyai %2$s koleksi terpaut`,
  _ = `Mempunyai %2$s koleksi terpaut`,
  _ = `+%1$s`,
  _ = `Steam Workshop memudahkan anda menghantar model 3D item yang telah siap untuk berpeluang diterima dan dimasukkan ke dalam permainan sebenar. Untuk menerbitkan item ke Workshop bagi dipertimbangan, baca dahulu dokumentasi rasmi yang dipautkan di sebelah kanan, kemudian klik butang Steam Workshop di menu utama permainan.`,
  _ = `Steam Workshop memudahkan anda menemui atau berkongsi kandungan baharu untuk permainan atau perisian anda. Setiap permainan atau perisian mungkin menyokong jenis kandungan yang sedikit berbeza dalam Workshop mereka. Sebaiknya, semak dokumentasi rasmi untuk maklumat lanjut tentang apa yang boleh dicipta dan dikongsi.`,
  _ = `Apabila anda menemui kandungan yang ingin ditambah ke dalam permainan anda, klik butang ‘Langgan’. Dalam kebanyakan kes, kandungan tersebut akan automatik tersedia apabila anda melancarkan semula permainan. Namun, sesetengah produk memerlukan anda masuk ke bahagian khas dalam permainan atau perisian untuk mengaktifkan atau mengakses kandungan baharu tersebut.`,
  _ = `Steam Workshop memudahkan anda menemui atau berkongsi kandungan baharu untuk permainan atau perisian anda. Setiap tajuk mungkin menyokong jenis kandungan yang sedikit berbeza dalam Workshop mereka. Sebaiknya, semak dokumentasi rasmi untuk maklumat lanjut tentang apa yang boleh dicipta dan dikongsi.`,
  _ = `Apabila anda menemui kandungan di bawah tab %1$s yang ingin ditambah ke dalam permainan anda, klik butang ‘Langgan’. Dalam kebanyakan kes, kandungan tersebut akan automatik tersedia apabila anda melancarkan semula permainan. Namun, sesetengah produk memerlukan anda masuk ke bahagian khas dalam permainan atau perisian untuk mengaktifkan atau mengakses kandungan baharu tersebut.`,
  _ = `Ciri Didayakan`,
  _ = `Ciri Steam Workshop yang digunakan oleh %1$s:`,
  _ = `Item Sedia Digunakan`,
  _ = `Item yang disiarkan dalam Workshop ini sedia untuk terus digunakan. Klik butang Langgan pada halaman butiran item tersebut dan item akan tersedia apabila anda memulakan %1$s.`,
  _ = `Item yang disiarkan dalam Workshop ini di bawah tab %2$s sedia untuk terus digunakan. Klik butang Langgan pada halaman butiran item tersebut dan item akan tersedia apabila anda memulakan %1$s.`,
  _ = `Sokongan Versi untuk Cabang Permainan`,
  _ = `Item boleh mempunyai versi yang berkaitan dengan cabang (beta) permainan berbeza. Ini memudahkan pembangun dan pengarang item Workshop bekerjasama bagi memastikan keserasian item mereka apabila %1$s menerima kemas kini.`,
  _ = `Pemilihan Item Terpilih`,
  _ = `Item yang disiarkan dalam Workshop ini tidak boleh terus digunakan di %1$s. Sebaliknya, pembangun berharap komuniti dapat menilai item yang paling mereka ingin lihat tersedia untuk dibeli atau dibuka dalam %1$s. Pembangun akan memilih item yang akan dipilih dan ditambah ke dalam %1$s.`,
  _ = `Item yang disiarkan dalam Workshop ini di bawah tab %2$s tidak boleh terus digunakan di %1$s. Pembangun berharap komuniti dapat menilai item yang paling mereka ingin lihat tersedia untuk dibeli atau dibuka dalam %1$s. Pembangun akan memilih item yang akan dipilih dan ditambah ke dalam %1$s.`,
  _ = `Jualan Item`,
  _ = `Item yang diterima daripada Workshop akan tersedia untuk dibeli atau boleh dibuka dalam %1$s.`,
  _ = `Jualan Langsung Item`,
  _ = `Item dalam Workshop ini mungkin disenaraikan untuk dijual secara langsung melalui Steam Workshop. Item ini mungkin memerlukan kelulusan daripada pembangun atau komuniti sebelum tersedia. Pencipta Kandungan: Lihat bahagian <a %s>Menjana Wang</a> di bawah untuk mengetahui lebih lanjut tentang cara menjual kandungan anda di Steam Workshop`,
  _ = `Pencipta Item Boleh Mendapat Royalti`,
  _ = `Item daripada Workshop ini yang diterima untuk dijual akan membayar sebahagian daripada hasil kepada pencipta jika item tersebut dijual dengan bayaran tertentu.`,
  _ = `Pembekal Perkhidmatan Boleh Mendapat Royalti`,
  _ = `Pengarang Workshop boleh memilih daripada senarai organisasi, pengguna, dan pembangun alat yang telah diluluskan terlebih dahulu untuk menerima peratusan hasil Valve daripada penjualan item mereka. Organisasi dan individu tertentu disenaraikan di bawah.`,
  _ = `Adakah anda pencipta kandungan dan mengenali organisasi atau individu lain yang ingin anda kongsikan kejayaan penjualan item anda? Sila maklumkan kepada kami <a href="%1$s">di sini</a>.`,
  _ = `Bahagian Hasil`,
  _ = `Ini adalah peratusan hasil yang diterima oleh pencipta item daripada jualan langsung item mereka.`,
  _ = `Klik %1$s untuk mengetahui lebih lanjut.`,
  _ = `di sini`,
  _ = `Item yang disiarkan dalam Workshop ini`,
  _ = `Item diterima untuk %1$s`,
  _ = `Pautan Berkaitan`,
  _ = `Lihat Dokumentasi Rasmi`,
  _ = `Cari Panduan Steam`,
  _ = `Panduan buatan komuniti untuk Workshop ini`,
  _ = `Untuk pembelian melalui Steam Workshop`,
  _ = `Terma Steam Workshop`,
  _ = `Untuk Hasil Steam Workshop`,
  _ = `Penyedia Perkhidmatan`,
  _ = `Lihat Laman`,
  _ = `Lihat Profil Steam`,
  _ = `Alat`,
  _ = `Komuniti`,
  _ = `Pengguna`,
  _ = `Lihat Butiran`,
  _ = `Paparan Pantas`,
  _ = `Undi`,
  _ = `untuk item buatan komuniti yang anda ingin lihat dalam permainan`,
  _ = `Klik untuk mula mengundi dalam Baris Gilir anda.`,
  _ = `Anda telah mengundi item %1$s setakat ini.`,
  _ = `Anda telah mengundi %1$s item setakat ini.`,
  _ = `Minggu lalu`,
  _ = `Bulan lepas`,
  _ = `Tiga bulan lepas`,
  _ = `Enam bulan lepas`,
  _ = `Tahun lepas`,
  _ = `Daripada Pengarang Diikuti`,
  _ = `Item yang baru disiarkan oleh pengarang anda ikuti`,
  _ = `Lagi daripada pengarang yang diikuti`,
  _ = `Item yang diterima`,
  _ = `Item berikut telah diterima dan mungkin tersedia sebagai drop atau boleh dibeli dalam permainan`,
  _ = `Lihat semua Item yang Diterima`,
  _ = `Paling Popular %1$s`,
  _ = `Paling Popular`,
  _ = `Rating terbaik dalam tempoh tiga bulan lalu`,
  _ = `Lihat paling popular`,
  _ = `Paling Dilanggan`,
  _ = `Pelanggan unik terkini terbanyak`,
  _ = `Lihat paling banyak dilanggan`,
  _ = `Baharu`,
  _ = `Item terkini disiarkan`,
  _ = `Lihat siaran terkini`,
  _ = `Masa Main Terbanyak`,
  _ = `Lihat paling banyak dimainkan`,
  _ = `Kemas Kini Terakhir`,
  _ = `Item dikemas kini terkini`,
  _ = `Lihat kemas kini terkini`,
  _ = `Kegemaran Rakan`,
  _ = `Item yang ditanda sebagai kegemaran oleh rakan anda`,
  _ = `Lihat semua kegemaran rakan`,
  _ = `Paling Diperlukan oleh Item Lain`,
  _ = `Item paling popular yang diperlukan oleh item lain untuk berfungsi dengan baik`,
  _ = `Lihat Semua`,
  _ = `Barang Niaga Paling Popular`,
  _ = `Lihat semua Barang Niaga Popular`,
  _ = `Lihat Semua`,
  _ = `Kegemaran Anda`,
  _ = `Lihat kegemaran yang terkini dikemas kini`,
  _ = `Item Anda Mainkan`,
  _ = `Lihat item terkini yang anda mainkan dan baharu dikemas kini`,
  _ = `Langganan Anda`,
  _ = `Lihat langganan anda yang baharu dikemas kini`,
  _ = `Dikemas kini dalam tempoh tiga bulan lalu`,
  _ = `Acara Istimewa: %1$s`,
  _ = `Lihat semua item yang ditag dengan %1$s`,
  _ = `%1$s rakan telah menambah ini ke Kegemaran mereka`,
  _ = `%1$s rakan telah menambah ini ke Kegemaran mereka`,
  _ = `Peta`,
  _ = `Item`,
  _ = `Permainan Tersuai dan Skrip Bot`,
  _ = `Item`,
  _ = `Tapis Mengikut Hero`,
  _ = `Peta`,
  _ = `Item`,
  _ = {
    language: _,
    Header_WorkshopTitle: _,
    Header_App_WorkshopTitle: _,
    Workshop_Error_Loading: _,
    Workshop_Error_Title: _,
    Workshop_Error_Browse_Desc: _,
    Error_Sorry: _,
    Error_Encountered: _,
    Error_TooManyRequests_Description: _,
    Workshop_ExitReact_Link: _,
    Workshop_Browsing: _,
    Workshop_Browsing_Mtx_Desc: _,
    Workshop_Browsing_ReadyToUse_Desc: _,
    Workshop_Browsing_Merchandise_Desc: _,
    Workshop_AcceptedForGame: _,
    Workshop_AcceptedMerch: _,
    Workshop_OfficialContent: _,
    Workshop_Browse_Author_Link: _,
    Workshop_Section_Mtx: _,
    Workshop_Section_ReadyToUse: _,
    Workshop_Section_Collections: _,
    Workshop_Section_Merchandise: _,
    Workshop_Section_Videos: _,
    Workshop_Saved_Queries: _,
    Workshop_Saved_Queries_Update: _,
    Workshop_Saved_Queries_Save_Title: _,
    Workshop_Saved_Queries_Save_Desc_Long: _,
    Workshop_Saved_Queries_Save_Desc: _,
    Workshop_Saved_Queries_Save_New: _,
    Workshop_Saved_Queries_Save_Btn: _,
    Workshop_Saved_Queries_Delete_Title: _,
    Workshop_Saved_Queries_Delete_Desc: _,
    Workshop_Saved_Queries_Delete_Btn: _,
    Workshop_LearnMore: _,
    Workshop_Filters_ClearBtn: _,
    Workshop_About: _,
    Workshop_BrowseSort_SortOrder: _,
    Workshop_BrowseSort_TimeFrame: _,
    SharedFiles_Browse_Trend_Option_Today: _,
    SharedFiles_Browse_Trend_Option_Week: _,
    SharedFiles_Browse_Trend_Option_Month: _,
    SharedFiles_Browse_Trend_Option_ThreeMonths: _,
    SharedFiles_Browse_Trend_Option_SixMonths: _,
    SharedFiles_Browse_Trend_Option_OneYear: _,
    SharedFiles_Browse_Trend_Option_AllTime: _,
    Workshop_BrowseSort_Combined: _,
    Workshop_BrowseSort_MostRecent: _,
    Workshop_BrowseSort_MostPopular: _,
    Workshop_BrowseSort_TopRated: _,
    Workshop_BrowseSort_LastUpdated: _,
    Workshop_BrowseSort_Reported: _,
    Workshop_BrowseSort_AdminOption: _,
    Workshop_BrowseSort_NumParentItems: _,
    Workshop_BrowseSort_NumParentCollections: _,
    Workshop_RequireApproval: _,
    Workshop_BrowseSort_ToRate: _,
    Workshop_BrowseSort_TotalUniqueSubscribers: _,
    Workshop_BrowseSort_TotalVotes: _,
    Workshop_BrowseSort_MostUpVotes: _,
    Workshop_BrowseSort_SearchRelevance: _,
    Workshop_BrowseSort_Playtime: _,
    Workshop_BrowseSort_PlaytimeTotal: _,
    Workshop_BrowseSort_PlaytimeAverage: _,
    Workshop_BrowseSort_PlaytimeAverageTotal: _,
    Workshop_BrowseSort_PlaytimeSessions: _,
    Workshop_BrowseSort_PlaytimeSessionsTotal: _,
    Workshop_BrowseSort_Inappropriate: _,
    Workshop_BrowseSort_BanContentCheck: _,
    Workshop_BrowseSort_CuratedAdmin: _,
    Workshop_BrowseSort_Nominee: _,
    Workshop_BrowseSort_Rated: _,
    Workshop_BrowseSort_AcceptedTime: _,
    Workshop_SpecialFilter_Desc: _,
    Workshop_SpecialFilter_None: _,
    Workshop_SpecialFilter_AcceptedForUse: _,
    Workshop_SpecialFilter_CreatedByFriends: _,
    Workshop_SpecialFilter_CreatedByFollowed: _,
    Workshop_SpecialFilter_FavoritedByFriends: _,
    Workshop_SpecialFilter_Reported: _,
    Workshop_SpecialFilter_ParentItems: _,
    Workshop_SpecialFilter_ParentCollections: _,
    Workshop_Menu_Home: _,
    Workshop_Menu_Browse: _,
    Workshop_Menu_YourItems: _,
    Workshop_Menu_Discussions: _,
    Workshop_Menu_About: _,
    Workshop_Menu_Search: _,
    Workshop_SubMenu_YourItems: _,
    Workshop_SubMenu_YourFavorites: _,
    Workshop_SubMenu_YourSubscriptions: _,
    Workshop_SubMenu_YourPlayed: _,
    Workshop_SubMenu_YourCollections: _,
    Workshop_SubMenu_YourVotingQueue: _,
    Workshop_SubMenu_YourPaymentInfo: _,
    Workshop_SubMenu_ViewYourRevenue: _,
    Workshop_SubMenu_ViewYourRevenue_Desc: _,
    Workshop_SubMenu_LegalAgreement: _,
    Workshop_SubMenu_VotingQueue: _,
    Workshop_ApplyFilters: _,
    Workshop_SortBy: _,
    Workshop_Tag_NoneSpecified: _,
    Workshop_RequiredDLC_Header: _,
    Workshop_RequiredDLC_Filter: _,
    Workshop_IncludeOwnedDLC_Filter: _,
    Workshop_ExcludeOwnedDLC_Filter: _,
    Workshop_OwnedDLC_None_Filter: _,
    Workshop_OwnedDLC_All_Filter: _,
    Workshop_OwnedDLC_More_Filter: _,
    Workshop_RequiredDLC_IncludeOwned: _,
    Workshop_RequiredDLC_ExcludeUnowned: _,
    Workshop_RequiredDLC_NameFilter: _,
    Workshop_Flag_Incompatible_Checkbox: _,
    Workshop_Flag_Incompatible_Checkbox_Desc: _,
    Workshop_Admin_View: _,
    Workshop_SearchResults_SearchText: _,
    Workshop_SearchResults_SearchText_TitleOnly: _,
    Workshop_SearchResults_SearchText_DescriptionOnly: _,
    Workshop_SearchedForChild: _,
    Workshop_SearchedForRequiredItem: _,
    Workshop_SearchResults_Tag: _,
    Workshop_SearchResults_KVTag: _,
    Workshop_SearchResults_Flag_Incompatible: _,
    Workshop_SearchResults_Flag_Accepted: _,
    Workshop_SearchTarget_MenuTitle: _,
    Workshop_SearchTarget_All: _,
    Workshop_SearchTarget_Title: _,
    Workshop_SearchTarget_Description: _,
    Workshop_Search_Help: _,
    Workshop_Search_Help_Example1: _,
    Workshop_Search_Help_Example2: _,
    Workshop_Search_Help_Example3: _,
    Workshop_Search_Help_Example_Red: _,
    Workshop_Search_Help_Example_Blue: _,
    Workshop_Search_Help_Example_Green: _,
    Workshop_Search_Help_Example_Room: _,
    Workshop_Search_Help_Advanced: _,
    Workshop_Search_Help_AdvancedExample1: _,
    Workshop_Search_Help_AdvancedExample2: _,
    Workshop_FiltersMenu_State_Title: _,
    Workshop_FiltersMenu_State_Left: _,
    Workshop_FiltersMenu_State_Right: _,
    Workshop_FiltersMenu_State_Collapsed: _,
    Workshop_DimmedItems_Title: _,
    Workshop_DimmedItems_Reported: _,
    Workshop_DimmedItems_BlockedCreators: _,
    Workshop_DimmedItems_VotedUp: _,
    Workshop_DimmedItems_VotedDown: _,
    Workshop_DimmedItems_Subscribed: _,
    Workshop_DateFilter_FilterByDate: _,
    Workshop_DateFilter_TimeCreated: _,
    Workshop_DateFilter_TimeCreated_After: _,
    Workshop_DateFilter_TimeCreated_Before: _,
    Workshop_DateFilter_TimeCreated_Between: _,
    Workshop_DateFilter_TimeUpdated: _,
    Workshop_DateFilter_TimeUpdated_After: _,
    Workshop_DateFilter_TimeUpdated_Before: _,
    Workshop_DateFilter_TimeUpdated_Between: _,
    Workshop_DateFilter_Between: _,
    Workshop_DateFilter_And: `Dan`,
    Workshop_NumResults: _,
    Workshop_NumResults_Plural: _,
    Workshop_NumPerPage: _,
    Workshop_PagingControls: _,
    Workshop_CreateCollection: _,
    Workshop_CreateMerchandise: _,
    Workshop_Item_QuickView: _,
    Workshop_Item_QuickView_ExpandBtn: _,
    Workshop_StatusIcon_TT_Subscribed: _,
    Workshop_StatusIcon_TT_Favorited: _,
    Workshop_StatusIcon_TT_Played: _,
    Workshop_StatusIcon_TT_Accepted: _,
    Workshop_StatusIcon_TT_Incompatible: _,
    Workshop_StatusIcon_TT_VotedUp: _,
    Workshop_StatusIcon_TT_VotedDown: _,
    Workshop_StatusIcon_TT_Reported: _,
    Workshop_StatusIcon_TT_BlockedCreator: _,
    Workshop_ItemDetails_Tab_Description: _,
    Workshop_ItemDetails_Tab_Discussions: _,
    Workshop_ItemDetails_Tab_Comments: _,
    Workshop_ItemDetails_Tab_Updates: _,
    Workshop_ItemDetails_Tab_Stats: _,
    Workshop_ItemDetails_Tab_ChangeNotes: _,
    Workshop_ItemDetails_Title: _,
    Workshop_ItemDetails_CreatedBy: _,
    Workshop_ItemDetails_NumRatings: _,
    Workshop_ItemDetails_NumRatings_Plural: _,
    Workshop_ItemDetails_NotEnoughRatings: _,
    Workshop_ItemDetails_TimestampWithTime: _,
    Workshop_ItemDetails_TimestampCreated: _,
    Workshop_ItemDetails_TimestampUpdated: _,
    Workshop_ItemDetails_Subscribe: _,
    Workshop_ItemDetails_Subscribed: _,
    Workshop_ItemDetails_Unsubscribe: _,
    Workshop_ItemDetails_Favorite: _,
    Workshop_ItemDetails_Favorited: _,
    Workshop_ItemDetails_Unfavorite: _,
    Workshop_ItemDetails_ViewDependentItems: _,
    Workshop_ItemDetails_AddToCollection: _,
    Workshop_ItemDetails_SaveCollectionToCollection: _,
    Workshop_ItemDetails_Signin_TT: _,
    Workshop_ItemDetails_Subscribe_TT: _,
    Workshop_ItemDetails_Unsubscribe_TT: _,
    Workshop_ItemDetails_Favorite_TT: _,
    Workshop_ItemDetails_ViewDependentItems_TT: _,
    Workshop_ItemDetails_Report_TT: _,
    Workshop_ItemDetails_Award_TT: _,
    Workshop_ItemDetails_AddToCollection_TT: _,
    Workshop_ItemDetails_FileSize: _,
    Workshop_ItemDetails_Stats_UniqueVisitors: _,
    Workshop_ItemDetails_Stats_CurrentSubscribers: _,
    Workshop_ItemDetails_Stats_CurrentFavorites: _,
    Workshop_ItemDetails_Stats_LifetimeFavorites: _,
    Workshop_ItemDetails_Stats_LifetimeSubscribers: _,
    Workshop_ItemDetails_Stats_LifetimePlaytimeSessions: _,
    Workshop_ItemDetails_ItemDependencies: _,
    Workshop_ItemDetails_RequiredDLC_Desc: _,
    Workshop_Collection_SubscribeToAll: _,
    Workshop_Collection_UnsubscribeFromAll: _,
    Workshop_Collection_SaveToCollection: _,
    Workshop_ItemDetails_ShowAllReactions: _,
    Workshop_ItemDetails_ReactionCount: _,
    Workshop_ItemDetails_ReactionCount_Plural: _,
    Workshop_ItemDetails_Tags_Title: `TAG`,
    Workshop_ItemDetails_Categories_Title: _,
    Workshop_ItemDetails_Description_Title: _,
    Workshop_ItemDetails_DependentItems: _,
    Workshop_ItemDetails_InCollections: _,
    Workshop_ItemDetails_InCollectionsByAuthor: _,
    Workshop_Dialog_Error: _,
    Workshop_Dialog_AccessDenied: _,
    Workshop_Dialog_Timeout: _,
    Workshop_Dialog_LimitExceeded: _,
    Workshop_Dialog_ErrorDesc: _,
    Workshop_Dialog_CollectionSubscribe: _,
    Workshop_Dialog_CollectionSubscribe_Desc: _,
    Workshop_Dialog_CollectionSubscribe_AddOnly: _,
    Workshop_Dialog_CollectionSubscribe_Overwrite: _,
    Workshop_Dialog_ItemDependencies: _,
    Workshop_Dialog_ItemDependencies_Desc1: _,
    Workshop_Dialog_ItemDependencies_Desc1_itemName: _,
    Workshop_Dialog_ItemDependencies_Desc2: _,
    Workshop_Dialog_ItemDependencies_Desc3: _,
    Workshop_Dialog_SubscribeJustThisItem: _,
    Workshop_Dialog_SubscribeAll: _,
    Workshop_Dialog_Report: _,
    Workshop_Dialog_Report_Desc: _,
    Workshop_Dialog_Report_Reason: _,
    Workshop_Dialog_Report_Reason_Desc: _,
    Workshop_Dialog_Report_DMCA_Desc: _,
    Workshop_Dialog_Report_Trademark_Desc: _,
    Workshop_Dialog_Report_Here: _,
    Workshop_Dialog_AddToCollection: _,
    Workshop_Dialog_AddToCollection_Desc: _,
    Workshop_Dialog_AddToCollection_NoSavedCollections_Desc: _,
    Workshop_Dialog_AddToCollection_OK: _,
    Workshop_Dialog_AddToCollection_Create: _,
    Workshop_Dialog_SaveCollectionToCollection: _,
    Workshop_Dialog_SaveCollectionToCollection_Desc: _,
    Workshop_Dialog_SaveCollectionToCollection_New: _,
    Workshop_Dialog_SaveCollectionToCollection_Existing: _,
    Workshop_Dialog_SaveCollectionToCollection_NewPrompt: _,
    Workshop_Dialog_SaveCollectionToCollection_Select: _,
    Workshop_Collection_NumChildItems: _,
    Workshop_Collection_NumChildItems_Plural: _,
    Workshop_Collection_NumChildCollections: _,
    Workshop_Collection_NumChildCollections_Plural: _,
    Workshop_Collection_ViewMore: _,
    Workshop_About_PageDesc_Curation: _,
    Workshop_About_PageDesc_ReadyToUseContent1: _,
    Workshop_About_PageDesc_ReadyToUseContent2: _,
    Workshop_About_PageDesc_ReadyToUseContent_Mixed1: _,
    Workshop_About_PageDesc_ReadyToUseContent_Mixed2: _,
    Workshop_About_EnabledFeatures: _,
    Workshop_About_EnabledFeatures_Desc: _,
    Workshop_About_Feature_ReadyToUse: _,
    Workshop_About_Feature_ReadyToUse_Desc: _,
    Workshop_About_Feature_ReadyToUse_Mixed_Desc: _,
    Workshop_About_Feature_Branch_Versioning: _,
    Workshop_About_Feature_Branch_Versioning_Desc: _,
    Workshop_About_Feature_ItemCuration: _,
    Workshop_About_Feature_ItemCuration_Desc: _,
    Workshop_About_Feature_ItemCuration_Mixed_Desc: _,
    Workshop_About_Feature_ItemMtx: _,
    Workshop_About_Feature_ItemMtx_Desc: _,
    Workshop_About_Feature_Commerce: _,
    Workshop_About_Feature_Commerce_Desc: _,
    Workshop_About_Feature_AuthorRoyalties: _,
    Workshop_About_Feature_AuthorRoyalties_Desc: _,
    Workshop_About_Feature_ServiceProviders: _,
    Workshop_About_Feature_ServiceProviders_Desc: _,
    Workshop_About_Request_ServiceProviders: _,
    Workshop_About_RevenueShare: _,
    Workshop_About_RevenueShare_Desc: _,
    Workshop_About_RevenueShare_Link: _,
    Workshop_About_RevenueShare_Here: _,
    Workshop_About_NumItems: _,
    Workshop_About_NumAcceptedItems: _,
    Workshop_About_RelatedLinks: _,
    Workshop_About_ViewOfficialDocs: _,
    Workshop_About_FindGuides: _,
    Workshop_About_FindGuides_Sub: _,
    Workshop_About_RefundLink_Sub: _,
    Workshop_About_WorkshopTerms: _,
    Workshop_About_WorkshopTerms_Sub: _,
    Workshop_About_section_ServiceProviders: _,
    Workshop_ServiceProviderRevenueSharing_ViewSite: _,
    Workshop_ServiceProviderRevenueSharing_ViewSteamProfile: _,
    Workshop_ServiceProvider_Category_Tools: _,
    Workshop_ServiceProvider_Category_Communities: _,
    Workshop_ServiceProvider_Category_Users: _,
    Workshop_GamepadUIAction_ViewDetails: _,
    Workshop_GamepadUIAction_QuickView: _,
    Workshop_Home_VotingQueue: _,
    Workshop_Home_VotingQueue_Desc: _,
    Workshop_Home_VotingQueue_Btn: _,
    Workshop_Home_VotingQueue_Count: _,
    Workshop_Home_VotingQueue_Count_Plural: _,
    Workshop_Home_MostPopular_SubTitle_Week: _,
    Workshop_Home_MostPopular_SubTitle_Month: _,
    Workshop_Home_MostPopular_SubTitle_ThreeMonths: _,
    Workshop_Home_MostPopular_SubTitle_SixMonths: _,
    Workshop_Home_MostPopular_SubTitle_Year: _,
    Workshop_Home_FromFollowedAuthors: _,
    Workshop_Home_FromFollowedAuthors_Desc: _,
    Workshop_Home_FromFollowedAuthors_Btn: _,
    Workshop_Home_AcceptedItems: _,
    Workshop_Home_AcceptedItems_Desc: _,
    Workshop_Home_AcceptedItems_Btn: _,
    Workshop_Home_MostPopular: _,
    Workshop_Home_MostPopular_LongTerm: _,
    Workshop_Home_MostPopular_LongTerm_Desc: _,
    Workshop_Home_MostPopular_LongTerm_Btn: _,
    Workshop_Home_MostSubscribed: _,
    Workshop_Home_MostSubscribed_Desc: _,
    Workshop_Home_MostSubscribed_Btn: _,
    Workshop_Home_MostRecent: _,
    Workshop_Home_MostRecent_Desc: _,
    Workshop_Home_MostRecent_Btn: _,
    Workshop_Home_MostPlaytime: _,
    Workshop_Home_MostPlaytime_Btn: _,
    Workshop_Home_LastUpdated: _,
    Workshop_Home_LastUpdated_Desc: _,
    Workshop_Home_LastUpdated_Btn: _,
    Workshop_Home_FriendsFavorites: _,
    Workshop_Home_FriendsFavorites_Desc: _,
    Workshop_Home_FriendsFavorites_Btn: _,
    Workshop_Home_NumParentItems: _,
    Workshop_Home_NumParentItems_Desc: _,
    Workshop_Home_NumParentItems_Btn: _,
    Workshop_Home_MostPopularMerch: _,
    Workshop_Home_MostPopularMerch_Btn: _,
    Workshop_Home_ViewAll: _,
    Workshop_Home_YourFavorites: _,
    Workshop_Home_YourFavorites_Btn: _,
    Workshop_Home_YourPlayed: _,
    Workshop_Home_YourPlayed_Btn: _,
    Workshop_Home_YourSubscriptions: _,
    Workshop_Home_YourSubscriptions_Btn: _,
    Workshop_Home_YourFiles_LastUpdated: _,
    Workshop_Home_SpecialEvent_Title_Tag: _,
    Workshop_Home_SpecialEvent_Link: _,
    Workshop_ItemTooltip_FriendsWhoFavorited: _,
    Workshop_ItemTooltip_FriendsWhoFavorited_Plural: _,
    SharedFiles_TF2_Tab_Items_ReadyToUse: _,
    SharedFiles_TF2_Tab_Items_Mtx: _,
    SharedFiles_Dota2_Tab_Items_ReadyToUse: _,
    SharedFiles_Dota2_Tab_Items_Mtx: _,
    SharedFiles_Dota2_HeroPicker: _,
    SharedFiles_CSGO_Tab_Items_ReadyToUse: _,
    SharedFiles_CSGO_Tab_Items_Mtx: _,
  };
export {
  _ as Error_Encountered,
  _ as Error_Sorry,
  _ as Error_TooManyRequests_Description,
  _ as Header_App_WorkshopTitle,
  _ as Header_WorkshopTitle,
  _ as SharedFiles_Browse_Trend_Option_AllTime,
  _ as SharedFiles_Browse_Trend_Option_Month,
  _ as SharedFiles_Browse_Trend_Option_OneYear,
  _ as SharedFiles_Browse_Trend_Option_SixMonths,
  _ as SharedFiles_Browse_Trend_Option_ThreeMonths,
  _ as SharedFiles_Browse_Trend_Option_Today,
  _ as SharedFiles_Browse_Trend_Option_Week,
  _ as SharedFiles_CSGO_Tab_Items_Mtx,
  _ as SharedFiles_CSGO_Tab_Items_ReadyToUse,
  _ as SharedFiles_Dota2_HeroPicker,
  _ as SharedFiles_Dota2_Tab_Items_Mtx,
  _ as SharedFiles_Dota2_Tab_Items_ReadyToUse,
  _ as SharedFiles_TF2_Tab_Items_Mtx,
  _ as SharedFiles_TF2_Tab_Items_ReadyToUse,
  _ as Workshop_About,
  _ as Workshop_About_EnabledFeatures,
  _ as Workshop_About_EnabledFeatures_Desc,
  _ as Workshop_About_Feature_AuthorRoyalties,
  _ as Workshop_About_Feature_AuthorRoyalties_Desc,
  _ as Workshop_About_Feature_Branch_Versioning,
  _ as Workshop_About_Feature_Branch_Versioning_Desc,
  _ as Workshop_About_Feature_Commerce,
  _ as Workshop_About_Feature_Commerce_Desc,
  _ as Workshop_About_Feature_ItemCuration,
  _ as Workshop_About_Feature_ItemCuration_Desc,
  _ as Workshop_About_Feature_ItemCuration_Mixed_Desc,
  _ as Workshop_About_Feature_ItemMtx,
  _ as Workshop_About_Feature_ItemMtx_Desc,
  _ as Workshop_About_Feature_ReadyToUse,
  _ as Workshop_About_Feature_ReadyToUse_Desc,
  _ as Workshop_About_Feature_ReadyToUse_Mixed_Desc,
  _ as Workshop_About_Feature_ServiceProviders,
  _ as Workshop_About_Feature_ServiceProviders_Desc,
  _ as Workshop_About_FindGuides,
  _ as Workshop_About_FindGuides_Sub,
  _ as Workshop_About_NumAcceptedItems,
  _ as Workshop_About_NumItems,
  _ as Workshop_About_PageDesc_Curation,
  _ as Workshop_About_PageDesc_ReadyToUseContent1,
  _ as Workshop_About_PageDesc_ReadyToUseContent2,
  _ as Workshop_About_PageDesc_ReadyToUseContent_Mixed1,
  _ as Workshop_About_PageDesc_ReadyToUseContent_Mixed2,
  _ as Workshop_About_RefundLink_Sub,
  _ as Workshop_About_RelatedLinks,
  _ as Workshop_About_Request_ServiceProviders,
  _ as Workshop_About_RevenueShare,
  _ as Workshop_About_RevenueShare_Desc,
  _ as Workshop_About_RevenueShare_Here,
  _ as Workshop_About_RevenueShare_Link,
  _ as Workshop_About_ViewOfficialDocs,
  _ as Workshop_About_WorkshopTerms,
  _ as Workshop_About_WorkshopTerms_Sub,
  _ as Workshop_About_section_ServiceProviders,
  _ as Workshop_AcceptedForGame,
  _ as Workshop_AcceptedMerch,
  _ as Workshop_Admin_View,
  _ as Workshop_ApplyFilters,
  _ as Workshop_BrowseSort_AcceptedTime,
  _ as Workshop_BrowseSort_AdminOption,
  _ as Workshop_BrowseSort_BanContentCheck,
  _ as Workshop_BrowseSort_Combined,
  _ as Workshop_BrowseSort_CuratedAdmin,
  _ as Workshop_BrowseSort_Inappropriate,
  _ as Workshop_BrowseSort_LastUpdated,
  _ as Workshop_BrowseSort_MostPopular,
  _ as Workshop_BrowseSort_MostRecent,
  _ as Workshop_BrowseSort_MostUpVotes,
  _ as Workshop_BrowseSort_Nominee,
  _ as Workshop_BrowseSort_NumParentCollections,
  _ as Workshop_BrowseSort_NumParentItems,
  _ as Workshop_BrowseSort_Playtime,
  _ as Workshop_BrowseSort_PlaytimeAverage,
  _ as Workshop_BrowseSort_PlaytimeAverageTotal,
  _ as Workshop_BrowseSort_PlaytimeSessions,
  _ as Workshop_BrowseSort_PlaytimeSessionsTotal,
  _ as Workshop_BrowseSort_PlaytimeTotal,
  _ as Workshop_BrowseSort_Rated,
  _ as Workshop_BrowseSort_Reported,
  _ as Workshop_BrowseSort_SearchRelevance,
  _ as Workshop_BrowseSort_SortOrder,
  _ as Workshop_BrowseSort_TimeFrame,
  _ as Workshop_BrowseSort_ToRate,
  _ as Workshop_BrowseSort_TopRated,
  _ as Workshop_BrowseSort_TotalUniqueSubscribers,
  _ as Workshop_BrowseSort_TotalVotes,
  _ as Workshop_Browse_Author_Link,
  _ as Workshop_Browsing,
  _ as Workshop_Browsing_Merchandise_Desc,
  _ as Workshop_Browsing_Mtx_Desc,
  _ as Workshop_Browsing_ReadyToUse_Desc,
  _ as Workshop_Collection_NumChildCollections,
  _ as Workshop_Collection_NumChildCollections_Plural,
  _ as Workshop_Collection_NumChildItems,
  _ as Workshop_Collection_NumChildItems_Plural,
  _ as Workshop_Collection_SaveToCollection,
  _ as Workshop_Collection_SubscribeToAll,
  _ as Workshop_Collection_UnsubscribeFromAll,
  _ as Workshop_Collection_ViewMore,
  _ as Workshop_CreateCollection,
  _ as Workshop_CreateMerchandise,
  _ as Workshop_DateFilter_And,
  _ as Workshop_DateFilter_Between,
  _ as Workshop_DateFilter_FilterByDate,
  _ as Workshop_DateFilter_TimeCreated,
  _ as Workshop_DateFilter_TimeCreated_After,
  _ as Workshop_DateFilter_TimeCreated_Before,
  _ as Workshop_DateFilter_TimeCreated_Between,
  _ as Workshop_DateFilter_TimeUpdated,
  _ as Workshop_DateFilter_TimeUpdated_After,
  _ as Workshop_DateFilter_TimeUpdated_Before,
  _ as Workshop_DateFilter_TimeUpdated_Between,
  _ as Workshop_Dialog_AccessDenied,
  _ as Workshop_Dialog_AddToCollection,
  _ as Workshop_Dialog_AddToCollection_Create,
  _ as Workshop_Dialog_AddToCollection_Desc,
  _ as Workshop_Dialog_AddToCollection_NoSavedCollections_Desc,
  _ as Workshop_Dialog_AddToCollection_OK,
  _ as Workshop_Dialog_CollectionSubscribe,
  _ as Workshop_Dialog_CollectionSubscribe_AddOnly,
  _ as Workshop_Dialog_CollectionSubscribe_Desc,
  _ as Workshop_Dialog_CollectionSubscribe_Overwrite,
  _ as Workshop_Dialog_Error,
  _ as Workshop_Dialog_ErrorDesc,
  _ as Workshop_Dialog_ItemDependencies,
  _ as Workshop_Dialog_ItemDependencies_Desc1,
  _ as Workshop_Dialog_ItemDependencies_Desc1_itemName,
  _ as Workshop_Dialog_ItemDependencies_Desc2,
  _ as Workshop_Dialog_ItemDependencies_Desc3,
  _ as Workshop_Dialog_LimitExceeded,
  _ as Workshop_Dialog_Report,
  _ as Workshop_Dialog_Report_DMCA_Desc,
  _ as Workshop_Dialog_Report_Desc,
  _ as Workshop_Dialog_Report_Here,
  _ as Workshop_Dialog_Report_Reason,
  _ as Workshop_Dialog_Report_Reason_Desc,
  _ as Workshop_Dialog_Report_Trademark_Desc,
  _ as Workshop_Dialog_SaveCollectionToCollection,
  _ as Workshop_Dialog_SaveCollectionToCollection_Desc,
  _ as Workshop_Dialog_SaveCollectionToCollection_Existing,
  _ as Workshop_Dialog_SaveCollectionToCollection_New,
  _ as Workshop_Dialog_SaveCollectionToCollection_NewPrompt,
  _ as Workshop_Dialog_SaveCollectionToCollection_Select,
  _ as Workshop_Dialog_SubscribeAll,
  _ as Workshop_Dialog_SubscribeJustThisItem,
  _ as Workshop_Dialog_Timeout,
  _ as Workshop_DimmedItems_BlockedCreators,
  _ as Workshop_DimmedItems_Reported,
  _ as Workshop_DimmedItems_Subscribed,
  _ as Workshop_DimmedItems_Title,
  _ as Workshop_DimmedItems_VotedDown,
  _ as Workshop_DimmedItems_VotedUp,
  _ as Workshop_Error_Browse_Desc,
  _ as Workshop_Error_Loading,
  _ as Workshop_Error_Title,
  _ as Workshop_ExcludeOwnedDLC_Filter,
  _ as Workshop_ExitReact_Link,
  _ as Workshop_FiltersMenu_State_Collapsed,
  _ as Workshop_FiltersMenu_State_Left,
  _ as Workshop_FiltersMenu_State_Right,
  _ as Workshop_FiltersMenu_State_Title,
  _ as Workshop_Filters_ClearBtn,
  _ as Workshop_Flag_Incompatible_Checkbox,
  _ as Workshop_Flag_Incompatible_Checkbox_Desc,
  _ as Workshop_GamepadUIAction_QuickView,
  _ as Workshop_GamepadUIAction_ViewDetails,
  _ as Workshop_Home_AcceptedItems,
  _ as Workshop_Home_AcceptedItems_Btn,
  _ as Workshop_Home_AcceptedItems_Desc,
  _ as Workshop_Home_FriendsFavorites,
  _ as Workshop_Home_FriendsFavorites_Btn,
  _ as Workshop_Home_FriendsFavorites_Desc,
  _ as Workshop_Home_FromFollowedAuthors,
  _ as Workshop_Home_FromFollowedAuthors_Btn,
  _ as Workshop_Home_FromFollowedAuthors_Desc,
  _ as Workshop_Home_LastUpdated,
  _ as Workshop_Home_LastUpdated_Btn,
  _ as Workshop_Home_LastUpdated_Desc,
  _ as Workshop_Home_MostPlaytime,
  _ as Workshop_Home_MostPlaytime_Btn,
  _ as Workshop_Home_MostPopular,
  _ as Workshop_Home_MostPopularMerch,
  _ as Workshop_Home_MostPopularMerch_Btn,
  _ as Workshop_Home_MostPopular_LongTerm,
  _ as Workshop_Home_MostPopular_LongTerm_Btn,
  _ as Workshop_Home_MostPopular_LongTerm_Desc,
  _ as Workshop_Home_MostPopular_SubTitle_Month,
  _ as Workshop_Home_MostPopular_SubTitle_SixMonths,
  _ as Workshop_Home_MostPopular_SubTitle_ThreeMonths,
  _ as Workshop_Home_MostPopular_SubTitle_Week,
  _ as Workshop_Home_MostPopular_SubTitle_Year,
  _ as Workshop_Home_MostRecent,
  _ as Workshop_Home_MostRecent_Btn,
  _ as Workshop_Home_MostRecent_Desc,
  _ as Workshop_Home_MostSubscribed,
  _ as Workshop_Home_MostSubscribed_Btn,
  _ as Workshop_Home_MostSubscribed_Desc,
  _ as Workshop_Home_NumParentItems,
  _ as Workshop_Home_NumParentItems_Btn,
  _ as Workshop_Home_NumParentItems_Desc,
  _ as Workshop_Home_SpecialEvent_Link,
  _ as Workshop_Home_SpecialEvent_Title_Tag,
  _ as Workshop_Home_ViewAll,
  _ as Workshop_Home_VotingQueue,
  _ as Workshop_Home_VotingQueue_Btn,
  _ as Workshop_Home_VotingQueue_Count,
  _ as Workshop_Home_VotingQueue_Count_Plural,
  _ as Workshop_Home_VotingQueue_Desc,
  _ as Workshop_Home_YourFavorites,
  _ as Workshop_Home_YourFavorites_Btn,
  _ as Workshop_Home_YourFiles_LastUpdated,
  _ as Workshop_Home_YourPlayed,
  _ as Workshop_Home_YourPlayed_Btn,
  _ as Workshop_Home_YourSubscriptions,
  _ as Workshop_Home_YourSubscriptions_Btn,
  _ as Workshop_IncludeOwnedDLC_Filter,
  _ as Workshop_ItemDetails_AddToCollection,
  _ as Workshop_ItemDetails_AddToCollection_TT,
  _ as Workshop_ItemDetails_Award_TT,
  _ as Workshop_ItemDetails_Categories_Title,
  _ as Workshop_ItemDetails_CreatedBy,
  _ as Workshop_ItemDetails_DependentItems,
  _ as Workshop_ItemDetails_Description_Title,
  _ as Workshop_ItemDetails_Favorite,
  _ as Workshop_ItemDetails_Favorite_TT,
  _ as Workshop_ItemDetails_Favorited,
  _ as Workshop_ItemDetails_FileSize,
  _ as Workshop_ItemDetails_InCollections,
  _ as Workshop_ItemDetails_InCollectionsByAuthor,
  _ as Workshop_ItemDetails_ItemDependencies,
  _ as Workshop_ItemDetails_NotEnoughRatings,
  _ as Workshop_ItemDetails_NumRatings,
  _ as Workshop_ItemDetails_NumRatings_Plural,
  _ as Workshop_ItemDetails_ReactionCount,
  _ as Workshop_ItemDetails_ReactionCount_Plural,
  _ as Workshop_ItemDetails_Report_TT,
  _ as Workshop_ItemDetails_RequiredDLC_Desc,
  _ as Workshop_ItemDetails_SaveCollectionToCollection,
  _ as Workshop_ItemDetails_ShowAllReactions,
  _ as Workshop_ItemDetails_Signin_TT,
  _ as Workshop_ItemDetails_Stats_CurrentFavorites,
  _ as Workshop_ItemDetails_Stats_CurrentSubscribers,
  _ as Workshop_ItemDetails_Stats_LifetimeFavorites,
  _ as Workshop_ItemDetails_Stats_LifetimePlaytimeSessions,
  _ as Workshop_ItemDetails_Stats_LifetimeSubscribers,
  _ as Workshop_ItemDetails_Stats_UniqueVisitors,
  _ as Workshop_ItemDetails_Subscribe,
  _ as Workshop_ItemDetails_Subscribe_TT,
  _ as Workshop_ItemDetails_Subscribed,
  _ as Workshop_ItemDetails_Tab_ChangeNotes,
  _ as Workshop_ItemDetails_Tab_Comments,
  _ as Workshop_ItemDetails_Tab_Description,
  _ as Workshop_ItemDetails_Tab_Discussions,
  _ as Workshop_ItemDetails_Tab_Stats,
  _ as Workshop_ItemDetails_Tab_Updates,
  _ as Workshop_ItemDetails_Tags_Title,
  _ as Workshop_ItemDetails_TimestampCreated,
  _ as Workshop_ItemDetails_TimestampUpdated,
  _ as Workshop_ItemDetails_TimestampWithTime,
  _ as Workshop_ItemDetails_Title,
  _ as Workshop_ItemDetails_Unfavorite,
  _ as Workshop_ItemDetails_Unsubscribe,
  _ as Workshop_ItemDetails_Unsubscribe_TT,
  _ as Workshop_ItemDetails_ViewDependentItems,
  _ as Workshop_ItemDetails_ViewDependentItems_TT,
  _ as Workshop_ItemTooltip_FriendsWhoFavorited,
  _ as Workshop_ItemTooltip_FriendsWhoFavorited_Plural,
  _ as Workshop_Item_QuickView,
  _ as Workshop_Item_QuickView_ExpandBtn,
  _ as Workshop_LearnMore,
  _ as Workshop_Menu_About,
  _ as Workshop_Menu_Browse,
  _ as Workshop_Menu_Discussions,
  _ as Workshop_Menu_Home,
  _ as Workshop_Menu_Search,
  _ as Workshop_Menu_YourItems,
  _ as Workshop_NumPerPage,
  _ as Workshop_NumResults,
  _ as Workshop_NumResults_Plural,
  _ as Workshop_OfficialContent,
  _ as Workshop_OwnedDLC_All_Filter,
  _ as Workshop_OwnedDLC_More_Filter,
  _ as Workshop_OwnedDLC_None_Filter,
  _ as Workshop_PagingControls,
  _ as Workshop_RequireApproval,
  _ as Workshop_RequiredDLC_ExcludeUnowned,
  _ as Workshop_RequiredDLC_Filter,
  _ as Workshop_RequiredDLC_Header,
  _ as Workshop_RequiredDLC_IncludeOwned,
  _ as Workshop_RequiredDLC_NameFilter,
  _ as Workshop_Saved_Queries,
  _ as Workshop_Saved_Queries_Delete_Btn,
  _ as Workshop_Saved_Queries_Delete_Desc,
  _ as Workshop_Saved_Queries_Delete_Title,
  _ as Workshop_Saved_Queries_Save_Btn,
  _ as Workshop_Saved_Queries_Save_Desc,
  _ as Workshop_Saved_Queries_Save_Desc_Long,
  _ as Workshop_Saved_Queries_Save_New,
  _ as Workshop_Saved_Queries_Save_Title,
  _ as Workshop_Saved_Queries_Update,
  _ as Workshop_SearchResults_Flag_Accepted,
  _ as Workshop_SearchResults_Flag_Incompatible,
  _ as Workshop_SearchResults_KVTag,
  _ as Workshop_SearchResults_SearchText,
  _ as Workshop_SearchResults_SearchText_DescriptionOnly,
  _ as Workshop_SearchResults_SearchText_TitleOnly,
  _ as Workshop_SearchResults_Tag,
  _ as Workshop_SearchTarget_All,
  _ as Workshop_SearchTarget_Description,
  _ as Workshop_SearchTarget_MenuTitle,
  _ as Workshop_SearchTarget_Title,
  _ as Workshop_Search_Help,
  _ as Workshop_Search_Help_Advanced,
  _ as Workshop_Search_Help_AdvancedExample1,
  _ as Workshop_Search_Help_AdvancedExample2,
  _ as Workshop_Search_Help_Example1,
  _ as Workshop_Search_Help_Example2,
  _ as Workshop_Search_Help_Example3,
  _ as Workshop_Search_Help_Example_Blue,
  _ as Workshop_Search_Help_Example_Green,
  _ as Workshop_Search_Help_Example_Red,
  _ as Workshop_Search_Help_Example_Room,
  _ as Workshop_SearchedForChild,
  _ as Workshop_SearchedForRequiredItem,
  _ as Workshop_Section_Collections,
  _ as Workshop_Section_Merchandise,
  _ as Workshop_Section_Mtx,
  _ as Workshop_Section_ReadyToUse,
  _ as Workshop_Section_Videos,
  _ as Workshop_ServiceProviderRevenueSharing_ViewSite,
  _ as Workshop_ServiceProviderRevenueSharing_ViewSteamProfile,
  _ as Workshop_ServiceProvider_Category_Communities,
  _ as Workshop_ServiceProvider_Category_Tools,
  _ as Workshop_ServiceProvider_Category_Users,
  _ as Workshop_SortBy,
  _ as Workshop_SpecialFilter_AcceptedForUse,
  _ as Workshop_SpecialFilter_CreatedByFollowed,
  _ as Workshop_SpecialFilter_CreatedByFriends,
  _ as Workshop_SpecialFilter_Desc,
  _ as Workshop_SpecialFilter_FavoritedByFriends,
  _ as Workshop_SpecialFilter_None,
  _ as Workshop_SpecialFilter_ParentCollections,
  _ as Workshop_SpecialFilter_ParentItems,
  _ as Workshop_SpecialFilter_Reported,
  _ as Workshop_StatusIcon_TT_Accepted,
  _ as Workshop_StatusIcon_TT_BlockedCreator,
  _ as Workshop_StatusIcon_TT_Favorited,
  _ as Workshop_StatusIcon_TT_Incompatible,
  _ as Workshop_StatusIcon_TT_Played,
  _ as Workshop_StatusIcon_TT_Reported,
  _ as Workshop_StatusIcon_TT_Subscribed,
  _ as Workshop_StatusIcon_TT_VotedDown,
  _ as Workshop_StatusIcon_TT_VotedUp,
  _ as Workshop_SubMenu_LegalAgreement,
  _ as Workshop_SubMenu_ViewYourRevenue,
  _ as Workshop_SubMenu_ViewYourRevenue_Desc,
  _ as Workshop_SubMenu_VotingQueue,
  _ as Workshop_SubMenu_YourCollections,
  _ as Workshop_SubMenu_YourFavorites,
  _ as Workshop_SubMenu_YourItems,
  _ as Workshop_SubMenu_YourPaymentInfo,
  _ as Workshop_SubMenu_YourPlayed,
  _ as Workshop_SubMenu_YourSubscriptions,
  _ as Workshop_SubMenu_YourVotingQueue,
  _ as Workshop_Tag_NoneSpecified,
  _ as default,
  _ as language,
};
