var _ = `Forum gönderileri`,
  _ = `Genel Tartışmalar`,
  _ = `Şikâyet Edilen Gönderiler`,
  _ = `Atölye Tartışmaları`,
  _ = `Takas Yapma`,
  _ = `Etkinlikler ve Duyurular`,
  _ = `1 şikâyet`,
  _ = `%1$s şikâyet`,
  _ = `1 konu`,
  _ = `%1$s konu`,
  _ = `%2$s - %1$s`,
  _ = `%3$s başlığında %2$s için %1$s var`,
  _ = `1 şikâyet`,
  _ = `%1$s şikâyet`,
  _ = `1 konu`,
  _ = `%1$s konu`,
  _ = `Steam Topluluğu`,
  _ = `Steam Topluluğu :: Hata`,
  _ = `Hata`,
  _ = `Bilinmeyen hata`,
  _ = `Oyunlar`,
  _ = `Steam Topluluğu :: %1$s :: Oyunlar`,
  _ = `Ara - Steam Topluluk Pazarı`,
  _ = `%1$s - Steam Topluluk Pazarı`,
  _ = `Pazar Öğesi - Steam Topluluk Pazarı`,
  _ = `Steam Topluluk Pazarı`,
  _ = `Profil bulunamadı`,
  _ = `Kullanıcının istek listesi yüklenemedi.`,
  _ = `Yakın zamanda çok fazla talepte bulundunuz. Lütfen bekleyin ve talebinizi daha sonra tekrar gönderin.`,
  _ = `Yükleniyor`,
  _ = `%%1$s TAMAMLANDI`,
  _ = `DURAKLATILDI - %%1$s TAMAMLANDI`,
  _ = `%1$s/%2$s İNDİRİLDİ`,
  _ = `BAŞARIMLAR`,
  _ = `Kalan tahmini süre: %1$s`,
  _ = `%1$s/%2$s`,
  _ = `KALDIRILIYOR`,
  _ = `GÜNCELLE`,
  _ = `KALDIR`,
  _ = `İNDİR`,
  _ = `DURAKLAT`,
  _ = `DEVAM ET`,
  _ = `KALDIRILIYOR`,
  _ = `İPTAL ET`,
  _ = `Bu içerik için gizlilik ayarlarımı görüntüle.`,
  _ = `Oyun bul`,
  _ = `Her ikinizde de olan oyunlar`,
  _ = `Oynama süresi`,
  _ = `Ad`,
  _ = `Başarım tamamlama`,
  _ = `TOPLAM OYNAMA`,
  _ = `SON OYNAMA`,
  _ = `SON İKİ HAFTA`,
  _ = `Oyun Bilgileri ve Bağlantıları`,
  _ = `Uzaktan İndirme`,
  _ = `ŞURAYA UZAKTAN İNDİR: %1$s`,
  _ = `UZAKTAN İNDİRME DURUMU: %1$s`,
  _ = `Bilgisayarınıza ulaşılamıyor`,
  _ = `Steam istemcinize uzaktan oyun indirmek için bilgisayarınız uyanık ve internete bağlı, oturumunuz da açık olmalıdır`,
  _ = `SSS'yi Okuyun`,
  _ = `%1$s. %2$s`,
  _ = `Daha fazla bilgi`,
  _ = `UZAKTAN İNDİRME KULLANILAMAZ`,
  _ = `%1$s kurulumunu kaldırmak istiyor musunuz? Ürün, oyun kütüphanenizde kalmaya devam eder fakat ileride oynamak isterseniz içeriğini tekrar indirmeniz gerekir.`,
  _ = `%1$s | "%2$s"`,
  _ = `Son Oynananlar: %1$s`,
  _ = `Tüm Oyunlar: %1$s`,
  _ = `%100 Başarımlı Oyunlar: %1$s`,
  _ = `İncelemeler: %1$s`,
  _ = `Takip Edilenler: %1$s`,
  _ = `İstek Listesi`,
  _ = `Mevcut tüm başarımlar kazanıldı`,
  _ = `Tüm başarımlarını tamamladığınız oyunlarınız burada gösterilir.`,
  _ = `Oyuncuların %%1$s kadarı bu başarıma sahip`,
  _ = `Mağaza Sayfası`,
  _ = `Forumlar`,
  _ = `Gruplar`,
  _ = `Resmî İnternet Sitesi`,
  _ = `Haberler`,
  _ = `Başarımlarım`,
  _ = `%1$s - Başarımlar`,
  _ = `%1$s - İstatistikler`,
  _ = `%1$s - Kişisel Oyun Verisi`,
  _ = `Sıralama Listelerim`,
  _ = `%1$s - Sıralama Listeleri`,
  _ = `Global Başarımlar`,
  _ = `Global Sıralama Listeleri`,
  _ = `Oyun İstatistikleri`,
  _ = `Oyun İçeriği`,
  _ = `Oyun İstatistiklerim`,
  _ = `Oyun İçeriğim`,
  _ = `Oyun Bağlantıları`,
  _ = `Ekran Görüntülerim - %1$s`,
  _ = `Ekran Görüntüleri (%1$s) - %2$s`,
  _ = `%1$s Oynayan Arkadaşlarım`,
  _ = `Koleksiyon Kartlarım - %1$s`,
  _ = `İncelemem`,
  _ = `%1$s adlı kullanıcının incelemesi`,
  _ = `Topluluk Merkezi`,
  _ = `Notlarım`,
  _ = `%1$s saat`,
  _ = `%1$s dakika`,
  _ = `Gizli olarak işaretle`,
  _ = `Gizliliğini kaldır`,
  _ = `Bu oyunu gizli olarak işaretle ve arkadaşlarımdan gizle.`,
  _ = `© Valve Corporation. Tüm hakları saklıdır. Tüm ticari markalar, ABD ve diğer ülkelerde ilgili sahiplerinin mülkiyetindedir. `,
  _ = `Bu internet sitesindeki bazı coğrafi veriler %1$s tarafından sağlanmaktadır.`,
  _ = `Gizlilik Politikası`,
  _ = `Yasal Bilgi`,
  _ = `Steam Abonelik Sözleşmesi`,
  _ = `İadeler`,
  _ = `Çerezler`,
  _ = `Erişilebilirlik`,
  _ = `Mevcut yasaklamalar`,
  _ = `Topluluk mesajları`,
  _ = `Şikâyet edilen içerikler`,
  _ = `Moderasyona tabi tutulmuş içerikler`,
  _ = `Steam yönergelerini ihlal ettiği için şikâyet ettiğiniz içerikler.`,
  _ = `Steam'de paylaştığınız ve moderasyona tabi tutulan içerikler.`,
  _ = `Son güncelleme: %1$s`,
  _ = `İndir`,
  _ = `Herkese Açık Yorumlar (%1$s)`,
  _ = `Geliştirici Yorumları (%1$s)`,
  _ = `Bu, sadece öğeye katkıda bulunanların ve oyun geliştiricilerinin görebileceği özel bir başlıktır.`,
  _ = `Dikkat: Oyun yapımcılarıyla (örn. Valve) yazışmanız, gönderinizin seçileceğini garanti etmez.`,
  _ = `Boyut`,
  _ = `Tüm ekran görüntüleri`,
  _ = `Tüm çizimler`,
  _ = `Tüm videolar`,
  _ = `Açıklama`,
  _ = `Açıklamayı düzenle`,
  _ = `Spoiler Etiketi Ekle`,
  _ = `Spoiler Etiketini Kaldır`,
  _ = `Spoiler etiketi sayesinde arkadaşlarınız ve topluluk üyeleri, oyun hakkındaki spoiler içeren bilgileri görmemeyi seçebilir.`,
  _ = `(Spoiler etiketleri dört hafta sonra kaldırılır.)`,
  _ = `Bu ekran görüntüsündeki kullanıcılar: `,
  _ = `Bu ekran görüntüsündeki atölye öğeleri: `,
  _ = `Bu ekran görüntüsündeki etiketinizi kaldırın.`,
  _ = `Konum`,
  _ = `Etiketler:`,
  _ = `Rehber Yükleniyor`,
  _ = `Bu rehberi %1$s içinde kullanmak için abone ol`,
  _ = `Rehber İçeriği`,
  _ = `Genel Bakış`,
  _ = `Yorumlar`,
  _ = `Düzenle`,
  _ = `{BAĞLANTI SİLİNDİ}`,
  _ = `Buradaki bağlantı adresi filtrelerimiz tarafından kaldırılmıştır. Bu genellikle kimlik avı ve kötü amaçlı yazılım saldırılarını önlemek için yapılır.`,
  _ = `Rehber İçeriği`,
  _ = `Rehberinizin düzenini ve rehber içindeki bölümlerin isimlerini belirleyin. Bölümleri sürükleyerek yeniden sıralayabilirsiniz.`,
  _ = `Rehberin yayınlanabilmesi için bu bölüm doldurulmalıdır.`,
  _ = `İçerik Listenizi Oluşturun`,
  _ = `Bölüm ekle`,
  _ = `(yeni bölüm, henüz başlık yok)`,
  _ = `Bu bölümü düzenle`,
  _ = `Bu bölümü sil`,
  _ = `Bu bölümü kaldırmak istediğinizden emin misiniz? Bu işlem geri alınamaz.`,
  _ = `Görseller`,
  _ = `Rehberinizde kullanmak istediğiniz görselleri seçin ve yükleyin. Gerekli olan bütün görselleri buraya yükleyin. Böylece rehberinizin bölümlerini tek tek düzenlerken istediğiniz görseli kolayca seçebilirsiniz.`,
  _ = `Rehberiniz için görseller yükleyin`,
  _ = `Katılımcı Ekle`,
  _ = `Buradan arkadaşlarınızı katılımcı olarak ekleyip onlara rehberinizi düzenleme yetkisi verebilirsiniz.`,
  _ = `Arkadaşlarınızı katılımcı olarak ekleyin`,
  _ = `Katılımcı ekle`,
  _ = `Rehberi İncele`,
  _ = `Rehber Bölümünü Düzenle`,
  _ = `Bölüm Başlığı`,
  _ = `Bölüm İçeriği`,
  _ = `Düzenle`,
  _ = `Ön İzle`,
  _ = `Değişiklikleri Görüntüle`,
  _ = `Son kaydetmenizden bu yana metninizde yaptığınız değişiklikler bu şekilde gösterilecektir:`,
  _ = `Bu şekilde görünen metin eklendi`,
  _ = `Bu şekilde görünen metin silindi`,
  _ = `Bu bölümde yaptığınız değişiklikler henüz kaydedilmedi.`,
  _ = `Bu bölümde yaptığınız değişiklikler henüz kaydedilmedi. Bu değişiklikleri iptal etmek istediğinizden emin misiniz?`,
  _ = `Son kaydetme`,
  _ = `Kaydet`,
  _ = `İptal Et`,
  _ = `Ekran Görüntüleri`,
  _ = `Videolar`,
  _ = `Rehberinize eklemek için aşağıdaki görsellerden birine tıklayın`,
  _ = `Rehberinize eklemek için aşağıdaki ekran görüntülerinden birine tıklayın`,
  _ = `Rehberinize eklemek için aşağıdaki videolardan birine tıklayın`,
  _ = `Görsel Ekleme Seçenekleri`,
  _ = `Boyut`,
  _ = `yarı genişlik`,
  _ = `tam genişlik`,
  _ = `orijinal boyut`,
  _ = `Hizalama`,
  _ = `sola`,
  _ = `sağa`,
  _ = `hizada`,
  _ = `Sola hizalanmış`,
  _ = `Sağa hizalanmış`,
  _ = `Tam genişlik`,
  _ = `Ekle`,
  _ = `YouTube™ Videosu Ekle`,
  _ = `YouTube™ video adresini girin`,
  _ = `Alıntı metin`,
  _ = `Gizli yazı (spoiler)`,
  _ = `Lütfen bir başlık girin`,
  _ = `Rehberi aç`,
  _ = ``,
  _ = `Atölye öğeleri:`,
  _ = `ve %1$s tane daha`,
  _ = `Yorum ve detayları görüntüle`,
  _ = `%1$s yorumu ve detayı görüntüle`,
  _ = `Ekran Görüntüleri`,
  _ = `Çizimler`,
  _ = `Videolar`,
  _ = `Atölye Öğeleri`,
  _ = `Fiziksel Ürünler`,
  _ = `Koleksiyonlar`,
  _ = `Rehberler`,
  _ = `Atölye Öğeleri`,
  _ = `Atölye Koleksiyonları`,
  _ = `Rehberler`,
  _ = `Favoriler`,
  _ = `Abone Olunan Öğeler`,
  _ = `Oynanan`,
  _ = `Oyuna göre filtrele`,
  _ = `Tüm oyunlar`,
  _ = `Bir oyun seçin`,
  _ = `Öğeler`,
  _ = `Favoriler`,
  _ = `Abone Olunan Öğeler`,
  _ = `Oluşturulma Tarihi`,
  _ = `Alfabetik`,
  _ = `Güncellenme Tarihi`,
  _ = `Abone Olma Tarihi`,
  _ = `Favorilere Eklenme Tarihi`,
  _ = `Seçilen terimlerle etiketlenen öğeleri göster:`,
  _ = `Oluşturan:`,
  _ = `%3$s sonuçtan %1$s ile %2$s arası gösteriliyor`,
  _ = `%1$s için dosya bulunamadı.`,
  _ = `%3$s sonuçtan %1$s ile %2$s arası gösteriliyor`,
  _ = `Son Güncelleme %1$s`,
  _ = `Eklenme tarihi %1$s`,
  _ = `Bu öğe favoriler listenizden kaldırıldı:`,
  _ = `Abonelik olma tarihi %1$s`,
  _ = `Şu öğelerin aboneliğini kaldırdınız:`,
  _ = `Yaşasın! Steam Atölyesi öğelerinizden bazıları kullanılmak üzere seçildi!`,
  _ = `Lütfen kutlamaya başlamadan önce <a href="%1$s">ödeme bilgilerinizi</a> girin, böylece kime ödeme yapacağımızı bilelim!`,
  _ = `Ödeme bilgilerinizi onaylarken bir hata meydaha geldi. Lütfen <a href="%1$s">ödeme bilgilerinizi</a> inceleyin ve güncelleyin.`,
  _ = `Bu öğeler için katılımcı olarak gösterildiniz`,
  _ = `Lütfen bu öğeler için belirtilen sahiplik payını inceleyin ve onaylayın`,
  _ = `Pay:`,
  _ = `Atölyeniz`,
  _ = `Bu kullanıcı yeni bir Steam rehberi yayınladığında, yeni bir koleksiyon oluşturduğunda, Steam Atölyesi'ne yeni öğeler koyduğunda bunlardan haberdâr olmak için bu kullanıcıyı takip edin.`,
  _ = `Sizi takip eden Steam kullanıcıları, siz bir Steam rehberi yayınladığınızda, yeni bir koleksiyon oluşturduğunuzda, Steam Atölyesi'ne yeni öğeler koyduğunuzda bunlardan haberdâr olacaktır.`,
  _ = `Takipçi`,
  _ = `Takipçiler`,
  _ = `Takip et: %1$s`,
  _ = `%1$s takip ediliyor`,
  _ = `%1$s kullanıcısını takibi bırak`,
  _ = `Gelirinizi Görüntüleyin`,
  _ = `Atölye öğelerinizin satışından gelen gelir`,
  _ = `Ödeme Bilgisi Girin veya Güncelleyin`,
  _ = `Yasal Sözleşmeyi Görüntüle`,
  _ = `Tüm Aboneliklerden Ayrıl`,
  _ = `Tüm aboneliklerden ayrılmak istiyor musunuz?`,
  _ = `Tüm aboneliklerden ayrılmak istediğinizden emin misiniz?<br><br>Bu işlem geri alınamaz!`,
  _ = `Tüm %1$s aboneliklerinden ayrılmak istediğinizden emin misiniz?<br><br>Bu işlem geri alınamaz!`,
  _ = `Koleksiyona Kaydet`,
  _ = `Abonelikleri Koleksiyona Kaydet`,
  _ = `Aboneliklerinizi yeni bir koleksiyona mı yoksa mevcut bir koleksiyona mı kaydetmek istersiniz?`,
  _ = `Yeni Koleksiyon`,
  _ = `Bu koleksiyon için bir ad girin:`,
  _ = `Mevcut Koleksiyon`,
  _ = `Üzerine yazılacak bir koleksiyon seçin: `,
  _ = `Mevcut bir koleksiyonunuz yok. Yeni bir koleksiyon oluşturmak ister misiniz?`,
  _ = `Yönetici Etiketleri`,
  _ = `Steam Rehberleri`,
  _ = `Entegre Rehberler`,
  _ = `Kahraman Yapıları`,
  _ = `Oyun sırasında size oyunu öğreten özel entegre rehberler`,
  _ = `Özel olarak %1$s ile entegre edilen rehberler`,
  _ = `Popüler Kategoriler`,
  _ = `Entegre Rehberler`,
  _ = `Favorileriniz`,
  _ = `Popüler Steam Rehberleri`,
  _ = `Yazılı rehberler, bilgiler ve çözümler`,
  _ = `Tümünü Görüntüle (%1$s)`,
  _ = `%1$s Rehber`,
  _ = `%1$s Rehber`,
  _ = `Oluşturduğunuz rehberler`,
  _ = `Rehberler Hakkında Daha Fazla Bilgi`,
  _ = `Steam Rehberleri hakkında daha fazla bilgi için tıklayın`,
  _ = `Göz at:`,
  _ = `Ana Sayfa`,
  _ = `Rehber Oluştur`,
  _ = `Rehber oluşturmak istiyorsanız öncelikle %1$s sahibi olmalısınız.`,
  _ = `Bu oyun için rehber hazırlayan ilk kişi olun!`,
  _ = `Uzmanlığınızı gösterin ya da zorluk yaşayan oyunculara yardımcı olun.`,
  _ = `Adım adım talimatlar oluşturun, oyun sırlarını ortaya çıkarın veya belirli haritalar için en uygun stratejileri önerin.`,
  _ = `Bu oyun için oyuncular tarafından oluşturulan rehberlere göz atın ve oy verin. Ya da kendi rehberinizi oluştururak ipuçlarınızı toplulukla paylaşın.`,
  _ = `Kendi rehberinizi oluşturun`,
  _ = `Ekran görüntüleri`,
  _ = `Çizimler`,
  _ = `Videolar`,
  _ = `%3$s sonuçtan %1$s ile %2$s arası gösteriliyor`,
  _ = `Başa dön`,
  _ = `Görüntülenen:`,
  _ = `Resim duvarı`,
  _ = `Tablo`,
  _ = `En popüler`,
  _ = `Yeniden eskiye`,
  _ = `Eskiden yeniye`,
  _ = `Tüm Ekran Görüntüleriniz`,
  _ = `Herkese Açık Ekran Görüntüleriniz`,
  _ = `Sadece Arkadaşlara Açık Ekran Görüntüleriniz`,
  _ = `Gizli Ekran Görüntüleriniz`,
  _ = `Listelenmemiş Ekran Görüntüleriniz`,
  _ = `Tüm Çizimleriniz`,
  _ = `Herkese Açık Çizimleriniz`,
  _ = `Sadece Arkadaşlara Açık Çizimleriniz`,
  _ = `Gizli Çizimleriniz`,
  _ = `Listelenmemiş Çizimleriniz`,
  _ = `Tüm Videolarınız`,
  _ = `Herkese Açık Videolarınız`,
  _ = `Sadece Arkadaşlara Açık Videolarınız`,
  _ = `Gizli Videolarınız`,
  _ = `Listelenmemiş Videolarınız`,
  _ = `Ekran görüntülerini yönet`,
  _ = `Çizimleri yönet`,
  _ = `Videoları yönet`,
  _ = `İşlem yapmak istediğiniz ekran görüntülerini seçin.`,
  _ = `İşlem yapmak istediğiniz çizimleri aşağıdan seçin.`,
  _ = `İşlem yapmak istediğiniz videoları seçin.`,
  _ = `İptal Et`,
  _ = `YouTube'dan video ekle`,
  _ = `YouTube hesabı bağla`,
  _ = `YouTube hesabının ilişkilendirmesini kaldır`,
  _ = `Kaldır`,
  _ = `YouTube hesabınızın ilişkilendirmesini kaldırmak istediğinizden emin misiniz?`,
  _ = `Steam, YouTube verilerimi nasıl kullanıyor?`,
  _ = `YouTube hesabınızı Steam ile ilişkilendirmek YouTube API Hizmetleri'ni kullanır. YouTube hesabınızı Steam profilinizle ilişkilendirerek %1$s ve %2$s koşullarını kabul edersiniz.`,
  _ = `Steam, YouTube hesabınızı doğrulamak ve YouTube'a yüklemiş olduğunuz videoların listesini size sunmak için YouTube API Hizmetleri'ni kullanır. YouTube hesabınızı Steam'le ilişkilendirdiğinizde Steam, YouTube için hesabınızın kimlik doğrulama belirteçlerini içeren tarayıcınıza veya Steam istemcinize bir çerez koyar. Bu çerez 30 gün sonra geçerliliğini yitirir. Steam, YouTube hesabınızdaki yüklenmiş videoların listesine eriştiğinde, elde edilen veriler sadece size ilgili listeyi Steam'de göstermek için kullanılır.`,
  _ = `YouTube hesabınızdaki bir videoyu Steam'e gönderdiğinizde Steam, videonun ID'si ve videonun ait olduğu YouTube hesabının ID'si de dâhil olmak üzere sadece videoyu Steam'de göstermek için gerekli olan bilgileri saklar. Bu veriler sadece videoyu Steam'de göstermek ve Steam'de içerik moderasyonu yapmak için kullanılır.`,
  _ = `Steam'in %1$s erişimini %2$s aracılığıyla iptal edebilirsiniz.`,
  _ = `YouTube Hizmet Şartları`,
  _ = `Google Gizlilik Politikası`,
  _ = `Yetkili Veriler`,
  _ = `Google güvenlik ayarları sayfası`,
  _ = `Videolarınız artık Steam'de.`,
  _ = `Oyunlardaki en iyi anlarınızı arkadaşlarınızla paylaşın. Hazırladığınız muhteşem özetleri, bilgili incelemeleri, yardımcı eğitim videolarını ve oyunlarla ilgili oluşturduğunuz tüm diğer harika videolarınızı gönderin.`,
  _ = `1. YouTube™ hesabınızı Steam profilinizle ilişkilendirin.`,
  _ = `2. Profilinize eklemek istediğiniz videoları seçin.`,
  _ = `3. Videolarınızı Steam arkadaşlarınızla paylaşın.`,
  _ = `YouTube videolarınıza erişin`,
  _ = `Şu anda %1$s YouTube hesabınız ilişkilendirilmiş durumda.`,
  _ = `Bu hesabın ilişkilendirmesini kaldırın ve başka hesap ekleyin.`,
  _ = `Bu hesabın ilişkilendirmesini kaldır`,
  _ = `Bu hesapla devam et`,
  _ = `YouTube hesabınız başarıyla ilişkilendirildi`,
  _ = `1 video başarıyla eklendi`,
  _ = `%1$s video başarıyla eklendi`,
  _ = `YouTube koleksiyonunuzda seçilebilecek video bulunamadı.`,
  _ = `Sadece herkese açık olarak ayarlanmış, yerleştirilmeye uygun ve kullanıcı adı aramasında sizin kullanıcı adınızın görüntülendiği YouTube videolarını ekleyebilirsiniz. Hesabınızı ilişkilendirmek için daha yeni bir videoyu herkese açık duruma getirdiyseniz, videonuzun YouTube tarafından listelenmesi ve arama sonuçlarında görüntülenmesi biraz zaman alabilir.`,
  _ = `Zaten %1$s YouTube hesabınız Steam ile ilişkilendirilmiş.`,
  _ = `YouTube hesabını değiştirmek için buraya tıklayın`,
  _ = `hesabı değiştir`,
  _ = `1. Eklemek istediğiniz videoları seçin.`,
  _ = `%1$s hesabı için 1 video kullanılabilir`,
  _ = `%2$s hesabı için kullanılabilir en son %1$s video gösteriliyor`,
  _ = `2. Videoları bir oyun ile eşleştirin.`,
  _ = `Sol menüden videolarınızı seçtikten sonra (isteğe bağlı)`,
  _ = `- hiçbiri / diğer (altta belirtin) -`,
  _ = `Diğer / Listelenmemiş:`,
  _ = `3. Videoyu profilinize ekleyin.`,
  _ = `Video ekle`,
  _ = `Not: YouTube hesabınızdan ekleyeceğiniz videoların herkese açık şekilde ayarlanmış ve yerleştirilmeye uygun olması gerekmektedir. YouTube hesabınıza daha yeni video eklediyseniz ve listede göremiyorsanız, aşağıdaki butona tıklayarak listeyi yenileyin.`,
  _ = `YouTube video listesini yenile`,
  _ = `4. İşlemi tamamlayın.`,
  _ = `İşleminizi tamamladığınızda videoları profil sayfanızda görmek için "Bitti"ye tıklayın.`,
  _ = `Bitti`,
  _ = `Video listenize erişilirken bir sorun oluştu, lütfen tekrar deneyin.`,
  _ = `Çizim yükle`,
  _ = `Ekran görüntüsü yükle...`,
  _ = `Herkese Açık Yap`,
  _ = `Sadece Arkadaşlara Görünür Yap`,
  _ = `Gizli Yap`,
  _ = `Listelenmemiş Yap`,
  _ = `Sil`,
  _ = `Tümünü Seç`,
  _ = `Bitti`,
  _ = `Bu öğeler silinsin mi?`,
  _ = `Gizliliği Güncelle`,
  _ = `Bu işlem ile %1$s, Steam Cloud'dan silinecek. Devam etmek istiyor musunuz?`,
  _ = `Bu %1$s görünürlüğünü %2$s olarak güncelleyecek. Devam etmek istiyor musunuz?`,
  _ = `Devam Et`,
  _ = `İptal Et`,
  _ = `Hay aksi!`,
  _ = `Öğe seçilmedi.`,
  _ = `Silinecek öğeleri seçmek için küçük resimlerin köşelerindeki kutuları işaretleyin.`,
  _ = `Tamam`,
  _ = `Görünürlük güncellenemedi`,
  _ = `Herkese Açık veya Sadece Arkadaşlara görünür olarak ayarlamaya çalıştığınız bir veya daha fazla ekran görüntüsü güncellenemedi. Steam Topluluğu'nda resmî olarak yer almayan oyunlara ait ekran görüntüleri paylaşılamaz ve bu görüntüleri sadece siz görebilirsiniz.`,
  _ = `Spoiler içerebilir.`,
  _ = `Resmi görmek için imleci üzerine getirin.`,
  _ = `Eşleşen ekran görüntüsü bulunamadı.`,
  _ = `%1$s, görüntüleyebileceğiniz bir ekran görüntüsüne sahip değil.`,
  _ = `Hiçbir ekran görüntüsünü favorilerinize eklemediniz.`,
  _ = `%1$s, görüntüleyebileceğiniz bir favori ekran görüntüsüne sahip değil.`,
  _ = `Steam Cloud üzerinde depolanmış bir çiziminiz yok. Çizim yüklemek için oyun merkezinin Çizimler sekmesine gidin ve sağ üstte Çizim Yükle butonunu kullanın. Aşağıdaki Çizim Yükle butonunu da kullanabilirsiniz.`,
  _ = `%1$s, görüntüleyebileceğiniz bir çizime sahip değil.`,
  _ = `Hiçbir çizimi favorilerinize eklemediniz.`,
  _ = `%1$s, görüntüleyebileceğiniz bir favori çizime sahip değil.`,
  _ = `Eşleşen video bulunamadı.`,
  _ = `%1$s, görüntüleyebileceğiniz bir videoya sahip değil.`,
  _ = `Hiçbir videoyu favorilerinize eklemediniz.`,
  _ = `%1$s, görüntüleyebileceğiniz bir favori videoya sahip değil.`,
  _ = `Bu görünürlük ayarına sahip bir ekran görüntünüz yok.`,
  _ = `Steam, favori oyunlarınızdan ekran görüntüsü almayı ve bu görüntüleri paylaşmayı kolaylaştırır.`,
  _ = `Steam Arayüzü çalıştıran herhangi bir oyundayken kısayol tuşuyla (varsayılan F12) ekran görüntüsü alabilirsiniz. Daha sonra aldığınız bu ekran görüntülerini Steam Topluluğu'nda yayınlayabilir ve Facebook, Twitter veya Reddit üzerinden arkadaşlarınızla paylaşabilirsiniz.`,
  _ = `Kaydedeceğiniz en iyi anlarınızı arkadaşlarınıza göstermek için, 1 GB'lık kişisel Steam Cloud depolama alanınızda binlerce ekran görüntüsü saklayabilirsiniz. Veya görünürlük ayarını gizli yaparak bu anları kendinize saklayabilirsiniz.`,
  _ = `Oluşturan: %1$s`,
  _ = `%1$s Favorileri`,
  _ = {
    Moderation_SubjectTypeName_ForumPost: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    moderation_claim_report_count: _,
    moderation_claim_report_count_Plural: _,
    moderation_claim_subject_count: _,
    moderation_claim_subject_count_Plural: _,
    moderation_claim_n_reports_on_m_subjects: _,
    moderation_forumpost_summary: _,
    moderation_forumpost_summary_reports_fragment: _,
    moderation_forumpost_summary_reports_fragment_Plural: _,
    moderation_forumpost_summary_subjects_fragment: _,
    moderation_forumpost_summary_subjects_fragment_Plural: _,
    community_title: _,
    community_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    profile_games_list: _,
    profile_games_list_title: _,
    Market_Search_Title: _,
    Market_Item_Title: _,
    Market_Item_GenericTitle: _,
    Market_GenericTitle: _,
    profile_error_profilenotfound: _,
    profile_games_list_error_loadfailed: _,
    Error_RateLimited: _,
    Loading: _,
    GamesList_Header_Downloading: _,
    GamesList_Header_Paused: _,
    GamesList_Header_DownloadBytes: _,
    GamesList_Header_Achievements: _,
    GamesList_TimeRemaining: _,
    GamesList_Achievement_Fraction: _,
    GamesList_Uninstalling: _,
    GamesList_Button_UpdateRequired: _,
    GamesList_Button_Uninstall: _,
    GamesList_Button_Download: _,
    GamesList_Button_Pause: _,
    GamesList_Button_Resume: _,
    GamesList_Button_Uninstalling: _,
    GamesList_Button_Cancel: _,
    GamesList_PrivacySettings_Tooltip: _,
    GamesList_Filter_Placeholder: _,
    GamesList_Filter_BothOwned: _,
    GamesList_Sort_HoursPlayed: _,
    GamesList_Sort_Name: `Ad`,
    GamesList_Sort_AchievementCompletion: _,
    GamesList_Header_TotalPlayed: _,
    GamesList_Header_LastPlayed: _,
    GamesList_Header_TwoWeeks: _,
    GamesList_MenuLabel_GameInfo: _,
    GamesList_MenuLabel_RemoteDownload: _,
    GamesList_Header_RemoteDownload: _,
    GamesList_Header_RemoteDownloadStatus: _,
    GamesList_RemoteDownload_NoConnection: _,
    GamesList_RemoteDownload_Help: _,
    GamesList_RemoteDownload_ReadTheFAQ: _,
    GamesList_RemoteDownload_Info: _,
    GamesList_RemoteDownload_LearnMore: _,
    GamesList_RemoteDownload_NoRemoteControl: _,
    GamesList_RemoteDownload_UninstallConfirm: _,
    GamesList_Client_Indicator: _,
    GamesList_Tab_RecentlyPlayed: _,
    GamesList_Tab_AllGames: _,
    GamesList_Tab_PerfectGames: _,
    GamesList_Tab_Reviews: _,
    GamesList_Tab_Followed: _,
    GamesList_Tab_Wishlist: _,
    Perfect_Game_Description: _,
    GamesList_PerfectGames_Description: _,
    GamesList_Achievement_Unlock_Percentage: _,
    Community_StorePage: _,
    Community_Forums: _,
    Community_Groups: _,
    Community_OfficialWebsite: _,
    Community_News: _,
    Community_UsersAchievementsFirstPerson: _,
    Community_UsersAchievements: _,
    Community_UsersStats: _,
    Community_GamePersonalData: _,
    Community_UsersLeaderboardsFirstPerson: _,
    Community_UsersLeaderboards: _,
    Community_GlobalAchievements: _,
    Community_GlobalLeaderboards: _,
    Community_GameStats: _,
    Community_GameContent: _,
    Community_GameStatsFirstPerson: _,
    Community_GameContentFirstPerson: _,
    Community_GameLinks: _,
    Community_ScreenshotsMenuItemFirstPerson: _,
    Community_ScreenshotsMenuItemThirdPerson: _,
    Community_FriendsWhoPlayMenuItemFirstPerson: _,
    Community_TradingCardsMenuItemFirstPerson: _,
    Community_ReviewMenuItemFirstPerson: _,
    Community_ReviewMenuItemThirdPerson: _,
    Community_GameHubMenuItem: _,
    Community_GameNotesFirstPerson: _,
    Playtime_Hours: _,
    Playtime_Minutes: _,
    AppPrivacy_MarkAsPrivate: _,
    AppPrivacy_UnmarkAsPrivate: _,
    AppPrivacy_Explanation: _,
    footer_legal_notice: _,
    footer_geodata_notice: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_accessibility: _,
    profiletabs_currentbans: _,
    profiletabs_communitymessages: _,
    profiletabs_reportedcontent: _,
    profiletabs_moderatedcontent: _,
    reportedcontent_description: _,
    moderatedcontent_description: _,
    reportedcontent_lastupdated: _,
    SharedFiles_ItemDownload: _,
    SharedFiles_PublicComments: _,
    SharedFiles_DeveloperComments: _,
    Workshop_DeveloperThreadDesc: _,
    Workshop_DeveloperThreadDisclaimerText: _,
    Workshop_ImageSize: _,
    SharedFiles_Media_ViewAppScreenshots: _,
    SharedFiles_Media_ViewAppFanArt: _,
    SharedFiles_Media_ViewAppVideos: _,
    SharedFiles_ItemEditText_Text_Caption: _,
    SharedFiles_OwnerControl_EditCaption: _,
    SharedFiles_AddSpoilerTag: _,
    SharedFiles_RemoveSpoilerTag: _,
    SharedFiles_SpoilerTagInstructions: _,
    SharedFiles_SpoilerTagsExpire: _,
    SharedFiles_Stats_TaggedUsers: _,
    SharedFiles_Stats_TaggedWorkshopItems: _,
    SharedFiles_RemoveSelfTag_Tooltip: _,
    Screenshots_Location: _,
    SharedFiles_Tags: _,
    SharedFiles_WaitingForIntegratedGuide: _,
    Workshop_Subscribe_IntegratedGuide: _,
    SharedFiles_Guide_Index: _,
    SharedFiles_Guide_Overview: _,
    SharedFiles_Guide_Comments: _,
    SharedFiles_Item_Edit_Link: _,
    Community_RemoveLink_BeWary: _,
    Community_RemoveLink_Tooltip: _,
    SharedFiles_ManageGuide_Contents: _,
    SharedFiles_ManageGuide_Contents_Desc: _,
    SharedFiles_ManageGuide_Required: _,
    SharedFiles_ManageGuide_NoSubSections: _,
    SharedFiles_ManageGuide_AddSection: _,
    SharedFiles_ManageGuide_NoSectionTitle: _,
    SharedFiles_ManageGuide_EditThisSection: _,
    SharedFiles_ManageGuide_DeleteThisSection: _,
    SharedFiles_ManageGuide_RemoveSectionConfirm: _,
    SharedFiles_ManageGuide_Images: _,
    SharedFiles_ManageGuide_Images_Desc: _,
    SharedFiles_ManageGuide_NoPreviewImages: _,
    SharedFiles_ManageGuide_Contributors: _,
    SharedFiles_ManageGuide_Contributors_Desc: _,
    SharedFiles_ManageGuide_NoContributors: _,
    SharedFiles_ManageGuide_AddContributor: _,
    SharedFiles_ManageGuide_Preview: _,
    SharedFiles_ManageGuide_EditSubSection: _,
    SharedFiles_ManageGuide_SubSectionTitle: _,
    SharedFiles_ManageGuide_SubSectionContents: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Edit: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Preview: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Changes: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Desc: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Insert: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Delete: _,
    SharedFiles_ManageGuide_SubSectionContentChanged: _,
    SharedFiles_ManageGuide_SubSectionContentChanged_CancelConfirm: _,
    SharedFiles_ManageGuide_SubSectionContentSaved: _,
    SharedFiles_ManageGuide_Save: _,
    SharedFiles_ManageGuide_Cancel: _,
    SharedFiles_ManageGuide_Screenshots: _,
    SharedFiles_ManageGuide_Videos: _,
    SharedFiles_ManageGuide_SubImages: _,
    SharedFiles_ManageGuide_SubScreenshots: _,
    SharedFiles_ManageGuide_SubVideos: _,
    SharedFiles_ManageGuide_ImageInsertionOptions: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_Size: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeThumb: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeFull: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeOriginal: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_Layout: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutLeft: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutRight: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutInline: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Left: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Right: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Full: _,
    SharedFiles_ManageGuide_InsertImage: _,
    SharedFiles_ManageGuide_InsertYouTubeVideo: _,
    SharedFiles_ManageGuide_PromptYouTubeUrl: _,
    Discussions_FormattingHelp_Quote: _,
    Discussions_FormattingHelp_Spoiler: _,
    SharedFiles_ItemEditText_ErrorNoTitle: _,
    SharedFiles_OwnerControl_BackGuide: _,
    empty_no_comma_following: ``,
    SharedFiles_WorkshopItemsTagged: _,
    SharedFiles_And_N_More: _,
    Workshop_ItemModalViewDetails: _,
    Workshop_ItemModalViewCountDetails: _,
    Profile_Screenshots: _,
    Profile_Images: _,
    Profile_Videos: _,
    Profile_Workshop_Items: _,
    SharedFiles_Tab_Merchandise: _,
    Profile_Collections: _,
    Profile_Guides: _,
    SharedFiles_SharedFiles_Items: _,
    SharedFiles_SharedFiles_Collections: _,
    SharedFiles_SharedFiles_Guides: _,
    SharedFiles_Favorites: _,
    SharedFiles_Subscriptions: _,
    SharedFiles_Browse_MyFiles_Played: _,
    SharedFiles_FilterByGame: _,
    Profile_SharedFiles_AllGames: _,
    Profile_SharedFiles_SelectAGame: _,
    SharedFiles_Browse_MyFiles_Items: _,
    SharedFiles_Browse_MyFiles_Favorites: _,
    SharedFiles_Browse_MyFiles_Subscriptions: _,
    SharedFiles_Browse_MyFiles_Sort_CreationOrder: _,
    SharedFiles_Browse_MyFiles_Sort_Alpha: _,
    SharedFiles_Browse_MyFiles_Sort_LastUpdated: _,
    SharedFiles_Browse_MyFiles_Sort_Subscribed: _,
    SharedFiles_Browse_MyFiles_Sort_Favorited: _,
    SharedFiles_TagsSearch: _,
    SharedFiles_ByAuthor: _,
    Workshop_BrowsePaging: _,
    Workshop_NoItems: _,
    SharedFiles_UserList_BrowsePaging: _,
    SharedFiles_UserList_LastUpdated: _,
    SharedFiles_Favorites_Subscribed: _,
    SharedFiles_Favorites_NowUnsubscribed: _,
    SharedFiles_Subscription_Subscribed: _,
    SharedFiles_Subscription_NowUnsubscribed: _,
    Workshop_HasLinkedItems: _,
    Workshop_PaymentInfo_NotCreated: _,
    Workshop_PaymentInfo_Rejected: _,
    Workshop_SplitsAcceptTheseDesc1: _,
    Workshop_SplitsAcceptTheseDesc2: _,
    Workshop_SplitsPercentage: _,
    Profile_YourWorkshop: _,
    CommunityFollower_Description: _,
    CommunityFollower_Description_Yours: _,
    CommunityFollower_One_Follower: _,
    CommunityFollower_NumFollowers: _,
    CommunityFollower_FollowUser: _,
    CommunityFollower_FollowingUser: _,
    CommunityFollower_UnfollowUser: _,
    Workshop_ViewYourRevenue: _,
    Workshop_ViewYourRevenue_desc: _,
    Workshop_Link_PaymentInfo: _,
    Workshop_Link_LegalAgreement: _,
    SharedFiles_UnsubscribeAll_Btn: _,
    SharedFiles_UnsubscribeAll_Confirm_Title: _,
    SharedFiles_UnsubscribeAll_Confirm_Desc: _,
    SharedFiles_UnsubscribeAll_Confirm_App_Desc: _,
    SharedFiles_SaveSubscribedToCollection_Btn: _,
    SharedFiles_SaveSubscribedToCollection_Title: _,
    SharedFiles_SaveSubscribedToCollection_Desc: _,
    SharedFiles_SaveSubscribedToCollection_New: _,
    SharedFiles_SaveSubscribedToCollection_NewDesc: _,
    SharedFiles_SaveSubscribedToCollection_Existing: _,
    SharedFiles_SaveSubscribedToCollection_ExistingDesc: _,
    SharedFiles_SaveSubscribedToCollection_NoExistingCollections: _,
    SharedFiles_AdminTags: _,
    SharedFiles_SearchedForFileType_WebGuide: _,
    SharedFiles_SearchedForFileType_IntegratedGuide: _,
    SharedFiles_Dota2_IntegratedGuide: _,
    SharedFiles_Dota2_IntegratedGuide_Desc: _,
    AppHub_Guides_IntegratedGuides_Desc: _,
    AppHub_Guides_PopularCategories: _,
    AppHub_Guides_IntegratedGuides: _,
    AppHub_Guides_YourFavorites: _,
    AppHub_Guides_MostPopularThisWeek: _,
    AppHub_Guides_MostPopularThisWeek_Desc: _,
    AppHub_Guides_ViewAll: _,
    AppHub_Guides_NumGuides_Singular: _,
    AppHub_Guides_NumGuides_Plural: _,
    AppHub_Guides_GuidesYouHaveMade: _,
    AppHub_Guides_MoreInfo_Title: _,
    AppHub_Guides_MoreInfo_button: _,
    Workshop_BrowseBy: _,
    SharedFiles_Browse_GuideHome: _,
    SharedFiles_CreateGuide: _,
    SharedFiles_MustOwnAppToCreateGuide: _,
    SharedFiles_NoGuides_Title: _,
    SharedFiles_NoGuides_Desc1: _,
    SharedFiles_NoGuides_Desc2: _,
    SharedFiles_BrowseGuide_subtitle_nolink: _,
    SharedFiles_BrowseGuide_createNewBtnLabel: _,
    Community_Screenshots: _,
    Community_Images: _,
    Community_Videos: _,
    Paging_ShowingXtoYofZ: _,
    AppHubHome_BackToTop: _,
    Screenshots_Viewing: _,
    Profile_SharedFiles_ImageWallView: _,
    Profile_SharedFiles_GridView: _,
    Profile_SharedFiles_MostPopular: _,
    Profile_SharedFiles_NewestFirst: _,
    Profile_SharedFiles_OldestFirst: _,
    Screenshots_AllYourScreenshots: _,
    Screenshots_YourPublicScreenshots: _,
    Screenshots_YourFriendsOnlyScreenshots: _,
    Screenshots_YourPrivateScreenshots: _,
    Screenshots_YourUnlistedScreenshots: _,
    Images_AllYourImages: _,
    Images_YourPublicImages: _,
    Images_YourFriendsOnlyImages: _,
    Images_YourPrivateImages: _,
    Images_YourUnlistedImages: _,
    Videos_AllYourVideos: _,
    Videos_YourPublicVideos: _,
    Videos_YourFriendsOnlyVideos: _,
    Videos_YourPrivateVideos: _,
    Videos_YourUnlistedVideos: _,
    Screenshots_Manage: _,
    Images_Manage: _,
    Videos_Manage: _,
    Screenshots_SelectScreenshots: _,
    Images_SelectImages: _,
    Videos_SelectVideos: _,
    Videos_Cancel: _,
    Videos_AddFromYouTube: _,
    Videos_LinkYouTubeAcct: _,
    Videos_UnlinkYouTubeAcct: _,
    Videos_UnlinkButton: _,
    Videos_UnlinkConfirmText: _,
    Videos_Privacy: _,
    Videos_YoutubeTerms_1: _,
    Videos_YoutubeTerms_2: _,
    Videos_YoutubeTerms_3: _,
    Videos_YoutubeTerms_4: _,
    Videos_YoutubeTermsLink_TermsOfService: _,
    Videos_YoutubeTermsLink_PrivacyPolicy: _,
    Videos_YoutubeTermsLink_AuthorizedData: _,
    Videos_YoutubeTermsLink_SecuritySettings: _,
    Videos_NowOnSteam: _,
    Videos_ShareDescription: _,
    Videos_Desc1: _,
    Videos_Desc2: _,
    Videos_Desc3: _,
    Videos_AccessYourYouTubeVideos: _,
    Videos_CurrentlyLinkedTo: _,
    Videos_UnlinkToAddAnother: _,
    Videos_UnlinkAcct: _,
    Videos_ContinueWithAcct: _,
    Videos_SuccessfullyLinkedYouTube: _,
    Videos_SuccessfullyAddedSingular: _,
    Videos_SuccessfullyAddedPlural: _,
    Videos_NoVideosMsg1: _,
    Videos_NoVideosMsg2: _,
    Videos_CurrentlyLinkedMsg: _,
    Videos_ClickHereToChange: _,
    Videos_ChangeAccount: _,
    Videos_AddStep1: _,
    Videos_AvailCountSingular: _,
    Videos_AvailCountPlural: _,
    Videos_AddStep2: _,
    Videos_AddStep2Note: _,
    Videos_OptionNoneOther: _,
    Videos_OtherUnlisted: _,
    Videos_AddStep3: _,
    Videos_AddVideo: _,
    Videos_AddNote2: _,
    Videos_Refresh: _,
    Videos_AddStep4: _,
    Videos_AddNote4: _,
    Videos_AddDone: _,
    Videos_IssuesAccessing: _,
    Images_Upload: _,
    Screenshots_Upload: _,
    Screenshots_MakePublic: _,
    Screenshots_MakeFriendsOnly: _,
    Screenshots_MakePrivate: _,
    Screenshots_MakeUnlisted: _,
    Screenshots_Delete: `Sil`,
    Screenshots_SelectAll: _,
    Screenshots_Done: _,
    Screenshots_DeleteScreenshots: _,
    Screenshots_UpdatePrivacy: _,
    Screenshots_AreYouSureDelete: _,
    Screenshots_AreYouSurePrivacyChange: _,
    Screenshots_Continue: _,
    Screenshots_Cancel: _,
    Screenshots_Oops: _,
    Screenshots_NoneSelected: _,
    Screenshots_SelectScreenshotsToDelete: _,
    Screenshots_OK: _,
    Screenshots_VisUpdateFailed: _,
    Screenshots_VisUpdateFailedMessage: _,
    Blotter_PotentialSpoilers: _,
    Blotter_RevealImage: _,
    Profile_SharedFiles_NoScreenshotsSelf: _,
    Profile_SharedFiles_NoScreenshotsForYou: _,
    Profile_SharedFiles_NoScreenshotsFavoritesSelf: _,
    Profile_SharedFiles_NoScreenshotsFavoritesForYou: _,
    Profile_SharedFiles_NoImagesSelf: _,
    Profile_SharedFiles_NoImagesForYou: _,
    Profile_SharedFiles_NoImagesFavoritesSelf: _,
    Profile_SharedFiles_NoImagesFavoritesForYou: _,
    Profile_SharedFiles_NoVideosSelf: _,
    Profile_SharedFiles_NoVideosForYou: _,
    Profile_SharedFiles_NoVideosFavoritesSelf: _,
    Profile_SharedFiles_NoVideosFavoritesForYou: _,
    Profile_SharedFiles_NoScreenshotsThisVisibility: _,
    Screenshots_SteamHasThem: _,
    Screenshots_Instructions1: _,
    Screenshots_Instructions2: _,
    Profile_SharedFiles_By: _,
    Profile_SharedFiles_FavoritedBy: _,
  };
export {
  _ as AppHubHome_BackToTop,
  _ as AppHub_Guides_GuidesYouHaveMade,
  _ as AppHub_Guides_IntegratedGuides,
  _ as AppHub_Guides_IntegratedGuides_Desc,
  _ as AppHub_Guides_MoreInfo_Title,
  _ as AppHub_Guides_MoreInfo_button,
  _ as AppHub_Guides_MostPopularThisWeek,
  _ as AppHub_Guides_MostPopularThisWeek_Desc,
  _ as AppHub_Guides_NumGuides_Plural,
  _ as AppHub_Guides_NumGuides_Singular,
  _ as AppHub_Guides_PopularCategories,
  _ as AppHub_Guides_ViewAll,
  _ as AppHub_Guides_YourFavorites,
  _ as AppPrivacy_Explanation,
  _ as AppPrivacy_MarkAsPrivate,
  _ as AppPrivacy_UnmarkAsPrivate,
  _ as Blotter_PotentialSpoilers,
  _ as Blotter_RevealImage,
  _ as CommunityFollower_Description,
  _ as CommunityFollower_Description_Yours,
  _ as CommunityFollower_FollowUser,
  _ as CommunityFollower_FollowingUser,
  _ as CommunityFollower_NumFollowers,
  _ as CommunityFollower_One_Follower,
  _ as CommunityFollower_UnfollowUser,
  _ as Community_Forums,
  _ as Community_FriendsWhoPlayMenuItemFirstPerson,
  _ as Community_GameContent,
  _ as Community_GameContentFirstPerson,
  _ as Community_GameHubMenuItem,
  _ as Community_GameLinks,
  _ as Community_GameNotesFirstPerson,
  _ as Community_GamePersonalData,
  _ as Community_GameStats,
  _ as Community_GameStatsFirstPerson,
  _ as Community_GlobalAchievements,
  _ as Community_GlobalLeaderboards,
  _ as Community_Groups,
  _ as Community_Images,
  _ as Community_News,
  _ as Community_OfficialWebsite,
  _ as Community_RemoveLink_BeWary,
  _ as Community_RemoveLink_Tooltip,
  _ as Community_ReviewMenuItemFirstPerson,
  _ as Community_ReviewMenuItemThirdPerson,
  _ as Community_Screenshots,
  _ as Community_ScreenshotsMenuItemFirstPerson,
  _ as Community_ScreenshotsMenuItemThirdPerson,
  _ as Community_StorePage,
  _ as Community_TradingCardsMenuItemFirstPerson,
  _ as Community_UsersAchievements,
  _ as Community_UsersAchievementsFirstPerson,
  _ as Community_UsersLeaderboards,
  _ as Community_UsersLeaderboardsFirstPerson,
  _ as Community_UsersStats,
  _ as Community_Videos,
  _ as Discussions_FormattingHelp_Quote,
  _ as Discussions_FormattingHelp_Spoiler,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as GamesList_Achievement_Fraction,
  _ as GamesList_Achievement_Unlock_Percentage,
  _ as GamesList_Button_Cancel,
  _ as GamesList_Button_Download,
  _ as GamesList_Button_Pause,
  _ as GamesList_Button_Resume,
  _ as GamesList_Button_Uninstall,
  _ as GamesList_Button_Uninstalling,
  _ as GamesList_Button_UpdateRequired,
  _ as GamesList_Client_Indicator,
  _ as GamesList_Filter_BothOwned,
  _ as GamesList_Filter_Placeholder,
  _ as GamesList_Header_Achievements,
  _ as GamesList_Header_DownloadBytes,
  _ as GamesList_Header_Downloading,
  _ as GamesList_Header_LastPlayed,
  _ as GamesList_Header_Paused,
  _ as GamesList_Header_RemoteDownload,
  _ as GamesList_Header_RemoteDownloadStatus,
  _ as GamesList_Header_TotalPlayed,
  _ as GamesList_Header_TwoWeeks,
  _ as GamesList_MenuLabel_GameInfo,
  _ as GamesList_MenuLabel_RemoteDownload,
  _ as GamesList_PerfectGames_Description,
  _ as GamesList_PrivacySettings_Tooltip,
  _ as GamesList_RemoteDownload_Help,
  _ as GamesList_RemoteDownload_Info,
  _ as GamesList_RemoteDownload_LearnMore,
  _ as GamesList_RemoteDownload_NoConnection,
  _ as GamesList_RemoteDownload_NoRemoteControl,
  _ as GamesList_RemoteDownload_ReadTheFAQ,
  _ as GamesList_RemoteDownload_UninstallConfirm,
  _ as GamesList_Sort_AchievementCompletion,
  _ as GamesList_Sort_HoursPlayed,
  _ as GamesList_Sort_Name,
  _ as GamesList_Tab_AllGames,
  _ as GamesList_Tab_Followed,
  _ as GamesList_Tab_PerfectGames,
  _ as GamesList_Tab_RecentlyPlayed,
  _ as GamesList_Tab_Reviews,
  _ as GamesList_Tab_Wishlist,
  _ as GamesList_TimeRemaining,
  _ as GamesList_Uninstalling,
  _ as Images_AllYourImages,
  _ as Images_Manage,
  _ as Images_SelectImages,
  _ as Images_Upload,
  _ as Images_YourFriendsOnlyImages,
  _ as Images_YourPrivateImages,
  _ as Images_YourPublicImages,
  _ as Images_YourUnlistedImages,
  _ as Loading,
  _ as Market_GenericTitle,
  _ as Market_Item_GenericTitle,
  _ as Market_Item_Title,
  _ as Market_Search_Title,
  _ as Moderation_SubjectTypeName_ForumPost,
  _ as Paging_ShowingXtoYofZ,
  _ as Perfect_Game_Description,
  _ as Playtime_Hours,
  _ as Playtime_Minutes,
  _ as Profile_Collections,
  _ as Profile_Guides,
  _ as Profile_Images,
  _ as Profile_Screenshots,
  _ as Profile_SharedFiles_AllGames,
  _ as Profile_SharedFiles_By,
  _ as Profile_SharedFiles_FavoritedBy,
  _ as Profile_SharedFiles_GridView,
  _ as Profile_SharedFiles_ImageWallView,
  _ as Profile_SharedFiles_MostPopular,
  _ as Profile_SharedFiles_NewestFirst,
  _ as Profile_SharedFiles_NoImagesFavoritesForYou,
  _ as Profile_SharedFiles_NoImagesFavoritesSelf,
  _ as Profile_SharedFiles_NoImagesForYou,
  _ as Profile_SharedFiles_NoImagesSelf,
  _ as Profile_SharedFiles_NoScreenshotsFavoritesForYou,
  _ as Profile_SharedFiles_NoScreenshotsFavoritesSelf,
  _ as Profile_SharedFiles_NoScreenshotsForYou,
  _ as Profile_SharedFiles_NoScreenshotsSelf,
  _ as Profile_SharedFiles_NoScreenshotsThisVisibility,
  _ as Profile_SharedFiles_NoVideosFavoritesForYou,
  _ as Profile_SharedFiles_NoVideosFavoritesSelf,
  _ as Profile_SharedFiles_NoVideosForYou,
  _ as Profile_SharedFiles_NoVideosSelf,
  _ as Profile_SharedFiles_OldestFirst,
  _ as Profile_SharedFiles_SelectAGame,
  _ as Profile_Videos,
  _ as Profile_Workshop_Items,
  _ as Profile_YourWorkshop,
  _ as Screenshots_AllYourScreenshots,
  _ as Screenshots_AreYouSureDelete,
  _ as Screenshots_AreYouSurePrivacyChange,
  _ as Screenshots_Cancel,
  _ as Screenshots_Continue,
  _ as Screenshots_Delete,
  _ as Screenshots_DeleteScreenshots,
  _ as Screenshots_Done,
  _ as Screenshots_Instructions1,
  _ as Screenshots_Instructions2,
  _ as Screenshots_Location,
  _ as Screenshots_MakeFriendsOnly,
  _ as Screenshots_MakePrivate,
  _ as Screenshots_MakePublic,
  _ as Screenshots_MakeUnlisted,
  _ as Screenshots_Manage,
  _ as Screenshots_NoneSelected,
  _ as Screenshots_OK,
  _ as Screenshots_Oops,
  _ as Screenshots_SelectAll,
  _ as Screenshots_SelectScreenshots,
  _ as Screenshots_SelectScreenshotsToDelete,
  _ as Screenshots_SteamHasThem,
  _ as Screenshots_UpdatePrivacy,
  _ as Screenshots_Upload,
  _ as Screenshots_Viewing,
  _ as Screenshots_VisUpdateFailed,
  _ as Screenshots_VisUpdateFailedMessage,
  _ as Screenshots_YourFriendsOnlyScreenshots,
  _ as Screenshots_YourPrivateScreenshots,
  _ as Screenshots_YourPublicScreenshots,
  _ as Screenshots_YourUnlistedScreenshots,
  _ as SharedFiles_AddSpoilerTag,
  _ as SharedFiles_AdminTags,
  _ as SharedFiles_And_N_More,
  _ as SharedFiles_BrowseGuide_createNewBtnLabel,
  _ as SharedFiles_BrowseGuide_subtitle_nolink,
  _ as SharedFiles_Browse_GuideHome,
  _ as SharedFiles_Browse_MyFiles_Favorites,
  _ as SharedFiles_Browse_MyFiles_Items,
  _ as SharedFiles_Browse_MyFiles_Played,
  _ as SharedFiles_Browse_MyFiles_Sort_Alpha,
  _ as SharedFiles_Browse_MyFiles_Sort_CreationOrder,
  _ as SharedFiles_Browse_MyFiles_Sort_Favorited,
  _ as SharedFiles_Browse_MyFiles_Sort_LastUpdated,
  _ as SharedFiles_Browse_MyFiles_Sort_Subscribed,
  _ as SharedFiles_Browse_MyFiles_Subscriptions,
  _ as SharedFiles_ByAuthor,
  _ as SharedFiles_CreateGuide,
  _ as SharedFiles_DeveloperComments,
  _ as SharedFiles_Dota2_IntegratedGuide,
  _ as SharedFiles_Dota2_IntegratedGuide_Desc,
  _ as SharedFiles_Favorites,
  _ as SharedFiles_Favorites_NowUnsubscribed,
  _ as SharedFiles_Favorites_Subscribed,
  _ as SharedFiles_FilterByGame,
  _ as SharedFiles_Guide_Comments,
  _ as SharedFiles_Guide_Index,
  _ as SharedFiles_Guide_Overview,
  _ as SharedFiles_ItemDownload,
  _ as SharedFiles_ItemEditText_ErrorNoTitle,
  _ as SharedFiles_ItemEditText_Text_Caption,
  _ as SharedFiles_Item_Edit_Link,
  _ as SharedFiles_ManageGuide_AddContributor,
  _ as SharedFiles_ManageGuide_AddSection,
  _ as SharedFiles_ManageGuide_Cancel,
  _ as SharedFiles_ManageGuide_Contents,
  _ as SharedFiles_ManageGuide_Contents_Desc,
  _ as SharedFiles_ManageGuide_Contributors,
  _ as SharedFiles_ManageGuide_Contributors_Desc,
  _ as SharedFiles_ManageGuide_DeleteThisSection,
  _ as SharedFiles_ManageGuide_EditSubSection,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Delete,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Desc,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Insert,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Changes,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Edit,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Preview,
  _ as SharedFiles_ManageGuide_EditThisSection,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_Layout,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutInline,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutLeft,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutRight,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_Size,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeFull,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeOriginal,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeThumb,
  _ as SharedFiles_ManageGuide_Images,
  _ as SharedFiles_ManageGuide_Images_Desc,
  _ as SharedFiles_ManageGuide_InsertImage,
  _ as SharedFiles_ManageGuide_InsertYouTubeVideo,
  _ as SharedFiles_ManageGuide_NoContributors,
  _ as SharedFiles_ManageGuide_NoPreviewImages,
  _ as SharedFiles_ManageGuide_NoSectionTitle,
  _ as SharedFiles_ManageGuide_NoSubSections,
  _ as SharedFiles_ManageGuide_Preview,
  _ as SharedFiles_ManageGuide_PromptYouTubeUrl,
  _ as SharedFiles_ManageGuide_RemoveSectionConfirm,
  _ as SharedFiles_ManageGuide_Required,
  _ as SharedFiles_ManageGuide_Save,
  _ as SharedFiles_ManageGuide_Screenshots,
  _ as SharedFiles_ManageGuide_SubImages,
  _ as SharedFiles_ManageGuide_SubScreenshots,
  _ as SharedFiles_ManageGuide_SubSectionContentChanged,
  _ as SharedFiles_ManageGuide_SubSectionContentChanged_CancelConfirm,
  _ as SharedFiles_ManageGuide_SubSectionContentSaved,
  _ as SharedFiles_ManageGuide_SubSectionContents,
  _ as SharedFiles_ManageGuide_SubSectionTitle,
  _ as SharedFiles_ManageGuide_SubVideos,
  _ as SharedFiles_ManageGuide_Videos,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Full,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Left,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Right,
  _ as SharedFiles_Media_ViewAppFanArt,
  _ as SharedFiles_Media_ViewAppScreenshots,
  _ as SharedFiles_Media_ViewAppVideos,
  _ as SharedFiles_MustOwnAppToCreateGuide,
  _ as SharedFiles_NoGuides_Desc1,
  _ as SharedFiles_NoGuides_Desc2,
  _ as SharedFiles_NoGuides_Title,
  _ as SharedFiles_OwnerControl_BackGuide,
  _ as SharedFiles_OwnerControl_EditCaption,
  _ as SharedFiles_PublicComments,
  _ as SharedFiles_RemoveSelfTag_Tooltip,
  _ as SharedFiles_RemoveSpoilerTag,
  _ as SharedFiles_SaveSubscribedToCollection_Btn,
  _ as SharedFiles_SaveSubscribedToCollection_Desc,
  _ as SharedFiles_SaveSubscribedToCollection_Existing,
  _ as SharedFiles_SaveSubscribedToCollection_ExistingDesc,
  _ as SharedFiles_SaveSubscribedToCollection_New,
  _ as SharedFiles_SaveSubscribedToCollection_NewDesc,
  _ as SharedFiles_SaveSubscribedToCollection_NoExistingCollections,
  _ as SharedFiles_SaveSubscribedToCollection_Title,
  _ as SharedFiles_SearchedForFileType_IntegratedGuide,
  _ as SharedFiles_SearchedForFileType_WebGuide,
  _ as SharedFiles_SharedFiles_Collections,
  _ as SharedFiles_SharedFiles_Guides,
  _ as SharedFiles_SharedFiles_Items,
  _ as SharedFiles_SpoilerTagInstructions,
  _ as SharedFiles_SpoilerTagsExpire,
  _ as SharedFiles_Stats_TaggedUsers,
  _ as SharedFiles_Stats_TaggedWorkshopItems,
  _ as SharedFiles_Subscription_NowUnsubscribed,
  _ as SharedFiles_Subscription_Subscribed,
  _ as SharedFiles_Subscriptions,
  _ as SharedFiles_Tab_Merchandise,
  _ as SharedFiles_Tags,
  _ as SharedFiles_TagsSearch,
  _ as SharedFiles_UnsubscribeAll_Btn,
  _ as SharedFiles_UnsubscribeAll_Confirm_App_Desc,
  _ as SharedFiles_UnsubscribeAll_Confirm_Desc,
  _ as SharedFiles_UnsubscribeAll_Confirm_Title,
  _ as SharedFiles_UserList_BrowsePaging,
  _ as SharedFiles_UserList_LastUpdated,
  _ as SharedFiles_WaitingForIntegratedGuide,
  _ as SharedFiles_WorkshopItemsTagged,
  _ as Videos_AccessYourYouTubeVideos,
  _ as Videos_AddDone,
  _ as Videos_AddFromYouTube,
  _ as Videos_AddNote2,
  _ as Videos_AddNote4,
  _ as Videos_AddStep1,
  _ as Videos_AddStep2,
  _ as Videos_AddStep2Note,
  _ as Videos_AddStep3,
  _ as Videos_AddStep4,
  _ as Videos_AddVideo,
  _ as Videos_AllYourVideos,
  _ as Videos_AvailCountPlural,
  _ as Videos_AvailCountSingular,
  _ as Videos_Cancel,
  _ as Videos_ChangeAccount,
  _ as Videos_ClickHereToChange,
  _ as Videos_ContinueWithAcct,
  _ as Videos_CurrentlyLinkedMsg,
  _ as Videos_CurrentlyLinkedTo,
  _ as Videos_Desc1,
  _ as Videos_Desc2,
  _ as Videos_Desc3,
  _ as Videos_IssuesAccessing,
  _ as Videos_LinkYouTubeAcct,
  _ as Videos_Manage,
  _ as Videos_NoVideosMsg1,
  _ as Videos_NoVideosMsg2,
  _ as Videos_NowOnSteam,
  _ as Videos_OptionNoneOther,
  _ as Videos_OtherUnlisted,
  _ as Videos_Privacy,
  _ as Videos_Refresh,
  _ as Videos_SelectVideos,
  _ as Videos_ShareDescription,
  _ as Videos_SuccessfullyAddedPlural,
  _ as Videos_SuccessfullyAddedSingular,
  _ as Videos_SuccessfullyLinkedYouTube,
  _ as Videos_UnlinkAcct,
  _ as Videos_UnlinkButton,
  _ as Videos_UnlinkConfirmText,
  _ as Videos_UnlinkToAddAnother,
  _ as Videos_UnlinkYouTubeAcct,
  _ as Videos_YourFriendsOnlyVideos,
  _ as Videos_YourPrivateVideos,
  _ as Videos_YourPublicVideos,
  _ as Videos_YourUnlistedVideos,
  _ as Videos_YoutubeTermsLink_AuthorizedData,
  _ as Videos_YoutubeTermsLink_PrivacyPolicy,
  _ as Videos_YoutubeTermsLink_SecuritySettings,
  _ as Videos_YoutubeTermsLink_TermsOfService,
  _ as Videos_YoutubeTerms_1,
  _ as Videos_YoutubeTerms_2,
  _ as Videos_YoutubeTerms_3,
  _ as Videos_YoutubeTerms_4,
  _ as Workshop_BrowseBy,
  _ as Workshop_BrowsePaging,
  _ as Workshop_DeveloperThreadDesc,
  _ as Workshop_DeveloperThreadDisclaimerText,
  _ as Workshop_HasLinkedItems,
  _ as Workshop_ImageSize,
  _ as Workshop_ItemModalViewCountDetails,
  _ as Workshop_ItemModalViewDetails,
  _ as Workshop_Link_LegalAgreement,
  _ as Workshop_Link_PaymentInfo,
  _ as Workshop_NoItems,
  _ as Workshop_PaymentInfo_NotCreated,
  _ as Workshop_PaymentInfo_Rejected,
  _ as Workshop_SplitsAcceptTheseDesc1,
  _ as Workshop_SplitsAcceptTheseDesc2,
  _ as Workshop_SplitsPercentage,
  _ as Workshop_Subscribe_IntegratedGuide,
  _ as Workshop_ViewYourRevenue,
  _ as Workshop_ViewYourRevenue_desc,
  _ as community_errorpage_title,
  _ as community_title,
  _ as default,
  _ as empty_no_comma_following,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_accessibility,
  _ as footer_cookies,
  _ as footer_geodata_notice,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_privacy_policy,
  _ as footer_refunds,
  _ as footer_ssa,
  _ as moderatedcontent_description,
  _ as moderation_claim_n_reports_on_m_subjects,
  _ as moderation_claim_report_count,
  _ as moderation_claim_report_count_Plural,
  _ as moderation_claim_subject_count,
  _ as moderation_claim_subject_count_Plural,
  _ as moderation_forumpost_summary,
  _ as moderation_forumpost_summary_reports_fragment,
  _ as moderation_forumpost_summary_reports_fragment_Plural,
  _ as moderation_forumpost_summary_subjects_fragment,
  _ as moderation_forumpost_summary_subjects_fragment_Plural,
  _ as profile_error_profilenotfound,
  _ as profile_games_list,
  _ as profile_games_list_error_loadfailed,
  _ as profile_games_list_title,
  _ as profiletabs_communitymessages,
  _ as profiletabs_currentbans,
  _ as profiletabs_moderatedcontent,
  _ as profiletabs_reportedcontent,
  _ as reportedcontent_description,
  _ as reportedcontent_lastupdated,
};
