var _ = `koreana`,
  _ = `Steam 창작마당`,
  _ = `%1$s Steam 창작마당`,
  _ = `해당 페이지를 불러오는 도중 오류가 발생했습니다. 나중에 다시 시도해 주세요.`,
  _ = `오류!`,
  _ = `오류가 발생했습니다. 나중에 다시 시도해 주세요.(%1$s)`,
  _ = `죄송합니다!`,
  _ = `요청을 처리하는 도중 오류가 발생했습니다.`,
  _ = `너무 많은 요청을 보냈습니다. 잠시 기다렸다가 나중에 다시 시도해 주세요.`,
  _ = `(관리자 전용) 이전 창작마당 보기`,
  _ = `검색: %1$s`,
  _ = `(마음에 드는 콘텐츠에 투표하세요.)`,
  _ = `(콘텐츠를 게임에 추가하려면 구독하세요.)`,
  _ = `(마음에 드는 콘텐츠에 투표하세요.)`,
  _ = `승인된 콘텐츠`,
  _ = `승인 완료`,
  _ = `공식 콘텐츠`,
  _ = `제작자: %1$s`,
  _ = `콘텐츠`,
  _ = `콘텐츠`,
  _ = `모음집`,
  _ = `상품`,
  _ = `동영상`,
  _ = `저장된 쿼리`,
  _ = `이 검색 쿼리 저장`,
  _ = `검색 쿼리 이름 입력`,
  _ = `현재 사용 중인 검색 쿼리 필터와 정렬 옵션을 저장하여 나중에 더 빠르게 검색할 수 있습니다. 저장된 쿼리는 '내 콘텐츠'에서 확인할 수 있습니다.`,
  _ = `새 검색 쿼리로 저장하거나 기존 검색 쿼리를 선택하여 업데이트하세요.`,
  _ = `<새롭게 저장된 검색>`,
  _ = `저장`,
  _ = `저장된 검색 삭제`,
  _ = `저장된 검색('%1$s')을 삭제할까요?`,
  _ = `삭제`,
  _ = `자세한 정보`,
  _ = `필터 제거`,
  _ = `%1$s 창작마당`,
  _ = `정렬 순서`,
  _ = `기간`,
  _ = `오늘`,
  _ = `1주`,
  _ = `30일`,
  _ = `3개월`,
  _ = `6개월`,
  _ = `1년`,
  _ = `전체`,
  _ = `%1$s(%2$s)`,
  _ = `최근 출시순`,
  _ = `인기순`,
  _ = `최고 평가순(전체 기간)`,
  _ = `최근 업데이트`,
  _ = `신고 가중치`,
  _ = `(관리자) %1$s`,
  _ = `다른 콘텐츠에 가장 많이 필요한 콘텐츠`,
  _ = `대부분 모음집에 포함된 콘텐츠`,
  _ = `(관리자) 승인 대기열`,
  _ = `아직 평가가 없는 콘텐츠`,
  _ = `전체 구독자 수`,
  _ = `전체 투표수`,
  _ = `최다 추천`,
  _ = `검색 관련성`,
  _ = `최근 플레이 시간`,
  _ = `전체 플레이 시간`,
  _ = `최근 평균 플레이 시간`,
  _ = `전체 평균 플레이 시간`,
  _ = `플레이 세션`,
  _ = `전체 플레이 세션`,
  _ = `Inappropriate Score`,
  _ = `Ban Content Check`,
  _ = `Curated Admin`,
  _ = `후보작`,
  _ = `내가 평가한 콘텐츠`,
  _ = `승인 날짜`,
  _ = `특수 필터: `,
  _ = `없음`,
  _ = `승인된 콘텐츠`,
  _ = `친구가 제작한 콘텐츠`,
  _ = `팔로우한 제작자의 콘텐츠`,
  _ = `친구가 좋아하는 콘텐츠`,
  _ = `신고됨(관리자 전용)`,
  _ = `다른 콘텐츠에 필요한 콘텐츠`,
  _ = `모음집에 포함된 콘텐츠`,
  _ = `홈`,
  _ = `검색`,
  _ = `내 콘텐츠`,
  _ = `토론`,
  _ = `소개`,
  _ = `%1$s 검색`,
  _ = `내가 게시한 콘텐츠(%1$s)`,
  _ = `즐겨찾기(%1$s)`,
  _ = `구독한 콘텐츠(%1$s)`,
  _ = `플레이한 콘텐츠(%1$s)`,
  _ = `내 모음집(%1$s)`,
  _ = `투표 대기열`,
  _ = `결제 정보`,
  _ = `수익 보기`,
  _ = `(창작마당 콘텐츠 판매 수익)`,
  _ = `이용 약관 보기`,
  _ = `투표 대기열`,
  _ = `필터 적용`,
  _ = `정렬 기준: %1$s`,
  _ = `<선택 안 함>`,
  _ = `필요한 DLC`,
  _ = `필요한 DLC: %1$s`,
  _ = `소유한 DLC 포함`,
  _ = `소유하지 않은 DLC가 필요한 콘텐츠 제외`,
  _ = `소유한 DLC가 없습니다.`,
  _ = `모든 DLC를 소유하고 있습니다.`,
  _ = `(이외 %1$s개)`,
  _ = `소유한 DLC 포함`,
  _ = `소유하지 않은 DLC 제외`,
  _ = `이름으로 필터링`,
  _ = `사용할 수 없는 콘텐츠 보기`,
  _ = `종종 콘텐츠를 게임에 추가할 수 없는 경우가 있습니다. 이 체크박스를 선택하면 이러한 콘텐츠를 확인할 수 있습니다.`,
  _ = `숨겨진 콘텐츠 및 친구 공개 콘텐츠 보기`,
  _ = `'%1$s' 검색 결과`,
  _ = `검색 결과: '%1$s'(제목 기준)`,
  _ = `검색 결과: '%1$s'(설명 기준)`,
  _ = `포함 콘텐츠: '%1$s'`,
  _ = `정상 작동을 위해 필요한 콘텐츠: '%1$s'`,
  _ = `%1$s: %2$s`,
  _ = `%1$s: %2$s`,
  _ = `태그: 사용할 수 없는 콘텐츠`,
  _ = `태그: 승인된 콘텐츠`,
  _ = `콘텐츠 검색 기준을 선택하세요.`,
  _ = `제목 및 설명 검색`,
  _ = `제목`,
  _ = `설명`,
  _ = `%1$s, %2$s, %3$s 연산자(대문자로 입력 필수)를 사용하여 더 구체적으로 검색할 수 있습니다. 또한 %1$s 및 %3$s 연산자 대신 %4$s 및 %5$s 문자를 사용할 수도 있습니다.`,
  _ = `'%1$s'으로 검색하면 검색 텍스트에서 '%2$s' 및 '%3$s' 검색어를 모두 포함한 콘텐츠를 찾습니다.`,
  _ = `'%1$s'으로 검색하면 사용하면 검색 텍스트에서 '%2$s' 또는 '%3$s' 검색어를 포함한 콘텐츠를 찾습니다.`,
  _ = `'%1$s'으로 검색하면 사용하면 검색 텍스트에서 '%2$s' 검색어를 포함하지만 '%3$s' 검색어는 포함하지 않은 콘텐츠를 찾습니다.`,
  _ = `빨간색`,
  _ = `파란색`,
  _ = `초록색`,
  _ = `방`,
  _ = `검색어에 괄호를 조합하여 사용하면 더 구체적으로 검색할 수 있습니다.`,
  _ = `'%1$s'으로 검색하면 검색 텍스트에서 '%2$s' 검색어와 함께 '%3$s' 또는 '%4$s' 검색어를 포함한 콘텐츠를 찾습니다.`,
  _ = `'%1$s'으로 검색하면 검색 텍스트에서 '%2$s' 검색어와 함께 '%3$s' 또는 '%4$s' 검색어를 포함하지만 '%5$s' 검색어를 포함하지 않은 콘텐츠를 찾습니다.`,
  _ = `필터 표시 위치:`,
  _ = `왼쪽`,
  _ = `오른쪽`,
  _ = `접기`,
  _ = `다음 콘텐츠 숨기기:`,
  _ = `신고한 콘텐츠`,
  _ = `차단한 사용자가 제작한 콘텐츠`,
  _ = `추천한 콘텐츠`,
  _ = `비추천한 콘텐츠`,
  _ = `구독 목록에 있는 콘텐츠`,
  _ = `날짜로 필터링`,
  _ = `게시 날짜`,
  _ = `%1$s 이후 게시`,
  _ = `%1$s 이전 게시`,
  _ = `게시 날짜: %1$s~%2$s 사이`,
  _ = `마지막 업데이트 날짜`,
  _ = `%1$s 이후 업데이트`,
  _ = `%1$s 이전 업데이트`,
  _ = `업데이트 날짜: %1$s~%2$s 사이`,
  _ = `기간:`,
  _ = `~`,
  _ = `필터와 일치하는 콘텐츠: 1개`,
  _ = `필터와 일치하는 콘텐츠: %2$s개`,
  _ = `페이지당:`,
  _ = `%1$s/%2$s`,
  _ = `모음집 만들기`,
  _ = `디자인 제출`,
  _ = `빠른 보기`,
  _ = `더 보기`,
  _ = `이 콘텐츠를 구독하고 있습니다.`,
  _ = `이 콘텐츠는 즐겨찾기 목록에 있습니다.`,
  _ = `플레이한 콘텐츠`,
  _ = `이 콘텐츠는 승인되어 이 게임 내에서 사용할 수 있습니다!`,
  _ = `이 콘텐츠는 해당 게임과 호환되지 않는 것으로 표시되었습니다.`,
  _ = `이 콘텐츠를 추천했습니다.`,
  _ = `이 콘텐츠를 비추천했습니다.`,
  _ = `Steam 커뮤니티 가이드라인 위반하는 콘텐츠로 신고했습니다.`,
  _ = `이 사용자를 차단했습니다.`,
  _ = `설명`,
  _ = `토론`,
  _ = `댓글(%1$s)`,
  _ = `공지`,
  _ = `콘텐츠 통계`,
  _ = `업데이트 노트(%1$s)`,
  _ = `Steam 창작마당 :: %1$s`,
  _ = `제작자: `,
  _ = `평점 %2$s`,
  _ = `평점 %2$s`,
  _ = `평점 부족`,
  _ = `%1$s %2$s`,
  _ = `게시일:`,
  _ = `업데이트한 날짜:`,
  _ = `구독`,
  _ = `구독함`,
  _ = `구독 취소`,
  _ = `즐겨찾기에 추가`,
  _ = `즐겨찾기에 추가됨`,
  _ = `즐겨찾기에서 제거`,
  _ = `연동 콘텐츠 보기`,
  _ = `모음집에 추가`,
  _ = `모음집에 저장`,
  _ = `이 작업을 수행하려면 로그인하세요.`,
  _ = `다운로드하려면 구독하세요.`,
  _ = `콘텐츠를 게임에서 제거하려면 구독을 취소하세요.`,
  _ = `나중에 이 콘텐츠를 쉽게 찾을 수 있도록 즐겨찾기에 추가하세요.`,
  _ = `이 콘텐츠와 연동해야 정상적으로 사용할 수 있는 콘텐츠 %1$s개를 모두 표시합니다. 일부 콘텐츠는 비공개 또는 친구 공개로 설정되어 있을 수 있습니다.`,
  _ = `Steam 온라인 행동 규칙을 위반한 콘텐츠로 신고하세요.`,
  _ = `어워드를 수여하세요.`,
  _ = `모음집에 추가하세요.`,
  _ = `파일 크기:`,
  _ = `방문자 수:`,
  _ = `구독자 수:`,
  _ = `즐겨찾기:`,
  _ = `전체 고유 즐겨찾기 수:`,
  _ = `전체 구독자 수:`,
  _ = `전체 플레이 세션:`,
  _ = `필요한 콘텐츠:`,
  _ = `필요한 DLC:`,
  _ = `모두 구독`,
  _ = `모든 구독 취소`,
  _ = `모음집에 저장`,
  _ = `커뮤니티 어워드 모두 보기`,
  _ = `커뮤니티 어워드 %1$s개`,
  _ = `커뮤니티 어워드 %1$s개`,
  _ = `태그`,
  _ = `카테고리`,
  _ = `설명`,
  _ = `필수:`,
  _ = `%1$s 모음집에 포함됨`,
  _ = `%2$s님의 %1$s 모음집에 포함됨`,
  _ = `오류`,
  _ = `이 작업을 수행할 권한이 없습니다.`,
  _ = `Steam과 통신하는 도중 오류가 발생했습니다. 나중에 다시 시도해 주세요.`,
  _ = `짧은 시간 내에 너무 많은 작업을 시도했습니다. 잠시 기다렸다가 다시 시도해 주세요.`,
  _ = `오류가 발생했습니다. 나중에 다시 시도해 주세요.`,
  _ = `모두 구독`,
  _ = `이 모음집의 콘텐츠를 구독에 추가하거나 기존 구독에 이 모음집의 콘텐츠만 포함하도록 구독을 덮어쓸까요?`,
  _ = `기존 구독에 추가`,
  _ = `기존 구독 덮어쓰기`,
  _ = `추가로 필요한 콘텐츠`,
  _ = `이 콘텐츠를 이용하려면 다음 콘텐츠가 모두 필요합니다.`,
  _ = `<1>%1$s</1> 콘텐츠를 이용하려면 다음 콘텐츠가 모두 필요합니다.`,
  _ = `각 콘텐츠를 클릭하여 자세한 정보를 확인한 후 구독할 수 있습니다.`,
  _ = `추가로 필요한 모든 콘텐츠와 이러한 추가 콘텐츠에 필요한 모든 콘텐츠까지 구독할 수도 있지만 그러면 훨씬 더 많은 콘텐츠가 포함될 수 있다는 점에 유의하세요.`,
  _ = `이 콘텐츠만 구독`,
  _ = `모두 구독`,
  _ = `콘텐츠 신고`,
  _ = `이 콘텐츠가 Steam 서비스 약관에 위반되는 이유를 설명해 주세요. 이와 관련된 정보와 링크를 모두 포함해 주세요. 이 신고 제출은 취소할 수 없습니다.`,
  _ = `이유: %1$s`,
  _ = `먼저 이 콘텐츠를 신고하는 이유를 선택해 주세요.`,
  _ = `저작권을 보유하고 있으며 저작권 침해를 신고하고자 하는 경우, DMCA 저작권 침해 신고서(%1$s)를 작성하여 제출해 주세요.`,
  _ = `상표권 침해 관련 문제는 %1$s에서 신고해 주세요.`,
  _ = `여기`,
  _ = `모음집에 추가`,
  _ = `'%1$s' 콘텐츠가 아래 선택된 모음집에 추가됩니다.`,
  _ = `저장된 모읍집이 없습니다. 아래에 이름을 입력하여 새 모음집을 만들 수 있습니다.`,
  _ = `선택한 모음집에 추가`,
  _ = `새 모음집 만들기`,
  _ = `모음집 덮어쓰기`,
  _ = `이 모음집을 새 모음집에 저장하거나 기존 모음집에 덮어쓸까요?`,
  _ = `새 모음집`,
  _ = `기존 모음집`,
  _ = `모음집 이름 입력:`,
  _ = `덮어쓸 모음집 선택:`,
  _ = `포함된 콘텐츠: %2$s개`,
  _ = `포함된 콘텐츠: %2$s개`,
  _ = `연결된 모음집: %2$s개`,
  _ = `연결된 모음집: %2$s개`,
  _ = `+%1$s`,
  _ = `Steam 창작마당은 완성된 3D 모델을 제출하고 실제 게임에 적용시킬 수 있는 가장 쉬운 방법입니다. 창작마당에 콘텐츠를 올려 개발자가 선택을 고려하도록 하려면, 먼저 오른쪽에 링크된 공식 문서를 읽어보고 게임 내 주 메뉴에서 '창작마당' 버튼을 누르세요.`,
  _ = `Steam 창작마당을 통해 게임이나 소프트웨어를 위한 새로운 콘텐츠를 더 쉽게 찾고 공유할 수 있습니다. 각각의 게임과 소프트웨어가 창작마당 내에서 지원하는 콘텐츠 유형이 조금씩 다를 수 있으므로 어떤 콘텐츠를 제작하고 공유할 수 있는지는 공식 문서를 참고하는 것이 좋습니다.`,
  _ = `게임에 추가하고 싶은 콘텐츠를 찾았다면 '구독' 버튼을 누르세요. 대부분의 경우 게임을 실행하면 콘텐츠를 자동으로 이용할 수 있지만 일부 콘텐츠는 게임이나 소프트웨어 내에서 콘텐츠를 활성화해야 이용할 수 있습니다.`,
  _ = `Steam 창작마당을 통해 게임이나 소프트웨어를 위한 새로운 콘텐츠를 더 쉽게 찾고 공유할 수 있습니다. 각각의 게임이 창작마당 내에서 지원하는 콘텐츠 유형이 조금씩 다를 수 있으므로 어떤 콘텐츠를 제작하고 공유할 수 있는지는 공식 문서를 참고하는 것이 좋습니다.`,
  _ = `%1$s 탭에서 게임에 추가하고 싶은 콘텐츠를 찾았다면 '구독' 버튼을 누르세요. 대부분의 경우 게임을 실행하면 콘텐츠를 자동으로 이용할 수 있지만 일부 콘텐츠는 게임이나 소프트웨어 내에서 콘텐츠를 활성화해야 이용할 수 있습니다.`,
  _ = `사용하는 기능`,
  _ = `다음은 %1$s 게임에서 사용 가능한 Steam 창작마당 기능입니다.`,
  _ = `바로 사용 가능한 콘텐츠`,
  _ = `이 창작마당에 등록된 콘텐츠는 바로 사용할 수 있습니다. 콘텐츠 세부 정보 페이지에서 '구독' 버튼을 누르면 다음 번 %1$s 실행 시 자동으로 사용할 수 있습니다.`,
  _ = `이 창작마당의 %2$s 탭에 게시된 콘텐츠는 바로 사용할 수 있습니다. 콘텐츠 상세 정보 페이지의 구독 버튼을 클릭하면 %1$s 실행 시 자동으로 사용할 수 있습니다.`,
  _ = `게임 브랜치에 대한 버전 관리 지원`,
  _ = `콘텐츠는 다양한 게임(베타) 브랜치와 관련된 버전을 포함할 수 있습니다. 이러한 기능은 개발자와 창작마당 제작자가 %1$s 게임이 업데이트될 때마다 콘텐츠의 호환성 유지를 위해 더욱 쉽게 협업할 수 있는 환경을 제공합니다.`,
  _ = `큐레이트 콘텐츠 선택`,
  _ = `이 창작마당에 등록된 콘텐츠는 %1$s 게임에서 바로 사용할 수 없습니다. 개발자는 커뮤니티의 평가를 통해 %1$s 게임 내에서 구매하거나 잠금 해제할 수 있기를 바라는 콘텐츠가 무엇인지 확인한 후 %1$s 게임에 추가할 콘텐츠를 최종 결정합니다.`,
  _ = `이 창작마당의 %2$s 탭에 등록된 콘텐츠는 %1$s 게임에서 바로 사용할 수 없습니다. 개발자는 커뮤니티의 평가를 통해 %1$s 게임 내에서 구매하거나 잠금 해제할 수 있기를 바라는 콘텐츠가 무엇인지 확인한 후 %1$s 게임에 추가할 콘텐츠를 최종 결정합니다.`,
  _ = `콘텐츠 판매`,
  _ = `창작마당에서 승인된 콘텐츠는 %1$s 내에서 구매하거나 잠금 해제할 수 있습니다.`,
  _ = `콘텐츠 직접 판매`,
  _ = `이 창작마당의 콘텐츠는 Steam 창작마당을 통해 직접 판매할 수 있습니다. 이러한 콘텐츠를 판매하려면 개발자나 커뮤니티의 승인이 필요할 수 있습니다. 콘텐츠 제작자는 아래 <a %s>수익 창출</a> 섹션에서 Steam 창작마당에서 콘텐츠를 판매하는 방법에 대한 자세한 정보를 확인할 수 있습니다.`,
  _ = `콘텐츠 제작자 수익 분배`,
  _ = `이 창작마당에서 판매가 승인된 콘텐츠의 제작자는 판매 수익의 일부를 분배받습니다.`,
  _ = `서비스 제공자 수익 분배`,
  _ = `창작마당 제작자는 콘텐츠 판매로 발생하는 Valve 수익의 일정 비율을 사전에 승인된 단체, 사용자, 도구 제작자에게 분배할 수 있습니다. 승인된 단체 및 개인 도구 제작자는 아래와 같습니다.`,
  _ = `콘텐츠 제작자이신가요? 아니면 콘텐츠를 제작하여 판매에 성공한 경험을 공유하고 싶어 하는 단체나 개인 제작자를 알고 계신가요? 알고 계신다면 <a href="%1$s">저희에게 알려주세요</a>!`,
  _ = `수익 분배`,
  _ = `콘텐츠가 판매되면 콘텐츠 제작자가 받게 되는 수익 분배율입니다.`,
  _ = `자세한 정보는 %1$s에서 알아보세요.`,
  _ = `여기`,
  _ = `이 창작마당에 게시된 콘텐츠 수`,
  _ = `%1$s에 추가된 콘텐츠`,
  _ = `관련 링크`,
  _ = `공식 문서 보기`,
  _ = `Steam 가이드 찾기`,
  _ = `이 창작마당을 위한 커뮤니티 제작 가이드`,
  _ = `Steam 창작마당을 통해 구매한 제품`,
  _ = `Steam 창작마당 이용 약관`,
  _ = `Steam 창작마당 수익`,
  _ = `서비스 제공자`,
  _ = `사이트 보기`,
  _ = `Steam 프로필 보기`,
  _ = `도구`,
  _ = `커뮤니티`,
  _ = `사용자`,
  _ = `세부 정보 보기`,
  _ = `빠른 보기`,
  _ = `투표`,
  _ = `게임에 추가되었으면 하는 커뮤니티 콘텐츠에 투표하세요!`,
  _ = `현재 대기열에 있는 콘텐츠에 투표하세요!`,
  _ = `현재까지 투표한 콘텐츠: %1$s개`,
  _ = `현재까지 투표한 콘텐츠: %1$s개`,
  _ = `최근 7일`,
  _ = `최근 1개월`,
  _ = `최근 3개월`,
  _ = `최근 6개월`,
  _ = `최근 1년`,
  _ = `팔로우한 제작자의 콘텐츠`,
  _ = `내가 팔로우한 제작자가 최근에 게시한 콘텐츠`,
  _ = `팔로우한 제작자의 콘텐츠 더 보기`,
  _ = `승인된 콘텐츠`,
  _ = `아래 콘텐츠는 승인되어 게임 내에서 획득하거나 구매할 수 있습니다.`,
  _ = `승인된 모든 콘텐츠 보기`,
  _ = `최고 인기 %1$s`,
  _ = `최고 인기`,
  _ = `지난 3개월 최고 평점 기준 정렬`,
  _ = `최고 인기 콘텐츠 보기`,
  _ = `최다 구독`,
  _ = `현재 가장 많은 고유 구독자 수 기준 정렬`,
  _ = `가장 많이 구독된 콘텐츠 보기`,
  _ = `신규 콘텐츠`,
  _ = `최근 게시된 콘텐츠`,
  _ = `최근 게시된 콘텐츠 보기`,
  _ = `최장 플레이 시간`,
  _ = `최다 플레이 콘텐츠 보기`,
  _ = `최근 업데이트`,
  _ = `최근 업데이트된 콘텐츠`,
  _ = `최근 업데이트된 콘텐츠 보기`,
  _ = `친구의 즐겨찾기`,
  _ = `친구가 즐겨찾기에 추가한 콘텐츠`,
  _ = `친구의 즐겨찾기 모두 보기`,
  _ = `다른 콘텐츠에 가장 많이 필요한 콘텐츠`,
  _ = `다른 콘텐츠를 정상적으로 이용하기 위해 필요한 가장 인기 있는 콘텐츠`,
  _ = `모두 보기`,
  _ = `최고 인기 상품`,
  _ = `인기 상품 모두 보기`,
  _ = `모두 보기`,
  _ = `내 즐겨찾기`,
  _ = `최근 업데이트된 즐겨찾기 보기`,
  _ = `플레이한 콘텐츠`,
  _ = `최근 업데이트된 플레이한 콘텐츠 보기`,
  _ = `내 구독`,
  _ = `최근 업데이트된 구독 보기`,
  _ = `지난 3개월 이내에 업데이트`,
  _ = `특별 이벤트: %1$s`,
  _ = `%1$s 태그가 지정된 콘텐츠 모두 보기`,
  _ = `친구 %1$s명이 즐겨찾기에 추가했습니다.`,
  _ = `친구 %1$s명이 즐겨찾기에 추가했습니다.`,
  _ = `맵`,
  _ = `콘텐츠`,
  _ = `맞춤 게임 및 봇 스크립트`,
  _ = `콘텐츠`,
  _ = `영웅으로 필터링`,
  _ = `맵`,
  _ = `콘텐츠`,
  _ = {
    language: _,
    Header_WorkshopTitle: _,
    Header_App_WorkshopTitle: _,
    Workshop_Error_Loading: _,
    Workshop_Error_Title: _,
    Workshop_Error_Browse_Desc: _,
    Error_Sorry: _,
    Error_Encountered: _,
    Error_TooManyRequests_Description: _,
    Workshop_ExitReact_Link: _,
    Workshop_Browsing: _,
    Workshop_Browsing_Mtx_Desc: _,
    Workshop_Browsing_ReadyToUse_Desc: _,
    Workshop_Browsing_Merchandise_Desc: _,
    Workshop_AcceptedForGame: _,
    Workshop_AcceptedMerch: _,
    Workshop_OfficialContent: _,
    Workshop_Browse_Author_Link: _,
    Workshop_Section_Mtx: _,
    Workshop_Section_ReadyToUse: _,
    Workshop_Section_Collections: _,
    Workshop_Section_Merchandise: _,
    Workshop_Section_Videos: _,
    Workshop_Saved_Queries: _,
    Workshop_Saved_Queries_Update: _,
    Workshop_Saved_Queries_Save_Title: _,
    Workshop_Saved_Queries_Save_Desc_Long: _,
    Workshop_Saved_Queries_Save_Desc: _,
    Workshop_Saved_Queries_Save_New: _,
    Workshop_Saved_Queries_Save_Btn: _,
    Workshop_Saved_Queries_Delete_Title: _,
    Workshop_Saved_Queries_Delete_Desc: _,
    Workshop_Saved_Queries_Delete_Btn: _,
    Workshop_LearnMore: _,
    Workshop_Filters_ClearBtn: _,
    Workshop_About: _,
    Workshop_BrowseSort_SortOrder: _,
    Workshop_BrowseSort_TimeFrame: _,
    SharedFiles_Browse_Trend_Option_Today: _,
    SharedFiles_Browse_Trend_Option_Week: _,
    SharedFiles_Browse_Trend_Option_Month: _,
    SharedFiles_Browse_Trend_Option_ThreeMonths: _,
    SharedFiles_Browse_Trend_Option_SixMonths: _,
    SharedFiles_Browse_Trend_Option_OneYear: _,
    SharedFiles_Browse_Trend_Option_AllTime: _,
    Workshop_BrowseSort_Combined: _,
    Workshop_BrowseSort_MostRecent: _,
    Workshop_BrowseSort_MostPopular: _,
    Workshop_BrowseSort_TopRated: _,
    Workshop_BrowseSort_LastUpdated: _,
    Workshop_BrowseSort_Reported: _,
    Workshop_BrowseSort_AdminOption: _,
    Workshop_BrowseSort_NumParentItems: _,
    Workshop_BrowseSort_NumParentCollections: _,
    Workshop_RequireApproval: _,
    Workshop_BrowseSort_ToRate: _,
    Workshop_BrowseSort_TotalUniqueSubscribers: _,
    Workshop_BrowseSort_TotalVotes: _,
    Workshop_BrowseSort_MostUpVotes: _,
    Workshop_BrowseSort_SearchRelevance: _,
    Workshop_BrowseSort_Playtime: _,
    Workshop_BrowseSort_PlaytimeTotal: _,
    Workshop_BrowseSort_PlaytimeAverage: _,
    Workshop_BrowseSort_PlaytimeAverageTotal: _,
    Workshop_BrowseSort_PlaytimeSessions: _,
    Workshop_BrowseSort_PlaytimeSessionsTotal: _,
    Workshop_BrowseSort_Inappropriate: _,
    Workshop_BrowseSort_BanContentCheck: _,
    Workshop_BrowseSort_CuratedAdmin: _,
    Workshop_BrowseSort_Nominee: _,
    Workshop_BrowseSort_Rated: _,
    Workshop_BrowseSort_AcceptedTime: _,
    Workshop_SpecialFilter_Desc: _,
    Workshop_SpecialFilter_None: _,
    Workshop_SpecialFilter_AcceptedForUse: _,
    Workshop_SpecialFilter_CreatedByFriends: _,
    Workshop_SpecialFilter_CreatedByFollowed: _,
    Workshop_SpecialFilter_FavoritedByFriends: _,
    Workshop_SpecialFilter_Reported: _,
    Workshop_SpecialFilter_ParentItems: _,
    Workshop_SpecialFilter_ParentCollections: _,
    Workshop_Menu_Home: `홈`,
    Workshop_Menu_Browse: _,
    Workshop_Menu_YourItems: _,
    Workshop_Menu_Discussions: _,
    Workshop_Menu_About: _,
    Workshop_Menu_Search: _,
    Workshop_SubMenu_YourItems: _,
    Workshop_SubMenu_YourFavorites: _,
    Workshop_SubMenu_YourSubscriptions: _,
    Workshop_SubMenu_YourPlayed: _,
    Workshop_SubMenu_YourCollections: _,
    Workshop_SubMenu_YourVotingQueue: _,
    Workshop_SubMenu_YourPaymentInfo: _,
    Workshop_SubMenu_ViewYourRevenue: _,
    Workshop_SubMenu_ViewYourRevenue_Desc: _,
    Workshop_SubMenu_LegalAgreement: _,
    Workshop_SubMenu_VotingQueue: _,
    Workshop_ApplyFilters: _,
    Workshop_SortBy: _,
    Workshop_Tag_NoneSpecified: _,
    Workshop_RequiredDLC_Header: _,
    Workshop_RequiredDLC_Filter: _,
    Workshop_IncludeOwnedDLC_Filter: _,
    Workshop_ExcludeOwnedDLC_Filter: _,
    Workshop_OwnedDLC_None_Filter: _,
    Workshop_OwnedDLC_All_Filter: _,
    Workshop_OwnedDLC_More_Filter: _,
    Workshop_RequiredDLC_IncludeOwned: _,
    Workshop_RequiredDLC_ExcludeUnowned: _,
    Workshop_RequiredDLC_NameFilter: _,
    Workshop_Flag_Incompatible_Checkbox: _,
    Workshop_Flag_Incompatible_Checkbox_Desc: _,
    Workshop_Admin_View: _,
    Workshop_SearchResults_SearchText: _,
    Workshop_SearchResults_SearchText_TitleOnly: _,
    Workshop_SearchResults_SearchText_DescriptionOnly: _,
    Workshop_SearchedForChild: _,
    Workshop_SearchedForRequiredItem: _,
    Workshop_SearchResults_Tag: _,
    Workshop_SearchResults_KVTag: _,
    Workshop_SearchResults_Flag_Incompatible: _,
    Workshop_SearchResults_Flag_Accepted: _,
    Workshop_SearchTarget_MenuTitle: _,
    Workshop_SearchTarget_All: _,
    Workshop_SearchTarget_Title: _,
    Workshop_SearchTarget_Description: _,
    Workshop_Search_Help: _,
    Workshop_Search_Help_Example1: _,
    Workshop_Search_Help_Example2: _,
    Workshop_Search_Help_Example3: _,
    Workshop_Search_Help_Example_Red: _,
    Workshop_Search_Help_Example_Blue: _,
    Workshop_Search_Help_Example_Green: _,
    Workshop_Search_Help_Example_Room: `방`,
    Workshop_Search_Help_Advanced: _,
    Workshop_Search_Help_AdvancedExample1: _,
    Workshop_Search_Help_AdvancedExample2: _,
    Workshop_FiltersMenu_State_Title: _,
    Workshop_FiltersMenu_State_Left: _,
    Workshop_FiltersMenu_State_Right: _,
    Workshop_FiltersMenu_State_Collapsed: _,
    Workshop_DimmedItems_Title: _,
    Workshop_DimmedItems_Reported: _,
    Workshop_DimmedItems_BlockedCreators: _,
    Workshop_DimmedItems_VotedUp: _,
    Workshop_DimmedItems_VotedDown: _,
    Workshop_DimmedItems_Subscribed: _,
    Workshop_DateFilter_FilterByDate: _,
    Workshop_DateFilter_TimeCreated: _,
    Workshop_DateFilter_TimeCreated_After: _,
    Workshop_DateFilter_TimeCreated_Before: _,
    Workshop_DateFilter_TimeCreated_Between: _,
    Workshop_DateFilter_TimeUpdated: _,
    Workshop_DateFilter_TimeUpdated_After: _,
    Workshop_DateFilter_TimeUpdated_Before: _,
    Workshop_DateFilter_TimeUpdated_Between: _,
    Workshop_DateFilter_Between: _,
    Workshop_DateFilter_And: `~`,
    Workshop_NumResults: _,
    Workshop_NumResults_Plural: _,
    Workshop_NumPerPage: _,
    Workshop_PagingControls: _,
    Workshop_CreateCollection: _,
    Workshop_CreateMerchandise: _,
    Workshop_Item_QuickView: _,
    Workshop_Item_QuickView_ExpandBtn: _,
    Workshop_StatusIcon_TT_Subscribed: _,
    Workshop_StatusIcon_TT_Favorited: _,
    Workshop_StatusIcon_TT_Played: _,
    Workshop_StatusIcon_TT_Accepted: _,
    Workshop_StatusIcon_TT_Incompatible: _,
    Workshop_StatusIcon_TT_VotedUp: _,
    Workshop_StatusIcon_TT_VotedDown: _,
    Workshop_StatusIcon_TT_Reported: _,
    Workshop_StatusIcon_TT_BlockedCreator: _,
    Workshop_ItemDetails_Tab_Description: _,
    Workshop_ItemDetails_Tab_Discussions: _,
    Workshop_ItemDetails_Tab_Comments: _,
    Workshop_ItemDetails_Tab_Updates: _,
    Workshop_ItemDetails_Tab_Stats: _,
    Workshop_ItemDetails_Tab_ChangeNotes: _,
    Workshop_ItemDetails_Title: _,
    Workshop_ItemDetails_CreatedBy: _,
    Workshop_ItemDetails_NumRatings: _,
    Workshop_ItemDetails_NumRatings_Plural: _,
    Workshop_ItemDetails_NotEnoughRatings: _,
    Workshop_ItemDetails_TimestampWithTime: _,
    Workshop_ItemDetails_TimestampCreated: _,
    Workshop_ItemDetails_TimestampUpdated: _,
    Workshop_ItemDetails_Subscribe: _,
    Workshop_ItemDetails_Subscribed: _,
    Workshop_ItemDetails_Unsubscribe: _,
    Workshop_ItemDetails_Favorite: _,
    Workshop_ItemDetails_Favorited: _,
    Workshop_ItemDetails_Unfavorite: _,
    Workshop_ItemDetails_ViewDependentItems: _,
    Workshop_ItemDetails_AddToCollection: _,
    Workshop_ItemDetails_SaveCollectionToCollection: _,
    Workshop_ItemDetails_Signin_TT: _,
    Workshop_ItemDetails_Subscribe_TT: _,
    Workshop_ItemDetails_Unsubscribe_TT: _,
    Workshop_ItemDetails_Favorite_TT: _,
    Workshop_ItemDetails_ViewDependentItems_TT: _,
    Workshop_ItemDetails_Report_TT: _,
    Workshop_ItemDetails_Award_TT: _,
    Workshop_ItemDetails_AddToCollection_TT: _,
    Workshop_ItemDetails_FileSize: _,
    Workshop_ItemDetails_Stats_UniqueVisitors: _,
    Workshop_ItemDetails_Stats_CurrentSubscribers: _,
    Workshop_ItemDetails_Stats_CurrentFavorites: _,
    Workshop_ItemDetails_Stats_LifetimeFavorites: _,
    Workshop_ItemDetails_Stats_LifetimeSubscribers: _,
    Workshop_ItemDetails_Stats_LifetimePlaytimeSessions: _,
    Workshop_ItemDetails_ItemDependencies: _,
    Workshop_ItemDetails_RequiredDLC_Desc: _,
    Workshop_Collection_SubscribeToAll: _,
    Workshop_Collection_UnsubscribeFromAll: _,
    Workshop_Collection_SaveToCollection: _,
    Workshop_ItemDetails_ShowAllReactions: _,
    Workshop_ItemDetails_ReactionCount: _,
    Workshop_ItemDetails_ReactionCount_Plural: _,
    Workshop_ItemDetails_Tags_Title: _,
    Workshop_ItemDetails_Categories_Title: _,
    Workshop_ItemDetails_Description_Title: _,
    Workshop_ItemDetails_DependentItems: _,
    Workshop_ItemDetails_InCollections: _,
    Workshop_ItemDetails_InCollectionsByAuthor: _,
    Workshop_Dialog_Error: _,
    Workshop_Dialog_AccessDenied: _,
    Workshop_Dialog_Timeout: _,
    Workshop_Dialog_LimitExceeded: _,
    Workshop_Dialog_ErrorDesc: _,
    Workshop_Dialog_CollectionSubscribe: _,
    Workshop_Dialog_CollectionSubscribe_Desc: _,
    Workshop_Dialog_CollectionSubscribe_AddOnly: _,
    Workshop_Dialog_CollectionSubscribe_Overwrite: _,
    Workshop_Dialog_ItemDependencies: _,
    Workshop_Dialog_ItemDependencies_Desc1: _,
    Workshop_Dialog_ItemDependencies_Desc1_itemName: _,
    Workshop_Dialog_ItemDependencies_Desc2: _,
    Workshop_Dialog_ItemDependencies_Desc3: _,
    Workshop_Dialog_SubscribeJustThisItem: _,
    Workshop_Dialog_SubscribeAll: _,
    Workshop_Dialog_Report: _,
    Workshop_Dialog_Report_Desc: _,
    Workshop_Dialog_Report_Reason: _,
    Workshop_Dialog_Report_Reason_Desc: _,
    Workshop_Dialog_Report_DMCA_Desc: _,
    Workshop_Dialog_Report_Trademark_Desc: _,
    Workshop_Dialog_Report_Here: _,
    Workshop_Dialog_AddToCollection: _,
    Workshop_Dialog_AddToCollection_Desc: _,
    Workshop_Dialog_AddToCollection_NoSavedCollections_Desc: _,
    Workshop_Dialog_AddToCollection_OK: _,
    Workshop_Dialog_AddToCollection_Create: _,
    Workshop_Dialog_SaveCollectionToCollection: _,
    Workshop_Dialog_SaveCollectionToCollection_Desc: _,
    Workshop_Dialog_SaveCollectionToCollection_New: _,
    Workshop_Dialog_SaveCollectionToCollection_Existing: _,
    Workshop_Dialog_SaveCollectionToCollection_NewPrompt: _,
    Workshop_Dialog_SaveCollectionToCollection_Select: _,
    Workshop_Collection_NumChildItems: _,
    Workshop_Collection_NumChildItems_Plural: _,
    Workshop_Collection_NumChildCollections: _,
    Workshop_Collection_NumChildCollections_Plural: _,
    Workshop_Collection_ViewMore: _,
    Workshop_About_PageDesc_Curation: _,
    Workshop_About_PageDesc_ReadyToUseContent1: _,
    Workshop_About_PageDesc_ReadyToUseContent2: _,
    Workshop_About_PageDesc_ReadyToUseContent_Mixed1: _,
    Workshop_About_PageDesc_ReadyToUseContent_Mixed2: _,
    Workshop_About_EnabledFeatures: _,
    Workshop_About_EnabledFeatures_Desc: _,
    Workshop_About_Feature_ReadyToUse: _,
    Workshop_About_Feature_ReadyToUse_Desc: _,
    Workshop_About_Feature_ReadyToUse_Mixed_Desc: _,
    Workshop_About_Feature_Branch_Versioning: _,
    Workshop_About_Feature_Branch_Versioning_Desc: _,
    Workshop_About_Feature_ItemCuration: _,
    Workshop_About_Feature_ItemCuration_Desc: _,
    Workshop_About_Feature_ItemCuration_Mixed_Desc: _,
    Workshop_About_Feature_ItemMtx: _,
    Workshop_About_Feature_ItemMtx_Desc: _,
    Workshop_About_Feature_Commerce: _,
    Workshop_About_Feature_Commerce_Desc: _,
    Workshop_About_Feature_AuthorRoyalties: _,
    Workshop_About_Feature_AuthorRoyalties_Desc: _,
    Workshop_About_Feature_ServiceProviders: _,
    Workshop_About_Feature_ServiceProviders_Desc: _,
    Workshop_About_Request_ServiceProviders: _,
    Workshop_About_RevenueShare: _,
    Workshop_About_RevenueShare_Desc: _,
    Workshop_About_RevenueShare_Link: _,
    Workshop_About_RevenueShare_Here: _,
    Workshop_About_NumItems: _,
    Workshop_About_NumAcceptedItems: _,
    Workshop_About_RelatedLinks: _,
    Workshop_About_ViewOfficialDocs: _,
    Workshop_About_FindGuides: _,
    Workshop_About_FindGuides_Sub: _,
    Workshop_About_RefundLink_Sub: _,
    Workshop_About_WorkshopTerms: _,
    Workshop_About_WorkshopTerms_Sub: _,
    Workshop_About_section_ServiceProviders: _,
    Workshop_ServiceProviderRevenueSharing_ViewSite: _,
    Workshop_ServiceProviderRevenueSharing_ViewSteamProfile: _,
    Workshop_ServiceProvider_Category_Tools: _,
    Workshop_ServiceProvider_Category_Communities: _,
    Workshop_ServiceProvider_Category_Users: _,
    Workshop_GamepadUIAction_ViewDetails: _,
    Workshop_GamepadUIAction_QuickView: _,
    Workshop_Home_VotingQueue: _,
    Workshop_Home_VotingQueue_Desc: _,
    Workshop_Home_VotingQueue_Btn: _,
    Workshop_Home_VotingQueue_Count: _,
    Workshop_Home_VotingQueue_Count_Plural: _,
    Workshop_Home_MostPopular_SubTitle_Week: _,
    Workshop_Home_MostPopular_SubTitle_Month: _,
    Workshop_Home_MostPopular_SubTitle_ThreeMonths: _,
    Workshop_Home_MostPopular_SubTitle_SixMonths: _,
    Workshop_Home_MostPopular_SubTitle_Year: _,
    Workshop_Home_FromFollowedAuthors: _,
    Workshop_Home_FromFollowedAuthors_Desc: _,
    Workshop_Home_FromFollowedAuthors_Btn: _,
    Workshop_Home_AcceptedItems: _,
    Workshop_Home_AcceptedItems_Desc: _,
    Workshop_Home_AcceptedItems_Btn: _,
    Workshop_Home_MostPopular: _,
    Workshop_Home_MostPopular_LongTerm: _,
    Workshop_Home_MostPopular_LongTerm_Desc: _,
    Workshop_Home_MostPopular_LongTerm_Btn: _,
    Workshop_Home_MostSubscribed: _,
    Workshop_Home_MostSubscribed_Desc: _,
    Workshop_Home_MostSubscribed_Btn: _,
    Workshop_Home_MostRecent: _,
    Workshop_Home_MostRecent_Desc: _,
    Workshop_Home_MostRecent_Btn: _,
    Workshop_Home_MostPlaytime: _,
    Workshop_Home_MostPlaytime_Btn: _,
    Workshop_Home_LastUpdated: _,
    Workshop_Home_LastUpdated_Desc: _,
    Workshop_Home_LastUpdated_Btn: _,
    Workshop_Home_FriendsFavorites: _,
    Workshop_Home_FriendsFavorites_Desc: _,
    Workshop_Home_FriendsFavorites_Btn: _,
    Workshop_Home_NumParentItems: _,
    Workshop_Home_NumParentItems_Desc: _,
    Workshop_Home_NumParentItems_Btn: _,
    Workshop_Home_MostPopularMerch: _,
    Workshop_Home_MostPopularMerch_Btn: _,
    Workshop_Home_ViewAll: _,
    Workshop_Home_YourFavorites: _,
    Workshop_Home_YourFavorites_Btn: _,
    Workshop_Home_YourPlayed: _,
    Workshop_Home_YourPlayed_Btn: _,
    Workshop_Home_YourSubscriptions: _,
    Workshop_Home_YourSubscriptions_Btn: _,
    Workshop_Home_YourFiles_LastUpdated: _,
    Workshop_Home_SpecialEvent_Title_Tag: _,
    Workshop_Home_SpecialEvent_Link: _,
    Workshop_ItemTooltip_FriendsWhoFavorited: _,
    Workshop_ItemTooltip_FriendsWhoFavorited_Plural: _,
    SharedFiles_TF2_Tab_Items_ReadyToUse: `맵`,
    SharedFiles_TF2_Tab_Items_Mtx: _,
    SharedFiles_Dota2_Tab_Items_ReadyToUse: _,
    SharedFiles_Dota2_Tab_Items_Mtx: _,
    SharedFiles_Dota2_HeroPicker: _,
    SharedFiles_CSGO_Tab_Items_ReadyToUse: `맵`,
    SharedFiles_CSGO_Tab_Items_Mtx: _,
  };
export {
  _ as Error_Encountered,
  _ as Error_Sorry,
  _ as Error_TooManyRequests_Description,
  _ as Header_App_WorkshopTitle,
  _ as Header_WorkshopTitle,
  _ as SharedFiles_Browse_Trend_Option_AllTime,
  _ as SharedFiles_Browse_Trend_Option_Month,
  _ as SharedFiles_Browse_Trend_Option_OneYear,
  _ as SharedFiles_Browse_Trend_Option_SixMonths,
  _ as SharedFiles_Browse_Trend_Option_ThreeMonths,
  _ as SharedFiles_Browse_Trend_Option_Today,
  _ as SharedFiles_Browse_Trend_Option_Week,
  _ as SharedFiles_CSGO_Tab_Items_Mtx,
  _ as SharedFiles_CSGO_Tab_Items_ReadyToUse,
  _ as SharedFiles_Dota2_HeroPicker,
  _ as SharedFiles_Dota2_Tab_Items_Mtx,
  _ as SharedFiles_Dota2_Tab_Items_ReadyToUse,
  _ as SharedFiles_TF2_Tab_Items_Mtx,
  _ as SharedFiles_TF2_Tab_Items_ReadyToUse,
  _ as Workshop_About,
  _ as Workshop_About_EnabledFeatures,
  _ as Workshop_About_EnabledFeatures_Desc,
  _ as Workshop_About_Feature_AuthorRoyalties,
  _ as Workshop_About_Feature_AuthorRoyalties_Desc,
  _ as Workshop_About_Feature_Branch_Versioning,
  _ as Workshop_About_Feature_Branch_Versioning_Desc,
  _ as Workshop_About_Feature_Commerce,
  _ as Workshop_About_Feature_Commerce_Desc,
  _ as Workshop_About_Feature_ItemCuration,
  _ as Workshop_About_Feature_ItemCuration_Desc,
  _ as Workshop_About_Feature_ItemCuration_Mixed_Desc,
  _ as Workshop_About_Feature_ItemMtx,
  _ as Workshop_About_Feature_ItemMtx_Desc,
  _ as Workshop_About_Feature_ReadyToUse,
  _ as Workshop_About_Feature_ReadyToUse_Desc,
  _ as Workshop_About_Feature_ReadyToUse_Mixed_Desc,
  _ as Workshop_About_Feature_ServiceProviders,
  _ as Workshop_About_Feature_ServiceProviders_Desc,
  _ as Workshop_About_FindGuides,
  _ as Workshop_About_FindGuides_Sub,
  _ as Workshop_About_NumAcceptedItems,
  _ as Workshop_About_NumItems,
  _ as Workshop_About_PageDesc_Curation,
  _ as Workshop_About_PageDesc_ReadyToUseContent1,
  _ as Workshop_About_PageDesc_ReadyToUseContent2,
  _ as Workshop_About_PageDesc_ReadyToUseContent_Mixed1,
  _ as Workshop_About_PageDesc_ReadyToUseContent_Mixed2,
  _ as Workshop_About_RefundLink_Sub,
  _ as Workshop_About_RelatedLinks,
  _ as Workshop_About_Request_ServiceProviders,
  _ as Workshop_About_RevenueShare,
  _ as Workshop_About_RevenueShare_Desc,
  _ as Workshop_About_RevenueShare_Here,
  _ as Workshop_About_RevenueShare_Link,
  _ as Workshop_About_ViewOfficialDocs,
  _ as Workshop_About_WorkshopTerms,
  _ as Workshop_About_WorkshopTerms_Sub,
  _ as Workshop_About_section_ServiceProviders,
  _ as Workshop_AcceptedForGame,
  _ as Workshop_AcceptedMerch,
  _ as Workshop_Admin_View,
  _ as Workshop_ApplyFilters,
  _ as Workshop_BrowseSort_AcceptedTime,
  _ as Workshop_BrowseSort_AdminOption,
  _ as Workshop_BrowseSort_BanContentCheck,
  _ as Workshop_BrowseSort_Combined,
  _ as Workshop_BrowseSort_CuratedAdmin,
  _ as Workshop_BrowseSort_Inappropriate,
  _ as Workshop_BrowseSort_LastUpdated,
  _ as Workshop_BrowseSort_MostPopular,
  _ as Workshop_BrowseSort_MostRecent,
  _ as Workshop_BrowseSort_MostUpVotes,
  _ as Workshop_BrowseSort_Nominee,
  _ as Workshop_BrowseSort_NumParentCollections,
  _ as Workshop_BrowseSort_NumParentItems,
  _ as Workshop_BrowseSort_Playtime,
  _ as Workshop_BrowseSort_PlaytimeAverage,
  _ as Workshop_BrowseSort_PlaytimeAverageTotal,
  _ as Workshop_BrowseSort_PlaytimeSessions,
  _ as Workshop_BrowseSort_PlaytimeSessionsTotal,
  _ as Workshop_BrowseSort_PlaytimeTotal,
  _ as Workshop_BrowseSort_Rated,
  _ as Workshop_BrowseSort_Reported,
  _ as Workshop_BrowseSort_SearchRelevance,
  _ as Workshop_BrowseSort_SortOrder,
  _ as Workshop_BrowseSort_TimeFrame,
  _ as Workshop_BrowseSort_ToRate,
  _ as Workshop_BrowseSort_TopRated,
  _ as Workshop_BrowseSort_TotalUniqueSubscribers,
  _ as Workshop_BrowseSort_TotalVotes,
  _ as Workshop_Browse_Author_Link,
  _ as Workshop_Browsing,
  _ as Workshop_Browsing_Merchandise_Desc,
  _ as Workshop_Browsing_Mtx_Desc,
  _ as Workshop_Browsing_ReadyToUse_Desc,
  _ as Workshop_Collection_NumChildCollections,
  _ as Workshop_Collection_NumChildCollections_Plural,
  _ as Workshop_Collection_NumChildItems,
  _ as Workshop_Collection_NumChildItems_Plural,
  _ as Workshop_Collection_SaveToCollection,
  _ as Workshop_Collection_SubscribeToAll,
  _ as Workshop_Collection_UnsubscribeFromAll,
  _ as Workshop_Collection_ViewMore,
  _ as Workshop_CreateCollection,
  _ as Workshop_CreateMerchandise,
  _ as Workshop_DateFilter_And,
  _ as Workshop_DateFilter_Between,
  _ as Workshop_DateFilter_FilterByDate,
  _ as Workshop_DateFilter_TimeCreated,
  _ as Workshop_DateFilter_TimeCreated_After,
  _ as Workshop_DateFilter_TimeCreated_Before,
  _ as Workshop_DateFilter_TimeCreated_Between,
  _ as Workshop_DateFilter_TimeUpdated,
  _ as Workshop_DateFilter_TimeUpdated_After,
  _ as Workshop_DateFilter_TimeUpdated_Before,
  _ as Workshop_DateFilter_TimeUpdated_Between,
  _ as Workshop_Dialog_AccessDenied,
  _ as Workshop_Dialog_AddToCollection,
  _ as Workshop_Dialog_AddToCollection_Create,
  _ as Workshop_Dialog_AddToCollection_Desc,
  _ as Workshop_Dialog_AddToCollection_NoSavedCollections_Desc,
  _ as Workshop_Dialog_AddToCollection_OK,
  _ as Workshop_Dialog_CollectionSubscribe,
  _ as Workshop_Dialog_CollectionSubscribe_AddOnly,
  _ as Workshop_Dialog_CollectionSubscribe_Desc,
  _ as Workshop_Dialog_CollectionSubscribe_Overwrite,
  _ as Workshop_Dialog_Error,
  _ as Workshop_Dialog_ErrorDesc,
  _ as Workshop_Dialog_ItemDependencies,
  _ as Workshop_Dialog_ItemDependencies_Desc1,
  _ as Workshop_Dialog_ItemDependencies_Desc1_itemName,
  _ as Workshop_Dialog_ItemDependencies_Desc2,
  _ as Workshop_Dialog_ItemDependencies_Desc3,
  _ as Workshop_Dialog_LimitExceeded,
  _ as Workshop_Dialog_Report,
  _ as Workshop_Dialog_Report_DMCA_Desc,
  _ as Workshop_Dialog_Report_Desc,
  _ as Workshop_Dialog_Report_Here,
  _ as Workshop_Dialog_Report_Reason,
  _ as Workshop_Dialog_Report_Reason_Desc,
  _ as Workshop_Dialog_Report_Trademark_Desc,
  _ as Workshop_Dialog_SaveCollectionToCollection,
  _ as Workshop_Dialog_SaveCollectionToCollection_Desc,
  _ as Workshop_Dialog_SaveCollectionToCollection_Existing,
  _ as Workshop_Dialog_SaveCollectionToCollection_New,
  _ as Workshop_Dialog_SaveCollectionToCollection_NewPrompt,
  _ as Workshop_Dialog_SaveCollectionToCollection_Select,
  _ as Workshop_Dialog_SubscribeAll,
  _ as Workshop_Dialog_SubscribeJustThisItem,
  _ as Workshop_Dialog_Timeout,
  _ as Workshop_DimmedItems_BlockedCreators,
  _ as Workshop_DimmedItems_Reported,
  _ as Workshop_DimmedItems_Subscribed,
  _ as Workshop_DimmedItems_Title,
  _ as Workshop_DimmedItems_VotedDown,
  _ as Workshop_DimmedItems_VotedUp,
  _ as Workshop_Error_Browse_Desc,
  _ as Workshop_Error_Loading,
  _ as Workshop_Error_Title,
  _ as Workshop_ExcludeOwnedDLC_Filter,
  _ as Workshop_ExitReact_Link,
  _ as Workshop_FiltersMenu_State_Collapsed,
  _ as Workshop_FiltersMenu_State_Left,
  _ as Workshop_FiltersMenu_State_Right,
  _ as Workshop_FiltersMenu_State_Title,
  _ as Workshop_Filters_ClearBtn,
  _ as Workshop_Flag_Incompatible_Checkbox,
  _ as Workshop_Flag_Incompatible_Checkbox_Desc,
  _ as Workshop_GamepadUIAction_QuickView,
  _ as Workshop_GamepadUIAction_ViewDetails,
  _ as Workshop_Home_AcceptedItems,
  _ as Workshop_Home_AcceptedItems_Btn,
  _ as Workshop_Home_AcceptedItems_Desc,
  _ as Workshop_Home_FriendsFavorites,
  _ as Workshop_Home_FriendsFavorites_Btn,
  _ as Workshop_Home_FriendsFavorites_Desc,
  _ as Workshop_Home_FromFollowedAuthors,
  _ as Workshop_Home_FromFollowedAuthors_Btn,
  _ as Workshop_Home_FromFollowedAuthors_Desc,
  _ as Workshop_Home_LastUpdated,
  _ as Workshop_Home_LastUpdated_Btn,
  _ as Workshop_Home_LastUpdated_Desc,
  _ as Workshop_Home_MostPlaytime,
  _ as Workshop_Home_MostPlaytime_Btn,
  _ as Workshop_Home_MostPopular,
  _ as Workshop_Home_MostPopularMerch,
  _ as Workshop_Home_MostPopularMerch_Btn,
  _ as Workshop_Home_MostPopular_LongTerm,
  _ as Workshop_Home_MostPopular_LongTerm_Btn,
  _ as Workshop_Home_MostPopular_LongTerm_Desc,
  _ as Workshop_Home_MostPopular_SubTitle_Month,
  _ as Workshop_Home_MostPopular_SubTitle_SixMonths,
  _ as Workshop_Home_MostPopular_SubTitle_ThreeMonths,
  _ as Workshop_Home_MostPopular_SubTitle_Week,
  _ as Workshop_Home_MostPopular_SubTitle_Year,
  _ as Workshop_Home_MostRecent,
  _ as Workshop_Home_MostRecent_Btn,
  _ as Workshop_Home_MostRecent_Desc,
  _ as Workshop_Home_MostSubscribed,
  _ as Workshop_Home_MostSubscribed_Btn,
  _ as Workshop_Home_MostSubscribed_Desc,
  _ as Workshop_Home_NumParentItems,
  _ as Workshop_Home_NumParentItems_Btn,
  _ as Workshop_Home_NumParentItems_Desc,
  _ as Workshop_Home_SpecialEvent_Link,
  _ as Workshop_Home_SpecialEvent_Title_Tag,
  _ as Workshop_Home_ViewAll,
  _ as Workshop_Home_VotingQueue,
  _ as Workshop_Home_VotingQueue_Btn,
  _ as Workshop_Home_VotingQueue_Count,
  _ as Workshop_Home_VotingQueue_Count_Plural,
  _ as Workshop_Home_VotingQueue_Desc,
  _ as Workshop_Home_YourFavorites,
  _ as Workshop_Home_YourFavorites_Btn,
  _ as Workshop_Home_YourFiles_LastUpdated,
  _ as Workshop_Home_YourPlayed,
  _ as Workshop_Home_YourPlayed_Btn,
  _ as Workshop_Home_YourSubscriptions,
  _ as Workshop_Home_YourSubscriptions_Btn,
  _ as Workshop_IncludeOwnedDLC_Filter,
  _ as Workshop_ItemDetails_AddToCollection,
  _ as Workshop_ItemDetails_AddToCollection_TT,
  _ as Workshop_ItemDetails_Award_TT,
  _ as Workshop_ItemDetails_Categories_Title,
  _ as Workshop_ItemDetails_CreatedBy,
  _ as Workshop_ItemDetails_DependentItems,
  _ as Workshop_ItemDetails_Description_Title,
  _ as Workshop_ItemDetails_Favorite,
  _ as Workshop_ItemDetails_Favorite_TT,
  _ as Workshop_ItemDetails_Favorited,
  _ as Workshop_ItemDetails_FileSize,
  _ as Workshop_ItemDetails_InCollections,
  _ as Workshop_ItemDetails_InCollectionsByAuthor,
  _ as Workshop_ItemDetails_ItemDependencies,
  _ as Workshop_ItemDetails_NotEnoughRatings,
  _ as Workshop_ItemDetails_NumRatings,
  _ as Workshop_ItemDetails_NumRatings_Plural,
  _ as Workshop_ItemDetails_ReactionCount,
  _ as Workshop_ItemDetails_ReactionCount_Plural,
  _ as Workshop_ItemDetails_Report_TT,
  _ as Workshop_ItemDetails_RequiredDLC_Desc,
  _ as Workshop_ItemDetails_SaveCollectionToCollection,
  _ as Workshop_ItemDetails_ShowAllReactions,
  _ as Workshop_ItemDetails_Signin_TT,
  _ as Workshop_ItemDetails_Stats_CurrentFavorites,
  _ as Workshop_ItemDetails_Stats_CurrentSubscribers,
  _ as Workshop_ItemDetails_Stats_LifetimeFavorites,
  _ as Workshop_ItemDetails_Stats_LifetimePlaytimeSessions,
  _ as Workshop_ItemDetails_Stats_LifetimeSubscribers,
  _ as Workshop_ItemDetails_Stats_UniqueVisitors,
  _ as Workshop_ItemDetails_Subscribe,
  _ as Workshop_ItemDetails_Subscribe_TT,
  _ as Workshop_ItemDetails_Subscribed,
  _ as Workshop_ItemDetails_Tab_ChangeNotes,
  _ as Workshop_ItemDetails_Tab_Comments,
  _ as Workshop_ItemDetails_Tab_Description,
  _ as Workshop_ItemDetails_Tab_Discussions,
  _ as Workshop_ItemDetails_Tab_Stats,
  _ as Workshop_ItemDetails_Tab_Updates,
  _ as Workshop_ItemDetails_Tags_Title,
  _ as Workshop_ItemDetails_TimestampCreated,
  _ as Workshop_ItemDetails_TimestampUpdated,
  _ as Workshop_ItemDetails_TimestampWithTime,
  _ as Workshop_ItemDetails_Title,
  _ as Workshop_ItemDetails_Unfavorite,
  _ as Workshop_ItemDetails_Unsubscribe,
  _ as Workshop_ItemDetails_Unsubscribe_TT,
  _ as Workshop_ItemDetails_ViewDependentItems,
  _ as Workshop_ItemDetails_ViewDependentItems_TT,
  _ as Workshop_ItemTooltip_FriendsWhoFavorited,
  _ as Workshop_ItemTooltip_FriendsWhoFavorited_Plural,
  _ as Workshop_Item_QuickView,
  _ as Workshop_Item_QuickView_ExpandBtn,
  _ as Workshop_LearnMore,
  _ as Workshop_Menu_About,
  _ as Workshop_Menu_Browse,
  _ as Workshop_Menu_Discussions,
  _ as Workshop_Menu_Home,
  _ as Workshop_Menu_Search,
  _ as Workshop_Menu_YourItems,
  _ as Workshop_NumPerPage,
  _ as Workshop_NumResults,
  _ as Workshop_NumResults_Plural,
  _ as Workshop_OfficialContent,
  _ as Workshop_OwnedDLC_All_Filter,
  _ as Workshop_OwnedDLC_More_Filter,
  _ as Workshop_OwnedDLC_None_Filter,
  _ as Workshop_PagingControls,
  _ as Workshop_RequireApproval,
  _ as Workshop_RequiredDLC_ExcludeUnowned,
  _ as Workshop_RequiredDLC_Filter,
  _ as Workshop_RequiredDLC_Header,
  _ as Workshop_RequiredDLC_IncludeOwned,
  _ as Workshop_RequiredDLC_NameFilter,
  _ as Workshop_Saved_Queries,
  _ as Workshop_Saved_Queries_Delete_Btn,
  _ as Workshop_Saved_Queries_Delete_Desc,
  _ as Workshop_Saved_Queries_Delete_Title,
  _ as Workshop_Saved_Queries_Save_Btn,
  _ as Workshop_Saved_Queries_Save_Desc,
  _ as Workshop_Saved_Queries_Save_Desc_Long,
  _ as Workshop_Saved_Queries_Save_New,
  _ as Workshop_Saved_Queries_Save_Title,
  _ as Workshop_Saved_Queries_Update,
  _ as Workshop_SearchResults_Flag_Accepted,
  _ as Workshop_SearchResults_Flag_Incompatible,
  _ as Workshop_SearchResults_KVTag,
  _ as Workshop_SearchResults_SearchText,
  _ as Workshop_SearchResults_SearchText_DescriptionOnly,
  _ as Workshop_SearchResults_SearchText_TitleOnly,
  _ as Workshop_SearchResults_Tag,
  _ as Workshop_SearchTarget_All,
  _ as Workshop_SearchTarget_Description,
  _ as Workshop_SearchTarget_MenuTitle,
  _ as Workshop_SearchTarget_Title,
  _ as Workshop_Search_Help,
  _ as Workshop_Search_Help_Advanced,
  _ as Workshop_Search_Help_AdvancedExample1,
  _ as Workshop_Search_Help_AdvancedExample2,
  _ as Workshop_Search_Help_Example1,
  _ as Workshop_Search_Help_Example2,
  _ as Workshop_Search_Help_Example3,
  _ as Workshop_Search_Help_Example_Blue,
  _ as Workshop_Search_Help_Example_Green,
  _ as Workshop_Search_Help_Example_Red,
  _ as Workshop_Search_Help_Example_Room,
  _ as Workshop_SearchedForChild,
  _ as Workshop_SearchedForRequiredItem,
  _ as Workshop_Section_Collections,
  _ as Workshop_Section_Merchandise,
  _ as Workshop_Section_Mtx,
  _ as Workshop_Section_ReadyToUse,
  _ as Workshop_Section_Videos,
  _ as Workshop_ServiceProviderRevenueSharing_ViewSite,
  _ as Workshop_ServiceProviderRevenueSharing_ViewSteamProfile,
  _ as Workshop_ServiceProvider_Category_Communities,
  _ as Workshop_ServiceProvider_Category_Tools,
  _ as Workshop_ServiceProvider_Category_Users,
  _ as Workshop_SortBy,
  _ as Workshop_SpecialFilter_AcceptedForUse,
  _ as Workshop_SpecialFilter_CreatedByFollowed,
  _ as Workshop_SpecialFilter_CreatedByFriends,
  _ as Workshop_SpecialFilter_Desc,
  _ as Workshop_SpecialFilter_FavoritedByFriends,
  _ as Workshop_SpecialFilter_None,
  _ as Workshop_SpecialFilter_ParentCollections,
  _ as Workshop_SpecialFilter_ParentItems,
  _ as Workshop_SpecialFilter_Reported,
  _ as Workshop_StatusIcon_TT_Accepted,
  _ as Workshop_StatusIcon_TT_BlockedCreator,
  _ as Workshop_StatusIcon_TT_Favorited,
  _ as Workshop_StatusIcon_TT_Incompatible,
  _ as Workshop_StatusIcon_TT_Played,
  _ as Workshop_StatusIcon_TT_Reported,
  _ as Workshop_StatusIcon_TT_Subscribed,
  _ as Workshop_StatusIcon_TT_VotedDown,
  _ as Workshop_StatusIcon_TT_VotedUp,
  _ as Workshop_SubMenu_LegalAgreement,
  _ as Workshop_SubMenu_ViewYourRevenue,
  _ as Workshop_SubMenu_ViewYourRevenue_Desc,
  _ as Workshop_SubMenu_VotingQueue,
  _ as Workshop_SubMenu_YourCollections,
  _ as Workshop_SubMenu_YourFavorites,
  _ as Workshop_SubMenu_YourItems,
  _ as Workshop_SubMenu_YourPaymentInfo,
  _ as Workshop_SubMenu_YourPlayed,
  _ as Workshop_SubMenu_YourSubscriptions,
  _ as Workshop_SubMenu_YourVotingQueue,
  _ as Workshop_Tag_NoneSpecified,
  _ as default,
  _ as language,
};
