var _ = `romanian`,
  _ = `Postat inițial de %1$s:`,
  _ = `{LINK ELIMINAT}`,
  _ = `Acest URL a fost șters de către filtrele noastre. De obicei acest lucru se întâmplă pentru a preveni atacurile de tip phishing și malware.`,
  _ = `(Doar Valve/moderatori) Apasă pentru a afișa linkul`,
  _ = `%1$s comentarii`,
  _ = `Se afișează comentariile %1$s-%2$s din %3$s`,
  _ = `Adaugă un comentariu`,
  _ = `Postează comentariul`,
  _ = `Instrucțiuni de formatare`,
  _ = `Inserează un emoticon`,
  _ = `Emoticon %1$s`,
  _ = `Caută`,
  _ = `Utilizate recent`,
  _ = `Toate emoticoanele`,
  _ = `Niciun emoticon nu corespunde căutării tale.`,
  _ = `Nu deții încă niciun emoticon.`,
  _ = `Formatarea textului`,
  _ = `Aceste etichete de marcare îți permit să formatezi textul comentariilor și postărilor tale asemenea limbajului HTML.`,
  _ = `Sintaxă`,
  _ = `Exemplu`,
  _ = `Text cu bold`,
  _ = `Text subliniat`,
  _ = `Text italic`,
  _ = `Text tăiat cu o linie`,
  _ = `Text spoiler`,
  _ = `Nu interpretează [b]etichetele[/b] `,
  _ = `Link către un site web`,
  _ = `Text citat`,
  _ = `Font cu lățime fixă,
păstrează    spațiile`,
  _ = `Text de antet`,
  _ = `Text de antet`,
  _ = `Text de antet`,
  _ = `Listă cu marcatori`,
  _ = `Listă ordonată`,
  _ = `Abonează-te la subiect`,
  _ = `Dezabonează-te de la subiect`,
  _ = `Abonează-te la un subiect pentru a primi o notificare de fiecare dată când cineva postează un comentariu nou.`,
  _ = `Ai fost abonat automat la acest subiect de comentarii pentru că este asociat cu profilul tău Steam.`,
  _ = `A apărut o eroare la actualizarea abonamentului tău. Te rugăm să încerci din nou mai târziu.`,
  _ = `Șterge`,
  _ = `Ascunde și raportează comentariul acesta`,
  _ = `Marchează ca suspect`,
  _ = `Elimină marcajul de conținut necorespunzător: %1$s`,
  _ = `Neverificat`,
  _ = `Resetează`,
  _ = `Necesită verificare`,
  _ = `Foarte puțin probabil`,
  _ = `Puțin probabil`,
  _ = `Posibil`,
  _ = `Probabil`,
  _ = `Foarte probabil`,
  _ = `Necunoscut (%1$s)`,
  _ = `Deschide în instrumentul de moderare`,
  _ = `Ai raportat acest comentariu`,
  _ = `Ai blocat acest jucător`,
  _ = `Anulează`,
  _ = `vezi comentariul acesta`,
  _ = `Poți vedea acest conținut datorită permisiunilor tale de agent de asistență/moderator.`,
  _ = `Acest comentariu nu a fost încă analizat de sistemul nostru automat de verificare a conținutului și va fi ascuns temporar până când vom verifica dacă include sau nu un conținut dăunător (de exemplu, linkuri către site-uri web care încearcă să fure informații).`,
  _ = `Acest comentariu a fost semnalat în mod automat deoarece include un conținut potențial dăunător și a fost ascuns prin urmare.`,
  _ = `În mod normal nu îți este permis să comentezi aici, dar ai privilegii suplimentare care îți permit să faci asta.`,
  _ = `Acest comentariu a fost șters.`,
  _ = `Comentariul tău este prea scurt.`,
  _ = `Comentariul tău este prea lung. Lungimea maximă este de %1$s caractere.`,
  _ = `Nu îți permis să postezi un comentariu aici.`,
  _ = `Trebuie să fii conectat la cont pentru a posta un comentariu.`,
  _ = `Trebuie să deții acest joc pentru a aduce un comentariu acestui articol.`,
  _ = `Ai nevoie de cel puțin o oră de joc pentru a putea posta un comentariu.`,
  _ = `Comentariile sunt dezactivate pentru acest articol.`,
  _ = `Nu există comentarii încă.`,
  _ = {
    language: _,
    CommentThread_QuoteBlock_Author: _,
    CommentThread_RemovedLink: _,
    CommentThread_RemovedLink_Tooltip: _,
    CommentThread_RemovedLink_Reveal: _,
    CommentThread_NumberOfComments: _,
    CommentThread_ShowingXToYOfTotal: _,
    CommentThread_AddAComment: _,
    CommentThread_PostComment: _,
    CommentThread_FormattingHelp: _,
    CommentThread_InsertEmoticon: _,
    CommentThread_EmoticonHoverApp: _,
    CommentThread_EmoticonSearch: _,
    CommentThread_EmoticonRecentlyUsed: _,
    CommentThread_EmoticonAll: _,
    CommentThread_EmoticonNoResults: _,
    CommentThread_EmoticonNoneOwned: _,
    CommentThread_FormattingHelpHeader: _,
    Discussions_FormattingHelp_Description: _,
    Discussions_FormattingHelp_ColumnSyntax: _,
    Discussions_FormattingHelp_ColumnExample: _,
    Discussions_FormattingHelp_Bold: _,
    Discussions_FormattingHelp_Underline: _,
    Discussions_FormattingHelp_Italic: _,
    Discussions_FormattingHelp_Strike: _,
    Discussions_FormattingHelp_Spoiler: _,
    Discussions_FormattingHelp_Noparse: _,
    Discussions_FormattingHelp_Link: _,
    Discussions_FormattingHelp_Quote: _,
    Discussions_FormattingHelp_Code: _,
    Discussions_FormattingHelp_H1: _,
    Discussions_FormattingHelp_H2: _,
    Discussions_FormattingHelp_H3: _,
    Discussions_FormattingHelp_List: _,
    Discussions_FormattingHelp_OList: _,
    CommentThread_Subscribe: _,
    CommentThread_Unsubscribe: _,
    CommentThread_SubscribeHint: _,
    CommentThread_SubscribeHintOwnThread: _,
    CommentThread_SubscribeError: _,
    CommentThread_DeleteComment: _,
    CommentThread_HideComment: _,
    CommentThread_MarkSpam: _,
    CommentThread_ClearContentCheck: _,
    BanContentCheckResult_NotScanned: _,
    BanContentCheckResult_Reset: _,
    BanContentCheckResult_NeedsChecking: _,
    BanContentCheckResult_VeryUnlikely: _,
    BanContentCheckResult_Unlikely: _,
    BanContentCheckResult_Possible: _,
    BanContentCheckResult_Likely: _,
    BanContentCheckResult_VeryLikely: _,
    BanContentCheckResult_Unknown: _,
    CommentThread_ModerationTool: _,
    CommentThread_HiddenByUser: _,
    CommentThread_HiddenByBlocked: _,
    CommentThread_HiddenUndo: _,
    CommentThread_HiddenViewComment: _,
    CommentThread_ModeratorViewContent: _,
    CommentThread_NeedsContentCheck: _,
    CommentThread_FailedContentCheck: _,
    CommentThread_PermissionOverride: _,
    CommentThread_Deleted: _,
    CommentThread_PostError_TooShort: _,
    CommentThread_PostError_TooLong: _,
    CommentThread_PostError_NotAllowed: _,
    CommentThread_PostError_NotLoggedIn: _,
    CommentThread_PostError_MustOwnApp: _,
    CommentThread_PostError_LimitedUser: _,
    CommentThread_CommentsDisabled: _,
    CommentThread_NoComments: _,
  };
export {
  _ as BanContentCheckResult_Likely,
  _ as BanContentCheckResult_NeedsChecking,
  _ as BanContentCheckResult_NotScanned,
  _ as BanContentCheckResult_Possible,
  _ as BanContentCheckResult_Reset,
  _ as BanContentCheckResult_Unknown,
  _ as BanContentCheckResult_Unlikely,
  _ as BanContentCheckResult_VeryLikely,
  _ as BanContentCheckResult_VeryUnlikely,
  _ as CommentThread_AddAComment,
  _ as CommentThread_ClearContentCheck,
  _ as CommentThread_CommentsDisabled,
  _ as CommentThread_DeleteComment,
  _ as CommentThread_Deleted,
  _ as CommentThread_EmoticonAll,
  _ as CommentThread_EmoticonHoverApp,
  _ as CommentThread_EmoticonNoResults,
  _ as CommentThread_EmoticonNoneOwned,
  _ as CommentThread_EmoticonRecentlyUsed,
  _ as CommentThread_EmoticonSearch,
  _ as CommentThread_FailedContentCheck,
  _ as CommentThread_FormattingHelp,
  _ as CommentThread_FormattingHelpHeader,
  _ as CommentThread_HiddenByBlocked,
  _ as CommentThread_HiddenByUser,
  _ as CommentThread_HiddenUndo,
  _ as CommentThread_HiddenViewComment,
  _ as CommentThread_HideComment,
  _ as CommentThread_InsertEmoticon,
  _ as CommentThread_MarkSpam,
  _ as CommentThread_ModerationTool,
  _ as CommentThread_ModeratorViewContent,
  _ as CommentThread_NeedsContentCheck,
  _ as CommentThread_NoComments,
  _ as CommentThread_NumberOfComments,
  _ as CommentThread_PermissionOverride,
  _ as CommentThread_PostComment,
  _ as CommentThread_PostError_LimitedUser,
  _ as CommentThread_PostError_MustOwnApp,
  _ as CommentThread_PostError_NotAllowed,
  _ as CommentThread_PostError_NotLoggedIn,
  _ as CommentThread_PostError_TooLong,
  _ as CommentThread_PostError_TooShort,
  _ as CommentThread_QuoteBlock_Author,
  _ as CommentThread_RemovedLink,
  _ as CommentThread_RemovedLink_Reveal,
  _ as CommentThread_RemovedLink_Tooltip,
  _ as CommentThread_ShowingXToYOfTotal,
  _ as CommentThread_Subscribe,
  _ as CommentThread_SubscribeError,
  _ as CommentThread_SubscribeHint,
  _ as CommentThread_SubscribeHintOwnThread,
  _ as CommentThread_Unsubscribe,
  _ as Discussions_FormattingHelp_Bold,
  _ as Discussions_FormattingHelp_Code,
  _ as Discussions_FormattingHelp_ColumnExample,
  _ as Discussions_FormattingHelp_ColumnSyntax,
  _ as Discussions_FormattingHelp_Description,
  _ as Discussions_FormattingHelp_H1,
  _ as Discussions_FormattingHelp_H2,
  _ as Discussions_FormattingHelp_H3,
  _ as Discussions_FormattingHelp_Italic,
  _ as Discussions_FormattingHelp_Link,
  _ as Discussions_FormattingHelp_List,
  _ as Discussions_FormattingHelp_Noparse,
  _ as Discussions_FormattingHelp_OList,
  _ as Discussions_FormattingHelp_Quote,
  _ as Discussions_FormattingHelp_Spoiler,
  _ as Discussions_FormattingHelp_Strike,
  _ as Discussions_FormattingHelp_Underline,
  _ as default,
  _ as language,
};
