var _ = `Форумни публикации`,
  _ = `Общи дискусии`,
  _ = `Докладвани публикации`,
  _ = `Дискусии на работилницата`,
  _ = `Търговия`,
  _ = `Събития и анонси`,
  _ = `1 доклад`,
  _ = `%1$s доклада`,
  _ = `1 тема`,
  _ = `%1$s теми`,
  _ = `%1$s на %2$s`,
  _ = `%1$s на %2$s в темата — %3$s`,
  _ = `1 доклад`,
  _ = `%1$s доклада`,
  _ = `1 тема`,
  _ = `%1$s теми`,
  _ = `Steam общност`,
  _ = `Steam общност :: Грешка`,
  _ = `Грешка`,
  _ = `Неизвестна грешка`,
  _ = `Игри`,
  _ = `Steam общност :: %1$s :: Игри`,
  _ = `Търсене — Обществения Steam пазар`,
  _ = `%1$s — Обществения Steam пазар`,
  _ = `Артикул на пазара — Обществения Steam пазар`,
  _ = `Общественият Steam пазар`,
  _ = `Профилът не е намерен`,
  _ = `Неуспешно зареждане на списъка с желания за потребителя.`,
  _ = `Наскоро сте направили прекалено много заявки. Моля, изчакайте и опитайте Вашата заявка по-късно.`,
  _ = `Зареждане`,
  _ = `%1$s% ЗАВЪРШЕНИ`,
  _ = `ПАУЗИРАНО — %1$s% ЗАВЪРШЕНИ`,
  _ = `%1$s/%2$s СВАЛЕНИ`,
  _ = `ПОСТИЖЕНИЯ`,
  _ = `Остава(т) приблизително %1$s`,
  _ = `%1$s/%2$s`,
  _ = `ДЕИНСТАЛИРАНЕ`,
  _ = `ОБНОВЯВАНЕ`,
  _ = `ДЕИНСТАЛИРАНЕ`,
  _ = `СВАЛЯНЕ`,
  _ = `ПАУЗА`,
  _ = `ВЪЗОБНОВЯВАНЕ`,
  _ = `ДЕИНСТАЛИРАНЕ`,
  _ = `ОТКАЗ`,
  _ = `Преглед на настройките ми за поверителност за това съдържание`,
  _ = `Намиране на игра`,
  _ = `Филтриране за игри, които и двамата притежавате`,
  _ = `Игрално време`,
  _ = `Име`,
  _ = `Завършване на постижения`,
  _ = `ОБЩО ИЗИГРАНО`,
  _ = `ПОСЛЕДНО ПУСКАНЕ`,
  _ = `ПОСЛЕДНИТЕ ДВЕ СЕДМИЦИ`,
  _ = `Инф. и връзки за играта`,
  _ = `Дистанционно сваляне`,
  _ = `ДИСТАНЦИОННО СВАЛЯНЕ КЪМ: %1$s`,
  _ = `СТАТУС НА ДИСТАНЦИОННОТО СВАЛЯНЕ: %1$s`,
  _ = `Невъзможно достигане на компютъра Ви`,
  _ = `С цел да сваляте дистанционно игри към Вашия Steam клиент, компютърът Ви трябва да бъде активен с интернет връзка и ще е нужно да сте вписани.`,
  _ = `Прочетете ЧЗВ`,
  _ = `%1$s. %2$s`,
  _ = `Научете още`,
  _ = `ДИСТАНЦИОННОТО СВАЛЯНЕ Е НЕДОСТЪПНО`,
  _ = `Бихте ли искали да деинсталирате %1$s? %1$s ще остане в игралната Ви библиотека, но за бъдещо пускане първо ще е нужно да свалите повторно цялото съдържание.`,
  _ = `%1$s | „%2$s“`,
  _ = `Наскоро пускани %1$s`,
  _ = `Всички игри %1$s`,
  _ = `Перфектни игри %1$s`,
  _ = `Рецензии %1$s`,
  _ = `Следвани %1$s`,
  _ = `Списък с желания`,
  _ = `Достигнати са всички възможни постижения`,
  _ = `Тук ще намерите Вашите „Перфектни игри“. Това са заглавията, в които сте достигнали всички възможни постижения.`,
  _ = `%1$s% от играчите имат това постижение`,
  _ = `Страница в магазина`,
  _ = `Форуми`,
  _ = `Групи`,
  _ = `Официален уебсайт`,
  _ = `Новини`,
  _ = `Моите постижения`,
  _ = `Постиженията на %1$s`,
  _ = `Статистиките на %1$s`,
  _ = `Личните игрални данни на %1$s`,
  _ = `Моите класации`,
  _ = `Класациите на %1$s`,
  _ = `Глобални постижения`,
  _ = `Глобални класации`,
  _ = `Игрални статистики`,
  _ = `Игрално съдържание`,
  _ = `Моите игрални статистики`,
  _ = `Моето игрално съдържание`,
  _ = `Игрални връзки`,
  _ = `Моите снимки (%1$s)`,
  _ = `Снимките на %1$s (%2$s)`,
  _ = `Приятелите ми, които играят %1$s`,
  _ = `Моите карти за размяна (%1$s)`,
  _ = `Рецензията ми`,
  _ = `Рецензията на %1$s`,
  _ = `Обществен център`,
  _ = `Моите бележки`,
  _ = `%1$s часа`,
  _ = `%1$s минути`,
  _ = `Маркиране като лична`,
  _ = `Премахване на маркирането като лична`,
  _ = `Маркиране на тази игра като лична и скриване от приятелите ми`,
  _ = `© Valve Corporation. Всички права запазени. Всички търговски марки принадлежат на съответните им собственици в САЩ и други страни.`,
  _ = `Част от географските сведения на този уебсайт се предоставят от %1$s.`,
  _ = `Декларация за поверителност`,
  _ = `Юридическа\xA0информация`,
  _ = `Условия за ползване на Steam`,
  _ = `Възстановявания`,
  _ = `Бисквитки`,
  _ = `Достъпност`,
  _ = `Текущи забрани`,
  _ = `Обществени съобщения`,
  _ = `Докладвано съдържание`,
  _ = `Модерирано съдържание`,
  _ = `Това са неща в Steam, които сте докладвали за нарушаване на насоките в Steam.`,
  _ = `Това е списък от съдържание, което сте публикували в Steam и то е било модерирано.`,
  _ = `Последно обновено: %1$s`,
  _ = ``,
  _ = {
    Moderation_SubjectTypeName_ForumPost: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    moderation_claim_report_count: _,
    moderation_claim_report_count_Plural: _,
    moderation_claim_subject_count: _,
    moderation_claim_subject_count_Plural: _,
    moderation_claim_n_reports_on_m_subjects: _,
    moderation_forumpost_summary: _,
    moderation_forumpost_summary_reports_fragment: _,
    moderation_forumpost_summary_reports_fragment_Plural: _,
    moderation_forumpost_summary_subjects_fragment: _,
    moderation_forumpost_summary_subjects_fragment_Plural: _,
    community_title: _,
    community_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    profile_games_list: _,
    profile_games_list_title: _,
    Market_Search_Title: _,
    Market_Item_Title: _,
    Market_Item_GenericTitle: _,
    Market_GenericTitle: _,
    profile_error_profilenotfound: _,
    profile_games_list_error_loadfailed: _,
    Error_RateLimited: _,
    Loading: _,
    GamesList_Header_Downloading: _,
    GamesList_Header_Paused: _,
    GamesList_Header_DownloadBytes: _,
    GamesList_Header_Achievements: _,
    GamesList_TimeRemaining: _,
    GamesList_Achievement_Fraction: _,
    GamesList_Uninstalling: _,
    GamesList_Button_UpdateRequired: _,
    GamesList_Button_Uninstall: _,
    GamesList_Button_Download: _,
    GamesList_Button_Pause: _,
    GamesList_Button_Resume: _,
    GamesList_Button_Uninstalling: _,
    GamesList_Button_Cancel: _,
    GamesList_PrivacySettings_Tooltip: _,
    GamesList_Filter_Placeholder: _,
    GamesList_Filter_BothOwned: _,
    GamesList_Sort_HoursPlayed: _,
    GamesList_Sort_Name: _,
    GamesList_Sort_AchievementCompletion: _,
    GamesList_Header_TotalPlayed: _,
    GamesList_Header_LastPlayed: _,
    GamesList_Header_TwoWeeks: _,
    GamesList_MenuLabel_GameInfo: _,
    GamesList_MenuLabel_RemoteDownload: _,
    GamesList_Header_RemoteDownload: _,
    GamesList_Header_RemoteDownloadStatus: _,
    GamesList_RemoteDownload_NoConnection: _,
    GamesList_RemoteDownload_Help: _,
    GamesList_RemoteDownload_ReadTheFAQ: _,
    GamesList_RemoteDownload_Info: _,
    GamesList_RemoteDownload_LearnMore: _,
    GamesList_RemoteDownload_NoRemoteControl: _,
    GamesList_RemoteDownload_UninstallConfirm: _,
    GamesList_Client_Indicator: _,
    GamesList_Tab_RecentlyPlayed: _,
    GamesList_Tab_AllGames: _,
    GamesList_Tab_PerfectGames: _,
    GamesList_Tab_Reviews: _,
    GamesList_Tab_Followed: _,
    GamesList_Tab_Wishlist: _,
    Perfect_Game_Description: _,
    GamesList_PerfectGames_Description: _,
    GamesList_Achievement_Unlock_Percentage: _,
    Community_StorePage: _,
    Community_Forums: _,
    Community_Groups: _,
    Community_OfficialWebsite: _,
    Community_News: _,
    Community_UsersAchievementsFirstPerson: _,
    Community_UsersAchievements: _,
    Community_UsersStats: _,
    Community_GamePersonalData: _,
    Community_UsersLeaderboardsFirstPerson: _,
    Community_UsersLeaderboards: _,
    Community_GlobalAchievements: _,
    Community_GlobalLeaderboards: _,
    Community_GameStats: _,
    Community_GameContent: _,
    Community_GameStatsFirstPerson: _,
    Community_GameContentFirstPerson: _,
    Community_GameLinks: _,
    Community_ScreenshotsMenuItemFirstPerson: _,
    Community_ScreenshotsMenuItemThirdPerson: _,
    Community_FriendsWhoPlayMenuItemFirstPerson: _,
    Community_TradingCardsMenuItemFirstPerson: _,
    Community_ReviewMenuItemFirstPerson: _,
    Community_ReviewMenuItemThirdPerson: _,
    Community_GameHubMenuItem: _,
    Community_GameNotesFirstPerson: _,
    Playtime_Hours: _,
    Playtime_Minutes: _,
    AppPrivacy_MarkAsPrivate: _,
    AppPrivacy_UnmarkAsPrivate: _,
    AppPrivacy_Explanation: _,
    footer_legal_notice: _,
    footer_geodata_notice: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_accessibility: _,
    profiletabs_currentbans: _,
    profiletabs_communitymessages: _,
    profiletabs_reportedcontent: _,
    profiletabs_moderatedcontent: _,
    reportedcontent_description: _,
    moderatedcontent_description: _,
    reportedcontent_lastupdated: _,
    empty_no_comma_following: ``,
  };
export {
  _ as AppPrivacy_Explanation,
  _ as AppPrivacy_MarkAsPrivate,
  _ as AppPrivacy_UnmarkAsPrivate,
  _ as Community_Forums,
  _ as Community_FriendsWhoPlayMenuItemFirstPerson,
  _ as Community_GameContent,
  _ as Community_GameContentFirstPerson,
  _ as Community_GameHubMenuItem,
  _ as Community_GameLinks,
  _ as Community_GameNotesFirstPerson,
  _ as Community_GamePersonalData,
  _ as Community_GameStats,
  _ as Community_GameStatsFirstPerson,
  _ as Community_GlobalAchievements,
  _ as Community_GlobalLeaderboards,
  _ as Community_Groups,
  _ as Community_News,
  _ as Community_OfficialWebsite,
  _ as Community_ReviewMenuItemFirstPerson,
  _ as Community_ReviewMenuItemThirdPerson,
  _ as Community_ScreenshotsMenuItemFirstPerson,
  _ as Community_ScreenshotsMenuItemThirdPerson,
  _ as Community_StorePage,
  _ as Community_TradingCardsMenuItemFirstPerson,
  _ as Community_UsersAchievements,
  _ as Community_UsersAchievementsFirstPerson,
  _ as Community_UsersLeaderboards,
  _ as Community_UsersLeaderboardsFirstPerson,
  _ as Community_UsersStats,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as GamesList_Achievement_Fraction,
  _ as GamesList_Achievement_Unlock_Percentage,
  _ as GamesList_Button_Cancel,
  _ as GamesList_Button_Download,
  _ as GamesList_Button_Pause,
  _ as GamesList_Button_Resume,
  _ as GamesList_Button_Uninstall,
  _ as GamesList_Button_Uninstalling,
  _ as GamesList_Button_UpdateRequired,
  _ as GamesList_Client_Indicator,
  _ as GamesList_Filter_BothOwned,
  _ as GamesList_Filter_Placeholder,
  _ as GamesList_Header_Achievements,
  _ as GamesList_Header_DownloadBytes,
  _ as GamesList_Header_Downloading,
  _ as GamesList_Header_LastPlayed,
  _ as GamesList_Header_Paused,
  _ as GamesList_Header_RemoteDownload,
  _ as GamesList_Header_RemoteDownloadStatus,
  _ as GamesList_Header_TotalPlayed,
  _ as GamesList_Header_TwoWeeks,
  _ as GamesList_MenuLabel_GameInfo,
  _ as GamesList_MenuLabel_RemoteDownload,
  _ as GamesList_PerfectGames_Description,
  _ as GamesList_PrivacySettings_Tooltip,
  _ as GamesList_RemoteDownload_Help,
  _ as GamesList_RemoteDownload_Info,
  _ as GamesList_RemoteDownload_LearnMore,
  _ as GamesList_RemoteDownload_NoConnection,
  _ as GamesList_RemoteDownload_NoRemoteControl,
  _ as GamesList_RemoteDownload_ReadTheFAQ,
  _ as GamesList_RemoteDownload_UninstallConfirm,
  _ as GamesList_Sort_AchievementCompletion,
  _ as GamesList_Sort_HoursPlayed,
  _ as GamesList_Sort_Name,
  _ as GamesList_Tab_AllGames,
  _ as GamesList_Tab_Followed,
  _ as GamesList_Tab_PerfectGames,
  _ as GamesList_Tab_RecentlyPlayed,
  _ as GamesList_Tab_Reviews,
  _ as GamesList_Tab_Wishlist,
  _ as GamesList_TimeRemaining,
  _ as GamesList_Uninstalling,
  _ as Loading,
  _ as Market_GenericTitle,
  _ as Market_Item_GenericTitle,
  _ as Market_Item_Title,
  _ as Market_Search_Title,
  _ as Moderation_SubjectTypeName_ForumPost,
  _ as Perfect_Game_Description,
  _ as Playtime_Hours,
  _ as Playtime_Minutes,
  _ as community_errorpage_title,
  _ as community_title,
  _ as default,
  _ as empty_no_comma_following,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_accessibility,
  _ as footer_cookies,
  _ as footer_geodata_notice,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_privacy_policy,
  _ as footer_refunds,
  _ as footer_ssa,
  _ as moderatedcontent_description,
  _ as moderation_claim_n_reports_on_m_subjects,
  _ as moderation_claim_report_count,
  _ as moderation_claim_report_count_Plural,
  _ as moderation_claim_subject_count,
  _ as moderation_claim_subject_count_Plural,
  _ as moderation_forumpost_summary,
  _ as moderation_forumpost_summary_reports_fragment,
  _ as moderation_forumpost_summary_reports_fragment_Plural,
  _ as moderation_forumpost_summary_subjects_fragment,
  _ as moderation_forumpost_summary_subjects_fragment_Plural,
  _ as profile_error_profilenotfound,
  _ as profile_games_list,
  _ as profile_games_list_error_loadfailed,
  _ as profile_games_list_title,
  _ as profiletabs_communitymessages,
  _ as profiletabs_currentbans,
  _ as profiletabs_moderatedcontent,
  _ as profiletabs_reportedcontent,
  _ as reportedcontent_description,
  _ as reportedcontent_lastupdated,
};
