var _ = `Buscar no Mercado da Comunidade`,
  _ = `Redefinir filtros`,
  _ = `Buscar`,
  _ = `Selecione um jogo...`,
  _ = `Recém-jogados com itens`,
  _ = `Jogos populares com itens`,
  _ = `Limpar seleção`,
  _ = `Buscar...`,
  _ = `Buscar em %1$s...`,
  _ = `Itens do jogo`,
  _ = `Itens do Steam`,
  _ = `Tipo do item`,
  _ = `Este jogo não tem filtros de Mercado.`,
  _ = `Clique em "Buscar" para ver os itens disponíveis.`,
  _ = `Houve um erro ao carregar os filtros para este jogo.`,
  _ = `Preço`,
  _ = `Preço mín.`,
  _ = `Preço máx.`,
  _ = `Tudo`,
  _ = `Outro`,
  _ = `Filtrar...`,
  _ = `Filtrar por jogo...`,
  _ = `Recurso beta — compartilhe comentários`,
  _ = `Buscar nomes de itens no Mercado...`,
  _ = `Caixas de Armas, Cápsulas de Adesivos, Pacotes de Lembrança etc.`,
  _ = `Mercado da Comunidade Steam`,
  _ = `Compre e venda itens para membros da comunidade com o saldo da Carteira Steam`,
  _ = `Saiba mais`,
  _ = `Buscar no Mercado`,
  _ = `Nova busca...`,
  _ = `Filtros`,
  _ = `Sair do beta do Mercado`,
  _ = `Enviar comentários`,
  _ = `Este item é uma commodity, onde todos os itens individuais são efetivamente idênticos. Não é possível acessar anúncios individuais; no entanto, você pode fazer uma encomenda para comprar a um preço especifico, sendo que o anúncio mais barato será automaticamente associado à encomenda de maior quantidade.`,
  _ = `%1$s resultado`,
  _ = `%1$s resultados encontrados`,
  _ = `%1$s resultado encontrado para:`,
  _ = `%1$s resultados encontrados para:`,
  _ = `Resultados para:`,
  _ = `%2$s anúncio encontrado`,
  _ = `%2$s anúncios encontrados`,
  _ = `Popularidade`,
  _ = `Nome (A a Z)`,
  _ = `Nome (Z a A)`,
  _ = `Preço (crescente)`,
  _ = `Preço (decrescente)`,
  _ = `Quantidade (crescente)`,
  _ = `Quantidade (decrescente)`,
  _ = `%1$s (crescente)`,
  _ = `%1$s (decrescente)`,
  _ = `Ordenar por:`,
  _ = `Buscar`,
  _ = `Buscar...`,
  _ = `Comprar`,
  _ = `Vender`,
  _ = `Comprar agora`,
  _ = `Encomendar...`,
  _ = `Encomendar:`,
  _ = `Fechar`,
  _ = `Quantidade à venda: %1$s`,
  _ = `Qtd.: %1$s`,
  _ = `A partir de %1$s`,
  _ = `%1$s`,
  _ = `Filtrar resultados...`,
  _ = `Busca avançada`,
  _ = `Busca avançada`,
  _ = `Buscar um item...`,
  _ = `Página inicial do Mercado`,
  _ = `Jogos populares`,
  _ = `Incluir descrições na busca`,
  _ = `Algumas entradas mais antigas usam descrições textuais para propriedades importantes que não são acessíveis com os filtros abaixo. Esta opção permitirá que o texto buscado seja comparado com a descrição completa em vez de apenas com o nome da entrada.`,
  _ = `Filtros`,
  _ = `Redefinir busca`,
  _ = `Inserir texto de filtro personalizado...`,
  _ = `Após a compra, este item:`,
  _ = `não será trocável por um dia`,
  _ = `não será trocável por uma semana`,
  _ = `não será trocável por %1$s dias`,
  _ = `não será trocável`,
  _ = `não poderá ser anunciado no Mercado da Comunidade por um dia`,
  _ = `não poderá ser anunciado no Mercado da Comunidade por uma semana`,
  _ = `não poderá ser anunciado no Mercado da Comunidade por %1$s dias`,
  _ = `poderá ser revendido no Mercado da Comunidade Steam imediatamente`,
  _ = `%1$s: %2$s – %3$s`,
  _ = `%1$s: "%2$s"`,
  _ = `Comprar um item`,
  _ = `Nome`,
  _ = `Preço`,
  _ = `Subtotal:`,
  _ = `Tarifa de %1$s (%2$s%):`,
  _ = `Tarifa do jogo (%1$s%):`,
  _ = `Tarifa de transação do Steam (%1$s%):`,
  _ = `Imposto local sobre vendas (%1$s):`,
  _ = `Total:`,
  _ = `Forma de pagamento:`,
  _ = `Minha Carteira Steam`,
  _ = `Conta Steam:`,
  _ = `Endereço de cobrança:`,
  _ = `Nome`,
  _ = `Sobrenome`,
  _ = `Endereço de cobrança`,
  _ = `Endereço de cobrança, linha 2`,
  _ = `Cidade`,
  _ = `Estado/UF/Província`,
  _ = `CEP ou código postal`,
  _ = `País`,
  _ = `Salvar o meu endereço para agilizar compras futuras`,
  _ = `Adicionar fundos`,
  _ = `Comprar`,
  _ = `Aceito os termos do %1$s (última atualização em %2$s)`,
  _ = `Acordo de Assinatura do Steam`,
  _ = `Você precisa aceitar os termos do Acordo de Assinatura do Steam para concluir esta transação.`,
  _ = `Ao clicar em "Comprar" você concorda que está recebendo acesso imediato ao conteúdo digital do item e que por esse motivo qualquer possibilidade de anulação da venda resultante termina — a compra é definitiva.`,
  _ = `Ocorreu um problema com a compra do seu item. É possível que o anúncio tenha sido removido. Atualize a página e tente novamente.`,
  _ = `Ocorreu um problema ao aguardar que confirmasse a compra do item. Atualize a página e tente novamente.`,
  _ = `Os seguintes campos são obrigatórios:`,
  _ = `Informe um endereço militar válido`,
  _ = `Informe um CEP ou código postal válido`,
  _ = `Parabéns pela compra! Você pode ver o novo item no <1>seu inventário</1>.`,
  _ = `Ver inventário`,
  _ = `Confirmação adicional necessária`,
  _ = `Aguardando a confirmação da compra...`,
  _ = `Algumas compras exigem confirmação pelo aplicativo móvel do Steam.`,
  _ = `Algumas compras exigem confirmação por um e-mail do Steam Guard.`,
  _ = `Algumas compras exigem confirmação pelo aplicativo móvel do Steam ou e-mail do Steam Guard.`,
  _ = `Use o aplicativo móvel do Steam para confirmar a compra...`,
  _ = `Acesse o seu e-mail para confirmar a compra...`,
  _ = `Use o aplicativo móvel do Steam ou acesse o seu e-mail para confirmar a compra...`,
  _ = `Compra concluída com sucesso`,
  _ = `Fechar`,
  _ = `Ver inventário`,
  _ = `Salvar o meu endereço para agilizar compras futuras`,
  _ = `Este anúncio não está mais disponível`,
  _ = `Indisponível`,
  _ = `Este anúncio não está mais disponível para compra.`,
  _ = `(meu anúncio)`,
  _ = `Comprar — %1$s`,
  _ = `Encomendar`,
  _ = `Que tipo de item deseja comprar?`,
  _ = `Selecione um item...`,
  _ = `Que preço deseja pagar:`,
  _ = `(por item)`,
  _ = `Quantos deseja comprar:`,
  _ = `Preço máximo %1$s:`,
  _ = `Este é o valor máximo que será cobrado pela sua encomenda. Os itens serão comprados pelo menor preço possível, portanto, a sua encomenda poderá custar menos do que este valor.`,
  _ = `Buscando anúncios do item no preço desejado...`,
  _ = `Compra bem-sucedida! O item foi adicionado ao seu inventário e o recibo foi enviado para o seu e-mail.`,
  _ = `Sucesso! A sua encomenda foi criada.`,
  _ = `Você receberá automaticamente uma notificação por e-mail quando a compra for concluída. Você pode cancelar a encomenda na parte superior desta página ou na página inicial do Mercado.`,
  _ = `Ops! Houve um problema ao receber a confirmação dos servidores Steam. Verifique se a sua encomenda foi criada ou processada. Caso contrário, tente novamente mais tarde.`,
  _ = `O preço mínimo por unidade é %1$s`,
  _ = `≤\xA0%1$s`,
  _ = `≥ %1$s`,
  _ = `Preço`,
  _ = `Quantidade`,
  _ = `%1$s à venda, a partir de %2$s`,
  _ = `Não há anúncios ativos para este item`,
  _ = `%1$s encomendas por %2$s ou menos`,
  _ = `Não há encomendas ativas para este item.`,
  _ = `Selecione uma aba acima para ver informações de encomenda`,
  _ = `Não encontrou o item ou preço que deseja?`,
  _ = `Não encontrou um preço que lhe agrade?`,
  _ = `Encomendas (cumulativo)`,
  _ = `1 encomenda por %2$s ou mais`,
  _ = `%1$s encomendas por %2$s ou mais`,
  _ = `1 anúncio por %2$s ou menos`,
  _ = `%1$s anúncios por %2$s ou menos`,
  _ = `1 encomenda por <1>%2$s</1>`,
  _ = `%3$s encomendas por <1>%2$s ou menos</1>`,
  _ = `Valores medianos de venda`,
  _ = `Semana`,
  _ = `Mês`,
  _ = `Ano`,
  _ = `Desde o início`,
  _ = `%1$s vendido(s)`,
  _ = `Preço`,
  _ = `Quantidade`,
  _ = `Sem dados para o período selecionado`,
  _ = `Sem dados de compra`,
  _ = `N/D`,
  _ = `NOME`,
  _ = `PREÇO`,
  _ = `QUANTIDADE`,
  _ = `ANUNCIADO EM`,
  _ = `Cancelar`,
  _ = `Remover`,
  _ = `Meus anúncios e encomendas ativos`,
  _ = `Anúncios`,
  _ = `Encomendas`,
  _ = `Compras: minhas encomendas`,
  _ = `Vendas: meus anúncios`,
  _ = `Houve um problema ao carregar os dados deste item.`,
  _ = `Você não tem anúncios nem encomendas ativas para este item.`,
  _ = `Você não tem encomendas ativas para este item.`,
  _ = `Você não tem anúncios ativos para este item. Venda itens pelo seu inventário ou clicando no botão "Vender" nesta página.`,
  _ = `Quantidade: %1$s`,
  _ = `Ver tudo (%1$s)`,
  _ = `Houve um problema ao cancelar a sua encomenda. Tente novamente mais tarde.`,
  _ = `Houve um problema ao remover o seu anúncio. Tente novamente mais tarde.`,
  _ = `Remover um anúncio`,
  _ = `Tem certeza de que deseja remover o anúncio de %1$s e devolver o item ao seu inventário?`,
  _ = `Tem certeza de que deseja remover o anúncio e devolver o item ao seu inventário?`,
  _ = `Sim, remover anúncio`,
  _ = `Não`,
  _ = `Anúncio removido com sucesso`,
  _ = `Escolha um item do seu inventário`,
  _ = `O que é uma encomenda?`,
  _ = `Defina o seu preço preferido, e a compra será realizada automaticamente quando o item estiver disponível pelo preço escolhido.`,
  _ = `O Steam garantirá que você pague o melhor preço disponível.`,
  _ = `Para este item, encomendas serão processadas com a opção de compra mais barata, não importando as suas características.`,
  _ = `A partir de %1$s`,
  _ = `Ops!`,
  _ = `Ocorreu um erro ao processar a sua solicitação:`,
  _ = `Você realizou solicitações demais recentemente. Aguarde e tente realizar a sua solicitação novamente mais tarde.`,
  _ = `Pode conter:`,
  _ = `Houve um problema ao carregar este conteúdo`,
  _ = `O item solicitado pode não existir ou um problema temporário pode estar impedindo o seu carregamento. Tente novamente mais tarde.`,
  _ = `Filtrar anúncios`,
  _ = `Nenhum anúncio encontrado`,
  _ = `Mais opções...`,
  _ = `Filtrar...`,
  _ = `Informações`,
  _ = `Gráfico de vendas`,
  _ = `Encomendas`,
  _ = `Filtros`,
  _ = `Mín.`,
  _ = `Máx.`,
  _ = `Acessórios`,
  _ = `Qualquer um`,
  _ = `Nenhum`,
  _ = `%1$s: %2$s`,
  _ = `Você não pode comprar este item porque a compra e venda deste tipo de item está indisponível em seu país.`,
  _ = `Você não pode comprar este item porque a compra deste tipo de item está indisponível em seu país.`,
  _ = `Este anúncio ainda não tem imagens únicas ou aprimoradas. A imagem aqui exibida pode variar ligeiramente do item anunciado.`,
  _ = `Exibir fundo`,
  _ = `Houve um erro ao tentar exibir o anúncio.`,
  _ = `Você não pode comprar nem vender itens no Mercado pelo seguinte motivo:`,
  _ = `Você não pode comprar nem vender itens no Mercado pelos seguintes motivos:`,
  _ = `Ver resultados`,
  _ = `Exibir em grade`,
  _ = `Exibir em lista`,
  _ = `Houve um problema ao carregar resultados adicionais. Tente novamente mais tarde.`,
  _ = `Você está tentando acessar um item de um jogo novo no Steam que você nunca jogou. Tenha cautela.`,
  _ = `Clique para exibir o item mesmo assim`,
  _ = `Filtrar por jogo`,
  _ = `Ver todos os jogos`,
  _ = `A sua conta está atualmente trancada.`,
  _ = `Informações sobre este trancamento podem ser encontradas ao clicar na barra vermelha exibida no canto superior direito após iniciar a sessão no cliente Steam.  Para informações adicionais, entre em contato com o Suporte Steam.`,
  _ = `A sua conta está atualmente trancada. Informações sobre este trancamento podem ser encontradas ao clicar na barra vermelha exibida no canto superior direito após iniciar a sessão no cliente Steam.`,
  _ = `Para remover esta restrição...`,
  _ = `A sua conta está atualmente proibida de trocar.`,
  _ = `Esta conta atualmente não pode usar o Mercado da Comunidade Steam.`,
  _ = `A proibição pode ser temporária (com duração variável) ou permanente. Para saber quando (e se) poderá voltar a trocar, clique na barra vermelha exibida no canto superior direito após iniciar a sessão no cliente Steam.`,
  _ = `A sua conta foi proibida de trocar. Para saber quando poderá voltar a trocar, clique na barra vermelha exibida no canto superior direito após iniciar a sessão no cliente Steam.`,
  _ = `Mais informações...`,
  _ = `É necessário ter realizado uma compra no Steam há mais de %1$s dias, mas há menos de um ano, sem estornos ou disputas de pagamento recentes.`,
  _ = `Realize uma compra na Loja Steam. Crédito da Carteira, jogos e conteúdos adicionais são compras válidas — já a ativação de códigos de produto e presentes não são compras válidas. O Suporte Steam não pode remover tal restrição.`,
  _ = `É necessário ter realizado uma compra no Steam há mais de %1$s dias, mas há menos de um ano, sem estornos ou disputas de pagamento recentes. O Suporte Steam não pode remover estas restrições.`,
  _ = `Parece que você realizou uma compra válida na Loja Steam, mas ainda não completou %1$s dias.`,
  _ = `É necessário ter realizado uma compra válida no Steam entre %1$s dias e um ano, sem estornos ou disputas de pagamento recentes. Parece que você realizou uma compra, mas a mesma ainda não completou %1$s dias. O Suporte Steam não pode remover tal restrição.`,
  _ = `A senha da sua conta foi redefinida recentemente.`,
  _ = `Esta restrição será removida automaticamente %1$s dias após a última redefinição de senha da conta, ou %2$s dias caso a conta não tenha sido usada por muito tempo. Apenas o processo de redefinição de senha por tê-la esquecido implica nesta restrição. Alterá-la por si só não implica em restrições. O Suporte Steam não pode remover quaisquer restrições.`,
  _ = `A senha da sua conta Steam foi redefinida recentemente. Para ajudar a proteger usuários que podem ter tido a sua conta de e-mail comprometida, acesso ao Mercado da Comunidade por será restrito por %1$s dias após uma redefinição de senha.`,
  _ = `Você adicionou fundos à sua Carteira Steam recentemente com um cartão de crédito não verificado cujo uso aumentou nos últimos dias. Você pode tentar <1>verificar os fundos agora</1> ou aguardar a remoção automática da restrição.

OBS.: a verificação de fundos pode não funcionar com todos os bancos ou cartões de crédito. Caso não consiga verificar o seu cartão, você precisará esperar até que a forma de pagamento seja verificada pelo Steam. O Suporte Steam não pode fornecer ou converter os valores de verificação, nem remover tal restrição.`,
  _ = `Você adicionou fundos à sua Carteira Steam recentemente com PayPal ou uma forma de pagamento não verificada cujo uso aumentou nos últimos dias. Você não poderá usar o Mercado por alguns dias enquanto os fundos são verificados.`,
  _ = `Você adicionou fundos à sua Carteira Steam recentemente usando uma nova conta PayPal ou uma forma de pagamento cujo uso aumentou nos últimos dias. Você não poderá usar o Mercado por alguns dias enquanto os fundos são verificados.`,
  _ = `Você aceitou um vale-presente digital de um amigo recentemente.`,
  _ = `Você aceitou um vale-presente digital de um amigo recentemente. Não será possível usar o Mercado da Comunidade Steam nos primeiros %1$s dias após a compra do vale-presente.`,
  _ = `O Steam está tendo problemas com os cookies do seu navegador.`,
  _ = `O seu cookie parece ser inválido. Tente finalizar a sessão no Steam e iniciá-la novamente. Além disso, verifique se os cookies estão ativados no seu navegador e que não há extensões interferindo com o cookie do Steam.`,
  _ = `O seu navegador pode estar com cookies desativados. Verifique se todos os cookies são permitidos pelo seu navegador e, então, tente finalizar a sessão e iniciá-la novamente.`,
  _ = `Você está acessando o Mercado de um dispositivo não protegido pelo Steam Guard por %1$s dias.`,
  _ = `Caso tenha um dispositivo já verificado, você poderá usar o Mercado no mesmo. Caso contrário, você precisará aguardar até que verifiquemos este dispositivo para usar o Mercado.`,
  _ = `Você iniciou a sessão em um novo dispositivo ou navegador. Para proteger os itens no seu inventário, você não poderá usar o Mercado neste dispositivo por %1$s dias.`,
  _ = `Você reembolsou uma transação para a sua Carteira Steam recentemente.`,
  _ = `Você não poderá usar o Mercado nos %1$s dias seguintes ao seu autorrembolso mais recente. O Suporte Steam não pode remover quaisquer restrições.`,
  _ = `Você recentemente reembolsou uma transação em troca de créditos da Carteira Steam. Você não poderá usar o Mercado nos %1$s dias seguintes ao seu autorrembolso mais recente.`,
  _ = `A sua conta é limitada.`,
  _ = `A sua conta é limitada e não tem acesso a certos recursos do Steam, incluindo o Mercado da Comunidade.`,
  _ = `A sua conta é limitada e não tem acesso a certos recursos do Steam, incluindo o Mercado da Comunidade.`,
  _ = `Você redefiniu ou ativou o Steam Guard recentemente e poderá usar o Mercado %1$s dias após a ativação do Steam Guard.`,
  _ = `Você precisa aguardar até que o Steam Guard esteja ativado na sua conta por 15 dias. O Suporte Steam não pode remover tal restrição.`,
  _ = `A sua conta precisa estar protegida pelo Steam Guard por pelo menos %1$s dias.`,
  _ = `Ative o Steam Guard na sua conta. Confirme que o seu endereço de e-mail foi verificado e você já tenha iniciado a sessão com a sua conta após a ativação do Steam Guard.`,
  _ = `A sua conta precisa estar protegida pelo Steam Guard por pelo menos %1$s dias.`,
  _ = `Caso não haja mais nada que restrinja o seu acesso, você poderá usar o Mercado da Comunidade em %1$s`,
  _ = `A sua conta está suspensa temporariamente de trocar e usar o Mercado.`,
  _ = {
    AdvancedSearch_Heading: _,
    AdvancedSearch_Reset: _,
    AdvancedSearch_Search: _,
    AdvancedSearch_AppSelect_Placeholder: _,
    AdvancedSearch_AppSelect_YourGames: _,
    AdvancedSearch_AppSelect_PopularGames: _,
    AdvancedSearch_AppSelect_Clear: _,
    AdvancedSearch_TextSearch_Placeholder: _,
    AdvancedSearch_TextSearch_PlaceholderWithApp: _,
    AdvancedSearch_TypeSwitch_InGame: _,
    AdvancedSearch_TypeSwitch_SteamItems: _,
    AdvancedSearch_SteamItems_TypeLabel: _,
    AdvancedSearch_NoFacets: _,
    AdvancedSearch_NoFacetsSearch: _,
    AdvancedSearch_FacetLoadError: _,
    AdvancedSearch_PriceFieldLabel: _,
    AdvancedSearch_MinPricePlaceholder: _,
    AdvancedSearch_MaxPricePlaceholder: _,
    AdvancedSearch_CustomFilter_All: _,
    AdvancedSearch_CustomFilter_Other: _,
    AdvancedSearch_FilterGeneric_Placeholder: _,
    AdvancedSearch_AppSelect_FilterPlaceholder: _,
    AdvancedSearch_BetaTag: _,
    AdvancedSearch_TextSearch_Tooltip: _,
    AdvancedSearch_CSContainers_Tooltip: _,
    Header_MarketTitle: _,
    Header_MarketDescription: _,
    Header_LearnMore: _,
    Header_Search_Placeholder: _,
    Header_Search_PlaceholderNew: _,
    Header_Search_Filters: _,
    Header_OptOut: _,
    Header_GiveFeedback: _,
    CommodityExplanation: _,
    Search_AmountFound: _,
    Search_AmountFound_Plural: _,
    Search_AmountFoundFor: _,
    Search_AmountFoundFor_Plural: _,
    Search_ResultsFoundFor: _,
    Search_ListingsFound: _,
    Search_ListingsFound_Plural: _,
    SortBy_Popularity: _,
    SortBy_Name_Asc: _,
    SortBy_Name_Desc: _,
    SortBy_Price_Asc: _,
    SortBy_Price_Desc: _,
    SortBy_Quantity_Asc: _,
    SortBy_Quantity_Desc: _,
    SortBy_AssetProperty_Asc: _,
    SortBy_AssetProperty_Desc: _,
    SortBy_Label: _,
    Search_Button: _,
    Search_Placeholder: _,
    Button_Buy: _,
    Button_Sell: _,
    Button_BuyNow: _,
    Button_BuyOrder: _,
    BuyOrder_PlaceOrderHeader: _,
    Button_Close: _,
    Search_ListingQuantity: _,
    Search_ListingQuantity_Abbreviation: _,
    Bucket_PriceFrom: _,
    AccessorySearch_AttachedAccessoryType: _,
    FilterResults_Placeholder: _,
    AdvancedSearch_Header: _,
    AdvancedSearch_Link: _,
    MarketSearch_Placeholder: _,
    Breadcrumbs_Home: _,
    MarketHome_PopularApps: _,
    AdvancedSearch_IncludeDescriptions: _,
    AdvancedSearch_IncludeDescriptions_Tooltip: _,
    MarketSearch_FilterColumn_Header: _,
    MarketSearch_Reset: _,
    Listings_TextFilter_Placeholder: _,
    Economy_Market_Purchase_Restrictions: _,
    Economy_Market_Purchase_TradableRestriction_1Day: _,
    Economy_Market_Purchase_TradableRestriction_7Days: _,
    Economy_Market_Purchase_TradableRestriction_NDays: _,
    Economy_Market_Purchase_TradableRestriction_Permanent: _,
    Economy_Market_Purchase_MarketableRestriction_1Day: _,
    Economy_Market_Purchase_MarketableRestriction_7Days: _,
    Economy_Market_Purchase_MarketableRestriction_NDays: _,
    Economy_Market_Purchase_MarketableRestriction_None: _,
    AssetPropertyNumberFilterRange: _,
    AssetPropertyStringFilter: _,
    PurchaseDialog_Header: _,
    PurchaseDialog_Details_Column_Name: _,
    PurchaseDialog_Details_Column_Price: _,
    PurchaseDialog_Subtotal_Label: _,
    PurchaseDialog_PublisherFee_Label: _,
    PurchaseDialog_PublisherFee_Label_Generic: _,
    PurchaseDialog_SteamFee_Label: _,
    PurchaseDialog_LocalTax_Label: _,
    PurchaseDialog_Total_Label: _,
    PurchaseDialog_PaymentMethod_Label: _,
    PurchaseDialog_PaymentMethod_Wallet: _,
    PurchaseDialog_SteamAccount_Label: _,
    PurchaseDialog_BillingInfo_Label: _,
    PurchaseDialog_BillingInfo_FirstName: _,
    PurchaseDialog_BillingInfo_LastName: _,
    PurchaseDialog_BillingInfo_Address: _,
    PurchaseDialog_BillingInfo_AddressLine2: _,
    PurchaseDialog_BillingInfo_City: _,
    PurchaseDialog_BillingInfo_StateProvince: _,
    PurchaseDialog_BillingInfo_ZipPostal: _,
    PurchaseDialog_BillingInfo_Country: _,
    PurchaseDialog_BillingInfo_SaveInfo: _,
    PurchaseDialog_Action_AddFunds: _,
    PurchaseDialog_Action_Purchase: _,
    PurchaseDialog_SSA_Link: _,
    PurchaseDialog_SSA_Link_Title: _,
    PurchaseDialog_SSA_Fail: _,
    PurchaseDialog_EU_SSA: _,
    PurchaseDialog_Error_ServerGeneric: _,
    PurchaseDialog_Error_NoConfirmation: _,
    PurchaseDialog_Error_MissingRequired: _,
    PurchaseDialog_Error_InvalidMilitaryCity: _,
    PurchaseDialog_Error_InvalidPostal: _,
    PurchaseDialog_PurchaseComplete: _,
    PurchaseDialog_Button_ViewInventory: _,
    PurchaseDialog_Confirmation_Title: _,
    PurchaseDialog_Confirmation_Title_Wait: _,
    PurchaseDialog_Confirmation_Body_Mobile: _,
    PurchaseDialog_Confirmation_Body_Email: _,
    PurchaseDialog_Confirmation_Body_Unknown: _,
    PurchaseDialog_Confirmation_Description_Mobile: _,
    PurchaseDialog_Confirmation_Description_Email: _,
    PurchaseDialog_Confirmation_Description_Unknown: _,
    PurchaseDialog_Purchase_Successful: _,
    PurchaseDialog_Close: _,
    PurchaseDialog_ViewInventory: _,
    PurhcaseDialog_SaveMyAddress: _,
    Listing_NotAvailable: _,
    Listing_NotAvailable_Short: _,
    Listing_NotAvailable_Long: _,
    Listing_MyListing: _,
    BuyOrderDialog_Header: _,
    BuyOrderDialog_Header_NoItem: _,
    BuyOrderDialog_BucketPicker_Label: _,
    BuyOrderDialog_BucketPicker_Placeholder: _,
    BuyOrderDialog_PriceField: _,
    BuyOrderDialog_PriceField_Suffix: _,
    BuyOrderDialog_QuantityField: _,
    BuyOrderDialog_MaxPrice: _,
    BuyOrderDialog_MaxPrice_Tip: _,
    BuyOrderDialog_Status_Pending: _,
    BuyOrderDialog_Status_Filled: _,
    BuyOrderDialog_Status_Settled: _,
    BuyOrderDialog_Status_Settled_Note: _,
    BuyOrderDialog_Status_GenericError: _,
    BuyOrderDialog_MinPriceError: _,
    OrderBook_Table_PriceOrLess: _,
    OrderBook_Table_PriceOrMore: _,
    OrderBook_Table_Price: _,
    OrderBook_Table_Quantity: _,
    OrderBook_SellOrder_Description: _,
    OrderBook_SellOrder_Description_None: _,
    OrderBook_BuyOrder_Description: _,
    OrderBook_BuyOrder_Description_None: _,
    OrderBook_BuyOrder_NeedBucket: _,
    OrderBook_BuyOrder_Explanation_Unique: _,
    OrderBook_BuyOrder_Explanation_Commodity: _,
    OrderBook_Graph_Title: _,
    OrderBook_Graph_BuyTooltip: _,
    OrderBook_Graph_BuyTooltip_Plural: _,
    OrderBook_Graph_SellTooltip: _,
    OrderBook_Graph_SellTooltip_Plural: _,
    OrderBook_PlaceOrder_BuyRequests: _,
    OrderBook_PlaceOrder_BuyRequests_Plural: _,
    MedianSalePrice_Graph_Title: _,
    Graph_TimeScale_Week: _,
    Graph_TimeScale_Month: _,
    Graph_TimeScale_Year: `Ano`,
    Graph_TimeScale_Lifetime: _,
    Graph_NumberSold: _,
    Graph_Label_Price: _,
    Graph_Label_Volume: _,
    Graph_NoData: _,
    Graph_Tooltip_NoPurchaseData: _,
    Graph_Tooltip_NA: `N/D`,
    MyOrders_GridHeader_Name: _,
    MyOrders_GridHeader_Price: _,
    MyOrders_GridHeader_Quantity: _,
    MyOrders_GridHeader_DateListed: _,
    MyOrders_Cancel: _,
    MyOrders_Remove: _,
    MyOrders_Heading: _,
    MyOrders_Heading_Sell: _,
    MyOrders_Heading_Buy: _,
    MyOrders_Heading_MyPurchaseOffers: _,
    MyOrders_Heading_MyListings: _,
    MyOrders_FailedToLoad: _,
    MyOrders_NoActiveOrders_Item: _,
    MyOrders_NoBuyOrders_Item: _,
    MyOrders_NoSellOrders_Item: _,
    MyOrders_QuantityWithValue: _,
    MyOrders_SeeAllN: _,
    CancelBuyOrder_GenericError: _,
    CancelListing_GenericError: _,
    CancelListing_Dialog_Header: _,
    CancelListing_Dialog_Prompt: _,
    CancelListing_Dialog_Prompt_Generic: _,
    CancelListing_Dialog_Yes: _,
    CancelListing_Dialog_No: _,
    CancelListing_Dialog_Success: _,
    SellDialog_Frame_Title: _,
    UniqueBuyOrder_Explanation_Header: _,
    UniqueBuyOrder_Explanation_1: _,
    UniqueBuyOrder_Explanation_2: _,
    UniqueBuyOrder_Explanation_3: _,
    PriceFilter_ValueAndUp: _,
    Error_Sorry: _,
    Error_Encountered: _,
    Error_TooManyRequests_Description: _,
    Container_ContentsLabel: _,
    Error_LoadingContent: _,
    Error_LoadingMarketItem: _,
    ListingFilter_Title: _,
    Listings_NoneFound: _,
    ItemBucketPicker_Overflow_Placeholder: _,
    ItemBucketPicker_Overflow_FilterPlaceholder: _,
    Mobile_InfoSection: _,
    Mobile_GraphSection: _,
    Mobile_BuyOrderSection: _,
    Mobile_FiltersButton: _,
    AssetProperty_Range_MinPlaceholder: _,
    AssetProperty_Range_MaxPlaceholder: _,
    Accessories_FieldSectionLabel: _,
    Accessories_AnyFilter: _,
    Accessories_NoneFilter: _,
    Accessories_TypeAndValue_Breadcrumb: _,
    Item_CountryBuySellRestricted: _,
    Item_CountryBuyRestricted: _,
    Listing_EnhancedAppearance_Missing: _,
    Listing_EnhancedAppearance_ShowBackground: _,
    Listing_SomethingWentWrong: _,
    Unavailable_Header: _,
    Unavailable_Header_Plural: _,
    Filter_ViewResults: _,
    Results_GridView_Tooltip: _,
    Results_ListView_Tooltip: _,
    Results_PageLoadError: _,
    Market_AppUnplayedAndUnvetted: _,
    Market_AppUnplayedAndUnvetted_Dismiss: _,
    Home_GamePicker_Label: _,
    Home_GamePicker_ViewAll: _,
    Economy_Market_TopLevelReason_AccountLocked: _,
    Economy_Market_TopLevelTooltip_AccountLocked: _,
    Economy_Market_HeaderTip_AccountLocked: _,
    Economy_Market_TopLevelTooltip_RemoveRestrictionLink: _,
    Economy_Market_TopLevelReason_AccountTradeBanned: _,
    Economy_Market_TopLevelReason_Unknown: _,
    Economy_Market_TopLevelTooltip_AccountTradeBanned: _,
    Economy_Market_HeaderTip_AccountTradeBanned: _,
    Economy_Market_TopLevelTooltip_MoreInfoLink: _,
    Economy_Market_TopLevelReason_AccountNotTrusted: _,
    Economy_Market_TopLevelTooltip_AccountNotTrusted: _,
    Economy_Market_HeaderTip_AccountNotTrusted: _,
    Economy_Market_TopLevelReason_AccountNotTrusted_Waiting: _,
    Economy_Market_TTopLevelTooltip_AccountNotTrusted_Waiting: _,
    Economy_Market_TopLevelReason_AccountPasswordRecentlyReset: _,
    Economy_Market_TopLevelTooltip_AccountPasswordRecentlyReset: _,
    Economy_Market_HeaderTip_AccountPasswordRecentlyReset: _,
    Economy_Market_HeaderTip_NewPaymentMethod_NoDate: _,
    Economy_Market_HeaderTip_AccountHasNewPaymentMethod: _,
    Economy_Market_TopLevelReason_AccountHasNewPaymentMethod: _,
    Economy_Market_TopLevelReason_AcceptedWalletGift: _,
    Economy_Market_HeaderTip_AcceptedWalletGift: _,
    Economy_Market_TopLevelReason_InvalidCookie: _,
    Economy_Market_TopLevelTooltip_InvalidCookie: _,
    Economy_Market_HeaderTip_InvalidCookie: _,
    Economy_Market_TopLevelReason_NewDevice: _,
    Economy_Market_TopLevelTooltip_NewDevice: _,
    Economy_Market_HeaderTip_NewDevice: _,
    Economy_Market_TopLevelReason_SelfRefund: _,
    Economy_Market_TopLevelTooltip_SelfRefund: _,
    Economy_Market_HeaderTip_SelfRefund: _,
    Economy_Market_TopLevelReason_LimitedUser: _,
    Economy_Market_TopLevelTooltip_LimitedUser: _,
    Economy_Market_HeaderTip_LimitedUser: _,
    Economy_Market_HeaderTip_SteamGuardOnlyRecentlyEnabled: _,
    Economy_Market_TopLevelTooltip_SteamGuardRecentlyEnabled: _,
    Economy_Market_TopLevelReason_NoSteamGuard: _,
    Economy_Market_TopLevelTooltip_SteamGuardDisabled: _,
    Economy_Market_HeaderTip_NoSteamGuard: _,
    Economy_Market_HeaderTip_TimeCanUse: _,
    Economy_Market_TopLevelReason_TradeCooldown: _,
  };
export {
  _ as Accessories_AnyFilter,
  _ as Accessories_FieldSectionLabel,
  _ as Accessories_NoneFilter,
  _ as Accessories_TypeAndValue_Breadcrumb,
  _ as AccessorySearch_AttachedAccessoryType,
  _ as AdvancedSearch_AppSelect_Clear,
  _ as AdvancedSearch_AppSelect_FilterPlaceholder,
  _ as AdvancedSearch_AppSelect_Placeholder,
  _ as AdvancedSearch_AppSelect_PopularGames,
  _ as AdvancedSearch_AppSelect_YourGames,
  _ as AdvancedSearch_BetaTag,
  _ as AdvancedSearch_CSContainers_Tooltip,
  _ as AdvancedSearch_CustomFilter_All,
  _ as AdvancedSearch_CustomFilter_Other,
  _ as AdvancedSearch_FacetLoadError,
  _ as AdvancedSearch_FilterGeneric_Placeholder,
  _ as AdvancedSearch_Header,
  _ as AdvancedSearch_Heading,
  _ as AdvancedSearch_IncludeDescriptions,
  _ as AdvancedSearch_IncludeDescriptions_Tooltip,
  _ as AdvancedSearch_Link,
  _ as AdvancedSearch_MaxPricePlaceholder,
  _ as AdvancedSearch_MinPricePlaceholder,
  _ as AdvancedSearch_NoFacets,
  _ as AdvancedSearch_NoFacetsSearch,
  _ as AdvancedSearch_PriceFieldLabel,
  _ as AdvancedSearch_Reset,
  _ as AdvancedSearch_Search,
  _ as AdvancedSearch_SteamItems_TypeLabel,
  _ as AdvancedSearch_TextSearch_Placeholder,
  _ as AdvancedSearch_TextSearch_PlaceholderWithApp,
  _ as AdvancedSearch_TextSearch_Tooltip,
  _ as AdvancedSearch_TypeSwitch_InGame,
  _ as AdvancedSearch_TypeSwitch_SteamItems,
  _ as AssetPropertyNumberFilterRange,
  _ as AssetPropertyStringFilter,
  _ as AssetProperty_Range_MaxPlaceholder,
  _ as AssetProperty_Range_MinPlaceholder,
  _ as Breadcrumbs_Home,
  _ as Bucket_PriceFrom,
  _ as Button_Buy,
  _ as Button_BuyNow,
  _ as Button_BuyOrder,
  _ as Button_Close,
  _ as Button_Sell,
  _ as BuyOrderDialog_BucketPicker_Label,
  _ as BuyOrderDialog_BucketPicker_Placeholder,
  _ as BuyOrderDialog_Header,
  _ as BuyOrderDialog_Header_NoItem,
  _ as BuyOrderDialog_MaxPrice,
  _ as BuyOrderDialog_MaxPrice_Tip,
  _ as BuyOrderDialog_MinPriceError,
  _ as BuyOrderDialog_PriceField,
  _ as BuyOrderDialog_PriceField_Suffix,
  _ as BuyOrderDialog_QuantityField,
  _ as BuyOrderDialog_Status_Filled,
  _ as BuyOrderDialog_Status_GenericError,
  _ as BuyOrderDialog_Status_Pending,
  _ as BuyOrderDialog_Status_Settled,
  _ as BuyOrderDialog_Status_Settled_Note,
  _ as BuyOrder_PlaceOrderHeader,
  _ as CancelBuyOrder_GenericError,
  _ as CancelListing_Dialog_Header,
  _ as CancelListing_Dialog_No,
  _ as CancelListing_Dialog_Prompt,
  _ as CancelListing_Dialog_Prompt_Generic,
  _ as CancelListing_Dialog_Success,
  _ as CancelListing_Dialog_Yes,
  _ as CancelListing_GenericError,
  _ as CommodityExplanation,
  _ as Container_ContentsLabel,
  _ as Economy_Market_HeaderTip_AcceptedWalletGift,
  _ as Economy_Market_HeaderTip_AccountHasNewPaymentMethod,
  _ as Economy_Market_HeaderTip_AccountLocked,
  _ as Economy_Market_HeaderTip_AccountNotTrusted,
  _ as Economy_Market_HeaderTip_AccountPasswordRecentlyReset,
  _ as Economy_Market_HeaderTip_AccountTradeBanned,
  _ as Economy_Market_HeaderTip_InvalidCookie,
  _ as Economy_Market_HeaderTip_LimitedUser,
  _ as Economy_Market_HeaderTip_NewDevice,
  _ as Economy_Market_HeaderTip_NewPaymentMethod_NoDate,
  _ as Economy_Market_HeaderTip_NoSteamGuard,
  _ as Economy_Market_HeaderTip_SelfRefund,
  _ as Economy_Market_HeaderTip_SteamGuardOnlyRecentlyEnabled,
  _ as Economy_Market_HeaderTip_TimeCanUse,
  _ as Economy_Market_Purchase_MarketableRestriction_1Day,
  _ as Economy_Market_Purchase_MarketableRestriction_7Days,
  _ as Economy_Market_Purchase_MarketableRestriction_NDays,
  _ as Economy_Market_Purchase_MarketableRestriction_None,
  _ as Economy_Market_Purchase_Restrictions,
  _ as Economy_Market_Purchase_TradableRestriction_1Day,
  _ as Economy_Market_Purchase_TradableRestriction_7Days,
  _ as Economy_Market_Purchase_TradableRestriction_NDays,
  _ as Economy_Market_Purchase_TradableRestriction_Permanent,
  _ as Economy_Market_TTopLevelTooltip_AccountNotTrusted_Waiting,
  _ as Economy_Market_TopLevelReason_AcceptedWalletGift,
  _ as Economy_Market_TopLevelReason_AccountHasNewPaymentMethod,
  _ as Economy_Market_TopLevelReason_AccountLocked,
  _ as Economy_Market_TopLevelReason_AccountNotTrusted,
  _ as Economy_Market_TopLevelReason_AccountNotTrusted_Waiting,
  _ as Economy_Market_TopLevelReason_AccountPasswordRecentlyReset,
  _ as Economy_Market_TopLevelReason_AccountTradeBanned,
  _ as Economy_Market_TopLevelReason_InvalidCookie,
  _ as Economy_Market_TopLevelReason_LimitedUser,
  _ as Economy_Market_TopLevelReason_NewDevice,
  _ as Economy_Market_TopLevelReason_NoSteamGuard,
  _ as Economy_Market_TopLevelReason_SelfRefund,
  _ as Economy_Market_TopLevelReason_TradeCooldown,
  _ as Economy_Market_TopLevelReason_Unknown,
  _ as Economy_Market_TopLevelTooltip_AccountLocked,
  _ as Economy_Market_TopLevelTooltip_AccountNotTrusted,
  _ as Economy_Market_TopLevelTooltip_AccountPasswordRecentlyReset,
  _ as Economy_Market_TopLevelTooltip_AccountTradeBanned,
  _ as Economy_Market_TopLevelTooltip_InvalidCookie,
  _ as Economy_Market_TopLevelTooltip_LimitedUser,
  _ as Economy_Market_TopLevelTooltip_MoreInfoLink,
  _ as Economy_Market_TopLevelTooltip_NewDevice,
  _ as Economy_Market_TopLevelTooltip_RemoveRestrictionLink,
  _ as Economy_Market_TopLevelTooltip_SelfRefund,
  _ as Economy_Market_TopLevelTooltip_SteamGuardDisabled,
  _ as Economy_Market_TopLevelTooltip_SteamGuardRecentlyEnabled,
  _ as Error_Encountered,
  _ as Error_LoadingContent,
  _ as Error_LoadingMarketItem,
  _ as Error_Sorry,
  _ as Error_TooManyRequests_Description,
  _ as FilterResults_Placeholder,
  _ as Filter_ViewResults,
  _ as Graph_Label_Price,
  _ as Graph_Label_Volume,
  _ as Graph_NoData,
  _ as Graph_NumberSold,
  _ as Graph_TimeScale_Lifetime,
  _ as Graph_TimeScale_Month,
  _ as Graph_TimeScale_Week,
  _ as Graph_TimeScale_Year,
  _ as Graph_Tooltip_NA,
  _ as Graph_Tooltip_NoPurchaseData,
  _ as Header_GiveFeedback,
  _ as Header_LearnMore,
  _ as Header_MarketDescription,
  _ as Header_MarketTitle,
  _ as Header_OptOut,
  _ as Header_Search_Filters,
  _ as Header_Search_Placeholder,
  _ as Header_Search_PlaceholderNew,
  _ as Home_GamePicker_Label,
  _ as Home_GamePicker_ViewAll,
  _ as ItemBucketPicker_Overflow_FilterPlaceholder,
  _ as ItemBucketPicker_Overflow_Placeholder,
  _ as Item_CountryBuyRestricted,
  _ as Item_CountryBuySellRestricted,
  _ as ListingFilter_Title,
  _ as Listing_EnhancedAppearance_Missing,
  _ as Listing_EnhancedAppearance_ShowBackground,
  _ as Listing_MyListing,
  _ as Listing_NotAvailable,
  _ as Listing_NotAvailable_Long,
  _ as Listing_NotAvailable_Short,
  _ as Listing_SomethingWentWrong,
  _ as Listings_NoneFound,
  _ as Listings_TextFilter_Placeholder,
  _ as MarketHome_PopularApps,
  _ as MarketSearch_FilterColumn_Header,
  _ as MarketSearch_Placeholder,
  _ as MarketSearch_Reset,
  _ as Market_AppUnplayedAndUnvetted,
  _ as Market_AppUnplayedAndUnvetted_Dismiss,
  _ as MedianSalePrice_Graph_Title,
  _ as Mobile_BuyOrderSection,
  _ as Mobile_FiltersButton,
  _ as Mobile_GraphSection,
  _ as Mobile_InfoSection,
  _ as MyOrders_Cancel,
  _ as MyOrders_FailedToLoad,
  _ as MyOrders_GridHeader_DateListed,
  _ as MyOrders_GridHeader_Name,
  _ as MyOrders_GridHeader_Price,
  _ as MyOrders_GridHeader_Quantity,
  _ as MyOrders_Heading,
  _ as MyOrders_Heading_Buy,
  _ as MyOrders_Heading_MyListings,
  _ as MyOrders_Heading_MyPurchaseOffers,
  _ as MyOrders_Heading_Sell,
  _ as MyOrders_NoActiveOrders_Item,
  _ as MyOrders_NoBuyOrders_Item,
  _ as MyOrders_NoSellOrders_Item,
  _ as MyOrders_QuantityWithValue,
  _ as MyOrders_Remove,
  _ as MyOrders_SeeAllN,
  _ as OrderBook_BuyOrder_Description,
  _ as OrderBook_BuyOrder_Description_None,
  _ as OrderBook_BuyOrder_Explanation_Commodity,
  _ as OrderBook_BuyOrder_Explanation_Unique,
  _ as OrderBook_BuyOrder_NeedBucket,
  _ as OrderBook_Graph_BuyTooltip,
  _ as OrderBook_Graph_BuyTooltip_Plural,
  _ as OrderBook_Graph_SellTooltip,
  _ as OrderBook_Graph_SellTooltip_Plural,
  _ as OrderBook_Graph_Title,
  _ as OrderBook_PlaceOrder_BuyRequests,
  _ as OrderBook_PlaceOrder_BuyRequests_Plural,
  _ as OrderBook_SellOrder_Description,
  _ as OrderBook_SellOrder_Description_None,
  _ as OrderBook_Table_Price,
  _ as OrderBook_Table_PriceOrLess,
  _ as OrderBook_Table_PriceOrMore,
  _ as OrderBook_Table_Quantity,
  _ as PriceFilter_ValueAndUp,
  _ as PurchaseDialog_Action_AddFunds,
  _ as PurchaseDialog_Action_Purchase,
  _ as PurchaseDialog_BillingInfo_Address,
  _ as PurchaseDialog_BillingInfo_AddressLine2,
  _ as PurchaseDialog_BillingInfo_City,
  _ as PurchaseDialog_BillingInfo_Country,
  _ as PurchaseDialog_BillingInfo_FirstName,
  _ as PurchaseDialog_BillingInfo_Label,
  _ as PurchaseDialog_BillingInfo_LastName,
  _ as PurchaseDialog_BillingInfo_SaveInfo,
  _ as PurchaseDialog_BillingInfo_StateProvince,
  _ as PurchaseDialog_BillingInfo_ZipPostal,
  _ as PurchaseDialog_Button_ViewInventory,
  _ as PurchaseDialog_Close,
  _ as PurchaseDialog_Confirmation_Body_Email,
  _ as PurchaseDialog_Confirmation_Body_Mobile,
  _ as PurchaseDialog_Confirmation_Body_Unknown,
  _ as PurchaseDialog_Confirmation_Description_Email,
  _ as PurchaseDialog_Confirmation_Description_Mobile,
  _ as PurchaseDialog_Confirmation_Description_Unknown,
  _ as PurchaseDialog_Confirmation_Title,
  _ as PurchaseDialog_Confirmation_Title_Wait,
  _ as PurchaseDialog_Details_Column_Name,
  _ as PurchaseDialog_Details_Column_Price,
  _ as PurchaseDialog_EU_SSA,
  _ as PurchaseDialog_Error_InvalidMilitaryCity,
  _ as PurchaseDialog_Error_InvalidPostal,
  _ as PurchaseDialog_Error_MissingRequired,
  _ as PurchaseDialog_Error_NoConfirmation,
  _ as PurchaseDialog_Error_ServerGeneric,
  _ as PurchaseDialog_Header,
  _ as PurchaseDialog_LocalTax_Label,
  _ as PurchaseDialog_PaymentMethod_Label,
  _ as PurchaseDialog_PaymentMethod_Wallet,
  _ as PurchaseDialog_PublisherFee_Label,
  _ as PurchaseDialog_PublisherFee_Label_Generic,
  _ as PurchaseDialog_PurchaseComplete,
  _ as PurchaseDialog_Purchase_Successful,
  _ as PurchaseDialog_SSA_Fail,
  _ as PurchaseDialog_SSA_Link,
  _ as PurchaseDialog_SSA_Link_Title,
  _ as PurchaseDialog_SteamAccount_Label,
  _ as PurchaseDialog_SteamFee_Label,
  _ as PurchaseDialog_Subtotal_Label,
  _ as PurchaseDialog_Total_Label,
  _ as PurchaseDialog_ViewInventory,
  _ as PurhcaseDialog_SaveMyAddress,
  _ as Results_GridView_Tooltip,
  _ as Results_ListView_Tooltip,
  _ as Results_PageLoadError,
  _ as Search_AmountFound,
  _ as Search_AmountFoundFor,
  _ as Search_AmountFoundFor_Plural,
  _ as Search_AmountFound_Plural,
  _ as Search_Button,
  _ as Search_ListingQuantity,
  _ as Search_ListingQuantity_Abbreviation,
  _ as Search_ListingsFound,
  _ as Search_ListingsFound_Plural,
  _ as Search_Placeholder,
  _ as Search_ResultsFoundFor,
  _ as SellDialog_Frame_Title,
  _ as SortBy_AssetProperty_Asc,
  _ as SortBy_AssetProperty_Desc,
  _ as SortBy_Label,
  _ as SortBy_Name_Asc,
  _ as SortBy_Name_Desc,
  _ as SortBy_Popularity,
  _ as SortBy_Price_Asc,
  _ as SortBy_Price_Desc,
  _ as SortBy_Quantity_Asc,
  _ as SortBy_Quantity_Desc,
  _ as Unavailable_Header,
  _ as Unavailable_Header_Plural,
  _ as UniqueBuyOrder_Explanation_1,
  _ as UniqueBuyOrder_Explanation_2,
  _ as UniqueBuyOrder_Explanation_3,
  _ as UniqueBuyOrder_Explanation_Header,
  _ as default,
};
