var _ = `Buscar en el mercado de la comunidad`,
  _ = `Restablecer filtros`,
  _ = `Buscar`,
  _ = `Selecciona un juego...`,
  _ = `Jugados recientemente con artículos`,
  _ = `Juegos populares con artículos`,
  _ = `Borrar selección`,
  _ = `Buscar...`,
  _ = `Buscar en «%1$s»...`,
  _ = `Artículos dentro del juego`,
  _ = `Artículos de Steam`,
  _ = `Tipo de artículo`,
  _ = `Este juego no tiene filtros del mercado.`,
  _ = `Haz clic en «Buscar» para ver los artículos disponibles.`,
  _ = `Se produjo un error al cargar los filtros de este juego.`,
  _ = `Precio`,
  _ = `Precio mínimo`,
  _ = `Precio máximo`,
  _ = `Todo`,
  _ = `Otro`,
  _ = `Filtrar...`,
  _ = `Filtrar por producto...`,
  _ = `Característica en fase beta: danos tu opinión`,
  _ = `Buscar en los nombres de los artículos del mercado...`,
  _ = `Cajas de armas, cápsulas de pegatinas, paquetes de recuerdos, etc.`,
  _ = `Mercado de la comunidad de Steam`,
  _ = `Compra y vende artículos a la comunidad a cambio de fondos de la Cartera de Steam`,
  _ = `Más información`,
  _ = `Buscar en el mercado`,
  _ = `Nueva búsqueda...`,
  _ = `Filtros`,
  _ = `Salir de la beta del mercado`,
  _ = `Enviar comentarios`,
  _ = `Este artículo es una mercancía, donde todos los artículos individuales son idénticos. No puedes acceder a los anuncios individuales, pero sí realizar pedidos para comprar a un precio específico. El anuncio más barato se emparejará automáticamente con el pedido de compra más alto.`,
  _ = `Se encontró %1$s\xA0resultado`,
  _ = `Se encontraron %1$s\xA0resultados`,
  _ = `Se encontró %1$s\xA0resultado para:`,
  _ = `Se encontraron %1$s\xA0resultados para:`,
  _ = `Resultados para:`,
  _ = `Se encontró %2$s\xA0anuncio`,
  _ = `Se encontraron %2$s\xA0anuncios`,
  _ = `Popularidad`,
  _ = `Nombre (de la A a la Z)`,
  _ = `Nombre (de la Z a la A)`,
  _ = `Precio (de menor a mayor)`,
  _ = `Precio (de mayor a menor)`,
  _ = `Cantidad (de menor a mayor)`,
  _ = `Cantidad (de mayor a menor)`,
  _ = `%1$s (de menor a mayor)`,
  _ = `%1$s (de mayor a menor)`,
  _ = `Ordenar por:`,
  _ = `Buscar`,
  _ = `Buscar...`,
  _ = `Comprar`,
  _ = `Vender`,
  _ = `Comprar ahora`,
  _ = `Realizar pedido de compra...`,
  _ = `Realizar un pedido:`,
  _ = `Cerrar`,
  _ = `Cantidad a la venta: %1$s`,
  _ = `Cantidad: %1$s`,
  _ = `A partir de %1$s`,
  _ = `%1$s — Conectado`,
  _ = `Filtrar resultados...`,
  _ = `Búsqueda avanzada`,
  _ = `Búsqueda avanzada`,
  _ = `Buscar un artículo...`,
  _ = `Página principal del mercado`,
  _ = `Juegos populares`,
  _ = `Incluir descripciones en la búsqueda`,
  _ = `Algunos artículos más antiguos utilizan descripciones de texto para indicar propiedades importantes que no pueden filtrarse con las opciones de abajo. Esta opción permite que tu búsqueda coincida con todo el texto de la descripción, en lugar de hacerlo solo con el nombre del artículo.`,
  _ = `Filtros`,
  _ = `Restablecer búsqueda`,
  _ = `Escribe un texto personalizado para filtrar...`,
  _ = `Después de la compra, este artículo:`,
  _ = `no será intercambiable durante un día`,
  _ = `no será intercambiable durante una semana`,
  _ = `no será intercambiable durante %1$s\xA0días`,
  _ = `no será intercambiable`,
  _ = `no se podrá anunciar en el mercado de la comunidad durante un día`,
  _ = `no se podrá anunciar en el mercado de la comunidad durante una semana`,
  _ = `no se podrá anunciar en el mercado de la comunidad durante %1$s\xA0días`,
  _ = `puede volver a venderse de inmediato en el mercado de la comunidad de Steam`,
  _ = `%1$s: %2$s - %3$s`,
  _ = `%1$s: «%2$s»`,
  _ = `Comprar un artículo`,
  _ = `Nombre`,
  _ = `Precio`,
  _ = `Subtotal:`,
  _ = `Tasa de %1$s (%2$s\xA0%):`,
  _ = `Tasa del juego (%1$s\xA0%):`,
  _ = `Tasa de transacción de Steam (%1$s\xA0%):`,
  _ = `Impuesto local sobre las ventas (%1$s):`,
  _ = `Total:`,
  _ = `Método de pago:`,
  _ = `Mi Cartera de Steam`,
  _ = `Cuenta de Steam:`,
  _ = `Dirección de facturación:`,
  _ = `Nombre`,
  _ = `Apellidos`,
  _ = `Dirección de facturación`,
  _ = `Dirección de facturación (segunda línea)`,
  _ = `Localidad`,
  _ = `Estado o provincia`,
  _ = `Código postal`,
  _ = `País`,
  _ = `Guardar mi dirección para facilitar la compra la próxima vez`,
  _ = `Añadir fondos`,
  _ = `Comprar`,
  _ = `Acepto las condiciones del %1$s (última actualización: %2$s).`,
  _ = `Acuerdo de Suscriptor a Steam`,
  _ = `Para completar la transacción, es necesario aceptar las condiciones del Acuerdo de Suscriptor a Steam.`,
  _ = `Al hacer clic en «Comprar» aceptas recibir acceso inmediato a este contenido digital y que, por lo tanto, termina cualquier posibilidad de anular la compra resultante; es decir, la compra es final.`,
  _ = `Ha habido un problema al comprar el artículo. Puede que hayan eliminado el anuncio. Actualiza la página e inténtalo de nuevo.`,
  _ = `Ha habido un problema al comprar el artículo. Se ha producido un error al esperar a que confirmaras esta acción. Actualiza la página e inténtalo de nuevo.`,
  _ = `Los siguientes campos son obligatorios:`,
  _ = `Por favor, introduce una dirección militar válida`,
  _ = `Introduce un código postal válido`,
  _ = `¡Enhorabuena por la compra! Puedes ver tu nuevo artículo en el <1>inventario</1>.`,
  _ = `Ver inventario`,
  _ = `Se requiere una confirmación adicional`,
  _ = `A la espera de que confirmes esta compra...`,
  _ = `Algunas compras requieren seguridad adicional a través de la aplicación Steam\xA0Mobile.`,
  _ = `Algunas compras requieren seguridad adicional a través del correo electrónico de Steam\xA0Guard.`,
  _ = `Algunas compras requieren seguridad adicional a través de la aplicación Steam\xA0Mobile o correo electrónico.`,
  _ = `Confirma mediante la aplicación Steam\xA0Mobile para completar la compra...`,
  _ = `Confirma mediante correo electrónico para completar la compra...`,
  _ = `Confirma mediante la aplicación Steam\xA0Mobile o correo electrónico para completar la compra...`,
  _ = `La compra se ha completado con éxito`,
  _ = `Cerrar`,
  _ = `Ver inventario`,
  _ = `Guardar mi dirección para agilizar la compra la próxima vez`,
  _ = `Este anuncio ya no está disponible`,
  _ = `No disponible`,
  _ = `Este anuncio ya no está disponible para su compra.`,
  _ = `(Mi anuncio)`,
  _ = `Comprar %1$s`,
  _ = `Realizar pedido de compra`,
  _ = `¿Qué tipo de artículo quieres comprar?`,
  _ = `Seleccionar un artículo...`,
  _ = `Qué precio quieres pagar:`,
  _ = `(por artículo)`,
  _ = `Cuántos quieres comprar:`,
  _ = `Precio máximo %1$s:`,
  _ = `Esto es lo máximo que puedes gastar como resultado de este pedido de compra. Los artículos se comprarán al precio más barato disponible, por lo que el pedido puede acabar costando menos que esta cantidad.`,
  _ = `Buscando anuncios de artículos que coincidan con el precio deseado...`,
  _ = `¡Compra realizada con éxito! El artículo ya está en tu inventario y hemos enviado un recibo a tu dirección de correo electrónico.`,
  _ = `¡Listo! Se ha realizado tu pedido de compra.`,
  _ = `Se te notificará automáticamente por correo electrónico cuando la compra se complete. Puedes cancelar este pedido en la parte superior de esta página o desde la página principal del mercado.`,
  _ = `¡Lo sentimos! Hemos tenido problemas para recibir respuesta de los servidores de Steam sobre tu pedido. Comprueba que este se haya creado o completado. Si no es así, inténtalo de nuevo más tarde.`,
  _ = `El precio mínimo por unidad es %1$s`,
  _ = `%1$s o menos`,
  _ = `%1$s o más`,
  _ = `Precio`,
  _ = `Cantidad`,
  _ = `%1$s\xA0a la venta a partir de %2$s`,
  _ = `No existen anuncios activos para este artículo`,
  _ = `%1$s\xA0pedidos de compra a %2$s o menos`,
  _ = `No existen pedidos de compra activos para este artículo.`,
  _ = `Selecciona una pestaña de arriba para ver la información del pedido de compra`,
  _ = `¿No ves el artículo o el precio que quieres?`,
  _ = `¿No ves un precio que te guste?`,
  _ = `Pedidos de compra y anuncios de venta (acumulativo)`,
  _ = `1\xA0pedido de compra a %2$s o más`,
  _ = `%1$s\xA0pedidos de compra a %2$s o más`,
  _ = `1\xA0anuncio de venta a %2$s o menos`,
  _ = `%1$s\xA0anuncios de venta a %2$s o menos`,
  _ = `1\xA0solicitud para comprar por <1>%2$s</1>`,
  _ = `%3$s\xA0pedidos de compra a <1>%2$s o menos</1>`,
  _ = `Medianas de los precios de venta`,
  _ = `Semana`,
  _ = `Mes`,
  _ = `Año`,
  _ = `General`,
  _ = `%1$s\xA0vendido(s)`,
  _ = `Precio`,
  _ = `Volumen`,
  _ = `No hay datos para este intervalo de tiempo.`,
  _ = `No hay datos de compra`,
  _ = `No disponible`,
  _ = `NOMBRE`,
  _ = `PRECIO`,
  _ = `CANTIDAD`,
  _ = `PUBLICADO EL`,
  _ = `Cancelar`,
  _ = `Eliminar`,
  _ = `Mis pedidos activos`,
  _ = `Anuncios de venta`,
  _ = `Pedidos de compra`,
  _ = `Compras - Mis ofertas`,
  _ = `Ventas - Mis anuncios`,
  _ = `Hubo un problema al cargar los datos de pedidos para este artículo.`,
  _ = `No tienes pedidos activos para este artículo.`,
  _ = `No tienes pedidos de compra activos para este artículo.`,
  _ = `No tienes a la venta ningún ejemplar de este artículo. Vende artículos desde tu inventario o haz clic en el botón «Vender» de esta página.`,
  _ = `Cantidad: %1$s`,
  _ = `Lista completa (%1$s)`,
  _ = `Ha habido un problema al cancelar tu pedido. Por favor, inténtalo de nuevo más tarde.`,
  _ = `Ha habido un problema al eliminar tu anuncio. Por favor, inténtalo de nuevo más tarde.`,
  _ = `Eliminar un anuncio`,
  _ = `¿Quieres eliminar el anuncio de %1$s y devolver el artículo a tu inventario?`,
  _ = `¿Quieres eliminar este anuncio y devolver el artículo a tu inventario?`,
  _ = `Sí, eliminar este anuncio`,
  _ = `No`,
  _ = `Tu anuncio se eliminó correctamente`,
  _ = `Selecciona un artículo de tu inventario`,
  _ = `¿Qué es un pedido de compra?`,
  _ = `Establece tu precio preferido y la compra se realizará automáticamente cuando el artículo esté disponible a ese precio.`,
  _ = `Steam se asegurará de que obtengas el mejor precio disponible.`,
  _ = `Para este artículo, los pedidos de compra se emparejarán con la opción más barata independientemente de cualquier característica única.`,
  _ = `%1$s y más`,
  _ = `¡Lo sentimos!`,
  _ = `Se ha producido un error mientras se procesaba la solicitud:`,
  _ = `Has realizado demasiadas solicitudes recientemente. Por favor, espera e inténtalo de nuevo más tarde.`,
  _ = `Posibles contenidos:`,
  _ = `Se produjo un problema al cargar este contenido`,
  _ = `Es posible que el artículo solicitado no exista o que haya un problema temporal que impida su carga. Inténtalo de nuevo más tarde.`,
  _ = `Filtrar anuncios`,
  _ = `No se ha encontrado ningún anuncio`,
  _ = `Más opciones...`,
  _ = `Filtrar...`,
  _ = `Información`,
  _ = `Gráfico de ventas`,
  _ = `Pedidos de compra`,
  _ = `Filtros`,
  _ = `Mín.`,
  _ = `Máx.`,
  _ = `Accesorios`,
  _ = `Cualquiera`,
  _ = `Ninguno`,
  _ = `%1$s: %2$s`,
  _ = `No puedes comprar este artículo, porque la compra y venta de este tipo de artículo no está disponible en tu país.`,
  _ = `No puedes comprar este tipo de artículo porque no está disponible en tu país.`,
  _ = `Este anuncio aún no tiene imágenes únicas o mejoradas. La imagen que se muestra aquí puede ser ligeramente diferente del artículo anunciado.`,
  _ = `Mostrar fondo`,
  _ = `Ha habido un problema al tratar de mostrar este anuncio.`,
  _ = `No puedes comprar ni vender artículos en el mercado por el siguiente motivo:`,
  _ = `No puedes comprar ni vender artículos en el mercado por los siguientes motivos:`,
  _ = `Ver resultados`,
  _ = `Ver como cuadrícula`,
  _ = `Ver como lista`,
  _ = `Se ha producido un problema al cargar los resultados adicionales. Vuelve a intentarlo más tarde.`,
  _ = `Estás intentando ver un artículo de un nuevo juego de Steam al que no has jugado nunca. Ten cuidado con dicho artículo.`,
  _ = `Haz clic aquí para ver este artículo de todos modos`,
  _ = `Filtrar por producto`,
  _ = `Ver todos los juegos`,
  _ = `Tu cuenta se encuentra actualmente bloqueada.`,
  _ = `Puedes encontrar más información sobre este bloqueo haciendo clic en la barra roja que aparece en la esquina superior derecha tras haber iniciado sesión en el cliente de Steam. Por favor, contacta con el Soporte de Steam para obtener información adicional.`,
  _ = `Tu cuenta se encuentra actualmente bloqueada. Puedes encontrar más información sobre este bloqueo haciendo clic en la barra roja que aparece en la esquina superior derecha tras haber iniciado sesión en el cliente de Steam.`,
  _ = `Para eliminar esta restricción...`,
  _ = `Tu cuenta tiene bloqueado el intercambio.`,
  _ = `Actualmente esta cuenta no puede utilizar el mercado de la comunidad de Steam.`,
  _ = `La duración del bloqueo del intercambio puede variar de temporal a permanente. Para ver cuándo caduca este bloqueo, haz clic en la barra roja que se muestra en la esquina superior derecha tras haber iniciado sesión en el cliente de Steam.`,
  _ = `Tu cuenta tiene bloqueado el intercambio. Para ver cuándo caduca este bloqueo, haz clic en la barra roja que se muestra en la esquina superior derecha tras haber iniciado sesión en el cliente de Steam.`,
  _ = `Más información...`,
  _ = `Debes haber realizado una compra válida en Steam que tenga entre %1$s\xA0días y un año de antigüedad sin contracargos recientes o disputas de pago.`,
  _ = `Por favor, realiza una compra en la tienda de Steam. El crédito de la Cartera, los juegos y los DLC son compras válidas; las claves de producto y los regalos, no. El Soporte de Steam no puede eliminar esta restricción.`,
  _ = `Debes haber realizado una compra válida en Steam que tenga entre %1$s\xA0días y un año de antigüedad sin contracargos recientes o disputas de pago. El Soporte de Steam no puede eliminar esta restricción.`,
  _ = `Parece que realizaste una compra válida en la tienda de Steam, pero aún no tiene %1$s\xA0días de antigüedad.`,
  _ = `Requerimos una compra de Steam que tenga entre %1$s\xA0días y un año de antigüedad sin contracargos recientes o disputas de pago. Parece que realizaste una compra, pero aún no han pasado los %1$s\xA0días necesarios. El Soporte de Steam no puede eliminar esta restricción.`,
  _ = `La contraseña de tu cuenta se ha restablecido recientemente.`,
  _ = `Esta restricción se eliminará automáticamente a los %1$s\xA0días del último restablecimiento de contraseña. Si la cuenta no se había usado en mucho tiempo, la restricción puede durar hasta %2$s\xA0días. Solo el proceso de restablecimiento aplica esta restricción; cambiar la contraseña de la cuenta no conllevará restricciones. El Soporte de Steam no puede eliminar ninguna restricción.`,
  _ = `La contraseña de tu cuenta de Steam se ha restablecido recientemente. Para ayudar a proteger a los usuarios que hayan podido ver comprometida la seguridad de su cuenta de correo electrónico u otras cuentas, restringimos el acceso al mercado de la comunidad durante %1$s\xA0días tras el restablecimiento de la contraseña.`,
  _ = `Recientemente has añadido fondos a tu Cartera de Steam empleando una tarjeta de crédito no verificada cuya utilización se ha visto incrementada hace poco. Puedes intentar <1>verificar tus fondos ahora</1> o esperar hasta que la restricción se elimine automáticamente.

AVISO: Es posible que la verificación de los fondos no funcione con todos los bancos o tarjetas de crédito. Si no puedes verificar tu tarjeta, entonces debes esperar a que el método de pago sea verificado con Steam. El Soporte de Steam no puede proporcionar o convertir los cargos de verificación, así como tampoco eliminar esta restricción.`,
  _ = `Recientemente has añadido fondos a tu Cartera de Steam empleando PayPal o un método de pago no verificado cuya utilización se ha visto incrementada hace poco. No podrás usar el mercado durante unos días mientras verificamos tus fondos.`,
  _ = `Recientemente has añadido fondos a tu Cartera de Steam empleando una nueva cuenta de PayPal o un método de pago no verificado cuya utilización se ha visto incrementada hace poco. No podrás usar el mercado durante unos días mientras verificamos tus fondos.`,
  _ = `Has aceptado una tarjeta regalo digital de un amigo recientemente.`,
  _ = `Has aceptado una tarjeta regalo digital de un amigo recientemente. No podrás utilizar el mercado de la comunidad durante %1$s\xA0días después de que tu amigo haya comprado la tarjeta.`,
  _ = `Steam está teniendo problemas para utilizar la cookie de tu navegador.`,
  _ = `Tu cookie no parece ser válida. Por favor, prueba a cerrar sesión y luego volver a conectarte a Steam. Asegúrate también de que las cookies de tu navegador se encuentran debidamente habilitadas y que no existen complementos en el navegador que puedan interferir con la cookie de Steam.`,
  _ = `Puede que tu navegador no tenga habilitadas las cookies. Comprueba que tu navegador acepta todas las cookies y prueba a cerrar la sesión y volver a iniciarla.`,
  _ = `Estás iniciando sesión en el mercado desde un dispositivo que no ha sido protegido por Steam\xA0Guard durante %1$s\xA0días.`,
  _ = `Si tienes un dispositivo que ya se haya verificado, aún podrás seguir utilizando el mercado a través de él. De lo contrario deberás esperar a que verifiquemos este dispositivo.`,
  _ = `Has iniciado sesión desde un nuevo dispositivo o navegador web. Con el fin de proteger los artículos de tu inventario, no podrás utilizar el mercado desde este dispositivo durante %1$s\xA0días.`,
  _ = `Has reembolsado recientemente una transacción en tu Cartera de Steam.`,
  _ = `No podrás utilizar el mercado hasta %1$s\xA0días después de tu último reembolso. El Soporte de Steam no puede eliminar ningún tipo de restricción.`,
  _ = `Recientemente has reembolsado una transacción en tu Cartera de Steam. No podrás utilizar el mercado hasta %1$s\xA0días después de tu último reembolso.`,
  _ = `Tu cuenta está limitada.`,
  _ = `Tu cuenta está limitada y no tiene acceso a determinadas características de Steam, entre las que se incluye el mercado de la comunidad.`,
  _ = `Tu cuenta está limitada y no tiene acceso a determinadas características de Steam, entre las que se incluye el mercado de la comunidad.`,
  _ = `Has restablecido o activado Steam\xA0Guard recientemente. Deberás esperar %1$s\xA0días tras la activación de Steam\xA0Guard.`,
  _ = `Debes esperar a que Steam\xA0Guard haya estado activo en tu cuenta durante 15\xA0días. El Soporte de Steam no puede eliminar esta restricción.`,
  _ = `Tu cuenta debe estar protegida por Steam\xA0Guard durante al menos %1$s\xA0días.`,
  _ = `Debes activar Steam\xA0Guard en tu cuenta. Asegúrate de que tu correo electrónico esté verificado y de que has iniciado sesión en tu cuenta un par de veces después de activar Steam\xA0Guard.`,
  _ = `Tu cuenta debe estar protegida por Steam\xA0Guard durante al menos %1$s\xA0días.`,
  _ = `Suponiendo que nada más obligue a restringirte el acceso, podrás usar el mercado de la comunidad el %1$s.`,
  _ = `Tu cuenta está en un período temporal de suspensión de intercambios y de características del mercado.`,
  _ = {
    AdvancedSearch_Heading: _,
    AdvancedSearch_Reset: _,
    AdvancedSearch_Search: _,
    AdvancedSearch_AppSelect_Placeholder: _,
    AdvancedSearch_AppSelect_YourGames: _,
    AdvancedSearch_AppSelect_PopularGames: _,
    AdvancedSearch_AppSelect_Clear: _,
    AdvancedSearch_TextSearch_Placeholder: _,
    AdvancedSearch_TextSearch_PlaceholderWithApp: _,
    AdvancedSearch_TypeSwitch_InGame: _,
    AdvancedSearch_TypeSwitch_SteamItems: _,
    AdvancedSearch_SteamItems_TypeLabel: _,
    AdvancedSearch_NoFacets: _,
    AdvancedSearch_NoFacetsSearch: _,
    AdvancedSearch_FacetLoadError: _,
    AdvancedSearch_PriceFieldLabel: _,
    AdvancedSearch_MinPricePlaceholder: _,
    AdvancedSearch_MaxPricePlaceholder: _,
    AdvancedSearch_CustomFilter_All: _,
    AdvancedSearch_CustomFilter_Other: _,
    AdvancedSearch_FilterGeneric_Placeholder: _,
    AdvancedSearch_AppSelect_FilterPlaceholder: _,
    AdvancedSearch_BetaTag: _,
    AdvancedSearch_TextSearch_Tooltip: _,
    AdvancedSearch_CSContainers_Tooltip: _,
    Header_MarketTitle: _,
    Header_MarketDescription: _,
    Header_LearnMore: _,
    Header_Search_Placeholder: _,
    Header_Search_PlaceholderNew: _,
    Header_Search_Filters: _,
    Header_OptOut: _,
    Header_GiveFeedback: _,
    CommodityExplanation: _,
    Search_AmountFound: _,
    Search_AmountFound_Plural: _,
    Search_AmountFoundFor: _,
    Search_AmountFoundFor_Plural: _,
    Search_ResultsFoundFor: _,
    Search_ListingsFound: _,
    Search_ListingsFound_Plural: _,
    SortBy_Popularity: _,
    SortBy_Name_Asc: _,
    SortBy_Name_Desc: _,
    SortBy_Price_Asc: _,
    SortBy_Price_Desc: _,
    SortBy_Quantity_Asc: _,
    SortBy_Quantity_Desc: _,
    SortBy_AssetProperty_Asc: _,
    SortBy_AssetProperty_Desc: _,
    SortBy_Label: _,
    Search_Button: _,
    Search_Placeholder: _,
    Button_Buy: _,
    Button_Sell: _,
    Button_BuyNow: _,
    Button_BuyOrder: _,
    BuyOrder_PlaceOrderHeader: _,
    Button_Close: _,
    Search_ListingQuantity: _,
    Search_ListingQuantity_Abbreviation: _,
    Bucket_PriceFrom: _,
    AccessorySearch_AttachedAccessoryType: _,
    FilterResults_Placeholder: _,
    AdvancedSearch_Header: _,
    AdvancedSearch_Link: _,
    MarketSearch_Placeholder: _,
    Breadcrumbs_Home: _,
    MarketHome_PopularApps: _,
    AdvancedSearch_IncludeDescriptions: _,
    AdvancedSearch_IncludeDescriptions_Tooltip: _,
    MarketSearch_FilterColumn_Header: _,
    MarketSearch_Reset: _,
    Listings_TextFilter_Placeholder: _,
    Economy_Market_Purchase_Restrictions: _,
    Economy_Market_Purchase_TradableRestriction_1Day: _,
    Economy_Market_Purchase_TradableRestriction_7Days: _,
    Economy_Market_Purchase_TradableRestriction_NDays: _,
    Economy_Market_Purchase_TradableRestriction_Permanent: _,
    Economy_Market_Purchase_MarketableRestriction_1Day: _,
    Economy_Market_Purchase_MarketableRestriction_7Days: _,
    Economy_Market_Purchase_MarketableRestriction_NDays: _,
    Economy_Market_Purchase_MarketableRestriction_None: _,
    AssetPropertyNumberFilterRange: _,
    AssetPropertyStringFilter: _,
    PurchaseDialog_Header: _,
    PurchaseDialog_Details_Column_Name: _,
    PurchaseDialog_Details_Column_Price: _,
    PurchaseDialog_Subtotal_Label: _,
    PurchaseDialog_PublisherFee_Label: _,
    PurchaseDialog_PublisherFee_Label_Generic: _,
    PurchaseDialog_SteamFee_Label: _,
    PurchaseDialog_LocalTax_Label: _,
    PurchaseDialog_Total_Label: _,
    PurchaseDialog_PaymentMethod_Label: _,
    PurchaseDialog_PaymentMethod_Wallet: _,
    PurchaseDialog_SteamAccount_Label: _,
    PurchaseDialog_BillingInfo_Label: _,
    PurchaseDialog_BillingInfo_FirstName: _,
    PurchaseDialog_BillingInfo_LastName: _,
    PurchaseDialog_BillingInfo_Address: _,
    PurchaseDialog_BillingInfo_AddressLine2: _,
    PurchaseDialog_BillingInfo_City: _,
    PurchaseDialog_BillingInfo_StateProvince: _,
    PurchaseDialog_BillingInfo_ZipPostal: _,
    PurchaseDialog_BillingInfo_Country: _,
    PurchaseDialog_BillingInfo_SaveInfo: _,
    PurchaseDialog_Action_AddFunds: _,
    PurchaseDialog_Action_Purchase: _,
    PurchaseDialog_SSA_Link: _,
    PurchaseDialog_SSA_Link_Title: _,
    PurchaseDialog_SSA_Fail: _,
    PurchaseDialog_EU_SSA: _,
    PurchaseDialog_Error_ServerGeneric: _,
    PurchaseDialog_Error_NoConfirmation: _,
    PurchaseDialog_Error_MissingRequired: _,
    PurchaseDialog_Error_InvalidMilitaryCity: _,
    PurchaseDialog_Error_InvalidPostal: _,
    PurchaseDialog_PurchaseComplete: _,
    PurchaseDialog_Button_ViewInventory: _,
    PurchaseDialog_Confirmation_Title: _,
    PurchaseDialog_Confirmation_Title_Wait: _,
    PurchaseDialog_Confirmation_Body_Mobile: _,
    PurchaseDialog_Confirmation_Body_Email: _,
    PurchaseDialog_Confirmation_Body_Unknown: _,
    PurchaseDialog_Confirmation_Description_Mobile: _,
    PurchaseDialog_Confirmation_Description_Email: _,
    PurchaseDialog_Confirmation_Description_Unknown: _,
    PurchaseDialog_Purchase_Successful: _,
    PurchaseDialog_Close: _,
    PurchaseDialog_ViewInventory: _,
    PurhcaseDialog_SaveMyAddress: _,
    Listing_NotAvailable: _,
    Listing_NotAvailable_Short: _,
    Listing_NotAvailable_Long: _,
    Listing_MyListing: _,
    BuyOrderDialog_Header: _,
    BuyOrderDialog_Header_NoItem: _,
    BuyOrderDialog_BucketPicker_Label: _,
    BuyOrderDialog_BucketPicker_Placeholder: _,
    BuyOrderDialog_PriceField: _,
    BuyOrderDialog_PriceField_Suffix: _,
    BuyOrderDialog_QuantityField: _,
    BuyOrderDialog_MaxPrice: _,
    BuyOrderDialog_MaxPrice_Tip: _,
    BuyOrderDialog_Status_Pending: _,
    BuyOrderDialog_Status_Filled: _,
    BuyOrderDialog_Status_Settled: _,
    BuyOrderDialog_Status_Settled_Note: _,
    BuyOrderDialog_Status_GenericError: _,
    BuyOrderDialog_MinPriceError: _,
    OrderBook_Table_PriceOrLess: _,
    OrderBook_Table_PriceOrMore: _,
    OrderBook_Table_Price: _,
    OrderBook_Table_Quantity: _,
    OrderBook_SellOrder_Description: _,
    OrderBook_SellOrder_Description_None: _,
    OrderBook_BuyOrder_Description: _,
    OrderBook_BuyOrder_Description_None: _,
    OrderBook_BuyOrder_NeedBucket: _,
    OrderBook_BuyOrder_Explanation_Unique: _,
    OrderBook_BuyOrder_Explanation_Commodity: _,
    OrderBook_Graph_Title: _,
    OrderBook_Graph_BuyTooltip: _,
    OrderBook_Graph_BuyTooltip_Plural: _,
    OrderBook_Graph_SellTooltip: _,
    OrderBook_Graph_SellTooltip_Plural: _,
    OrderBook_PlaceOrder_BuyRequests: _,
    OrderBook_PlaceOrder_BuyRequests_Plural: _,
    MedianSalePrice_Graph_Title: _,
    Graph_TimeScale_Week: _,
    Graph_TimeScale_Month: `Mes`,
    Graph_TimeScale_Year: _,
    Graph_TimeScale_Lifetime: _,
    Graph_NumberSold: _,
    Graph_Label_Price: _,
    Graph_Label_Volume: _,
    Graph_NoData: _,
    Graph_Tooltip_NoPurchaseData: _,
    Graph_Tooltip_NA: _,
    MyOrders_GridHeader_Name: _,
    MyOrders_GridHeader_Price: _,
    MyOrders_GridHeader_Quantity: _,
    MyOrders_GridHeader_DateListed: _,
    MyOrders_Cancel: _,
    MyOrders_Remove: _,
    MyOrders_Heading: _,
    MyOrders_Heading_Sell: _,
    MyOrders_Heading_Buy: _,
    MyOrders_Heading_MyPurchaseOffers: _,
    MyOrders_Heading_MyListings: _,
    MyOrders_FailedToLoad: _,
    MyOrders_NoActiveOrders_Item: _,
    MyOrders_NoBuyOrders_Item: _,
    MyOrders_NoSellOrders_Item: _,
    MyOrders_QuantityWithValue: _,
    MyOrders_SeeAllN: _,
    CancelBuyOrder_GenericError: _,
    CancelListing_GenericError: _,
    CancelListing_Dialog_Header: _,
    CancelListing_Dialog_Prompt: _,
    CancelListing_Dialog_Prompt_Generic: _,
    CancelListing_Dialog_Yes: _,
    CancelListing_Dialog_No: `No`,
    CancelListing_Dialog_Success: _,
    SellDialog_Frame_Title: _,
    UniqueBuyOrder_Explanation_Header: _,
    UniqueBuyOrder_Explanation_1: _,
    UniqueBuyOrder_Explanation_2: _,
    UniqueBuyOrder_Explanation_3: _,
    PriceFilter_ValueAndUp: _,
    Error_Sorry: _,
    Error_Encountered: _,
    Error_TooManyRequests_Description: _,
    Container_ContentsLabel: _,
    Error_LoadingContent: _,
    Error_LoadingMarketItem: _,
    ListingFilter_Title: _,
    Listings_NoneFound: _,
    ItemBucketPicker_Overflow_Placeholder: _,
    ItemBucketPicker_Overflow_FilterPlaceholder: _,
    Mobile_InfoSection: _,
    Mobile_GraphSection: _,
    Mobile_BuyOrderSection: _,
    Mobile_FiltersButton: _,
    AssetProperty_Range_MinPlaceholder: _,
    AssetProperty_Range_MaxPlaceholder: _,
    Accessories_FieldSectionLabel: _,
    Accessories_AnyFilter: _,
    Accessories_NoneFilter: _,
    Accessories_TypeAndValue_Breadcrumb: _,
    Item_CountryBuySellRestricted: _,
    Item_CountryBuyRestricted: _,
    Listing_EnhancedAppearance_Missing: _,
    Listing_EnhancedAppearance_ShowBackground: _,
    Listing_SomethingWentWrong: _,
    Unavailable_Header: _,
    Unavailable_Header_Plural: _,
    Filter_ViewResults: _,
    Results_GridView_Tooltip: _,
    Results_ListView_Tooltip: _,
    Results_PageLoadError: _,
    Market_AppUnplayedAndUnvetted: _,
    Market_AppUnplayedAndUnvetted_Dismiss: _,
    Home_GamePicker_Label: _,
    Home_GamePicker_ViewAll: _,
    Economy_Market_TopLevelReason_AccountLocked: _,
    Economy_Market_TopLevelTooltip_AccountLocked: _,
    Economy_Market_HeaderTip_AccountLocked: _,
    Economy_Market_TopLevelTooltip_RemoveRestrictionLink: _,
    Economy_Market_TopLevelReason_AccountTradeBanned: _,
    Economy_Market_TopLevelReason_Unknown: _,
    Economy_Market_TopLevelTooltip_AccountTradeBanned: _,
    Economy_Market_HeaderTip_AccountTradeBanned: _,
    Economy_Market_TopLevelTooltip_MoreInfoLink: _,
    Economy_Market_TopLevelReason_AccountNotTrusted: _,
    Economy_Market_TopLevelTooltip_AccountNotTrusted: _,
    Economy_Market_HeaderTip_AccountNotTrusted: _,
    Economy_Market_TopLevelReason_AccountNotTrusted_Waiting: _,
    Economy_Market_TTopLevelTooltip_AccountNotTrusted_Waiting: _,
    Economy_Market_TopLevelReason_AccountPasswordRecentlyReset: _,
    Economy_Market_TopLevelTooltip_AccountPasswordRecentlyReset: _,
    Economy_Market_HeaderTip_AccountPasswordRecentlyReset: _,
    Economy_Market_HeaderTip_NewPaymentMethod_NoDate: _,
    Economy_Market_HeaderTip_AccountHasNewPaymentMethod: _,
    Economy_Market_TopLevelReason_AccountHasNewPaymentMethod: _,
    Economy_Market_TopLevelReason_AcceptedWalletGift: _,
    Economy_Market_HeaderTip_AcceptedWalletGift: _,
    Economy_Market_TopLevelReason_InvalidCookie: _,
    Economy_Market_TopLevelTooltip_InvalidCookie: _,
    Economy_Market_HeaderTip_InvalidCookie: _,
    Economy_Market_TopLevelReason_NewDevice: _,
    Economy_Market_TopLevelTooltip_NewDevice: _,
    Economy_Market_HeaderTip_NewDevice: _,
    Economy_Market_TopLevelReason_SelfRefund: _,
    Economy_Market_TopLevelTooltip_SelfRefund: _,
    Economy_Market_HeaderTip_SelfRefund: _,
    Economy_Market_TopLevelReason_LimitedUser: _,
    Economy_Market_TopLevelTooltip_LimitedUser: _,
    Economy_Market_HeaderTip_LimitedUser: _,
    Economy_Market_HeaderTip_SteamGuardOnlyRecentlyEnabled: _,
    Economy_Market_TopLevelTooltip_SteamGuardRecentlyEnabled: _,
    Economy_Market_TopLevelReason_NoSteamGuard: _,
    Economy_Market_TopLevelTooltip_SteamGuardDisabled: _,
    Economy_Market_HeaderTip_NoSteamGuard: _,
    Economy_Market_HeaderTip_TimeCanUse: _,
    Economy_Market_TopLevelReason_TradeCooldown: _,
  };
export {
  _ as Accessories_AnyFilter,
  _ as Accessories_FieldSectionLabel,
  _ as Accessories_NoneFilter,
  _ as Accessories_TypeAndValue_Breadcrumb,
  _ as AccessorySearch_AttachedAccessoryType,
  _ as AdvancedSearch_AppSelect_Clear,
  _ as AdvancedSearch_AppSelect_FilterPlaceholder,
  _ as AdvancedSearch_AppSelect_Placeholder,
  _ as AdvancedSearch_AppSelect_PopularGames,
  _ as AdvancedSearch_AppSelect_YourGames,
  _ as AdvancedSearch_BetaTag,
  _ as AdvancedSearch_CSContainers_Tooltip,
  _ as AdvancedSearch_CustomFilter_All,
  _ as AdvancedSearch_CustomFilter_Other,
  _ as AdvancedSearch_FacetLoadError,
  _ as AdvancedSearch_FilterGeneric_Placeholder,
  _ as AdvancedSearch_Header,
  _ as AdvancedSearch_Heading,
  _ as AdvancedSearch_IncludeDescriptions,
  _ as AdvancedSearch_IncludeDescriptions_Tooltip,
  _ as AdvancedSearch_Link,
  _ as AdvancedSearch_MaxPricePlaceholder,
  _ as AdvancedSearch_MinPricePlaceholder,
  _ as AdvancedSearch_NoFacets,
  _ as AdvancedSearch_NoFacetsSearch,
  _ as AdvancedSearch_PriceFieldLabel,
  _ as AdvancedSearch_Reset,
  _ as AdvancedSearch_Search,
  _ as AdvancedSearch_SteamItems_TypeLabel,
  _ as AdvancedSearch_TextSearch_Placeholder,
  _ as AdvancedSearch_TextSearch_PlaceholderWithApp,
  _ as AdvancedSearch_TextSearch_Tooltip,
  _ as AdvancedSearch_TypeSwitch_InGame,
  _ as AdvancedSearch_TypeSwitch_SteamItems,
  _ as AssetPropertyNumberFilterRange,
  _ as AssetPropertyStringFilter,
  _ as AssetProperty_Range_MaxPlaceholder,
  _ as AssetProperty_Range_MinPlaceholder,
  _ as Breadcrumbs_Home,
  _ as Bucket_PriceFrom,
  _ as Button_Buy,
  _ as Button_BuyNow,
  _ as Button_BuyOrder,
  _ as Button_Close,
  _ as Button_Sell,
  _ as BuyOrderDialog_BucketPicker_Label,
  _ as BuyOrderDialog_BucketPicker_Placeholder,
  _ as BuyOrderDialog_Header,
  _ as BuyOrderDialog_Header_NoItem,
  _ as BuyOrderDialog_MaxPrice,
  _ as BuyOrderDialog_MaxPrice_Tip,
  _ as BuyOrderDialog_MinPriceError,
  _ as BuyOrderDialog_PriceField,
  _ as BuyOrderDialog_PriceField_Suffix,
  _ as BuyOrderDialog_QuantityField,
  _ as BuyOrderDialog_Status_Filled,
  _ as BuyOrderDialog_Status_GenericError,
  _ as BuyOrderDialog_Status_Pending,
  _ as BuyOrderDialog_Status_Settled,
  _ as BuyOrderDialog_Status_Settled_Note,
  _ as BuyOrder_PlaceOrderHeader,
  _ as CancelBuyOrder_GenericError,
  _ as CancelListing_Dialog_Header,
  _ as CancelListing_Dialog_No,
  _ as CancelListing_Dialog_Prompt,
  _ as CancelListing_Dialog_Prompt_Generic,
  _ as CancelListing_Dialog_Success,
  _ as CancelListing_Dialog_Yes,
  _ as CancelListing_GenericError,
  _ as CommodityExplanation,
  _ as Container_ContentsLabel,
  _ as Economy_Market_HeaderTip_AcceptedWalletGift,
  _ as Economy_Market_HeaderTip_AccountHasNewPaymentMethod,
  _ as Economy_Market_HeaderTip_AccountLocked,
  _ as Economy_Market_HeaderTip_AccountNotTrusted,
  _ as Economy_Market_HeaderTip_AccountPasswordRecentlyReset,
  _ as Economy_Market_HeaderTip_AccountTradeBanned,
  _ as Economy_Market_HeaderTip_InvalidCookie,
  _ as Economy_Market_HeaderTip_LimitedUser,
  _ as Economy_Market_HeaderTip_NewDevice,
  _ as Economy_Market_HeaderTip_NewPaymentMethod_NoDate,
  _ as Economy_Market_HeaderTip_NoSteamGuard,
  _ as Economy_Market_HeaderTip_SelfRefund,
  _ as Economy_Market_HeaderTip_SteamGuardOnlyRecentlyEnabled,
  _ as Economy_Market_HeaderTip_TimeCanUse,
  _ as Economy_Market_Purchase_MarketableRestriction_1Day,
  _ as Economy_Market_Purchase_MarketableRestriction_7Days,
  _ as Economy_Market_Purchase_MarketableRestriction_NDays,
  _ as Economy_Market_Purchase_MarketableRestriction_None,
  _ as Economy_Market_Purchase_Restrictions,
  _ as Economy_Market_Purchase_TradableRestriction_1Day,
  _ as Economy_Market_Purchase_TradableRestriction_7Days,
  _ as Economy_Market_Purchase_TradableRestriction_NDays,
  _ as Economy_Market_Purchase_TradableRestriction_Permanent,
  _ as Economy_Market_TTopLevelTooltip_AccountNotTrusted_Waiting,
  _ as Economy_Market_TopLevelReason_AcceptedWalletGift,
  _ as Economy_Market_TopLevelReason_AccountHasNewPaymentMethod,
  _ as Economy_Market_TopLevelReason_AccountLocked,
  _ as Economy_Market_TopLevelReason_AccountNotTrusted,
  _ as Economy_Market_TopLevelReason_AccountNotTrusted_Waiting,
  _ as Economy_Market_TopLevelReason_AccountPasswordRecentlyReset,
  _ as Economy_Market_TopLevelReason_AccountTradeBanned,
  _ as Economy_Market_TopLevelReason_InvalidCookie,
  _ as Economy_Market_TopLevelReason_LimitedUser,
  _ as Economy_Market_TopLevelReason_NewDevice,
  _ as Economy_Market_TopLevelReason_NoSteamGuard,
  _ as Economy_Market_TopLevelReason_SelfRefund,
  _ as Economy_Market_TopLevelReason_TradeCooldown,
  _ as Economy_Market_TopLevelReason_Unknown,
  _ as Economy_Market_TopLevelTooltip_AccountLocked,
  _ as Economy_Market_TopLevelTooltip_AccountNotTrusted,
  _ as Economy_Market_TopLevelTooltip_AccountPasswordRecentlyReset,
  _ as Economy_Market_TopLevelTooltip_AccountTradeBanned,
  _ as Economy_Market_TopLevelTooltip_InvalidCookie,
  _ as Economy_Market_TopLevelTooltip_LimitedUser,
  _ as Economy_Market_TopLevelTooltip_MoreInfoLink,
  _ as Economy_Market_TopLevelTooltip_NewDevice,
  _ as Economy_Market_TopLevelTooltip_RemoveRestrictionLink,
  _ as Economy_Market_TopLevelTooltip_SelfRefund,
  _ as Economy_Market_TopLevelTooltip_SteamGuardDisabled,
  _ as Economy_Market_TopLevelTooltip_SteamGuardRecentlyEnabled,
  _ as Error_Encountered,
  _ as Error_LoadingContent,
  _ as Error_LoadingMarketItem,
  _ as Error_Sorry,
  _ as Error_TooManyRequests_Description,
  _ as FilterResults_Placeholder,
  _ as Filter_ViewResults,
  _ as Graph_Label_Price,
  _ as Graph_Label_Volume,
  _ as Graph_NoData,
  _ as Graph_NumberSold,
  _ as Graph_TimeScale_Lifetime,
  _ as Graph_TimeScale_Month,
  _ as Graph_TimeScale_Week,
  _ as Graph_TimeScale_Year,
  _ as Graph_Tooltip_NA,
  _ as Graph_Tooltip_NoPurchaseData,
  _ as Header_GiveFeedback,
  _ as Header_LearnMore,
  _ as Header_MarketDescription,
  _ as Header_MarketTitle,
  _ as Header_OptOut,
  _ as Header_Search_Filters,
  _ as Header_Search_Placeholder,
  _ as Header_Search_PlaceholderNew,
  _ as Home_GamePicker_Label,
  _ as Home_GamePicker_ViewAll,
  _ as ItemBucketPicker_Overflow_FilterPlaceholder,
  _ as ItemBucketPicker_Overflow_Placeholder,
  _ as Item_CountryBuyRestricted,
  _ as Item_CountryBuySellRestricted,
  _ as ListingFilter_Title,
  _ as Listing_EnhancedAppearance_Missing,
  _ as Listing_EnhancedAppearance_ShowBackground,
  _ as Listing_MyListing,
  _ as Listing_NotAvailable,
  _ as Listing_NotAvailable_Long,
  _ as Listing_NotAvailable_Short,
  _ as Listing_SomethingWentWrong,
  _ as Listings_NoneFound,
  _ as Listings_TextFilter_Placeholder,
  _ as MarketHome_PopularApps,
  _ as MarketSearch_FilterColumn_Header,
  _ as MarketSearch_Placeholder,
  _ as MarketSearch_Reset,
  _ as Market_AppUnplayedAndUnvetted,
  _ as Market_AppUnplayedAndUnvetted_Dismiss,
  _ as MedianSalePrice_Graph_Title,
  _ as Mobile_BuyOrderSection,
  _ as Mobile_FiltersButton,
  _ as Mobile_GraphSection,
  _ as Mobile_InfoSection,
  _ as MyOrders_Cancel,
  _ as MyOrders_FailedToLoad,
  _ as MyOrders_GridHeader_DateListed,
  _ as MyOrders_GridHeader_Name,
  _ as MyOrders_GridHeader_Price,
  _ as MyOrders_GridHeader_Quantity,
  _ as MyOrders_Heading,
  _ as MyOrders_Heading_Buy,
  _ as MyOrders_Heading_MyListings,
  _ as MyOrders_Heading_MyPurchaseOffers,
  _ as MyOrders_Heading_Sell,
  _ as MyOrders_NoActiveOrders_Item,
  _ as MyOrders_NoBuyOrders_Item,
  _ as MyOrders_NoSellOrders_Item,
  _ as MyOrders_QuantityWithValue,
  _ as MyOrders_Remove,
  _ as MyOrders_SeeAllN,
  _ as OrderBook_BuyOrder_Description,
  _ as OrderBook_BuyOrder_Description_None,
  _ as OrderBook_BuyOrder_Explanation_Commodity,
  _ as OrderBook_BuyOrder_Explanation_Unique,
  _ as OrderBook_BuyOrder_NeedBucket,
  _ as OrderBook_Graph_BuyTooltip,
  _ as OrderBook_Graph_BuyTooltip_Plural,
  _ as OrderBook_Graph_SellTooltip,
  _ as OrderBook_Graph_SellTooltip_Plural,
  _ as OrderBook_Graph_Title,
  _ as OrderBook_PlaceOrder_BuyRequests,
  _ as OrderBook_PlaceOrder_BuyRequests_Plural,
  _ as OrderBook_SellOrder_Description,
  _ as OrderBook_SellOrder_Description_None,
  _ as OrderBook_Table_Price,
  _ as OrderBook_Table_PriceOrLess,
  _ as OrderBook_Table_PriceOrMore,
  _ as OrderBook_Table_Quantity,
  _ as PriceFilter_ValueAndUp,
  _ as PurchaseDialog_Action_AddFunds,
  _ as PurchaseDialog_Action_Purchase,
  _ as PurchaseDialog_BillingInfo_Address,
  _ as PurchaseDialog_BillingInfo_AddressLine2,
  _ as PurchaseDialog_BillingInfo_City,
  _ as PurchaseDialog_BillingInfo_Country,
  _ as PurchaseDialog_BillingInfo_FirstName,
  _ as PurchaseDialog_BillingInfo_Label,
  _ as PurchaseDialog_BillingInfo_LastName,
  _ as PurchaseDialog_BillingInfo_SaveInfo,
  _ as PurchaseDialog_BillingInfo_StateProvince,
  _ as PurchaseDialog_BillingInfo_ZipPostal,
  _ as PurchaseDialog_Button_ViewInventory,
  _ as PurchaseDialog_Close,
  _ as PurchaseDialog_Confirmation_Body_Email,
  _ as PurchaseDialog_Confirmation_Body_Mobile,
  _ as PurchaseDialog_Confirmation_Body_Unknown,
  _ as PurchaseDialog_Confirmation_Description_Email,
  _ as PurchaseDialog_Confirmation_Description_Mobile,
  _ as PurchaseDialog_Confirmation_Description_Unknown,
  _ as PurchaseDialog_Confirmation_Title,
  _ as PurchaseDialog_Confirmation_Title_Wait,
  _ as PurchaseDialog_Details_Column_Name,
  _ as PurchaseDialog_Details_Column_Price,
  _ as PurchaseDialog_EU_SSA,
  _ as PurchaseDialog_Error_InvalidMilitaryCity,
  _ as PurchaseDialog_Error_InvalidPostal,
  _ as PurchaseDialog_Error_MissingRequired,
  _ as PurchaseDialog_Error_NoConfirmation,
  _ as PurchaseDialog_Error_ServerGeneric,
  _ as PurchaseDialog_Header,
  _ as PurchaseDialog_LocalTax_Label,
  _ as PurchaseDialog_PaymentMethod_Label,
  _ as PurchaseDialog_PaymentMethod_Wallet,
  _ as PurchaseDialog_PublisherFee_Label,
  _ as PurchaseDialog_PublisherFee_Label_Generic,
  _ as PurchaseDialog_PurchaseComplete,
  _ as PurchaseDialog_Purchase_Successful,
  _ as PurchaseDialog_SSA_Fail,
  _ as PurchaseDialog_SSA_Link,
  _ as PurchaseDialog_SSA_Link_Title,
  _ as PurchaseDialog_SteamAccount_Label,
  _ as PurchaseDialog_SteamFee_Label,
  _ as PurchaseDialog_Subtotal_Label,
  _ as PurchaseDialog_Total_Label,
  _ as PurchaseDialog_ViewInventory,
  _ as PurhcaseDialog_SaveMyAddress,
  _ as Results_GridView_Tooltip,
  _ as Results_ListView_Tooltip,
  _ as Results_PageLoadError,
  _ as Search_AmountFound,
  _ as Search_AmountFoundFor,
  _ as Search_AmountFoundFor_Plural,
  _ as Search_AmountFound_Plural,
  _ as Search_Button,
  _ as Search_ListingQuantity,
  _ as Search_ListingQuantity_Abbreviation,
  _ as Search_ListingsFound,
  _ as Search_ListingsFound_Plural,
  _ as Search_Placeholder,
  _ as Search_ResultsFoundFor,
  _ as SellDialog_Frame_Title,
  _ as SortBy_AssetProperty_Asc,
  _ as SortBy_AssetProperty_Desc,
  _ as SortBy_Label,
  _ as SortBy_Name_Asc,
  _ as SortBy_Name_Desc,
  _ as SortBy_Popularity,
  _ as SortBy_Price_Asc,
  _ as SortBy_Price_Desc,
  _ as SortBy_Quantity_Asc,
  _ as SortBy_Quantity_Desc,
  _ as Unavailable_Header,
  _ as Unavailable_Header_Plural,
  _ as UniqueBuyOrder_Explanation_1,
  _ as UniqueBuyOrder_Explanation_2,
  _ as UniqueBuyOrder_Explanation_3,
  _ as UniqueBuyOrder_Explanation_Header,
  _ as default,
};
