var _ = `hungarian`,
  _ = `Steam Műhely`,
  _ = `A(z) %1$s Steam Műhelye`,
  _ = `Probléma adódott az oldal betöltésekor. Kérjük, próbáld újra később.`,
  _ = `Hiba`,
  _ = `Probléma adódott a művelet végrehajtásakor. Próbáld újra később. (%1$s)`,
  _ = `Sajnáljuk!`,
  _ = `Hiba történt kérésed feldolgozásakor:`,
  _ = `Túl sok kérést küldtél mostanában. Kérjük várj, és próbálkozz a kéréseddel újra később.`,
  _ = `Régi Műhely megnézése (csak admin)`,
  _ = `Böngészés: %1$s`,
  _ = `(Szavazz a kedvenceidre)`,
  _ = `(A játékodhoz adásához iratkozz fel)`,
  _ = `(Szavazz a kedvenceidre)`,
  _ = `Játékhoz elfogadva`,
  _ = `Elfogadva`,
  _ = `Hivatalos tartalom`,
  _ = `Készítő: %1$s`,
  _ = `Tárgyak`,
  _ = `Tárgyak`,
  _ = `Gyűjtemények`,
  _ = `Árucikkek`,
  _ = `Videók`,
  _ = `Mentett lekérdezések`,
  _ = `E keresési lekérdezés mentése`,
  _ = `Adj nevet a keresésednek`,
  _ = `Jelenlegi keresési szűrőid és rendezési beállításaid mentése a gyors jövőbeli újrahasználáshoz. Ezeket az „Elemeid” alatt találod.`,
  _ = `Mentés új keresési lekérdezésként, vagy egy korábbi keresési lekérdezés választása annak frissítéséhez.`,
  _ = `<Új mentett keresés>`,
  _ = `Mentés`,
  _ = `Mentett keresés törlése`,
  _ = `Biztosan törölni akarod a(z) „%1$s” mentett keresésedet?`,
  _ = `Törlés`,
  _ = `Tudj meg többet`,
  _ = `Keresés törlése`,
  _ = `A(z) %1$s Steam Műhelye`,
  _ = `Rendezési sorrend`,
  _ = `Időkeret`,
  _ = `Ma`,
  _ = `Egy hét`,
  _ = `Harminc nap`,
  _ = `Három hónap`,
  _ = `Hat hónap`,
  _ = `Egy év`,
  _ = `Minden idők`,
  _ = `%1$s (%2$s)`,
  _ = `Legutóbbi`,
  _ = `Legnépszerűbb`,
  _ = `Az eddigi legjobbra értékelt`,
  _ = `Legutóbbi frissítés`,
  _ = `Jelentéssúlyozás`,
  _ = `(Admin) %1$s`,
  _ = `Más elemekhez legtöbbször szükséges`,
  _ = `A legtöbb gyűjteményben`,
  _ = `(Admin) Jóváhagyási sor`,
  _ = `Még nem értékelt`,
  _ = `Összes egyedi feliratkozó`,
  _ = `Összes szavazat`,
  _ = `Legtöbb támogató szavazat`,
  _ = `Keresési relevancia`,
  _ = `Közelmúltbeli játékidő`,
  _ = `Összesített játékidő`,
  _ = `Közelmúltbeli átlagos játékidő`,
  _ = `Összesített átlag játékidő`,
  _ = `Játékmenetek`,
  _ = `Játékmenetek összesített száma`,
  _ = `Inappropriate Score`,
  _ = `Ban Content Check`,
  _ = `Curated Admin`,
  _ = `Jelölt`,
  _ = `Általad értékelt`,
  _ = `Elfogadás dátuma`,
  _ = `Speciális szűrők: `,
  _ = `Nincs`,
  _ = `Játékhoz elfogadva`,
  _ = `Barátok által létrehozott`,
  _ = `Követett által létrehozott`,
  _ = `Barátok által kedvencnek jelölt`,
  _ = `Jelentett (csak admin)`,
  _ = `Más elemekhez szükséges`,
  _ = `Gyűjteményekben`,
  _ = `Kezdőoldal`,
  _ = `Böngészés`,
  _ = `Elemeid`,
  _ = `Témák`,
  _ = `Ismertető`,
  _ = `%1$s keresése`,
  _ = `Általad közzétett elemek (%1$s)`,
  _ = `Kedvenceid (%1$s)`,
  _ = `Feliratkozott elemek (%1$s)`,
  _ = `Játszott elemek (%1$s)`,
  _ = `Gyűjteményeid (%1$s)`,
  _ = `Szavazási várólistád`,
  _ = `Fizetési adataid`,
  _ = `Jövedelmed megnézése`,
  _ = `(műhely-elemeid eladásából származik)`,
  _ = `Jogi megállapodás megnézése`,
  _ = `Szavazási várólista`,
  _ = `Szűrők alkalmazása`,
  _ = `Rendezés: %1$s`,
  _ = `<nincs kiválasztva>`,
  _ = `DLC szükséges`,
  _ = `Szükséges DLC: %1$s`,
  _ = `Általad birtokolt DLC-t igénylők`,
  _ = `Általad nem birtokolt DLC-ket igénylő elemek kizárása`,
  _ = `Nincs egy DLC-d sem.`,
  _ = `Megvan az összes elérhető DLC.`,
  _ = `(még %1$s elem)`,
  _ = `Birtokolt DLC-k bevonása`,
  _ = `Nem birtokolt DLC-k kizárása`,
  _ = `Szűrés név szerint`,
  _ = `Összeférhetetlen elemek mutatása`,
  _ = `Egyes elemek nem kerülhetnek be a játékba. Ha ezt bejelölöd, ennek ellenére megtalálhatod ezeket.`,
  _ = `Nem nyilvános elemek megnézése`,
  _ = `Találatok erre: „%1$s”`,
  _ = `Találatok erre: „%1$s” (csak cím)`,
  _ = `Találatok erre: „%1$s” (csak leírás)`,
  _ = `Tartalmazza ezt: „%1$s”`,
  _ = `A megfelelő működéshez „%1$s” szükséges.`,
  _ = `%1$s: %2$s`,
  _ = `%1$s: %2$s`,
  _ = `Címke: összeférhetetlen elemek`,
  _ = `Címke: elfogadott elemek`,
  _ = `Add meg, az elem mely szöveges mezőiben szeretnél keresni:`,
  _ = `Cím és leírás`,
  _ = `Csak cím`,
  _ = `Csak leírás`,
  _ = `Bonyolultabb kereséseket is össze tudsz állítani %1$s, %2$s és %3$s operátorok használatával (nagybetűvel kell őket írni). Alternatív módon használhatsz %4$s és %5$s karaktereket az %1$s és a %3$s rövidítésére.`,
  _ = `A „%1$s” a keresési szövegben „%2$s” és „%3$s” szavakkal is rendelkező elemeket keresi.`,
  _ = `A „%1$s” a keresési szövegben „%2$s” vagy „%3$s” szavakkal rendelkező elemeket keresi.`,
  _ = `A „%1$s” a keresési szövegben a „%2$s” szóval rendelkező, de a „%3$s” szóval nem rendelkező elemeket keresi.`,
  _ = `piros`,
  _ = `kék`,
  _ = `zöld`,
  _ = `szoba`,
  _ = `A keresési kifejezéseket zárójelekkel kombinálva igen specifikus kereséseket állíthatsz össze.`,
  _ = `A „%1$s” a keresési szövegben „%2$s”, és mellette a „%3$s” vagy a „%4$s” szavakkal rendelkező elemeket keresi.`,
  _ = `A „%1$s” a keresési szövegben „%2$s”, és mellette a „%3$s” vagy a „%4$s” szavakkal rendelkező, de a „%5$s” szóval nem rendelkező elemeket keresi.`,
  _ = `Szűrők kívánt elhelyezkedése:`,
  _ = `Bal oldalon`,
  _ = `Jobb oldalon`,
  _ = `Összecsukva`,
  _ = `Ezen elemek elhalványítása:`,
  _ = `Általad jelentett`,
  _ = `Általad blokkolt felhasználók készítették`,
  _ = `Szavazatoddal támogattad`,
  _ = `Szavazatoddal ellenezted`,
  _ = `Feliratkozási listádban`,
  _ = `Szűrés dátum szerint`,
  _ = `Közzététel dátuma`,
  _ = `%1$s után közzétéve`,
  _ = `%1$s előtt közzétéve`,
  _ = `%1$s és %2$s között közzétéve`,
  _ = `Legutóbbi frissítés dátuma`,
  _ = `%1$s után frissítve`,
  _ = `%1$s előtt frissítve`,
  _ = `%1$s és %2$s között frissítve`,
  _ = `E dátumok között:`,
  _ = `és`,
  _ = `1 elem felel meg a szűrőknek`,
  _ = `%2$s elem felel meg a szűrőknek`,
  _ = `Oldalanként:`,
  _ = `%1$s / %2$s`,
  _ = `Gyűjtemény létrehozása`,
  _ = `Terved beküldése`,
  _ = `Gyorsnézet`,
  _ = `Több mutatása`,
  _ = `Fel vagy iratkozva erre az elemre.`,
  _ = `Ez az elem a Kedvencek listádon van.`,
  _ = `Már játszottál ezzel az elemmel.`,
  _ = `Ezt az elemet elfogadták e játékban használatra!`,
  _ = `Ez az elem összeférhetetlennek lett jelölve ehhez a játékhoz.`,
  _ = `Támogattad ezt az elemet.`,
  _ = `Ellenezted ezt az elemet.`,
  _ = `Jelentetted ezt az elemet a Steam közösségi irányelvek megsértéséért.`,
  _ = `Blokkoltad ezt a felhasználót.`,
  _ = `Leírás`,
  _ = `Témák`,
  _ = `Hozzászólások (%1$s)`,
  _ = `Bejelentések`,
  _ = `Elemstatisztikák`,
  _ = `Változásjegyzék (%1$s)`,
  _ = `Steam Műhely :: %1$s`,
  _ = `Készítette: `,
  _ = `%2$s értékelés`,
  _ = `%2$s értékelés`,
  _ = `Nincs elegendő értékelés`,
  _ = `%1$s, %2$s`,
  _ = `Közzétéve:`,
  _ = `Frissítve: `,
  _ = `Feliratkozás`,
  _ = `Feliratkozva`,
  _ = `Leiratkozás`,
  _ = `Kedvenc`,
  _ = `Kedvencnek jelölve`,
  _ = `Kedvencnek jelölés törlése`,
  _ = `Függő elemek megnézése`,
  _ = `Gyűjteményhez adás`,
  _ = `Mentés gyűjteménybe`,
  _ = `Kérjük, jelentkezz be e művelet végrehajtásához.`,
  _ = `Feliratkozás a letöltéshez`,
  _ = `Leiratkozás ezen elem eltávolításához a játékodból.`,
  _ = `Találd meg könnyen ezt az elemet később.`,
  _ = `Mind a(z) %1$s elem megnézése, amelyek helyes működése ettől az elemtől függ. Ne feledd, hogy némelyik rejtettként, vagy csak barátoknak elérhetőként lehet jelölve.`,
  _ = `Ezen elem jelentése a Steam online viselkedési szabályzat megsértéséért.`,
  _ = `Díjazás`,
  _ = `Hozzáadás az egyik gyűjteményedhez.`,
  _ = `Fájlméret:`,
  _ = `Látogatók:`,
  _ = `Feliratkozók:`,
  _ = `Kedvencek:`,
  _ = `Összes egyedi kedvelés:`,
  _ = `Összes egyedi feliratkozó:`,
  _ = `Összes játékmenet:`,
  _ = `A következő elemek szükségesek: `,
  _ = `A következő DLC szükséges: `,
  _ = `Feliratkozás mindre`,
  _ = `Leiratkozás mindről`,
  _ = `Mentés gyűjteménybe`,
  _ = `Összes közösségi díj kinyitása`,
  _ = `%1$s közösségi díj`,
  _ = `%1$s közösségi díj`,
  _ = `CÍMKÉK`,
  _ = `KATEGÓRIÁK`,
  _ = `LEÍRÁS`,
  _ = `Ehhez szükséges:`,
  _ = `%1$s gyűjteményben`,
  _ = `%1$s %2$s készítette gyűjteményben`,
  _ = `Hiba`,
  _ = `Nincs jogosultságod e művelet végrehajtásához.`,
  _ = `Probléma adódott a Steammel való kapcsolatfelvétel során. Próbáld meg később.`,
  _ = `Túl sok műveletet próbáltál meg végrehajtani rövid idő alatt. Kérjük, várj még egy kicsit, mielőtt újból megpróbálnád.`,
  _ = `Hiba történt e művelet végrehajtásának megkísérlésekor. Kérjük, próbálkozz később.`,
  _ = `Feliratkozás mindre`,
  _ = `Hozzáadni akarod e gyűjtemény elemeit a feliratkozásaidhoz, vagy felülírni a feliratkozásaidat kizárólag e gyűjtemény elemeivel?`,
  _ = `Csak hozzáadás`,
  _ = `Feliratkozásaim felülírása`,
  _ = `További szükséges elemek`,
  _ = `Ez az elem a következő elemek mindegyikét igényli a megfelelő működéshez.`,
  _ = `A(z) <1>%1$s</1> a következő elemek mindegyikét igényli a megfelelő működéshez.`,
  _ = `Itt a folytatás előtt mindegyikre rá tudsz kattintani további információért és a feliratkozáshoz.`,
  _ = `Választhatod azt is, hogy feliratkozol az összes szükséges elemre (és az általuk megkövetelt elemekre is), de légy óvatos, mivel ez sok további elemet jelenthet.`,
  _ = `Feliratkozás csak erre az elemre`,
  _ = `Feliratkozás mindre`,
  _ = `Elem jelentése`,
  _ = `Most írd le, milyen módon sérti ez az elem a Steam szolgáltatási feltételeit, beleértve bármilyen releváns információt és hivatkozást. E jelentés beküldését nem lehet visszavonni.`,
  _ = `Ok: %1$s`,
  _ = `Először válassz egy okot, amiért jelented ezt az elemet:`,
  _ = `Ha szerzői jogsértést szeretnél jelenteni, és te vagy a szerzői jogok birtokosa, kérjük, lépj tovább a DMCA-nak megfelelő szerzői jogsértés-jelentő űrlapra %1$s.`,
  _ = `Ha védjegypanaszt szeretnél benyújtani, kérjük, %1$s tedd meg.`,
  _ = `itt`,
  _ = `Gyűjteményhez adás`,
  _ = `A(z) „%1$s” hozzá lesz adva az alább kiválasztott gyűjteményekhez:`,
  _ = `Nincsenek mentett gyűjteményeid. Létre tudsz hozni újat egy név megadásával alább.`,
  _ = `Hozzáadás a kiválasztott gyűjteményekhez`,
  _ = `Új gyűjtemény létrehozása`,
  _ = `Gyűjtemény felülírása`,
  _ = `Új gyűjteményként vagy egy meglévő gyűjteményt felülírva szeretnéd elmenteni ezt a gyűjteményt?`,
  _ = `Új gyűjtemény`,
  _ = `Meglévő gyűjtemény`,
  _ = `Adj nevet e gyűjteménynek:`,
  _ = `Válassz felülírandó gyűjteményt:`,
  _ = `%2$s elemet tartalmaz.`,
  _ = `%2$s elemet tartalmaz`,
  _ = `%2$s kapcsolt gyűjteménye van.`,
  _ = `%2$s kapcsolt gyűjteménye van.`,
  _ = `+%1$s`,
  _ = `A Steam Műhely minden eddiginél könnyebbé teszi befejezett tárgyak 3D modelljeinek közzétételét, hogy azok esélyt kapjanak az elfogadásra és a játékba való bekerülésre. Hogy elemet tehess közzé a Műhelyben elbírálásra, először olvasd el a jobb oldalt hivatkozott hivatalos dokumentációt, majd kattints a játék főmenüjében a Steam Műhely (Steam Workshop) gombra.`,
  _ = `A Steam Műhely megkönnyíti új tartalom felfedezését vagy megosztását játékodhoz vagy szoftveredhez. Minden játék vagy szoftver kissé eltérő fajta tartalmakat támogathat a Műhelyében, így a legjobb megnézni a hivatalos dokumentációt annak részleteiért, hogy mit lehet készíteni és ott megosztani.`,
  _ = `Amikor olyan tartalmat találsz, amit szeretnél játékodhoz adni, kattints a Feliratkozás gombra. A legtöbb esetben a tartalom automatikusan elérhető lesz, amikor legközelebb elindítod a játékot. Egyes termékeknél viszont fel kell keresned a játék vagy szoftver egy konkrét részét az új tartalom eléréséhez.`,
  _ = `A Steam Műhely megkönnyíti új tartalom felfedezését vagy megosztását játékodhoz vagy szoftveredhez. Minden termék kissé eltérő fajta tartalmakat támogathat a Műhelyében, így a legjobb megnézni a hivatalos dokumentációt annak részleteiért, hogy mit lehet készíteni és ott megosztani.`,
  _ = `Amikor olyan tartalmat találsz a(z) %1$s fülön, amit szeretnél játékodhoz adni, kattints a Feliratkozás gombra. A legtöbb esetben a tartalom automatikusan elérhető lesz, amikor legközelebb elindítod a játékot. Egyes termékeknél viszont fel kell keresned a játék vagy szoftver egy konkrét részét az új tartalom eléréséhez.`,
  _ = `Elérhető funkciók`,
  _ = `A(z) %1$s ezeket a Steam Műhely funkciókat használja:`,
  _ = `Használatra kész elemek`,
  _ = `Az e Műhelyben közzétett elemek azonnali használatra készek. Kattints az elem részletes oldalának Feliratkozás gombjára, és az elem a(z) %1$s elindítása után elérhető lesz.`,
  _ = `Az e Műhelyben a(z) %2$s fül alatt közzétett elemek készek az azonnali használatra. Kattints az elem részletes oldalának Feliratkozás gombjára, és az elem a(z) %1$s elindítása után elérhető lesz.`,
  _ = `Verziótámogatás játékágakhoz`,
  _ = `Az elemeknek lehetnek különböző (béta) játékágakhoz társított verziói. Ez megkönnyíti a fejlesztőknek és a Műhely-elem-készítőknek az együttműködést az elemeik kompatibilitásának biztosítására, amikor a(z) %1$s frissítéseket kap.`,
  _ = `Gondozott elemkészletek`,
  _ = `Az e Műhelyben közzétett elemek nem használhatók azonnal a(z) %1$s játékban. A fejlesztők várják, hogy a közösség pozitívan értékelje azon elemeket, melyeket leginkább szeretne a(z) %1$s játékban elérhetőként vagy megvehetőként látni. Végül a fejlesztők kiválasztják, mely elemek kerüljenek be a(z) %1$s játékba.`,
  _ = `Az e Műhelyben a(z) %2$s fülön közzétett elemek nem használhatók azonnal a(z) %1$s játékban. A fejlesztők várják, hogy a közösség pozitívan értékelje azon elemeket, melyeket leginkább szeretne a(z) %1$s játékban megvásárolhatóként vagy feloldhatóként látni. Végül a fejlesztők kiválasztják, mely elemek kerüljenek be a(z) %1$s játékba.`,
  _ = `Elem-eladások`,
  _ = `Az elfogadott Műhely-elemek elérhetővé válnak megvásárlásra vagy feloldásra a(z) %1$s játékban.`,
  _ = `Közvetlen elemeladások`,
  _ = `Az e Műhelyben szereplő elemek eladásra kínálhatók közvetlenül a Steam Műhelyen keresztül. Ezekhez az elemekhez szükség lehet a fejlesztők vagy a közösség jóváhagyására, mielőtt elérhetővé válnának. Tartalomkészítők: nézzétek meg alul a <a %s>Pénzkeresés</a> részt, hogy többet tudjatok meg tartalmatok Steam Műhelyen keresztüli értékesítéséről.`,
  _ = `Az alkotók honoráriumot kaphatnak`,
  _ = `Az e Műhelyből értékesítésre elfogadott elemek, ha azok pénzért kerülnek árusításra, részesedést fizetnek a készítőknek a bevételből.`,
  _ = `A szolgáltatók honoráriumot kaphatnak`,
  _ = `A Műhely-alkotók választhatnak szervezetek, felhasználók és eszközkészítők előre engedélyezett listájából, akik százalékot kaphatnak a Valve bevételéből az eladott elemeik után. A konkrét szervezetek és személyek alább vannak felsorolva.`,
  _ = `Tartalomkészítő vagy, és tudomásod van további olyan szervezetről vagy személyről, akivel szeretnél osztozni elemeladásaid sikerén? Tudasd velünk <a href="%1$s">itt</a>.`,
  _ = `Bevételmegosztás`,
  _ = `Ez a bevétel azon százaléka, amelyet egy elem készítője az eleme közvetlen eladásából kap.`,
  _ = `További információkért kattints %1$s.`,
  _ = `ide`,
  _ = `E Műhelyben közzétett elemek`,
  _ = `Elfogadott elemek a(z) %1$s játékhoz`,
  _ = `Kapcsolódó hivatkozások`,
  _ = `Hivatalos dokumentáció megnézése`,
  _ = `Steames útmutatók keresése`,
  _ = `Közösség-készítette útmutatók ehhez a Műhelyhez`,
  _ = `Steam Műhelyen keresztüli vásárlásokhoz`,
  _ = `Steam Műhely felhasználási feltételek`,
  _ = `Steam Műhely jövedelemhez`,
  _ = `Szolgáltatók`,
  _ = `Oldal megnézése`,
  _ = `Steam profil megnézése`,
  _ = `Kellékek`,
  _ = `Közösségek`,
  _ = `Felhasználók`,
  _ = `Részletek megnézése`,
  _ = `Gyorsnézet`,
  _ = `Szavazz`,
  _ = `a közösség által készített elemekre, amelyeket szeretnél látni a játékban`,
  _ = `Kattints a szavazás megkezdéséhez a Várólistádban.`,
  _ = `Eddig %1$s elemre szavaztál.`,
  _ = `Eddig %1$s elemre szavaztál.`,
  _ = `Az elmúlt héten`,
  _ = `Az elmúlt hónapban`,
  _ = `Az elmúlt három hónapban`,
  _ = `Az elmúlt hat hónapban`,
  _ = `Az elmúlt évben`,
  _ = `Követett készítőktől`,
  _ = `Újonnan közzétett elemek általad követett készítőktől`,
  _ = `Még több a követett készítőktől`,
  _ = `Elfogadott elemek`,
  _ = `Ezek az elemek el lettek fogadva, és esetlegesen eshetnek vagy elérhetővé válhatnak megvételre a játékban.`,
  _ = `Minden elfogadott elem megnézése`,
  _ = `Legnépszerűbb %1$s`,
  _ = `Legnépszerűbb`,
  _ = `Az elmúlt három hónapban legjobbra értékeltek.`,
  _ = `Legnépszerűbbek megnézése`,
  _ = `Legtöbb feliratkozó`,
  _ = `Legtöbb jelenlegi egyedi feliratkozó.`,
  _ = `Legtöbb feliratkozásos megnézése`,
  _ = `Új`,
  _ = `Legutóbb közzétett elemek.`,
  _ = `Nemrég közzétettek megnézése`,
  _ = `Legtöbb játékidő`,
  _ = `Legjátszottabbak megnézése`,
  _ = `Legutóbb frissítve`,
  _ = `Legutóbb frissített elemek.`,
  _ = `Nemrég frissítettek megnézése`,
  _ = `Barátok kedvencei`,
  _ = `A barátaid által kedvencnek jelölt elemek.`,
  _ = `Összes barát kedvenceinek megnézése`,
  _ = `Más elemekhez legtöbbször szükséges`,
  _ = `A más elemek megfelelő működéséhez szükséges legnépszerűbb elemek.`,
  _ = `Összes megnézése`,
  _ = `A legnépszerűbb árucikkek`,
  _ = `Összes népszerű árucikk megnézése`,
  _ = `Összes megnézése`,
  _ = `Kedvenceid`,
  _ = `Nemrég frissített kedvencek megnézése`,
  _ = `Játszott elemeid`,
  _ = `Nemrég frissített általad játszottak megnézése`,
  _ = `Feliratkozásaid`,
  _ = `Nemrég frissített feliratkozásaid megnézése`,
  _ = `Az elmúlt három hónapon belül frissítve`,
  _ = `Különleges esemény: %1$s`,
  _ = `Az összes „%1$s” címkéjű elem megnézése`,
  _ = `%1$s barátod adta ezt a kedvenceihez`,
  _ = `%1$s barátod adta ezt a kedvenceihez`,
  _ = `Pályák`,
  _ = `Tárgyak`,
  _ = `Egyedi játékok és bot szkriptek`,
  _ = `Tárgyak`,
  _ = `Szűrés hős szerint`,
  _ = `Pályák`,
  _ = `Tárgyak`,
  _ = {
    language: _,
    Header_WorkshopTitle: _,
    Header_App_WorkshopTitle: _,
    Workshop_Error_Loading: _,
    Workshop_Error_Title: _,
    Workshop_Error_Browse_Desc: _,
    Error_Sorry: _,
    Error_Encountered: _,
    Error_TooManyRequests_Description: _,
    Workshop_ExitReact_Link: _,
    Workshop_Browsing: _,
    Workshop_Browsing_Mtx_Desc: _,
    Workshop_Browsing_ReadyToUse_Desc: _,
    Workshop_Browsing_Merchandise_Desc: _,
    Workshop_AcceptedForGame: _,
    Workshop_AcceptedMerch: _,
    Workshop_OfficialContent: _,
    Workshop_Browse_Author_Link: _,
    Workshop_Section_Mtx: _,
    Workshop_Section_ReadyToUse: _,
    Workshop_Section_Collections: _,
    Workshop_Section_Merchandise: _,
    Workshop_Section_Videos: _,
    Workshop_Saved_Queries: _,
    Workshop_Saved_Queries_Update: _,
    Workshop_Saved_Queries_Save_Title: _,
    Workshop_Saved_Queries_Save_Desc_Long: _,
    Workshop_Saved_Queries_Save_Desc: _,
    Workshop_Saved_Queries_Save_New: _,
    Workshop_Saved_Queries_Save_Btn: _,
    Workshop_Saved_Queries_Delete_Title: _,
    Workshop_Saved_Queries_Delete_Desc: _,
    Workshop_Saved_Queries_Delete_Btn: _,
    Workshop_LearnMore: _,
    Workshop_Filters_ClearBtn: _,
    Workshop_About: _,
    Workshop_BrowseSort_SortOrder: _,
    Workshop_BrowseSort_TimeFrame: _,
    SharedFiles_Browse_Trend_Option_Today: `Ma`,
    SharedFiles_Browse_Trend_Option_Week: _,
    SharedFiles_Browse_Trend_Option_Month: _,
    SharedFiles_Browse_Trend_Option_ThreeMonths: _,
    SharedFiles_Browse_Trend_Option_SixMonths: _,
    SharedFiles_Browse_Trend_Option_OneYear: _,
    SharedFiles_Browse_Trend_Option_AllTime: _,
    Workshop_BrowseSort_Combined: _,
    Workshop_BrowseSort_MostRecent: _,
    Workshop_BrowseSort_MostPopular: _,
    Workshop_BrowseSort_TopRated: _,
    Workshop_BrowseSort_LastUpdated: _,
    Workshop_BrowseSort_Reported: _,
    Workshop_BrowseSort_AdminOption: _,
    Workshop_BrowseSort_NumParentItems: _,
    Workshop_BrowseSort_NumParentCollections: _,
    Workshop_RequireApproval: _,
    Workshop_BrowseSort_ToRate: _,
    Workshop_BrowseSort_TotalUniqueSubscribers: _,
    Workshop_BrowseSort_TotalVotes: _,
    Workshop_BrowseSort_MostUpVotes: _,
    Workshop_BrowseSort_SearchRelevance: _,
    Workshop_BrowseSort_Playtime: _,
    Workshop_BrowseSort_PlaytimeTotal: _,
    Workshop_BrowseSort_PlaytimeAverage: _,
    Workshop_BrowseSort_PlaytimeAverageTotal: _,
    Workshop_BrowseSort_PlaytimeSessions: _,
    Workshop_BrowseSort_PlaytimeSessionsTotal: _,
    Workshop_BrowseSort_Inappropriate: _,
    Workshop_BrowseSort_BanContentCheck: _,
    Workshop_BrowseSort_CuratedAdmin: _,
    Workshop_BrowseSort_Nominee: _,
    Workshop_BrowseSort_Rated: _,
    Workshop_BrowseSort_AcceptedTime: _,
    Workshop_SpecialFilter_Desc: _,
    Workshop_SpecialFilter_None: _,
    Workshop_SpecialFilter_AcceptedForUse: _,
    Workshop_SpecialFilter_CreatedByFriends: _,
    Workshop_SpecialFilter_CreatedByFollowed: _,
    Workshop_SpecialFilter_FavoritedByFriends: _,
    Workshop_SpecialFilter_Reported: _,
    Workshop_SpecialFilter_ParentItems: _,
    Workshop_SpecialFilter_ParentCollections: _,
    Workshop_Menu_Home: _,
    Workshop_Menu_Browse: _,
    Workshop_Menu_YourItems: _,
    Workshop_Menu_Discussions: _,
    Workshop_Menu_About: _,
    Workshop_Menu_Search: _,
    Workshop_SubMenu_YourItems: _,
    Workshop_SubMenu_YourFavorites: _,
    Workshop_SubMenu_YourSubscriptions: _,
    Workshop_SubMenu_YourPlayed: _,
    Workshop_SubMenu_YourCollections: _,
    Workshop_SubMenu_YourVotingQueue: _,
    Workshop_SubMenu_YourPaymentInfo: _,
    Workshop_SubMenu_ViewYourRevenue: _,
    Workshop_SubMenu_ViewYourRevenue_Desc: _,
    Workshop_SubMenu_LegalAgreement: _,
    Workshop_SubMenu_VotingQueue: _,
    Workshop_ApplyFilters: _,
    Workshop_SortBy: _,
    Workshop_Tag_NoneSpecified: _,
    Workshop_RequiredDLC_Header: _,
    Workshop_RequiredDLC_Filter: _,
    Workshop_IncludeOwnedDLC_Filter: _,
    Workshop_ExcludeOwnedDLC_Filter: _,
    Workshop_OwnedDLC_None_Filter: _,
    Workshop_OwnedDLC_All_Filter: _,
    Workshop_OwnedDLC_More_Filter: _,
    Workshop_RequiredDLC_IncludeOwned: _,
    Workshop_RequiredDLC_ExcludeUnowned: _,
    Workshop_RequiredDLC_NameFilter: _,
    Workshop_Flag_Incompatible_Checkbox: _,
    Workshop_Flag_Incompatible_Checkbox_Desc: _,
    Workshop_Admin_View: _,
    Workshop_SearchResults_SearchText: _,
    Workshop_SearchResults_SearchText_TitleOnly: _,
    Workshop_SearchResults_SearchText_DescriptionOnly: _,
    Workshop_SearchedForChild: _,
    Workshop_SearchedForRequiredItem: _,
    Workshop_SearchResults_Tag: _,
    Workshop_SearchResults_KVTag: _,
    Workshop_SearchResults_Flag_Incompatible: _,
    Workshop_SearchResults_Flag_Accepted: _,
    Workshop_SearchTarget_MenuTitle: _,
    Workshop_SearchTarget_All: _,
    Workshop_SearchTarget_Title: _,
    Workshop_SearchTarget_Description: _,
    Workshop_Search_Help: _,
    Workshop_Search_Help_Example1: _,
    Workshop_Search_Help_Example2: _,
    Workshop_Search_Help_Example3: _,
    Workshop_Search_Help_Example_Red: _,
    Workshop_Search_Help_Example_Blue: _,
    Workshop_Search_Help_Example_Green: _,
    Workshop_Search_Help_Example_Room: _,
    Workshop_Search_Help_Advanced: _,
    Workshop_Search_Help_AdvancedExample1: _,
    Workshop_Search_Help_AdvancedExample2: _,
    Workshop_FiltersMenu_State_Title: _,
    Workshop_FiltersMenu_State_Left: _,
    Workshop_FiltersMenu_State_Right: _,
    Workshop_FiltersMenu_State_Collapsed: _,
    Workshop_DimmedItems_Title: _,
    Workshop_DimmedItems_Reported: _,
    Workshop_DimmedItems_BlockedCreators: _,
    Workshop_DimmedItems_VotedUp: _,
    Workshop_DimmedItems_VotedDown: _,
    Workshop_DimmedItems_Subscribed: _,
    Workshop_DateFilter_FilterByDate: _,
    Workshop_DateFilter_TimeCreated: _,
    Workshop_DateFilter_TimeCreated_After: _,
    Workshop_DateFilter_TimeCreated_Before: _,
    Workshop_DateFilter_TimeCreated_Between: _,
    Workshop_DateFilter_TimeUpdated: _,
    Workshop_DateFilter_TimeUpdated_After: _,
    Workshop_DateFilter_TimeUpdated_Before: _,
    Workshop_DateFilter_TimeUpdated_Between: _,
    Workshop_DateFilter_Between: _,
    Workshop_DateFilter_And: `és`,
    Workshop_NumResults: _,
    Workshop_NumResults_Plural: _,
    Workshop_NumPerPage: _,
    Workshop_PagingControls: _,
    Workshop_CreateCollection: _,
    Workshop_CreateMerchandise: _,
    Workshop_Item_QuickView: _,
    Workshop_Item_QuickView_ExpandBtn: _,
    Workshop_StatusIcon_TT_Subscribed: _,
    Workshop_StatusIcon_TT_Favorited: _,
    Workshop_StatusIcon_TT_Played: _,
    Workshop_StatusIcon_TT_Accepted: _,
    Workshop_StatusIcon_TT_Incompatible: _,
    Workshop_StatusIcon_TT_VotedUp: _,
    Workshop_StatusIcon_TT_VotedDown: _,
    Workshop_StatusIcon_TT_Reported: _,
    Workshop_StatusIcon_TT_BlockedCreator: _,
    Workshop_ItemDetails_Tab_Description: _,
    Workshop_ItemDetails_Tab_Discussions: _,
    Workshop_ItemDetails_Tab_Comments: _,
    Workshop_ItemDetails_Tab_Updates: _,
    Workshop_ItemDetails_Tab_Stats: _,
    Workshop_ItemDetails_Tab_ChangeNotes: _,
    Workshop_ItemDetails_Title: _,
    Workshop_ItemDetails_CreatedBy: _,
    Workshop_ItemDetails_NumRatings: _,
    Workshop_ItemDetails_NumRatings_Plural: _,
    Workshop_ItemDetails_NotEnoughRatings: _,
    Workshop_ItemDetails_TimestampWithTime: _,
    Workshop_ItemDetails_TimestampCreated: _,
    Workshop_ItemDetails_TimestampUpdated: _,
    Workshop_ItemDetails_Subscribe: _,
    Workshop_ItemDetails_Subscribed: _,
    Workshop_ItemDetails_Unsubscribe: _,
    Workshop_ItemDetails_Favorite: _,
    Workshop_ItemDetails_Favorited: _,
    Workshop_ItemDetails_Unfavorite: _,
    Workshop_ItemDetails_ViewDependentItems: _,
    Workshop_ItemDetails_AddToCollection: _,
    Workshop_ItemDetails_SaveCollectionToCollection: _,
    Workshop_ItemDetails_Signin_TT: _,
    Workshop_ItemDetails_Subscribe_TT: _,
    Workshop_ItemDetails_Unsubscribe_TT: _,
    Workshop_ItemDetails_Favorite_TT: _,
    Workshop_ItemDetails_ViewDependentItems_TT: _,
    Workshop_ItemDetails_Report_TT: _,
    Workshop_ItemDetails_Award_TT: _,
    Workshop_ItemDetails_AddToCollection_TT: _,
    Workshop_ItemDetails_FileSize: _,
    Workshop_ItemDetails_Stats_UniqueVisitors: _,
    Workshop_ItemDetails_Stats_CurrentSubscribers: _,
    Workshop_ItemDetails_Stats_CurrentFavorites: _,
    Workshop_ItemDetails_Stats_LifetimeFavorites: _,
    Workshop_ItemDetails_Stats_LifetimeSubscribers: _,
    Workshop_ItemDetails_Stats_LifetimePlaytimeSessions: _,
    Workshop_ItemDetails_ItemDependencies: _,
    Workshop_ItemDetails_RequiredDLC_Desc: _,
    Workshop_Collection_SubscribeToAll: _,
    Workshop_Collection_UnsubscribeFromAll: _,
    Workshop_Collection_SaveToCollection: _,
    Workshop_ItemDetails_ShowAllReactions: _,
    Workshop_ItemDetails_ReactionCount: _,
    Workshop_ItemDetails_ReactionCount_Plural: _,
    Workshop_ItemDetails_Tags_Title: _,
    Workshop_ItemDetails_Categories_Title: _,
    Workshop_ItemDetails_Description_Title: _,
    Workshop_ItemDetails_DependentItems: _,
    Workshop_ItemDetails_InCollections: _,
    Workshop_ItemDetails_InCollectionsByAuthor: _,
    Workshop_Dialog_Error: _,
    Workshop_Dialog_AccessDenied: _,
    Workshop_Dialog_Timeout: _,
    Workshop_Dialog_LimitExceeded: _,
    Workshop_Dialog_ErrorDesc: _,
    Workshop_Dialog_CollectionSubscribe: _,
    Workshop_Dialog_CollectionSubscribe_Desc: _,
    Workshop_Dialog_CollectionSubscribe_AddOnly: _,
    Workshop_Dialog_CollectionSubscribe_Overwrite: _,
    Workshop_Dialog_ItemDependencies: _,
    Workshop_Dialog_ItemDependencies_Desc1: _,
    Workshop_Dialog_ItemDependencies_Desc1_itemName: _,
    Workshop_Dialog_ItemDependencies_Desc2: _,
    Workshop_Dialog_ItemDependencies_Desc3: _,
    Workshop_Dialog_SubscribeJustThisItem: _,
    Workshop_Dialog_SubscribeAll: _,
    Workshop_Dialog_Report: _,
    Workshop_Dialog_Report_Desc: _,
    Workshop_Dialog_Report_Reason: _,
    Workshop_Dialog_Report_Reason_Desc: _,
    Workshop_Dialog_Report_DMCA_Desc: _,
    Workshop_Dialog_Report_Trademark_Desc: _,
    Workshop_Dialog_Report_Here: `itt`,
    Workshop_Dialog_AddToCollection: _,
    Workshop_Dialog_AddToCollection_Desc: _,
    Workshop_Dialog_AddToCollection_NoSavedCollections_Desc: _,
    Workshop_Dialog_AddToCollection_OK: _,
    Workshop_Dialog_AddToCollection_Create: _,
    Workshop_Dialog_SaveCollectionToCollection: _,
    Workshop_Dialog_SaveCollectionToCollection_Desc: _,
    Workshop_Dialog_SaveCollectionToCollection_New: _,
    Workshop_Dialog_SaveCollectionToCollection_Existing: _,
    Workshop_Dialog_SaveCollectionToCollection_NewPrompt: _,
    Workshop_Dialog_SaveCollectionToCollection_Select: _,
    Workshop_Collection_NumChildItems: _,
    Workshop_Collection_NumChildItems_Plural: _,
    Workshop_Collection_NumChildCollections: _,
    Workshop_Collection_NumChildCollections_Plural: _,
    Workshop_Collection_ViewMore: _,
    Workshop_About_PageDesc_Curation: _,
    Workshop_About_PageDesc_ReadyToUseContent1: _,
    Workshop_About_PageDesc_ReadyToUseContent2: _,
    Workshop_About_PageDesc_ReadyToUseContent_Mixed1: _,
    Workshop_About_PageDesc_ReadyToUseContent_Mixed2: _,
    Workshop_About_EnabledFeatures: _,
    Workshop_About_EnabledFeatures_Desc: _,
    Workshop_About_Feature_ReadyToUse: _,
    Workshop_About_Feature_ReadyToUse_Desc: _,
    Workshop_About_Feature_ReadyToUse_Mixed_Desc: _,
    Workshop_About_Feature_Branch_Versioning: _,
    Workshop_About_Feature_Branch_Versioning_Desc: _,
    Workshop_About_Feature_ItemCuration: _,
    Workshop_About_Feature_ItemCuration_Desc: _,
    Workshop_About_Feature_ItemCuration_Mixed_Desc: _,
    Workshop_About_Feature_ItemMtx: _,
    Workshop_About_Feature_ItemMtx_Desc: _,
    Workshop_About_Feature_Commerce: _,
    Workshop_About_Feature_Commerce_Desc: _,
    Workshop_About_Feature_AuthorRoyalties: _,
    Workshop_About_Feature_AuthorRoyalties_Desc: _,
    Workshop_About_Feature_ServiceProviders: _,
    Workshop_About_Feature_ServiceProviders_Desc: _,
    Workshop_About_Request_ServiceProviders: _,
    Workshop_About_RevenueShare: _,
    Workshop_About_RevenueShare_Desc: _,
    Workshop_About_RevenueShare_Link: _,
    Workshop_About_RevenueShare_Here: `ide`,
    Workshop_About_NumItems: _,
    Workshop_About_NumAcceptedItems: _,
    Workshop_About_RelatedLinks: _,
    Workshop_About_ViewOfficialDocs: _,
    Workshop_About_FindGuides: _,
    Workshop_About_FindGuides_Sub: _,
    Workshop_About_RefundLink_Sub: _,
    Workshop_About_WorkshopTerms: _,
    Workshop_About_WorkshopTerms_Sub: _,
    Workshop_About_section_ServiceProviders: _,
    Workshop_ServiceProviderRevenueSharing_ViewSite: _,
    Workshop_ServiceProviderRevenueSharing_ViewSteamProfile: _,
    Workshop_ServiceProvider_Category_Tools: _,
    Workshop_ServiceProvider_Category_Communities: _,
    Workshop_ServiceProvider_Category_Users: _,
    Workshop_GamepadUIAction_ViewDetails: _,
    Workshop_GamepadUIAction_QuickView: _,
    Workshop_Home_VotingQueue: _,
    Workshop_Home_VotingQueue_Desc: _,
    Workshop_Home_VotingQueue_Btn: _,
    Workshop_Home_VotingQueue_Count: _,
    Workshop_Home_VotingQueue_Count_Plural: _,
    Workshop_Home_MostPopular_SubTitle_Week: _,
    Workshop_Home_MostPopular_SubTitle_Month: _,
    Workshop_Home_MostPopular_SubTitle_ThreeMonths: _,
    Workshop_Home_MostPopular_SubTitle_SixMonths: _,
    Workshop_Home_MostPopular_SubTitle_Year: _,
    Workshop_Home_FromFollowedAuthors: _,
    Workshop_Home_FromFollowedAuthors_Desc: _,
    Workshop_Home_FromFollowedAuthors_Btn: _,
    Workshop_Home_AcceptedItems: _,
    Workshop_Home_AcceptedItems_Desc: _,
    Workshop_Home_AcceptedItems_Btn: _,
    Workshop_Home_MostPopular: _,
    Workshop_Home_MostPopular_LongTerm: _,
    Workshop_Home_MostPopular_LongTerm_Desc: _,
    Workshop_Home_MostPopular_LongTerm_Btn: _,
    Workshop_Home_MostSubscribed: _,
    Workshop_Home_MostSubscribed_Desc: _,
    Workshop_Home_MostSubscribed_Btn: _,
    Workshop_Home_MostRecent: `Új`,
    Workshop_Home_MostRecent_Desc: _,
    Workshop_Home_MostRecent_Btn: _,
    Workshop_Home_MostPlaytime: _,
    Workshop_Home_MostPlaytime_Btn: _,
    Workshop_Home_LastUpdated: _,
    Workshop_Home_LastUpdated_Desc: _,
    Workshop_Home_LastUpdated_Btn: _,
    Workshop_Home_FriendsFavorites: _,
    Workshop_Home_FriendsFavorites_Desc: _,
    Workshop_Home_FriendsFavorites_Btn: _,
    Workshop_Home_NumParentItems: _,
    Workshop_Home_NumParentItems_Desc: _,
    Workshop_Home_NumParentItems_Btn: _,
    Workshop_Home_MostPopularMerch: _,
    Workshop_Home_MostPopularMerch_Btn: _,
    Workshop_Home_ViewAll: _,
    Workshop_Home_YourFavorites: _,
    Workshop_Home_YourFavorites_Btn: _,
    Workshop_Home_YourPlayed: _,
    Workshop_Home_YourPlayed_Btn: _,
    Workshop_Home_YourSubscriptions: _,
    Workshop_Home_YourSubscriptions_Btn: _,
    Workshop_Home_YourFiles_LastUpdated: _,
    Workshop_Home_SpecialEvent_Title_Tag: _,
    Workshop_Home_SpecialEvent_Link: _,
    Workshop_ItemTooltip_FriendsWhoFavorited: _,
    Workshop_ItemTooltip_FriendsWhoFavorited_Plural: _,
    SharedFiles_TF2_Tab_Items_ReadyToUse: _,
    SharedFiles_TF2_Tab_Items_Mtx: _,
    SharedFiles_Dota2_Tab_Items_ReadyToUse: _,
    SharedFiles_Dota2_Tab_Items_Mtx: _,
    SharedFiles_Dota2_HeroPicker: _,
    SharedFiles_CSGO_Tab_Items_ReadyToUse: _,
    SharedFiles_CSGO_Tab_Items_Mtx: _,
  };
export {
  _ as Error_Encountered,
  _ as Error_Sorry,
  _ as Error_TooManyRequests_Description,
  _ as Header_App_WorkshopTitle,
  _ as Header_WorkshopTitle,
  _ as SharedFiles_Browse_Trend_Option_AllTime,
  _ as SharedFiles_Browse_Trend_Option_Month,
  _ as SharedFiles_Browse_Trend_Option_OneYear,
  _ as SharedFiles_Browse_Trend_Option_SixMonths,
  _ as SharedFiles_Browse_Trend_Option_ThreeMonths,
  _ as SharedFiles_Browse_Trend_Option_Today,
  _ as SharedFiles_Browse_Trend_Option_Week,
  _ as SharedFiles_CSGO_Tab_Items_Mtx,
  _ as SharedFiles_CSGO_Tab_Items_ReadyToUse,
  _ as SharedFiles_Dota2_HeroPicker,
  _ as SharedFiles_Dota2_Tab_Items_Mtx,
  _ as SharedFiles_Dota2_Tab_Items_ReadyToUse,
  _ as SharedFiles_TF2_Tab_Items_Mtx,
  _ as SharedFiles_TF2_Tab_Items_ReadyToUse,
  _ as Workshop_About,
  _ as Workshop_About_EnabledFeatures,
  _ as Workshop_About_EnabledFeatures_Desc,
  _ as Workshop_About_Feature_AuthorRoyalties,
  _ as Workshop_About_Feature_AuthorRoyalties_Desc,
  _ as Workshop_About_Feature_Branch_Versioning,
  _ as Workshop_About_Feature_Branch_Versioning_Desc,
  _ as Workshop_About_Feature_Commerce,
  _ as Workshop_About_Feature_Commerce_Desc,
  _ as Workshop_About_Feature_ItemCuration,
  _ as Workshop_About_Feature_ItemCuration_Desc,
  _ as Workshop_About_Feature_ItemCuration_Mixed_Desc,
  _ as Workshop_About_Feature_ItemMtx,
  _ as Workshop_About_Feature_ItemMtx_Desc,
  _ as Workshop_About_Feature_ReadyToUse,
  _ as Workshop_About_Feature_ReadyToUse_Desc,
  _ as Workshop_About_Feature_ReadyToUse_Mixed_Desc,
  _ as Workshop_About_Feature_ServiceProviders,
  _ as Workshop_About_Feature_ServiceProviders_Desc,
  _ as Workshop_About_FindGuides,
  _ as Workshop_About_FindGuides_Sub,
  _ as Workshop_About_NumAcceptedItems,
  _ as Workshop_About_NumItems,
  _ as Workshop_About_PageDesc_Curation,
  _ as Workshop_About_PageDesc_ReadyToUseContent1,
  _ as Workshop_About_PageDesc_ReadyToUseContent2,
  _ as Workshop_About_PageDesc_ReadyToUseContent_Mixed1,
  _ as Workshop_About_PageDesc_ReadyToUseContent_Mixed2,
  _ as Workshop_About_RefundLink_Sub,
  _ as Workshop_About_RelatedLinks,
  _ as Workshop_About_Request_ServiceProviders,
  _ as Workshop_About_RevenueShare,
  _ as Workshop_About_RevenueShare_Desc,
  _ as Workshop_About_RevenueShare_Here,
  _ as Workshop_About_RevenueShare_Link,
  _ as Workshop_About_ViewOfficialDocs,
  _ as Workshop_About_WorkshopTerms,
  _ as Workshop_About_WorkshopTerms_Sub,
  _ as Workshop_About_section_ServiceProviders,
  _ as Workshop_AcceptedForGame,
  _ as Workshop_AcceptedMerch,
  _ as Workshop_Admin_View,
  _ as Workshop_ApplyFilters,
  _ as Workshop_BrowseSort_AcceptedTime,
  _ as Workshop_BrowseSort_AdminOption,
  _ as Workshop_BrowseSort_BanContentCheck,
  _ as Workshop_BrowseSort_Combined,
  _ as Workshop_BrowseSort_CuratedAdmin,
  _ as Workshop_BrowseSort_Inappropriate,
  _ as Workshop_BrowseSort_LastUpdated,
  _ as Workshop_BrowseSort_MostPopular,
  _ as Workshop_BrowseSort_MostRecent,
  _ as Workshop_BrowseSort_MostUpVotes,
  _ as Workshop_BrowseSort_Nominee,
  _ as Workshop_BrowseSort_NumParentCollections,
  _ as Workshop_BrowseSort_NumParentItems,
  _ as Workshop_BrowseSort_Playtime,
  _ as Workshop_BrowseSort_PlaytimeAverage,
  _ as Workshop_BrowseSort_PlaytimeAverageTotal,
  _ as Workshop_BrowseSort_PlaytimeSessions,
  _ as Workshop_BrowseSort_PlaytimeSessionsTotal,
  _ as Workshop_BrowseSort_PlaytimeTotal,
  _ as Workshop_BrowseSort_Rated,
  _ as Workshop_BrowseSort_Reported,
  _ as Workshop_BrowseSort_SearchRelevance,
  _ as Workshop_BrowseSort_SortOrder,
  _ as Workshop_BrowseSort_TimeFrame,
  _ as Workshop_BrowseSort_ToRate,
  _ as Workshop_BrowseSort_TopRated,
  _ as Workshop_BrowseSort_TotalUniqueSubscribers,
  _ as Workshop_BrowseSort_TotalVotes,
  _ as Workshop_Browse_Author_Link,
  _ as Workshop_Browsing,
  _ as Workshop_Browsing_Merchandise_Desc,
  _ as Workshop_Browsing_Mtx_Desc,
  _ as Workshop_Browsing_ReadyToUse_Desc,
  _ as Workshop_Collection_NumChildCollections,
  _ as Workshop_Collection_NumChildCollections_Plural,
  _ as Workshop_Collection_NumChildItems,
  _ as Workshop_Collection_NumChildItems_Plural,
  _ as Workshop_Collection_SaveToCollection,
  _ as Workshop_Collection_SubscribeToAll,
  _ as Workshop_Collection_UnsubscribeFromAll,
  _ as Workshop_Collection_ViewMore,
  _ as Workshop_CreateCollection,
  _ as Workshop_CreateMerchandise,
  _ as Workshop_DateFilter_And,
  _ as Workshop_DateFilter_Between,
  _ as Workshop_DateFilter_FilterByDate,
  _ as Workshop_DateFilter_TimeCreated,
  _ as Workshop_DateFilter_TimeCreated_After,
  _ as Workshop_DateFilter_TimeCreated_Before,
  _ as Workshop_DateFilter_TimeCreated_Between,
  _ as Workshop_DateFilter_TimeUpdated,
  _ as Workshop_DateFilter_TimeUpdated_After,
  _ as Workshop_DateFilter_TimeUpdated_Before,
  _ as Workshop_DateFilter_TimeUpdated_Between,
  _ as Workshop_Dialog_AccessDenied,
  _ as Workshop_Dialog_AddToCollection,
  _ as Workshop_Dialog_AddToCollection_Create,
  _ as Workshop_Dialog_AddToCollection_Desc,
  _ as Workshop_Dialog_AddToCollection_NoSavedCollections_Desc,
  _ as Workshop_Dialog_AddToCollection_OK,
  _ as Workshop_Dialog_CollectionSubscribe,
  _ as Workshop_Dialog_CollectionSubscribe_AddOnly,
  _ as Workshop_Dialog_CollectionSubscribe_Desc,
  _ as Workshop_Dialog_CollectionSubscribe_Overwrite,
  _ as Workshop_Dialog_Error,
  _ as Workshop_Dialog_ErrorDesc,
  _ as Workshop_Dialog_ItemDependencies,
  _ as Workshop_Dialog_ItemDependencies_Desc1,
  _ as Workshop_Dialog_ItemDependencies_Desc1_itemName,
  _ as Workshop_Dialog_ItemDependencies_Desc2,
  _ as Workshop_Dialog_ItemDependencies_Desc3,
  _ as Workshop_Dialog_LimitExceeded,
  _ as Workshop_Dialog_Report,
  _ as Workshop_Dialog_Report_DMCA_Desc,
  _ as Workshop_Dialog_Report_Desc,
  _ as Workshop_Dialog_Report_Here,
  _ as Workshop_Dialog_Report_Reason,
  _ as Workshop_Dialog_Report_Reason_Desc,
  _ as Workshop_Dialog_Report_Trademark_Desc,
  _ as Workshop_Dialog_SaveCollectionToCollection,
  _ as Workshop_Dialog_SaveCollectionToCollection_Desc,
  _ as Workshop_Dialog_SaveCollectionToCollection_Existing,
  _ as Workshop_Dialog_SaveCollectionToCollection_New,
  _ as Workshop_Dialog_SaveCollectionToCollection_NewPrompt,
  _ as Workshop_Dialog_SaveCollectionToCollection_Select,
  _ as Workshop_Dialog_SubscribeAll,
  _ as Workshop_Dialog_SubscribeJustThisItem,
  _ as Workshop_Dialog_Timeout,
  _ as Workshop_DimmedItems_BlockedCreators,
  _ as Workshop_DimmedItems_Reported,
  _ as Workshop_DimmedItems_Subscribed,
  _ as Workshop_DimmedItems_Title,
  _ as Workshop_DimmedItems_VotedDown,
  _ as Workshop_DimmedItems_VotedUp,
  _ as Workshop_Error_Browse_Desc,
  _ as Workshop_Error_Loading,
  _ as Workshop_Error_Title,
  _ as Workshop_ExcludeOwnedDLC_Filter,
  _ as Workshop_ExitReact_Link,
  _ as Workshop_FiltersMenu_State_Collapsed,
  _ as Workshop_FiltersMenu_State_Left,
  _ as Workshop_FiltersMenu_State_Right,
  _ as Workshop_FiltersMenu_State_Title,
  _ as Workshop_Filters_ClearBtn,
  _ as Workshop_Flag_Incompatible_Checkbox,
  _ as Workshop_Flag_Incompatible_Checkbox_Desc,
  _ as Workshop_GamepadUIAction_QuickView,
  _ as Workshop_GamepadUIAction_ViewDetails,
  _ as Workshop_Home_AcceptedItems,
  _ as Workshop_Home_AcceptedItems_Btn,
  _ as Workshop_Home_AcceptedItems_Desc,
  _ as Workshop_Home_FriendsFavorites,
  _ as Workshop_Home_FriendsFavorites_Btn,
  _ as Workshop_Home_FriendsFavorites_Desc,
  _ as Workshop_Home_FromFollowedAuthors,
  _ as Workshop_Home_FromFollowedAuthors_Btn,
  _ as Workshop_Home_FromFollowedAuthors_Desc,
  _ as Workshop_Home_LastUpdated,
  _ as Workshop_Home_LastUpdated_Btn,
  _ as Workshop_Home_LastUpdated_Desc,
  _ as Workshop_Home_MostPlaytime,
  _ as Workshop_Home_MostPlaytime_Btn,
  _ as Workshop_Home_MostPopular,
  _ as Workshop_Home_MostPopularMerch,
  _ as Workshop_Home_MostPopularMerch_Btn,
  _ as Workshop_Home_MostPopular_LongTerm,
  _ as Workshop_Home_MostPopular_LongTerm_Btn,
  _ as Workshop_Home_MostPopular_LongTerm_Desc,
  _ as Workshop_Home_MostPopular_SubTitle_Month,
  _ as Workshop_Home_MostPopular_SubTitle_SixMonths,
  _ as Workshop_Home_MostPopular_SubTitle_ThreeMonths,
  _ as Workshop_Home_MostPopular_SubTitle_Week,
  _ as Workshop_Home_MostPopular_SubTitle_Year,
  _ as Workshop_Home_MostRecent,
  _ as Workshop_Home_MostRecent_Btn,
  _ as Workshop_Home_MostRecent_Desc,
  _ as Workshop_Home_MostSubscribed,
  _ as Workshop_Home_MostSubscribed_Btn,
  _ as Workshop_Home_MostSubscribed_Desc,
  _ as Workshop_Home_NumParentItems,
  _ as Workshop_Home_NumParentItems_Btn,
  _ as Workshop_Home_NumParentItems_Desc,
  _ as Workshop_Home_SpecialEvent_Link,
  _ as Workshop_Home_SpecialEvent_Title_Tag,
  _ as Workshop_Home_ViewAll,
  _ as Workshop_Home_VotingQueue,
  _ as Workshop_Home_VotingQueue_Btn,
  _ as Workshop_Home_VotingQueue_Count,
  _ as Workshop_Home_VotingQueue_Count_Plural,
  _ as Workshop_Home_VotingQueue_Desc,
  _ as Workshop_Home_YourFavorites,
  _ as Workshop_Home_YourFavorites_Btn,
  _ as Workshop_Home_YourFiles_LastUpdated,
  _ as Workshop_Home_YourPlayed,
  _ as Workshop_Home_YourPlayed_Btn,
  _ as Workshop_Home_YourSubscriptions,
  _ as Workshop_Home_YourSubscriptions_Btn,
  _ as Workshop_IncludeOwnedDLC_Filter,
  _ as Workshop_ItemDetails_AddToCollection,
  _ as Workshop_ItemDetails_AddToCollection_TT,
  _ as Workshop_ItemDetails_Award_TT,
  _ as Workshop_ItemDetails_Categories_Title,
  _ as Workshop_ItemDetails_CreatedBy,
  _ as Workshop_ItemDetails_DependentItems,
  _ as Workshop_ItemDetails_Description_Title,
  _ as Workshop_ItemDetails_Favorite,
  _ as Workshop_ItemDetails_Favorite_TT,
  _ as Workshop_ItemDetails_Favorited,
  _ as Workshop_ItemDetails_FileSize,
  _ as Workshop_ItemDetails_InCollections,
  _ as Workshop_ItemDetails_InCollectionsByAuthor,
  _ as Workshop_ItemDetails_ItemDependencies,
  _ as Workshop_ItemDetails_NotEnoughRatings,
  _ as Workshop_ItemDetails_NumRatings,
  _ as Workshop_ItemDetails_NumRatings_Plural,
  _ as Workshop_ItemDetails_ReactionCount,
  _ as Workshop_ItemDetails_ReactionCount_Plural,
  _ as Workshop_ItemDetails_Report_TT,
  _ as Workshop_ItemDetails_RequiredDLC_Desc,
  _ as Workshop_ItemDetails_SaveCollectionToCollection,
  _ as Workshop_ItemDetails_ShowAllReactions,
  _ as Workshop_ItemDetails_Signin_TT,
  _ as Workshop_ItemDetails_Stats_CurrentFavorites,
  _ as Workshop_ItemDetails_Stats_CurrentSubscribers,
  _ as Workshop_ItemDetails_Stats_LifetimeFavorites,
  _ as Workshop_ItemDetails_Stats_LifetimePlaytimeSessions,
  _ as Workshop_ItemDetails_Stats_LifetimeSubscribers,
  _ as Workshop_ItemDetails_Stats_UniqueVisitors,
  _ as Workshop_ItemDetails_Subscribe,
  _ as Workshop_ItemDetails_Subscribe_TT,
  _ as Workshop_ItemDetails_Subscribed,
  _ as Workshop_ItemDetails_Tab_ChangeNotes,
  _ as Workshop_ItemDetails_Tab_Comments,
  _ as Workshop_ItemDetails_Tab_Description,
  _ as Workshop_ItemDetails_Tab_Discussions,
  _ as Workshop_ItemDetails_Tab_Stats,
  _ as Workshop_ItemDetails_Tab_Updates,
  _ as Workshop_ItemDetails_Tags_Title,
  _ as Workshop_ItemDetails_TimestampCreated,
  _ as Workshop_ItemDetails_TimestampUpdated,
  _ as Workshop_ItemDetails_TimestampWithTime,
  _ as Workshop_ItemDetails_Title,
  _ as Workshop_ItemDetails_Unfavorite,
  _ as Workshop_ItemDetails_Unsubscribe,
  _ as Workshop_ItemDetails_Unsubscribe_TT,
  _ as Workshop_ItemDetails_ViewDependentItems,
  _ as Workshop_ItemDetails_ViewDependentItems_TT,
  _ as Workshop_ItemTooltip_FriendsWhoFavorited,
  _ as Workshop_ItemTooltip_FriendsWhoFavorited_Plural,
  _ as Workshop_Item_QuickView,
  _ as Workshop_Item_QuickView_ExpandBtn,
  _ as Workshop_LearnMore,
  _ as Workshop_Menu_About,
  _ as Workshop_Menu_Browse,
  _ as Workshop_Menu_Discussions,
  _ as Workshop_Menu_Home,
  _ as Workshop_Menu_Search,
  _ as Workshop_Menu_YourItems,
  _ as Workshop_NumPerPage,
  _ as Workshop_NumResults,
  _ as Workshop_NumResults_Plural,
  _ as Workshop_OfficialContent,
  _ as Workshop_OwnedDLC_All_Filter,
  _ as Workshop_OwnedDLC_More_Filter,
  _ as Workshop_OwnedDLC_None_Filter,
  _ as Workshop_PagingControls,
  _ as Workshop_RequireApproval,
  _ as Workshop_RequiredDLC_ExcludeUnowned,
  _ as Workshop_RequiredDLC_Filter,
  _ as Workshop_RequiredDLC_Header,
  _ as Workshop_RequiredDLC_IncludeOwned,
  _ as Workshop_RequiredDLC_NameFilter,
  _ as Workshop_Saved_Queries,
  _ as Workshop_Saved_Queries_Delete_Btn,
  _ as Workshop_Saved_Queries_Delete_Desc,
  _ as Workshop_Saved_Queries_Delete_Title,
  _ as Workshop_Saved_Queries_Save_Btn,
  _ as Workshop_Saved_Queries_Save_Desc,
  _ as Workshop_Saved_Queries_Save_Desc_Long,
  _ as Workshop_Saved_Queries_Save_New,
  _ as Workshop_Saved_Queries_Save_Title,
  _ as Workshop_Saved_Queries_Update,
  _ as Workshop_SearchResults_Flag_Accepted,
  _ as Workshop_SearchResults_Flag_Incompatible,
  _ as Workshop_SearchResults_KVTag,
  _ as Workshop_SearchResults_SearchText,
  _ as Workshop_SearchResults_SearchText_DescriptionOnly,
  _ as Workshop_SearchResults_SearchText_TitleOnly,
  _ as Workshop_SearchResults_Tag,
  _ as Workshop_SearchTarget_All,
  _ as Workshop_SearchTarget_Description,
  _ as Workshop_SearchTarget_MenuTitle,
  _ as Workshop_SearchTarget_Title,
  _ as Workshop_Search_Help,
  _ as Workshop_Search_Help_Advanced,
  _ as Workshop_Search_Help_AdvancedExample1,
  _ as Workshop_Search_Help_AdvancedExample2,
  _ as Workshop_Search_Help_Example1,
  _ as Workshop_Search_Help_Example2,
  _ as Workshop_Search_Help_Example3,
  _ as Workshop_Search_Help_Example_Blue,
  _ as Workshop_Search_Help_Example_Green,
  _ as Workshop_Search_Help_Example_Red,
  _ as Workshop_Search_Help_Example_Room,
  _ as Workshop_SearchedForChild,
  _ as Workshop_SearchedForRequiredItem,
  _ as Workshop_Section_Collections,
  _ as Workshop_Section_Merchandise,
  _ as Workshop_Section_Mtx,
  _ as Workshop_Section_ReadyToUse,
  _ as Workshop_Section_Videos,
  _ as Workshop_ServiceProviderRevenueSharing_ViewSite,
  _ as Workshop_ServiceProviderRevenueSharing_ViewSteamProfile,
  _ as Workshop_ServiceProvider_Category_Communities,
  _ as Workshop_ServiceProvider_Category_Tools,
  _ as Workshop_ServiceProvider_Category_Users,
  _ as Workshop_SortBy,
  _ as Workshop_SpecialFilter_AcceptedForUse,
  _ as Workshop_SpecialFilter_CreatedByFollowed,
  _ as Workshop_SpecialFilter_CreatedByFriends,
  _ as Workshop_SpecialFilter_Desc,
  _ as Workshop_SpecialFilter_FavoritedByFriends,
  _ as Workshop_SpecialFilter_None,
  _ as Workshop_SpecialFilter_ParentCollections,
  _ as Workshop_SpecialFilter_ParentItems,
  _ as Workshop_SpecialFilter_Reported,
  _ as Workshop_StatusIcon_TT_Accepted,
  _ as Workshop_StatusIcon_TT_BlockedCreator,
  _ as Workshop_StatusIcon_TT_Favorited,
  _ as Workshop_StatusIcon_TT_Incompatible,
  _ as Workshop_StatusIcon_TT_Played,
  _ as Workshop_StatusIcon_TT_Reported,
  _ as Workshop_StatusIcon_TT_Subscribed,
  _ as Workshop_StatusIcon_TT_VotedDown,
  _ as Workshop_StatusIcon_TT_VotedUp,
  _ as Workshop_SubMenu_LegalAgreement,
  _ as Workshop_SubMenu_ViewYourRevenue,
  _ as Workshop_SubMenu_ViewYourRevenue_Desc,
  _ as Workshop_SubMenu_VotingQueue,
  _ as Workshop_SubMenu_YourCollections,
  _ as Workshop_SubMenu_YourFavorites,
  _ as Workshop_SubMenu_YourItems,
  _ as Workshop_SubMenu_YourPaymentInfo,
  _ as Workshop_SubMenu_YourPlayed,
  _ as Workshop_SubMenu_YourSubscriptions,
  _ as Workshop_SubMenu_YourVotingQueue,
  _ as Workshop_Tag_NoneSpecified,
  _ as default,
  _ as language,
};
