var _ = `Prohledat komunitní trh`,
  _ = `Resetovat filtry`,
  _ = `Hledat`,
  _ = `Vybrat hru...`,
  _ = `Vaše nedávno hrané hry s položkami`,
  _ = `Populární hry s položkami`,
  _ = `Zrušit výběr`,
  _ = `Hledat...`,
  _ = `Hledat pod %1$s...`,
  _ = `Herní položky`,
  _ = `Komunitní položky`,
  _ = `Typ položky`,
  _ = `Tato hra nemá žádné filtry pro komunitní trh.`,
  _ = `Dostupné položky se zobrazí po kliknutí na „Hledat“.`,
  _ = `Při načítání filtrů pro tuto hru došlo k chybě.`,
  _ = `Cena`,
  _ = `Min. cena`,
  _ = `Max. cena`,
  _ = `Vše`,
  _ = `Jiné`,
  _ = `Filtrovat...`,
  _ = `Filtrovat podle hry...`,
  _ = `Beta verze – Podělte se s námi o svůj názor`,
  _ = `Hledat v názvech položek na trhu...`,
  _ = `Bedny se zbraněmi, kapsle se samolepkami, suvenýry atd.`,
  _ = `Komunitní trh`,
  _ = `Nakupujte a prodávejte položky ostatním členům komunity za prostředky peněženky.`,
  _ = `Více informací`,
  _ = `Prohledat komunitní trh`,
  _ = `Nové hledání...`,
  _ = `Filtry`,
  _ = `Zavřít novou verzi komunitního trhu`,
  _ = `Zpětná vazba`,
  _ = `Tato položka představuje zboží. To znamená, že jednotlivé položky jsou stejné a nejsou mezi nimi žádné rozdíly. Místo nákupu konkrétní položky ze seznamu jednotlivých nabídek pouze vytvoříte příkaz k nákupu za Vámi určenou kupní cenu. Nejlevnější nabídky k prodeji jsou automaticky přiřazovány k příkazům s nejvyšší kupní cenou.`,
  _ = `Byl nalezen %1$s výsledek`,
  _ = `Bylo nalezeno %1$s výsledků`,
  _ = `Nalezené výsledky (%1$s) pro:`,
  _ = `Nalezené výsledky (%1$s) pro:`,
  _ = `Výsledky pro:`,
  _ = `Byla nalezena %2$s nabídka`,
  _ = `Bylo nalezeno %2$s nabídek`,
  _ = `Popularita`,
  _ = `Název (od A do Z)`,
  _ = `Název (od Z do A)`,
  _ = `Cena (od nejnižší)`,
  _ = `Cena (od nejvyšší)`,
  _ = `Množství (od nejmenšího)`,
  _ = `Množství (od největšího)`,
  _ = `%1$s (od nejnižšího)`,
  _ = `%1$s (od nejvyššího)`,
  _ = `Řazení:`,
  _ = `Hledat`,
  _ = `Hledat...`,
  _ = `Zakoupit`,
  _ = `Prodat`,
  _ = `Zakoupit`,
  _ = `Vytvořit příkaz k nákupu...`,
  _ = `Vytvoření příkazu k nákupu`,
  _ = `Zavřít`,
  _ = `Množství k prodeji: %1$s`,
  _ = `Množství: %1$s`,
  _ = `Od %1$s`,
  _ = `%1$s`,
  _ = `Filtrovat výsledky...`,
  _ = `Pokročilé vyhledávání`,
  _ = `Pokročilé vyhledávání`,
  _ = `Hledat položku...`,
  _ = `Domovská stránka`,
  _ = `Populární hry`,
  _ = `Vyhledávat i v popisech`,
  _ = `Některé starší položky mají své vlastnosti určené v popisech, se kterými neumí níže nabízené filtry pracovat. Tato možnost zajistí, že hledaný text bude porovnán nejen proti názvům položek, ale také proti jejich popisům.`,
  _ = `Filtry`,
  _ = `Resetovat vyhledávání`,
  _ = `Zadejte text pro filtrování...`,
  _ = `Po zakoupení této položky ji:`,
  _ = `nebudete moci jeden den použít při obchodování`,
  _ = `nebudete moci jeden týden použít při obchodování`,
  _ = `nebudete moci %1$s dní použít při obchodování`,
  _ = `nebudete moci použít při obchodování`,
  _ = `nebudete moci jeden den vystavit na komunitním trhu`,
  _ = `nebudete moci jeden týden vystavit na komunitním trhu`,
  _ = `nebudete moci %1$s dní vystavit na komunitním trhu`,
  _ = `budete moci okamžitě znovu vystavit na komunitním trhu`,
  _ = `%1$s: %2$s – %3$s`,
  _ = `%1$s: „%2$s“`,
  _ = `Zakoupení položky`,
  _ = `Název`,
  _ = `Cena`,
  _ = `Mezisoučet:`,
  _ = `Poplatek hry %1$s (%2$s %):`,
  _ = `Poplatek hry (%1$s %):`,
  _ = `Poplatek za transakci ve službě Steam (%1$s %):`,
  _ = `Místní daň z obratu (%1$s):`,
  _ = `Celkem:`,
  _ = `Způsob platby:`,
  _ = `Moje peněženka služby Steam`,
  _ = `Účet služby Steam:`,
  _ = `Fakturační adresa:`,
  _ = `Křestní jméno`,
  _ = `Příjmení`,
  _ = `Fakturační adresa`,
  _ = `Fakturační adresa (2. řádek)`,
  _ = `Město`,
  _ = `Stát/provincie/kraj`,
  _ = `Poštovní směrovací číslo`,
  _ = `Země`,
  _ = `Uložit adresu pro zjednodušení dalších nákupů`,
  _ = `Přidat prostředky`,
  _ = `Zakoupit`,
  _ = `Souhlasím s\xA0podmínkami %1$s (poslední změna %2$s)`,
  _ = `Smlouvy o užívání služby Steam`,
  _ = `Chcete-li dokončit tuto transakci, musíte souhlasit s podmínkami Smlouvy o užívání služby Steam.`,
  _ = `Kliknutím na tlačítko „Zakoupit“ souhlasíte s tím, že Vám bude poskytnut okamžitý přístup k tomuto digitálnímu obsahu, a tudíž ztratíte jakoukoli možnost od tohoto nákupu odstoupit – tento nákup tedy bude konečný.`,
  _ = `Při nakupování Vaší položky došlo k chybě. Nabídka byla pravděpodobně odebrána. Obnovte stránku a zkuste to znovu.`,
  _ = `Při nakupování Vaší položky došlo k chybě. Něco se pokazilo při čekání na Vaše potvrzení této akce. Obnovte stránku a zkuste to znovu.`,
  _ = `Následující pole jsou povinná:`,
  _ = `Zadejte platnou armádní adresu.`,
  _ = `Zadejte platné poštovní směrovací číslo.`,
  _ = `Blahopřejeme k\xA0nákupu! Svoji novou položku si můžete prohlédnout v <1>inventáři</1>.`,
  _ = `Zobrazit inventář`,
  _ = `Je vyžadováno dodatečné potvrzení`,
  _ = `Čeká se na Vaše potvrzení tohoto nákupu...`,
  _ = `Některé nákupy vyžadují dodatečné potvrzení prostřednictvím mobilní aplikace služby Steam.`,
  _ = `Některé nákupy vyžadují dodatečné potvrzení prostřednictvím e-mailu.`,
  _ = `Některé nákupy vyžadují dodatečné potvrzení prostřednictvím mobilní aplikace služby Steam nebo e-mailu.`,
  _ = `Potvrďte svůj nákup prostřednictvím mobilní aplikace služby Steam...`,
  _ = `Potvrďte svůj nákup prostřednictvím e-mailu...`,
  _ = `Potvrďte svůj nákup prostřednictvím mobilní aplikace služby Steam nebo e-mailu...`,
  _ = `Nákup byl úspěšně dokončen`,
  _ = `Zavřít`,
  _ = `Zobrazit inventář`,
  _ = `Uložit adresu pro zjednodušení dalších nákupů`,
  _ = `Tato nabídka již není dostupná`,
  _ = `Nedostupná`,
  _ = `Tato nabídka již není dostupná.`,
  _ = `(Moje nabídka)`,
  _ = `Zakoupení položky %1$s`,
  _ = `Vytvořit příkaz k nákupu`,
  _ = `Jaký typ položky si chcete zakoupit?`,
  _ = `Vyberte položku...`,
  _ = `Jakou částku chcete zaplatit:`,
  _ = `(za 1 položku)`,
  _ = `Jaké množství chcete zakoupit:`,
  _ = `Maximální cena %1$s:`,
  _ = `Toto je nejvyšší možná částka, kterou za tuto transakci potenciálně utratíte. Položky budou zakoupeny za nejnižší dostupnou cenu, takže Vám z této částky může i něco zbýt.`,
  _ = `Vyhledávání položek odpovídajících Vámi požadované ceně...`,
  _ = `Nákup byl úspěšný! Tato položka je nyní ve Vašem inventáři a e-mailem Vám bylo zasláno potvrzení o nákupu.`,
  _ = `Povedlo se! Váš příkaz k nákupu byl vytvořen.`,
  _ = `Jakmile bude nákup proveden, budete automaticky upozorněni pomocí e-mailu. Příkaz k nákupu můžete zrušit navrchu této stránky nebo na domovské stránce komunitního trhu.`,
  _ = `Omlouváme se! Servery služby Steam se nám neozvaly ohledně Vašeho příkazu. Zkontrolujte, jestli opravdu došlo k jeho vytvoření. Pokud ne, zkuste to později znovu.`,
  _ = `Minimální cena za položku je %1$s`,
  _ = `%1$s nebo méně`,
  _ = `%1$s nebo více`,
  _ = `Cena`,
  _ = `Množství`,
  _ = `%1$s na prodej s cenou od %2$s`,
  _ = `Pro tuto položku neexistují žádné aktivní nabídky.`,
  _ = `%1$s žádostí o nákup za %2$s nebo méně`,
  _ = `Pro tuto položku neexistují žádné aktivní příkazy.`,
  _ = `Pro zobrazení informací o příkazu vyberte záložku výše.`,
  _ = `Nevidíte požadovanou položku nebo cenu?`,
  _ = `Nevidíte cenu, která by se Vám zamlouvala?`,
  _ = `Všechny příkazy k nákupu a nabídky k prodeji`,
  _ = `1 příkaz k nákupu za %2$s`,
  _ = `%1$s příkazů k nákupu za %2$s nebo více`,
  _ = `1 nabídka k prodeji za %2$s`,
  _ = `%1$s nabídek k prodeji za %2$s nebo méně`,
  _ = `1 příkaz k nákupu za <1>%2$s</1>`,
  _ = `%3$s příkazy k nákupu za <1>%2$s nebo méně</1>`,
  _ = `Medián cen`,
  _ = `Týden`,
  _ = `Měsíc`,
  _ = `Rok`,
  _ = `Od nepaměti`,
  _ = `%1$s prodáno`,
  _ = `Cena`,
  _ = `Množství`,
  _ = `Pro toto časové rozmezí neexistují žádná data`,
  _ = `Žádná data`,
  _ = `–`,
  _ = `NÁZEV`,
  _ = `CENA`,
  _ = `MNOŽSTVÍ`,
  _ = `VYSTAVENO`,
  _ = `Zrušit`,
  _ = `Odebrat`,
  _ = `Moje nabídky a příkazy`,
  _ = `Nabídky k prodeji`,
  _ = `Příkazy k nákupu`,
  _ = `Co chci koupit`,
  _ = `Co chci prodat`,
  _ = `Při načítání nabídek a příkazů pro tuto položku došlo k chybě.`,
  _ = `Pro tuto položku nemáte žádné aktivní nabídky k prodeji.`,
  _ = `Pro tuto položku nemáte žádné aktivní příkazy k nákupu.`,
  _ = `Neprodáváte žádnou tuto položku. Prodejte položky ze svého inventáře nebo na této stránce klikněte na tlačítko „Prodat“.`,
  _ = `Množství: %1$s`,
  _ = `Zobrazit všechny (%1$s)`,
  _ = `Při rušení Vašeho příkazu došlo k chybě. Zkuste to později znovu.`,
  _ = `Při odebírání Vaší nabídky došlo k chybě. Zkuste to později znovu.`,
  _ = `Odebrat nabídku`,
  _ = `Opravdu chcete odebrat nabídku položky %1$s a vrátit položku do svého inventáře?`,
  _ = `Opravdu chcete odebrat tuto nabídku a vrátit položku do svého inventáře?`,
  _ = `Ano, odebrat nabídku`,
  _ = `Ne`,
  _ = `Vaše nabídka byla úspěšně odebrána.`,
  _ = `Vyberte položku ze svého inventáře`,
  _ = `Co je příkaz k nákupu?`,
  _ = `Pomocí příkazu k nákupu určíte, jakou částku chcete za položku zaplatit, a až bude položka za tuto cenu dostupná, dojde k jejímu automatickému zakoupení.`,
  _ = `Služba Steam zajistí, že pro zakoupení bude použita nejnižší možná cena.`,
  _ = `Konkrétně u této položky budou k příkazům k nákupu vždy nalezeny nabídky za nejnižší cenu, nezávisle na unikátních vlastnostech položek.`,
  _ = `%1$s a vyšší`,
  _ = `Omlouváme se!`,
  _ = `Při zpracovávání Vašeho požadavku došlo k\xA0chybě:`,
  _ = `Odeslali jste příliš mnoho požadavků. Počkejte a zkuste to později znovu.`,
  _ = `Možný obsah:`,
  _ = `Při načítání tohoto obsahu došlo k chybě.`,
  _ = `Požadovaná položka nemusí existovat, nebo mohla nastat dočasná chyba bránící v jejím načtení. Zkuste to později znovu.`,
  _ = `Filtrování nabídek`,
  _ = `Nebyly nalezeny žádné nabídky`,
  _ = `Další možnosti...`,
  _ = `Filtrovat...`,
  _ = `Informace`,
  _ = `Graf prodejů`,
  _ = `Příkazy k nákupu`,
  _ = `Filtry`,
  _ = `Min.`,
  _ = `Max.`,
  _ = `Doplňky`,
  _ = `Libovolné`,
  _ = `Žádné`,
  _ = `%1$s: %2$s`,
  _ = `Tuto položku si nemůžete zakoupit, protože ve Vaší zemi je zakázáno nakupovat a prodávat tento typ položek.`,
  _ = `Tuto položku si nemůžete zakoupit, protože ve Vaší zemi je zakázáno nakupovat tento typ položek.`,
  _ = `Tato nabídka prozatím nemá unikátní nebo vylepšené obrázky. Skutečný vzhled položky se může od zde prezentovaného obrázku mírně lišit.`,
  _ = `Zobrazit pozadí`,
  _ = `Při pokusu o zobrazení této nabídky došlo k chybě.`,
  _ = `Z následujícího důvodu nemůžete nakupovat nebo prodávat položky na komunitním trhu:`,
  _ = `Z následujících důvodů nemůžete nakupovat nebo prodávat položky na komunitním trhu:`,
  _ = `Zobrazit výsledky`,
  _ = `Zobrazit jako mřížku`,
  _ = `Zobrazit jako seznam`,
  _ = `Při načítání dodatečných výsledků došlo k chybě. Zkuste to později znovu.`,
  _ = `Chystáte se otevřít položku pocházející z nové hry, kterou jste nikdy předtím nehráli. Buďte proto obzvláště opatrní, abyste nekoupili zajíce v pytli.`,
  _ = `Jsem si toho vědom a chci pokračovat na položku`,
  _ = `Filtrovat podle hry`,
  _ = `Zobrazit všechny hry`,
  _ = `Váš účet je momentálně uzamčen.`,
  _ = `Pro více informací o uzamčení svého účtu klikněte po přihlášení do klienta služby Steam na červené pole v pravém horním rohu. Případné další dotazy směřujte na podporu služby Steam.`,
  _ = `Váš účet je momentálně uzamčen. Pro více informací o uzamčení svého účtu klikněte po přihlášení do klienta služby Steam na červené pole v pravém horním rohu.`,
  _ = `Chci toto omezení odstranit...`,
  _ = `Váš účet má momentálně zakázáno obchodovat.`,
  _ = `Tento účet momentálně nemůže používat komunitní trh služby Steam.`,
  _ = `Zákaz obchodování může být buď dočasný, nebo trvalý. Pokud chcete zjistit, kdy tento zákaz vyprší, klikněte po přihlášení do klienta služby Steam na červené pole v pravém horním rohu.`,
  _ = `Váš účet má momentálně zakázáno obchodovat. Pokud chcete zjistit, kdy tento zákaz vyprší, klikněte po přihlášení do klienta služby Steam na červené pole v pravém horním rohu.`,
  _ = `Více informací...`,
  _ = `Na svém účtu musíte mít uskutečněný platný nákup, který byl proveden před více než %1$s dny, ale zároveň není starší než jeden rok. Dále u Vás nesmíme evidovat žádné platební nesrovnalosti.`,
  _ = `Proveďte nákup v obchodě služby Steam. Za platný nákup se považuje nákup hry, DLC nebo přidání prostředků do peněženky služby Steam. Aktivace CD klíčů nebo dárků nikoli. Podpora služby Steam nemůže toto omezení odstranit.`,
  _ = `Na svém účtu musíte mít uskutečněný platný nákup, který byl proveden před více než %1$s dny, ale zároveň není starší než jeden rok. Dále u Vás nesmíme evidovat žádné platební nesrovnalosti. Podpora služby Steam nemůže toto omezení odstranit.`,
  _ = `V obchodě služby Steam jste již provedli platný nákup, od jeho uskutečnění však dosud neuběhlo %1$s dní.`,
  _ = `Na svém účtu musíte mít uskutečněný platný nákup, který byl proveden před více než %1$s dny, ale zároveň není starší než jeden rok. Dále u Vás nesmíme evidovat žádné platební nesrovnalosti. V obchodě služby Steam jste již provedli platný nákup, od jeho uskutečnění však dosud neuběhlo %1$s dní. Podpora služby Steam nemůže toto omezení odstranit.`,
  _ = `Heslo k Vašemu účtu bylo nedávno resetováno.`,
  _ = `Toto omezení bude automaticky odstraněno po %1$s dnech od posledního resetování hesla. Pokud nebyl účet delší dobu používán, může toto omezení trvat až %2$s dní. Pouze proces resetování hesla uvalí na účet toto omezení. Prostá změna hesla nevyústí v žádné omezení. Podpora služby Steam nemůže odstranit žádná z omezení.`,
  _ = `Heslo k Vašemu účtu služby Steam bylo nedávno resetováno. V zájmu ochrany uživatelů, kteří mohli mít ohrožený e-mailový účet nebo jiné účty, omezujeme po dobu %1$s dní po resetování hesla přístup na komunitní trh.`,
  _ = `Nedávno jste do své peněženky služby Steam přidali finanční prostředky pomocí neověřené platební karty, která byla v poslední době příliš často používána. <1>Prostředky můžete buď ověřit ihned</1>, nebo můžete počkat, až bude omezení automaticky odstraněno.

POZNÁMKA: Ověření prostředků nemusí fungovat u všech bank a platebních karet. Pokud Vaši kartu nelze ověřit, budete muset počkat, dokud nedojde k jejímu automatickému ověření službou Steam. Podpora služby Steam Vám nemůže sdělit výši autorizačních transakcí ani odstranit toto omezení.`,
  _ = `Nedávno jste do své peněženky služby Steam přidali finanční prostředky pomocí systému PayPal nebo pomocí způsobu platby, který není ověřený a který byl v poslední době příliš často používán. Dokud nebudou prostředky ověřeny, nebudete moci po dobu několika dní používat komunitní trh.`,
  _ = `Nedávno jste do své peněženky služby Steam přidali finanční prostředky pomocí nového účtu systému PayPal nebo pomocí způsobu platby, který není ověřený a který byl v poslední době příliš často používán. Dokud nebudou prostředky ověřeny, nebudete moci po dobu několika dní používat komunitní trh.`,
  _ = `Nedávno jste od přítele přijali digitální dárkový kupon.`,
  _ = `Nedávno jste od přítele přijali digitální dárkový kupon. %1$s dní od chvíle, kdy přítel tento kupon zakoupil, nebudete moci používat komunitní trh.`,
  _ = `Služba Steam má problém s použitím souboru cookie Vašeho prohlížeče.`,
  _ = `Váš soubor cookie je neplatný. Zkuste se odhlásit a znovu přihlásit. Dále se ujistěte, že jsou ve Vašem prohlížeči povoleny všechny soubory cookie a že žádný z doplňků prohlížeče nezasahuje do souborů cookie služby Steam.`,
  _ = `Ve Vašem prohlížeči možná nejsou povoleny všechny soubory cookie. Zkontrolujte to a zkuste se odhlásit a znovu přihlásit.`,
  _ = `Jste přihlášeni na zařízení, které je funkcí Steam Guard chráněno po dobu kratší než %1$s dnů.`,
  _ = `Pokud bylo Vaše zařízení již ověřeno, měl by na něm jít používat i komunitní trh. V opačném případě musíte počkat, dokud toto zařízení neověříme.`,
  _ = `Přihlásili jste se z nového zařízení nebo prohlížeče. V zájmu ochrany položek ve Vašem inventáři nebudete na tomto zařízení moci po dobu %1$s dní používat komunitní trh.`,
  _ = `Nedávno Vám byly vráceny prostředky do Vaší peněženky služby Steam.`,
  _ = `Po dobu %1$s dnů od posledního vrácení prostředků nelze používat komunitní trh. Podpora služby Steam nemůže odstranit žádná z omezení.`,
  _ = `Nedávno Vám byly vráceny prostředky do Vaší peněženky služby Steam. Po dobu %1$s dnů od posledního vrácení prostředků nelze používat komunitní trh.`,
  _ = `Váš účet je omezený.`,
  _ = `Váš účet je omezený a nemá přístup k určitým funkcím služby Steam, a to včetně komunitního trhu.`,
  _ = `Váš účet je omezený a nemá přístup k určitým funkcím služby Steam, a to včetně komunitního trhu.`,
  _ = `Nedávno jste na svém účtu resetovali nebo zapnuli funkci Steam Guard. Musíte počkat %1$s dnů od zapnutí funkce Steam Guard.`,
  _ = `Musíte počkat, dokud nebude funkce Steam Guard na Vašem účtu zapnuta po dobu nejméně 15 dnů. Podpora služby Steam nemůže toto omezení odstranit.`,
  _ = `Váš účet musí být chráněn funkcí Steam Guard nejméně po dobu %1$s\xA0dnů.`,
  _ = `Na svém účtu musíte mít zapnutou funkci Steam Guard. Ujistěte se, že je Vaše e-mailová adresa ověřená a že jste se po zapnutí funkce Steam Guard alespoň dvakrát přihlásili ke svému účtu.`,
  _ = `Váš účet musí být chráněn funkcí Steam Guard nejméně po dobu %1$s\xA0dnů.`,
  _ = `Pokud už nedojde k dalšímu omezení Vašeho přístupu, budete moci komunitní trh používat od %1$s.`,
  _ = `Váš účet má dočasně zakázáno obchodování a používání komunitního trhu.`,
  _ = {
    AdvancedSearch_Heading: _,
    AdvancedSearch_Reset: _,
    AdvancedSearch_Search: _,
    AdvancedSearch_AppSelect_Placeholder: _,
    AdvancedSearch_AppSelect_YourGames: _,
    AdvancedSearch_AppSelect_PopularGames: _,
    AdvancedSearch_AppSelect_Clear: _,
    AdvancedSearch_TextSearch_Placeholder: _,
    AdvancedSearch_TextSearch_PlaceholderWithApp: _,
    AdvancedSearch_TypeSwitch_InGame: _,
    AdvancedSearch_TypeSwitch_SteamItems: _,
    AdvancedSearch_SteamItems_TypeLabel: _,
    AdvancedSearch_NoFacets: _,
    AdvancedSearch_NoFacetsSearch: _,
    AdvancedSearch_FacetLoadError: _,
    AdvancedSearch_PriceFieldLabel: _,
    AdvancedSearch_MinPricePlaceholder: _,
    AdvancedSearch_MaxPricePlaceholder: _,
    AdvancedSearch_CustomFilter_All: _,
    AdvancedSearch_CustomFilter_Other: _,
    AdvancedSearch_FilterGeneric_Placeholder: _,
    AdvancedSearch_AppSelect_FilterPlaceholder: _,
    AdvancedSearch_BetaTag: _,
    AdvancedSearch_TextSearch_Tooltip: _,
    AdvancedSearch_CSContainers_Tooltip: _,
    Header_MarketTitle: _,
    Header_MarketDescription: _,
    Header_LearnMore: _,
    Header_Search_Placeholder: _,
    Header_Search_PlaceholderNew: _,
    Header_Search_Filters: _,
    Header_OptOut: _,
    Header_GiveFeedback: _,
    CommodityExplanation: _,
    Search_AmountFound: _,
    Search_AmountFound_Plural: _,
    Search_AmountFoundFor: _,
    Search_AmountFoundFor_Plural: _,
    Search_ResultsFoundFor: _,
    Search_ListingsFound: _,
    Search_ListingsFound_Plural: _,
    SortBy_Popularity: _,
    SortBy_Name_Asc: _,
    SortBy_Name_Desc: _,
    SortBy_Price_Asc: _,
    SortBy_Price_Desc: _,
    SortBy_Quantity_Asc: _,
    SortBy_Quantity_Desc: _,
    SortBy_AssetProperty_Asc: _,
    SortBy_AssetProperty_Desc: _,
    SortBy_Label: _,
    Search_Button: _,
    Search_Placeholder: _,
    Button_Buy: _,
    Button_Sell: _,
    Button_BuyNow: _,
    Button_BuyOrder: _,
    BuyOrder_PlaceOrderHeader: _,
    Button_Close: _,
    Search_ListingQuantity: _,
    Search_ListingQuantity_Abbreviation: _,
    Bucket_PriceFrom: _,
    AccessorySearch_AttachedAccessoryType: _,
    FilterResults_Placeholder: _,
    AdvancedSearch_Header: _,
    AdvancedSearch_Link: _,
    MarketSearch_Placeholder: _,
    Breadcrumbs_Home: _,
    MarketHome_PopularApps: _,
    AdvancedSearch_IncludeDescriptions: _,
    AdvancedSearch_IncludeDescriptions_Tooltip: _,
    MarketSearch_FilterColumn_Header: _,
    MarketSearch_Reset: _,
    Listings_TextFilter_Placeholder: _,
    Economy_Market_Purchase_Restrictions: _,
    Economy_Market_Purchase_TradableRestriction_1Day: _,
    Economy_Market_Purchase_TradableRestriction_7Days: _,
    Economy_Market_Purchase_TradableRestriction_NDays: _,
    Economy_Market_Purchase_TradableRestriction_Permanent: _,
    Economy_Market_Purchase_MarketableRestriction_1Day: _,
    Economy_Market_Purchase_MarketableRestriction_7Days: _,
    Economy_Market_Purchase_MarketableRestriction_NDays: _,
    Economy_Market_Purchase_MarketableRestriction_None: _,
    AssetPropertyNumberFilterRange: _,
    AssetPropertyStringFilter: _,
    PurchaseDialog_Header: _,
    PurchaseDialog_Details_Column_Name: _,
    PurchaseDialog_Details_Column_Price: _,
    PurchaseDialog_Subtotal_Label: _,
    PurchaseDialog_PublisherFee_Label: _,
    PurchaseDialog_PublisherFee_Label_Generic: _,
    PurchaseDialog_SteamFee_Label: _,
    PurchaseDialog_LocalTax_Label: _,
    PurchaseDialog_Total_Label: _,
    PurchaseDialog_PaymentMethod_Label: _,
    PurchaseDialog_PaymentMethod_Wallet: _,
    PurchaseDialog_SteamAccount_Label: _,
    PurchaseDialog_BillingInfo_Label: _,
    PurchaseDialog_BillingInfo_FirstName: _,
    PurchaseDialog_BillingInfo_LastName: _,
    PurchaseDialog_BillingInfo_Address: _,
    PurchaseDialog_BillingInfo_AddressLine2: _,
    PurchaseDialog_BillingInfo_City: _,
    PurchaseDialog_BillingInfo_StateProvince: _,
    PurchaseDialog_BillingInfo_ZipPostal: _,
    PurchaseDialog_BillingInfo_Country: _,
    PurchaseDialog_BillingInfo_SaveInfo: _,
    PurchaseDialog_Action_AddFunds: _,
    PurchaseDialog_Action_Purchase: _,
    PurchaseDialog_SSA_Link: _,
    PurchaseDialog_SSA_Link_Title: _,
    PurchaseDialog_SSA_Fail: _,
    PurchaseDialog_EU_SSA: _,
    PurchaseDialog_Error_ServerGeneric: _,
    PurchaseDialog_Error_NoConfirmation: _,
    PurchaseDialog_Error_MissingRequired: _,
    PurchaseDialog_Error_InvalidMilitaryCity: _,
    PurchaseDialog_Error_InvalidPostal: _,
    PurchaseDialog_PurchaseComplete: _,
    PurchaseDialog_Button_ViewInventory: _,
    PurchaseDialog_Confirmation_Title: _,
    PurchaseDialog_Confirmation_Title_Wait: _,
    PurchaseDialog_Confirmation_Body_Mobile: _,
    PurchaseDialog_Confirmation_Body_Email: _,
    PurchaseDialog_Confirmation_Body_Unknown: _,
    PurchaseDialog_Confirmation_Description_Mobile: _,
    PurchaseDialog_Confirmation_Description_Email: _,
    PurchaseDialog_Confirmation_Description_Unknown: _,
    PurchaseDialog_Purchase_Successful: _,
    PurchaseDialog_Close: _,
    PurchaseDialog_ViewInventory: _,
    PurhcaseDialog_SaveMyAddress: _,
    Listing_NotAvailable: _,
    Listing_NotAvailable_Short: _,
    Listing_NotAvailable_Long: _,
    Listing_MyListing: _,
    BuyOrderDialog_Header: _,
    BuyOrderDialog_Header_NoItem: _,
    BuyOrderDialog_BucketPicker_Label: _,
    BuyOrderDialog_BucketPicker_Placeholder: _,
    BuyOrderDialog_PriceField: _,
    BuyOrderDialog_PriceField_Suffix: _,
    BuyOrderDialog_QuantityField: _,
    BuyOrderDialog_MaxPrice: _,
    BuyOrderDialog_MaxPrice_Tip: _,
    BuyOrderDialog_Status_Pending: _,
    BuyOrderDialog_Status_Filled: _,
    BuyOrderDialog_Status_Settled: _,
    BuyOrderDialog_Status_Settled_Note: _,
    BuyOrderDialog_Status_GenericError: _,
    BuyOrderDialog_MinPriceError: _,
    OrderBook_Table_PriceOrLess: _,
    OrderBook_Table_PriceOrMore: _,
    OrderBook_Table_Price: _,
    OrderBook_Table_Quantity: _,
    OrderBook_SellOrder_Description: _,
    OrderBook_SellOrder_Description_None: _,
    OrderBook_BuyOrder_Description: _,
    OrderBook_BuyOrder_Description_None: _,
    OrderBook_BuyOrder_NeedBucket: _,
    OrderBook_BuyOrder_Explanation_Unique: _,
    OrderBook_BuyOrder_Explanation_Commodity: _,
    OrderBook_Graph_Title: _,
    OrderBook_Graph_BuyTooltip: _,
    OrderBook_Graph_BuyTooltip_Plural: _,
    OrderBook_Graph_SellTooltip: _,
    OrderBook_Graph_SellTooltip_Plural: _,
    OrderBook_PlaceOrder_BuyRequests: _,
    OrderBook_PlaceOrder_BuyRequests_Plural: _,
    MedianSalePrice_Graph_Title: _,
    Graph_TimeScale_Week: _,
    Graph_TimeScale_Month: _,
    Graph_TimeScale_Year: `Rok`,
    Graph_TimeScale_Lifetime: _,
    Graph_NumberSold: _,
    Graph_Label_Price: _,
    Graph_Label_Volume: _,
    Graph_NoData: _,
    Graph_Tooltip_NoPurchaseData: _,
    Graph_Tooltip_NA: `–`,
    MyOrders_GridHeader_Name: _,
    MyOrders_GridHeader_Price: _,
    MyOrders_GridHeader_Quantity: _,
    MyOrders_GridHeader_DateListed: _,
    MyOrders_Cancel: _,
    MyOrders_Remove: _,
    MyOrders_Heading: _,
    MyOrders_Heading_Sell: _,
    MyOrders_Heading_Buy: _,
    MyOrders_Heading_MyPurchaseOffers: _,
    MyOrders_Heading_MyListings: _,
    MyOrders_FailedToLoad: _,
    MyOrders_NoActiveOrders_Item: _,
    MyOrders_NoBuyOrders_Item: _,
    MyOrders_NoSellOrders_Item: _,
    MyOrders_QuantityWithValue: _,
    MyOrders_SeeAllN: _,
    CancelBuyOrder_GenericError: _,
    CancelListing_GenericError: _,
    CancelListing_Dialog_Header: _,
    CancelListing_Dialog_Prompt: _,
    CancelListing_Dialog_Prompt_Generic: _,
    CancelListing_Dialog_Yes: _,
    CancelListing_Dialog_No: `Ne`,
    CancelListing_Dialog_Success: _,
    SellDialog_Frame_Title: _,
    UniqueBuyOrder_Explanation_Header: _,
    UniqueBuyOrder_Explanation_1: _,
    UniqueBuyOrder_Explanation_2: _,
    UniqueBuyOrder_Explanation_3: _,
    PriceFilter_ValueAndUp: _,
    Error_Sorry: _,
    Error_Encountered: _,
    Error_TooManyRequests_Description: _,
    Container_ContentsLabel: _,
    Error_LoadingContent: _,
    Error_LoadingMarketItem: _,
    ListingFilter_Title: _,
    Listings_NoneFound: _,
    ItemBucketPicker_Overflow_Placeholder: _,
    ItemBucketPicker_Overflow_FilterPlaceholder: _,
    Mobile_InfoSection: _,
    Mobile_GraphSection: _,
    Mobile_BuyOrderSection: _,
    Mobile_FiltersButton: _,
    AssetProperty_Range_MinPlaceholder: _,
    AssetProperty_Range_MaxPlaceholder: _,
    Accessories_FieldSectionLabel: _,
    Accessories_AnyFilter: _,
    Accessories_NoneFilter: _,
    Accessories_TypeAndValue_Breadcrumb: _,
    Item_CountryBuySellRestricted: _,
    Item_CountryBuyRestricted: _,
    Listing_EnhancedAppearance_Missing: _,
    Listing_EnhancedAppearance_ShowBackground: _,
    Listing_SomethingWentWrong: _,
    Unavailable_Header: _,
    Unavailable_Header_Plural: _,
    Filter_ViewResults: _,
    Results_GridView_Tooltip: _,
    Results_ListView_Tooltip: _,
    Results_PageLoadError: _,
    Market_AppUnplayedAndUnvetted: _,
    Market_AppUnplayedAndUnvetted_Dismiss: _,
    Home_GamePicker_Label: _,
    Home_GamePicker_ViewAll: _,
    Economy_Market_TopLevelReason_AccountLocked: _,
    Economy_Market_TopLevelTooltip_AccountLocked: _,
    Economy_Market_HeaderTip_AccountLocked: _,
    Economy_Market_TopLevelTooltip_RemoveRestrictionLink: _,
    Economy_Market_TopLevelReason_AccountTradeBanned: _,
    Economy_Market_TopLevelReason_Unknown: _,
    Economy_Market_TopLevelTooltip_AccountTradeBanned: _,
    Economy_Market_HeaderTip_AccountTradeBanned: _,
    Economy_Market_TopLevelTooltip_MoreInfoLink: _,
    Economy_Market_TopLevelReason_AccountNotTrusted: _,
    Economy_Market_TopLevelTooltip_AccountNotTrusted: _,
    Economy_Market_HeaderTip_AccountNotTrusted: _,
    Economy_Market_TopLevelReason_AccountNotTrusted_Waiting: _,
    Economy_Market_TTopLevelTooltip_AccountNotTrusted_Waiting: _,
    Economy_Market_TopLevelReason_AccountPasswordRecentlyReset: _,
    Economy_Market_TopLevelTooltip_AccountPasswordRecentlyReset: _,
    Economy_Market_HeaderTip_AccountPasswordRecentlyReset: _,
    Economy_Market_HeaderTip_NewPaymentMethod_NoDate: _,
    Economy_Market_HeaderTip_AccountHasNewPaymentMethod: _,
    Economy_Market_TopLevelReason_AccountHasNewPaymentMethod: _,
    Economy_Market_TopLevelReason_AcceptedWalletGift: _,
    Economy_Market_HeaderTip_AcceptedWalletGift: _,
    Economy_Market_TopLevelReason_InvalidCookie: _,
    Economy_Market_TopLevelTooltip_InvalidCookie: _,
    Economy_Market_HeaderTip_InvalidCookie: _,
    Economy_Market_TopLevelReason_NewDevice: _,
    Economy_Market_TopLevelTooltip_NewDevice: _,
    Economy_Market_HeaderTip_NewDevice: _,
    Economy_Market_TopLevelReason_SelfRefund: _,
    Economy_Market_TopLevelTooltip_SelfRefund: _,
    Economy_Market_HeaderTip_SelfRefund: _,
    Economy_Market_TopLevelReason_LimitedUser: _,
    Economy_Market_TopLevelTooltip_LimitedUser: _,
    Economy_Market_HeaderTip_LimitedUser: _,
    Economy_Market_HeaderTip_SteamGuardOnlyRecentlyEnabled: _,
    Economy_Market_TopLevelTooltip_SteamGuardRecentlyEnabled: _,
    Economy_Market_TopLevelReason_NoSteamGuard: _,
    Economy_Market_TopLevelTooltip_SteamGuardDisabled: _,
    Economy_Market_HeaderTip_NoSteamGuard: _,
    Economy_Market_HeaderTip_TimeCanUse: _,
    Economy_Market_TopLevelReason_TradeCooldown: _,
  };
export {
  _ as Accessories_AnyFilter,
  _ as Accessories_FieldSectionLabel,
  _ as Accessories_NoneFilter,
  _ as Accessories_TypeAndValue_Breadcrumb,
  _ as AccessorySearch_AttachedAccessoryType,
  _ as AdvancedSearch_AppSelect_Clear,
  _ as AdvancedSearch_AppSelect_FilterPlaceholder,
  _ as AdvancedSearch_AppSelect_Placeholder,
  _ as AdvancedSearch_AppSelect_PopularGames,
  _ as AdvancedSearch_AppSelect_YourGames,
  _ as AdvancedSearch_BetaTag,
  _ as AdvancedSearch_CSContainers_Tooltip,
  _ as AdvancedSearch_CustomFilter_All,
  _ as AdvancedSearch_CustomFilter_Other,
  _ as AdvancedSearch_FacetLoadError,
  _ as AdvancedSearch_FilterGeneric_Placeholder,
  _ as AdvancedSearch_Header,
  _ as AdvancedSearch_Heading,
  _ as AdvancedSearch_IncludeDescriptions,
  _ as AdvancedSearch_IncludeDescriptions_Tooltip,
  _ as AdvancedSearch_Link,
  _ as AdvancedSearch_MaxPricePlaceholder,
  _ as AdvancedSearch_MinPricePlaceholder,
  _ as AdvancedSearch_NoFacets,
  _ as AdvancedSearch_NoFacetsSearch,
  _ as AdvancedSearch_PriceFieldLabel,
  _ as AdvancedSearch_Reset,
  _ as AdvancedSearch_Search,
  _ as AdvancedSearch_SteamItems_TypeLabel,
  _ as AdvancedSearch_TextSearch_Placeholder,
  _ as AdvancedSearch_TextSearch_PlaceholderWithApp,
  _ as AdvancedSearch_TextSearch_Tooltip,
  _ as AdvancedSearch_TypeSwitch_InGame,
  _ as AdvancedSearch_TypeSwitch_SteamItems,
  _ as AssetPropertyNumberFilterRange,
  _ as AssetPropertyStringFilter,
  _ as AssetProperty_Range_MaxPlaceholder,
  _ as AssetProperty_Range_MinPlaceholder,
  _ as Breadcrumbs_Home,
  _ as Bucket_PriceFrom,
  _ as Button_Buy,
  _ as Button_BuyNow,
  _ as Button_BuyOrder,
  _ as Button_Close,
  _ as Button_Sell,
  _ as BuyOrderDialog_BucketPicker_Label,
  _ as BuyOrderDialog_BucketPicker_Placeholder,
  _ as BuyOrderDialog_Header,
  _ as BuyOrderDialog_Header_NoItem,
  _ as BuyOrderDialog_MaxPrice,
  _ as BuyOrderDialog_MaxPrice_Tip,
  _ as BuyOrderDialog_MinPriceError,
  _ as BuyOrderDialog_PriceField,
  _ as BuyOrderDialog_PriceField_Suffix,
  _ as BuyOrderDialog_QuantityField,
  _ as BuyOrderDialog_Status_Filled,
  _ as BuyOrderDialog_Status_GenericError,
  _ as BuyOrderDialog_Status_Pending,
  _ as BuyOrderDialog_Status_Settled,
  _ as BuyOrderDialog_Status_Settled_Note,
  _ as BuyOrder_PlaceOrderHeader,
  _ as CancelBuyOrder_GenericError,
  _ as CancelListing_Dialog_Header,
  _ as CancelListing_Dialog_No,
  _ as CancelListing_Dialog_Prompt,
  _ as CancelListing_Dialog_Prompt_Generic,
  _ as CancelListing_Dialog_Success,
  _ as CancelListing_Dialog_Yes,
  _ as CancelListing_GenericError,
  _ as CommodityExplanation,
  _ as Container_ContentsLabel,
  _ as Economy_Market_HeaderTip_AcceptedWalletGift,
  _ as Economy_Market_HeaderTip_AccountHasNewPaymentMethod,
  _ as Economy_Market_HeaderTip_AccountLocked,
  _ as Economy_Market_HeaderTip_AccountNotTrusted,
  _ as Economy_Market_HeaderTip_AccountPasswordRecentlyReset,
  _ as Economy_Market_HeaderTip_AccountTradeBanned,
  _ as Economy_Market_HeaderTip_InvalidCookie,
  _ as Economy_Market_HeaderTip_LimitedUser,
  _ as Economy_Market_HeaderTip_NewDevice,
  _ as Economy_Market_HeaderTip_NewPaymentMethod_NoDate,
  _ as Economy_Market_HeaderTip_NoSteamGuard,
  _ as Economy_Market_HeaderTip_SelfRefund,
  _ as Economy_Market_HeaderTip_SteamGuardOnlyRecentlyEnabled,
  _ as Economy_Market_HeaderTip_TimeCanUse,
  _ as Economy_Market_Purchase_MarketableRestriction_1Day,
  _ as Economy_Market_Purchase_MarketableRestriction_7Days,
  _ as Economy_Market_Purchase_MarketableRestriction_NDays,
  _ as Economy_Market_Purchase_MarketableRestriction_None,
  _ as Economy_Market_Purchase_Restrictions,
  _ as Economy_Market_Purchase_TradableRestriction_1Day,
  _ as Economy_Market_Purchase_TradableRestriction_7Days,
  _ as Economy_Market_Purchase_TradableRestriction_NDays,
  _ as Economy_Market_Purchase_TradableRestriction_Permanent,
  _ as Economy_Market_TTopLevelTooltip_AccountNotTrusted_Waiting,
  _ as Economy_Market_TopLevelReason_AcceptedWalletGift,
  _ as Economy_Market_TopLevelReason_AccountHasNewPaymentMethod,
  _ as Economy_Market_TopLevelReason_AccountLocked,
  _ as Economy_Market_TopLevelReason_AccountNotTrusted,
  _ as Economy_Market_TopLevelReason_AccountNotTrusted_Waiting,
  _ as Economy_Market_TopLevelReason_AccountPasswordRecentlyReset,
  _ as Economy_Market_TopLevelReason_AccountTradeBanned,
  _ as Economy_Market_TopLevelReason_InvalidCookie,
  _ as Economy_Market_TopLevelReason_LimitedUser,
  _ as Economy_Market_TopLevelReason_NewDevice,
  _ as Economy_Market_TopLevelReason_NoSteamGuard,
  _ as Economy_Market_TopLevelReason_SelfRefund,
  _ as Economy_Market_TopLevelReason_TradeCooldown,
  _ as Economy_Market_TopLevelReason_Unknown,
  _ as Economy_Market_TopLevelTooltip_AccountLocked,
  _ as Economy_Market_TopLevelTooltip_AccountNotTrusted,
  _ as Economy_Market_TopLevelTooltip_AccountPasswordRecentlyReset,
  _ as Economy_Market_TopLevelTooltip_AccountTradeBanned,
  _ as Economy_Market_TopLevelTooltip_InvalidCookie,
  _ as Economy_Market_TopLevelTooltip_LimitedUser,
  _ as Economy_Market_TopLevelTooltip_MoreInfoLink,
  _ as Economy_Market_TopLevelTooltip_NewDevice,
  _ as Economy_Market_TopLevelTooltip_RemoveRestrictionLink,
  _ as Economy_Market_TopLevelTooltip_SelfRefund,
  _ as Economy_Market_TopLevelTooltip_SteamGuardDisabled,
  _ as Economy_Market_TopLevelTooltip_SteamGuardRecentlyEnabled,
  _ as Error_Encountered,
  _ as Error_LoadingContent,
  _ as Error_LoadingMarketItem,
  _ as Error_Sorry,
  _ as Error_TooManyRequests_Description,
  _ as FilterResults_Placeholder,
  _ as Filter_ViewResults,
  _ as Graph_Label_Price,
  _ as Graph_Label_Volume,
  _ as Graph_NoData,
  _ as Graph_NumberSold,
  _ as Graph_TimeScale_Lifetime,
  _ as Graph_TimeScale_Month,
  _ as Graph_TimeScale_Week,
  _ as Graph_TimeScale_Year,
  _ as Graph_Tooltip_NA,
  _ as Graph_Tooltip_NoPurchaseData,
  _ as Header_GiveFeedback,
  _ as Header_LearnMore,
  _ as Header_MarketDescription,
  _ as Header_MarketTitle,
  _ as Header_OptOut,
  _ as Header_Search_Filters,
  _ as Header_Search_Placeholder,
  _ as Header_Search_PlaceholderNew,
  _ as Home_GamePicker_Label,
  _ as Home_GamePicker_ViewAll,
  _ as ItemBucketPicker_Overflow_FilterPlaceholder,
  _ as ItemBucketPicker_Overflow_Placeholder,
  _ as Item_CountryBuyRestricted,
  _ as Item_CountryBuySellRestricted,
  _ as ListingFilter_Title,
  _ as Listing_EnhancedAppearance_Missing,
  _ as Listing_EnhancedAppearance_ShowBackground,
  _ as Listing_MyListing,
  _ as Listing_NotAvailable,
  _ as Listing_NotAvailable_Long,
  _ as Listing_NotAvailable_Short,
  _ as Listing_SomethingWentWrong,
  _ as Listings_NoneFound,
  _ as Listings_TextFilter_Placeholder,
  _ as MarketHome_PopularApps,
  _ as MarketSearch_FilterColumn_Header,
  _ as MarketSearch_Placeholder,
  _ as MarketSearch_Reset,
  _ as Market_AppUnplayedAndUnvetted,
  _ as Market_AppUnplayedAndUnvetted_Dismiss,
  _ as MedianSalePrice_Graph_Title,
  _ as Mobile_BuyOrderSection,
  _ as Mobile_FiltersButton,
  _ as Mobile_GraphSection,
  _ as Mobile_InfoSection,
  _ as MyOrders_Cancel,
  _ as MyOrders_FailedToLoad,
  _ as MyOrders_GridHeader_DateListed,
  _ as MyOrders_GridHeader_Name,
  _ as MyOrders_GridHeader_Price,
  _ as MyOrders_GridHeader_Quantity,
  _ as MyOrders_Heading,
  _ as MyOrders_Heading_Buy,
  _ as MyOrders_Heading_MyListings,
  _ as MyOrders_Heading_MyPurchaseOffers,
  _ as MyOrders_Heading_Sell,
  _ as MyOrders_NoActiveOrders_Item,
  _ as MyOrders_NoBuyOrders_Item,
  _ as MyOrders_NoSellOrders_Item,
  _ as MyOrders_QuantityWithValue,
  _ as MyOrders_Remove,
  _ as MyOrders_SeeAllN,
  _ as OrderBook_BuyOrder_Description,
  _ as OrderBook_BuyOrder_Description_None,
  _ as OrderBook_BuyOrder_Explanation_Commodity,
  _ as OrderBook_BuyOrder_Explanation_Unique,
  _ as OrderBook_BuyOrder_NeedBucket,
  _ as OrderBook_Graph_BuyTooltip,
  _ as OrderBook_Graph_BuyTooltip_Plural,
  _ as OrderBook_Graph_SellTooltip,
  _ as OrderBook_Graph_SellTooltip_Plural,
  _ as OrderBook_Graph_Title,
  _ as OrderBook_PlaceOrder_BuyRequests,
  _ as OrderBook_PlaceOrder_BuyRequests_Plural,
  _ as OrderBook_SellOrder_Description,
  _ as OrderBook_SellOrder_Description_None,
  _ as OrderBook_Table_Price,
  _ as OrderBook_Table_PriceOrLess,
  _ as OrderBook_Table_PriceOrMore,
  _ as OrderBook_Table_Quantity,
  _ as PriceFilter_ValueAndUp,
  _ as PurchaseDialog_Action_AddFunds,
  _ as PurchaseDialog_Action_Purchase,
  _ as PurchaseDialog_BillingInfo_Address,
  _ as PurchaseDialog_BillingInfo_AddressLine2,
  _ as PurchaseDialog_BillingInfo_City,
  _ as PurchaseDialog_BillingInfo_Country,
  _ as PurchaseDialog_BillingInfo_FirstName,
  _ as PurchaseDialog_BillingInfo_Label,
  _ as PurchaseDialog_BillingInfo_LastName,
  _ as PurchaseDialog_BillingInfo_SaveInfo,
  _ as PurchaseDialog_BillingInfo_StateProvince,
  _ as PurchaseDialog_BillingInfo_ZipPostal,
  _ as PurchaseDialog_Button_ViewInventory,
  _ as PurchaseDialog_Close,
  _ as PurchaseDialog_Confirmation_Body_Email,
  _ as PurchaseDialog_Confirmation_Body_Mobile,
  _ as PurchaseDialog_Confirmation_Body_Unknown,
  _ as PurchaseDialog_Confirmation_Description_Email,
  _ as PurchaseDialog_Confirmation_Description_Mobile,
  _ as PurchaseDialog_Confirmation_Description_Unknown,
  _ as PurchaseDialog_Confirmation_Title,
  _ as PurchaseDialog_Confirmation_Title_Wait,
  _ as PurchaseDialog_Details_Column_Name,
  _ as PurchaseDialog_Details_Column_Price,
  _ as PurchaseDialog_EU_SSA,
  _ as PurchaseDialog_Error_InvalidMilitaryCity,
  _ as PurchaseDialog_Error_InvalidPostal,
  _ as PurchaseDialog_Error_MissingRequired,
  _ as PurchaseDialog_Error_NoConfirmation,
  _ as PurchaseDialog_Error_ServerGeneric,
  _ as PurchaseDialog_Header,
  _ as PurchaseDialog_LocalTax_Label,
  _ as PurchaseDialog_PaymentMethod_Label,
  _ as PurchaseDialog_PaymentMethod_Wallet,
  _ as PurchaseDialog_PublisherFee_Label,
  _ as PurchaseDialog_PublisherFee_Label_Generic,
  _ as PurchaseDialog_PurchaseComplete,
  _ as PurchaseDialog_Purchase_Successful,
  _ as PurchaseDialog_SSA_Fail,
  _ as PurchaseDialog_SSA_Link,
  _ as PurchaseDialog_SSA_Link_Title,
  _ as PurchaseDialog_SteamAccount_Label,
  _ as PurchaseDialog_SteamFee_Label,
  _ as PurchaseDialog_Subtotal_Label,
  _ as PurchaseDialog_Total_Label,
  _ as PurchaseDialog_ViewInventory,
  _ as PurhcaseDialog_SaveMyAddress,
  _ as Results_GridView_Tooltip,
  _ as Results_ListView_Tooltip,
  _ as Results_PageLoadError,
  _ as Search_AmountFound,
  _ as Search_AmountFoundFor,
  _ as Search_AmountFoundFor_Plural,
  _ as Search_AmountFound_Plural,
  _ as Search_Button,
  _ as Search_ListingQuantity,
  _ as Search_ListingQuantity_Abbreviation,
  _ as Search_ListingsFound,
  _ as Search_ListingsFound_Plural,
  _ as Search_Placeholder,
  _ as Search_ResultsFoundFor,
  _ as SellDialog_Frame_Title,
  _ as SortBy_AssetProperty_Asc,
  _ as SortBy_AssetProperty_Desc,
  _ as SortBy_Label,
  _ as SortBy_Name_Asc,
  _ as SortBy_Name_Desc,
  _ as SortBy_Popularity,
  _ as SortBy_Price_Asc,
  _ as SortBy_Price_Desc,
  _ as SortBy_Quantity_Asc,
  _ as SortBy_Quantity_Desc,
  _ as Unavailable_Header,
  _ as Unavailable_Header_Plural,
  _ as UniqueBuyOrder_Explanation_1,
  _ as UniqueBuyOrder_Explanation_2,
  _ as UniqueBuyOrder_Explanation_3,
  _ as UniqueBuyOrder_Explanation_Header,
  _ as default,
};
