var _ = `indonesian`,
  _ = `Workshop Steam`,
  _ = `Workshop Steam untuk %1$s`,
  _ = `Terjadi kendala saat memuat halaman ini. Silakan coba lagi nanti.`,
  _ = `Eror`,
  _ = `Terjadi kendala saat melakukan tindakan tersebut. Silakan coba lagi nanti. (%1$s)`,
  _ = `Maaf!`,
  _ = `Terjadi kesalahan saat memproses permintaanmu:`,
  _ = `Kamu terlalu banyak mengajukan permintaan baru-baru ini. Mohon tunggu dan coba lagi nanti.`,
  _ = `(Hanya Admin) Lihat Workshop Lama`,
  _ = `Menelusuri: %1$s`,
  _ = `(Voting Favoritmu)`,
  _ = `(Berlangganan untuk menambahkannya ke game-mu)`,
  _ = `(Voting Favoritmu)`,
  _ = `Diterima untuk bermain`,
  _ = `Diterima`,
  _ = `Konten Resmi`,
  _ = `Berdasarkan %1$s`,
  _ = `Item`,
  _ = `Item`,
  _ = `Koleksi`,
  _ = `Merchandise`,
  _ = `Video`,
  _ = `Permintaan Tersimpan`,
  _ = `Simpan permintaan pencarian ini`,
  _ = `Masukkan nama untuk pencarianmu`,
  _ = `Simpan filter pencarian dan opsi pengurutanmu saat ini untuk digunakan lagi di masa mendatang. Kamu dapat menemukan ini di bagiain "Item-mu".`,
  _ = `Simpan sebagai permintaan pencarian baru atau pilih permintaan pencariaan yang tersimpan untuk diperbarui`,
  _ = `<Pencarian Tersimpan Baru>`,
  _ = `Simpan`,
  _ = `Hapus Pencarian yang Disimpan`,
  _ = `Apa kamu yakin ingin menghapus pencarian "%1$s" yang disimpan?`,
  _ = `Hapus`,
  _ = `Pelajari Lebih Lanjut`,
  _ = `Hapus pencarian`,
  _ = `Workshop Steam untuk %1$s`,
  _ = `Urutkan Berdasarkan`,
  _ = `Rentang Waktu`,
  _ = `Hari Ini`,
  _ = `Satu Minggu`,
  _ = `30 Hari`,
  _ = `Tiga Bulan`,
  _ = `Enam Bulan`,
  _ = `Satu Tahun`,
  _ = `Sepanjang Waktu`,
  _ = `%1$s (%2$s)`,
  _ = `Terkini`,
  _ = `Terpopuler`,
  _ = `Rating Tertinggi Sepanjang Waktu`,
  _ = `Terakhir Diperbarui`,
  _ = `Bobot Laporan`,
  _ = `(Admin) %1$s`,
  _ = `Paling Diperlukan oleh Item Lain`,
  _ = `Ada Dalam Sebagian Besar Koleksi`,
  _ = `(Admin) Antrean Persetujuan`,
  _ = `Belum Diberikan Rating`,
  _ = `Jumlah Pelanggan Unik`,
  _ = `Jumlah Total Vote`,
  _ = `Terbanyak Disukai`,
  _ = `Relevansi Pencarian`,
  _ = `Waktu Bermain Terkini`,
  _ = `Waktu Bermain Sepanjang Waktu`,
  _ = `Waktu Bermain Rata-rata Terkini`,
  _ = `Waktu Bermain Rata-rata Sepanjang Waktu`,
  _ = `Sesi Bermain`,
  _ = `Sesi Bermain Sepanjang Waktu`,
  _ = `Skor Tidak Pantas`,
  _ = `Pemeriksaan Konten yang di-ban`,
  _ = `Admin yang Dikurasi`,
  _ = `Calon Pemenang`,
  _ = `Diberikan Rating olehmu`,
  _ = `Tanggal Diterima`,
  _ = `Filter Khusus: `,
  _ = `Tidak ada`,
  _ = `Diterima untuk Bermain`,
  _ = `Dibuat oleh Teman`,
  _ = `Dibuat oleh yang Diikuti`,
  _ = `Difavoritkan oleh Teman`,
  _ = `Dilaporkan (Hanya Admin)`,
  _ = `Diperlukan oleh Item Lain`,
  _ = `Dalam Koleksi`,
  _ = `Beranda`,
  _ = `Telusuri`,
  _ = `Item-mu`,
  _ = `Diskusi`,
  _ = `Tentang`,
  _ = `Cari %1$s`,
  _ = `Item yang diposting olehmu (%1$s)`,
  _ = `Favoritmu (%1$s)`,
  _ = `Item Langganan (%1$s)`,
  _ = `Item yang Dimainkan (%1$s)`,
  _ = `Koleksimu (%1$s)`,
  _ = `Daftar voting milikmu`,
  _ = `Informasi Pembayaranmu`,
  _ = `Lihat Pendapatanmu`,
  _ = `(dari penjualan item Workshop-mu)`,
  _ = `Lihat Perjanjian Hukum`,
  _ = `Antrean Voting`,
  _ = `Terapkan filter`,
  _ = `Urutan berdasarkan: %1$s`,
  _ = `<none selected>`,
  _ = `DLC yang diperlukan`,
  _ = `DLC yang Diperlukan: %1$s`,
  _ = `Memerlukan DLC yang sudah dimiliki`,
  _ = `Kecualikan item yang memerlukan DLC yang tidak dimiliki`,
  _ = `Kamu tidak memiliki DLC apa pun`,
  _ = `Kamu memiliki semua DLC yang tersedia`,
  _ = `(%1$s item lainnya)`,
  _ = `Sertakan yang Dimiliki`,
  _ = `Kecualikan yang Tidak Dimiliki`,
  _ = `Filter berdasarkan Nama`,
  _ = `Tidak kompatibel`,
  _ = `Beberapa item tidak dapat dimasukkan ke dalam game. Kamu masih dapat mencarinya dengan mencentang kotak ini.`,
  _ = `Disembunyikan & Hanya untuk Teman`,
  _ = `Hasil untuk: "%1$s"`,
  _ = `Hasil untuk: "%1$s" (hanya judul)`,
  _ = `Hasil untuk: "%1$s" (hanya deskripsi)`,
  _ = `Berisikan item: "%1$s"`,
  _ = `Memerlukan "%1$s" agar dapat berfungsi dengan baik`,
  _ = `%1$s: %2$s`,
  _ = `%1$s: %2$s`,
  _ = `Tag: Item yang tidak kompatibel`,
  _ = `Tag: Item yang Diterima`,
  _ = `Tentukan kolom teks dari item yang ingin kamu cari:`,
  _ = `Judul & Deskripsi`,
  _ = `Hanya Judul`,
  _ = `Hanya Deskripsi`,
  _ = `Kamu dapat membuat pencarian yang lebih kompleks menggunakan operator %1$s, %2$s, dan %3$s (harus menggunakan huruf kapital). Atau, kamu dapat menggunakan karakter %4$s dan %5$s sebagai singkatan untuk %1$s dan %3$s.`,
  _ = `%1$s menemukan item dengan "%2$s" dan "%3$s" dalam teks pencarian`,
  _ = `%1$s menemukan item dengan "%2$s" atau "%3$s" dalam teks pencarian`,
  _ = `%1$s menemukan item dengan "%2$s", tapi tidak dengan "%3$s" dalam teks pencarian`,
  _ = `merah`,
  _ = `biru`,
  _ = `hijau`,
  _ = `ruangan`,
  _ = `Menggabungkan kata kunci pencarian dengan tanda kurung memungkinkanmu menghasilkan pencarian yang cukup spesifik.`,
  _ = `%1$s menemukan item dengan "%2$s", serta "%3$s" atau "%4$s" dalam teks pencarian.`,
  _ = `%1$s menemukan item dengan "%2$s" dan "%3$s" atau "%4$s", tapi tidak dengan "%5$s" dalam teks pencarian.`,
  _ = `Posisi ideal untuk filter:`,
  _ = `Sisi Kiri`,
  _ = `Sisi Kanan`,
  _ = `Diciutkan`,
  _ = `Redupkan tampilan item-item ini:`,
  _ = `Dilaporkan olehmu`,
  _ = `Dibuat oleh pengguna yang kamu blokir`,
  _ = `Disukai olehmu`,
  _ = `Tidak disukai olehmu`,
  _ = `Ada di daftar langgananmu`,
  _ = `Filter berdasarkan Tanggal`,
  _ = `Tanggal Diposting`,
  _ = `Diposting setelah %1$s`,
  _ = `Diposting sebelum %1$s`,
  _ = `Diposting antara %1$s dan %2$s`,
  _ = `Tanggal Terakhir Diperbarui`,
  _ = `Diperbarui setelah %1$s`,
  _ = `Diperbarui sebelum %1$s`,
  _ = `Diperbarui antara %1$s dan %2$s`,
  _ = `Antara`,
  _ = `Dan`,
  _ = `1 entri cocok dengan filter`,
  _ = `%2$s entri cocok dengan filter`,
  _ = `Per halaman:`,
  _ = `%1$s/%2$s`,
  _ = `Buat Koleksi`,
  _ = `Kirim desainmu`,
  _ = `Tampilan Cepat`,
  _ = `Lebih banyak lagi`,
  _ = `Kamu sudah berlangganan item ini`,
  _ = `Item ini ada di daftar Favoritmu`,
  _ = `Kamu sudah memainkan item ini`,
  _ = `Item ini telah diterima untuk digunakan dalam game ini!`,
  _ = `Item ini telah ditandai sebagai tidak kompatibel untuk game ini.`,
  _ = `Kamu menyukai item ini.`,
  _ = `Kamu tidak menyukai item ini.`,
  _ = `Kamu melaporkan item ini karena melanggar Pedoman Komunitas Steam.`,
  _ = `Kamu telah memblokir pengguna ini.`,
  _ = `Deskripsi`,
  _ = `Diskusi`,
  _ = `Komentar (%1$s)`,
  _ = `Pengumuman`,
  _ = `Statistik Item`,
  _ = `Catatan Perubahan (%1$s)`,
  _ = `Workshop Steam :: %1$s`,
  _ = `Dibuat oleh: `,
  _ = `%2$s rating`,
  _ = `%2$s rating`,
  _ = `Tidak cukup rating`,
  _ = `%1$s @ %2$s`,
  _ = `Diposting pada:`,
  _ = `Diperbarui pada:`,
  _ = `Langganan`,
  _ = `Berlangganan`,
  _ = `Stop Berlangganan`,
  _ = `Favorit`,
  _ = `Difavoritkan`,
  _ = `Batalkan favorit`,
  _ = `Lihat Item yang Bergantung`,
  _ = `Tambahkan ke Koleksi`,
  _ = `Simpan ke Koleksi`,
  _ = `Silakan login untuk melakukan tindakan ini`,
  _ = `Berlangganan untuk mengunduh`,
  _ = `Stop berlangganan untuk menghapus item ini dari game-mu`,
  _ = `Temukan item ini lagi nanti dengan mudah`,
  _ = `Lihat semua %1$s item yang bergantung pada item ini agar dapat berfungsi dengan baik. Perlu diingat bahwa beberapa item ditandai sebagai disembunyikan atau hanya teman.`,
  _ = `Laporkan item ini atas pelanggaran Aturan Perilaku Online Steam`,
  _ = `Penghargaan`,
  _ = `Tambahkan ke salah satu koleksimu`,
  _ = `Ukuran File:`,
  _ = `Pengunjung:`,
  _ = `Pelanggan:`,
  _ = `Favorit:`,
  _ = `Jumlah Favorit Unik:`,
  _ = `Jumlah Pelanggan Unik:`,
  _ = `Total Sesi Bermain:`,
  _ = `Memerlukan item berikut: `,
  _ = `Memerlukan DLC berikut: `,
  _ = `Berlangganan ke semua`,
  _ = `Stop semua langganan`,
  _ = `Simpan ke Koleksi`,
  _ = `Lihat semua Penghargaan Komunitas`,
  _ = `%1$s Penghargaan Komunitas`,
  _ = `%1$s Penghargaan Komunitas`,
  _ = `TAG`,
  _ = `KATEGORI`,
  _ = `DESKRIPSI`,
  _ = `Diperlukan oleh:`,
  _ = `Dalam %1$s Koleksi`,
  _ = `Dalam %1$s Koleksi oleh %2$s`,
  _ = `Eror`,
  _ = `Kamu tidak memiliki izin untuk melakukan tindakan itu.`,
  _ = `Terjadi kendala saat menghubungi Steam. Silakan coba lagi nanti.`,
  _ = `Anda telah mencoba melakukan terlalu banyak tindakan dalam waktu singkat. Mohon tunggu sebelum mencoba lagi.`,
  _ = `Terjadi kendala saat mencoba melakukan tindakan tersebut. Silakan coba lagi nanti.`,
  _ = `Berlangganan ke semua`,
  _ = `Apakah kamu ingin menambahkan item dalam koleksi ini ke langgananmu? Atau menimpa langgananmu agar hanya berisi item dari koleksi ini?`,
  _ = `Hanya Menambahkan`,
  _ = `Timpa Langganan Saya`,
  _ = `Item Tambahan yang Diperlukan`,
  _ = `Item ini memerlukan semua item berikut ini agar dapat berfungsi dengan baik.`,
  _ = `<1>%1$s</1> memerlukan semua item berikut ini agar dapat berfungsi dengan baik.`,
  _ = `Kamu dapat mengeklik masing-masing item di sini untuk mempelajari lebih lanjut dan berlangganan ke item tersebut sebelum melanjutkan.`,
  _ = `Kamu juga dapat memilih untuk berlangganan ke semua item yang diperlukan ini (dan semua item yang diperlukan selanjutnya), tapi perlu diingat bahwa itu akan mencakup lebih banyak item.`,
  _ = `Hanya Berlangganan Item Ini`,
  _ = `Berlangganan ke semua`,
  _ = `Laporkan item ini`,
  _ = `Sekarang, deskripsikan pelanggaran Persyaratan Steam terkait item ini. Silakan cantumkan informasi atau tautan yang relevan. Laporan tidak bisa dibatalkan.`,
  _ = `Alasan: %1$s`,
  _ = `Pertama, mohon pilih alasan kenapa kamu melaporkan produk ini:`,
  _ = `Jika kamu ingin melaporkan Pelanggaran Hak Cipta sebagai pemilik hak cipta, mohon isi formulir Laporan Pelanggaran Hak Cipta DMCA kami %1$s.`,
  _ = `Jika kamu ingin mengirimkan keluhan terkait Merek Dagang, silakan lapor %1$s.`,
  _ = `di sini`,
  _ = `Tambahkan ke Koleksi`,
  _ = `"%1$s" akan ditambahkan ke koleksi yang dipilih di bawah ini:`,
  _ = `Kamu tidak memiliki koleksi yang disimpan. Buat yang baru dengan memasukkan nama untuk koleksi di bawah ini.`,
  _ = `Tambahkan ke Koleksi Terpilih`,
  _ = `Buat Koleksi Baru`,
  _ = `Timpa Koleksi`,
  _ = `Apakah kamu ingin menyimpan koleksi ini ke koleksi baru atau yang sudah ada?`,
  _ = `Koleksi Baru`,
  _ = `Koleksi yang Sudah Ada`,
  _ = `Masukkan nama untuk koleksi ini:`,
  _ = `Pilih koleksi yang akan ditimpa:`,
  _ = `Berisi %2$s item`,
  _ = `Berisi %2$s item`,
  _ = `Memiliki %2$s koleksi tertaut`,
  _ = `Memiliki %2$s koleksi tertaut`,
  _ = `+%1$s`,
  _ = `Workshop Steam memudahkanmu untuk mengirimkan model 3D item yang berkesempatan untuk diterima dan dimasukkan ke game-nya. Untuk memublikasikan item di workshop, silakan baca dokumen resmi yang ada di sebelah kanan, lalu klik tombol Workshop Steam di menu utama game-nya.`,
  _ = `Workshop Steam memudahkanmu menemukan atau membagikan konten baru untuk game atau software-mu. Setiap game atau software mungkin mendukung jenis konten yang sedikit berbeda di Workshop-nya, jadi sebaiknya periksa dokumentasi resmi untuk rincian terkait konten apa yang dapat dibuat dan dibagikan secara lebih lanjut.`,
  _ = `Saat kamu menemukan konten yang ingin kamu tambahkan ke dalam game, klik tombol "berlangganan". Umumnya, konten tersebut akan tersedia secara otomatis saat kamu kembali meluncurkan game-nya. Namun, beberapa item mengharuskanmu untuk mengakses bagian dari game atau software tertentu untuk mengaktifkan atau mengakses konten baru tersebut.`,
  _ = `Workshop Steam memudahkanmu untuk menemukan atau membagikan konten baru untuk game maupun software-mu. Setiap produk mungkin mendukung jenis konten yang sedikit berbeda di Workshop-nya. Silakan baca dokumen resminya untuk rincian terkait konten apa yang bisa dibuat dan dibagikan secara lebih lanjut.`,
  _ = `Saat kamu menemukan konten dalam tab %1$s yang ingin kamu tambahkan ke dalam game, klik tombol "berlangganan". Umumnya, konten tersebut akan tersedia secara otomatis saat kamu kembali meluncurkan game-nya. Namun, beberapa item mengharuskanmu untuk mengakses bagian dari game atau software tertentu untuk mengaktifkan atau mengakses konten baru tersebut.`,
  _ = `Fitur yang Diaktifkan`,
  _ = `Berikut adalah fitur Workshop Steam yang digunakan oleh %1$s:`,
  _ = `Item yang Siap Digunakan`,
  _ = `Item yang diposting di Workshop ini sudah siap untuk digunakan. Klik tombol Berlangganan di halaman rincian item-nya dan item tersebut akan dapat digunakan saat kamu meluncurkan %1$s.`,
  _ = `Item yang diposting di Workshop ini dengan tag %2$s sudah siap untuk digunakan. Klik tombol Berlangganan di halaman rincian item-nya dan item tersebut akan dapat digunakan saat kamu meluncurkan %1$s.`,
  _ = `Dukungan Versi untuk Branch Game`,
  _ = `Item dapat memiliki beberapa versi terkaitkan dengan branch game (beta) yang berbeda. Hal ini memudahkan untuk pengembang dan pembuat item Workshop untuk bekerja sama untuk memastikan kompatibilitas item mereka saat %1$s menerima pembaruan.`,
  _ = `Pilihan Item yang Dikurasi`,
  _ = `Item-item yang diposting di Workshop ini tidak dapat langsung digunakan di %1$s. Sebaliknya, pengembang ingin komunitas mengevaluasi item mana yang paling ingin mereka lihat tersedia untuk dibeli atau dibuka di %1$s. Pada akhirnya, pengembang akan memilih item mana yang akan benar-benar diimplementasikan di %1$s.`,
  _ = `Item-item yang diposting di Workshop ini dengan tab %2$s tidak dapat langsung digunakan di %1$s. Pengembang ingin komunitas mengevaluasi item mana yang paling ingin mereka lihat tersedia untuk dibeli atau dibuka di %1$s. Pada akhirnya, pengembang akan memilih item mana yang akan benar-benar diimplementasikan di %1$s.`,
  _ = `Penjualan Item`,
  _ = `Item yang diterima di Workshop akan tersedia untuk dibeli atau dibuka dalam %1$s.`,
  _ = `Penjualan Item Langsung`,
  _ = `Item-item di Workshop ini dapat dijual langsung via Workshop Steam. Item-item ini mungkin memerlukan persetujuan pengembang atau komunitas sebelum tersedia. Kreator Konten: Lihat bagian <a %s>Mendapatkan Pembayaran</a> di bawah ini untuk mempelajari lebih lanjut tentang menjual konten di Workshop Steam`,
  _ = `Kreator Item Bisa Mendapatkan Royalti`,
  _ = `Item-item dari Workshop ini yang diterima untuk dijual akan memberikan sebagian dari hasil penjualan kepada pembuat item tersebut.`,
  _ = `Penyedia Jasa Bisa Mendapatkan Royalti`,
  _ = `Para pembuat di Workshop dapat memilih dari daftar organisasi, pengguna, dan pembuat alat yang telah disetujui sebelumnya untuk menerima persentase pendapatan Valve dari penjualan item mereka. Organisasi dan individu yang dimaksud tercantum di bawah ini.`,
  _ = `Apakah kamu seorang kreator konten yang mengenal organisasi atau individu lain yang ingin kamu ajak untuk berbagi hasil dari penjualan item-mu? Beri tahu kami siapa mereka <a href="%1$s">di sini</a>.`,
  _ = `Bagi Hasil`,
  _ = `Berikut adalah persentase hasil pendapatan penjualan item yang akan diterima oleh pembuatnya.`,
  _ = `Klik %1$s untuk mempelajari lebih lanjut.`,
  _ = `di sini`,
  _ = `Item yang diposting di Workshop ini`,
  _ = `Item yang diterima untuk %1$s`,
  _ = `Tautan Terkait`,
  _ = `Lihat Dokumentasi Resmi`,
  _ = `Temukan Panduan Steam`,
  _ = `Panduan buatan komunitas untuk Workshop ini`,
  _ = `Untuk pembelian via Workshop Steam`,
  _ = `Persyaratan Workshop Steam`,
  _ = `Untuk Pendapatan Workshop Steam`,
  _ = `Penyedia Jasa`,
  _ = `Lihat Situs`,
  _ = `Lihat Profil Steam`,
  _ = `Alat`,
  _ = `Komunitas`,
  _ = `Pengguna`,
  _ = `Lihat Rincian`,
  _ = `Tampilan Cepat`,
  _ = `Vote`,
  _ = `untuk item yang dibuat komunitas yang ingin kamu lihat di dalam game`,
  _ = `Klik untuk memulai voting di Daftarmu.`,
  _ = `Sejauh ini kamu sudah mem-voting %1$s item.`,
  _ = `Sejauh ini kamu sudah mem-voting %1$s item.`,
  _ = `Dalam satu minggu terakhir`,
  _ = `Dalam satu bulan terakhir`,
  _ = `Dalam tiga bulan terakhir`,
  _ = `Dalam enam bulan terakhir`,
  _ = `Dalam satu tahun terakhir`,
  _ = `Dari Pembuat yang Diikuti`,
  _ = `Item yang baru saja diposting oleh pembuat yang kamu ikuti`,
  _ = `Lainnya dari pembuat yang diikuti`,
  _ = `Item yang Disetujui`,
  _ = `Item ini telah disetujui dan akan tersedia sebagai drop atau dapat dibeli di dalam game`,
  _ = `Lihat semua item yang disetujui`,
  _ = `%1$s Terpopuler`,
  _ = `Terpopuler`,
  _ = `Terbaik dalam tiga bulan terakhir`,
  _ = `Lihat yang paling populer`,
  _ = `Langganan Terbanyak`,
  _ = `Pelanggan unik terkini`,
  _ = `Lihat langganan terbanyak`,
  _ = `Baru`,
  _ = `Item yang diposting baru-baru ini`,
  _ = `Lihat yang baru saja diposting`,
  _ = `Waktu Bermain Terbanyak`,
  _ = `Lihat yang paling sering dimainkan`,
  _ = `Terakhir Diperbarui`,
  _ = `Item yang diperbarui baru-baru ini`,
  _ = `Lihat yang baru saja diperbarui`,
  _ = `Favorit Teman`,
  _ = `Item yang ditandai sebagai favorit oleh temanmu`,
  _ = `Lihat semua favorit teman`,
  _ = `Paling Diperlukan oleh Item Lain`,
  _ = `Item paling populer yang dibutuhkan agar item lain dapat berfungsi dengan baik`,
  _ = `Lihat Semua`,
  _ = `Merchandise Terpopuler`,
  _ = `Lihat semua Merchandise Populer`,
  _ = `Lihat Semua`,
  _ = `Favoritmu`,
  _ = `Lihat favorit yang baru saja diperbarui`,
  _ = `Item yang Kamu Gunakan`,
  _ = `Lihat item-item yang baru saja diperbarui dan kamu gunakan`,
  _ = `Langgananmu`,
  _ = `Lihat langganan-langgananmu yang baru saja diperbarui`,
  _ = `Diperbarui dalam tiga bulan terakhir`,
  _ = `Event Spesial: %1$s`,
  _ = `Lihat semua item yang ditandai dengan %1$s`,
  _ = `%1$s teman telah menambahkan ini ke favoritnya`,
  _ = `%1$s teman telah menambahkan ini ke favorit mereka`,
  _ = `Map`,
  _ = `Item`,
  _ = `Game Kustom dan Skrip Bot`,
  _ = `Item`,
  _ = `Filter berdasarkan Hero`,
  _ = `Map`,
  _ = `Item`,
  _ = {
    language: _,
    Header_WorkshopTitle: _,
    Header_App_WorkshopTitle: _,
    Workshop_Error_Loading: _,
    Workshop_Error_Title: _,
    Workshop_Error_Browse_Desc: _,
    Error_Sorry: _,
    Error_Encountered: _,
    Error_TooManyRequests_Description: _,
    Workshop_ExitReact_Link: _,
    Workshop_Browsing: _,
    Workshop_Browsing_Mtx_Desc: _,
    Workshop_Browsing_ReadyToUse_Desc: _,
    Workshop_Browsing_Merchandise_Desc: _,
    Workshop_AcceptedForGame: _,
    Workshop_AcceptedMerch: _,
    Workshop_OfficialContent: _,
    Workshop_Browse_Author_Link: _,
    Workshop_Section_Mtx: _,
    Workshop_Section_ReadyToUse: _,
    Workshop_Section_Collections: _,
    Workshop_Section_Merchandise: _,
    Workshop_Section_Videos: _,
    Workshop_Saved_Queries: _,
    Workshop_Saved_Queries_Update: _,
    Workshop_Saved_Queries_Save_Title: _,
    Workshop_Saved_Queries_Save_Desc_Long: _,
    Workshop_Saved_Queries_Save_Desc: _,
    Workshop_Saved_Queries_Save_New: _,
    Workshop_Saved_Queries_Save_Btn: _,
    Workshop_Saved_Queries_Delete_Title: _,
    Workshop_Saved_Queries_Delete_Desc: _,
    Workshop_Saved_Queries_Delete_Btn: _,
    Workshop_LearnMore: _,
    Workshop_Filters_ClearBtn: _,
    Workshop_About: _,
    Workshop_BrowseSort_SortOrder: _,
    Workshop_BrowseSort_TimeFrame: _,
    SharedFiles_Browse_Trend_Option_Today: _,
    SharedFiles_Browse_Trend_Option_Week: _,
    SharedFiles_Browse_Trend_Option_Month: _,
    SharedFiles_Browse_Trend_Option_ThreeMonths: _,
    SharedFiles_Browse_Trend_Option_SixMonths: _,
    SharedFiles_Browse_Trend_Option_OneYear: _,
    SharedFiles_Browse_Trend_Option_AllTime: _,
    Workshop_BrowseSort_Combined: _,
    Workshop_BrowseSort_MostRecent: _,
    Workshop_BrowseSort_MostPopular: _,
    Workshop_BrowseSort_TopRated: _,
    Workshop_BrowseSort_LastUpdated: _,
    Workshop_BrowseSort_Reported: _,
    Workshop_BrowseSort_AdminOption: _,
    Workshop_BrowseSort_NumParentItems: _,
    Workshop_BrowseSort_NumParentCollections: _,
    Workshop_RequireApproval: _,
    Workshop_BrowseSort_ToRate: _,
    Workshop_BrowseSort_TotalUniqueSubscribers: _,
    Workshop_BrowseSort_TotalVotes: _,
    Workshop_BrowseSort_MostUpVotes: _,
    Workshop_BrowseSort_SearchRelevance: _,
    Workshop_BrowseSort_Playtime: _,
    Workshop_BrowseSort_PlaytimeTotal: _,
    Workshop_BrowseSort_PlaytimeAverage: _,
    Workshop_BrowseSort_PlaytimeAverageTotal: _,
    Workshop_BrowseSort_PlaytimeSessions: _,
    Workshop_BrowseSort_PlaytimeSessionsTotal: _,
    Workshop_BrowseSort_Inappropriate: _,
    Workshop_BrowseSort_BanContentCheck: _,
    Workshop_BrowseSort_CuratedAdmin: _,
    Workshop_BrowseSort_Nominee: _,
    Workshop_BrowseSort_Rated: _,
    Workshop_BrowseSort_AcceptedTime: _,
    Workshop_SpecialFilter_Desc: _,
    Workshop_SpecialFilter_None: _,
    Workshop_SpecialFilter_AcceptedForUse: _,
    Workshop_SpecialFilter_CreatedByFriends: _,
    Workshop_SpecialFilter_CreatedByFollowed: _,
    Workshop_SpecialFilter_FavoritedByFriends: _,
    Workshop_SpecialFilter_Reported: _,
    Workshop_SpecialFilter_ParentItems: _,
    Workshop_SpecialFilter_ParentCollections: _,
    Workshop_Menu_Home: _,
    Workshop_Menu_Browse: _,
    Workshop_Menu_YourItems: _,
    Workshop_Menu_Discussions: _,
    Workshop_Menu_About: _,
    Workshop_Menu_Search: _,
    Workshop_SubMenu_YourItems: _,
    Workshop_SubMenu_YourFavorites: _,
    Workshop_SubMenu_YourSubscriptions: _,
    Workshop_SubMenu_YourPlayed: _,
    Workshop_SubMenu_YourCollections: _,
    Workshop_SubMenu_YourVotingQueue: _,
    Workshop_SubMenu_YourPaymentInfo: _,
    Workshop_SubMenu_ViewYourRevenue: _,
    Workshop_SubMenu_ViewYourRevenue_Desc: _,
    Workshop_SubMenu_LegalAgreement: _,
    Workshop_SubMenu_VotingQueue: _,
    Workshop_ApplyFilters: _,
    Workshop_SortBy: _,
    Workshop_Tag_NoneSpecified: _,
    Workshop_RequiredDLC_Header: _,
    Workshop_RequiredDLC_Filter: _,
    Workshop_IncludeOwnedDLC_Filter: _,
    Workshop_ExcludeOwnedDLC_Filter: _,
    Workshop_OwnedDLC_None_Filter: _,
    Workshop_OwnedDLC_All_Filter: _,
    Workshop_OwnedDLC_More_Filter: _,
    Workshop_RequiredDLC_IncludeOwned: _,
    Workshop_RequiredDLC_ExcludeUnowned: _,
    Workshop_RequiredDLC_NameFilter: _,
    Workshop_Flag_Incompatible_Checkbox: _,
    Workshop_Flag_Incompatible_Checkbox_Desc: _,
    Workshop_Admin_View: _,
    Workshop_SearchResults_SearchText: _,
    Workshop_SearchResults_SearchText_TitleOnly: _,
    Workshop_SearchResults_SearchText_DescriptionOnly: _,
    Workshop_SearchedForChild: _,
    Workshop_SearchedForRequiredItem: _,
    Workshop_SearchResults_Tag: _,
    Workshop_SearchResults_KVTag: _,
    Workshop_SearchResults_Flag_Incompatible: _,
    Workshop_SearchResults_Flag_Accepted: _,
    Workshop_SearchTarget_MenuTitle: _,
    Workshop_SearchTarget_All: _,
    Workshop_SearchTarget_Title: _,
    Workshop_SearchTarget_Description: _,
    Workshop_Search_Help: _,
    Workshop_Search_Help_Example1: _,
    Workshop_Search_Help_Example2: _,
    Workshop_Search_Help_Example3: _,
    Workshop_Search_Help_Example_Red: _,
    Workshop_Search_Help_Example_Blue: _,
    Workshop_Search_Help_Example_Green: _,
    Workshop_Search_Help_Example_Room: _,
    Workshop_Search_Help_Advanced: _,
    Workshop_Search_Help_AdvancedExample1: _,
    Workshop_Search_Help_AdvancedExample2: _,
    Workshop_FiltersMenu_State_Title: _,
    Workshop_FiltersMenu_State_Left: _,
    Workshop_FiltersMenu_State_Right: _,
    Workshop_FiltersMenu_State_Collapsed: _,
    Workshop_DimmedItems_Title: _,
    Workshop_DimmedItems_Reported: _,
    Workshop_DimmedItems_BlockedCreators: _,
    Workshop_DimmedItems_VotedUp: _,
    Workshop_DimmedItems_VotedDown: _,
    Workshop_DimmedItems_Subscribed: _,
    Workshop_DateFilter_FilterByDate: _,
    Workshop_DateFilter_TimeCreated: _,
    Workshop_DateFilter_TimeCreated_After: _,
    Workshop_DateFilter_TimeCreated_Before: _,
    Workshop_DateFilter_TimeCreated_Between: _,
    Workshop_DateFilter_TimeUpdated: _,
    Workshop_DateFilter_TimeUpdated_After: _,
    Workshop_DateFilter_TimeUpdated_Before: _,
    Workshop_DateFilter_TimeUpdated_Between: _,
    Workshop_DateFilter_Between: _,
    Workshop_DateFilter_And: `Dan`,
    Workshop_NumResults: _,
    Workshop_NumResults_Plural: _,
    Workshop_NumPerPage: _,
    Workshop_PagingControls: _,
    Workshop_CreateCollection: _,
    Workshop_CreateMerchandise: _,
    Workshop_Item_QuickView: _,
    Workshop_Item_QuickView_ExpandBtn: _,
    Workshop_StatusIcon_TT_Subscribed: _,
    Workshop_StatusIcon_TT_Favorited: _,
    Workshop_StatusIcon_TT_Played: _,
    Workshop_StatusIcon_TT_Accepted: _,
    Workshop_StatusIcon_TT_Incompatible: _,
    Workshop_StatusIcon_TT_VotedUp: _,
    Workshop_StatusIcon_TT_VotedDown: _,
    Workshop_StatusIcon_TT_Reported: _,
    Workshop_StatusIcon_TT_BlockedCreator: _,
    Workshop_ItemDetails_Tab_Description: _,
    Workshop_ItemDetails_Tab_Discussions: _,
    Workshop_ItemDetails_Tab_Comments: _,
    Workshop_ItemDetails_Tab_Updates: _,
    Workshop_ItemDetails_Tab_Stats: _,
    Workshop_ItemDetails_Tab_ChangeNotes: _,
    Workshop_ItemDetails_Title: _,
    Workshop_ItemDetails_CreatedBy: _,
    Workshop_ItemDetails_NumRatings: _,
    Workshop_ItemDetails_NumRatings_Plural: _,
    Workshop_ItemDetails_NotEnoughRatings: _,
    Workshop_ItemDetails_TimestampWithTime: _,
    Workshop_ItemDetails_TimestampCreated: _,
    Workshop_ItemDetails_TimestampUpdated: _,
    Workshop_ItemDetails_Subscribe: _,
    Workshop_ItemDetails_Subscribed: _,
    Workshop_ItemDetails_Unsubscribe: _,
    Workshop_ItemDetails_Favorite: _,
    Workshop_ItemDetails_Favorited: _,
    Workshop_ItemDetails_Unfavorite: _,
    Workshop_ItemDetails_ViewDependentItems: _,
    Workshop_ItemDetails_AddToCollection: _,
    Workshop_ItemDetails_SaveCollectionToCollection: _,
    Workshop_ItemDetails_Signin_TT: _,
    Workshop_ItemDetails_Subscribe_TT: _,
    Workshop_ItemDetails_Unsubscribe_TT: _,
    Workshop_ItemDetails_Favorite_TT: _,
    Workshop_ItemDetails_ViewDependentItems_TT: _,
    Workshop_ItemDetails_Report_TT: _,
    Workshop_ItemDetails_Award_TT: _,
    Workshop_ItemDetails_AddToCollection_TT: _,
    Workshop_ItemDetails_FileSize: _,
    Workshop_ItemDetails_Stats_UniqueVisitors: _,
    Workshop_ItemDetails_Stats_CurrentSubscribers: _,
    Workshop_ItemDetails_Stats_CurrentFavorites: _,
    Workshop_ItemDetails_Stats_LifetimeFavorites: _,
    Workshop_ItemDetails_Stats_LifetimeSubscribers: _,
    Workshop_ItemDetails_Stats_LifetimePlaytimeSessions: _,
    Workshop_ItemDetails_ItemDependencies: _,
    Workshop_ItemDetails_RequiredDLC_Desc: _,
    Workshop_Collection_SubscribeToAll: _,
    Workshop_Collection_UnsubscribeFromAll: _,
    Workshop_Collection_SaveToCollection: _,
    Workshop_ItemDetails_ShowAllReactions: _,
    Workshop_ItemDetails_ReactionCount: _,
    Workshop_ItemDetails_ReactionCount_Plural: _,
    Workshop_ItemDetails_Tags_Title: `TAG`,
    Workshop_ItemDetails_Categories_Title: _,
    Workshop_ItemDetails_Description_Title: _,
    Workshop_ItemDetails_DependentItems: _,
    Workshop_ItemDetails_InCollections: _,
    Workshop_ItemDetails_InCollectionsByAuthor: _,
    Workshop_Dialog_Error: _,
    Workshop_Dialog_AccessDenied: _,
    Workshop_Dialog_Timeout: _,
    Workshop_Dialog_LimitExceeded: _,
    Workshop_Dialog_ErrorDesc: _,
    Workshop_Dialog_CollectionSubscribe: _,
    Workshop_Dialog_CollectionSubscribe_Desc: _,
    Workshop_Dialog_CollectionSubscribe_AddOnly: _,
    Workshop_Dialog_CollectionSubscribe_Overwrite: _,
    Workshop_Dialog_ItemDependencies: _,
    Workshop_Dialog_ItemDependencies_Desc1: _,
    Workshop_Dialog_ItemDependencies_Desc1_itemName: _,
    Workshop_Dialog_ItemDependencies_Desc2: _,
    Workshop_Dialog_ItemDependencies_Desc3: _,
    Workshop_Dialog_SubscribeJustThisItem: _,
    Workshop_Dialog_SubscribeAll: _,
    Workshop_Dialog_Report: _,
    Workshop_Dialog_Report_Desc: _,
    Workshop_Dialog_Report_Reason: _,
    Workshop_Dialog_Report_Reason_Desc: _,
    Workshop_Dialog_Report_DMCA_Desc: _,
    Workshop_Dialog_Report_Trademark_Desc: _,
    Workshop_Dialog_Report_Here: _,
    Workshop_Dialog_AddToCollection: _,
    Workshop_Dialog_AddToCollection_Desc: _,
    Workshop_Dialog_AddToCollection_NoSavedCollections_Desc: _,
    Workshop_Dialog_AddToCollection_OK: _,
    Workshop_Dialog_AddToCollection_Create: _,
    Workshop_Dialog_SaveCollectionToCollection: _,
    Workshop_Dialog_SaveCollectionToCollection_Desc: _,
    Workshop_Dialog_SaveCollectionToCollection_New: _,
    Workshop_Dialog_SaveCollectionToCollection_Existing: _,
    Workshop_Dialog_SaveCollectionToCollection_NewPrompt: _,
    Workshop_Dialog_SaveCollectionToCollection_Select: _,
    Workshop_Collection_NumChildItems: _,
    Workshop_Collection_NumChildItems_Plural: _,
    Workshop_Collection_NumChildCollections: _,
    Workshop_Collection_NumChildCollections_Plural: _,
    Workshop_Collection_ViewMore: _,
    Workshop_About_PageDesc_Curation: _,
    Workshop_About_PageDesc_ReadyToUseContent1: _,
    Workshop_About_PageDesc_ReadyToUseContent2: _,
    Workshop_About_PageDesc_ReadyToUseContent_Mixed1: _,
    Workshop_About_PageDesc_ReadyToUseContent_Mixed2: _,
    Workshop_About_EnabledFeatures: _,
    Workshop_About_EnabledFeatures_Desc: _,
    Workshop_About_Feature_ReadyToUse: _,
    Workshop_About_Feature_ReadyToUse_Desc: _,
    Workshop_About_Feature_ReadyToUse_Mixed_Desc: _,
    Workshop_About_Feature_Branch_Versioning: _,
    Workshop_About_Feature_Branch_Versioning_Desc: _,
    Workshop_About_Feature_ItemCuration: _,
    Workshop_About_Feature_ItemCuration_Desc: _,
    Workshop_About_Feature_ItemCuration_Mixed_Desc: _,
    Workshop_About_Feature_ItemMtx: _,
    Workshop_About_Feature_ItemMtx_Desc: _,
    Workshop_About_Feature_Commerce: _,
    Workshop_About_Feature_Commerce_Desc: _,
    Workshop_About_Feature_AuthorRoyalties: _,
    Workshop_About_Feature_AuthorRoyalties_Desc: _,
    Workshop_About_Feature_ServiceProviders: _,
    Workshop_About_Feature_ServiceProviders_Desc: _,
    Workshop_About_Request_ServiceProviders: _,
    Workshop_About_RevenueShare: _,
    Workshop_About_RevenueShare_Desc: _,
    Workshop_About_RevenueShare_Link: _,
    Workshop_About_RevenueShare_Here: _,
    Workshop_About_NumItems: _,
    Workshop_About_NumAcceptedItems: _,
    Workshop_About_RelatedLinks: _,
    Workshop_About_ViewOfficialDocs: _,
    Workshop_About_FindGuides: _,
    Workshop_About_FindGuides_Sub: _,
    Workshop_About_RefundLink_Sub: _,
    Workshop_About_WorkshopTerms: _,
    Workshop_About_WorkshopTerms_Sub: _,
    Workshop_About_section_ServiceProviders: _,
    Workshop_ServiceProviderRevenueSharing_ViewSite: _,
    Workshop_ServiceProviderRevenueSharing_ViewSteamProfile: _,
    Workshop_ServiceProvider_Category_Tools: _,
    Workshop_ServiceProvider_Category_Communities: _,
    Workshop_ServiceProvider_Category_Users: _,
    Workshop_GamepadUIAction_ViewDetails: _,
    Workshop_GamepadUIAction_QuickView: _,
    Workshop_Home_VotingQueue: _,
    Workshop_Home_VotingQueue_Desc: _,
    Workshop_Home_VotingQueue_Btn: _,
    Workshop_Home_VotingQueue_Count: _,
    Workshop_Home_VotingQueue_Count_Plural: _,
    Workshop_Home_MostPopular_SubTitle_Week: _,
    Workshop_Home_MostPopular_SubTitle_Month: _,
    Workshop_Home_MostPopular_SubTitle_ThreeMonths: _,
    Workshop_Home_MostPopular_SubTitle_SixMonths: _,
    Workshop_Home_MostPopular_SubTitle_Year: _,
    Workshop_Home_FromFollowedAuthors: _,
    Workshop_Home_FromFollowedAuthors_Desc: _,
    Workshop_Home_FromFollowedAuthors_Btn: _,
    Workshop_Home_AcceptedItems: _,
    Workshop_Home_AcceptedItems_Desc: _,
    Workshop_Home_AcceptedItems_Btn: _,
    Workshop_Home_MostPopular: _,
    Workshop_Home_MostPopular_LongTerm: _,
    Workshop_Home_MostPopular_LongTerm_Desc: _,
    Workshop_Home_MostPopular_LongTerm_Btn: _,
    Workshop_Home_MostSubscribed: _,
    Workshop_Home_MostSubscribed_Desc: _,
    Workshop_Home_MostSubscribed_Btn: _,
    Workshop_Home_MostRecent: _,
    Workshop_Home_MostRecent_Desc: _,
    Workshop_Home_MostRecent_Btn: _,
    Workshop_Home_MostPlaytime: _,
    Workshop_Home_MostPlaytime_Btn: _,
    Workshop_Home_LastUpdated: _,
    Workshop_Home_LastUpdated_Desc: _,
    Workshop_Home_LastUpdated_Btn: _,
    Workshop_Home_FriendsFavorites: _,
    Workshop_Home_FriendsFavorites_Desc: _,
    Workshop_Home_FriendsFavorites_Btn: _,
    Workshop_Home_NumParentItems: _,
    Workshop_Home_NumParentItems_Desc: _,
    Workshop_Home_NumParentItems_Btn: _,
    Workshop_Home_MostPopularMerch: _,
    Workshop_Home_MostPopularMerch_Btn: _,
    Workshop_Home_ViewAll: _,
    Workshop_Home_YourFavorites: _,
    Workshop_Home_YourFavorites_Btn: _,
    Workshop_Home_YourPlayed: _,
    Workshop_Home_YourPlayed_Btn: _,
    Workshop_Home_YourSubscriptions: _,
    Workshop_Home_YourSubscriptions_Btn: _,
    Workshop_Home_YourFiles_LastUpdated: _,
    Workshop_Home_SpecialEvent_Title_Tag: _,
    Workshop_Home_SpecialEvent_Link: _,
    Workshop_ItemTooltip_FriendsWhoFavorited: _,
    Workshop_ItemTooltip_FriendsWhoFavorited_Plural: _,
    SharedFiles_TF2_Tab_Items_ReadyToUse: `Map`,
    SharedFiles_TF2_Tab_Items_Mtx: _,
    SharedFiles_Dota2_Tab_Items_ReadyToUse: _,
    SharedFiles_Dota2_Tab_Items_Mtx: _,
    SharedFiles_Dota2_HeroPicker: _,
    SharedFiles_CSGO_Tab_Items_ReadyToUse: `Map`,
    SharedFiles_CSGO_Tab_Items_Mtx: _,
  };
export {
  _ as Error_Encountered,
  _ as Error_Sorry,
  _ as Error_TooManyRequests_Description,
  _ as Header_App_WorkshopTitle,
  _ as Header_WorkshopTitle,
  _ as SharedFiles_Browse_Trend_Option_AllTime,
  _ as SharedFiles_Browse_Trend_Option_Month,
  _ as SharedFiles_Browse_Trend_Option_OneYear,
  _ as SharedFiles_Browse_Trend_Option_SixMonths,
  _ as SharedFiles_Browse_Trend_Option_ThreeMonths,
  _ as SharedFiles_Browse_Trend_Option_Today,
  _ as SharedFiles_Browse_Trend_Option_Week,
  _ as SharedFiles_CSGO_Tab_Items_Mtx,
  _ as SharedFiles_CSGO_Tab_Items_ReadyToUse,
  _ as SharedFiles_Dota2_HeroPicker,
  _ as SharedFiles_Dota2_Tab_Items_Mtx,
  _ as SharedFiles_Dota2_Tab_Items_ReadyToUse,
  _ as SharedFiles_TF2_Tab_Items_Mtx,
  _ as SharedFiles_TF2_Tab_Items_ReadyToUse,
  _ as Workshop_About,
  _ as Workshop_About_EnabledFeatures,
  _ as Workshop_About_EnabledFeatures_Desc,
  _ as Workshop_About_Feature_AuthorRoyalties,
  _ as Workshop_About_Feature_AuthorRoyalties_Desc,
  _ as Workshop_About_Feature_Branch_Versioning,
  _ as Workshop_About_Feature_Branch_Versioning_Desc,
  _ as Workshop_About_Feature_Commerce,
  _ as Workshop_About_Feature_Commerce_Desc,
  _ as Workshop_About_Feature_ItemCuration,
  _ as Workshop_About_Feature_ItemCuration_Desc,
  _ as Workshop_About_Feature_ItemCuration_Mixed_Desc,
  _ as Workshop_About_Feature_ItemMtx,
  _ as Workshop_About_Feature_ItemMtx_Desc,
  _ as Workshop_About_Feature_ReadyToUse,
  _ as Workshop_About_Feature_ReadyToUse_Desc,
  _ as Workshop_About_Feature_ReadyToUse_Mixed_Desc,
  _ as Workshop_About_Feature_ServiceProviders,
  _ as Workshop_About_Feature_ServiceProviders_Desc,
  _ as Workshop_About_FindGuides,
  _ as Workshop_About_FindGuides_Sub,
  _ as Workshop_About_NumAcceptedItems,
  _ as Workshop_About_NumItems,
  _ as Workshop_About_PageDesc_Curation,
  _ as Workshop_About_PageDesc_ReadyToUseContent1,
  _ as Workshop_About_PageDesc_ReadyToUseContent2,
  _ as Workshop_About_PageDesc_ReadyToUseContent_Mixed1,
  _ as Workshop_About_PageDesc_ReadyToUseContent_Mixed2,
  _ as Workshop_About_RefundLink_Sub,
  _ as Workshop_About_RelatedLinks,
  _ as Workshop_About_Request_ServiceProviders,
  _ as Workshop_About_RevenueShare,
  _ as Workshop_About_RevenueShare_Desc,
  _ as Workshop_About_RevenueShare_Here,
  _ as Workshop_About_RevenueShare_Link,
  _ as Workshop_About_ViewOfficialDocs,
  _ as Workshop_About_WorkshopTerms,
  _ as Workshop_About_WorkshopTerms_Sub,
  _ as Workshop_About_section_ServiceProviders,
  _ as Workshop_AcceptedForGame,
  _ as Workshop_AcceptedMerch,
  _ as Workshop_Admin_View,
  _ as Workshop_ApplyFilters,
  _ as Workshop_BrowseSort_AcceptedTime,
  _ as Workshop_BrowseSort_AdminOption,
  _ as Workshop_BrowseSort_BanContentCheck,
  _ as Workshop_BrowseSort_Combined,
  _ as Workshop_BrowseSort_CuratedAdmin,
  _ as Workshop_BrowseSort_Inappropriate,
  _ as Workshop_BrowseSort_LastUpdated,
  _ as Workshop_BrowseSort_MostPopular,
  _ as Workshop_BrowseSort_MostRecent,
  _ as Workshop_BrowseSort_MostUpVotes,
  _ as Workshop_BrowseSort_Nominee,
  _ as Workshop_BrowseSort_NumParentCollections,
  _ as Workshop_BrowseSort_NumParentItems,
  _ as Workshop_BrowseSort_Playtime,
  _ as Workshop_BrowseSort_PlaytimeAverage,
  _ as Workshop_BrowseSort_PlaytimeAverageTotal,
  _ as Workshop_BrowseSort_PlaytimeSessions,
  _ as Workshop_BrowseSort_PlaytimeSessionsTotal,
  _ as Workshop_BrowseSort_PlaytimeTotal,
  _ as Workshop_BrowseSort_Rated,
  _ as Workshop_BrowseSort_Reported,
  _ as Workshop_BrowseSort_SearchRelevance,
  _ as Workshop_BrowseSort_SortOrder,
  _ as Workshop_BrowseSort_TimeFrame,
  _ as Workshop_BrowseSort_ToRate,
  _ as Workshop_BrowseSort_TopRated,
  _ as Workshop_BrowseSort_TotalUniqueSubscribers,
  _ as Workshop_BrowseSort_TotalVotes,
  _ as Workshop_Browse_Author_Link,
  _ as Workshop_Browsing,
  _ as Workshop_Browsing_Merchandise_Desc,
  _ as Workshop_Browsing_Mtx_Desc,
  _ as Workshop_Browsing_ReadyToUse_Desc,
  _ as Workshop_Collection_NumChildCollections,
  _ as Workshop_Collection_NumChildCollections_Plural,
  _ as Workshop_Collection_NumChildItems,
  _ as Workshop_Collection_NumChildItems_Plural,
  _ as Workshop_Collection_SaveToCollection,
  _ as Workshop_Collection_SubscribeToAll,
  _ as Workshop_Collection_UnsubscribeFromAll,
  _ as Workshop_Collection_ViewMore,
  _ as Workshop_CreateCollection,
  _ as Workshop_CreateMerchandise,
  _ as Workshop_DateFilter_And,
  _ as Workshop_DateFilter_Between,
  _ as Workshop_DateFilter_FilterByDate,
  _ as Workshop_DateFilter_TimeCreated,
  _ as Workshop_DateFilter_TimeCreated_After,
  _ as Workshop_DateFilter_TimeCreated_Before,
  _ as Workshop_DateFilter_TimeCreated_Between,
  _ as Workshop_DateFilter_TimeUpdated,
  _ as Workshop_DateFilter_TimeUpdated_After,
  _ as Workshop_DateFilter_TimeUpdated_Before,
  _ as Workshop_DateFilter_TimeUpdated_Between,
  _ as Workshop_Dialog_AccessDenied,
  _ as Workshop_Dialog_AddToCollection,
  _ as Workshop_Dialog_AddToCollection_Create,
  _ as Workshop_Dialog_AddToCollection_Desc,
  _ as Workshop_Dialog_AddToCollection_NoSavedCollections_Desc,
  _ as Workshop_Dialog_AddToCollection_OK,
  _ as Workshop_Dialog_CollectionSubscribe,
  _ as Workshop_Dialog_CollectionSubscribe_AddOnly,
  _ as Workshop_Dialog_CollectionSubscribe_Desc,
  _ as Workshop_Dialog_CollectionSubscribe_Overwrite,
  _ as Workshop_Dialog_Error,
  _ as Workshop_Dialog_ErrorDesc,
  _ as Workshop_Dialog_ItemDependencies,
  _ as Workshop_Dialog_ItemDependencies_Desc1,
  _ as Workshop_Dialog_ItemDependencies_Desc1_itemName,
  _ as Workshop_Dialog_ItemDependencies_Desc2,
  _ as Workshop_Dialog_ItemDependencies_Desc3,
  _ as Workshop_Dialog_LimitExceeded,
  _ as Workshop_Dialog_Report,
  _ as Workshop_Dialog_Report_DMCA_Desc,
  _ as Workshop_Dialog_Report_Desc,
  _ as Workshop_Dialog_Report_Here,
  _ as Workshop_Dialog_Report_Reason,
  _ as Workshop_Dialog_Report_Reason_Desc,
  _ as Workshop_Dialog_Report_Trademark_Desc,
  _ as Workshop_Dialog_SaveCollectionToCollection,
  _ as Workshop_Dialog_SaveCollectionToCollection_Desc,
  _ as Workshop_Dialog_SaveCollectionToCollection_Existing,
  _ as Workshop_Dialog_SaveCollectionToCollection_New,
  _ as Workshop_Dialog_SaveCollectionToCollection_NewPrompt,
  _ as Workshop_Dialog_SaveCollectionToCollection_Select,
  _ as Workshop_Dialog_SubscribeAll,
  _ as Workshop_Dialog_SubscribeJustThisItem,
  _ as Workshop_Dialog_Timeout,
  _ as Workshop_DimmedItems_BlockedCreators,
  _ as Workshop_DimmedItems_Reported,
  _ as Workshop_DimmedItems_Subscribed,
  _ as Workshop_DimmedItems_Title,
  _ as Workshop_DimmedItems_VotedDown,
  _ as Workshop_DimmedItems_VotedUp,
  _ as Workshop_Error_Browse_Desc,
  _ as Workshop_Error_Loading,
  _ as Workshop_Error_Title,
  _ as Workshop_ExcludeOwnedDLC_Filter,
  _ as Workshop_ExitReact_Link,
  _ as Workshop_FiltersMenu_State_Collapsed,
  _ as Workshop_FiltersMenu_State_Left,
  _ as Workshop_FiltersMenu_State_Right,
  _ as Workshop_FiltersMenu_State_Title,
  _ as Workshop_Filters_ClearBtn,
  _ as Workshop_Flag_Incompatible_Checkbox,
  _ as Workshop_Flag_Incompatible_Checkbox_Desc,
  _ as Workshop_GamepadUIAction_QuickView,
  _ as Workshop_GamepadUIAction_ViewDetails,
  _ as Workshop_Home_AcceptedItems,
  _ as Workshop_Home_AcceptedItems_Btn,
  _ as Workshop_Home_AcceptedItems_Desc,
  _ as Workshop_Home_FriendsFavorites,
  _ as Workshop_Home_FriendsFavorites_Btn,
  _ as Workshop_Home_FriendsFavorites_Desc,
  _ as Workshop_Home_FromFollowedAuthors,
  _ as Workshop_Home_FromFollowedAuthors_Btn,
  _ as Workshop_Home_FromFollowedAuthors_Desc,
  _ as Workshop_Home_LastUpdated,
  _ as Workshop_Home_LastUpdated_Btn,
  _ as Workshop_Home_LastUpdated_Desc,
  _ as Workshop_Home_MostPlaytime,
  _ as Workshop_Home_MostPlaytime_Btn,
  _ as Workshop_Home_MostPopular,
  _ as Workshop_Home_MostPopularMerch,
  _ as Workshop_Home_MostPopularMerch_Btn,
  _ as Workshop_Home_MostPopular_LongTerm,
  _ as Workshop_Home_MostPopular_LongTerm_Btn,
  _ as Workshop_Home_MostPopular_LongTerm_Desc,
  _ as Workshop_Home_MostPopular_SubTitle_Month,
  _ as Workshop_Home_MostPopular_SubTitle_SixMonths,
  _ as Workshop_Home_MostPopular_SubTitle_ThreeMonths,
  _ as Workshop_Home_MostPopular_SubTitle_Week,
  _ as Workshop_Home_MostPopular_SubTitle_Year,
  _ as Workshop_Home_MostRecent,
  _ as Workshop_Home_MostRecent_Btn,
  _ as Workshop_Home_MostRecent_Desc,
  _ as Workshop_Home_MostSubscribed,
  _ as Workshop_Home_MostSubscribed_Btn,
  _ as Workshop_Home_MostSubscribed_Desc,
  _ as Workshop_Home_NumParentItems,
  _ as Workshop_Home_NumParentItems_Btn,
  _ as Workshop_Home_NumParentItems_Desc,
  _ as Workshop_Home_SpecialEvent_Link,
  _ as Workshop_Home_SpecialEvent_Title_Tag,
  _ as Workshop_Home_ViewAll,
  _ as Workshop_Home_VotingQueue,
  _ as Workshop_Home_VotingQueue_Btn,
  _ as Workshop_Home_VotingQueue_Count,
  _ as Workshop_Home_VotingQueue_Count_Plural,
  _ as Workshop_Home_VotingQueue_Desc,
  _ as Workshop_Home_YourFavorites,
  _ as Workshop_Home_YourFavorites_Btn,
  _ as Workshop_Home_YourFiles_LastUpdated,
  _ as Workshop_Home_YourPlayed,
  _ as Workshop_Home_YourPlayed_Btn,
  _ as Workshop_Home_YourSubscriptions,
  _ as Workshop_Home_YourSubscriptions_Btn,
  _ as Workshop_IncludeOwnedDLC_Filter,
  _ as Workshop_ItemDetails_AddToCollection,
  _ as Workshop_ItemDetails_AddToCollection_TT,
  _ as Workshop_ItemDetails_Award_TT,
  _ as Workshop_ItemDetails_Categories_Title,
  _ as Workshop_ItemDetails_CreatedBy,
  _ as Workshop_ItemDetails_DependentItems,
  _ as Workshop_ItemDetails_Description_Title,
  _ as Workshop_ItemDetails_Favorite,
  _ as Workshop_ItemDetails_Favorite_TT,
  _ as Workshop_ItemDetails_Favorited,
  _ as Workshop_ItemDetails_FileSize,
  _ as Workshop_ItemDetails_InCollections,
  _ as Workshop_ItemDetails_InCollectionsByAuthor,
  _ as Workshop_ItemDetails_ItemDependencies,
  _ as Workshop_ItemDetails_NotEnoughRatings,
  _ as Workshop_ItemDetails_NumRatings,
  _ as Workshop_ItemDetails_NumRatings_Plural,
  _ as Workshop_ItemDetails_ReactionCount,
  _ as Workshop_ItemDetails_ReactionCount_Plural,
  _ as Workshop_ItemDetails_Report_TT,
  _ as Workshop_ItemDetails_RequiredDLC_Desc,
  _ as Workshop_ItemDetails_SaveCollectionToCollection,
  _ as Workshop_ItemDetails_ShowAllReactions,
  _ as Workshop_ItemDetails_Signin_TT,
  _ as Workshop_ItemDetails_Stats_CurrentFavorites,
  _ as Workshop_ItemDetails_Stats_CurrentSubscribers,
  _ as Workshop_ItemDetails_Stats_LifetimeFavorites,
  _ as Workshop_ItemDetails_Stats_LifetimePlaytimeSessions,
  _ as Workshop_ItemDetails_Stats_LifetimeSubscribers,
  _ as Workshop_ItemDetails_Stats_UniqueVisitors,
  _ as Workshop_ItemDetails_Subscribe,
  _ as Workshop_ItemDetails_Subscribe_TT,
  _ as Workshop_ItemDetails_Subscribed,
  _ as Workshop_ItemDetails_Tab_ChangeNotes,
  _ as Workshop_ItemDetails_Tab_Comments,
  _ as Workshop_ItemDetails_Tab_Description,
  _ as Workshop_ItemDetails_Tab_Discussions,
  _ as Workshop_ItemDetails_Tab_Stats,
  _ as Workshop_ItemDetails_Tab_Updates,
  _ as Workshop_ItemDetails_Tags_Title,
  _ as Workshop_ItemDetails_TimestampCreated,
  _ as Workshop_ItemDetails_TimestampUpdated,
  _ as Workshop_ItemDetails_TimestampWithTime,
  _ as Workshop_ItemDetails_Title,
  _ as Workshop_ItemDetails_Unfavorite,
  _ as Workshop_ItemDetails_Unsubscribe,
  _ as Workshop_ItemDetails_Unsubscribe_TT,
  _ as Workshop_ItemDetails_ViewDependentItems,
  _ as Workshop_ItemDetails_ViewDependentItems_TT,
  _ as Workshop_ItemTooltip_FriendsWhoFavorited,
  _ as Workshop_ItemTooltip_FriendsWhoFavorited_Plural,
  _ as Workshop_Item_QuickView,
  _ as Workshop_Item_QuickView_ExpandBtn,
  _ as Workshop_LearnMore,
  _ as Workshop_Menu_About,
  _ as Workshop_Menu_Browse,
  _ as Workshop_Menu_Discussions,
  _ as Workshop_Menu_Home,
  _ as Workshop_Menu_Search,
  _ as Workshop_Menu_YourItems,
  _ as Workshop_NumPerPage,
  _ as Workshop_NumResults,
  _ as Workshop_NumResults_Plural,
  _ as Workshop_OfficialContent,
  _ as Workshop_OwnedDLC_All_Filter,
  _ as Workshop_OwnedDLC_More_Filter,
  _ as Workshop_OwnedDLC_None_Filter,
  _ as Workshop_PagingControls,
  _ as Workshop_RequireApproval,
  _ as Workshop_RequiredDLC_ExcludeUnowned,
  _ as Workshop_RequiredDLC_Filter,
  _ as Workshop_RequiredDLC_Header,
  _ as Workshop_RequiredDLC_IncludeOwned,
  _ as Workshop_RequiredDLC_NameFilter,
  _ as Workshop_Saved_Queries,
  _ as Workshop_Saved_Queries_Delete_Btn,
  _ as Workshop_Saved_Queries_Delete_Desc,
  _ as Workshop_Saved_Queries_Delete_Title,
  _ as Workshop_Saved_Queries_Save_Btn,
  _ as Workshop_Saved_Queries_Save_Desc,
  _ as Workshop_Saved_Queries_Save_Desc_Long,
  _ as Workshop_Saved_Queries_Save_New,
  _ as Workshop_Saved_Queries_Save_Title,
  _ as Workshop_Saved_Queries_Update,
  _ as Workshop_SearchResults_Flag_Accepted,
  _ as Workshop_SearchResults_Flag_Incompatible,
  _ as Workshop_SearchResults_KVTag,
  _ as Workshop_SearchResults_SearchText,
  _ as Workshop_SearchResults_SearchText_DescriptionOnly,
  _ as Workshop_SearchResults_SearchText_TitleOnly,
  _ as Workshop_SearchResults_Tag,
  _ as Workshop_SearchTarget_All,
  _ as Workshop_SearchTarget_Description,
  _ as Workshop_SearchTarget_MenuTitle,
  _ as Workshop_SearchTarget_Title,
  _ as Workshop_Search_Help,
  _ as Workshop_Search_Help_Advanced,
  _ as Workshop_Search_Help_AdvancedExample1,
  _ as Workshop_Search_Help_AdvancedExample2,
  _ as Workshop_Search_Help_Example1,
  _ as Workshop_Search_Help_Example2,
  _ as Workshop_Search_Help_Example3,
  _ as Workshop_Search_Help_Example_Blue,
  _ as Workshop_Search_Help_Example_Green,
  _ as Workshop_Search_Help_Example_Red,
  _ as Workshop_Search_Help_Example_Room,
  _ as Workshop_SearchedForChild,
  _ as Workshop_SearchedForRequiredItem,
  _ as Workshop_Section_Collections,
  _ as Workshop_Section_Merchandise,
  _ as Workshop_Section_Mtx,
  _ as Workshop_Section_ReadyToUse,
  _ as Workshop_Section_Videos,
  _ as Workshop_ServiceProviderRevenueSharing_ViewSite,
  _ as Workshop_ServiceProviderRevenueSharing_ViewSteamProfile,
  _ as Workshop_ServiceProvider_Category_Communities,
  _ as Workshop_ServiceProvider_Category_Tools,
  _ as Workshop_ServiceProvider_Category_Users,
  _ as Workshop_SortBy,
  _ as Workshop_SpecialFilter_AcceptedForUse,
  _ as Workshop_SpecialFilter_CreatedByFollowed,
  _ as Workshop_SpecialFilter_CreatedByFriends,
  _ as Workshop_SpecialFilter_Desc,
  _ as Workshop_SpecialFilter_FavoritedByFriends,
  _ as Workshop_SpecialFilter_None,
  _ as Workshop_SpecialFilter_ParentCollections,
  _ as Workshop_SpecialFilter_ParentItems,
  _ as Workshop_SpecialFilter_Reported,
  _ as Workshop_StatusIcon_TT_Accepted,
  _ as Workshop_StatusIcon_TT_BlockedCreator,
  _ as Workshop_StatusIcon_TT_Favorited,
  _ as Workshop_StatusIcon_TT_Incompatible,
  _ as Workshop_StatusIcon_TT_Played,
  _ as Workshop_StatusIcon_TT_Reported,
  _ as Workshop_StatusIcon_TT_Subscribed,
  _ as Workshop_StatusIcon_TT_VotedDown,
  _ as Workshop_StatusIcon_TT_VotedUp,
  _ as Workshop_SubMenu_LegalAgreement,
  _ as Workshop_SubMenu_ViewYourRevenue,
  _ as Workshop_SubMenu_ViewYourRevenue_Desc,
  _ as Workshop_SubMenu_VotingQueue,
  _ as Workshop_SubMenu_YourCollections,
  _ as Workshop_SubMenu_YourFavorites,
  _ as Workshop_SubMenu_YourItems,
  _ as Workshop_SubMenu_YourPaymentInfo,
  _ as Workshop_SubMenu_YourPlayed,
  _ as Workshop_SubMenu_YourSubscriptions,
  _ as Workshop_SubMenu_YourVotingQueue,
  _ as Workshop_Tag_NoneSpecified,
  _ as default,
  _ as language,
};
