var _ = `Сообщения на форуме`,
  _ = `Общие обсуждения`,
  _ = `Публикации с жалобами`,
  _ = `Обсуждения в мастерской`,
  _ = `Обмен`,
  _ = `События и объявления`,
  _ = `Жалоб: 1`,
  _ = `Жалоб: %1$s`,
  _ = `Тем: 1`,
  _ = `Тем: %1$s`,
  _ = `%1$s. %2$s.`,
  _ = `%1$s. %2$s. Раздел: %3$s.`,
  _ = `Жалоб: 1`,
  _ = `Жалоб: %1$s`,
  _ = `Тем: 1`,
  _ = `Тем: %1$s`,
  _ = `Сообщество Steam`,
  _ = `Сообщество Steam :: Ошибка`,
  _ = `Ошибка`,
  _ = `Неизвестная ошибка`,
  _ = `Игры`,
  _ = `Сообщество Steam :: %1$s :: Игры`,
  _ = `Поиск — торговая площадка сообщества Steam`,
  _ = `%1$s — торговая площадка сообщества Steam`,
  _ = `Предмет — торговая площадка сообщества Steam`,
  _ = `Торговая площадка сообщества Steam`,
  _ = `Профиль не найден`,
  _ = `Не удалось загрузить список желаемого.`,
  _ = `За недавнее время вы отправили слишком много запросов. Повторите попытку позже.`,
  _ = `Загрузка`,
  _ = `ВЫПОЛНЕНО: %1$s%`,
  _ = `ПРИОСТАНОВЛЕНО — ВЫПОЛНЕНО: %1$s%`,
  _ = `ЗАГРУЖЕНО: %1$s ИЗ %2$s`,
  _ = `ДОСТИЖЕНИЯ`,
  _ = `Осталось примерно %1$s`,
  _ = `%1$s/%2$s`,
  _ = `УДАЛЕНИЕ`,
  _ = `ОБНОВИТЬ`,
  _ = `УДАЛИТЬ`,
  _ = `ЗАГРУЗИТЬ`,
  _ = `ПРИОСТАНОВИТЬ`,
  _ = `ВОЗОБНОВИТЬ`,
  _ = `УДАЛЕНИЕ`,
  _ = `ОТМЕНА`,
  _ = `Показать мои настройки приватности для этого контента`,
  _ = `Найти игру`,
  _ = `Игры, которые есть у вас обоих`,
  _ = `время в игре`,
  _ = `название`,
  _ = `процент достижений`,
  _ = `ОБЩЕЕ ВРЕМЯ В ИГРЕ`,
  _ = `ПОСЛЕДНИЙ ЗАПУСК`,
  _ = `ЗА ПОСЛЕДНИЕ ДВЕ НЕДЕЛИ`,
  _ = `Об игре / ссылки`,
  _ = `Удалённая загрузка`,
  _ = `УДАЛЁННАЯ ЗАГРУЗКА НА: %1$s`,
  _ = `СТАТУС УДАЛЁННОЙ ЗАГРУЗКИ: %1$s`,
  _ = `Не удалось получить доступ к вашему ПК`,
  _ = `Чтобы удалённо начать загрузку через клиент Steam, ваш компьютер должен находиться в активном режиме и быть подключённым к сети, а вы должны войти в свой аккаунт`,
  _ = `Прочитайте ответы на частые вопросы`,
  _ = `%1$s. %2$s.`,
  _ = `Подробности`,
  _ = `УДАЛЁННАЯ ЗАГРУЗКА НЕДОСТУПНА`,
  _ = `Вы точно хотите удалить %1$s? Игра останется в библиотеке, но, чтобы поиграть в неё в будущем, её придётся загрузить заново.`,
  _ = `%1$s | «%2$s»`,
  _ = `Недавно запущенные %1$s`,
  _ = `Все игры %1$s`,
  _ = `Идеальные игры %1$s`,
  _ = `Обзоры %1$s`,
  _ = `Подписки %1$s`,
  _ = `Список желаемого`,
  _ = `Получены все достижения`,
  _ = `Здесь вы найдёте свои идеальные игры (те, в которых вы получили все достижения).`,
  _ = `Это достижение есть у %1$s% игроков`,
  _ = `Страница в магазине`,
  _ = `Обсуждения`,
  _ = `Группы`,
  _ = `Официальный сайт`,
  _ = `Новости`,
  _ = `Мои достижения`,
  _ = `%1$s: достижения`,
  _ = `%1$s: статистика`,
  _ = `%1$s: личная статистика`,
  _ = `Мои таблицы лидеров`,
  _ = `%1$s: таблицы лидеров`,
  _ = `Глобальные достижения`,
  _ = `Глобальные таблицы лидеров`,
  _ = `Игровая статистика`,
  _ = `Игровой контент`,
  _ = `Моя игровая статистика`,
  _ = `Мой игровой контент`,
  _ = `Ссылки на игры`,
  _ = `Мои скриншоты %1$s`,
  _ = `%1$s: скриншоты %2$s`,
  _ = `Мои друзья, игравшие в это %1$s`,
  _ = `Мои карточки %1$s`,
  _ = `Мой обзор`,
  _ = `Обзор от %1$s`,
  _ = `Центр сообщества`,
  _ = `Мои заметки`,
  _ = `%1$s ч.`,
  _ = `%1$s мин.`,
  _ = `Сделать приватной`,
  _ = `Показывать всем`,
  _ = `Сделать игру приватной и не показывать её друзьям`,
  _ = `© Valve Corporation. Все права сохранены. Все торговые марки являются собственностью соответствующих владельцев в США и других странах.`,
  _ = `Часть географических сведений на этом сайте предоставлена %1$s.`,
  _ = `Политика конфиденциальности`,
  _ = `Правовая информация`,
  _ = `Соглашение подписчика Steam`,
  _ = `Возврат средств`,
  _ = `Файлы cookie`,
  _ = `Доступность`,
  _ = `Текущие блокировки`,
  _ = `Сообщения в сообществе`,
  _ = `Жалобы на контент`,
  _ = `Прошедшее модерацию`,
  _ = `Вы сообщили о том, что данный контент нарушает правила Steam.`,
  _ = `Размещённый вами контент в Steam, который прошёл модерацию.`,
  _ = `Обновлено: %1$s`,
  _ = `Скачать`,
  _ = `Публичные комментарии (%1$s)`,
  _ = `Комментарии разработчика (%1$s)`,
  _ = `Это закрытый раздел. Он доступен только авторам этой работы и разработчикам игры.`,
  _ = `Примечание: переписка с разработчиками игры (например, Valve) не гарантирует, что ваша работа будет принята.`,
  _ = `Размер`,
  _ = `Просмотреть все скриншоты`,
  _ = `Посмотреть все иллюстрации`,
  _ = `Просмотреть все видео`,
  _ = `Заголовок`,
  _ = `Изменить заголовок`,
  _ = `Добавить метку спойлера`,
  _ = `Убрать метку спойлера`,
  _ = `Метка спойлера поможет вашим друзьям и сообществу понять, что в вашем контенте есть моменты, раскрывающие важные детали игры — спойлеры. Игроки смогут избежать их, если захотят.`,
  _ = `(Метки спойлеров снимаются через четыре недели.)`,
  _ = `Пользователи на этом скриншоте:`,
  _ = `Работы из мастерской на скриншоте: `,
  _ = `Удалить себя из отметок к этому скриншоту`,
  _ = `Местоположение`,
  _ = `Метки:`,
  _ = `Загрузка руководства`,
  _ = `Подпишитесь, чтобы использовать это руководство в %1$s`,
  _ = `Оглавление руководства`,
  _ = `Главная`,
  _ = `Комментарии`,
  _ = `Изменить`,
  _ = `{ССЫЛКА УДАЛЕНА}`,
  _ = `Эта ссылка удалена нашими фильтрами. Как правило, это делается для защиты от фишинга и вредоносных программ.`,
  _ = `Содержание руководства`,
  _ = `Определите структуру руководства и озаглавьте каждый его раздел. Порядок разделов можно менять, перетаскивая их.`,
  _ = `Этот раздел необходим, чтобы опубликовать руководство.`,
  _ = `Создать оглавление`,
  _ = `Добавить раздел`,
  _ = `(новый раздел, пока без названия)`,
  _ = `Изменить раздел`,
  _ = `Удалить раздел`,
  _ = `Вы точно хотите удалить этот раздел? Данное действие необратимо.`,
  _ = `Изображения`,
  _ = `Выберите и загрузите изображения, которые вы бы хотели использовать в руководстве. Загруженные изображения будут доступны для выбора во время редактирования отдельных его разделов.`,
  _ = `Загрузите изображения для своего руководства`,
  _ = `Добавить авторов`,
  _ = `Здесь вы можете добавить друзей в соавторы, предоставив им возможность редактировать руководство.`,
  _ = `Добавить друзей как авторов`,
  _ = `Добавить автора`,
  _ = `Предпросмотр`,
  _ = `Изменить раздел руководства`,
  _ = `Название раздела`,
  _ = `Содержимое раздела`,
  _ = `Редактирование`,
  _ = `Предпросмотр`,
  _ = `Сравнение`,
  _ = `Все изменения текста с момента последнего сохранения будут отображаться так:`,
  _ = `Добавленный текст показан так`,
  _ = `Удалённый текст показан так`,
  _ = `В этом разделе есть несохранённые изменения.`,
  _ = `В этом разделе есть несохранённые изменения. Вы точно хотите их отменить?`,
  _ = `Последнее сохранение`,
  _ = `Сохранить`,
  _ = `Отменить`,
  _ = `Скриншоты`,
  _ = `Видео`,
  _ = `Нажмите на изображение ниже, чтобы добавить его в руководство`,
  _ = `Нажмите на скриншот ниже, чтобы добавить его в руководство`,
  _ = `Нажмите на видео ниже, чтобы добавить его в руководство`,
  _ = `Опции вставки изображения`,
  _ = `Размер`,
  _ = `в полширины`,
  _ = `во всю ширину`,
  _ = `оригинальный размер`,
  _ = `Выравнивание`,
  _ = `по левому краю`,
  _ = `по правому краю`,
  _ = `по центру`,
  _ = `По левому краю`,
  _ = `По правому краю`,
  _ = `Во всю ширину`,
  _ = `Вставить`,
  _ = `Вставить видео с YouTube™`,
  _ = `Введите ссылку на видео с YouTube™`,
  _ = `Цитата`,
  _ = `Текст под спойлером`,
  _ = `Введите название`,
  _ = `Открыть руководство`,
  _ = ``,
  _ = `Работы в мастерской:`,
  _ = `и ещё %1$s`,
  _ = `Подробности и комментарии`,
  _ = `Просмотреть подробности и комментарии (%1$s)`,
  _ = `Скриншоты`,
  _ = `Иллюстрации`,
  _ = `Видео`,
  _ = `Работы в мастерской`,
  _ = `Атрибутика`,
  _ = `Коллекции`,
  _ = `Руководства`,
  _ = `Работы в мастерской`,
  _ = `Коллекции в мастерской`,
  _ = `Руководства`,
  _ = `Добавления в избранное`,
  _ = `Подписки на работы`,
  _ = `Сыграно`,
  _ = `Сортировать по игре`,
  _ = `Все игры`,
  _ = `Выбрать игру`,
  _ = `Работы`,
  _ = `В избранном`,
  _ = `Подписки на работы`,
  _ = `По дате создания`,
  _ = `По алфавиту`,
  _ = `По дате изменения`,
  _ = `По дате подписки`,
  _ = `По дате добавления`,
  _ = `Показать продукты со всеми выбранными метками:`,
  _ = `от`,
  _ = `Обновления %1$s–%2$s из %3$s`,
  _ = `Не найдено файлов, удовлетворяющих критериям запроса %1$s.`,
  _ = `Результаты %1$s–%2$s из %3$s`,
  _ = `Последнее обновление %1$s`,
  _ = `Добавлена %1$s`,
  _ = `Эта работа удалена из избранного:`,
  _ = `В подписках с %1$s`,
  _ = `Вы отписались от:`,
  _ = `Ура! Вашу работу из мастерской Steam приняли для игры!`,
  _ = `Прежде чем вы убежите праздновать, сначала введите свои <a href="%1$s">финансовые данные</a>, чтобы мы знали, кому платить!`,
  _ = `Возникла проблема при проверке ваших <a href="%1$s">финансовых данных</a>. Убедитесь в их правильности и повторите попытку.`,
  _ = `Вас отметили в качестве одного из создателей следующих работ`,
  _ = `Проверьте и подтвердите авторство для следующих работ:`,
  _ = `Процент:`,
  _ = `Ваша мастерская`,
  _ = `Подписавшись на этого пользователя, вы сможете увидеть его новые руководства, коллекции и работы в мастерской.`,
  _ = `Пользователи Steam, подписавшиеся на вас, увидят ваши новые руководства, коллекции и работы в мастерской.`,
  _ = `Подписчики`,
  _ = `Подписчики`,
  _ = `Подписаться на %1$s`,
  _ = `Вы подписаны на %1$s`,
  _ = `Отписаться от %1$s`,
  _ = `Просмотреть доход`,
  _ = `С продаж ваших работ в мастерской`,
  _ = `Ввести или обновить свои финансовые данные`,
  _ = `Просмотреть соглашение подписчика Steam`,
  _ = `Отписаться от всего`,
  _ = `Отписаться от всего?`,
  _ = `Вы уверены, что хотите удалить все подписки?<br><br>Это действие нельзя отменить!`,
  _ = `Вы уверены, что хотите удалить все подписки на %1$s?<br><br>Это действие нельзя отменить!`,
  _ = `Сохранить в коллекции`,
  _ = `Сохранить подписки в коллекции`,
  _ = `Вы хотите сохранить свои подписки в новой или существующей коллекции?`,
  _ = `В новой коллекции`,
  _ = `Введите название коллекции:`,
  _ = `В существующей коллекции`,
  _ = `Выберите коллекцию, которую хотите заменить: `,
  _ = `Сейчас у вас нет коллекций. Хотите создать новую?`,
  _ = `Метки администратора`,
  _ = `Руководства Steam`,
  _ = `Интегрированные руководства`,
  _ = `Сборки героя`,
  _ = `Особым образом интегрированные руководства, обучающие во время игры`,
  _ = `Руководства, которые были специально интегрированы с %1$s`,
  _ = `Популярные категории`,
  _ = `Интегрированные руководства`,
  _ = `У вас в избранном`,
  _ = `Популярные руководства Steam`,
  _ = `Пользовательские руководства, советы и прохождения`,
  _ = `Просмотреть все (%1$s)`,
  _ = `Руководств: %1$s`,
  _ = `Руководств: %1$s`,
  _ = `Руководства, написанные вами`,
  _ = `О руководствах`,
  _ = `Нажмите здесь, чтобы узнать больше о руководствах Steam`,
  _ = `Просмотреть:`,
  _ = `Главная`,
  _ = `Написать руководство`,
  _ = `Если вы хотите написать руководство, то сначала приобретите %1$s.`,
  _ = `Станьте первым, кто напишет руководство по этой игре!`,
  _ = `Продемонстрируйте своё мастерство или просто помогите другим с прохождением.`,
  _ = `Создайте руководство по прохождению, поделитесь секретами игры или предложите оптимальные стратегии для конкретных уровней.`,
  _ = `Читайте и оценивайте руководства пользователей по этой игре — либо напишите собственное и поделитесь советами с сообществом.`,
  _ = `Написать своё`,
  _ = `Скриншоты`,
  _ = `Иллюстрации`,
  _ = `Видео`,
  _ = `Показаны %1$s–%2$s из %3$s`,
  _ = `Наверх`,
  _ = `Отображаются`,
  _ = `Стеной`,
  _ = `Сеткой`,
  _ = `Самые популярные`,
  _ = `Сначала новые`,
  _ = `Сначала старые`,
  _ = `Все ваши скриншоты`,
  _ = `Видимые всем`,
  _ = `Видимые только друзьям`,
  _ = `Видимые только мне`,
  _ = `С доступом по ссылке`,
  _ = `Все ваши иллюстрации`,
  _ = `Видимые всем`,
  _ = `Видимые только друзьям`,
  _ = `Видимые только мне`,
  _ = `С доступом по ссылке`,
  _ = `Все ваши видео`,
  _ = `Видимые всем`,
  _ = `Видимые только друзьям`,
  _ = `Видимые только мне`,
  _ = `С доступом по ссылке`,
  _ = `Управление скриншотами`,
  _ = `Управление иллюстрациями`,
  _ = `Управление видео`,
  _ = `Выберите скриншоты, к которым хотите применить действие.`,
  _ = `Ниже выберите иллюстрации, к которым хотите применить действие.`,
  _ = `Выберите видео, к которым хотите применить действие.`,
  _ = `Отмена`,
  _ = `Добавить видео с YouTube`,
  _ = `Привязать аккаунт YouTube`,
  _ = `Отвязать аккаунт YouTube`,
  _ = `Отвязать`,
  _ = `Вы уверены, что хотите отвязать свой аккаунт YouTube?`,
  _ = `Как Steam использует мои данные с YouTube?`,
  _ = `Привязка аккаунта YouTube к Steam осуществляется с помощью сервисов API YouTube. Используя YouTube и привязывая свой аккаунт YouTube к профилю Steam, вы соглашаетесь с %1$s и %2$s.`,
  _ = `Steam использует cервисы API YouTube для аутентификации аккаунтов YouTube и доступа к списку размещённых вами видео. Если вы привяжете свой аккаунт YouTube к Steam, в браузере или клиенте Steam будет создан файл cookie с информацией для аутентификации вашего аккаунта на YouTube. Срок действия этого файла cookie истекает через 30 дней. Доступ к списку ваших видео на YouTube нужен исключительно для показа этого списка вам в Steam.`,
  _ = `Когда вы публикуете в Steam видео с YouTube, в Steam сохраняется только необходимая для его показа информация, включая идентификатор видео и номер аккаунта YouTube. Эти данные используются исключительно для отображения видео и модерации контента в Steam.`,
  _ = `Вы можете отозвать у Steam доступ к вашим %1$s на %2$s.`,
  _ = `условиями использования YouTube`,
  _ = `политикой конфиденциальности Google`,
  _ = `авторизованным данным`,
  _ = `странице настроек безопасности Google`,
  _ = `Ваши видео. Теперь в Steam.`,
  _ = `Поделитесь лучшими игровыми моментами со своими друзьями. Публикуйте потрясающие мгновения, проницательные рецензии, полезные советы и другие великолепные вещи, которые вы создали, вдохновившись игрой.`,
  _ = `1. Привяжите свой аккаунт YouTube к профилю Steam.`,
  _ = `2. Выберите видео, которое хотите добавить в свой профиль.`,
  _ = `3. Покажите его своим друзьям в Steam, они будут восхищены.`,
  _ = `Получить доступ к моим видео на YouTube`,
  _ = `Сейчас с вашим профилем связан аккаунт Youtube %1$s.`,
  _ = `Отвяжите этот аккаунт, чтобы связать профиль с другим.`,
  _ = `Отвязать аккаунт`,
  _ = `Продолжить использование аккаунта`,
  _ = `Ваш аккаунт YouTube привязан к профилю Steam`,
  _ = `Добавлено 1 видео`,
  _ = `Добавлены видео (%1$s)`,
  _ = `В вашей коллекции YouTube не найдено ни одного видео.`,
  _ = `Вы можете добавлять только видимые всем и доступные для размещения на сторонних ресурсах видео с YouTube, которые отображаются в списке результатов поиска по вашему имени пользователя. Если вы только что сделали видео публичным, то может пройти некоторое время, прежде чем YouTube обновит индексы в результатах поиска.`,
  _ = `На данный момент к вашему профилю Steam привязан аккаунт YouTube %1$s.`,
  _ = `Нажмите здесь, чтобы изменить связанные с профилем аккаунты YouTube`,
  _ = `сменить аккаунт`,
  _ = `1. Выберите одно или несколько видео, которые хотите добавить.`,
  _ = `Доступно 1 видео (аккаунт: %1$s)`,
  _ = `Показаны последние доступные видео (%1$s) для аккаунта: %2$s`,
  _ = `2. Укажите, из какой игры это видео.`,
  _ = `После того как вы выберете видео слева. (Необязательно)`,
  _ = `- нет / другое (выберите из списка) -`,
  _ = `Другие / не из списка`,
  _ = `3. Добавьте его в свой профиль.`,
  _ = `Добавить видео`,
  _ = `Примечание: из аккаунта YouTube можно добавлять только видимые всем и доступные для размещения на сторонних ресурсах видео. Если вы только что добавили видео к вашему аккаунту YouTube и не видите его в списке, попробуйте его обновить, нажав на кнопку ниже.`,
  _ = `Обновить список видео с YouTube`,
  _ = `4. Последний шаг.`,
  _ = `Нажмите «Готово», чтобы увидеть видео на странице вашего профиля.`,
  _ = `Готово`,
  _ = `Ошибка доступа к вашим видеоматериалам. Повторите попытку.`,
  _ = `Загрузить иллюстрации`,
  _ = `Загрузить скриншоты...`,
  _ = `Показывать всем`,
  _ = `Показывать только друзьям`,
  _ = `Не показывать никому`,
  _ = `Сделать доступ по ссылке`,
  _ = `Удалить`,
  _ = `Выбрать все`,
  _ = `Готово`,
  _ = `Удалить эти скриншоты?`,
  _ = `Обновить видимость`,
  _ = `Это действие приведёт к удалению %1$s из Steam Cloud. Продолжить?`,
  _ = `Видимость %1$s сменится на «%2$s». Продолжить?`,
  _ = `Продолжить`,
  _ = `Отмена`,
  _ = `Ой!`,
  _ = `Вы ничего не выбрали.`,
  _ = `Используйте галочку в углу каждой миниатюры, чтобы отметить скриншоты для удаления.`,
  _ = `OK`,
  _ = `Не удалось изменить настройки видимости`,
  _ = `Один или более скриншотов, которые вы пытались сделать доступными для всех или только для друзей, не могут быть обновлены. Скриншоты, недоступные для просмотра другим игрокам в сообществе Steam, могут быть просмотрены только вами.`,
  _ = `Возможны спойлеры.`,
  _ = `Наведите курсор, чтобы показать изображение.`,
  _ = `Не удалось найти подходящие скриншоты.`,
  _ = `У пользователя %1$s нет скриншотов, которые видны вам.`,
  _ = `Вы не добавили в избранное ни одного скриншота.`,
  _ = `У пользователя %1$s нет избранных скриншотов, которые видны вам.`,
  _ = `В данный момент у вас нет иллюстраций, хранящихся в Steam Cloud. Чтобы загрузить иллюстрацию, откройте вкладку «Иллюстрации» в центре сообщества игры и найдите кнопку «Загрузить иллюстрацию» справа вверху. Или нажмите кнопку «Загрузить иллюстрацию» ниже.`,
  _ = `У пользователя %1$s нет иллюстраций, которые видны вам.`,
  _ = `У вас нет избранных иллюстраций.`,
  _ = `У пользователя %1$s нет избранных иллюстраций, которые видны вам.`,
  _ = `Не удалось найти подходящие видео.`,
  _ = `У пользователя %1$s нет видео, которые видны вам.`,
  _ = `Вы не добавили в избранное ни одного видео.`,
  _ = `У пользователя %1$s нет избранных видео, которые видны вам.`,
  _ = `У вас нет скриншотов с выбранными настройками видимости.`,
  _ = `В Steam стало ещё легче делать скриншоты любимых игр и делиться ими.`,
  _ = `Нажмите горячую клавишу (по умолчанию — F12), находясь в любой игре, поддерживающей оверлей Steam, чтобы сделать скриншот. Затем опубликуйте их в вашем профиле сообщества Steam, на странице в Facebook, в профиле X («Твиттера») или на Reddit, чтобы поделиться ими со своими друзьями.`,
  _ = `С 1 Гбайт личного пространства в Steam Cloud вы можете загружать тысячи скриншотов, чтобы показать лучшие моменты игры всем своим друзьям. Или скройте их, если не хотите никому показывать.`,
  _ = `Автор: %1$s`,
  _ = `В избранном у: %1$s`,
  _ = {
    Moderation_SubjectTypeName_ForumPost: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    moderation_claim_report_count: _,
    moderation_claim_report_count_Plural: _,
    moderation_claim_subject_count: _,
    moderation_claim_subject_count_Plural: _,
    moderation_claim_n_reports_on_m_subjects: _,
    moderation_forumpost_summary: _,
    moderation_forumpost_summary_reports_fragment: _,
    moderation_forumpost_summary_reports_fragment_Plural: _,
    moderation_forumpost_summary_subjects_fragment: _,
    moderation_forumpost_summary_subjects_fragment_Plural: _,
    community_title: _,
    community_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    profile_games_list: _,
    profile_games_list_title: _,
    Market_Search_Title: _,
    Market_Item_Title: _,
    Market_Item_GenericTitle: _,
    Market_GenericTitle: _,
    profile_error_profilenotfound: _,
    profile_games_list_error_loadfailed: _,
    Error_RateLimited: _,
    Loading: _,
    GamesList_Header_Downloading: _,
    GamesList_Header_Paused: _,
    GamesList_Header_DownloadBytes: _,
    GamesList_Header_Achievements: _,
    GamesList_TimeRemaining: _,
    GamesList_Achievement_Fraction: _,
    GamesList_Uninstalling: _,
    GamesList_Button_UpdateRequired: _,
    GamesList_Button_Uninstall: _,
    GamesList_Button_Download: _,
    GamesList_Button_Pause: _,
    GamesList_Button_Resume: _,
    GamesList_Button_Uninstalling: _,
    GamesList_Button_Cancel: _,
    GamesList_PrivacySettings_Tooltip: _,
    GamesList_Filter_Placeholder: _,
    GamesList_Filter_BothOwned: _,
    GamesList_Sort_HoursPlayed: _,
    GamesList_Sort_Name: _,
    GamesList_Sort_AchievementCompletion: _,
    GamesList_Header_TotalPlayed: _,
    GamesList_Header_LastPlayed: _,
    GamesList_Header_TwoWeeks: _,
    GamesList_MenuLabel_GameInfo: _,
    GamesList_MenuLabel_RemoteDownload: _,
    GamesList_Header_RemoteDownload: _,
    GamesList_Header_RemoteDownloadStatus: _,
    GamesList_RemoteDownload_NoConnection: _,
    GamesList_RemoteDownload_Help: _,
    GamesList_RemoteDownload_ReadTheFAQ: _,
    GamesList_RemoteDownload_Info: _,
    GamesList_RemoteDownload_LearnMore: _,
    GamesList_RemoteDownload_NoRemoteControl: _,
    GamesList_RemoteDownload_UninstallConfirm: _,
    GamesList_Client_Indicator: _,
    GamesList_Tab_RecentlyPlayed: _,
    GamesList_Tab_AllGames: _,
    GamesList_Tab_PerfectGames: _,
    GamesList_Tab_Reviews: _,
    GamesList_Tab_Followed: _,
    GamesList_Tab_Wishlist: _,
    Perfect_Game_Description: _,
    GamesList_PerfectGames_Description: _,
    GamesList_Achievement_Unlock_Percentage: _,
    Community_StorePage: _,
    Community_Forums: _,
    Community_Groups: _,
    Community_OfficialWebsite: _,
    Community_News: _,
    Community_UsersAchievementsFirstPerson: _,
    Community_UsersAchievements: _,
    Community_UsersStats: _,
    Community_GamePersonalData: _,
    Community_UsersLeaderboardsFirstPerson: _,
    Community_UsersLeaderboards: _,
    Community_GlobalAchievements: _,
    Community_GlobalLeaderboards: _,
    Community_GameStats: _,
    Community_GameContent: _,
    Community_GameStatsFirstPerson: _,
    Community_GameContentFirstPerson: _,
    Community_GameLinks: _,
    Community_ScreenshotsMenuItemFirstPerson: _,
    Community_ScreenshotsMenuItemThirdPerson: _,
    Community_FriendsWhoPlayMenuItemFirstPerson: _,
    Community_TradingCardsMenuItemFirstPerson: _,
    Community_ReviewMenuItemFirstPerson: _,
    Community_ReviewMenuItemThirdPerson: _,
    Community_GameHubMenuItem: _,
    Community_GameNotesFirstPerson: _,
    Playtime_Hours: _,
    Playtime_Minutes: _,
    AppPrivacy_MarkAsPrivate: _,
    AppPrivacy_UnmarkAsPrivate: _,
    AppPrivacy_Explanation: _,
    footer_legal_notice: _,
    footer_geodata_notice: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_accessibility: _,
    profiletabs_currentbans: _,
    profiletabs_communitymessages: _,
    profiletabs_reportedcontent: _,
    profiletabs_moderatedcontent: _,
    reportedcontent_description: _,
    moderatedcontent_description: _,
    reportedcontent_lastupdated: _,
    SharedFiles_ItemDownload: _,
    SharedFiles_PublicComments: _,
    SharedFiles_DeveloperComments: _,
    Workshop_DeveloperThreadDesc: _,
    Workshop_DeveloperThreadDisclaimerText: _,
    Workshop_ImageSize: _,
    SharedFiles_Media_ViewAppScreenshots: _,
    SharedFiles_Media_ViewAppFanArt: _,
    SharedFiles_Media_ViewAppVideos: _,
    SharedFiles_ItemEditText_Text_Caption: _,
    SharedFiles_OwnerControl_EditCaption: _,
    SharedFiles_AddSpoilerTag: _,
    SharedFiles_RemoveSpoilerTag: _,
    SharedFiles_SpoilerTagInstructions: _,
    SharedFiles_SpoilerTagsExpire: _,
    SharedFiles_Stats_TaggedUsers: _,
    SharedFiles_Stats_TaggedWorkshopItems: _,
    SharedFiles_RemoveSelfTag_Tooltip: _,
    Screenshots_Location: _,
    SharedFiles_Tags: _,
    SharedFiles_WaitingForIntegratedGuide: _,
    Workshop_Subscribe_IntegratedGuide: _,
    SharedFiles_Guide_Index: _,
    SharedFiles_Guide_Overview: _,
    SharedFiles_Guide_Comments: _,
    SharedFiles_Item_Edit_Link: _,
    Community_RemoveLink_BeWary: _,
    Community_RemoveLink_Tooltip: _,
    SharedFiles_ManageGuide_Contents: _,
    SharedFiles_ManageGuide_Contents_Desc: _,
    SharedFiles_ManageGuide_Required: _,
    SharedFiles_ManageGuide_NoSubSections: _,
    SharedFiles_ManageGuide_AddSection: _,
    SharedFiles_ManageGuide_NoSectionTitle: _,
    SharedFiles_ManageGuide_EditThisSection: _,
    SharedFiles_ManageGuide_DeleteThisSection: _,
    SharedFiles_ManageGuide_RemoveSectionConfirm: _,
    SharedFiles_ManageGuide_Images: _,
    SharedFiles_ManageGuide_Images_Desc: _,
    SharedFiles_ManageGuide_NoPreviewImages: _,
    SharedFiles_ManageGuide_Contributors: _,
    SharedFiles_ManageGuide_Contributors_Desc: _,
    SharedFiles_ManageGuide_NoContributors: _,
    SharedFiles_ManageGuide_AddContributor: _,
    SharedFiles_ManageGuide_Preview: _,
    SharedFiles_ManageGuide_EditSubSection: _,
    SharedFiles_ManageGuide_SubSectionTitle: _,
    SharedFiles_ManageGuide_SubSectionContents: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Edit: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Preview: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Changes: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Desc: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Insert: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Delete: _,
    SharedFiles_ManageGuide_SubSectionContentChanged: _,
    SharedFiles_ManageGuide_SubSectionContentChanged_CancelConfirm: _,
    SharedFiles_ManageGuide_SubSectionContentSaved: _,
    SharedFiles_ManageGuide_Save: _,
    SharedFiles_ManageGuide_Cancel: _,
    SharedFiles_ManageGuide_Screenshots: _,
    SharedFiles_ManageGuide_Videos: _,
    SharedFiles_ManageGuide_SubImages: _,
    SharedFiles_ManageGuide_SubScreenshots: _,
    SharedFiles_ManageGuide_SubVideos: _,
    SharedFiles_ManageGuide_ImageInsertionOptions: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_Size: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeThumb: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeFull: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeOriginal: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_Layout: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutLeft: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutRight: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutInline: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Left: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Right: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Full: _,
    SharedFiles_ManageGuide_InsertImage: _,
    SharedFiles_ManageGuide_InsertYouTubeVideo: _,
    SharedFiles_ManageGuide_PromptYouTubeUrl: _,
    Discussions_FormattingHelp_Quote: _,
    Discussions_FormattingHelp_Spoiler: _,
    SharedFiles_ItemEditText_ErrorNoTitle: _,
    SharedFiles_OwnerControl_BackGuide: _,
    empty_no_comma_following: ``,
    SharedFiles_WorkshopItemsTagged: _,
    SharedFiles_And_N_More: _,
    Workshop_ItemModalViewDetails: _,
    Workshop_ItemModalViewCountDetails: _,
    Profile_Screenshots: _,
    Profile_Images: _,
    Profile_Videos: _,
    Profile_Workshop_Items: _,
    SharedFiles_Tab_Merchandise: _,
    Profile_Collections: _,
    Profile_Guides: _,
    SharedFiles_SharedFiles_Items: _,
    SharedFiles_SharedFiles_Collections: _,
    SharedFiles_SharedFiles_Guides: _,
    SharedFiles_Favorites: _,
    SharedFiles_Subscriptions: _,
    SharedFiles_Browse_MyFiles_Played: _,
    SharedFiles_FilterByGame: _,
    Profile_SharedFiles_AllGames: _,
    Profile_SharedFiles_SelectAGame: _,
    SharedFiles_Browse_MyFiles_Items: _,
    SharedFiles_Browse_MyFiles_Favorites: _,
    SharedFiles_Browse_MyFiles_Subscriptions: _,
    SharedFiles_Browse_MyFiles_Sort_CreationOrder: _,
    SharedFiles_Browse_MyFiles_Sort_Alpha: _,
    SharedFiles_Browse_MyFiles_Sort_LastUpdated: _,
    SharedFiles_Browse_MyFiles_Sort_Subscribed: _,
    SharedFiles_Browse_MyFiles_Sort_Favorited: _,
    SharedFiles_TagsSearch: _,
    SharedFiles_ByAuthor: _,
    Workshop_BrowsePaging: _,
    Workshop_NoItems: _,
    SharedFiles_UserList_BrowsePaging: _,
    SharedFiles_UserList_LastUpdated: _,
    SharedFiles_Favorites_Subscribed: _,
    SharedFiles_Favorites_NowUnsubscribed: _,
    SharedFiles_Subscription_Subscribed: _,
    SharedFiles_Subscription_NowUnsubscribed: _,
    Workshop_HasLinkedItems: _,
    Workshop_PaymentInfo_NotCreated: _,
    Workshop_PaymentInfo_Rejected: _,
    Workshop_SplitsAcceptTheseDesc1: _,
    Workshop_SplitsAcceptTheseDesc2: _,
    Workshop_SplitsPercentage: _,
    Profile_YourWorkshop: _,
    CommunityFollower_Description: _,
    CommunityFollower_Description_Yours: _,
    CommunityFollower_One_Follower: _,
    CommunityFollower_NumFollowers: _,
    CommunityFollower_FollowUser: _,
    CommunityFollower_FollowingUser: _,
    CommunityFollower_UnfollowUser: _,
    Workshop_ViewYourRevenue: _,
    Workshop_ViewYourRevenue_desc: _,
    Workshop_Link_PaymentInfo: _,
    Workshop_Link_LegalAgreement: _,
    SharedFiles_UnsubscribeAll_Btn: _,
    SharedFiles_UnsubscribeAll_Confirm_Title: _,
    SharedFiles_UnsubscribeAll_Confirm_Desc: _,
    SharedFiles_UnsubscribeAll_Confirm_App_Desc: _,
    SharedFiles_SaveSubscribedToCollection_Btn: _,
    SharedFiles_SaveSubscribedToCollection_Title: _,
    SharedFiles_SaveSubscribedToCollection_Desc: _,
    SharedFiles_SaveSubscribedToCollection_New: _,
    SharedFiles_SaveSubscribedToCollection_NewDesc: _,
    SharedFiles_SaveSubscribedToCollection_Existing: _,
    SharedFiles_SaveSubscribedToCollection_ExistingDesc: _,
    SharedFiles_SaveSubscribedToCollection_NoExistingCollections: _,
    SharedFiles_AdminTags: _,
    SharedFiles_SearchedForFileType_WebGuide: _,
    SharedFiles_SearchedForFileType_IntegratedGuide: _,
    SharedFiles_Dota2_IntegratedGuide: _,
    SharedFiles_Dota2_IntegratedGuide_Desc: _,
    AppHub_Guides_IntegratedGuides_Desc: _,
    AppHub_Guides_PopularCategories: _,
    AppHub_Guides_IntegratedGuides: _,
    AppHub_Guides_YourFavorites: _,
    AppHub_Guides_MostPopularThisWeek: _,
    AppHub_Guides_MostPopularThisWeek_Desc: _,
    AppHub_Guides_ViewAll: _,
    AppHub_Guides_NumGuides_Singular: _,
    AppHub_Guides_NumGuides_Plural: _,
    AppHub_Guides_GuidesYouHaveMade: _,
    AppHub_Guides_MoreInfo_Title: _,
    AppHub_Guides_MoreInfo_button: _,
    Workshop_BrowseBy: _,
    SharedFiles_Browse_GuideHome: _,
    SharedFiles_CreateGuide: _,
    SharedFiles_MustOwnAppToCreateGuide: _,
    SharedFiles_NoGuides_Title: _,
    SharedFiles_NoGuides_Desc1: _,
    SharedFiles_NoGuides_Desc2: _,
    SharedFiles_BrowseGuide_subtitle_nolink: _,
    SharedFiles_BrowseGuide_createNewBtnLabel: _,
    Community_Screenshots: _,
    Community_Images: _,
    Community_Videos: _,
    Paging_ShowingXtoYofZ: _,
    AppHubHome_BackToTop: _,
    Screenshots_Viewing: _,
    Profile_SharedFiles_ImageWallView: _,
    Profile_SharedFiles_GridView: _,
    Profile_SharedFiles_MostPopular: _,
    Profile_SharedFiles_NewestFirst: _,
    Profile_SharedFiles_OldestFirst: _,
    Screenshots_AllYourScreenshots: _,
    Screenshots_YourPublicScreenshots: _,
    Screenshots_YourFriendsOnlyScreenshots: _,
    Screenshots_YourPrivateScreenshots: _,
    Screenshots_YourUnlistedScreenshots: _,
    Images_AllYourImages: _,
    Images_YourPublicImages: _,
    Images_YourFriendsOnlyImages: _,
    Images_YourPrivateImages: _,
    Images_YourUnlistedImages: _,
    Videos_AllYourVideos: _,
    Videos_YourPublicVideos: _,
    Videos_YourFriendsOnlyVideos: _,
    Videos_YourPrivateVideos: _,
    Videos_YourUnlistedVideos: _,
    Screenshots_Manage: _,
    Images_Manage: _,
    Videos_Manage: _,
    Screenshots_SelectScreenshots: _,
    Images_SelectImages: _,
    Videos_SelectVideos: _,
    Videos_Cancel: _,
    Videos_AddFromYouTube: _,
    Videos_LinkYouTubeAcct: _,
    Videos_UnlinkYouTubeAcct: _,
    Videos_UnlinkButton: _,
    Videos_UnlinkConfirmText: _,
    Videos_Privacy: _,
    Videos_YoutubeTerms_1: _,
    Videos_YoutubeTerms_2: _,
    Videos_YoutubeTerms_3: _,
    Videos_YoutubeTerms_4: _,
    Videos_YoutubeTermsLink_TermsOfService: _,
    Videos_YoutubeTermsLink_PrivacyPolicy: _,
    Videos_YoutubeTermsLink_AuthorizedData: _,
    Videos_YoutubeTermsLink_SecuritySettings: _,
    Videos_NowOnSteam: _,
    Videos_ShareDescription: _,
    Videos_Desc1: _,
    Videos_Desc2: _,
    Videos_Desc3: _,
    Videos_AccessYourYouTubeVideos: _,
    Videos_CurrentlyLinkedTo: _,
    Videos_UnlinkToAddAnother: _,
    Videos_UnlinkAcct: _,
    Videos_ContinueWithAcct: _,
    Videos_SuccessfullyLinkedYouTube: _,
    Videos_SuccessfullyAddedSingular: _,
    Videos_SuccessfullyAddedPlural: _,
    Videos_NoVideosMsg1: _,
    Videos_NoVideosMsg2: _,
    Videos_CurrentlyLinkedMsg: _,
    Videos_ClickHereToChange: _,
    Videos_ChangeAccount: _,
    Videos_AddStep1: _,
    Videos_AvailCountSingular: _,
    Videos_AvailCountPlural: _,
    Videos_AddStep2: _,
    Videos_AddStep2Note: _,
    Videos_OptionNoneOther: _,
    Videos_OtherUnlisted: _,
    Videos_AddStep3: _,
    Videos_AddVideo: _,
    Videos_AddNote2: _,
    Videos_Refresh: _,
    Videos_AddStep4: _,
    Videos_AddNote4: _,
    Videos_AddDone: _,
    Videos_IssuesAccessing: _,
    Images_Upload: _,
    Screenshots_Upload: _,
    Screenshots_MakePublic: _,
    Screenshots_MakeFriendsOnly: _,
    Screenshots_MakePrivate: _,
    Screenshots_MakeUnlisted: _,
    Screenshots_Delete: _,
    Screenshots_SelectAll: _,
    Screenshots_Done: _,
    Screenshots_DeleteScreenshots: _,
    Screenshots_UpdatePrivacy: _,
    Screenshots_AreYouSureDelete: _,
    Screenshots_AreYouSurePrivacyChange: _,
    Screenshots_Continue: _,
    Screenshots_Cancel: _,
    Screenshots_Oops: _,
    Screenshots_NoneSelected: _,
    Screenshots_SelectScreenshotsToDelete: _,
    Screenshots_OK: `OK`,
    Screenshots_VisUpdateFailed: _,
    Screenshots_VisUpdateFailedMessage: _,
    Blotter_PotentialSpoilers: _,
    Blotter_RevealImage: _,
    Profile_SharedFiles_NoScreenshotsSelf: _,
    Profile_SharedFiles_NoScreenshotsForYou: _,
    Profile_SharedFiles_NoScreenshotsFavoritesSelf: _,
    Profile_SharedFiles_NoScreenshotsFavoritesForYou: _,
    Profile_SharedFiles_NoImagesSelf: _,
    Profile_SharedFiles_NoImagesForYou: _,
    Profile_SharedFiles_NoImagesFavoritesSelf: _,
    Profile_SharedFiles_NoImagesFavoritesForYou: _,
    Profile_SharedFiles_NoVideosSelf: _,
    Profile_SharedFiles_NoVideosForYou: _,
    Profile_SharedFiles_NoVideosFavoritesSelf: _,
    Profile_SharedFiles_NoVideosFavoritesForYou: _,
    Profile_SharedFiles_NoScreenshotsThisVisibility: _,
    Screenshots_SteamHasThem: _,
    Screenshots_Instructions1: _,
    Screenshots_Instructions2: _,
    Profile_SharedFiles_By: _,
    Profile_SharedFiles_FavoritedBy: _,
  };
export {
  _ as AppHubHome_BackToTop,
  _ as AppHub_Guides_GuidesYouHaveMade,
  _ as AppHub_Guides_IntegratedGuides,
  _ as AppHub_Guides_IntegratedGuides_Desc,
  _ as AppHub_Guides_MoreInfo_Title,
  _ as AppHub_Guides_MoreInfo_button,
  _ as AppHub_Guides_MostPopularThisWeek,
  _ as AppHub_Guides_MostPopularThisWeek_Desc,
  _ as AppHub_Guides_NumGuides_Plural,
  _ as AppHub_Guides_NumGuides_Singular,
  _ as AppHub_Guides_PopularCategories,
  _ as AppHub_Guides_ViewAll,
  _ as AppHub_Guides_YourFavorites,
  _ as AppPrivacy_Explanation,
  _ as AppPrivacy_MarkAsPrivate,
  _ as AppPrivacy_UnmarkAsPrivate,
  _ as Blotter_PotentialSpoilers,
  _ as Blotter_RevealImage,
  _ as CommunityFollower_Description,
  _ as CommunityFollower_Description_Yours,
  _ as CommunityFollower_FollowUser,
  _ as CommunityFollower_FollowingUser,
  _ as CommunityFollower_NumFollowers,
  _ as CommunityFollower_One_Follower,
  _ as CommunityFollower_UnfollowUser,
  _ as Community_Forums,
  _ as Community_FriendsWhoPlayMenuItemFirstPerson,
  _ as Community_GameContent,
  _ as Community_GameContentFirstPerson,
  _ as Community_GameHubMenuItem,
  _ as Community_GameLinks,
  _ as Community_GameNotesFirstPerson,
  _ as Community_GamePersonalData,
  _ as Community_GameStats,
  _ as Community_GameStatsFirstPerson,
  _ as Community_GlobalAchievements,
  _ as Community_GlobalLeaderboards,
  _ as Community_Groups,
  _ as Community_Images,
  _ as Community_News,
  _ as Community_OfficialWebsite,
  _ as Community_RemoveLink_BeWary,
  _ as Community_RemoveLink_Tooltip,
  _ as Community_ReviewMenuItemFirstPerson,
  _ as Community_ReviewMenuItemThirdPerson,
  _ as Community_Screenshots,
  _ as Community_ScreenshotsMenuItemFirstPerson,
  _ as Community_ScreenshotsMenuItemThirdPerson,
  _ as Community_StorePage,
  _ as Community_TradingCardsMenuItemFirstPerson,
  _ as Community_UsersAchievements,
  _ as Community_UsersAchievementsFirstPerson,
  _ as Community_UsersLeaderboards,
  _ as Community_UsersLeaderboardsFirstPerson,
  _ as Community_UsersStats,
  _ as Community_Videos,
  _ as Discussions_FormattingHelp_Quote,
  _ as Discussions_FormattingHelp_Spoiler,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as GamesList_Achievement_Fraction,
  _ as GamesList_Achievement_Unlock_Percentage,
  _ as GamesList_Button_Cancel,
  _ as GamesList_Button_Download,
  _ as GamesList_Button_Pause,
  _ as GamesList_Button_Resume,
  _ as GamesList_Button_Uninstall,
  _ as GamesList_Button_Uninstalling,
  _ as GamesList_Button_UpdateRequired,
  _ as GamesList_Client_Indicator,
  _ as GamesList_Filter_BothOwned,
  _ as GamesList_Filter_Placeholder,
  _ as GamesList_Header_Achievements,
  _ as GamesList_Header_DownloadBytes,
  _ as GamesList_Header_Downloading,
  _ as GamesList_Header_LastPlayed,
  _ as GamesList_Header_Paused,
  _ as GamesList_Header_RemoteDownload,
  _ as GamesList_Header_RemoteDownloadStatus,
  _ as GamesList_Header_TotalPlayed,
  _ as GamesList_Header_TwoWeeks,
  _ as GamesList_MenuLabel_GameInfo,
  _ as GamesList_MenuLabel_RemoteDownload,
  _ as GamesList_PerfectGames_Description,
  _ as GamesList_PrivacySettings_Tooltip,
  _ as GamesList_RemoteDownload_Help,
  _ as GamesList_RemoteDownload_Info,
  _ as GamesList_RemoteDownload_LearnMore,
  _ as GamesList_RemoteDownload_NoConnection,
  _ as GamesList_RemoteDownload_NoRemoteControl,
  _ as GamesList_RemoteDownload_ReadTheFAQ,
  _ as GamesList_RemoteDownload_UninstallConfirm,
  _ as GamesList_Sort_AchievementCompletion,
  _ as GamesList_Sort_HoursPlayed,
  _ as GamesList_Sort_Name,
  _ as GamesList_Tab_AllGames,
  _ as GamesList_Tab_Followed,
  _ as GamesList_Tab_PerfectGames,
  _ as GamesList_Tab_RecentlyPlayed,
  _ as GamesList_Tab_Reviews,
  _ as GamesList_Tab_Wishlist,
  _ as GamesList_TimeRemaining,
  _ as GamesList_Uninstalling,
  _ as Images_AllYourImages,
  _ as Images_Manage,
  _ as Images_SelectImages,
  _ as Images_Upload,
  _ as Images_YourFriendsOnlyImages,
  _ as Images_YourPrivateImages,
  _ as Images_YourPublicImages,
  _ as Images_YourUnlistedImages,
  _ as Loading,
  _ as Market_GenericTitle,
  _ as Market_Item_GenericTitle,
  _ as Market_Item_Title,
  _ as Market_Search_Title,
  _ as Moderation_SubjectTypeName_ForumPost,
  _ as Paging_ShowingXtoYofZ,
  _ as Perfect_Game_Description,
  _ as Playtime_Hours,
  _ as Playtime_Minutes,
  _ as Profile_Collections,
  _ as Profile_Guides,
  _ as Profile_Images,
  _ as Profile_Screenshots,
  _ as Profile_SharedFiles_AllGames,
  _ as Profile_SharedFiles_By,
  _ as Profile_SharedFiles_FavoritedBy,
  _ as Profile_SharedFiles_GridView,
  _ as Profile_SharedFiles_ImageWallView,
  _ as Profile_SharedFiles_MostPopular,
  _ as Profile_SharedFiles_NewestFirst,
  _ as Profile_SharedFiles_NoImagesFavoritesForYou,
  _ as Profile_SharedFiles_NoImagesFavoritesSelf,
  _ as Profile_SharedFiles_NoImagesForYou,
  _ as Profile_SharedFiles_NoImagesSelf,
  _ as Profile_SharedFiles_NoScreenshotsFavoritesForYou,
  _ as Profile_SharedFiles_NoScreenshotsFavoritesSelf,
  _ as Profile_SharedFiles_NoScreenshotsForYou,
  _ as Profile_SharedFiles_NoScreenshotsSelf,
  _ as Profile_SharedFiles_NoScreenshotsThisVisibility,
  _ as Profile_SharedFiles_NoVideosFavoritesForYou,
  _ as Profile_SharedFiles_NoVideosFavoritesSelf,
  _ as Profile_SharedFiles_NoVideosForYou,
  _ as Profile_SharedFiles_NoVideosSelf,
  _ as Profile_SharedFiles_OldestFirst,
  _ as Profile_SharedFiles_SelectAGame,
  _ as Profile_Videos,
  _ as Profile_Workshop_Items,
  _ as Profile_YourWorkshop,
  _ as Screenshots_AllYourScreenshots,
  _ as Screenshots_AreYouSureDelete,
  _ as Screenshots_AreYouSurePrivacyChange,
  _ as Screenshots_Cancel,
  _ as Screenshots_Continue,
  _ as Screenshots_Delete,
  _ as Screenshots_DeleteScreenshots,
  _ as Screenshots_Done,
  _ as Screenshots_Instructions1,
  _ as Screenshots_Instructions2,
  _ as Screenshots_Location,
  _ as Screenshots_MakeFriendsOnly,
  _ as Screenshots_MakePrivate,
  _ as Screenshots_MakePublic,
  _ as Screenshots_MakeUnlisted,
  _ as Screenshots_Manage,
  _ as Screenshots_NoneSelected,
  _ as Screenshots_OK,
  _ as Screenshots_Oops,
  _ as Screenshots_SelectAll,
  _ as Screenshots_SelectScreenshots,
  _ as Screenshots_SelectScreenshotsToDelete,
  _ as Screenshots_SteamHasThem,
  _ as Screenshots_UpdatePrivacy,
  _ as Screenshots_Upload,
  _ as Screenshots_Viewing,
  _ as Screenshots_VisUpdateFailed,
  _ as Screenshots_VisUpdateFailedMessage,
  _ as Screenshots_YourFriendsOnlyScreenshots,
  _ as Screenshots_YourPrivateScreenshots,
  _ as Screenshots_YourPublicScreenshots,
  _ as Screenshots_YourUnlistedScreenshots,
  _ as SharedFiles_AddSpoilerTag,
  _ as SharedFiles_AdminTags,
  _ as SharedFiles_And_N_More,
  _ as SharedFiles_BrowseGuide_createNewBtnLabel,
  _ as SharedFiles_BrowseGuide_subtitle_nolink,
  _ as SharedFiles_Browse_GuideHome,
  _ as SharedFiles_Browse_MyFiles_Favorites,
  _ as SharedFiles_Browse_MyFiles_Items,
  _ as SharedFiles_Browse_MyFiles_Played,
  _ as SharedFiles_Browse_MyFiles_Sort_Alpha,
  _ as SharedFiles_Browse_MyFiles_Sort_CreationOrder,
  _ as SharedFiles_Browse_MyFiles_Sort_Favorited,
  _ as SharedFiles_Browse_MyFiles_Sort_LastUpdated,
  _ as SharedFiles_Browse_MyFiles_Sort_Subscribed,
  _ as SharedFiles_Browse_MyFiles_Subscriptions,
  _ as SharedFiles_ByAuthor,
  _ as SharedFiles_CreateGuide,
  _ as SharedFiles_DeveloperComments,
  _ as SharedFiles_Dota2_IntegratedGuide,
  _ as SharedFiles_Dota2_IntegratedGuide_Desc,
  _ as SharedFiles_Favorites,
  _ as SharedFiles_Favorites_NowUnsubscribed,
  _ as SharedFiles_Favorites_Subscribed,
  _ as SharedFiles_FilterByGame,
  _ as SharedFiles_Guide_Comments,
  _ as SharedFiles_Guide_Index,
  _ as SharedFiles_Guide_Overview,
  _ as SharedFiles_ItemDownload,
  _ as SharedFiles_ItemEditText_ErrorNoTitle,
  _ as SharedFiles_ItemEditText_Text_Caption,
  _ as SharedFiles_Item_Edit_Link,
  _ as SharedFiles_ManageGuide_AddContributor,
  _ as SharedFiles_ManageGuide_AddSection,
  _ as SharedFiles_ManageGuide_Cancel,
  _ as SharedFiles_ManageGuide_Contents,
  _ as SharedFiles_ManageGuide_Contents_Desc,
  _ as SharedFiles_ManageGuide_Contributors,
  _ as SharedFiles_ManageGuide_Contributors_Desc,
  _ as SharedFiles_ManageGuide_DeleteThisSection,
  _ as SharedFiles_ManageGuide_EditSubSection,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Delete,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Desc,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Insert,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Changes,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Edit,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Preview,
  _ as SharedFiles_ManageGuide_EditThisSection,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_Layout,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutInline,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutLeft,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutRight,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_Size,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeFull,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeOriginal,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeThumb,
  _ as SharedFiles_ManageGuide_Images,
  _ as SharedFiles_ManageGuide_Images_Desc,
  _ as SharedFiles_ManageGuide_InsertImage,
  _ as SharedFiles_ManageGuide_InsertYouTubeVideo,
  _ as SharedFiles_ManageGuide_NoContributors,
  _ as SharedFiles_ManageGuide_NoPreviewImages,
  _ as SharedFiles_ManageGuide_NoSectionTitle,
  _ as SharedFiles_ManageGuide_NoSubSections,
  _ as SharedFiles_ManageGuide_Preview,
  _ as SharedFiles_ManageGuide_PromptYouTubeUrl,
  _ as SharedFiles_ManageGuide_RemoveSectionConfirm,
  _ as SharedFiles_ManageGuide_Required,
  _ as SharedFiles_ManageGuide_Save,
  _ as SharedFiles_ManageGuide_Screenshots,
  _ as SharedFiles_ManageGuide_SubImages,
  _ as SharedFiles_ManageGuide_SubScreenshots,
  _ as SharedFiles_ManageGuide_SubSectionContentChanged,
  _ as SharedFiles_ManageGuide_SubSectionContentChanged_CancelConfirm,
  _ as SharedFiles_ManageGuide_SubSectionContentSaved,
  _ as SharedFiles_ManageGuide_SubSectionContents,
  _ as SharedFiles_ManageGuide_SubSectionTitle,
  _ as SharedFiles_ManageGuide_SubVideos,
  _ as SharedFiles_ManageGuide_Videos,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Full,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Left,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Right,
  _ as SharedFiles_Media_ViewAppFanArt,
  _ as SharedFiles_Media_ViewAppScreenshots,
  _ as SharedFiles_Media_ViewAppVideos,
  _ as SharedFiles_MustOwnAppToCreateGuide,
  _ as SharedFiles_NoGuides_Desc1,
  _ as SharedFiles_NoGuides_Desc2,
  _ as SharedFiles_NoGuides_Title,
  _ as SharedFiles_OwnerControl_BackGuide,
  _ as SharedFiles_OwnerControl_EditCaption,
  _ as SharedFiles_PublicComments,
  _ as SharedFiles_RemoveSelfTag_Tooltip,
  _ as SharedFiles_RemoveSpoilerTag,
  _ as SharedFiles_SaveSubscribedToCollection_Btn,
  _ as SharedFiles_SaveSubscribedToCollection_Desc,
  _ as SharedFiles_SaveSubscribedToCollection_Existing,
  _ as SharedFiles_SaveSubscribedToCollection_ExistingDesc,
  _ as SharedFiles_SaveSubscribedToCollection_New,
  _ as SharedFiles_SaveSubscribedToCollection_NewDesc,
  _ as SharedFiles_SaveSubscribedToCollection_NoExistingCollections,
  _ as SharedFiles_SaveSubscribedToCollection_Title,
  _ as SharedFiles_SearchedForFileType_IntegratedGuide,
  _ as SharedFiles_SearchedForFileType_WebGuide,
  _ as SharedFiles_SharedFiles_Collections,
  _ as SharedFiles_SharedFiles_Guides,
  _ as SharedFiles_SharedFiles_Items,
  _ as SharedFiles_SpoilerTagInstructions,
  _ as SharedFiles_SpoilerTagsExpire,
  _ as SharedFiles_Stats_TaggedUsers,
  _ as SharedFiles_Stats_TaggedWorkshopItems,
  _ as SharedFiles_Subscription_NowUnsubscribed,
  _ as SharedFiles_Subscription_Subscribed,
  _ as SharedFiles_Subscriptions,
  _ as SharedFiles_Tab_Merchandise,
  _ as SharedFiles_Tags,
  _ as SharedFiles_TagsSearch,
  _ as SharedFiles_UnsubscribeAll_Btn,
  _ as SharedFiles_UnsubscribeAll_Confirm_App_Desc,
  _ as SharedFiles_UnsubscribeAll_Confirm_Desc,
  _ as SharedFiles_UnsubscribeAll_Confirm_Title,
  _ as SharedFiles_UserList_BrowsePaging,
  _ as SharedFiles_UserList_LastUpdated,
  _ as SharedFiles_WaitingForIntegratedGuide,
  _ as SharedFiles_WorkshopItemsTagged,
  _ as Videos_AccessYourYouTubeVideos,
  _ as Videos_AddDone,
  _ as Videos_AddFromYouTube,
  _ as Videos_AddNote2,
  _ as Videos_AddNote4,
  _ as Videos_AddStep1,
  _ as Videos_AddStep2,
  _ as Videos_AddStep2Note,
  _ as Videos_AddStep3,
  _ as Videos_AddStep4,
  _ as Videos_AddVideo,
  _ as Videos_AllYourVideos,
  _ as Videos_AvailCountPlural,
  _ as Videos_AvailCountSingular,
  _ as Videos_Cancel,
  _ as Videos_ChangeAccount,
  _ as Videos_ClickHereToChange,
  _ as Videos_ContinueWithAcct,
  _ as Videos_CurrentlyLinkedMsg,
  _ as Videos_CurrentlyLinkedTo,
  _ as Videos_Desc1,
  _ as Videos_Desc2,
  _ as Videos_Desc3,
  _ as Videos_IssuesAccessing,
  _ as Videos_LinkYouTubeAcct,
  _ as Videos_Manage,
  _ as Videos_NoVideosMsg1,
  _ as Videos_NoVideosMsg2,
  _ as Videos_NowOnSteam,
  _ as Videos_OptionNoneOther,
  _ as Videos_OtherUnlisted,
  _ as Videos_Privacy,
  _ as Videos_Refresh,
  _ as Videos_SelectVideos,
  _ as Videos_ShareDescription,
  _ as Videos_SuccessfullyAddedPlural,
  _ as Videos_SuccessfullyAddedSingular,
  _ as Videos_SuccessfullyLinkedYouTube,
  _ as Videos_UnlinkAcct,
  _ as Videos_UnlinkButton,
  _ as Videos_UnlinkConfirmText,
  _ as Videos_UnlinkToAddAnother,
  _ as Videos_UnlinkYouTubeAcct,
  _ as Videos_YourFriendsOnlyVideos,
  _ as Videos_YourPrivateVideos,
  _ as Videos_YourPublicVideos,
  _ as Videos_YourUnlistedVideos,
  _ as Videos_YoutubeTermsLink_AuthorizedData,
  _ as Videos_YoutubeTermsLink_PrivacyPolicy,
  _ as Videos_YoutubeTermsLink_SecuritySettings,
  _ as Videos_YoutubeTermsLink_TermsOfService,
  _ as Videos_YoutubeTerms_1,
  _ as Videos_YoutubeTerms_2,
  _ as Videos_YoutubeTerms_3,
  _ as Videos_YoutubeTerms_4,
  _ as Workshop_BrowseBy,
  _ as Workshop_BrowsePaging,
  _ as Workshop_DeveloperThreadDesc,
  _ as Workshop_DeveloperThreadDisclaimerText,
  _ as Workshop_HasLinkedItems,
  _ as Workshop_ImageSize,
  _ as Workshop_ItemModalViewCountDetails,
  _ as Workshop_ItemModalViewDetails,
  _ as Workshop_Link_LegalAgreement,
  _ as Workshop_Link_PaymentInfo,
  _ as Workshop_NoItems,
  _ as Workshop_PaymentInfo_NotCreated,
  _ as Workshop_PaymentInfo_Rejected,
  _ as Workshop_SplitsAcceptTheseDesc1,
  _ as Workshop_SplitsAcceptTheseDesc2,
  _ as Workshop_SplitsPercentage,
  _ as Workshop_Subscribe_IntegratedGuide,
  _ as Workshop_ViewYourRevenue,
  _ as Workshop_ViewYourRevenue_desc,
  _ as community_errorpage_title,
  _ as community_title,
  _ as default,
  _ as empty_no_comma_following,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_accessibility,
  _ as footer_cookies,
  _ as footer_geodata_notice,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_privacy_policy,
  _ as footer_refunds,
  _ as footer_ssa,
  _ as moderatedcontent_description,
  _ as moderation_claim_n_reports_on_m_subjects,
  _ as moderation_claim_report_count,
  _ as moderation_claim_report_count_Plural,
  _ as moderation_claim_subject_count,
  _ as moderation_claim_subject_count_Plural,
  _ as moderation_forumpost_summary,
  _ as moderation_forumpost_summary_reports_fragment,
  _ as moderation_forumpost_summary_reports_fragment_Plural,
  _ as moderation_forumpost_summary_subjects_fragment,
  _ as moderation_forumpost_summary_subjects_fragment_Plural,
  _ as profile_error_profilenotfound,
  _ as profile_games_list,
  _ as profile_games_list_error_loadfailed,
  _ as profile_games_list_title,
  _ as profiletabs_communitymessages,
  _ as profiletabs_currentbans,
  _ as profiletabs_moderatedcontent,
  _ as profiletabs_reportedcontent,
  _ as reportedcontent_description,
  _ as reportedcontent_lastupdated,
};
