var _ = `english`,
  _ = `Steam Workshop`,
  _ = `The Steam Workshop for %1$s`,
  _ = `There was a problem loading this page. Please try again later.`,
  _ = `Error`,
  _ = `There was a problem performing that action. Please try again later. (%1$s)`,
  _ = `Sorry!`,
  _ = `An error was encountered while processing your request:`,
  _ = `You've made too many requests recently. Please wait and try your request again later.`,
  _ = `(Admin Only) View Old Workshop`,
  _ = `Browsing: %1$s`,
  _ = `(Vote for Your Favorites)`,
  _ = `(Subscribe to add to your game)`,
  _ = `(Vote for Your Favorites)`,
  _ = `Accepted for Game`,
  _ = `Accepted`,
  _ = `Official Content`,
  _ = `By %1$s`,
  _ = `Items`,
  _ = `Items`,
  _ = `Collections`,
  _ = `Merchandise`,
  _ = `Videos`,
  _ = `Saved Queries`,
  _ = `Save this search query`,
  _ = `Enter a name for your search`,
  _ = `Save your current search filters and sort options to quickly use again in the future. You can find these under 'Your Items'.`,
  _ = `Save as a new search query or select a previously saved search query to update`,
  _ = `<New Saved Search>`,
  _ = `Save`,
  _ = `Delete Saved Search`,
  _ = `Are you sure you want to delete your saved search '%1$s'?`,
  _ = `Delete`,
  _ = `Learn More`,
  _ = `Clear search`,
  _ = `The Steam Workshop for %1$s`,
  _ = `Sort Order`,
  _ = `Time Frame`,
  _ = `Today`,
  _ = `One Week`,
  _ = `Thirty Days`,
  _ = `Three Months`,
  _ = `Six Months`,
  _ = `One Year`,
  _ = `All Time`,
  _ = `%1$s (%2$s)`,
  _ = `Most Recent`,
  _ = `Most Popular`,
  _ = `Top Rated All Time`,
  _ = `Last Updated`,
  _ = `Report Weight`,
  _ = `(Admin) %1$s`,
  _ = `Most Required by Other Items`,
  _ = `In Most Collections`,
  _ = `(Admin) Approval Queue`,
  _ = `Not Yet Rated`,
  _ = `Total Unique Subscribers`,
  _ = `Total Votes`,
  _ = `Most Up Votes`,
  _ = `Search Relevance`,
  _ = `Recent Playtime`,
  _ = `Lifetime Playtime`,
  _ = `Recent Average Playtime`,
  _ = `Lifetime Average Playtime`,
  _ = `Play Sessions`,
  _ = `Lifetime Play Sessions`,
  _ = `Inappropriate Score`,
  _ = `Ban Content Check`,
  _ = `Curated Admin`,
  _ = `Nominee`,
  _ = `Rated by You`,
  _ = `Date Accepted`,
  _ = `Special Filters: `,
  _ = `None`,
  _ = `Accepted for Game`,
  _ = `Created by Friends`,
  _ = `Created by Followed`,
  _ = `Favorited by Friends`,
  _ = `Reported (Admin Only)`,
  _ = `Required by Other Items`,
  _ = `In Collections`,
  _ = `Home`,
  _ = `Browse`,
  _ = `Your Items`,
  _ = `Discussions`,
  _ = `About`,
  _ = `Search %1$s`,
  _ = `Items you've posted (%1$s)`,
  _ = `Your favorites (%1$s)`,
  _ = `Subscribed items (%1$s)`,
  _ = `Played items (%1$s)`,
  _ = `Your collections (%1$s)`,
  _ = `Your voting queue`,
  _ = `Your Payment Info`,
  _ = `View Your Revenue`,
  _ = `(from sales of your Workshop items)`,
  _ = `View Legal Agreement`,
  _ = `Voting Queue`,
  _ = `Apply filters`,
  _ = `Sort by: %1$s`,
  _ = `<none selected>`,
  _ = `Required DLC`,
  _ = `Required DLC: %1$s`,
  _ = `Require DLC that you own`,
  _ = `Exclude items that require DLC that you do not own`,
  _ = `You don't own any DLC`,
  _ = `You own all available DLC`,
  _ = `(%1$s more items)`,
  _ = `Include Owned`,
  _ = `Exclude Unowned`,
  _ = `Filter by Name`,
  _ = `Show incompatible items`,
  _ = `Some items are not possible to include in the game. You can still find them if you select this box.`,
  _ = `View Hidden & Friends-Only Items`,
  _ = `Results for: "%1$s"`,
  _ = `Results for: "%1$s" (title only)`,
  _ = `Results for: "%1$s" (description only)`,
  _ = `Containing item: "%1$s"`,
  _ = `Require "%1$s" in order to function properly`,
  _ = `%1$s: %2$s`,
  _ = `%1$s: %2$s`,
  _ = `Tag: Incompatible items`,
  _ = `Tag: Accepted items`,
  _ = `Specify what text fields of the item you want to search:`,
  _ = `Title & Description`,
  _ = `Title Only`,
  _ = `Description Only`,
  _ = `You can build more complex searches using %1$s, %2$s, and %3$s operators (must be capitalized). Alternatively, you can use the %4$s and %5$s characters as a shorthand for %1$s and %3$s.`,
  _ = `%1$s finds items with both '%2$s' and '%3$s' in the search text`,
  _ = `%1$s finds items with either '%2$s' or '%3$s' in the search text`,
  _ = `%1$s finds items with '%2$s' but not '%3$s' in the search text`,
  _ = `red`,
  _ = `blue`,
  _ = `green`,
  _ = `room`,
  _ = `Combining search terms with parentheses will let you build some pretty specific searches.`,
  _ = `%1$s finds items with '%2$s', paired with either '%3$s' or '%4$s' in the search text.`,
  _ = `%1$s finds items with '%2$s' and '%3$s' or '%4$s', but not '%5$s' in the search text.`,
  _ = `Desired position for filters:`,
  _ = `Left Side`,
  _ = `Right Side`,
  _ = `Collapsed`,
  _ = `Dim these items:`,
  _ = `Reported by you`,
  _ = `Created by users you've blocked`,
  _ = `Voted up by you`,
  _ = `Voted down by you`,
  _ = `In your subscription list`,
  _ = `Filter by Date`,
  _ = `Posted Date`,
  _ = `Posted after %1$s`,
  _ = `Posted before %1$s`,
  _ = `Posted between %1$s and %2$s`,
  _ = `Date Last Updated`,
  _ = `Updated after %1$s`,
  _ = `Updated before %1$s`,
  _ = `Updated between %1$s and %2$s`,
  _ = `Between`,
  _ = `And`,
  _ = `1 entry matching filters`,
  _ = `%2$s entries matching filters`,
  _ = `Per page:`,
  _ = `%1$s / %2$s`,
  _ = `Create Collection`,
  _ = `Submit your design`,
  _ = `Quick View`,
  _ = `See More`,
  _ = `You are subscribed to this item`,
  _ = `This item is in your Favorites list`,
  _ = `You have played this item`,
  _ = `This item has been accepted for use within this game!`,
  _ = `This item has been marked incompatible for this game.`,
  _ = `You gave this item a thumbs up.`,
  _ = `You gave this item a thumbs down.`,
  _ = `You reported this item for violating Steam Community Guidelines.`,
  _ = `You have blocked this user.`,
  _ = `Description`,
  _ = `Discussions`,
  _ = `Comments (%1$s)`,
  _ = `Announcements`,
  _ = `Item Stats`,
  _ = `Change Notes (%1$s)`,
  _ = `Steam Workshop :: %1$s`,
  _ = `Created by: `,
  _ = `%2$s rating`,
  _ = `%2$s ratings`,
  _ = `Not enough ratings`,
  _ = `%1$s @ %2$s`,
  _ = `Posted:`,
  _ = `Updated:`,
  _ = `Subscribe`,
  _ = `Subscribed`,
  _ = `Unsubscribe`,
  _ = `Favorite`,
  _ = `Favorited`,
  _ = `Unfavorite`,
  _ = `View Dependent Items`,
  _ = `Add to Collection`,
  _ = `Save to Collection`,
  _ = `Please sign in to take this action`,
  _ = `Subscribe to download`,
  _ = `Unsubscribe to remove this item from your game`,
  _ = `Easily find this item again later`,
  _ = `View all %1$s items that depend on this item in order to function properly. Note that some may be marked hidden or friends-only.`,
  _ = `Report this item for violating the Steam Online Conduct Rules`,
  _ = `Award`,
  _ = `Add to one of your collections`,
  _ = `File Size:`,
  _ = `Visitors:`,
  _ = `Subscribers:`,
  _ = `Favorites:`,
  _ = `Total Unique Favorites:`,
  _ = `Total Unique Subscribers:`,
  _ = `Total Play Sessions:`,
  _ = `Requires the following items: `,
  _ = `Requires the following DLC: `,
  _ = `Subscribe to all`,
  _ = `Unsubscribe from all`,
  _ = `Save to Collection`,
  _ = `Expand all Community Awards`,
  _ = `%1$s Community Award`,
  _ = `%1$s Community Awards`,
  _ = `TAGS`,
  _ = `CATEGORIES`,
  _ = `DESCRIPTION`,
  _ = `Required By:`,
  _ = `In %1$s Collections`,
  _ = `In %1$s Collections by %2$s`,
  _ = `Error`,
  _ = `You do not have permission to perform that action.`,
  _ = `There was an issue contacting Steam. Please try again later.`,
  _ = `You have attempted to perform too many actions within a short period of time. Please wait a little longer before trying again.`,
  _ = `There was a problem trying to perform that action. Please try again later.`,
  _ = `Subscribe to All`,
  _ = `Do you want to add the items in this collection to your subscriptions, or overwrite your subscriptions to contain only items from this collection?`,
  _ = `Add Only`,
  _ = `Overwrite My Subscriptions`,
  _ = `Additional Required Items`,
  _ = `This item requires all of the following other items in order to function properly.`,
  _ = `<1>%1$s</1> requires all of the following other items in order to function properly.`,
  _ = `You can click on each one here to learn more about and subscribe to the item before proceeding.`,
  _ = `You can also choose to subscribe to all these required items (and all the items they in turn require), but be warned that could include many more items.`,
  _ = `Subscribe to Just This Item`,
  _ = `Subscribe to All`,
  _ = `Report this item`,
  _ = `Now, please describe the way in which this item is in violation of the Steam Terms of Service. Please include any relevant information or links. Filing this report cannot be undone.`,
  _ = `Reason: %1$s`,
  _ = `First, select a reason why you are reporting this item:`,
  _ = `If you'd like to report Copyright Infringement and are the copyright holder, please proceed to our DMCA compliant notice of copyright infringement form %1$s.`,
  _ = `If you'd like to file a Trademark complaint, please file one %1$s.`,
  _ = `here`,
  _ = `Add to Collection`,
  _ = `'%1$s' will be added to the selected collections below:`,
  _ = `You don't have any saved collections. You can create a new one by entering a name for it below.`,
  _ = `Add to Selected Collections`,
  _ = `Create New Collection`,
  _ = `Overwrite Collection`,
  _ = `Would you like to save this collection to a new collection or overwrite an existing collection?`,
  _ = `New Collection`,
  _ = `Existing Collection`,
  _ = `Enter a name for this collection:`,
  _ = `Select a collection to overwrite:`,
  _ = `Contains %2$s item`,
  _ = `Contains %2$s items`,
  _ = `Has %2$s linked collection`,
  _ = `Has %2$s linked collections`,
  _ = `+%1$s`,
  _ = `The Steam Workshop makes it easier than ever for you to submit finished 3D models of items for a chance to have them accepted and incorporated to the actual game. To publish an item to the workshop for consideration, first read the official documentation linked on the right, then click the Steam Workshop button in the main menu of the game.`,
  _ = `The Steam Workshop makes it easy to discover or share new content for your game or software. Each game or software might support slightly different kinds of content in their Workshop, so it's best to check out the official documentation for more details on what can be created and shared in that area.`,
  _ = `When you find content you wish to add to your game, click the 'subscribe' button. In most cases the content will be automatically available the next time you launch the game. But some products require that you go into a dedicated area of the game or software to activate or access the new content.`,
  _ = `The Steam Workshop makes it easy to discover or share new content for your game or software. Each title might support slightly different kinds of content in their Workshop, so it's best to check out the official documentation for more details on what can be created and shared in that area.`,
  _ = `When you find content under the %1$s tab you wish to add to your game, click the 'subscribe' button. In most cases the content will be automatically available the next time you launch the game. But some products require that you go into a dedicated area of the game or software to activate or access the new content.`,
  _ = `Enabled Features`,
  _ = `These are the Steam Workshop features utilized by %1$s:`,
  _ = `Ready-To-Use Items`,
  _ = `Items posted in this Workshop are ready for immediate use. Click the Subscribe button on the detail page for the item and it will be available when you start %1$s.`,
  _ = `Items posted in this Workshop under the %2$s tab are ready for immediate use. Click the Subscribe button on the detail page for the item and it will be available when you start %1$s.`,
  _ = `Versioning Support for Game Branches`,
  _ = `Items can have versions associated with different game (beta) branches. This makes it easier for developers and Workshop item authors to work together to ensure compatibility of their items as %1$s receives updates.`,
  _ = `Curated Item Selection`,
  _ = `Items posted in this Workshop aren't immediately usable in %1$s. Instead, the developers are looking to the community to rate up items they would most like to see made available to buy or unlock within %1$s. Ultimately, the developers choose which items to select and add to %1$s.`,
  _ = `Items posted in this Workshop under the %2$s tab aren't immediately usable in %1$s. The developers are looking to the community to rate up items they would most like to see made available to buy or unlock within %1$s. Ultimately, the developers choose which items to select and add to %1$s.`,
  _ = `Item Sales`,
  _ = `Accepted items from the Workshop are made available for purchase or can be unlocked within %1$s.`,
  _ = `Direct Item Sales`,
  _ = `Items in this Workshop may be listed for sale directly via the Steam Workshop. These items may need approval from the developers or community prior to availability. Content Creators: Check out the <a %s>Earning Money</a> section below to learn more about selling your content on the Steam Workshop`,
  _ = `Item Creators Can Earn Royalties`,
  _ = `Items from this Workshop that are accepted for sale will pay the creators a split of the revenue if that item is sold for a fee.`,
  _ = `Service Providers Can Earn Royalties`,
  _ = `Workshop authors can select from a pre-approved list of organizations, users, and toolmakers to receive a percentage of Valve's revenue from sale of their items. The specific organizations and individuals are listed below.`,
  _ = `Are you a content creator and know of another organization or individual you'd like to be able to share in the success of your item's sales? Please let us know <a href="%1$s">here</a>.`,
  _ = `Revenue Share`,
  _ = `This is the percentage of revenue an item creator receives from direct sales of their item.`,
  _ = `Click %1$s to learn more.`,
  _ = `here`,
  _ = `Items posted in this Workshop`,
  _ = `Items accepted for %1$s`,
  _ = `Related Links`,
  _ = `View Official Documentation`,
  _ = `Find Steam Guides`,
  _ = `Community-made guides for this Workshop`,
  _ = `For purchases via Steam Workshop`,
  _ = `Steam Workshop Terms`,
  _ = `For Steam Workshop Revenue`,
  _ = `Service Providers`,
  _ = `View Site`,
  _ = `View Steam Profile`,
  _ = `Tools`,
  _ = `Communities`,
  _ = `Users`,
  _ = `View Details`,
  _ = `Quick View`,
  _ = `Vote`,
  _ = `for community-made items you want to see in the game`,
  _ = `Click to get started voting in your Queue.`,
  _ = `You've voted on %1$s item thus far.`,
  _ = `You've voted on %1$s items thus far.`,
  _ = `In the past week`,
  _ = `In the past month`,
  _ = `In the past three months`,
  _ = `In the past six months`,
  _ = `In the past year`,
  _ = `From Followed Authors`,
  _ = `Recently posted items from authors you follow`,
  _ = `More from followed authors`,
  _ = `Accepted Items`,
  _ = `These items have been accepted and may be available as drops or purchases within the game`,
  _ = `View all Accepted Items`,
  _ = `Most Popular %1$s`,
  _ = `Most Popular`,
  _ = `Best rated in the past three months`,
  _ = `View most popular`,
  _ = `Most Subscribed`,
  _ = `Most current unique subscribers`,
  _ = `View most subscribed`,
  _ = `New`,
  _ = `Items posted most recently`,
  _ = `View recently posted`,
  _ = `Most Playtime`,
  _ = `View most played`,
  _ = `Last Updated`,
  _ = `Items updated most recently`,
  _ = `View recently updated`,
  _ = `Friends' Favorites`,
  _ = `Items marked as favorites by your friends`,
  _ = `See all friends' favorites`,
  _ = `Most Required by Other Items`,
  _ = `Most popular items that other items require in order to function properly`,
  _ = `View All`,
  _ = `Most Popular Merchandise`,
  _ = `See all Popular Merchandise`,
  _ = `View All`,
  _ = `Your Favorites`,
  _ = `View recently updated favorites`,
  _ = `Your Played Items`,
  _ = `View recently updated played items you've played`,
  _ = `Your Subscriptions`,
  _ = `View your recently updated subscriptions`,
  _ = `Updated within the last three months`,
  _ = `Special Event: %1$s`,
  _ = `See all items tagged with %1$s`,
  _ = `%1$s friend has added this to their Favorites`,
  _ = `%1$s friends has added this to their Favorites`,
  _ = `Maps`,
  _ = `Items`,
  _ = `Custom Games and Bot Scripts`,
  _ = `Items`,
  _ = `Filter by Hero`,
  _ = `Maps`,
  _ = `Items`,
  _ = {
    language: _,
    Header_WorkshopTitle: _,
    Header_App_WorkshopTitle: _,
    Workshop_Error_Loading: _,
    Workshop_Error_Title: _,
    Workshop_Error_Browse_Desc: _,
    Error_Sorry: _,
    Error_Encountered: _,
    Error_TooManyRequests_Description: _,
    Workshop_ExitReact_Link: _,
    Workshop_Browsing: _,
    Workshop_Browsing_Mtx_Desc: _,
    Workshop_Browsing_ReadyToUse_Desc: _,
    Workshop_Browsing_Merchandise_Desc: _,
    Workshop_AcceptedForGame: _,
    Workshop_AcceptedMerch: _,
    Workshop_OfficialContent: _,
    Workshop_Browse_Author_Link: _,
    Workshop_Section_Mtx: _,
    Workshop_Section_ReadyToUse: _,
    Workshop_Section_Collections: _,
    Workshop_Section_Merchandise: _,
    Workshop_Section_Videos: _,
    Workshop_Saved_Queries: _,
    Workshop_Saved_Queries_Update: _,
    Workshop_Saved_Queries_Save_Title: _,
    Workshop_Saved_Queries_Save_Desc_Long: _,
    Workshop_Saved_Queries_Save_Desc: _,
    Workshop_Saved_Queries_Save_New: _,
    Workshop_Saved_Queries_Save_Btn: _,
    Workshop_Saved_Queries_Delete_Title: _,
    Workshop_Saved_Queries_Delete_Desc: _,
    Workshop_Saved_Queries_Delete_Btn: _,
    Workshop_LearnMore: _,
    Workshop_Filters_ClearBtn: _,
    Workshop_About: _,
    Workshop_BrowseSort_SortOrder: _,
    Workshop_BrowseSort_TimeFrame: _,
    SharedFiles_Browse_Trend_Option_Today: _,
    SharedFiles_Browse_Trend_Option_Week: _,
    SharedFiles_Browse_Trend_Option_Month: _,
    SharedFiles_Browse_Trend_Option_ThreeMonths: _,
    SharedFiles_Browse_Trend_Option_SixMonths: _,
    SharedFiles_Browse_Trend_Option_OneYear: _,
    SharedFiles_Browse_Trend_Option_AllTime: _,
    Workshop_BrowseSort_Combined: _,
    Workshop_BrowseSort_MostRecent: _,
    Workshop_BrowseSort_MostPopular: _,
    Workshop_BrowseSort_TopRated: _,
    Workshop_BrowseSort_LastUpdated: _,
    Workshop_BrowseSort_Reported: _,
    Workshop_BrowseSort_AdminOption: _,
    Workshop_BrowseSort_NumParentItems: _,
    Workshop_BrowseSort_NumParentCollections: _,
    Workshop_RequireApproval: _,
    Workshop_BrowseSort_ToRate: _,
    Workshop_BrowseSort_TotalUniqueSubscribers: _,
    Workshop_BrowseSort_TotalVotes: _,
    Workshop_BrowseSort_MostUpVotes: _,
    Workshop_BrowseSort_SearchRelevance: _,
    Workshop_BrowseSort_Playtime: _,
    Workshop_BrowseSort_PlaytimeTotal: _,
    Workshop_BrowseSort_PlaytimeAverage: _,
    Workshop_BrowseSort_PlaytimeAverageTotal: _,
    Workshop_BrowseSort_PlaytimeSessions: _,
    Workshop_BrowseSort_PlaytimeSessionsTotal: _,
    Workshop_BrowseSort_Inappropriate: _,
    Workshop_BrowseSort_BanContentCheck: _,
    Workshop_BrowseSort_CuratedAdmin: _,
    Workshop_BrowseSort_Nominee: _,
    Workshop_BrowseSort_Rated: _,
    Workshop_BrowseSort_AcceptedTime: _,
    Workshop_SpecialFilter_Desc: _,
    Workshop_SpecialFilter_None: _,
    Workshop_SpecialFilter_AcceptedForUse: _,
    Workshop_SpecialFilter_CreatedByFriends: _,
    Workshop_SpecialFilter_CreatedByFollowed: _,
    Workshop_SpecialFilter_FavoritedByFriends: _,
    Workshop_SpecialFilter_Reported: _,
    Workshop_SpecialFilter_ParentItems: _,
    Workshop_SpecialFilter_ParentCollections: _,
    Workshop_Menu_Home: _,
    Workshop_Menu_Browse: _,
    Workshop_Menu_YourItems: _,
    Workshop_Menu_Discussions: _,
    Workshop_Menu_About: _,
    Workshop_Menu_Search: _,
    Workshop_SubMenu_YourItems: _,
    Workshop_SubMenu_YourFavorites: _,
    Workshop_SubMenu_YourSubscriptions: _,
    Workshop_SubMenu_YourPlayed: _,
    Workshop_SubMenu_YourCollections: _,
    Workshop_SubMenu_YourVotingQueue: _,
    Workshop_SubMenu_YourPaymentInfo: _,
    Workshop_SubMenu_ViewYourRevenue: _,
    Workshop_SubMenu_ViewYourRevenue_Desc: _,
    Workshop_SubMenu_LegalAgreement: _,
    Workshop_SubMenu_VotingQueue: _,
    Workshop_ApplyFilters: _,
    Workshop_SortBy: _,
    Workshop_Tag_NoneSpecified: _,
    Workshop_RequiredDLC_Header: _,
    Workshop_RequiredDLC_Filter: _,
    Workshop_IncludeOwnedDLC_Filter: _,
    Workshop_ExcludeOwnedDLC_Filter: _,
    Workshop_OwnedDLC_None_Filter: _,
    Workshop_OwnedDLC_All_Filter: _,
    Workshop_OwnedDLC_More_Filter: _,
    Workshop_RequiredDLC_IncludeOwned: _,
    Workshop_RequiredDLC_ExcludeUnowned: _,
    Workshop_RequiredDLC_NameFilter: _,
    Workshop_Flag_Incompatible_Checkbox: _,
    Workshop_Flag_Incompatible_Checkbox_Desc: _,
    Workshop_Admin_View: _,
    Workshop_SearchResults_SearchText: _,
    Workshop_SearchResults_SearchText_TitleOnly: _,
    Workshop_SearchResults_SearchText_DescriptionOnly: _,
    Workshop_SearchedForChild: _,
    Workshop_SearchedForRequiredItem: _,
    Workshop_SearchResults_Tag: _,
    Workshop_SearchResults_KVTag: _,
    Workshop_SearchResults_Flag_Incompatible: _,
    Workshop_SearchResults_Flag_Accepted: _,
    Workshop_SearchTarget_MenuTitle: _,
    Workshop_SearchTarget_All: _,
    Workshop_SearchTarget_Title: _,
    Workshop_SearchTarget_Description: _,
    Workshop_Search_Help: _,
    Workshop_Search_Help_Example1: _,
    Workshop_Search_Help_Example2: _,
    Workshop_Search_Help_Example3: _,
    Workshop_Search_Help_Example_Red: `red`,
    Workshop_Search_Help_Example_Blue: _,
    Workshop_Search_Help_Example_Green: _,
    Workshop_Search_Help_Example_Room: _,
    Workshop_Search_Help_Advanced: _,
    Workshop_Search_Help_AdvancedExample1: _,
    Workshop_Search_Help_AdvancedExample2: _,
    Workshop_FiltersMenu_State_Title: _,
    Workshop_FiltersMenu_State_Left: _,
    Workshop_FiltersMenu_State_Right: _,
    Workshop_FiltersMenu_State_Collapsed: _,
    Workshop_DimmedItems_Title: _,
    Workshop_DimmedItems_Reported: _,
    Workshop_DimmedItems_BlockedCreators: _,
    Workshop_DimmedItems_VotedUp: _,
    Workshop_DimmedItems_VotedDown: _,
    Workshop_DimmedItems_Subscribed: _,
    Workshop_DateFilter_FilterByDate: _,
    Workshop_DateFilter_TimeCreated: _,
    Workshop_DateFilter_TimeCreated_After: _,
    Workshop_DateFilter_TimeCreated_Before: _,
    Workshop_DateFilter_TimeCreated_Between: _,
    Workshop_DateFilter_TimeUpdated: _,
    Workshop_DateFilter_TimeUpdated_After: _,
    Workshop_DateFilter_TimeUpdated_Before: _,
    Workshop_DateFilter_TimeUpdated_Between: _,
    Workshop_DateFilter_Between: _,
    Workshop_DateFilter_And: `And`,
    Workshop_NumResults: _,
    Workshop_NumResults_Plural: _,
    Workshop_NumPerPage: _,
    Workshop_PagingControls: _,
    Workshop_CreateCollection: _,
    Workshop_CreateMerchandise: _,
    Workshop_Item_QuickView: _,
    Workshop_Item_QuickView_ExpandBtn: _,
    Workshop_StatusIcon_TT_Subscribed: _,
    Workshop_StatusIcon_TT_Favorited: _,
    Workshop_StatusIcon_TT_Played: _,
    Workshop_StatusIcon_TT_Accepted: _,
    Workshop_StatusIcon_TT_Incompatible: _,
    Workshop_StatusIcon_TT_VotedUp: _,
    Workshop_StatusIcon_TT_VotedDown: _,
    Workshop_StatusIcon_TT_Reported: _,
    Workshop_StatusIcon_TT_BlockedCreator: _,
    Workshop_ItemDetails_Tab_Description: _,
    Workshop_ItemDetails_Tab_Discussions: _,
    Workshop_ItemDetails_Tab_Comments: _,
    Workshop_ItemDetails_Tab_Updates: _,
    Workshop_ItemDetails_Tab_Stats: _,
    Workshop_ItemDetails_Tab_ChangeNotes: _,
    Workshop_ItemDetails_Title: _,
    Workshop_ItemDetails_CreatedBy: _,
    Workshop_ItemDetails_NumRatings: _,
    Workshop_ItemDetails_NumRatings_Plural: _,
    Workshop_ItemDetails_NotEnoughRatings: _,
    Workshop_ItemDetails_TimestampWithTime: _,
    Workshop_ItemDetails_TimestampCreated: _,
    Workshop_ItemDetails_TimestampUpdated: _,
    Workshop_ItemDetails_Subscribe: _,
    Workshop_ItemDetails_Subscribed: _,
    Workshop_ItemDetails_Unsubscribe: _,
    Workshop_ItemDetails_Favorite: _,
    Workshop_ItemDetails_Favorited: _,
    Workshop_ItemDetails_Unfavorite: _,
    Workshop_ItemDetails_ViewDependentItems: _,
    Workshop_ItemDetails_AddToCollection: _,
    Workshop_ItemDetails_SaveCollectionToCollection: _,
    Workshop_ItemDetails_Signin_TT: _,
    Workshop_ItemDetails_Subscribe_TT: _,
    Workshop_ItemDetails_Unsubscribe_TT: _,
    Workshop_ItemDetails_Favorite_TT: _,
    Workshop_ItemDetails_ViewDependentItems_TT: _,
    Workshop_ItemDetails_Report_TT: _,
    Workshop_ItemDetails_Award_TT: _,
    Workshop_ItemDetails_AddToCollection_TT: _,
    Workshop_ItemDetails_FileSize: _,
    Workshop_ItemDetails_Stats_UniqueVisitors: _,
    Workshop_ItemDetails_Stats_CurrentSubscribers: _,
    Workshop_ItemDetails_Stats_CurrentFavorites: _,
    Workshop_ItemDetails_Stats_LifetimeFavorites: _,
    Workshop_ItemDetails_Stats_LifetimeSubscribers: _,
    Workshop_ItemDetails_Stats_LifetimePlaytimeSessions: _,
    Workshop_ItemDetails_ItemDependencies: _,
    Workshop_ItemDetails_RequiredDLC_Desc: _,
    Workshop_Collection_SubscribeToAll: _,
    Workshop_Collection_UnsubscribeFromAll: _,
    Workshop_Collection_SaveToCollection: _,
    Workshop_ItemDetails_ShowAllReactions: _,
    Workshop_ItemDetails_ReactionCount: _,
    Workshop_ItemDetails_ReactionCount_Plural: _,
    Workshop_ItemDetails_Tags_Title: _,
    Workshop_ItemDetails_Categories_Title: _,
    Workshop_ItemDetails_Description_Title: _,
    Workshop_ItemDetails_DependentItems: _,
    Workshop_ItemDetails_InCollections: _,
    Workshop_ItemDetails_InCollectionsByAuthor: _,
    Workshop_Dialog_Error: _,
    Workshop_Dialog_AccessDenied: _,
    Workshop_Dialog_Timeout: _,
    Workshop_Dialog_LimitExceeded: _,
    Workshop_Dialog_ErrorDesc: _,
    Workshop_Dialog_CollectionSubscribe: _,
    Workshop_Dialog_CollectionSubscribe_Desc: _,
    Workshop_Dialog_CollectionSubscribe_AddOnly: _,
    Workshop_Dialog_CollectionSubscribe_Overwrite: _,
    Workshop_Dialog_ItemDependencies: _,
    Workshop_Dialog_ItemDependencies_Desc1: _,
    Workshop_Dialog_ItemDependencies_Desc1_itemName: _,
    Workshop_Dialog_ItemDependencies_Desc2: _,
    Workshop_Dialog_ItemDependencies_Desc3: _,
    Workshop_Dialog_SubscribeJustThisItem: _,
    Workshop_Dialog_SubscribeAll: _,
    Workshop_Dialog_Report: _,
    Workshop_Dialog_Report_Desc: _,
    Workshop_Dialog_Report_Reason: _,
    Workshop_Dialog_Report_Reason_Desc: _,
    Workshop_Dialog_Report_DMCA_Desc: _,
    Workshop_Dialog_Report_Trademark_Desc: _,
    Workshop_Dialog_Report_Here: _,
    Workshop_Dialog_AddToCollection: _,
    Workshop_Dialog_AddToCollection_Desc: _,
    Workshop_Dialog_AddToCollection_NoSavedCollections_Desc: _,
    Workshop_Dialog_AddToCollection_OK: _,
    Workshop_Dialog_AddToCollection_Create: _,
    Workshop_Dialog_SaveCollectionToCollection: _,
    Workshop_Dialog_SaveCollectionToCollection_Desc: _,
    Workshop_Dialog_SaveCollectionToCollection_New: _,
    Workshop_Dialog_SaveCollectionToCollection_Existing: _,
    Workshop_Dialog_SaveCollectionToCollection_NewPrompt: _,
    Workshop_Dialog_SaveCollectionToCollection_Select: _,
    Workshop_Collection_NumChildItems: _,
    Workshop_Collection_NumChildItems_Plural: _,
    Workshop_Collection_NumChildCollections: _,
    Workshop_Collection_NumChildCollections_Plural: _,
    Workshop_Collection_ViewMore: _,
    Workshop_About_PageDesc_Curation: _,
    Workshop_About_PageDesc_ReadyToUseContent1: _,
    Workshop_About_PageDesc_ReadyToUseContent2: _,
    Workshop_About_PageDesc_ReadyToUseContent_Mixed1: _,
    Workshop_About_PageDesc_ReadyToUseContent_Mixed2: _,
    Workshop_About_EnabledFeatures: _,
    Workshop_About_EnabledFeatures_Desc: _,
    Workshop_About_Feature_ReadyToUse: _,
    Workshop_About_Feature_ReadyToUse_Desc: _,
    Workshop_About_Feature_ReadyToUse_Mixed_Desc: _,
    Workshop_About_Feature_Branch_Versioning: _,
    Workshop_About_Feature_Branch_Versioning_Desc: _,
    Workshop_About_Feature_ItemCuration: _,
    Workshop_About_Feature_ItemCuration_Desc: _,
    Workshop_About_Feature_ItemCuration_Mixed_Desc: _,
    Workshop_About_Feature_ItemMtx: _,
    Workshop_About_Feature_ItemMtx_Desc: _,
    Workshop_About_Feature_Commerce: _,
    Workshop_About_Feature_Commerce_Desc: _,
    Workshop_About_Feature_AuthorRoyalties: _,
    Workshop_About_Feature_AuthorRoyalties_Desc: _,
    Workshop_About_Feature_ServiceProviders: _,
    Workshop_About_Feature_ServiceProviders_Desc: _,
    Workshop_About_Request_ServiceProviders: _,
    Workshop_About_RevenueShare: _,
    Workshop_About_RevenueShare_Desc: _,
    Workshop_About_RevenueShare_Link: _,
    Workshop_About_RevenueShare_Here: _,
    Workshop_About_NumItems: _,
    Workshop_About_NumAcceptedItems: _,
    Workshop_About_RelatedLinks: _,
    Workshop_About_ViewOfficialDocs: _,
    Workshop_About_FindGuides: _,
    Workshop_About_FindGuides_Sub: _,
    Workshop_About_RefundLink_Sub: _,
    Workshop_About_WorkshopTerms: _,
    Workshop_About_WorkshopTerms_Sub: _,
    Workshop_About_section_ServiceProviders: _,
    Workshop_ServiceProviderRevenueSharing_ViewSite: _,
    Workshop_ServiceProviderRevenueSharing_ViewSteamProfile: _,
    Workshop_ServiceProvider_Category_Tools: _,
    Workshop_ServiceProvider_Category_Communities: _,
    Workshop_ServiceProvider_Category_Users: _,
    Workshop_GamepadUIAction_ViewDetails: _,
    Workshop_GamepadUIAction_QuickView: _,
    Workshop_Home_VotingQueue: _,
    Workshop_Home_VotingQueue_Desc: _,
    Workshop_Home_VotingQueue_Btn: _,
    Workshop_Home_VotingQueue_Count: _,
    Workshop_Home_VotingQueue_Count_Plural: _,
    Workshop_Home_MostPopular_SubTitle_Week: _,
    Workshop_Home_MostPopular_SubTitle_Month: _,
    Workshop_Home_MostPopular_SubTitle_ThreeMonths: _,
    Workshop_Home_MostPopular_SubTitle_SixMonths: _,
    Workshop_Home_MostPopular_SubTitle_Year: _,
    Workshop_Home_FromFollowedAuthors: _,
    Workshop_Home_FromFollowedAuthors_Desc: _,
    Workshop_Home_FromFollowedAuthors_Btn: _,
    Workshop_Home_AcceptedItems: _,
    Workshop_Home_AcceptedItems_Desc: _,
    Workshop_Home_AcceptedItems_Btn: _,
    Workshop_Home_MostPopular: _,
    Workshop_Home_MostPopular_LongTerm: _,
    Workshop_Home_MostPopular_LongTerm_Desc: _,
    Workshop_Home_MostPopular_LongTerm_Btn: _,
    Workshop_Home_MostSubscribed: _,
    Workshop_Home_MostSubscribed_Desc: _,
    Workshop_Home_MostSubscribed_Btn: _,
    Workshop_Home_MostRecent: `New`,
    Workshop_Home_MostRecent_Desc: _,
    Workshop_Home_MostRecent_Btn: _,
    Workshop_Home_MostPlaytime: _,
    Workshop_Home_MostPlaytime_Btn: _,
    Workshop_Home_LastUpdated: _,
    Workshop_Home_LastUpdated_Desc: _,
    Workshop_Home_LastUpdated_Btn: _,
    Workshop_Home_FriendsFavorites: _,
    Workshop_Home_FriendsFavorites_Desc: _,
    Workshop_Home_FriendsFavorites_Btn: _,
    Workshop_Home_NumParentItems: _,
    Workshop_Home_NumParentItems_Desc: _,
    Workshop_Home_NumParentItems_Btn: _,
    Workshop_Home_MostPopularMerch: _,
    Workshop_Home_MostPopularMerch_Btn: _,
    Workshop_Home_ViewAll: _,
    Workshop_Home_YourFavorites: _,
    Workshop_Home_YourFavorites_Btn: _,
    Workshop_Home_YourPlayed: _,
    Workshop_Home_YourPlayed_Btn: _,
    Workshop_Home_YourSubscriptions: _,
    Workshop_Home_YourSubscriptions_Btn: _,
    Workshop_Home_YourFiles_LastUpdated: _,
    Workshop_Home_SpecialEvent_Title_Tag: _,
    Workshop_Home_SpecialEvent_Link: _,
    Workshop_ItemTooltip_FriendsWhoFavorited: _,
    Workshop_ItemTooltip_FriendsWhoFavorited_Plural: _,
    SharedFiles_TF2_Tab_Items_ReadyToUse: _,
    SharedFiles_TF2_Tab_Items_Mtx: _,
    SharedFiles_Dota2_Tab_Items_ReadyToUse: _,
    SharedFiles_Dota2_Tab_Items_Mtx: _,
    SharedFiles_Dota2_HeroPicker: _,
    SharedFiles_CSGO_Tab_Items_ReadyToUse: _,
    SharedFiles_CSGO_Tab_Items_Mtx: _,
  };
export {
  _ as Error_Encountered,
  _ as Error_Sorry,
  _ as Error_TooManyRequests_Description,
  _ as Header_App_WorkshopTitle,
  _ as Header_WorkshopTitle,
  _ as SharedFiles_Browse_Trend_Option_AllTime,
  _ as SharedFiles_Browse_Trend_Option_Month,
  _ as SharedFiles_Browse_Trend_Option_OneYear,
  _ as SharedFiles_Browse_Trend_Option_SixMonths,
  _ as SharedFiles_Browse_Trend_Option_ThreeMonths,
  _ as SharedFiles_Browse_Trend_Option_Today,
  _ as SharedFiles_Browse_Trend_Option_Week,
  _ as SharedFiles_CSGO_Tab_Items_Mtx,
  _ as SharedFiles_CSGO_Tab_Items_ReadyToUse,
  _ as SharedFiles_Dota2_HeroPicker,
  _ as SharedFiles_Dota2_Tab_Items_Mtx,
  _ as SharedFiles_Dota2_Tab_Items_ReadyToUse,
  _ as SharedFiles_TF2_Tab_Items_Mtx,
  _ as SharedFiles_TF2_Tab_Items_ReadyToUse,
  _ as Workshop_About,
  _ as Workshop_About_EnabledFeatures,
  _ as Workshop_About_EnabledFeatures_Desc,
  _ as Workshop_About_Feature_AuthorRoyalties,
  _ as Workshop_About_Feature_AuthorRoyalties_Desc,
  _ as Workshop_About_Feature_Branch_Versioning,
  _ as Workshop_About_Feature_Branch_Versioning_Desc,
  _ as Workshop_About_Feature_Commerce,
  _ as Workshop_About_Feature_Commerce_Desc,
  _ as Workshop_About_Feature_ItemCuration,
  _ as Workshop_About_Feature_ItemCuration_Desc,
  _ as Workshop_About_Feature_ItemCuration_Mixed_Desc,
  _ as Workshop_About_Feature_ItemMtx,
  _ as Workshop_About_Feature_ItemMtx_Desc,
  _ as Workshop_About_Feature_ReadyToUse,
  _ as Workshop_About_Feature_ReadyToUse_Desc,
  _ as Workshop_About_Feature_ReadyToUse_Mixed_Desc,
  _ as Workshop_About_Feature_ServiceProviders,
  _ as Workshop_About_Feature_ServiceProviders_Desc,
  _ as Workshop_About_FindGuides,
  _ as Workshop_About_FindGuides_Sub,
  _ as Workshop_About_NumAcceptedItems,
  _ as Workshop_About_NumItems,
  _ as Workshop_About_PageDesc_Curation,
  _ as Workshop_About_PageDesc_ReadyToUseContent1,
  _ as Workshop_About_PageDesc_ReadyToUseContent2,
  _ as Workshop_About_PageDesc_ReadyToUseContent_Mixed1,
  _ as Workshop_About_PageDesc_ReadyToUseContent_Mixed2,
  _ as Workshop_About_RefundLink_Sub,
  _ as Workshop_About_RelatedLinks,
  _ as Workshop_About_Request_ServiceProviders,
  _ as Workshop_About_RevenueShare,
  _ as Workshop_About_RevenueShare_Desc,
  _ as Workshop_About_RevenueShare_Here,
  _ as Workshop_About_RevenueShare_Link,
  _ as Workshop_About_ViewOfficialDocs,
  _ as Workshop_About_WorkshopTerms,
  _ as Workshop_About_WorkshopTerms_Sub,
  _ as Workshop_About_section_ServiceProviders,
  _ as Workshop_AcceptedForGame,
  _ as Workshop_AcceptedMerch,
  _ as Workshop_Admin_View,
  _ as Workshop_ApplyFilters,
  _ as Workshop_BrowseSort_AcceptedTime,
  _ as Workshop_BrowseSort_AdminOption,
  _ as Workshop_BrowseSort_BanContentCheck,
  _ as Workshop_BrowseSort_Combined,
  _ as Workshop_BrowseSort_CuratedAdmin,
  _ as Workshop_BrowseSort_Inappropriate,
  _ as Workshop_BrowseSort_LastUpdated,
  _ as Workshop_BrowseSort_MostPopular,
  _ as Workshop_BrowseSort_MostRecent,
  _ as Workshop_BrowseSort_MostUpVotes,
  _ as Workshop_BrowseSort_Nominee,
  _ as Workshop_BrowseSort_NumParentCollections,
  _ as Workshop_BrowseSort_NumParentItems,
  _ as Workshop_BrowseSort_Playtime,
  _ as Workshop_BrowseSort_PlaytimeAverage,
  _ as Workshop_BrowseSort_PlaytimeAverageTotal,
  _ as Workshop_BrowseSort_PlaytimeSessions,
  _ as Workshop_BrowseSort_PlaytimeSessionsTotal,
  _ as Workshop_BrowseSort_PlaytimeTotal,
  _ as Workshop_BrowseSort_Rated,
  _ as Workshop_BrowseSort_Reported,
  _ as Workshop_BrowseSort_SearchRelevance,
  _ as Workshop_BrowseSort_SortOrder,
  _ as Workshop_BrowseSort_TimeFrame,
  _ as Workshop_BrowseSort_ToRate,
  _ as Workshop_BrowseSort_TopRated,
  _ as Workshop_BrowseSort_TotalUniqueSubscribers,
  _ as Workshop_BrowseSort_TotalVotes,
  _ as Workshop_Browse_Author_Link,
  _ as Workshop_Browsing,
  _ as Workshop_Browsing_Merchandise_Desc,
  _ as Workshop_Browsing_Mtx_Desc,
  _ as Workshop_Browsing_ReadyToUse_Desc,
  _ as Workshop_Collection_NumChildCollections,
  _ as Workshop_Collection_NumChildCollections_Plural,
  _ as Workshop_Collection_NumChildItems,
  _ as Workshop_Collection_NumChildItems_Plural,
  _ as Workshop_Collection_SaveToCollection,
  _ as Workshop_Collection_SubscribeToAll,
  _ as Workshop_Collection_UnsubscribeFromAll,
  _ as Workshop_Collection_ViewMore,
  _ as Workshop_CreateCollection,
  _ as Workshop_CreateMerchandise,
  _ as Workshop_DateFilter_And,
  _ as Workshop_DateFilter_Between,
  _ as Workshop_DateFilter_FilterByDate,
  _ as Workshop_DateFilter_TimeCreated,
  _ as Workshop_DateFilter_TimeCreated_After,
  _ as Workshop_DateFilter_TimeCreated_Before,
  _ as Workshop_DateFilter_TimeCreated_Between,
  _ as Workshop_DateFilter_TimeUpdated,
  _ as Workshop_DateFilter_TimeUpdated_After,
  _ as Workshop_DateFilter_TimeUpdated_Before,
  _ as Workshop_DateFilter_TimeUpdated_Between,
  _ as Workshop_Dialog_AccessDenied,
  _ as Workshop_Dialog_AddToCollection,
  _ as Workshop_Dialog_AddToCollection_Create,
  _ as Workshop_Dialog_AddToCollection_Desc,
  _ as Workshop_Dialog_AddToCollection_NoSavedCollections_Desc,
  _ as Workshop_Dialog_AddToCollection_OK,
  _ as Workshop_Dialog_CollectionSubscribe,
  _ as Workshop_Dialog_CollectionSubscribe_AddOnly,
  _ as Workshop_Dialog_CollectionSubscribe_Desc,
  _ as Workshop_Dialog_CollectionSubscribe_Overwrite,
  _ as Workshop_Dialog_Error,
  _ as Workshop_Dialog_ErrorDesc,
  _ as Workshop_Dialog_ItemDependencies,
  _ as Workshop_Dialog_ItemDependencies_Desc1,
  _ as Workshop_Dialog_ItemDependencies_Desc1_itemName,
  _ as Workshop_Dialog_ItemDependencies_Desc2,
  _ as Workshop_Dialog_ItemDependencies_Desc3,
  _ as Workshop_Dialog_LimitExceeded,
  _ as Workshop_Dialog_Report,
  _ as Workshop_Dialog_Report_DMCA_Desc,
  _ as Workshop_Dialog_Report_Desc,
  _ as Workshop_Dialog_Report_Here,
  _ as Workshop_Dialog_Report_Reason,
  _ as Workshop_Dialog_Report_Reason_Desc,
  _ as Workshop_Dialog_Report_Trademark_Desc,
  _ as Workshop_Dialog_SaveCollectionToCollection,
  _ as Workshop_Dialog_SaveCollectionToCollection_Desc,
  _ as Workshop_Dialog_SaveCollectionToCollection_Existing,
  _ as Workshop_Dialog_SaveCollectionToCollection_New,
  _ as Workshop_Dialog_SaveCollectionToCollection_NewPrompt,
  _ as Workshop_Dialog_SaveCollectionToCollection_Select,
  _ as Workshop_Dialog_SubscribeAll,
  _ as Workshop_Dialog_SubscribeJustThisItem,
  _ as Workshop_Dialog_Timeout,
  _ as Workshop_DimmedItems_BlockedCreators,
  _ as Workshop_DimmedItems_Reported,
  _ as Workshop_DimmedItems_Subscribed,
  _ as Workshop_DimmedItems_Title,
  _ as Workshop_DimmedItems_VotedDown,
  _ as Workshop_DimmedItems_VotedUp,
  _ as Workshop_Error_Browse_Desc,
  _ as Workshop_Error_Loading,
  _ as Workshop_Error_Title,
  _ as Workshop_ExcludeOwnedDLC_Filter,
  _ as Workshop_ExitReact_Link,
  _ as Workshop_FiltersMenu_State_Collapsed,
  _ as Workshop_FiltersMenu_State_Left,
  _ as Workshop_FiltersMenu_State_Right,
  _ as Workshop_FiltersMenu_State_Title,
  _ as Workshop_Filters_ClearBtn,
  _ as Workshop_Flag_Incompatible_Checkbox,
  _ as Workshop_Flag_Incompatible_Checkbox_Desc,
  _ as Workshop_GamepadUIAction_QuickView,
  _ as Workshop_GamepadUIAction_ViewDetails,
  _ as Workshop_Home_AcceptedItems,
  _ as Workshop_Home_AcceptedItems_Btn,
  _ as Workshop_Home_AcceptedItems_Desc,
  _ as Workshop_Home_FriendsFavorites,
  _ as Workshop_Home_FriendsFavorites_Btn,
  _ as Workshop_Home_FriendsFavorites_Desc,
  _ as Workshop_Home_FromFollowedAuthors,
  _ as Workshop_Home_FromFollowedAuthors_Btn,
  _ as Workshop_Home_FromFollowedAuthors_Desc,
  _ as Workshop_Home_LastUpdated,
  _ as Workshop_Home_LastUpdated_Btn,
  _ as Workshop_Home_LastUpdated_Desc,
  _ as Workshop_Home_MostPlaytime,
  _ as Workshop_Home_MostPlaytime_Btn,
  _ as Workshop_Home_MostPopular,
  _ as Workshop_Home_MostPopularMerch,
  _ as Workshop_Home_MostPopularMerch_Btn,
  _ as Workshop_Home_MostPopular_LongTerm,
  _ as Workshop_Home_MostPopular_LongTerm_Btn,
  _ as Workshop_Home_MostPopular_LongTerm_Desc,
  _ as Workshop_Home_MostPopular_SubTitle_Month,
  _ as Workshop_Home_MostPopular_SubTitle_SixMonths,
  _ as Workshop_Home_MostPopular_SubTitle_ThreeMonths,
  _ as Workshop_Home_MostPopular_SubTitle_Week,
  _ as Workshop_Home_MostPopular_SubTitle_Year,
  _ as Workshop_Home_MostRecent,
  _ as Workshop_Home_MostRecent_Btn,
  _ as Workshop_Home_MostRecent_Desc,
  _ as Workshop_Home_MostSubscribed,
  _ as Workshop_Home_MostSubscribed_Btn,
  _ as Workshop_Home_MostSubscribed_Desc,
  _ as Workshop_Home_NumParentItems,
  _ as Workshop_Home_NumParentItems_Btn,
  _ as Workshop_Home_NumParentItems_Desc,
  _ as Workshop_Home_SpecialEvent_Link,
  _ as Workshop_Home_SpecialEvent_Title_Tag,
  _ as Workshop_Home_ViewAll,
  _ as Workshop_Home_VotingQueue,
  _ as Workshop_Home_VotingQueue_Btn,
  _ as Workshop_Home_VotingQueue_Count,
  _ as Workshop_Home_VotingQueue_Count_Plural,
  _ as Workshop_Home_VotingQueue_Desc,
  _ as Workshop_Home_YourFavorites,
  _ as Workshop_Home_YourFavorites_Btn,
  _ as Workshop_Home_YourFiles_LastUpdated,
  _ as Workshop_Home_YourPlayed,
  _ as Workshop_Home_YourPlayed_Btn,
  _ as Workshop_Home_YourSubscriptions,
  _ as Workshop_Home_YourSubscriptions_Btn,
  _ as Workshop_IncludeOwnedDLC_Filter,
  _ as Workshop_ItemDetails_AddToCollection,
  _ as Workshop_ItemDetails_AddToCollection_TT,
  _ as Workshop_ItemDetails_Award_TT,
  _ as Workshop_ItemDetails_Categories_Title,
  _ as Workshop_ItemDetails_CreatedBy,
  _ as Workshop_ItemDetails_DependentItems,
  _ as Workshop_ItemDetails_Description_Title,
  _ as Workshop_ItemDetails_Favorite,
  _ as Workshop_ItemDetails_Favorite_TT,
  _ as Workshop_ItemDetails_Favorited,
  _ as Workshop_ItemDetails_FileSize,
  _ as Workshop_ItemDetails_InCollections,
  _ as Workshop_ItemDetails_InCollectionsByAuthor,
  _ as Workshop_ItemDetails_ItemDependencies,
  _ as Workshop_ItemDetails_NotEnoughRatings,
  _ as Workshop_ItemDetails_NumRatings,
  _ as Workshop_ItemDetails_NumRatings_Plural,
  _ as Workshop_ItemDetails_ReactionCount,
  _ as Workshop_ItemDetails_ReactionCount_Plural,
  _ as Workshop_ItemDetails_Report_TT,
  _ as Workshop_ItemDetails_RequiredDLC_Desc,
  _ as Workshop_ItemDetails_SaveCollectionToCollection,
  _ as Workshop_ItemDetails_ShowAllReactions,
  _ as Workshop_ItemDetails_Signin_TT,
  _ as Workshop_ItemDetails_Stats_CurrentFavorites,
  _ as Workshop_ItemDetails_Stats_CurrentSubscribers,
  _ as Workshop_ItemDetails_Stats_LifetimeFavorites,
  _ as Workshop_ItemDetails_Stats_LifetimePlaytimeSessions,
  _ as Workshop_ItemDetails_Stats_LifetimeSubscribers,
  _ as Workshop_ItemDetails_Stats_UniqueVisitors,
  _ as Workshop_ItemDetails_Subscribe,
  _ as Workshop_ItemDetails_Subscribe_TT,
  _ as Workshop_ItemDetails_Subscribed,
  _ as Workshop_ItemDetails_Tab_ChangeNotes,
  _ as Workshop_ItemDetails_Tab_Comments,
  _ as Workshop_ItemDetails_Tab_Description,
  _ as Workshop_ItemDetails_Tab_Discussions,
  _ as Workshop_ItemDetails_Tab_Stats,
  _ as Workshop_ItemDetails_Tab_Updates,
  _ as Workshop_ItemDetails_Tags_Title,
  _ as Workshop_ItemDetails_TimestampCreated,
  _ as Workshop_ItemDetails_TimestampUpdated,
  _ as Workshop_ItemDetails_TimestampWithTime,
  _ as Workshop_ItemDetails_Title,
  _ as Workshop_ItemDetails_Unfavorite,
  _ as Workshop_ItemDetails_Unsubscribe,
  _ as Workshop_ItemDetails_Unsubscribe_TT,
  _ as Workshop_ItemDetails_ViewDependentItems,
  _ as Workshop_ItemDetails_ViewDependentItems_TT,
  _ as Workshop_ItemTooltip_FriendsWhoFavorited,
  _ as Workshop_ItemTooltip_FriendsWhoFavorited_Plural,
  _ as Workshop_Item_QuickView,
  _ as Workshop_Item_QuickView_ExpandBtn,
  _ as Workshop_LearnMore,
  _ as Workshop_Menu_About,
  _ as Workshop_Menu_Browse,
  _ as Workshop_Menu_Discussions,
  _ as Workshop_Menu_Home,
  _ as Workshop_Menu_Search,
  _ as Workshop_Menu_YourItems,
  _ as Workshop_NumPerPage,
  _ as Workshop_NumResults,
  _ as Workshop_NumResults_Plural,
  _ as Workshop_OfficialContent,
  _ as Workshop_OwnedDLC_All_Filter,
  _ as Workshop_OwnedDLC_More_Filter,
  _ as Workshop_OwnedDLC_None_Filter,
  _ as Workshop_PagingControls,
  _ as Workshop_RequireApproval,
  _ as Workshop_RequiredDLC_ExcludeUnowned,
  _ as Workshop_RequiredDLC_Filter,
  _ as Workshop_RequiredDLC_Header,
  _ as Workshop_RequiredDLC_IncludeOwned,
  _ as Workshop_RequiredDLC_NameFilter,
  _ as Workshop_Saved_Queries,
  _ as Workshop_Saved_Queries_Delete_Btn,
  _ as Workshop_Saved_Queries_Delete_Desc,
  _ as Workshop_Saved_Queries_Delete_Title,
  _ as Workshop_Saved_Queries_Save_Btn,
  _ as Workshop_Saved_Queries_Save_Desc,
  _ as Workshop_Saved_Queries_Save_Desc_Long,
  _ as Workshop_Saved_Queries_Save_New,
  _ as Workshop_Saved_Queries_Save_Title,
  _ as Workshop_Saved_Queries_Update,
  _ as Workshop_SearchResults_Flag_Accepted,
  _ as Workshop_SearchResults_Flag_Incompatible,
  _ as Workshop_SearchResults_KVTag,
  _ as Workshop_SearchResults_SearchText,
  _ as Workshop_SearchResults_SearchText_DescriptionOnly,
  _ as Workshop_SearchResults_SearchText_TitleOnly,
  _ as Workshop_SearchResults_Tag,
  _ as Workshop_SearchTarget_All,
  _ as Workshop_SearchTarget_Description,
  _ as Workshop_SearchTarget_MenuTitle,
  _ as Workshop_SearchTarget_Title,
  _ as Workshop_Search_Help,
  _ as Workshop_Search_Help_Advanced,
  _ as Workshop_Search_Help_AdvancedExample1,
  _ as Workshop_Search_Help_AdvancedExample2,
  _ as Workshop_Search_Help_Example1,
  _ as Workshop_Search_Help_Example2,
  _ as Workshop_Search_Help_Example3,
  _ as Workshop_Search_Help_Example_Blue,
  _ as Workshop_Search_Help_Example_Green,
  _ as Workshop_Search_Help_Example_Red,
  _ as Workshop_Search_Help_Example_Room,
  _ as Workshop_SearchedForChild,
  _ as Workshop_SearchedForRequiredItem,
  _ as Workshop_Section_Collections,
  _ as Workshop_Section_Merchandise,
  _ as Workshop_Section_Mtx,
  _ as Workshop_Section_ReadyToUse,
  _ as Workshop_Section_Videos,
  _ as Workshop_ServiceProviderRevenueSharing_ViewSite,
  _ as Workshop_ServiceProviderRevenueSharing_ViewSteamProfile,
  _ as Workshop_ServiceProvider_Category_Communities,
  _ as Workshop_ServiceProvider_Category_Tools,
  _ as Workshop_ServiceProvider_Category_Users,
  _ as Workshop_SortBy,
  _ as Workshop_SpecialFilter_AcceptedForUse,
  _ as Workshop_SpecialFilter_CreatedByFollowed,
  _ as Workshop_SpecialFilter_CreatedByFriends,
  _ as Workshop_SpecialFilter_Desc,
  _ as Workshop_SpecialFilter_FavoritedByFriends,
  _ as Workshop_SpecialFilter_None,
  _ as Workshop_SpecialFilter_ParentCollections,
  _ as Workshop_SpecialFilter_ParentItems,
  _ as Workshop_SpecialFilter_Reported,
  _ as Workshop_StatusIcon_TT_Accepted,
  _ as Workshop_StatusIcon_TT_BlockedCreator,
  _ as Workshop_StatusIcon_TT_Favorited,
  _ as Workshop_StatusIcon_TT_Incompatible,
  _ as Workshop_StatusIcon_TT_Played,
  _ as Workshop_StatusIcon_TT_Reported,
  _ as Workshop_StatusIcon_TT_Subscribed,
  _ as Workshop_StatusIcon_TT_VotedDown,
  _ as Workshop_StatusIcon_TT_VotedUp,
  _ as Workshop_SubMenu_LegalAgreement,
  _ as Workshop_SubMenu_ViewYourRevenue,
  _ as Workshop_SubMenu_ViewYourRevenue_Desc,
  _ as Workshop_SubMenu_VotingQueue,
  _ as Workshop_SubMenu_YourCollections,
  _ as Workshop_SubMenu_YourFavorites,
  _ as Workshop_SubMenu_YourItems,
  _ as Workshop_SubMenu_YourPaymentInfo,
  _ as Workshop_SubMenu_YourPlayed,
  _ as Workshop_SubMenu_YourSubscriptions,
  _ as Workshop_SubMenu_YourVotingQueue,
  _ as Workshop_Tag_NoneSpecified,
  _ as default,
  _ as language,
};
