var _ = `danish`,
  _ = `Oprindeligt skrevet af %1$s:`,
  _ = `{LINK FJERNET}`,
  _ = `URL'en, der blev linket herfra, er blevet fjernet af vores filtre. Normalt sker dette for at beskytte mod phishing og malwareangreb.`,
  _ = `(Kun Valve/moderator) Klik for at afsløre link`,
  _ = `%1$s kommentarer`,
  _ = `Viser %1$s-%2$s af %3$s kommentarer`,
  _ = `Tilføj en kommentar`,
  _ = `Send kommentar`,
  _ = `Formateringshjælp`,
  _ = `Indsæt emotikon`,
  _ = `%1$s-emotikon`,
  _ = `Søg`,
  _ = `Senest anvendt`,
  _ = `Alle emotikoner`,
  _ = `Ingen emotikoner matcher din søgning.`,
  _ = `Du ejer ikke nogen emotikoner endnu.`,
  _ = `Tekstformatering`,
  _ = `Disse markeringstags gør dig i stand til at føje formatering til dine kommentarer og indlæg, i lighed med HTML.`,
  _ = `Syntaks`,
  _ = `Eksempel`,
  _ = `Fed skrift`,
  _ = `Understreget skrift`,
  _ = `Kursiv skrift`,
  _ = `Gennemstreget tekst`,
  _ = `Spoilertekst`,
  _ = `Fortolker ikke [b]tags[/b] `,
  _ = `Websitelink`,
  _ = `Citeret tekst`,
  _ = `Skrift med fast bredde,
bevarer    mellemrum`,
  _ = `Sidehovedtekst`,
  _ = `Sidehovedtekst`,
  _ = `Sidehovedtekst`,
  _ = `Listepunkt`,
  _ = `Sorteret liste`,
  _ = `Abonner på tråd`,
  _ = `Opsig abonnement på kommentarer`,
  _ = `Abonner på en tråd for at modtage notifikationer, når nogen skriver en ny kommentar.`,
  _ = `Du blev automatisk abonneret på denne tråd, fordi den er associeret med din Steam-profil.`,
  _ = `Der opstod et problem med opdatering af dit abonnement. Prøv venligst igen senere.`,
  _ = `Slet`,
  _ = `Skjul og rapportér denne kommentar`,
  _ = `Marker som mistænkeligt`,
  _ = `Fjern markeringen "Forbudt indhold": %1$s`,
  _ = `Ikke scannet`,
  _ = `Nulstil`,
  _ = `Skal kontrolleres`,
  _ = `Meget usandsynligt`,
  _ = `Usandsynligt`,
  _ = `Muligt`,
  _ = `Sandsynligt`,
  _ = `Meget sandsynligt`,
  _ = `Ukendt (%1$s)`,
  _ = `Åbn i moderatorværktøj`,
  _ = `Du har rapporteret denne kommentar`,
  _ = `Du har blokeret denne spiller`,
  _ = `Fortryd`,
  _ = `vis denne kommentar`,
  _ = `Du kan se det på grund af dine support-/moderatortilladelser.`,
  _ = `Denne kommentar afventer at blive analyseret af vores automatiske indholdskontrolsystem. Den er midlertidigt skjult, indtil vi bekræfter, at indholdet ikke er skadeligt (f.eks. links til websider, som forsøger at stjæle oplysninger).`,
  _ = `Denne kommentar er automatisk blevet markeret på grund af potentielt skadeligt indhold og er blevet skjult som følge deraf.`,
  _ = `Normalt ville du ikke kunne skrive en kommentar her, men du har yderligere rettigheder, som giver dig tilladelse til det.`,
  _ = `Denne kommentar blev slettet.`,
  _ = `Din kommentar er for kort.`,
  _ = `Din kommentar er for lang. Den maksimale længde er %1$s tegn.`,
  _ = `Du har ikke tilladelse til at skrive en kommentar her.`,
  _ = `Du skal være logget ind for at skrive en kommentar.`,
  _ = `Du skal eje dette spil for at kunne kommentere på denne genstand.`,
  _ = `Du skal have mindst en times spilletid, før du kan skrive en kommentar.`,
  _ = `Kommentarer er deaktiveret for denne genstand.`,
  _ = `Der er ingen kommentarer endnu.`,
  _ = {
    language: _,
    CommentThread_QuoteBlock_Author: _,
    CommentThread_RemovedLink: _,
    CommentThread_RemovedLink_Tooltip: _,
    CommentThread_RemovedLink_Reveal: _,
    CommentThread_NumberOfComments: _,
    CommentThread_ShowingXToYOfTotal: _,
    CommentThread_AddAComment: _,
    CommentThread_PostComment: _,
    CommentThread_FormattingHelp: _,
    CommentThread_InsertEmoticon: _,
    CommentThread_EmoticonHoverApp: _,
    CommentThread_EmoticonSearch: _,
    CommentThread_EmoticonRecentlyUsed: _,
    CommentThread_EmoticonAll: _,
    CommentThread_EmoticonNoResults: _,
    CommentThread_EmoticonNoneOwned: _,
    CommentThread_FormattingHelpHeader: _,
    Discussions_FormattingHelp_Description: _,
    Discussions_FormattingHelp_ColumnSyntax: _,
    Discussions_FormattingHelp_ColumnExample: _,
    Discussions_FormattingHelp_Bold: _,
    Discussions_FormattingHelp_Underline: _,
    Discussions_FormattingHelp_Italic: _,
    Discussions_FormattingHelp_Strike: _,
    Discussions_FormattingHelp_Spoiler: _,
    Discussions_FormattingHelp_Noparse: _,
    Discussions_FormattingHelp_Link: _,
    Discussions_FormattingHelp_Quote: _,
    Discussions_FormattingHelp_Code: _,
    Discussions_FormattingHelp_H1: _,
    Discussions_FormattingHelp_H2: _,
    Discussions_FormattingHelp_H3: _,
    Discussions_FormattingHelp_List: _,
    Discussions_FormattingHelp_OList: _,
    CommentThread_Subscribe: _,
    CommentThread_Unsubscribe: _,
    CommentThread_SubscribeHint: _,
    CommentThread_SubscribeHintOwnThread: _,
    CommentThread_SubscribeError: _,
    CommentThread_DeleteComment: _,
    CommentThread_HideComment: _,
    CommentThread_MarkSpam: _,
    CommentThread_ClearContentCheck: _,
    BanContentCheckResult_NotScanned: _,
    BanContentCheckResult_Reset: _,
    BanContentCheckResult_NeedsChecking: _,
    BanContentCheckResult_VeryUnlikely: _,
    BanContentCheckResult_Unlikely: _,
    BanContentCheckResult_Possible: _,
    BanContentCheckResult_Likely: _,
    BanContentCheckResult_VeryLikely: _,
    BanContentCheckResult_Unknown: _,
    CommentThread_ModerationTool: _,
    CommentThread_HiddenByUser: _,
    CommentThread_HiddenByBlocked: _,
    CommentThread_HiddenUndo: _,
    CommentThread_HiddenViewComment: _,
    CommentThread_ModeratorViewContent: _,
    CommentThread_NeedsContentCheck: _,
    CommentThread_FailedContentCheck: _,
    CommentThread_PermissionOverride: _,
    CommentThread_Deleted: _,
    CommentThread_PostError_TooShort: _,
    CommentThread_PostError_TooLong: _,
    CommentThread_PostError_NotAllowed: _,
    CommentThread_PostError_NotLoggedIn: _,
    CommentThread_PostError_MustOwnApp: _,
    CommentThread_PostError_LimitedUser: _,
    CommentThread_CommentsDisabled: _,
    CommentThread_NoComments: _,
  };
export {
  _ as BanContentCheckResult_Likely,
  _ as BanContentCheckResult_NeedsChecking,
  _ as BanContentCheckResult_NotScanned,
  _ as BanContentCheckResult_Possible,
  _ as BanContentCheckResult_Reset,
  _ as BanContentCheckResult_Unknown,
  _ as BanContentCheckResult_Unlikely,
  _ as BanContentCheckResult_VeryLikely,
  _ as BanContentCheckResult_VeryUnlikely,
  _ as CommentThread_AddAComment,
  _ as CommentThread_ClearContentCheck,
  _ as CommentThread_CommentsDisabled,
  _ as CommentThread_DeleteComment,
  _ as CommentThread_Deleted,
  _ as CommentThread_EmoticonAll,
  _ as CommentThread_EmoticonHoverApp,
  _ as CommentThread_EmoticonNoResults,
  _ as CommentThread_EmoticonNoneOwned,
  _ as CommentThread_EmoticonRecentlyUsed,
  _ as CommentThread_EmoticonSearch,
  _ as CommentThread_FailedContentCheck,
  _ as CommentThread_FormattingHelp,
  _ as CommentThread_FormattingHelpHeader,
  _ as CommentThread_HiddenByBlocked,
  _ as CommentThread_HiddenByUser,
  _ as CommentThread_HiddenUndo,
  _ as CommentThread_HiddenViewComment,
  _ as CommentThread_HideComment,
  _ as CommentThread_InsertEmoticon,
  _ as CommentThread_MarkSpam,
  _ as CommentThread_ModerationTool,
  _ as CommentThread_ModeratorViewContent,
  _ as CommentThread_NeedsContentCheck,
  _ as CommentThread_NoComments,
  _ as CommentThread_NumberOfComments,
  _ as CommentThread_PermissionOverride,
  _ as CommentThread_PostComment,
  _ as CommentThread_PostError_LimitedUser,
  _ as CommentThread_PostError_MustOwnApp,
  _ as CommentThread_PostError_NotAllowed,
  _ as CommentThread_PostError_NotLoggedIn,
  _ as CommentThread_PostError_TooLong,
  _ as CommentThread_PostError_TooShort,
  _ as CommentThread_QuoteBlock_Author,
  _ as CommentThread_RemovedLink,
  _ as CommentThread_RemovedLink_Reveal,
  _ as CommentThread_RemovedLink_Tooltip,
  _ as CommentThread_ShowingXToYOfTotal,
  _ as CommentThread_Subscribe,
  _ as CommentThread_SubscribeError,
  _ as CommentThread_SubscribeHint,
  _ as CommentThread_SubscribeHintOwnThread,
  _ as CommentThread_Unsubscribe,
  _ as Discussions_FormattingHelp_Bold,
  _ as Discussions_FormattingHelp_Code,
  _ as Discussions_FormattingHelp_ColumnExample,
  _ as Discussions_FormattingHelp_ColumnSyntax,
  _ as Discussions_FormattingHelp_Description,
  _ as Discussions_FormattingHelp_H1,
  _ as Discussions_FormattingHelp_H2,
  _ as Discussions_FormattingHelp_H3,
  _ as Discussions_FormattingHelp_Italic,
  _ as Discussions_FormattingHelp_Link,
  _ as Discussions_FormattingHelp_List,
  _ as Discussions_FormattingHelp_Noparse,
  _ as Discussions_FormattingHelp_OList,
  _ as Discussions_FormattingHelp_Quote,
  _ as Discussions_FormattingHelp_Spoiler,
  _ as Discussions_FormattingHelp_Strike,
  _ as Discussions_FormattingHelp_Underline,
  _ as default,
  _ as language,
};
