var _ = `Cerca nel Mercato della Comunità`,
  _ = `Ripristina filtri`,
  _ = `Ricerca`,
  _ = `Scegli un gioco...`,
  _ = `I titoli con oggetti a cui hai giocato di recente`,
  _ = `Giochi popolari con oggetti`,
  _ = `Cancella selezione`,
  _ = `Cerca...`,
  _ = `Cerca in %1$s...`,
  _ = `Oggetti di gioco`,
  _ = `Oggetti di Steam`,
  _ = `Tipo di oggetto`,
  _ = `Questo gioco non ha filtri per il Mercato.`,
  _ = `Clicca su "Cerca" per vedere gli oggetti disponibili.`,
  _ = `Si è verificato un problema durante il caricamento dei filtri per questo gioco.`,
  _ = `Prezzo`,
  _ = `Prezzo min`,
  _ = `Prezzo max`,
  _ = `Tutti`,
  _ = `Altri`,
  _ = `Filtra...`,
  _ = `Filtra per gioco...`,
  _ = `Funzionalità beta - Fornisci un feedback`,
  _ = `Cerca tra i nomi degli oggetti del Mercato...`,
  _ = `Casse di armi, capsule degli adesivi, pacchetti di souvenir ecc.`,
  _ = `Mercato della Comunità di Steam`,
  _ = `Acquista e vendi oggetti ad altri membri della Comunità per ricevere fondi del Portafoglio di Steam`,
  _ = `Ulteriori informazioni`,
  _ = `Cerca nel Mercato`,
  _ = `Nuova ricerca...`,
  _ = `Filtri`,
  _ = `Esci dalla beta del Mercato`,
  _ = `Invia un suggerimento`,
  _ = `Le singole copie di questo oggetto in vendita sono identiche. Non essendo le singole inserzioni visibili, puoi creare ordini per un prezzo specifico. Gli oggetti messi in vendita al prezzo più accessibile verranno associati automaticamente agli ordini d'acquisto col prezzo più alto.`,
  _ = `%1$s risultato trovato`,
  _ = `%1$s risultati trovati`,
  _ = `%1$s risultato trovato per:`,
  _ = `%1$s risultati trovati per:`,
  _ = `Risultati per:`,
  _ = `%2$s inserzione trovata`,
  _ = `%2$s inserzioni trovate`,
  _ = `Popolarità`,
  _ = `Nome (dalla A alla Z)`,
  _ = `Nome (dalla Z alla A)`,
  _ = `Prezzo (crescente)`,
  _ = `Prezzo (decrescente)`,
  _ = `Quantità (crescente)`,
  _ = `Quantità (decrescente)`,
  _ = `%1$s (crescente)`,
  _ = `%1$s (decrescente)`,
  _ = `Ordina per:`,
  _ = `Ricerca`,
  _ = `Cerca...`,
  _ = `Acquista`,
  _ = `Vendi`,
  _ = `Acquista ora`,
  _ = `Effettua ordine d'acquisto...`,
  _ = `Effettua un ordine:`,
  _ = `Chiudi`,
  _ = `Quantità in vendita: %1$s`,
  _ = `Quantità: %1$s`,
  _ = `Da %1$s`,
  _ = `%1$s applicato`,
  _ = `Filtra risultati...`,
  _ = `Ricerca avanzata`,
  _ = `Ricerca avanzata`,
  _ = `Cerca un oggetto...`,
  _ = `Pagina iniziale del Mercato`,
  _ = `Giochi popolari`,
  _ = `Includi le descrizioni nella ricerca`,
  _ = `Alcuni articoli più vecchi utilizzano descrizioni testuali per le proprietà significative degli articoli stessi che non sono accessibili con i filtri sottostanti. Questa opzione farà sì che il testo della tua ricerca venga confrontato con il testo presente nella descrizione completa, anziché con il solo nome dell'articolo.`,
  _ = `Filtri`,
  _ = `Azzera ricerca`,
  _ = `Inserisci filtro di testo personalizzato...`,
  _ = `Dopo l'acquisto, questo oggetto:`,
  _ = `non sarà scambiabile per un giorno`,
  _ = `non sarà scambiabile per una settimana`,
  _ = `non sarà scambiabile per %1$s giorni`,
  _ = `non sarà scambiabile`,
  _ = `non potrà essere messo in vendita sul Mercato della Comunità di Steam per un giorno`,
  _ = `non potrà essere messo in vendita sul Mercato della Comunità di Steam per una settimana`,
  _ = `non potrà essere messo in vendita sul Mercato della Comunità di Steam per %1$s giorni`,
  _ = `può essere rivenduto immediatamente sul Mercato della Comunità di Steam`,
  _ = `%1$s: %2$s - %3$s`,
  _ = `%1$s: "%2$s"`,
  _ = `Acquista un oggetto`,
  _ = `Titolo`,
  _ = `Prezzo`,
  _ = `Subtotale:`,
  _ = `Commissione per %1$s (%2$s%):`,
  _ = `Commissione del gioco (%1$s%):`,
  _ = `Commissione di transazione di Steam (%1$s%):`,
  _ = `Imposta locale sulle vendite (%1$s):`,
  _ = `Totale:`,
  _ = `Metodo di pagamento:`,
  _ = `Il mio Portafoglio di Steam`,
  _ = `Account di Steam:`,
  _ = `Indirizzo di fatturazione:`,
  _ = `Nome`,
  _ = `Cognome`,
  _ = `Indirizzo di fatturazione`,
  _ = `Indirizzo di fatturazione - riga 2`,
  _ = `Città`,
  _ = `Stato / Provincia`,
  _ = `CAP o codice postale`,
  _ = `Paese`,
  _ = `Salva il mio indirizzo per facilitare i prossimi acquisti`,
  _ = `Aggiungi fondi`,
  _ = `Acquisto`,
  _ = `Accetto i termini del %1$s (ultimo aggiornamento: %2$s)`,
  _ = `Contratto di sottoscrizione a Steam`,
  _ = `Devi accettare i termini del Contratto di Sottoscrizione a Steam per completare la transazione`,
  _ = `Facendo clic su "Acquista" accetti di ricevere accesso immediato a questo contenuto digitale e che non è possibile annullare l'acquisto. L'acquisto è definitivo.`,
  _ = `Si è verificato un problema durante l'acquisto dell'oggetto. L'inserzione potrebbe essere stata rimossa. Aggiorna la pagina e riprova.`,
  _ = `C'è stato un problema durante l'acquisto del tuo oggetto. Si è verificato un errore nell'attesa che tu confermassi questa azione. Aggiorna la pagina e riprova.`,
  _ = `I seguenti campi sono obbligatori:`,
  _ = `Immetti un indirizzo militare valido`,
  _ = `Inserisci un CAP o altro codice postale valido`,
  _ = `Congratulazioni per il tuo acquisto! Puoi vedere il tuo nuovo oggetto nel <1>tuo inventario</1>.`,
  _ = `Visualizza l'inventario`,
  _ = `È richiesta una conferma aggiuntiva`,
  _ = `In attesa che tu confermi questo acquisto...`,
  _ = `Alcuni acquisti richiedono un passaggio di sicurezza aggiuntivo tramite la tua app mobile di Steam.`,
  _ = `Alcuni acquisti richiedono un passaggio di sicurezza aggiuntivo tramite la tua e-mail di Steam Guard.`,
  _ = `Alcuni acquisti richiedono un passaggio di sicurezza aggiuntivo tramite la tua app mobile di Steam o tramite e-mail.`,
  _ = `Conferma tramite l'app mobile di Steam per completare l'acquisto...`,
  _ = `Conferma tramite e-mail per completare l'acquisto...`,
  _ = `Conferma tramite l'app mobile di Steam o l'e-mail per completare l'acquisto...`,
  _ = `Acquisto completato`,
  _ = `Chiudi`,
  _ = `Visualizza l'inventario`,
  _ = `Salva il mio indirizzo per rendere più veloci i prossimi acquisti`,
  _ = `Questa inserzione non è più disponibile`,
  _ = `Non disponibile`,
  _ = `Questa inserzione non è più disponibile per l'acquisto.`,
  _ = `(Il mio annuncio)`,
  _ = `Acquista - %1$s`,
  _ = `Crea l'ordine`,
  _ = `Quale tipo di articolo desideri acquistare?`,
  _ = `Seleziona un articolo...`,
  _ = `Quale prezzo vuoi pagare:`,
  _ = `(per oggetto)`,
  _ = `Quanti ne vuoi acquistare:`,
  _ = `Prezzo massimo %1$s:`,
  _ = `Questo è l'importo massimo che sei disposto a spendere per quest'ordine d'acquisto. Gli oggetti saranno acquistati al prezzo più basso possibile, quindi l'ordine potrebbe effettivamente costare meno di questa somma.`,
  _ = `Ricerca di inserzioni corrispondenti al prezzo desiderato...`,
  _ = `Acquisto riuscito! L'oggetto ora è nel tuo inventario e ti è stata mandata una ricevuta tramite e-mail.`,
  _ = `Operazione completata! Il tuo ordine d'acquisto è stato inserito.`,
  _ = `Riceverai una notifica automatica via e-mail quando il tuo acquisto sarà completo. Puoi annullare questo ordine d'acquisto in cima a questa pagina, o dalla pagina iniziale del Mercato.`,
  _ = `Siamo spiacenti! Abbiamo riscontrato un problema di comunicazione con i server di Steam riguardo al tuo ordine. Verifica se il tuo ordine è stato effettivamente creato o completato. Se non è così, allora ti invitiamo a riprovare più tardi.`,
  _ = `Il prezzo minimo per unità è di %1$s`,
  _ = `%1$s o meno`,
  _ = `%1$s o più`,
  _ = `Prezzo`,
  _ = `Quantità`,
  _ = `%1$s in vendita a partire da %2$s`,
  _ = `Non ci sono inserzioni attive per questo oggetto`,
  _ = `%1$s ordini a %2$s o meno`,
  _ = `Non ci sono ordini d'acquisto attivi per questo oggetto.`,
  _ = `Seleziona una scheda qui sopra per vedere le informazioni sull'ordine d'acquisto`,
  _ = `Non vedi l'articolo o il prezzo che cerchi?`,
  _ = `Nessun prezzo ti convince?`,
  _ = `Ordini e inserzioni (cumulativi)`,
  _ = `1 ordine d'acquisto a %2$s o più`,
  _ = `%1$s ordini d'acquisto a %2$s o più`,
  _ = `1 inserzione a %2$s o meno`,
  _ = `%1$s inserzioni a %2$s o meno`,
  _ = `1 richiesta d'acquisto a <1>%2$s</1>`,
  _ = `%3$s richieste di acquisto a <1>%2$s o meno</1>`,
  _ = `Prezzi di vendita mediani`,
  _ = `Settimana`,
  _ = `Mese`,
  _ = `Anno`,
  _ = `Totale`,
  _ = `%1$s venduti`,
  _ = `Prezzo`,
  _ = `Quantità`,
  _ = `Nessun dato per questo intervallo di tempo`,
  _ = `Nessun dato sugli acquisti`,
  _ = `N/D`,
  _ = `NOME`,
  _ = `PREZZO`,
  _ = `QUANTITÀ`,
  _ = `INSERITA IL GIORNO`,
  _ = `Annulla`,
  _ = `Rimuovi`,
  _ = `I miei ordini attivi`,
  _ = `Inserzioni`,
  _ = `Ordini d'acquisto`,
  _ = `Acquisti - Le mie offerte`,
  _ = `Vendite - I miei annunci`,
  _ = `Si è verificato un problema durante il caricamento dei dati dell'ordine per questo oggetto.`,
  _ = `Non hai ordini attivi per questo oggetto.`,
  _ = `Non hai ordini d'acquisto attivi per questo oggetto.`,
  _ = `Non stai vendendo alcuna copia di questo oggetto. Vendi gli oggetti dal tuo inventario, oppure clicca sul pulsante "Vendi" su questa pagina.`,
  _ = `Quantità: %1$s`,
  _ = `Vedi tutto (%1$s)`,
  _ = `Si è verificato un problema durante l'annullamento dell'ordine. Riprova più tardi.`,
  _ = `Si è verificato un problema durante la rimozione dell'inserzione. Riprova più tardi.`,
  _ = `Rimuovi un'inserzione`,
  _ = `Vuoi rimuovere l'inserzione di %1$s e rimettere l'oggetto nel tuo inventario?`,
  _ = `Vuoi rimuovere questa inserzione e rimettere l'oggetto nel tuo inventario?`,
  _ = `Sì, rimuovi l'inserzione`,
  _ = `No`,
  _ = `La tua inserzione è stata rimossa con successo`,
  _ = `Scegli un oggetto dal tuo inventario`,
  _ = `Cos'è un ordine d'acquisto?`,
  _ = `Imposta il prezzo che preferisci e l'acquisto verrà effettuato automaticamente quando l'oggetto sarà disponibile a quel prezzo.`,
  _ = `Steam ti garantirà il miglior prezzo disponibile.`,
  _ = `Per quest'oggetto gli ordini d'acquisto saranno abbinati all'opzione più economica a prescindere da tutte le caratteristiche uniche dell'oggetto.`,
  _ = `%1$s e oltre`,
  _ = `Ci dispiace!`,
  _ = `Si è verificato un errore durante l'elaborazione della tua richiesta:`,
  _ = `Hai fatto troppe richieste di recente. Attendi e riprova a inviare la tua richiesta più tardi.`,
  _ = `Possibili contenuti:`,
  _ = `Si è verificato un problema con il caricamento di questo contenuto`,
  _ = `L'oggetto richiesto potrebbe non esistere o potrebbe esserci un problema temporaneo che ne impedisce il caricamento. Riprova più tardi.`,
  _ = `Filtra le inserzioni`,
  _ = `Nessuna offerta trovata`,
  _ = `Altre opzioni...`,
  _ = `Filtra...`,
  _ = `Informazioni`,
  _ = `Grafico delle vendite`,
  _ = `Ordini d'acquisto`,
  _ = `Filtri`,
  _ = `Min`,
  _ = `Max`,
  _ = `Accessori`,
  _ = `Qualunque`,
  _ = `Nessuno`,
  _ = `%1$s: %2$s`,
  _ = `Non puoi comprare questo oggetto poiché nel tuo Paese non è consentito comprare e vendere questo tipo di oggetto.`,
  _ = `Non puoi comprare questo oggetto poiché nel tuo Paese non è consentito comprare questo tipo di oggetto.`,
  _ = `Questo annuncio non ha ancora immagini uniche o migliorate. L'immagine mostrata qui potrebbe variare leggermente dall'articolo in vendita.`,
  _ = `Mostra sfondo`,
  _ = `Si è verificato un errore durante il tentativo di visualizzare questo annuncio`,
  _ = `Non puoi acquistare o vendere oggetti sul Mercato per il seguente motivo:`,
  _ = `Non puoi acquistare o vendere oggetti sul Mercato per i seguenti motivi:`,
  _ = `Visualizza risultati`,
  _ = `Visualizza come griglia`,
  _ = `Visualizza come elenco`,
  _ = `Si è verificato un problema durante il caricamento dei risultati aggiuntivi. Riprova più tardi.`,
  _ = `Stai tentando di visualizzare un oggetto per un gioco nuovo su Steam al quale non hai mai giocato. Usa cautela con questo oggetto.`,
  _ = `Clicca qui per visualizzare comunque questo oggetto`,
  _ = `Filtra per gioco`,
  _ = `Mostra tutti i giochi`,
  _ = `Il tuo account è bloccato.`,
  _ = `Per trovare le informazioni su questo blocco, clicca sulla barra rossa nell'angolo in alto a destra, dopo aver eseguito l'accesso al client di Steam. Per altre informazioni, contatta l'Assistenza di Steam.`,
  _ = `Il tuo account è stato bloccato. Puoi trovare informazioni su questo blocco cliccando sulla barra rossa visibile nell'angolo in alto a destra del client di Steam dopo aver effettuato l'accesso.`,
  _ = `Per rimuovere questa restrizione...`,
  _ = `Il tuo account è bandito dagli scambi.`,
  _ = `Attualmente questo account non può utilizzare il Mercato della Comunità di Steam.`,
  _ = `I ban sugli scambi possono essere temporanei o permanenti. Per vedere la durata di un ban, clicca sulla barra rossa in alto a destra, dopo aver eseguito l'accesso al client di Steam.`,
  _ = `Il tuo account non può fare scambi. Per vedere la data di scadenza di questo ban, clicca sulla barra rossa visibile nell'angolo in alto a destra del client di Steam dopo aver effettuato l'accesso.`,
  _ = `Altre informazioni...`,
  _ = `Devi aver fatto un acquisto su Steam in un periodo compreso tra %1$s giorni e un anno fa senza chargeback o contestazioni di pagamento di alcun tipo.`,
  _ = `Fai un acquisto nel Negozio di Steam. I crediti del Portafoglio, i giochi e i DLC sono acquisti validi. I codici prodotto e i doni, invece, non lo sono. L'Assistenza di Steam non può rimuovere questa restrizione.`,
  _ = `Devi aver fatto un acquisto su Steam in un periodo compreso tra %1$s giorni e un anno fa senza chargeback o contestazioni di pagamento di alcun tipo. L'Assistenza di Steam non può rimuovere questa restrizione.`,
  _ = `Sembra che tu abbia fatto un acquisto valido nel Negozio di Steam, ma non sono passati ancora %1$s giorni.`,
  _ = `Devi aver fatto un acquisto su Steam in un periodo compreso tra %1$s giorni e un anno fa senza chargeback o contestazioni di pagamento di alcun tipo. Il tuo ultimo acquisto è stato fatto meno di %1$s giorni fa. L'Assistenza di Steam non può rimuovere questa restrizione.`,
  _ = `La password del tuo account è stata cambiata recentemente.`,
  _ = `Questa restrizione verrà rimossa automaticamente dopo %1$s giorni dall'ultimo ripristino della password. Se l'account è rimasto inutilizzato per molto tempo, questa restrizione può durare fino a %2$s giorni. Questa restrizione non viene applicata quando modifichi la password del tuo account, ma soltanto quando la ripristini. L'Assistenza di Steam non può rimuovere queste restrizioni.`,
  _ = `La password del tuo account di Steam è stata ripristinata di recente. Per proteggere gli utenti che potrebbero aver subito il furto dell'account di posta o altro, limitiamo l'accesso al Mercato della Comunità per %1$s giorni dopo la reimpostazione della password.`,
  _ = `Hai recentemente aggiunto fondi al tuo Portafoglio di Steam utilizzando una carta di credito non verificata di cui abbiamo riscontrato un uso insolitamente frequente nell'ultimo periodo. Puoi provare a <1>convalidare i fondi ora</1> o attendere fino alla rimozione automatica di questa restrizione.

NOTA: la verifica dei fondi potrebbe non funzionare per tutte le banche o le carte di credito. Se non puoi verificare la tua carta, dovrai aspettare che il metodo di pagamento venga verificato da Steam. L'Assistenza di Steam non può fornire le cifre dei pagamenti di verifica e non può rimuovere la restrizione.`,
  _ = `Hai recentemente aggiunto fondi al tuo Portafoglio di Steam utilizzando PayPal o un metodo di pagamento non verificato di cui abbiamo riscontrato un uso più frequente nell'ultimo periodo. Non potrai usare il Mercato per alcuni giorni mentre i fondi vengono verificati.`,
  _ = `Hai recentemente aggiunto fondi al tuo Portafoglio di Steam tramite un account PayPal nuovo o un metodo di pagamento non verificato di cui abbiamo riscontrato un uso più frequente nell'ultimo periodo. Non potrai utilizzare il Mercato per qualche giorno mentre i fondi vengono verificati.`,
  _ = `Di recente hai accettato un buono regalo digitale da un amico.`,
  _ = `Di recente hai accettato un buono regalo digitale da un amico. Non potrai usare il Mercato della Comunità di Steam per %1$s giorni dalla data di acquisto del buono regalo da parte del tuo amico.`,
  _ = `Steam non riesce a utilizzare i cookie del tuo browser.`,
  _ = `I tuoi cookie non sono validi. Prova a disconnetterti e a rieseguire l'accesso a Steam. Inoltre, assicurati che i cookie del browser siano abilitati e che non ci siano componenti aggiuntivi che interferiscono con i cookie di Steam.`,
  _ = `I cookie potrebbero non essere attivati per il tuo browser. Assicurati che tutti i cookie siano attivati e prova a disconnetterti e a ripetere l'accesso.`,
  _ = `Stai effettuando l'accesso al Mercato da un dispositivo che non è stato protetto da Steam Guard per %1$s giorni.`,
  _ = `Se hai un dispositivo verificato, potrai usarlo per usufruire del Mercato, altrimenti dovrai aspettare che questo dispositivo venga verificato prima di poter utilizzare il Mercato.`,
  _ = `Hai eseguito l'accesso da un nuovo dispositivo o browser web. Per proteggere gli oggetti del tuo inventario, non potrai usare il Mercato della Comunità su questo dispositivo per %1$s giorni.`,
  _ = `Hai ottenuto da poco tempo il rimborso per una transazione nel tuo Portafoglio di Steam.`,
  _ = `Non potrai utilizzare il Mercato per %1$s giorni dall'ultimo rimborso. L'Assistenza di Steam non può rimuovere le restrizioni.`,
  _ = `Abbiamo rimborsato recentemente una transazione nel tuo Portafoglio di Steam. Non potrai usare il Mercato della Comunità per %1$s giorni dopo il tuo ultimo rimborso.`,
  _ = `Il tuo account è limitato.`,
  _ = `Il tuo account è limitato e non ha l'accesso ad alcune funzionalità di Steam tra cui il Mercato della Comunità di Steam.`,
  _ = `Il tuo account è limitato e non ha l'accesso ad alcune funzionalità di Steam tra cui il Mercato della Comunità di Steam.`,
  _ = `Steam Guard è stato attivato o reimpostato di recente sul tuo account. Dovrai attendere %1$s giorni da quando è avvenuta l'attivazione.`,
  _ = `Steam Guard deve essere abilitato sul tuo account da almeno 15 giorni. L'Assistenza di Steam non può rimuovere questa restrizione.`,
  _ = `Il tuo account deve essere protetto da Steam Guard da almeno %1$s giorni.`,
  _ = `Devi abilitare Steam Guard sul tuo account. Dovrai verificare il tuo indirizzo e-mail ed eseguire l'accesso all'account due volte dopo l'attivazione di Steam Guard.`,
  _ = `Il tuo account deve essere protetto da Steam Guard da almeno %1$s giorni.`,
  _ = `A meno di ulteriori restrizioni in cui potrebbe incorrere il tuo account, potrai usare il Mercato della Comunità il giorno %1$s`,
  _ = `Il tuo account è temporaneamente sospeso dalle funzionalità di scambio e del Mercato.`,
  _ = {
    AdvancedSearch_Heading: _,
    AdvancedSearch_Reset: _,
    AdvancedSearch_Search: _,
    AdvancedSearch_AppSelect_Placeholder: _,
    AdvancedSearch_AppSelect_YourGames: _,
    AdvancedSearch_AppSelect_PopularGames: _,
    AdvancedSearch_AppSelect_Clear: _,
    AdvancedSearch_TextSearch_Placeholder: _,
    AdvancedSearch_TextSearch_PlaceholderWithApp: _,
    AdvancedSearch_TypeSwitch_InGame: _,
    AdvancedSearch_TypeSwitch_SteamItems: _,
    AdvancedSearch_SteamItems_TypeLabel: _,
    AdvancedSearch_NoFacets: _,
    AdvancedSearch_NoFacetsSearch: _,
    AdvancedSearch_FacetLoadError: _,
    AdvancedSearch_PriceFieldLabel: _,
    AdvancedSearch_MinPricePlaceholder: _,
    AdvancedSearch_MaxPricePlaceholder: _,
    AdvancedSearch_CustomFilter_All: _,
    AdvancedSearch_CustomFilter_Other: _,
    AdvancedSearch_FilterGeneric_Placeholder: _,
    AdvancedSearch_AppSelect_FilterPlaceholder: _,
    AdvancedSearch_BetaTag: _,
    AdvancedSearch_TextSearch_Tooltip: _,
    AdvancedSearch_CSContainers_Tooltip: _,
    Header_MarketTitle: _,
    Header_MarketDescription: _,
    Header_LearnMore: _,
    Header_Search_Placeholder: _,
    Header_Search_PlaceholderNew: _,
    Header_Search_Filters: _,
    Header_OptOut: _,
    Header_GiveFeedback: _,
    CommodityExplanation: _,
    Search_AmountFound: _,
    Search_AmountFound_Plural: _,
    Search_AmountFoundFor: _,
    Search_AmountFoundFor_Plural: _,
    Search_ResultsFoundFor: _,
    Search_ListingsFound: _,
    Search_ListingsFound_Plural: _,
    SortBy_Popularity: _,
    SortBy_Name_Asc: _,
    SortBy_Name_Desc: _,
    SortBy_Price_Asc: _,
    SortBy_Price_Desc: _,
    SortBy_Quantity_Asc: _,
    SortBy_Quantity_Desc: _,
    SortBy_AssetProperty_Asc: _,
    SortBy_AssetProperty_Desc: _,
    SortBy_Label: _,
    Search_Button: _,
    Search_Placeholder: _,
    Button_Buy: _,
    Button_Sell: _,
    Button_BuyNow: _,
    Button_BuyOrder: _,
    BuyOrder_PlaceOrderHeader: _,
    Button_Close: _,
    Search_ListingQuantity: _,
    Search_ListingQuantity_Abbreviation: _,
    Bucket_PriceFrom: _,
    AccessorySearch_AttachedAccessoryType: _,
    FilterResults_Placeholder: _,
    AdvancedSearch_Header: _,
    AdvancedSearch_Link: _,
    MarketSearch_Placeholder: _,
    Breadcrumbs_Home: _,
    MarketHome_PopularApps: _,
    AdvancedSearch_IncludeDescriptions: _,
    AdvancedSearch_IncludeDescriptions_Tooltip: _,
    MarketSearch_FilterColumn_Header: _,
    MarketSearch_Reset: _,
    Listings_TextFilter_Placeholder: _,
    Economy_Market_Purchase_Restrictions: _,
    Economy_Market_Purchase_TradableRestriction_1Day: _,
    Economy_Market_Purchase_TradableRestriction_7Days: _,
    Economy_Market_Purchase_TradableRestriction_NDays: _,
    Economy_Market_Purchase_TradableRestriction_Permanent: _,
    Economy_Market_Purchase_MarketableRestriction_1Day: _,
    Economy_Market_Purchase_MarketableRestriction_7Days: _,
    Economy_Market_Purchase_MarketableRestriction_NDays: _,
    Economy_Market_Purchase_MarketableRestriction_None: _,
    AssetPropertyNumberFilterRange: _,
    AssetPropertyStringFilter: _,
    PurchaseDialog_Header: _,
    PurchaseDialog_Details_Column_Name: _,
    PurchaseDialog_Details_Column_Price: _,
    PurchaseDialog_Subtotal_Label: _,
    PurchaseDialog_PublisherFee_Label: _,
    PurchaseDialog_PublisherFee_Label_Generic: _,
    PurchaseDialog_SteamFee_Label: _,
    PurchaseDialog_LocalTax_Label: _,
    PurchaseDialog_Total_Label: _,
    PurchaseDialog_PaymentMethod_Label: _,
    PurchaseDialog_PaymentMethod_Wallet: _,
    PurchaseDialog_SteamAccount_Label: _,
    PurchaseDialog_BillingInfo_Label: _,
    PurchaseDialog_BillingInfo_FirstName: _,
    PurchaseDialog_BillingInfo_LastName: _,
    PurchaseDialog_BillingInfo_Address: _,
    PurchaseDialog_BillingInfo_AddressLine2: _,
    PurchaseDialog_BillingInfo_City: _,
    PurchaseDialog_BillingInfo_StateProvince: _,
    PurchaseDialog_BillingInfo_ZipPostal: _,
    PurchaseDialog_BillingInfo_Country: _,
    PurchaseDialog_BillingInfo_SaveInfo: _,
    PurchaseDialog_Action_AddFunds: _,
    PurchaseDialog_Action_Purchase: _,
    PurchaseDialog_SSA_Link: _,
    PurchaseDialog_SSA_Link_Title: _,
    PurchaseDialog_SSA_Fail: _,
    PurchaseDialog_EU_SSA: _,
    PurchaseDialog_Error_ServerGeneric: _,
    PurchaseDialog_Error_NoConfirmation: _,
    PurchaseDialog_Error_MissingRequired: _,
    PurchaseDialog_Error_InvalidMilitaryCity: _,
    PurchaseDialog_Error_InvalidPostal: _,
    PurchaseDialog_PurchaseComplete: _,
    PurchaseDialog_Button_ViewInventory: _,
    PurchaseDialog_Confirmation_Title: _,
    PurchaseDialog_Confirmation_Title_Wait: _,
    PurchaseDialog_Confirmation_Body_Mobile: _,
    PurchaseDialog_Confirmation_Body_Email: _,
    PurchaseDialog_Confirmation_Body_Unknown: _,
    PurchaseDialog_Confirmation_Description_Mobile: _,
    PurchaseDialog_Confirmation_Description_Email: _,
    PurchaseDialog_Confirmation_Description_Unknown: _,
    PurchaseDialog_Purchase_Successful: _,
    PurchaseDialog_Close: _,
    PurchaseDialog_ViewInventory: _,
    PurhcaseDialog_SaveMyAddress: _,
    Listing_NotAvailable: _,
    Listing_NotAvailable_Short: _,
    Listing_NotAvailable_Long: _,
    Listing_MyListing: _,
    BuyOrderDialog_Header: _,
    BuyOrderDialog_Header_NoItem: _,
    BuyOrderDialog_BucketPicker_Label: _,
    BuyOrderDialog_BucketPicker_Placeholder: _,
    BuyOrderDialog_PriceField: _,
    BuyOrderDialog_PriceField_Suffix: _,
    BuyOrderDialog_QuantityField: _,
    BuyOrderDialog_MaxPrice: _,
    BuyOrderDialog_MaxPrice_Tip: _,
    BuyOrderDialog_Status_Pending: _,
    BuyOrderDialog_Status_Filled: _,
    BuyOrderDialog_Status_Settled: _,
    BuyOrderDialog_Status_Settled_Note: _,
    BuyOrderDialog_Status_GenericError: _,
    BuyOrderDialog_MinPriceError: _,
    OrderBook_Table_PriceOrLess: _,
    OrderBook_Table_PriceOrMore: _,
    OrderBook_Table_Price: _,
    OrderBook_Table_Quantity: _,
    OrderBook_SellOrder_Description: _,
    OrderBook_SellOrder_Description_None: _,
    OrderBook_BuyOrder_Description: _,
    OrderBook_BuyOrder_Description_None: _,
    OrderBook_BuyOrder_NeedBucket: _,
    OrderBook_BuyOrder_Explanation_Unique: _,
    OrderBook_BuyOrder_Explanation_Commodity: _,
    OrderBook_Graph_Title: _,
    OrderBook_Graph_BuyTooltip: _,
    OrderBook_Graph_BuyTooltip_Plural: _,
    OrderBook_Graph_SellTooltip: _,
    OrderBook_Graph_SellTooltip_Plural: _,
    OrderBook_PlaceOrder_BuyRequests: _,
    OrderBook_PlaceOrder_BuyRequests_Plural: _,
    MedianSalePrice_Graph_Title: _,
    Graph_TimeScale_Week: _,
    Graph_TimeScale_Month: _,
    Graph_TimeScale_Year: _,
    Graph_TimeScale_Lifetime: _,
    Graph_NumberSold: _,
    Graph_Label_Price: _,
    Graph_Label_Volume: _,
    Graph_NoData: _,
    Graph_Tooltip_NoPurchaseData: _,
    Graph_Tooltip_NA: `N/D`,
    MyOrders_GridHeader_Name: _,
    MyOrders_GridHeader_Price: _,
    MyOrders_GridHeader_Quantity: _,
    MyOrders_GridHeader_DateListed: _,
    MyOrders_Cancel: _,
    MyOrders_Remove: _,
    MyOrders_Heading: _,
    MyOrders_Heading_Sell: _,
    MyOrders_Heading_Buy: _,
    MyOrders_Heading_MyPurchaseOffers: _,
    MyOrders_Heading_MyListings: _,
    MyOrders_FailedToLoad: _,
    MyOrders_NoActiveOrders_Item: _,
    MyOrders_NoBuyOrders_Item: _,
    MyOrders_NoSellOrders_Item: _,
    MyOrders_QuantityWithValue: _,
    MyOrders_SeeAllN: _,
    CancelBuyOrder_GenericError: _,
    CancelListing_GenericError: _,
    CancelListing_Dialog_Header: _,
    CancelListing_Dialog_Prompt: _,
    CancelListing_Dialog_Prompt_Generic: _,
    CancelListing_Dialog_Yes: _,
    CancelListing_Dialog_No: `No`,
    CancelListing_Dialog_Success: _,
    SellDialog_Frame_Title: _,
    UniqueBuyOrder_Explanation_Header: _,
    UniqueBuyOrder_Explanation_1: _,
    UniqueBuyOrder_Explanation_2: _,
    UniqueBuyOrder_Explanation_3: _,
    PriceFilter_ValueAndUp: _,
    Error_Sorry: _,
    Error_Encountered: _,
    Error_TooManyRequests_Description: _,
    Container_ContentsLabel: _,
    Error_LoadingContent: _,
    Error_LoadingMarketItem: _,
    ListingFilter_Title: _,
    Listings_NoneFound: _,
    ItemBucketPicker_Overflow_Placeholder: _,
    ItemBucketPicker_Overflow_FilterPlaceholder: _,
    Mobile_InfoSection: _,
    Mobile_GraphSection: _,
    Mobile_BuyOrderSection: _,
    Mobile_FiltersButton: _,
    AssetProperty_Range_MinPlaceholder: `Min`,
    AssetProperty_Range_MaxPlaceholder: `Max`,
    Accessories_FieldSectionLabel: _,
    Accessories_AnyFilter: _,
    Accessories_NoneFilter: _,
    Accessories_TypeAndValue_Breadcrumb: _,
    Item_CountryBuySellRestricted: _,
    Item_CountryBuyRestricted: _,
    Listing_EnhancedAppearance_Missing: _,
    Listing_EnhancedAppearance_ShowBackground: _,
    Listing_SomethingWentWrong: _,
    Unavailable_Header: _,
    Unavailable_Header_Plural: _,
    Filter_ViewResults: _,
    Results_GridView_Tooltip: _,
    Results_ListView_Tooltip: _,
    Results_PageLoadError: _,
    Market_AppUnplayedAndUnvetted: _,
    Market_AppUnplayedAndUnvetted_Dismiss: _,
    Home_GamePicker_Label: _,
    Home_GamePicker_ViewAll: _,
    Economy_Market_TopLevelReason_AccountLocked: _,
    Economy_Market_TopLevelTooltip_AccountLocked: _,
    Economy_Market_HeaderTip_AccountLocked: _,
    Economy_Market_TopLevelTooltip_RemoveRestrictionLink: _,
    Economy_Market_TopLevelReason_AccountTradeBanned: _,
    Economy_Market_TopLevelReason_Unknown: _,
    Economy_Market_TopLevelTooltip_AccountTradeBanned: _,
    Economy_Market_HeaderTip_AccountTradeBanned: _,
    Economy_Market_TopLevelTooltip_MoreInfoLink: _,
    Economy_Market_TopLevelReason_AccountNotTrusted: _,
    Economy_Market_TopLevelTooltip_AccountNotTrusted: _,
    Economy_Market_HeaderTip_AccountNotTrusted: _,
    Economy_Market_TopLevelReason_AccountNotTrusted_Waiting: _,
    Economy_Market_TTopLevelTooltip_AccountNotTrusted_Waiting: _,
    Economy_Market_TopLevelReason_AccountPasswordRecentlyReset: _,
    Economy_Market_TopLevelTooltip_AccountPasswordRecentlyReset: _,
    Economy_Market_HeaderTip_AccountPasswordRecentlyReset: _,
    Economy_Market_HeaderTip_NewPaymentMethod_NoDate: _,
    Economy_Market_HeaderTip_AccountHasNewPaymentMethod: _,
    Economy_Market_TopLevelReason_AccountHasNewPaymentMethod: _,
    Economy_Market_TopLevelReason_AcceptedWalletGift: _,
    Economy_Market_HeaderTip_AcceptedWalletGift: _,
    Economy_Market_TopLevelReason_InvalidCookie: _,
    Economy_Market_TopLevelTooltip_InvalidCookie: _,
    Economy_Market_HeaderTip_InvalidCookie: _,
    Economy_Market_TopLevelReason_NewDevice: _,
    Economy_Market_TopLevelTooltip_NewDevice: _,
    Economy_Market_HeaderTip_NewDevice: _,
    Economy_Market_TopLevelReason_SelfRefund: _,
    Economy_Market_TopLevelTooltip_SelfRefund: _,
    Economy_Market_HeaderTip_SelfRefund: _,
    Economy_Market_TopLevelReason_LimitedUser: _,
    Economy_Market_TopLevelTooltip_LimitedUser: _,
    Economy_Market_HeaderTip_LimitedUser: _,
    Economy_Market_HeaderTip_SteamGuardOnlyRecentlyEnabled: _,
    Economy_Market_TopLevelTooltip_SteamGuardRecentlyEnabled: _,
    Economy_Market_TopLevelReason_NoSteamGuard: _,
    Economy_Market_TopLevelTooltip_SteamGuardDisabled: _,
    Economy_Market_HeaderTip_NoSteamGuard: _,
    Economy_Market_HeaderTip_TimeCanUse: _,
    Economy_Market_TopLevelReason_TradeCooldown: _,
  };
export {
  _ as Accessories_AnyFilter,
  _ as Accessories_FieldSectionLabel,
  _ as Accessories_NoneFilter,
  _ as Accessories_TypeAndValue_Breadcrumb,
  _ as AccessorySearch_AttachedAccessoryType,
  _ as AdvancedSearch_AppSelect_Clear,
  _ as AdvancedSearch_AppSelect_FilterPlaceholder,
  _ as AdvancedSearch_AppSelect_Placeholder,
  _ as AdvancedSearch_AppSelect_PopularGames,
  _ as AdvancedSearch_AppSelect_YourGames,
  _ as AdvancedSearch_BetaTag,
  _ as AdvancedSearch_CSContainers_Tooltip,
  _ as AdvancedSearch_CustomFilter_All,
  _ as AdvancedSearch_CustomFilter_Other,
  _ as AdvancedSearch_FacetLoadError,
  _ as AdvancedSearch_FilterGeneric_Placeholder,
  _ as AdvancedSearch_Header,
  _ as AdvancedSearch_Heading,
  _ as AdvancedSearch_IncludeDescriptions,
  _ as AdvancedSearch_IncludeDescriptions_Tooltip,
  _ as AdvancedSearch_Link,
  _ as AdvancedSearch_MaxPricePlaceholder,
  _ as AdvancedSearch_MinPricePlaceholder,
  _ as AdvancedSearch_NoFacets,
  _ as AdvancedSearch_NoFacetsSearch,
  _ as AdvancedSearch_PriceFieldLabel,
  _ as AdvancedSearch_Reset,
  _ as AdvancedSearch_Search,
  _ as AdvancedSearch_SteamItems_TypeLabel,
  _ as AdvancedSearch_TextSearch_Placeholder,
  _ as AdvancedSearch_TextSearch_PlaceholderWithApp,
  _ as AdvancedSearch_TextSearch_Tooltip,
  _ as AdvancedSearch_TypeSwitch_InGame,
  _ as AdvancedSearch_TypeSwitch_SteamItems,
  _ as AssetPropertyNumberFilterRange,
  _ as AssetPropertyStringFilter,
  _ as AssetProperty_Range_MaxPlaceholder,
  _ as AssetProperty_Range_MinPlaceholder,
  _ as Breadcrumbs_Home,
  _ as Bucket_PriceFrom,
  _ as Button_Buy,
  _ as Button_BuyNow,
  _ as Button_BuyOrder,
  _ as Button_Close,
  _ as Button_Sell,
  _ as BuyOrderDialog_BucketPicker_Label,
  _ as BuyOrderDialog_BucketPicker_Placeholder,
  _ as BuyOrderDialog_Header,
  _ as BuyOrderDialog_Header_NoItem,
  _ as BuyOrderDialog_MaxPrice,
  _ as BuyOrderDialog_MaxPrice_Tip,
  _ as BuyOrderDialog_MinPriceError,
  _ as BuyOrderDialog_PriceField,
  _ as BuyOrderDialog_PriceField_Suffix,
  _ as BuyOrderDialog_QuantityField,
  _ as BuyOrderDialog_Status_Filled,
  _ as BuyOrderDialog_Status_GenericError,
  _ as BuyOrderDialog_Status_Pending,
  _ as BuyOrderDialog_Status_Settled,
  _ as BuyOrderDialog_Status_Settled_Note,
  _ as BuyOrder_PlaceOrderHeader,
  _ as CancelBuyOrder_GenericError,
  _ as CancelListing_Dialog_Header,
  _ as CancelListing_Dialog_No,
  _ as CancelListing_Dialog_Prompt,
  _ as CancelListing_Dialog_Prompt_Generic,
  _ as CancelListing_Dialog_Success,
  _ as CancelListing_Dialog_Yes,
  _ as CancelListing_GenericError,
  _ as CommodityExplanation,
  _ as Container_ContentsLabel,
  _ as Economy_Market_HeaderTip_AcceptedWalletGift,
  _ as Economy_Market_HeaderTip_AccountHasNewPaymentMethod,
  _ as Economy_Market_HeaderTip_AccountLocked,
  _ as Economy_Market_HeaderTip_AccountNotTrusted,
  _ as Economy_Market_HeaderTip_AccountPasswordRecentlyReset,
  _ as Economy_Market_HeaderTip_AccountTradeBanned,
  _ as Economy_Market_HeaderTip_InvalidCookie,
  _ as Economy_Market_HeaderTip_LimitedUser,
  _ as Economy_Market_HeaderTip_NewDevice,
  _ as Economy_Market_HeaderTip_NewPaymentMethod_NoDate,
  _ as Economy_Market_HeaderTip_NoSteamGuard,
  _ as Economy_Market_HeaderTip_SelfRefund,
  _ as Economy_Market_HeaderTip_SteamGuardOnlyRecentlyEnabled,
  _ as Economy_Market_HeaderTip_TimeCanUse,
  _ as Economy_Market_Purchase_MarketableRestriction_1Day,
  _ as Economy_Market_Purchase_MarketableRestriction_7Days,
  _ as Economy_Market_Purchase_MarketableRestriction_NDays,
  _ as Economy_Market_Purchase_MarketableRestriction_None,
  _ as Economy_Market_Purchase_Restrictions,
  _ as Economy_Market_Purchase_TradableRestriction_1Day,
  _ as Economy_Market_Purchase_TradableRestriction_7Days,
  _ as Economy_Market_Purchase_TradableRestriction_NDays,
  _ as Economy_Market_Purchase_TradableRestriction_Permanent,
  _ as Economy_Market_TTopLevelTooltip_AccountNotTrusted_Waiting,
  _ as Economy_Market_TopLevelReason_AcceptedWalletGift,
  _ as Economy_Market_TopLevelReason_AccountHasNewPaymentMethod,
  _ as Economy_Market_TopLevelReason_AccountLocked,
  _ as Economy_Market_TopLevelReason_AccountNotTrusted,
  _ as Economy_Market_TopLevelReason_AccountNotTrusted_Waiting,
  _ as Economy_Market_TopLevelReason_AccountPasswordRecentlyReset,
  _ as Economy_Market_TopLevelReason_AccountTradeBanned,
  _ as Economy_Market_TopLevelReason_InvalidCookie,
  _ as Economy_Market_TopLevelReason_LimitedUser,
  _ as Economy_Market_TopLevelReason_NewDevice,
  _ as Economy_Market_TopLevelReason_NoSteamGuard,
  _ as Economy_Market_TopLevelReason_SelfRefund,
  _ as Economy_Market_TopLevelReason_TradeCooldown,
  _ as Economy_Market_TopLevelReason_Unknown,
  _ as Economy_Market_TopLevelTooltip_AccountLocked,
  _ as Economy_Market_TopLevelTooltip_AccountNotTrusted,
  _ as Economy_Market_TopLevelTooltip_AccountPasswordRecentlyReset,
  _ as Economy_Market_TopLevelTooltip_AccountTradeBanned,
  _ as Economy_Market_TopLevelTooltip_InvalidCookie,
  _ as Economy_Market_TopLevelTooltip_LimitedUser,
  _ as Economy_Market_TopLevelTooltip_MoreInfoLink,
  _ as Economy_Market_TopLevelTooltip_NewDevice,
  _ as Economy_Market_TopLevelTooltip_RemoveRestrictionLink,
  _ as Economy_Market_TopLevelTooltip_SelfRefund,
  _ as Economy_Market_TopLevelTooltip_SteamGuardDisabled,
  _ as Economy_Market_TopLevelTooltip_SteamGuardRecentlyEnabled,
  _ as Error_Encountered,
  _ as Error_LoadingContent,
  _ as Error_LoadingMarketItem,
  _ as Error_Sorry,
  _ as Error_TooManyRequests_Description,
  _ as FilterResults_Placeholder,
  _ as Filter_ViewResults,
  _ as Graph_Label_Price,
  _ as Graph_Label_Volume,
  _ as Graph_NoData,
  _ as Graph_NumberSold,
  _ as Graph_TimeScale_Lifetime,
  _ as Graph_TimeScale_Month,
  _ as Graph_TimeScale_Week,
  _ as Graph_TimeScale_Year,
  _ as Graph_Tooltip_NA,
  _ as Graph_Tooltip_NoPurchaseData,
  _ as Header_GiveFeedback,
  _ as Header_LearnMore,
  _ as Header_MarketDescription,
  _ as Header_MarketTitle,
  _ as Header_OptOut,
  _ as Header_Search_Filters,
  _ as Header_Search_Placeholder,
  _ as Header_Search_PlaceholderNew,
  _ as Home_GamePicker_Label,
  _ as Home_GamePicker_ViewAll,
  _ as ItemBucketPicker_Overflow_FilterPlaceholder,
  _ as ItemBucketPicker_Overflow_Placeholder,
  _ as Item_CountryBuyRestricted,
  _ as Item_CountryBuySellRestricted,
  _ as ListingFilter_Title,
  _ as Listing_EnhancedAppearance_Missing,
  _ as Listing_EnhancedAppearance_ShowBackground,
  _ as Listing_MyListing,
  _ as Listing_NotAvailable,
  _ as Listing_NotAvailable_Long,
  _ as Listing_NotAvailable_Short,
  _ as Listing_SomethingWentWrong,
  _ as Listings_NoneFound,
  _ as Listings_TextFilter_Placeholder,
  _ as MarketHome_PopularApps,
  _ as MarketSearch_FilterColumn_Header,
  _ as MarketSearch_Placeholder,
  _ as MarketSearch_Reset,
  _ as Market_AppUnplayedAndUnvetted,
  _ as Market_AppUnplayedAndUnvetted_Dismiss,
  _ as MedianSalePrice_Graph_Title,
  _ as Mobile_BuyOrderSection,
  _ as Mobile_FiltersButton,
  _ as Mobile_GraphSection,
  _ as Mobile_InfoSection,
  _ as MyOrders_Cancel,
  _ as MyOrders_FailedToLoad,
  _ as MyOrders_GridHeader_DateListed,
  _ as MyOrders_GridHeader_Name,
  _ as MyOrders_GridHeader_Price,
  _ as MyOrders_GridHeader_Quantity,
  _ as MyOrders_Heading,
  _ as MyOrders_Heading_Buy,
  _ as MyOrders_Heading_MyListings,
  _ as MyOrders_Heading_MyPurchaseOffers,
  _ as MyOrders_Heading_Sell,
  _ as MyOrders_NoActiveOrders_Item,
  _ as MyOrders_NoBuyOrders_Item,
  _ as MyOrders_NoSellOrders_Item,
  _ as MyOrders_QuantityWithValue,
  _ as MyOrders_Remove,
  _ as MyOrders_SeeAllN,
  _ as OrderBook_BuyOrder_Description,
  _ as OrderBook_BuyOrder_Description_None,
  _ as OrderBook_BuyOrder_Explanation_Commodity,
  _ as OrderBook_BuyOrder_Explanation_Unique,
  _ as OrderBook_BuyOrder_NeedBucket,
  _ as OrderBook_Graph_BuyTooltip,
  _ as OrderBook_Graph_BuyTooltip_Plural,
  _ as OrderBook_Graph_SellTooltip,
  _ as OrderBook_Graph_SellTooltip_Plural,
  _ as OrderBook_Graph_Title,
  _ as OrderBook_PlaceOrder_BuyRequests,
  _ as OrderBook_PlaceOrder_BuyRequests_Plural,
  _ as OrderBook_SellOrder_Description,
  _ as OrderBook_SellOrder_Description_None,
  _ as OrderBook_Table_Price,
  _ as OrderBook_Table_PriceOrLess,
  _ as OrderBook_Table_PriceOrMore,
  _ as OrderBook_Table_Quantity,
  _ as PriceFilter_ValueAndUp,
  _ as PurchaseDialog_Action_AddFunds,
  _ as PurchaseDialog_Action_Purchase,
  _ as PurchaseDialog_BillingInfo_Address,
  _ as PurchaseDialog_BillingInfo_AddressLine2,
  _ as PurchaseDialog_BillingInfo_City,
  _ as PurchaseDialog_BillingInfo_Country,
  _ as PurchaseDialog_BillingInfo_FirstName,
  _ as PurchaseDialog_BillingInfo_Label,
  _ as PurchaseDialog_BillingInfo_LastName,
  _ as PurchaseDialog_BillingInfo_SaveInfo,
  _ as PurchaseDialog_BillingInfo_StateProvince,
  _ as PurchaseDialog_BillingInfo_ZipPostal,
  _ as PurchaseDialog_Button_ViewInventory,
  _ as PurchaseDialog_Close,
  _ as PurchaseDialog_Confirmation_Body_Email,
  _ as PurchaseDialog_Confirmation_Body_Mobile,
  _ as PurchaseDialog_Confirmation_Body_Unknown,
  _ as PurchaseDialog_Confirmation_Description_Email,
  _ as PurchaseDialog_Confirmation_Description_Mobile,
  _ as PurchaseDialog_Confirmation_Description_Unknown,
  _ as PurchaseDialog_Confirmation_Title,
  _ as PurchaseDialog_Confirmation_Title_Wait,
  _ as PurchaseDialog_Details_Column_Name,
  _ as PurchaseDialog_Details_Column_Price,
  _ as PurchaseDialog_EU_SSA,
  _ as PurchaseDialog_Error_InvalidMilitaryCity,
  _ as PurchaseDialog_Error_InvalidPostal,
  _ as PurchaseDialog_Error_MissingRequired,
  _ as PurchaseDialog_Error_NoConfirmation,
  _ as PurchaseDialog_Error_ServerGeneric,
  _ as PurchaseDialog_Header,
  _ as PurchaseDialog_LocalTax_Label,
  _ as PurchaseDialog_PaymentMethod_Label,
  _ as PurchaseDialog_PaymentMethod_Wallet,
  _ as PurchaseDialog_PublisherFee_Label,
  _ as PurchaseDialog_PublisherFee_Label_Generic,
  _ as PurchaseDialog_PurchaseComplete,
  _ as PurchaseDialog_Purchase_Successful,
  _ as PurchaseDialog_SSA_Fail,
  _ as PurchaseDialog_SSA_Link,
  _ as PurchaseDialog_SSA_Link_Title,
  _ as PurchaseDialog_SteamAccount_Label,
  _ as PurchaseDialog_SteamFee_Label,
  _ as PurchaseDialog_Subtotal_Label,
  _ as PurchaseDialog_Total_Label,
  _ as PurchaseDialog_ViewInventory,
  _ as PurhcaseDialog_SaveMyAddress,
  _ as Results_GridView_Tooltip,
  _ as Results_ListView_Tooltip,
  _ as Results_PageLoadError,
  _ as Search_AmountFound,
  _ as Search_AmountFoundFor,
  _ as Search_AmountFoundFor_Plural,
  _ as Search_AmountFound_Plural,
  _ as Search_Button,
  _ as Search_ListingQuantity,
  _ as Search_ListingQuantity_Abbreviation,
  _ as Search_ListingsFound,
  _ as Search_ListingsFound_Plural,
  _ as Search_Placeholder,
  _ as Search_ResultsFoundFor,
  _ as SellDialog_Frame_Title,
  _ as SortBy_AssetProperty_Asc,
  _ as SortBy_AssetProperty_Desc,
  _ as SortBy_Label,
  _ as SortBy_Name_Asc,
  _ as SortBy_Name_Desc,
  _ as SortBy_Popularity,
  _ as SortBy_Price_Asc,
  _ as SortBy_Price_Desc,
  _ as SortBy_Quantity_Asc,
  _ as SortBy_Quantity_Desc,
  _ as Unavailable_Header,
  _ as Unavailable_Header_Plural,
  _ as UniqueBuyOrder_Explanation_1,
  _ as UniqueBuyOrder_Explanation_2,
  _ as UniqueBuyOrder_Explanation_3,
  _ as UniqueBuyOrder_Explanation_Header,
  _ as default,
};
