var _ = `Publicaciones en foro`,
  _ = `Discusiones generales`,
  _ = `Publicaciones denunciadas`,
  _ = `Discusiones del Workshop`,
  _ = `Intercambios`,
  _ = `Eventos y anuncios`,
  _ = `1 denuncia`,
  _ = `%1$s denuncias`,
  _ = `1\xA0asunto`,
  _ = `%1$s\xA0asuntos`,
  _ = `%1$s el %2$s`,
  _ = `%1$s en %2$s en el tema: %3$s`,
  _ = `1 denuncia`,
  _ = `%1$s denuncias`,
  _ = `1\xA0asunto`,
  _ = `%1$s\xA0asuntos`,
  _ = `Comunidad de Steam`,
  _ = `Comunidad de Steam :: Error`,
  _ = `Error`,
  _ = `Error desconocido`,
  _ = `Juegos`,
  _ = `Comunidad de Steam :: %1$s :: Juegos`,
  _ = `Buscar - Mercado de la Comunidad de Steam`,
  _ = `%1$s - Mercado de la Comunidad de Steam`,
  _ = `Artículo del Mercado - Mercado de la Comunidad de Steam`,
  _ = `Mercado de la Comunidad de Steam`,
  _ = `No se encontró el perfil`,
  _ = `No se ha podido cargar la lista de deseados del usuario.`,
  _ = `Has hecho demasiadas solicitudes recientemente. Espera e inténtalo de nuevo más tarde.`,
  _ = `Cargando`,
  _ = `%1$s% COMPLETADO`,
  _ = `PAUSADO - %1$s% COMPLETADO`,
  _ = `%1$s / %2$s DESCARGADO`,
  _ = `LOGROS`,
  _ = `Tiempo restante estimado: %1$s`,
  _ = `%1$s/%2$s`,
  _ = `DESINSTALANDO`,
  _ = `ACTUALIZAR`,
  _ = `DESINSTALAR`,
  _ = `DESCARGAR`,
  _ = `PONER EN PAUSA`,
  _ = `REANUDAR`,
  _ = `DESINSTALANDO`,
  _ = `CANCELAR`,
  _ = `Ver mis ajustes de privacidad para este contenido`,
  _ = `Buscar un juego`,
  _ = `Filtrar productos que ambos tienen`,
  _ = `Tiempo de juego`,
  _ = `Nombre`,
  _ = `Logros completados`,
  _ = `TIEMPO TOTAL DE JUEGO`,
  _ = `ÚLTIMA SESIÓN`,
  _ = `DOS ÚLTIMAS SEMANAS`,
  _ = `Información y enlaces del juego`,
  _ = `Descarga remota`,
  _ = `DESCARGAR REMOTAMENTE A: %1$s`,
  _ = `ESTADO DE DESCARGA REMOTA: %1$s`,
  _ = `Sin acceso a tu PC`,
  _ = `Para hacer una descarga remota a tu cliente de Steam, tu PC debe estar activa y tener una conexión a internet, y tú tienes que haber iniciado sesión`,
  _ = `Leer preguntas frecuentes`,
  _ = `%1$s. %2$s`,
  _ = `Más información`,
  _ = `DESCARGA REMOTA NO DISPONIBLE`,
  _ = `¿Quieres desinstalar %1$s? Este permanecerá en tu biblioteca de juegos, pero para jugarlo en el futuro primero tendrás que volver a descargar todo su contenido. `,
  _ = `%1$s - "%2$s"`,
  _ = `Jugados recientemente %1$s`,
  _ = `Todos los juegos %1$s`,
  _ = `Juegos completados %1$s`,
  _ = `Reseñas %1$s`,
  _ = `Seguidos %1$s`,
  _ = `Lista de deseados`,
  _ = `Obtuviste todos los logros posibles`,
  _ = `Aquí vas a encontrar los juegos que has completado o los juegos en los que obtuviste todos los logros posibles.`,
  _ = `El %1$s\xA0% de los jugadores tiene este logro`,
  _ = `Página de la tienda`,
  _ = `Foros`,
  _ = `Grupos`,
  _ = `Sitio web oficial`,
  _ = `Noticias`,
  _ = `Mis logros`,
  _ = `Logros de %1$s`,
  _ = `Estadísticas de %1$s`,
  _ = `Datos de juego personales de %1$s`,
  _ = `Mis marcadores`,
  _ = `Marcadores de %1$s`,
  _ = `Logros globales`,
  _ = `Marcadores globales`,
  _ = `Estadísticas de juego`,
  _ = `Contenido del juego`,
  _ = `Mis estadísticas de juego`,
  _ = `Mi contenido de juego`,
  _ = `Enlaces del juego`,
  _ = `Mis capturas %1$s`,
  _ = `Capturas de %1$s %2$s`,
  _ = `Amigos que juegan %1$s`,
  _ = `Mis tarjetas %1$s`,
  _ = `Mi reseña`,
  _ = `Reseña de %1$s`,
  _ = `Punto de encuentro`,
  _ = `Mis notas`,
  _ = `%1$s horas`,
  _ = `%1$s minutos`,
  _ = `Marcar como privado`,
  _ = `Desmarcar como privado`,
  _ = `Marcar este juego como privado y ocultarlo de mis amigos`,
  _ = `© Valve Corporation. Todos los derechos reservados. Todas las marcas registradas pertenecen a sus respectivos dueños en EE. UU. y otros países.`,
  _ = `Algunos datos geoespaciales de este sitio web se obtienen de %1$s.`,
  _ = `Política de Privacidad`,
  _ = `Información legal`,
  _ = `Acuerdo de Suscriptor a Steam`,
  _ = `Reembolsos`,
  _ = `Cookies`,
  _ = `Accesibilidad`,
  _ = `Bloqueos actuales`,
  _ = `Mensajes de la comunidad`,
  _ = `Contenido denunciado`,
  _ = `Contenido moderado`,
  _ = `Estos son los contenidos publicados en Steam que denunciaste por incumplir las directrices de la plataforma.`,
  _ = `Esta es una lista de los contenidos que publicaste en Steam y que han sido moderados.`,
  _ = `Última actualización %1$s`,
  _ = ``,
  _ = {
    Moderation_SubjectTypeName_ForumPost: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    moderation_claim_report_count: _,
    moderation_claim_report_count_Plural: _,
    moderation_claim_subject_count: _,
    moderation_claim_subject_count_Plural: _,
    moderation_claim_n_reports_on_m_subjects: _,
    moderation_forumpost_summary: _,
    moderation_forumpost_summary_reports_fragment: _,
    moderation_forumpost_summary_reports_fragment_Plural: _,
    moderation_forumpost_summary_subjects_fragment: _,
    moderation_forumpost_summary_subjects_fragment_Plural: _,
    community_title: _,
    community_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    profile_games_list: _,
    profile_games_list_title: _,
    Market_Search_Title: _,
    Market_Item_Title: _,
    Market_Item_GenericTitle: _,
    Market_GenericTitle: _,
    profile_error_profilenotfound: _,
    profile_games_list_error_loadfailed: _,
    Error_RateLimited: _,
    Loading: _,
    GamesList_Header_Downloading: _,
    GamesList_Header_Paused: _,
    GamesList_Header_DownloadBytes: _,
    GamesList_Header_Achievements: _,
    GamesList_TimeRemaining: _,
    GamesList_Achievement_Fraction: _,
    GamesList_Uninstalling: _,
    GamesList_Button_UpdateRequired: _,
    GamesList_Button_Uninstall: _,
    GamesList_Button_Download: _,
    GamesList_Button_Pause: _,
    GamesList_Button_Resume: _,
    GamesList_Button_Uninstalling: _,
    GamesList_Button_Cancel: _,
    GamesList_PrivacySettings_Tooltip: _,
    GamesList_Filter_Placeholder: _,
    GamesList_Filter_BothOwned: _,
    GamesList_Sort_HoursPlayed: _,
    GamesList_Sort_Name: _,
    GamesList_Sort_AchievementCompletion: _,
    GamesList_Header_TotalPlayed: _,
    GamesList_Header_LastPlayed: _,
    GamesList_Header_TwoWeeks: _,
    GamesList_MenuLabel_GameInfo: _,
    GamesList_MenuLabel_RemoteDownload: _,
    GamesList_Header_RemoteDownload: _,
    GamesList_Header_RemoteDownloadStatus: _,
    GamesList_RemoteDownload_NoConnection: _,
    GamesList_RemoteDownload_Help: _,
    GamesList_RemoteDownload_ReadTheFAQ: _,
    GamesList_RemoteDownload_Info: _,
    GamesList_RemoteDownload_LearnMore: _,
    GamesList_RemoteDownload_NoRemoteControl: _,
    GamesList_RemoteDownload_UninstallConfirm: _,
    GamesList_Client_Indicator: _,
    GamesList_Tab_RecentlyPlayed: _,
    GamesList_Tab_AllGames: _,
    GamesList_Tab_PerfectGames: _,
    GamesList_Tab_Reviews: _,
    GamesList_Tab_Followed: _,
    GamesList_Tab_Wishlist: _,
    Perfect_Game_Description: _,
    GamesList_PerfectGames_Description: _,
    GamesList_Achievement_Unlock_Percentage: _,
    Community_StorePage: _,
    Community_Forums: _,
    Community_Groups: _,
    Community_OfficialWebsite: _,
    Community_News: _,
    Community_UsersAchievementsFirstPerson: _,
    Community_UsersAchievements: _,
    Community_UsersStats: _,
    Community_GamePersonalData: _,
    Community_UsersLeaderboardsFirstPerson: _,
    Community_UsersLeaderboards: _,
    Community_GlobalAchievements: _,
    Community_GlobalLeaderboards: _,
    Community_GameStats: _,
    Community_GameContent: _,
    Community_GameStatsFirstPerson: _,
    Community_GameContentFirstPerson: _,
    Community_GameLinks: _,
    Community_ScreenshotsMenuItemFirstPerson: _,
    Community_ScreenshotsMenuItemThirdPerson: _,
    Community_FriendsWhoPlayMenuItemFirstPerson: _,
    Community_TradingCardsMenuItemFirstPerson: _,
    Community_ReviewMenuItemFirstPerson: _,
    Community_ReviewMenuItemThirdPerson: _,
    Community_GameHubMenuItem: _,
    Community_GameNotesFirstPerson: _,
    Playtime_Hours: _,
    Playtime_Minutes: _,
    AppPrivacy_MarkAsPrivate: _,
    AppPrivacy_UnmarkAsPrivate: _,
    AppPrivacy_Explanation: _,
    footer_legal_notice: _,
    footer_geodata_notice: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_accessibility: _,
    profiletabs_currentbans: _,
    profiletabs_communitymessages: _,
    profiletabs_reportedcontent: _,
    profiletabs_moderatedcontent: _,
    reportedcontent_description: _,
    moderatedcontent_description: _,
    reportedcontent_lastupdated: _,
    empty_no_comma_following: ``,
  };
export {
  _ as AppPrivacy_Explanation,
  _ as AppPrivacy_MarkAsPrivate,
  _ as AppPrivacy_UnmarkAsPrivate,
  _ as Community_Forums,
  _ as Community_FriendsWhoPlayMenuItemFirstPerson,
  _ as Community_GameContent,
  _ as Community_GameContentFirstPerson,
  _ as Community_GameHubMenuItem,
  _ as Community_GameLinks,
  _ as Community_GameNotesFirstPerson,
  _ as Community_GamePersonalData,
  _ as Community_GameStats,
  _ as Community_GameStatsFirstPerson,
  _ as Community_GlobalAchievements,
  _ as Community_GlobalLeaderboards,
  _ as Community_Groups,
  _ as Community_News,
  _ as Community_OfficialWebsite,
  _ as Community_ReviewMenuItemFirstPerson,
  _ as Community_ReviewMenuItemThirdPerson,
  _ as Community_ScreenshotsMenuItemFirstPerson,
  _ as Community_ScreenshotsMenuItemThirdPerson,
  _ as Community_StorePage,
  _ as Community_TradingCardsMenuItemFirstPerson,
  _ as Community_UsersAchievements,
  _ as Community_UsersAchievementsFirstPerson,
  _ as Community_UsersLeaderboards,
  _ as Community_UsersLeaderboardsFirstPerson,
  _ as Community_UsersStats,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as GamesList_Achievement_Fraction,
  _ as GamesList_Achievement_Unlock_Percentage,
  _ as GamesList_Button_Cancel,
  _ as GamesList_Button_Download,
  _ as GamesList_Button_Pause,
  _ as GamesList_Button_Resume,
  _ as GamesList_Button_Uninstall,
  _ as GamesList_Button_Uninstalling,
  _ as GamesList_Button_UpdateRequired,
  _ as GamesList_Client_Indicator,
  _ as GamesList_Filter_BothOwned,
  _ as GamesList_Filter_Placeholder,
  _ as GamesList_Header_Achievements,
  _ as GamesList_Header_DownloadBytes,
  _ as GamesList_Header_Downloading,
  _ as GamesList_Header_LastPlayed,
  _ as GamesList_Header_Paused,
  _ as GamesList_Header_RemoteDownload,
  _ as GamesList_Header_RemoteDownloadStatus,
  _ as GamesList_Header_TotalPlayed,
  _ as GamesList_Header_TwoWeeks,
  _ as GamesList_MenuLabel_GameInfo,
  _ as GamesList_MenuLabel_RemoteDownload,
  _ as GamesList_PerfectGames_Description,
  _ as GamesList_PrivacySettings_Tooltip,
  _ as GamesList_RemoteDownload_Help,
  _ as GamesList_RemoteDownload_Info,
  _ as GamesList_RemoteDownload_LearnMore,
  _ as GamesList_RemoteDownload_NoConnection,
  _ as GamesList_RemoteDownload_NoRemoteControl,
  _ as GamesList_RemoteDownload_ReadTheFAQ,
  _ as GamesList_RemoteDownload_UninstallConfirm,
  _ as GamesList_Sort_AchievementCompletion,
  _ as GamesList_Sort_HoursPlayed,
  _ as GamesList_Sort_Name,
  _ as GamesList_Tab_AllGames,
  _ as GamesList_Tab_Followed,
  _ as GamesList_Tab_PerfectGames,
  _ as GamesList_Tab_RecentlyPlayed,
  _ as GamesList_Tab_Reviews,
  _ as GamesList_Tab_Wishlist,
  _ as GamesList_TimeRemaining,
  _ as GamesList_Uninstalling,
  _ as Loading,
  _ as Market_GenericTitle,
  _ as Market_Item_GenericTitle,
  _ as Market_Item_Title,
  _ as Market_Search_Title,
  _ as Moderation_SubjectTypeName_ForumPost,
  _ as Perfect_Game_Description,
  _ as Playtime_Hours,
  _ as Playtime_Minutes,
  _ as community_errorpage_title,
  _ as community_title,
  _ as default,
  _ as empty_no_comma_following,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_accessibility,
  _ as footer_cookies,
  _ as footer_geodata_notice,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_privacy_policy,
  _ as footer_refunds,
  _ as footer_ssa,
  _ as moderatedcontent_description,
  _ as moderation_claim_n_reports_on_m_subjects,
  _ as moderation_claim_report_count,
  _ as moderation_claim_report_count_Plural,
  _ as moderation_claim_subject_count,
  _ as moderation_claim_subject_count_Plural,
  _ as moderation_forumpost_summary,
  _ as moderation_forumpost_summary_reports_fragment,
  _ as moderation_forumpost_summary_reports_fragment_Plural,
  _ as moderation_forumpost_summary_subjects_fragment,
  _ as moderation_forumpost_summary_subjects_fragment_Plural,
  _ as profile_error_profilenotfound,
  _ as profile_games_list,
  _ as profile_games_list_error_loadfailed,
  _ as profile_games_list_title,
  _ as profiletabs_communitymessages,
  _ as profiletabs_currentbans,
  _ as profiletabs_moderatedcontent,
  _ as profiletabs_reportedcontent,
  _ as reportedcontent_description,
  _ as reportedcontent_lastupdated,
};
