var _ = `brazilian`,
  _ = `Escrito originalmente por %1$s:`,
  _ = `{LINK REMOVIDO}`,
  _ = `O URL que estava aqui foi removido pelos nossos filtros. Geralmente isso acontece para impedir ataques de phishing e malware.`,
  _ = `(Somente para a Valve e moderadores) Clique para revelar o link`,
  _ = `%1$s comentários`,
  _ = `Exibindo comentários %1$s–%2$s de %3$s`,
  _ = `Adicionar um comentário`,
  _ = `Publicar comentário`,
  _ = `Ajuda com formatação`,
  _ = `Inserir emoticon`,
  _ = `Emoticon de %1$s`,
  _ = `Buscar`,
  _ = `Últimos usados`,
  _ = `Todos os emoticons`,
  _ = `Nenhum emoticon corresponde à busca.`,
  _ = `Você ainda não possui nenhum emoticon.`,
  _ = `Formatação de texto`,
  _ = `Essas tags permitem adicionar formatação ao texto dos seus comentários e mensagens nas discussões, de forma semelhante a HTML.`,
  _ = `Sintaxe`,
  _ = `Exemplo`,
  _ = `Texto em negrito`,
  _ = `Texto sublinhado`,
  _ = `Texto em itálico`,
  _ = `Texto riscado`,
  _ = `Texto oculto`,
  _ = `Não interpreta [b]marcadores[/b] `,
  _ = `Link para website`,
  _ = `Citação`,
  _ = `Fonte de largura fixa,
preserva  espaços`,
  _ = `Texto de cabeçalho`,
  _ = `Texto de cabeçalho`,
  _ = `Texto de cabeçalho`,
  _ = `Lista com marcadores`,
  _ = `Lista ordenada`,
  _ = `Receber notificações`,
  _ = `Deixar de receber notificações`,
  _ = `Ative para receber uma notificação sempre que houver um comentário novo aqui.`,
  _ = `Você receberá notificações de comentários novos por ser algo associado ao seu Perfil Steam.`,
  _ = `Houve um problema ao atualizar a sua inscrição. Tente novamente mais tarde.`,
  _ = `Excluir`,
  _ = `Ocultar e denunciar comentário`,
  _ = `Marcar como suspeito`,
  _ = `Remover sinalização de conteúdo passível de banimento: %1$s`,
  _ = `Não verificado`,
  _ = `Reiniciar`,
  _ = `Requer verificação`,
  _ = `Muito improvável`,
  _ = `Improvável`,
  _ = `Plausível`,
  _ = `Provável`,
  _ = `Muito provável`,
  _ = `Desconhecido (%1$s)`,
  _ = `Abrir na ferramenta de moderação`,
  _ = `Você denunciou este comentário`,
  _ = `Você bloqueou este usuário`,
  _ = `Desfazer`,
  _ = `exibir este comentário`,
  _ = `As suas permissões de suporte/moderação permitem visualizá-lo.`,
  _ = `Este comentário ainda não foi revisado pelo nosso sistema de verificação automática de conteúdo. Por isso, ele permanecerá oculto até que seja verificado que não há conteúdo nocivo (como links para sites que tentam roubar dados de usuários).`,
  _ = `Este comentário foi sinalizado automaticamente por conter conteúdo potencialmente nocivo. Por isso, ele foi ocultado.`,
  _ = `Você normalmente não teria permissão para comentar aqui, mas você possui privilégios adicionais.`,
  _ = `Este comentário foi excluído.`,
  _ = `O seu comentário é muito curto.`,
  _ = `O seu comentário é muito longo. Ele não pode ultrapassar %1$s caracteres.`,
  _ = `Você não tem permissão para publicar um comentário aqui.`,
  _ = `Inicie a sessão para publicar um comentário.`,
  _ = `Você precisa ter este jogo para comentar neste item.`,
  _ = `Você precisa ter pelo menos uma hora de jogo antes de poder publicar um comentário.`,
  _ = `Comentários desativados para este item.`,
  _ = `Nenhum comentário ainda.`,
  _ = {
    language: _,
    CommentThread_QuoteBlock_Author: _,
    CommentThread_RemovedLink: _,
    CommentThread_RemovedLink_Tooltip: _,
    CommentThread_RemovedLink_Reveal: _,
    CommentThread_NumberOfComments: _,
    CommentThread_ShowingXToYOfTotal: _,
    CommentThread_AddAComment: _,
    CommentThread_PostComment: _,
    CommentThread_FormattingHelp: _,
    CommentThread_InsertEmoticon: _,
    CommentThread_EmoticonHoverApp: _,
    CommentThread_EmoticonSearch: _,
    CommentThread_EmoticonRecentlyUsed: _,
    CommentThread_EmoticonAll: _,
    CommentThread_EmoticonNoResults: _,
    CommentThread_EmoticonNoneOwned: _,
    CommentThread_FormattingHelpHeader: _,
    Discussions_FormattingHelp_Description: _,
    Discussions_FormattingHelp_ColumnSyntax: _,
    Discussions_FormattingHelp_ColumnExample: _,
    Discussions_FormattingHelp_Bold: _,
    Discussions_FormattingHelp_Underline: _,
    Discussions_FormattingHelp_Italic: _,
    Discussions_FormattingHelp_Strike: _,
    Discussions_FormattingHelp_Spoiler: _,
    Discussions_FormattingHelp_Noparse: _,
    Discussions_FormattingHelp_Link: _,
    Discussions_FormattingHelp_Quote: _,
    Discussions_FormattingHelp_Code: _,
    Discussions_FormattingHelp_H1: _,
    Discussions_FormattingHelp_H2: _,
    Discussions_FormattingHelp_H3: _,
    Discussions_FormattingHelp_List: _,
    Discussions_FormattingHelp_OList: _,
    CommentThread_Subscribe: _,
    CommentThread_Unsubscribe: _,
    CommentThread_SubscribeHint: _,
    CommentThread_SubscribeHintOwnThread: _,
    CommentThread_SubscribeError: _,
    CommentThread_DeleteComment: _,
    CommentThread_HideComment: _,
    CommentThread_MarkSpam: _,
    CommentThread_ClearContentCheck: _,
    BanContentCheckResult_NotScanned: _,
    BanContentCheckResult_Reset: _,
    BanContentCheckResult_NeedsChecking: _,
    BanContentCheckResult_VeryUnlikely: _,
    BanContentCheckResult_Unlikely: _,
    BanContentCheckResult_Possible: _,
    BanContentCheckResult_Likely: _,
    BanContentCheckResult_VeryLikely: _,
    BanContentCheckResult_Unknown: _,
    CommentThread_ModerationTool: _,
    CommentThread_HiddenByUser: _,
    CommentThread_HiddenByBlocked: _,
    CommentThread_HiddenUndo: _,
    CommentThread_HiddenViewComment: _,
    CommentThread_ModeratorViewContent: _,
    CommentThread_NeedsContentCheck: _,
    CommentThread_FailedContentCheck: _,
    CommentThread_PermissionOverride: _,
    CommentThread_Deleted: _,
    CommentThread_PostError_TooShort: _,
    CommentThread_PostError_TooLong: _,
    CommentThread_PostError_NotAllowed: _,
    CommentThread_PostError_NotLoggedIn: _,
    CommentThread_PostError_MustOwnApp: _,
    CommentThread_PostError_LimitedUser: _,
    CommentThread_CommentsDisabled: _,
    CommentThread_NoComments: _,
  };
export {
  _ as BanContentCheckResult_Likely,
  _ as BanContentCheckResult_NeedsChecking,
  _ as BanContentCheckResult_NotScanned,
  _ as BanContentCheckResult_Possible,
  _ as BanContentCheckResult_Reset,
  _ as BanContentCheckResult_Unknown,
  _ as BanContentCheckResult_Unlikely,
  _ as BanContentCheckResult_VeryLikely,
  _ as BanContentCheckResult_VeryUnlikely,
  _ as CommentThread_AddAComment,
  _ as CommentThread_ClearContentCheck,
  _ as CommentThread_CommentsDisabled,
  _ as CommentThread_DeleteComment,
  _ as CommentThread_Deleted,
  _ as CommentThread_EmoticonAll,
  _ as CommentThread_EmoticonHoverApp,
  _ as CommentThread_EmoticonNoResults,
  _ as CommentThread_EmoticonNoneOwned,
  _ as CommentThread_EmoticonRecentlyUsed,
  _ as CommentThread_EmoticonSearch,
  _ as CommentThread_FailedContentCheck,
  _ as CommentThread_FormattingHelp,
  _ as CommentThread_FormattingHelpHeader,
  _ as CommentThread_HiddenByBlocked,
  _ as CommentThread_HiddenByUser,
  _ as CommentThread_HiddenUndo,
  _ as CommentThread_HiddenViewComment,
  _ as CommentThread_HideComment,
  _ as CommentThread_InsertEmoticon,
  _ as CommentThread_MarkSpam,
  _ as CommentThread_ModerationTool,
  _ as CommentThread_ModeratorViewContent,
  _ as CommentThread_NeedsContentCheck,
  _ as CommentThread_NoComments,
  _ as CommentThread_NumberOfComments,
  _ as CommentThread_PermissionOverride,
  _ as CommentThread_PostComment,
  _ as CommentThread_PostError_LimitedUser,
  _ as CommentThread_PostError_MustOwnApp,
  _ as CommentThread_PostError_NotAllowed,
  _ as CommentThread_PostError_NotLoggedIn,
  _ as CommentThread_PostError_TooLong,
  _ as CommentThread_PostError_TooShort,
  _ as CommentThread_QuoteBlock_Author,
  _ as CommentThread_RemovedLink,
  _ as CommentThread_RemovedLink_Reveal,
  _ as CommentThread_RemovedLink_Tooltip,
  _ as CommentThread_ShowingXToYOfTotal,
  _ as CommentThread_Subscribe,
  _ as CommentThread_SubscribeError,
  _ as CommentThread_SubscribeHint,
  _ as CommentThread_SubscribeHintOwnThread,
  _ as CommentThread_Unsubscribe,
  _ as Discussions_FormattingHelp_Bold,
  _ as Discussions_FormattingHelp_Code,
  _ as Discussions_FormattingHelp_ColumnExample,
  _ as Discussions_FormattingHelp_ColumnSyntax,
  _ as Discussions_FormattingHelp_Description,
  _ as Discussions_FormattingHelp_H1,
  _ as Discussions_FormattingHelp_H2,
  _ as Discussions_FormattingHelp_H3,
  _ as Discussions_FormattingHelp_Italic,
  _ as Discussions_FormattingHelp_Link,
  _ as Discussions_FormattingHelp_List,
  _ as Discussions_FormattingHelp_Noparse,
  _ as Discussions_FormattingHelp_OList,
  _ as Discussions_FormattingHelp_Quote,
  _ as Discussions_FormattingHelp_Spoiler,
  _ as Discussions_FormattingHelp_Strike,
  _ as Discussions_FormattingHelp_Underline,
  _ as default,
  _ as language,
};
