var _ = `مراقب`,
  _ = `مشرف`,
  _ = `مدير Valve`,
  _ = `غير معروف`,
  _ = `الإحصائيات`,
  _ = `تعذر استرداد البيانات الوصفية للبلاغ المقدم ضد هذه الدردشة (خطأ: %1$s)`,
  _ = `لـ%1$s`,
  _ = `الأصدقاء:`,
  _ = `مدة الدردشة قبل تقديم البلاغ:`,
  _ = `عنوان IP الخاص بالمُرسل:`,
  _ = `الدردشة الأولى (تقديرية):`,
  _ = `الرسائل التي تم الإبلاغ عنها`,
  _ = `تشغيل/إيقاف BBCode`,
  _ = `تمت إزالة الصورة`,
  _ = `مرئية عند التمرير`,
  _ = `تم الإبلاغ:`,
  _ = `مزوّد خدمة الإنترنت المستخدم أول مرة في هذه الدردشة قبل %1$s`,
  _ = `غرف الدردشة الحديثة:`,
  _ = `اسم المجموعة:`,
  _ = `اسم الغرفة:`,
  _ = `شركاء الدردشة الحديثون:`,
  _ = `الرسائل المبلغ عنها من إرسال %1$s`,
  _ = `رسائل المجموعة المبلغ عنها من إرسال %1$s`,
  _ = `افتراضي`,
  _ = `الإبلاغات عن مجموعة الدردشة "%1$s"`,
  _ = `الأعضاء:`,
  _ = `الغرف:`,
  _ = `تم التعطيل`,
  _ = `الشعار:`,
  _ = `نوع المجموعة:`,
  _ = `المالك:`,
  _ = `مخصصة خاصة (معرف المجموعة %1$s)`,
  _ = `تم إنشاء التطبيق (معرّف التطبيق %1$s)`,
  _ = `التطبيق الرسمي لمجموعة المجتمع (معرّف العشيرة %1$s)`,
  _ = `عامة - العشيرة: %1$s (معرّف العشيرة %2$s)`,
  _ = `خاصة - العشيرة: %1$s (معرّف العشيرة %2$s)`,
  _ = `تم اختيار %1$s`,
  _ = `كل غير المحلول`,
  _ = `بلا`,
  _ = `تبرئة`,
  _ = `تبرئة (%1$s)`,
  _ = `معاقبة...`,
  _ = `معاقبة... (%1$s)`,
  _ = `التصعيد...`,
  _ = `التصعيد... (%1$s)`,
  _ = `تأكيد المعاقبة`,
  _ = `تأكيد المعاقبة (%1$s)`,
  _ = `إقفال الموضوع`,
  _ = `إقفال الموضوع (%1$s)`,
  _ = `فتح الموضوع`,
  _ = `فتح الموضوع (%1$s)`,
  _ = `الاحتفاظ بالقرار`,
  _ = `الاحتفاظ بالقرار (%1$s)`,
  _ = `إبلاغ كمحتوى مشبوه`,
  _ = `إبلاغ كمحتوى مشبوه (%1$s)`,
  _ = `غير معروف`,
  _ = `مستوى المشرف الخاص بك: %1$s`,
  _ = `المطالبة بالمواضيع`,
  _ = `المطالبة بالمزيد؟`,
  _ = `لم تتبقَ تقارير تحلها. هل تريد المطالبة بالمزيد؟`,
  _ = `المطالبة بالدفعة ذات أعلى أولوية:`,
  _ = `المطالبة (%1$s)`,
  _ = `المطالبة بحالات التصعيد (%1$s)`,
  _ = `المطالبة بحالات Valve فقط (%1$s)`,
  _ = `المطالبة...`,
  _ = `إطلاق الكل`,
  _ = `التالي`,
  _ = `الإشراف`,
  _ = `موافق`,
  _ = `اختر المستوى المراد التصعيد إليه:`,
  _ = `تصعيد %1$s من المواضيع`,
  _ = `تصعيد %1$s من المواضيع`,
  _ = `اختيار سبب التصعيد`,
  _ = `السبب:`,
  _ = `تصعيد`,
  _ = `أي مشرف`,
  _ = `مشرف`,
  _ = `Valve`,
  _ = `Valve فقط`,
  _ = `المشرف مطلوب`,
  _ = `ملاحظة التصعيد:`,
  _ = `حُذفت البيانات الوصفية المتعلقة بتقرير الدردشة هذا بسبب قدمها. يُحتفظ بها لمدة تصل إلى 21 يومًا فقط.`,
  _ = `يمكن تحسين سجل الدردشة هذا برسائل إضافية تم إرسالها بعد التقرير بفترة %1$s`,
  _ = `إزالة المحتوى المُبلغ عنه`,
  _ = `تغيير تصنيف المحتوى المُبلغ عنه`,
  _ = `إقفال الحساب لنشره محتوى مشبوهًا فيه`,
  _ = `إضافة عقوبة مضايقة`,
  _ = `غير معروف (%1$s)`,
  _ = `إزالة المستخدم وتحذيره`,
  _ = `الإزالة والحظر من المركز`,
  _ = `الإزالة والطرد من المجموعة`,
  _ = `تمت المعاقبة`,
  _ = `تمت التبرئة`,
  _ = `%1$s من الإبلاغات عن %2$s من الرسائل الواردة من "%3$s"`,
  _ = `%1$s من الإبلاغات عن %2$s من الرسائل الواردة في "%3$s"`,
  _ = `(موضوع واحد)`,
  _ = `(%1$s من المواضيع)`,
  _ = `حُذفت جميع المنشورات`,
  _ = `حُذفت المشاركات في آخر %1$s من الأيام`,
  _ = `محظور من المجتمع بشكل دائم`,
  _ = `محظور في المجتمع لمدة %1$s من الأيام`,
  _ = `حُذف المُحتوى المُبلغ عنه`,
  _ = `محظور في المركز بشكل دائم`,
  _ = `محظور من المركز لمدة %1$s من الأيام`,
  _ = `تم الإبلاغ كمحتوى مشبوه`,
  _ = `أُعيدت التسمية`,
  _ = `محظور من المقايضة بشكل دائم`,
  _ = `محظور من المقايضة لمدة %1$s من الأيام`,
  _ = `طُرد من المجموعة`,
  _ = `غير معروف`,
  _ = `أدخل رمز طلب الدعم من TicketMaster الذي قدمه هذا المستخدم.`,
  _ = `رمز طلب الدعم:`,
  _ = `نزاع`,
  _ = `إلغاء`,
  _ = `حفظ`,
  _ = `رمز طلب الدعم: `,
  _ = `تمت تبرئته عند المراجعة الأولى`,
  _ = `مُعاقَب عند المراجعة الأولى`,
  _ = `يحتوي هذا الموضوع على عرض مقايضة مرفق`,
  _ = `لا توجد بيانات`,
  _ = `خطأ: تعذر تحميل سجل التدقيق.`,
  _ = `الأسباب:`,
  _ = `%1$s (%2$s)`,
  _ = `لا توجد بلاغات`,
  _ = `تمت التبرئة في %1$s`,
  _ = `تم الحل في %1$s`,
  _ = `محل نزاع في %1$s`,
  _ = `تم حل النزاع في %1$s`,
  _ = `انقر للتحديد...`,
  _ = `الإشراف`,
  _ = `المواضيع المُبلغ عنها`,
  _ = `محل نزاع بالفعل`,
  _ = `جميع أنواع المواضيع`,
  _ = `%1$s لم يتم الحل، %1$s محل نزاع`,
  _ = {
    moderation_moderatorlevel_any: _,
    moderation_moderatorlevel_supervisor: _,
    moderation_moderatorlevel_valveadmin: _,
    moderation_moderatorlevel_unknown: _,
    moderation_statistics: _,
    moderation_chatmetadataerror: _,
    moderation_friendsforduration: _,
    moderation_friends_label: _,
    moderation_chatduration_label: _,
    moderation_senderip_label: _,
    moderation_firstchatted_label: _,
    moderation_reported_message: _,
    moderation_toggle_bbcode: _,
    moderation_image_removed: _,
    moderation_image_obscured: _,
    moderation_reported_time_label: _,
    moderation_network_firstused_time: _,
    moderation_recentchatrooms_label: _,
    moderation_groupname_label: _,
    moderation_roomname_label: _,
    moderation_recentchatpartners_label: _,
    moderation_chat_reportedmessagesfrom: _,
    moderation_chatgroup_reportedmessagesfrom: _,
    moderation_chatgroup_defaultroom: _,
    moderation_chatgroup_reports: _,
    moderation_chatgroup_membercount: _,
    moderation_chatgroup_chatrooms: _,
    moderation_chatgroup_disabled: _,
    moderation_chatgroup_tagline: _,
    moderation_chatgroup_type: _,
    moderation_chatgroup_owner: _,
    moderation_chatgroup_type_privateadhoc: _,
    moderation_chatgroup_type_app: _,
    moderation_chatgroup_type_clanapp: _,
    moderation_chatgroup_type_clanpublic: _,
    moderation_chatgroup_type_clanprivate: _,
    moderation_num_selected: _,
    moderation_select_all_unresolved: _,
    moderation_select_none: _,
    moderation_actions_acquit: _,
    moderation_actions_acquit_multiple: _,
    moderation_actions_sanction: _,
    moderation_actions_sanction_multiple: _,
    moderation_actions_escalate: _,
    moderation_actions_escalate_multiple: _,
    moderation_actions_confirmsanction: _,
    moderation_actions_confirmsanction_multiple: _,
    moderation_actions_lockthread: _,
    moderation_actions_lockthread_multiple: _,
    moderation_actions_unlockthread: _,
    moderation_actions_unlockthread_multiple: _,
    moderation_actions_sustain: _,
    moderation_actions_sustain_multiple: _,
    moderation_actions_suspicious: _,
    moderation_actions_suspicious_multiple: _,
    moderation_actions_unknown: _,
    moderation_moderator_level: _,
    moderation_claim_subjects: _,
    moderation_claim_more: _,
    moderation_claim_more_desc: _,
    moderation_claim_batch_desc: _,
    moderation_claim_amount: _,
    moderation_claim_escalated_amount: _,
    moderation_claim_valve_amount: _,
    moderation_claim_reports: _,
    moderation_release_reports: _,
    moderation_moderatoractions_next: _,
    moderation_moderatoractions_moderate: _,
    moderation_moderatoractions_ok: _,
    moderation_escalation_description: _,
    moderation_escalation_title: _,
    moderation_escalation_title_Plural: _,
    moderation_escalation_reason_select: _,
    moderation_escalation_reason_label: _,
    moderation_escalation_escalate: _,
    moderation_escalationlevel_any: _,
    moderation_escalationlevel_supervisor: _,
    moderation_escalationlevel_valve: _,
    moderation_escalationlevel_valve_desc: _,
    moderation_escalationlevel_supervisor_desc: _,
    moderation_escalation_escalationnote: _,
    moderation_chatmetadata_deleted: _,
    moderation_chatmetadata_futurelogcollection: _,
    moderation_resolutionaction_removed: _,
    moderation_resolutionaction_relabelled: _,
    moderation_resolutionaction_suspicious: _,
    moderation_resolutionaction_harassmentstrike: _,
    moderation_resolutionaction_unknownvalue: _,
    moderation_resolutionaction_removeandwarn: _,
    moderation_resolutionaction_removeandban: _,
    moderation_resolutionaction_removeandkick: _,
    moderation_resolutionstatus_sanctioned: _,
    moderation_resolutionstatus_acquitted: _,
    moderation_subjectgroupsummary_chatmsg: _,
    moderation_subjectgroupsummary_chatgroup: _,
    subject_count: _,
    subject_count_Plural: _,
    moderation_sanction_commenthistorydeleted_forever: _,
    moderation_sanction_commenthistorydeleted: _,
    moderation_sanction_communitybanned_forever: _,
    moderation_sanction_communitybanned: _,
    moderation_sanction_deleted: _,
    moderation_sanction_hubbanned_forever: _,
    moderation_sanction_hubbanned: _,
    moderation_sanction_markassuspicious: _,
    moderation_sanction_relabelled: _,
    moderation_sanction_tradebanned_forever: _,
    moderation_sanction_tradebanned: _,
    moderation_sanction_kickedfromgroup: _,
    moderation_sanction_unknown: _,
    moderation_ownerdispute_description: _,
    moderation_ownerdispute_ticketmastercode: _,
    moderation_ownerdispute_dispute: _,
    moderation_ownerdispute_cancel: _,
    moderation_editownerdisputedetails_save: _,
    moderation_editownerdisputedetails_label: _,
    originalresolution_acquitted: _,
    originalresolution_sanctioned: _,
    has_trade_offer: _,
    subjectauditlog_noentries: _,
    subjectauditlog_error: _,
    reasonlist_title: _,
    reasonlist_reasonwithcount: _,
    contentreportslist_noreports: _,
    contentreportslist_acquitted_at: _,
    contentreportslist_resolved_at: _,
    contentreportslist_disputed_at: _,
    contentreportslist_dispute_resolved_at: _,
    commentsanctiondialog_selectreason: _,
    commentsanctiondialog_moderate: _,
    reportedsubjectlist_header: _,
    moderation_already_owner_disputed: _,
    moderationstats_alltypes: _,
    forumsubjectlist_subjectreportsummary: _,
  };
export {
  _ as commentsanctiondialog_moderate,
  _ as commentsanctiondialog_selectreason,
  _ as contentreportslist_acquitted_at,
  _ as contentreportslist_dispute_resolved_at,
  _ as contentreportslist_disputed_at,
  _ as contentreportslist_noreports,
  _ as contentreportslist_resolved_at,
  _ as default,
  _ as forumsubjectlist_subjectreportsummary,
  _ as has_trade_offer,
  _ as moderation_actions_acquit,
  _ as moderation_actions_acquit_multiple,
  _ as moderation_actions_confirmsanction,
  _ as moderation_actions_confirmsanction_multiple,
  _ as moderation_actions_escalate,
  _ as moderation_actions_escalate_multiple,
  _ as moderation_actions_lockthread,
  _ as moderation_actions_lockthread_multiple,
  _ as moderation_actions_sanction,
  _ as moderation_actions_sanction_multiple,
  _ as moderation_actions_suspicious,
  _ as moderation_actions_suspicious_multiple,
  _ as moderation_actions_sustain,
  _ as moderation_actions_sustain_multiple,
  _ as moderation_actions_unknown,
  _ as moderation_actions_unlockthread,
  _ as moderation_actions_unlockthread_multiple,
  _ as moderation_already_owner_disputed,
  _ as moderation_chat_reportedmessagesfrom,
  _ as moderation_chatduration_label,
  _ as moderation_chatgroup_chatrooms,
  _ as moderation_chatgroup_defaultroom,
  _ as moderation_chatgroup_disabled,
  _ as moderation_chatgroup_membercount,
  _ as moderation_chatgroup_owner,
  _ as moderation_chatgroup_reportedmessagesfrom,
  _ as moderation_chatgroup_reports,
  _ as moderation_chatgroup_tagline,
  _ as moderation_chatgroup_type,
  _ as moderation_chatgroup_type_app,
  _ as moderation_chatgroup_type_clanapp,
  _ as moderation_chatgroup_type_clanprivate,
  _ as moderation_chatgroup_type_clanpublic,
  _ as moderation_chatgroup_type_privateadhoc,
  _ as moderation_chatmetadata_deleted,
  _ as moderation_chatmetadata_futurelogcollection,
  _ as moderation_chatmetadataerror,
  _ as moderation_claim_amount,
  _ as moderation_claim_batch_desc,
  _ as moderation_claim_escalated_amount,
  _ as moderation_claim_more,
  _ as moderation_claim_more_desc,
  _ as moderation_claim_reports,
  _ as moderation_claim_subjects,
  _ as moderation_claim_valve_amount,
  _ as moderation_editownerdisputedetails_label,
  _ as moderation_editownerdisputedetails_save,
  _ as moderation_escalation_description,
  _ as moderation_escalation_escalate,
  _ as moderation_escalation_escalationnote,
  _ as moderation_escalation_reason_label,
  _ as moderation_escalation_reason_select,
  _ as moderation_escalation_title,
  _ as moderation_escalation_title_Plural,
  _ as moderation_escalationlevel_any,
  _ as moderation_escalationlevel_supervisor,
  _ as moderation_escalationlevel_supervisor_desc,
  _ as moderation_escalationlevel_valve,
  _ as moderation_escalationlevel_valve_desc,
  _ as moderation_firstchatted_label,
  _ as moderation_friends_label,
  _ as moderation_friendsforduration,
  _ as moderation_groupname_label,
  _ as moderation_image_obscured,
  _ as moderation_image_removed,
  _ as moderation_moderator_level,
  _ as moderation_moderatoractions_moderate,
  _ as moderation_moderatoractions_next,
  _ as moderation_moderatoractions_ok,
  _ as moderation_moderatorlevel_any,
  _ as moderation_moderatorlevel_supervisor,
  _ as moderation_moderatorlevel_unknown,
  _ as moderation_moderatorlevel_valveadmin,
  _ as moderation_network_firstused_time,
  _ as moderation_num_selected,
  _ as moderation_ownerdispute_cancel,
  _ as moderation_ownerdispute_description,
  _ as moderation_ownerdispute_dispute,
  _ as moderation_ownerdispute_ticketmastercode,
  _ as moderation_recentchatpartners_label,
  _ as moderation_recentchatrooms_label,
  _ as moderation_release_reports,
  _ as moderation_reported_message,
  _ as moderation_reported_time_label,
  _ as moderation_resolutionaction_harassmentstrike,
  _ as moderation_resolutionaction_relabelled,
  _ as moderation_resolutionaction_removeandban,
  _ as moderation_resolutionaction_removeandkick,
  _ as moderation_resolutionaction_removeandwarn,
  _ as moderation_resolutionaction_removed,
  _ as moderation_resolutionaction_suspicious,
  _ as moderation_resolutionaction_unknownvalue,
  _ as moderation_resolutionstatus_acquitted,
  _ as moderation_resolutionstatus_sanctioned,
  _ as moderation_roomname_label,
  _ as moderation_sanction_commenthistorydeleted,
  _ as moderation_sanction_commenthistorydeleted_forever,
  _ as moderation_sanction_communitybanned,
  _ as moderation_sanction_communitybanned_forever,
  _ as moderation_sanction_deleted,
  _ as moderation_sanction_hubbanned,
  _ as moderation_sanction_hubbanned_forever,
  _ as moderation_sanction_kickedfromgroup,
  _ as moderation_sanction_markassuspicious,
  _ as moderation_sanction_relabelled,
  _ as moderation_sanction_tradebanned,
  _ as moderation_sanction_tradebanned_forever,
  _ as moderation_sanction_unknown,
  _ as moderation_select_all_unresolved,
  _ as moderation_select_none,
  _ as moderation_senderip_label,
  _ as moderation_statistics,
  _ as moderation_subjectgroupsummary_chatgroup,
  _ as moderation_subjectgroupsummary_chatmsg,
  _ as moderation_toggle_bbcode,
  _ as moderationstats_alltypes,
  _ as originalresolution_acquitted,
  _ as originalresolution_sanctioned,
  _ as reasonlist_reasonwithcount,
  _ as reasonlist_title,
  _ as reportedsubjectlist_header,
  _ as subject_count,
  _ as subject_count_Plural,
  _ as subjectauditlog_error,
  _ as subjectauditlog_noentries,
};
