var _ = `latam`,
  _ = `Ver en el Mercado de la Comunidad`,
  _ = `Ver mis anuncios`,
  _ = `A partir de: %1$s`,
  _ = `Volumen: %1$s vendido(s) en las últimas 24 horas`,
  _ = `Vender`,
  _ = `Etiquetas: `,
  _ = `Protegido contra intercambios`,
  _ = `Los artículos protegidos contra intercambios no se pueden modificar, consumir ni transferir.`,
  _ = `%1$s: %2$s`,
  _ = `En el Mercado`,
  _ = `Mientras tengas este artículo a la venta, no podrás modificarlo ni consumirlo.`,
  _ = `Este artículo tiene un valor de: %1$s`,
  _ = `%1$s gemas`,
  _ = `Transformar en gemas...`,
  _ = `Este artículo puede transformarse en gemas para utilizarlas para crear paquetes de refuerzo. <1>Obtén más información aquí</1>.`,
  _ = `Accesorios`,
  _ = {
    language: _,
    SellOnMarket_View: _,
    SellOnMarket_ViewListing: _,
    SellOnMarket_LowestPrice: _,
    SellOnMarket_Volume: _,
    SellOnMarket_SellThisItem: _,
    ItemDescription_Tags: _,
    ItemDescription_TradeProtected: _,
    ItemDescription_TradeProtectedTooltip: _,
    ItemDescription_AssetPropertyLabelColonValue: _,
    ItemDescription_ListedItem: _,
    ItemDescription_ListedItemTooltip: _,
    ItemDescription_ThisItemIsWorthGems: _,
    ItemDescription_XGems: _,
    ItemDescription_TurnIntoGemsButton: _,
    ItemDescription_GemDescription: _,
    ItemDescription_AccessoriesList_Title: _,
  };
export {
  _ as ItemDescription_AccessoriesList_Title,
  _ as ItemDescription_AssetPropertyLabelColonValue,
  _ as ItemDescription_GemDescription,
  _ as ItemDescription_ListedItem,
  _ as ItemDescription_ListedItemTooltip,
  _ as ItemDescription_Tags,
  _ as ItemDescription_ThisItemIsWorthGems,
  _ as ItemDescription_TradeProtected,
  _ as ItemDescription_TradeProtectedTooltip,
  _ as ItemDescription_TurnIntoGemsButton,
  _ as ItemDescription_XGems,
  _ as SellOnMarket_LowestPrice,
  _ as SellOnMarket_SellThisItem,
  _ as SellOnMarket_View,
  _ as SellOnMarket_ViewListing,
  _ as SellOnMarket_Volume,
  _ as default,
  _ as language,
};
