var _ = `Communitymarkt doorzoeken`,
  _ = `Filters opnieuw instellen`,
  _ = `Zoeken`,
  _ = `Spel selecteren ...`,
  _ = `Onlangs gespeelde spellen met voorwerpen`,
  _ = `Populaire spellen met voorwerpen`,
  _ = `Selectie wissen`,
  _ = `Zoeken ...`,
  _ = `Zoeken in %1$s ...`,
  _ = `Voorwerpen in het spel`,
  _ = `Steam-voorwerpen`,
  _ = `Voorwerpsoort`,
  _ = `Dit spel heeft geen marktfilters.`,
  _ = `Klik op Zoeken om beschikbare voorwerpen te bekijken.`,
  _ = `Er is een fout opgetreden bij het laden van de filters voor dit spel.`,
  _ = `Prijs`,
  _ = `Min. prijs`,
  _ = `Max. prijs`,
  _ = `Alle`,
  _ = `Overige`,
  _ = `Filteren ...`,
  _ = `Filteren op spel ...`,
  _ = `Bètafunctie – feedback geven`,
  _ = `Zoeken in voorwerpnamen op de communitymarkt ...`,
  _ = `Wapenkisten, stickercapsules, souvenirpakketten, etc.`,
  _ = `Steam-communitymarkt`,
  _ = `Verhandel voorwerpen met leden van de community met je Steam-portemonneesaldo`,
  _ = `Meer informatie`,
  _ = `De markt doorzoeken`,
  _ = `Nieuwe zoekopdracht ...`,
  _ = `Filters`,
  _ = `De bèta van de Steam-communitymarkt afsluiten`,
  _ = `Feedback geven`,
  _ = `Dit voorwerp is een handelsartikel waarbij alle individuele voorwerpen praktisch identiek zijn. Individuele vermeldingen zijn niet toegankelijk - je kunt opdracht geven om voorwerpen te kopen voor een specifieke prijs, waarbij de goedkoopste vermelding automatisch gekoppeld wordt aan de hoogste aankoopopdracht.`,
  _ = `%1$s resultaat gevonden`,
  _ = `%1$s resultaten gevonden`,
  _ = `%1$s resultaat gevonden voor:`,
  _ = `%1$s resultaten gevonden voor:`,
  _ = `Resultaten voor:`,
  _ = `%2$s vermelding gevonden`,
  _ = `%2$s vermeldingen gevonden`,
  _ = `Populariteit`,
  _ = `Naam (A tot Z)`,
  _ = `Naam (Z tot A)`,
  _ = `Prijs (laag naar hoog)`,
  _ = `Prijs (hoog naar laag)`,
  _ = `Aantal (laag naar hoog)`,
  _ = `Aantal (hoog naar laag)`,
  _ = `%1$s (laag naar hoog)`,
  _ = `%1$s (hoog naar laag)`,
  _ = `Sorteren op:`,
  _ = `Zoeken`,
  _ = `Zoeken ...`,
  _ = `Kopen`,
  _ = `Verkopen`,
  _ = `Nu kopen`,
  _ = `Aankooporder plaatsen ...`,
  _ = `Bestelling plaatsen:`,
  _ = `Sluiten`,
  _ = `Aantal te koop: %1$s`,
  _ = `Aantal: %1$s`,
  _ = `Van %1$s`,
  _ = `%1$s aangesloten`,
  _ = `Resultaten filteren ...`,
  _ = `Geavanceerd zoeken`,
  _ = `Geavanceerd zoeken`,
  _ = `Naar een voorwerp zoeken ...`,
  _ = `Markt-startpagina`,
  _ = `Populaire spellen`,
  _ = `Beschrijvingen opnemen in zoekopdracht`,
  _ = `Sommige oudere voorwerpen maken gebruik van tekst om belangrijke voorwerpeigenschappen te beschrijven en deze tekst kan niet worden doorzocht met behulp van onderstaande filters. Met deze optie kun je zoeken in de volledige beschrijving in plaats van alleen de naam van het voorwerp.`,
  _ = `Filters`,
  _ = `Zoekopdracht wissen`,
  _ = `Aangepaste filtertekst invoeren ...`,
  _ = `Na aankoop zal dit voorwerp:`,
  _ = `een dag niet ruilbaar zijn`,
  _ = `een week niet ruilbaar zijn`,
  _ = `%1$s dagen niet ruilbaar zijn`,
  _ = `niet ruilbaar zijn`,
  _ = `een dag niet op de Steam-communitymarkt kunnen worden gezet`,
  _ = `een week niet op de Steam-communitymarkt kunnen worden gezet`,
  _ = `%1$s dagen niet op de Steam-communitymarkt kunnen worden gezet`,
  _ = `direct op de Steam-communitymarkt kunnen worden doorverkocht`,
  _ = `%1$s: %2$s - %3$s`,
  _ = `%1$s: '%2$s'`,
  _ = `Een voorwerp kopen`,
  _ = `Naam`,
  _ = `Prijs`,
  _ = `Subtotaal:`,
  _ = `%1$s-vergoeding (%2$s%):`,
  _ = `Spelvergoeding (%1$s%):`,
  _ = `Steam-transactiekosten (%1$s%):`,
  _ = `Lokale verkoopbelasting (%1$s):`,
  _ = `Totaal:`,
  _ = `Betalingswijze:`,
  _ = `Mijn Steam-portemonnee`,
  _ = `Steam-account:`,
  _ = `Factuuradres:`,
  _ = `Voornaam`,
  _ = `Achternaam`,
  _ = `Factureringsadres`,
  _ = `Factureringsadres, regel 2`,
  _ = `Stad`,
  _ = `Staat/provincie`,
  _ = `Postcode`,
  _ = `Land`,
  _ = `Mijn adres bewaren zodat ik de volgende keer makkelijker een bestelling kan plaatsen`,
  _ = `Saldo toevoegen`,
  _ = `Kopen`,
  _ = `Ik ga akkoord met de voorwaarden van de %1$s (laatst bijgewerkt op %2$s)`,
  _ = `Steam-gebruikersovereenkomst (Steam Subscriber Agreement)`,
  _ = `Je moet akkoord gaan met de Steam-gebruikersovereenkomst (Steam Subscriber Agreement) om deze transactie te kunnen voltooien.`,
  _ = `Door op Kopen te klikken, ga je ermee akkoord dat je onmiddellijke toegang tot de digitale inhoud krijgt. Je hebt dan niet meer de mogelijkheid om je aan de aankoop te onttrekken. De aankoop is definitief.`,
  _ = `Er is een probleem opgetreden bij het kopen van je voorwerp. Mogelijk is de vermelding verwijderd. Vernieuw de pagina en probeer het opnieuw.`,
  _ = `Er is een probleem opgetreden bij het kopen van je voorwerp. Tijdens het wachten op je bevestiging is er iets fout gegaan. Vernieuw de pagina en probeer het opnieuw.`,
  _ = `De volgende velden zijn verplicht:`,
  _ = `Voer een geldig militair adres in`,
  _ = `Vul een geldige postcode in`,
  _ = `Gefeliciteerd met je aankoop! Je kunt je nieuwe aankoop bekijken in <1>je inventaris</1>.`,
  _ = `Inventaris weergeven`,
  _ = `Extra bevestiging vereist`,
  _ = `Wachten tot je de aankoop bevestigt ...`,
  _ = `Sommige aankopen moeten ter beveiliging via je mobiele Steam-app worden bevestigd.`,
  _ = `Sommige aankopen moeten ter beveiliging met een Steam Guard-code via e-mail worden bevestigd.`,
  _ = `Sommige aankopen moeten ter beveiliging via je mobiele Steam-app of e-mail worden bevestigd.`,
  _ = `Bevestig via de mobiele Steam-app om je aankoop te voltooien ...`,
  _ = `Bevestig via e-mail om je aankoop te voltooien ...`,
  _ = `Bevestig via de mobiele Steam-app of e-mail om je aankoop te voltooien ...`,
  _ = `Aankoop voltooid`,
  _ = `Sluiten`,
  _ = `Inventaris weergeven`,
  _ = `Mijn adres bewaren zodat ik de volgende keer sneller een bestelling kan plaatsen`,
  _ = `Deze vermelding is niet meer beschikbaar`,
  _ = `Niet beschikbaar`,
  _ = `Deze vermelding is niet meer beschikbaar en het voorwerp kan niet meer gekocht worden.`,
  _ = `(Mijn vermelding)`,
  _ = `Kopen – %1$s`,
  _ = `Aankooporder plaatsen`,
  _ = `Wat voor type voorwerp wil je kopen?`,
  _ = `Selecteer een voorwerp ...`,
  _ = `Welke prijs wil je betalen:`,
  _ = `(per voorwerp)`,
  _ = `Hoeveel wil je er kopen:`,
  _ = `Maximumprijs %1$s:`,
  _ = `Dit is het hoogste bedrag dat je in rekening gebracht kan worden voor deze aankooporder. Voorwerpen worden voor de laagst mogelijke prijs gekocht, dus je order kan uiteindelijk goedkoper uitvallen dan dit bedrag.`,
  _ = `Overeenkomende voorwerpvermeldingen voor je gewenste prijs aan het zoeken ...`,
  _ = `Aankoop geslaagd! Je voorwerp bevindt zich in je inventaris en je ontvangstbewijs is naar je toe gemaild.`,
  _ = `Gelukt! Je aankooporder is geplaatst.`,
  _ = `Je wordt automatisch via e-mail op de hoogte gesteld wanneer de aankoop is voltooid. Je kunt deze aankooporder bovenaan de pagina of vanuit de markt annuleren.`,
  _ = `Sorry! We ondervinden problemen bij de communicatie met de Steam-servers over je bestelling. Controleer of je bestelling echt is aangemaakt. Probeer het later opnieuw als dat niet zo is.`,
  _ = `De minimumprijs per eenheid is %1$s`,
  _ = `%1$s of minder`,
  _ = `%1$s of meer`,
  _ = `Prijs`,
  _ = `Aantal`,
  _ = `%1$s te koop vanaf %2$s`,
  _ = `Er zijn geen actieve vermeldingen voor dit voorwerp`,
  _ = `%1$s verzoeken om te kopen voor %2$s of minder`,
  _ = `Er zijn geen actieve aankooporders voor dit item.`,
  _ = `Selecteer hierboven een tabblad om de gegevens van de aankooporder te bekijken`,
  _ = `Staat je gewenste voorwerp of bedrag er niet bij?`,
  _ = `Zie je geen goede prijs?`,
  _ = `Koop- en verkooporders (cumulatief)`,
  _ = `1 aankooporder voor %2$s of meer`,
  _ = `%1$s aankooporders voor %2$s of meer`,
  _ = `1 verkooporder voor %2$s of minder`,
  _ = `%1$s verkooporders voor %2$s of minder`,
  _ = `1 verzoek om te kopen voor <1>%2$s</1>`,
  _ = `%3$s verzoeken om te kopen voor <1>%2$s of minder</1>`,
  _ = `Mediane verkoopprijzen`,
  _ = `Week`,
  _ = `Maand`,
  _ = `Jaar`,
  _ = `Aller tijden`,
  _ = `%1$s verkocht`,
  _ = `Prijs`,
  _ = `Aantal`,
  _ = `Geen gegevens voor deze periode`,
  _ = `Geen aankoopgegevens`,
  _ = `n.v.t.`,
  _ = `NAAM`,
  _ = `PRIJS`,
  _ = `AANTAL`,
  _ = `GEPLAATST OP`,
  _ = `Annuleren`,
  _ = `Verwijderen`,
  _ = `Mijn actieve bestellingen`,
  _ = `Verkooporders`,
  _ = `Aankooporders`,
  _ = `Kopen – Mijn bestellingen`,
  _ = `Verkopen – Mijn vermeldingen`,
  _ = `Er is een probleem opgetreden bij het laden van de bestellingsgegevens van dit voorwerp.`,
  _ = `Er zijn geen actieve bestellingen voor dit voorwerp.`,
  _ = `Er zijn geen actieve aankooporders voor dit voorwerp.`,
  _ = `Je biedt dit voorwerp niet te koop aan. Verkoop voorwerpen uit je inventaris of klik op de knop Verkopen op deze pagina.`,
  _ = `Aantal: %1$s`,
  _ = `Alle %1$s weergeven`,
  _ = `Er is een probleem opgetreden bij het annuleren van je bestelling. Probeer het later opnieuw.`,
  _ = `Er is een probleem opgetreden bij het verwijderen van je vermelding. Probeer het later opnieuw.`,
  _ = `Een vermelding verwijderen`,
  _ = `Wil je de vermelding van %1$s verwijderen en het voorwerp terugzetten in je inventaris?`,
  _ = `Wil je deze vermelding verwijderen en het voorwerp terugzetten in je inventaris?`,
  _ = `Ja, vermelding verwijderen`,
  _ = `Nee`,
  _ = `Je vermelding is verwijderd`,
  _ = `Een voorwerp uit je inventaris kiezen`,
  _ = `Wat is een aankooporder?`,
  _ = `Stel je gewenste prijs in en het voorwerp wordt automatisch gekocht wanneer het tegen die prijs beschikbaar is.`,
  _ = `Steam zorgt ervoor dat je de best mogelijke prijs betaalt.`,
  _ = `Voor dit voorwerp zullen aankooporders worden gekoppeld aan de goedkoopste opties ongeacht eventuele unieke kenmerken.`,
  _ = `%1$s en hoger`,
  _ = `Helaas!`,
  _ = `Er is een fout opgetreden bij het verwerken van je verzoek:`,
  _ = `Je hebt in korte tijd te veel verzoeken verzonden. Wacht even en probeer het later opnieuw.`,
  _ = `Mogelijke inhoud:`,
  _ = `Er is een probleem opgetreden bij het laden van deze inhoud`,
  _ = `Het gevraagde voorwerp bestaat mogelijk niet of er is een tijdelijk probleem waardoor het niet geladen kan worden. Probeer het later opnieuw.`,
  _ = `Vermeldingen filteren ...`,
  _ = `Geen vermeldingen gevonden`,
  _ = `Meer opties ...`,
  _ = `Filteren ...`,
  _ = `Info`,
  _ = `Verkoopgrafiek`,
  _ = `Aankooporders`,
  _ = `Filters`,
  _ = `Min.`,
  _ = `Max.`,
  _ = `Accessoires`,
  _ = `Alle`,
  _ = `Geen`,
  _ = `%1$s: %2$s`,
  _ = `Je kunt dit voorwerp niet kopen, omdat de aan- en verkoop van dit type voorwerp geblokkeerd is in jouw land.`,
  _ = `Je kunt dit voorwerp niet kopen, omdat de aankoop van dit type voorwerp geblokkeerd is in jouw land.`,
  _ = `Deze vermelding beschikt nog niet over unieke of verbeterde afbeeldingen. De hier weergegeven afbeelding kan enigszins afwijken van het daadwerkelijke voorwerp.`,
  _ = `Achtergrond weergeven`,
  _ = `Er is een fout opgetreden bij het weergeven van deze vermelding`,
  _ = `Je kunt op dit moment niets op de markt kopen of verkopen om de volgende reden:`,
  _ = `Je kunt op dit moment niets op de markt kopen of verkopen om de volgende redenen:`,
  _ = `Resultaten weergeven`,
  _ = `Als raster weergeven`,
  _ = `Als lijst weergeven`,
  _ = `Er is een probleem opgetreden bij het laden van de aanvullende resultaten. Probeer het later opnieuw.`,
  _ = `Je probeert een voorwerp te bekijken voor een nieuw spel op Steam dat je nog nooit hebt gespeeld. Wees voorzichtig met dit voorwerp.`,
  _ = `Klik hier om dit voorwerp toch te bekijken`,
  _ = `Filteren op spel`,
  _ = `Alle spellen weergeven`,
  _ = `Je account is momenteel vergrendeld.`,
  _ = `Informatie over deze vergrendeling vind je door op de rode balk te klikken die rechtsboven in de Steam-client wordt weergegeven als je bent ingelogd. Neem contact op met Steam Support voor meer informatie.`,
  _ = `Je account is momenteel vergrendeld. Informatie over deze vergrendeling vind je door op de rode balk te klikken die rechtsboven in de Steam-client wordt weergegeven als je bent ingelogd.`,
  _ = `Om deze beperking te verwijderen ...`,
  _ = `Je account heeft momenteel een ruilban.`,
  _ = `Dit account kan momenteel geen gebruik maken van de Steam-communitymarkt.`,
  _ = `Een ruilban kan tijdelijk of permanent zijn. Om te zien wanneer de ruilban verloopt, klik je op de rode balk die rechtsboven in de Steam-client wordt weergegeven als je bent ingelogd.`,
  _ = `Je account heeft een ruilban. Om te zien wanneer de ruilban verloopt, klik je op de rode balk die rechtsboven in de Steam-client wordt weergegeven als je bent ingelogd.`,
  _ = `Meer informatie ...`,
  _ = `Je moet een Steam-aankoop hebben die tussen de %1$s dagen en een jaar oud is, zonder recente terugvorderingen of betalingsgeschillen.`,
  _ = `Koop iets in de Steam-winkel. Portemonneesaldo, spellen en DLC zijn geldige aankopen, maar cd-sleutels en geschenken niet. Steam Support kan deze beperking niet verwijderen.`,
  _ = `Je moet een Steam-aankoop hebben die tussen de %1$s dagen en een jaar oud is, zonder recente terugvorderingen of betalingsgeschillen. Steam Support kan deze beperking niet verwijderen.`,
  _ = `Zo te zien heb je wel een geldige aankoop gedaan in de Steam-winkel, maar was dat minder dan %1$s dagen geleden.`,
  _ = `We vereisen een Steam-aankoop die tussen de %1$s dagen en een jaar oud is, zonder recente terugvorderingen of betalingsgeschillen. Zo te zien heb je wel een geldige aankoop gedaan in de Steam-winkel, maar was dat minder dan %1$s dagen geleden. Steam Support kan deze beperking niet verwijderen.`,
  _ = `Het wachtwoord van je account is recent opnieuw ingesteld.`,
  _ = `Deze beperking wordt %1$s dagen na het opnieuw instellen van je wachtwoord automatisch verwijderd. Als het account lange tijd niet is gebruikt, kan deze beperking tot %2$s dagen duren. Dit type beperking wordt alleen opgelegd na het volledig opnieuw instellen van je wachtwoord (een 'reset'). Er gelden geen beperkingen als je je wachtwoord gewoon wijzigt. Steam Support kan geen beperkingen verwijderen.`,
  _ = `Het wachtwoord van je Steam-account is onlangs opnieuw ingesteld. Om gebruikers te beschermen van wie het e-mailaccount of andere accounts zijn gekraakt, beperken we de toegang tot de communitymarkt voor %1$s dagen na het opnieuw instellen van het wachtwoord.`,
  _ = `Je hebt onlangs geld toegevoegd aan je Steam-portemonnee met een ongeverifieerde creditcard die recent vaker is gebruikt dan normaal. Je kunt proberen <1>het saldo nu te verifiëren</1> of wachten totdat de beperking automatisch wordt verwijderd.

LET OP: Het verifiëren van het saldo werkt niet met alle banken en creditcards. Als je je kaart niet kunt verifiëren, moet je wachten totdat Steam je betaalmethode heeft geverifieerd. Steam Support kan de verificatie-afschrijvingen niet delen of omzetten en kan deze beperking niet verwijderen.`,
  _ = `Je hebt onlangs geld toegevoegd aan je Steam-portemonnee met een PayPal-account of een ongeverifieerde betaalmethode die recent vaker is gebruikt dan normaal. Je kunt de markt een paar dagen niet gebruiken totdat het saldo is geverifieerd.`,
  _ = `Je hebt onlangs geld toegevoegd aan je Steam-portemonnee met een nieuw PayPal-account of een ongeverifieerde betaalmethode die recent vaker is gebruikt dan normaal. Je kunt de markt een paar dagen niet gebruiken totdat het saldo is geverifieerd.`,
  _ = `Je hebt onlangs een digitale cadeaukaart van een vriend geaccepteerd.`,
  _ = `Je hebt onlangs een digitale cadeaukaart van een vriend geaccepteerd. Je kunt de communitymarkt daarom tijdelijk niet gebruiken. De markt is %1$s dagen nadat je vriend de cadeaukaart heeft gekocht weer beschikbaar.`,
  _ = `Steam heeft problemen met de cookies van je browser.`,
  _ = `Je cookie lijkt ongeldig. Probeer uit te loggen bij Steam en dan weer in te loggen. Controleer of het opslaan van cookies is ingeschakeld in je browser en of er geen browserextensies zijn geïnstalleerd die de werking van de Steam-cookie in de weg kunnen staan.`,
  _ = `Cookies zijn mogelijk niet ingeschakeld in je browser. Controleer of cookies in je browser zijn toegestaan en probeer uit te loggen en opnieuw in te loggen.`,
  _ = `Je logt in op de markt via een apparaat dat al %1$s dagen niet door Steam Guard wordt beschermd.`,
  _ = `Als je een apparaat hebt dat al geverifieerd is, kun je dat apparaat gebruiken voor de markt. Anders moet je wachten tot we dit apparaat hebben geverifieerd.`,
  _ = `Je bent ingelogd met een nieuw apparaat of een nieuwe webbrowser. Om de voorwerpen in je inventaris te beschermen, kun je de markt %1$s dagen lang niet op dit apparaat gebruiken.`,
  _ = `Je hebt onlangs een terugvordering voor een transactie ontvangen als Steam-portemonneesaldo.`,
  _ = `Je kunt de markt tot %1$s dagen na je meest recente terugvordering niet gebruiken. Steam Support kan geen beperkingen verwijderen.`,
  _ = `Je hebt onlangs een transactie in je Steam-portemonnee terugbetaald gekregen. Je kunt de markt tot %1$s dagen na je meest recente terugvordering niet gebruiken.`,
  _ = `Je account is beperkt.`,
  _ = `Je account is beperkt en heeft daarom geen toegang tot bepaalde Steam-functies, zoals de Steam-communitymarkt.`,
  _ = `Je account is beperkt en heeft daarom geen toegang tot bepaalde Steam-functies, zoals de Steam-communitymarkt.`,
  _ = `Steam Guard is onlangs gereset of ingeschakeld op je account. Je moet wachten tot %1$s dagen nadat Steam Guard is ingeschakeld.`,
  _ = `Je moet wachten totdat Steam Guard 15 dagen is ingeschakeld op je account. Steam Support kan deze beperking niet verwijderen.`,
  _ = `Je account moet minstens %1$s dagen beschermd zijn door Steam Guard.`,
  _ = `Je moet Steam Guard op je account hebben geactiveerd. Controleer of je e-mail is geverifieerd en of je twee keer op je account bent ingelogd na het activeren van Steam Guard.`,
  _ = `Je account moet minstens %1$s dagen beschermd zijn door Steam Guard.`,
  _ = `Aangenomen dat niets je toegang verder beperkt, zul je de communitymarkt kunnen gebruiken op %1$s`,
  _ = `Je account heeft een tijdelijke afkoelperiode voor ruil- en marktfuncties.`,
  _ = {
    AdvancedSearch_Heading: _,
    AdvancedSearch_Reset: _,
    AdvancedSearch_Search: _,
    AdvancedSearch_AppSelect_Placeholder: _,
    AdvancedSearch_AppSelect_YourGames: _,
    AdvancedSearch_AppSelect_PopularGames: _,
    AdvancedSearch_AppSelect_Clear: _,
    AdvancedSearch_TextSearch_Placeholder: _,
    AdvancedSearch_TextSearch_PlaceholderWithApp: _,
    AdvancedSearch_TypeSwitch_InGame: _,
    AdvancedSearch_TypeSwitch_SteamItems: _,
    AdvancedSearch_SteamItems_TypeLabel: _,
    AdvancedSearch_NoFacets: _,
    AdvancedSearch_NoFacetsSearch: _,
    AdvancedSearch_FacetLoadError: _,
    AdvancedSearch_PriceFieldLabel: _,
    AdvancedSearch_MinPricePlaceholder: _,
    AdvancedSearch_MaxPricePlaceholder: _,
    AdvancedSearch_CustomFilter_All: _,
    AdvancedSearch_CustomFilter_Other: _,
    AdvancedSearch_FilterGeneric_Placeholder: _,
    AdvancedSearch_AppSelect_FilterPlaceholder: _,
    AdvancedSearch_BetaTag: _,
    AdvancedSearch_TextSearch_Tooltip: _,
    AdvancedSearch_CSContainers_Tooltip: _,
    Header_MarketTitle: _,
    Header_MarketDescription: _,
    Header_LearnMore: _,
    Header_Search_Placeholder: _,
    Header_Search_PlaceholderNew: _,
    Header_Search_Filters: _,
    Header_OptOut: _,
    Header_GiveFeedback: _,
    CommodityExplanation: _,
    Search_AmountFound: _,
    Search_AmountFound_Plural: _,
    Search_AmountFoundFor: _,
    Search_AmountFoundFor_Plural: _,
    Search_ResultsFoundFor: _,
    Search_ListingsFound: _,
    Search_ListingsFound_Plural: _,
    SortBy_Popularity: _,
    SortBy_Name_Asc: _,
    SortBy_Name_Desc: _,
    SortBy_Price_Asc: _,
    SortBy_Price_Desc: _,
    SortBy_Quantity_Asc: _,
    SortBy_Quantity_Desc: _,
    SortBy_AssetProperty_Asc: _,
    SortBy_AssetProperty_Desc: _,
    SortBy_Label: _,
    Search_Button: _,
    Search_Placeholder: _,
    Button_Buy: _,
    Button_Sell: _,
    Button_BuyNow: _,
    Button_BuyOrder: _,
    BuyOrder_PlaceOrderHeader: _,
    Button_Close: _,
    Search_ListingQuantity: _,
    Search_ListingQuantity_Abbreviation: _,
    Bucket_PriceFrom: _,
    AccessorySearch_AttachedAccessoryType: _,
    FilterResults_Placeholder: _,
    AdvancedSearch_Header: _,
    AdvancedSearch_Link: _,
    MarketSearch_Placeholder: _,
    Breadcrumbs_Home: _,
    MarketHome_PopularApps: _,
    AdvancedSearch_IncludeDescriptions: _,
    AdvancedSearch_IncludeDescriptions_Tooltip: _,
    MarketSearch_FilterColumn_Header: _,
    MarketSearch_Reset: _,
    Listings_TextFilter_Placeholder: _,
    Economy_Market_Purchase_Restrictions: _,
    Economy_Market_Purchase_TradableRestriction_1Day: _,
    Economy_Market_Purchase_TradableRestriction_7Days: _,
    Economy_Market_Purchase_TradableRestriction_NDays: _,
    Economy_Market_Purchase_TradableRestriction_Permanent: _,
    Economy_Market_Purchase_MarketableRestriction_1Day: _,
    Economy_Market_Purchase_MarketableRestriction_7Days: _,
    Economy_Market_Purchase_MarketableRestriction_NDays: _,
    Economy_Market_Purchase_MarketableRestriction_None: _,
    AssetPropertyNumberFilterRange: _,
    AssetPropertyStringFilter: _,
    PurchaseDialog_Header: _,
    PurchaseDialog_Details_Column_Name: _,
    PurchaseDialog_Details_Column_Price: _,
    PurchaseDialog_Subtotal_Label: _,
    PurchaseDialog_PublisherFee_Label: _,
    PurchaseDialog_PublisherFee_Label_Generic: _,
    PurchaseDialog_SteamFee_Label: _,
    PurchaseDialog_LocalTax_Label: _,
    PurchaseDialog_Total_Label: _,
    PurchaseDialog_PaymentMethod_Label: _,
    PurchaseDialog_PaymentMethod_Wallet: _,
    PurchaseDialog_SteamAccount_Label: _,
    PurchaseDialog_BillingInfo_Label: _,
    PurchaseDialog_BillingInfo_FirstName: _,
    PurchaseDialog_BillingInfo_LastName: _,
    PurchaseDialog_BillingInfo_Address: _,
    PurchaseDialog_BillingInfo_AddressLine2: _,
    PurchaseDialog_BillingInfo_City: _,
    PurchaseDialog_BillingInfo_StateProvince: _,
    PurchaseDialog_BillingInfo_ZipPostal: _,
    PurchaseDialog_BillingInfo_Country: _,
    PurchaseDialog_BillingInfo_SaveInfo: _,
    PurchaseDialog_Action_AddFunds: _,
    PurchaseDialog_Action_Purchase: _,
    PurchaseDialog_SSA_Link: _,
    PurchaseDialog_SSA_Link_Title: _,
    PurchaseDialog_SSA_Fail: _,
    PurchaseDialog_EU_SSA: _,
    PurchaseDialog_Error_ServerGeneric: _,
    PurchaseDialog_Error_NoConfirmation: _,
    PurchaseDialog_Error_MissingRequired: _,
    PurchaseDialog_Error_InvalidMilitaryCity: _,
    PurchaseDialog_Error_InvalidPostal: _,
    PurchaseDialog_PurchaseComplete: _,
    PurchaseDialog_Button_ViewInventory: _,
    PurchaseDialog_Confirmation_Title: _,
    PurchaseDialog_Confirmation_Title_Wait: _,
    PurchaseDialog_Confirmation_Body_Mobile: _,
    PurchaseDialog_Confirmation_Body_Email: _,
    PurchaseDialog_Confirmation_Body_Unknown: _,
    PurchaseDialog_Confirmation_Description_Mobile: _,
    PurchaseDialog_Confirmation_Description_Email: _,
    PurchaseDialog_Confirmation_Description_Unknown: _,
    PurchaseDialog_Purchase_Successful: _,
    PurchaseDialog_Close: _,
    PurchaseDialog_ViewInventory: _,
    PurhcaseDialog_SaveMyAddress: _,
    Listing_NotAvailable: _,
    Listing_NotAvailable_Short: _,
    Listing_NotAvailable_Long: _,
    Listing_MyListing: _,
    BuyOrderDialog_Header: _,
    BuyOrderDialog_Header_NoItem: _,
    BuyOrderDialog_BucketPicker_Label: _,
    BuyOrderDialog_BucketPicker_Placeholder: _,
    BuyOrderDialog_PriceField: _,
    BuyOrderDialog_PriceField_Suffix: _,
    BuyOrderDialog_QuantityField: _,
    BuyOrderDialog_MaxPrice: _,
    BuyOrderDialog_MaxPrice_Tip: _,
    BuyOrderDialog_Status_Pending: _,
    BuyOrderDialog_Status_Filled: _,
    BuyOrderDialog_Status_Settled: _,
    BuyOrderDialog_Status_Settled_Note: _,
    BuyOrderDialog_Status_GenericError: _,
    BuyOrderDialog_MinPriceError: _,
    OrderBook_Table_PriceOrLess: _,
    OrderBook_Table_PriceOrMore: _,
    OrderBook_Table_Price: _,
    OrderBook_Table_Quantity: _,
    OrderBook_SellOrder_Description: _,
    OrderBook_SellOrder_Description_None: _,
    OrderBook_BuyOrder_Description: _,
    OrderBook_BuyOrder_Description_None: _,
    OrderBook_BuyOrder_NeedBucket: _,
    OrderBook_BuyOrder_Explanation_Unique: _,
    OrderBook_BuyOrder_Explanation_Commodity: _,
    OrderBook_Graph_Title: _,
    OrderBook_Graph_BuyTooltip: _,
    OrderBook_Graph_BuyTooltip_Plural: _,
    OrderBook_Graph_SellTooltip: _,
    OrderBook_Graph_SellTooltip_Plural: _,
    OrderBook_PlaceOrder_BuyRequests: _,
    OrderBook_PlaceOrder_BuyRequests_Plural: _,
    MedianSalePrice_Graph_Title: _,
    Graph_TimeScale_Week: _,
    Graph_TimeScale_Month: _,
    Graph_TimeScale_Year: _,
    Graph_TimeScale_Lifetime: _,
    Graph_NumberSold: _,
    Graph_Label_Price: _,
    Graph_Label_Volume: _,
    Graph_NoData: _,
    Graph_Tooltip_NoPurchaseData: _,
    Graph_Tooltip_NA: _,
    MyOrders_GridHeader_Name: _,
    MyOrders_GridHeader_Price: _,
    MyOrders_GridHeader_Quantity: _,
    MyOrders_GridHeader_DateListed: _,
    MyOrders_Cancel: _,
    MyOrders_Remove: _,
    MyOrders_Heading: _,
    MyOrders_Heading_Sell: _,
    MyOrders_Heading_Buy: _,
    MyOrders_Heading_MyPurchaseOffers: _,
    MyOrders_Heading_MyListings: _,
    MyOrders_FailedToLoad: _,
    MyOrders_NoActiveOrders_Item: _,
    MyOrders_NoBuyOrders_Item: _,
    MyOrders_NoSellOrders_Item: _,
    MyOrders_QuantityWithValue: _,
    MyOrders_SeeAllN: _,
    CancelBuyOrder_GenericError: _,
    CancelListing_GenericError: _,
    CancelListing_Dialog_Header: _,
    CancelListing_Dialog_Prompt: _,
    CancelListing_Dialog_Prompt_Generic: _,
    CancelListing_Dialog_Yes: _,
    CancelListing_Dialog_No: `Nee`,
    CancelListing_Dialog_Success: _,
    SellDialog_Frame_Title: _,
    UniqueBuyOrder_Explanation_Header: _,
    UniqueBuyOrder_Explanation_1: _,
    UniqueBuyOrder_Explanation_2: _,
    UniqueBuyOrder_Explanation_3: _,
    PriceFilter_ValueAndUp: _,
    Error_Sorry: _,
    Error_Encountered: _,
    Error_TooManyRequests_Description: _,
    Container_ContentsLabel: _,
    Error_LoadingContent: _,
    Error_LoadingMarketItem: _,
    ListingFilter_Title: _,
    Listings_NoneFound: _,
    ItemBucketPicker_Overflow_Placeholder: _,
    ItemBucketPicker_Overflow_FilterPlaceholder: _,
    Mobile_InfoSection: _,
    Mobile_GraphSection: _,
    Mobile_BuyOrderSection: _,
    Mobile_FiltersButton: _,
    AssetProperty_Range_MinPlaceholder: _,
    AssetProperty_Range_MaxPlaceholder: _,
    Accessories_FieldSectionLabel: _,
    Accessories_AnyFilter: _,
    Accessories_NoneFilter: _,
    Accessories_TypeAndValue_Breadcrumb: _,
    Item_CountryBuySellRestricted: _,
    Item_CountryBuyRestricted: _,
    Listing_EnhancedAppearance_Missing: _,
    Listing_EnhancedAppearance_ShowBackground: _,
    Listing_SomethingWentWrong: _,
    Unavailable_Header: _,
    Unavailable_Header_Plural: _,
    Filter_ViewResults: _,
    Results_GridView_Tooltip: _,
    Results_ListView_Tooltip: _,
    Results_PageLoadError: _,
    Market_AppUnplayedAndUnvetted: _,
    Market_AppUnplayedAndUnvetted_Dismiss: _,
    Home_GamePicker_Label: _,
    Home_GamePicker_ViewAll: _,
    Economy_Market_TopLevelReason_AccountLocked: _,
    Economy_Market_TopLevelTooltip_AccountLocked: _,
    Economy_Market_HeaderTip_AccountLocked: _,
    Economy_Market_TopLevelTooltip_RemoveRestrictionLink: _,
    Economy_Market_TopLevelReason_AccountTradeBanned: _,
    Economy_Market_TopLevelReason_Unknown: _,
    Economy_Market_TopLevelTooltip_AccountTradeBanned: _,
    Economy_Market_HeaderTip_AccountTradeBanned: _,
    Economy_Market_TopLevelTooltip_MoreInfoLink: _,
    Economy_Market_TopLevelReason_AccountNotTrusted: _,
    Economy_Market_TopLevelTooltip_AccountNotTrusted: _,
    Economy_Market_HeaderTip_AccountNotTrusted: _,
    Economy_Market_TopLevelReason_AccountNotTrusted_Waiting: _,
    Economy_Market_TTopLevelTooltip_AccountNotTrusted_Waiting: _,
    Economy_Market_TopLevelReason_AccountPasswordRecentlyReset: _,
    Economy_Market_TopLevelTooltip_AccountPasswordRecentlyReset: _,
    Economy_Market_HeaderTip_AccountPasswordRecentlyReset: _,
    Economy_Market_HeaderTip_NewPaymentMethod_NoDate: _,
    Economy_Market_HeaderTip_AccountHasNewPaymentMethod: _,
    Economy_Market_TopLevelReason_AccountHasNewPaymentMethod: _,
    Economy_Market_TopLevelReason_AcceptedWalletGift: _,
    Economy_Market_HeaderTip_AcceptedWalletGift: _,
    Economy_Market_TopLevelReason_InvalidCookie: _,
    Economy_Market_TopLevelTooltip_InvalidCookie: _,
    Economy_Market_HeaderTip_InvalidCookie: _,
    Economy_Market_TopLevelReason_NewDevice: _,
    Economy_Market_TopLevelTooltip_NewDevice: _,
    Economy_Market_HeaderTip_NewDevice: _,
    Economy_Market_TopLevelReason_SelfRefund: _,
    Economy_Market_TopLevelTooltip_SelfRefund: _,
    Economy_Market_HeaderTip_SelfRefund: _,
    Economy_Market_TopLevelReason_LimitedUser: _,
    Economy_Market_TopLevelTooltip_LimitedUser: _,
    Economy_Market_HeaderTip_LimitedUser: _,
    Economy_Market_HeaderTip_SteamGuardOnlyRecentlyEnabled: _,
    Economy_Market_TopLevelTooltip_SteamGuardRecentlyEnabled: _,
    Economy_Market_TopLevelReason_NoSteamGuard: _,
    Economy_Market_TopLevelTooltip_SteamGuardDisabled: _,
    Economy_Market_HeaderTip_NoSteamGuard: _,
    Economy_Market_HeaderTip_TimeCanUse: _,
    Economy_Market_TopLevelReason_TradeCooldown: _,
  };
export {
  _ as Accessories_AnyFilter,
  _ as Accessories_FieldSectionLabel,
  _ as Accessories_NoneFilter,
  _ as Accessories_TypeAndValue_Breadcrumb,
  _ as AccessorySearch_AttachedAccessoryType,
  _ as AdvancedSearch_AppSelect_Clear,
  _ as AdvancedSearch_AppSelect_FilterPlaceholder,
  _ as AdvancedSearch_AppSelect_Placeholder,
  _ as AdvancedSearch_AppSelect_PopularGames,
  _ as AdvancedSearch_AppSelect_YourGames,
  _ as AdvancedSearch_BetaTag,
  _ as AdvancedSearch_CSContainers_Tooltip,
  _ as AdvancedSearch_CustomFilter_All,
  _ as AdvancedSearch_CustomFilter_Other,
  _ as AdvancedSearch_FacetLoadError,
  _ as AdvancedSearch_FilterGeneric_Placeholder,
  _ as AdvancedSearch_Header,
  _ as AdvancedSearch_Heading,
  _ as AdvancedSearch_IncludeDescriptions,
  _ as AdvancedSearch_IncludeDescriptions_Tooltip,
  _ as AdvancedSearch_Link,
  _ as AdvancedSearch_MaxPricePlaceholder,
  _ as AdvancedSearch_MinPricePlaceholder,
  _ as AdvancedSearch_NoFacets,
  _ as AdvancedSearch_NoFacetsSearch,
  _ as AdvancedSearch_PriceFieldLabel,
  _ as AdvancedSearch_Reset,
  _ as AdvancedSearch_Search,
  _ as AdvancedSearch_SteamItems_TypeLabel,
  _ as AdvancedSearch_TextSearch_Placeholder,
  _ as AdvancedSearch_TextSearch_PlaceholderWithApp,
  _ as AdvancedSearch_TextSearch_Tooltip,
  _ as AdvancedSearch_TypeSwitch_InGame,
  _ as AdvancedSearch_TypeSwitch_SteamItems,
  _ as AssetPropertyNumberFilterRange,
  _ as AssetPropertyStringFilter,
  _ as AssetProperty_Range_MaxPlaceholder,
  _ as AssetProperty_Range_MinPlaceholder,
  _ as Breadcrumbs_Home,
  _ as Bucket_PriceFrom,
  _ as Button_Buy,
  _ as Button_BuyNow,
  _ as Button_BuyOrder,
  _ as Button_Close,
  _ as Button_Sell,
  _ as BuyOrderDialog_BucketPicker_Label,
  _ as BuyOrderDialog_BucketPicker_Placeholder,
  _ as BuyOrderDialog_Header,
  _ as BuyOrderDialog_Header_NoItem,
  _ as BuyOrderDialog_MaxPrice,
  _ as BuyOrderDialog_MaxPrice_Tip,
  _ as BuyOrderDialog_MinPriceError,
  _ as BuyOrderDialog_PriceField,
  _ as BuyOrderDialog_PriceField_Suffix,
  _ as BuyOrderDialog_QuantityField,
  _ as BuyOrderDialog_Status_Filled,
  _ as BuyOrderDialog_Status_GenericError,
  _ as BuyOrderDialog_Status_Pending,
  _ as BuyOrderDialog_Status_Settled,
  _ as BuyOrderDialog_Status_Settled_Note,
  _ as BuyOrder_PlaceOrderHeader,
  _ as CancelBuyOrder_GenericError,
  _ as CancelListing_Dialog_Header,
  _ as CancelListing_Dialog_No,
  _ as CancelListing_Dialog_Prompt,
  _ as CancelListing_Dialog_Prompt_Generic,
  _ as CancelListing_Dialog_Success,
  _ as CancelListing_Dialog_Yes,
  _ as CancelListing_GenericError,
  _ as CommodityExplanation,
  _ as Container_ContentsLabel,
  _ as Economy_Market_HeaderTip_AcceptedWalletGift,
  _ as Economy_Market_HeaderTip_AccountHasNewPaymentMethod,
  _ as Economy_Market_HeaderTip_AccountLocked,
  _ as Economy_Market_HeaderTip_AccountNotTrusted,
  _ as Economy_Market_HeaderTip_AccountPasswordRecentlyReset,
  _ as Economy_Market_HeaderTip_AccountTradeBanned,
  _ as Economy_Market_HeaderTip_InvalidCookie,
  _ as Economy_Market_HeaderTip_LimitedUser,
  _ as Economy_Market_HeaderTip_NewDevice,
  _ as Economy_Market_HeaderTip_NewPaymentMethod_NoDate,
  _ as Economy_Market_HeaderTip_NoSteamGuard,
  _ as Economy_Market_HeaderTip_SelfRefund,
  _ as Economy_Market_HeaderTip_SteamGuardOnlyRecentlyEnabled,
  _ as Economy_Market_HeaderTip_TimeCanUse,
  _ as Economy_Market_Purchase_MarketableRestriction_1Day,
  _ as Economy_Market_Purchase_MarketableRestriction_7Days,
  _ as Economy_Market_Purchase_MarketableRestriction_NDays,
  _ as Economy_Market_Purchase_MarketableRestriction_None,
  _ as Economy_Market_Purchase_Restrictions,
  _ as Economy_Market_Purchase_TradableRestriction_1Day,
  _ as Economy_Market_Purchase_TradableRestriction_7Days,
  _ as Economy_Market_Purchase_TradableRestriction_NDays,
  _ as Economy_Market_Purchase_TradableRestriction_Permanent,
  _ as Economy_Market_TTopLevelTooltip_AccountNotTrusted_Waiting,
  _ as Economy_Market_TopLevelReason_AcceptedWalletGift,
  _ as Economy_Market_TopLevelReason_AccountHasNewPaymentMethod,
  _ as Economy_Market_TopLevelReason_AccountLocked,
  _ as Economy_Market_TopLevelReason_AccountNotTrusted,
  _ as Economy_Market_TopLevelReason_AccountNotTrusted_Waiting,
  _ as Economy_Market_TopLevelReason_AccountPasswordRecentlyReset,
  _ as Economy_Market_TopLevelReason_AccountTradeBanned,
  _ as Economy_Market_TopLevelReason_InvalidCookie,
  _ as Economy_Market_TopLevelReason_LimitedUser,
  _ as Economy_Market_TopLevelReason_NewDevice,
  _ as Economy_Market_TopLevelReason_NoSteamGuard,
  _ as Economy_Market_TopLevelReason_SelfRefund,
  _ as Economy_Market_TopLevelReason_TradeCooldown,
  _ as Economy_Market_TopLevelReason_Unknown,
  _ as Economy_Market_TopLevelTooltip_AccountLocked,
  _ as Economy_Market_TopLevelTooltip_AccountNotTrusted,
  _ as Economy_Market_TopLevelTooltip_AccountPasswordRecentlyReset,
  _ as Economy_Market_TopLevelTooltip_AccountTradeBanned,
  _ as Economy_Market_TopLevelTooltip_InvalidCookie,
  _ as Economy_Market_TopLevelTooltip_LimitedUser,
  _ as Economy_Market_TopLevelTooltip_MoreInfoLink,
  _ as Economy_Market_TopLevelTooltip_NewDevice,
  _ as Economy_Market_TopLevelTooltip_RemoveRestrictionLink,
  _ as Economy_Market_TopLevelTooltip_SelfRefund,
  _ as Economy_Market_TopLevelTooltip_SteamGuardDisabled,
  _ as Economy_Market_TopLevelTooltip_SteamGuardRecentlyEnabled,
  _ as Error_Encountered,
  _ as Error_LoadingContent,
  _ as Error_LoadingMarketItem,
  _ as Error_Sorry,
  _ as Error_TooManyRequests_Description,
  _ as FilterResults_Placeholder,
  _ as Filter_ViewResults,
  _ as Graph_Label_Price,
  _ as Graph_Label_Volume,
  _ as Graph_NoData,
  _ as Graph_NumberSold,
  _ as Graph_TimeScale_Lifetime,
  _ as Graph_TimeScale_Month,
  _ as Graph_TimeScale_Week,
  _ as Graph_TimeScale_Year,
  _ as Graph_Tooltip_NA,
  _ as Graph_Tooltip_NoPurchaseData,
  _ as Header_GiveFeedback,
  _ as Header_LearnMore,
  _ as Header_MarketDescription,
  _ as Header_MarketTitle,
  _ as Header_OptOut,
  _ as Header_Search_Filters,
  _ as Header_Search_Placeholder,
  _ as Header_Search_PlaceholderNew,
  _ as Home_GamePicker_Label,
  _ as Home_GamePicker_ViewAll,
  _ as ItemBucketPicker_Overflow_FilterPlaceholder,
  _ as ItemBucketPicker_Overflow_Placeholder,
  _ as Item_CountryBuyRestricted,
  _ as Item_CountryBuySellRestricted,
  _ as ListingFilter_Title,
  _ as Listing_EnhancedAppearance_Missing,
  _ as Listing_EnhancedAppearance_ShowBackground,
  _ as Listing_MyListing,
  _ as Listing_NotAvailable,
  _ as Listing_NotAvailable_Long,
  _ as Listing_NotAvailable_Short,
  _ as Listing_SomethingWentWrong,
  _ as Listings_NoneFound,
  _ as Listings_TextFilter_Placeholder,
  _ as MarketHome_PopularApps,
  _ as MarketSearch_FilterColumn_Header,
  _ as MarketSearch_Placeholder,
  _ as MarketSearch_Reset,
  _ as Market_AppUnplayedAndUnvetted,
  _ as Market_AppUnplayedAndUnvetted_Dismiss,
  _ as MedianSalePrice_Graph_Title,
  _ as Mobile_BuyOrderSection,
  _ as Mobile_FiltersButton,
  _ as Mobile_GraphSection,
  _ as Mobile_InfoSection,
  _ as MyOrders_Cancel,
  _ as MyOrders_FailedToLoad,
  _ as MyOrders_GridHeader_DateListed,
  _ as MyOrders_GridHeader_Name,
  _ as MyOrders_GridHeader_Price,
  _ as MyOrders_GridHeader_Quantity,
  _ as MyOrders_Heading,
  _ as MyOrders_Heading_Buy,
  _ as MyOrders_Heading_MyListings,
  _ as MyOrders_Heading_MyPurchaseOffers,
  _ as MyOrders_Heading_Sell,
  _ as MyOrders_NoActiveOrders_Item,
  _ as MyOrders_NoBuyOrders_Item,
  _ as MyOrders_NoSellOrders_Item,
  _ as MyOrders_QuantityWithValue,
  _ as MyOrders_Remove,
  _ as MyOrders_SeeAllN,
  _ as OrderBook_BuyOrder_Description,
  _ as OrderBook_BuyOrder_Description_None,
  _ as OrderBook_BuyOrder_Explanation_Commodity,
  _ as OrderBook_BuyOrder_Explanation_Unique,
  _ as OrderBook_BuyOrder_NeedBucket,
  _ as OrderBook_Graph_BuyTooltip,
  _ as OrderBook_Graph_BuyTooltip_Plural,
  _ as OrderBook_Graph_SellTooltip,
  _ as OrderBook_Graph_SellTooltip_Plural,
  _ as OrderBook_Graph_Title,
  _ as OrderBook_PlaceOrder_BuyRequests,
  _ as OrderBook_PlaceOrder_BuyRequests_Plural,
  _ as OrderBook_SellOrder_Description,
  _ as OrderBook_SellOrder_Description_None,
  _ as OrderBook_Table_Price,
  _ as OrderBook_Table_PriceOrLess,
  _ as OrderBook_Table_PriceOrMore,
  _ as OrderBook_Table_Quantity,
  _ as PriceFilter_ValueAndUp,
  _ as PurchaseDialog_Action_AddFunds,
  _ as PurchaseDialog_Action_Purchase,
  _ as PurchaseDialog_BillingInfo_Address,
  _ as PurchaseDialog_BillingInfo_AddressLine2,
  _ as PurchaseDialog_BillingInfo_City,
  _ as PurchaseDialog_BillingInfo_Country,
  _ as PurchaseDialog_BillingInfo_FirstName,
  _ as PurchaseDialog_BillingInfo_Label,
  _ as PurchaseDialog_BillingInfo_LastName,
  _ as PurchaseDialog_BillingInfo_SaveInfo,
  _ as PurchaseDialog_BillingInfo_StateProvince,
  _ as PurchaseDialog_BillingInfo_ZipPostal,
  _ as PurchaseDialog_Button_ViewInventory,
  _ as PurchaseDialog_Close,
  _ as PurchaseDialog_Confirmation_Body_Email,
  _ as PurchaseDialog_Confirmation_Body_Mobile,
  _ as PurchaseDialog_Confirmation_Body_Unknown,
  _ as PurchaseDialog_Confirmation_Description_Email,
  _ as PurchaseDialog_Confirmation_Description_Mobile,
  _ as PurchaseDialog_Confirmation_Description_Unknown,
  _ as PurchaseDialog_Confirmation_Title,
  _ as PurchaseDialog_Confirmation_Title_Wait,
  _ as PurchaseDialog_Details_Column_Name,
  _ as PurchaseDialog_Details_Column_Price,
  _ as PurchaseDialog_EU_SSA,
  _ as PurchaseDialog_Error_InvalidMilitaryCity,
  _ as PurchaseDialog_Error_InvalidPostal,
  _ as PurchaseDialog_Error_MissingRequired,
  _ as PurchaseDialog_Error_NoConfirmation,
  _ as PurchaseDialog_Error_ServerGeneric,
  _ as PurchaseDialog_Header,
  _ as PurchaseDialog_LocalTax_Label,
  _ as PurchaseDialog_PaymentMethod_Label,
  _ as PurchaseDialog_PaymentMethod_Wallet,
  _ as PurchaseDialog_PublisherFee_Label,
  _ as PurchaseDialog_PublisherFee_Label_Generic,
  _ as PurchaseDialog_PurchaseComplete,
  _ as PurchaseDialog_Purchase_Successful,
  _ as PurchaseDialog_SSA_Fail,
  _ as PurchaseDialog_SSA_Link,
  _ as PurchaseDialog_SSA_Link_Title,
  _ as PurchaseDialog_SteamAccount_Label,
  _ as PurchaseDialog_SteamFee_Label,
  _ as PurchaseDialog_Subtotal_Label,
  _ as PurchaseDialog_Total_Label,
  _ as PurchaseDialog_ViewInventory,
  _ as PurhcaseDialog_SaveMyAddress,
  _ as Results_GridView_Tooltip,
  _ as Results_ListView_Tooltip,
  _ as Results_PageLoadError,
  _ as Search_AmountFound,
  _ as Search_AmountFoundFor,
  _ as Search_AmountFoundFor_Plural,
  _ as Search_AmountFound_Plural,
  _ as Search_Button,
  _ as Search_ListingQuantity,
  _ as Search_ListingQuantity_Abbreviation,
  _ as Search_ListingsFound,
  _ as Search_ListingsFound_Plural,
  _ as Search_Placeholder,
  _ as Search_ResultsFoundFor,
  _ as SellDialog_Frame_Title,
  _ as SortBy_AssetProperty_Asc,
  _ as SortBy_AssetProperty_Desc,
  _ as SortBy_Label,
  _ as SortBy_Name_Asc,
  _ as SortBy_Name_Desc,
  _ as SortBy_Popularity,
  _ as SortBy_Price_Asc,
  _ as SortBy_Price_Desc,
  _ as SortBy_Quantity_Asc,
  _ as SortBy_Quantity_Desc,
  _ as Unavailable_Header,
  _ as Unavailable_Header_Plural,
  _ as UniqueBuyOrder_Explanation_1,
  _ as UniqueBuyOrder_Explanation_2,
  _ as UniqueBuyOrder_Explanation_3,
  _ as UniqueBuyOrder_Explanation_Header,
  _ as default,
};
