var _ = `Post del forum`,
  _ = `Discussioni generali`,
  _ = `Messaggi segnalati`,
  _ = `Discussioni del Workshop`,
  _ = `Scambi`,
  _ = `Eventi e annunci`,
  _ = `1 segnalazione`,
  _ = `%1$s segnalazioni`,
  _ = `1 elemento`,
  _ = `%1$s elementi`,
  _ = `%1$s su %2$s`,
  _ = `%1$s su %2$s nella discussione: %3$s`,
  _ = `1 segnalazione`,
  _ = `%1$s segnalazioni`,
  _ = `1 soggetto`,
  _ = `%1$s soggetti`,
  _ = `Comunità di Steam`,
  _ = `Comunità di Steam :: Errore`,
  _ = `Errore`,
  _ = `Errore sconosciuto`,
  _ = `Giochi`,
  _ = `Comunità di Steam :: %1$s :: Giochi`,
  _ = `Cerca - Mercato della Comunità di Steam`,
  _ = `%1$s - Mercato della Comunità di Steam`,
  _ = `Oggetto del mercato - Mercato della Comunità di Steam`,
  _ = `Mercato della Comunità di Steam`,
  _ = `Profilo non trovato`,
  _ = `Impossibile caricare la Lista dei desideri dell'utente.`,
  _ = `Hai fatto troppe richieste di recente. Attendi e riprova a inviare la tua richiesta più tardi.`,
  _ = `Caricamento`,
  _ = `COMPLETAMENTO: %1$s%`,
  _ = `IN PAUSA - COMPLETAMENTO: %1$s%`,
  _ = `SCARICATI: %1$s/%2$s`,
  _ = `ACHIEVEMENT`,
  _ = `Tempo residuo: %1$s`,
  _ = `%1$s/%2$s`,
  _ = `DISINSTALLAZIONE IN CORSO`,
  _ = `AGGIORNA`,
  _ = `DISINSTALLA`,
  _ = `SCARICA`,
  _ = `METTI IN PAUSA`,
  _ = `RIPRENDI`,
  _ = `DISINSTALLAZIONE IN CORSO`,
  _ = `ANNULLA`,
  _ = `Visualizza le mie impostazioni sulla privacy per questo contenuto`,
  _ = `Trova un gioco`,
  _ = `Filtra per i giochi che avete entrambi`,
  _ = `Tempo di gioco`,
  _ = `Titolo`,
  _ = `Achievement ottenuti`,
  _ = `TEMPO DI GIOCO TOTALE`,
  _ = `ULTIMO AVVIO`,
  _ = `ULTIME DUE SETTIMANE`,
  _ = `Informazioni e link sul gioco`,
  _ = `Download remoto`,
  _ = `DOWNLOAD REMOTO SU: %1$s`,
  _ = `STATO DOWNLOAD REMOTO: %1$s`,
  _ = `Impossibile raggiungere il tuo PC`,
  _ = `Per scaricare da remoto i giochi sul tuo client di Steam, il tuo PC deve essere attivo e connesso a internet e devi avere effettuato l'accesso`,
  _ = `Leggi le domande frequenti`,
  _ = `%1$s. %2$s`,
  _ = `Altre informazioni`,
  _ = `DOWNLOAD REMOTO NON DISPONIBILE: `,
  _ = `Vuoi disinstallare %1$s? Resterà nella tua Libreria, ma se vorrai giocarci in futuro dovrai scaricarlo nuovamente.`,
  _ = `%1$s | "%2$s"`,
  _ = `Giocati di recente %1$s`,
  _ = `Tutti i giochi %1$s`,
  _ = `Giochi completati %1$s`,
  _ = `Recensioni %1$s`,
  _ = `Seguiti %1$s`,
  _ = `Lista dei desideri`,
  _ = `Ottenuti tutti gli achievement possibili`,
  _ = `Qui troverai i tuoi giochi completati, o i giochi in cui hai ottenuto tutti gli achievement possibili`,
  _ = `Giocatori con questo achievement: %1$s%`,
  _ = `Pagina del Negozio`,
  _ = `Forum`,
  _ = `Gruppi`,
  _ = `Sito web ufficiale`,
  _ = `Notizie`,
  _ = `I miei achievement`,
  _ = `Achievement di %1$s`,
  _ = `Statistiche di %1$s`,
  _ = `Dati di gioco personali di %1$s`,
  _ = `Le mie classifiche`,
  _ = `Classifiche di %1$s`,
  _ = `Achievement globali`,
  _ = `Classifiche globali`,
  _ = `Statistiche di gioco`,
  _ = `Contenuti di gioco`,
  _ = `Le mie statistiche di gioco`,
  _ = `I miei contenuti di gioco`,
  _ = `Link ai giochi`,
  _ = `I miei screenshot: %1$s`,
  _ = `Screenshot di %1$s: %2$s`,
  _ = `Amici che giocano a %1$s`,
  _ = `Le mie carte collezionabili: %1$s`,
  _ = `La mia recensione`,
  _ = `Recensione di %1$s`,
  _ = `Hub della Comunità`,
  _ = `Le mie note`,
  _ = `%1$s ore`,
  _ = `%1$s minuti`,
  _ = `Contrassegna come privato`,
  _ = `Elimina contrassegno Privato`,
  _ = `Contrassegna questo gioco come privato e nascondilo ai miei amici`,
  _ = `© Valve Corporation. Tutti i diritti riservati. Tutti i marchi appartengono ai rispettivi proprietari negli Stati Uniti e in altri Paesi.`,
  _ = `Alcuni dati geospaziali su questo sito sono forniti da %1$s.`,
  _ = `Informativa sulla privacy`,
  _ = `Informazioni legali`,
  _ = `Contratto di sottoscrizione a Steam`,
  _ = `Rimborsi`,
  _ = `Cookie`,
  _ = `Accessibilità`,
  _ = `Ban attivi`,
  _ = `Messaggi della Comunità`,
  _ = `Contenuto segnalato`,
  _ = `Contenuto moderato`,
  _ = `Questi sono i contenuti su Steam che hai segnalato per violazione delle linee guida di Steam.`,
  _ = `Questo è un elenco di contenuti che hai pubblicato su Steam e che sono stati moderati.`,
  _ = `Ultimo aggiornamento: %1$s`,
  _ = ``,
  _ = {
    Moderation_SubjectTypeName_ForumPost: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    moderation_claim_report_count: _,
    moderation_claim_report_count_Plural: _,
    moderation_claim_subject_count: _,
    moderation_claim_subject_count_Plural: _,
    moderation_claim_n_reports_on_m_subjects: _,
    moderation_forumpost_summary: _,
    moderation_forumpost_summary_reports_fragment: _,
    moderation_forumpost_summary_reports_fragment_Plural: _,
    moderation_forumpost_summary_subjects_fragment: _,
    moderation_forumpost_summary_subjects_fragment_Plural: _,
    community_title: _,
    community_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    profile_games_list: _,
    profile_games_list_title: _,
    Market_Search_Title: _,
    Market_Item_Title: _,
    Market_Item_GenericTitle: _,
    Market_GenericTitle: _,
    profile_error_profilenotfound: _,
    profile_games_list_error_loadfailed: _,
    Error_RateLimited: _,
    Loading: _,
    GamesList_Header_Downloading: _,
    GamesList_Header_Paused: _,
    GamesList_Header_DownloadBytes: _,
    GamesList_Header_Achievements: _,
    GamesList_TimeRemaining: _,
    GamesList_Achievement_Fraction: _,
    GamesList_Uninstalling: _,
    GamesList_Button_UpdateRequired: _,
    GamesList_Button_Uninstall: _,
    GamesList_Button_Download: _,
    GamesList_Button_Pause: _,
    GamesList_Button_Resume: _,
    GamesList_Button_Uninstalling: _,
    GamesList_Button_Cancel: _,
    GamesList_PrivacySettings_Tooltip: _,
    GamesList_Filter_Placeholder: _,
    GamesList_Filter_BothOwned: _,
    GamesList_Sort_HoursPlayed: _,
    GamesList_Sort_Name: _,
    GamesList_Sort_AchievementCompletion: _,
    GamesList_Header_TotalPlayed: _,
    GamesList_Header_LastPlayed: _,
    GamesList_Header_TwoWeeks: _,
    GamesList_MenuLabel_GameInfo: _,
    GamesList_MenuLabel_RemoteDownload: _,
    GamesList_Header_RemoteDownload: _,
    GamesList_Header_RemoteDownloadStatus: _,
    GamesList_RemoteDownload_NoConnection: _,
    GamesList_RemoteDownload_Help: _,
    GamesList_RemoteDownload_ReadTheFAQ: _,
    GamesList_RemoteDownload_Info: _,
    GamesList_RemoteDownload_LearnMore: _,
    GamesList_RemoteDownload_NoRemoteControl: _,
    GamesList_RemoteDownload_UninstallConfirm: _,
    GamesList_Client_Indicator: _,
    GamesList_Tab_RecentlyPlayed: _,
    GamesList_Tab_AllGames: _,
    GamesList_Tab_PerfectGames: _,
    GamesList_Tab_Reviews: _,
    GamesList_Tab_Followed: _,
    GamesList_Tab_Wishlist: _,
    Perfect_Game_Description: _,
    GamesList_PerfectGames_Description: _,
    GamesList_Achievement_Unlock_Percentage: _,
    Community_StorePage: _,
    Community_Forums: _,
    Community_Groups: _,
    Community_OfficialWebsite: _,
    Community_News: _,
    Community_UsersAchievementsFirstPerson: _,
    Community_UsersAchievements: _,
    Community_UsersStats: _,
    Community_GamePersonalData: _,
    Community_UsersLeaderboardsFirstPerson: _,
    Community_UsersLeaderboards: _,
    Community_GlobalAchievements: _,
    Community_GlobalLeaderboards: _,
    Community_GameStats: _,
    Community_GameContent: _,
    Community_GameStatsFirstPerson: _,
    Community_GameContentFirstPerson: _,
    Community_GameLinks: _,
    Community_ScreenshotsMenuItemFirstPerson: _,
    Community_ScreenshotsMenuItemThirdPerson: _,
    Community_FriendsWhoPlayMenuItemFirstPerson: _,
    Community_TradingCardsMenuItemFirstPerson: _,
    Community_ReviewMenuItemFirstPerson: _,
    Community_ReviewMenuItemThirdPerson: _,
    Community_GameHubMenuItem: _,
    Community_GameNotesFirstPerson: _,
    Playtime_Hours: _,
    Playtime_Minutes: _,
    AppPrivacy_MarkAsPrivate: _,
    AppPrivacy_UnmarkAsPrivate: _,
    AppPrivacy_Explanation: _,
    footer_legal_notice: _,
    footer_geodata_notice: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_accessibility: _,
    profiletabs_currentbans: _,
    profiletabs_communitymessages: _,
    profiletabs_reportedcontent: _,
    profiletabs_moderatedcontent: _,
    reportedcontent_description: _,
    moderatedcontent_description: _,
    reportedcontent_lastupdated: _,
    empty_no_comma_following: ``,
  };
export {
  _ as AppPrivacy_Explanation,
  _ as AppPrivacy_MarkAsPrivate,
  _ as AppPrivacy_UnmarkAsPrivate,
  _ as Community_Forums,
  _ as Community_FriendsWhoPlayMenuItemFirstPerson,
  _ as Community_GameContent,
  _ as Community_GameContentFirstPerson,
  _ as Community_GameHubMenuItem,
  _ as Community_GameLinks,
  _ as Community_GameNotesFirstPerson,
  _ as Community_GamePersonalData,
  _ as Community_GameStats,
  _ as Community_GameStatsFirstPerson,
  _ as Community_GlobalAchievements,
  _ as Community_GlobalLeaderboards,
  _ as Community_Groups,
  _ as Community_News,
  _ as Community_OfficialWebsite,
  _ as Community_ReviewMenuItemFirstPerson,
  _ as Community_ReviewMenuItemThirdPerson,
  _ as Community_ScreenshotsMenuItemFirstPerson,
  _ as Community_ScreenshotsMenuItemThirdPerson,
  _ as Community_StorePage,
  _ as Community_TradingCardsMenuItemFirstPerson,
  _ as Community_UsersAchievements,
  _ as Community_UsersAchievementsFirstPerson,
  _ as Community_UsersLeaderboards,
  _ as Community_UsersLeaderboardsFirstPerson,
  _ as Community_UsersStats,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as GamesList_Achievement_Fraction,
  _ as GamesList_Achievement_Unlock_Percentage,
  _ as GamesList_Button_Cancel,
  _ as GamesList_Button_Download,
  _ as GamesList_Button_Pause,
  _ as GamesList_Button_Resume,
  _ as GamesList_Button_Uninstall,
  _ as GamesList_Button_Uninstalling,
  _ as GamesList_Button_UpdateRequired,
  _ as GamesList_Client_Indicator,
  _ as GamesList_Filter_BothOwned,
  _ as GamesList_Filter_Placeholder,
  _ as GamesList_Header_Achievements,
  _ as GamesList_Header_DownloadBytes,
  _ as GamesList_Header_Downloading,
  _ as GamesList_Header_LastPlayed,
  _ as GamesList_Header_Paused,
  _ as GamesList_Header_RemoteDownload,
  _ as GamesList_Header_RemoteDownloadStatus,
  _ as GamesList_Header_TotalPlayed,
  _ as GamesList_Header_TwoWeeks,
  _ as GamesList_MenuLabel_GameInfo,
  _ as GamesList_MenuLabel_RemoteDownload,
  _ as GamesList_PerfectGames_Description,
  _ as GamesList_PrivacySettings_Tooltip,
  _ as GamesList_RemoteDownload_Help,
  _ as GamesList_RemoteDownload_Info,
  _ as GamesList_RemoteDownload_LearnMore,
  _ as GamesList_RemoteDownload_NoConnection,
  _ as GamesList_RemoteDownload_NoRemoteControl,
  _ as GamesList_RemoteDownload_ReadTheFAQ,
  _ as GamesList_RemoteDownload_UninstallConfirm,
  _ as GamesList_Sort_AchievementCompletion,
  _ as GamesList_Sort_HoursPlayed,
  _ as GamesList_Sort_Name,
  _ as GamesList_Tab_AllGames,
  _ as GamesList_Tab_Followed,
  _ as GamesList_Tab_PerfectGames,
  _ as GamesList_Tab_RecentlyPlayed,
  _ as GamesList_Tab_Reviews,
  _ as GamesList_Tab_Wishlist,
  _ as GamesList_TimeRemaining,
  _ as GamesList_Uninstalling,
  _ as Loading,
  _ as Market_GenericTitle,
  _ as Market_Item_GenericTitle,
  _ as Market_Item_Title,
  _ as Market_Search_Title,
  _ as Moderation_SubjectTypeName_ForumPost,
  _ as Perfect_Game_Description,
  _ as Playtime_Hours,
  _ as Playtime_Minutes,
  _ as community_errorpage_title,
  _ as community_title,
  _ as default,
  _ as empty_no_comma_following,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_accessibility,
  _ as footer_cookies,
  _ as footer_geodata_notice,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_privacy_policy,
  _ as footer_refunds,
  _ as footer_ssa,
  _ as moderatedcontent_description,
  _ as moderation_claim_n_reports_on_m_subjects,
  _ as moderation_claim_report_count,
  _ as moderation_claim_report_count_Plural,
  _ as moderation_claim_subject_count,
  _ as moderation_claim_subject_count_Plural,
  _ as moderation_forumpost_summary,
  _ as moderation_forumpost_summary_reports_fragment,
  _ as moderation_forumpost_summary_reports_fragment_Plural,
  _ as moderation_forumpost_summary_subjects_fragment,
  _ as moderation_forumpost_summary_subjects_fragment_Plural,
  _ as profile_error_profilenotfound,
  _ as profile_games_list,
  _ as profile_games_list_error_loadfailed,
  _ as profile_games_list_title,
  _ as profiletabs_communitymessages,
  _ as profiletabs_currentbans,
  _ as profiletabs_moderatedcontent,
  _ as profiletabs_reportedcontent,
  _ as reportedcontent_description,
  _ as reportedcontent_lastupdated,
};
