var _ = `italian`,
  _ = `Workshop di Steam`,
  _ = `Il Workshop di Steam per %1$s`,
  _ = `Si è verificato un problema durante il caricamento di questa pagina. Riprova più tardi.`,
  _ = `Errore`,
  _ = `Si è verificato un problema durante l'esecuzione dell'azione. Riprova più tardi. (%1$s)`,
  _ = `Ci dispiace!`,
  _ = `Si è verificato un errore durante l'elaborazione della tua richiesta:`,
  _ = `Hai fatto troppe richieste di recente. Attendi e riprova a inviare la tua richiesta più tardi.`,
  _ = `(Solo per amministratori) Vedi la vecchia versione del Workshop`,
  _ = `Stai sfogliando: %1$s`,
  _ = `(Vota i tuoi preferiti)`,
  _ = `(Iscriviti per aggiungerlo al tuo gioco)`,
  _ = `(Vota i tuoi preferiti)`,
  _ = `Accettati per il gioco`,
  _ = `Accettato`,
  _ = `Contenuti ufficiali`,
  _ = `Da %1$s`,
  _ = `Articoli`,
  _ = `Articoli`,
  _ = `Collezioni`,
  _ = `Articolo`,
  _ = `Video`,
  _ = `Ricerche salvate`,
  _ = `Salva questa ricerca`,
  _ = `Inserisci un nome per la tua ricerca`,
  _ = `Salva i tuoi filtri di ricerca e le opzioni di ordinamento attuali per utilizzarli nuovamente in futuro. Puoi trovarli sotto "I tuoi oggetti".`,
  _ = `Salva come nuova ricerca o seleziona una ricerca precedentemente salvata per aggiornarla`,
  _ = `<Nuova ricerca salvata>`,
  _ = `Salva`,
  _ = `Elimina ricerca salvata`,
  _ = `Vuoi davvero eliminare la ricerca salvata "%1$s"?`,
  _ = `Elimina`,
  _ = `Ulteriori informazioni`,
  _ = `Azzera ricerca`,
  _ = `Il Workshop di Steam per %1$s`,
  _ = `Ordine`,
  _ = `Periodo`,
  _ = `Oggi`,
  _ = `Una settimana`,
  _ = `Trenta giorni`,
  _ = `Tre mesi`,
  _ = `Sei mesi`,
  _ = `Un anno`,
  _ = `Sempre`,
  _ = `%1$s (%2$s)`,
  _ = `Più recenti`,
  _ = `Più popolari`,
  _ = `I più votati di tutti i tempi`,
  _ = `Ultimo aggiornamento`,
  _ = `Peso della segnalazione`,
  _ = `(Amministratore) %1$s`,
  _ = `Più richiesti da altri oggetti`,
  _ = `Nel maggior numero di collezioni`,
  _ = `(Amministratore) Coda di approvazione`,
  _ = `Senza valutazione`,
  _ = `Sottoscrittori unici totali`,
  _ = `Voti totali`,
  _ = `I più votati`,
  _ = `Rilevanza della ricerca`,
  _ = `Tempo di gioco recente`,
  _ = `Tempo di gioco totale`,
  _ = `Tempo di gioco medio recente`,
  _ = `Tempo di gioco medio totale`,
  _ = `Sessioni di gioco`,
  _ = `Sessioni di gioco totali`,
  _ = `Punteggio inappropriato`,
  _ = `Verifica dei contenuti banditi`,
  _ = `Amministrazione da curatore`,
  _ = `Candidato`,
  _ = `Valutati da te`,
  _ = `Data accettata`,
  _ = `Filtri speciali: `,
  _ = `Nessuno`,
  _ = `Accettati per il gioco`,
  _ = `Creati dagli amici`,
  _ = `Creati dagli utenti che segui`,
  _ = `Preferiti dagli amici`,
  _ = `Segnalati (solo amministratori)`,
  _ = `Richiesti da altri oggetti`,
  _ = `Nelle collezioni`,
  _ = `Pagina iniziale`,
  _ = `Sfoglia`,
  _ = `I tuoi oggetti`,
  _ = `Discussioni`,
  _ = `Generali`,
  _ = `Cerca in %1$s`,
  _ = `Oggetti che hai pubblicato (%1$s)`,
  _ = `I tuoi preferiti (%1$s)`,
  _ = `Oggetti sottoscritti (%1$s)`,
  _ = `Oggetti giocati (%1$s)`,
  _ = `Le tue collezioni (%1$s)`,
  _ = `La tua coda di valutazione`,
  _ = `I tuoi dati di pagamento`,
  _ = `Mostra i tuoi ricavi`,
  _ = `(dagli oggetti del Workshop venduti)`,
  _ = `Visualizza il contratto legale`,
  _ = `Coda di valutazione`,
  _ = `Applica filtri`,
  _ = `Ordina per: %1$s`,
  _ = `<nessuna selezione>`,
  _ = `DLC necessari`,
  _ = `DLC necessari: %1$s`,
  _ = `Richiede DLC che possiedi`,
  _ = `Escludi elementi che richiedono DLC che non possiedi`,
  _ = `Non possiedi alcun DLC`,
  _ = `Possiedi tutti i DLC disponibili`,
  _ = `(%1$s articoli in più)`,
  _ = `Includi i DLC che possiedi`,
  _ = `Escludi i DLC che possiedi`,
  _ = `Filtra per nome`,
  _ = `Mostra oggetti incompatibili`,
  _ = `Alcuni oggetti non sono compatibili col gioco. Clicca questa casella per includerli nella ricerca.`,
  _ = `Oggetti non pubblici`,
  _ = `Risultati per: "%1$s"`,
  _ = `Risultati per: "%1$s" (solo titolo)`,
  _ = `Risultati per: "%1$s" (solo descrizione)`,
  _ = `Oggetto contenuto: "%1$s"`,
  _ = `Richiede "%1$s" per funzionare correttamente`,
  _ = `%1$s: %2$s`,
  _ = `%1$s: %2$s`,
  _ = `Etichetta: Oggetti incompatibili`,
  _ = `Etichetta: Oggetti accettati`,
  _ = `Specifica i campi di testo dell'oggetto che desideri cercare:`,
  _ = `Titolo e descrizione`,
  _ = `Solo titolo`,
  _ = `Solo descrizione`,
  _ = `Puoi creare ricerche più complesse utilizzando gli operatori %1$s, %2$s, e %3$s (devono essere in maiuscolo). In alternativa, puoi utilizzare i caratteri %4$s e %5$s come scorciatoia per %1$s e %3$s.`,
  _ = `%1$s trova elementi sia con "%2$s" che con "%3$s" nel testo di ricerca`,
  _ = `%1$s trova elementi con "%2$s" o con "%3$s" nel testo di ricerca`,
  _ = `%1$s trova elementi con "%2$s" ma non con "%3$s" nel testo di ricerca`,
  _ = `rosso`,
  _ = `blu`,
  _ = `verde`,
  _ = `room`,
  _ = `Combinare i termini di ricerca con le parentesi ti permetterà di creare ricerche piuttosto specifiche.`,
  _ = `%1$s trova elementi con "%2$s", associati con "%3$s" o con "%4$s" nel testo di ricerca.`,
  _ = `%1$s trova elementi con "%2$s" e "%3$s" o "%4$s", ma non con "%5$s" nel testo di ricerca.`,
  _ = `Posizione desiderata per i filtri:`,
  _ = `Lato sinistro`,
  _ = `Lato destro`,
  _ = `Minimizzato`,
  _ = `Rendi questi oggetti meno visibili:`,
  _ = `Segnalati da te`,
  _ = `Creati da utenti che hai bloccato`,
  _ = `Votati positivamente da te`,
  _ = `Votati negativamente da te`,
  _ = `Nella tua lista di sottoscrizioni`,
  _ = `Filtra per data`,
  _ = `Data di pubblicazione`,
  _ = `Pubblicati dopo: %1$s`,
  _ = `Pubblicati prima di: %1$s`,
  _ = `Pubblicati nel periodo da %1$s a %2$s`,
  _ = `Data ultimo aggiornamento`,
  _ = `Aggiornati dopo: %1$s`,
  _ = `Aggiornati prima di %1$s`,
  _ = `Aggiornati nel periodo da %1$s a %2$s`,
  _ = `tra`,
  _ = `e`,
  _ = `1 voce corrispondente ai filtri`,
  _ = `%2$s voci corrispondenti ai filtri`,
  _ = `Per pagina:`,
  _ = `%1$s/%2$s`,
  _ = `Crea collezione`,
  _ = `Invia il tuo design`,
  _ = `Vista rapida`,
  _ = `Vedi altro`,
  _ = `Sottoscrizione all'oggetto effettuata`,
  _ = `Questo oggetto è nel tuo elenco Preferiti`,
  _ = `Hai giocato con questo elemento`,
  _ = `Questo oggetto è stato approvato per l'uso all'interno di questo gioco!`,
  _ = `Questo oggetto è stato contrassegnato come incompatibile per questo gioco.`,
  _ = `Hai dato un pollice su a questo oggetto.`,
  _ = `Hai dato un pollice giù a questo oggetto.`,
  _ = `Hai segnalato questo oggetto per violazione delle Linee guida della Comunità di Steam.`,
  _ = `Hai bloccato questo utente.`,
  _ = `Descrizione`,
  _ = `Discussioni`,
  _ = `Commenti (%1$s)`,
  _ = `Annunci`,
  _ = `Statistiche dell'elemento`,
  _ = `Note sulle modifiche (%1$s)`,
  _ = `Workshop di Steam :: %1$s`,
  _ = `Creato da: `,
  _ = `%2$s valutazione`,
  _ = `%2$s valutazioni`,
  _ = `Valutazioni insufficienti`,
  _ = `%1$s alle ore %2$s`,
  _ = `Pubblicazione:`,
  _ = `Aggiornamento:`,
  _ = `Sottoscrivi`,
  _ = `Sottoscritto`,
  _ = `Annulla sottoscrizione`,
  _ = `Aggiungi ai preferiti`,
  _ = `Preferito`,
  _ = `Rimuovi dai preferiti`,
  _ = `Visualizza oggetti dipendenti`,
  _ = `Aggiungi alla collezione`,
  _ = `Salva nella collezione`,
  _ = `Accedi per eseguire questa azione`,
  _ = `Iscriviti per scaricare`,
  _ = `Annulla la sottoscrizione per rimuovere questo oggetto dal tuo gioco`,
  _ = `Ritrova facilmente questo oggetto più tardi`,
  _ = `Vedi tutti gli articoli (%1$s) che dipendono da questo oggetto per funzionare correttamente. Nota che alcuni potrebbero essere contrassegnati come nascosti o visibili solo agli amici.`,
  _ = `Segnala questo oggetto per violazione delle norme di condotta online di Steam`,
  _ = `Premia`,
  _ = `Aggiungi a una tua collezione`,
  _ = `Dimensioni file:`,
  _ = `Visitatori:`,
  _ = `Iscritti:`,
  _ = `Preferiti:`,
  _ = `Preferiti unici totali:`,
  _ = `Sottoscrittori unici totali:`,
  _ = `Sessioni di gioco totali:`,
  _ = `Richiede i seguenti oggetti: `,
  _ = `Richiede i seguenti DLC: `,
  _ = `Iscriviti a tutti`,
  _ = `Annulla tutte le sottoscrizioni`,
  _ = `Salva nella collezione`,
  _ = `Espandi tutti i premi della Comunità`,
  _ = `%1$s premio della Comunità`,
  _ = `%1$s premi della Comunità`,
  _ = `ETICHETTE`,
  _ = `CATEGORIE`,
  _ = `DESCRIZIONE`,
  _ = `Richiesto da:`,
  _ = `In %1$s collezioni`,
  _ = `In %1$s collezioni di %2$s`,
  _ = `Errore`,
  _ = `Non hai i permessi necessari per poter eseguire quell'azione.`,
  _ = `Si è verificato un problema nel contattare Steam. Riprova più tardi.`,
  _ = `Hai cercato di eseguire troppe azioni in un breve periodo di tempo. Attendi prima di riprovare.`,
  _ = `Si è verificato un problema durante il tentativo di esecuzione dell'azione. Riprova più tardi.`,
  _ = `Iscriviti a tutti`,
  _ = `Vuoi aggiungere gli articoli di questa collezione alle tue iscrizioni o sovrascrivere le tue iscrizioni in modo che contengano solo gli articoli di questa collezione?`,
  _ = `Aggiungi solamente`,
  _ = `Sovrascrivi le mie sottoscrizioni`,
  _ = `Oggetti aggiuntivi richiesti`,
  _ = `Questo oggetto richiede tutti i seguenti altri oggetti per funzionare correttamente.`,
  _ = `<1>%1$s</1> richiede tutti i seguenti altri oggetti per funzionare correttamente.`,
  _ = `Puoi cliccare su ciascuno di essi per saperne di più e abbonarti all'oggetto prima di procedere.`,
  _ = `Puoi anche scegliere di abbonarti a tutti questi oggetti richiesti (e a tutti gli oggetti che a loro volta li richiedono), ma tieni presente che potrebbero includere molti altri oggetti.`,
  _ = `Iscriviti solo a questo oggetto`,
  _ = `Iscriviti a tutti`,
  _ = `Segnala questo oggetto`,
  _ = `Descrivi in che modo questo oggetto sta violando i termini di servizio di Steam. Ti preghiamo di includere tutte le informazioni o i link rilevanti. L'invio di questa segnalazione non può essere annullato.`,
  _ = `Motivo: %1$s`,
  _ = `Innanzitutto, seleziona un motivo per cui stai segnalando questo oggetto:`,
  _ = `Se intendi segnalare una violazione di copyright in veste di legittimo detentore dei diritti, clicca %1$s per aprire il modulo di avviso di violazione di copyright DMCA.`,
  _ = `Se desideri inoltrare un reclamo relativo al marchio, puoi farlo %1$s.`,
  _ = `qui`,
  _ = `Aggiungi alla collezione`,
  _ = `"%1$s" verrà aggiunto alle raccolte selezionate di seguito:`,
  _ = `Non hai alcuna collezione salvata. Puoi crearne una nuova inserendo un nome qui sotto.`,
  _ = `Aggiungi alle raccolte selezionate`,
  _ = `Crea nuova collezione`,
  _ = `Sovrascrivi collezione`,
  _ = `Vuoi salvare questa collezione in una nuova collezione o sovrascriverne una esistente?`,
  _ = `Nuova collezione`,
  _ = `Collezione esistente`,
  _ = `Inserisci un nome per questa collezione:`,
  _ = `Seleziona una collezione da sovrascrivere:`,
  _ = `Contiene %2$s oggetto`,
  _ = `Contiene %2$s oggetti`,
  _ = `Ha %2$s collezione associata`,
  _ = `Ha %2$s collezioni associate`,
  _ = `+%1$s`,
  _ = `Il Workshop di Steam rende più semplice che mai la possibilità di caricare modelli 3D completi di oggetti per avere la possibilità di vederli accettati e inseriti nel gioco. Per pubblicare un oggetto nel Workshop e farlo giudicare da altri utenti, leggi prima di tutto la documentazione ufficiale elencata sulla destra, quindi clicca sul pulsante del Workshop di Steam nel menu principale del gioco.`,
  _ = `Il Workshop di Steam facilita la scoperta e la condivisione di nuovi contenuti per il tuo gioco o software. Ogni gioco o software potrebbe supportare tipi di contenuti leggermente diversi nel proprio Workshop, pertanto è consigliabile consultare la documentazione ufficiale per ulteriori informazioni su cosa si può creare e condividere in tale area.`,
  _ = `Quando trovi un contenuto che desideri aggiungere al tuo gioco, clicca sul pulsante "Sottoscrivi". Nella maggior parte dei casi, i contenuti saranno resi disponibili automaticamente la prossima volta che avvierai il gioco. Alcuni prodotti necessiteranno che tu acceda ad un'area dedicata del gioco o software per attivare o accedere ai nuovi contenuti.`,
  _ = `Con il Workshop di Steam è facile scoprire o condividere nuovi contenuti per il tuo gioco o software. Ciascun prodotto potrebbe supportare tipi leggermente diversi di contenuti nel suo Workshop dedicato, perciò è meglio consultare la documentazione ufficiale per ulteriori dettagli su cosa è possibile creare e condividere in quel settore.`,
  _ = `Per aggiungere al gioco dei contenuti che hai trovato nella scheda %1$s, clicca sul pulsante "Sottoscrivi". Nella maggior parte dei casi, il contenuto verrà automaticamente reso disponibile la prossima vota che avvierai il gioco. Alcuni prodotti potrebbero richiedere che tu acceda ad un'area particolare del gioco o software per attivare e avere accesso ai nuovi contenuti.`,
  _ = `Funzionalità abilitate`,
  _ = `Queste sono le funzionalità del Workshop di Steam utilizzate da %1$s:`,
  _ = `Oggetti pronti all'uso`,
  _ = `Gli oggetti pubblicati in questo Workshop sono pronti per l'utilizzo immediato. Clicca sul pulsante "Sottoscrivi" dalla pagina di un oggetto e sarà disponibile all'utilizzo quando avvierai %1$s.`,
  _ = `Gli oggetti pubblicati in questo Workshop nella scheda %2$s sono pronti per essere utilizzati immediatamente. Clicca sul pulsante "Sottoscrivi" nella pagina dei dettagli dell'oggetto per averlo disponibile non appena avvierai %1$s.`,
  _ = `Compatibilità con le versioni per i rami di gioco`,
  _ = `Gli oggetti possono avere versioni associate a diversi rami di gioco (beta). In questo modo è più facile per gli sviluppatori e gli autori di oggetti del Workshop collaborare per garantire la compatibilità degli oggetti che creano man mano che %1$s riceve gli aggiornamenti.`,
  _ = `Selezione di oggetti curati`,
  _ = `Gli oggetti pubblicati in questo Workshop non sono pronti per essere utilizzati immediatamente su %1$s. Gli sviluppatori affidano invece alla Comunità il compito di valutare gli oggetti che vorrebbero vedere disponibili per l'acquisto o lo sblocco all'interno di %1$s. In ultima analisi, gli sviluppatori sceglieranno quali oggetti aggiungere a %1$s.`,
  _ = `Gli oggetti pubblicati in questo Workshop nella scheda %2$s non sono pronti per essere utilizzati immediatamente su %1$s. Gli sviluppatori affidano alla Comunità il compito di valutare gli oggetti che vorrebbero vedere disponibili per l'acquisto o lo sblocco all'interno di %1$s. In ultima analisi, gli sviluppatori sceglieranno quali oggetti aggiungere a %1$s.`,
  _ = `Vendita di oggetti`,
  _ = `Gli oggetti accettati nel Workshop sono resi disponibili per l'acquisto o possono essere sbloccati all'interno di %1$s.`,
  _ = `Vendite dirette degli oggetti`,
  _ = `Gli oggetti di questo Workshop possono essere venduti direttamente nel Workshop di Steam. Questi oggetti potrebbero richiedere l'approvazione degli sviluppatori o della Comunità prima di poter essere vendibili. Sei un creatore di contenuti? Leggi la sezione <a %s>Come guadagnare</a> qui sotto per ulteriori informazioni su come vendere i tuoi contenuti nel Workshop di Steam.`,
  _ = `Gli autori di oggetti possono ricevere le royalty`,
  _ = `Gli oggetti di questo Workshop che verranno accettati per la vendita consentiranno agli autori di spartirsene il ricavo, se hanno un prezzo.`,
  _ = `Anche i fornitori di servizi possono ottenere royalty`,
  _ = `Gli autori del Workshop possono scegliere da una lista pre-approvata di organizzazioni, utenti e sviluppatori per ricevere una percentuale del ricavo di Valve relativo alla vendita dei propri oggetti. Le organizzazioni e le persone specifiche sono elencate qui sotto.`,
  _ = `Sei un creatore di contenuti e conosci un'altra organizzazione o persona con cui ti piacerebbe condividere il successo delle vendite del tuo oggetto? Faccelo sapere nell'area <a href="%1$s">delle discussioni</a>.`,
  _ = `Quota dei ricavi`,
  _ = `Questa è la percentuale del ricavo che un autore riceve dalle vendite dirette del suo oggetto.`,
  _ = `Clicca %1$s per saperne di più.`,
  _ = `qui`,
  _ = `Oggetti pubblicati in questo Workshop`,
  _ = `Oggetti accettati per %1$s`,
  _ = `Collegamenti correlati`,
  _ = `Visualizza la documentazione ufficiale`,
  _ = `Trova guide di Steam`,
  _ = `Le guide create dalla Comunità per questo Workshop`,
  _ = `Per gli acquisti tramite il Workshop di Steam`,
  _ = `Termini del Workshop di Steam`,
  _ = `Per i ricavi del Workshop di Steam`,
  _ = `Fornitori di servizi`,
  _ = `Mostra sito`,
  _ = `Mostra profilo di Steam`,
  _ = `Strumenti`,
  _ = `Comunità`,
  _ = `Utenti`,
  _ = `Visualizza dettagli`,
  _ = `Vista rapida`,
  _ = `Vota`,
  _ = `per oggetti creati dalla Comunità che vorresti vedere in gioco`,
  _ = `Clicca per iniziare a votare gli oggetti del tuo elenco.`,
  _ = `Finora hai valutato %1$s oggetto.`,
  _ = `Finora hai valutato %1$s oggetti.`,
  _ = `Nella scorsa settimana`,
  _ = `Nel mese scorso`,
  _ = `Negli ultimi tre mesi`,
  _ = `Negli ultimi sei mesi`,
  _ = `Nell'ultimo anno`,
  _ = `Dagli autori che segui`,
  _ = `Oggetti pubblicati di recente dagli autori che segui`,
  _ = `Altro dagli autori che segui`,
  _ = `Oggetti accettati`,
  _ = `Questi oggetti sono stati accettati e potrebbero essere trovati o acquistati in gioco`,
  _ = `Vedi tutti gli oggetti accettati`,
  _ = `%1$s più popolari`,
  _ = `Più popolari`,
  _ = `Con le migliori recensioni negli ultimi tre mesi`,
  _ = `Visualizza più popolari`,
  _ = `Più sottoscritti`,
  _ = `Più sottoscrittori unici attuali`,
  _ = `Visualizza i più sottoscritti`,
  _ = `Nuovi`,
  _ = `Oggetti pubblicati più di recente`,
  _ = `Visualizza pubblicati di recente`,
  _ = `Tempo di gioco maggiore`,
  _ = `Visualizza più giocati`,
  _ = `Ultimo aggiornamento`,
  _ = `Oggetti aggiornati più di recente`,
  _ = `Visualizza aggiornati di recente`,
  _ = `Preferiti degli amici`,
  _ = `Oggetti preferiti dai tuoi amici`,
  _ = `Mostra tutti i preferiti degli amici`,
  _ = `Più richiesti da altri oggetti`,
  _ = `Gli oggetti più popolari che altri oggetti richiedono per funzionare correttamente`,
  _ = `Mostra tutti`,
  _ = `Articoli più gettonati`,
  _ = `Visualizza gli articoli più gettonati`,
  _ = `Mostra tutto`,
  _ = `I tuoi preferiti`,
  _ = `Visualizza preferiti aggiornati di recente`,
  _ = `Oggetti con cui hai giocato`,
  _ = `Visualizza gli oggetti recentemente aggiornati con cui hai giocato`,
  _ = `Le tue sottoscrizioni`,
  _ = `Visualizza le tue sottoscrizioni aggiornate di recente`,
  _ = `Aggiornati negli ultimi tre mesi`,
  _ = `Evento speciale: %1$s`,
  _ = `Mostra tutti gli oggetti etichettati come "%1$s"`,
  _ = `%1$s amico lo ha aggiunto ai suoi preferiti`,
  _ = `%1$s amici lo hanno aggiunto ai loro preferiti`,
  _ = `Mappe`,
  _ = `Oggetti`,
  _ = `Modalità personalizzate e script dei bot`,
  _ = `Articoli`,
  _ = `Filtra per Eroe`,
  _ = `Mappe`,
  _ = `Oggetti`,
  _ = {
    language: _,
    Header_WorkshopTitle: _,
    Header_App_WorkshopTitle: _,
    Workshop_Error_Loading: _,
    Workshop_Error_Title: _,
    Workshop_Error_Browse_Desc: _,
    Error_Sorry: _,
    Error_Encountered: _,
    Error_TooManyRequests_Description: _,
    Workshop_ExitReact_Link: _,
    Workshop_Browsing: _,
    Workshop_Browsing_Mtx_Desc: _,
    Workshop_Browsing_ReadyToUse_Desc: _,
    Workshop_Browsing_Merchandise_Desc: _,
    Workshop_AcceptedForGame: _,
    Workshop_AcceptedMerch: _,
    Workshop_OfficialContent: _,
    Workshop_Browse_Author_Link: _,
    Workshop_Section_Mtx: _,
    Workshop_Section_ReadyToUse: _,
    Workshop_Section_Collections: _,
    Workshop_Section_Merchandise: _,
    Workshop_Section_Videos: _,
    Workshop_Saved_Queries: _,
    Workshop_Saved_Queries_Update: _,
    Workshop_Saved_Queries_Save_Title: _,
    Workshop_Saved_Queries_Save_Desc_Long: _,
    Workshop_Saved_Queries_Save_Desc: _,
    Workshop_Saved_Queries_Save_New: _,
    Workshop_Saved_Queries_Save_Btn: _,
    Workshop_Saved_Queries_Delete_Title: _,
    Workshop_Saved_Queries_Delete_Desc: _,
    Workshop_Saved_Queries_Delete_Btn: _,
    Workshop_LearnMore: _,
    Workshop_Filters_ClearBtn: _,
    Workshop_About: _,
    Workshop_BrowseSort_SortOrder: _,
    Workshop_BrowseSort_TimeFrame: _,
    SharedFiles_Browse_Trend_Option_Today: _,
    SharedFiles_Browse_Trend_Option_Week: _,
    SharedFiles_Browse_Trend_Option_Month: _,
    SharedFiles_Browse_Trend_Option_ThreeMonths: _,
    SharedFiles_Browse_Trend_Option_SixMonths: _,
    SharedFiles_Browse_Trend_Option_OneYear: _,
    SharedFiles_Browse_Trend_Option_AllTime: _,
    Workshop_BrowseSort_Combined: _,
    Workshop_BrowseSort_MostRecent: _,
    Workshop_BrowseSort_MostPopular: _,
    Workshop_BrowseSort_TopRated: _,
    Workshop_BrowseSort_LastUpdated: _,
    Workshop_BrowseSort_Reported: _,
    Workshop_BrowseSort_AdminOption: _,
    Workshop_BrowseSort_NumParentItems: _,
    Workshop_BrowseSort_NumParentCollections: _,
    Workshop_RequireApproval: _,
    Workshop_BrowseSort_ToRate: _,
    Workshop_BrowseSort_TotalUniqueSubscribers: _,
    Workshop_BrowseSort_TotalVotes: _,
    Workshop_BrowseSort_MostUpVotes: _,
    Workshop_BrowseSort_SearchRelevance: _,
    Workshop_BrowseSort_Playtime: _,
    Workshop_BrowseSort_PlaytimeTotal: _,
    Workshop_BrowseSort_PlaytimeAverage: _,
    Workshop_BrowseSort_PlaytimeAverageTotal: _,
    Workshop_BrowseSort_PlaytimeSessions: _,
    Workshop_BrowseSort_PlaytimeSessionsTotal: _,
    Workshop_BrowseSort_Inappropriate: _,
    Workshop_BrowseSort_BanContentCheck: _,
    Workshop_BrowseSort_CuratedAdmin: _,
    Workshop_BrowseSort_Nominee: _,
    Workshop_BrowseSort_Rated: _,
    Workshop_BrowseSort_AcceptedTime: _,
    Workshop_SpecialFilter_Desc: _,
    Workshop_SpecialFilter_None: _,
    Workshop_SpecialFilter_AcceptedForUse: _,
    Workshop_SpecialFilter_CreatedByFriends: _,
    Workshop_SpecialFilter_CreatedByFollowed: _,
    Workshop_SpecialFilter_FavoritedByFriends: _,
    Workshop_SpecialFilter_Reported: _,
    Workshop_SpecialFilter_ParentItems: _,
    Workshop_SpecialFilter_ParentCollections: _,
    Workshop_Menu_Home: _,
    Workshop_Menu_Browse: _,
    Workshop_Menu_YourItems: _,
    Workshop_Menu_Discussions: _,
    Workshop_Menu_About: _,
    Workshop_Menu_Search: _,
    Workshop_SubMenu_YourItems: _,
    Workshop_SubMenu_YourFavorites: _,
    Workshop_SubMenu_YourSubscriptions: _,
    Workshop_SubMenu_YourPlayed: _,
    Workshop_SubMenu_YourCollections: _,
    Workshop_SubMenu_YourVotingQueue: _,
    Workshop_SubMenu_YourPaymentInfo: _,
    Workshop_SubMenu_ViewYourRevenue: _,
    Workshop_SubMenu_ViewYourRevenue_Desc: _,
    Workshop_SubMenu_LegalAgreement: _,
    Workshop_SubMenu_VotingQueue: _,
    Workshop_ApplyFilters: _,
    Workshop_SortBy: _,
    Workshop_Tag_NoneSpecified: _,
    Workshop_RequiredDLC_Header: _,
    Workshop_RequiredDLC_Filter: _,
    Workshop_IncludeOwnedDLC_Filter: _,
    Workshop_ExcludeOwnedDLC_Filter: _,
    Workshop_OwnedDLC_None_Filter: _,
    Workshop_OwnedDLC_All_Filter: _,
    Workshop_OwnedDLC_More_Filter: _,
    Workshop_RequiredDLC_IncludeOwned: _,
    Workshop_RequiredDLC_ExcludeUnowned: _,
    Workshop_RequiredDLC_NameFilter: _,
    Workshop_Flag_Incompatible_Checkbox: _,
    Workshop_Flag_Incompatible_Checkbox_Desc: _,
    Workshop_Admin_View: _,
    Workshop_SearchResults_SearchText: _,
    Workshop_SearchResults_SearchText_TitleOnly: _,
    Workshop_SearchResults_SearchText_DescriptionOnly: _,
    Workshop_SearchedForChild: _,
    Workshop_SearchedForRequiredItem: _,
    Workshop_SearchResults_Tag: _,
    Workshop_SearchResults_KVTag: _,
    Workshop_SearchResults_Flag_Incompatible: _,
    Workshop_SearchResults_Flag_Accepted: _,
    Workshop_SearchTarget_MenuTitle: _,
    Workshop_SearchTarget_All: _,
    Workshop_SearchTarget_Title: _,
    Workshop_SearchTarget_Description: _,
    Workshop_Search_Help: _,
    Workshop_Search_Help_Example1: _,
    Workshop_Search_Help_Example2: _,
    Workshop_Search_Help_Example3: _,
    Workshop_Search_Help_Example_Red: _,
    Workshop_Search_Help_Example_Blue: `blu`,
    Workshop_Search_Help_Example_Green: _,
    Workshop_Search_Help_Example_Room: _,
    Workshop_Search_Help_Advanced: _,
    Workshop_Search_Help_AdvancedExample1: _,
    Workshop_Search_Help_AdvancedExample2: _,
    Workshop_FiltersMenu_State_Title: _,
    Workshop_FiltersMenu_State_Left: _,
    Workshop_FiltersMenu_State_Right: _,
    Workshop_FiltersMenu_State_Collapsed: _,
    Workshop_DimmedItems_Title: _,
    Workshop_DimmedItems_Reported: _,
    Workshop_DimmedItems_BlockedCreators: _,
    Workshop_DimmedItems_VotedUp: _,
    Workshop_DimmedItems_VotedDown: _,
    Workshop_DimmedItems_Subscribed: _,
    Workshop_DateFilter_FilterByDate: _,
    Workshop_DateFilter_TimeCreated: _,
    Workshop_DateFilter_TimeCreated_After: _,
    Workshop_DateFilter_TimeCreated_Before: _,
    Workshop_DateFilter_TimeCreated_Between: _,
    Workshop_DateFilter_TimeUpdated: _,
    Workshop_DateFilter_TimeUpdated_After: _,
    Workshop_DateFilter_TimeUpdated_Before: _,
    Workshop_DateFilter_TimeUpdated_Between: _,
    Workshop_DateFilter_Between: `tra`,
    Workshop_DateFilter_And: `e`,
    Workshop_NumResults: _,
    Workshop_NumResults_Plural: _,
    Workshop_NumPerPage: _,
    Workshop_PagingControls: _,
    Workshop_CreateCollection: _,
    Workshop_CreateMerchandise: _,
    Workshop_Item_QuickView: _,
    Workshop_Item_QuickView_ExpandBtn: _,
    Workshop_StatusIcon_TT_Subscribed: _,
    Workshop_StatusIcon_TT_Favorited: _,
    Workshop_StatusIcon_TT_Played: _,
    Workshop_StatusIcon_TT_Accepted: _,
    Workshop_StatusIcon_TT_Incompatible: _,
    Workshop_StatusIcon_TT_VotedUp: _,
    Workshop_StatusIcon_TT_VotedDown: _,
    Workshop_StatusIcon_TT_Reported: _,
    Workshop_StatusIcon_TT_BlockedCreator: _,
    Workshop_ItemDetails_Tab_Description: _,
    Workshop_ItemDetails_Tab_Discussions: _,
    Workshop_ItemDetails_Tab_Comments: _,
    Workshop_ItemDetails_Tab_Updates: _,
    Workshop_ItemDetails_Tab_Stats: _,
    Workshop_ItemDetails_Tab_ChangeNotes: _,
    Workshop_ItemDetails_Title: _,
    Workshop_ItemDetails_CreatedBy: _,
    Workshop_ItemDetails_NumRatings: _,
    Workshop_ItemDetails_NumRatings_Plural: _,
    Workshop_ItemDetails_NotEnoughRatings: _,
    Workshop_ItemDetails_TimestampWithTime: _,
    Workshop_ItemDetails_TimestampCreated: _,
    Workshop_ItemDetails_TimestampUpdated: _,
    Workshop_ItemDetails_Subscribe: _,
    Workshop_ItemDetails_Subscribed: _,
    Workshop_ItemDetails_Unsubscribe: _,
    Workshop_ItemDetails_Favorite: _,
    Workshop_ItemDetails_Favorited: _,
    Workshop_ItemDetails_Unfavorite: _,
    Workshop_ItemDetails_ViewDependentItems: _,
    Workshop_ItemDetails_AddToCollection: _,
    Workshop_ItemDetails_SaveCollectionToCollection: _,
    Workshop_ItemDetails_Signin_TT: _,
    Workshop_ItemDetails_Subscribe_TT: _,
    Workshop_ItemDetails_Unsubscribe_TT: _,
    Workshop_ItemDetails_Favorite_TT: _,
    Workshop_ItemDetails_ViewDependentItems_TT: _,
    Workshop_ItemDetails_Report_TT: _,
    Workshop_ItemDetails_Award_TT: _,
    Workshop_ItemDetails_AddToCollection_TT: _,
    Workshop_ItemDetails_FileSize: _,
    Workshop_ItemDetails_Stats_UniqueVisitors: _,
    Workshop_ItemDetails_Stats_CurrentSubscribers: _,
    Workshop_ItemDetails_Stats_CurrentFavorites: _,
    Workshop_ItemDetails_Stats_LifetimeFavorites: _,
    Workshop_ItemDetails_Stats_LifetimeSubscribers: _,
    Workshop_ItemDetails_Stats_LifetimePlaytimeSessions: _,
    Workshop_ItemDetails_ItemDependencies: _,
    Workshop_ItemDetails_RequiredDLC_Desc: _,
    Workshop_Collection_SubscribeToAll: _,
    Workshop_Collection_UnsubscribeFromAll: _,
    Workshop_Collection_SaveToCollection: _,
    Workshop_ItemDetails_ShowAllReactions: _,
    Workshop_ItemDetails_ReactionCount: _,
    Workshop_ItemDetails_ReactionCount_Plural: _,
    Workshop_ItemDetails_Tags_Title: _,
    Workshop_ItemDetails_Categories_Title: _,
    Workshop_ItemDetails_Description_Title: _,
    Workshop_ItemDetails_DependentItems: _,
    Workshop_ItemDetails_InCollections: _,
    Workshop_ItemDetails_InCollectionsByAuthor: _,
    Workshop_Dialog_Error: _,
    Workshop_Dialog_AccessDenied: _,
    Workshop_Dialog_Timeout: _,
    Workshop_Dialog_LimitExceeded: _,
    Workshop_Dialog_ErrorDesc: _,
    Workshop_Dialog_CollectionSubscribe: _,
    Workshop_Dialog_CollectionSubscribe_Desc: _,
    Workshop_Dialog_CollectionSubscribe_AddOnly: _,
    Workshop_Dialog_CollectionSubscribe_Overwrite: _,
    Workshop_Dialog_ItemDependencies: _,
    Workshop_Dialog_ItemDependencies_Desc1: _,
    Workshop_Dialog_ItemDependencies_Desc1_itemName: _,
    Workshop_Dialog_ItemDependencies_Desc2: _,
    Workshop_Dialog_ItemDependencies_Desc3: _,
    Workshop_Dialog_SubscribeJustThisItem: _,
    Workshop_Dialog_SubscribeAll: _,
    Workshop_Dialog_Report: _,
    Workshop_Dialog_Report_Desc: _,
    Workshop_Dialog_Report_Reason: _,
    Workshop_Dialog_Report_Reason_Desc: _,
    Workshop_Dialog_Report_DMCA_Desc: _,
    Workshop_Dialog_Report_Trademark_Desc: _,
    Workshop_Dialog_Report_Here: `qui`,
    Workshop_Dialog_AddToCollection: _,
    Workshop_Dialog_AddToCollection_Desc: _,
    Workshop_Dialog_AddToCollection_NoSavedCollections_Desc: _,
    Workshop_Dialog_AddToCollection_OK: _,
    Workshop_Dialog_AddToCollection_Create: _,
    Workshop_Dialog_SaveCollectionToCollection: _,
    Workshop_Dialog_SaveCollectionToCollection_Desc: _,
    Workshop_Dialog_SaveCollectionToCollection_New: _,
    Workshop_Dialog_SaveCollectionToCollection_Existing: _,
    Workshop_Dialog_SaveCollectionToCollection_NewPrompt: _,
    Workshop_Dialog_SaveCollectionToCollection_Select: _,
    Workshop_Collection_NumChildItems: _,
    Workshop_Collection_NumChildItems_Plural: _,
    Workshop_Collection_NumChildCollections: _,
    Workshop_Collection_NumChildCollections_Plural: _,
    Workshop_Collection_ViewMore: _,
    Workshop_About_PageDesc_Curation: _,
    Workshop_About_PageDesc_ReadyToUseContent1: _,
    Workshop_About_PageDesc_ReadyToUseContent2: _,
    Workshop_About_PageDesc_ReadyToUseContent_Mixed1: _,
    Workshop_About_PageDesc_ReadyToUseContent_Mixed2: _,
    Workshop_About_EnabledFeatures: _,
    Workshop_About_EnabledFeatures_Desc: _,
    Workshop_About_Feature_ReadyToUse: _,
    Workshop_About_Feature_ReadyToUse_Desc: _,
    Workshop_About_Feature_ReadyToUse_Mixed_Desc: _,
    Workshop_About_Feature_Branch_Versioning: _,
    Workshop_About_Feature_Branch_Versioning_Desc: _,
    Workshop_About_Feature_ItemCuration: _,
    Workshop_About_Feature_ItemCuration_Desc: _,
    Workshop_About_Feature_ItemCuration_Mixed_Desc: _,
    Workshop_About_Feature_ItemMtx: _,
    Workshop_About_Feature_ItemMtx_Desc: _,
    Workshop_About_Feature_Commerce: _,
    Workshop_About_Feature_Commerce_Desc: _,
    Workshop_About_Feature_AuthorRoyalties: _,
    Workshop_About_Feature_AuthorRoyalties_Desc: _,
    Workshop_About_Feature_ServiceProviders: _,
    Workshop_About_Feature_ServiceProviders_Desc: _,
    Workshop_About_Request_ServiceProviders: _,
    Workshop_About_RevenueShare: _,
    Workshop_About_RevenueShare_Desc: _,
    Workshop_About_RevenueShare_Link: _,
    Workshop_About_RevenueShare_Here: `qui`,
    Workshop_About_NumItems: _,
    Workshop_About_NumAcceptedItems: _,
    Workshop_About_RelatedLinks: _,
    Workshop_About_ViewOfficialDocs: _,
    Workshop_About_FindGuides: _,
    Workshop_About_FindGuides_Sub: _,
    Workshop_About_RefundLink_Sub: _,
    Workshop_About_WorkshopTerms: _,
    Workshop_About_WorkshopTerms_Sub: _,
    Workshop_About_section_ServiceProviders: _,
    Workshop_ServiceProviderRevenueSharing_ViewSite: _,
    Workshop_ServiceProviderRevenueSharing_ViewSteamProfile: _,
    Workshop_ServiceProvider_Category_Tools: _,
    Workshop_ServiceProvider_Category_Communities: _,
    Workshop_ServiceProvider_Category_Users: _,
    Workshop_GamepadUIAction_ViewDetails: _,
    Workshop_GamepadUIAction_QuickView: _,
    Workshop_Home_VotingQueue: _,
    Workshop_Home_VotingQueue_Desc: _,
    Workshop_Home_VotingQueue_Btn: _,
    Workshop_Home_VotingQueue_Count: _,
    Workshop_Home_VotingQueue_Count_Plural: _,
    Workshop_Home_MostPopular_SubTitle_Week: _,
    Workshop_Home_MostPopular_SubTitle_Month: _,
    Workshop_Home_MostPopular_SubTitle_ThreeMonths: _,
    Workshop_Home_MostPopular_SubTitle_SixMonths: _,
    Workshop_Home_MostPopular_SubTitle_Year: _,
    Workshop_Home_FromFollowedAuthors: _,
    Workshop_Home_FromFollowedAuthors_Desc: _,
    Workshop_Home_FromFollowedAuthors_Btn: _,
    Workshop_Home_AcceptedItems: _,
    Workshop_Home_AcceptedItems_Desc: _,
    Workshop_Home_AcceptedItems_Btn: _,
    Workshop_Home_MostPopular: _,
    Workshop_Home_MostPopular_LongTerm: _,
    Workshop_Home_MostPopular_LongTerm_Desc: _,
    Workshop_Home_MostPopular_LongTerm_Btn: _,
    Workshop_Home_MostSubscribed: _,
    Workshop_Home_MostSubscribed_Desc: _,
    Workshop_Home_MostSubscribed_Btn: _,
    Workshop_Home_MostRecent: _,
    Workshop_Home_MostRecent_Desc: _,
    Workshop_Home_MostRecent_Btn: _,
    Workshop_Home_MostPlaytime: _,
    Workshop_Home_MostPlaytime_Btn: _,
    Workshop_Home_LastUpdated: _,
    Workshop_Home_LastUpdated_Desc: _,
    Workshop_Home_LastUpdated_Btn: _,
    Workshop_Home_FriendsFavorites: _,
    Workshop_Home_FriendsFavorites_Desc: _,
    Workshop_Home_FriendsFavorites_Btn: _,
    Workshop_Home_NumParentItems: _,
    Workshop_Home_NumParentItems_Desc: _,
    Workshop_Home_NumParentItems_Btn: _,
    Workshop_Home_MostPopularMerch: _,
    Workshop_Home_MostPopularMerch_Btn: _,
    Workshop_Home_ViewAll: _,
    Workshop_Home_YourFavorites: _,
    Workshop_Home_YourFavorites_Btn: _,
    Workshop_Home_YourPlayed: _,
    Workshop_Home_YourPlayed_Btn: _,
    Workshop_Home_YourSubscriptions: _,
    Workshop_Home_YourSubscriptions_Btn: _,
    Workshop_Home_YourFiles_LastUpdated: _,
    Workshop_Home_SpecialEvent_Title_Tag: _,
    Workshop_Home_SpecialEvent_Link: _,
    Workshop_ItemTooltip_FriendsWhoFavorited: _,
    Workshop_ItemTooltip_FriendsWhoFavorited_Plural: _,
    SharedFiles_TF2_Tab_Items_ReadyToUse: _,
    SharedFiles_TF2_Tab_Items_Mtx: _,
    SharedFiles_Dota2_Tab_Items_ReadyToUse: _,
    SharedFiles_Dota2_Tab_Items_Mtx: _,
    SharedFiles_Dota2_HeroPicker: _,
    SharedFiles_CSGO_Tab_Items_ReadyToUse: _,
    SharedFiles_CSGO_Tab_Items_Mtx: _,
  };
export {
  _ as Error_Encountered,
  _ as Error_Sorry,
  _ as Error_TooManyRequests_Description,
  _ as Header_App_WorkshopTitle,
  _ as Header_WorkshopTitle,
  _ as SharedFiles_Browse_Trend_Option_AllTime,
  _ as SharedFiles_Browse_Trend_Option_Month,
  _ as SharedFiles_Browse_Trend_Option_OneYear,
  _ as SharedFiles_Browse_Trend_Option_SixMonths,
  _ as SharedFiles_Browse_Trend_Option_ThreeMonths,
  _ as SharedFiles_Browse_Trend_Option_Today,
  _ as SharedFiles_Browse_Trend_Option_Week,
  _ as SharedFiles_CSGO_Tab_Items_Mtx,
  _ as SharedFiles_CSGO_Tab_Items_ReadyToUse,
  _ as SharedFiles_Dota2_HeroPicker,
  _ as SharedFiles_Dota2_Tab_Items_Mtx,
  _ as SharedFiles_Dota2_Tab_Items_ReadyToUse,
  _ as SharedFiles_TF2_Tab_Items_Mtx,
  _ as SharedFiles_TF2_Tab_Items_ReadyToUse,
  _ as Workshop_About,
  _ as Workshop_About_EnabledFeatures,
  _ as Workshop_About_EnabledFeatures_Desc,
  _ as Workshop_About_Feature_AuthorRoyalties,
  _ as Workshop_About_Feature_AuthorRoyalties_Desc,
  _ as Workshop_About_Feature_Branch_Versioning,
  _ as Workshop_About_Feature_Branch_Versioning_Desc,
  _ as Workshop_About_Feature_Commerce,
  _ as Workshop_About_Feature_Commerce_Desc,
  _ as Workshop_About_Feature_ItemCuration,
  _ as Workshop_About_Feature_ItemCuration_Desc,
  _ as Workshop_About_Feature_ItemCuration_Mixed_Desc,
  _ as Workshop_About_Feature_ItemMtx,
  _ as Workshop_About_Feature_ItemMtx_Desc,
  _ as Workshop_About_Feature_ReadyToUse,
  _ as Workshop_About_Feature_ReadyToUse_Desc,
  _ as Workshop_About_Feature_ReadyToUse_Mixed_Desc,
  _ as Workshop_About_Feature_ServiceProviders,
  _ as Workshop_About_Feature_ServiceProviders_Desc,
  _ as Workshop_About_FindGuides,
  _ as Workshop_About_FindGuides_Sub,
  _ as Workshop_About_NumAcceptedItems,
  _ as Workshop_About_NumItems,
  _ as Workshop_About_PageDesc_Curation,
  _ as Workshop_About_PageDesc_ReadyToUseContent1,
  _ as Workshop_About_PageDesc_ReadyToUseContent2,
  _ as Workshop_About_PageDesc_ReadyToUseContent_Mixed1,
  _ as Workshop_About_PageDesc_ReadyToUseContent_Mixed2,
  _ as Workshop_About_RefundLink_Sub,
  _ as Workshop_About_RelatedLinks,
  _ as Workshop_About_Request_ServiceProviders,
  _ as Workshop_About_RevenueShare,
  _ as Workshop_About_RevenueShare_Desc,
  _ as Workshop_About_RevenueShare_Here,
  _ as Workshop_About_RevenueShare_Link,
  _ as Workshop_About_ViewOfficialDocs,
  _ as Workshop_About_WorkshopTerms,
  _ as Workshop_About_WorkshopTerms_Sub,
  _ as Workshop_About_section_ServiceProviders,
  _ as Workshop_AcceptedForGame,
  _ as Workshop_AcceptedMerch,
  _ as Workshop_Admin_View,
  _ as Workshop_ApplyFilters,
  _ as Workshop_BrowseSort_AcceptedTime,
  _ as Workshop_BrowseSort_AdminOption,
  _ as Workshop_BrowseSort_BanContentCheck,
  _ as Workshop_BrowseSort_Combined,
  _ as Workshop_BrowseSort_CuratedAdmin,
  _ as Workshop_BrowseSort_Inappropriate,
  _ as Workshop_BrowseSort_LastUpdated,
  _ as Workshop_BrowseSort_MostPopular,
  _ as Workshop_BrowseSort_MostRecent,
  _ as Workshop_BrowseSort_MostUpVotes,
  _ as Workshop_BrowseSort_Nominee,
  _ as Workshop_BrowseSort_NumParentCollections,
  _ as Workshop_BrowseSort_NumParentItems,
  _ as Workshop_BrowseSort_Playtime,
  _ as Workshop_BrowseSort_PlaytimeAverage,
  _ as Workshop_BrowseSort_PlaytimeAverageTotal,
  _ as Workshop_BrowseSort_PlaytimeSessions,
  _ as Workshop_BrowseSort_PlaytimeSessionsTotal,
  _ as Workshop_BrowseSort_PlaytimeTotal,
  _ as Workshop_BrowseSort_Rated,
  _ as Workshop_BrowseSort_Reported,
  _ as Workshop_BrowseSort_SearchRelevance,
  _ as Workshop_BrowseSort_SortOrder,
  _ as Workshop_BrowseSort_TimeFrame,
  _ as Workshop_BrowseSort_ToRate,
  _ as Workshop_BrowseSort_TopRated,
  _ as Workshop_BrowseSort_TotalUniqueSubscribers,
  _ as Workshop_BrowseSort_TotalVotes,
  _ as Workshop_Browse_Author_Link,
  _ as Workshop_Browsing,
  _ as Workshop_Browsing_Merchandise_Desc,
  _ as Workshop_Browsing_Mtx_Desc,
  _ as Workshop_Browsing_ReadyToUse_Desc,
  _ as Workshop_Collection_NumChildCollections,
  _ as Workshop_Collection_NumChildCollections_Plural,
  _ as Workshop_Collection_NumChildItems,
  _ as Workshop_Collection_NumChildItems_Plural,
  _ as Workshop_Collection_SaveToCollection,
  _ as Workshop_Collection_SubscribeToAll,
  _ as Workshop_Collection_UnsubscribeFromAll,
  _ as Workshop_Collection_ViewMore,
  _ as Workshop_CreateCollection,
  _ as Workshop_CreateMerchandise,
  _ as Workshop_DateFilter_And,
  _ as Workshop_DateFilter_Between,
  _ as Workshop_DateFilter_FilterByDate,
  _ as Workshop_DateFilter_TimeCreated,
  _ as Workshop_DateFilter_TimeCreated_After,
  _ as Workshop_DateFilter_TimeCreated_Before,
  _ as Workshop_DateFilter_TimeCreated_Between,
  _ as Workshop_DateFilter_TimeUpdated,
  _ as Workshop_DateFilter_TimeUpdated_After,
  _ as Workshop_DateFilter_TimeUpdated_Before,
  _ as Workshop_DateFilter_TimeUpdated_Between,
  _ as Workshop_Dialog_AccessDenied,
  _ as Workshop_Dialog_AddToCollection,
  _ as Workshop_Dialog_AddToCollection_Create,
  _ as Workshop_Dialog_AddToCollection_Desc,
  _ as Workshop_Dialog_AddToCollection_NoSavedCollections_Desc,
  _ as Workshop_Dialog_AddToCollection_OK,
  _ as Workshop_Dialog_CollectionSubscribe,
  _ as Workshop_Dialog_CollectionSubscribe_AddOnly,
  _ as Workshop_Dialog_CollectionSubscribe_Desc,
  _ as Workshop_Dialog_CollectionSubscribe_Overwrite,
  _ as Workshop_Dialog_Error,
  _ as Workshop_Dialog_ErrorDesc,
  _ as Workshop_Dialog_ItemDependencies,
  _ as Workshop_Dialog_ItemDependencies_Desc1,
  _ as Workshop_Dialog_ItemDependencies_Desc1_itemName,
  _ as Workshop_Dialog_ItemDependencies_Desc2,
  _ as Workshop_Dialog_ItemDependencies_Desc3,
  _ as Workshop_Dialog_LimitExceeded,
  _ as Workshop_Dialog_Report,
  _ as Workshop_Dialog_Report_DMCA_Desc,
  _ as Workshop_Dialog_Report_Desc,
  _ as Workshop_Dialog_Report_Here,
  _ as Workshop_Dialog_Report_Reason,
  _ as Workshop_Dialog_Report_Reason_Desc,
  _ as Workshop_Dialog_Report_Trademark_Desc,
  _ as Workshop_Dialog_SaveCollectionToCollection,
  _ as Workshop_Dialog_SaveCollectionToCollection_Desc,
  _ as Workshop_Dialog_SaveCollectionToCollection_Existing,
  _ as Workshop_Dialog_SaveCollectionToCollection_New,
  _ as Workshop_Dialog_SaveCollectionToCollection_NewPrompt,
  _ as Workshop_Dialog_SaveCollectionToCollection_Select,
  _ as Workshop_Dialog_SubscribeAll,
  _ as Workshop_Dialog_SubscribeJustThisItem,
  _ as Workshop_Dialog_Timeout,
  _ as Workshop_DimmedItems_BlockedCreators,
  _ as Workshop_DimmedItems_Reported,
  _ as Workshop_DimmedItems_Subscribed,
  _ as Workshop_DimmedItems_Title,
  _ as Workshop_DimmedItems_VotedDown,
  _ as Workshop_DimmedItems_VotedUp,
  _ as Workshop_Error_Browse_Desc,
  _ as Workshop_Error_Loading,
  _ as Workshop_Error_Title,
  _ as Workshop_ExcludeOwnedDLC_Filter,
  _ as Workshop_ExitReact_Link,
  _ as Workshop_FiltersMenu_State_Collapsed,
  _ as Workshop_FiltersMenu_State_Left,
  _ as Workshop_FiltersMenu_State_Right,
  _ as Workshop_FiltersMenu_State_Title,
  _ as Workshop_Filters_ClearBtn,
  _ as Workshop_Flag_Incompatible_Checkbox,
  _ as Workshop_Flag_Incompatible_Checkbox_Desc,
  _ as Workshop_GamepadUIAction_QuickView,
  _ as Workshop_GamepadUIAction_ViewDetails,
  _ as Workshop_Home_AcceptedItems,
  _ as Workshop_Home_AcceptedItems_Btn,
  _ as Workshop_Home_AcceptedItems_Desc,
  _ as Workshop_Home_FriendsFavorites,
  _ as Workshop_Home_FriendsFavorites_Btn,
  _ as Workshop_Home_FriendsFavorites_Desc,
  _ as Workshop_Home_FromFollowedAuthors,
  _ as Workshop_Home_FromFollowedAuthors_Btn,
  _ as Workshop_Home_FromFollowedAuthors_Desc,
  _ as Workshop_Home_LastUpdated,
  _ as Workshop_Home_LastUpdated_Btn,
  _ as Workshop_Home_LastUpdated_Desc,
  _ as Workshop_Home_MostPlaytime,
  _ as Workshop_Home_MostPlaytime_Btn,
  _ as Workshop_Home_MostPopular,
  _ as Workshop_Home_MostPopularMerch,
  _ as Workshop_Home_MostPopularMerch_Btn,
  _ as Workshop_Home_MostPopular_LongTerm,
  _ as Workshop_Home_MostPopular_LongTerm_Btn,
  _ as Workshop_Home_MostPopular_LongTerm_Desc,
  _ as Workshop_Home_MostPopular_SubTitle_Month,
  _ as Workshop_Home_MostPopular_SubTitle_SixMonths,
  _ as Workshop_Home_MostPopular_SubTitle_ThreeMonths,
  _ as Workshop_Home_MostPopular_SubTitle_Week,
  _ as Workshop_Home_MostPopular_SubTitle_Year,
  _ as Workshop_Home_MostRecent,
  _ as Workshop_Home_MostRecent_Btn,
  _ as Workshop_Home_MostRecent_Desc,
  _ as Workshop_Home_MostSubscribed,
  _ as Workshop_Home_MostSubscribed_Btn,
  _ as Workshop_Home_MostSubscribed_Desc,
  _ as Workshop_Home_NumParentItems,
  _ as Workshop_Home_NumParentItems_Btn,
  _ as Workshop_Home_NumParentItems_Desc,
  _ as Workshop_Home_SpecialEvent_Link,
  _ as Workshop_Home_SpecialEvent_Title_Tag,
  _ as Workshop_Home_ViewAll,
  _ as Workshop_Home_VotingQueue,
  _ as Workshop_Home_VotingQueue_Btn,
  _ as Workshop_Home_VotingQueue_Count,
  _ as Workshop_Home_VotingQueue_Count_Plural,
  _ as Workshop_Home_VotingQueue_Desc,
  _ as Workshop_Home_YourFavorites,
  _ as Workshop_Home_YourFavorites_Btn,
  _ as Workshop_Home_YourFiles_LastUpdated,
  _ as Workshop_Home_YourPlayed,
  _ as Workshop_Home_YourPlayed_Btn,
  _ as Workshop_Home_YourSubscriptions,
  _ as Workshop_Home_YourSubscriptions_Btn,
  _ as Workshop_IncludeOwnedDLC_Filter,
  _ as Workshop_ItemDetails_AddToCollection,
  _ as Workshop_ItemDetails_AddToCollection_TT,
  _ as Workshop_ItemDetails_Award_TT,
  _ as Workshop_ItemDetails_Categories_Title,
  _ as Workshop_ItemDetails_CreatedBy,
  _ as Workshop_ItemDetails_DependentItems,
  _ as Workshop_ItemDetails_Description_Title,
  _ as Workshop_ItemDetails_Favorite,
  _ as Workshop_ItemDetails_Favorite_TT,
  _ as Workshop_ItemDetails_Favorited,
  _ as Workshop_ItemDetails_FileSize,
  _ as Workshop_ItemDetails_InCollections,
  _ as Workshop_ItemDetails_InCollectionsByAuthor,
  _ as Workshop_ItemDetails_ItemDependencies,
  _ as Workshop_ItemDetails_NotEnoughRatings,
  _ as Workshop_ItemDetails_NumRatings,
  _ as Workshop_ItemDetails_NumRatings_Plural,
  _ as Workshop_ItemDetails_ReactionCount,
  _ as Workshop_ItemDetails_ReactionCount_Plural,
  _ as Workshop_ItemDetails_Report_TT,
  _ as Workshop_ItemDetails_RequiredDLC_Desc,
  _ as Workshop_ItemDetails_SaveCollectionToCollection,
  _ as Workshop_ItemDetails_ShowAllReactions,
  _ as Workshop_ItemDetails_Signin_TT,
  _ as Workshop_ItemDetails_Stats_CurrentFavorites,
  _ as Workshop_ItemDetails_Stats_CurrentSubscribers,
  _ as Workshop_ItemDetails_Stats_LifetimeFavorites,
  _ as Workshop_ItemDetails_Stats_LifetimePlaytimeSessions,
  _ as Workshop_ItemDetails_Stats_LifetimeSubscribers,
  _ as Workshop_ItemDetails_Stats_UniqueVisitors,
  _ as Workshop_ItemDetails_Subscribe,
  _ as Workshop_ItemDetails_Subscribe_TT,
  _ as Workshop_ItemDetails_Subscribed,
  _ as Workshop_ItemDetails_Tab_ChangeNotes,
  _ as Workshop_ItemDetails_Tab_Comments,
  _ as Workshop_ItemDetails_Tab_Description,
  _ as Workshop_ItemDetails_Tab_Discussions,
  _ as Workshop_ItemDetails_Tab_Stats,
  _ as Workshop_ItemDetails_Tab_Updates,
  _ as Workshop_ItemDetails_Tags_Title,
  _ as Workshop_ItemDetails_TimestampCreated,
  _ as Workshop_ItemDetails_TimestampUpdated,
  _ as Workshop_ItemDetails_TimestampWithTime,
  _ as Workshop_ItemDetails_Title,
  _ as Workshop_ItemDetails_Unfavorite,
  _ as Workshop_ItemDetails_Unsubscribe,
  _ as Workshop_ItemDetails_Unsubscribe_TT,
  _ as Workshop_ItemDetails_ViewDependentItems,
  _ as Workshop_ItemDetails_ViewDependentItems_TT,
  _ as Workshop_ItemTooltip_FriendsWhoFavorited,
  _ as Workshop_ItemTooltip_FriendsWhoFavorited_Plural,
  _ as Workshop_Item_QuickView,
  _ as Workshop_Item_QuickView_ExpandBtn,
  _ as Workshop_LearnMore,
  _ as Workshop_Menu_About,
  _ as Workshop_Menu_Browse,
  _ as Workshop_Menu_Discussions,
  _ as Workshop_Menu_Home,
  _ as Workshop_Menu_Search,
  _ as Workshop_Menu_YourItems,
  _ as Workshop_NumPerPage,
  _ as Workshop_NumResults,
  _ as Workshop_NumResults_Plural,
  _ as Workshop_OfficialContent,
  _ as Workshop_OwnedDLC_All_Filter,
  _ as Workshop_OwnedDLC_More_Filter,
  _ as Workshop_OwnedDLC_None_Filter,
  _ as Workshop_PagingControls,
  _ as Workshop_RequireApproval,
  _ as Workshop_RequiredDLC_ExcludeUnowned,
  _ as Workshop_RequiredDLC_Filter,
  _ as Workshop_RequiredDLC_Header,
  _ as Workshop_RequiredDLC_IncludeOwned,
  _ as Workshop_RequiredDLC_NameFilter,
  _ as Workshop_Saved_Queries,
  _ as Workshop_Saved_Queries_Delete_Btn,
  _ as Workshop_Saved_Queries_Delete_Desc,
  _ as Workshop_Saved_Queries_Delete_Title,
  _ as Workshop_Saved_Queries_Save_Btn,
  _ as Workshop_Saved_Queries_Save_Desc,
  _ as Workshop_Saved_Queries_Save_Desc_Long,
  _ as Workshop_Saved_Queries_Save_New,
  _ as Workshop_Saved_Queries_Save_Title,
  _ as Workshop_Saved_Queries_Update,
  _ as Workshop_SearchResults_Flag_Accepted,
  _ as Workshop_SearchResults_Flag_Incompatible,
  _ as Workshop_SearchResults_KVTag,
  _ as Workshop_SearchResults_SearchText,
  _ as Workshop_SearchResults_SearchText_DescriptionOnly,
  _ as Workshop_SearchResults_SearchText_TitleOnly,
  _ as Workshop_SearchResults_Tag,
  _ as Workshop_SearchTarget_All,
  _ as Workshop_SearchTarget_Description,
  _ as Workshop_SearchTarget_MenuTitle,
  _ as Workshop_SearchTarget_Title,
  _ as Workshop_Search_Help,
  _ as Workshop_Search_Help_Advanced,
  _ as Workshop_Search_Help_AdvancedExample1,
  _ as Workshop_Search_Help_AdvancedExample2,
  _ as Workshop_Search_Help_Example1,
  _ as Workshop_Search_Help_Example2,
  _ as Workshop_Search_Help_Example3,
  _ as Workshop_Search_Help_Example_Blue,
  _ as Workshop_Search_Help_Example_Green,
  _ as Workshop_Search_Help_Example_Red,
  _ as Workshop_Search_Help_Example_Room,
  _ as Workshop_SearchedForChild,
  _ as Workshop_SearchedForRequiredItem,
  _ as Workshop_Section_Collections,
  _ as Workshop_Section_Merchandise,
  _ as Workshop_Section_Mtx,
  _ as Workshop_Section_ReadyToUse,
  _ as Workshop_Section_Videos,
  _ as Workshop_ServiceProviderRevenueSharing_ViewSite,
  _ as Workshop_ServiceProviderRevenueSharing_ViewSteamProfile,
  _ as Workshop_ServiceProvider_Category_Communities,
  _ as Workshop_ServiceProvider_Category_Tools,
  _ as Workshop_ServiceProvider_Category_Users,
  _ as Workshop_SortBy,
  _ as Workshop_SpecialFilter_AcceptedForUse,
  _ as Workshop_SpecialFilter_CreatedByFollowed,
  _ as Workshop_SpecialFilter_CreatedByFriends,
  _ as Workshop_SpecialFilter_Desc,
  _ as Workshop_SpecialFilter_FavoritedByFriends,
  _ as Workshop_SpecialFilter_None,
  _ as Workshop_SpecialFilter_ParentCollections,
  _ as Workshop_SpecialFilter_ParentItems,
  _ as Workshop_SpecialFilter_Reported,
  _ as Workshop_StatusIcon_TT_Accepted,
  _ as Workshop_StatusIcon_TT_BlockedCreator,
  _ as Workshop_StatusIcon_TT_Favorited,
  _ as Workshop_StatusIcon_TT_Incompatible,
  _ as Workshop_StatusIcon_TT_Played,
  _ as Workshop_StatusIcon_TT_Reported,
  _ as Workshop_StatusIcon_TT_Subscribed,
  _ as Workshop_StatusIcon_TT_VotedDown,
  _ as Workshop_StatusIcon_TT_VotedUp,
  _ as Workshop_SubMenu_LegalAgreement,
  _ as Workshop_SubMenu_ViewYourRevenue,
  _ as Workshop_SubMenu_ViewYourRevenue_Desc,
  _ as Workshop_SubMenu_VotingQueue,
  _ as Workshop_SubMenu_YourCollections,
  _ as Workshop_SubMenu_YourFavorites,
  _ as Workshop_SubMenu_YourItems,
  _ as Workshop_SubMenu_YourPaymentInfo,
  _ as Workshop_SubMenu_YourPlayed,
  _ as Workshop_SubMenu_YourSubscriptions,
  _ as Workshop_SubMenu_YourVotingQueue,
  _ as Workshop_Tag_NoneSpecified,
  _ as default,
  _ as language,
};
