var _ = `tchinese`,
  _ = `引用自 %1$s：`,
  _ = `{連結已移除}`,
  _ = `這裡連結的網址已經被我們的過濾器移除。通常是為了防止網路釣魚和惡意軟體攻擊。`,
  _ = `（僅限 Valve/ 管理員）點擊以顯示連結`,
  _ = `%1$s 則留言`,
  _ = `目前顯示第 %1$s-%2$s 則留言，共 %3$s 則`,
  _ = `新增留言`,
  _ = `發表留言`,
  _ = `格式說明`,
  _ = `插入表情符號`,
  _ = `%1$s 表情符號`,
  _ = `搜尋`,
  _ = `近期使用`,
  _ = `所有表情符號`,
  _ = `沒有與搜尋相符的表情符號。`,
  _ = `您尚未擁有任何表情符號。`,
  _ = `文字格式`,
  _ = `這些標記能讓您為留言和文章內的文字加上格式，和 HTML 相似。`,
  _ = `語法`,
  _ = `範例`,
  _ = `粗體`,
  _ = `底線`,
  _ = `斜體`,
  _ = `刪除線`,
  _ = `隱藏文字`,
  _ = `不解析[b]標籤[/b] `,
  _ = `網站連結`,
  _ = `引用文字`,
  _ = `等寬字體、
保留空格`,
  _ = `標題文字`,
  _ = `標題文字`,
  _ = `標題文字`,
  _ = `項目符號列表`,
  _ = `排序列表`,
  _ = `訂閱留言串`,
  _ = `取消訂閱留言串`,
  _ = `訂閱留言串以便在有人發表新留言時收到通知`,
  _ = `由於這是您的 Steam 個人檔案底下的留言串，系統已自動替您訂閱`,
  _ = `更新您的訂閱時發生錯誤，請稍後再試。`,
  _ = `刪除`,
  _ = `隱藏並檢舉這篇留言`,
  _ = `標記可疑內容`,
  _ = `清除可封鎖內容旗標：%1$s`,
  _ = `未掃描`,
  _ = `重設`,
  _ = `需要檢查`,
  _ = `極不可能`,
  _ = `不太可能`,
  _ = `可能`,
  _ = `較有可能`,
  _ = `極有可能`,
  _ = `未知（%1$s）`,
  _ = `在板務工具中開啟`,
  _ = `您已檢舉這篇留言`,
  _ = `您已封鎖這位玩家`,
  _ = `復原`,
  _ = `檢視這篇留言`,
  _ = `您具有客服 / 板務權限，因此看得到內容。`,
  _ = `這篇留言正在等待我們的自動內容檢查系統進行分析。在確認內容無害之前（例如：試圖竊取資訊的釣魚網站連結），此項目將暫時維持隱藏狀態。`,
  _ = `這篇留言經系統自動標示為包含可能有害的內容，因此已被隱藏。`,
  _ = `在正常狀況下，您不能在此處發表留言，但您擁有的額外權限允許您這麼做。`,
  _ = `這篇留言已被刪除。`,
  _ = `您的留言過短。`,
  _ = `您的留言過長。長度限制為 %1$s 個字元。`,
  _ = `您無法在這裡發表留言。`,
  _ = `您必須登入才能發表留言。`,
  _ = `您必須擁有此遊戲才能對此項目發表留言。`,
  _ = `您必須擁有至少一小時的遊玩時間才能發表留言。`,
  _ = `此項目已停用留言功能。`,
  _ = `尚無任何留言。`,
  _ = {
    language: _,
    CommentThread_QuoteBlock_Author: _,
    CommentThread_RemovedLink: _,
    CommentThread_RemovedLink_Tooltip: _,
    CommentThread_RemovedLink_Reveal: _,
    CommentThread_NumberOfComments: _,
    CommentThread_ShowingXToYOfTotal: _,
    CommentThread_AddAComment: _,
    CommentThread_PostComment: _,
    CommentThread_FormattingHelp: _,
    CommentThread_InsertEmoticon: _,
    CommentThread_EmoticonHoverApp: _,
    CommentThread_EmoticonSearch: _,
    CommentThread_EmoticonRecentlyUsed: _,
    CommentThread_EmoticonAll: _,
    CommentThread_EmoticonNoResults: _,
    CommentThread_EmoticonNoneOwned: _,
    CommentThread_FormattingHelpHeader: _,
    Discussions_FormattingHelp_Description: _,
    Discussions_FormattingHelp_ColumnSyntax: _,
    Discussions_FormattingHelp_ColumnExample: _,
    Discussions_FormattingHelp_Bold: _,
    Discussions_FormattingHelp_Underline: _,
    Discussions_FormattingHelp_Italic: _,
    Discussions_FormattingHelp_Strike: _,
    Discussions_FormattingHelp_Spoiler: _,
    Discussions_FormattingHelp_Noparse: _,
    Discussions_FormattingHelp_Link: _,
    Discussions_FormattingHelp_Quote: _,
    Discussions_FormattingHelp_Code: _,
    Discussions_FormattingHelp_H1: _,
    Discussions_FormattingHelp_H2: _,
    Discussions_FormattingHelp_H3: _,
    Discussions_FormattingHelp_List: _,
    Discussions_FormattingHelp_OList: _,
    CommentThread_Subscribe: _,
    CommentThread_Unsubscribe: _,
    CommentThread_SubscribeHint: _,
    CommentThread_SubscribeHintOwnThread: _,
    CommentThread_SubscribeError: _,
    CommentThread_DeleteComment: _,
    CommentThread_HideComment: _,
    CommentThread_MarkSpam: _,
    CommentThread_ClearContentCheck: _,
    BanContentCheckResult_NotScanned: _,
    BanContentCheckResult_Reset: _,
    BanContentCheckResult_NeedsChecking: _,
    BanContentCheckResult_VeryUnlikely: _,
    BanContentCheckResult_Unlikely: _,
    BanContentCheckResult_Possible: _,
    BanContentCheckResult_Likely: _,
    BanContentCheckResult_VeryLikely: _,
    BanContentCheckResult_Unknown: _,
    CommentThread_ModerationTool: _,
    CommentThread_HiddenByUser: _,
    CommentThread_HiddenByBlocked: _,
    CommentThread_HiddenUndo: _,
    CommentThread_HiddenViewComment: _,
    CommentThread_ModeratorViewContent: _,
    CommentThread_NeedsContentCheck: _,
    CommentThread_FailedContentCheck: _,
    CommentThread_PermissionOverride: _,
    CommentThread_Deleted: _,
    CommentThread_PostError_TooShort: _,
    CommentThread_PostError_TooLong: _,
    CommentThread_PostError_NotAllowed: _,
    CommentThread_PostError_NotLoggedIn: _,
    CommentThread_PostError_MustOwnApp: _,
    CommentThread_PostError_LimitedUser: _,
    CommentThread_CommentsDisabled: _,
    CommentThread_NoComments: _,
  };
export {
  _ as BanContentCheckResult_Likely,
  _ as BanContentCheckResult_NeedsChecking,
  _ as BanContentCheckResult_NotScanned,
  _ as BanContentCheckResult_Possible,
  _ as BanContentCheckResult_Reset,
  _ as BanContentCheckResult_Unknown,
  _ as BanContentCheckResult_Unlikely,
  _ as BanContentCheckResult_VeryLikely,
  _ as BanContentCheckResult_VeryUnlikely,
  _ as CommentThread_AddAComment,
  _ as CommentThread_ClearContentCheck,
  _ as CommentThread_CommentsDisabled,
  _ as CommentThread_DeleteComment,
  _ as CommentThread_Deleted,
  _ as CommentThread_EmoticonAll,
  _ as CommentThread_EmoticonHoverApp,
  _ as CommentThread_EmoticonNoResults,
  _ as CommentThread_EmoticonNoneOwned,
  _ as CommentThread_EmoticonRecentlyUsed,
  _ as CommentThread_EmoticonSearch,
  _ as CommentThread_FailedContentCheck,
  _ as CommentThread_FormattingHelp,
  _ as CommentThread_FormattingHelpHeader,
  _ as CommentThread_HiddenByBlocked,
  _ as CommentThread_HiddenByUser,
  _ as CommentThread_HiddenUndo,
  _ as CommentThread_HiddenViewComment,
  _ as CommentThread_HideComment,
  _ as CommentThread_InsertEmoticon,
  _ as CommentThread_MarkSpam,
  _ as CommentThread_ModerationTool,
  _ as CommentThread_ModeratorViewContent,
  _ as CommentThread_NeedsContentCheck,
  _ as CommentThread_NoComments,
  _ as CommentThread_NumberOfComments,
  _ as CommentThread_PermissionOverride,
  _ as CommentThread_PostComment,
  _ as CommentThread_PostError_LimitedUser,
  _ as CommentThread_PostError_MustOwnApp,
  _ as CommentThread_PostError_NotAllowed,
  _ as CommentThread_PostError_NotLoggedIn,
  _ as CommentThread_PostError_TooLong,
  _ as CommentThread_PostError_TooShort,
  _ as CommentThread_QuoteBlock_Author,
  _ as CommentThread_RemovedLink,
  _ as CommentThread_RemovedLink_Reveal,
  _ as CommentThread_RemovedLink_Tooltip,
  _ as CommentThread_ShowingXToYOfTotal,
  _ as CommentThread_Subscribe,
  _ as CommentThread_SubscribeError,
  _ as CommentThread_SubscribeHint,
  _ as CommentThread_SubscribeHintOwnThread,
  _ as CommentThread_Unsubscribe,
  _ as Discussions_FormattingHelp_Bold,
  _ as Discussions_FormattingHelp_Code,
  _ as Discussions_FormattingHelp_ColumnExample,
  _ as Discussions_FormattingHelp_ColumnSyntax,
  _ as Discussions_FormattingHelp_Description,
  _ as Discussions_FormattingHelp_H1,
  _ as Discussions_FormattingHelp_H2,
  _ as Discussions_FormattingHelp_H3,
  _ as Discussions_FormattingHelp_Italic,
  _ as Discussions_FormattingHelp_Link,
  _ as Discussions_FormattingHelp_List,
  _ as Discussions_FormattingHelp_Noparse,
  _ as Discussions_FormattingHelp_OList,
  _ as Discussions_FormattingHelp_Quote,
  _ as Discussions_FormattingHelp_Spoiler,
  _ as Discussions_FormattingHelp_Strike,
  _ as Discussions_FormattingHelp_Underline,
  _ as default,
  _ as language,
};
