var _ = `Laporan konten`,
  _ = `Dikirim olehmu`,
  _ = `Pada kontenmu`,
  _ = `Konten ini tidak ilegal atau melanggar Persyaratan Layanan Steam.`,
  _ = `Jika kamu percaya ini adalah suatu kesalahan, kamu dapat menyengketakan hasil ini.`,
  _ = `Disengketakan: menunggu pemeriksaan`,
  _ = `Komunikasi diblokir`,
  _ = `%1$s - %2$s`,
  _ = `Penyataan Alasan`,
  _ = `Pembatasan Visibilitas`,
  _ = `Fakta dan situasi yang dirujuk untuk pengambilan keputusan`,
  _ = `Alasan keputusan`,
  _ = `Dasar hukum yang dirujuk`,
  _ = `Rujukan ke dasar perjanjian`,
  _ = `Penjelasan tentang mengapa konten dianggap ilegal merujuk pada alasan tersebut`,
  _ = `Jenis konten`,
  _ = `Sumber informasi`,
  _ = `Apakah konten terdeteksi/dikenali menggunakan cara pengautomasian?`,
  _ = `Apakah keputusan diambil dengan cara automasi?`,
  _ = `Konten ilegal`,
  _ = `Konten yang melanggar hukum, merupakan perilaku pelanggaran pidana, menimbulkan tuntutan hukum, atau melanggar hukum apa pun, tidak diizinkan di Steam.`,
  _ = `Konten yang tidak kompatibel dengan syarat dan ketentuan`,
  _ = `Konten di Steam harus memenuhi %1$s dan %2$s.`,
  _ = `Peraturan Perilaku Online Steam`,
  _ = `Perjanjian Pelanggan Steam`,
  _ = `Laporan pengguna`,
  _ = `Tidak ada`,
  _ = `Ya`,
  _ = `Sepenuhnya dengan automasi`,
  _ = `Sebagian dengan automasi`,
  _ = `Konten disembunyikan`,
  _ = `Saat membuat keputusan terkait konten atau akun, kami mempertimbangkan konten yang dimaksud, informasi akun terkait, informasi yang diberikan melalui pelaporan, dan investigasi kami sendiri.`,
  _ = `(placeholder untuk informasi penyelesaian di luar pengadilan)`,
  _ = `Ya`,
  _ = `Tidak`,
  _ = `Kirim`,
  _ = `Batal`,
  _ = `Pemeriksaan Sengketa`,
  _ = `Sertakan semua informasi pendukung untuk sengketamu:`,
  _ = `Dasar sengketa`,
  _ = `Dengan mengeklik %1$s, kamu menyatakan bahwa semua informasi di sini bersifat akurat sesuai dengan yang kamu ketahui.`,
  _ = `Diselesaikan pada %1$s`,
  _ = `Diselesaikan pada %1$s, disengketakan oleh pemilik pada %2$s`,
  _ = `Diselesaikan pada %1$s, disengketakan oleh pemilik pada %2$s, sengketa selesai pada %3$s`,
  _ = `Dilaporkan pada %1$s`,
  _ = `Dilaporkan pada %1$s, diselesaikan pada %2$s`,
  _ = `Dilaporkan pada %1$s, diselesaikan pada %2$s, disengketakan pada %3$s`,
  _ = `Dilaporkan pada %1$s, diselesaikan pada %2$s, disengketakan pada %3$s, sengketa selesai pada %4$s`,
  _ = `pesan obrolan dari %1$s yang dikirim pada %2$s`,
  _ = `pesan di ruang obrolan dari %1$s yang dikirim pada %2$s`,
  _ = `ID Laporan %1$s`,
  _ = `utas komentar`,
  _ = `Laporkan konten`,
  _ = `Ini hanya untuk melaporkan spam, iklan, konten ilegal, dan postingan problematik (pelecehan, perkelahian, atau kasar).`,
  _ = `Apa jenis masalah yang kamu laporkan?`,
  _ = `Kirim Laporan`,
  _ = `Laporkan sebagai:`,
  _ = `Sebelumnya`,
  _ = `Sediakan informasi tambahan yang relevan ke laporanmu. Dengan mengirimkan laporan ini, kamu menyatakan bahwa isinya benar dan akurat sesuai pengetahuanmu.`,
  _ = `Tambahkan informasi tambahan di sini.`,
  _ = `Pelanggaran hak cipta`,
  _ = `Keluhan merek dagang`,
  _ = `Namamu (opsional)`,
  _ = `Kasar`,
  _ = `Aktivitas komersial`,
  _ = `Pelanggaran informasi pelanggan`,
  _ = `Mengeksploitasi anak di bawah umur`,
  _ = `Menganggu`,
  _ = `Pelecehan`,
  _ = `Materi nonkonsensual`,
  _ = `Konten ketelanjangan atau seksual`,
  _ = `Keluar Topik`,
  _ = `Pelanggaran perlindungan data dan privasi`,
  _ = `Ulasan tidak otentik/dimanipulasi`,
  _ = `Penipuan dan pencurian`,
  _ = `Terorisme`,
  _ = `Kekerasan dan menyakiti diri`,
  _ = `Diskusi sosial dan pemilu`,
  _ = `Konten Mencurigakan`,
  _ = `Konten yang Tidak Pantas`,
  _ = `Lainnya`,
  _ = `Phishing, penipuan, menyamar sebagai teman atau Bantuan Steam`,
  _ = `Pelecehan, spam, gambar tidak pantas`,
  _ = `(Tidak diketahui)`,
  _ = `(Tidak diketahui)`,
  _ = `(Tidak diketahui)`,
  _ = `Pelecehan`,
  _ = `Perundungan dan intimidasi`,
  _ = `Penguntitan`,
  _ = `Doxxing`,
  _ = `Pelecehan lainnya`,
  _ = `Mendukung kekerasan`,
  _ = `Membahas atau mendukung tindakan menyakiti diri`,
  _ = `Membahas atau mendukung tindakan bunuh diri`,
  _ = `Tindakan kekerasan atau menyakiti diri lainnya`,
  _ = `Ancaman kekerasan yang nyata`,
  _ = `Mengutip konten yang telah dimoderasi`,
  _ = `Phishing atau pencurian akun`,
  _ = `Manipulasi pemilu atau opini publik`,
  _ = `Percobaan penipuan`,
  _ = `Penautan ke konten berbahaya`,
  _ = `Penyamaran`,
  _ = `Penipuan atau pencurian lainnya`,
  _ = `Mendukung terorisme`,
  _ = `Mengorganisir terorisme`,
  _ = `Lainnya terkait terorisme`,
  _ = `Perilaku Kasar yang Ditargetkan`,
  _ = `Mengejek dan mempermalukan`,
  _ = `Diskriminasi`,
  _ = `Perilaku kasar lainnya`,
  _ = `Trolling`,
  _ = `Provokasi`,
  _ = `Pengalihan`,
  _ = `Perilaku mengganggu lainnya`,
  _ = `Spam`,
  _ = `Mengemis`,
  _ = `Memposting ulang`,
  _ = `Tindakan keluar topik lainnya`,
  _ = `Konten seksual anak di bawah umur`,
  _ = `Merayu atau membujuk anak di bawah umur`,
  _ = `Eksploitasi anak di bawah umur lainnya`,
  _ = `Konten ketelanjangan atau seksual`,
  _ = `Materi nonkonsensual`,
  _ = `Pengiklanan`,
  _ = `Tautan rujukan`,
  _ = `Perjudian`,
  _ = `Undian`,
  _ = `Aktivitas komersial lainnya`,
  _ = `Ulasan tidak otentik atau dimanipulasi`,
  _ = `Iklan atau komunikasi komersial tersembunyi`,
  _ = `Informasi menyesatkan tentang karakteristik barang dan jasa`,
  _ = `Informasi menyesatkan tentang hak konsumen`,
  _ = `Ketidakpatuhan terhadap peraturan penentuan harga`,
  _ = `Hak untuk dilupakan`,
  _ = `Tidak adanya basis untuk pemrosesan data`,
  _ = `Pelanggaran perlindungan data atau privasi lainnya`,
  _ = `Pelecehan terhadap wanita`,
  _ = `Perundungan dan intimidasi terhadap wanita`,
  _ = `Menguntit wanita`,
  _ = `Doksing terhadap wanita`,
  _ = `Pelecehan lainnya terhadap wanita`,
  _ = `Mendorong tindak kekerasan terhadap wanita`,
  _ = `Pelecehan yang menarget wanita`,
  _ = `Konten seksual palsu (deepfake) terhadap anak di bawah umur`,
  _ = `Konten nonkonsensual terhadap wanita`,
  _ = `Konten nonkonsensual palsu (deepfake) terhadap wanita`,
  _ = `Konten nonkonsensual palsu (deepfake)`,
  _ = `Menarget perempuan`,
  _ = `Deepfake`,
  _ = `Pembajakan`,
  _ = `Melanggar Persyaratan Steam`,
  _ = `Salah kategori`,
  _ = `Memintas filter kata-kata kasar`,
  _ = `Laporan dikirim`,
  _ = `Terima kasih telah mengirimkan laporanmu. Laporan tersebut telah dikirim untuk diperiksa oleh moderator.`,
  _ = `Terima kasih telah mengirimkan laporanmu. Kami telah mengumpulkan sebagian kecil dari log obrolan dan mengirimkannya untuk diperiksa. Kamu tidak perlu melakukan tindakan lainnya.`,
  _ = `Terjadi kesalahan saat mengirimkan laporan`,
  _ = `Terjadi kesalahan saat mengirimkan laporanmu. Silakan coba lagi nanti.`,
  _ = `Kamu tidak dapat melaporkan konten untuk sementara waktu.`,
  _ = `Kamu dapat mengambil tindakan tambahan untuk mencegah pesan masuk di waktu mendatang:`,
  _ = `Pengguna ini telah diblokir secara otomatis. Kamu tidak akan lagi menerima pesan dari mereka.`,
  _ = `Batalkan blokiran`,
  _ = `Hapus Teman`,
  _ = `Pengguna ini masih berada dalam Daftar Temanmu dan kamu dapat memilih untuk berhenti berteman. Kamu akan menghilang dari Daftar Temannya tanpa diketahui.`,
  _ = `Teman Dihapus`,
  _ = `Pelajari lebih lanjut tentang penanganan pelanggaran di Steam`,
  _ = `Utas forum`,
  _ = `Utas komentar`,
  _ = `Pesan Obrolan Teman`,
  _ = `Pesan Ruang Obrolan`,
  _ = `Grup Obrolan`,
  _ = `Gambar Konten Buatan Pengguna (UGC)`,
  _ = `(Tidak diketahui)`,
  _ = `Selesaikan tanpa tindakan`,
  _ = `Menunggu pemeriksaan`,
  _ = `Ditinjau: tidak ada tindakan yang diperlukan`,
  _ = `Konten segera dihapus`,
  _ = `Konten dihapus`,
  _ = `Konten dilabel ulang`,
  _ = `Akun dikunci karena konten yang mencurigakan`,
  _ = `Hak istimewa Komunitas Steam-mu ditangguhkan`,
  _ = `Dihapus dan diperingatkan`,
  _ = `Dihapus dan di-ban dari hub`,
  _ = `Dihapus dan dikeluarkan dari grup`,
  _ = `Dihukum`,
  _ = `Tidak Diketahui Kompatibilitasnya`,
  _ = `Dibebaskan`,
  _ = `Laporan aktif terakhir dibatalkan`,
  _ = `Rsolusi disengketakan`,
  _ = `Ditindaklanjuti`,
  _ = `Dihukum`,
  _ = `Pemeriksaan dilanjutkan`,
  _ = `Pembahasan tidak terselesaikan`,
  _ = `Rincian pembahasan diperbarui`,
  _ = `Terkunci`,
  _ = `Dibuka pada`,
  _ = `Dihapus`,
  _ = `Peringatan dikeluarkan`,
  _ = `Di-ban dari hub konten`,
  _ = `Di-ban dari Komunitas Steam`,
  _ = `Di-ban dari melakukan pertukaran`,
  _ = `Konten ditandai sebagai mencurigakan`,
  _ = `Reset konten pembuat`,
  _ = `Diteruskan ke Valve karena mengandung unsur pelecehan seksual anak`,
  _ = `Diteruskan ke Valve karena mengandung unsur terorisme`,
  _ = `Diklaim`,
  _ = `Dirilis`,
  _ = `Pesan pribadi dikirim`,
  _ = `Tindakan Tidak Diketahui`,
  _ = `Moderasi disengketakan oleh pemilik`,
  _ = `Catatan: %1$s`,
  _ = `Peringatan: %1$s`,
  _ = `Ban: %1$s`,
  _ = `Pemberitahuan Penghapusan Konten: %1$s`,
  _ = `Penipuan, phishing, dan pencurian`,
  _ = `Phishing, pencurian, penipuan, penautan ke konten berbahaya, pembuatan identitas palsu yang bertujuan untuk menyesatkan pemain lain`,
  _ = `Privasi`,
  _ = `Doksing, menguntit, mengejek dan mempermalukan, mendistribusikan gambar intim tanpa persetujuan`,
  _ = `Kesalamatan anak-anak`,
  _ = `Eksploitasi anak di bawah umur, pelecehan seksual terhadap anak-anak, membujuk anak di bawah umur, menganiaya anak-anak`,
  _ = `Mempromosikan kekerasan`,
  _ = `Mendorong atau memfasilitasi kekerasan di dunia nyata, menyakiti diri sendiri atau bunuh diri, ancaman bahaya, terorisme`,
  _ = `Pelecehan, perundungan, dan perilaku mengganggu`,
  _ = `Perilaku yang mengganggu forum, termasuk trolling, penggunaan bahasa kasar, spamming, atau memposting ulang konten yang sudah ditutup atau dihapus`,
  _ = `Sensitif atau mengganggu`,
  _ = `Gambar orang asli yang memiliki unsur ketelanjangan dan bersifat seksual eksplisit, konten dewasa tanpa label atau batasan usia tepat, penggambaran kekerasan yang nyata atau meresahkan, atau gore`,
  _ = `Periklanan dan kegiatan komersial`,
  _ = `Tautan rujukan, kontes, undian, perjudian, jual-beli akun Steam`,
  _ = `Melakukan cheat dan pembajakan`,
  _ = `Membahas atau mendorong perilaku cheat, eksploitasi, dan pembajakan game`,
  _ = `Lainnya`,
  _ = `Konten ini ilegal atau tidak pantas berdasarkan alasan yang tidak ditampilkan di sini`,
  _ = `Kekayaan Intelektual`,
  _ = `Melanggar hak cipta atau merek dagang, atau mengabaikan batasan lisensi`,
  _ = `Alasan pelaporan konten: %1$s`,
  _ = `Kamu akan meninggalkan halaman ini dan diarahkan ke formulir laporan hak cipta Steam.`,
  _ = `Kamu akan meninggalkan halaman ini dan diarahkan ke formulir merek dagang Steam.`,
  _ = `Kami telah menerima laporanmu`,
  _ = `Kamu menlaporkan %1$s`,
  _ = `Laporanmu telah diselesaikan`,
  _ = `Tidak ada tindakan yang diambil terkait %1$s`,
  _ = `Laporanmu telah diselesaikan`,
  _ = `Tindakan diambil terkait %1$s`,
  _ = `Kami telah menerima sengketamu`,
  _ = `Kamu menyengketakan pemeriksaan %1$s`,
  _ = `Sengketamu telah diselesaikan`,
  _ = `Tidak ada tindakan yang diambil terkait %1$s`,
  _ = `Sengketamu telah diselesaikan`,
  _ = `Tindakan diambil terkait %1$s`,
  _ = `Kamu menlaporkan %1$s`,
  _ = `Staf moderasi Steam akan mengevaluasi konten dan mengambil tindakan yang sesuai dengan %1$s Steam. Kamu akan menerima pemberitahuan Steam saat laporan telah ditindaklanjuti.`,
  _ = `Pedoman & Aturan Komunitas`,
  _ = `Kami juga merekomendasikanmu untuk melihat informasi di %1$s.`,
  _ = `Kami telah menyelesaikan laporanmu`,
  _ = `Setelah dievaluasi oleh %1$s, kami menemukan bahwa konten tersebut tidak melanggar\xA0%2$s Steam.`,
  _ = `Kamu juga berhak untuk mencari penyelesaian melalui badan penyelesaian sengketa di luar pengadilan yang bersertifikasi, atau untuk mengajukan gugatan di hadapan pengadilan yang berwenang.`,
  _ = `Jika kamu tidak setuju dengan keputusan ini, kamu dapat mengajukan %1$s.`,
  _ = `sengketa`,
  _ = `Menangani penyalahgunaan, pelecehan, dan pelanggaran lainnya di Steam`,
  _ = `Ajukan sengketa`,
  _ = `Silakan berikan informasi apa pun yang menjelaskan mengapa kamu yakin bahwa keputusan Steam tentang konten ini salah.`,
  _ = `Kamu akan diberi tahu saat sengketa telah diselesaikan.`,
  _ = `Terjadi kesalahan. Silakan coba lagi nanti.`,
  _ = `Kami telah mengambil tindakan atas laporanmu`,
  _ = `Setelah dievaluasi oleh %1$s, kami menemukan bahwa konten tersebut melanggar\xA0%2$s Steam.`,
  _ = `Terima kasih telah membantu kami menjaga lingkungan yang aman di Steam.`,
  _ = `moderator`,
  _ = `sistem pemeriksa konten otomatis kami`,
  _ = `moderator dengan bantuan otomatis`,
  _ = `Kami telah menerima sengketamu`,
  _ = `Staf peninjau sengketa Steam akan mengevaluasi ulang konten tersebut.`,
  _ = `Kamu akan menerima pemberitahuan ketika peninjauan selesai.`,
  _ = `Kami telah menyelesaikan peninjauan kami`,
  _ = `Setelah dievaluasi oleh staf peninjau sengketa Steam, konten tersebut ditemukan tidak melanggar\xA0%1$s Steam.`,
  _ = `Jika kamu yakin ini adalah kesalahan, kamu berhak mencari penyelesaian melalui badan penyelesaian sengketa di luar pengadilan yang bersertifikasi atau mengajukan banding ke pengadilan yang berwenang.`,
  _ = `Kami telah menyelesaikan peninjauan kami`,
  _ = `Setelah dievaluasi oleh staf peninjau sengketa Steam, konten yang kamu laporkan ditemukan melanggar\xA0%1$s Steam.`,
  _ = `Terima kasih telah membantu kami menjaga lingkungan yang aman di Steam.`,
  _ = `Rincian laporan`,
  _ = `Kamu menulis:`,
  _ = `postingan forum`,
  _ = `%1$s terkait topik "%2$s" di Hub %3$s`,
  _ = `%2$s di Hub %1$s`,
  _ = `Laporkan Konten Ini`,
  _ = `Login ke Komunitas Steam untuk melaporkan konten yang tidak pantas atau ilegal.`,
  _ = `Jika kamu tidak dapat login, kamu dapat <1>mengajukan laporan anonim</1>.`,
  _ = `mengajukan laporan anonim`,
  _ = `Login`,
  _ = `Gabung ke Steam`,
  _ = `Buat Akun`,
  _ = `%1$s atau %2$s`,
  _ = `Memuat waktu jeda saat ini`,
  _ = `Gagal memuat waktu jeda saat ini!`,
  _ = `Waktu jeda pelaporan akan berakhir pada %1$s`,
  _ = `Tidak ada waktu jeda`,
  _ = `hari`,
  _ = `Waktu jeda baru untuk pengguna:`,
  _ = `Hapus waktu jeda`,
  _ = `(%1$s hari)`,
  _ = `Atur waktu jeda pelaporan`,
  _ = `Memblokir pengguna dari melaporkan konten atau menyengketakan moderasi saat mereka menyalahgunakan sistem.`,
  _ = `Atur waktu jeda`,
  _ = `Hapus laporan yang belum terselesaikan milik pengguna ini`,
  _ = `%1$s/%2$s laporan dibebaskan, %3$s/%4$s dalam seminggu terakhir.`,
  _ = ``,
  _ = {
    moderation_contentreports_title: _,
    moderation_submittedbyyou_title: _,
    moderation_onyourcontent_title: _,
    moderation_acquitted_description: _,
    moderation_maydispute_description: _,
    moderation_state_disputed: _,
    moderation_state_communicationblocked: _,
    moderation_sanctioned_for_reason: _,
    moderation_statementofreasons_header: _,
    moderation_statementofreasons_visibilityrestriction: _,
    moderation_statementofreasons_factsandcircumstances: _,
    moderation_statementofreasons_decisionground: _,
    moderation_statementofreasons_legalground: _,
    moderation_statementofreasons_contractualground: _,
    moderation_statementofreasons_explanationwhy: _,
    moderation_statementofreasons_contenttype: _,
    moderation_statementofreasons_informationsource: _,
    moderation_statementofreasons_automatedidentification: _,
    moderation_statementofreasons_automateddecision: _,
    moderation_statementofreasons_decisionground_legal: _,
    moderation_statementofreasons_explanation_legal: _,
    moderation_statementofreasons_decisionground_genericcontractual: _,
    moderation_statementofreasons_explanation_genericcontractual: _,
    moderation_statementofreasons_explanation_genericcontractual_steam_online_conduct_rules:
      _,
    moderation_statementofreasons_explanation_genericcontractual_steam_subscriber_agreement:
      _,
    moderation_statementofreasons_informationsource_report: _,
    moderation_none: _,
    moderation_automateddetection: `Ya`,
    moderation_fullyautomatedresolution: _,
    moderation_partiallyautomatedresolution: _,
    moderation_statementofreasons_visibilityrestriction_removed: _,
    moderation_statementofreasons_factsandcircumstances_text: _,
    moderation_outofcourtsettlement: _,
    moderation_yes: `Ya`,
    moderation_no: _,
    moderation_submit: _,
    moderation_cancel: _,
    moderation_dispute_title: _,
    moderation_dispute_description: _,
    moderation_detailsplaceholder: _,
    moderation_attestation: _,
    moderation_subjectreportedandresolved: _,
    moderation_subjectreporteddisputed: _,
    moderation_subjectdisputeresolved: _,
    moderation_reportedon: _,
    moderation_reportedandresolvedon: _,
    moderation_reportedanddisputed: _,
    moderation_reporteddisputeresolved: _,
    moderation_chatreport_desc: _,
    moderation_chatgroupmsgreport_desc: _,
    moderation_reportid: _,
    moderation_commentthread_desc: _,
    ReportContent_Title: _,
    ReportContent_Description: _,
    ReportContent_PickAReason: _,
    ReportContent_ReportButton: _,
    ReportContent_ReportAs: _,
    ReportContent_Back: _,
    ReportContent_Attestation: _,
    ReportContent_DetailsPlaceholder: _,
    ReportContent_CopyrightInfringement: _,
    ReportContent_TrademarkComplaint: _,
    ReportContent_YourNamePlaceholder: _,
    ContentReportReasonCategory_Abusive: _,
    ContentReportReasonCategory_Commercial: _,
    ContentReportReasonCategory_ConsumerInformation: _,
    ContentReportReasonCategory_CSAM: _,
    ContentReportReasonCategory_Disruptive: _,
    ContentReportReasonCategory_Harassment: _,
    ContentReportReasonCategory_Nonconsensual: _,
    ContentReportReasonCategory_NudityOrSexualContent: _,
    ContentReportReasonCategory_Offtopic: _,
    ContentReportReasonCategory_Privacy: _,
    ContentReportReasonCategory_ReviewManipulation: _,
    ContentReportReasonCategory_ScamsAndTheft: _,
    ContentReportReasonCategory_Terrorism: _,
    ContentReportReasonCategory_ViolenceAndSelfHarm: _,
    ContentReportReasonCategory_CivicDiscourse: _,
    ContentReportReasonCategory_Suspicious: _,
    ContentReportReasonCategory_Inappropriate: _,
    ContentReportReasonCategory_Other: _,
    ContentReportReasonCategoryDesc_Suspicious: _,
    ContentReportReasonCategoryDesc_Inappropriate: _,
    ContentReportReason_Invalid: _,
    ContentReportReason_None: _,
    ContentReportReason_Unknown: _,
    ContentReportReason_Harassment: _,
    ContentReportReason_BullyingAndIntimidation: _,
    ContentReportReason_Stalking: _,
    ContentReportReason_Doxxing: _,
    ContentReportReason_OtherHarassment: _,
    ContentReportReason_EncouragingViolence: _,
    ContentReportReason_EncouragingSelfHarm: _,
    ContentReportReason_EncouragingSuicide: _,
    ContentReportReason_OtherViolenceOrSelfHarm: _,
    ContentReportReason_CredibleThreatOfViolence: _,
    ContentReportReason_QuotesModeratedContent: _,
    ContentReportReason_PhishingOrAccountTheft: _,
    ContentReportReason_NegativeEffectonDiscourseOrElections: _,
    ContentReportReason_AttemptedScamming: _,
    ContentReportReason_LinkingToMaliciousContent: _,
    ContentReportReason_Impersonation: _,
    ContentReportReason_OtherScamsAndTheft: _,
    ContentReportReason_EncouragingTerrorism: _,
    ContentReportReason_OrganizingTerrorism: _,
    ContentReportReason_OtherTerrorism: _,
    ContentReportReason_TargetedAbuse: _,
    ContentReportReason_NamingAndShaming: _,
    ContentReportReason_Discrimination: _,
    ContentReportReason_OtherAbuse: _,
    ContentReportReason_Trolling: _,
    ContentReportReason_Baiting: _,
    ContentReportReason_Derailing: _,
    ContentReportReason_OtherDisruptive: _,
    ContentReportReason_Spam: _,
    ContentReportReason_Begging: _,
    ContentReportReason_Reposting: _,
    ContentReportReason_OtherOffTopic: _,
    ContentReportReason_CSAMSexualContent: _,
    ContentReportReason_CSAMGroomingOrEnticement: _,
    ContentReportReason_CSAMOther: _,
    ContentReportReason_NudityOrSexualContent: _,
    ContentReportReason_NonConsensualMaterial: _,
    ContentReportReason_Advertising: _,
    ContentReportReason_ReferralLinks: _,
    ContentReportReason_Gambling: _,
    ContentReportReason_Raffles: _,
    ContentReportReason_OtherCommercialActivity: _,
    ContentReportReason_InauthenticReview: _,
    ContentReportReason_HiddenAdvertisementOrCommercialCommunication: _,
    ContentReportReason_MisleadingInformationAboutGoodsOrServices: _,
    ContentReportReason_MisleadingInformationAboutConsumerRights: _,
    ContentReportReason_NoncomplianceWithPricingRegulations: _,
    ContentReportReason_RightToBeForgottenViolation: _,
    ContentReportReason_MissingProcessingGroundForData: _,
    ContentReportReason_OtherDataProtectionAndPrivacyViolation: _,
    ContentReportReason_GenderedHarassment: _,
    ContentReportReason_GenderedBullyingAndIntimidation: _,
    ContentReportReason_GenderedStalking: _,
    ContentReportReason_GenderedDoxxing: _,
    ContentReportReason_GenderedOtherHarassment: _,
    ContentReportReason_GenderedEncouragingViolence: _,
    ContentReportReason_GenderedTargetedAbuse: _,
    ContentReportReason_CSAMFakedSexualContent: _,
    ContentReportReason_GenderedNonConsensualMaterial: _,
    ContentReportReason_FakedGenderedNonConsensualMaterial: _,
    ContentReportReason_FakedNonConsensualMaterial: _,
    ContentReportReason_Gendered: _,
    ContentReportReason_Deepfake: _,
    ContentReportReason_Piracy: _,
    ContentReportReason_ToSViolation: _,
    ContentReportReason_Miscategorized: _,
    ContentReportReason_BypassingProfanityFilter: _,
    ContentReportSubmitted_Title: _,
    ContentReportSubmitted_Description: _,
    ContentReportSubmitted_Chat_Description: _,
    ContentReportSubmissionError_Title: _,
    ContentReportSubmissionError_Description: _,
    ContentReportSubmissionOnCooldown_Description: _,
    ContentReport_FriendOptions_CallToAction: _,
    ContentReport_FriendOptions_BlockedDesc: _,
    ContentReport_FriendOptions_Unblock: _,
    ContentReport_FriendOptions_Remove: _,
    ContentReport_FriendOptions_RemoveDesc: _,
    ContentReport_FriendOptions_RemoveSuccess: _,
    ContentReport_LearnMore_Misconduct: _,
    moderation_subjecttype_forumpost: _,
    moderation_subjecttype_commentthread: _,
    moderation_subjecttype_friendchatmsg: _,
    moderation_subjecttype_chatroommsg: _,
    moderation_subjecttype_chatgroup: _,
    moderation_subjettype_ugcfile: _,
    moderation_subjecttype_unknown: _,
    moderation_resolvewithnoaction: _,
    moderation_resolutionstatus_pending: _,
    moderation_resolutionstatus_acquitted: _,
    moderation_resolutionstatus_purged: _,
    moderation_resolutionstatus_removed: _,
    moderation_resolutionstatus_relabelled: _,
    moderation_resolutionstatus_suspicious: _,
    moderation_resolutionstatus_harassmentstrike: _,
    moderation_resolutionstatus_removeandwarn: _,
    moderation_resolutionstatus_removeandban: _,
    moderation_resolutionstatus_removeandkick: _,
    moderation_resolutionstatus_sanctioned: _,
    moderation_resolutionstatus_unknown: _,
    moderationaction_acquitted: _,
    moderationaction_cancelled: _,
    moderationaction_disputed: _,
    moderationaction_escalated: _,
    moderationaction_sanctioned: _,
    moderationaction_sustained: _,
    moderationaction_unresolved: _,
    moderationaction_updated: _,
    moderationaction_locked: _,
    moderationaction_unlocked: _,
    moderationaction_deleted: _,
    moderationaction_warned: _,
    moderationaction_banned_from_hub: _,
    moderationaction_banned_from_community: _,
    moderationaction_trade_banned: _,
    moderationaction_marked_as_suspicious: _,
    moderationaction_reset_content: _,
    moderationaction_escalated_for_csam: _,
    moderationaction_escalated_for_terrorism: _,
    moderationaction_claimed: _,
    moderationaction_released: _,
    moderationaction_privatemessaged: _,
    moderationaction_unknown: _,
    moderationaction_ownerdisputed: _,
    moderatormessage_count_note: _,
    moderatormessage_count_warning: _,
    moderatormessage_count_bannotice: _,
    moderatormessage_count_contentremoval: _,
    reportforumpost_reason_scams: _,
    reportforumpost_description_scams: _,
    reportforumpost_reason_privacy: _,
    reportforumpost_description_privacy: _,
    reportforumpost_reason_childsafety: _,
    reportforumpost_description_childsafety: _,
    reportforumpost_reason_promotingviolence: _,
    reportforumpost_description_promotingviolence: _,
    reportforumpost_reason_disruptive: _,
    reportforumpost_description_disruptive: _,
    reportforumpost_reason_sensitiveordisturbing: _,
    reportforumpost_description_sensitiveordisturbing: _,
    reportforumpost_reason_advertising: _,
    reportforumpost_description_advertising: _,
    reportforumpost_reason_cheating: _,
    reportforumpost_description_cheating: _,
    reportforumpost_reason_notfound: _,
    reportforumpost_description_notfound: _,
    reportforumpost_reason_intellectualproperty: _,
    reportforumpost_description_intellectualproperty: _,
    reportforumpost_reasonforreport: _,
    WarnBeforeNavigatingToCopyrightReportForm: _,
    WarnBeforeNavigatingToTrademarkReportForm: _,
    reportedcontentlist_unresolved_title: _,
    reportedcontentlist_unresolved_body: _,
    reportedcontentlist_acquitted_title: _,
    reportedcontentlist_acquitted_body: _,
    reportedcontentlist_sanctioned_title: _,
    reportedcontentlist_sanctioned_body: _,
    reportedcontentlist_disputed_title: _,
    reportedcontentlist_disputed_body: _,
    reportedcontentlist_disputedenied_title: _,
    reportedcontentlist_disputedenied_body: _,
    reportedcontentlist_disputesanctioned_title: _,
    reportedcontentlist_disputesanctioned_body: _,
    reportedcontent_unresolved_1: _,
    reportedcontent_unresolved_2: _,
    reportedcontent_community_guidelines: _,
    reportedcontent_unresolved_3: _,
    reportedcontent_acquitted_1: _,
    reportedcontent_acquitted_2: _,
    reportedcontent_acquitted_2_eu_addendum: _,
    reportedcontent_dispute_submit_dispute: _,
    reportedcontent_dispute_acquittal: _,
    reportedcontent_harassment_guidance: _,
    reportedcontent_submit_dispute_title: _,
    reportedcontent_submit_dispute_description: _,
    reportedcontent_dispute_acknowledged: _,
    reportedcontent_error: _,
    reportedcontent_sanctioned_1: _,
    reportedcontent_sanctioned_2: _,
    reportedcontent_sanctioned_3: _,
    reportedcontent_moderatedby_human: _,
    reportedcontent_moderatedby_machine: _,
    reportedcontent_moderatedby_assistedhuman: _,
    reportedcontent_disputed_1: _,
    reportedcontent_disputed_2: _,
    reportedcontent_disputed_3: _,
    reportedcontent_disputedenied_1: _,
    reportedcontent_disputedenied_2: _,
    reportedcontent_disputedenied_eu_addendum: _,
    reportedcontent_disputesanctioned_1: _,
    reportedcontent_disputesanctioned_2: _,
    reportedcontent_disputesanctioned_3: _,
    reportedcontent_content_report_breadcrumb: _,
    reportedcontent_you_wrote: _,
    reportedcontent_summary_forumpost: _,
    reportedcontent_summary_forumpost_on: _,
    reportedcontent_summary_forumtopic_in: _,
    anonymousreport_title: _,
    anonymousreport_description: _,
    anonymousreport_footer: _,
    anonymousreport_footer_action: _,
    anonymousreport_signin: _,
    anonymousreport_join: _,
    anonymousreport_createaccount: _,
    anonymousreport_signin_or_join: _,
    setcooldown_loading: _,
    setcooldown_errorloading: _,
    setcooldown_expireson: _,
    setcooldown_nocooldown: _,
    setcooldown_days: _,
    setcooldown_newcooldownlabel: _,
    setcooldown_clearcooldown: _,
    setcooldown_cooldownsummary: _,
    setcooldown_dialogtitle: _,
    setcooldown_dialogdescription: _,
    setcooldown_setbutton: _,
    setcooldown_clearopenreports: _,
    setcooldown_statssummary: _,
    nocomma: ``,
  };
export {
  _ as ContentReportReasonCategoryDesc_Inappropriate,
  _ as ContentReportReasonCategoryDesc_Suspicious,
  _ as ContentReportReasonCategory_Abusive,
  _ as ContentReportReasonCategory_CSAM,
  _ as ContentReportReasonCategory_CivicDiscourse,
  _ as ContentReportReasonCategory_Commercial,
  _ as ContentReportReasonCategory_ConsumerInformation,
  _ as ContentReportReasonCategory_Disruptive,
  _ as ContentReportReasonCategory_Harassment,
  _ as ContentReportReasonCategory_Inappropriate,
  _ as ContentReportReasonCategory_Nonconsensual,
  _ as ContentReportReasonCategory_NudityOrSexualContent,
  _ as ContentReportReasonCategory_Offtopic,
  _ as ContentReportReasonCategory_Other,
  _ as ContentReportReasonCategory_Privacy,
  _ as ContentReportReasonCategory_ReviewManipulation,
  _ as ContentReportReasonCategory_ScamsAndTheft,
  _ as ContentReportReasonCategory_Suspicious,
  _ as ContentReportReasonCategory_Terrorism,
  _ as ContentReportReasonCategory_ViolenceAndSelfHarm,
  _ as ContentReportReason_Advertising,
  _ as ContentReportReason_AttemptedScamming,
  _ as ContentReportReason_Baiting,
  _ as ContentReportReason_Begging,
  _ as ContentReportReason_BullyingAndIntimidation,
  _ as ContentReportReason_BypassingProfanityFilter,
  _ as ContentReportReason_CSAMFakedSexualContent,
  _ as ContentReportReason_CSAMGroomingOrEnticement,
  _ as ContentReportReason_CSAMOther,
  _ as ContentReportReason_CSAMSexualContent,
  _ as ContentReportReason_CredibleThreatOfViolence,
  _ as ContentReportReason_Deepfake,
  _ as ContentReportReason_Derailing,
  _ as ContentReportReason_Discrimination,
  _ as ContentReportReason_Doxxing,
  _ as ContentReportReason_EncouragingSelfHarm,
  _ as ContentReportReason_EncouragingSuicide,
  _ as ContentReportReason_EncouragingTerrorism,
  _ as ContentReportReason_EncouragingViolence,
  _ as ContentReportReason_FakedGenderedNonConsensualMaterial,
  _ as ContentReportReason_FakedNonConsensualMaterial,
  _ as ContentReportReason_Gambling,
  _ as ContentReportReason_Gendered,
  _ as ContentReportReason_GenderedBullyingAndIntimidation,
  _ as ContentReportReason_GenderedDoxxing,
  _ as ContentReportReason_GenderedEncouragingViolence,
  _ as ContentReportReason_GenderedHarassment,
  _ as ContentReportReason_GenderedNonConsensualMaterial,
  _ as ContentReportReason_GenderedOtherHarassment,
  _ as ContentReportReason_GenderedStalking,
  _ as ContentReportReason_GenderedTargetedAbuse,
  _ as ContentReportReason_Harassment,
  _ as ContentReportReason_HiddenAdvertisementOrCommercialCommunication,
  _ as ContentReportReason_Impersonation,
  _ as ContentReportReason_InauthenticReview,
  _ as ContentReportReason_Invalid,
  _ as ContentReportReason_LinkingToMaliciousContent,
  _ as ContentReportReason_Miscategorized,
  _ as ContentReportReason_MisleadingInformationAboutConsumerRights,
  _ as ContentReportReason_MisleadingInformationAboutGoodsOrServices,
  _ as ContentReportReason_MissingProcessingGroundForData,
  _ as ContentReportReason_NamingAndShaming,
  _ as ContentReportReason_NegativeEffectonDiscourseOrElections,
  _ as ContentReportReason_NonConsensualMaterial,
  _ as ContentReportReason_NoncomplianceWithPricingRegulations,
  _ as ContentReportReason_None,
  _ as ContentReportReason_NudityOrSexualContent,
  _ as ContentReportReason_OrganizingTerrorism,
  _ as ContentReportReason_OtherAbuse,
  _ as ContentReportReason_OtherCommercialActivity,
  _ as ContentReportReason_OtherDataProtectionAndPrivacyViolation,
  _ as ContentReportReason_OtherDisruptive,
  _ as ContentReportReason_OtherHarassment,
  _ as ContentReportReason_OtherOffTopic,
  _ as ContentReportReason_OtherScamsAndTheft,
  _ as ContentReportReason_OtherTerrorism,
  _ as ContentReportReason_OtherViolenceOrSelfHarm,
  _ as ContentReportReason_PhishingOrAccountTheft,
  _ as ContentReportReason_Piracy,
  _ as ContentReportReason_QuotesModeratedContent,
  _ as ContentReportReason_Raffles,
  _ as ContentReportReason_ReferralLinks,
  _ as ContentReportReason_Reposting,
  _ as ContentReportReason_RightToBeForgottenViolation,
  _ as ContentReportReason_Spam,
  _ as ContentReportReason_Stalking,
  _ as ContentReportReason_TargetedAbuse,
  _ as ContentReportReason_ToSViolation,
  _ as ContentReportReason_Trolling,
  _ as ContentReportReason_Unknown,
  _ as ContentReportSubmissionError_Description,
  _ as ContentReportSubmissionError_Title,
  _ as ContentReportSubmissionOnCooldown_Description,
  _ as ContentReportSubmitted_Chat_Description,
  _ as ContentReportSubmitted_Description,
  _ as ContentReportSubmitted_Title,
  _ as ContentReport_FriendOptions_BlockedDesc,
  _ as ContentReport_FriendOptions_CallToAction,
  _ as ContentReport_FriendOptions_Remove,
  _ as ContentReport_FriendOptions_RemoveDesc,
  _ as ContentReport_FriendOptions_RemoveSuccess,
  _ as ContentReport_FriendOptions_Unblock,
  _ as ContentReport_LearnMore_Misconduct,
  _ as ReportContent_Attestation,
  _ as ReportContent_Back,
  _ as ReportContent_CopyrightInfringement,
  _ as ReportContent_Description,
  _ as ReportContent_DetailsPlaceholder,
  _ as ReportContent_PickAReason,
  _ as ReportContent_ReportAs,
  _ as ReportContent_ReportButton,
  _ as ReportContent_Title,
  _ as ReportContent_TrademarkComplaint,
  _ as ReportContent_YourNamePlaceholder,
  _ as WarnBeforeNavigatingToCopyrightReportForm,
  _ as WarnBeforeNavigatingToTrademarkReportForm,
  _ as anonymousreport_createaccount,
  _ as anonymousreport_description,
  _ as anonymousreport_footer,
  _ as anonymousreport_footer_action,
  _ as anonymousreport_join,
  _ as anonymousreport_signin,
  _ as anonymousreport_signin_or_join,
  _ as anonymousreport_title,
  _ as default,
  _ as moderation_acquitted_description,
  _ as moderation_attestation,
  _ as moderation_automateddetection,
  _ as moderation_cancel,
  _ as moderation_chatgroupmsgreport_desc,
  _ as moderation_chatreport_desc,
  _ as moderation_commentthread_desc,
  _ as moderation_contentreports_title,
  _ as moderation_detailsplaceholder,
  _ as moderation_dispute_description,
  _ as moderation_dispute_title,
  _ as moderation_fullyautomatedresolution,
  _ as moderation_maydispute_description,
  _ as moderation_no,
  _ as moderation_none,
  _ as moderation_onyourcontent_title,
  _ as moderation_outofcourtsettlement,
  _ as moderation_partiallyautomatedresolution,
  _ as moderation_reportedanddisputed,
  _ as moderation_reportedandresolvedon,
  _ as moderation_reporteddisputeresolved,
  _ as moderation_reportedon,
  _ as moderation_reportid,
  _ as moderation_resolutionstatus_acquitted,
  _ as moderation_resolutionstatus_harassmentstrike,
  _ as moderation_resolutionstatus_pending,
  _ as moderation_resolutionstatus_purged,
  _ as moderation_resolutionstatus_relabelled,
  _ as moderation_resolutionstatus_removeandban,
  _ as moderation_resolutionstatus_removeandkick,
  _ as moderation_resolutionstatus_removeandwarn,
  _ as moderation_resolutionstatus_removed,
  _ as moderation_resolutionstatus_sanctioned,
  _ as moderation_resolutionstatus_suspicious,
  _ as moderation_resolutionstatus_unknown,
  _ as moderation_resolvewithnoaction,
  _ as moderation_sanctioned_for_reason,
  _ as moderation_state_communicationblocked,
  _ as moderation_state_disputed,
  _ as moderation_statementofreasons_automateddecision,
  _ as moderation_statementofreasons_automatedidentification,
  _ as moderation_statementofreasons_contenttype,
  _ as moderation_statementofreasons_contractualground,
  _ as moderation_statementofreasons_decisionground,
  _ as moderation_statementofreasons_decisionground_genericcontractual,
  _ as moderation_statementofreasons_decisionground_legal,
  _ as moderation_statementofreasons_explanation_genericcontractual,
  _ as moderation_statementofreasons_explanation_genericcontractual_steam_online_conduct_rules,
  _ as moderation_statementofreasons_explanation_genericcontractual_steam_subscriber_agreement,
  _ as moderation_statementofreasons_explanation_legal,
  _ as moderation_statementofreasons_explanationwhy,
  _ as moderation_statementofreasons_factsandcircumstances,
  _ as moderation_statementofreasons_factsandcircumstances_text,
  _ as moderation_statementofreasons_header,
  _ as moderation_statementofreasons_informationsource,
  _ as moderation_statementofreasons_informationsource_report,
  _ as moderation_statementofreasons_legalground,
  _ as moderation_statementofreasons_visibilityrestriction,
  _ as moderation_statementofreasons_visibilityrestriction_removed,
  _ as moderation_subjectdisputeresolved,
  _ as moderation_subjectreportedandresolved,
  _ as moderation_subjectreporteddisputed,
  _ as moderation_subjecttype_chatgroup,
  _ as moderation_subjecttype_chatroommsg,
  _ as moderation_subjecttype_commentthread,
  _ as moderation_subjecttype_forumpost,
  _ as moderation_subjecttype_friendchatmsg,
  _ as moderation_subjecttype_unknown,
  _ as moderation_subjettype_ugcfile,
  _ as moderation_submit,
  _ as moderation_submittedbyyou_title,
  _ as moderation_yes,
  _ as moderationaction_acquitted,
  _ as moderationaction_banned_from_community,
  _ as moderationaction_banned_from_hub,
  _ as moderationaction_cancelled,
  _ as moderationaction_claimed,
  _ as moderationaction_deleted,
  _ as moderationaction_disputed,
  _ as moderationaction_escalated,
  _ as moderationaction_escalated_for_csam,
  _ as moderationaction_escalated_for_terrorism,
  _ as moderationaction_locked,
  _ as moderationaction_marked_as_suspicious,
  _ as moderationaction_ownerdisputed,
  _ as moderationaction_privatemessaged,
  _ as moderationaction_released,
  _ as moderationaction_reset_content,
  _ as moderationaction_sanctioned,
  _ as moderationaction_sustained,
  _ as moderationaction_trade_banned,
  _ as moderationaction_unknown,
  _ as moderationaction_unlocked,
  _ as moderationaction_unresolved,
  _ as moderationaction_updated,
  _ as moderationaction_warned,
  _ as moderatormessage_count_bannotice,
  _ as moderatormessage_count_contentremoval,
  _ as moderatormessage_count_note,
  _ as moderatormessage_count_warning,
  _ as nocomma,
  _ as reportedcontent_acquitted_1,
  _ as reportedcontent_acquitted_2,
  _ as reportedcontent_acquitted_2_eu_addendum,
  _ as reportedcontent_community_guidelines,
  _ as reportedcontent_content_report_breadcrumb,
  _ as reportedcontent_dispute_acknowledged,
  _ as reportedcontent_dispute_acquittal,
  _ as reportedcontent_dispute_submit_dispute,
  _ as reportedcontent_disputed_1,
  _ as reportedcontent_disputed_2,
  _ as reportedcontent_disputed_3,
  _ as reportedcontent_disputedenied_1,
  _ as reportedcontent_disputedenied_2,
  _ as reportedcontent_disputedenied_eu_addendum,
  _ as reportedcontent_disputesanctioned_1,
  _ as reportedcontent_disputesanctioned_2,
  _ as reportedcontent_disputesanctioned_3,
  _ as reportedcontent_error,
  _ as reportedcontent_harassment_guidance,
  _ as reportedcontent_moderatedby_assistedhuman,
  _ as reportedcontent_moderatedby_human,
  _ as reportedcontent_moderatedby_machine,
  _ as reportedcontent_sanctioned_1,
  _ as reportedcontent_sanctioned_2,
  _ as reportedcontent_sanctioned_3,
  _ as reportedcontent_submit_dispute_description,
  _ as reportedcontent_submit_dispute_title,
  _ as reportedcontent_summary_forumpost,
  _ as reportedcontent_summary_forumpost_on,
  _ as reportedcontent_summary_forumtopic_in,
  _ as reportedcontent_unresolved_1,
  _ as reportedcontent_unresolved_2,
  _ as reportedcontent_unresolved_3,
  _ as reportedcontent_you_wrote,
  _ as reportedcontentlist_acquitted_body,
  _ as reportedcontentlist_acquitted_title,
  _ as reportedcontentlist_disputed_body,
  _ as reportedcontentlist_disputed_title,
  _ as reportedcontentlist_disputedenied_body,
  _ as reportedcontentlist_disputedenied_title,
  _ as reportedcontentlist_disputesanctioned_body,
  _ as reportedcontentlist_disputesanctioned_title,
  _ as reportedcontentlist_sanctioned_body,
  _ as reportedcontentlist_sanctioned_title,
  _ as reportedcontentlist_unresolved_body,
  _ as reportedcontentlist_unresolved_title,
  _ as reportforumpost_description_advertising,
  _ as reportforumpost_description_cheating,
  _ as reportforumpost_description_childsafety,
  _ as reportforumpost_description_disruptive,
  _ as reportforumpost_description_intellectualproperty,
  _ as reportforumpost_description_notfound,
  _ as reportforumpost_description_privacy,
  _ as reportforumpost_description_promotingviolence,
  _ as reportforumpost_description_scams,
  _ as reportforumpost_description_sensitiveordisturbing,
  _ as reportforumpost_reason_advertising,
  _ as reportforumpost_reason_cheating,
  _ as reportforumpost_reason_childsafety,
  _ as reportforumpost_reason_disruptive,
  _ as reportforumpost_reason_intellectualproperty,
  _ as reportforumpost_reason_notfound,
  _ as reportforumpost_reason_privacy,
  _ as reportforumpost_reason_promotingviolence,
  _ as reportforumpost_reason_scams,
  _ as reportforumpost_reason_sensitiveordisturbing,
  _ as reportforumpost_reasonforreport,
  _ as setcooldown_clearcooldown,
  _ as setcooldown_clearopenreports,
  _ as setcooldown_cooldownsummary,
  _ as setcooldown_days,
  _ as setcooldown_dialogdescription,
  _ as setcooldown_dialogtitle,
  _ as setcooldown_errorloading,
  _ as setcooldown_expireson,
  _ as setcooldown_loading,
  _ as setcooldown_newcooldownlabel,
  _ as setcooldown_nocooldown,
  _ as setcooldown_setbutton,
  _ as setcooldown_statssummary,
};
