var _ = `Fórumbejegyzések`,
  _ = `Általános témák`,
  _ = `Jelentett hozzászólások`,
  _ = `Műhely-témák`,
  _ = `Csere`,
  _ = `Események és bejelentések`,
  _ = `1 jelentés`,
  _ = `%1$s jelentés`,
  _ = `1 eset`,
  _ = `%1$s eset`,
  _ = `%1$s %2$s darabról`,
  _ = `%1$s %2$sről a(z) %3$s témában`,
  _ = `1 jelentés`,
  _ = `%1$s jelentés`,
  _ = `1 eset`,
  _ = `%1$s eset`,
  _ = `Steam Közösség`,
  _ = `Steam Közösség :: Hiba`,
  _ = `Hiba`,
  _ = `Ismeretlen hiba`,
  _ = `Játékok`,
  _ = `Steam Közösség :: %1$s :: Játékok`,
  _ = `Keresés – Steam Közösségi Piac`,
  _ = `%1$s – Steam Közösségi Piac`,
  _ = `Piaci tétel – Steam Közösségi Piac`,
  _ = `Steam Közösségi Piac`,
  _ = `A profil nem található.`,
  _ = `Nem sikerült a felhasználó kívánságlistájának betöltése.`,
  _ = `Túl sok kérést küldtél mostanában. Kérjük várj, és próbálkozz a kéréseddel újra később.`,
  _ = `Betöltés`,
  _ = `%1$s% KÉSZ`,
  _ = `SZÜNETELTETVE – %1$s% KÉSZ`,
  _ = `%1$s / %2$s LETÖLTVE`,
  _ = `TELJESÍTMÉNYEK`,
  _ = `Körülbelül %1$s van hátra`,
  _ = `%1$s/%2$s`,
  _ = `ELTÁVOLÍTÁS ALATT`,
  _ = `FRISSÍTÉS`,
  _ = `ELTÁVOLÍTÁS`,
  _ = `LETÖLTÉS`,
  _ = `SZÜNET`,
  _ = `FOLYTATÁS`,
  _ = `ELTÁVOLÍTÁS ALATT`,
  _ = `MÉGSE`,
  _ = `Adatvédelmi beállításaim megnézése e tartalomhoz.`,
  _ = `Játék keresése`,
  _ = `Szűrés mindkettőtök birtokolta játékokra`,
  _ = `Játékidő`,
  _ = `Név`,
  _ = `Teljesítményállapot`,
  _ = `ÖSSZESEN JÁTSZVA`,
  _ = `LEGUTÓBB JÁTSZVA`,
  _ = `ELMÚLT KÉT HÉT`,
  _ = `Játékinfó és hivatkozások`,
  _ = `Távoli letöltés`,
  _ = `TÁVOLI LETÖLTÉS IDE: %1$s`,
  _ = `TÁVOLI LETÖLTÉS ÁLLAPOTA: %1$s`,
  _ = `Nem sikerült elérni a PC-det`,
  _ = `Ahhoz, hogy távolról játékokat tölthess le a Steam kliensedre, a számítógépednek ébren kell lennie, internetkapcsolattal kell rendelkeznie, és bejelentkezve kell lenned.`,
  _ = `Olvasd el a GYIK-et.`,
  _ = `%1$s %2$s`,
  _ = `További információ`,
  _ = `A TÁVOLI LETÖLTÉS NEM ÉRHETŐ EL`,
  _ = `El szeretnéd távolítani a(z) %1$s terméket? A játékkönyvtáradban marad, de hogy játszani tudj vele a jövőben, először újra le kell majd töltened az összes tartalmát.`,
  _ = `%1$s | „%2$s”`,
  _ = `Nemrég játszott %1$s`,
  _ = `Összes játék %1$s`,
  _ = `Tökéletes játékok %1$s`,
  _ = `Értékelések %1$s`,
  _ = `Követve %1$s`,
  _ = `Kívánságlista`,
  _ = `Összes lehetséges teljesítmény elérve.`,
  _ = `Itt találod a tökéletes játékaidat, vagyis azokat a játékokat, amelyeknél az összes lehetséges teljesítményt megszerezted.`,
  _ = `A játékosok %1$s%-ának van meg ez a teljesítmény.`,
  _ = `Áruházi oldal`,
  _ = `Fórumok`,
  _ = `Csoportok`,
  _ = `Hivatalos weboldal`,
  _ = `Hírek`,
  _ = `Teljesítményeim`,
  _ = `%1$s teljesítményei`,
  _ = `%1$s statisztikái`,
  _ = `%1$s személyes játékadatai`,
  _ = `Ranglistáim`,
  _ = `%1$s ranglistái`,
  _ = `Globális teljesítmények`,
  _ = `Globális ranglisták`,
  _ = `Játékstatisztikák`,
  _ = `Játéktartalom`,
  _ = `Játékstatisztikáim`,
  _ = `Játéktartalmaim`,
  _ = `Játékhivatkozások`,
  _ = `Képernyőmentéseim %1$s`,
  _ = `%1$s képernyőmentései %2$s`,
  _ = `Ezzel játszó barátaim %1$s`,
  _ = `Játékkártyáim %1$s`,
  _ = `Értékelésem`,
  _ = `%1$s értékelése`,
  _ = `Közösségközpont`,
  _ = `Jegyzeteim`,
  _ = `%1$s óra`,
  _ = `%1$s perc`,
  _ = `Megjelölés privátként`,
  _ = `Privát megjelölés eltávolítása`,
  _ = `E játék megjelölése privátként és elrejtése a barátaim elől.`,
  _ = `&copy; Valve Corporation. Minden jog fenntartva. A védjegyek jogos tulajdonosaiké az Egyesült Államokban és más országokban.`,
  _ = `Az oldal egyes térinformatikai adatait a(z) %1$s szolgáltatja.`,
  _ = `Adatvédelmi szabályzat`,
  _ = `Jogi információk`,
  _ = `Steam előfizetői szerződés`,
  _ = `Visszatérítések`,
  _ = `Sütik`,
  _ = `Kisegítő lehetőségek`,
  _ = `Jelenlegi kitiltások`,
  _ = `Közösségi üzenetek`,
  _ = `Jelentett tartalom`,
  _ = `Moderált tartalom`,
  _ = `Ezek azok a dolgok a Steamen, amelyeket jelentettél a Steam irányelveinek megsértése miatt.`,
  _ = `Ez egy lista a Steamen általad közzétett tartalmakról, amelyek moderálásra kerültek.`,
  _ = `Legutóbb frissítve: %1$s`,
  _ = ``,
  _ = {
    Moderation_SubjectTypeName_ForumPost: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    moderation_claim_report_count: _,
    moderation_claim_report_count_Plural: _,
    moderation_claim_subject_count: _,
    moderation_claim_subject_count_Plural: _,
    moderation_claim_n_reports_on_m_subjects: _,
    moderation_forumpost_summary: _,
    moderation_forumpost_summary_reports_fragment: _,
    moderation_forumpost_summary_reports_fragment_Plural: _,
    moderation_forumpost_summary_subjects_fragment: _,
    moderation_forumpost_summary_subjects_fragment_Plural: _,
    community_title: _,
    community_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    profile_games_list: _,
    profile_games_list_title: _,
    Market_Search_Title: _,
    Market_Item_Title: _,
    Market_Item_GenericTitle: _,
    Market_GenericTitle: _,
    profile_error_profilenotfound: _,
    profile_games_list_error_loadfailed: _,
    Error_RateLimited: _,
    Loading: _,
    GamesList_Header_Downloading: _,
    GamesList_Header_Paused: _,
    GamesList_Header_DownloadBytes: _,
    GamesList_Header_Achievements: _,
    GamesList_TimeRemaining: _,
    GamesList_Achievement_Fraction: _,
    GamesList_Uninstalling: _,
    GamesList_Button_UpdateRequired: _,
    GamesList_Button_Uninstall: _,
    GamesList_Button_Download: _,
    GamesList_Button_Pause: _,
    GamesList_Button_Resume: _,
    GamesList_Button_Uninstalling: _,
    GamesList_Button_Cancel: _,
    GamesList_PrivacySettings_Tooltip: _,
    GamesList_Filter_Placeholder: _,
    GamesList_Filter_BothOwned: _,
    GamesList_Sort_HoursPlayed: _,
    GamesList_Sort_Name: _,
    GamesList_Sort_AchievementCompletion: _,
    GamesList_Header_TotalPlayed: _,
    GamesList_Header_LastPlayed: _,
    GamesList_Header_TwoWeeks: _,
    GamesList_MenuLabel_GameInfo: _,
    GamesList_MenuLabel_RemoteDownload: _,
    GamesList_Header_RemoteDownload: _,
    GamesList_Header_RemoteDownloadStatus: _,
    GamesList_RemoteDownload_NoConnection: _,
    GamesList_RemoteDownload_Help: _,
    GamesList_RemoteDownload_ReadTheFAQ: _,
    GamesList_RemoteDownload_Info: _,
    GamesList_RemoteDownload_LearnMore: _,
    GamesList_RemoteDownload_NoRemoteControl: _,
    GamesList_RemoteDownload_UninstallConfirm: _,
    GamesList_Client_Indicator: _,
    GamesList_Tab_RecentlyPlayed: _,
    GamesList_Tab_AllGames: _,
    GamesList_Tab_PerfectGames: _,
    GamesList_Tab_Reviews: _,
    GamesList_Tab_Followed: _,
    GamesList_Tab_Wishlist: _,
    Perfect_Game_Description: _,
    GamesList_PerfectGames_Description: _,
    GamesList_Achievement_Unlock_Percentage: _,
    Community_StorePage: _,
    Community_Forums: _,
    Community_Groups: _,
    Community_OfficialWebsite: _,
    Community_News: _,
    Community_UsersAchievementsFirstPerson: _,
    Community_UsersAchievements: _,
    Community_UsersStats: _,
    Community_GamePersonalData: _,
    Community_UsersLeaderboardsFirstPerson: _,
    Community_UsersLeaderboards: _,
    Community_GlobalAchievements: _,
    Community_GlobalLeaderboards: _,
    Community_GameStats: _,
    Community_GameContent: _,
    Community_GameStatsFirstPerson: _,
    Community_GameContentFirstPerson: _,
    Community_GameLinks: _,
    Community_ScreenshotsMenuItemFirstPerson: _,
    Community_ScreenshotsMenuItemThirdPerson: _,
    Community_FriendsWhoPlayMenuItemFirstPerson: _,
    Community_TradingCardsMenuItemFirstPerson: _,
    Community_ReviewMenuItemFirstPerson: _,
    Community_ReviewMenuItemThirdPerson: _,
    Community_GameHubMenuItem: _,
    Community_GameNotesFirstPerson: _,
    Playtime_Hours: _,
    Playtime_Minutes: _,
    AppPrivacy_MarkAsPrivate: _,
    AppPrivacy_UnmarkAsPrivate: _,
    AppPrivacy_Explanation: _,
    footer_legal_notice: _,
    footer_geodata_notice: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_accessibility: _,
    profiletabs_currentbans: _,
    profiletabs_communitymessages: _,
    profiletabs_reportedcontent: _,
    profiletabs_moderatedcontent: _,
    reportedcontent_description: _,
    moderatedcontent_description: _,
    reportedcontent_lastupdated: _,
    empty_no_comma_following: ``,
  };
export {
  _ as AppPrivacy_Explanation,
  _ as AppPrivacy_MarkAsPrivate,
  _ as AppPrivacy_UnmarkAsPrivate,
  _ as Community_Forums,
  _ as Community_FriendsWhoPlayMenuItemFirstPerson,
  _ as Community_GameContent,
  _ as Community_GameContentFirstPerson,
  _ as Community_GameHubMenuItem,
  _ as Community_GameLinks,
  _ as Community_GameNotesFirstPerson,
  _ as Community_GamePersonalData,
  _ as Community_GameStats,
  _ as Community_GameStatsFirstPerson,
  _ as Community_GlobalAchievements,
  _ as Community_GlobalLeaderboards,
  _ as Community_Groups,
  _ as Community_News,
  _ as Community_OfficialWebsite,
  _ as Community_ReviewMenuItemFirstPerson,
  _ as Community_ReviewMenuItemThirdPerson,
  _ as Community_ScreenshotsMenuItemFirstPerson,
  _ as Community_ScreenshotsMenuItemThirdPerson,
  _ as Community_StorePage,
  _ as Community_TradingCardsMenuItemFirstPerson,
  _ as Community_UsersAchievements,
  _ as Community_UsersAchievementsFirstPerson,
  _ as Community_UsersLeaderboards,
  _ as Community_UsersLeaderboardsFirstPerson,
  _ as Community_UsersStats,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as GamesList_Achievement_Fraction,
  _ as GamesList_Achievement_Unlock_Percentage,
  _ as GamesList_Button_Cancel,
  _ as GamesList_Button_Download,
  _ as GamesList_Button_Pause,
  _ as GamesList_Button_Resume,
  _ as GamesList_Button_Uninstall,
  _ as GamesList_Button_Uninstalling,
  _ as GamesList_Button_UpdateRequired,
  _ as GamesList_Client_Indicator,
  _ as GamesList_Filter_BothOwned,
  _ as GamesList_Filter_Placeholder,
  _ as GamesList_Header_Achievements,
  _ as GamesList_Header_DownloadBytes,
  _ as GamesList_Header_Downloading,
  _ as GamesList_Header_LastPlayed,
  _ as GamesList_Header_Paused,
  _ as GamesList_Header_RemoteDownload,
  _ as GamesList_Header_RemoteDownloadStatus,
  _ as GamesList_Header_TotalPlayed,
  _ as GamesList_Header_TwoWeeks,
  _ as GamesList_MenuLabel_GameInfo,
  _ as GamesList_MenuLabel_RemoteDownload,
  _ as GamesList_PerfectGames_Description,
  _ as GamesList_PrivacySettings_Tooltip,
  _ as GamesList_RemoteDownload_Help,
  _ as GamesList_RemoteDownload_Info,
  _ as GamesList_RemoteDownload_LearnMore,
  _ as GamesList_RemoteDownload_NoConnection,
  _ as GamesList_RemoteDownload_NoRemoteControl,
  _ as GamesList_RemoteDownload_ReadTheFAQ,
  _ as GamesList_RemoteDownload_UninstallConfirm,
  _ as GamesList_Sort_AchievementCompletion,
  _ as GamesList_Sort_HoursPlayed,
  _ as GamesList_Sort_Name,
  _ as GamesList_Tab_AllGames,
  _ as GamesList_Tab_Followed,
  _ as GamesList_Tab_PerfectGames,
  _ as GamesList_Tab_RecentlyPlayed,
  _ as GamesList_Tab_Reviews,
  _ as GamesList_Tab_Wishlist,
  _ as GamesList_TimeRemaining,
  _ as GamesList_Uninstalling,
  _ as Loading,
  _ as Market_GenericTitle,
  _ as Market_Item_GenericTitle,
  _ as Market_Item_Title,
  _ as Market_Search_Title,
  _ as Moderation_SubjectTypeName_ForumPost,
  _ as Perfect_Game_Description,
  _ as Playtime_Hours,
  _ as Playtime_Minutes,
  _ as community_errorpage_title,
  _ as community_title,
  _ as default,
  _ as empty_no_comma_following,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_accessibility,
  _ as footer_cookies,
  _ as footer_geodata_notice,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_privacy_policy,
  _ as footer_refunds,
  _ as footer_ssa,
  _ as moderatedcontent_description,
  _ as moderation_claim_n_reports_on_m_subjects,
  _ as moderation_claim_report_count,
  _ as moderation_claim_report_count_Plural,
  _ as moderation_claim_subject_count,
  _ as moderation_claim_subject_count_Plural,
  _ as moderation_forumpost_summary,
  _ as moderation_forumpost_summary_reports_fragment,
  _ as moderation_forumpost_summary_reports_fragment_Plural,
  _ as moderation_forumpost_summary_subjects_fragment,
  _ as moderation_forumpost_summary_subjects_fragment_Plural,
  _ as profile_error_profilenotfound,
  _ as profile_games_list,
  _ as profile_games_list_error_loadfailed,
  _ as profile_games_list_title,
  _ as profiletabs_communitymessages,
  _ as profiletabs_currentbans,
  _ as profiletabs_moderatedcontent,
  _ as profiletabs_reportedcontent,
  _ as reportedcontent_description,
  _ as reportedcontent_lastupdated,
};
