var _ = `Postingan forum`,
  _ = `Diskusi Umum`,
  _ = `Postingan yang Dilaporkan`,
  _ = `Diskusi Workshop`,
  _ = `Pertukaran`,
  _ = `Event & Pengumuman`,
  _ = `1 laporan`,
  _ = `%1$s laporan`,
  _ = `1 subjek`,
  _ = `%1$s subjek`,
  _ = `%1$s dalam %2$s`,
  _ = `%1$s dari %2$s berisi topik: %3$s`,
  _ = `1 laporan`,
  _ = `%1$s laporan`,
  _ = `1 subjek`,
  _ = `%1$s subjek`,
  _ = `Komunitas Steam`,
  _ = `Komunitas Steam :: Eror`,
  _ = `Eror`,
  _ = `Eror tidak diketahui`,
  _ = `Game`,
  _ = `Komunitas Steam :: %1$s :: Game`,
  _ = `Pencarian - Pasar Komunitas Steam`,
  _ = `%1$s - Pasar Komunitas Steam`,
  _ = `Item Pasar - Pasar Komunitas Steam`,
  _ = `Pasar Komunitas Steam`,
  _ = `Profil tidak ditemukan`,
  _ = `Gagal memuat wishlist untuk pengguna.`,
  _ = `Kamu terlalu banyak mengajukan permintaan baru-baru ini. Mohon tunggu dan coba lagi nanti.`,
  _ = `Memuat`,
  _ = `%1$s% DIUNDUH`,
  _ = `DIJEDA - %1$s% DIUNDUH`,
  _ = `%1$s/%2$s DIUNDUH`,
  _ = `PENCAPAIAN`,
  _ = `Sekitar %1$s tersisa`,
  _ = `%1$s/%2$s`,
  _ = `MENGHAPUS INSTALAN`,
  _ = `PEMBARUAN`,
  _ = `HAPUS INSTALAN`,
  _ = `UNDUH`,
  _ = `JEDA`,
  _ = `LANJUTKAN`,
  _ = `MENGHAPUS INSTALAN`,
  _ = `BATAL`,
  _ = `Lihat pengaturan privasi saya untuk konten ini`,
  _ = `Temukan game`,
  _ = `Filter berdasarkan game yang sama-sama dimiliki`,
  _ = `Waktu Bermain`,
  _ = `Nama`,
  _ = `Penyelesaian Pencapaian`,
  _ = `TOTAL DIMAINKAN`,
  _ = `TERAKHIR DIMAINKAN`,
  _ = `DUA MINGGU TERAKHIR`,
  _ = `Info & Tautan Game`,
  _ = `Pengunduhan Jarak Jauh`,
  _ = `PENGUNDUHAN JARAK JAUH KE: %1$s`,
  _ = `STATUS PENGUNDUHAN JARAK JAUH: %1$s`,
  _ = `Tidak dapat menjangkau PC-mu`,
  _ = `Untuk mengunduh game secara jarak jauh ke Steam Client-mu, PC-mu harus menyala juga memiliki koneksi internet dan kamu harus sudah login.`,
  _ = `Baca FAQ`,
  _ = `%1$s. %2$s`,
  _ = `Pelajari lebih lanjut`,
  _ = `PENGUNDUHAN JARAK JAUH TIDAK TERSEDIA`,
  _ = `Apa kamu ingin menghapus instalan %1$s? Game akan tetap ada di Perpustakaan Game-mu. Namun, jika ingin memainkannya lagi, kamu harus mengunduh ulang kontennya dahulu.`,
  _ = `%1$s | "%2$s"`,
  _ = `Baru Dimainkan %1$s`,
  _ = `Semua Game %1$s`,
  _ = `Selesai Sempurna %1$s`,
  _ = `Ulasan %1$s`,
  _ = `Diikuti %1$s`,
  _ = `Wishlist`,
  _ = `Mendapatkan semua pencapaian yang mungkin didapat`,
  _ = `Disini kamu akan menemukan game-mu yang Selesai Sempurna atau game yang kamu dapatkan semua pencapaian yang mungkin didapat.`,
  _ = `%1$s% pemain telah membuka pencapaian ini`,
  _ = `Halaman Toko`,
  _ = `Forum`,
  _ = `Grup`,
  _ = `Situs Web Resmi`,
  _ = `Berita`,
  _ = `Pencapaian Saya`,
  _ = `Pencapaian %1$s`,
  _ = `Statistik %1$s`,
  _ = `Data Game Pribadi %1$s`,
  _ = `Papan Peringkat Saya`,
  _ = `Papan Peringkat %1$s`,
  _ = `Pencapaian Global`,
  _ = `Papan Peringkat Global`,
  _ = `Statistik Game`,
  _ = `Konten Game`,
  _ = `Statistik Game Saya`,
  _ = `Konten Game Saya`,
  _ = `Tautan Game`,
  _ = `Screenshot Saya %1$s`,
  _ = `Screenshot %1$s (%2$s)`,
  _ = `Teman yang Bermain %1$s`,
  _ = `Trading Card Saya %1$s`,
  _ = `Ulasan Saya`,
  _ = `Ulasan oleh %1$s`,
  _ = `Hub Komunitas`,
  _ = `Catatan Saya`,
  _ = `%1$s jam`,
  _ = `%1$s menit`,
  _ = `Tandai sebagai Privat`,
  _ = `Cabut Tanda sebagai Privat`,
  _ = `Tandai game ini sebagai privat dan sembunyikan dari teman-teman`,
  _ = `© Valve Corporation. Hak cipta dilindungi Undang-Undang. Semua merek dagang merupakan hak pemilik dari negara AS dan negara lainnya.`,
  _ = `Beberapa data geospasial di situs web ini disediakan oleh %1$s.`,
  _ = `Kebijakan Privasi`,
  _ = `Legal`,
  _ = `Perjanjian Pelanggan Steam`,
  _ = `Pengembalian Dana`,
  _ = `Cookie`,
  _ = `Aksesibilitas`,
  _ = `Ban saat ini`,
  _ = `Pesan komunitas`,
  _ = `Konten yang dilaporkan`,
  _ = `Konten yang dimoderasi`,
  _ = `Berikut adalah beberapa hal di Steam yang telah kamu laporkan karena melanggar pedoman Steam.`,
  _ = `Ini adalah daftar konten yang kamu unggah ke Steam yang telah dimoderasi.`,
  _ = `Terakhir diperbarui: %1$s`,
  _ = `Unduhan`,
  _ = `Komentar Publik (%1$s)`,
  _ = `Komentar Pengembang (%1$s)`,
  _ = `Ini adalah utas privat yang bisa dilihat oleh kontributor item ini dan pengembang game-nya.`,
  _ = `Catatan: Bekerja sama dengan pengembang game tersebut (cth. Valve) tidak menjamin pengajuan item-mu akan terpilih.`,
  _ = `Ukuran`,
  _ = `Lihat semua screenshot`,
  _ = `Lihat semua ilustrasi`,
  _ = `Lihat semua video`,
  _ = `Takarir`,
  _ = `Edit takarir`,
  _ = `Tambahkan Tag Spoiler`,
  _ = `Hapus Tag Spoiler`,
  _ = `Tag spoiler dapat menghalangi pengguna lain dari melihat konten ini untuk menghindari spoiler game.`,
  _ = `(Tag spoiler berlaku selama empat minggu.)`,
  _ = `Pengguna yang ada di screenshot ini: `,
  _ = `Item workshop yang ada di screenshot ini: `,
  _ = `Hapus tag-mu di screenshot ini`,
  _ = `Lokasi`,
  _ = `Tag:`,
  _ = `Memuat Panduan`,
  _ = `Berlangganan untuk menggunakan panduan ini di %1$s`,
  _ = `Indeks Panduan`,
  _ = `Ringkasan`,
  _ = `Komentar`,
  _ = `Edit`,
  _ = `{TAUTAN DIHAPUS}`,
  _ = `URL yang diposting di sini telah dihapus oleh filter kami. Ini biasanya dilakukan untuk mencegah phishing dan serangan malware.`,
  _ = `Konten Panduan`,
  _ = `Tentukan susunan dan nama bagian panduanmu. Seret bagian-bagian tersebut untuk menyusun urutannya.`,
  _ = `Bagian ini diperlukan sebelum panduan dapat dipublikasikan.`,
  _ = `Buat Daftar Isimu`,
  _ = `Tambahkan bagian`,
  _ = `(bagian baru, belum ada nama)`,
  _ = `Edit bagian ini`,
  _ = `Hapus bagian ini`,
  _ = `Apa kamu yakin ingin menghapus bagian ini? Tindakan ini tidak dapat dibatalkan.`,
  _ = `Gambar`,
  _ = `Pilih dan unggah gambar yang mewakili panduanmu. Unggah semua gambar yang diperlukan di sini agar bisa dipilih saat mengedit masing-masing bagian dalam panduanmu.`,
  _ = `Unggah gambar untuk panduanmu`,
  _ = `Tambahkan Kontributor`,
  _ = `Di sini, kamu bisa menambahkan temanmu sebagai kontributor untuk memberikan mereka akses untuk mengedit panduanmu.`,
  _ = `Tambahkan teman sebagai kontributor`,
  _ = `Tambahkan kontributor`,
  _ = `Pratinjau Panduan`,
  _ = `Edit Bagian Panduan`,
  _ = `Nama Bagian`,
  _ = `Konten Bagian`,
  _ = `Edit`,
  _ = `Pratinjau`,
  _ = `Lihat Perbedaan`,
  _ = `Setiap perubahan teks sejak terakhir disimpan akan terlihat seperti ini:`,
  _ = `Teks ini ditampilkan seperti ini telah ditambahkan`,
  _ = `Teks ini ditampilkan seperti ini telah dihapus`,
  _ = `Terdapat perubahan pada bagian ini dan belum disimpan.`,
  _ = `Terdapat perubahan pada bagian ini dan belum disimpan. Apa kamu yakin ingin membuang perubahan-perubahan ini?`,
  _ = `Terakhir disimpan`,
  _ = `Simpan`,
  _ = `Batal`,
  _ = `Screenshot`,
  _ = `Video`,
  _ = `Klik gambar di bawah ini untuk ditambahkan ke panduanmu`,
  _ = `Klik screenshot di bawah ini untuk ditambahkan ke panduanmu`,
  _ = `Klik video di bawah ini untuk ditambahkan ke panduanmu`,
  _ = `Opsi Penyisipan Gambar`,
  _ = `Ukuran`,
  _ = `setengah ukuran lebar`,
  _ = `lebar ukuran penuh`,
  _ = `ukuran original`,
  _ = `Jajaran`,
  _ = `kiri`,
  _ = `kanan`,
  _ = `sebaris`,
  _ = `Rata kiri`,
  _ = `Rata Kanan`,
  _ = `Lebar ukuran penuh`,
  _ = `Sisipkan`,
  _ = `Sisipkan Video YouTube™`,
  _ = `Masukkan URL video YouTube™`,
  _ = `Teks kutipan`,
  _ = `Teks spoiler`,
  _ = `Silakan masukkan judul`,
  _ = `Ke panduanmu`,
  _ = ``,
  _ = `Item Workshop:`,
  _ = `dan %1$s lainnya`,
  _ = `Lihat komentar & rincian`,
  _ = `Lihat %1$s komentar & rincian`,
  _ = `Screenshot`,
  _ = `Ilustrasi`,
  _ = `Video`,
  _ = `Item Workshop`,
  _ = `Merchandise`,
  _ = `Koleksi`,
  _ = `Panduan`,
  _ = `Item Workshop`,
  _ = `Koleksi Workshop`,
  _ = `Panduan`,
  _ = `Favorit`,
  _ = `Item Langganan`,
  _ = `Dimainkan`,
  _ = `Filter berdasarkan game`,
  _ = `Semua game`,
  _ = `Pilih game`,
  _ = `Item`,
  _ = `Difavoritkan`,
  _ = `Item Langganan`,
  _ = `Tanggal Dibuat`,
  _ = `Urutan Abjad`,
  _ = `Tanggal Diperbarui`,
  _ = `Tanggal Berlangganan`,
  _ = `Tanggal Difavoritkan`,
  _ = `Lihat item yang di-tag dengan kata kunci berikut:`,
  _ = `oleh`,
  _ = `Menampilkan %1$s—%2$s dari %3$s kiriman`,
  _ = `Tidak menemukan file %1$s yang dicari.`,
  _ = `Menampilkan %1$s—%2$s dari %3$s kiriman`,
  _ = `Terakhir Diperbarui %1$s`,
  _ = `Ditambahkan pada %1$s`,
  _ = `Item ini telah dihapus dari daftar favoritmu:`,
  _ = `Berlangganan pada %1$s`,
  _ = `Kamu sudah tidak berlangganan:`,
  _ = `Hore! Beberapa kiriman Workshop Steam-mu telah terpilih!`,
  _ = `Sebelum kamu merayakannya, silakan masukkan <a href="%1$s">info pembayaranmu</a> agar kami tahu siapa yang harus dibayar!`,
  _ = `Terjadi kendala saat memverifikasi info pembayaranmu. Silakan tinjau <a href="%1$s">info pembayaranmu</a> dan perbarui infonya.`,
  _ = `Kamu telah ditandai sebagai kontributor untuk item berikut`,
  _ = `Mohon tinjau dan terima pencantuman kredit di item berikut`,
  _ = `Persentase:`,
  _ = `Workshop Saya`,
  _ = `Ikuti pengguna ini untuk melihat saat mereka memposting Panduan Steam baru, membuat Koleksi baru, atau memposting item ke Workshop Steam.`,
  _ = `Pengguna Steam yang mengikutimu dapat melihat saat kamu memposting Panduan Steam baru, membuat Koleksi baru, atau memposting item ke Workshop Steam.`,
  _ = `Pengikut`,
  _ = `Pengikut`,
  _ = `Ikuti %1$s`,
  _ = `Mengikuti %1$s`,
  _ = `Stop ikuti %1$s`,
  _ = `Lihat Pendapatanmu`,
  _ = `Dari penjualan item Workshop-mu`,
  _ = `Masukkan atau Perbarui Info Pembayaranmu`,
  _ = `Lihat Perjanjian Hukum`,
  _ = `Stop Semua Langganan`,
  _ = `Stop Semua Langganan?`,
  _ = `Apa kamu yakin ingin stop semua langganan?<br><br>Tindakan ini tidak dapat dibatalkan!`,
  _ = `Apa kamu yakin ingin stop semua langganan %1$s?<br><br>Tindakan ini tidak dapat dibatalkan!`,
  _ = `Simpan ke Koleksi`,
  _ = `Simpan Langganan ke Koleksi`,
  _ = `Apakah kamu ingin menyimpan langgananmu ke koleksi baru atau yang sudah ada?`,
  _ = `Koleksi Baru`,
  _ = `Masukkan nama untuk koleksi ini:`,
  _ = `Koleksi yang Sudah Ada`,
  _ = `Pilih koleksi yang akan ditimpa: `,
  _ = `Kamu tidak memiliki koleksi apa pun. Buat baru?`,
  _ = `Tag Admin`,
  _ = `Panduan Steam`,
  _ = `Panduan Terpadu`,
  _ = `Build Hero`,
  _ = `Panduan khusus terintegrasi untuk mengajarimu selama kamu bermain`,
  _ = `Panduan yang dipadukan dengan %1$s`,
  _ = `Kategori Populer`,
  _ = `Panduan Terpadu`,
  _ = `Favoritmu`,
  _ = `Panduan Steam Populer`,
  _ = `Panduan, referensi, dan petunjuk langkah tertulis`,
  _ = `Lihat Semua (%1$s)`,
  _ = `%1$s Panduan`,
  _ = `%1$s Panduan`,
  _ = `Panduan yang kamu buat`,
  _ = `Info Lebih Lanjut Tentang Panduan`,
  _ = `Klik di sini untuk mempelajari Panduan Steam lebih lanjut`,
  _ = `Telusuri berdasarkan:`,
  _ = `Beranda`,
  _ = `Buat Panduan`,
  _ = `Jika kamu ingin membuat panduan, kamu harus membeli %1$s terlebih dulu.`,
  _ = `Jadilah orang pertama yang membuat panduan untuk game ini!`,
  _ = `Tunjukkan keahlianmu atau bantu pemain lain yang sedang kesulitan.`,
  _ = `Buat panduan langkah yang mudah diikuti, temukan rahasia dalam game, atau sarankan strategi yang optimal untuk map tertentu.`,
  _ = `Telusuri dan beri rating panduan game yang dibuat oleh pemain lain. Kamu juga bisa membuat panduanmu untuk dibagikan ke komunitas.`,
  _ = `Buat panduanmu`,
  _ = `Screenshot`,
  _ = `Ilustrasi`,
  _ = `Video`,
  _ = `Tampilkan %1$s - %2$s dari %3$s`,
  _ = `Kembali ke atas`,
  _ = `Melihat`,
  _ = `Galeri dinding`,
  _ = `Kisi`,
  _ = `Terpopuler`,
  _ = `Mulai dari terbaru`,
  _ = `Mulai dari terlama`,
  _ = `Semua Screenshot Milikmu`,
  _ = `Screenshot Publik Milikmu`,
  _ = `Screenshot Khusus Teman Milikmu`,
  _ = `Screenshot Privat Milikmu`,
  _ = `Screenshot Tidak Terdaftar Milikmu`,
  _ = `Semua Ilustrasimu`,
  _ = `Ilustrasi Publik`,
  _ = `Ilustrasi Khusus Teman`,
  _ = `Ilustrasi Privat`,
  _ = `Ilustrasi Tidak Terdaftar Milikmu`,
  _ = `Semua Videomu`,
  _ = `Video Publik Milikmu`,
  _ = `Video Khusus Teman Milikmu`,
  _ = `Video Privat Milikmu`,
  _ = `Video Tidak Terdaftar Milikmu`,
  _ = `Kelola screenshot`,
  _ = `Kelola ilustrasi`,
  _ = `Kelola video`,
  _ = `Pilih screenshot yang akan kamu tindak.`,
  _ = `Pilih ilustrasi di bawah ini yang akan kamu tindak.`,
  _ = `Pilih video yang akan kamu tindak.`,
  _ = `Batal`,
  _ = `Tambahkan video dari YouTube`,
  _ = `Tautkan akun YouTube`,
  _ = `Batalkan penautan akun YouTube`,
  _ = `Batalkan penautan`,
  _ = `Apakah kamu yakin ingin membatalkan penautan akun YouTube milikmu?`,
  _ = `Bagaimana Steam menggunakan data saya dari YouTube?`,
  _ = `Menautkan akun Youtube ke Steam menggunakan Layanan API Youtube. Dengan menggunakan YouTube dan menautkan akun YouTube ke Profil Steam-mu, kamu menyetujui untuk mematuhi %1$s dan %2$s.`,
  _ = `Steam menggunakan Layanan API YouTube untuk mengautentikasi akun YouTube-mu dan untuk mengakses daftar video yang telah kamu posting ke YouTube. Saat kamu menautkan akun YouTube-mu ke Steam, Steam akan menempatkan cookie di browser atau Steam Client yang berisi token autentikasi akunmu untuk YouTube. Cookie ini kedaluwarsa setelah 30 hari. Ketika Steam mengakses daftar video yang diposting ke akun YouTube-mu, data ini hanya digunakan untuk menampilkan daftar tersebut kepadamu di Steam.`,
  _ = `Saat kamu memposting video dari akun YouTube ke Steam, Steam hanya akan menyimpan informasi yang diperlukan untuk menampilkan video di Steam, termasuk ID video dan ID akun YouTube dari video tersebut. Data ini hanya akan digunakan untuk menampilkan video di Steam dan untuk moderasi konten di Steam.`,
  _ = `Kamu dapat mencabut akses Steam ke %1$s milikmu melalui %2$s.`,
  _ = `Persyaratan Layanan YouTube`,
  _ = `Kebijakan Privasi Google`,
  _ = `Data yang Diotorisasi`,
  _ = `Halaman pengaturan keamanan Google`,
  _ = `Videomu. Sekarang ada di Steam.`,
  _ = `Bagikan momen gaming terbaikmu dengan teman-temanmu. Unggah sorotan keren, ulasan yang mendalam, tutorial yang membantu, dan hal keren lainnya buatanmu yang terinspirasi dari game.`,
  _ = `1. Tautkan akun YouTube™ milikmu ke Profil Steam-mu.`,
  _ = `2. Pilih video yang ingin kamu tambahkan ke profilmu.`,
  _ = `3. Bagikan dengan teman-teman Steam-mu agar mereka dapat menontonnya.`,
  _ = `Akses video YouTube`,
  _ = `Saat ini kamu tertaut dengan akun YouTube %1$s.`,
  _ = `Batalkan penautan akun ini untuk menambahkan akun lainnya.`,
  _ = `Batalkan penautan akun ini`,
  _ = `Lanjutkan dengan akun ini`,
  _ = `Berhasil menautkan akun YouTube-mu`,
  _ = `Berhasil menambahkan 1 video`,
  _ = `Berhasil menambahkan %1$s video`,
  _ = `Tidak ada video yang dapat dipilih dari koleksi YouTube-mu.`,
  _ = `Kamu hanya dapat menambahkan video YouTube yang dapat diperlihatkan secara publik, bisa disematkan, dan juga bisa dicari nama penggunanya. Jika kamu baru saja mengatur video yang ditampilkan secara publik agar akunmu bisa ditautkan, YouTube memerlukan waktu untuk memasukkannya agar dapat dicari nanti.`,
  _ = `Kamu saat ini memiliki akun YouTube %1$s yang ditautkan ke Steam.`,
  _ = `Klik di sini untuk mengubah akun YouTube`,
  _ = `ganti akun`,
  _ = `1. Pilih video yang akan ditambahkan.`,
  _ = `1 video tersedia untuk akun %1$s`,
  _ = `Menampilkan %1$s video terkini yang tersedia untuk akun: %2$s`,
  _ = `2. Kaitkan video tersebut dengan sebuah game.`,
  _ = `Setelah kamu memilih video yang ada di sebelah kiri. (Opsional)`,
  _ = `- tidak ada / lainnya (jelaskan di bawah ini) -`,
  _ = `Lainnya / Tidak Terdaftar`,
  _ = `3. Tambahkan ke profilmu.`,
  _ = `Tambahkan video`,
  _ = `Catatan: Agar kamu bisa menambahkan video dari akun YouTube-mu, videonya harus dapat dilihat secara Publik dan bisa disematkan. Jika kamu baru saja menambahkan video ke akun YouTube-mu dan belum melihatnya, coba refresh dengan menekan tombol di bawah ini.`,
  _ = `Refresh daftar video YouTube`,
  _ = `4. Selesaikan.`,
  _ = `Setelah selesai, klik Selesai untuk melihat video di halaman profilmu.`,
  _ = `Selesai`,
  _ = `Terjadi kendala saat mengakses umpan videomu, silakan coba lagi.`,
  _ = `Unggah ilustrasi`,
  _ = `Unggah screenshot...`,
  _ = `Jadikan Publik`,
  _ = `Jadikan Hanya Teman`,
  _ = `Jadikan Privat`,
  _ = `Jadikan Tidak Terdaftar`,
  _ = `Hapus`,
  _ = `Pilih Semua`,
  _ = `Selesai`,
  _ = `Hapus item-item ini?`,
  _ = `Perbarui Privasi`,
  _ = `%1$s akan dihapus dari Steam Cloud. Lanjutkan?`,
  _ = `Ini akan memperbarui visibilitas %1$s menjadi %2$s. Lanjutkan?`,
  _ = `Lanjut`,
  _ = `Batal`,
  _ = `Ups!`,
  _ = `Tidak ada item yang dipilih.`,
  _ = `Pilih item yang akan dihapus melalui kotak yang ada di bagian ujung setiap thumbnail.`,
  _ = `OK`,
  _ = `Gagal memperbarui visibilitas`,
  _ = `Tidak dapat memperbarui visibilitas satu atau beberapa screenshot menjadi Publik atau Hanya Teman. Screenshot untuk game yang belum dirilis di Komunitas Steam secara publik tidak dapat dibagikan dan hanya bisa dilihat olehmu.`,
  _ = `Berpotensi mengandung spoiler.`,
  _ = `Geser untuk menampilkan gambar.`,
  _ = `Tidak menemukan screenshot yang dicari.`,
  _ = `%1$s tidak memiliki screenshot yang bisa kamu lihat.`,
  _ = `Kamu belum memilih screenshot apa pun sebagai favorit.`,
  _ = `%1$s tidak memiliki screenshot favorit yang bisa kamu lihat.`,
  _ = `Saat ini, kamu tidak memiliki ilustrasi yang disimpan di Steam Cloud. Kunjungi tab Ilustrasi Hub Game dan cari tombol Unggah Ilustrasi di sebelah kanan atas untuk mengunggah ilustrasi. Atau, klik tombol "Unggah ilustrasi" di bawah ini.`,
  _ = `%1$s tidak memiliki ilustrasi yang bisa kamu lihat.`,
  _ = `Kamu belum memilih ilustrasi apa pun sebagai favorit.`,
  _ = `%1$s tidak memiliki ilustrasi favorit yang bisa kamu lihat.`,
  _ = `Tidak menemukan video yang dicari.`,
  _ = `%1$s tidak memiliki video yang bisa kamu lihat.`,
  _ = `Kamu belum memilih video apa pun sebagai favorit.`,
  _ = `%1$s tidak memiliki video favorit yang bisa kamu lihat.`,
  _ = `Tidak ada screenshot yang diatur ke visibilitas ini.`,
  _ = `Steam memudahkanmu untuk mengambil dan berbagi screenshot dari game favoritmu.`,
  _ = `Tekan tombol pintas (F12 secara default) untuk mengambil screenshot saat kamu sedang bermain game yang menjalankan Overlay Steam. Kemudian publikasikan ke profil Komunitas Steam-mu serta Facebook, Twitter, atau Reddit untuk membagikannya dengan teman-temanmu.`,
  _ = `Dengan Steam Cloud pribadi berukuran 1GB, kamu bisa mengunggah ribuan screenshot untuk menampilkan momen terbaikmu kepada teman-teman atau kamu bisa menyimpannya untuk dirimu sendiri.`,
  _ = `Oleh %1$s`,
  _ = `Favorit %1$s`,
  _ = {
    Moderation_SubjectTypeName_ForumPost: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    moderation_claim_report_count: _,
    moderation_claim_report_count_Plural: _,
    moderation_claim_subject_count: _,
    moderation_claim_subject_count_Plural: _,
    moderation_claim_n_reports_on_m_subjects: _,
    moderation_forumpost_summary: _,
    moderation_forumpost_summary_reports_fragment: _,
    moderation_forumpost_summary_reports_fragment_Plural: _,
    moderation_forumpost_summary_subjects_fragment: _,
    moderation_forumpost_summary_subjects_fragment_Plural: _,
    community_title: _,
    community_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    profile_games_list: _,
    profile_games_list_title: _,
    Market_Search_Title: _,
    Market_Item_Title: _,
    Market_Item_GenericTitle: _,
    Market_GenericTitle: _,
    profile_error_profilenotfound: _,
    profile_games_list_error_loadfailed: _,
    Error_RateLimited: _,
    Loading: _,
    GamesList_Header_Downloading: _,
    GamesList_Header_Paused: _,
    GamesList_Header_DownloadBytes: _,
    GamesList_Header_Achievements: _,
    GamesList_TimeRemaining: _,
    GamesList_Achievement_Fraction: _,
    GamesList_Uninstalling: _,
    GamesList_Button_UpdateRequired: _,
    GamesList_Button_Uninstall: _,
    GamesList_Button_Download: _,
    GamesList_Button_Pause: _,
    GamesList_Button_Resume: _,
    GamesList_Button_Uninstalling: _,
    GamesList_Button_Cancel: _,
    GamesList_PrivacySettings_Tooltip: _,
    GamesList_Filter_Placeholder: _,
    GamesList_Filter_BothOwned: _,
    GamesList_Sort_HoursPlayed: _,
    GamesList_Sort_Name: _,
    GamesList_Sort_AchievementCompletion: _,
    GamesList_Header_TotalPlayed: _,
    GamesList_Header_LastPlayed: _,
    GamesList_Header_TwoWeeks: _,
    GamesList_MenuLabel_GameInfo: _,
    GamesList_MenuLabel_RemoteDownload: _,
    GamesList_Header_RemoteDownload: _,
    GamesList_Header_RemoteDownloadStatus: _,
    GamesList_RemoteDownload_NoConnection: _,
    GamesList_RemoteDownload_Help: _,
    GamesList_RemoteDownload_ReadTheFAQ: _,
    GamesList_RemoteDownload_Info: _,
    GamesList_RemoteDownload_LearnMore: _,
    GamesList_RemoteDownload_NoRemoteControl: _,
    GamesList_RemoteDownload_UninstallConfirm: _,
    GamesList_Client_Indicator: _,
    GamesList_Tab_RecentlyPlayed: _,
    GamesList_Tab_AllGames: _,
    GamesList_Tab_PerfectGames: _,
    GamesList_Tab_Reviews: _,
    GamesList_Tab_Followed: _,
    GamesList_Tab_Wishlist: _,
    Perfect_Game_Description: _,
    GamesList_PerfectGames_Description: _,
    GamesList_Achievement_Unlock_Percentage: _,
    Community_StorePage: _,
    Community_Forums: _,
    Community_Groups: _,
    Community_OfficialWebsite: _,
    Community_News: _,
    Community_UsersAchievementsFirstPerson: _,
    Community_UsersAchievements: _,
    Community_UsersStats: _,
    Community_GamePersonalData: _,
    Community_UsersLeaderboardsFirstPerson: _,
    Community_UsersLeaderboards: _,
    Community_GlobalAchievements: _,
    Community_GlobalLeaderboards: _,
    Community_GameStats: _,
    Community_GameContent: _,
    Community_GameStatsFirstPerson: _,
    Community_GameContentFirstPerson: _,
    Community_GameLinks: _,
    Community_ScreenshotsMenuItemFirstPerson: _,
    Community_ScreenshotsMenuItemThirdPerson: _,
    Community_FriendsWhoPlayMenuItemFirstPerson: _,
    Community_TradingCardsMenuItemFirstPerson: _,
    Community_ReviewMenuItemFirstPerson: _,
    Community_ReviewMenuItemThirdPerson: _,
    Community_GameHubMenuItem: _,
    Community_GameNotesFirstPerson: _,
    Playtime_Hours: _,
    Playtime_Minutes: _,
    AppPrivacy_MarkAsPrivate: _,
    AppPrivacy_UnmarkAsPrivate: _,
    AppPrivacy_Explanation: _,
    footer_legal_notice: _,
    footer_geodata_notice: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_accessibility: _,
    profiletabs_currentbans: _,
    profiletabs_communitymessages: _,
    profiletabs_reportedcontent: _,
    profiletabs_moderatedcontent: _,
    reportedcontent_description: _,
    moderatedcontent_description: _,
    reportedcontent_lastupdated: _,
    SharedFiles_ItemDownload: _,
    SharedFiles_PublicComments: _,
    SharedFiles_DeveloperComments: _,
    Workshop_DeveloperThreadDesc: _,
    Workshop_DeveloperThreadDisclaimerText: _,
    Workshop_ImageSize: _,
    SharedFiles_Media_ViewAppScreenshots: _,
    SharedFiles_Media_ViewAppFanArt: _,
    SharedFiles_Media_ViewAppVideos: _,
    SharedFiles_ItemEditText_Text_Caption: _,
    SharedFiles_OwnerControl_EditCaption: _,
    SharedFiles_AddSpoilerTag: _,
    SharedFiles_RemoveSpoilerTag: _,
    SharedFiles_SpoilerTagInstructions: _,
    SharedFiles_SpoilerTagsExpire: _,
    SharedFiles_Stats_TaggedUsers: _,
    SharedFiles_Stats_TaggedWorkshopItems: _,
    SharedFiles_RemoveSelfTag_Tooltip: _,
    Screenshots_Location: _,
    SharedFiles_Tags: _,
    SharedFiles_WaitingForIntegratedGuide: _,
    Workshop_Subscribe_IntegratedGuide: _,
    SharedFiles_Guide_Index: _,
    SharedFiles_Guide_Overview: _,
    SharedFiles_Guide_Comments: _,
    SharedFiles_Item_Edit_Link: _,
    Community_RemoveLink_BeWary: _,
    Community_RemoveLink_Tooltip: _,
    SharedFiles_ManageGuide_Contents: _,
    SharedFiles_ManageGuide_Contents_Desc: _,
    SharedFiles_ManageGuide_Required: _,
    SharedFiles_ManageGuide_NoSubSections: _,
    SharedFiles_ManageGuide_AddSection: _,
    SharedFiles_ManageGuide_NoSectionTitle: _,
    SharedFiles_ManageGuide_EditThisSection: _,
    SharedFiles_ManageGuide_DeleteThisSection: _,
    SharedFiles_ManageGuide_RemoveSectionConfirm: _,
    SharedFiles_ManageGuide_Images: _,
    SharedFiles_ManageGuide_Images_Desc: _,
    SharedFiles_ManageGuide_NoPreviewImages: _,
    SharedFiles_ManageGuide_Contributors: _,
    SharedFiles_ManageGuide_Contributors_Desc: _,
    SharedFiles_ManageGuide_NoContributors: _,
    SharedFiles_ManageGuide_AddContributor: _,
    SharedFiles_ManageGuide_Preview: _,
    SharedFiles_ManageGuide_EditSubSection: _,
    SharedFiles_ManageGuide_SubSectionTitle: _,
    SharedFiles_ManageGuide_SubSectionContents: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Edit: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Preview: _,
    SharedFiles_ManageGuide_EditSubSection_Tab_Changes: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Desc: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Insert: _,
    SharedFiles_ManageGuide_EditSubSection_Diff_Delete: _,
    SharedFiles_ManageGuide_SubSectionContentChanged: _,
    SharedFiles_ManageGuide_SubSectionContentChanged_CancelConfirm: _,
    SharedFiles_ManageGuide_SubSectionContentSaved: _,
    SharedFiles_ManageGuide_Save: _,
    SharedFiles_ManageGuide_Cancel: _,
    SharedFiles_ManageGuide_Screenshots: _,
    SharedFiles_ManageGuide_Videos: _,
    SharedFiles_ManageGuide_SubImages: _,
    SharedFiles_ManageGuide_SubScreenshots: _,
    SharedFiles_ManageGuide_SubVideos: _,
    SharedFiles_ManageGuide_ImageInsertionOptions: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_Size: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeThumb: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeFull: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_SizeOriginal: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_Layout: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutLeft: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutRight: _,
    SharedFiles_ManageGuide_ImageInsertionOptions_LayoutInline: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Left: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Right: _,
    SharedFiles_ManageGuide_YouTubeInsertionOptions_Full: _,
    SharedFiles_ManageGuide_InsertImage: _,
    SharedFiles_ManageGuide_InsertYouTubeVideo: _,
    SharedFiles_ManageGuide_PromptYouTubeUrl: _,
    Discussions_FormattingHelp_Quote: _,
    Discussions_FormattingHelp_Spoiler: _,
    SharedFiles_ItemEditText_ErrorNoTitle: _,
    SharedFiles_OwnerControl_BackGuide: _,
    empty_no_comma_following: ``,
    SharedFiles_WorkshopItemsTagged: _,
    SharedFiles_And_N_More: _,
    Workshop_ItemModalViewDetails: _,
    Workshop_ItemModalViewCountDetails: _,
    Profile_Screenshots: _,
    Profile_Images: _,
    Profile_Videos: _,
    Profile_Workshop_Items: _,
    SharedFiles_Tab_Merchandise: _,
    Profile_Collections: _,
    Profile_Guides: _,
    SharedFiles_SharedFiles_Items: _,
    SharedFiles_SharedFiles_Collections: _,
    SharedFiles_SharedFiles_Guides: _,
    SharedFiles_Favorites: _,
    SharedFiles_Subscriptions: _,
    SharedFiles_Browse_MyFiles_Played: _,
    SharedFiles_FilterByGame: _,
    Profile_SharedFiles_AllGames: _,
    Profile_SharedFiles_SelectAGame: _,
    SharedFiles_Browse_MyFiles_Items: _,
    SharedFiles_Browse_MyFiles_Favorites: _,
    SharedFiles_Browse_MyFiles_Subscriptions: _,
    SharedFiles_Browse_MyFiles_Sort_CreationOrder: _,
    SharedFiles_Browse_MyFiles_Sort_Alpha: _,
    SharedFiles_Browse_MyFiles_Sort_LastUpdated: _,
    SharedFiles_Browse_MyFiles_Sort_Subscribed: _,
    SharedFiles_Browse_MyFiles_Sort_Favorited: _,
    SharedFiles_TagsSearch: _,
    SharedFiles_ByAuthor: _,
    Workshop_BrowsePaging: _,
    Workshop_NoItems: _,
    SharedFiles_UserList_BrowsePaging: _,
    SharedFiles_UserList_LastUpdated: _,
    SharedFiles_Favorites_Subscribed: _,
    SharedFiles_Favorites_NowUnsubscribed: _,
    SharedFiles_Subscription_Subscribed: _,
    SharedFiles_Subscription_NowUnsubscribed: _,
    Workshop_HasLinkedItems: _,
    Workshop_PaymentInfo_NotCreated: _,
    Workshop_PaymentInfo_Rejected: _,
    Workshop_SplitsAcceptTheseDesc1: _,
    Workshop_SplitsAcceptTheseDesc2: _,
    Workshop_SplitsPercentage: _,
    Profile_YourWorkshop: _,
    CommunityFollower_Description: _,
    CommunityFollower_Description_Yours: _,
    CommunityFollower_One_Follower: _,
    CommunityFollower_NumFollowers: _,
    CommunityFollower_FollowUser: _,
    CommunityFollower_FollowingUser: _,
    CommunityFollower_UnfollowUser: _,
    Workshop_ViewYourRevenue: _,
    Workshop_ViewYourRevenue_desc: _,
    Workshop_Link_PaymentInfo: _,
    Workshop_Link_LegalAgreement: _,
    SharedFiles_UnsubscribeAll_Btn: _,
    SharedFiles_UnsubscribeAll_Confirm_Title: _,
    SharedFiles_UnsubscribeAll_Confirm_Desc: _,
    SharedFiles_UnsubscribeAll_Confirm_App_Desc: _,
    SharedFiles_SaveSubscribedToCollection_Btn: _,
    SharedFiles_SaveSubscribedToCollection_Title: _,
    SharedFiles_SaveSubscribedToCollection_Desc: _,
    SharedFiles_SaveSubscribedToCollection_New: _,
    SharedFiles_SaveSubscribedToCollection_NewDesc: _,
    SharedFiles_SaveSubscribedToCollection_Existing: _,
    SharedFiles_SaveSubscribedToCollection_ExistingDesc: _,
    SharedFiles_SaveSubscribedToCollection_NoExistingCollections: _,
    SharedFiles_AdminTags: _,
    SharedFiles_SearchedForFileType_WebGuide: _,
    SharedFiles_SearchedForFileType_IntegratedGuide: _,
    SharedFiles_Dota2_IntegratedGuide: _,
    SharedFiles_Dota2_IntegratedGuide_Desc: _,
    AppHub_Guides_IntegratedGuides_Desc: _,
    AppHub_Guides_PopularCategories: _,
    AppHub_Guides_IntegratedGuides: _,
    AppHub_Guides_YourFavorites: _,
    AppHub_Guides_MostPopularThisWeek: _,
    AppHub_Guides_MostPopularThisWeek_Desc: _,
    AppHub_Guides_ViewAll: _,
    AppHub_Guides_NumGuides_Singular: _,
    AppHub_Guides_NumGuides_Plural: _,
    AppHub_Guides_GuidesYouHaveMade: _,
    AppHub_Guides_MoreInfo_Title: _,
    AppHub_Guides_MoreInfo_button: _,
    Workshop_BrowseBy: _,
    SharedFiles_Browse_GuideHome: _,
    SharedFiles_CreateGuide: _,
    SharedFiles_MustOwnAppToCreateGuide: _,
    SharedFiles_NoGuides_Title: _,
    SharedFiles_NoGuides_Desc1: _,
    SharedFiles_NoGuides_Desc2: _,
    SharedFiles_BrowseGuide_subtitle_nolink: _,
    SharedFiles_BrowseGuide_createNewBtnLabel: _,
    Community_Screenshots: _,
    Community_Images: _,
    Community_Videos: _,
    Paging_ShowingXtoYofZ: _,
    AppHubHome_BackToTop: _,
    Screenshots_Viewing: _,
    Profile_SharedFiles_ImageWallView: _,
    Profile_SharedFiles_GridView: _,
    Profile_SharedFiles_MostPopular: _,
    Profile_SharedFiles_NewestFirst: _,
    Profile_SharedFiles_OldestFirst: _,
    Screenshots_AllYourScreenshots: _,
    Screenshots_YourPublicScreenshots: _,
    Screenshots_YourFriendsOnlyScreenshots: _,
    Screenshots_YourPrivateScreenshots: _,
    Screenshots_YourUnlistedScreenshots: _,
    Images_AllYourImages: _,
    Images_YourPublicImages: _,
    Images_YourFriendsOnlyImages: _,
    Images_YourPrivateImages: _,
    Images_YourUnlistedImages: _,
    Videos_AllYourVideos: _,
    Videos_YourPublicVideos: _,
    Videos_YourFriendsOnlyVideos: _,
    Videos_YourPrivateVideos: _,
    Videos_YourUnlistedVideos: _,
    Screenshots_Manage: _,
    Images_Manage: _,
    Videos_Manage: _,
    Screenshots_SelectScreenshots: _,
    Images_SelectImages: _,
    Videos_SelectVideos: _,
    Videos_Cancel: _,
    Videos_AddFromYouTube: _,
    Videos_LinkYouTubeAcct: _,
    Videos_UnlinkYouTubeAcct: _,
    Videos_UnlinkButton: _,
    Videos_UnlinkConfirmText: _,
    Videos_Privacy: _,
    Videos_YoutubeTerms_1: _,
    Videos_YoutubeTerms_2: _,
    Videos_YoutubeTerms_3: _,
    Videos_YoutubeTerms_4: _,
    Videos_YoutubeTermsLink_TermsOfService: _,
    Videos_YoutubeTermsLink_PrivacyPolicy: _,
    Videos_YoutubeTermsLink_AuthorizedData: _,
    Videos_YoutubeTermsLink_SecuritySettings: _,
    Videos_NowOnSteam: _,
    Videos_ShareDescription: _,
    Videos_Desc1: _,
    Videos_Desc2: _,
    Videos_Desc3: _,
    Videos_AccessYourYouTubeVideos: _,
    Videos_CurrentlyLinkedTo: _,
    Videos_UnlinkToAddAnother: _,
    Videos_UnlinkAcct: _,
    Videos_ContinueWithAcct: _,
    Videos_SuccessfullyLinkedYouTube: _,
    Videos_SuccessfullyAddedSingular: _,
    Videos_SuccessfullyAddedPlural: _,
    Videos_NoVideosMsg1: _,
    Videos_NoVideosMsg2: _,
    Videos_CurrentlyLinkedMsg: _,
    Videos_ClickHereToChange: _,
    Videos_ChangeAccount: _,
    Videos_AddStep1: _,
    Videos_AvailCountSingular: _,
    Videos_AvailCountPlural: _,
    Videos_AddStep2: _,
    Videos_AddStep2Note: _,
    Videos_OptionNoneOther: _,
    Videos_OtherUnlisted: _,
    Videos_AddStep3: _,
    Videos_AddVideo: _,
    Videos_AddNote2: _,
    Videos_Refresh: _,
    Videos_AddStep4: _,
    Videos_AddNote4: _,
    Videos_AddDone: _,
    Videos_IssuesAccessing: _,
    Images_Upload: _,
    Screenshots_Upload: _,
    Screenshots_MakePublic: _,
    Screenshots_MakeFriendsOnly: _,
    Screenshots_MakePrivate: _,
    Screenshots_MakeUnlisted: _,
    Screenshots_Delete: _,
    Screenshots_SelectAll: _,
    Screenshots_Done: _,
    Screenshots_DeleteScreenshots: _,
    Screenshots_UpdatePrivacy: _,
    Screenshots_AreYouSureDelete: _,
    Screenshots_AreYouSurePrivacyChange: _,
    Screenshots_Continue: _,
    Screenshots_Cancel: _,
    Screenshots_Oops: _,
    Screenshots_NoneSelected: _,
    Screenshots_SelectScreenshotsToDelete: _,
    Screenshots_OK: `OK`,
    Screenshots_VisUpdateFailed: _,
    Screenshots_VisUpdateFailedMessage: _,
    Blotter_PotentialSpoilers: _,
    Blotter_RevealImage: _,
    Profile_SharedFiles_NoScreenshotsSelf: _,
    Profile_SharedFiles_NoScreenshotsForYou: _,
    Profile_SharedFiles_NoScreenshotsFavoritesSelf: _,
    Profile_SharedFiles_NoScreenshotsFavoritesForYou: _,
    Profile_SharedFiles_NoImagesSelf: _,
    Profile_SharedFiles_NoImagesForYou: _,
    Profile_SharedFiles_NoImagesFavoritesSelf: _,
    Profile_SharedFiles_NoImagesFavoritesForYou: _,
    Profile_SharedFiles_NoVideosSelf: _,
    Profile_SharedFiles_NoVideosForYou: _,
    Profile_SharedFiles_NoVideosFavoritesSelf: _,
    Profile_SharedFiles_NoVideosFavoritesForYou: _,
    Profile_SharedFiles_NoScreenshotsThisVisibility: _,
    Screenshots_SteamHasThem: _,
    Screenshots_Instructions1: _,
    Screenshots_Instructions2: _,
    Profile_SharedFiles_By: _,
    Profile_SharedFiles_FavoritedBy: _,
  };
export {
  _ as AppHubHome_BackToTop,
  _ as AppHub_Guides_GuidesYouHaveMade,
  _ as AppHub_Guides_IntegratedGuides,
  _ as AppHub_Guides_IntegratedGuides_Desc,
  _ as AppHub_Guides_MoreInfo_Title,
  _ as AppHub_Guides_MoreInfo_button,
  _ as AppHub_Guides_MostPopularThisWeek,
  _ as AppHub_Guides_MostPopularThisWeek_Desc,
  _ as AppHub_Guides_NumGuides_Plural,
  _ as AppHub_Guides_NumGuides_Singular,
  _ as AppHub_Guides_PopularCategories,
  _ as AppHub_Guides_ViewAll,
  _ as AppHub_Guides_YourFavorites,
  _ as AppPrivacy_Explanation,
  _ as AppPrivacy_MarkAsPrivate,
  _ as AppPrivacy_UnmarkAsPrivate,
  _ as Blotter_PotentialSpoilers,
  _ as Blotter_RevealImage,
  _ as CommunityFollower_Description,
  _ as CommunityFollower_Description_Yours,
  _ as CommunityFollower_FollowUser,
  _ as CommunityFollower_FollowingUser,
  _ as CommunityFollower_NumFollowers,
  _ as CommunityFollower_One_Follower,
  _ as CommunityFollower_UnfollowUser,
  _ as Community_Forums,
  _ as Community_FriendsWhoPlayMenuItemFirstPerson,
  _ as Community_GameContent,
  _ as Community_GameContentFirstPerson,
  _ as Community_GameHubMenuItem,
  _ as Community_GameLinks,
  _ as Community_GameNotesFirstPerson,
  _ as Community_GamePersonalData,
  _ as Community_GameStats,
  _ as Community_GameStatsFirstPerson,
  _ as Community_GlobalAchievements,
  _ as Community_GlobalLeaderboards,
  _ as Community_Groups,
  _ as Community_Images,
  _ as Community_News,
  _ as Community_OfficialWebsite,
  _ as Community_RemoveLink_BeWary,
  _ as Community_RemoveLink_Tooltip,
  _ as Community_ReviewMenuItemFirstPerson,
  _ as Community_ReviewMenuItemThirdPerson,
  _ as Community_Screenshots,
  _ as Community_ScreenshotsMenuItemFirstPerson,
  _ as Community_ScreenshotsMenuItemThirdPerson,
  _ as Community_StorePage,
  _ as Community_TradingCardsMenuItemFirstPerson,
  _ as Community_UsersAchievements,
  _ as Community_UsersAchievementsFirstPerson,
  _ as Community_UsersLeaderboards,
  _ as Community_UsersLeaderboardsFirstPerson,
  _ as Community_UsersStats,
  _ as Community_Videos,
  _ as Discussions_FormattingHelp_Quote,
  _ as Discussions_FormattingHelp_Spoiler,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as GamesList_Achievement_Fraction,
  _ as GamesList_Achievement_Unlock_Percentage,
  _ as GamesList_Button_Cancel,
  _ as GamesList_Button_Download,
  _ as GamesList_Button_Pause,
  _ as GamesList_Button_Resume,
  _ as GamesList_Button_Uninstall,
  _ as GamesList_Button_Uninstalling,
  _ as GamesList_Button_UpdateRequired,
  _ as GamesList_Client_Indicator,
  _ as GamesList_Filter_BothOwned,
  _ as GamesList_Filter_Placeholder,
  _ as GamesList_Header_Achievements,
  _ as GamesList_Header_DownloadBytes,
  _ as GamesList_Header_Downloading,
  _ as GamesList_Header_LastPlayed,
  _ as GamesList_Header_Paused,
  _ as GamesList_Header_RemoteDownload,
  _ as GamesList_Header_RemoteDownloadStatus,
  _ as GamesList_Header_TotalPlayed,
  _ as GamesList_Header_TwoWeeks,
  _ as GamesList_MenuLabel_GameInfo,
  _ as GamesList_MenuLabel_RemoteDownload,
  _ as GamesList_PerfectGames_Description,
  _ as GamesList_PrivacySettings_Tooltip,
  _ as GamesList_RemoteDownload_Help,
  _ as GamesList_RemoteDownload_Info,
  _ as GamesList_RemoteDownload_LearnMore,
  _ as GamesList_RemoteDownload_NoConnection,
  _ as GamesList_RemoteDownload_NoRemoteControl,
  _ as GamesList_RemoteDownload_ReadTheFAQ,
  _ as GamesList_RemoteDownload_UninstallConfirm,
  _ as GamesList_Sort_AchievementCompletion,
  _ as GamesList_Sort_HoursPlayed,
  _ as GamesList_Sort_Name,
  _ as GamesList_Tab_AllGames,
  _ as GamesList_Tab_Followed,
  _ as GamesList_Tab_PerfectGames,
  _ as GamesList_Tab_RecentlyPlayed,
  _ as GamesList_Tab_Reviews,
  _ as GamesList_Tab_Wishlist,
  _ as GamesList_TimeRemaining,
  _ as GamesList_Uninstalling,
  _ as Images_AllYourImages,
  _ as Images_Manage,
  _ as Images_SelectImages,
  _ as Images_Upload,
  _ as Images_YourFriendsOnlyImages,
  _ as Images_YourPrivateImages,
  _ as Images_YourPublicImages,
  _ as Images_YourUnlistedImages,
  _ as Loading,
  _ as Market_GenericTitle,
  _ as Market_Item_GenericTitle,
  _ as Market_Item_Title,
  _ as Market_Search_Title,
  _ as Moderation_SubjectTypeName_ForumPost,
  _ as Paging_ShowingXtoYofZ,
  _ as Perfect_Game_Description,
  _ as Playtime_Hours,
  _ as Playtime_Minutes,
  _ as Profile_Collections,
  _ as Profile_Guides,
  _ as Profile_Images,
  _ as Profile_Screenshots,
  _ as Profile_SharedFiles_AllGames,
  _ as Profile_SharedFiles_By,
  _ as Profile_SharedFiles_FavoritedBy,
  _ as Profile_SharedFiles_GridView,
  _ as Profile_SharedFiles_ImageWallView,
  _ as Profile_SharedFiles_MostPopular,
  _ as Profile_SharedFiles_NewestFirst,
  _ as Profile_SharedFiles_NoImagesFavoritesForYou,
  _ as Profile_SharedFiles_NoImagesFavoritesSelf,
  _ as Profile_SharedFiles_NoImagesForYou,
  _ as Profile_SharedFiles_NoImagesSelf,
  _ as Profile_SharedFiles_NoScreenshotsFavoritesForYou,
  _ as Profile_SharedFiles_NoScreenshotsFavoritesSelf,
  _ as Profile_SharedFiles_NoScreenshotsForYou,
  _ as Profile_SharedFiles_NoScreenshotsSelf,
  _ as Profile_SharedFiles_NoScreenshotsThisVisibility,
  _ as Profile_SharedFiles_NoVideosFavoritesForYou,
  _ as Profile_SharedFiles_NoVideosFavoritesSelf,
  _ as Profile_SharedFiles_NoVideosForYou,
  _ as Profile_SharedFiles_NoVideosSelf,
  _ as Profile_SharedFiles_OldestFirst,
  _ as Profile_SharedFiles_SelectAGame,
  _ as Profile_Videos,
  _ as Profile_Workshop_Items,
  _ as Profile_YourWorkshop,
  _ as Screenshots_AllYourScreenshots,
  _ as Screenshots_AreYouSureDelete,
  _ as Screenshots_AreYouSurePrivacyChange,
  _ as Screenshots_Cancel,
  _ as Screenshots_Continue,
  _ as Screenshots_Delete,
  _ as Screenshots_DeleteScreenshots,
  _ as Screenshots_Done,
  _ as Screenshots_Instructions1,
  _ as Screenshots_Instructions2,
  _ as Screenshots_Location,
  _ as Screenshots_MakeFriendsOnly,
  _ as Screenshots_MakePrivate,
  _ as Screenshots_MakePublic,
  _ as Screenshots_MakeUnlisted,
  _ as Screenshots_Manage,
  _ as Screenshots_NoneSelected,
  _ as Screenshots_OK,
  _ as Screenshots_Oops,
  _ as Screenshots_SelectAll,
  _ as Screenshots_SelectScreenshots,
  _ as Screenshots_SelectScreenshotsToDelete,
  _ as Screenshots_SteamHasThem,
  _ as Screenshots_UpdatePrivacy,
  _ as Screenshots_Upload,
  _ as Screenshots_Viewing,
  _ as Screenshots_VisUpdateFailed,
  _ as Screenshots_VisUpdateFailedMessage,
  _ as Screenshots_YourFriendsOnlyScreenshots,
  _ as Screenshots_YourPrivateScreenshots,
  _ as Screenshots_YourPublicScreenshots,
  _ as Screenshots_YourUnlistedScreenshots,
  _ as SharedFiles_AddSpoilerTag,
  _ as SharedFiles_AdminTags,
  _ as SharedFiles_And_N_More,
  _ as SharedFiles_BrowseGuide_createNewBtnLabel,
  _ as SharedFiles_BrowseGuide_subtitle_nolink,
  _ as SharedFiles_Browse_GuideHome,
  _ as SharedFiles_Browse_MyFiles_Favorites,
  _ as SharedFiles_Browse_MyFiles_Items,
  _ as SharedFiles_Browse_MyFiles_Played,
  _ as SharedFiles_Browse_MyFiles_Sort_Alpha,
  _ as SharedFiles_Browse_MyFiles_Sort_CreationOrder,
  _ as SharedFiles_Browse_MyFiles_Sort_Favorited,
  _ as SharedFiles_Browse_MyFiles_Sort_LastUpdated,
  _ as SharedFiles_Browse_MyFiles_Sort_Subscribed,
  _ as SharedFiles_Browse_MyFiles_Subscriptions,
  _ as SharedFiles_ByAuthor,
  _ as SharedFiles_CreateGuide,
  _ as SharedFiles_DeveloperComments,
  _ as SharedFiles_Dota2_IntegratedGuide,
  _ as SharedFiles_Dota2_IntegratedGuide_Desc,
  _ as SharedFiles_Favorites,
  _ as SharedFiles_Favorites_NowUnsubscribed,
  _ as SharedFiles_Favorites_Subscribed,
  _ as SharedFiles_FilterByGame,
  _ as SharedFiles_Guide_Comments,
  _ as SharedFiles_Guide_Index,
  _ as SharedFiles_Guide_Overview,
  _ as SharedFiles_ItemDownload,
  _ as SharedFiles_ItemEditText_ErrorNoTitle,
  _ as SharedFiles_ItemEditText_Text_Caption,
  _ as SharedFiles_Item_Edit_Link,
  _ as SharedFiles_ManageGuide_AddContributor,
  _ as SharedFiles_ManageGuide_AddSection,
  _ as SharedFiles_ManageGuide_Cancel,
  _ as SharedFiles_ManageGuide_Contents,
  _ as SharedFiles_ManageGuide_Contents_Desc,
  _ as SharedFiles_ManageGuide_Contributors,
  _ as SharedFiles_ManageGuide_Contributors_Desc,
  _ as SharedFiles_ManageGuide_DeleteThisSection,
  _ as SharedFiles_ManageGuide_EditSubSection,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Delete,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Desc,
  _ as SharedFiles_ManageGuide_EditSubSection_Diff_Insert,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Changes,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Edit,
  _ as SharedFiles_ManageGuide_EditSubSection_Tab_Preview,
  _ as SharedFiles_ManageGuide_EditThisSection,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_Layout,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutInline,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutLeft,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_LayoutRight,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_Size,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeFull,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeOriginal,
  _ as SharedFiles_ManageGuide_ImageInsertionOptions_SizeThumb,
  _ as SharedFiles_ManageGuide_Images,
  _ as SharedFiles_ManageGuide_Images_Desc,
  _ as SharedFiles_ManageGuide_InsertImage,
  _ as SharedFiles_ManageGuide_InsertYouTubeVideo,
  _ as SharedFiles_ManageGuide_NoContributors,
  _ as SharedFiles_ManageGuide_NoPreviewImages,
  _ as SharedFiles_ManageGuide_NoSectionTitle,
  _ as SharedFiles_ManageGuide_NoSubSections,
  _ as SharedFiles_ManageGuide_Preview,
  _ as SharedFiles_ManageGuide_PromptYouTubeUrl,
  _ as SharedFiles_ManageGuide_RemoveSectionConfirm,
  _ as SharedFiles_ManageGuide_Required,
  _ as SharedFiles_ManageGuide_Save,
  _ as SharedFiles_ManageGuide_Screenshots,
  _ as SharedFiles_ManageGuide_SubImages,
  _ as SharedFiles_ManageGuide_SubScreenshots,
  _ as SharedFiles_ManageGuide_SubSectionContentChanged,
  _ as SharedFiles_ManageGuide_SubSectionContentChanged_CancelConfirm,
  _ as SharedFiles_ManageGuide_SubSectionContentSaved,
  _ as SharedFiles_ManageGuide_SubSectionContents,
  _ as SharedFiles_ManageGuide_SubSectionTitle,
  _ as SharedFiles_ManageGuide_SubVideos,
  _ as SharedFiles_ManageGuide_Videos,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Full,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Left,
  _ as SharedFiles_ManageGuide_YouTubeInsertionOptions_Right,
  _ as SharedFiles_Media_ViewAppFanArt,
  _ as SharedFiles_Media_ViewAppScreenshots,
  _ as SharedFiles_Media_ViewAppVideos,
  _ as SharedFiles_MustOwnAppToCreateGuide,
  _ as SharedFiles_NoGuides_Desc1,
  _ as SharedFiles_NoGuides_Desc2,
  _ as SharedFiles_NoGuides_Title,
  _ as SharedFiles_OwnerControl_BackGuide,
  _ as SharedFiles_OwnerControl_EditCaption,
  _ as SharedFiles_PublicComments,
  _ as SharedFiles_RemoveSelfTag_Tooltip,
  _ as SharedFiles_RemoveSpoilerTag,
  _ as SharedFiles_SaveSubscribedToCollection_Btn,
  _ as SharedFiles_SaveSubscribedToCollection_Desc,
  _ as SharedFiles_SaveSubscribedToCollection_Existing,
  _ as SharedFiles_SaveSubscribedToCollection_ExistingDesc,
  _ as SharedFiles_SaveSubscribedToCollection_New,
  _ as SharedFiles_SaveSubscribedToCollection_NewDesc,
  _ as SharedFiles_SaveSubscribedToCollection_NoExistingCollections,
  _ as SharedFiles_SaveSubscribedToCollection_Title,
  _ as SharedFiles_SearchedForFileType_IntegratedGuide,
  _ as SharedFiles_SearchedForFileType_WebGuide,
  _ as SharedFiles_SharedFiles_Collections,
  _ as SharedFiles_SharedFiles_Guides,
  _ as SharedFiles_SharedFiles_Items,
  _ as SharedFiles_SpoilerTagInstructions,
  _ as SharedFiles_SpoilerTagsExpire,
  _ as SharedFiles_Stats_TaggedUsers,
  _ as SharedFiles_Stats_TaggedWorkshopItems,
  _ as SharedFiles_Subscription_NowUnsubscribed,
  _ as SharedFiles_Subscription_Subscribed,
  _ as SharedFiles_Subscriptions,
  _ as SharedFiles_Tab_Merchandise,
  _ as SharedFiles_Tags,
  _ as SharedFiles_TagsSearch,
  _ as SharedFiles_UnsubscribeAll_Btn,
  _ as SharedFiles_UnsubscribeAll_Confirm_App_Desc,
  _ as SharedFiles_UnsubscribeAll_Confirm_Desc,
  _ as SharedFiles_UnsubscribeAll_Confirm_Title,
  _ as SharedFiles_UserList_BrowsePaging,
  _ as SharedFiles_UserList_LastUpdated,
  _ as SharedFiles_WaitingForIntegratedGuide,
  _ as SharedFiles_WorkshopItemsTagged,
  _ as Videos_AccessYourYouTubeVideos,
  _ as Videos_AddDone,
  _ as Videos_AddFromYouTube,
  _ as Videos_AddNote2,
  _ as Videos_AddNote4,
  _ as Videos_AddStep1,
  _ as Videos_AddStep2,
  _ as Videos_AddStep2Note,
  _ as Videos_AddStep3,
  _ as Videos_AddStep4,
  _ as Videos_AddVideo,
  _ as Videos_AllYourVideos,
  _ as Videos_AvailCountPlural,
  _ as Videos_AvailCountSingular,
  _ as Videos_Cancel,
  _ as Videos_ChangeAccount,
  _ as Videos_ClickHereToChange,
  _ as Videos_ContinueWithAcct,
  _ as Videos_CurrentlyLinkedMsg,
  _ as Videos_CurrentlyLinkedTo,
  _ as Videos_Desc1,
  _ as Videos_Desc2,
  _ as Videos_Desc3,
  _ as Videos_IssuesAccessing,
  _ as Videos_LinkYouTubeAcct,
  _ as Videos_Manage,
  _ as Videos_NoVideosMsg1,
  _ as Videos_NoVideosMsg2,
  _ as Videos_NowOnSteam,
  _ as Videos_OptionNoneOther,
  _ as Videos_OtherUnlisted,
  _ as Videos_Privacy,
  _ as Videos_Refresh,
  _ as Videos_SelectVideos,
  _ as Videos_ShareDescription,
  _ as Videos_SuccessfullyAddedPlural,
  _ as Videos_SuccessfullyAddedSingular,
  _ as Videos_SuccessfullyLinkedYouTube,
  _ as Videos_UnlinkAcct,
  _ as Videos_UnlinkButton,
  _ as Videos_UnlinkConfirmText,
  _ as Videos_UnlinkToAddAnother,
  _ as Videos_UnlinkYouTubeAcct,
  _ as Videos_YourFriendsOnlyVideos,
  _ as Videos_YourPrivateVideos,
  _ as Videos_YourPublicVideos,
  _ as Videos_YourUnlistedVideos,
  _ as Videos_YoutubeTermsLink_AuthorizedData,
  _ as Videos_YoutubeTermsLink_PrivacyPolicy,
  _ as Videos_YoutubeTermsLink_SecuritySettings,
  _ as Videos_YoutubeTermsLink_TermsOfService,
  _ as Videos_YoutubeTerms_1,
  _ as Videos_YoutubeTerms_2,
  _ as Videos_YoutubeTerms_3,
  _ as Videos_YoutubeTerms_4,
  _ as Workshop_BrowseBy,
  _ as Workshop_BrowsePaging,
  _ as Workshop_DeveloperThreadDesc,
  _ as Workshop_DeveloperThreadDisclaimerText,
  _ as Workshop_HasLinkedItems,
  _ as Workshop_ImageSize,
  _ as Workshop_ItemModalViewCountDetails,
  _ as Workshop_ItemModalViewDetails,
  _ as Workshop_Link_LegalAgreement,
  _ as Workshop_Link_PaymentInfo,
  _ as Workshop_NoItems,
  _ as Workshop_PaymentInfo_NotCreated,
  _ as Workshop_PaymentInfo_Rejected,
  _ as Workshop_SplitsAcceptTheseDesc1,
  _ as Workshop_SplitsAcceptTheseDesc2,
  _ as Workshop_SplitsPercentage,
  _ as Workshop_Subscribe_IntegratedGuide,
  _ as Workshop_ViewYourRevenue,
  _ as Workshop_ViewYourRevenue_desc,
  _ as community_errorpage_title,
  _ as community_title,
  _ as default,
  _ as empty_no_comma_following,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_accessibility,
  _ as footer_cookies,
  _ as footer_geodata_notice,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_privacy_policy,
  _ as footer_refunds,
  _ as footer_ssa,
  _ as moderatedcontent_description,
  _ as moderation_claim_n_reports_on_m_subjects,
  _ as moderation_claim_report_count,
  _ as moderation_claim_report_count_Plural,
  _ as moderation_claim_subject_count,
  _ as moderation_claim_subject_count_Plural,
  _ as moderation_forumpost_summary,
  _ as moderation_forumpost_summary_reports_fragment,
  _ as moderation_forumpost_summary_reports_fragment_Plural,
  _ as moderation_forumpost_summary_subjects_fragment,
  _ as moderation_forumpost_summary_subjects_fragment_Plural,
  _ as profile_error_profilenotfound,
  _ as profile_games_list,
  _ as profile_games_list_error_loadfailed,
  _ as profile_games_list_title,
  _ as profiletabs_communitymessages,
  _ as profiletabs_currentbans,
  _ as profiletabs_moderatedcontent,
  _ as profiletabs_reportedcontent,
  _ as reportedcontent_description,
  _ as reportedcontent_lastupdated,
};
