var _ = `portuguese`,
  _ = `Publicado inicialmente por %1$s:`,
  _ = `{LINK REMOVIDO}`,
  _ = `O URL que estava aqui foi removido pelos nossos filtros. Normalmente, isto acontece para impedir ataques de phishing e malware.`,
  _ = `(Só para a Valve) Clica para revelar o link`,
  _ = `%1$s comentários`,
  _ = `A mostrar %1$s-%2$s de %3$s comentários`,
  _ = `Faz um comentário`,
  _ = `Publicar comentário`,
  _ = `Ajuda com formatação`,
  _ = `Inserir emoticon`,
  _ = `Emoticon - %1$s`,
  _ = `Procurar`,
  _ = `Usados recentemente`,
  _ = `Todos os emoticons`,
  _ = `Nenhum emoticon correspondente.`,
  _ = `Ainda não tens nenhum emoticon.`,
  _ = `Formatação de texto`,
  _ = `Estas tags permitem-te adicionar formatação ao texto dos teus comentários e mensagens, de forma semelhante a HTML.`,
  _ = `Sintaxe`,
  _ = `Exemplo`,
  _ = `Texto a negrito`,
  _ = `Texto sublinhado`,
  _ = `Texto em itálico`,
  _ = `Texto rasurado`,
  _ = `Texto ocultado`,
  _ = `Não interpreta [b]tags[/b] `,
  _ = `Link para site`,
  _ = `Texto citado`,
  _ = `Tipo de letra de largura fixa,
preserva   espaços`,
  _ = `Texto de cabeçalho`,
  _ = `Texto de cabeçalho`,
  _ = `Texto de cabeçalho`,
  _ = `Lista com marcas`,
  _ = `Lista ordenada`,
  _ = `Subscrever o tópico`,
  _ = `Anular subscrição do tópico`,
  _ = `Subscreve um tópico para receberes notificações de comentários sempre que alguém fizer um novo comentário.`,
  _ = `Subscreveste automaticamente este tópico porque está associado ao teu perfil do Steam.`,
  _ = `Ocorreu um problema ao atualizar a tua subscrição. Tenta de novo mais tarde.`,
  _ = `Eliminar`,
  _ = `Ocultar e denunciar este comentário`,
  _ = `Marcar como suspeito`,
  _ = `Remover sinalização de conteúdo impróprio: %1$s`,
  _ = `Não verificado`,
  _ = `Repor`,
  _ = `Precisa de verificação`,
  _ = `Muito improvável`,
  _ = `Improvável`,
  _ = `Possível`,
  _ = `Provável`,
  _ = `Muito provável`,
  _ = `Desconhecido ( %1$s )`,
  _ = `Abrir na ferramenta de moderação`,
  _ = `Denunciaste este comentário`,
  _ = `Bloqueaste este utilizador`,
  _ = `Anular`,
  _ = `ver este comentário`,
  _ = `As tuas permissões de suporte/moderador permitem-te ver isto.`,
  _ = `Este comentário está a aguardar pelo nosso sistema automatizado de verificação de conteúdo. Será oculto temporariamente até que seja confirmado que não possui conteúdo prejudicial (como links para sites que tentam roubar informações).`,
  _ = `Este comentário foi sinalizado automaticamente devido ao seu possível conteúdo prejudicial. Como resultado, o comentário foi ocultado.`,
  _ = `Normalmente não poderias deixar comentários aqui, mas tens privilégios adicionais que te permitem fazê-lo.`,
  _ = `Este comentário foi eliminado.`,
  _ = `O teu comentário é demasiado curto.`,
  _ = `O teu comentário é demasiado longo. Máximo permitido: %1$s caracteres.`,
  _ = `Não tens permissão para publicar um comentário aqui.`,
  _ = `Precisas de ter sessão iniciada para poderes publicar um comentário.`,
  _ = `Precisas de ter este jogo para poderes comentar neste item.`,
  _ = `Precisas de pelo menos uma hora de jogo para poderes publicar um comentário.`,
  _ = `Os comentários estão desativados para este item.`,
  _ = `Ainda não existem comentários.`,
  _ = {
    language: _,
    CommentThread_QuoteBlock_Author: _,
    CommentThread_RemovedLink: _,
    CommentThread_RemovedLink_Tooltip: _,
    CommentThread_RemovedLink_Reveal: _,
    CommentThread_NumberOfComments: _,
    CommentThread_ShowingXToYOfTotal: _,
    CommentThread_AddAComment: _,
    CommentThread_PostComment: _,
    CommentThread_FormattingHelp: _,
    CommentThread_InsertEmoticon: _,
    CommentThread_EmoticonHoverApp: _,
    CommentThread_EmoticonSearch: _,
    CommentThread_EmoticonRecentlyUsed: _,
    CommentThread_EmoticonAll: _,
    CommentThread_EmoticonNoResults: _,
    CommentThread_EmoticonNoneOwned: _,
    CommentThread_FormattingHelpHeader: _,
    Discussions_FormattingHelp_Description: _,
    Discussions_FormattingHelp_ColumnSyntax: _,
    Discussions_FormattingHelp_ColumnExample: _,
    Discussions_FormattingHelp_Bold: _,
    Discussions_FormattingHelp_Underline: _,
    Discussions_FormattingHelp_Italic: _,
    Discussions_FormattingHelp_Strike: _,
    Discussions_FormattingHelp_Spoiler: _,
    Discussions_FormattingHelp_Noparse: _,
    Discussions_FormattingHelp_Link: _,
    Discussions_FormattingHelp_Quote: _,
    Discussions_FormattingHelp_Code: _,
    Discussions_FormattingHelp_H1: _,
    Discussions_FormattingHelp_H2: _,
    Discussions_FormattingHelp_H3: _,
    Discussions_FormattingHelp_List: _,
    Discussions_FormattingHelp_OList: _,
    CommentThread_Subscribe: _,
    CommentThread_Unsubscribe: _,
    CommentThread_SubscribeHint: _,
    CommentThread_SubscribeHintOwnThread: _,
    CommentThread_SubscribeError: _,
    CommentThread_DeleteComment: _,
    CommentThread_HideComment: _,
    CommentThread_MarkSpam: _,
    CommentThread_ClearContentCheck: _,
    BanContentCheckResult_NotScanned: _,
    BanContentCheckResult_Reset: _,
    BanContentCheckResult_NeedsChecking: _,
    BanContentCheckResult_VeryUnlikely: _,
    BanContentCheckResult_Unlikely: _,
    BanContentCheckResult_Possible: _,
    BanContentCheckResult_Likely: _,
    BanContentCheckResult_VeryLikely: _,
    BanContentCheckResult_Unknown: _,
    CommentThread_ModerationTool: _,
    CommentThread_HiddenByUser: _,
    CommentThread_HiddenByBlocked: _,
    CommentThread_HiddenUndo: _,
    CommentThread_HiddenViewComment: _,
    CommentThread_ModeratorViewContent: _,
    CommentThread_NeedsContentCheck: _,
    CommentThread_FailedContentCheck: _,
    CommentThread_PermissionOverride: _,
    CommentThread_Deleted: _,
    CommentThread_PostError_TooShort: _,
    CommentThread_PostError_TooLong: _,
    CommentThread_PostError_NotAllowed: _,
    CommentThread_PostError_NotLoggedIn: _,
    CommentThread_PostError_MustOwnApp: _,
    CommentThread_PostError_LimitedUser: _,
    CommentThread_CommentsDisabled: _,
    CommentThread_NoComments: _,
  };
export {
  _ as BanContentCheckResult_Likely,
  _ as BanContentCheckResult_NeedsChecking,
  _ as BanContentCheckResult_NotScanned,
  _ as BanContentCheckResult_Possible,
  _ as BanContentCheckResult_Reset,
  _ as BanContentCheckResult_Unknown,
  _ as BanContentCheckResult_Unlikely,
  _ as BanContentCheckResult_VeryLikely,
  _ as BanContentCheckResult_VeryUnlikely,
  _ as CommentThread_AddAComment,
  _ as CommentThread_ClearContentCheck,
  _ as CommentThread_CommentsDisabled,
  _ as CommentThread_DeleteComment,
  _ as CommentThread_Deleted,
  _ as CommentThread_EmoticonAll,
  _ as CommentThread_EmoticonHoverApp,
  _ as CommentThread_EmoticonNoResults,
  _ as CommentThread_EmoticonNoneOwned,
  _ as CommentThread_EmoticonRecentlyUsed,
  _ as CommentThread_EmoticonSearch,
  _ as CommentThread_FailedContentCheck,
  _ as CommentThread_FormattingHelp,
  _ as CommentThread_FormattingHelpHeader,
  _ as CommentThread_HiddenByBlocked,
  _ as CommentThread_HiddenByUser,
  _ as CommentThread_HiddenUndo,
  _ as CommentThread_HiddenViewComment,
  _ as CommentThread_HideComment,
  _ as CommentThread_InsertEmoticon,
  _ as CommentThread_MarkSpam,
  _ as CommentThread_ModerationTool,
  _ as CommentThread_ModeratorViewContent,
  _ as CommentThread_NeedsContentCheck,
  _ as CommentThread_NoComments,
  _ as CommentThread_NumberOfComments,
  _ as CommentThread_PermissionOverride,
  _ as CommentThread_PostComment,
  _ as CommentThread_PostError_LimitedUser,
  _ as CommentThread_PostError_MustOwnApp,
  _ as CommentThread_PostError_NotAllowed,
  _ as CommentThread_PostError_NotLoggedIn,
  _ as CommentThread_PostError_TooLong,
  _ as CommentThread_PostError_TooShort,
  _ as CommentThread_QuoteBlock_Author,
  _ as CommentThread_RemovedLink,
  _ as CommentThread_RemovedLink_Reveal,
  _ as CommentThread_RemovedLink_Tooltip,
  _ as CommentThread_ShowingXToYOfTotal,
  _ as CommentThread_Subscribe,
  _ as CommentThread_SubscribeError,
  _ as CommentThread_SubscribeHint,
  _ as CommentThread_SubscribeHintOwnThread,
  _ as CommentThread_Unsubscribe,
  _ as Discussions_FormattingHelp_Bold,
  _ as Discussions_FormattingHelp_Code,
  _ as Discussions_FormattingHelp_ColumnExample,
  _ as Discussions_FormattingHelp_ColumnSyntax,
  _ as Discussions_FormattingHelp_Description,
  _ as Discussions_FormattingHelp_H1,
  _ as Discussions_FormattingHelp_H2,
  _ as Discussions_FormattingHelp_H3,
  _ as Discussions_FormattingHelp_Italic,
  _ as Discussions_FormattingHelp_Link,
  _ as Discussions_FormattingHelp_List,
  _ as Discussions_FormattingHelp_Noparse,
  _ as Discussions_FormattingHelp_OList,
  _ as Discussions_FormattingHelp_Quote,
  _ as Discussions_FormattingHelp_Spoiler,
  _ as Discussions_FormattingHelp_Strike,
  _ as Discussions_FormattingHelp_Underline,
  _ as default,
  _ as language,
};
