var _ = `掲示板への投稿`,
  _ = `総合掲示板`,
  _ = `報告された投稿`,
  _ = `ワークショップ掲示板`,
  _ = `トレーディング`,
  _ = `イベントとお知らせ`,
  _ = `1件の報告`,
  _ = `%1$s件の報告`,
  _ = `1件の案件`,
  _ = `%1$s件の案件`,
  _ = `%2$sに%1$s`,
  _ = `%3$sのトピックに関する%2$sの内%1$s`,
  _ = `1件の報告`,
  _ = `%1$s件の報告`,
  _ = `1件の案件`,
  _ = `%1$s件の案件`,
  _ = `Steamコミュニティ`,
  _ = `Steamコミュニティ :: エラー`,
  _ = `エラー`,
  _ = `不明なエラー`,
  _ = `ゲーム`,
  _ = `Steamコミュニティ :: %1$s :: ゲーム`,
  _ = `検索－Steamコミュニティマーケット`,
  _ = `%1$s－Steamコミュニティマーケット`,
  _ = `マーケットアイテムーSteamコミュニティマーケット`,
  _ = `Steamコミュニティマーケット`,
  _ = `プロフィールが見つかりません`,
  _ = `ユーザーのウィッシュリストの読み込みに失敗しました。`,
  _ = `リクエスト回数が多すぎます。しばらく待ってから、もう一度お試しください。`,
  _ = `読み込み中`,
  _ = `%1$s%完了`,
  _ = `一時停止－%1$s%完了`,
  _ = `%1$s／%2$sダウンロード済み`,
  _ = `実績`,
  _ = `推定残り時間：%1$s`,
  _ = `%1$s／%2$s`,
  _ = `アンインストール中`,
  _ = `アップデート`,
  _ = `アンインストール`,
  _ = `ダウンロード`,
  _ = `一時停止`,
  _ = `再開`,
  _ = `アンインストール中`,
  _ = `キャンセル`,
  _ = `このコンテンツに対するプライバシー設定を表示`,
  _ = `ゲームを検索`,
  _ = `あなたも持っているゲームだけ表示`,
  _ = `プレイ時間`,
  _ = `名前`,
  _ = `実績達成`,
  _ = `合計プレイ時間`,
  _ = `最後にプレイ`,
  _ = `過去2週間`,
  _ = `ゲーム情報＆リンク`,
  _ = `リモートダウンロード`,
  _ = `リモートダウンロード先：%1$s`,
  _ = `リモートダウンロードの状況：%1$s`,
  _ = `お使いのPCにアクセスできません`,
  _ = `Steamクライアントにゲームをリモートダウンロードするには、PCが起動状態でインターネットに接続されていること、およびサインインしていることが必要です。`,
  _ = `FAQを見る`,
  _ = `%1$s%2$s`,
  _ = `詳細を表示`,
  _ = `リモートダウンロード利用不可`,
  _ = `%1$sをアンインストールしますか？今後もゲームライブラリには残りますが、プレイするにはコンテンツを再度ダウンロードする必要があります。`,
  _ = `%1$s | 「%2$s」`,
  _ = `最近プレイしたゲーム：%1$s`,
  _ = `すべてのゲーム：%1$s`,
  _ = `全実績解除：%1$s`,
  _ = `レビュー：%1$s`,
  _ = `フォロー：%1$s`,
  _ = `ウィッシュリスト`,
  _ = `入手可能な実績をすべて獲得しました`,
  _ = `これは、完全クリアしたゲーム、または可能なすべての実績を獲得したゲームを確認できるセクションです。`,
  _ = `%1$s%のプレイヤーがこの実績を達成`,
  _ = `ストアページ`,
  _ = `掲示板`,
  _ = `グループ`,
  _ = `公式Webサイト`,
  _ = `ニュース`,
  _ = `自分の実績`,
  _ = `%1$sの実績`,
  _ = `%1$sのデータ`,
  _ = `%1$sの個人ゲームデータ`,
  _ = `自分のランキング`,
  _ = `%1$sのランキング`,
  _ = `グローバル実績`,
  _ = `グローバルランキング`,
  _ = `ゲームデータ`,
  _ = `ゲームコンテンツ`,
  _ = `ゲームデータ`,
  _ = `ゲームコンテンツ`,
  _ = `ゲームリンク`,
  _ = `自分のスクリーンショット%1$s`,
  _ = `%1$sのスクリーンショット%2$s`,
  _ = `%1$sをプレイしたフレンド`,
  _ = `自分のトレーディングカード%1$s`,
  _ = `自分のレビュー`,
  _ = `%1$sのレビュー`,
  _ = `コミュニティハブ`,
  _ = `自分のメモ`,
  _ = `%1$s時間`,
  _ = `%1$s分`,
  _ = `非公開に設定`,
  _ = `非公開の設定を解除`,
  _ = `このゲームを非公開に設定し、フレンドに表示されないようにします`,
  _ = `©  Valve Corporation. All rights reserved. 商標はすべて米国およびその他の国の各社が所有します。`,
  _ = `このWebサイトで使用されている地域データの一部は%1$sによって提供されています。`,
  _ = `プライバシーポリシー`,
  _ = `法的事項`,
  _ = `Steam利用規約`,
  _ = `返金`,
  _ = `Cookie`,
  _ = `アクセシビリティ`,
  _ = `現在の禁止措置`,
  _ = `コミュニティメッセージ`,
  _ = `報告したコンテンツ`,
  _ = `モデレーションされたコンテンツ`,
  _ = `これらは、Steamのガイドラインに違反したとしてあなたが報告したものです。`,
  _ = `これは、あなたがSteamに投稿したコンテンツの中でモデレーションが行われたものの一覧です。`,
  _ = `最終更新：%1$s`,
  _ = ``,
  _ = {
    Moderation_SubjectTypeName_ForumPost: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    moderation_claim_report_count: _,
    moderation_claim_report_count_Plural: _,
    moderation_claim_subject_count: _,
    moderation_claim_subject_count_Plural: _,
    moderation_claim_n_reports_on_m_subjects: _,
    moderation_forumpost_summary: _,
    moderation_forumpost_summary_reports_fragment: _,
    moderation_forumpost_summary_reports_fragment_Plural: _,
    moderation_forumpost_summary_subjects_fragment: _,
    moderation_forumpost_summary_subjects_fragment_Plural: _,
    community_title: _,
    community_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    profile_games_list: _,
    profile_games_list_title: _,
    Market_Search_Title: _,
    Market_Item_Title: _,
    Market_Item_GenericTitle: _,
    Market_GenericTitle: _,
    profile_error_profilenotfound: _,
    profile_games_list_error_loadfailed: _,
    Error_RateLimited: _,
    Loading: _,
    GamesList_Header_Downloading: _,
    GamesList_Header_Paused: _,
    GamesList_Header_DownloadBytes: _,
    GamesList_Header_Achievements: _,
    GamesList_TimeRemaining: _,
    GamesList_Achievement_Fraction: _,
    GamesList_Uninstalling: _,
    GamesList_Button_UpdateRequired: _,
    GamesList_Button_Uninstall: _,
    GamesList_Button_Download: _,
    GamesList_Button_Pause: _,
    GamesList_Button_Resume: _,
    GamesList_Button_Uninstalling: _,
    GamesList_Button_Cancel: _,
    GamesList_PrivacySettings_Tooltip: _,
    GamesList_Filter_Placeholder: _,
    GamesList_Filter_BothOwned: _,
    GamesList_Sort_HoursPlayed: _,
    GamesList_Sort_Name: _,
    GamesList_Sort_AchievementCompletion: _,
    GamesList_Header_TotalPlayed: _,
    GamesList_Header_LastPlayed: _,
    GamesList_Header_TwoWeeks: _,
    GamesList_MenuLabel_GameInfo: _,
    GamesList_MenuLabel_RemoteDownload: _,
    GamesList_Header_RemoteDownload: _,
    GamesList_Header_RemoteDownloadStatus: _,
    GamesList_RemoteDownload_NoConnection: _,
    GamesList_RemoteDownload_Help: _,
    GamesList_RemoteDownload_ReadTheFAQ: _,
    GamesList_RemoteDownload_Info: _,
    GamesList_RemoteDownload_LearnMore: _,
    GamesList_RemoteDownload_NoRemoteControl: _,
    GamesList_RemoteDownload_UninstallConfirm: _,
    GamesList_Client_Indicator: _,
    GamesList_Tab_RecentlyPlayed: _,
    GamesList_Tab_AllGames: _,
    GamesList_Tab_PerfectGames: _,
    GamesList_Tab_Reviews: _,
    GamesList_Tab_Followed: _,
    GamesList_Tab_Wishlist: _,
    Perfect_Game_Description: _,
    GamesList_PerfectGames_Description: _,
    GamesList_Achievement_Unlock_Percentage: _,
    Community_StorePage: _,
    Community_Forums: _,
    Community_Groups: _,
    Community_OfficialWebsite: _,
    Community_News: _,
    Community_UsersAchievementsFirstPerson: _,
    Community_UsersAchievements: _,
    Community_UsersStats: _,
    Community_GamePersonalData: _,
    Community_UsersLeaderboardsFirstPerson: _,
    Community_UsersLeaderboards: _,
    Community_GlobalAchievements: _,
    Community_GlobalLeaderboards: _,
    Community_GameStats: _,
    Community_GameContent: _,
    Community_GameStatsFirstPerson: _,
    Community_GameContentFirstPerson: _,
    Community_GameLinks: _,
    Community_ScreenshotsMenuItemFirstPerson: _,
    Community_ScreenshotsMenuItemThirdPerson: _,
    Community_FriendsWhoPlayMenuItemFirstPerson: _,
    Community_TradingCardsMenuItemFirstPerson: _,
    Community_ReviewMenuItemFirstPerson: _,
    Community_ReviewMenuItemThirdPerson: _,
    Community_GameHubMenuItem: _,
    Community_GameNotesFirstPerson: _,
    Playtime_Hours: _,
    Playtime_Minutes: _,
    AppPrivacy_MarkAsPrivate: _,
    AppPrivacy_UnmarkAsPrivate: _,
    AppPrivacy_Explanation: _,
    footer_legal_notice: _,
    footer_geodata_notice: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_accessibility: _,
    profiletabs_currentbans: _,
    profiletabs_communitymessages: _,
    profiletabs_reportedcontent: _,
    profiletabs_moderatedcontent: _,
    reportedcontent_description: _,
    moderatedcontent_description: _,
    reportedcontent_lastupdated: _,
    empty_no_comma_following: ``,
  };
export {
  _ as AppPrivacy_Explanation,
  _ as AppPrivacy_MarkAsPrivate,
  _ as AppPrivacy_UnmarkAsPrivate,
  _ as Community_Forums,
  _ as Community_FriendsWhoPlayMenuItemFirstPerson,
  _ as Community_GameContent,
  _ as Community_GameContentFirstPerson,
  _ as Community_GameHubMenuItem,
  _ as Community_GameLinks,
  _ as Community_GameNotesFirstPerson,
  _ as Community_GamePersonalData,
  _ as Community_GameStats,
  _ as Community_GameStatsFirstPerson,
  _ as Community_GlobalAchievements,
  _ as Community_GlobalLeaderboards,
  _ as Community_Groups,
  _ as Community_News,
  _ as Community_OfficialWebsite,
  _ as Community_ReviewMenuItemFirstPerson,
  _ as Community_ReviewMenuItemThirdPerson,
  _ as Community_ScreenshotsMenuItemFirstPerson,
  _ as Community_ScreenshotsMenuItemThirdPerson,
  _ as Community_StorePage,
  _ as Community_TradingCardsMenuItemFirstPerson,
  _ as Community_UsersAchievements,
  _ as Community_UsersAchievementsFirstPerson,
  _ as Community_UsersLeaderboards,
  _ as Community_UsersLeaderboardsFirstPerson,
  _ as Community_UsersStats,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as GamesList_Achievement_Fraction,
  _ as GamesList_Achievement_Unlock_Percentage,
  _ as GamesList_Button_Cancel,
  _ as GamesList_Button_Download,
  _ as GamesList_Button_Pause,
  _ as GamesList_Button_Resume,
  _ as GamesList_Button_Uninstall,
  _ as GamesList_Button_Uninstalling,
  _ as GamesList_Button_UpdateRequired,
  _ as GamesList_Client_Indicator,
  _ as GamesList_Filter_BothOwned,
  _ as GamesList_Filter_Placeholder,
  _ as GamesList_Header_Achievements,
  _ as GamesList_Header_DownloadBytes,
  _ as GamesList_Header_Downloading,
  _ as GamesList_Header_LastPlayed,
  _ as GamesList_Header_Paused,
  _ as GamesList_Header_RemoteDownload,
  _ as GamesList_Header_RemoteDownloadStatus,
  _ as GamesList_Header_TotalPlayed,
  _ as GamesList_Header_TwoWeeks,
  _ as GamesList_MenuLabel_GameInfo,
  _ as GamesList_MenuLabel_RemoteDownload,
  _ as GamesList_PerfectGames_Description,
  _ as GamesList_PrivacySettings_Tooltip,
  _ as GamesList_RemoteDownload_Help,
  _ as GamesList_RemoteDownload_Info,
  _ as GamesList_RemoteDownload_LearnMore,
  _ as GamesList_RemoteDownload_NoConnection,
  _ as GamesList_RemoteDownload_NoRemoteControl,
  _ as GamesList_RemoteDownload_ReadTheFAQ,
  _ as GamesList_RemoteDownload_UninstallConfirm,
  _ as GamesList_Sort_AchievementCompletion,
  _ as GamesList_Sort_HoursPlayed,
  _ as GamesList_Sort_Name,
  _ as GamesList_Tab_AllGames,
  _ as GamesList_Tab_Followed,
  _ as GamesList_Tab_PerfectGames,
  _ as GamesList_Tab_RecentlyPlayed,
  _ as GamesList_Tab_Reviews,
  _ as GamesList_Tab_Wishlist,
  _ as GamesList_TimeRemaining,
  _ as GamesList_Uninstalling,
  _ as Loading,
  _ as Market_GenericTitle,
  _ as Market_Item_GenericTitle,
  _ as Market_Item_Title,
  _ as Market_Search_Title,
  _ as Moderation_SubjectTypeName_ForumPost,
  _ as Perfect_Game_Description,
  _ as Playtime_Hours,
  _ as Playtime_Minutes,
  _ as community_errorpage_title,
  _ as community_title,
  _ as default,
  _ as empty_no_comma_following,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_accessibility,
  _ as footer_cookies,
  _ as footer_geodata_notice,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_privacy_policy,
  _ as footer_refunds,
  _ as footer_ssa,
  _ as moderatedcontent_description,
  _ as moderation_claim_n_reports_on_m_subjects,
  _ as moderation_claim_report_count,
  _ as moderation_claim_report_count_Plural,
  _ as moderation_claim_subject_count,
  _ as moderation_claim_subject_count_Plural,
  _ as moderation_forumpost_summary,
  _ as moderation_forumpost_summary_reports_fragment,
  _ as moderation_forumpost_summary_reports_fragment_Plural,
  _ as moderation_forumpost_summary_subjects_fragment,
  _ as moderation_forumpost_summary_subjects_fragment_Plural,
  _ as profile_error_profilenotfound,
  _ as profile_games_list,
  _ as profile_games_list_error_loadfailed,
  _ as profile_games_list_title,
  _ as profiletabs_communitymessages,
  _ as profiletabs_currentbans,
  _ as profiletabs_moderatedcontent,
  _ as profiletabs_reportedcontent,
  _ as reportedcontent_description,
  _ as reportedcontent_lastupdated,
};
