var _ = `Valve – Confidențial`,
  _ = `Această pagină cu acces restricționat conține informații confidențiale Valve. Pentru a folosi sau a accesa această pagină, trebuie să fi semnat cu Valve un acord de confidențialitate și/sau un acord de licență care acoperă informațiile confidențiale.`,
  _ = `Steamworks este setul de instrumente și servicii dezvoltate de <1>Valve</1> care te ajută să configurezi, gestionezi și operezi jocul tău pe <2>Steam</2>.`,
  _ = `Contactează asistența`,
  _ = `Eroare la încărcarea informațiilor despre prețuri. Te rugăm să încerci din nou în scurt timp.`,
  _ = `Despre prețurile regionale`,
  _ = `Produsele de pe Steam pot fi comercializate folosind %1$s monede diferite și %2$s <1>grupuri regionale</1>. Steam îți pune la dispoziție instrumentele necesare pentru a stabili și gestiona prețurile jocului tău astfel încât să oferi un preț adecvat pentru fiecare piață.`,
  _ = `Reține faptul că deții controlul absolut în ceea ce privește stabilirea prețurilor pentru jocul tău pentru toate monedele și grupurile regionale disponibile.`,
  _ = `Pentru mai multe detalii despre gestionarea prețurilor, te rugăm să consulți %1$s.`,
  _ = `documentația privind stabilirea prețurilor`,
  _ = `Pentru a gestiona prețurile jocului tău, accesează-ți %1$s.`,
  _ = `Accesează panoul de control pentru stabilirea prețurilor`,
  _ = `Pentru a gestiona prețurile jocului tău, accesează-ți panoul de control pentru stabilirea prețurilor.`,
  _ = `Ultima actualizare a conversiilor valutare: %1$s`,
  _ = `Instrumentul de explorare pentru conversia prețurilor`,
  _ = `Acest instrument îți prezintă modul în care funcționează cele trei metode încorporate privind conversia prețurilor și a monedelor:`,
  _ = `%1$s – această metodă are în vedere mai mulți factori pentru fiecare monedă, inclusiv puterea de cumpărare locală, valoarea așteptată a costurilor bunurilor de divertisment și cursul de schimb.`,
  _ = `%1$s – această metodă utilizează date publice despre puterea de cumpărare a clienților dintr-o anumită țară și/sau regiune.`,
  _ = `%1$s – această metodă folosește un simplu curs de schimb valutar de la momentul indicat.`,
  _ = `Moneda de bază`,
  _ = `Prețul de bază`,
  _ = `Metoda de conversie`,
  _ = `Moneda`,
  _ = `Conversie cu multiple variabile`,
  _ = `Conversie bazată doar pe puterea de cumpărare`,
  _ = `Conversie bazată doar pe cursul de schimb`,
  _ = `Prețurile specifice fiecărei regiuni (exprimate toate în USD)`,
  _ = `Regiune`,
  _ = `test`,
  _ = `%1$s (%2$s) – Chestionar privind conținutul`,
  _ = `Chestionar privind conținutul`,
  _ = `%1$s (%2$s) – chestionare privind conținutul`,
  _ = `Chestionare privind conținutul`,
  _ = `Nu există nicio aplicație cu acest ID. Verifică adresa și încearcă din nou.`,
  _ = `Acces refuzat`,
  _ = `Neconectat`,
  _ = `Rezumat`,
  _ = `O listă completă cu testele efectuate în cadrul acestei verificări și rezultatele acestora este disponibilă mai jos.`,
  _ = `Mai jos este un rezumat al testelor individuale și al clasificărilor de compatibilitate rezultate.`,
  _ = `Rezultatele testelor care determină acest titlu ca find jucabil sunt notate mai jos.`,
  _ = `Proprietate`,
  _ = `Valoare`,
  _ = `Descriere`,
  _ = `Iată o previzualizare a modului în care aceste informații vor fi afișate în magazin jucătorilor. Prezentarea din magazin se poate modifica în viitor.`,
  _ = `Rapoarte anterioare`,
  _ = `Rezultatele testării`,
  _ = `Rezultat`,
  _ = `Test`,
  _ = `Comentarii`,
  _ = `Impactul asupra clasificării`,
  _ = `Aprobat`,
  _ = `Respins`,
  _ = `Respins`,
  _ = `---`,
  _ = `Acesta este un raport istoric de la %1$s`,
  _ = `Se afișează raportul publicat în prezent`,
  _ = `Data publicării: %1$s`,
  _ = `Data raportului: %1$s`,
  _ = `Vezi documentația`,
  _ = `Publică aceste rezultate`,
  _ = `Publici rezultatele verificării compatibilității?`,
  _ = `Sigur dorești să publici aceste rezultate? Rezultatele vor fi imediat afișate în magazinul Steam.`,
  _ = `Eroare necunoscută -- Te rugăm să încerci din nou`,
  _ = `Solicitare de testare`,
  _ = `Solicitarea este activă`,
  _ = `Solicitarea a fost închisă`,
  _ = `Vezi detaliile solicitării`,
  _ = `Discută acest raport cu echipa de testare`,
  _ = `Introdu aici întrebările sau comentariile.`,
  _ = `Te rugăm să descrii aici modificările din noua versiunea compilată.`,
  _ = `Dacă versiunea compilată de pe Steam a jocului tău este actualizată pentru a rezolva problemele menționate mai sus, te rugăm să selectezi o ramură și să retrimiți solicitarea pentru verificare.`,
  _ = `Te rugăm să selectezi o ramură și să trimiți jocul pentru reverificarea compatibilității cu Steam Deck, care va include și testarea compatibilității cu Steam Machine.`,
  _ = `Trimite pentru reverificare`,
  _ = `Dacă ai efectuat modificări la versiunea compilată a jocului de la ultima verificare, poți solicita o nouă verificare a compatibilității.`,
  _ = `Te rugăm să descrii mai jos motivul pentru cererea de reverificare. Cele mai des întâlnite motive pentru reverificare includ:`,
  _ = `Ai adus modificări versiunii tale compilate pentru a rezolva problemele semnalate de un test de compatibilitate anterior. Te rugăm să descrii problemele specifice pe care consideri că le-ai rezolvat.`,
  _ = `Ai lansat sau vei lansa o versiune compilată nouă a jocului tău și dorești actualizarea raportului de compatibilitate.`,
  _ = `Solicit o reverificare folosind ramura „%1$s”. Versiunea compilată de pe Steam a jocului a fost actualizată pentru a rezolva problemele raportate.`,
  _ = `Istoricul testării`,
  _ = `Afișare în magazin`,
  _ = `Compatibilitatea hardware: %1$s (%2$s)`,
  _ = `Publicată`,
  _ = `Nepublicată`,
  _ = `Istoric`,
  _ = `Mediul de rulare recomandat`,
  _ = `Aceasta este versiunea jocului tău (conținut/executabile) care va fi livrată clienților și rulată de aceștia în mod implicit pe Steam Deck.`,
  _ = `Formatul de input dorit`,
  _ = `Necesită h264`,
  _ = `Versiunea Proton testată`,
  _ = `ID-ul compilării pentru test`,
  _ = `Depanare pentru RPO`,
  _ = `Depanare pentru FDM`,
  _ = `Activare TSO`,
  _ = `Compatibilitatea jocului tău cu %1$s este „Nedeterminată”, deoarece verificarea pentru %1$s este incompletă`,
  _ = `În prezent, titlul tău nu poate fi jucat pe %1$s`,
  _ = `Jocul tău nu este complet compatibil cu %1$s din cauza unor probleme legate de componenta Proton sau de însuși dispozitivul %1$s. Am consemnat aceste probleme și lucrăm la rezolvarea lor. Între timp, jocul tău nu va porni sau funcționa în mod corespunzător pe %1$s.`,
  _ = `Titlul tău este „Jucabil” pe %1$s`,
  _ = `Titlul tău poate fi jucat pe %1$s, dar necesită acțiuni suplimentare de configurare din partea utilizatorilor pentru a funcționa corespunzător. Poți remedia problemele descrise mai jos și retrimite solicitarea de verificare a compatibilității.`,
  _ = `Jocul tău este „Verificat” pe %1$s!`,
  _ = `Felicitări! Jocul tău oferă o experiență grozavă pe %1$s și va fi prezentat ca atare în magazinul Steam și în bibliotecile Steam ale jucătorilor pe %1$s.`,
  _ = `Dorești să partajezi această realizare cu fanii tăi? Iată un link către o pagină șic pe care o poți folosi: %1$s`,
  _ = `Jocul tău nu a fost testat pe Steam Machine`,
  _ = `Jocul tău nu a fost testat pe Steam Frame`,
  _ = `Din această cauză, titlul tău este clasificat drept jucabil.`,
  _ = `Din această cauză, titlul tău este clasificat drept incompatibil.`,
  _ = `Acest lucru este afișat ca un mesaj informativ pentru clienți.`,
  _ = `Nevalid`,
  _ = `Pornire lansator`,
  _ = `Lansator`,
  _ = `Lansator: controler`,
  _ = `Lansator: text`,
  _ = `Lansator: tastatură`,
  _ = `Avertismente ale dispozitivului`,
  _ = `Pornirea jocului`,
  _ = `Un singur jucător`,
  _ = `Mai mulți jucători locali`,
  _ = `Mai mulți jucători online`,
  _ = `Antitrișare`,
  _ = `Antitrișare`,
  _ = `Antitrișare/mai mulți jucători`,
  _ = `Configurație implicită pentru controler`,
  _ = `Tastatură`,
  _ = `Pictograme pentru controler`,
  _ = `Performanța configurației implicite`,
  _ = `Afișează`,
  _ = `Output video`,
  _ = `Rezoluție nativă`,
  _ = `Lizibilitatea textului`,
  _ = `Audio`,
  _ = `Meniu`,
  _ = `Salvări multiplatformă în cloud`,
  _ = `Un singur jucător offline`,
  _ = `Controler extern (jucătorul principal)`,
  _ = `Controler extern (mai mulți jucători locali)`,
  _ = `Configurarea inițială`,
  _ = `Configurarea inițială a controlerului`,
  _ = `Configurarea inițială (offline)`,
  _ = `Funcționalitatea jocului`,
  _ = `RV`,
  _ = `Notă`,
  _ = `Închidere fără probleme`,
  _ = `Închidere fără probleme (lansator)`,
  _ = `Input simultan de la gamepad și mouse`,
  _ = `Funcționalitate auxiliară: editor de hărți`,
  _ = `Compatibilitate cu limitatorul de cadre`,
  _ = `Ferestre active multiple (auto)`,
  _ = `Ferestre active multiple (manual)`,
  _ = `Software`,
  _ = `Input simultan de la gamepad și mouse`,
  _ = `Input de text`,
  _ = `Input audio`,
  _ = `Revenire din starea de repaus`,
  _ = `Output video redimensionat`,
  _ = `Conținut și linkuri externe`,
  _ = `Retras`,
  _ = `Fontul este compatibil cu toate caracterele`,
  _ = `Afișează setările salvate pe fiecare dispozitiv, nu în cloud`,
  _ = `Configurație implicită pentru controler`,
  _ = `Controler implicit activat`,
  _ = `Salvarea în cloud este activată în mod implicit`,
  _ = `Periferice (tastatură)`,
  _ = `Periferice (cameră web)`,
  _ = `Periferice (chitară USB)`,
  _ = `Compatibilitate cu HDR`,
  _ = `Compatibilitate cu sistemul de operare`,
  _ = `Steam Machine – performanța configurației implicite`,
  _ = `Steam Machine – performanța transmisiunii RV`,
  _ = `Steam Machine – compatibilitate cu transmisiuni RV`,
  _ = `Steam Machine – avertismente ale dispozitivului`,
  _ = `Steam Machine – afișaj`,
  _ = `Steam Machine – audio`,
  _ = `Steam Machine`,
  _ = `Steam OS`,
  _ = `Steam Deck`,
  _ = `Steam Frame (rulare autonomă)`,
  _ = `Te rugăm să soliciți o testare pentru Steam Deck care va iniția testarea pentru o clasificare de compatibilitate de tip „%1$s”.`,
  _ = `Bine ai venit! Aici îți poți trimite jocul pentru verificarea compatibilității cu Steam Frame (rulare autonomă).`,
  _ = `Lista de autoverificare a compatibilității cu Steam Frame (rulare autonomă)`,
  _ = `Mai jos, am enumerat câteva dintre cele mai importante criterii pe care le luăm în considerare în procesul de verificare a compatibilității unui titlu cu Steam Frame. Te rugăm să completezi formularul de mai jos și să ne comunici compilația sau ramura jocului tău pe care dorești să o testăm. Titlul tău va fi inclus în lista de așteptare pentru verificare. După finalizarea verificării, vei primi o notificare prin e-mail care va cuprinde un rezumat al evaluării, iar această pagină va fi actualizată cu informații detaliate despre rezultatele verificării.`,
  _ = `Pentru mai multe informații despre procesul de testare, consultă documentația %1$s.`,
  _ = `documentația cu privire la procesul de verificare a compatibilității cu Steam Frame (rulare autonomă)`,
  _ = `Acestea sunt unele dintre cele mai importante elemente pe care le vom verifica pentru a atribui jocului tău un nivel de compatibilitate. Pentru a începe procesul de verificare a compatibilității cu Steam Frame, te rugăm să răspunzi, cât de corect posibil, la următoarele întrebări.`,
  _ = `Solicitările de testare nu sunt disponibile înainte ca jocul să fie lansat.`,
  _ = `Va oferi titlul tău o experiență grozavă pentru jucători pe Steam Deck? Avem un proces de evaluare în cadrul căruia titlul tău va fi jucat și testat de echipa noastră. Dacă experiența de joc este impecabilă, titlul tău va primi eticheta „Verificat”.`,
  _ = `Bine ai venit! Aici îți poți trimite jocul pentru verificarea compatibilității cu Steam Deck.`,
  _ = `Mai jos, am enumerat câteva dintre cele mai importante criterii pe care le luăm în considerare în procesul de verificare a compatibilității unui titlu cu Steam Deck. Te rugăm să completezi formularul de mai jos și să ne comunici compilația sau ramura jocului tău pe care dorești să o testăm. Titlul tău va fi inclus în lista de așteptare pentru verificare. După finalizarea verificării, vei primi o notificare prin e-mail care va cuprinde un rezumat al evaluării, iar această pagină va fi actualizată cu informații detaliate despre rezultatele verificării.`,
  _ = `Poți să-ți trimiți jocul chiar dacă nu îndeplinește toate criteriile pentru atribuirea etichetei Verificat. Utilizăm aceste informații de autoverificare pentru a prioritiza jocurile pentru verificare, precum și pentru a comunica orice problemă de compatibilitate a jocului tău în cel mai clar mod posibil.`,
  _ = `Pentru mai multe informații despre procesul de testare, consultă %1$s și %2$s.`,
  _ = `documentația cu privire la procesul de verificare a compatibilității cu Steam Deck`,
  _ = `recomandările suplimentare cu privire la dispozitivul Steam Deck`,
  _ = `Lista de autoverificare a compatibilității cu Steam Deck`,
  _ = `Acestea sunt unele dintre cele mai importante elemente pe care le vom verifica pentru a atribui jocului tău un nivel de compatibilitate. Pentru a începe procesul de verificare a compatibilității cu Steam Deck, te rugăm să răspunzi, cât de corect posibil, la următoarele întrebări.`,
  _ = `În acest moment, procesul de evaluare a compatibilității cu Steam Deck este disponibil doar pentru jocuri. Nu există niciun proces de evaluare a compatibilității pentru alte tipuri de aplicații, cum ar fi DLC-urile, instrumentele sau coloanele sonore, cu excepția unor cazuri excepționale.`,
  _ = `Compatibilitate pentru controlere`,
  _ = `Introducere de text`,
  _ = `Afișaj`,
  _ = `Funcționalitate`,
  _ = `Steam Cloud`,
  _ = `Lansator`,
  _ = `Ramură`,
  _ = `Vă rog să utilizați această ramură pentru testare`,
  _ = `Marchează ca fiind gata pentru verificare...`,
  _ = `Compilația ta va fi marcată ca fiind gata pentru verificarea compatibilității cu Steam Deck. Rezultatele îți vor fi trimise prin e-mail în câteva zile.`,
  _ = `Mai jos ne poți lăsa mențiuni care să faciliteze procesul de verificare sau să ne oferi datele de conectare ale unui cont de testare pentru serverele terțe.`,
  _ = `Introdu mențiunile aici`,
  _ = `Solicitare de asistență pentru această verificare`,
  _ = `Pentru mai multe detalii, consultă acest raport de testare pe site-ul de asistență.`,
  _ = `Creează o solicitare de asistență pentru verificarea compatibilității cu Steam Deck`,
  _ = `Atunci când creezi o solicitare de asistență, te rugăm să incluzi întrebări sau comentarii pentru echipa de testare.`,
  _ = `Dacă ai întrebări specifice despre procesul de verificare a compatibilității sau rezultatele pentru jocul tău, te rugăm să le introduci mai jos.`,
  _ = `Te rugăm să reții că, dacă dorești o reverificare a titlului tău, este mai eficient să folosești butonul „TRIMITE PENTRU REVERIFICARE” de mai jos, decât să soliciți acest lucru aici.`,
  _ = `Am o întrebare sau un comentariu cu privire la raportul de compatibilitate cu Steam Deck: `,
  _ = `Da, jocul meu oferă o compatibilitate deplină pentru controlere: toate funcțiile sunt accesibile prin intermediul unui controler, folosind configurația implicită.`,
  _ = `Da, titlul meu afișează indicații pentru controlerul Steam Deck sau Xbox în joc atunci când este vorba despre apăsarea unui buton.`,
  _ = `Jocul meu nu necesită nicio introducere de text sau jocul meu apelează API-urile Steam de introducere de text corespunzătoare, atunci când este necesar.`,
  _ = `Jocul meu nu necesită nicio introducere de text.`,
  _ = `Jocul meu apelează API-urile Steam corespunzătoare pentru tastatură sau introducerea de text din partea jucătorilor atunci când este necesar.`,
  _ = `Jocul meu nu utilizează API-urile Steam atunci când este necesară introducerea de text de către jucători.`,
  _ = `Titlul meu nu are fișiere cu salvări de joc.`,
  _ = `Titlul meu are fișiere cu salvările de joc, dar nu utilizează Steam Cloud pentru acestea.`,
  _ = `Titlul meu utilizează Steam Cloud pentru salvările de joc. Există doar o versiune compilată pentru Windows.`,
  _ = `Titlul meu utilizează Steam Cloud pentru salvările de joc și oferă compatibilitate multiplatformă pentru fișierele cu salvări (de exemplu, Windows/Linux).`,
  _ = `Titlul meu utilizează Steam Cloud pentru salvările de joc, dar nu oferă compatibilitate multiplatformă pentru fișierele cu salvări (de exemplu, Windows/Linux).`,
  _ = `Da, titlul meu poate rula la rezoluția de 1280x800 (preferat) sau de 1280x720.`,
  _ = `Da, caracterul cu cea mai mică dimensiune pe ecran în jocul meu nu are niciodată o înălțime mai mică de 9 pixeli la rezoluția de 1280x800.`,
  _ = `Jocul meu nu prezintă niciun lansator sau lansatorul jocului meu poate fi operat fără probleme prin intermediul unui controler.`,
  _ = `Titlul meu este compatibil cu Steam Cloud pentru salvările de joc sau titlul meu nu are fișiere cu salvări.`,
  _ = `Jocul meu oferă compatibilitate multiplatformă pentru fișierele cu salvări sau jocul meu rulează pe o singură platformă (Linux/Windows).`,
  _ = `Dacă nu este indicat altfel, vom testa versiunea ta compilată pentru Windows utilizând componenta Proton.`,
  _ = `Dacă este posibil, testați versiunea mea compilată pentru Linux în locul celei pentru Windows.`,
  _ = `Jocul meu nu utilizează un lansator sau un instrument extern de configurare.`,
  _ = `Jocul meu utilizează un lansator care oferă o compatibilitate deplină pentru controlere.`,
  _ = `Jocul meu utilizează un lansator care nu este pe de plin funcțional dacă utilizatorul are numai un controler, fără tastatură sau mouse.`,
  _ = `(Deși compatibilitatea multiplatformă pentru fișierele cu salvări nu este o cerință pentru a primi eticheta „Verificat”, aceasta este foarte importantă pentru clienții care pot juca uneori titlul pe un PC cu Windows și alteori pe un dispozitiv Steam Deck care rulează o versiune Linux nativă. Te rugăm să consulți %1$s.)`,
  _ = `documentația`,
  _ = `(Ecranul dispozitivului Steam Deck este mult mai mic decât majoritatea ecranelor de calculator. Dacă jocul tău are text de dimensiuni mici, acesta poate fi dificil sau imposibil de citit de către clienți pe ecranul dispozitivului Steam Deck, chiar dacă textul poate fi citit confortabil pe un monitor normal.)`,
  _ = `(Majoritatea dispozitivelor Steam Deck nu au atașată o tastatură. Ca urmare, clienții se bazează pe tastatura virtuală pentru introducerea de text, iar Steam oferă API-uri pentru a facilita utilizarea tastaturilor virtuale integrate. Dacă este nevoie ca utilizatorii să deschidă manual tastatura, jocul tău nu va primi eticheta de „Verificat”. Te rugăm să consulți %1$s.)`,
  _ = `recomandările cu privire la input`,
  _ = `(Dacă jocul tău utilizează un lansator, acesta va trebui să îndeplinească aceleași condiții pentru a primi eticheta „Verificat” ca jocul însuși: trebuie să fie pe deplin funcțional cu comenzile încorporate ale dispozitivului Steam Deck, conținutul să fie lizibil etc. Dacă lansatorul nu îndeplinește aceste cerințe, titlul tău nu poate fi considerat „Verificat”, chiar dacă jocul propriu-zis ar îndeplini aceste condiții. Te rugăm să consulți %1$s.)`,
  _ = `recomandările cu privire la lansator`,
  _ = `(O mare parte dintre clienții care utilizează Steam Deck folosesc în egală măsură și un calculator de tip desktop. Posibilitatea de salvare în cloud nu este obligatorie pentru a primi eticheta „Verificat”, dar este importantă pentru clienți: integrarea compatibilității pentru salvări în %1$s le va permite clienților să salveze jocul pe desktop și să-l continue pe Steam Deck sau invers.)`,
  _ = `Steam Cloud`,
  _ = `(Notă: pentru a primi eticheta „Verificat” este necesară compatibilitatea deplină cu controlere.)`,
  _ = `Jocul tău a fost adăugat în lista noastră de așteptare pentru verificare.`,
  _ = `Vom verifica în curând titlul tău și te vom anunța dacă există probleme.`,
  _ = `Te rugăm să-ți finalizezi verificarea compilării pentru Steam înainte de a o trimite pentru evaluarea compatibilității cu hardware-ul.`,
  _ = `În prezent, titlul tău nu poate fi jucat pe Steam Deck`,
  _ = `Jocul tău nu este complet compatibil cu Steam Deck din cauza unor probleme legate de componenta Proton sau de însuși dispozitivul Steam Deck. Am consemnat aceste probleme și lucrăm la rezolvarea lor. Între timp, jocul tău nu va porni sau funcționa în mod corespunzător pe Steam Deck.`,
  _ = `Titlul tău este „Jucabil” pe Steam Deck`,
  _ = `Titlul tău poate fi jucat pe Steam Deck, dar necesită acțiuni suplimentare de configurare din partea utilizatorilor pentru a funcționa corespunzător. Poți remedia problemele descrise mai jos și retrimite solicitarea de verificare a compatibilității cu Steam Deck.`,
  _ = `Compilare`,
  _ = `Dacă este posibil, testați versiunea mea compilată pentru Android în locul celei pentru Windows.`,
  _ = `Testați versiunea mea compilată pentru Windows`,
  _ = `Testați versiunea mea compilată pentru Linux`,
  _ = `Ar trebui să testăm experiența 2D sau RV (dacă este disponibilă)?`,
  _ = `2D`,
  _ = `RV`,
  _ = `Nu este valabil pentru titlurile %1$s`,
  _ = `Verificat, fără a fi fost utilizată opțiunea „Șterge starea evaluării de performanță”`,
  _ = `Verificat, cu minim o utilizare a opțiunii „Șterge starea evaluării de performanță”`,
  _ = `Jucabil, fără a fi fost utilizată opțiunea „Șterge starea evaluării de performanță”`,
  _ = `Jucabil, cu minim o utilizare a opțiunii „Șterge starea evaluării de performanță”`,
  _ = `Unsupported (incompatibil)`,
  _ = `Nu e un titlu RV (evaluarea nu se aplică)`,
  _ = `Interfața de evaluare a performanței`,
  _ = `Utilizează interfața de evaluare a performanței pentru a completa răspunsul de mai jos. Consultă %1$s pentru mai multe informații.`,
  _ = `documentația privind performanța din RV`,
  _ = `(Dacă jocul tău are text de dimensiuni mici, acesta poate fi dificil sau imposibil de citit de către clienți pe ecranele Steam Frame, chiar dacă textul poate fi citit confortabil pe un monitor normal.)`,
  _ = `(Majoritatea căștilor Steam Frame nu au atașată o tastatură. Ca urmare, clienții se bazează pe tastatura virtuală pentru introducerea de text, iar Steam oferă API-uri pentru a facilita utilizarea tastaturilor virtuale integrate. Dacă este nevoie ca utilizatorii să deschidă manual tastatura, jocul tău nu va primi eticheta de „Verificat”. Te rugăm să consulți %1$s.)`,
  _ = `lista cu cerințele de compatibilitate pentru Steam Frame`,
  _ = `(Dacă jocul tău utilizează un lansator, acesta va trebui să îndeplinească aceleași condiții pentru a primi eticheta „Verificat” ca jocul însuși: trebuie să fie pe deplin funcțional cu comenzile încorporate ale căștii Steam Frame, conținutul să fie lizibil etc. Dacă lansatorul nu îndeplinește aceste cerințe, titlul tău nu poate fi considerat „Verificat”, chiar dacă jocul propriu-zis ar îndeplini aceste condiții. Te rugăm să consulți %1$s.)`,
  _ = `(O mare parte dintre clienții care utilizează Steam Frame folosesc în egală măsură și un calculator de tip desktop. Posibilitatea de salvare în cloud nu este obligatorie pentru a primi eticheta „Verificat”, dar este importantă pentru clienți: integrarea compatibilității pentru salvări în %1$s le va permite clienților să salveze jocul pe desktop și să-l continue pe Steam Frame sau invers.)`,
  _ = `(Deși compatibilitatea multiplatformă pentru fișierele cu salvări nu este o cerință pentru a primi eticheta „Verificat”, aceasta este foarte importantă pentru clienții care pot juca uneori titlul pe un PC cu Windows și alteori pe o cască Steam Frame care rulează o versiune Linux nativă. Te rugăm să consulți %1$s.)`,
  _ = `Da, titlul meu afișează indicații pentru controlerele Steam Frame/Deck sau Xbox în joc atunci când este vorba despre apăsarea unui buton.`,
  _ = `Dacă rezultatul de mai sus pentru evaluarea performanței a necesitat cel puțin o utilizare a opțiunii „Șterge starea evaluării de performanță”, te rugăm să selectezi unul sau mai multe din motivele de mai jos.`,
  _ = `Performanța este redusă la pornirea jocului`,
  _ = `Performanța este redusă pe durata ecranelor de încărcare`,
  _ = `Altul (te rugăm să specifici)`,
  _ = `Soliciți verificarea unei versiuni pentru Android, dar %1$s nu are niciun depozit Android.`,
  _ = `pachetul tău cu acces pentru dezvoltatori`,
  _ = `dummy`,
  _ = {
    Valve_Confidential: _,
    Valve_Confidential_Description: _,
    Footer_Description: _,
    Footer_Sitemap_ContactSupport: _,
    PricingExplorer_LoadError: _,
    PricingExplorer_About_Title: _,
    PricingExplorer_About_Desc1: _,
    PricingExplorer_About_Desc2: _,
    PricingExplorer_About_Link1: _,
    PricingExplorer_About_LinkName1: _,
    PricingExplorer_About_Link2: _,
    PricingExplorer_About_LinkName2: _,
    PricingExplorer_About_Dash: _,
    PricingExplorer_About_LastUpdated: _,
    PricingExplorer_Explore_title: _,
    PricingExplorer_Explore_desc1: _,
    PricingExplorer_Explore_line1: _,
    PricingExplorer_Explore_line2: _,
    PricingExplorer_Explore_line3: _,
    PricingExplorer_Base: _,
    PricingExplorer_BasePrice: _,
    PricingExplorer_TableHeader: _,
    PricingExplorer_Column1: _,
    PricingExplorer_Column2: _,
    PricingExplorer_Column3: _,
    PricingExplorer_Column4: _,
    PricingExplorer_Regions_TableHeader: _,
    PricingExplorer_Regions_Column1: _,
    Pricing_Dummy: _,
    ContentSurvey_Title: _,
    ContentSurvey_Title_Default: _,
    ContentSurvey_History_Title: _,
    ContentSurvey_History_Title_Default: _,
    ContentSurvey_InvalidApp: _,
    PartnerSite_PermissionDenied: _,
    PartnerSite_NotLoggedIn: _,
    SteamDeck_BuildReview_Status_Raw_Title: _,
    SteamDeck_BuildReview_Status_Raw_Description: _,
    SteamDeck_BuildReview_Status_TestProperties_Description: _,
    SteamDeck_BuildReview_Status_TestProperties_Playable: _,
    SteamDeck_BuildReview_Status_TestProperty_Name: _,
    SteamDeck_BuildReview_Status_TestProperty_Value: _,
    SteamDeck_BuildReview_Status_TestProperty_Desc: _,
    SteamDeck_BuildReview_Status_Description: _,
    SteamDeck_BuildReview_Header_History: _,
    SteamDeck_BuildReview_Header_Results: _,
    SteamDeck_BuildReview_Status_Raw_Result: _,
    SteamDeck_BuildReview_Status_Raw_Test: _,
    SteamDeck_BuildReview_Status_Raw_Comment: _,
    SteamDeck_BuildReview_Status_Raw_Impact: _,
    SteamDeck_BuildReview_Status_Pass: _,
    SteamDeck_BuildReview_Status_Fail: _,
    SteamDeck_BuildReview_Status_FailMinor: _,
    SteamDeck_BuildReview_Status_NotApplicable: `---`,
    SteamDeck_BuildReview_Viewing_Historical: _,
    SteamDeck_BuildReview_Viewing_Published: _,
    SteamDeck_BuildReview_PublishedOn: _,
    SteamDeck_BuildReview_ReportedOn: _,
    SteamDeck_BuildReview_Documentation: _,
    SteamDeck_BuildReview_PublishResults: _,
    SteamDeck_BuildReview_PublishDialog_Title: _,
    SteamDeck_BuildReview_PublishDialog_Body: _,
    SteamDeck_BuildReview_UnknownError: _,
    SteamDeck_BuildReview_Help_Request_Title: _,
    SteamDeck_BuildReview_RequestStatusActive: _,
    SteamDeck_BuildReview_RequestStatusClosed: _,
    SteamDeck_BuildReview_InReview_ViewTicket: _,
    SteamDeck_BuildReview_Create_HelpRequest: _,
    SteamDeck_BuildReview_Create_HelpRequest_NotesDefault: _,
    SteamDeck_BuildReview_Create_HelpRequest_NotesDefault_Rereview: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label_Machine: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Button: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_1: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2a: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2b: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Ticket_Content: _,
    SteamDeck_BuildReview_CompatibilityTests: _,
    SteamDeck_BuildReview_Status_Title: _,
    SteamDeck_HardwareCompatibility_Title: _,
    SteamDeck_AppLanding_Published: _,
    SteamDeck_AppLanding_Unpublished: _,
    SteamDeck_AppLanding_History: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RecommendedRuntime: _,
    SteamDeckVerified_TestDisplayName_TestPropertyDescription_RecommendedRuntime:
      _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_ExpectedInput: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RequiresH264: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TestedProtonVersion: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TestedBuildID: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RPODebug: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_FDMDebug: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TSOEnable: _,
    SteamHardware_BuildReview_Unknown_Title: _,
    SteamHardware_BuildReview_Unsupported_Title: _,
    SteamHardware_BuildReview_Unsupported_Description: _,
    SteamHardware_BuildReview_Playable_Title: _,
    SteamHardware_BuildReview_Playable_Description: _,
    SteamHardware_BuildReview_Verified_Title: _,
    SteamHardware_BuildReview_Verified_Description: _,
    SteamHardware_BuildReview_Verified_Share: _,
    SteamHardware_Machine_Unknown: _,
    SteamHardware_Frame_Unknown: _,
    SteamHardware_RatingImpact_Playable: _,
    SteamHardware_RatingImpact_Unsupported: _,
    SteamHardware_RatingImpact_Informational: _,
    SteamDeckVerified_TestDisplayName_0: _,
    SteamDeckVerified_TestDisplayName_1: _,
    SteamDeckVerified_TestDisplayName_2: _,
    SteamDeckVerified_TestDisplayName_3: _,
    SteamDeckVerified_TestDisplayName_4: _,
    SteamDeckVerified_TestDisplayName_5: _,
    SteamDeckVerified_TestDisplayName_6: _,
    SteamDeckVerified_TestDisplayName_7: _,
    SteamDeckVerified_TestDisplayName_8: _,
    SteamDeckVerified_TestDisplayName_9: _,
    SteamDeckVerified_TestDisplayName_10: _,
    SteamDeckVerified_TestDisplayName_11: _,
    SteamDeckVerified_TestDisplayName_12: _,
    SteamDeckVerified_TestDisplayName_13: _,
    SteamDeckVerified_TestDisplayName_14: _,
    SteamDeckVerified_TestDisplayName_15: _,
    SteamDeckVerified_TestDisplayName_16: _,
    SteamDeckVerified_TestDisplayName_17: _,
    SteamDeckVerified_TestDisplayName_18: _,
    SteamDeckVerified_TestDisplayName_19: _,
    SteamDeckVerified_TestDisplayName_20: _,
    SteamDeckVerified_TestDisplayName_21: _,
    SteamDeckVerified_TestDisplayName_22: _,
    SteamDeckVerified_TestDisplayName_23: _,
    SteamDeckVerified_TestDisplayName_24: _,
    SteamDeckVerified_TestDisplayName_25: _,
    SteamDeckVerified_TestDisplayName_26: _,
    SteamDeckVerified_TestDisplayName_27: _,
    SteamDeckVerified_TestDisplayName_29: _,
    SteamDeckVerified_TestDisplayName_30: _,
    SteamDeckVerified_TestDisplayName_31: _,
    SteamDeckVerified_TestDisplayName_32: _,
    SteamDeckVerified_TestDisplayName_33: `RV`,
    SteamDeckVerified_TestDisplayName_34: _,
    SteamDeckVerified_TestDisplayName_35: _,
    SteamDeckVerified_TestDisplayName_36: _,
    SteamDeckVerified_TestDisplayName_37: _,
    SteamDeckVerified_TestDisplayName_38: _,
    SteamDeckVerified_TestDisplayName_39: _,
    SteamDeckVerified_TestDisplayName_40: _,
    SteamDeckVerified_TestDisplayName_41: _,
    SteamDeckVerified_TestDisplayName_42: _,
    SteamDeckVerified_TestDisplayName_43: _,
    SteamDeckVerified_TestDisplayName_44: _,
    SteamDeckVerified_TestDisplayName_45: _,
    SteamDeckVerified_TestDisplayName_46: _,
    SteamDeckVerified_TestDisplayName_47: _,
    SteamDeckVerified_TestDisplayName_48: _,
    SteamDeckVerified_TestDisplayName_49: _,
    SteamDeckVerified_TestDisplayName_50: _,
    SteamDeckVerified_TestDisplayName_51: _,
    SteamDeckVerified_TestDisplayName_52: _,
    SteamDeckVerified_TestDisplayName_53: _,
    SteamDeckVerified_TestDisplayName_54: _,
    SteamDeckVerified_TestDisplayName_55: _,
    SteamDeckVerified_TestDisplayName_56: _,
    SteamDeckVerified_TestDisplayName_57: _,
    SteamDeckVerified_TestDisplayName_58: _,
    SteamDeckVerified_TestDisplayName_59: _,
    SteamDeckVerified_TestDisplayName_60: _,
    SteamDeckVerified_TestDisplayName_61: _,
    SteamDeckVerified_TestDisplayName_62: _,
    SteamDeckVerified_TestDisplayName_63: _,
    SteamDeckVerified_TestDisplayName_64: _,
    SteamDeckVerified_TestDisplayName_65: _,
    Compatibility_Tab_Steam_Machine: _,
    Compatibility_Tab_Steam_OS: _,
    Compatibility_Tab_Steam_Deck: _,
    Compatibility_Tab_Steam_Frame: _,
    SteamDeck_BuildReview_PleaseRequestTest: _,
    SteamFrame_BuildReview_Checklist_Intro_Header_V2: _,
    SteamFrame_BuildReview_PleaseConfirm_Title_V2: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P1: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P3: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P3_ReviewProcess: _,
    SteamFrame_BuildReview_PleaseConfirm_Description_V2: _,
    SteamDeck_TestRequest_BuildNotReleased: _,
    SteamDeck_BuildReview_Checklist_Intro: _,
    SteamDeck_BuildReview_Checklist_Intro_Header_V2: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P1: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P2: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3_ReviewProcess: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3_Additional: _,
    SteamDeck_BuildReview_PleaseConfirm_Title_V2: _,
    SteamDeck_BuildReview_PleaseConfirm_Description_V2: _,
    SteamDeck_BuildReview_AppTypeUnavailable: _,
    SteamDeck_BuildReview_Checklist_Input: _,
    SteamDeck_BuildReview_Checklist_Text: _,
    SteamDeck_BuildReview_Checklist_Display: _,
    SteamDeck_BuildReview_Checklist_Functionality: _,
    SteamDeck_BuildReview_Checklist_SteamCloud: _,
    SteamDeck_BuildReview_Checklist_Launcher: _,
    SteamDeck_BuildReview_Checklist_Branch: _,
    SteamDeck_BuildReview_Checklist_Branch_PleaseTest: _,
    SteamDeck_BuildReview_MarkReady_Button: _,
    SteamDeck_BuildReview_MarkReady_Description: _,
    SteamDeck_BuildReview_MarkReady_Notes: _,
    SteamDeck_BuildReview_MarkReady_NotesDefault: _,
    SteamDeck_BuildReview_HelpRequest_Link: _,
    SteamDeck_BuildReview_ViewMoreDetailsInHelp: _,
    SteamDeck_BuildReview_Create_HelpRequest_Title: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes_1: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes_2: _,
    SteamDeck_BuildReview_Create_HelpRequest_SupportTicketIntro: _,
    SteamDeck_BuildReview_Check_Controller: _,
    SteamDeck_BuildReview_Check_Icons: _,
    SteamDeck_BuildReview_Check_TextInput: _,
    SteamDeck_BuildReview_Check_TextInput_V2_NoTextEntry: _,
    SteamDeck_BuildReview_Check_TextInput_V2_YesSteamAPIs: _,
    SteamDeck_BuildReview_Check_TextInput_V2_NoSteamAPIs: _,
    SteamDeck_BuildReview_Check_Cloud_NoSaves: _,
    SteamDeck_BuildReview_Check_Cloud_YesSavesNoCloud: _,
    SteamDeck_BuildReview_Check_Cloud_SinglePlatform: _,
    SteamDeck_BuildReview_Check_Cloud_YesCrossSaves: _,
    SteamDeck_BuildReview_Check_Cloud_NoCrossSaves: _,
    SteamDeck_BuildReview_Check_Display1280: _,
    SteamDeck_BuildReview_Check_DisplayFont: _,
    SteamDeck_BuildReview_Check_FunctionalityLauncher: _,
    SteamDeck_BuildReview_Check_FunctionalityCloudSaves: _,
    SteamDeck_BuildReview_Check_FunctionalityCrossPlatformCloudSaves: _,
    SteamDeck_BuildReview_Check_TestLinuxBuild_Preamble: _,
    SteamDeck_BuildReview_Check_TestLinuxBuild: _,
    SteamDeck_BuildReview_Check_Launcher_V2_NoLauncher: _,
    SteamDeck_BuildReview_Check_Launcher_V2_ControllerSupport: _,
    SteamDeck_BuildReview_Check_Launcher_V2_NoControllerSupport: _,
    SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves: _,
    SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves_Documentation: _,
    SteamDeck_BuildReview_CheckNote_DisplayFont: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_InputRecommendations:
      _,
    SteamDeck_BuildReview_CheckNote_Launcher_V2_NoControllerSupport: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_LauncherRecommendations:
      _,
    SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud: _,
    SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud_SteamCloud: _,
    SteamDeck_BuildReview_CheckNote_FullController: _,
    SteamDeck_BuildReview_InReview_Title: _,
    SteamDeck_BuildReview_InReview_Description: _,
    SteamDeck_BuildReview_PleaseComplete: _,
    SteamDeck_BuildReview_Unsupported_Title: _,
    SteamDeck_BuildReview_Unsupported_Description: _,
    SteamDeck_BuildReview_NotMeetRequirements_Title: _,
    SteamDeck_BuildReview_NotMeetRequirements_Description: _,
    SteamFrame_BuildReview_Checklist_Build: _,
    SteamFrame_BuildReview_Build_Android: _,
    SteamFrame_BuildReview_Build_Windows: _,
    SteamFrame_BuildReview_Build_Linux: _,
    SteamFrame_BuildReview_Checklist_Dimension: _,
    SteamFrame_BuildReview_Dimension_2D: `2D`,
    SteamFrame_BuildReview_Dimension_VR: `RV`,
    SteamFrame_NotApplicableForDimension: _,
    SteamFrame_BuildReview_Check_VRPerformance_Verified_Without: _,
    SteamFrame_BuildReview_Check_VRPerformance_Verified_With: _,
    SteamFrame_BuildReview_Check_VRPerformance_Playable_Without: _,
    SteamFrame_BuildReview_Check_VRPerformance_Playable_With: _,
    SteamFrame_BuildReview_Check_VRPerformance_Unsupported: _,
    SteamFrame_BuildReview_Check_VRPerformance_NotApplicable: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_Title: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_Description: _,
    SteamFrame_BuildReview_VRPerformanceLink: _,
    SteamFrame_BuildReview_CheckNote_DisplayFont: _,
    SteamFrame_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs: _,
    SteamFrame_BuildReview_Compatibility_Checklist: _,
    SteamFrame_BuildReview_CheckNote_Launcher_V2_NoControllerSupport: _,
    SteamFrame_BuildReview_CheckNote_Cloud_YesSavesNoCloud: _,
    SteamFrame_BuildReview_CheckNote_Cloud_NoCrossSaves: _,
    SteamFrame_BuildReview_Check_Icons: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_StatusReason: _,
    SteamFrame_BuildReview_Check_VRPerformance_Startup: _,
    SteamFrame_BuildReview_Check_VRPerformance_Loading: _,
    SteamFrame_BuildReview_Check_VRPerformance_Other: _,
    SteamFrame_BuildReview_CheckNote_Missing_Android_License: _,
    SteamFrame_BuildReview_CheckNote_Missing_Android_License_Link: _,
    dummy: _,
  };
export {
  _ as Compatibility_Tab_Steam_Deck,
  _ as Compatibility_Tab_Steam_Frame,
  _ as Compatibility_Tab_Steam_Machine,
  _ as Compatibility_Tab_Steam_OS,
  _ as ContentSurvey_History_Title,
  _ as ContentSurvey_History_Title_Default,
  _ as ContentSurvey_InvalidApp,
  _ as ContentSurvey_Title,
  _ as ContentSurvey_Title_Default,
  _ as Footer_Description,
  _ as Footer_Sitemap_ContactSupport,
  _ as PartnerSite_NotLoggedIn,
  _ as PartnerSite_PermissionDenied,
  _ as PricingExplorer_About_Dash,
  _ as PricingExplorer_About_Desc1,
  _ as PricingExplorer_About_Desc2,
  _ as PricingExplorer_About_LastUpdated,
  _ as PricingExplorer_About_Link1,
  _ as PricingExplorer_About_Link2,
  _ as PricingExplorer_About_LinkName1,
  _ as PricingExplorer_About_LinkName2,
  _ as PricingExplorer_About_Title,
  _ as PricingExplorer_Base,
  _ as PricingExplorer_BasePrice,
  _ as PricingExplorer_Column1,
  _ as PricingExplorer_Column2,
  _ as PricingExplorer_Column3,
  _ as PricingExplorer_Column4,
  _ as PricingExplorer_Explore_desc1,
  _ as PricingExplorer_Explore_line1,
  _ as PricingExplorer_Explore_line2,
  _ as PricingExplorer_Explore_line3,
  _ as PricingExplorer_Explore_title,
  _ as PricingExplorer_LoadError,
  _ as PricingExplorer_Regions_Column1,
  _ as PricingExplorer_Regions_TableHeader,
  _ as PricingExplorer_TableHeader,
  _ as Pricing_Dummy,
  _ as SteamDeckVerified_TestDisplayName_0,
  _ as SteamDeckVerified_TestDisplayName_1,
  _ as SteamDeckVerified_TestDisplayName_10,
  _ as SteamDeckVerified_TestDisplayName_11,
  _ as SteamDeckVerified_TestDisplayName_12,
  _ as SteamDeckVerified_TestDisplayName_13,
  _ as SteamDeckVerified_TestDisplayName_14,
  _ as SteamDeckVerified_TestDisplayName_15,
  _ as SteamDeckVerified_TestDisplayName_16,
  _ as SteamDeckVerified_TestDisplayName_17,
  _ as SteamDeckVerified_TestDisplayName_18,
  _ as SteamDeckVerified_TestDisplayName_19,
  _ as SteamDeckVerified_TestDisplayName_2,
  _ as SteamDeckVerified_TestDisplayName_20,
  _ as SteamDeckVerified_TestDisplayName_21,
  _ as SteamDeckVerified_TestDisplayName_22,
  _ as SteamDeckVerified_TestDisplayName_23,
  _ as SteamDeckVerified_TestDisplayName_24,
  _ as SteamDeckVerified_TestDisplayName_25,
  _ as SteamDeckVerified_TestDisplayName_26,
  _ as SteamDeckVerified_TestDisplayName_27,
  _ as SteamDeckVerified_TestDisplayName_29,
  _ as SteamDeckVerified_TestDisplayName_3,
  _ as SteamDeckVerified_TestDisplayName_30,
  _ as SteamDeckVerified_TestDisplayName_31,
  _ as SteamDeckVerified_TestDisplayName_32,
  _ as SteamDeckVerified_TestDisplayName_33,
  _ as SteamDeckVerified_TestDisplayName_34,
  _ as SteamDeckVerified_TestDisplayName_35,
  _ as SteamDeckVerified_TestDisplayName_36,
  _ as SteamDeckVerified_TestDisplayName_37,
  _ as SteamDeckVerified_TestDisplayName_38,
  _ as SteamDeckVerified_TestDisplayName_39,
  _ as SteamDeckVerified_TestDisplayName_4,
  _ as SteamDeckVerified_TestDisplayName_40,
  _ as SteamDeckVerified_TestDisplayName_41,
  _ as SteamDeckVerified_TestDisplayName_42,
  _ as SteamDeckVerified_TestDisplayName_43,
  _ as SteamDeckVerified_TestDisplayName_44,
  _ as SteamDeckVerified_TestDisplayName_45,
  _ as SteamDeckVerified_TestDisplayName_46,
  _ as SteamDeckVerified_TestDisplayName_47,
  _ as SteamDeckVerified_TestDisplayName_48,
  _ as SteamDeckVerified_TestDisplayName_49,
  _ as SteamDeckVerified_TestDisplayName_5,
  _ as SteamDeckVerified_TestDisplayName_50,
  _ as SteamDeckVerified_TestDisplayName_51,
  _ as SteamDeckVerified_TestDisplayName_52,
  _ as SteamDeckVerified_TestDisplayName_53,
  _ as SteamDeckVerified_TestDisplayName_54,
  _ as SteamDeckVerified_TestDisplayName_55,
  _ as SteamDeckVerified_TestDisplayName_56,
  _ as SteamDeckVerified_TestDisplayName_57,
  _ as SteamDeckVerified_TestDisplayName_58,
  _ as SteamDeckVerified_TestDisplayName_59,
  _ as SteamDeckVerified_TestDisplayName_6,
  _ as SteamDeckVerified_TestDisplayName_60,
  _ as SteamDeckVerified_TestDisplayName_61,
  _ as SteamDeckVerified_TestDisplayName_62,
  _ as SteamDeckVerified_TestDisplayName_63,
  _ as SteamDeckVerified_TestDisplayName_64,
  _ as SteamDeckVerified_TestDisplayName_65,
  _ as SteamDeckVerified_TestDisplayName_7,
  _ as SteamDeckVerified_TestDisplayName_8,
  _ as SteamDeckVerified_TestDisplayName_9,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyDescription_RecommendedRuntime,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_ExpectedInput,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_FDMDebug,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RPODebug,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RecommendedRuntime,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RequiresH264,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TSOEnable,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TestedBuildID,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TestedProtonVersion,
  _ as SteamDeck_AppLanding_History,
  _ as SteamDeck_AppLanding_Published,
  _ as SteamDeck_AppLanding_Unpublished,
  _ as SteamDeck_BuildReview_AppTypeUnavailable,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves_Documentation,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud_SteamCloud,
  _ as SteamDeck_BuildReview_CheckNote_DisplayFont,
  _ as SteamDeck_BuildReview_CheckNote_FullController,
  _ as SteamDeck_BuildReview_CheckNote_Launcher_V2_NoControllerSupport,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_InputRecommendations,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_LauncherRecommendations,
  _ as SteamDeck_BuildReview_Check_Cloud_NoCrossSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_NoSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_SinglePlatform,
  _ as SteamDeck_BuildReview_Check_Cloud_YesCrossSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_YesSavesNoCloud,
  _ as SteamDeck_BuildReview_Check_Controller,
  _ as SteamDeck_BuildReview_Check_Display1280,
  _ as SteamDeck_BuildReview_Check_DisplayFont,
  _ as SteamDeck_BuildReview_Check_FunctionalityCloudSaves,
  _ as SteamDeck_BuildReview_Check_FunctionalityCrossPlatformCloudSaves,
  _ as SteamDeck_BuildReview_Check_FunctionalityLauncher,
  _ as SteamDeck_BuildReview_Check_Icons,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_ControllerSupport,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_NoControllerSupport,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_NoLauncher,
  _ as SteamDeck_BuildReview_Check_TestLinuxBuild,
  _ as SteamDeck_BuildReview_Check_TestLinuxBuild_Preamble,
  _ as SteamDeck_BuildReview_Check_TextInput,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_NoSteamAPIs,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_NoTextEntry,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_YesSteamAPIs,
  _ as SteamDeck_BuildReview_Checklist_Branch,
  _ as SteamDeck_BuildReview_Checklist_Branch_PleaseTest,
  _ as SteamDeck_BuildReview_Checklist_Display,
  _ as SteamDeck_BuildReview_Checklist_Functionality,
  _ as SteamDeck_BuildReview_Checklist_Input,
  _ as SteamDeck_BuildReview_Checklist_Intro,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P1,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P2,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3_Additional,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3_ReviewProcess,
  _ as SteamDeck_BuildReview_Checklist_Intro_Header_V2,
  _ as SteamDeck_BuildReview_Checklist_Launcher,
  _ as SteamDeck_BuildReview_Checklist_SteamCloud,
  _ as SteamDeck_BuildReview_Checklist_Text,
  _ as SteamDeck_BuildReview_CompatibilityTests,
  _ as SteamDeck_BuildReview_Create_HelpRequest,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_1,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2a,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2b,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes,
  _ as SteamDeck_BuildReview_Create_HelpRequest_NotesDefault,
  _ as SteamDeck_BuildReview_Create_HelpRequest_NotesDefault_Rereview,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes_1,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes_2,
  _ as SteamDeck_BuildReview_Create_HelpRequest_SupportTicketIntro,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Title,
  _ as SteamDeck_BuildReview_Documentation,
  _ as SteamDeck_BuildReview_Header_History,
  _ as SteamDeck_BuildReview_Header_Results,
  _ as SteamDeck_BuildReview_HelpRequest_Link,
  _ as SteamDeck_BuildReview_Help_Request_Title,
  _ as SteamDeck_BuildReview_InReview_Description,
  _ as SteamDeck_BuildReview_InReview_Title,
  _ as SteamDeck_BuildReview_InReview_ViewTicket,
  _ as SteamDeck_BuildReview_MarkReady_Button,
  _ as SteamDeck_BuildReview_MarkReady_Description,
  _ as SteamDeck_BuildReview_MarkReady_Notes,
  _ as SteamDeck_BuildReview_MarkReady_NotesDefault,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Description,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Button,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label_Machine,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Ticket_Content,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Title,
  _ as SteamDeck_BuildReview_PleaseComplete,
  _ as SteamDeck_BuildReview_PleaseConfirm_Description_V2,
  _ as SteamDeck_BuildReview_PleaseConfirm_Title_V2,
  _ as SteamDeck_BuildReview_PleaseRequestTest,
  _ as SteamDeck_BuildReview_PublishDialog_Body,
  _ as SteamDeck_BuildReview_PublishDialog_Title,
  _ as SteamDeck_BuildReview_PublishResults,
  _ as SteamDeck_BuildReview_PublishedOn,
  _ as SteamDeck_BuildReview_ReportedOn,
  _ as SteamDeck_BuildReview_RequestStatusActive,
  _ as SteamDeck_BuildReview_RequestStatusClosed,
  _ as SteamDeck_BuildReview_Status_Description,
  _ as SteamDeck_BuildReview_Status_Fail,
  _ as SteamDeck_BuildReview_Status_FailMinor,
  _ as SteamDeck_BuildReview_Status_NotApplicable,
  _ as SteamDeck_BuildReview_Status_Pass,
  _ as SteamDeck_BuildReview_Status_Raw_Comment,
  _ as SteamDeck_BuildReview_Status_Raw_Description,
  _ as SteamDeck_BuildReview_Status_Raw_Impact,
  _ as SteamDeck_BuildReview_Status_Raw_Result,
  _ as SteamDeck_BuildReview_Status_Raw_Test,
  _ as SteamDeck_BuildReview_Status_Raw_Title,
  _ as SteamDeck_BuildReview_Status_TestProperties_Description,
  _ as SteamDeck_BuildReview_Status_TestProperties_Playable,
  _ as SteamDeck_BuildReview_Status_TestProperty_Desc,
  _ as SteamDeck_BuildReview_Status_TestProperty_Name,
  _ as SteamDeck_BuildReview_Status_TestProperty_Value,
  _ as SteamDeck_BuildReview_Status_Title,
  _ as SteamDeck_BuildReview_UnknownError,
  _ as SteamDeck_BuildReview_Unsupported_Description,
  _ as SteamDeck_BuildReview_Unsupported_Title,
  _ as SteamDeck_BuildReview_ViewMoreDetailsInHelp,
  _ as SteamDeck_BuildReview_Viewing_Historical,
  _ as SteamDeck_BuildReview_Viewing_Published,
  _ as SteamDeck_HardwareCompatibility_Title,
  _ as SteamDeck_TestRequest_BuildNotReleased,
  _ as SteamFrame_BuildReview_Build_Android,
  _ as SteamFrame_BuildReview_Build_Linux,
  _ as SteamFrame_BuildReview_Build_Windows,
  _ as SteamFrame_BuildReview_CheckNote_Cloud_NoCrossSaves,
  _ as SteamFrame_BuildReview_CheckNote_Cloud_YesSavesNoCloud,
  _ as SteamFrame_BuildReview_CheckNote_DisplayFont,
  _ as SteamFrame_BuildReview_CheckNote_Launcher_V2_NoControllerSupport,
  _ as SteamFrame_BuildReview_CheckNote_Missing_Android_License,
  _ as SteamFrame_BuildReview_CheckNote_Missing_Android_License_Link,
  _ as SteamFrame_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs,
  _ as SteamFrame_BuildReview_Check_Icons,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Loading,
  _ as SteamFrame_BuildReview_Check_VRPerformance_NotApplicable,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Other,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Playable_With,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Playable_Without,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Startup,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Unsupported,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Verified_With,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Verified_Without,
  _ as SteamFrame_BuildReview_Checklist_Build,
  _ as SteamFrame_BuildReview_Checklist_Dimension,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P1,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P3,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P3_ReviewProcess,
  _ as SteamFrame_BuildReview_Checklist_Intro_Header_V2,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_Description,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_StatusReason,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_Title,
  _ as SteamFrame_BuildReview_Compatibility_Checklist,
  _ as SteamFrame_BuildReview_Dimension_2D,
  _ as SteamFrame_BuildReview_Dimension_VR,
  _ as SteamFrame_BuildReview_PleaseConfirm_Description_V2,
  _ as SteamFrame_BuildReview_PleaseConfirm_Title_V2,
  _ as SteamFrame_BuildReview_VRPerformanceLink,
  _ as SteamFrame_NotApplicableForDimension,
  _ as SteamHardware_BuildReview_Playable_Description,
  _ as SteamHardware_BuildReview_Playable_Title,
  _ as SteamHardware_BuildReview_Unknown_Title,
  _ as SteamHardware_BuildReview_Unsupported_Description,
  _ as SteamHardware_BuildReview_Unsupported_Title,
  _ as SteamHardware_BuildReview_Verified_Description,
  _ as SteamHardware_BuildReview_Verified_Share,
  _ as SteamHardware_BuildReview_Verified_Title,
  _ as SteamHardware_Frame_Unknown,
  _ as SteamHardware_Machine_Unknown,
  _ as SteamHardware_RatingImpact_Informational,
  _ as SteamHardware_RatingImpact_Playable,
  _ as SteamHardware_RatingImpact_Unsupported,
  _ as Valve_Confidential,
  _ as Valve_Confidential_Description,
  _ as default,
  _ as dummy,
};
