var _ = `Valve-konfidentiellt`,
  _ = `Den här sidan har begränsad åtkomst och innehåller Valve-konfidentiell information. Du måste ha ett sekretess- och/eller licensavtal som täcker konfidentiell information med Valve för att använda och komma åt sidan.`,
  _ = `Steamworks består av ett antal verktyg och tjänster framtagna av <1>Valve</1> som hjälper dig att konfigurera, hantera och driva dina spel på <2>Steam</2>.`,
  _ = `Kontakta kundtjänst`,
  _ = `Fel vid inläsning av prisinformation. Försök igen om en stund.`,
  _ = `Regional prissättning`,
  _ = `Priset för varje produkt på Steam anges och visas med %1$s olika valutor och %2$s <1>regionsgrupper</1>. Steam har verktyg som hjälper dig att välja och hantera priset på spelet på lämpliga nivåer för varje marknad.`,
  _ = `Det är upp till dig att välja hur mycket spelet ska kosta i varje valuta och regionsgrupp.`,
  _ = `Läs %1$s för mer information om prishantering.`,
  _ = `Dokumentation om prissättning`,
  _ = `Gå till %1$s om du vill hantera priser.`,
  _ = `Gå till prissättningsinstrumentpanelen`,
  _ = `Gå till prissättningsinstrumentpanelen för att hantera spelets prissättning`,
  _ = `Valutaomvandlingar uppdaterades senast %1$s`,
  _ = `Utforskningsverktyg för prisomvandling`,
  _ = `Det här verktyget visar tre metoder för att omvandla priser och valutor:`,
  _ = `%1$s – den här metoden tar hänsyn till flera faktorer för varje valuta, inklusive lokal köpkraft, den förväntade kostnaden på jämförbara underhållningsprodukter och valutakurs.`,
  _ = `%1$s – den här metoden använder offentliga data om kundernas köpkraft i ett visst land och region.`,
  _ = `%1$s – den här metoden använder en enkel valutakurs vid den angivna tidpunkten.`,
  _ = `Grundvaluta`,
  _ = `Grundpris`,
  _ = `Omvandlingsmetod`,
  _ = `Valuta`,
  _ = `Omvandling med flera variabler`,
  _ = `Endast köpkraftsomvandling`,
  _ = `Endast växelkurs`,
  _ = `Regionspecifika priser (rapporteras i USD)`,
  _ = `Region`,
  _ = `dummy`,
  _ = `%1$s (%2$s) – innehållsundersökning`,
  _ = `Innehållsundersökning`,
  _ = `%1$s (%2$s) – innehållsundersökningar`,
  _ = `Innehållsundersökningar`,
  _ = `Det finns ingen app med detta ID. Kontrollera adressen och försök igen.`,
  _ = `Åtkomst nekad`,
  _ = `Inte inloggad`,
  _ = `Sammanfattning`,
  _ = `En komplett lista med de tester som utfördes under granskningen samt resultatet finns nedan.`,
  _ = `Nedan följer en sammanfattning av enskilda tester och resulterande kompatibilitetsklassificeringar.`,
  _ = `Testresultatet som ger det här spelet klassificeringen Spelbart anges nedan.`,
  _ = `Egenskap`,
  _ = `Värde`,
  _ = `Beskrivning`,
  _ = `Här är en förhandsvisning av hur detta kommer att se ut i butiken för spelare som tittar på ditt spel. Butikspresentationen kan komma att ändras i framtiden.`,
  _ = `Tidigare rapporter`,
  _ = `Testresultat`,
  _ = `Resultat`,
  _ = `Test`,
  _ = `Kommentarer`,
  _ = `Inverkan på klassificeringen`,
  _ = `Godkänd`,
  _ = `Inte godkänd`,
  _ = `Inte godkänd`,
  _ = `---`,
  _ = `Detta är en tidigare rapport från %1$s`,
  _ = `Visar rapporten som är publicerad just nu`,
  _ = `Publicerades: %1$s`,
  _ = `Rapporterades: %1$s`,
  _ = `Se dokumentation`,
  _ = `Publicera dessa resultat`,
  _ = `Vill du publicera kompatibilitetsresultatet?`,
  _ = `Är du säker på att du vill publicera resultatet? Resultatet blir omedelbart synligt i Steam-butiken.`,
  _ = `Okänt fel – försök igen`,
  _ = `Testbegäran`,
  _ = `Begäran är aktiv`,
  _ = `Begäran är stängd`,
  _ = `Visa information om begäran`,
  _ = `Diskutera rapporten med testteamet`,
  _ = `Skriv frågor eller kommentarer här`,
  _ = `Beskriv ändringarna i din nya byggversion här.`,
  _ = `Om spelets byggversion på Steam har uppdaterats för att lösa ovanstående problem, välj då en gren och skicka in byggversionen på nytt så att den kan granskas igen.`,
  _ = `Välj en gren och skicka in spelet på en ny kompatibilitetsgranskning för Steam Deck, vilket inkluderar testning på Steam Machine.`,
  _ = `Skicka in för ny granskning`,
  _ = `Du kan be om en ny kompatibilitetsgranskning om du har gjort ändringar i spelets byggversion sedan föregående granskning.`,
  _ = `Beskriv anledningen till din begäran om omprövning nedan. Vanliga skäl till omprövning:`,
  _ = `Du har gjort ändringar i byggversionen för att åtgärda problem som orsakade att spelet inte klarade en tidigare kompatibilitetsgranskning. Beskriv de specifika problem som du anser har åtgärdats.`,
  _ = `Du har gett ut eller kommer att ge ut en ny version av ditt spel och vill att rapporten ska uppdateras.`,
  _ = `Ber om ett nytt test med grenen %1$s. Spelets byggversion på Steam har uppdaterats för att åtgärda de rapporterade problemen.`,
  _ = `Testhistorik`,
  _ = `Butiksvisning`,
  _ = `Kompatibilitet med maskinvara: %1$s (%2$s)`,
  _ = `Publicerad`,
  _ = `Opublicerad`,
  _ = `Historik`,
  _ = `Rekommenderad körtid`,
  _ = `Det är den här versionen av spelet (innehåll/körbara filer) som levereras till kunder och körs som standard på Steam Deck.`,
  _ = `Förväntat inmatningsformat`,
  _ = `Kräver h264`,
  _ = `Testad Proton-version`,
  _ = `Testversions-ID`,
  _ = `RPO-felsökning`,
  _ = `FDM-felsökning`,
  _ = `Aktivera TSO`,
  _ = `Spelet har fått klassificeringen Inte fastställt på %1$s eftersom testningen av %1$s är ofullständig.`,
  _ = `Spelet kan inte spelas på %1$s just nu.`,
  _ = `Spelet stöds inte fullt ut på %1$s. Det beror på problem med Proton eller själva %1$s. Vi har noterat felen och arbetar mot en lösning. Under tiden kommer spelet inte att kunna startas eller köras ordentligt på Steam %1$s.`,
  _ = `Spelet har fått klassificeringen Spelbart på %1$s.`,
  _ = `Ditt spel är spelbart på %1$s, men lite extra ansträngning från kunder krävs för att kunna interagera med eller konfigurera spelet. Åtgärda de problem som beskrivs nedan och skicka in spelet för en ny kompatibilitetsgranskning.`,
  _ = `Spelet är Verifierat på %1$s!`,
  _ = `Grattis! Ditt spel är en toppenupplevelse på %1$s, och så kommer det att visas i båda Steam-butiken och spelarnas Steam-bibliotek på %1$s.`,
  _ = `Vill du dela den här milstolpen med dina fans? Här är en länk till en snygg startsida som du kan använda: %1$s`,
  _ = `Ditt spel har inte testats på Steam Machine`,
  _ = `Ditt spel har inte testats på Steam Frame`,
  _ = `Detta gör att klassificeringen blir Spelbart.`,
  _ = `Detta gör att klassificeringen blir Stöds inte.`,
  _ = `Detta visas som ett informationsmeddelande till kunder`,
  _ = `Ogiltig`,
  _ = `Startprogram – uppstart`,
  _ = `Startprogram`,
  _ = `Startprogram – handkontroll`,
  _ = `Startprogram – text`,
  _ = `Startprogram – tangentbord`,
  _ = `Enhetsvarningar`,
  _ = `Spelstart`,
  _ = `Singleplayer`,
  _ = `Multiplayer lokalt`,
  _ = `Multiplayer online`,
  _ = `Antifusk`,
  _ = `Antifusk`,
  _ = `Antifusk/flerspelarläge`,
  _ = `Standardkontrollkonfiguration`,
  _ = `Tangentbord`,
  _ = `Kontrollglyfer`,
  _ = `Standardkonfigurationens prestanda`,
  _ = `Skärm`,
  _ = `Videoutmatning`,
  _ = `Standardupplösning`,
  _ = `Textläsbarhet`,
  _ = `Ljud`,
  _ = `Meny`,
  _ = `Plattformsoberoende Cloud-sparning`,
  _ = `Singleplayer offline`,
  _ = `Extern handkontroll (huvudspelare)`,
  _ = `Extern handkontroll (multiplayer lokalt)`,
  _ = `Förstagångskonfiguration`,
  _ = `Förstagångskonfiguration (handkontroll)`,
  _ = `Förstagångskonfiguration (offline)`,
  _ = `Spelfunktionalitet`,
  _ = `VR`,
  _ = `Obs!`,
  _ = `Problemfritt avslut`,
  _ = `Problemfritt avslut (startprogram)`,
  _ = `Samtidig handkontrolls-/musinmatning`,
  _ = `Tilläggsfunktion: banredigerare`,
  _ = `Bildfrekvensgräns stöds`,
  _ = `Fokus med flera fönster (automatiskt)`,
  _ = `Fokus med flera fönster (manuellt)`,
  _ = `Programvara`,
  _ = `Samtidig handkontrolls-/musinmatning`,
  _ = `Textinmatning`,
  _ = `Ljudinmatning`,
  _ = `Återuppta från viloläge`,
  _ = `Skalad skärmutmatning`,
  _ = `Externa länkar/externt innehåll`,
  _ = `Återkallad`,
  _ = `Teckensnitt stöder alla tecken`,
  _ = `Skärminställningar lagras per enhet, inte i molnet`,
  _ = `Standardkontrollkonfiguration`,
  _ = `Standardkontroll aktiverad`,
  _ = `Molnlagring aktiveras som standard`,
  _ = `Kringutrustning (tangentbord)`,
  _ = `Kringutrustning (webbkamera)`,
  _ = `Kringutrustning (usb-gitarr)`,
  _ = `HDR-stöd`,
  _ = `Operativsystemsstöd`,
  _ = `Prestanda för standardkonfiguration (Steam Machine)`,
  _ = `Prestanda för VR-streaming (Steam Machine)`,
  _ = `Stöd för VR-streaming (Steam Machine)`,
  _ = `Enhetsvarningar (Steam Machine)`,
  _ = `Skärm (Steam Machine)`,
  _ = `Ljud (Steam Machine)`,
  _ = `Steam Machine`,
  _ = `SteamOS`,
  _ = `Steam Deck`,
  _ = `Steam Frame Standalone`,
  _ = `Be om ett Steam Deck-test som startar testning för klassificering av kompatibilitet med %1$s.`,
  _ = `Välkommen! Här kan du skicka in din titel för en granskning av kompatibilitet med Steam Frame Standalone.`,
  _ = `Checklista för självgranskning av kompatibilitet med Steam Frame Standalone`,
  _ = `Nedan har vi räknat upp några av de viktigaste kriterierna som vi kontrollerar när vi granskar en titel för Steam Frame-kompatibilitet. Fyll i formuläret nedan och nämn vilken byggversion/gren av spelet som du vill att vi ska testa, så lägger vi till spelet i granskningskön. När granskningen är klar får du ett e-postmeddelande med en sammanfattning, och den här sidan uppdateras med detaljerade testresultat.`,
  _ = `För mer information om testprocessen, gå till %1$s.`,
  _ = `Granskningsprocessen för Steam Frame Standalone-kompatibilitet`,
  _ = `Detta är några av de viktigaste sakerna vi granskar för att ge ditt spel en kompatibilitetsbedömning. Besvara följande frågor efter bästa förmåga för att påbörja granskningsprocessen för kompatibilitet med Steam Frame.`,
  _ = `Testförfrågningar är inte tillgängliga innan spelet har släppts`,
  _ = `Är ditt spel en bra upplevelse på Steam Deck? Ditt spel kommer att spelas och testas av vårt team under granskningsprocessen. Om det är en fin upplevelse för spelare på Steam Deck, får spelet märkningen Verifierat för Deck.`,
  _ = `Välkommen! Här kan du skicka in din titel för granskning av kompatibilitet med Deck.`,
  _ = `Nedan har vi räknat upp några av de viktigaste kriterierna som vi kontrollerar när vi granskar en titel för Steam Deck-kompatibilitet. Fyll i formuläret nedan och berätta för oss vilken byggversion/gren av ditt spel du vill att vi ska testa, så lägger vi till spelet i vår granskningskö. När granskningen är klar får du ett e-postmeddelande med en sammanfattning, och den här sidan kommer att uppdateras med detaljerade testresultat.`,
  _ = `Du kan skicka in din titel även om den inte uppfyller alla kriterier för att tilldelas klassificeringen Verifierat. Vi använder information från självtestet för att prioritera titlar för granskning samt för att kommunicera eventuella kompatibilitetsproblem med spelet på tydligt sätt.`,
  _ = `För mer information om testprocessen, gå till %1$s och %2$s.`,
  _ = `Granskning av kompatibilitet med Steam Deck`,
  _ = `ytterligare rekommendationer för Steam Deck`,
  _ = `Checklista för självgranskning av kompatibilitet med Steam Deck`,
  _ = `Detta är några av de viktigaste sakerna vi granskar för att ge ditt spel en kompatibilitetsbedömning. Besvara följande frågor efter bästa förmåga för att påbörja granskningsprocessen för kompatibilitet med Steam Deck`,
  _ = `Vid denna tidpunkt är granskningen av kompatibilitet med Steam Deck endast tillgänglig för spel. Det finns ingen kompatibilitetsgranskningsprocess för andra applikationstyper såsom DLC, verktyg eller soundtrack, annat än i undantagsfall.`,
  _ = `Kontrollstöd`,
  _ = `Textinmatning`,
  _ = `Skärm`,
  _ = `Funktionalitet`,
  _ = `Steam Cloud`,
  _ = `Startprogram`,
  _ = `Gren`,
  _ = `Testa med denna gren`,
  _ = `Markera som redo för granskning ...`,
  _ = `Detta markerar din byggversion som redo för granskning av kompatibilitet med Steam Deck. Du kommer att få resultaten via e-post om ett par dagar.`,
  _ = `Du kan skriva anteckningar nedan för att hjälpa till att påskynda testningen, eller för att tillhandahålla uppgifter för testkonton till inloggningsservrar från tredje part.`,
  _ = `Skriv anteckningar här`,
  _ = `Hjälpförfrågan för denna granskning`,
  _ = `Mer information om testrapporten finns på hjälpsidan.`,
  _ = `Skapa ett supportärende gällande granskning av kompatibilitet med Steam Deck`,
  _ = `Inkludera frågor eller kommentarer till testteamet när du skapar supportärendet.`,
  _ = `Om du har specifika frågor om processen för kompatibilitetsgranskning eller resultaten för ditt spel så kan du ställa dem nedan.`,
  _ = `Observera att om du vill att ditt spel granskas igen, är det mer effektivt att använda knappen Skicka in för ny granskning än att fråga här.`,
  _ = `Jag har en fråga eller en kommentar gällande rapporten om kompatibilitet med Steam Deck: `,
  _ = `Ja, mitt spel har fullt stöd för handkontroll: alla funktioner är tillgängliga via en handkontroll med standardkonfigurationen`,
  _ = `Ja, mitt spel visar Steam Deck- eller Xbox-handkontrolltips vid hänvisningar till knapptryck på en handkontroll.`,
  _ = `Antingen: mitt spel kräver ingen textinmatning; eller mitt spel anropar relevanta Steam-API:er för textinmatning när så behövs.`,
  _ = `Mitt spel kräver ingen textinmatning.`,
  _ = `Mitt spel anropar lämpligt tangentbords- eller textinmatnings-API när textinmatning krävs från användare.`,
  _ = `Mitt spel använder inte Steam-API:er när textinmatning krävs från användare.`,
  _ = `Mitt spel använder inte sparade spelfiler.`,
  _ = `Mitt spel använder sparade spelfiler, men använder inte Steam Cloud för lagring.`,
  _ = `Mitt spel använder Steam Cloud för att spara spelfiler; det finns bara en byggversion för Windows.`,
  _ = `Mitt spel använder Steam Cloud för att spara spelfiler och har stöd för plattformsoberoende spelfiler (dvs. Windows/Linux).`,
  _ = `Mitt spel använder Steam Cloud för att spara spelfiler men har inte stöd för plattformsoberoende spelfiler (dvs. Windows/Linux).`,
  _ = `Ja, mitt spel kan köras på upplösning 1280x800 (föredras) eller 1280x720.`,
  _ = `Ja, minsta teckensnitt på skärmen i mitt spel är aldrig under 9 pixlar i höjd (på 1280x800).`,
  _ = `Antingen: mitt spel har inget startprogram; eller mitt spels startprogram kan styras helt via en handkontroll.`,
  _ = `Antingen: mitt spel har stöd för Steam Cloud för att spara spel; eller mitt spel har inga sparfiler.`,
  _ = `Antingen: mitt spel har stöd för plattformsoberoende sparfiler; eller mitt spel kan enbart köras på en enda plattform (Linux/Windows).`,
  _ = `Om inget annat anges testar vi din Windows-byggversion med Proton.`,
  _ = `Om möjligt, testa Linux-byggversionen istället för Windows-byggversionen.`,
  _ = `Mitt spel använder inte ett startprogram eller externt konfigurationsverktyg.`,
  _ = `Mitt spel använder ett startprogram och startprogrammet har fullt stöd för handkontroll.`,
  _ = `Mitt spel använder ett startprogram och startprogrammet fungerar inte fullt ut om användaren bara har en handkontroll (inte tangentbord eller mus).`,
  _ = `(Även om plattformsoberoende sparfiler inte krävs för att markeras som ett ”verifierat” spel, är detta mycket värdefullt för kunder som ibland spelar på en Windows-pc och ibland på en Steam Deck med Linux. Läs %1$s.)`,
  _ = `dokumentationen`,
  _ = `(Steam Deck-skärmen är mycket mindre än de flesta pc-skärmar. Om ditt spel har liten text kan det vara svårt eller omöjligt för kunder att läsa den på Steam Deck-skärmen, även om texten är lättläst på en traditionell bildskärm.)`,
  _ = `(De flesta Steam Deck-enheter har inte ett tangentbord anslutet så kunderna förlitar sig på skärmtangentbordet för textinmatning, och Steam tillhandahåller API:er för att göra det enkelt att använda det inbyggda skärmtangentbordet. Om kunderna måste öppna tangentbordet manuellt kommer ditt spel inte att kunna markeras som ”verifierat”. Läs %1$s.)`,
  _ = `rekommendationer om input`,
  _ = `(Om ditt spel använder ett startprogram har startprogrammet samma krav på sig som själva spelet för att kunna verifieras: det måste vara fullt användbart med endast Steam Decks inbyggda kontroller, text måste vara läsbar osv. Om ditt startprogram inte uppfyller dessa krav kan ditt spel inte verifieras, även om själva spelet annars vore verifierat. Läs %1$s.)`,
  _ = `rekommendationerna om startprogram`,
  _ = `(En stor del av Steam Deck-kunder äger även en stationär pc. Cloud-lagring krävs inte för klassificeringen ”verifierat”, men är mycket värdefullt för kunder: genom att ha stöd för sparfiler i %1$s kan kunder spara spel på pc och sedan återuppta spelandet på Steam Deck eller vice versa.)`,
  _ = `Steam Cloud`,
  _ = `(Obs: Fullt kontrollstöd krävs för klassificeringen Verifierat.)`,
  _ = `Ditt spel har lagts till i granskningskön`,
  _ = `Vi testar ditt spel inom kort och meddelar dig om det är några problem.`,
  _ = `Slutför granskningen av din byggversion på Steam innan du skickar in den för granskning av maskinvarukompatibilitet.`,
  _ = `Ditt spel kan inte spelas på Steam Deck just nu`,
  _ = `Ditt spel stöds inte helt på Steam Deck. Detta beror på problem med Proton eller själva Steam Deck. Vi har noterat felen för att kunna jobba på en lösning. Under tiden kan inte ditt spel startas eller köras ordentligt på Steam Deck.`,
  _ = `Ditt spel är spelbart på Steam Deck`,
  _ = `Ditt spel är spelbart på Steam Deck, men kräver extra ansträngningar från användare för att interagera med eller konfigurera spelet. Du kan åtgärda de problem som beskrivs nedan och skicka in igen för att genomgå en ny granskning av kompatibilitet med Steam Deck.`,
  _ = `Byggversion`,
  _ = `Om möjligt, testa Android-byggversionen istället för Windows-byggversionen.`,
  _ = `Testa min Windows-byggversion`,
  _ = `Testa min Linux-byggversion`,
  _ = `Ska vi testa 2D-upplevelsen eller VR (om tillgängligt)?`,
  _ = `2D`,
  _ = `VR`,
  _ = `Gäller inte för %1$s-titlar`,
  _ = `Verifierat, utan användning av Rensa prestandautvärderingsstatus.`,
  _ = `Verifierat, med minst en användning av Rensa prestandautvärderingsstatus.`,
  _ = `Spelbart, utan användning av Rensa prestandautvärderingsstatus.`,
  _ = `Spelbart, med minst en användning av Rensa prestandautvärderingsstatus.`,
  _ = `Unsupported`,
  _ = `Inte en VR-titel (utvärdering gäller inte)`,
  _ = `Prestandautvärderingsöverlägg`,
  _ = `Använd prestandautvärderingsöverlägget för att fylla i svaret nedan. Se %1$s för mer information.`,
  _ = `VR-prestanda (dokumentation)`,
  _ = `(Om spelet innehåller liten text kan det bli svårt eller omöjligt för kunderna att läsa den på Steam Frames skärm, även om texten är lättläst på vanliga bildskärmar.)`,
  _ = `(Steam Frame används oftast utan ett anslutet tangentbord, så kunderna förlitar sig på skärmtangentbordet för textinmatning. Steam erbjuder API:er som gör det enkelt att använda det inbyggda skärmtangentbordet. Om kunderna måste öppna tangentbordet manuellt kan spelet inte få klassificeringen Verifierat. Läs %1$s.)`,
  _ = `Checklista för kompatibilitet med Steam Frame`,
  _ = `(Eventuella startprogram har samma krav på sig som själva spelet för att kunna verifieras. Startprogrammet måste vara fullt användbart med endast Steam Frames inbyggda kontroller, texten måste vara läsbar och så vidare. Om startprogrammet inte uppfyller dessa krav kan spelet inte bli verifierat, även det i övrigt uppfyller alla krav. Läs %1$s.)`,
  _ = `(En stor del av Steam Frame-kunder använder också stationära pc-datorer. Molnlagring krävs inte för att få klassificeringen Verifierat, men det är något kunder uppskattar. Genom att erbjuda stöd för sparfiler i %1$s kan kunder spara sina framsteg på pc och sedan återuppta spelet på Steam Frame eller vice versa.)`,
  _ = `(Plattformsoberoende sparfiler krävs inte för att få klassificeringen Verifierat, men det uppskattas av kunder som växlar mellan att spela på en Windows-pc och en Steam Frame med Linux. Läs %1$s.)`,
  _ = `Ja, spelet visar handkontrolltips för Steam Frame eller Steam Deck vid hänvisning till knapptryck på handkontroll.`,
  _ = `Om resultatet för prestandautvärderingen ovan krävde att Rensa prestandautvärderingsstatus användes minst en gång, välj en eller flera anledningar nedan.`,
  _ = `Prestandan försämras vid spelstart`,
  _ = `Prestandan försämras under laddningsskärmar`,
  _ = `Annat (specificera)`,
  _ = `Du försöker be om en granskning på Android, men %1$s har inga Android-depåer.`,
  _ = `ditt utvecklarpaket`,
  _ = `dummy`,
  _ = {
    Valve_Confidential: _,
    Valve_Confidential_Description: _,
    Footer_Description: _,
    Footer_Sitemap_ContactSupport: _,
    PricingExplorer_LoadError: _,
    PricingExplorer_About_Title: _,
    PricingExplorer_About_Desc1: _,
    PricingExplorer_About_Desc2: _,
    PricingExplorer_About_Link1: _,
    PricingExplorer_About_LinkName1: _,
    PricingExplorer_About_Link2: _,
    PricingExplorer_About_LinkName2: _,
    PricingExplorer_About_Dash: _,
    PricingExplorer_About_LastUpdated: _,
    PricingExplorer_Explore_title: _,
    PricingExplorer_Explore_desc1: _,
    PricingExplorer_Explore_line1: _,
    PricingExplorer_Explore_line2: _,
    PricingExplorer_Explore_line3: _,
    PricingExplorer_Base: _,
    PricingExplorer_BasePrice: _,
    PricingExplorer_TableHeader: _,
    PricingExplorer_Column1: _,
    PricingExplorer_Column2: _,
    PricingExplorer_Column3: _,
    PricingExplorer_Column4: _,
    PricingExplorer_Regions_TableHeader: _,
    PricingExplorer_Regions_Column1: _,
    Pricing_Dummy: _,
    ContentSurvey_Title: _,
    ContentSurvey_Title_Default: _,
    ContentSurvey_History_Title: _,
    ContentSurvey_History_Title_Default: _,
    ContentSurvey_InvalidApp: _,
    PartnerSite_PermissionDenied: _,
    PartnerSite_NotLoggedIn: _,
    SteamDeck_BuildReview_Status_Raw_Title: _,
    SteamDeck_BuildReview_Status_Raw_Description: _,
    SteamDeck_BuildReview_Status_TestProperties_Description: _,
    SteamDeck_BuildReview_Status_TestProperties_Playable: _,
    SteamDeck_BuildReview_Status_TestProperty_Name: _,
    SteamDeck_BuildReview_Status_TestProperty_Value: _,
    SteamDeck_BuildReview_Status_TestProperty_Desc: _,
    SteamDeck_BuildReview_Status_Description: _,
    SteamDeck_BuildReview_Header_History: _,
    SteamDeck_BuildReview_Header_Results: _,
    SteamDeck_BuildReview_Status_Raw_Result: _,
    SteamDeck_BuildReview_Status_Raw_Test: _,
    SteamDeck_BuildReview_Status_Raw_Comment: _,
    SteamDeck_BuildReview_Status_Raw_Impact: _,
    SteamDeck_BuildReview_Status_Pass: _,
    SteamDeck_BuildReview_Status_Fail: _,
    SteamDeck_BuildReview_Status_FailMinor: _,
    SteamDeck_BuildReview_Status_NotApplicable: `---`,
    SteamDeck_BuildReview_Viewing_Historical: _,
    SteamDeck_BuildReview_Viewing_Published: _,
    SteamDeck_BuildReview_PublishedOn: _,
    SteamDeck_BuildReview_ReportedOn: _,
    SteamDeck_BuildReview_Documentation: _,
    SteamDeck_BuildReview_PublishResults: _,
    SteamDeck_BuildReview_PublishDialog_Title: _,
    SteamDeck_BuildReview_PublishDialog_Body: _,
    SteamDeck_BuildReview_UnknownError: _,
    SteamDeck_BuildReview_Help_Request_Title: _,
    SteamDeck_BuildReview_RequestStatusActive: _,
    SteamDeck_BuildReview_RequestStatusClosed: _,
    SteamDeck_BuildReview_InReview_ViewTicket: _,
    SteamDeck_BuildReview_Create_HelpRequest: _,
    SteamDeck_BuildReview_Create_HelpRequest_NotesDefault: _,
    SteamDeck_BuildReview_Create_HelpRequest_NotesDefault_Rereview: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label_Machine: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Button: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_1: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2a: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2b: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Ticket_Content: _,
    SteamDeck_BuildReview_CompatibilityTests: _,
    SteamDeck_BuildReview_Status_Title: _,
    SteamDeck_HardwareCompatibility_Title: _,
    SteamDeck_AppLanding_Published: _,
    SteamDeck_AppLanding_Unpublished: _,
    SteamDeck_AppLanding_History: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RecommendedRuntime: _,
    SteamDeckVerified_TestDisplayName_TestPropertyDescription_RecommendedRuntime:
      _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_ExpectedInput: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RequiresH264: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TestedProtonVersion: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TestedBuildID: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RPODebug: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_FDMDebug: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TSOEnable: _,
    SteamHardware_BuildReview_Unknown_Title: _,
    SteamHardware_BuildReview_Unsupported_Title: _,
    SteamHardware_BuildReview_Unsupported_Description: _,
    SteamHardware_BuildReview_Playable_Title: _,
    SteamHardware_BuildReview_Playable_Description: _,
    SteamHardware_BuildReview_Verified_Title: _,
    SteamHardware_BuildReview_Verified_Description: _,
    SteamHardware_BuildReview_Verified_Share: _,
    SteamHardware_Machine_Unknown: _,
    SteamHardware_Frame_Unknown: _,
    SteamHardware_RatingImpact_Playable: _,
    SteamHardware_RatingImpact_Unsupported: _,
    SteamHardware_RatingImpact_Informational: _,
    SteamDeckVerified_TestDisplayName_0: _,
    SteamDeckVerified_TestDisplayName_1: _,
    SteamDeckVerified_TestDisplayName_2: _,
    SteamDeckVerified_TestDisplayName_3: _,
    SteamDeckVerified_TestDisplayName_4: _,
    SteamDeckVerified_TestDisplayName_5: _,
    SteamDeckVerified_TestDisplayName_6: _,
    SteamDeckVerified_TestDisplayName_7: _,
    SteamDeckVerified_TestDisplayName_8: _,
    SteamDeckVerified_TestDisplayName_9: _,
    SteamDeckVerified_TestDisplayName_10: _,
    SteamDeckVerified_TestDisplayName_11: _,
    SteamDeckVerified_TestDisplayName_12: _,
    SteamDeckVerified_TestDisplayName_13: _,
    SteamDeckVerified_TestDisplayName_14: _,
    SteamDeckVerified_TestDisplayName_15: _,
    SteamDeckVerified_TestDisplayName_16: _,
    SteamDeckVerified_TestDisplayName_17: _,
    SteamDeckVerified_TestDisplayName_18: _,
    SteamDeckVerified_TestDisplayName_19: _,
    SteamDeckVerified_TestDisplayName_20: _,
    SteamDeckVerified_TestDisplayName_21: _,
    SteamDeckVerified_TestDisplayName_22: _,
    SteamDeckVerified_TestDisplayName_23: _,
    SteamDeckVerified_TestDisplayName_24: _,
    SteamDeckVerified_TestDisplayName_25: _,
    SteamDeckVerified_TestDisplayName_26: _,
    SteamDeckVerified_TestDisplayName_27: _,
    SteamDeckVerified_TestDisplayName_29: _,
    SteamDeckVerified_TestDisplayName_30: _,
    SteamDeckVerified_TestDisplayName_31: _,
    SteamDeckVerified_TestDisplayName_32: _,
    SteamDeckVerified_TestDisplayName_33: `VR`,
    SteamDeckVerified_TestDisplayName_34: _,
    SteamDeckVerified_TestDisplayName_35: _,
    SteamDeckVerified_TestDisplayName_36: _,
    SteamDeckVerified_TestDisplayName_37: _,
    SteamDeckVerified_TestDisplayName_38: _,
    SteamDeckVerified_TestDisplayName_39: _,
    SteamDeckVerified_TestDisplayName_40: _,
    SteamDeckVerified_TestDisplayName_41: _,
    SteamDeckVerified_TestDisplayName_42: _,
    SteamDeckVerified_TestDisplayName_43: _,
    SteamDeckVerified_TestDisplayName_44: _,
    SteamDeckVerified_TestDisplayName_45: _,
    SteamDeckVerified_TestDisplayName_46: _,
    SteamDeckVerified_TestDisplayName_47: _,
    SteamDeckVerified_TestDisplayName_48: _,
    SteamDeckVerified_TestDisplayName_49: _,
    SteamDeckVerified_TestDisplayName_50: _,
    SteamDeckVerified_TestDisplayName_51: _,
    SteamDeckVerified_TestDisplayName_52: _,
    SteamDeckVerified_TestDisplayName_53: _,
    SteamDeckVerified_TestDisplayName_54: _,
    SteamDeckVerified_TestDisplayName_55: _,
    SteamDeckVerified_TestDisplayName_56: _,
    SteamDeckVerified_TestDisplayName_57: _,
    SteamDeckVerified_TestDisplayName_58: _,
    SteamDeckVerified_TestDisplayName_59: _,
    SteamDeckVerified_TestDisplayName_60: _,
    SteamDeckVerified_TestDisplayName_61: _,
    SteamDeckVerified_TestDisplayName_62: _,
    SteamDeckVerified_TestDisplayName_63: _,
    SteamDeckVerified_TestDisplayName_64: _,
    SteamDeckVerified_TestDisplayName_65: _,
    Compatibility_Tab_Steam_Machine: _,
    Compatibility_Tab_Steam_OS: _,
    Compatibility_Tab_Steam_Deck: _,
    Compatibility_Tab_Steam_Frame: _,
    SteamDeck_BuildReview_PleaseRequestTest: _,
    SteamFrame_BuildReview_Checklist_Intro_Header_V2: _,
    SteamFrame_BuildReview_PleaseConfirm_Title_V2: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P1: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P3: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P3_ReviewProcess: _,
    SteamFrame_BuildReview_PleaseConfirm_Description_V2: _,
    SteamDeck_TestRequest_BuildNotReleased: _,
    SteamDeck_BuildReview_Checklist_Intro: _,
    SteamDeck_BuildReview_Checklist_Intro_Header_V2: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P1: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P2: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3_ReviewProcess: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3_Additional: _,
    SteamDeck_BuildReview_PleaseConfirm_Title_V2: _,
    SteamDeck_BuildReview_PleaseConfirm_Description_V2: _,
    SteamDeck_BuildReview_AppTypeUnavailable: _,
    SteamDeck_BuildReview_Checklist_Input: _,
    SteamDeck_BuildReview_Checklist_Text: _,
    SteamDeck_BuildReview_Checklist_Display: _,
    SteamDeck_BuildReview_Checklist_Functionality: _,
    SteamDeck_BuildReview_Checklist_SteamCloud: _,
    SteamDeck_BuildReview_Checklist_Launcher: _,
    SteamDeck_BuildReview_Checklist_Branch: _,
    SteamDeck_BuildReview_Checklist_Branch_PleaseTest: _,
    SteamDeck_BuildReview_MarkReady_Button: _,
    SteamDeck_BuildReview_MarkReady_Description: _,
    SteamDeck_BuildReview_MarkReady_Notes: _,
    SteamDeck_BuildReview_MarkReady_NotesDefault: _,
    SteamDeck_BuildReview_HelpRequest_Link: _,
    SteamDeck_BuildReview_ViewMoreDetailsInHelp: _,
    SteamDeck_BuildReview_Create_HelpRequest_Title: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes_1: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes_2: _,
    SteamDeck_BuildReview_Create_HelpRequest_SupportTicketIntro: _,
    SteamDeck_BuildReview_Check_Controller: _,
    SteamDeck_BuildReview_Check_Icons: _,
    SteamDeck_BuildReview_Check_TextInput: _,
    SteamDeck_BuildReview_Check_TextInput_V2_NoTextEntry: _,
    SteamDeck_BuildReview_Check_TextInput_V2_YesSteamAPIs: _,
    SteamDeck_BuildReview_Check_TextInput_V2_NoSteamAPIs: _,
    SteamDeck_BuildReview_Check_Cloud_NoSaves: _,
    SteamDeck_BuildReview_Check_Cloud_YesSavesNoCloud: _,
    SteamDeck_BuildReview_Check_Cloud_SinglePlatform: _,
    SteamDeck_BuildReview_Check_Cloud_YesCrossSaves: _,
    SteamDeck_BuildReview_Check_Cloud_NoCrossSaves: _,
    SteamDeck_BuildReview_Check_Display1280: _,
    SteamDeck_BuildReview_Check_DisplayFont: _,
    SteamDeck_BuildReview_Check_FunctionalityLauncher: _,
    SteamDeck_BuildReview_Check_FunctionalityCloudSaves: _,
    SteamDeck_BuildReview_Check_FunctionalityCrossPlatformCloudSaves: _,
    SteamDeck_BuildReview_Check_TestLinuxBuild_Preamble: _,
    SteamDeck_BuildReview_Check_TestLinuxBuild: _,
    SteamDeck_BuildReview_Check_Launcher_V2_NoLauncher: _,
    SteamDeck_BuildReview_Check_Launcher_V2_ControllerSupport: _,
    SteamDeck_BuildReview_Check_Launcher_V2_NoControllerSupport: _,
    SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves: _,
    SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves_Documentation: _,
    SteamDeck_BuildReview_CheckNote_DisplayFont: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_InputRecommendations:
      _,
    SteamDeck_BuildReview_CheckNote_Launcher_V2_NoControllerSupport: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_LauncherRecommendations:
      _,
    SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud: _,
    SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud_SteamCloud: _,
    SteamDeck_BuildReview_CheckNote_FullController: _,
    SteamDeck_BuildReview_InReview_Title: _,
    SteamDeck_BuildReview_InReview_Description: _,
    SteamDeck_BuildReview_PleaseComplete: _,
    SteamDeck_BuildReview_Unsupported_Title: _,
    SteamDeck_BuildReview_Unsupported_Description: _,
    SteamDeck_BuildReview_NotMeetRequirements_Title: _,
    SteamDeck_BuildReview_NotMeetRequirements_Description: _,
    SteamFrame_BuildReview_Checklist_Build: _,
    SteamFrame_BuildReview_Build_Android: _,
    SteamFrame_BuildReview_Build_Windows: _,
    SteamFrame_BuildReview_Build_Linux: _,
    SteamFrame_BuildReview_Checklist_Dimension: _,
    SteamFrame_BuildReview_Dimension_2D: `2D`,
    SteamFrame_BuildReview_Dimension_VR: `VR`,
    SteamFrame_NotApplicableForDimension: _,
    SteamFrame_BuildReview_Check_VRPerformance_Verified_Without: _,
    SteamFrame_BuildReview_Check_VRPerformance_Verified_With: _,
    SteamFrame_BuildReview_Check_VRPerformance_Playable_Without: _,
    SteamFrame_BuildReview_Check_VRPerformance_Playable_With: _,
    SteamFrame_BuildReview_Check_VRPerformance_Unsupported: _,
    SteamFrame_BuildReview_Check_VRPerformance_NotApplicable: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_Title: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_Description: _,
    SteamFrame_BuildReview_VRPerformanceLink: _,
    SteamFrame_BuildReview_CheckNote_DisplayFont: _,
    SteamFrame_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs: _,
    SteamFrame_BuildReview_Compatibility_Checklist: _,
    SteamFrame_BuildReview_CheckNote_Launcher_V2_NoControllerSupport: _,
    SteamFrame_BuildReview_CheckNote_Cloud_YesSavesNoCloud: _,
    SteamFrame_BuildReview_CheckNote_Cloud_NoCrossSaves: _,
    SteamFrame_BuildReview_Check_Icons: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_StatusReason: _,
    SteamFrame_BuildReview_Check_VRPerformance_Startup: _,
    SteamFrame_BuildReview_Check_VRPerformance_Loading: _,
    SteamFrame_BuildReview_Check_VRPerformance_Other: _,
    SteamFrame_BuildReview_CheckNote_Missing_Android_License: _,
    SteamFrame_BuildReview_CheckNote_Missing_Android_License_Link: _,
    dummy: _,
  };
export {
  _ as Compatibility_Tab_Steam_Deck,
  _ as Compatibility_Tab_Steam_Frame,
  _ as Compatibility_Tab_Steam_Machine,
  _ as Compatibility_Tab_Steam_OS,
  _ as ContentSurvey_History_Title,
  _ as ContentSurvey_History_Title_Default,
  _ as ContentSurvey_InvalidApp,
  _ as ContentSurvey_Title,
  _ as ContentSurvey_Title_Default,
  _ as Footer_Description,
  _ as Footer_Sitemap_ContactSupport,
  _ as PartnerSite_NotLoggedIn,
  _ as PartnerSite_PermissionDenied,
  _ as PricingExplorer_About_Dash,
  _ as PricingExplorer_About_Desc1,
  _ as PricingExplorer_About_Desc2,
  _ as PricingExplorer_About_LastUpdated,
  _ as PricingExplorer_About_Link1,
  _ as PricingExplorer_About_Link2,
  _ as PricingExplorer_About_LinkName1,
  _ as PricingExplorer_About_LinkName2,
  _ as PricingExplorer_About_Title,
  _ as PricingExplorer_Base,
  _ as PricingExplorer_BasePrice,
  _ as PricingExplorer_Column1,
  _ as PricingExplorer_Column2,
  _ as PricingExplorer_Column3,
  _ as PricingExplorer_Column4,
  _ as PricingExplorer_Explore_desc1,
  _ as PricingExplorer_Explore_line1,
  _ as PricingExplorer_Explore_line2,
  _ as PricingExplorer_Explore_line3,
  _ as PricingExplorer_Explore_title,
  _ as PricingExplorer_LoadError,
  _ as PricingExplorer_Regions_Column1,
  _ as PricingExplorer_Regions_TableHeader,
  _ as PricingExplorer_TableHeader,
  _ as Pricing_Dummy,
  _ as SteamDeckVerified_TestDisplayName_0,
  _ as SteamDeckVerified_TestDisplayName_1,
  _ as SteamDeckVerified_TestDisplayName_10,
  _ as SteamDeckVerified_TestDisplayName_11,
  _ as SteamDeckVerified_TestDisplayName_12,
  _ as SteamDeckVerified_TestDisplayName_13,
  _ as SteamDeckVerified_TestDisplayName_14,
  _ as SteamDeckVerified_TestDisplayName_15,
  _ as SteamDeckVerified_TestDisplayName_16,
  _ as SteamDeckVerified_TestDisplayName_17,
  _ as SteamDeckVerified_TestDisplayName_18,
  _ as SteamDeckVerified_TestDisplayName_19,
  _ as SteamDeckVerified_TestDisplayName_2,
  _ as SteamDeckVerified_TestDisplayName_20,
  _ as SteamDeckVerified_TestDisplayName_21,
  _ as SteamDeckVerified_TestDisplayName_22,
  _ as SteamDeckVerified_TestDisplayName_23,
  _ as SteamDeckVerified_TestDisplayName_24,
  _ as SteamDeckVerified_TestDisplayName_25,
  _ as SteamDeckVerified_TestDisplayName_26,
  _ as SteamDeckVerified_TestDisplayName_27,
  _ as SteamDeckVerified_TestDisplayName_29,
  _ as SteamDeckVerified_TestDisplayName_3,
  _ as SteamDeckVerified_TestDisplayName_30,
  _ as SteamDeckVerified_TestDisplayName_31,
  _ as SteamDeckVerified_TestDisplayName_32,
  _ as SteamDeckVerified_TestDisplayName_33,
  _ as SteamDeckVerified_TestDisplayName_34,
  _ as SteamDeckVerified_TestDisplayName_35,
  _ as SteamDeckVerified_TestDisplayName_36,
  _ as SteamDeckVerified_TestDisplayName_37,
  _ as SteamDeckVerified_TestDisplayName_38,
  _ as SteamDeckVerified_TestDisplayName_39,
  _ as SteamDeckVerified_TestDisplayName_4,
  _ as SteamDeckVerified_TestDisplayName_40,
  _ as SteamDeckVerified_TestDisplayName_41,
  _ as SteamDeckVerified_TestDisplayName_42,
  _ as SteamDeckVerified_TestDisplayName_43,
  _ as SteamDeckVerified_TestDisplayName_44,
  _ as SteamDeckVerified_TestDisplayName_45,
  _ as SteamDeckVerified_TestDisplayName_46,
  _ as SteamDeckVerified_TestDisplayName_47,
  _ as SteamDeckVerified_TestDisplayName_48,
  _ as SteamDeckVerified_TestDisplayName_49,
  _ as SteamDeckVerified_TestDisplayName_5,
  _ as SteamDeckVerified_TestDisplayName_50,
  _ as SteamDeckVerified_TestDisplayName_51,
  _ as SteamDeckVerified_TestDisplayName_52,
  _ as SteamDeckVerified_TestDisplayName_53,
  _ as SteamDeckVerified_TestDisplayName_54,
  _ as SteamDeckVerified_TestDisplayName_55,
  _ as SteamDeckVerified_TestDisplayName_56,
  _ as SteamDeckVerified_TestDisplayName_57,
  _ as SteamDeckVerified_TestDisplayName_58,
  _ as SteamDeckVerified_TestDisplayName_59,
  _ as SteamDeckVerified_TestDisplayName_6,
  _ as SteamDeckVerified_TestDisplayName_60,
  _ as SteamDeckVerified_TestDisplayName_61,
  _ as SteamDeckVerified_TestDisplayName_62,
  _ as SteamDeckVerified_TestDisplayName_63,
  _ as SteamDeckVerified_TestDisplayName_64,
  _ as SteamDeckVerified_TestDisplayName_65,
  _ as SteamDeckVerified_TestDisplayName_7,
  _ as SteamDeckVerified_TestDisplayName_8,
  _ as SteamDeckVerified_TestDisplayName_9,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyDescription_RecommendedRuntime,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_ExpectedInput,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_FDMDebug,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RPODebug,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RecommendedRuntime,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RequiresH264,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TSOEnable,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TestedBuildID,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TestedProtonVersion,
  _ as SteamDeck_AppLanding_History,
  _ as SteamDeck_AppLanding_Published,
  _ as SteamDeck_AppLanding_Unpublished,
  _ as SteamDeck_BuildReview_AppTypeUnavailable,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves_Documentation,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud_SteamCloud,
  _ as SteamDeck_BuildReview_CheckNote_DisplayFont,
  _ as SteamDeck_BuildReview_CheckNote_FullController,
  _ as SteamDeck_BuildReview_CheckNote_Launcher_V2_NoControllerSupport,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_InputRecommendations,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_LauncherRecommendations,
  _ as SteamDeck_BuildReview_Check_Cloud_NoCrossSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_NoSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_SinglePlatform,
  _ as SteamDeck_BuildReview_Check_Cloud_YesCrossSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_YesSavesNoCloud,
  _ as SteamDeck_BuildReview_Check_Controller,
  _ as SteamDeck_BuildReview_Check_Display1280,
  _ as SteamDeck_BuildReview_Check_DisplayFont,
  _ as SteamDeck_BuildReview_Check_FunctionalityCloudSaves,
  _ as SteamDeck_BuildReview_Check_FunctionalityCrossPlatformCloudSaves,
  _ as SteamDeck_BuildReview_Check_FunctionalityLauncher,
  _ as SteamDeck_BuildReview_Check_Icons,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_ControllerSupport,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_NoControllerSupport,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_NoLauncher,
  _ as SteamDeck_BuildReview_Check_TestLinuxBuild,
  _ as SteamDeck_BuildReview_Check_TestLinuxBuild_Preamble,
  _ as SteamDeck_BuildReview_Check_TextInput,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_NoSteamAPIs,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_NoTextEntry,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_YesSteamAPIs,
  _ as SteamDeck_BuildReview_Checklist_Branch,
  _ as SteamDeck_BuildReview_Checklist_Branch_PleaseTest,
  _ as SteamDeck_BuildReview_Checklist_Display,
  _ as SteamDeck_BuildReview_Checklist_Functionality,
  _ as SteamDeck_BuildReview_Checklist_Input,
  _ as SteamDeck_BuildReview_Checklist_Intro,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P1,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P2,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3_Additional,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3_ReviewProcess,
  _ as SteamDeck_BuildReview_Checklist_Intro_Header_V2,
  _ as SteamDeck_BuildReview_Checklist_Launcher,
  _ as SteamDeck_BuildReview_Checklist_SteamCloud,
  _ as SteamDeck_BuildReview_Checklist_Text,
  _ as SteamDeck_BuildReview_CompatibilityTests,
  _ as SteamDeck_BuildReview_Create_HelpRequest,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_1,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2a,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2b,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes,
  _ as SteamDeck_BuildReview_Create_HelpRequest_NotesDefault,
  _ as SteamDeck_BuildReview_Create_HelpRequest_NotesDefault_Rereview,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes_1,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes_2,
  _ as SteamDeck_BuildReview_Create_HelpRequest_SupportTicketIntro,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Title,
  _ as SteamDeck_BuildReview_Documentation,
  _ as SteamDeck_BuildReview_Header_History,
  _ as SteamDeck_BuildReview_Header_Results,
  _ as SteamDeck_BuildReview_HelpRequest_Link,
  _ as SteamDeck_BuildReview_Help_Request_Title,
  _ as SteamDeck_BuildReview_InReview_Description,
  _ as SteamDeck_BuildReview_InReview_Title,
  _ as SteamDeck_BuildReview_InReview_ViewTicket,
  _ as SteamDeck_BuildReview_MarkReady_Button,
  _ as SteamDeck_BuildReview_MarkReady_Description,
  _ as SteamDeck_BuildReview_MarkReady_Notes,
  _ as SteamDeck_BuildReview_MarkReady_NotesDefault,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Description,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Button,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label_Machine,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Ticket_Content,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Title,
  _ as SteamDeck_BuildReview_PleaseComplete,
  _ as SteamDeck_BuildReview_PleaseConfirm_Description_V2,
  _ as SteamDeck_BuildReview_PleaseConfirm_Title_V2,
  _ as SteamDeck_BuildReview_PleaseRequestTest,
  _ as SteamDeck_BuildReview_PublishDialog_Body,
  _ as SteamDeck_BuildReview_PublishDialog_Title,
  _ as SteamDeck_BuildReview_PublishResults,
  _ as SteamDeck_BuildReview_PublishedOn,
  _ as SteamDeck_BuildReview_ReportedOn,
  _ as SteamDeck_BuildReview_RequestStatusActive,
  _ as SteamDeck_BuildReview_RequestStatusClosed,
  _ as SteamDeck_BuildReview_Status_Description,
  _ as SteamDeck_BuildReview_Status_Fail,
  _ as SteamDeck_BuildReview_Status_FailMinor,
  _ as SteamDeck_BuildReview_Status_NotApplicable,
  _ as SteamDeck_BuildReview_Status_Pass,
  _ as SteamDeck_BuildReview_Status_Raw_Comment,
  _ as SteamDeck_BuildReview_Status_Raw_Description,
  _ as SteamDeck_BuildReview_Status_Raw_Impact,
  _ as SteamDeck_BuildReview_Status_Raw_Result,
  _ as SteamDeck_BuildReview_Status_Raw_Test,
  _ as SteamDeck_BuildReview_Status_Raw_Title,
  _ as SteamDeck_BuildReview_Status_TestProperties_Description,
  _ as SteamDeck_BuildReview_Status_TestProperties_Playable,
  _ as SteamDeck_BuildReview_Status_TestProperty_Desc,
  _ as SteamDeck_BuildReview_Status_TestProperty_Name,
  _ as SteamDeck_BuildReview_Status_TestProperty_Value,
  _ as SteamDeck_BuildReview_Status_Title,
  _ as SteamDeck_BuildReview_UnknownError,
  _ as SteamDeck_BuildReview_Unsupported_Description,
  _ as SteamDeck_BuildReview_Unsupported_Title,
  _ as SteamDeck_BuildReview_ViewMoreDetailsInHelp,
  _ as SteamDeck_BuildReview_Viewing_Historical,
  _ as SteamDeck_BuildReview_Viewing_Published,
  _ as SteamDeck_HardwareCompatibility_Title,
  _ as SteamDeck_TestRequest_BuildNotReleased,
  _ as SteamFrame_BuildReview_Build_Android,
  _ as SteamFrame_BuildReview_Build_Linux,
  _ as SteamFrame_BuildReview_Build_Windows,
  _ as SteamFrame_BuildReview_CheckNote_Cloud_NoCrossSaves,
  _ as SteamFrame_BuildReview_CheckNote_Cloud_YesSavesNoCloud,
  _ as SteamFrame_BuildReview_CheckNote_DisplayFont,
  _ as SteamFrame_BuildReview_CheckNote_Launcher_V2_NoControllerSupport,
  _ as SteamFrame_BuildReview_CheckNote_Missing_Android_License,
  _ as SteamFrame_BuildReview_CheckNote_Missing_Android_License_Link,
  _ as SteamFrame_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs,
  _ as SteamFrame_BuildReview_Check_Icons,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Loading,
  _ as SteamFrame_BuildReview_Check_VRPerformance_NotApplicable,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Other,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Playable_With,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Playable_Without,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Startup,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Unsupported,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Verified_With,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Verified_Without,
  _ as SteamFrame_BuildReview_Checklist_Build,
  _ as SteamFrame_BuildReview_Checklist_Dimension,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P1,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P3,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P3_ReviewProcess,
  _ as SteamFrame_BuildReview_Checklist_Intro_Header_V2,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_Description,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_StatusReason,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_Title,
  _ as SteamFrame_BuildReview_Compatibility_Checklist,
  _ as SteamFrame_BuildReview_Dimension_2D,
  _ as SteamFrame_BuildReview_Dimension_VR,
  _ as SteamFrame_BuildReview_PleaseConfirm_Description_V2,
  _ as SteamFrame_BuildReview_PleaseConfirm_Title_V2,
  _ as SteamFrame_BuildReview_VRPerformanceLink,
  _ as SteamFrame_NotApplicableForDimension,
  _ as SteamHardware_BuildReview_Playable_Description,
  _ as SteamHardware_BuildReview_Playable_Title,
  _ as SteamHardware_BuildReview_Unknown_Title,
  _ as SteamHardware_BuildReview_Unsupported_Description,
  _ as SteamHardware_BuildReview_Unsupported_Title,
  _ as SteamHardware_BuildReview_Verified_Description,
  _ as SteamHardware_BuildReview_Verified_Share,
  _ as SteamHardware_BuildReview_Verified_Title,
  _ as SteamHardware_Frame_Unknown,
  _ as SteamHardware_Machine_Unknown,
  _ as SteamHardware_RatingImpact_Informational,
  _ as SteamHardware_RatingImpact_Playable,
  _ as SteamHardware_RatingImpact_Unsupported,
  _ as Valve_Confidential,
  _ as Valve_Confidential_Description,
  _ as default,
  _ as dummy,
};
