var _ = `Select an USD price below`,
  _ = `Free`,
  _ = `Set to Free...`,
  _ = `Update this package to free for customers`,
  _ = `This package can only be set free by a Steam support representitive. Please use the "Contact Steam Publishing" link under "Documentation and Help" for assistance.`,
  _ = `Convert Package To Free?`,
  _ = `This will set your package pricing as free, mark your app so that it can appear in the Free To Play hub, and change the price display based on the term you select below. This change cannot be reversed without filing a ticket to the Steamworks support team.`,
  _ = `This package can only be converted to free by a Steam support representitive. Click below to create a support request ticket with details of your request.`,
  _ = `Select the appropriate text to show instead of price:`,
  _ = `"Free to Play" - The game is free to download and play, but includes optional in-game purchases (items, currency, DLC, or other monetization).`,
  _ = `"Free" - The game is completely free to download and play. No in-game purchases or paid content.`,
  _ = `Convert to free`,
  _ = `Updating Game's Store Page to be included in Free genre. Store Publish Required.`,
  _ = `Updating Package to be Free`,
  _ = `Conversion to free succeeded.  Page will reload when you close the dialog.`,
  _ = `Failed to update store app page: %1$s`,
  _ = `Failed to change package type: %1$s`,
  _ = `Conversion Method (%1$s)`,
  _ = `See Details`,
  _ = `From the drop-down below, please select the price for which you would like to sell your product. For whatever base price you select, this tool will suggest appropriate regional prices based on our experience with other titles at similar price points. Note that some countries recommended conversions include VAT/GST/JCT. VAT/GST/JCT are value-added taxes, similar to sales tax, levied by tax authorities. In countries where VAT is required by applicable law, it is included in the prices and collected on purchases from applicable countries. A list of countries where VAT is collected can be found here:`,
  _ = `Before submitting, please double-check your prices IN ALL CURRENCIES and think carefully about your product. For various reasons, we recommend partners not tweak their prices in the first weeks after release. You can submit a new price request prior to launch if needed, but once your product is live, your prices will stand. See the %1$s to learn more.`,
  _ = `pricing and discounting documentation`,
  _ = `Once you're happy with your price, hit the Save button to send it to Valve for review and processing.`,
  _ = `Edit On Bulk Pricing Page`,
  _ = `Edit this package's pricing from the bulk pricing tool`,
  _ = `Help and Guidelines`,
  _ = `Looking for help or suggestions in pricing your title? Below is a link to some common considerations and guidelines.`,
  _ = `Pricing Documentation`,
  _ = `FAQ`,
  _ = `Switching to Free?`,
  _ = `If your game has already released and you need to switch from paid to free, click %1$s to learn more and request assistance.`,
  _ = `here`,
  _ = `Entering custom prices`,
  _ = `You can enter your own prices for each currency by editing the text box directly.`,
  _ = `You can also use this button to calculate each currency based on the selected conversion method and your entered custom USD.`,
  _ = `Select From Price Tiers`,
  _ = `Select USD Base Price`,
  _ = `Open a dialog with a set of common price tiers to allow setting them across all of the currencies below.`,
  _ = `Multi-variable conversion`,
  _ = `Purchasing power conversion only`,
  _ = `Exchange-rate conversion only`,
  _ = `Last updated:`,
  _ = `Conversion methods are generated using public data as of January, 2026`,
  _ = `New conversion methods available`,
  _ = `To help price your game in 37 different currencies and 4 region groups, Steam now offers a few different methods for assisting in converting from your desired base price`,
  _ = `Pricing is entirely up to you; these tools are merely designed to help simplify the process if you so choose.`,
  _ = `Please visit our %1$s or click 'see details' above to learn more about the different conversion methods available.`,
  _ = `Conversion Method Details page`,
  _ = `Apply Conversion Method Prices`,
  _ = `To help you manage your pricing across the 35+ currencies that Steam supports, this tool offers optional methods of conversion for translating your base USD price into region appropriate levels.`,
  _ = `Select a price below to set that price for USD and apply converted prices for all other currencies. Depends on the conversion method selected above.`,
  _ = `You can enter prices for each individual supported currency, or use one of Steam's conversion methods to convert your USD price to all other currencies.`,
  _ = `There are two ways to use Steam's conversion methods:`,
  _ = `Select a common USD price from the Price Tiers drop-down menu below and Steam will fill in the other currencies based on the conversion method selected.`,
  _ = `For non-common USD prices, type a value into the USD price field. Then click the button that says 'Convert Prices...' and follow the instructions.`,
  _ = `Suggested conversion:`,
  _ = `This price is suggested based on the conversion method selected above and a USD price of %1$s.`,
  _ = `dummy`,
  _ = ``,
  _ = {
    PricingGuideline_Default: _,
    FreeOnDemand_InlineOption: _,
    FreeOnDemand_Button: _,
    FreeOnDemand_Button_ttip: _,
    FreeOnDemand_Button_disabled_ttip: _,
    FreeOnDemand_Title: _,
    FreeOnDemand_Desc: _,
    FreeOnDemand_Desc_NotPermitted: _,
    FreeOnDemand_Radio: _,
    FreeOnDemand_Radio_FreeToPlay: _,
    FreeOnDemand_Radio_Free: _,
    FreeOnDemand_Button_Confirm: _,
    FreeOnDemand_Convert_Store: _,
    FreeOnDemand_Convert_Package: _,
    FreeOnDemand_ConvertSuccess: _,
    FreeOnDemand_Store_Error: _,
    FreeOnDemand_Package_Error: _,
    ConversionMethod_Title: _,
    ConversionMethod_Link: _,
    SinglePricingPackage_Desc_1: _,
    SinglePricingPackage_Desc_2: _,
    SinglePricingPackage_Desc_2_Link: _,
    SinglePricingPackage_Desc_3: _,
    SinglePackagePricing_Right_Edit: _,
    SinglePackagePricing_Right_Edit_desc: _,
    SinglePackagePricing_Right_Help_Title: _,
    SinglePackagePricing_Right_Help_Desc: _,
    SinglePackagePricing_Right_Link: _,
    SinglePackagePricing_Right_FAQ: `FAQ`,
    SinglePackagePricing_Right_FAQ_switching: _,
    SinglePackagePricing_Right_FAQ_switching_answer: _,
    SinglePackagePricing_Right_FAQ_switching_answer_link: _,
    SinglePackagePricing_Right_Convert_Title: _,
    SinglePackagePricing_Right_Custom_Desc: _,
    SinglePackagePricing_Right_Convert_Desc: _,
    PricingDashboard_Select_Price: _,
    PricingDashboard_Select_Price_button: _,
    PricingDashboard_Select_Price_button_ttip: _,
    ConversionMethod_Nuanced: _,
    ConversionMethod_PPP: _,
    ConversionMethod_FX: _,
    PricingExplorer_Time_Title: _,
    PricingExplorer_Time_Disc: _,
    Tour_ConversionMethod_Title: _,
    Tour_ConversionMethod_Desc1: _,
    Tour_ConversionMethod_Desc2: _,
    Tour_ConversionMethod_Desc3: _,
    Tour_ConversionMethod_Link: _,
    PricingDashboard_ApplyConversion_Method: _,
    PricingDashboard_ApplyGuidelines_Instructions_MultiOptions: _,
    PricingDashboard_GuidelinesPickerDescription_New: _,
    SinglePricingPackage_Intro_1: _,
    SinglePricingPackage_Intro_2: _,
    SinglePricingPackage_Intro_2a: _,
    SinglePricingPackage_Intro_2b: _,
    PricingDashboard_Method_SuggestedPrice: _,
    PricingDashboard_Method_SuggestedPrice_ttip: _,
    dummy: _,
    empty_no_trailing_comma: ``,
  };
export {
  _ as ConversionMethod_FX,
  _ as ConversionMethod_Link,
  _ as ConversionMethod_Nuanced,
  _ as ConversionMethod_PPP,
  _ as ConversionMethod_Title,
  _ as FreeOnDemand_Button,
  _ as FreeOnDemand_Button_Confirm,
  _ as FreeOnDemand_Button_disabled_ttip,
  _ as FreeOnDemand_Button_ttip,
  _ as FreeOnDemand_ConvertSuccess,
  _ as FreeOnDemand_Convert_Package,
  _ as FreeOnDemand_Convert_Store,
  _ as FreeOnDemand_Desc,
  _ as FreeOnDemand_Desc_NotPermitted,
  _ as FreeOnDemand_InlineOption,
  _ as FreeOnDemand_Package_Error,
  _ as FreeOnDemand_Radio,
  _ as FreeOnDemand_Radio_Free,
  _ as FreeOnDemand_Radio_FreeToPlay,
  _ as FreeOnDemand_Store_Error,
  _ as FreeOnDemand_Title,
  _ as PricingDashboard_ApplyConversion_Method,
  _ as PricingDashboard_ApplyGuidelines_Instructions_MultiOptions,
  _ as PricingDashboard_GuidelinesPickerDescription_New,
  _ as PricingDashboard_Method_SuggestedPrice,
  _ as PricingDashboard_Method_SuggestedPrice_ttip,
  _ as PricingDashboard_Select_Price,
  _ as PricingDashboard_Select_Price_button,
  _ as PricingDashboard_Select_Price_button_ttip,
  _ as PricingExplorer_Time_Disc,
  _ as PricingExplorer_Time_Title,
  _ as PricingGuideline_Default,
  _ as SinglePackagePricing_Right_Convert_Desc,
  _ as SinglePackagePricing_Right_Convert_Title,
  _ as SinglePackagePricing_Right_Custom_Desc,
  _ as SinglePackagePricing_Right_Edit,
  _ as SinglePackagePricing_Right_Edit_desc,
  _ as SinglePackagePricing_Right_FAQ,
  _ as SinglePackagePricing_Right_FAQ_switching,
  _ as SinglePackagePricing_Right_FAQ_switching_answer,
  _ as SinglePackagePricing_Right_FAQ_switching_answer_link,
  _ as SinglePackagePricing_Right_Help_Desc,
  _ as SinglePackagePricing_Right_Help_Title,
  _ as SinglePackagePricing_Right_Link,
  _ as SinglePricingPackage_Desc_1,
  _ as SinglePricingPackage_Desc_2,
  _ as SinglePricingPackage_Desc_2_Link,
  _ as SinglePricingPackage_Desc_3,
  _ as SinglePricingPackage_Intro_1,
  _ as SinglePricingPackage_Intro_2,
  _ as SinglePricingPackage_Intro_2a,
  _ as SinglePricingPackage_Intro_2b,
  _ as Tour_ConversionMethod_Desc1,
  _ as Tour_ConversionMethod_Desc2,
  _ as Tour_ConversionMethod_Desc3,
  _ as Tour_ConversionMethod_Link,
  _ as Tour_ConversionMethod_Title,
  _ as default,
  _ as dummy,
  _ as empty_no_trailing_comma,
};
