var _ = `不明`,
  _ = `美元`,
  _ = `英鎊`,
  _ = `歐元`,
  _ = `瑞士法郎`,
  _ = `俄羅斯盧布`,
  _ = `波蘭茲羅提`,
  _ = `巴西雷亞爾`,
  _ = `日圓`,
  _ = `挪威克朗`,
  _ = `印尼盾`,
  _ = `馬來西亞令吉`,
  _ = `菲律賓披索`,
  _ = `新加坡元`,
  _ = `泰銖`,
  _ = `越南盾`,
  _ = `韓元`,
  _ = `新土耳其里拉`,
  _ = `烏克蘭格里夫納`,
  _ = `墨西哥披索`,
  _ = `加幣`,
  _ = `澳幣`,
  _ = `紐西蘭元`,
  _ = `中國人民幣`,
  _ = `印度盧比`,
  _ = `智利披索`,
  _ = `秘魯索爾`,
  _ = `哥倫比亞披索`,
  _ = `南非蘭特`,
  _ = `港幣`,
  _ = `新台幣`,
  _ = `沙烏地阿拉伯里亞爾`,
  _ = `阿聯迪拉姆`,
  _ = `阿根廷披索`,
  _ = `以色列新謝克爾`,
  _ = `哈薩克堅戈`,
  _ = `科威特第納爾`,
  _ = `卡達里亞爾`,
  _ = `哥斯大黎加科朗`,
  _ = `烏拉圭披索`,
  _ = `保加利亞列弗`,
  _ = `瑞典克朗`,
  _ = `克羅埃西亞庫納`,
  _ = `捷克克朗`,
  _ = `丹麥克朗`,
  _ = `匈牙利福林`,
  _ = `羅馬尼亞列伊`,
  _ = `白俄羅斯盧布`,
  _ = `獨立國家聯合體屬地 - 顯示給亞美尼亞、亞塞拜然、白俄羅斯、喬治亞、吉爾吉斯、摩爾多瓦、塔吉克、土庫曼和烏茲別克的顧客`,
  _ = `南亞國家 / 地區 - 顯示給孟加拉、不丹、巴基斯坦和斯里蘭卡的顧客`,
  _ = `拉丁美洲國家 / 地區 - 顯示給阿根廷、貝里斯、玻利維亞、厄瓜多、薩爾瓦多、蓋亞那、瓜地馬拉、宏都拉斯、尼加拉瓜、巴拿馬、巴拉圭、蘇利南和委內瑞拉的顧客`,
  _ = `中東和北非國家 / 地區 - 顯示給阿爾及利亞、巴林、埃及、伊拉克、約旦、黎巴嫩、利比亞、摩洛哥、阿曼、巴勒斯坦、蘇丹、突尼西亞、土耳其和葉門的顧客`,
  _ = `不明`,
  _ = `dummy`,
  _ = {
    CurrencyCodeDescription_Unknown: _,
    CurrencyCodeDescription_USD: _,
    CurrencyCodeDescription_GBP: _,
    CurrencyCodeDescription_EUR: _,
    CurrencyCodeDescription_CHF: _,
    CurrencyCodeDescription_RUB: _,
    CurrencyCodeDescription_PLN: _,
    CurrencyCodeDescription_BRL: _,
    CurrencyCodeDescription_JPY: _,
    CurrencyCodeDescription_NOK: _,
    CurrencyCodeDescription_IDR: _,
    CurrencyCodeDescription_MYR: _,
    CurrencyCodeDescription_PHP: _,
    CurrencyCodeDescription_SGD: _,
    CurrencyCodeDescription_THB: _,
    CurrencyCodeDescription_VND: _,
    CurrencyCodeDescription_KRW: _,
    CurrencyCodeDescription_TRY: _,
    CurrencyCodeDescription_UAH: _,
    CurrencyCodeDescription_MXN: _,
    CurrencyCodeDescription_CAD: _,
    CurrencyCodeDescription_AUD: _,
    CurrencyCodeDescription_NZD: _,
    CurrencyCodeDescription_CNY: _,
    CurrencyCodeDescription_INR: _,
    CurrencyCodeDescription_CLP: _,
    CurrencyCodeDescription_PEN: _,
    CurrencyCodeDescription_COP: _,
    CurrencyCodeDescription_ZAR: _,
    CurrencyCodeDescription_HKD: _,
    CurrencyCodeDescription_TWD: _,
    CurrencyCodeDescription_SAR: _,
    CurrencyCodeDescription_AED: _,
    CurrencyCodeDescription_ARS: _,
    CurrencyCodeDescription_ILS: _,
    CurrencyCodeDescription_KZT: _,
    CurrencyCodeDescription_KWD: _,
    CurrencyCodeDescription_QAR: _,
    CurrencyCodeDescription_CRC: _,
    CurrencyCodeDescription_UYU: _,
    CurrencyCodeDescription_BGN: _,
    CurrencyCodeDescription_SEK: _,
    CurrencyCodeDescription_HRK: _,
    CurrencyCodeDescription_CZK: _,
    CurrencyCodeDescription_DKK: _,
    CurrencyCodeDescription_HUF: _,
    CurrencyCodeDescription_RON: _,
    CurrencyCodeDescription_BYN: _,
    Region_Pricing_Tooltip_CIS: _,
    Region_Pricing_Tooltip_SASIA: _,
    Region_Pricing_Tooltip_LATAM: _,
    Region_Pricing_Tooltip_MENA: _,
    Region_Pricing_Tooltip_Unknown: _,
    dummy: _,
  };
export {
  _ as CurrencyCodeDescription_AED,
  _ as CurrencyCodeDescription_ARS,
  _ as CurrencyCodeDescription_AUD,
  _ as CurrencyCodeDescription_BGN,
  _ as CurrencyCodeDescription_BRL,
  _ as CurrencyCodeDescription_BYN,
  _ as CurrencyCodeDescription_CAD,
  _ as CurrencyCodeDescription_CHF,
  _ as CurrencyCodeDescription_CLP,
  _ as CurrencyCodeDescription_CNY,
  _ as CurrencyCodeDescription_COP,
  _ as CurrencyCodeDescription_CRC,
  _ as CurrencyCodeDescription_CZK,
  _ as CurrencyCodeDescription_DKK,
  _ as CurrencyCodeDescription_EUR,
  _ as CurrencyCodeDescription_GBP,
  _ as CurrencyCodeDescription_HKD,
  _ as CurrencyCodeDescription_HRK,
  _ as CurrencyCodeDescription_HUF,
  _ as CurrencyCodeDescription_IDR,
  _ as CurrencyCodeDescription_ILS,
  _ as CurrencyCodeDescription_INR,
  _ as CurrencyCodeDescription_JPY,
  _ as CurrencyCodeDescription_KRW,
  _ as CurrencyCodeDescription_KWD,
  _ as CurrencyCodeDescription_KZT,
  _ as CurrencyCodeDescription_MXN,
  _ as CurrencyCodeDescription_MYR,
  _ as CurrencyCodeDescription_NOK,
  _ as CurrencyCodeDescription_NZD,
  _ as CurrencyCodeDescription_PEN,
  _ as CurrencyCodeDescription_PHP,
  _ as CurrencyCodeDescription_PLN,
  _ as CurrencyCodeDescription_QAR,
  _ as CurrencyCodeDescription_RON,
  _ as CurrencyCodeDescription_RUB,
  _ as CurrencyCodeDescription_SAR,
  _ as CurrencyCodeDescription_SEK,
  _ as CurrencyCodeDescription_SGD,
  _ as CurrencyCodeDescription_THB,
  _ as CurrencyCodeDescription_TRY,
  _ as CurrencyCodeDescription_TWD,
  _ as CurrencyCodeDescription_UAH,
  _ as CurrencyCodeDescription_USD,
  _ as CurrencyCodeDescription_UYU,
  _ as CurrencyCodeDescription_Unknown,
  _ as CurrencyCodeDescription_VND,
  _ as CurrencyCodeDescription_ZAR,
  _ as Region_Pricing_Tooltip_CIS,
  _ as Region_Pricing_Tooltip_LATAM,
  _ as Region_Pricing_Tooltip_MENA,
  _ as Region_Pricing_Tooltip_SASIA,
  _ as Region_Pricing_Tooltip_Unknown,
  _ as default,
  _ as dummy,
};
