var _ = `Documentatie`,
  _ = `Startpagina`,
  _ = `Aan de slag`,
  _ = `Winkelaanwezigheid`,
  _ = `Functies`,
  _ = `Financiën`,
  _ = `Verkoop en marketing`,
  _ = `Steamworks SDK`,
  _ = `Cafélicentie`,
  _ = `Steam VR`,
  _ = `Alle weergeven`,
  _ = `Beheerderstools`,
  _ = `Bronnen`,
  _ = `Steam VR`,
  _ = `Steam-internetcaféprogramma`,
  _ = `Steamworks-discussies`,
  _ = `Steamworks-videotutorials`,
  _ = `Nieuws en updates`,
  _ = `Steamworks-blog`,
  _ = `Steam-blog`,
  _ = `Steam VR-blog`,
  _ = `Steam Deck-blog`,
  _ = `Steamworks`,
  _ = `taal`,
  _ = `Taal wijzigen`,
  _ = `Uitloggen`,
  _ = `Inloggen`,
  _ = `Dashboard`,
  _ = `SteamVR Tracking`,
  _ = `Apps en pakketten`,
  _ = `Alle applicaties`,
  _ = `Pakketten weergeven`,
  _ = `Bundels`,
  _ = `Prijzen`,
  _ = `Prijzen (NIEUW!)`,
  _ = `Kortingsbeheer`,
  _ = `Goedkeuringen voor uitverkopen (NIEUW!)`,
  _ = `Uitverkoop-en festivalregistratie`,
  _ = `Steam Next Festival`,
  _ = `Makersstartpagina instellen`,
  _ = `Aangepaste URL voor makersstartpagina instellen`,
  _ = `Marketingtools en -gegevens`,
  _ = `Beheer dagaanbiedingen`,
  _ = `Steam Deck-compatibiliteit`,
  _ = `Ondersteuning`,
  _ = `Tools`,
  _ = `Economie beheren`,
  _ = `Steam-sleutel opzoeken`,
  _ = `Steam-sleutels verbannen`,
  _ = `Sjablonen voor Steam-sleutelpakketten weergeven`,
  _ = `Navigatieverkeer winkel en Steam-platform`,
  _ = `Aanbevolen handelingen voor catalogus`,
  _ = `Meet Steam @ industrieconferenties`,
  _ = `Gebruikers en rechten`,
  _ = `Overzicht`,
  _ = `Bedrijfsgegevens`,
  _ = `Applicaties weergeven`,
  _ = `Gebruikers beheren`,
  _ = `Groepen beheren`,
  _ = `Financiële info`,
  _ = `Documentatie en hulp`,
  _ = `Ontwikkelaarscommunitygroep bezoeken`,
  _ = `Ontwikkelaarsfora bezoeken`,
  _ = `Contact opnemen met Steam Publishing`,
  _ = `Contact opnemen met Steamworks-ondersteuning`,
  _ = `Steamworks-ontwikkelaarsondersteuning`,
  _ = `Zonder affiliatie`,
  _ = `Zoeken op appnaam of -ID`,
  _ = `Documentatie weergeven`,
  _ = `Documentatiearchief weergeven`,
  _ = `Pakketgegevens`,
  _ = `Gebruikersgeschiedenis`,
  _ = `Uitnodigingsgeschiedenis`,
  _ = `Postadressen`,
  _ = `Voorbeeld van nieuwe documentatie bekijken`,
  _ = `Applicaties overdragen`,
  _ = `Applicaties delen`,
  _ = `Directe aankoop`,
  _ = `Bankgegevens betaling weergeven`,
  _ = `Ingediende facturen controleren`,
  _ = `Facturen maken/beheren`,
  _ = `Winkelbeheer`,
  _ = `Spotlights`,
  _ = `Startpagina`,
  _ = `OEM-tools`,
  _ = `OEM-ticketbundels`,
  _ = `Internetcaféprogramma`,
  _ = `Locaties beheren`,
  _ = `Commerciële licenties beheren`,
  _ = `Gebruiksgeschiedenis`,
  _ = `Inhoudsbeperking`,
  _ = `Portemonneefinanciering`,
  _ = `Configuratie`,
  _ = `Activiteitsgeschiedenis`,
  _ = `Goedkeuring voor financiering`,
  _ = `Organisatie wisselen`,
  _ = `Steamworks-organisatie wisselen`,
  _ = `Je Steam-account is lid van meerdere Steamworks-organisaties.`,
  _ = `Veel Steamworks-functies zijn alleen toegankelijk als je daarvoor de benodigde rechten binnen de geselecteerde Steamworks-organisatie hebt.`,
  _ = `Via het keuzemenu hieronder kun je naar een andere organisatie wisselen:`,
  _ = `Wisselen`,
  _ = `Annuleren`,
  _ = `Promotie`,
  _ = `Spel`,
  _ = `Applicatie`,
  _ = `Tool`,
  _ = `Demo`,
  _ = `DLC`,
  _ = `Mod`,
  _ = `Gids`,
  _ = `Configuratie`,
  _ = `Muziek`,
  _ = `Plug-in`,
  _ = `Hardware`,
  _ = `Video`,
  _ = `Serie`,
  _ = `Aflevering`,
  _ = `Film`,
  _ = `Bèta`,
  _ = `Seizoenspas`,
  _ = `Navigatie`,
  _ = {
    Header_Global_Documentation: _,
    Header_Global_Documentation_Home: _,
    Header_Global_Documentation_GettingStarted: _,
    Header_Global_Documentation_StorePresence: _,
    Header_Global_Documentation_Features: _,
    Header_Global_Documentation_Finance: _,
    Header_Global_Documentation_SalesMarketing: _,
    Header_Global_Documentation_SteamworksSDK: _,
    Header_Global_Documentation_PCCafe: _,
    Header_Global_Documentation_SteamVR: _,
    Header_Global_Documentation_Seeall: _,
    Header_Nav_DocumentationAdmin: _,
    Header_Global_Resources: _,
    Header_Global_Resources_SteamVR: _,
    Header_Global_Resources_PCCafe: _,
    Header_Global_Resources_Discussions: _,
    Header_Global_Resources_VideoTutorials: _,
    Header_Global_News: _,
    Header_Global_News_Steamworks: _,
    Header_Global_News_Steam: _,
    Header_Global_News_SteamVR: _,
    Header_Global_News_SteamDeck: _,
    Steamworks_Logo_Label: _,
    global_menu_language: _,
    global_menu_change_language: _,
    global_menu_sign_out: _,
    global_menu_sign_in: _,
    Header_Nav_Dashboard: _,
    Header_Nav_Lighthouse: _,
    Header_Nav_AppsPackages: _,
    Header_Nav_AppsPackages_All: _,
    Header_Nav_AppsPackages_ViewPackages: _,
    Header_Nav_AppsPackages_Bundles: _,
    Header_Nav_AppsPackages_Pricing: _,
    Header_Nav_AppsPackages_PricingNew: _,
    Header_Nav_AppsPackages_SaleApproval: _,
    Header_Nav_AppsPackages_SaleApprovalNew: _,
    Header_Nav_AppsPackages_Events: _,
    Header_Nav_AppsPackages_NextFestRecaps: _,
    Header_Nav_AppsPackages_CreatorHome: _,
    Header_Nav_AppsPackages_CreatorHome_Vanity: _,
    Header_Nav_PublisherMarketingStats: _,
    Header_Nav_DailyDeal_Management: _,
    Header_Nav_SteamDeck_Compat: _,
    Header_Nav_Support: _,
    Header_Nav_Tools: _,
    Header_Nav_Tools_Economy: _,
    Header_Nav_Tools_QueryCDKey: _,
    Header_Nav_Tools_BanCDKeys: _,
    Header_Nav_Tools_CDKeyRestrictions: _,
    Header_Nav_Tools_NavTraffic: _,
    Header_Nav_Tools_HealthChecks: _,
    Header_Nav_Tools_MeetSteam: _,
    Header_Nav_UsersPermissions: _,
    Header_Nav_UsersPermissions_Overview: _,
    Header_Nav_UsersPermissions_CompanyDetails: _,
    Header_Nav_UsersPermissions_Applications: _,
    Header_Nav_UsersPermissions_Users: _,
    Header_Nav_UsersPermissions_Groups: _,
    Header_Nav_FinancialInfo: _,
    Header_Nav_DocumentationHelp: _,
    Header_Nav_DeveloperCommunity: _,
    Header_Nav_DeveloperForums: _,
    Header_Nav_Contact_Steam: _,
    Header_Nav_Contact_Dev_Support: _,
    Header_Nav_Contact_Dev_Support2: _,
    Header_Nav_Unaffiliated: _,
    Header_Search_By_Appid: _,
    Header_Nav_ViewDocumentation: _,
    Header_Nav_ViewDocumentationArchive: _,
    Header_Nav_PackageDetails: _,
    Header_Nav_UserGroupHistory: _,
    Header_Nav_UserInviteHistory: _,
    Header_Nav_MailingAddresses: _,
    Header_Nav_PreviewNewDocumentation: _,
    Header_Nav_TransferRequests: _,
    Header_Nav_ShareApplications: _,
    Header_Nav_DirectPurchasing: _,
    Header_Nav_DirectPurchasing_Config: _,
    Header_Nav_DirectPurchasing_OpenInvoices: _,
    Header_Nav_DirectPurchasing_CreateInvoices: _,
    Header_Nav_StoreAdmin: _,
    Header_Nav_StoreAdmin_Spotlights: _,
    Header_Nav_StoreAdmin_Frontpage: _,
    Header_Nav_OEM: _,
    Header_Nav_OEM_Ticket_Batches: _,
    Header_Nav_Sites: _,
    Header_Nav_Sites_Edit_Sites: _,
    Header_Nav_Sites_Current_Usage: _,
    Header_Nav_Sites_Historical_Usage: _,
    Header_Nav_Sites_Content_Control: _,
    Header_Nav_WalletFunding: _,
    Header_Nav_WalletFunding_Config: _,
    Header_Nav_WalletFunding_Usage: _,
    Header_Nav_WalletFunding_Approval: _,
    change_partner_link: _,
    change_partner_dialog_title: _,
    change_partner_dialog_desc_part1: _,
    change_partner_dialog_desc_part2: _,
    change_partner_dialog_desc_part3: _,
    change_partner_dialog_submit: _,
    change_partner_dialog_cancel: _,
    AppType_TitleCase_Advertising: _,
    AppType_TitleCase_Game: _,
    AppType_TitleCase_Application: _,
    AppType_TitleCase_Tool: _,
    AppType_TitleCase_Demo: _,
    AppType_TitleCase_DLC: `DLC`,
    AppType_TitleCase_Mod: `Mod`,
    AppType_TitleCase_Guide: _,
    AppType_TitleCase_Config: _,
    AppType_TitleCase_Music: _,
    AppType_TitleCase_PlugIn: _,
    AppType_TitleCase_Hardware: _,
    AppType_TitleCase_Video: _,
    AppType_TitleCase_Series: _,
    AppType_TitleCase_Episode: _,
    AppType_TitleCase_Movie: _,
    AppType_TitleCase_Beta: _,
    AppType_TitleCase_DLC_SeasonPass: _,
    Aria_Navigation: _,
  };
export {
  _ as AppType_TitleCase_Advertising,
  _ as AppType_TitleCase_Application,
  _ as AppType_TitleCase_Beta,
  _ as AppType_TitleCase_Config,
  _ as AppType_TitleCase_DLC,
  _ as AppType_TitleCase_DLC_SeasonPass,
  _ as AppType_TitleCase_Demo,
  _ as AppType_TitleCase_Episode,
  _ as AppType_TitleCase_Game,
  _ as AppType_TitleCase_Guide,
  _ as AppType_TitleCase_Hardware,
  _ as AppType_TitleCase_Mod,
  _ as AppType_TitleCase_Movie,
  _ as AppType_TitleCase_Music,
  _ as AppType_TitleCase_PlugIn,
  _ as AppType_TitleCase_Series,
  _ as AppType_TitleCase_Tool,
  _ as AppType_TitleCase_Video,
  _ as Aria_Navigation,
  _ as Header_Global_Documentation,
  _ as Header_Global_Documentation_Features,
  _ as Header_Global_Documentation_Finance,
  _ as Header_Global_Documentation_GettingStarted,
  _ as Header_Global_Documentation_Home,
  _ as Header_Global_Documentation_PCCafe,
  _ as Header_Global_Documentation_SalesMarketing,
  _ as Header_Global_Documentation_Seeall,
  _ as Header_Global_Documentation_SteamVR,
  _ as Header_Global_Documentation_SteamworksSDK,
  _ as Header_Global_Documentation_StorePresence,
  _ as Header_Global_News,
  _ as Header_Global_News_Steam,
  _ as Header_Global_News_SteamDeck,
  _ as Header_Global_News_SteamVR,
  _ as Header_Global_News_Steamworks,
  _ as Header_Global_Resources,
  _ as Header_Global_Resources_Discussions,
  _ as Header_Global_Resources_PCCafe,
  _ as Header_Global_Resources_SteamVR,
  _ as Header_Global_Resources_VideoTutorials,
  _ as Header_Nav_AppsPackages,
  _ as Header_Nav_AppsPackages_All,
  _ as Header_Nav_AppsPackages_Bundles,
  _ as Header_Nav_AppsPackages_CreatorHome,
  _ as Header_Nav_AppsPackages_CreatorHome_Vanity,
  _ as Header_Nav_AppsPackages_Events,
  _ as Header_Nav_AppsPackages_NextFestRecaps,
  _ as Header_Nav_AppsPackages_Pricing,
  _ as Header_Nav_AppsPackages_PricingNew,
  _ as Header_Nav_AppsPackages_SaleApproval,
  _ as Header_Nav_AppsPackages_SaleApprovalNew,
  _ as Header_Nav_AppsPackages_ViewPackages,
  _ as Header_Nav_Contact_Dev_Support,
  _ as Header_Nav_Contact_Dev_Support2,
  _ as Header_Nav_Contact_Steam,
  _ as Header_Nav_DailyDeal_Management,
  _ as Header_Nav_Dashboard,
  _ as Header_Nav_DeveloperCommunity,
  _ as Header_Nav_DeveloperForums,
  _ as Header_Nav_DirectPurchasing,
  _ as Header_Nav_DirectPurchasing_Config,
  _ as Header_Nav_DirectPurchasing_CreateInvoices,
  _ as Header_Nav_DirectPurchasing_OpenInvoices,
  _ as Header_Nav_DocumentationAdmin,
  _ as Header_Nav_DocumentationHelp,
  _ as Header_Nav_FinancialInfo,
  _ as Header_Nav_Lighthouse,
  _ as Header_Nav_MailingAddresses,
  _ as Header_Nav_OEM,
  _ as Header_Nav_OEM_Ticket_Batches,
  _ as Header_Nav_PackageDetails,
  _ as Header_Nav_PreviewNewDocumentation,
  _ as Header_Nav_PublisherMarketingStats,
  _ as Header_Nav_ShareApplications,
  _ as Header_Nav_Sites,
  _ as Header_Nav_Sites_Content_Control,
  _ as Header_Nav_Sites_Current_Usage,
  _ as Header_Nav_Sites_Edit_Sites,
  _ as Header_Nav_Sites_Historical_Usage,
  _ as Header_Nav_SteamDeck_Compat,
  _ as Header_Nav_StoreAdmin,
  _ as Header_Nav_StoreAdmin_Frontpage,
  _ as Header_Nav_StoreAdmin_Spotlights,
  _ as Header_Nav_Support,
  _ as Header_Nav_Tools,
  _ as Header_Nav_Tools_BanCDKeys,
  _ as Header_Nav_Tools_CDKeyRestrictions,
  _ as Header_Nav_Tools_Economy,
  _ as Header_Nav_Tools_HealthChecks,
  _ as Header_Nav_Tools_MeetSteam,
  _ as Header_Nav_Tools_NavTraffic,
  _ as Header_Nav_Tools_QueryCDKey,
  _ as Header_Nav_TransferRequests,
  _ as Header_Nav_Unaffiliated,
  _ as Header_Nav_UserGroupHistory,
  _ as Header_Nav_UserInviteHistory,
  _ as Header_Nav_UsersPermissions,
  _ as Header_Nav_UsersPermissions_Applications,
  _ as Header_Nav_UsersPermissions_CompanyDetails,
  _ as Header_Nav_UsersPermissions_Groups,
  _ as Header_Nav_UsersPermissions_Overview,
  _ as Header_Nav_UsersPermissions_Users,
  _ as Header_Nav_ViewDocumentation,
  _ as Header_Nav_ViewDocumentationArchive,
  _ as Header_Nav_WalletFunding,
  _ as Header_Nav_WalletFunding_Approval,
  _ as Header_Nav_WalletFunding_Config,
  _ as Header_Nav_WalletFunding_Usage,
  _ as Header_Search_By_Appid,
  _ as Steamworks_Logo_Label,
  _ as change_partner_dialog_cancel,
  _ as change_partner_dialog_desc_part1,
  _ as change_partner_dialog_desc_part2,
  _ as change_partner_dialog_desc_part3,
  _ as change_partner_dialog_submit,
  _ as change_partner_dialog_title,
  _ as change_partner_link,
  _ as default,
  _ as global_menu_change_language,
  _ as global_menu_language,
  _ as global_menu_sign_in,
  _ as global_menu_sign_out,
};
