var _ = `Конфиденциальная информация Valve`,
  _ = `Эта страница с ограниченным доступом содержит конфиденциальную информацию Valve. Чтобы получить доступ к странице, вы должны принять соглашение о неразглашении и/или лицензионное соглашение Valve.`,
  _ = `Steamworks — это набор инструментов и служб от <1>Valve</1>, позволяющих настроить и поддерживать игру в <2>Steam</2>.`,
  _ = `Связаться со службой поддержки`,
  _ = `Ошибка при загрузке информации о ценах. Повторите попытку позже.`,
  _ = `О региональном ценообразовании`,
  _ = `Цена для каждого продукта в Steam указывается и отображается в различных валютах (%1$s) для разных <1>групп регионов (%2$s)</1>. В Steam есть инструменты, с помощью которых можно установить цену на игру и управлять ею на соответствующем уровне для каждого регионального рынка.`,
  _ = `Цены на игры в каждой валюте и для каждой группы регионов остаются полностью на ваше усмотрение.`,
  _ = `Дополнительную информацию можно найти в %1$s`,
  _ = `документации о ценообразовании`,
  _ = `Задать и изменить цены на игру можно на %1$s`,
  _ = `Открыть панель управления ценами`,
  _ = `Задать и изменить цены на игру можно на панели управления ценами`,
  _ = `Последнее обновление данных о конвертации валют: %1$s`,
  _ = `Инструмент анализа конвертации цен`,
  _ = `Этот инструмент демонстрирует работу трёх методов конвертации цен и валют:`,
  _ = `%1$s — этот метод учитывает несколько факторов для каждой валюты, включая локальную покупательную способность, ожидаемую стоимость сопоставимых развлекательных товаров и курс обмена валют.`,
  _ = `%1$s — этот метод использует общедоступные данные о покупательной способности пользователей в определённой стране или регионе.`,
  _ = `%1$s — этот метод использует курс обмена валют в указанное время.`,
  _ = `Базовая валюта`,
  _ = `Базовая цена`,
  _ = `Метод конвертации`,
  _ = `Валюта`,
  _ = `Многофакторная конвертация`,
  _ = `Конвертация только на базе покупательной способности`,
  _ = `Конвертация только на базе курса обмена`,
  _ = `Цены для регионов (в долларах США)`,
  _ = `Регион`,
  _ = `dummy`,
  _ = `%1$s (%2$s) — опрос о контенте`,
  _ = `Опрос о контенте`,
  _ = `%1$s (%2$s) — опросы о контенте`,
  _ = `Опросы о контенте`,
  _ = `Нет приложения с таким номером. Проверьте адрес и повторите попытку.`,
  _ = `Доступ запрещён`,
  _ = `Вы не вошли в аккаунт`,
  _ = `Итоги`,
  _ = `Ниже перечислен полный список тестов, выполненных в ходе данной проверки, и их результаты.`,
  _ = `Ниже приведены итоги отдельных тестов и присвоенных в результате категорий совместимости.`,
  _ = `Ниже приведены результаты тестов, которые позволяют присвоить игре категорию «Можно играть».`,
  _ = `Параметр`,
  _ = `Значение`,
  _ = `Описание:`,
  _ = `Вот как эта информация будет отображаться пользователям. В будущем её отображение в магазине может измениться.`,
  _ = `Предыдущие отчёты`,
  _ = `Результаты проверки`,
  _ = `Результат`,
  _ = `Тест`,
  _ = `Комментарии`,
  _ = `Влияние на категорию`,
  _ = `Пройдено`,
  _ = `Не пройдено`,
  _ = `Не пройдено`,
  _ = `---`,
  _ = `Это предыдущий результат от %1$s`,
  _ = `Вы видите опубликованный отчёт`,
  _ = `Опубликовано: %1$s`,
  _ = `Дата проверки: %1$s`,
  _ = `Посмотреть документацию`,
  _ = `Опубликовать результаты`,
  _ = `Опубликовать результаты проверки на совместимость?`,
  _ = `Вы уверены, что хотите опубликовать эти результаты? Они сразу будут видны пользователям магазина Steam.`,
  _ = `Неизвестная ошибка. Повторите попытку.`,
  _ = `Запрос на проверку`,
  _ = `Запрос в процессе обработки`,
  _ = `Запрос закрыт`,
  _ = `Показать подробности запроса`,
  _ = `Обсудить этот отчёт с командой тестирования`,
  _ = `Введите вопросы или комментарии`,
  _ = `Опишите здесь изменения в вашей новой сборке`,
  _ = `Если вы обновили сборку игры в Steam, чтобы исправить вышеуказанные проблемы, выберите ветку и снова отправьте игру на проверку.`,
  _ = `Выберите ветку и отправьте её на повторную проверку совместимости со Steam Deck, которая будет включать тестирование на Steam Machine.`,
  _ = `Отправить на повторную проверку`,
  _ = `Если вы внесли изменения в игровую сборку после последней проверки, вы можете запросить новую проверку совместимости.`,
  _ = `Опишите причину, по которой вы запрашиваете повторную проверку. Среди наиболее распространённых причин повторной проверки:`,
  _ = `Вы изменили свою сборку, чтобы решить проблемы, которые были выявлены во время предыдущей проверки на совместимость. Опишите конкретные проблемы, которые, по вашему мнению, были решены.`,
  _ = `Вы выпустили или планируете выпустить новую версию своей игры и хотите, чтобы информация была обновлена.`,
  _ = `Запрос на повторное тестирование с помощью ветки «%1$s». Сборка игры в Steam была обновлена, чтобы исправить найденные проблемы.`,
  _ = `История проверок`,
  _ = `Отображение в магазине`,
  _ = `Совместимость с оборудованием: %1$s (%2$s)`,
  _ = `Опубликовано`,
  _ = `Не опубликовано`,
  _ = `История`,
  _ = `Рекомендованная среда выполнения`,
  _ = `Это версия вашей игры (контента / исполняемых файлов), которая будет по умолчанию доступна пользователям на Steam Deck.`,
  _ = `Ожидаемый формат ввода`,
  _ = `Требуется H.264`,
  _ = `Тестовая версия Proton`,
  _ = `ID тестовой сборки`,
  _ = `Отладка RPO`,
  _ = `Отладка FDM`,
  _ = `Включить TSO`,
  _ = `Статус поддержки игры на %1$s — «Неизвестно», поскольку тестирование %1$s не завершено`,
  _ = `Ваша игра не поддерживается на %1$s на данный момент`,
  _ = `Ваша игра не поддерживается полноценно на %1$s из-за проблем Proton или %1$s. Мы зафиксировали эти проблемы и работаем над их решением. На данный момент ваша игра не будет запускаться и корректно работать на %1$s.`,
  _ = `В вашу игру можно играть на %1$s`,
  _ = `В вашу игру можно играть на %1$s, но от пользователей требуются дополнительные действия или настройка игры. Вы можете исправить проблемы, описанные ниже, и снова отправить игру на проверку совместимости.`,
  _ = `Ваша игра полностью совместима со %1$s!`,
  _ = `Поздравляем! Ваша игра отлично работает на %1$s, и это будет отображено в магазине Steam и в библиотеках пользователей на %1$s.`,
  _ = `Хотите рассказать об этом достижении фанатам? Поделитесь с ними ссылкой на стильную целевую страницу: %1$s`,
  _ = `Ваша игра не проверялась на Steam Machine`,
  _ = `Ваша игра не проверялась на Steam Frame`,
  _ = `Это причина присвоения категории «Можно играть»`,
  _ = `Это причина присвоения категории «Не поддерживается»`,
  _ = `Отображается как сообщение с информацией для пользователей`,
  _ = `Неверно`,
  _ = `Запуск лаунчера`,
  _ = `Лаунчер`,
  _ = `Контроллер в лаунчере`,
  _ = `Текст в лаунчере`,
  _ = `Клавиатура в лаунчере`,
  _ = `Предупреждения устройства`,
  _ = `Запуск игры`,
  _ = `Одиночная игра`,
  _ = `Локальный мультиплеер`,
  _ = `Онлайн-мультиплеер`,
  _ = `Античит`,
  _ = `Античит`,
  _ = `Античит или многопользовательский режим`,
  _ = `Стандартные настройки контроллера`,
  _ = `Клавиатура`,
  _ = `Иконки контроллера`,
  _ = `Качество управления по умолчанию`,
  _ = `Отображение`,
  _ = `Вывод изображения`,
  _ = `Нативное разрешение`,
  _ = `Читабельность текста`,
  _ = `Звук`,
  _ = `Меню`,
  _ = `Кроссплатформенное сохранение в Steam Cloud`,
  _ = `Одиночная игра вне сети`,
  _ = `Внешний контроллер (основной игрок)`,
  _ = `Внешний контроллер (локальный мультиплеер)`,
  _ = `Первый запуск`,
  _ = `Первый запуск с контроллером`,
  _ = `Первый запуск вне сети`,
  _ = `Функциональность игры`,
  _ = `Виртуальная реальность`,
  _ = `Примечание`,
  _ = `Успешный выход`,
  _ = `Успешный выход (лаунчер)`,
  _ = `Одновременный ввод с геймпада и мыши`,
  _ = `Вспомогательная функция: редактор карт`,
  _ = `Поддержка ограничения частоты кадров`,
  _ = `Выделение нескольких окон (автоматически)`,
  _ = `Выделение нескольких окон (вручную)`,
  _ = `Программное обеспечение`,
  _ = `Одновременный ввод с геймпада и мыши`,
  _ = `Текстовый ввод`,
  _ = `Ввод звука`,
  _ = `Выход из спящего режима`,
  _ = `Вывод с экрана масштабирован`,
  _ = `Внешние ссылки / Контекст`,
  _ = `Больше не доступно`,
  _ = `Шрифт поддерживает все символы`,
  _ = `Настройки экрана сохраняются на устройстве, не в облаке`,
  _ = `Управление с клавиатуры по умолчанию`,
  _ = `Включён стандартный контроллер`,
  _ = `Облачные сохранения включены по умолчанию`,
  _ = `Периферийные устройства (клавиатура)`,
  _ = `Периферийные устройства (веб-камера)`,
  _ = `Периферийные устройства (USB-гитара)`,
  _ = `Поддержка HDR`,
  _ = `Поддержка ОС`,
  _ = `Качество стандартного управления на Steam Machine`,
  _ = `Качество VR-трансляции на Steam Machine`,
  _ = `Поддержка VR-трансляции на Steam Machine`,
  _ = `Предупреждения устройства Steam Machine`,
  _ = `Экран для Steam Machine`,
  _ = `Звук Steam Machine`,
  _ = `Steam Machine`,
  _ = `SteamOS`,
  _ = `Steam Deck`,
  _ = `Steam Frame (в самостоятельном режиме)`,
  _ = `Запросите проверку на Steam Deck, что станет первым шагом тестирования для получения категории совместимости со %1$s.`,
  _ = `Добро пожаловать! Здесь вы можете отправить свою игру на проверку совместимости со Steam Frame в самостоятельном режиме.`,
  _ = `Контрольный список для проверки на совместимость со Steam Frame в самостоятельном режиме`,
  _ = `Далее перечислены некоторые из наиболее важных критериев, на которые мы обращаем внимание при проверке игры на совместимость со Steam Frame. Заполните форму ниже и сообщите, какую сборку или ветку своей игры вы хотите протестировать, и она будет добавлена в очередь на проверку. Когда проверка будет завершена, вы получите по эл. почте уведомление с её итогами, после чего на данную страницу будут добавлены подробные результаты тестирования.`,
  _ = `Чтобы узнать больше о процессе проверки, ознакомьтесь с документацией о %1$s.`,
  _ = `процессе проверки на совместимость со Steam Frame в самостоятельном режиме.`,
  _ = `Вот несколько самых важных пунктов, на которые мы будем опираться, чтобы присвоить вашей игре категорию совместимости со Steam Frame. Чтобы начать процесс проверки на совместимость, ответьте на следующие вопросы на основании имеющихся у вас сведений.`,
  _ = `Невыпущенную игру нельзя отправить на проверку`,
  _ = `Будет ли ваша игра хорошо работать на Steam Deck? Мы разработали специальный процесс проверки, в рамках которого наша команда протестирует вашу игру. Игры, в которые можно без проблем играть на Steam Deck, получат пометку «Полностью совместима».`,
  _ = `Добро пожаловать! Здесь вы можете отправить свою игру на проверку совместимости со Steam Deck.`,
  _ = `Ниже перечислены некоторые из наиболее важных критериев, на которые мы обращаем внимание при проверке игры на совместимость со Steam Deck. Заполните форму ниже и сообщите, какую сборку или ветку своей игры вы хотите протестировать, и она будет добавлена в очередь на проверку. Когда проверка будет завершена, вы получите по эл. почте уведомление с её итогами, после чего на данную страницу будут добавлены подробные результаты тестирования.`,
  _ = `Вы можете отправить свою игру, даже если она не соответствует всем критериям получения пометки <b>«Полностью совместима»</b>. Мы используем данные самостоятельного тестирования для того, чтобы распределять игры для проверки, а также сообщать о любых проблемах совместимости вашей игры наиболее понятным образом.`,
  _ = `Чтобы узнать больше о процессе проверки, ознакомьтесь с документацией о %1$s и %2$s.`,
  _ = `процессе проверки на совместимость со Steam Deck`,
  _ = `дополнительными рекомендациями для Steam Deck`,
  _ = `Контрольный список для самостоятельной проверки на совместимость со Steam Deck`,
  _ = `Вот несколько самых важных пунктов, на которые мы будем опираться, чтобы присвоить вашей игре категорию совместимости со Steam Deck. Чтобы начать процесс проверки на совместимость со Steam Deck, ответьте на следующие вопросы на основании имеющихся у вас сведений.`,
  _ = `В настоящее время процесс проверки на совместимость со Steam Deck доступен только для игр. Для приложений другого типа, например дополнений, инструментов или саундтреков, подобный процесс не предусмотрен, за исключением особых случаев.`,
  _ = `Поддержка контроллеров`,
  _ = `Ввод текста`,
  _ = `Отображение`,
  _ = `Функциональность`,
  _ = `Steam Cloud`,
  _ = `Лаунчер`,
  _ = `Ветка`,
  _ = `Ветка, которую нужно использовать при проверке`,
  _ = `Готова к проверке`,
  _ = `Ваша сборка будет отмечена как готовая к проверке на совместимость со Steam Deck. Через несколько дней вы получите электронное письмо с результатами.`,
  _ = `Ниже вы можете оставить комментарии, чтобы помочь ускорить процесс тестирования или предоставить данные тестовых аккаунтов для входа на сторонние серверы.`,
  _ = `Оставьте комментарии здесь`,
  _ = `Запросить помощь по поводу этой проверки`,
  _ = `Подробную информацию можно найти в отчёте о тестировании на сайте поддержки`,
  _ = `Создать обращение в службу поддержку по поводу проверки совместимости со Steam Deck`,
  _ = `Включите в обращение вопросы или комментарии для команды тестирования.`,
  _ = `Если у вас есть вопросы о процессе проверки на совместимость или о результатах проверки вашей игры, задайте их ниже.`,
  _ = `Обращаем ваше внимание, что если вы хотите запросить повторную проверку для своей игры, вам следует воспользоваться кнопкой «ОТПРАВИТЬ НА ПОВТОРНУЮ ПРОВЕРКУ», а не просить об этом здесь.`,
  _ = `У меня есть вопрос или комментарий по поводу отчёта о совместимости со Steam Deck: `,
  _ = `Да, в моей игре есть полная поддержка контроллера: все функции доступны с его стандартными настройками`,
  _ = `Да, в моей игре отображаются подсказки для Steam Deck или контроллера Xbox при нажатии кнопок на контроллере`,
  _ = `В моей игре не требуется ввод текста или игра вызывает подходящие API ввода текста Steam`,
  _ = `В моей игре не требуется ввод текста`,
  _ = `Моя игра вызывает подходящие API клавиатуры / ввода текста Steam, когда нужен ввод текста от пользователей`,
  _ = `Моя игра не использует API Steam, когда нужен ввод текста от пользователей`,
  _ = `У моей игры нет файлов сохранений`,
  _ = `В моей игре есть файлы сохранений, но для них не используется Steam Cloud`,
  _ = `Моя игра использует Steam Cloud для сохранений. Есть только сборка для Windows`,
  _ = `Моя игра использует Steam Cloud и поддерживает кроссплатформенные сохранения (например, Windows/Linux)`,
  _ = `Моя игра использует Steam Cloud и не поддерживает кроссплатформенные сохранения (например, Windows/Linux)`,
  _ = `Да, моя игра может работать с разрешением 1 280 на 800 пикселей (предпочтительно) или 1 280 на 720 пикселей.`,
  _ = `Да, минимальная высота шрифта в моей игре составляет не менее 9 пикселей при разрешении 1 280 на 800 пикселей.`,
  _ = `У моей игры нет лаунчера, или лаунчером можно управлять с помощью контроллера.`,
  _ = `Моя игра поддерживает Steam Cloud или у игры нет файлов сохранений.`,
  _ = `Моя игра поддерживает кроссплатформенные сохранения или работает только на одной платформе (Linux/Windows).`,
  _ = `Если не указано другое, мы проверим вашу сборку для Windows, используя Proton.`,
  _ = `По возможности протестировать мою сборку для Linux вместо моей сборки для Windows.`,
  _ = `Моя игра не использует лаунчер или внешние инструменты настройки`,
  _ = `Моя игра использует лаунчер, и у него есть полная поддержка контроллера`,
  _ = `Моя игра использует лаунчер, и он не полностью функционален, если у пользователя есть только контроллер, но нет клавиатуры или мыши`,
  _ = `(Хотя кроссплатформенные сохранения не являются требованием для получения категории «Полностью совместима», они очень ценны для пользователей, которые могут иногда играть на ПК с Windows, а иногда — на Steam Deck со сборкой для Linux. Подробнее об этом можно прочитать в %1$s.)`,
  _ = `документации`,
  _ = `(Экран Steam Deck гораздо меньше, чем большинство экранов ПК. Если в вашей игре есть мелкий текст, его может быть сложно или невозможно прочитать на экране Steam Deck, даже если его комфортно читать на обычном мониторе.)`,
  _ = `(Обычно к Steam Deck не подключена клавиатура, поэтому для ввода текста игроки используют экранную клавиатуру, а Steam предоставляет API, чтобы встроенными экранными клавиатурами было просто пользоваться. Если пользователям приходится открывать клавиатуру вручную, ваша игра не сможет получить категорию «Полностью совместима». Ознакомьтесь с %1$s.)`,
  _ = `рекомендациями для элементов ввода`,
  _ = `(Если ваша игра использует лаунчер, к нему применяются такие же требования совместимости, как и к игре: нужно, чтобы его можно было использовать с применением лишь встроенных элементов управления Steam Deck, текст должен быть читабельным и так далее. Если лаунчер не соответствует этим требованиям, игра не получит пометку «Полностью совместима», даже если сама по себе она могла быть попасть в эту категорию. Ознакомьтесь с %1$s>.)`,
  _ = `рекомендациями для лаунчера`,
  _ = `(Большая часть пользователей Steam Deck играет и на ПК. Облачные сохранения не являются требованием для получения категории «Полностью совместима», но они очень ценны для пользователей: добавление поддержки %1$s для сохранения игр позволит пользователям сохранять игры на компьютере и продолжать игру на Steam Deck или наоборот.)`,
  _ = `Steam Cloud`,
  _ = `(Примечание: для получения категории «Полностью совместима» требуется полная поддержка контроллеров.)`,
  _ = `Ваша игра добавлена в очередь на проверку`,
  _ = `Мы скоро проверим игру и свяжемся с вами, если у нас возникнут вопросы.`,
  _ = `Завершите проверку сборки для Steam, прежде чем отправлять игру на проверку совместимости с оборудованием.`,
  _ = `Ваша игра не поддерживается на Steam Deck на данный момент`,
  _ = `Ваша игра не поддерживается полноценно на Steam Deck из-за проблем в Proton или Steam Deck. Мы зафиксировали эти проблемы и работаем над их решением. На данный момент ваша игра не будет запускаться и корректно работать на Steam Deck.`,
  _ = `В вашу игру можно играть на Steam Deck`,
  _ = `В вашу игру можно играть на Steam Deck, но от пользователей требуются дополнительные действия или настройка игры. Вы можете исправить проблемы, описанные ниже, и снова отправить игру на проверку совместимости со Steam Deck.`,
  _ = `Сборка`,
  _ = `По возможности протестировать мою сборку для Android вместо моей сборки для Windows.`,
  _ = `Протестировать сборку для Windows`,
  _ = `Протестировать сборку для Linux`,
  _ = `Должны ли мы проверить обычную (2D) или VR-версию (если она доступна)?`,
  _ = `2D`,
  _ = `VR`,
  _ = `Не применимо к %1$s-продуктам`,
  _ = `Полностью совместима (опция «Очистить статус оценки производительности» не использовалась)`,
  _ = `Полностью совместима (опция «Очистить статус оценки производительности» использовалась как минимум один раз)`,
  _ = `Можно играть (опция «Очистить статус оценки производительности» не использовалась)`,
  _ = `Можно играть (опция «Очистить статус оценки производительности» использовалась как минимум один раз)`,
  _ = `Unsupported`,
  _ = `Не является VR-игрой (не оценивается)`,
  _ = `Оверлей оценки производительности`,
  _ = `Используйте оверлей оценки производительности, чтобы добавить ответ ниже. Дополнительную информацию можно найти здесь: «%1$s».`,
  _ = `Документация о производительности VR`,
  _ = `(Если в вашей игре есть мелкий текст, его может быть сложно или невозможно прочитать на экране Steam Frame, даже если его комфортно читать на обычном мониторе.)`,
  _ = `(Обычно к Steam Frame не подключена клавиатура, поэтому для ввода текста игроки используют экранную клавиатуру, а Steam предоставляет API, чтобы встроенными экранными клавиатурами было просто пользоваться. Если пользователям приходится открывать клавиатуру вручную, ваша игра не сможет получить категорию «Полностью совместима». Ознакомьтесь с %1$s.)`,
  _ = `Контрольный список для проверки на совместимость со Steam Frame`,
  _ = `(Если ваша игра использует лаунчер, к нему применяются такие же требования совместимости, как и к игре: нужно, чтобы его можно было использовать с применением лишь встроенных элементов управления Steam Frame, текст должен быть читабельным и так далее. Если лаунчер не соответствует этим требованиям, игра не получит пометку «Полностью совместима», даже если сама по себе она могла быть попасть в эту категорию. Ознакомьтесь с %1$s>.)`,
  _ = `(Большая часть пользователей Steam Frame играет и на ПК. Облачные сохранения не являются требованием для получения категории «Полностью совместима», но они очень ценны для пользователей: добавление поддержки %1$s для сохранения игр позволит пользователям сохранять игры на компьютере и продолжать игру на Steam Frame или наоборот.)`,
  _ = `(Хотя кроссплатформенные сохранения не являются требованием для получения категории «Полностью совместима», они очень ценны для пользователей, которые могут иногда играть на ПК с Windows, а иногда — на Steam Frame со сборкой для Linux. Подробнее об этом можно прочитать в %1$s.)`,
  _ = `Да, в моей игре отображаются подсказки для Steam Frame/Deck или контроллера Xbox при нажатии кнопок на контроллере`,
  _ = `Если для получения результата оценки производительности выше потребовалось хотя бы один раз использовать опцию «Очистить статус оценки производительности», выберите одну или несколько причин ниже.`,
  _ = `Производительность снижается при запуске игры`,
  _ = `Производительность снижается на экранах загрузки`,
  _ = `Другое (опишите подробнее)`,
  _ = `Вы запрашиваете проверку для Android, но у %1$s отсутствуют соответствующие хранилища.`,
  _ = `вашего комплекта Developer Comp`,
  _ = `dummy`,
  _ = {
    Valve_Confidential: _,
    Valve_Confidential_Description: _,
    Footer_Description: _,
    Footer_Sitemap_ContactSupport: _,
    PricingExplorer_LoadError: _,
    PricingExplorer_About_Title: _,
    PricingExplorer_About_Desc1: _,
    PricingExplorer_About_Desc2: _,
    PricingExplorer_About_Link1: _,
    PricingExplorer_About_LinkName1: _,
    PricingExplorer_About_Link2: _,
    PricingExplorer_About_LinkName2: _,
    PricingExplorer_About_Dash: _,
    PricingExplorer_About_LastUpdated: _,
    PricingExplorer_Explore_title: _,
    PricingExplorer_Explore_desc1: _,
    PricingExplorer_Explore_line1: _,
    PricingExplorer_Explore_line2: _,
    PricingExplorer_Explore_line3: _,
    PricingExplorer_Base: _,
    PricingExplorer_BasePrice: _,
    PricingExplorer_TableHeader: _,
    PricingExplorer_Column1: _,
    PricingExplorer_Column2: _,
    PricingExplorer_Column3: _,
    PricingExplorer_Column4: _,
    PricingExplorer_Regions_TableHeader: _,
    PricingExplorer_Regions_Column1: _,
    Pricing_Dummy: _,
    ContentSurvey_Title: _,
    ContentSurvey_Title_Default: _,
    ContentSurvey_History_Title: _,
    ContentSurvey_History_Title_Default: _,
    ContentSurvey_InvalidApp: _,
    PartnerSite_PermissionDenied: _,
    PartnerSite_NotLoggedIn: _,
    SteamDeck_BuildReview_Status_Raw_Title: _,
    SteamDeck_BuildReview_Status_Raw_Description: _,
    SteamDeck_BuildReview_Status_TestProperties_Description: _,
    SteamDeck_BuildReview_Status_TestProperties_Playable: _,
    SteamDeck_BuildReview_Status_TestProperty_Name: _,
    SteamDeck_BuildReview_Status_TestProperty_Value: _,
    SteamDeck_BuildReview_Status_TestProperty_Desc: _,
    SteamDeck_BuildReview_Status_Description: _,
    SteamDeck_BuildReview_Header_History: _,
    SteamDeck_BuildReview_Header_Results: _,
    SteamDeck_BuildReview_Status_Raw_Result: _,
    SteamDeck_BuildReview_Status_Raw_Test: _,
    SteamDeck_BuildReview_Status_Raw_Comment: _,
    SteamDeck_BuildReview_Status_Raw_Impact: _,
    SteamDeck_BuildReview_Status_Pass: _,
    SteamDeck_BuildReview_Status_Fail: _,
    SteamDeck_BuildReview_Status_FailMinor: _,
    SteamDeck_BuildReview_Status_NotApplicable: `---`,
    SteamDeck_BuildReview_Viewing_Historical: _,
    SteamDeck_BuildReview_Viewing_Published: _,
    SteamDeck_BuildReview_PublishedOn: _,
    SteamDeck_BuildReview_ReportedOn: _,
    SteamDeck_BuildReview_Documentation: _,
    SteamDeck_BuildReview_PublishResults: _,
    SteamDeck_BuildReview_PublishDialog_Title: _,
    SteamDeck_BuildReview_PublishDialog_Body: _,
    SteamDeck_BuildReview_UnknownError: _,
    SteamDeck_BuildReview_Help_Request_Title: _,
    SteamDeck_BuildReview_RequestStatusActive: _,
    SteamDeck_BuildReview_RequestStatusClosed: _,
    SteamDeck_BuildReview_InReview_ViewTicket: _,
    SteamDeck_BuildReview_Create_HelpRequest: _,
    SteamDeck_BuildReview_Create_HelpRequest_NotesDefault: _,
    SteamDeck_BuildReview_Create_HelpRequest_NotesDefault_Rereview: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label_Machine: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Button: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_1: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2a: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2b: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Ticket_Content: _,
    SteamDeck_BuildReview_CompatibilityTests: _,
    SteamDeck_BuildReview_Status_Title: _,
    SteamDeck_HardwareCompatibility_Title: _,
    SteamDeck_AppLanding_Published: _,
    SteamDeck_AppLanding_Unpublished: _,
    SteamDeck_AppLanding_History: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RecommendedRuntime: _,
    SteamDeckVerified_TestDisplayName_TestPropertyDescription_RecommendedRuntime:
      _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_ExpectedInput: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RequiresH264: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TestedProtonVersion: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TestedBuildID: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RPODebug: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_FDMDebug: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TSOEnable: _,
    SteamHardware_BuildReview_Unknown_Title: _,
    SteamHardware_BuildReview_Unsupported_Title: _,
    SteamHardware_BuildReview_Unsupported_Description: _,
    SteamHardware_BuildReview_Playable_Title: _,
    SteamHardware_BuildReview_Playable_Description: _,
    SteamHardware_BuildReview_Verified_Title: _,
    SteamHardware_BuildReview_Verified_Description: _,
    SteamHardware_BuildReview_Verified_Share: _,
    SteamHardware_Machine_Unknown: _,
    SteamHardware_Frame_Unknown: _,
    SteamHardware_RatingImpact_Playable: _,
    SteamHardware_RatingImpact_Unsupported: _,
    SteamHardware_RatingImpact_Informational: _,
    SteamDeckVerified_TestDisplayName_0: _,
    SteamDeckVerified_TestDisplayName_1: _,
    SteamDeckVerified_TestDisplayName_2: _,
    SteamDeckVerified_TestDisplayName_3: _,
    SteamDeckVerified_TestDisplayName_4: _,
    SteamDeckVerified_TestDisplayName_5: _,
    SteamDeckVerified_TestDisplayName_6: _,
    SteamDeckVerified_TestDisplayName_7: _,
    SteamDeckVerified_TestDisplayName_8: _,
    SteamDeckVerified_TestDisplayName_9: _,
    SteamDeckVerified_TestDisplayName_10: _,
    SteamDeckVerified_TestDisplayName_11: _,
    SteamDeckVerified_TestDisplayName_12: _,
    SteamDeckVerified_TestDisplayName_13: _,
    SteamDeckVerified_TestDisplayName_14: _,
    SteamDeckVerified_TestDisplayName_15: _,
    SteamDeckVerified_TestDisplayName_16: _,
    SteamDeckVerified_TestDisplayName_17: _,
    SteamDeckVerified_TestDisplayName_18: _,
    SteamDeckVerified_TestDisplayName_19: _,
    SteamDeckVerified_TestDisplayName_20: _,
    SteamDeckVerified_TestDisplayName_21: _,
    SteamDeckVerified_TestDisplayName_22: _,
    SteamDeckVerified_TestDisplayName_23: _,
    SteamDeckVerified_TestDisplayName_24: _,
    SteamDeckVerified_TestDisplayName_25: _,
    SteamDeckVerified_TestDisplayName_26: _,
    SteamDeckVerified_TestDisplayName_27: _,
    SteamDeckVerified_TestDisplayName_29: _,
    SteamDeckVerified_TestDisplayName_30: _,
    SteamDeckVerified_TestDisplayName_31: _,
    SteamDeckVerified_TestDisplayName_32: _,
    SteamDeckVerified_TestDisplayName_33: _,
    SteamDeckVerified_TestDisplayName_34: _,
    SteamDeckVerified_TestDisplayName_35: _,
    SteamDeckVerified_TestDisplayName_36: _,
    SteamDeckVerified_TestDisplayName_37: _,
    SteamDeckVerified_TestDisplayName_38: _,
    SteamDeckVerified_TestDisplayName_39: _,
    SteamDeckVerified_TestDisplayName_40: _,
    SteamDeckVerified_TestDisplayName_41: _,
    SteamDeckVerified_TestDisplayName_42: _,
    SteamDeckVerified_TestDisplayName_43: _,
    SteamDeckVerified_TestDisplayName_44: _,
    SteamDeckVerified_TestDisplayName_45: _,
    SteamDeckVerified_TestDisplayName_46: _,
    SteamDeckVerified_TestDisplayName_47: _,
    SteamDeckVerified_TestDisplayName_48: _,
    SteamDeckVerified_TestDisplayName_49: _,
    SteamDeckVerified_TestDisplayName_50: _,
    SteamDeckVerified_TestDisplayName_51: _,
    SteamDeckVerified_TestDisplayName_52: _,
    SteamDeckVerified_TestDisplayName_53: _,
    SteamDeckVerified_TestDisplayName_54: _,
    SteamDeckVerified_TestDisplayName_55: _,
    SteamDeckVerified_TestDisplayName_56: _,
    SteamDeckVerified_TestDisplayName_57: _,
    SteamDeckVerified_TestDisplayName_58: _,
    SteamDeckVerified_TestDisplayName_59: _,
    SteamDeckVerified_TestDisplayName_60: _,
    SteamDeckVerified_TestDisplayName_61: _,
    SteamDeckVerified_TestDisplayName_62: _,
    SteamDeckVerified_TestDisplayName_63: _,
    SteamDeckVerified_TestDisplayName_64: _,
    SteamDeckVerified_TestDisplayName_65: _,
    Compatibility_Tab_Steam_Machine: _,
    Compatibility_Tab_Steam_OS: _,
    Compatibility_Tab_Steam_Deck: _,
    Compatibility_Tab_Steam_Frame: _,
    SteamDeck_BuildReview_PleaseRequestTest: _,
    SteamFrame_BuildReview_Checklist_Intro_Header_V2: _,
    SteamFrame_BuildReview_PleaseConfirm_Title_V2: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P1: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P3: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P3_ReviewProcess: _,
    SteamFrame_BuildReview_PleaseConfirm_Description_V2: _,
    SteamDeck_TestRequest_BuildNotReleased: _,
    SteamDeck_BuildReview_Checklist_Intro: _,
    SteamDeck_BuildReview_Checklist_Intro_Header_V2: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P1: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P2: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3_ReviewProcess: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3_Additional: _,
    SteamDeck_BuildReview_PleaseConfirm_Title_V2: _,
    SteamDeck_BuildReview_PleaseConfirm_Description_V2: _,
    SteamDeck_BuildReview_AppTypeUnavailable: _,
    SteamDeck_BuildReview_Checklist_Input: _,
    SteamDeck_BuildReview_Checklist_Text: _,
    SteamDeck_BuildReview_Checklist_Display: _,
    SteamDeck_BuildReview_Checklist_Functionality: _,
    SteamDeck_BuildReview_Checklist_SteamCloud: _,
    SteamDeck_BuildReview_Checklist_Launcher: _,
    SteamDeck_BuildReview_Checklist_Branch: _,
    SteamDeck_BuildReview_Checklist_Branch_PleaseTest: _,
    SteamDeck_BuildReview_MarkReady_Button: _,
    SteamDeck_BuildReview_MarkReady_Description: _,
    SteamDeck_BuildReview_MarkReady_Notes: _,
    SteamDeck_BuildReview_MarkReady_NotesDefault: _,
    SteamDeck_BuildReview_HelpRequest_Link: _,
    SteamDeck_BuildReview_ViewMoreDetailsInHelp: _,
    SteamDeck_BuildReview_Create_HelpRequest_Title: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes_1: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes_2: _,
    SteamDeck_BuildReview_Create_HelpRequest_SupportTicketIntro: _,
    SteamDeck_BuildReview_Check_Controller: _,
    SteamDeck_BuildReview_Check_Icons: _,
    SteamDeck_BuildReview_Check_TextInput: _,
    SteamDeck_BuildReview_Check_TextInput_V2_NoTextEntry: _,
    SteamDeck_BuildReview_Check_TextInput_V2_YesSteamAPIs: _,
    SteamDeck_BuildReview_Check_TextInput_V2_NoSteamAPIs: _,
    SteamDeck_BuildReview_Check_Cloud_NoSaves: _,
    SteamDeck_BuildReview_Check_Cloud_YesSavesNoCloud: _,
    SteamDeck_BuildReview_Check_Cloud_SinglePlatform: _,
    SteamDeck_BuildReview_Check_Cloud_YesCrossSaves: _,
    SteamDeck_BuildReview_Check_Cloud_NoCrossSaves: _,
    SteamDeck_BuildReview_Check_Display1280: _,
    SteamDeck_BuildReview_Check_DisplayFont: _,
    SteamDeck_BuildReview_Check_FunctionalityLauncher: _,
    SteamDeck_BuildReview_Check_FunctionalityCloudSaves: _,
    SteamDeck_BuildReview_Check_FunctionalityCrossPlatformCloudSaves: _,
    SteamDeck_BuildReview_Check_TestLinuxBuild_Preamble: _,
    SteamDeck_BuildReview_Check_TestLinuxBuild: _,
    SteamDeck_BuildReview_Check_Launcher_V2_NoLauncher: _,
    SteamDeck_BuildReview_Check_Launcher_V2_ControllerSupport: _,
    SteamDeck_BuildReview_Check_Launcher_V2_NoControllerSupport: _,
    SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves: _,
    SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves_Documentation: _,
    SteamDeck_BuildReview_CheckNote_DisplayFont: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_InputRecommendations:
      _,
    SteamDeck_BuildReview_CheckNote_Launcher_V2_NoControllerSupport: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_LauncherRecommendations:
      _,
    SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud: _,
    SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud_SteamCloud: _,
    SteamDeck_BuildReview_CheckNote_FullController: _,
    SteamDeck_BuildReview_InReview_Title: _,
    SteamDeck_BuildReview_InReview_Description: _,
    SteamDeck_BuildReview_PleaseComplete: _,
    SteamDeck_BuildReview_Unsupported_Title: _,
    SteamDeck_BuildReview_Unsupported_Description: _,
    SteamDeck_BuildReview_NotMeetRequirements_Title: _,
    SteamDeck_BuildReview_NotMeetRequirements_Description: _,
    SteamFrame_BuildReview_Checklist_Build: _,
    SteamFrame_BuildReview_Build_Android: _,
    SteamFrame_BuildReview_Build_Windows: _,
    SteamFrame_BuildReview_Build_Linux: _,
    SteamFrame_BuildReview_Checklist_Dimension: _,
    SteamFrame_BuildReview_Dimension_2D: `2D`,
    SteamFrame_BuildReview_Dimension_VR: `VR`,
    SteamFrame_NotApplicableForDimension: _,
    SteamFrame_BuildReview_Check_VRPerformance_Verified_Without: _,
    SteamFrame_BuildReview_Check_VRPerformance_Verified_With: _,
    SteamFrame_BuildReview_Check_VRPerformance_Playable_Without: _,
    SteamFrame_BuildReview_Check_VRPerformance_Playable_With: _,
    SteamFrame_BuildReview_Check_VRPerformance_Unsupported: _,
    SteamFrame_BuildReview_Check_VRPerformance_NotApplicable: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_Title: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_Description: _,
    SteamFrame_BuildReview_VRPerformanceLink: _,
    SteamFrame_BuildReview_CheckNote_DisplayFont: _,
    SteamFrame_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs: _,
    SteamFrame_BuildReview_Compatibility_Checklist: _,
    SteamFrame_BuildReview_CheckNote_Launcher_V2_NoControllerSupport: _,
    SteamFrame_BuildReview_CheckNote_Cloud_YesSavesNoCloud: _,
    SteamFrame_BuildReview_CheckNote_Cloud_NoCrossSaves: _,
    SteamFrame_BuildReview_Check_Icons: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_StatusReason: _,
    SteamFrame_BuildReview_Check_VRPerformance_Startup: _,
    SteamFrame_BuildReview_Check_VRPerformance_Loading: _,
    SteamFrame_BuildReview_Check_VRPerformance_Other: _,
    SteamFrame_BuildReview_CheckNote_Missing_Android_License: _,
    SteamFrame_BuildReview_CheckNote_Missing_Android_License_Link: _,
    dummy: _,
  };
export {
  _ as Compatibility_Tab_Steam_Deck,
  _ as Compatibility_Tab_Steam_Frame,
  _ as Compatibility_Tab_Steam_Machine,
  _ as Compatibility_Tab_Steam_OS,
  _ as ContentSurvey_History_Title,
  _ as ContentSurvey_History_Title_Default,
  _ as ContentSurvey_InvalidApp,
  _ as ContentSurvey_Title,
  _ as ContentSurvey_Title_Default,
  _ as Footer_Description,
  _ as Footer_Sitemap_ContactSupport,
  _ as PartnerSite_NotLoggedIn,
  _ as PartnerSite_PermissionDenied,
  _ as PricingExplorer_About_Dash,
  _ as PricingExplorer_About_Desc1,
  _ as PricingExplorer_About_Desc2,
  _ as PricingExplorer_About_LastUpdated,
  _ as PricingExplorer_About_Link1,
  _ as PricingExplorer_About_Link2,
  _ as PricingExplorer_About_LinkName1,
  _ as PricingExplorer_About_LinkName2,
  _ as PricingExplorer_About_Title,
  _ as PricingExplorer_Base,
  _ as PricingExplorer_BasePrice,
  _ as PricingExplorer_Column1,
  _ as PricingExplorer_Column2,
  _ as PricingExplorer_Column3,
  _ as PricingExplorer_Column4,
  _ as PricingExplorer_Explore_desc1,
  _ as PricingExplorer_Explore_line1,
  _ as PricingExplorer_Explore_line2,
  _ as PricingExplorer_Explore_line3,
  _ as PricingExplorer_Explore_title,
  _ as PricingExplorer_LoadError,
  _ as PricingExplorer_Regions_Column1,
  _ as PricingExplorer_Regions_TableHeader,
  _ as PricingExplorer_TableHeader,
  _ as Pricing_Dummy,
  _ as SteamDeckVerified_TestDisplayName_0,
  _ as SteamDeckVerified_TestDisplayName_1,
  _ as SteamDeckVerified_TestDisplayName_10,
  _ as SteamDeckVerified_TestDisplayName_11,
  _ as SteamDeckVerified_TestDisplayName_12,
  _ as SteamDeckVerified_TestDisplayName_13,
  _ as SteamDeckVerified_TestDisplayName_14,
  _ as SteamDeckVerified_TestDisplayName_15,
  _ as SteamDeckVerified_TestDisplayName_16,
  _ as SteamDeckVerified_TestDisplayName_17,
  _ as SteamDeckVerified_TestDisplayName_18,
  _ as SteamDeckVerified_TestDisplayName_19,
  _ as SteamDeckVerified_TestDisplayName_2,
  _ as SteamDeckVerified_TestDisplayName_20,
  _ as SteamDeckVerified_TestDisplayName_21,
  _ as SteamDeckVerified_TestDisplayName_22,
  _ as SteamDeckVerified_TestDisplayName_23,
  _ as SteamDeckVerified_TestDisplayName_24,
  _ as SteamDeckVerified_TestDisplayName_25,
  _ as SteamDeckVerified_TestDisplayName_26,
  _ as SteamDeckVerified_TestDisplayName_27,
  _ as SteamDeckVerified_TestDisplayName_29,
  _ as SteamDeckVerified_TestDisplayName_3,
  _ as SteamDeckVerified_TestDisplayName_30,
  _ as SteamDeckVerified_TestDisplayName_31,
  _ as SteamDeckVerified_TestDisplayName_32,
  _ as SteamDeckVerified_TestDisplayName_33,
  _ as SteamDeckVerified_TestDisplayName_34,
  _ as SteamDeckVerified_TestDisplayName_35,
  _ as SteamDeckVerified_TestDisplayName_36,
  _ as SteamDeckVerified_TestDisplayName_37,
  _ as SteamDeckVerified_TestDisplayName_38,
  _ as SteamDeckVerified_TestDisplayName_39,
  _ as SteamDeckVerified_TestDisplayName_4,
  _ as SteamDeckVerified_TestDisplayName_40,
  _ as SteamDeckVerified_TestDisplayName_41,
  _ as SteamDeckVerified_TestDisplayName_42,
  _ as SteamDeckVerified_TestDisplayName_43,
  _ as SteamDeckVerified_TestDisplayName_44,
  _ as SteamDeckVerified_TestDisplayName_45,
  _ as SteamDeckVerified_TestDisplayName_46,
  _ as SteamDeckVerified_TestDisplayName_47,
  _ as SteamDeckVerified_TestDisplayName_48,
  _ as SteamDeckVerified_TestDisplayName_49,
  _ as SteamDeckVerified_TestDisplayName_5,
  _ as SteamDeckVerified_TestDisplayName_50,
  _ as SteamDeckVerified_TestDisplayName_51,
  _ as SteamDeckVerified_TestDisplayName_52,
  _ as SteamDeckVerified_TestDisplayName_53,
  _ as SteamDeckVerified_TestDisplayName_54,
  _ as SteamDeckVerified_TestDisplayName_55,
  _ as SteamDeckVerified_TestDisplayName_56,
  _ as SteamDeckVerified_TestDisplayName_57,
  _ as SteamDeckVerified_TestDisplayName_58,
  _ as SteamDeckVerified_TestDisplayName_59,
  _ as SteamDeckVerified_TestDisplayName_6,
  _ as SteamDeckVerified_TestDisplayName_60,
  _ as SteamDeckVerified_TestDisplayName_61,
  _ as SteamDeckVerified_TestDisplayName_62,
  _ as SteamDeckVerified_TestDisplayName_63,
  _ as SteamDeckVerified_TestDisplayName_64,
  _ as SteamDeckVerified_TestDisplayName_65,
  _ as SteamDeckVerified_TestDisplayName_7,
  _ as SteamDeckVerified_TestDisplayName_8,
  _ as SteamDeckVerified_TestDisplayName_9,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyDescription_RecommendedRuntime,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_ExpectedInput,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_FDMDebug,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RPODebug,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RecommendedRuntime,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RequiresH264,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TSOEnable,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TestedBuildID,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TestedProtonVersion,
  _ as SteamDeck_AppLanding_History,
  _ as SteamDeck_AppLanding_Published,
  _ as SteamDeck_AppLanding_Unpublished,
  _ as SteamDeck_BuildReview_AppTypeUnavailable,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves_Documentation,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud_SteamCloud,
  _ as SteamDeck_BuildReview_CheckNote_DisplayFont,
  _ as SteamDeck_BuildReview_CheckNote_FullController,
  _ as SteamDeck_BuildReview_CheckNote_Launcher_V2_NoControllerSupport,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_InputRecommendations,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_LauncherRecommendations,
  _ as SteamDeck_BuildReview_Check_Cloud_NoCrossSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_NoSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_SinglePlatform,
  _ as SteamDeck_BuildReview_Check_Cloud_YesCrossSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_YesSavesNoCloud,
  _ as SteamDeck_BuildReview_Check_Controller,
  _ as SteamDeck_BuildReview_Check_Display1280,
  _ as SteamDeck_BuildReview_Check_DisplayFont,
  _ as SteamDeck_BuildReview_Check_FunctionalityCloudSaves,
  _ as SteamDeck_BuildReview_Check_FunctionalityCrossPlatformCloudSaves,
  _ as SteamDeck_BuildReview_Check_FunctionalityLauncher,
  _ as SteamDeck_BuildReview_Check_Icons,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_ControllerSupport,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_NoControllerSupport,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_NoLauncher,
  _ as SteamDeck_BuildReview_Check_TestLinuxBuild,
  _ as SteamDeck_BuildReview_Check_TestLinuxBuild_Preamble,
  _ as SteamDeck_BuildReview_Check_TextInput,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_NoSteamAPIs,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_NoTextEntry,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_YesSteamAPIs,
  _ as SteamDeck_BuildReview_Checklist_Branch,
  _ as SteamDeck_BuildReview_Checklist_Branch_PleaseTest,
  _ as SteamDeck_BuildReview_Checklist_Display,
  _ as SteamDeck_BuildReview_Checklist_Functionality,
  _ as SteamDeck_BuildReview_Checklist_Input,
  _ as SteamDeck_BuildReview_Checklist_Intro,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P1,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P2,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3_Additional,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3_ReviewProcess,
  _ as SteamDeck_BuildReview_Checklist_Intro_Header_V2,
  _ as SteamDeck_BuildReview_Checklist_Launcher,
  _ as SteamDeck_BuildReview_Checklist_SteamCloud,
  _ as SteamDeck_BuildReview_Checklist_Text,
  _ as SteamDeck_BuildReview_CompatibilityTests,
  _ as SteamDeck_BuildReview_Create_HelpRequest,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_1,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2a,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2b,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes,
  _ as SteamDeck_BuildReview_Create_HelpRequest_NotesDefault,
  _ as SteamDeck_BuildReview_Create_HelpRequest_NotesDefault_Rereview,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes_1,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes_2,
  _ as SteamDeck_BuildReview_Create_HelpRequest_SupportTicketIntro,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Title,
  _ as SteamDeck_BuildReview_Documentation,
  _ as SteamDeck_BuildReview_Header_History,
  _ as SteamDeck_BuildReview_Header_Results,
  _ as SteamDeck_BuildReview_HelpRequest_Link,
  _ as SteamDeck_BuildReview_Help_Request_Title,
  _ as SteamDeck_BuildReview_InReview_Description,
  _ as SteamDeck_BuildReview_InReview_Title,
  _ as SteamDeck_BuildReview_InReview_ViewTicket,
  _ as SteamDeck_BuildReview_MarkReady_Button,
  _ as SteamDeck_BuildReview_MarkReady_Description,
  _ as SteamDeck_BuildReview_MarkReady_Notes,
  _ as SteamDeck_BuildReview_MarkReady_NotesDefault,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Description,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Button,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label_Machine,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Ticket_Content,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Title,
  _ as SteamDeck_BuildReview_PleaseComplete,
  _ as SteamDeck_BuildReview_PleaseConfirm_Description_V2,
  _ as SteamDeck_BuildReview_PleaseConfirm_Title_V2,
  _ as SteamDeck_BuildReview_PleaseRequestTest,
  _ as SteamDeck_BuildReview_PublishDialog_Body,
  _ as SteamDeck_BuildReview_PublishDialog_Title,
  _ as SteamDeck_BuildReview_PublishResults,
  _ as SteamDeck_BuildReview_PublishedOn,
  _ as SteamDeck_BuildReview_ReportedOn,
  _ as SteamDeck_BuildReview_RequestStatusActive,
  _ as SteamDeck_BuildReview_RequestStatusClosed,
  _ as SteamDeck_BuildReview_Status_Description,
  _ as SteamDeck_BuildReview_Status_Fail,
  _ as SteamDeck_BuildReview_Status_FailMinor,
  _ as SteamDeck_BuildReview_Status_NotApplicable,
  _ as SteamDeck_BuildReview_Status_Pass,
  _ as SteamDeck_BuildReview_Status_Raw_Comment,
  _ as SteamDeck_BuildReview_Status_Raw_Description,
  _ as SteamDeck_BuildReview_Status_Raw_Impact,
  _ as SteamDeck_BuildReview_Status_Raw_Result,
  _ as SteamDeck_BuildReview_Status_Raw_Test,
  _ as SteamDeck_BuildReview_Status_Raw_Title,
  _ as SteamDeck_BuildReview_Status_TestProperties_Description,
  _ as SteamDeck_BuildReview_Status_TestProperties_Playable,
  _ as SteamDeck_BuildReview_Status_TestProperty_Desc,
  _ as SteamDeck_BuildReview_Status_TestProperty_Name,
  _ as SteamDeck_BuildReview_Status_TestProperty_Value,
  _ as SteamDeck_BuildReview_Status_Title,
  _ as SteamDeck_BuildReview_UnknownError,
  _ as SteamDeck_BuildReview_Unsupported_Description,
  _ as SteamDeck_BuildReview_Unsupported_Title,
  _ as SteamDeck_BuildReview_ViewMoreDetailsInHelp,
  _ as SteamDeck_BuildReview_Viewing_Historical,
  _ as SteamDeck_BuildReview_Viewing_Published,
  _ as SteamDeck_HardwareCompatibility_Title,
  _ as SteamDeck_TestRequest_BuildNotReleased,
  _ as SteamFrame_BuildReview_Build_Android,
  _ as SteamFrame_BuildReview_Build_Linux,
  _ as SteamFrame_BuildReview_Build_Windows,
  _ as SteamFrame_BuildReview_CheckNote_Cloud_NoCrossSaves,
  _ as SteamFrame_BuildReview_CheckNote_Cloud_YesSavesNoCloud,
  _ as SteamFrame_BuildReview_CheckNote_DisplayFont,
  _ as SteamFrame_BuildReview_CheckNote_Launcher_V2_NoControllerSupport,
  _ as SteamFrame_BuildReview_CheckNote_Missing_Android_License,
  _ as SteamFrame_BuildReview_CheckNote_Missing_Android_License_Link,
  _ as SteamFrame_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs,
  _ as SteamFrame_BuildReview_Check_Icons,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Loading,
  _ as SteamFrame_BuildReview_Check_VRPerformance_NotApplicable,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Other,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Playable_With,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Playable_Without,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Startup,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Unsupported,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Verified_With,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Verified_Without,
  _ as SteamFrame_BuildReview_Checklist_Build,
  _ as SteamFrame_BuildReview_Checklist_Dimension,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P1,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P3,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P3_ReviewProcess,
  _ as SteamFrame_BuildReview_Checklist_Intro_Header_V2,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_Description,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_StatusReason,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_Title,
  _ as SteamFrame_BuildReview_Compatibility_Checklist,
  _ as SteamFrame_BuildReview_Dimension_2D,
  _ as SteamFrame_BuildReview_Dimension_VR,
  _ as SteamFrame_BuildReview_PleaseConfirm_Description_V2,
  _ as SteamFrame_BuildReview_PleaseConfirm_Title_V2,
  _ as SteamFrame_BuildReview_VRPerformanceLink,
  _ as SteamFrame_NotApplicableForDimension,
  _ as SteamHardware_BuildReview_Playable_Description,
  _ as SteamHardware_BuildReview_Playable_Title,
  _ as SteamHardware_BuildReview_Unknown_Title,
  _ as SteamHardware_BuildReview_Unsupported_Description,
  _ as SteamHardware_BuildReview_Unsupported_Title,
  _ as SteamHardware_BuildReview_Verified_Description,
  _ as SteamHardware_BuildReview_Verified_Share,
  _ as SteamHardware_BuildReview_Verified_Title,
  _ as SteamHardware_Frame_Unknown,
  _ as SteamHardware_Machine_Unknown,
  _ as SteamHardware_RatingImpact_Informational,
  _ as SteamHardware_RatingImpact_Playable,
  _ as SteamHardware_RatingImpact_Unsupported,
  _ as Valve_Confidential,
  _ as Valve_Confidential_Description,
  _ as default,
  _ as dummy,
};
