var _ = `在下方選擇一個美元價格`,
  _ = `免費使用`,
  _ = `設定為免費…`,
  _ = `為顧客將此套件更新為免費使用`,
  _ = `只有 Steam 客服可以將此套件設為免費套件。請使用「說明與文獻」下方的「聯繫 Steam 發行團隊」連結尋求協助。`,
  _ = `將套件轉換為免費？`,
  _ = `這會將您的套件定價設定為免費、標記您的應用程式以顯示於免費遊玩中心，並將價格顯示為您在下方選擇的用詞。此變更必須透過 Steam 客服團隊建立客服案件才能還原。`,
  _ = `只有 Steam 客服可以將此套件轉換為免費套件。請點擊下方以建立客服案件並提供您的請求詳情。`,
  _ = `選擇合適的文字來取代價格顯示：`,
  _ = `「免費遊玩」- 此遊戲免費下載和遊玩，但包含可選的遊戲內購買項目（物品、貨幣、DLC、或其它營利方式）。`,
  _ = `「免費」- 此遊戲可完全免費下載和遊玩。沒有遊戲內購買項目或付費內容。`,
  _ = `轉換為免費`,
  _ = `更新遊戲的商店頁面以包含在免費類型中。商店發佈所需。`,
  _ = `將套件更新為免費`,
  _ = `成功轉換為免費。頁面將在您關閉對話方塊後重新載入。`,
  _ = `更新商店應用程式頁面失敗：%1$s`,
  _ = `套件類型變更失敗：%1$s`,
  _ = `轉換方式（%1$s）`,
  _ = `檢視詳情`,
  _ = `請使用下方的下拉選單選擇產品定價。本工具將根據我們過往經手類似價位的產品的經驗，針對您選擇的基礎售價建議合適的分區定價。請注意部分國家 / 地區的建議定價已含 VAT/GST/JCT。VAT/GST/JCT 屬增值稅，與消費稅類似，且由稅務機關徵收。在依法須課徵增值稅的國家 / 地區中，定價將包含增值稅，且會隨購買徵收。有徵收增值稅的國家 / 地區清單如下：`,
  _ = `請在提交前審慎考慮您的產品的定價策略，並再三確認所有貨幣種類的定價。由於諸多原因，我們不推薦合作夥伴在產品推出的前幾週內變更定價。如有需要，您能在上架前提交新定價請求，不過一旦您的產品上架，您的定價將生效。詳情請參閱%1$s。`,
  _ = `定價與折扣文獻`,
  _ = `決定好定價後，請點擊儲存按鈕以提交給 Valve 進行審核與後續作業。`,
  _ = `前往大量定價頁面進行編輯`,
  _ = `使用大量定價工具編輯此套件的定價`,
  _ = `說明與守則`,
  _ = `定價方面需要協助或建議嗎？請參考以下連結中的常見考慮因素與原則。`,
  _ = `定價文獻`,
  _ = `常見問答`,
  _ = `轉為免費？`,
  _ = `如果您的遊戲已發行，但需要從付費轉為免費，請點擊%1$s以了解詳情並請求協助。`,
  _ = `此處`,
  _ = `輸入自訂價格`,
  _ = `您可以直接編輯文字方塊，為每種貨幣輸入各自的定價。`,
  _ = `您也可使用此按鈕，根據所選的轉換方式和您輸入的自訂美元定價來計算各貨幣的定價。`,
  _ = `從價格等級中選擇`,
  _ = `選擇美元基本定價`,
  _ = `開啟內含一組常見價格等級的對話框，允許將之用於設定下列所有幣種內的價格。`,
  _ = `多變數轉換`,
  _ = `僅依購買力轉換`,
  _ = `僅依匯率轉換`,
  _ = `最後更新於：`,
  _ = `轉換方式採用截至 2026 年 1 月的公開資料來產生結果`,
  _ = `有新的轉換方式可供使用`,
  _ = `為協助您以 37 種不同幣別和 4 個地區群組為您的遊戲訂價，Steam 現在提供幾種不同方式，讓您能以想使用的基本定價進行轉換`,
  _ = `定價完全由您決定，這些工具的設計只是在您選擇使用時，用來協助簡化這個過程。`,
  _ = `請前往我們的%1$s或點擊上方的「檢視詳情」深入了解不同可用的轉換方式。`,
  _ = `轉換方式詳情頁面`,
  _ = `套用轉換方式定價`,
  _ = `為協助各位管理 35 種以上 Steam 支援幣別的訂價，此工具提供數種可選擇的轉換方式，以基礎美元售價轉換為合理地區價格。`,
  _ = `於下方選擇一個價格設為美元定價，並為其它貨幣種類套用轉換後的定價。具體價格取決於上方選擇的轉換方式。`,
  _ = `您可為每個支援的貨幣種類輸入價格，或使用 Steam 提供的轉換方式之一將您的美元定價轉為所有其它幣種的定價。`,
  _ = `使用 Steam 轉換方式的方法有兩種：`,
  _ = `從下方的價格等級下拉選單中選擇一個常見的美元定價，Steam 將根據所選的轉換方式來填入其它幣種的定價。`,
  _ = `若為不常見的美元定價，則直接在美元價格欄位內填入數值。接著點擊「轉換價格…」按鈕並依步驟進行。`,
  _ = `轉換後建議定價：`,
  _ = `此定價是根據上方所選的轉換方式和 %1$s 的美元定價所建議的。`,
  _ = `dummy`,
  _ = ``,
  _ = {
    PricingGuideline_Default: _,
    FreeOnDemand_InlineOption: _,
    FreeOnDemand_Button: _,
    FreeOnDemand_Button_ttip: _,
    FreeOnDemand_Button_disabled_ttip: _,
    FreeOnDemand_Title: _,
    FreeOnDemand_Desc: _,
    FreeOnDemand_Desc_NotPermitted: _,
    FreeOnDemand_Radio: _,
    FreeOnDemand_Radio_FreeToPlay: _,
    FreeOnDemand_Radio_Free: _,
    FreeOnDemand_Button_Confirm: _,
    FreeOnDemand_Convert_Store: _,
    FreeOnDemand_Convert_Package: _,
    FreeOnDemand_ConvertSuccess: _,
    FreeOnDemand_Store_Error: _,
    FreeOnDemand_Package_Error: _,
    ConversionMethod_Title: _,
    ConversionMethod_Link: _,
    SinglePricingPackage_Desc_1: _,
    SinglePricingPackage_Desc_2: _,
    SinglePricingPackage_Desc_2_Link: _,
    SinglePricingPackage_Desc_3: _,
    SinglePackagePricing_Right_Edit: _,
    SinglePackagePricing_Right_Edit_desc: _,
    SinglePackagePricing_Right_Help_Title: _,
    SinglePackagePricing_Right_Help_Desc: _,
    SinglePackagePricing_Right_Link: _,
    SinglePackagePricing_Right_FAQ: _,
    SinglePackagePricing_Right_FAQ_switching: _,
    SinglePackagePricing_Right_FAQ_switching_answer: _,
    SinglePackagePricing_Right_FAQ_switching_answer_link: _,
    SinglePackagePricing_Right_Convert_Title: _,
    SinglePackagePricing_Right_Custom_Desc: _,
    SinglePackagePricing_Right_Convert_Desc: _,
    PricingDashboard_Select_Price: _,
    PricingDashboard_Select_Price_button: _,
    PricingDashboard_Select_Price_button_ttip: _,
    ConversionMethod_Nuanced: _,
    ConversionMethod_PPP: _,
    ConversionMethod_FX: _,
    PricingExplorer_Time_Title: _,
    PricingExplorer_Time_Disc: _,
    Tour_ConversionMethod_Title: _,
    Tour_ConversionMethod_Desc1: _,
    Tour_ConversionMethod_Desc2: _,
    Tour_ConversionMethod_Desc3: _,
    Tour_ConversionMethod_Link: _,
    PricingDashboard_ApplyConversion_Method: _,
    PricingDashboard_ApplyGuidelines_Instructions_MultiOptions: _,
    PricingDashboard_GuidelinesPickerDescription_New: _,
    SinglePricingPackage_Intro_1: _,
    SinglePricingPackage_Intro_2: _,
    SinglePricingPackage_Intro_2a: _,
    SinglePricingPackage_Intro_2b: _,
    PricingDashboard_Method_SuggestedPrice: _,
    PricingDashboard_Method_SuggestedPrice_ttip: _,
    dummy: _,
    empty_no_trailing_comma: ``,
  };
export {
  _ as ConversionMethod_FX,
  _ as ConversionMethod_Link,
  _ as ConversionMethod_Nuanced,
  _ as ConversionMethod_PPP,
  _ as ConversionMethod_Title,
  _ as FreeOnDemand_Button,
  _ as FreeOnDemand_Button_Confirm,
  _ as FreeOnDemand_Button_disabled_ttip,
  _ as FreeOnDemand_Button_ttip,
  _ as FreeOnDemand_ConvertSuccess,
  _ as FreeOnDemand_Convert_Package,
  _ as FreeOnDemand_Convert_Store,
  _ as FreeOnDemand_Desc,
  _ as FreeOnDemand_Desc_NotPermitted,
  _ as FreeOnDemand_InlineOption,
  _ as FreeOnDemand_Package_Error,
  _ as FreeOnDemand_Radio,
  _ as FreeOnDemand_Radio_Free,
  _ as FreeOnDemand_Radio_FreeToPlay,
  _ as FreeOnDemand_Store_Error,
  _ as FreeOnDemand_Title,
  _ as PricingDashboard_ApplyConversion_Method,
  _ as PricingDashboard_ApplyGuidelines_Instructions_MultiOptions,
  _ as PricingDashboard_GuidelinesPickerDescription_New,
  _ as PricingDashboard_Method_SuggestedPrice,
  _ as PricingDashboard_Method_SuggestedPrice_ttip,
  _ as PricingDashboard_Select_Price,
  _ as PricingDashboard_Select_Price_button,
  _ as PricingDashboard_Select_Price_button_ttip,
  _ as PricingExplorer_Time_Disc,
  _ as PricingExplorer_Time_Title,
  _ as PricingGuideline_Default,
  _ as SinglePackagePricing_Right_Convert_Desc,
  _ as SinglePackagePricing_Right_Convert_Title,
  _ as SinglePackagePricing_Right_Custom_Desc,
  _ as SinglePackagePricing_Right_Edit,
  _ as SinglePackagePricing_Right_Edit_desc,
  _ as SinglePackagePricing_Right_FAQ,
  _ as SinglePackagePricing_Right_FAQ_switching,
  _ as SinglePackagePricing_Right_FAQ_switching_answer,
  _ as SinglePackagePricing_Right_FAQ_switching_answer_link,
  _ as SinglePackagePricing_Right_Help_Desc,
  _ as SinglePackagePricing_Right_Help_Title,
  _ as SinglePackagePricing_Right_Link,
  _ as SinglePricingPackage_Desc_1,
  _ as SinglePricingPackage_Desc_2,
  _ as SinglePricingPackage_Desc_2_Link,
  _ as SinglePricingPackage_Desc_3,
  _ as SinglePricingPackage_Intro_1,
  _ as SinglePricingPackage_Intro_2,
  _ as SinglePricingPackage_Intro_2a,
  _ as SinglePricingPackage_Intro_2b,
  _ as Tour_ConversionMethod_Desc1,
  _ as Tour_ConversionMethod_Desc2,
  _ as Tour_ConversionMethod_Desc3,
  _ as Tour_ConversionMethod_Link,
  _ as Tour_ConversionMethod_Title,
  _ as default,
  _ as dummy,
  _ as empty_no_trailing_comma,
};
