var _ = `Confidencial da Valve`,
  _ = `Esta página de acesso restrito contém informações confidenciais da Valve. Deverá ter um acordo de não-divulgação (NDA) e/ou um acordo de licença que abranja informações confidenciais com a Valve para poder usar ou aceder a esta página.`,
  _ = `O Steamworks é o conjunto de ferramentas e serviços criados pela <1>Valve</1> que ajudam a configurar, gerir e operar o seu jogo no <2>Steam</2>.`,
  _ = `Contactar Suporte Steam`,
  _ = `Erro ao carregar informações de preços. Tente mais tarde.`,
  _ = `Sobre preços regionais`,
  _ = `O preço de cada produto no Steam é especificado e apresentado com base em %1$s moedas e %2$s <1>grupos de regiões</1> diferentes. O Steam disponibiliza ferramentas que ajudam a definir e gerir o preço do seu jogo a níveis adequados para cada mercado.`,
  _ = `Cabe-lhe a si definir os preços do seu jogo em cada moeda e grupo de regiões.`,
  _ = `Para mais detalhes sobre como gerir os seus preços, consulte: %1$s`,
  _ = `documentação sobre preços`,
  _ = `Para gerir os preços do seu jogo, aceda ao seu %1$s`,
  _ = `Visitar painel de gestão de preços`,
  _ = `Para gerir os preços do seu jogo, aceda ao seu painel de gestão de preços`,
  _ = `Conversão monetárias atualizadas pela última vez em %1$s`,
  _ = `Ferramenta de exploração de conversão de preço`,
  _ = `Esta ferramenta demonstra como os três métodos de conversão de preços e moedas funcionam:`,
  _ = `%1$s - Este método tem em conta vários fatores para cada moeda, incluindo o poder de compra local, as expectativas de custos de bens de entretenimento e a taxa de câmbio.`,
  _ = `%1$s - Este método usa dados públicos sobre o poder de compra dos utilizadores num determinado país e/ou região.`,
  _ = `%1$s - Este método usa uma taxa de câmbio simples no período indicado.`,
  _ = `Moeda base`,
  _ = `Preço base`,
  _ = `Método de conversão`,
  _ = `Moeda`,
  _ = `Conversão com várias variáveis`,
  _ = `Conversão com base no poder de compra`,
  _ = `Conversão com base na taxa de câmbio`,
  _ = `Preços em regiões específicas (todos apresentados em USD)`,
  _ = `Região`,
  _ = `dummy`,
  _ = `%1$s (%2$s) - Inquérito de conteúdo`,
  _ = `Inquérito de conteúdo`,
  _ = `%1$s (%2$s) - Inquéritos de conteúdo`,
  _ = `Inquéritos de conteúdo`,
  _ = `Não existe nenhuma aplicação associada a este ID. Confirme o endereço e tente de novo.`,
  _ = `Permissão negada`,
  _ = `Sem sessão iniciada`,
  _ = `Resumo`,
  _ = `A lista completa dos testes realizados durante a análise e os seus resultados podem ser encontrados abaixo.`,
  _ = `Abaixo segue⁠-⁠se um resumo dos testes individuais e classificações de compatibilidade resultantes.`,
  _ = `Os resultados dos testes que determinam este jogo como "Jogável" estão indicados abaixo.`,
  _ = `Propriedade`,
  _ = `Valor`,
  _ = `Descrição`,
  _ = `Aqui está uma pré-visualização de como estas informações irão aparecer aos utilizadores que visitarem a página do seu jogo na loja. A apresentação destas informações pode vir a ser alterada numa data futura.`,
  _ = `Relatórios anteriores`,
  _ = `Resultados dos testes`,
  _ = `Resultado`,
  _ = `Teste`,
  _ = `Comentários`,
  _ = `Impacto na classificação`,
  _ = `Aprovado`,
  _ = `Não aprovado`,
  _ = `Não aprovado`,
  _ = `---`,
  _ = `Isto é um relatório de %1$s`,
  _ = `A ver o relatório atualmente publicado`,
  _ = `Publicado em: %1$s`,
  _ = `Relatório gerado em: %1$s`,
  _ = `Ver documentação`,
  _ = `Publicar estes resultados`,
  _ = `Publicar resultados de compatibilidade?`,
  _ = `Tem a certeza de que deseja publicar estes resultados? Os resultados estarão imediatamente visíveis na Loja Steam.`,
  _ = `Erro desconhecido: tente de novo`,
  _ = `Pedido de teste`,
  _ = `Pedido ativo`,
  _ = `Pedido encerrado`,
  _ = `Ver detalhes do pedido`,
  _ = `Discutir relatório com a equipa de testes`,
  _ = `Escreva perguntas ou comentários aqui`,
  _ = `Descreva as alterações da sua nova build aqui:`,
  _ = `Se a build do seu jogo no Steam foi atualizada com correções dos problemas mencionados acima, selecione um ramo e volte a enviá-la para análise.`,
  _ = `Selecione um ramo e envie para uma nova análise de compatibilidade com o Steam Deck, o que incluirá testes na Steam Machine.`,
  _ = `Enviar para nova análise`,
  _ = `Caso tenha efetuado alterações à build do seu jogo posteriores à última análise, pode pedir uma nova análise da compatibilidade.`,
  _ = `Descreva abaixo o motivo do seu pedido de reanálise. Exemplos:`,
  _ = `Efetuou alterações à sua build para corrigir os problemas descritos em testes falhados de uma análise de compatibilidade anterior. Descreva de forma específica os problemas que considera ter corrigido.`,
  _ = `Lançou ou está prestes a lançar uma nova versão do seu jogo e pretende que o relatório seja atualizado.`,
  _ = `Solicito novos testes com o ramo "%1$s". A build do jogo no Steam foi atualizada com correções dos problemas relatados.`,
  _ = `Histórico de testes`,
  _ = `Apresentação na loja`,
  _ = `Compatibilidade com hardware: %1$s (%2$s)`,
  _ = `Publicado`,
  _ = `Não publicado`,
  _ = `Histórico`,
  _ = `Runtime recomendado`,
  _ = `Esta é a versão do seu jogo (conteúdo/executáveis) que será entregue aos clientes por predefinição no Steam Deck.`,
  _ = `Formato de entrada esperado`,
  _ = `Requer h264`,
  _ = `Versão do Proton testada`,
  _ = `ID da build de teste`,
  _ = `Depuração de RPO`,
  _ = `Depuração de FDM`,
  _ = `Ativar TSO`,
  _ = `O seu jogo tem a classificação de "Desconhecido" no dispositivo "%1$s" porque os testes neste hardware ainda não foram concluídos.`,
  _ = `O seu jogo não é jogável no dispositivo "%1$s" de momento`,
  _ = `O seu jogo não é totalmente compatível com o dispositivo "%1$s" devido a problemas relativos ao Proton ou ao próprio dispositivo. Tomámos nota destes problemas para trabalharmos na sua resolução. Entretanto, o seu jogo não vai abrir ou funcionar devidamente no dispositivo "%1$s".`,
  _ = `O seu jogo é "Jogável" no dispositivo "%1$s"`,
  _ = `O seu jogo é jogável no dispositivo "%1$s", mas os utilizadores terão de seguir alguns passos adicionais para que possam interagir com o mesmo ou configurá-lo. Pode corrigir os problemas descritos abaixo e reenviar o jogo para análise de compatibilidade.`,
  _ = `O seu jogo foi "Aprovado" para o dispositivo "%1$s"!`,
  _ = `Parabéns! O seu jogo é uma ótima experiência no dispositivo "%1$s" e será apresentado como tal na Loja Steam e nas Bibliotecas Steam dos utilizadores nesse dispositivo.`,
  _ = `Deseja partilhar este marco importante com os seus fãs? Fica aqui um link para uma página especial que pode usar: %1$s`,
  _ = `O seu jogo não foi testado na Steam Machine`,
  _ = `O seu jogo não foi testado no Steam Frame`,
  _ = `Isto está a fazer com que a sua classificação seja "Jogável"`,
  _ = `Isto está a fazer com que a sua classificação seja "Incompatível"`,
  _ = `Isto aparece como uma mensagem informativa para os utilizadores`,
  _ = `Inválido`,
  _ = `Arranque do launcher`,
  _ = `Launcher`,
  _ = `Launcher usável com comando`,
  _ = `Texto do launcher`,
  _ = `Launcher usável com teclado`,
  _ = `Avisos do dispositivo`,
  _ = `Arranque do jogo`,
  _ = `Modo para um jogador`,
  _ = `Modo multijogador local`,
  _ = `Modo multijogador online`,
  _ = `Anti-cheats`,
  _ = `Anti-cheats`,
  _ = `Anti-cheats / Multijogador`,
  _ = `Configuração de comando predefinida`,
  _ = `Teclado`,
  _ = `Símbolos do comando`,
  _ = `Desempenho da configuração predefinida`,
  _ = `Visualização`,
  _ = `Saída de vídeo`,
  _ = `Resolução nativa`,
  _ = `Legibilidade do texto`,
  _ = `Áudio`,
  _ = `Menu`,
  _ = `Progresso guardado na Cloud entre plataformas`,
  _ = `Modo para um só jogador offline`,
  _ = `Comando externo funciona (jogador principal)`,
  _ = `Comando externo funciona (multijogador local)`,
  _ = `Configuração inicial`,
  _ = `A configuração inicial funciona com comando`,
  _ = `Configuração inicial offline`,
  _ = `Funcionalidade do jogo`,
  _ = `R.V.`,
  _ = `Observação`,
  _ = `Encerra sem problemas`,
  _ = `Encerra sem problemas (launcher)`,
  _ = `Input simultâneo do comando/rato`,
  _ = `Funcionalidade auxiliar: Editor de mapas`,
  _ = `Compatível com limitador de taxa de frames`,
  _ = `Foco com várias janelas (automático)`,
  _ = `Foco com várias janelas (manual)`,
  _ = `Software`,
  _ = `Input simultâneo do comando/rato`,
  _ = `Entrada de texto`,
  _ = `Entrada de áudio`,
  _ = `Retomar ao despertar`,
  _ = `Saída de imagem redimensionada`,
  _ = `Conteúdo e links externos`,
  _ = `Removido`,
  _ = `Tipo de letra compatível com todos os caracteres`,
  _ = `Definições de ecrã armazenadas no dispositivo e não na Steam Cloud`,
  _ = `Configuração de comando predefinida`,
  _ = `Comando ativo por predefinição`,
  _ = `A opção de ficheiros guardados na Cloud está ativa por predefinição`,
  _ = `Periféricos (teclado)`,
  _ = `Periféricos (webcam)`,
  _ = `Periféricos (guitarra USB)`,
  _ = `Compatibilidade com HDR`,
  _ = `Compatibilidade com SO`,
  _ = `Desempenho da configuração predefinida (Steam Machine)`,
  _ = `Desempenho do streaming de realidade virtual (Steam Machine)`,
  _ = `Compatível com streaming de realidade virtual (Steam Machine)`,
  _ = `Avisos do dispositivo (Steam Machine)`,
  _ = `Visualização (Steam Machine)`,
  _ = `Áudio (Steam Machine)`,
  _ = `Steam Machine`,
  _ = `SteamOS`,
  _ = `Steam Deck`,
  _ = `Steam Frame (headset)`,
  _ = `Solicite um teste de compatibilidade com o Steam Deck para dar início aos testes necessários à atribuição de uma classificação de compatibilidade com o dispositivo "%1$s".`,
  _ = `Olá! Aqui pode enviar a sua aplicação para análise de compatibilidade com o headset do Steam Frame.`,
  _ = `Autoavaliação de compatibilidade com o headset do Steam Frame `,
  _ = `Abaixo segue-se uma lista dos critérios mais importantes que nós verificamos ao analisar a compatibilidade de um jogo com o Steam Frame. Preencha o formulário abaixo e diga-nos a build ou ramo que gostaria que testássemos e colocaremos o jogo na fila de análises. Assim que o processo de análise for concluído, receberá uma notificação por e-mail com um resumo e esta página será atualizada com resultados detalhados dos testes.`,
  _ = `Para mais informações sobre este processo, consulte o artigo %1$s.`,
  _ = `Processo de análise de compatibilidade com o Steam Frame (para jogos executados diretamente no headset)`,
  _ = `Estes são alguns dos critérios mais importantes que iremos analisar para podermos atribuir uma classificação de compatibilidade ao seu jogo. Para dar início ao processo de análise da compatibilidade com o Steam Frame, responda às seguintes questões da melhor forma que puder.`,
  _ = `Não é possível solicitar testes antes do lançamento do jogo`,
  _ = `Será que os jogadores terão uma boa experiência com o seu jogo no Steam Deck? A nossa equipa tem um processo de análise que consiste em jogar e testar o seu jogo. Se esta análise demonstrar uma boa experiência no Steam Deck, o jogo será marcado como "Aprovado para o Steam Deck".`,
  _ = `Olá! Aqui pode enviar o seu jogo para análise de compatibilidade com o Steam Deck.`,
  _ = `Abaixo segue-se uma lista dos critérios mais importantes que nós verificamos ao analisar a compatibilidade de um jogo com o Steam Deck. Preencha o formulário abaixo e diga-nos a build ou ramo que gostaria que testássemos e colocaremos o jogo na fila de análises. Assim que o processo de análise for concluído, receberá uma notificação por e-mail com um resumo e esta página será atualizada com resultados detalhados dos testes.`,
  _ = `Pode enviar o seu jogo mesmo se não cumprir todos os critérios para receber a classificação de Aprovado. Nós usamos estas informações para definir a prioridade de análise de jogos e para comunicar da forma mais clara possível quaisquer problemas de compatibilidade que o seu jogo possa ter.`,
  _ = `Para mais informações sobre este processo, consulte a documentação do %1$s e as %2$s.`,
  _ = `processo de análise de compatibilidade com o Steam Deck`,
  _ = `recomendações adicionais para o Steam Deck`,
  _ = `Autoavaliação de compatibilidade com o Steam Deck`,
  _ = `Estes são alguns dos critérios mais importantes que iremos analisar para podermos atribuir uma classificação de compatibilidade ao seu jogo. Para dar início ao processo de análise da compatibilidade com o Steam Deck, responda às seguintes questões da melhor forma que puder.`,
  _ = `De momento, o processo de análise de compatibilidade do Steam Deck só está disponível para jogos. Este processo não está disponível para outros tipos de aplicações, como DLCs, ferramentas ou bandas sonoras, a não ser em casos excecionais.`,
  _ = `Compatibilidade com comandos`,
  _ = `Entrada de texto`,
  _ = `Visualização`,
  _ = `Funcionalidade`,
  _ = `Steam Cloud`,
  _ = `Launcher`,
  _ = `Ramo`,
  _ = `Por favor, realizar testes com este ramo`,
  _ = `Marcar como pronto para análise...`,
  _ = `Isto irá marcar a sua build como pronta para análise de compatibilidade com o Steam Deck. Receberá uma notificação por e-mail dentro de alguns dias com os resultados.`,
  _ = `Pode deixar comentários abaixo para nos ajudar a agilizar os testes ou para nos fornecer credenciais de acesso a servidores de terceiros para fins de teste.`,
  _ = `Insira comentários aqui`,
  _ = `Pedido de ajuda para esta análise`,
  _ = `Para mais detalhes, consulte este relatório de teste no site de Ajuda.`,
  _ = `Criar pedido de ajuda sobre a análise de compatibilidade com o Steam Deck`,
  _ = `Inclua perguntas ou comentários para a equipa de testes quando fizer o pedido de ajuda.`,
  _ = `Se tiver dúvidas específicas sobre o processo de análise da compatibilidade ou sobre os resultados do seu jogo, escreva-as abaixo.`,
  _ = `Caso pretenda que o seu jogo volte a ser analisado, clique no botão abaixo "ENVIAR PARA NOVA ANÁLISE" em vez de usar este formulário.`,
  _ = `Tenho uma pergunta ou comentário acerca do relatório de compatibilidade com o Steam Deck: `,
  _ = `Sim, o meu jogo tem compatibilidade total com comando; todas as funcionalidades são acessíveis por meio de um comando com a configuração padrão.`,
  _ = `Sim, o meu jogo mostra os ícones corretos do Steam Deck ou do comando da Xbox no jogo quando se referem aos botões de um comando.`,
  _ = `O meu jogo não requer nenhuma entrada de texto OU chama as APIs de entrada de texto do Steam apropriadas quando necessário.`,
  _ = `Não é necessário introduzir texto no meu jogo.`,
  _ = `O meu jogo chama as APIs de teclado/entrada de texto apropriadas do Steam quando é necessário introduzir texto.`,
  _ = `O meu jogo não usa as APIs do Steam quando é necessário introduzir texto.`,
  _ = `O meu jogo não armazena dados de progresso.`,
  _ = `O meu jogo armazena ficheiros de progresso, mas não na Steam Cloud.`,
  _ = `O meu jogo usa a Steam Cloud para armazenar ficheiros de progresso e só tem uma build para Windows.`,
  _ = `O meu jogo usa a Steam Cloud para armazenar ficheiros de progresso e os ficheiros funcionam entre plataformas (ou seja, Windows e Linux).`,
  _ = `O meu jogo usa a Steam Cloud para armazenar ficheiros de progresso, mas os ficheiros não funcionam entre plataformas (ou seja, Windows e Linux).`,
  _ = `Sim, o meu jogo pode ser executado com a resolução de 1280x800 (preferência) ou 1280x720.`,
  _ = `Sim, os caracteres mais pequenos no meu jogo nunca têm menos de 9 pixels de altura na resolução de 1280x800.`,
  _ = `O meu jogo não tem um launcher OU o launcher é completamente navegável com um comando.`,
  _ = `O meu jogo armazena ficheiros de progresso na Steam Cloud OU o meu jogo não armazena ficheiros de progresso.`,
  _ = `O meu jogo armazena ficheiros de progresso na Steam Cloud que são compatíveis entre plataformas OU o meu jogo só está disponível numa plataforma (Linux ou Windows).`,
  _ = `A não ser que o contrário seja indicado, iremos testar a sua build para Windows através de Proton.`,
  _ = `Se disponível, testar a minha build para Linux em vez da minha build para Windows`,
  _ = `O meu jogo não usa nenhum launcher ou ferramenta de configuração externa.`,
  _ = `O meu jogo usa um launcher que tem compatibilidade total com comando.`,
  _ = `O meu jogo usa um launcher que não é totalmente funcional se o utilizador só tiver um comando; requer teclado e/ou rato.`,
  _ = `(Embora ficheiros de progresso entre plataformas não sejam obrigatórios para um jogo receber a classificação "Aprovado", são úteis para utilizadores que ora joguem num PC com Windows, ora num Steam Deck a usar a versão nativa do jogo para Linux. Consulte a %1$s.)`,
  _ = `documentação`,
  _ = `(O ecrã do Steam Deck é muito mais pequeno do que a maioria dos monitores para PC. Se o seu jogo tiver texto pequeno, utilizadores do Deck podem ter problemas ao lê-lo, mesmo se for fácil de ler num monitor tradicional.)`,
  _ = `(A maioria dos utilizadores do Steam Deck não liga um teclado ao dispositivo, então depende do teclado virtual para poder escrever. O Steam fornece as APIs para que seja fácil utilizar teclados virtuais. Se o utilizador precisar de abrir o teclado manualmente, o seu jogo não poderá receber a classificação "Aprovado". Consulte as %1$s.)`,
  _ = `recomendações sobre entrada de texto`,
  _ = `(Se o seu jogo tiver um launcher, este tem de cumprir os mesmos requisitos que o jogo para poder ser "Aprovado": tem de poder ser usado só com os controlos do Steam Deck, tem de ser legível, etc. Se o seu launcher não cumprir estes requisitos, o seu jogo não poderá receber a classificação "Aprovado", mesmo se o jogo em si os cumprir. Consulte as %1$s.)`,
  _ = `recomendações sobre launchers`,
  _ = `(Grande parte dos utilizadores do Steam Deck também tem PCs. O jogo não precisa de armazenar ficheiros de progresso na Steam Cloud para poder ser considerado "Aprovado", mas é algo muito valioso para os utilizadores. Oferecer compatibilidade com a %1$s para ficheiros de progresso permite aos utilizadores guardar o progresso no computador e continuar o jogo no Deck ou vice‑versa.)`,
  _ = `Steam Cloud`,
  _ = `(Atenção: o seu jogo necessita de ter compatibilidade total com comando para poder obter a classificação "Aprovado".)`,
  _ = `O seu jogo está agora na fila para ser analisado.`,
  _ = `Iremos analisar o seu jogo em breve e entraremos em contacto consigo caso encontremos problemas.`,
  _ = `Conclua a verificação da sua build do Steam antes de efetuar o envio para análise de compatibilidade com hardware.`,
  _ = `O seu jogo não é jogável no Steam Deck de momento`,
  _ = `O seu jogo não é totalmente compatível com o Steam Deck devido a problemas relativos ao Proton ou ao próprio Steam Deck. Tomámos nota destes problemas para trabalharmos na sua resolução. Entretanto, o seu jogo não vai abrir ou funcionar devidamente no Steam Deck.`,
  _ = `O seu jogo é "Jogável" no Steam Deck`,
  _ = `O seu jogo é jogável no Steam Deck, mas os utilizadores terão de seguir alguns passos adicionais para que possam interagir com o mesmo ou configurá-lo. Pode corrigir os problemas descritos abaixo e reenviar o jogo para análise de compatibilidade com o Steam Deck.`,
  _ = `Build`,
  _ = `Se disponível, testar a minha build para Android em vez da minha build para Windows`,
  _ = `Testar a minha build para Windows`,
  _ = `Testar a minha build para Linux`,
  _ = `Deveríamos testar a versão 2D ou de R.V. (se disponível)?`,
  _ = `2D`,
  _ = `R.V.`,
  _ = `Não aplicável a aplicações de %1$s`,
  _ = `Aprovado, sem qualquer utilização de "Apagar estado de avaliação de desempenho"`,
  _ = `Aprovado, com pelo menos uma utilização de "Apagar estado de avaliação de desempenho"`,
  _ = `Jogável, sem qualquer utilização de "Apagar estado de avaliação de desempenho"`,
  _ = `Jogável, com pelo menos uma utilização de "Apagar estado de avaliação de desempenho"`,
  _ = `Incompatível`,
  _ = `Jogo sem R.V. (a avaliação não se aplica)`,
  _ = `Painel de avaliação de desempenho`,
  _ = `Use o painel de avaliação de desempenho para preencher a resposta abaixo. Consulte a %1$s para mais informações.`,
  _ = `documentação sobre o desempenho da R.V.`,
  _ = `(Se o seu jogo tiver texto pequeno, utilizadores do Steam Frame podem ter problemas ao lê-lo, mesmo se for fácil de ler num monitor tradicional.)`,
  _ = `(A maioria dos utilizadores do Steam Frame não liga um teclado ao dispositivo, então depende do teclado virtual para poder escrever. O Steam fornece as APIs para que seja fácil utilizar teclados virtuais. Se o utilizador precisar de abrir o teclado manualmente, o seu jogo não poderá receber a classificação "Aprovado". Consulte a %1$s.)`,
  _ = `Lista de compatibilidade com o Steam Frame`,
  _ = `(Se o seu jogo tiver um launcher, este tem de cumprir os mesmos requisitos que o jogo para poder ser "Aprovado": tem de poder ser usado só com os controlos do Steam Frame, tem de ser legível, etc. Se o seu launcher não cumprir estes requisitos, o seu jogo não poderá receber a classificação "Aprovado", mesmo se o jogo em si os cumprir. Consulte as %1$s.)`,
  _ = `(Grande parte dos utilizadores do Steam Frame também tem PCs. O jogo não precisa de armazenar ficheiros de progresso na Steam Cloud para poder ser considerado "Aprovado", mas é algo muito valioso para os utilizadores. Oferecer compatibilidade com a %1$s para ficheiros de progresso permite aos utilizadores guardar o progresso no computador e continuar o jogo no Steam Frame ou vice‑versa.)`,
  _ = `(Embora ficheiros de progresso entre plataformas não sejam obrigatórios para um jogo receber a classificação "Aprovado", são úteis para utilizadores que ora joguem num PC com Windows, ora num Steam Frame a usar a versão nativa do jogo para Linux. Consulte a %1$s.)`,
  _ = `Sim, o meu jogo mostra os ícones corretos do Steam Frame/Deck ou do comando da Xbox no jogo quando se referem aos botões de um comando.`,
  _ = `Se o resultado da avaliação de desempenho acima exigiu pelo menos uma utilização de "Apagar estado de avaliação de desempenho", selecione um ou mais motivos abaixo.`,
  _ = `O desempenho é reduzido ao iniciar o jogo`,
  _ = `O desempenho é reduzido durante ecrãs de carregamento`,
  _ = `Outro motivo (é necessário especificar)`,
  _ = `Solicitou uma análise da versão para Android, mas %1$s não possui nenhum depot para Android.`,
  _ = `o seu pacote complementar de desenvolvimento`,
  _ = `dummy`,
  _ = {
    Valve_Confidential: _,
    Valve_Confidential_Description: _,
    Footer_Description: _,
    Footer_Sitemap_ContactSupport: _,
    PricingExplorer_LoadError: _,
    PricingExplorer_About_Title: _,
    PricingExplorer_About_Desc1: _,
    PricingExplorer_About_Desc2: _,
    PricingExplorer_About_Link1: _,
    PricingExplorer_About_LinkName1: _,
    PricingExplorer_About_Link2: _,
    PricingExplorer_About_LinkName2: _,
    PricingExplorer_About_Dash: _,
    PricingExplorer_About_LastUpdated: _,
    PricingExplorer_Explore_title: _,
    PricingExplorer_Explore_desc1: _,
    PricingExplorer_Explore_line1: _,
    PricingExplorer_Explore_line2: _,
    PricingExplorer_Explore_line3: _,
    PricingExplorer_Base: _,
    PricingExplorer_BasePrice: _,
    PricingExplorer_TableHeader: _,
    PricingExplorer_Column1: _,
    PricingExplorer_Column2: _,
    PricingExplorer_Column3: _,
    PricingExplorer_Column4: _,
    PricingExplorer_Regions_TableHeader: _,
    PricingExplorer_Regions_Column1: _,
    Pricing_Dummy: _,
    ContentSurvey_Title: _,
    ContentSurvey_Title_Default: _,
    ContentSurvey_History_Title: _,
    ContentSurvey_History_Title_Default: _,
    ContentSurvey_InvalidApp: _,
    PartnerSite_PermissionDenied: _,
    PartnerSite_NotLoggedIn: _,
    SteamDeck_BuildReview_Status_Raw_Title: _,
    SteamDeck_BuildReview_Status_Raw_Description: _,
    SteamDeck_BuildReview_Status_TestProperties_Description: _,
    SteamDeck_BuildReview_Status_TestProperties_Playable: _,
    SteamDeck_BuildReview_Status_TestProperty_Name: _,
    SteamDeck_BuildReview_Status_TestProperty_Value: _,
    SteamDeck_BuildReview_Status_TestProperty_Desc: _,
    SteamDeck_BuildReview_Status_Description: _,
    SteamDeck_BuildReview_Header_History: _,
    SteamDeck_BuildReview_Header_Results: _,
    SteamDeck_BuildReview_Status_Raw_Result: _,
    SteamDeck_BuildReview_Status_Raw_Test: _,
    SteamDeck_BuildReview_Status_Raw_Comment: _,
    SteamDeck_BuildReview_Status_Raw_Impact: _,
    SteamDeck_BuildReview_Status_Pass: _,
    SteamDeck_BuildReview_Status_Fail: _,
    SteamDeck_BuildReview_Status_FailMinor: _,
    SteamDeck_BuildReview_Status_NotApplicable: `---`,
    SteamDeck_BuildReview_Viewing_Historical: _,
    SteamDeck_BuildReview_Viewing_Published: _,
    SteamDeck_BuildReview_PublishedOn: _,
    SteamDeck_BuildReview_ReportedOn: _,
    SteamDeck_BuildReview_Documentation: _,
    SteamDeck_BuildReview_PublishResults: _,
    SteamDeck_BuildReview_PublishDialog_Title: _,
    SteamDeck_BuildReview_PublishDialog_Body: _,
    SteamDeck_BuildReview_UnknownError: _,
    SteamDeck_BuildReview_Help_Request_Title: _,
    SteamDeck_BuildReview_RequestStatusActive: _,
    SteamDeck_BuildReview_RequestStatusClosed: _,
    SteamDeck_BuildReview_InReview_ViewTicket: _,
    SteamDeck_BuildReview_Create_HelpRequest: _,
    SteamDeck_BuildReview_Create_HelpRequest_NotesDefault: _,
    SteamDeck_BuildReview_Create_HelpRequest_NotesDefault_Rereview: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label_Machine: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Button: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_1: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2a: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2b: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Ticket_Content: _,
    SteamDeck_BuildReview_CompatibilityTests: _,
    SteamDeck_BuildReview_Status_Title: _,
    SteamDeck_HardwareCompatibility_Title: _,
    SteamDeck_AppLanding_Published: _,
    SteamDeck_AppLanding_Unpublished: _,
    SteamDeck_AppLanding_History: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RecommendedRuntime: _,
    SteamDeckVerified_TestDisplayName_TestPropertyDescription_RecommendedRuntime:
      _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_ExpectedInput: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RequiresH264: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TestedProtonVersion: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TestedBuildID: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RPODebug: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_FDMDebug: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TSOEnable: _,
    SteamHardware_BuildReview_Unknown_Title: _,
    SteamHardware_BuildReview_Unsupported_Title: _,
    SteamHardware_BuildReview_Unsupported_Description: _,
    SteamHardware_BuildReview_Playable_Title: _,
    SteamHardware_BuildReview_Playable_Description: _,
    SteamHardware_BuildReview_Verified_Title: _,
    SteamHardware_BuildReview_Verified_Description: _,
    SteamHardware_BuildReview_Verified_Share: _,
    SteamHardware_Machine_Unknown: _,
    SteamHardware_Frame_Unknown: _,
    SteamHardware_RatingImpact_Playable: _,
    SteamHardware_RatingImpact_Unsupported: _,
    SteamHardware_RatingImpact_Informational: _,
    SteamDeckVerified_TestDisplayName_0: _,
    SteamDeckVerified_TestDisplayName_1: _,
    SteamDeckVerified_TestDisplayName_2: _,
    SteamDeckVerified_TestDisplayName_3: _,
    SteamDeckVerified_TestDisplayName_4: _,
    SteamDeckVerified_TestDisplayName_5: _,
    SteamDeckVerified_TestDisplayName_6: _,
    SteamDeckVerified_TestDisplayName_7: _,
    SteamDeckVerified_TestDisplayName_8: _,
    SteamDeckVerified_TestDisplayName_9: _,
    SteamDeckVerified_TestDisplayName_10: _,
    SteamDeckVerified_TestDisplayName_11: _,
    SteamDeckVerified_TestDisplayName_12: _,
    SteamDeckVerified_TestDisplayName_13: _,
    SteamDeckVerified_TestDisplayName_14: _,
    SteamDeckVerified_TestDisplayName_15: _,
    SteamDeckVerified_TestDisplayName_16: _,
    SteamDeckVerified_TestDisplayName_17: _,
    SteamDeckVerified_TestDisplayName_18: _,
    SteamDeckVerified_TestDisplayName_19: _,
    SteamDeckVerified_TestDisplayName_20: _,
    SteamDeckVerified_TestDisplayName_21: _,
    SteamDeckVerified_TestDisplayName_22: _,
    SteamDeckVerified_TestDisplayName_23: _,
    SteamDeckVerified_TestDisplayName_24: _,
    SteamDeckVerified_TestDisplayName_25: _,
    SteamDeckVerified_TestDisplayName_26: _,
    SteamDeckVerified_TestDisplayName_27: _,
    SteamDeckVerified_TestDisplayName_29: _,
    SteamDeckVerified_TestDisplayName_30: _,
    SteamDeckVerified_TestDisplayName_31: _,
    SteamDeckVerified_TestDisplayName_32: _,
    SteamDeckVerified_TestDisplayName_33: _,
    SteamDeckVerified_TestDisplayName_34: _,
    SteamDeckVerified_TestDisplayName_35: _,
    SteamDeckVerified_TestDisplayName_36: _,
    SteamDeckVerified_TestDisplayName_37: _,
    SteamDeckVerified_TestDisplayName_38: _,
    SteamDeckVerified_TestDisplayName_39: _,
    SteamDeckVerified_TestDisplayName_40: _,
    SteamDeckVerified_TestDisplayName_41: _,
    SteamDeckVerified_TestDisplayName_42: _,
    SteamDeckVerified_TestDisplayName_43: _,
    SteamDeckVerified_TestDisplayName_44: _,
    SteamDeckVerified_TestDisplayName_45: _,
    SteamDeckVerified_TestDisplayName_46: _,
    SteamDeckVerified_TestDisplayName_47: _,
    SteamDeckVerified_TestDisplayName_48: _,
    SteamDeckVerified_TestDisplayName_49: _,
    SteamDeckVerified_TestDisplayName_50: _,
    SteamDeckVerified_TestDisplayName_51: _,
    SteamDeckVerified_TestDisplayName_52: _,
    SteamDeckVerified_TestDisplayName_53: _,
    SteamDeckVerified_TestDisplayName_54: _,
    SteamDeckVerified_TestDisplayName_55: _,
    SteamDeckVerified_TestDisplayName_56: _,
    SteamDeckVerified_TestDisplayName_57: _,
    SteamDeckVerified_TestDisplayName_58: _,
    SteamDeckVerified_TestDisplayName_59: _,
    SteamDeckVerified_TestDisplayName_60: _,
    SteamDeckVerified_TestDisplayName_61: _,
    SteamDeckVerified_TestDisplayName_62: _,
    SteamDeckVerified_TestDisplayName_63: _,
    SteamDeckVerified_TestDisplayName_64: _,
    SteamDeckVerified_TestDisplayName_65: _,
    Compatibility_Tab_Steam_Machine: _,
    Compatibility_Tab_Steam_OS: _,
    Compatibility_Tab_Steam_Deck: _,
    Compatibility_Tab_Steam_Frame: _,
    SteamDeck_BuildReview_PleaseRequestTest: _,
    SteamFrame_BuildReview_Checklist_Intro_Header_V2: _,
    SteamFrame_BuildReview_PleaseConfirm_Title_V2: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P1: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P3: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P3_ReviewProcess: _,
    SteamFrame_BuildReview_PleaseConfirm_Description_V2: _,
    SteamDeck_TestRequest_BuildNotReleased: _,
    SteamDeck_BuildReview_Checklist_Intro: _,
    SteamDeck_BuildReview_Checklist_Intro_Header_V2: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P1: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P2: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3_ReviewProcess: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3_Additional: _,
    SteamDeck_BuildReview_PleaseConfirm_Title_V2: _,
    SteamDeck_BuildReview_PleaseConfirm_Description_V2: _,
    SteamDeck_BuildReview_AppTypeUnavailable: _,
    SteamDeck_BuildReview_Checklist_Input: _,
    SteamDeck_BuildReview_Checklist_Text: _,
    SteamDeck_BuildReview_Checklist_Display: _,
    SteamDeck_BuildReview_Checklist_Functionality: _,
    SteamDeck_BuildReview_Checklist_SteamCloud: _,
    SteamDeck_BuildReview_Checklist_Launcher: _,
    SteamDeck_BuildReview_Checklist_Branch: _,
    SteamDeck_BuildReview_Checklist_Branch_PleaseTest: _,
    SteamDeck_BuildReview_MarkReady_Button: _,
    SteamDeck_BuildReview_MarkReady_Description: _,
    SteamDeck_BuildReview_MarkReady_Notes: _,
    SteamDeck_BuildReview_MarkReady_NotesDefault: _,
    SteamDeck_BuildReview_HelpRequest_Link: _,
    SteamDeck_BuildReview_ViewMoreDetailsInHelp: _,
    SteamDeck_BuildReview_Create_HelpRequest_Title: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes_1: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes_2: _,
    SteamDeck_BuildReview_Create_HelpRequest_SupportTicketIntro: _,
    SteamDeck_BuildReview_Check_Controller: _,
    SteamDeck_BuildReview_Check_Icons: _,
    SteamDeck_BuildReview_Check_TextInput: _,
    SteamDeck_BuildReview_Check_TextInput_V2_NoTextEntry: _,
    SteamDeck_BuildReview_Check_TextInput_V2_YesSteamAPIs: _,
    SteamDeck_BuildReview_Check_TextInput_V2_NoSteamAPIs: _,
    SteamDeck_BuildReview_Check_Cloud_NoSaves: _,
    SteamDeck_BuildReview_Check_Cloud_YesSavesNoCloud: _,
    SteamDeck_BuildReview_Check_Cloud_SinglePlatform: _,
    SteamDeck_BuildReview_Check_Cloud_YesCrossSaves: _,
    SteamDeck_BuildReview_Check_Cloud_NoCrossSaves: _,
    SteamDeck_BuildReview_Check_Display1280: _,
    SteamDeck_BuildReview_Check_DisplayFont: _,
    SteamDeck_BuildReview_Check_FunctionalityLauncher: _,
    SteamDeck_BuildReview_Check_FunctionalityCloudSaves: _,
    SteamDeck_BuildReview_Check_FunctionalityCrossPlatformCloudSaves: _,
    SteamDeck_BuildReview_Check_TestLinuxBuild_Preamble: _,
    SteamDeck_BuildReview_Check_TestLinuxBuild: _,
    SteamDeck_BuildReview_Check_Launcher_V2_NoLauncher: _,
    SteamDeck_BuildReview_Check_Launcher_V2_ControllerSupport: _,
    SteamDeck_BuildReview_Check_Launcher_V2_NoControllerSupport: _,
    SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves: _,
    SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves_Documentation: _,
    SteamDeck_BuildReview_CheckNote_DisplayFont: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_InputRecommendations:
      _,
    SteamDeck_BuildReview_CheckNote_Launcher_V2_NoControllerSupport: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_LauncherRecommendations:
      _,
    SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud: _,
    SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud_SteamCloud: _,
    SteamDeck_BuildReview_CheckNote_FullController: _,
    SteamDeck_BuildReview_InReview_Title: _,
    SteamDeck_BuildReview_InReview_Description: _,
    SteamDeck_BuildReview_PleaseComplete: _,
    SteamDeck_BuildReview_Unsupported_Title: _,
    SteamDeck_BuildReview_Unsupported_Description: _,
    SteamDeck_BuildReview_NotMeetRequirements_Title: _,
    SteamDeck_BuildReview_NotMeetRequirements_Description: _,
    SteamFrame_BuildReview_Checklist_Build: _,
    SteamFrame_BuildReview_Build_Android: _,
    SteamFrame_BuildReview_Build_Windows: _,
    SteamFrame_BuildReview_Build_Linux: _,
    SteamFrame_BuildReview_Checklist_Dimension: _,
    SteamFrame_BuildReview_Dimension_2D: `2D`,
    SteamFrame_BuildReview_Dimension_VR: _,
    SteamFrame_NotApplicableForDimension: _,
    SteamFrame_BuildReview_Check_VRPerformance_Verified_Without: _,
    SteamFrame_BuildReview_Check_VRPerformance_Verified_With: _,
    SteamFrame_BuildReview_Check_VRPerformance_Playable_Without: _,
    SteamFrame_BuildReview_Check_VRPerformance_Playable_With: _,
    SteamFrame_BuildReview_Check_VRPerformance_Unsupported: _,
    SteamFrame_BuildReview_Check_VRPerformance_NotApplicable: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_Title: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_Description: _,
    SteamFrame_BuildReview_VRPerformanceLink: _,
    SteamFrame_BuildReview_CheckNote_DisplayFont: _,
    SteamFrame_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs: _,
    SteamFrame_BuildReview_Compatibility_Checklist: _,
    SteamFrame_BuildReview_CheckNote_Launcher_V2_NoControllerSupport: _,
    SteamFrame_BuildReview_CheckNote_Cloud_YesSavesNoCloud: _,
    SteamFrame_BuildReview_CheckNote_Cloud_NoCrossSaves: _,
    SteamFrame_BuildReview_Check_Icons: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_StatusReason: _,
    SteamFrame_BuildReview_Check_VRPerformance_Startup: _,
    SteamFrame_BuildReview_Check_VRPerformance_Loading: _,
    SteamFrame_BuildReview_Check_VRPerformance_Other: _,
    SteamFrame_BuildReview_CheckNote_Missing_Android_License: _,
    SteamFrame_BuildReview_CheckNote_Missing_Android_License_Link: _,
    dummy: _,
  };
export {
  _ as Compatibility_Tab_Steam_Deck,
  _ as Compatibility_Tab_Steam_Frame,
  _ as Compatibility_Tab_Steam_Machine,
  _ as Compatibility_Tab_Steam_OS,
  _ as ContentSurvey_History_Title,
  _ as ContentSurvey_History_Title_Default,
  _ as ContentSurvey_InvalidApp,
  _ as ContentSurvey_Title,
  _ as ContentSurvey_Title_Default,
  _ as Footer_Description,
  _ as Footer_Sitemap_ContactSupport,
  _ as PartnerSite_NotLoggedIn,
  _ as PartnerSite_PermissionDenied,
  _ as PricingExplorer_About_Dash,
  _ as PricingExplorer_About_Desc1,
  _ as PricingExplorer_About_Desc2,
  _ as PricingExplorer_About_LastUpdated,
  _ as PricingExplorer_About_Link1,
  _ as PricingExplorer_About_Link2,
  _ as PricingExplorer_About_LinkName1,
  _ as PricingExplorer_About_LinkName2,
  _ as PricingExplorer_About_Title,
  _ as PricingExplorer_Base,
  _ as PricingExplorer_BasePrice,
  _ as PricingExplorer_Column1,
  _ as PricingExplorer_Column2,
  _ as PricingExplorer_Column3,
  _ as PricingExplorer_Column4,
  _ as PricingExplorer_Explore_desc1,
  _ as PricingExplorer_Explore_line1,
  _ as PricingExplorer_Explore_line2,
  _ as PricingExplorer_Explore_line3,
  _ as PricingExplorer_Explore_title,
  _ as PricingExplorer_LoadError,
  _ as PricingExplorer_Regions_Column1,
  _ as PricingExplorer_Regions_TableHeader,
  _ as PricingExplorer_TableHeader,
  _ as Pricing_Dummy,
  _ as SteamDeckVerified_TestDisplayName_0,
  _ as SteamDeckVerified_TestDisplayName_1,
  _ as SteamDeckVerified_TestDisplayName_10,
  _ as SteamDeckVerified_TestDisplayName_11,
  _ as SteamDeckVerified_TestDisplayName_12,
  _ as SteamDeckVerified_TestDisplayName_13,
  _ as SteamDeckVerified_TestDisplayName_14,
  _ as SteamDeckVerified_TestDisplayName_15,
  _ as SteamDeckVerified_TestDisplayName_16,
  _ as SteamDeckVerified_TestDisplayName_17,
  _ as SteamDeckVerified_TestDisplayName_18,
  _ as SteamDeckVerified_TestDisplayName_19,
  _ as SteamDeckVerified_TestDisplayName_2,
  _ as SteamDeckVerified_TestDisplayName_20,
  _ as SteamDeckVerified_TestDisplayName_21,
  _ as SteamDeckVerified_TestDisplayName_22,
  _ as SteamDeckVerified_TestDisplayName_23,
  _ as SteamDeckVerified_TestDisplayName_24,
  _ as SteamDeckVerified_TestDisplayName_25,
  _ as SteamDeckVerified_TestDisplayName_26,
  _ as SteamDeckVerified_TestDisplayName_27,
  _ as SteamDeckVerified_TestDisplayName_29,
  _ as SteamDeckVerified_TestDisplayName_3,
  _ as SteamDeckVerified_TestDisplayName_30,
  _ as SteamDeckVerified_TestDisplayName_31,
  _ as SteamDeckVerified_TestDisplayName_32,
  _ as SteamDeckVerified_TestDisplayName_33,
  _ as SteamDeckVerified_TestDisplayName_34,
  _ as SteamDeckVerified_TestDisplayName_35,
  _ as SteamDeckVerified_TestDisplayName_36,
  _ as SteamDeckVerified_TestDisplayName_37,
  _ as SteamDeckVerified_TestDisplayName_38,
  _ as SteamDeckVerified_TestDisplayName_39,
  _ as SteamDeckVerified_TestDisplayName_4,
  _ as SteamDeckVerified_TestDisplayName_40,
  _ as SteamDeckVerified_TestDisplayName_41,
  _ as SteamDeckVerified_TestDisplayName_42,
  _ as SteamDeckVerified_TestDisplayName_43,
  _ as SteamDeckVerified_TestDisplayName_44,
  _ as SteamDeckVerified_TestDisplayName_45,
  _ as SteamDeckVerified_TestDisplayName_46,
  _ as SteamDeckVerified_TestDisplayName_47,
  _ as SteamDeckVerified_TestDisplayName_48,
  _ as SteamDeckVerified_TestDisplayName_49,
  _ as SteamDeckVerified_TestDisplayName_5,
  _ as SteamDeckVerified_TestDisplayName_50,
  _ as SteamDeckVerified_TestDisplayName_51,
  _ as SteamDeckVerified_TestDisplayName_52,
  _ as SteamDeckVerified_TestDisplayName_53,
  _ as SteamDeckVerified_TestDisplayName_54,
  _ as SteamDeckVerified_TestDisplayName_55,
  _ as SteamDeckVerified_TestDisplayName_56,
  _ as SteamDeckVerified_TestDisplayName_57,
  _ as SteamDeckVerified_TestDisplayName_58,
  _ as SteamDeckVerified_TestDisplayName_59,
  _ as SteamDeckVerified_TestDisplayName_6,
  _ as SteamDeckVerified_TestDisplayName_60,
  _ as SteamDeckVerified_TestDisplayName_61,
  _ as SteamDeckVerified_TestDisplayName_62,
  _ as SteamDeckVerified_TestDisplayName_63,
  _ as SteamDeckVerified_TestDisplayName_64,
  _ as SteamDeckVerified_TestDisplayName_65,
  _ as SteamDeckVerified_TestDisplayName_7,
  _ as SteamDeckVerified_TestDisplayName_8,
  _ as SteamDeckVerified_TestDisplayName_9,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyDescription_RecommendedRuntime,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_ExpectedInput,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_FDMDebug,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RPODebug,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RecommendedRuntime,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RequiresH264,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TSOEnable,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TestedBuildID,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TestedProtonVersion,
  _ as SteamDeck_AppLanding_History,
  _ as SteamDeck_AppLanding_Published,
  _ as SteamDeck_AppLanding_Unpublished,
  _ as SteamDeck_BuildReview_AppTypeUnavailable,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves_Documentation,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud_SteamCloud,
  _ as SteamDeck_BuildReview_CheckNote_DisplayFont,
  _ as SteamDeck_BuildReview_CheckNote_FullController,
  _ as SteamDeck_BuildReview_CheckNote_Launcher_V2_NoControllerSupport,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_InputRecommendations,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_LauncherRecommendations,
  _ as SteamDeck_BuildReview_Check_Cloud_NoCrossSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_NoSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_SinglePlatform,
  _ as SteamDeck_BuildReview_Check_Cloud_YesCrossSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_YesSavesNoCloud,
  _ as SteamDeck_BuildReview_Check_Controller,
  _ as SteamDeck_BuildReview_Check_Display1280,
  _ as SteamDeck_BuildReview_Check_DisplayFont,
  _ as SteamDeck_BuildReview_Check_FunctionalityCloudSaves,
  _ as SteamDeck_BuildReview_Check_FunctionalityCrossPlatformCloudSaves,
  _ as SteamDeck_BuildReview_Check_FunctionalityLauncher,
  _ as SteamDeck_BuildReview_Check_Icons,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_ControllerSupport,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_NoControllerSupport,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_NoLauncher,
  _ as SteamDeck_BuildReview_Check_TestLinuxBuild,
  _ as SteamDeck_BuildReview_Check_TestLinuxBuild_Preamble,
  _ as SteamDeck_BuildReview_Check_TextInput,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_NoSteamAPIs,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_NoTextEntry,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_YesSteamAPIs,
  _ as SteamDeck_BuildReview_Checklist_Branch,
  _ as SteamDeck_BuildReview_Checklist_Branch_PleaseTest,
  _ as SteamDeck_BuildReview_Checklist_Display,
  _ as SteamDeck_BuildReview_Checklist_Functionality,
  _ as SteamDeck_BuildReview_Checklist_Input,
  _ as SteamDeck_BuildReview_Checklist_Intro,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P1,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P2,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3_Additional,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3_ReviewProcess,
  _ as SteamDeck_BuildReview_Checklist_Intro_Header_V2,
  _ as SteamDeck_BuildReview_Checklist_Launcher,
  _ as SteamDeck_BuildReview_Checklist_SteamCloud,
  _ as SteamDeck_BuildReview_Checklist_Text,
  _ as SteamDeck_BuildReview_CompatibilityTests,
  _ as SteamDeck_BuildReview_Create_HelpRequest,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_1,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2a,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2b,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes,
  _ as SteamDeck_BuildReview_Create_HelpRequest_NotesDefault,
  _ as SteamDeck_BuildReview_Create_HelpRequest_NotesDefault_Rereview,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes_1,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes_2,
  _ as SteamDeck_BuildReview_Create_HelpRequest_SupportTicketIntro,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Title,
  _ as SteamDeck_BuildReview_Documentation,
  _ as SteamDeck_BuildReview_Header_History,
  _ as SteamDeck_BuildReview_Header_Results,
  _ as SteamDeck_BuildReview_HelpRequest_Link,
  _ as SteamDeck_BuildReview_Help_Request_Title,
  _ as SteamDeck_BuildReview_InReview_Description,
  _ as SteamDeck_BuildReview_InReview_Title,
  _ as SteamDeck_BuildReview_InReview_ViewTicket,
  _ as SteamDeck_BuildReview_MarkReady_Button,
  _ as SteamDeck_BuildReview_MarkReady_Description,
  _ as SteamDeck_BuildReview_MarkReady_Notes,
  _ as SteamDeck_BuildReview_MarkReady_NotesDefault,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Description,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Button,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label_Machine,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Ticket_Content,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Title,
  _ as SteamDeck_BuildReview_PleaseComplete,
  _ as SteamDeck_BuildReview_PleaseConfirm_Description_V2,
  _ as SteamDeck_BuildReview_PleaseConfirm_Title_V2,
  _ as SteamDeck_BuildReview_PleaseRequestTest,
  _ as SteamDeck_BuildReview_PublishDialog_Body,
  _ as SteamDeck_BuildReview_PublishDialog_Title,
  _ as SteamDeck_BuildReview_PublishResults,
  _ as SteamDeck_BuildReview_PublishedOn,
  _ as SteamDeck_BuildReview_ReportedOn,
  _ as SteamDeck_BuildReview_RequestStatusActive,
  _ as SteamDeck_BuildReview_RequestStatusClosed,
  _ as SteamDeck_BuildReview_Status_Description,
  _ as SteamDeck_BuildReview_Status_Fail,
  _ as SteamDeck_BuildReview_Status_FailMinor,
  _ as SteamDeck_BuildReview_Status_NotApplicable,
  _ as SteamDeck_BuildReview_Status_Pass,
  _ as SteamDeck_BuildReview_Status_Raw_Comment,
  _ as SteamDeck_BuildReview_Status_Raw_Description,
  _ as SteamDeck_BuildReview_Status_Raw_Impact,
  _ as SteamDeck_BuildReview_Status_Raw_Result,
  _ as SteamDeck_BuildReview_Status_Raw_Test,
  _ as SteamDeck_BuildReview_Status_Raw_Title,
  _ as SteamDeck_BuildReview_Status_TestProperties_Description,
  _ as SteamDeck_BuildReview_Status_TestProperties_Playable,
  _ as SteamDeck_BuildReview_Status_TestProperty_Desc,
  _ as SteamDeck_BuildReview_Status_TestProperty_Name,
  _ as SteamDeck_BuildReview_Status_TestProperty_Value,
  _ as SteamDeck_BuildReview_Status_Title,
  _ as SteamDeck_BuildReview_UnknownError,
  _ as SteamDeck_BuildReview_Unsupported_Description,
  _ as SteamDeck_BuildReview_Unsupported_Title,
  _ as SteamDeck_BuildReview_ViewMoreDetailsInHelp,
  _ as SteamDeck_BuildReview_Viewing_Historical,
  _ as SteamDeck_BuildReview_Viewing_Published,
  _ as SteamDeck_HardwareCompatibility_Title,
  _ as SteamDeck_TestRequest_BuildNotReleased,
  _ as SteamFrame_BuildReview_Build_Android,
  _ as SteamFrame_BuildReview_Build_Linux,
  _ as SteamFrame_BuildReview_Build_Windows,
  _ as SteamFrame_BuildReview_CheckNote_Cloud_NoCrossSaves,
  _ as SteamFrame_BuildReview_CheckNote_Cloud_YesSavesNoCloud,
  _ as SteamFrame_BuildReview_CheckNote_DisplayFont,
  _ as SteamFrame_BuildReview_CheckNote_Launcher_V2_NoControllerSupport,
  _ as SteamFrame_BuildReview_CheckNote_Missing_Android_License,
  _ as SteamFrame_BuildReview_CheckNote_Missing_Android_License_Link,
  _ as SteamFrame_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs,
  _ as SteamFrame_BuildReview_Check_Icons,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Loading,
  _ as SteamFrame_BuildReview_Check_VRPerformance_NotApplicable,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Other,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Playable_With,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Playable_Without,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Startup,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Unsupported,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Verified_With,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Verified_Without,
  _ as SteamFrame_BuildReview_Checklist_Build,
  _ as SteamFrame_BuildReview_Checklist_Dimension,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P1,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P3,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P3_ReviewProcess,
  _ as SteamFrame_BuildReview_Checklist_Intro_Header_V2,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_Description,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_StatusReason,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_Title,
  _ as SteamFrame_BuildReview_Compatibility_Checklist,
  _ as SteamFrame_BuildReview_Dimension_2D,
  _ as SteamFrame_BuildReview_Dimension_VR,
  _ as SteamFrame_BuildReview_PleaseConfirm_Description_V2,
  _ as SteamFrame_BuildReview_PleaseConfirm_Title_V2,
  _ as SteamFrame_BuildReview_VRPerformanceLink,
  _ as SteamFrame_NotApplicableForDimension,
  _ as SteamHardware_BuildReview_Playable_Description,
  _ as SteamHardware_BuildReview_Playable_Title,
  _ as SteamHardware_BuildReview_Unknown_Title,
  _ as SteamHardware_BuildReview_Unsupported_Description,
  _ as SteamHardware_BuildReview_Unsupported_Title,
  _ as SteamHardware_BuildReview_Verified_Description,
  _ as SteamHardware_BuildReview_Verified_Share,
  _ as SteamHardware_BuildReview_Verified_Title,
  _ as SteamHardware_Frame_Unknown,
  _ as SteamHardware_Machine_Unknown,
  _ as SteamHardware_RatingImpact_Informational,
  _ as SteamHardware_RatingImpact_Playable,
  _ as SteamHardware_RatingImpact_Unsupported,
  _ as Valve_Confidential,
  _ as Valve_Confidential_Description,
  _ as default,
  _ as dummy,
};
