var _ = `Tài liệu`,
  _ = `Trang chủ`,
  _ = `Bắt đầu`,
  _ = `Diện mạo cửa hàng`,
  _ = `Tính năng`,
  _ = `Tài chính`,
  _ = `Bán hàng & Marketing`,
  _ = `Steamworks SDK`,
  _ = `Giấy phép phòng máy`,
  _ = `Steam VR`,
  _ = `Xem tất cả`,
  _ = `Công cụ quản trị`,
  _ = `Tài nguyên`,
  _ = `Steam VR`,
  _ = `Chương trình phòng máy Steam`,
  _ = `Thảo luận Steamworks`,
  _ = `Video hướng dẫn về Steamworks`,
  _ = `Tin tức & Cập nhật`,
  _ = `Blog Steamworks`,
  _ = `Blog Steam`,
  _ = `Blog Steam VR`,
  _ = `Blog Steam Deck`,
  _ = `Steamworks`,
  _ = `ngôn ngữ`,
  _ = `Thay đổi ngôn ngữ`,
  _ = `Đăng xuất`,
  _ = `Đăng nhập`,
  _ = `Trang tổng quan`,
  _ = `SteamVR Tracking`,
  _ = `Ứng dụng & Gói sản phẩm`,
  _ = `Tất cả ứng dụng`,
  _ = `Xem gói sản phẩm`,
  _ = `Bộ sản phẩm`,
  _ = `Định giá`,
  _ = `MỚI: Định giá!`,
  _ = `Quản lý giảm giá`,
  _ = `MỚI: Chấp thuận đăng bán!`,
  _ = `Đăng ký tham gia sự kiện ưu đãi & lễ hội`,
  _ = `Steam Next Fest`,
  _ = `Thiết lập trang chủ nhà sáng tạo`,
  _ = `Thiết lập URL tùy chỉnh cho trang chủ nhà sáng tạo`,
  _ = `Công cụ & Dữ liệu marketing`,
  _ = `Quản lý ưu đãi hằng ngày`,
  _ = `Tương thích Steam Deck`,
  _ = `Hỗ trợ`,
  _ = `Công cụ`,
  _ = `Quản lý kinh tế`,
  _ = `Truy vấn mã Steam`,
  _ = `Cấm mã Steam`,
  _ = `Xem mẫu gói mã Steam`,
  _ = `Lưu lượng điều hướng cửa hàng & nền tảng Steam`,
  _ = `Hành động khuyến nghị cho danh mục`,
  _ = `Meet Steam tại hội nghị trong ngành`,
  _ = `Người dùng & Quyền hạn`,
  _ = `Tổng quan`,
  _ = `Thông tin công ty`,
  _ = `Xem ứng dụng`,
  _ = `Quản lý người dùng`,
  _ = `Quản lý nhóm`,
  _ = `Thông tin tài chính`,
  _ = `Tài liệu & Trợ giúp`,
  _ = `Truy cập nhóm cộng đồng nhà phát triển`,
  _ = `Truy cập diễn đàn nhà phát triển`,
  _ = `Liên hệ phát hành Steam`,
  _ = `Liên hệ đội hỗ trợ Steamworks`,
  _ = `Đội hỗ trợ nhà phát triển Steamworks`,
  _ = `Không trực thuộc`,
  _ = `Tìm ứng dụng bằng tên hoặc ID`,
  _ = `Xem tài liệu`,
  _ = `Xem tài liệu lưu trữ`,
  _ = `Thông tin gói`,
  _ = `Lịch sử người dùng`,
  _ = `Lịch sử mời người dùng`,
  _ = `Địa chỉ nhận thư`,
  _ = `Xem trước tài liệu mới`,
  _ = `Chuyển giao ứng dụng`,
  _ = `Chia sẻ ứng dụng`,
  _ = `Mua trực tiếp`,
  _ = `Xem chi tiết thanh toán ngân hàng`,
  _ = `Đối chiếu hóa đơn đã gửi`,
  _ = `Tạo/Quản lý hóa đơn`,
  _ = `Quản trị cửa hàng`,
  _ = `Nổi bật`,
  _ = `Trang chủ`,
  _ = `Công cụ OEM`,
  _ = `Gói vé OEM`,
  _ = `Chương trình phòng máy`,
  _ = `Quản lý phòng máy`,
  _ = `Quản lý giấy phép thương mại`,
  _ = `Lịch sử sử dụng`,
  _ = `Kiểm soát nội dung`,
  _ = `Nạp tiền ví`,
  _ = `Thiết lập`,
  _ = `Lịch sử hoạt động`,
  _ = `Duyệt nạp tiền`,
  _ = `Đổi tổ chức`,
  _ = `Đổi tổ chức Steamworks`,
  _ = `Tài khoản Steam của bạn là thành viên của nhiều tổ chức Steamworks.`,
  _ = `Nhiều tính năng Steamworks chỉ được truy cập dựa trên quyền hạn của bạn trong tổ chức Steamworks hiện tại.`,
  _ = `Vui lòng chọn từ menu thả xuống bên dưới để đổi:`,
  _ = `Đổi`,
  _ = `Hủy`,
  _ = `Khuyến mãi`,
  _ = `Trò chơi`,
  _ = `Ứng dụng`,
  _ = `Công cụ`,
  _ = `Demo`,
  _ = `DLC`,
  _ = `Mod`,
  _ = `Hướng dẫn`,
  _ = `Thiết lập`,
  _ = `Nhạc`,
  _ = `Plugin`,
  _ = `Phần cứng`,
  _ = `Video`,
  _ = `Sê-ri`,
  _ = `Tập`,
  _ = `Phim ảnh`,
  _ = `Bản Beta`,
  _ = `Thẻ mùa`,
  _ = `Điều hướng`,
  _ = {
    Header_Global_Documentation: _,
    Header_Global_Documentation_Home: _,
    Header_Global_Documentation_GettingStarted: _,
    Header_Global_Documentation_StorePresence: _,
    Header_Global_Documentation_Features: _,
    Header_Global_Documentation_Finance: _,
    Header_Global_Documentation_SalesMarketing: _,
    Header_Global_Documentation_SteamworksSDK: _,
    Header_Global_Documentation_PCCafe: _,
    Header_Global_Documentation_SteamVR: _,
    Header_Global_Documentation_Seeall: _,
    Header_Nav_DocumentationAdmin: _,
    Header_Global_Resources: _,
    Header_Global_Resources_SteamVR: _,
    Header_Global_Resources_PCCafe: _,
    Header_Global_Resources_Discussions: _,
    Header_Global_Resources_VideoTutorials: _,
    Header_Global_News: _,
    Header_Global_News_Steamworks: _,
    Header_Global_News_Steam: _,
    Header_Global_News_SteamVR: _,
    Header_Global_News_SteamDeck: _,
    Steamworks_Logo_Label: _,
    global_menu_language: _,
    global_menu_change_language: _,
    global_menu_sign_out: _,
    global_menu_sign_in: _,
    Header_Nav_Dashboard: _,
    Header_Nav_Lighthouse: _,
    Header_Nav_AppsPackages: _,
    Header_Nav_AppsPackages_All: _,
    Header_Nav_AppsPackages_ViewPackages: _,
    Header_Nav_AppsPackages_Bundles: _,
    Header_Nav_AppsPackages_Pricing: _,
    Header_Nav_AppsPackages_PricingNew: _,
    Header_Nav_AppsPackages_SaleApproval: _,
    Header_Nav_AppsPackages_SaleApprovalNew: _,
    Header_Nav_AppsPackages_Events: _,
    Header_Nav_AppsPackages_NextFestRecaps: _,
    Header_Nav_AppsPackages_CreatorHome: _,
    Header_Nav_AppsPackages_CreatorHome_Vanity: _,
    Header_Nav_PublisherMarketingStats: _,
    Header_Nav_DailyDeal_Management: _,
    Header_Nav_SteamDeck_Compat: _,
    Header_Nav_Support: _,
    Header_Nav_Tools: _,
    Header_Nav_Tools_Economy: _,
    Header_Nav_Tools_QueryCDKey: _,
    Header_Nav_Tools_BanCDKeys: _,
    Header_Nav_Tools_CDKeyRestrictions: _,
    Header_Nav_Tools_NavTraffic: _,
    Header_Nav_Tools_HealthChecks: _,
    Header_Nav_Tools_MeetSteam: _,
    Header_Nav_UsersPermissions: _,
    Header_Nav_UsersPermissions_Overview: _,
    Header_Nav_UsersPermissions_CompanyDetails: _,
    Header_Nav_UsersPermissions_Applications: _,
    Header_Nav_UsersPermissions_Users: _,
    Header_Nav_UsersPermissions_Groups: _,
    Header_Nav_FinancialInfo: _,
    Header_Nav_DocumentationHelp: _,
    Header_Nav_DeveloperCommunity: _,
    Header_Nav_DeveloperForums: _,
    Header_Nav_Contact_Steam: _,
    Header_Nav_Contact_Dev_Support: _,
    Header_Nav_Contact_Dev_Support2: _,
    Header_Nav_Unaffiliated: _,
    Header_Search_By_Appid: _,
    Header_Nav_ViewDocumentation: _,
    Header_Nav_ViewDocumentationArchive: _,
    Header_Nav_PackageDetails: _,
    Header_Nav_UserGroupHistory: _,
    Header_Nav_UserInviteHistory: _,
    Header_Nav_MailingAddresses: _,
    Header_Nav_PreviewNewDocumentation: _,
    Header_Nav_TransferRequests: _,
    Header_Nav_ShareApplications: _,
    Header_Nav_DirectPurchasing: _,
    Header_Nav_DirectPurchasing_Config: _,
    Header_Nav_DirectPurchasing_OpenInvoices: _,
    Header_Nav_DirectPurchasing_CreateInvoices: _,
    Header_Nav_StoreAdmin: _,
    Header_Nav_StoreAdmin_Spotlights: _,
    Header_Nav_StoreAdmin_Frontpage: _,
    Header_Nav_OEM: _,
    Header_Nav_OEM_Ticket_Batches: _,
    Header_Nav_Sites: _,
    Header_Nav_Sites_Edit_Sites: _,
    Header_Nav_Sites_Current_Usage: _,
    Header_Nav_Sites_Historical_Usage: _,
    Header_Nav_Sites_Content_Control: _,
    Header_Nav_WalletFunding: _,
    Header_Nav_WalletFunding_Config: _,
    Header_Nav_WalletFunding_Usage: _,
    Header_Nav_WalletFunding_Approval: _,
    change_partner_link: _,
    change_partner_dialog_title: _,
    change_partner_dialog_desc_part1: _,
    change_partner_dialog_desc_part2: _,
    change_partner_dialog_desc_part3: _,
    change_partner_dialog_submit: _,
    change_partner_dialog_cancel: _,
    AppType_TitleCase_Advertising: _,
    AppType_TitleCase_Game: _,
    AppType_TitleCase_Application: _,
    AppType_TitleCase_Tool: _,
    AppType_TitleCase_Demo: _,
    AppType_TitleCase_DLC: `DLC`,
    AppType_TitleCase_Mod: `Mod`,
    AppType_TitleCase_Guide: _,
    AppType_TitleCase_Config: _,
    AppType_TitleCase_Music: _,
    AppType_TitleCase_PlugIn: _,
    AppType_TitleCase_Hardware: _,
    AppType_TitleCase_Video: _,
    AppType_TitleCase_Series: _,
    AppType_TitleCase_Episode: _,
    AppType_TitleCase_Movie: _,
    AppType_TitleCase_Beta: _,
    AppType_TitleCase_DLC_SeasonPass: _,
    Aria_Navigation: _,
  };
export {
  _ as AppType_TitleCase_Advertising,
  _ as AppType_TitleCase_Application,
  _ as AppType_TitleCase_Beta,
  _ as AppType_TitleCase_Config,
  _ as AppType_TitleCase_DLC,
  _ as AppType_TitleCase_DLC_SeasonPass,
  _ as AppType_TitleCase_Demo,
  _ as AppType_TitleCase_Episode,
  _ as AppType_TitleCase_Game,
  _ as AppType_TitleCase_Guide,
  _ as AppType_TitleCase_Hardware,
  _ as AppType_TitleCase_Mod,
  _ as AppType_TitleCase_Movie,
  _ as AppType_TitleCase_Music,
  _ as AppType_TitleCase_PlugIn,
  _ as AppType_TitleCase_Series,
  _ as AppType_TitleCase_Tool,
  _ as AppType_TitleCase_Video,
  _ as Aria_Navigation,
  _ as Header_Global_Documentation,
  _ as Header_Global_Documentation_Features,
  _ as Header_Global_Documentation_Finance,
  _ as Header_Global_Documentation_GettingStarted,
  _ as Header_Global_Documentation_Home,
  _ as Header_Global_Documentation_PCCafe,
  _ as Header_Global_Documentation_SalesMarketing,
  _ as Header_Global_Documentation_Seeall,
  _ as Header_Global_Documentation_SteamVR,
  _ as Header_Global_Documentation_SteamworksSDK,
  _ as Header_Global_Documentation_StorePresence,
  _ as Header_Global_News,
  _ as Header_Global_News_Steam,
  _ as Header_Global_News_SteamDeck,
  _ as Header_Global_News_SteamVR,
  _ as Header_Global_News_Steamworks,
  _ as Header_Global_Resources,
  _ as Header_Global_Resources_Discussions,
  _ as Header_Global_Resources_PCCafe,
  _ as Header_Global_Resources_SteamVR,
  _ as Header_Global_Resources_VideoTutorials,
  _ as Header_Nav_AppsPackages,
  _ as Header_Nav_AppsPackages_All,
  _ as Header_Nav_AppsPackages_Bundles,
  _ as Header_Nav_AppsPackages_CreatorHome,
  _ as Header_Nav_AppsPackages_CreatorHome_Vanity,
  _ as Header_Nav_AppsPackages_Events,
  _ as Header_Nav_AppsPackages_NextFestRecaps,
  _ as Header_Nav_AppsPackages_Pricing,
  _ as Header_Nav_AppsPackages_PricingNew,
  _ as Header_Nav_AppsPackages_SaleApproval,
  _ as Header_Nav_AppsPackages_SaleApprovalNew,
  _ as Header_Nav_AppsPackages_ViewPackages,
  _ as Header_Nav_Contact_Dev_Support,
  _ as Header_Nav_Contact_Dev_Support2,
  _ as Header_Nav_Contact_Steam,
  _ as Header_Nav_DailyDeal_Management,
  _ as Header_Nav_Dashboard,
  _ as Header_Nav_DeveloperCommunity,
  _ as Header_Nav_DeveloperForums,
  _ as Header_Nav_DirectPurchasing,
  _ as Header_Nav_DirectPurchasing_Config,
  _ as Header_Nav_DirectPurchasing_CreateInvoices,
  _ as Header_Nav_DirectPurchasing_OpenInvoices,
  _ as Header_Nav_DocumentationAdmin,
  _ as Header_Nav_DocumentationHelp,
  _ as Header_Nav_FinancialInfo,
  _ as Header_Nav_Lighthouse,
  _ as Header_Nav_MailingAddresses,
  _ as Header_Nav_OEM,
  _ as Header_Nav_OEM_Ticket_Batches,
  _ as Header_Nav_PackageDetails,
  _ as Header_Nav_PreviewNewDocumentation,
  _ as Header_Nav_PublisherMarketingStats,
  _ as Header_Nav_ShareApplications,
  _ as Header_Nav_Sites,
  _ as Header_Nav_Sites_Content_Control,
  _ as Header_Nav_Sites_Current_Usage,
  _ as Header_Nav_Sites_Edit_Sites,
  _ as Header_Nav_Sites_Historical_Usage,
  _ as Header_Nav_SteamDeck_Compat,
  _ as Header_Nav_StoreAdmin,
  _ as Header_Nav_StoreAdmin_Frontpage,
  _ as Header_Nav_StoreAdmin_Spotlights,
  _ as Header_Nav_Support,
  _ as Header_Nav_Tools,
  _ as Header_Nav_Tools_BanCDKeys,
  _ as Header_Nav_Tools_CDKeyRestrictions,
  _ as Header_Nav_Tools_Economy,
  _ as Header_Nav_Tools_HealthChecks,
  _ as Header_Nav_Tools_MeetSteam,
  _ as Header_Nav_Tools_NavTraffic,
  _ as Header_Nav_Tools_QueryCDKey,
  _ as Header_Nav_TransferRequests,
  _ as Header_Nav_Unaffiliated,
  _ as Header_Nav_UserGroupHistory,
  _ as Header_Nav_UserInviteHistory,
  _ as Header_Nav_UsersPermissions,
  _ as Header_Nav_UsersPermissions_Applications,
  _ as Header_Nav_UsersPermissions_CompanyDetails,
  _ as Header_Nav_UsersPermissions_Groups,
  _ as Header_Nav_UsersPermissions_Overview,
  _ as Header_Nav_UsersPermissions_Users,
  _ as Header_Nav_ViewDocumentation,
  _ as Header_Nav_ViewDocumentationArchive,
  _ as Header_Nav_WalletFunding,
  _ as Header_Nav_WalletFunding_Approval,
  _ as Header_Nav_WalletFunding_Config,
  _ as Header_Nav_WalletFunding_Usage,
  _ as Header_Search_By_Appid,
  _ as Steamworks_Logo_Label,
  _ as change_partner_dialog_cancel,
  _ as change_partner_dialog_desc_part1,
  _ as change_partner_dialog_desc_part2,
  _ as change_partner_dialog_desc_part3,
  _ as change_partner_dialog_submit,
  _ as change_partner_dialog_title,
  _ as change_partner_link,
  _ as default,
  _ as global_menu_change_language,
  _ as global_menu_language,
  _ as global_menu_sign_in,
  _ as global_menu_sign_out,
};
