var _ = `Valve: Απόρρητο`,
  _ = `Αυτή η σελίδα περιορισμένης πρόσβασης περιέχει εμπιστευτικές πληροφορίες της Valve. Πρέπει να έχετε σύμβαση εμπιστευτικότητας ή/και συμφωνητικό άδειας χρήσης που καλύπτει τις εμπιστευτικές πληροφορίες με τη Valve για να χρησιμοποιήσετε ή να αποκτήσετε πρόσβαση σε αυτήν τη σελίδα.`,
  _ = `Το Steamworks είναι το σύνολο εργαλείων και υπηρεσιών που έχουν φτιαχτεί από τη <1>Valve</1> και σας βοηθούν να διαμορφώσετε, να διαχειριστείτε και να λειτουργήσετε το παιχνίδι σας στο <2>Steam</2>.`,
  _ = `Επικοινωνήστε με την Υποστήριξη`,
  _ = `Σφάλμα κατά τη φόρτωση στοιχείων τιμολόγησης. Δοκιμάστε ξανά σε λίγο.`,
  _ = `Σχετικά με την τιμολόγηση ανά περιοχή`,
  _ = `Η τιμή για κάθε προϊόν στο Steam προσδιορίζεται και εμφανίζεται χρησιμοποιώντας %1$s διαφορετικά νομίσματα και %2$s <1>ομάδες περιοχών</1>. Το Steam προσφέρει εργαλεία για να σας βοηθήσει να ορίσετε και να διαχειριστείτε την τιμή του παιχνιδιού σας, σε επίπεδα που είναι κατάλληλα για κάθε αγορά.`,
  _ = `Οι τιμές που εισάγετε για το παιχνίδι σας σε κάθε νόμισμα και ομάδα περιοχής εξαρτώνται από εσάς.`,
  _ = `Για περισσότερες λεπτομέρειες σχετικά με τη διαχείριση της τιμολόγησής σας, δείτε την %1$s.`,
  _ = `τεκμηρίωση τιμολόγησης`,
  _ = `Για να διαχειριστείτε την τιμολόγηση του παιχνιδιού σας, μεταβείτε στον %1$s.`,
  _ = `Επισκεφθείτε τον πίνακα ελέγχου τιμολόγησης`,
  _ = `Για να διαχειριστείτε την τιμολόγηση του παιχνιδιού σας, μεταβείτε στον πίνακα ελέγχου τιμολόγησής σας`,
  _ = `Τελευταία ενημέρωση μετατροπών συναλλάγματος: %1$s`,
  _ = `Εργαλείο διερεύνησης μετατροπής τιμών`,
  _ = `Αυτό το εργαλείο δείχνει πώς λειτουργούν τρεις μέθοδοι μετατροπής τιμών και νομισμάτων:`,
  _ = `%1$s – Αυτή η μέθοδος λαμβάνει υπόψη πολλούς παράγοντες για κάθε νόμισμα, όπως την τοπική αγοραστική δύναμη, το αναμενόμενο κόστος συγκρίσιμων αγαθών ψυχαγωγίας και τη συναλλαγματική ισοτιμία.`,
  _ = `%1$s – Αυτή η μέθοδος χρησιμοποιεί δημόσια δεδομένα σχετικά με την αγοραστική δύναμη των πελατών σε μια δεδομένη χώρα ή/και περιοχή.`,
  _ = `%1$s – Αυτή η μέθοδος χρησιμοποιεί μια απλή συναλλαγματική ισοτιμία τη χρονική στιγμή που υποδεικνύεται.`,
  _ = `Βασικό νόμισμα`,
  _ = `Βασική τιμή`,
  _ = `Μέθοδος μετατροπής`,
  _ = `Νόμισμα`,
  _ = `Μετατροπή βάσει πολλών μεταβλητών`,
  _ = `Μετατροπή μόνο βάσει αγοραστικής δύναμης`,
  _ = `Μετατροπή μόνο βάσει συναλλαγματικής ισοτιμίας`,
  _ = `Τιμές βάσει περιοχής (αναφέρονται όλες σε USD)`,
  _ = `Περιοχή`,
  _ = `δοκιμή`,
  _ = `%1$s (%2$s) – Ερωτηματολόγιο περιεχομένου`,
  _ = `Ερωτηματολόγιο περιεχομένου`,
  _ = `%1$s (%2$s) – Ερωτηματολόγια περιεχομένου`,
  _ = `Ερωτηματολόγια περιεχομένου`,
  _ = `Δεν υπάρχει καμία εφαρμογή με αυτό το ID. Ελέγξτε τη διεύθυνση και δοκιμάστε ξανά.`,
  _ = `Η άδεια απορρίφθηκε`,
  _ = `Δεν έχετε συνδεθεί`,
  _ = `Πρόγραμμα`,
  _ = `Ακύρωση`,
  _ = `Άγνωστο σφάλμα – προσπαθήστε ξανά.`,
  _ = `Σε εξέλιξη`,
  _ = `Προεπεξεργασία σειρών: %1$s%`,
  _ = `Ακυρώθηκε`,
  _ = `Αναμονή για το AutoSnapshot`,
  _ = `Περίοδος %1$s/%2$s`,
  _ = `Εκπαίδευση %1$s`,
  _ = `Φόρτωση…`,
  _ = `Άγνωστo`,
  _ = `Σε εξέλιξη`,
  _ = `Σφάλμα`,
  _ = `Διακόπηκε νωρίς`,
  _ = `Περίοδος %1$s`,
  _ = `Ακρίβεια`,
  _ = `Εκπαίδευση:`,
  _ = `Επαλήθευση:`,
  _ = `Διάρκεια περιόδου: %1$s`,
  _ = `Τέλος εκπαίδευσης`,
  _ = `Συμπαγής πίνακας`,
  _ = `Ποσοστό δείγματος`,
  _ = `Σύνοψη`,
  _ = `Παρακάτω βρίσκεται ολόκληρη η λίστα των δοκιμών που πραγματοποιήθηκαν κατά τη διάρκεια αυτού του ελέγχου και των αποτελεσμάτων τους.`,
  _ = `Παρακάτω θα βρείτε μια σύνοψη των επιμέρους δοκιμών και των επακόλουθων αξιολογήσεων συμβατότητας.`,
  _ = `Τα αποτελέσματα δοκιμών που δίνουν σε αυτόν τον τίτλο την αξιολόγηση «Υποστηρίζεται» σημειώνονται παρακάτω.`,
  _ = `Ιδιότητα`,
  _ = `Τιμή`,
  _ = `Περιγραφή`,
  _ = `Εδώ είναι μία προεπισκόπηση του πώς θα εμφανίζεται αυτό στο Κατάστημα σε παίκτες που βλέπουν το παιχνίδι σας. Η παρουσίαση του Καταστήματος μπορεί να αλλάξει στο μέλλον.`,
  _ = `Παρελθοντικές αναφορές`,
  _ = `Αποτελέσματα δοκιμών`,
  _ = `Αποτέλεσμα`,
  _ = `Δοκιμή`,
  _ = `Σχόλια`,
  _ = `Αποτέλεσμα αξιολόγησης`,
  _ = `Επιτυχία`,
  _ = `Αποτυχία`,
  _ = `Αποτυχία`,
  _ = `---`,
  _ = `Αυτή είναι μία παρελθοντική αναφορά από %1$s`,
  _ = `Προβάλλεται η τρέχουσα δημοσιευμένη αναφορά`,
  _ = `Δημοσιεύτηκε: %1$s`,
  _ = `Αναφέρθηκε: %1$s`,
  _ = `Προβολή τεκμηρίωσης`,
  _ = `Δημοσίευση αποτελεσμάτων`,
  _ = `Δημοσίευση αποτελεσμάτων συμβατότητας;`,
  _ = `Θέλετε σίγουρα να δημοσιεύσετε αυτά τα αποτελέσματα; Τα αποτελέσματα θα είναι άμεσα ορατά στο Κατάστημα Steam.`,
  _ = `Άγνωστο σφάλμα – Δοκιμάστε ξανά`,
  _ = `Αίτημα δοκιμής`,
  _ = `Το αίτημα είναι ανοικτό`,
  _ = `Το αίτημα έχει κλείσει`,
  _ = `Προβολή λεπτομερειών αιτήματος`,
  _ = `Συζητήστε αυτήν την αναφορά με την ομάδα δοκιμών`,
  _ = `Εισαγάγετε ερωτήσεις ή σχόλια εδώ`,
  _ = `Περιγράψτε τις αλλαγές στη νέα σας δομή εδώ`,
  _ = `Εάν η δομή του παιχνιδιού σας στο Steam έχει ενημερωθεί για να διευθετηθούν τα προβλήματα που αναφέρονται παραπάνω, επιλέξτε έναν κλάδο και κάντε εκ νέου υποβολή για έλεγχο.`,
  _ = `Επιλέξτε έναν κλάδο και κάντε υποβολή για επανέλεγχο συμβατότητας Steam Deck που θα περιλαμβάνει δοκιμές για το Steam Machine.`,
  _ = `Υποβολή για επανέλεγχο`,
  _ = `Εάν πραγματοποιήσατε αλλαγές στη δομή του παιχνιδιού σας μετά τον τελευταίο έλεγχο, μπορείτε να ζητήσετε νέο έλεγχο συμβατότητας.`,
  _ = `Περιγράψτε τον λόγο για το αίτημα επανελέγχου σας παρακάτω. Οι συνήθεις λόγοι για επανέλεγχο περιλαμβάνουν:`,
  _ = `Πραγματοποιήσατε αλλαγές στη δομή σας για να διευθετήσετε προβλήματα αποτυχημένων δοκιμών από έναν προηγούμενο έλεγχο συμβατότητας. Περιγράψτε τα συγκεκριμένα προβλήματα που πιστεύετε ότι έχουν επιλυθεί.`,
  _ = `Έχετε κυκλοφορήσει ή θα κυκλοφορήσετε μια νέα έκδοση του παιχνιδιού σας και θέλετε να ενημερωθεί η αναφορά.`,
  _ = `Αίτηση για εκ νέου δοκιμή, χρησιμοποιώντας τον κλάδο «%1$s». Η δομή του παιχνιδιού στο Steam ενημερώθηκε για να διευθετηθούν τα προβλήματα που αναφέρθηκαν.`,
  _ = `Ιστορικό δοκιμών`,
  _ = `Προβολή στο Κατάστημα`,
  _ = `Συμβατότητα υλισμικού: %1$s (%2$s)`,
  _ = `Δημοσιευμένη`,
  _ = `Μη δημοσιευμένη`,
  _ = `Ιστορικό`,
  _ = `Προτεινόμενος χρόνος εκτέλεσης`,
  _ = `Αυτή είναι η έκδοση του παιχνιδιού σας (περιεχόμενο/εκτελέσιμα) που θα παραδοθεί και θα εκτελείται από τους πελάτες, από προεπιλογή, στο Steam Deck.`,
  _ = `Αναμενόμενη μορφή εισόδου`,
  _ = `Απαιτεί h264`,
  _ = `Δοκιμάστηκε η έκδοση Proton`,
  _ = `ID δομής δοκιμής`,
  _ = `Αποσφαλμάτωση RPO`,
  _ = `Αποσφαλμάτωση FDM`,
  _ = `Ενεργοποίηση TSO`,
  _ = `Το παιχνίδι σας έχει την αξιολόγηση «Άγνωστο» σε %1$s επειδή δεν έχουν ολοκληρωθεί οι δοκιμές %1$s.`,
  _ = `Το παιχνίδι σας δεν υποστηρίζεται σε %1$s αυτήν τη στιγμή`,
  _ = `Το παιχνίδι σας δεν υποστηρίζεται πλήρως σε %1$s λόγω προβλημάτων με το Proton ή με το ίδιο το %1$s. Λάβαμε υπόψη αυτά τα προβλήματα προκειμένου να τα επιλύσουμε. Εν τω μεταξύ, το παιχνίδι σας δεν θα εκκινεί ή δεν θα εκτελείται σωστά σε %1$s.`,
  _ = `Το παιχνίδι σας «Υποστηρίζεται» σε %1$s`,
  _ = `Το παιχνίδι σας υποστηρίζεται στο %1$s, αλλά απαιτείται κάποια επιπλέον προσπάθεια από τους πελάτες, για να αλληλεπιδράσουν με αυτό ή για να το διαμορφώσουν. Μπορείτε να διορθώσετε τα προβλήματα που περιγράφονται παρακάτω και να το υποβάλετε ξανά για έλεγχο συμβατότητας.`,
  _ = `Το παιχνίδι σας είναι «Επαληθευμένο για %1$s»!`,
  _ = `Συγχαρητήρια! Το παιχνίδι σας είναι υπέροχη εμπειρία σε %1$s και θα παρουσιαστεί ως τέτοια εντός του Καταστήματος Steam και εντός των Συλλογών Steam των παικτών σε %1$s.`,
  _ = `Θέλετε να μοιραστείτε αυτό το ορόσημο με τους φαν σας; Μπορείτε να χρησιμοποιήσετε αυτόν τον σύνδεσμο προς μια κομψή σελίδα υποδοχής: %1$s`,
  _ = `Δεν έχει γίνει δοκιμή του παιχνιδιού σας σε Steam Machine`,
  _ = `Δεν έχει γίνει δοκιμή του παιχνιδιού σας σε Steam Frame`,
  _ = `Αυτό κάνει την αξιολόγηση σας να είναι «Υποστηρίζεται»`,
  _ = `Αυτό κάνει την αξιολόγηση σας να είναι «Δεν Υποστηρίζεται»`,
  _ = `Αυτό εμφανίζεται ως πληροφοριακό μήνυμα στους πελάτες`,
  _ = `Μη έγκυρο`,
  _ = `Έναρξη προγράμματος εκκίνησης`,
  _ = `Πρόγραμμα εκκίνησης`,
  _ = `Χειριστήριο προγράμματος εκκίνησης`,
  _ = `Κείμενο προγράμματος εκκίνησης`,
  _ = `Πληκτρολόγιο προγράμματος εκκίνησης`,
  _ = `Προειδοποιήσεις συσκευής`,
  _ = `Εκκίνηση παιχνιδιού`,
  _ = `Ένας παίκτης`,
  _ = `Τοπικό πολλών παικτών`,
  _ = `Διαδικτυακό πολλών παικτών`,
  _ = `Anti-Cheat`,
  _ = `Anti-Cheat`,
  _ = `Anti-Cheat / Πολλών παικτών`,
  _ = `Προεπιλεγμένη διαμόρφωση χειριστηρίου`,
  _ = `Πληκτρολόγιο`,
  _ = `Γλυφές χειριστηρίου`,
  _ = `Επιδόσεις προεπιλεγμένης διαμόρφωσης`,
  _ = `Οθόνη`,
  _ = `Έξοδος βίντεο`,
  _ = `Εγγενής ανάλυση`,
  _ = `Αναγνωσιμότητα κειμένου`,
  _ = `Ήχος`,
  _ = `Μενού`,
  _ = `Αποθήκευση Cloud μεταξύ πλατφορμών`,
  _ = `Παιχνίδι ενός παίκτη εκτός σύνδεσης`,
  _ = `Εξωτερικό χειριστήριο (Κύριος παίκτης)`,
  _ = `Εξωτερικό χειριστήριο (Τοπικό πολλών παικτών)`,
  _ = `Εγκατάσταση για πρώτη φορά`,
  _ = `Εγκατάσταση χειριστηρίου για πρώτη φορά`,
  _ = `Εγκατάσταση για πρώτη φορά – Εκτός σύνδεσης`,
  _ = `Λειτουργικότητα παιχνιδιού`,
  _ = `VR`,
  _ = `Σημείωση`,
  _ = `Απρόσκοπτος τερματισμός`,
  _ = `Απρόσκοπτος τερματισμός (Πρόγραμμα εκκίνησης)`,
  _ = `Ταυτόχρονη είσοδος χειριστηρίου/ποντικιού`,
  _ = `Βοηθητική λειτουργικότητα: Επεξεργαστής χαρτών`,
  _ = `Υποστηρίζεται περιορισμός καρέ`,
  _ = `Εστίαση πολλαπλών παραθύρων (Αυτόματη)`,
  _ = `Εστίαση πολλαπλών παραθύρων (Μη αυτόματη)`,
  _ = `Λογισμικό`,
  _ = `Ταυτόχρονη είσοδος χειριστηρίου/ποντικιού`,
  _ = `Είσοδος κειμένου`,
  _ = `Είσοδος ήχου`,
  _ = `Επαναφορά από αναστολή λειτουργίας`,
  _ = `Έγινε κλιμάκωση της εξόδου οθόνης`,
  _ = `Εξωτερικοί σύνδεσμοι/περιεχόμενο`,
  _ = `Αποσύρθηκε`,
  _ = `Η γραμματοσειρά υποστηρίζει όλους τους χαρακτήρες`,
  _ = `Οι ρυθμίσεις προβολής αποθηκεύονται ανά συσκευή, όχι στο Cloud`,
  _ = `Προεπιλεγμένη διαμόρφωση χειριστηρίου`,
  _ = `Το προεπιλεγμένο χειριστήριο ενεργοποιήθηκε`,
  _ = `Οι αποθηκεύσεις σε Cloud είναι ενεργές από προεπιλογή`,
  _ = `Περιφερειακά (πληκτρολόγιο)`,
  _ = `Περιφερειακά (κάμερα υπολογιστή)`,
  _ = `Περιφερειακά (κιθάρα USB)`,
  _ = `Υποστήριξη HDR`,
  _ = `Υποστήριξη λειτουργικού συστήματος`,
  _ = `Steam Machine – Επιδόσεις προεπιλεγμένης διαμόρφωσης`,
  _ = `Steam Machine – Επιδόσεις μετάδοσης VR`,
  _ = `Steam Machine – Υποστήριξη μετάδοσης VR`,
  _ = `Steam Machine – Προειδοποιήσεις συσκευής`,
  _ = `Steam Machine – Οθόνη`,
  _ = `Steam Machine – Ήχος`,
  _ = `Steam Machine`,
  _ = `SteamOS`,
  _ = `Steam Deck`,
  _ = `Steam Frame (Αυτόνομο παιχνίδι)`,
  _ = `Ζητήστε μια δοκιμή Steam Deck, από την οποία θα εκκινήσουν δοκιμές για αξιολόγηση συμβατότητας με το %1$s.`,
  _ = `Καλώς ορίσατε! Εδώ μπορείτε να υποβάλετε τον τίτλο σας για έλεγχο συμβατότητας με το Steam Frame (Αυτόνομο παιχνίδι).`,
  _ = `Λίστα αυτοελέγχου συμβατότητας Steam Frame (Αυτόνομο παιχνίδι)`,
  _ = `Παρακάτω παραθέτουμε μερικά από τα πιο σημαντικά κριτήρια που εξετάζουμε κατά τον έλεγχο ενός τίτλου για συμβατότητα με το Steam Frame. Συμπληρώστε τη φόρμα παρακάτω, αναφέροντας ποια δομή/κλάδο του παιχνιδιού σας θα θέλατε να δοκιμάσουμε και θα προσθέσουμε το παιχνίδι σας στην ουρά ελέγχου. Όταν ολοκληρωθεί ο έλεγχος, θα λάβετε email ειδοποίησης με μια σύνοψη και η σελίδα αυτή θα ενημερωθεί με τα αναλυτικά αποτελέσματα των δοκιμών.`,
  _ = `Για περισσότερες πληροφορίες σχετικά με τη διαδικασία δοκιμής, δείτε εδώ: %1$s`,
  _ = `Διαδικασία ελέγχου συμβατότητας Steam Frame (Αυτόνομο παιχνίδι)`,
  _ = `Αυτά είναι μερικά από τα πιο σημαντικά στοιχεία που θα ελέγξουμε για να δώσουμε αξιολόγηση συμβατότητας στο παιχνίδι σας. Προκειμένου να ξεκινήσετε τη διαδικασία ελέγχου συμβατότητας Steam Frame, απαντήστε τα ακόλουθα ερωτήματα όσο καλύτερα μπορείτε.`,
  _ = `Τα αιτήματα δοκιμής δεν είναι διαθέσιμα πριν κυκλοφορήσει το παιχνίδι.`,
  _ = `Θα είναι το παιχνίδι σας μία υπέροχη εμπειρία για τους παίκτες στο Steam Deck; Έχουμε μία διαδικασία ελέγχου κατά την οποία η ομάδα μας θα παίξει και θα δοκιμάσει το παιχνίδι σας. Εάν είναι μια ομαλή εμπειρία για τους παίκτες στο Steam Deck, θα αποκτήσει την ετικέτα «Επαληθευμένο για Steam Deck».`,
  _ = `Καλώς ορίσατε! Εδώ μπορείτε να υποβάλετε τον τίτλο σας για έλεγχο συμβατότητας με το Steam Deck.`,
  _ = `Παρακάτω παραθέτουμε μερικά από τα πιο σημαντικά κριτήρια που εξετάζουμε κατά τον έλεγχο ενός τίτλου για συμβατότητα με το Steam Deck. Συμπληρώστε τη φόρμα παρακάτω, αναφέροντας ποια δομή/κλάδο του παιχνιδιού σας θα θέλατε να δοκιμάσουμε και θα προσθέσουμε το παιχνίδι σας στην ουρά ελέγχου. Όταν ολοκληρωθεί ο έλεγχος, θα λάβετε email ειδοποίησης με μια σύνοψη και η σελίδα αυτή θα ενημερωθεί με τα αναλυτικά αποτελέσματα των δοκιμών.`,
  _ = `Μπορείτε να υποβάλετε τον τίτλο σας, ακόμα και αν δεν πληροί όλα τα κριτήρια για να λάβει την αξιολόγηση «Επαληθευμένο». Χρησιμοποιούμε αυτά τα στοιχεία αυτοδοκιμής για να δώσουμε προτεραιότητα σε τίτλους για έλεγχο, καθώς επίσης και για να σας κοινοποιήσουμε τυχόν προβλήματα συμβατότητας του παιχνιδιού σας όσο πιο σαφώς γίνεται.`,
  _ = `Για περισσότερες πληροφορίες σχετικά με τη διαδικασία δοκιμής, δείτε εδώ: %1$s και %2$s.`,
  _ = `Διαδικασία ελέγχου συμβατότητας Steam Deck`,
  _ = `επιπλέον προτάσεις για το Steam Deck`,
  _ = `Λίστα αυτοελέγχου συμβατότητας Steam Deck`,
  _ = `Αυτά είναι μερικά από τα πιο σημαντικά στοιχεία που θα ελέγξουμε για να δώσουμε αξιολόγηση συμβατότητας στο παιχνίδι σας. Προκειμένου να ξεκινήσετε τη διαδικασία ελέγχου συμβατότητας Steam Deck, απαντήστε τα ακόλουθα ερωτήματα όσο καλύτερα μπορείτε.`,
  _ = `Αυτήν τη στιγμή, η διαδικασία ελέγχου συμβατότητας Steam Deck είναι διαθέσιμη μόνο για παιχνίδια. Δεν υπάρχει διαδικασία ελέγχου συμβατότητας για άλλους τύπους εφαρμογών, π.χ. για DLC, εργαλεία ή μουσικές υποκρούσεις, εκτός από εξαιρετικές περιπτώσεις.`,
  _ = `Υποστήριξη χειριστηρίων`,
  _ = `Εισαγωγή κειμένου`,
  _ = `Οθόνη`,
  _ = `Λειτουργικότητα`,
  _ = `Steam Cloud`,
  _ = `Πρόγραμμα εκκίνησης`,
  _ = `Κλάδος`,
  _ = `Κάντε δοκιμές χρησιμοποιώντας αυτόν τον κλάδο`,
  _ = `Επισήμανση ως έτοιμη για έλεγχο…`,
  _ = `Αυτό θα επισημάνει τη δομή σας ως έτοιμη για έλεγχο συμβατότητας με το Steam Deck. Θα ειδοποιηθείτε για τα αποτελέσματα μέσω e-mail σε μερικές ημέρες.`,
  _ = `Μπορείτε να αφήσετε σημειώσεις παρακάτω για να βοηθήσετε να επισπευσθεί η δοκιμή ή για να παράσχετε διαπιστευτήρια λογαριασμού δοκιμής σε διακομιστές σύνδεσης τρίτων.`,
  _ = `Εισαγάγετε σημειώσεις εδώ`,
  _ = `Αίτημα βοήθειας για αυτόν τον έλεγχο`,
  _ = `Για περισσότερες λεπτομέρειες, δείτε αυτήν την αναφορά δοκιμών στην ιστοσελίδα βοήθειας`,
  _ = `Δημιουργήστε ένα δελτίο υποστήριξης για τον έλεγχο συμβατότητας του Steam Deck`,
  _ = `Όταν ανοίγετε ένα δελτίο υποστήριξης, συμπεριλάβετε ερωτήσεις ή σχόλια για την ομάδα δοκιμών.`,
  _ = `Αν έχετε συγκεκριμένες ερωτήσεις σχετικά με τη διαδικασία ελέγχου συμβατότητας ή με τα αποτελέσματα για το παιχνίδι σας, εισαγάγετέ τες παρακάτω.`,
  _ = `Λάβετε υπόψη ότι εάν επιθυμείτε επανέλεγχο του τίτλου σας, θα είναι πιο αποτελεσματικό να χρησιμοποιήσετε το κουμπί «ΥΠΟΒΟΛΗ ΓΙΑ ΕΠΑΝΕΛΕΓΧΟ» παρακάτω, από το να ρωτήσετε εδώ.`,
  _ = `Έχω ερώτηση ή σχόλιο σχετικά με την αναφορά συμβατότητας του Steam Deck: `,
  _ = `Ναι, το παιχνίδι μου έχει πλήρη υποστήριξη χειριστηρίου: Όλη η λειτουργικότητα είναι προσβάσιμη μέσω ενός χειριστηρίου που χρησιμοποιεί την προεπιλεγμένη διαμόρφωση`,
  _ = `Ναι, το παιχνίδι μου εμφανίζει υποδείξεις Steam Deck ή χειριστηρίου Xbox εντός παιχνιδιού, όταν αναφέρεται σε πατήματα κουμπιών σε ένα χειριστήριο`,
  _ = `Είτε το παιχνίδι μου δεν απαιτεί καθόλου είσοδο κειμένου είτε το παιχνίδι μου καλεί τα κατάλληλα Steam API εισαγωγής κειμένου όταν είναι απαραίτητο`,
  _ = `Το παιχνίδι μου δεν απαιτεί είσοδο κειμένου`,
  _ = `Το παιχνίδι μου καλεί τα κατάλληλα Steam API πληκτρολογίου / εισαγωγής κειμένου όταν χρειάζεται εισαγωγή κειμένου από χρήστες`,
  _ = `Το παιχνίδι μου δεν χρησιμοποιεί Steam API όταν χρειάζεται εισαγωγή κειμένου από χρήστες`,
  _ = `Το παιχνίδι μου δεν έχει αρχεία αποθήκευσης παιχνιδιού`,
  _ = `Το παιχνίδι μου έχει αρχεία αποθήκευσης παιχνιδιού, αλλά δεν χρησιμοποιεί Steam Cloud για αυτά`,
  _ = `Το παιχνίδι μου χρησιμοποιεί Steam Cloud για αποθήκευση παιχνιδιών. Υπάρχει μόνο μία δομή για Windows`,
  _ = `Το παιχνίδι μου χρησιμοποιεί Steam Cloud για αποθήκευση παιχνιδιών και υποστηρίζει αρχεία αποθήκευσης μεταξύ πλατφορμών (δηλαδή, Windows/Linux)`,
  _ = `Το παιχνίδι μου χρησιμοποιεί Steam Cloud για αποθήκευση παιχνιδιών, αλλά δεν υποστηρίζει αρχεία αποθήκευσης μεταξύ πλατφορμών (δηλαδή, Windows/Linux)`,
  _ = `Ναι, το παιχνίδι μου μπορεί να εκτελεστεί σε ανάλυση 1280 × 800 (προτιμώμενη) ή 1280 × 720.`,
  _ = `Ναι, ο μικρότερος χαρακτήρας γραμματοσειράς στην οθόνη εντός του παιχνιδιού μου δεν είναι ποτέ κάτω από 9 πίξελ σε ύψος, σε ανάλυση 1280 × 800.`,
  _ = `Είτε το παιχνίδι μου δεν έχει πρόγραμμα εκκίνησης είτε στο πρόγραμμα εκκίνησης του παιχνιδιού μου μπορεί να γίνει πλοήγηση πλήρως μέσω ενός χειριστηρίου.`,
  _ = `Είτε το παιχνίδι μου υποστηρίζει Steam Cloud για αποθήκευση παιχνιδιών είτε το παιχνίδι μου δεν έχει αρχεία αποθήκευσης.`,
  _ = `Είτε το παιχνίδι μου υποστηρίζει αποθήκευση παιχνιδιών μεταξύ πλατφορμών είτε το παιχνίδι μου εκτελείται μόνο σε μία πλατφόρμα (Linux/Windows).`,
  _ = `Θα ελέγξουμε τη δομή των Windows σας που εκτελείται υπό Proton, εκτός αν αναφερθεί κάτι διαφορετικό.`,
  _ = `Αν είναι διαθέσιμη, δοκιμάστε τη δομή μου για Linux αντί για τη δομή μου για Windows`,
  _ = `Το παιχνίδι μου δεν χρησιμοποιεί κάποιο πρόγραμμα εκκίνησης ούτε κάποιο εξωτερικό εργαλείο διαμόρφωσης`,
  _ = `Το παιχνίδι μου χρησιμοποιεί ένα πρόγραμμα εκκίνησης και αυτό το πρόγραμμα εκκίνησης έχει πλήρη υποστήριξη χειριστηρίου`,
  _ = `Το παιχνίδι μου χρησιμοποιεί ένα πρόγραμμα εκκίνησης και αυτό το πρόγραμμα εκκίνησης δεν είναι πλήρως λειτουργικό αν ο χρήστης έχει μόνο χειριστήριο και όχι πληκτρολόγιο ή ποντίκι`,
  _ = `(Αν και οι αποθηκεύσεις μεταξύ πλατφορμών δεν απαιτούνται για την αξιολόγηση «Επαληθευμένο», είναι χρήσιμες για πελάτες που μπορεί μερικές φορές να παίζουν σε έναν υπολογιστή Windows και μερικές φορές σε ένα Steam Deck που εκτελεί μια εγγενή δομή Linux. Ανατρέξτε στην %1$s.)`,
  _ = `τεκμηρίωση`,
  _ = `(Η οθόνη του Steam Deck είναι πολύ μικρότερη από τις περισσότερες οθόνες υπολογιστή. Αν το παιχνίδι σας έχει μικρό κείμενο, μπορεί να είναι δύσκολο ή και αδύνατο να το διαβάσουν οι πελάτες στην οθόνη του Steam Deck, ακόμα και αν το κείμενο είναι ευανάγνωστο σε μια κλασική οθόνη.)`,
  _ = `(Τα περισσότερα Steam Deck δεν έχουν συνδεδεμένο πληκτρολόγιο, οπότε οι πελάτες βασίζονται σε πληκτρολόγια οθόνης για εισαγωγή κειμένου και το Steam παρέχει API για να κάνει εύκολη τη χρήση των ενσωματωμένων πληκτρολογίων οθόνης. Αν οι πελάτες χρειάζεται να ανοίξουν με μη αυτόματο τρόπο το πληκτρολόγιο, το παιχνίδι σας δεν θα μπορεί να λάβει την αξιολόγηση «Επαληθευμένο». Δείτε τις %1$s.)`,
  _ = `προτάσεις εισόδου`,
  _ = `(Αν το παιχνίδι σας χρησιμοποιεί ένα πρόγραμμα εκκίνησης, το πρόγραμμα εκκίνησης έχει τις ίδιες απαιτήσεις για την αξιολόγηση «Επαληθευμένο» όπως το παιχνίδι: Πρέπει να μπορεί να χρησιμοποιείται πλήρως μόνο με τα ενσωματωμένα στοιχεία ελέγχου του Steam Deck, να είναι ευανάγνωστο κτλ. Αν το πρόγραμμα εκκίνησης δεν πληροί αυτές τις απαιτήσεις, το παιχνίδι σας δεν θα μπορεί να λάβει την αξιολόγηση «Επαληθευμένο», ακόμα και αν από μόνο του θα τη λάμβανε. Δείτε τις %1$s.)`,
  _ = `προτάσεις προγράμματος εκκίνησης`,
  _ = `(Ένα μεγάλο μέρος των πελατών του Steam Deck είναι επίσης και πελάτες επιτραπέζιου υπολογιστή. Οι αποθηκεύσεις cloud δεν απαιτούνται για την αξιολόγηση «Επαληθευμένο», αλλά είναι χρήσιμες για τους πελάτες: η προσθήκη υποστήριξης %1$s για αποθήκευση παιχνιδιών θα επιτρέψει στους πελάτες να αποθηκεύουν το παιχνίδι τους σε έναν επιτραπέζιο υπολογιστή και να το συνεχίσουν στο Steam Deck ή αντίστροφα.)`,
  _ = `Steam Cloud`,
  _ = `(Σημείωση: Απαιτείται πλήρης υποστήριξη χειριστηρίου για την αξιολόγηση «Επαληθευμένο».)`,
  _ = `Το παιχνίδι σας προστέθηκε στην ουρά ελέγχου μας`,
  _ = `Θα ελέγξουμε το παιχνίδι σας σύντομα και θα σας ενημερώσουμε για τυχόν προβλήματα.`,
  _ = `Ολοκληρώστε τον έλεγχο της δομής σας στο Steam, πριν κάνετε υποβολή για έλεγχο συμβατότητας υλισμικού.`,
  _ = `Το παιχνίδι σας δεν υποστηρίζεται στο Steam Deck αυτήν τη στιγμή`,
  _ = `Το παιχνίδι σας δεν υποστηρίζεται πλήρως στο Steam Deck λόγω προβλημάτων με το Proton ή με το ίδιο το Steam Deck. Λάβαμε υπόψη αυτά τα προβλήματα προκειμένου να τα επιλύσουμε. Εν τω μεταξύ, το παιχνίδι σας δεν θα εκκινεί ή δεν θα εκτελείται σωστά στο Steam Deck.`,
  _ = `Το παιχνίδι σας «Υποστηρίζεται» στο Steam Deck`,
  _ = `Το παιχνίδι σας υποστηρίζεται στο Steam Deck, αλλά απαιτεί κάποια επιπλέον προσπάθεια από τους πελάτες για να αλληλεπιδράσουν με αυτό ή για να το διαμορφώσουν. Μπορείτε να διορθώσετε τα προβλήματα που περιγράφονται παρακάτω και να το υποβάλετε ξανά για έλεγχο συμβατότητας Steam Deck.`,
  _ = `Δομή`,
  _ = `Αν είναι διαθέσιμη, δοκιμάστε τη δομή μου για Android αντί για τη δομή μου για Windows`,
  _ = `Δοκιμή της δομής Windows`,
  _ = `Δοκιμή της δομής Linux`,
  _ = `Να δοκιμάσουμε την εμπειρία 2D ή την εμπειρία VR (αν είναι διαθέσιμη);`,
  _ = `2D`,
  _ = `VR`,
  _ = `Δεν ισχύει για τίτλους %1$s`,
  _ = `Επαληθευμένο, χωρίς χρήση της επιλογής «Εκκαθάριση κατάστασης αξιολόγησης επιδόσεων»`,
  _ = `Επαληθευμένο, χρησιμοποιώντας τουλάχιστον μία φορά την επιλογή «Εκκαθάριση κατάστασης αξιολόγησης επιδόσεων»`,
  _ = `Υποστηρίζεται, χωρίς χρήση της επιλογής «Εκκαθάριση κατάστασης αξιολόγησης επιδόσεων»`,
  _ = `Υποστηρίζεται, χρησιμοποιώντας τουλάχιστον μία φορά την επιλογή «Εκκαθάριση κατάστασης αξιολόγησης επιδόσεων»`,
  _ = `Δεν υποστηρίζεται`,
  _ = `Δεν είναι τίτλος VR (δεν ισχύει η αξιολόγηση)`,
  _ = `Επικάλυψη αξιολόγησης επιδόσεων`,
  _ = `Χρησιμοποιήστε την επικάλυψη αξιολόγησης επιδόσεων για να συμπληρώσετε την απάντηση παρακάτω. Ανατρέξτε στην %1$s για περισσότερες πληροφορίες.`,
  _ = `τεκμηρίωση επιδόσεων VR`,
  _ = `(Αν το παιχνίδι σας έχει μικρό κείμενο, μπορεί να είναι δύσκολο ή και αδύνατο να το διαβάσουν οι πελάτες στην οθόνη του Steam Frame, ακόμα και αν το κείμενο είναι ευανάγνωστο σε μια κλασική οθόνη.)`,
  _ = `(Τα περισσότερα Steam Frame δεν έχουν συνδεδεμένο πληκτρολόγιο, οπότε οι πελάτες βασίζονται σε πληκτρολόγια οθόνης για εισαγωγή κειμένου και το Steam παρέχει API για να κάνει εύκολη τη χρήση των ενσωματωμένων πληκτρολογίων οθόνης. Αν οι πελάτες χρειάζεται να ανοίξουν με μη αυτόματο τρόπο το πληκτρολόγιο, το παιχνίδι σας δεν θα μπορεί να λάβει την αξιολόγηση «Επαληθευμένο». Δείτε τη %1$s.)`,
  _ = `λίστα ελέγχου συμβατότητας Steam Frame`,
  _ = `(Αν το παιχνίδι σας χρησιμοποιεί ένα πρόγραμμα εκκίνησης, το πρόγραμμα εκκίνησης έχει τις ίδιες απαιτήσεις για την αξιολόγηση «Επαληθευμένο» όπως το παιχνίδι: Πρέπει να μπορεί να χρησιμοποιείται πλήρως μόνο με τα ενσωματωμένα στοιχεία ελέγχου του Steam Frame, να είναι ευανάγνωστο κτλ. Αν το πρόγραμμα εκκίνησης δεν πληροί αυτές τις απαιτήσεις, το παιχνίδι σας δεν θα μπορεί να λάβει την αξιολόγηση «Επαληθευμένο», ακόμα και αν από μόνο του θα τη λάμβανε. Δείτε τις %1$s.)`,
  _ = `(Ένα μεγάλο μέρος των πελατών του Steam Frame είναι επίσης και πελάτες επιτραπέζιου υπολογιστή. Οι αποθηκεύσεις cloud δεν απαιτούνται για την αξιολόγηση «Επαληθευμένο», αλλά είναι χρήσιμες για τους πελάτες: Η προσθήκη υποστήριξης %1$s για αποθήκευση παιχνιδιών θα επιτρέψει στους πελάτες να αποθηκεύουν το παιχνίδι τους σε έναν επιτραπέζιο υπολογιστή και να το συνεχίζουν στο Steam Frame ή αντίστροφα.)`,
  _ = `(Αν και οι αποθηκεύσεις μεταξύ πλατφορμών δεν απαιτούνται για την αξιολόγηση «Επαληθευμένο», είναι χρήσιμες για πελάτες που μπορεί μερικές φορές να παίζουν σε έναν υπολογιστή Windows και μερικές φορές σε ένα Steam Frame που εκτελεί μια εγγενή δομή Linux. Ανατρέξτε στην %1$s.)`,
  _ = `Ναι, το παιχνίδι μου εμφανίζει υποδείξεις Steam Frame ή χειριστηρίου Xbox εντός παιχνιδιού, όταν αναφέρεται σε πατήματα κουμπιών σε ένα χειριστήριο`,
  _ = `Αν για το αποτέλεσμα της παραπάνω αξιολόγησης επιδόσεων χρειάστηκε να χρησιμοποιήσετε τουλάχιστον μία φορά την επιλογή «Εκκαθάριση κατάστασης αξιολόγησης επιδόσεων», επιλέξτε έναν ή περισσότερους λόγους παρακάτω.`,
  _ = `Μειωμένες επιδόσεις κατά την εκκίνηση του παιχνιδιού`,
  _ = `Μειωμένες επιδόσεις κατά τη διάρκεια των οθονών φόρτωσης`,
  _ = `Άλλο (παράσχετε διευκρίνηση)`,
  _ = `Κάνετε αίτημα για έλεγχο Android, αλλά %1$s δεν διαθέτει κανένα ντεπό Android.`,
  _ = `το πακέτο «Developer Comp» σας`,
  _ = `dummy`,
  _ = {
    Valve_Confidential: _,
    Valve_Confidential_Description: _,
    Footer_Description: _,
    Footer_Sitemap_ContactSupport: _,
    PricingExplorer_LoadError: _,
    PricingExplorer_About_Title: _,
    PricingExplorer_About_Desc1: _,
    PricingExplorer_About_Desc2: _,
    PricingExplorer_About_Link1: _,
    PricingExplorer_About_LinkName1: _,
    PricingExplorer_About_Link2: _,
    PricingExplorer_About_LinkName2: _,
    PricingExplorer_About_Dash: _,
    PricingExplorer_About_LastUpdated: _,
    PricingExplorer_Explore_title: _,
    PricingExplorer_Explore_desc1: _,
    PricingExplorer_Explore_line1: _,
    PricingExplorer_Explore_line2: _,
    PricingExplorer_Explore_line3: _,
    PricingExplorer_Base: _,
    PricingExplorer_BasePrice: _,
    PricingExplorer_TableHeader: _,
    PricingExplorer_Column1: _,
    PricingExplorer_Column2: _,
    PricingExplorer_Column3: _,
    PricingExplorer_Column4: _,
    PricingExplorer_Regions_TableHeader: _,
    PricingExplorer_Regions_Column1: _,
    Pricing_Dummy: _,
    ContentSurvey_Title: _,
    ContentSurvey_Title_Default: _,
    ContentSurvey_History_Title: _,
    ContentSurvey_History_Title_Default: _,
    ContentSurvey_InvalidApp: _,
    PartnerSite_PermissionDenied: _,
    PartnerSite_NotLoggedIn: _,
    SteamLearn_Project_Schedule: _,
    SteamLearn_Project_Edit_Cancel: _,
    SteamLearn_Project_Create_Error: _,
    SteamLearn_Event_InProgress: _,
    SteamLearn_FetchStatus_Percent: _,
    SteamLearn_FetchStatus_Canceled: _,
    SteamLearn_TrainStatus_WaitingOnASS: _,
    SteamLearn_TrainStatus_InProgress: _,
    SteamLearn_Status_Train_TrainOption: _,
    SteamLearn_Status_Train_Status_Loading: _,
    SteamLearn_Status_Train_Status_Unknown: _,
    SteamLearn_Status_Train_Status_InProgress: _,
    SteamLearn_Status_Train_Status_Error: _,
    SteamLearn_Status_Train_Status_StoppedEarly: _,
    SteamLearn_Status_Train_EpochOption: _,
    SteamLearn_Status_Train_Axis_Accuracy: _,
    SteamLearn_Status_Train_BatchCurrent_Train: _,
    SteamLearn_Status_Train_BatchCurrent_Validate: _,
    SteamLearn_Status_Train_BatchCurrent_EpochDuration: _,
    SteamLearn_Status_Train_EndEarly: _,
    SteamLearn_Config_DataSource_Input_Preprocess_CompactTable: _,
    SteamLearn_SnapshotFilter_SamplePercent: _,
    SteamDeck_BuildReview_Status_Raw_Title: _,
    SteamDeck_BuildReview_Status_Raw_Description: _,
    SteamDeck_BuildReview_Status_TestProperties_Description: _,
    SteamDeck_BuildReview_Status_TestProperties_Playable: _,
    SteamDeck_BuildReview_Status_TestProperty_Name: _,
    SteamDeck_BuildReview_Status_TestProperty_Value: _,
    SteamDeck_BuildReview_Status_TestProperty_Desc: _,
    SteamDeck_BuildReview_Status_Description: _,
    SteamDeck_BuildReview_Header_History: _,
    SteamDeck_BuildReview_Header_Results: _,
    SteamDeck_BuildReview_Status_Raw_Result: _,
    SteamDeck_BuildReview_Status_Raw_Test: _,
    SteamDeck_BuildReview_Status_Raw_Comment: _,
    SteamDeck_BuildReview_Status_Raw_Impact: _,
    SteamDeck_BuildReview_Status_Pass: _,
    SteamDeck_BuildReview_Status_Fail: _,
    SteamDeck_BuildReview_Status_FailMinor: _,
    SteamDeck_BuildReview_Status_NotApplicable: `---`,
    SteamDeck_BuildReview_Viewing_Historical: _,
    SteamDeck_BuildReview_Viewing_Published: _,
    SteamDeck_BuildReview_PublishedOn: _,
    SteamDeck_BuildReview_ReportedOn: _,
    SteamDeck_BuildReview_Documentation: _,
    SteamDeck_BuildReview_PublishResults: _,
    SteamDeck_BuildReview_PublishDialog_Title: _,
    SteamDeck_BuildReview_PublishDialog_Body: _,
    SteamDeck_BuildReview_UnknownError: _,
    SteamDeck_BuildReview_Help_Request_Title: _,
    SteamDeck_BuildReview_RequestStatusActive: _,
    SteamDeck_BuildReview_RequestStatusClosed: _,
    SteamDeck_BuildReview_InReview_ViewTicket: _,
    SteamDeck_BuildReview_Create_HelpRequest: _,
    SteamDeck_BuildReview_Create_HelpRequest_NotesDefault: _,
    SteamDeck_BuildReview_Create_HelpRequest_NotesDefault_Rereview: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label_Machine: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Button: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_1: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2a: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2b: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Ticket_Content: _,
    SteamDeck_BuildReview_CompatibilityTests: _,
    SteamDeck_BuildReview_Status_Title: _,
    SteamDeck_HardwareCompatibility_Title: _,
    SteamDeck_AppLanding_Published: _,
    SteamDeck_AppLanding_Unpublished: _,
    SteamDeck_AppLanding_History: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RecommendedRuntime: _,
    SteamDeckVerified_TestDisplayName_TestPropertyDescription_RecommendedRuntime:
      _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_ExpectedInput: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RequiresH264: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TestedProtonVersion: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TestedBuildID: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RPODebug: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_FDMDebug: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TSOEnable: _,
    SteamHardware_BuildReview_Unknown_Title: _,
    SteamHardware_BuildReview_Unsupported_Title: _,
    SteamHardware_BuildReview_Unsupported_Description: _,
    SteamHardware_BuildReview_Playable_Title: _,
    SteamHardware_BuildReview_Playable_Description: _,
    SteamHardware_BuildReview_Verified_Title: _,
    SteamHardware_BuildReview_Verified_Description: _,
    SteamHardware_BuildReview_Verified_Share: _,
    SteamHardware_Machine_Unknown: _,
    SteamHardware_Frame_Unknown: _,
    SteamHardware_RatingImpact_Playable: _,
    SteamHardware_RatingImpact_Unsupported: _,
    SteamHardware_RatingImpact_Informational: _,
    SteamDeckVerified_TestDisplayName_0: _,
    SteamDeckVerified_TestDisplayName_1: _,
    SteamDeckVerified_TestDisplayName_2: _,
    SteamDeckVerified_TestDisplayName_3: _,
    SteamDeckVerified_TestDisplayName_4: _,
    SteamDeckVerified_TestDisplayName_5: _,
    SteamDeckVerified_TestDisplayName_6: _,
    SteamDeckVerified_TestDisplayName_7: _,
    SteamDeckVerified_TestDisplayName_8: _,
    SteamDeckVerified_TestDisplayName_9: _,
    SteamDeckVerified_TestDisplayName_10: _,
    SteamDeckVerified_TestDisplayName_11: _,
    SteamDeckVerified_TestDisplayName_12: _,
    SteamDeckVerified_TestDisplayName_13: _,
    SteamDeckVerified_TestDisplayName_14: _,
    SteamDeckVerified_TestDisplayName_15: _,
    SteamDeckVerified_TestDisplayName_16: _,
    SteamDeckVerified_TestDisplayName_17: _,
    SteamDeckVerified_TestDisplayName_18: _,
    SteamDeckVerified_TestDisplayName_19: _,
    SteamDeckVerified_TestDisplayName_20: _,
    SteamDeckVerified_TestDisplayName_21: _,
    SteamDeckVerified_TestDisplayName_22: _,
    SteamDeckVerified_TestDisplayName_23: _,
    SteamDeckVerified_TestDisplayName_24: _,
    SteamDeckVerified_TestDisplayName_25: _,
    SteamDeckVerified_TestDisplayName_26: _,
    SteamDeckVerified_TestDisplayName_27: _,
    SteamDeckVerified_TestDisplayName_29: _,
    SteamDeckVerified_TestDisplayName_30: _,
    SteamDeckVerified_TestDisplayName_31: _,
    SteamDeckVerified_TestDisplayName_32: _,
    SteamDeckVerified_TestDisplayName_33: `VR`,
    SteamDeckVerified_TestDisplayName_34: _,
    SteamDeckVerified_TestDisplayName_35: _,
    SteamDeckVerified_TestDisplayName_36: _,
    SteamDeckVerified_TestDisplayName_37: _,
    SteamDeckVerified_TestDisplayName_38: _,
    SteamDeckVerified_TestDisplayName_39: _,
    SteamDeckVerified_TestDisplayName_40: _,
    SteamDeckVerified_TestDisplayName_41: _,
    SteamDeckVerified_TestDisplayName_42: _,
    SteamDeckVerified_TestDisplayName_43: _,
    SteamDeckVerified_TestDisplayName_44: _,
    SteamDeckVerified_TestDisplayName_45: _,
    SteamDeckVerified_TestDisplayName_46: _,
    SteamDeckVerified_TestDisplayName_47: _,
    SteamDeckVerified_TestDisplayName_48: _,
    SteamDeckVerified_TestDisplayName_49: _,
    SteamDeckVerified_TestDisplayName_50: _,
    SteamDeckVerified_TestDisplayName_51: _,
    SteamDeckVerified_TestDisplayName_52: _,
    SteamDeckVerified_TestDisplayName_53: _,
    SteamDeckVerified_TestDisplayName_54: _,
    SteamDeckVerified_TestDisplayName_55: _,
    SteamDeckVerified_TestDisplayName_56: _,
    SteamDeckVerified_TestDisplayName_57: _,
    SteamDeckVerified_TestDisplayName_58: _,
    SteamDeckVerified_TestDisplayName_59: _,
    SteamDeckVerified_TestDisplayName_60: _,
    SteamDeckVerified_TestDisplayName_61: _,
    SteamDeckVerified_TestDisplayName_62: _,
    SteamDeckVerified_TestDisplayName_63: _,
    SteamDeckVerified_TestDisplayName_64: _,
    SteamDeckVerified_TestDisplayName_65: _,
    Compatibility_Tab_Steam_Machine: _,
    Compatibility_Tab_Steam_OS: _,
    Compatibility_Tab_Steam_Deck: _,
    Compatibility_Tab_Steam_Frame: _,
    SteamDeck_BuildReview_PleaseRequestTest: _,
    SteamFrame_BuildReview_Checklist_Intro_Header_V2: _,
    SteamFrame_BuildReview_PleaseConfirm_Title_V2: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P1: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P3: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P3_ReviewProcess: _,
    SteamFrame_BuildReview_PleaseConfirm_Description_V2: _,
    SteamDeck_TestRequest_BuildNotReleased: _,
    SteamDeck_BuildReview_Checklist_Intro: _,
    SteamDeck_BuildReview_Checklist_Intro_Header_V2: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P1: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P2: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3_ReviewProcess: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3_Additional: _,
    SteamDeck_BuildReview_PleaseConfirm_Title_V2: _,
    SteamDeck_BuildReview_PleaseConfirm_Description_V2: _,
    SteamDeck_BuildReview_AppTypeUnavailable: _,
    SteamDeck_BuildReview_Checklist_Input: _,
    SteamDeck_BuildReview_Checklist_Text: _,
    SteamDeck_BuildReview_Checklist_Display: _,
    SteamDeck_BuildReview_Checklist_Functionality: _,
    SteamDeck_BuildReview_Checklist_SteamCloud: _,
    SteamDeck_BuildReview_Checklist_Launcher: _,
    SteamDeck_BuildReview_Checklist_Branch: _,
    SteamDeck_BuildReview_Checklist_Branch_PleaseTest: _,
    SteamDeck_BuildReview_MarkReady_Button: _,
    SteamDeck_BuildReview_MarkReady_Description: _,
    SteamDeck_BuildReview_MarkReady_Notes: _,
    SteamDeck_BuildReview_MarkReady_NotesDefault: _,
    SteamDeck_BuildReview_HelpRequest_Link: _,
    SteamDeck_BuildReview_ViewMoreDetailsInHelp: _,
    SteamDeck_BuildReview_Create_HelpRequest_Title: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes_1: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes_2: _,
    SteamDeck_BuildReview_Create_HelpRequest_SupportTicketIntro: _,
    SteamDeck_BuildReview_Check_Controller: _,
    SteamDeck_BuildReview_Check_Icons: _,
    SteamDeck_BuildReview_Check_TextInput: _,
    SteamDeck_BuildReview_Check_TextInput_V2_NoTextEntry: _,
    SteamDeck_BuildReview_Check_TextInput_V2_YesSteamAPIs: _,
    SteamDeck_BuildReview_Check_TextInput_V2_NoSteamAPIs: _,
    SteamDeck_BuildReview_Check_Cloud_NoSaves: _,
    SteamDeck_BuildReview_Check_Cloud_YesSavesNoCloud: _,
    SteamDeck_BuildReview_Check_Cloud_SinglePlatform: _,
    SteamDeck_BuildReview_Check_Cloud_YesCrossSaves: _,
    SteamDeck_BuildReview_Check_Cloud_NoCrossSaves: _,
    SteamDeck_BuildReview_Check_Display1280: _,
    SteamDeck_BuildReview_Check_DisplayFont: _,
    SteamDeck_BuildReview_Check_FunctionalityLauncher: _,
    SteamDeck_BuildReview_Check_FunctionalityCloudSaves: _,
    SteamDeck_BuildReview_Check_FunctionalityCrossPlatformCloudSaves: _,
    SteamDeck_BuildReview_Check_TestLinuxBuild_Preamble: _,
    SteamDeck_BuildReview_Check_TestLinuxBuild: _,
    SteamDeck_BuildReview_Check_Launcher_V2_NoLauncher: _,
    SteamDeck_BuildReview_Check_Launcher_V2_ControllerSupport: _,
    SteamDeck_BuildReview_Check_Launcher_V2_NoControllerSupport: _,
    SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves: _,
    SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves_Documentation: _,
    SteamDeck_BuildReview_CheckNote_DisplayFont: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_InputRecommendations:
      _,
    SteamDeck_BuildReview_CheckNote_Launcher_V2_NoControllerSupport: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_LauncherRecommendations:
      _,
    SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud: _,
    SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud_SteamCloud: _,
    SteamDeck_BuildReview_CheckNote_FullController: _,
    SteamDeck_BuildReview_InReview_Title: _,
    SteamDeck_BuildReview_InReview_Description: _,
    SteamDeck_BuildReview_PleaseComplete: _,
    SteamDeck_BuildReview_Unsupported_Title: _,
    SteamDeck_BuildReview_Unsupported_Description: _,
    SteamDeck_BuildReview_NotMeetRequirements_Title: _,
    SteamDeck_BuildReview_NotMeetRequirements_Description: _,
    SteamFrame_BuildReview_Checklist_Build: _,
    SteamFrame_BuildReview_Build_Android: _,
    SteamFrame_BuildReview_Build_Windows: _,
    SteamFrame_BuildReview_Build_Linux: _,
    SteamFrame_BuildReview_Checklist_Dimension: _,
    SteamFrame_BuildReview_Dimension_2D: `2D`,
    SteamFrame_BuildReview_Dimension_VR: `VR`,
    SteamFrame_NotApplicableForDimension: _,
    SteamFrame_BuildReview_Check_VRPerformance_Verified_Without: _,
    SteamFrame_BuildReview_Check_VRPerformance_Verified_With: _,
    SteamFrame_BuildReview_Check_VRPerformance_Playable_Without: _,
    SteamFrame_BuildReview_Check_VRPerformance_Playable_With: _,
    SteamFrame_BuildReview_Check_VRPerformance_Unsupported: _,
    SteamFrame_BuildReview_Check_VRPerformance_NotApplicable: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_Title: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_Description: _,
    SteamFrame_BuildReview_VRPerformanceLink: _,
    SteamFrame_BuildReview_CheckNote_DisplayFont: _,
    SteamFrame_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs: _,
    SteamFrame_BuildReview_Compatibility_Checklist: _,
    SteamFrame_BuildReview_CheckNote_Launcher_V2_NoControllerSupport: _,
    SteamFrame_BuildReview_CheckNote_Cloud_YesSavesNoCloud: _,
    SteamFrame_BuildReview_CheckNote_Cloud_NoCrossSaves: _,
    SteamFrame_BuildReview_Check_Icons: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_StatusReason: _,
    SteamFrame_BuildReview_Check_VRPerformance_Startup: _,
    SteamFrame_BuildReview_Check_VRPerformance_Loading: _,
    SteamFrame_BuildReview_Check_VRPerformance_Other: _,
    SteamFrame_BuildReview_CheckNote_Missing_Android_License: _,
    SteamFrame_BuildReview_CheckNote_Missing_Android_License_Link: _,
    dummy: _,
  };
export {
  _ as Compatibility_Tab_Steam_Deck,
  _ as Compatibility_Tab_Steam_Frame,
  _ as Compatibility_Tab_Steam_Machine,
  _ as Compatibility_Tab_Steam_OS,
  _ as ContentSurvey_History_Title,
  _ as ContentSurvey_History_Title_Default,
  _ as ContentSurvey_InvalidApp,
  _ as ContentSurvey_Title,
  _ as ContentSurvey_Title_Default,
  _ as Footer_Description,
  _ as Footer_Sitemap_ContactSupport,
  _ as PartnerSite_NotLoggedIn,
  _ as PartnerSite_PermissionDenied,
  _ as PricingExplorer_About_Dash,
  _ as PricingExplorer_About_Desc1,
  _ as PricingExplorer_About_Desc2,
  _ as PricingExplorer_About_LastUpdated,
  _ as PricingExplorer_About_Link1,
  _ as PricingExplorer_About_Link2,
  _ as PricingExplorer_About_LinkName1,
  _ as PricingExplorer_About_LinkName2,
  _ as PricingExplorer_About_Title,
  _ as PricingExplorer_Base,
  _ as PricingExplorer_BasePrice,
  _ as PricingExplorer_Column1,
  _ as PricingExplorer_Column2,
  _ as PricingExplorer_Column3,
  _ as PricingExplorer_Column4,
  _ as PricingExplorer_Explore_desc1,
  _ as PricingExplorer_Explore_line1,
  _ as PricingExplorer_Explore_line2,
  _ as PricingExplorer_Explore_line3,
  _ as PricingExplorer_Explore_title,
  _ as PricingExplorer_LoadError,
  _ as PricingExplorer_Regions_Column1,
  _ as PricingExplorer_Regions_TableHeader,
  _ as PricingExplorer_TableHeader,
  _ as Pricing_Dummy,
  _ as SteamDeckVerified_TestDisplayName_0,
  _ as SteamDeckVerified_TestDisplayName_1,
  _ as SteamDeckVerified_TestDisplayName_10,
  _ as SteamDeckVerified_TestDisplayName_11,
  _ as SteamDeckVerified_TestDisplayName_12,
  _ as SteamDeckVerified_TestDisplayName_13,
  _ as SteamDeckVerified_TestDisplayName_14,
  _ as SteamDeckVerified_TestDisplayName_15,
  _ as SteamDeckVerified_TestDisplayName_16,
  _ as SteamDeckVerified_TestDisplayName_17,
  _ as SteamDeckVerified_TestDisplayName_18,
  _ as SteamDeckVerified_TestDisplayName_19,
  _ as SteamDeckVerified_TestDisplayName_2,
  _ as SteamDeckVerified_TestDisplayName_20,
  _ as SteamDeckVerified_TestDisplayName_21,
  _ as SteamDeckVerified_TestDisplayName_22,
  _ as SteamDeckVerified_TestDisplayName_23,
  _ as SteamDeckVerified_TestDisplayName_24,
  _ as SteamDeckVerified_TestDisplayName_25,
  _ as SteamDeckVerified_TestDisplayName_26,
  _ as SteamDeckVerified_TestDisplayName_27,
  _ as SteamDeckVerified_TestDisplayName_29,
  _ as SteamDeckVerified_TestDisplayName_3,
  _ as SteamDeckVerified_TestDisplayName_30,
  _ as SteamDeckVerified_TestDisplayName_31,
  _ as SteamDeckVerified_TestDisplayName_32,
  _ as SteamDeckVerified_TestDisplayName_33,
  _ as SteamDeckVerified_TestDisplayName_34,
  _ as SteamDeckVerified_TestDisplayName_35,
  _ as SteamDeckVerified_TestDisplayName_36,
  _ as SteamDeckVerified_TestDisplayName_37,
  _ as SteamDeckVerified_TestDisplayName_38,
  _ as SteamDeckVerified_TestDisplayName_39,
  _ as SteamDeckVerified_TestDisplayName_4,
  _ as SteamDeckVerified_TestDisplayName_40,
  _ as SteamDeckVerified_TestDisplayName_41,
  _ as SteamDeckVerified_TestDisplayName_42,
  _ as SteamDeckVerified_TestDisplayName_43,
  _ as SteamDeckVerified_TestDisplayName_44,
  _ as SteamDeckVerified_TestDisplayName_45,
  _ as SteamDeckVerified_TestDisplayName_46,
  _ as SteamDeckVerified_TestDisplayName_47,
  _ as SteamDeckVerified_TestDisplayName_48,
  _ as SteamDeckVerified_TestDisplayName_49,
  _ as SteamDeckVerified_TestDisplayName_5,
  _ as SteamDeckVerified_TestDisplayName_50,
  _ as SteamDeckVerified_TestDisplayName_51,
  _ as SteamDeckVerified_TestDisplayName_52,
  _ as SteamDeckVerified_TestDisplayName_53,
  _ as SteamDeckVerified_TestDisplayName_54,
  _ as SteamDeckVerified_TestDisplayName_55,
  _ as SteamDeckVerified_TestDisplayName_56,
  _ as SteamDeckVerified_TestDisplayName_57,
  _ as SteamDeckVerified_TestDisplayName_58,
  _ as SteamDeckVerified_TestDisplayName_59,
  _ as SteamDeckVerified_TestDisplayName_6,
  _ as SteamDeckVerified_TestDisplayName_60,
  _ as SteamDeckVerified_TestDisplayName_61,
  _ as SteamDeckVerified_TestDisplayName_62,
  _ as SteamDeckVerified_TestDisplayName_63,
  _ as SteamDeckVerified_TestDisplayName_64,
  _ as SteamDeckVerified_TestDisplayName_65,
  _ as SteamDeckVerified_TestDisplayName_7,
  _ as SteamDeckVerified_TestDisplayName_8,
  _ as SteamDeckVerified_TestDisplayName_9,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyDescription_RecommendedRuntime,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_ExpectedInput,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_FDMDebug,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RPODebug,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RecommendedRuntime,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RequiresH264,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TSOEnable,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TestedBuildID,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TestedProtonVersion,
  _ as SteamDeck_AppLanding_History,
  _ as SteamDeck_AppLanding_Published,
  _ as SteamDeck_AppLanding_Unpublished,
  _ as SteamDeck_BuildReview_AppTypeUnavailable,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves_Documentation,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud_SteamCloud,
  _ as SteamDeck_BuildReview_CheckNote_DisplayFont,
  _ as SteamDeck_BuildReview_CheckNote_FullController,
  _ as SteamDeck_BuildReview_CheckNote_Launcher_V2_NoControllerSupport,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_InputRecommendations,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_LauncherRecommendations,
  _ as SteamDeck_BuildReview_Check_Cloud_NoCrossSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_NoSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_SinglePlatform,
  _ as SteamDeck_BuildReview_Check_Cloud_YesCrossSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_YesSavesNoCloud,
  _ as SteamDeck_BuildReview_Check_Controller,
  _ as SteamDeck_BuildReview_Check_Display1280,
  _ as SteamDeck_BuildReview_Check_DisplayFont,
  _ as SteamDeck_BuildReview_Check_FunctionalityCloudSaves,
  _ as SteamDeck_BuildReview_Check_FunctionalityCrossPlatformCloudSaves,
  _ as SteamDeck_BuildReview_Check_FunctionalityLauncher,
  _ as SteamDeck_BuildReview_Check_Icons,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_ControllerSupport,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_NoControllerSupport,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_NoLauncher,
  _ as SteamDeck_BuildReview_Check_TestLinuxBuild,
  _ as SteamDeck_BuildReview_Check_TestLinuxBuild_Preamble,
  _ as SteamDeck_BuildReview_Check_TextInput,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_NoSteamAPIs,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_NoTextEntry,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_YesSteamAPIs,
  _ as SteamDeck_BuildReview_Checklist_Branch,
  _ as SteamDeck_BuildReview_Checklist_Branch_PleaseTest,
  _ as SteamDeck_BuildReview_Checklist_Display,
  _ as SteamDeck_BuildReview_Checklist_Functionality,
  _ as SteamDeck_BuildReview_Checklist_Input,
  _ as SteamDeck_BuildReview_Checklist_Intro,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P1,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P2,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3_Additional,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3_ReviewProcess,
  _ as SteamDeck_BuildReview_Checklist_Intro_Header_V2,
  _ as SteamDeck_BuildReview_Checklist_Launcher,
  _ as SteamDeck_BuildReview_Checklist_SteamCloud,
  _ as SteamDeck_BuildReview_Checklist_Text,
  _ as SteamDeck_BuildReview_CompatibilityTests,
  _ as SteamDeck_BuildReview_Create_HelpRequest,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_1,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2a,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2b,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes,
  _ as SteamDeck_BuildReview_Create_HelpRequest_NotesDefault,
  _ as SteamDeck_BuildReview_Create_HelpRequest_NotesDefault_Rereview,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes_1,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes_2,
  _ as SteamDeck_BuildReview_Create_HelpRequest_SupportTicketIntro,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Title,
  _ as SteamDeck_BuildReview_Documentation,
  _ as SteamDeck_BuildReview_Header_History,
  _ as SteamDeck_BuildReview_Header_Results,
  _ as SteamDeck_BuildReview_HelpRequest_Link,
  _ as SteamDeck_BuildReview_Help_Request_Title,
  _ as SteamDeck_BuildReview_InReview_Description,
  _ as SteamDeck_BuildReview_InReview_Title,
  _ as SteamDeck_BuildReview_InReview_ViewTicket,
  _ as SteamDeck_BuildReview_MarkReady_Button,
  _ as SteamDeck_BuildReview_MarkReady_Description,
  _ as SteamDeck_BuildReview_MarkReady_Notes,
  _ as SteamDeck_BuildReview_MarkReady_NotesDefault,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Description,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Button,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label_Machine,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Ticket_Content,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Title,
  _ as SteamDeck_BuildReview_PleaseComplete,
  _ as SteamDeck_BuildReview_PleaseConfirm_Description_V2,
  _ as SteamDeck_BuildReview_PleaseConfirm_Title_V2,
  _ as SteamDeck_BuildReview_PleaseRequestTest,
  _ as SteamDeck_BuildReview_PublishDialog_Body,
  _ as SteamDeck_BuildReview_PublishDialog_Title,
  _ as SteamDeck_BuildReview_PublishResults,
  _ as SteamDeck_BuildReview_PublishedOn,
  _ as SteamDeck_BuildReview_ReportedOn,
  _ as SteamDeck_BuildReview_RequestStatusActive,
  _ as SteamDeck_BuildReview_RequestStatusClosed,
  _ as SteamDeck_BuildReview_Status_Description,
  _ as SteamDeck_BuildReview_Status_Fail,
  _ as SteamDeck_BuildReview_Status_FailMinor,
  _ as SteamDeck_BuildReview_Status_NotApplicable,
  _ as SteamDeck_BuildReview_Status_Pass,
  _ as SteamDeck_BuildReview_Status_Raw_Comment,
  _ as SteamDeck_BuildReview_Status_Raw_Description,
  _ as SteamDeck_BuildReview_Status_Raw_Impact,
  _ as SteamDeck_BuildReview_Status_Raw_Result,
  _ as SteamDeck_BuildReview_Status_Raw_Test,
  _ as SteamDeck_BuildReview_Status_Raw_Title,
  _ as SteamDeck_BuildReview_Status_TestProperties_Description,
  _ as SteamDeck_BuildReview_Status_TestProperties_Playable,
  _ as SteamDeck_BuildReview_Status_TestProperty_Desc,
  _ as SteamDeck_BuildReview_Status_TestProperty_Name,
  _ as SteamDeck_BuildReview_Status_TestProperty_Value,
  _ as SteamDeck_BuildReview_Status_Title,
  _ as SteamDeck_BuildReview_UnknownError,
  _ as SteamDeck_BuildReview_Unsupported_Description,
  _ as SteamDeck_BuildReview_Unsupported_Title,
  _ as SteamDeck_BuildReview_ViewMoreDetailsInHelp,
  _ as SteamDeck_BuildReview_Viewing_Historical,
  _ as SteamDeck_BuildReview_Viewing_Published,
  _ as SteamDeck_HardwareCompatibility_Title,
  _ as SteamDeck_TestRequest_BuildNotReleased,
  _ as SteamFrame_BuildReview_Build_Android,
  _ as SteamFrame_BuildReview_Build_Linux,
  _ as SteamFrame_BuildReview_Build_Windows,
  _ as SteamFrame_BuildReview_CheckNote_Cloud_NoCrossSaves,
  _ as SteamFrame_BuildReview_CheckNote_Cloud_YesSavesNoCloud,
  _ as SteamFrame_BuildReview_CheckNote_DisplayFont,
  _ as SteamFrame_BuildReview_CheckNote_Launcher_V2_NoControllerSupport,
  _ as SteamFrame_BuildReview_CheckNote_Missing_Android_License,
  _ as SteamFrame_BuildReview_CheckNote_Missing_Android_License_Link,
  _ as SteamFrame_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs,
  _ as SteamFrame_BuildReview_Check_Icons,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Loading,
  _ as SteamFrame_BuildReview_Check_VRPerformance_NotApplicable,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Other,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Playable_With,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Playable_Without,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Startup,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Unsupported,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Verified_With,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Verified_Without,
  _ as SteamFrame_BuildReview_Checklist_Build,
  _ as SteamFrame_BuildReview_Checklist_Dimension,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P1,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P3,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P3_ReviewProcess,
  _ as SteamFrame_BuildReview_Checklist_Intro_Header_V2,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_Description,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_StatusReason,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_Title,
  _ as SteamFrame_BuildReview_Compatibility_Checklist,
  _ as SteamFrame_BuildReview_Dimension_2D,
  _ as SteamFrame_BuildReview_Dimension_VR,
  _ as SteamFrame_BuildReview_PleaseConfirm_Description_V2,
  _ as SteamFrame_BuildReview_PleaseConfirm_Title_V2,
  _ as SteamFrame_BuildReview_VRPerformanceLink,
  _ as SteamFrame_NotApplicableForDimension,
  _ as SteamHardware_BuildReview_Playable_Description,
  _ as SteamHardware_BuildReview_Playable_Title,
  _ as SteamHardware_BuildReview_Unknown_Title,
  _ as SteamHardware_BuildReview_Unsupported_Description,
  _ as SteamHardware_BuildReview_Unsupported_Title,
  _ as SteamHardware_BuildReview_Verified_Description,
  _ as SteamHardware_BuildReview_Verified_Share,
  _ as SteamHardware_BuildReview_Verified_Title,
  _ as SteamHardware_Frame_Unknown,
  _ as SteamHardware_Machine_Unknown,
  _ as SteamHardware_RatingImpact_Informational,
  _ as SteamHardware_RatingImpact_Playable,
  _ as SteamHardware_RatingImpact_Unsupported,
  _ as SteamLearn_Config_DataSource_Input_Preprocess_CompactTable,
  _ as SteamLearn_Event_InProgress,
  _ as SteamLearn_FetchStatus_Canceled,
  _ as SteamLearn_FetchStatus_Percent,
  _ as SteamLearn_Project_Create_Error,
  _ as SteamLearn_Project_Edit_Cancel,
  _ as SteamLearn_Project_Schedule,
  _ as SteamLearn_SnapshotFilter_SamplePercent,
  _ as SteamLearn_Status_Train_Axis_Accuracy,
  _ as SteamLearn_Status_Train_BatchCurrent_EpochDuration,
  _ as SteamLearn_Status_Train_BatchCurrent_Train,
  _ as SteamLearn_Status_Train_BatchCurrent_Validate,
  _ as SteamLearn_Status_Train_EndEarly,
  _ as SteamLearn_Status_Train_EpochOption,
  _ as SteamLearn_Status_Train_Status_Error,
  _ as SteamLearn_Status_Train_Status_InProgress,
  _ as SteamLearn_Status_Train_Status_Loading,
  _ as SteamLearn_Status_Train_Status_StoppedEarly,
  _ as SteamLearn_Status_Train_Status_Unknown,
  _ as SteamLearn_Status_Train_TrainOption,
  _ as SteamLearn_TrainStatus_InProgress,
  _ as SteamLearn_TrainStatus_WaitingOnASS,
  _ as Valve_Confidential,
  _ as Valve_Confidential_Description,
  _ as default,
  _ as dummy,
};
