var _ = `Selecciona un precio en dólares estadounidenses a continuación`,
  _ = `Gratis`,
  _ = `Configurar como gratuito...`,
  _ = `Actualiza este paquete para ofrecérselo gratis a los clientes`,
  _ = `Solo un representante del equipo de Soporte de Valve puede declarar este paquete como gratuito. Utiliza el enlace "Contacta al equipo de publicación de Steam" bajo "Documentación y ayuda" para obtener más asistencia.`,
  _ = `¿Quieres configurar el paquete como gratuito?`,
  _ = `Esto configurará el precio de tu paquete como gratuito, marcará tu aplicación para que aparezca en el punto de encuentro de Free to Play, y cambiará la ventana del precio en función del término que selecciones a continuación. Este cambio no se puede revertir sin enviar un ticket al equipo de Soporte de Steam.`,
  _ = `Solo un representante del equipo de Soporte de Valve puede declarar este paquete como gratuito. Haz clic a continuación para crear un ticket de solicitud de soporte con detalles sobre tu solicitud.`,
  _ = `Selecciona el texto adecuado que aparecerá en lugar del precio:`,
  _ = `"Free to Play": El juego se puede descargar y jugar gratis, pero incluye compras opcionales en el juego (artículos, moneda, DLC u otros tipos de monetización).`,
  _ = `"Gratis": El juego se puede descargar y jugar gratis. No incluye compras en el juego ni contenido de pago.`,
  _ = `Configurar como gratuito`,
  _ = `Actualizando la página de la tienda del juego para que se incluya en la categoría "gratuito". Se requiere publicar en la tienda.`,
  _ = `Actualizando el paquete para que sea gratuito`,
  _ = `La conversión a versión gratuita se realizó correctamente. La página se actualizará al cerrar este cuadro de diálogo.
`,
  _ = `No se pudo actualizar la página de la tienda de la aplicación: %1$s`,
  _ = `No se pudo cambiar el tipo de paquete: %1$s`,
  _ = `Método de conversión (%1$s)`,
  _ = `Ver detalles`,
  _ = `Selecciona el precio al que deseas vender tu producto en el menú despegable a continuación. Para cualquier precio base que elijas, esta herramienta sugerirá precios regionales apropiados con base en nuestra experiencia con otros títulos de precios similares. Ten en cuenta que las conversiones recomendadas para algunos países incluyen IVA/GST/JCT. IVA, GST y JCT, que son impuestos sobre el valor agregado, similares al impuesto sobre ventas, recaudados por las autoridades fiscales.
En los países donde la legislación vigente exige la aplicación del IVA, este viene incluido en los precios y se cobra en las compras realizadas desde esos países. Puedes encontrar una lista de los países en los que se recauda el IVA aquí: %1$s`,
  _ = `Antes de enviarlos, revisa tus precios EN TODAS LAS MONEDAS y piensa detenidamente acerca de tu producto. Por varias razones, recomendamos a nuestros socios no modificar sus precios durante las primeras semanas después del lanzamiento. Si lo necesitas, puedes enviar una solucitud de precios nuevos antes del lanzamiento, pero una vez que tu producto esté disponible para el público tus precios se mantendrán fijos. Para obtener más información, consulta la %1$s.`,
  _ = `documentación sobre precios y descuentos`,
  _ = `Cuando estés satisfecho con tu precio, presiona el botón "Guardar" para enviárselo a Valve para su revisión y procesamiento.`,
  _ = `Editar en la página de precios al por mayor`,
  _ = `Editar la fijación de precios de este paquete desde la herramienta de precios al por mayor`,
  _ = `Ayuda y directrices`,
  _ = `¿Buscas ayuda o sugerencias para fijar los precios de tu título? A continuación, encontrarás un enlace a algunas consideraciones y directrices comunes.`,
  _ = `Documentación sobre fijación de precios`,
  _ = `Preguntas frecuentes`,
  _ = `¿Quieres que tu producto pase a ser gratuito?`,
  _ = `Si tu juego ya está publicado y necesitas cambiarlo a gratuito, haz clic %1$s para obtener más información y solicitar ayuda.`,
  _ = `aquí`,
  _ = `Ingresar precios personalizados`,
  _ = `Puedes ingresar tus propios precios para cada moneda editando directamente el cuadro de texto.`,
  _ = `También puedes utilizar este botón para calcular cada moneda en función del método de conversión seleccionado y del valor personalizado en USD que hayas ingresado.`,
  _ = `Seleccionar de las categorías de precios`,
  _ = `Seleccionar precio base en USD`,
  _ = `Abre una ventana de diálogo con un conjunto de categorías de precios comunes, para así poder establecerlos para todas las monedas listadas a continuación.`,
  _ = `Conversión de variables múltiples`,
  _ = `Solo conversión basada en el poder adquisitivo`,
  _ = `Solo conversión basada en el tipo de cambio`,
  _ = `Última actualización:`,
  _ = `Los métodos de conversión se generan utilizando datos públicos a partir de enero de 2026.`,
  _ = `Hay nuevos métodos de conversión disponibles`,
  _ = `Para ayudarte a fijar el precio de tu juego en 37 monedas diferentes y 4 regiones, Steam ahora ofrece varios métodos para la conversión a partir del precio base que desees.`,
  _ = `El precio lo decides tú; estas herramientas están diseñadas para ayudarte a simplificar el proceso si así lo deseas.`,
  _ = `Visita nuestra %1$s o haz clic en "Ver detalles" anteriormente para obtener más información sobre los diferentes métodos de conversión disponibles.`,
  _ = `Página de detalles del método de conversión`,
  _ = `Aplicar precios del modo de conversión`,
  _ = `Para ayudarte a administrar los precios en las más de 35 monedas con las que es compatible Steam, esta herramienta te permite convertir el precio base en dólares estadounidenses (USD) en niveles adecuados para cada región.`,
  _ = `Selecciona un precio a continuación para establecerlo como precio en dólares estadounidenses (USD) y aplicar los precios con la conversión en todas las demás monedas. Depende del método de conversión seleccionado.`,
  _ = `Puedes ingresar precios para cada moneda individual admitida, o utilizar uno de los métodos de conversión de Steam para convertir tu precio en dólares estadounidenses a las demás monedas.`,
  _ = `Hay dos maneras de utilizar los métodos de conversión de Steam:`,
  _ = `Selecciona un precio común en USD en el menú desplegable del campo de precios que aparece a continuación, y Steam rellenará los campos de las otras divisas según el método de conversión que selecciones.`,
  _ = `Para precios no comunes en dólares estadounidenses, ingresa un valor en el campo de precio en USD, haz clic en el botón "Convertir precios..." y sigue las instrucciones.`,
  _ = `Sugerencia de conversión:`,
  _ = `El precio es una sugerencia basada en el método de conversión seleccionado arriba y un precio en dólares estadounidenses de %1$s.`,
  _ = `prueba`,
  _ = ``,
  _ = {
    PricingGuideline_Default: _,
    FreeOnDemand_InlineOption: _,
    FreeOnDemand_Button: _,
    FreeOnDemand_Button_ttip: _,
    FreeOnDemand_Button_disabled_ttip: _,
    FreeOnDemand_Title: _,
    FreeOnDemand_Desc: _,
    FreeOnDemand_Desc_NotPermitted: _,
    FreeOnDemand_Radio: _,
    FreeOnDemand_Radio_FreeToPlay: _,
    FreeOnDemand_Radio_Free: _,
    FreeOnDemand_Button_Confirm: _,
    FreeOnDemand_Convert_Store: _,
    FreeOnDemand_Convert_Package: _,
    FreeOnDemand_ConvertSuccess: _,
    FreeOnDemand_Store_Error: _,
    FreeOnDemand_Package_Error: _,
    ConversionMethod_Title: _,
    ConversionMethod_Link: _,
    SinglePricingPackage_Desc_1: _,
    SinglePricingPackage_Desc_2: _,
    SinglePricingPackage_Desc_2_Link: _,
    SinglePricingPackage_Desc_3: _,
    SinglePackagePricing_Right_Edit: _,
    SinglePackagePricing_Right_Edit_desc: _,
    SinglePackagePricing_Right_Help_Title: _,
    SinglePackagePricing_Right_Help_Desc: _,
    SinglePackagePricing_Right_Link: _,
    SinglePackagePricing_Right_FAQ: _,
    SinglePackagePricing_Right_FAQ_switching: _,
    SinglePackagePricing_Right_FAQ_switching_answer: _,
    SinglePackagePricing_Right_FAQ_switching_answer_link: _,
    SinglePackagePricing_Right_Convert_Title: _,
    SinglePackagePricing_Right_Custom_Desc: _,
    SinglePackagePricing_Right_Convert_Desc: _,
    PricingDashboard_Select_Price: _,
    PricingDashboard_Select_Price_button: _,
    PricingDashboard_Select_Price_button_ttip: _,
    ConversionMethod_Nuanced: _,
    ConversionMethod_PPP: _,
    ConversionMethod_FX: _,
    PricingExplorer_Time_Title: _,
    PricingExplorer_Time_Disc: _,
    Tour_ConversionMethod_Title: _,
    Tour_ConversionMethod_Desc1: _,
    Tour_ConversionMethod_Desc2: _,
    Tour_ConversionMethod_Desc3: _,
    Tour_ConversionMethod_Link: _,
    PricingDashboard_ApplyConversion_Method: _,
    PricingDashboard_ApplyGuidelines_Instructions_MultiOptions: _,
    PricingDashboard_GuidelinesPickerDescription_New: _,
    SinglePricingPackage_Intro_1: _,
    SinglePricingPackage_Intro_2: _,
    SinglePricingPackage_Intro_2a: _,
    SinglePricingPackage_Intro_2b: _,
    PricingDashboard_Method_SuggestedPrice: _,
    PricingDashboard_Method_SuggestedPrice_ttip: _,
    dummy: _,
    empty_no_trailing_comma: ``,
  };
export {
  _ as ConversionMethod_FX,
  _ as ConversionMethod_Link,
  _ as ConversionMethod_Nuanced,
  _ as ConversionMethod_PPP,
  _ as ConversionMethod_Title,
  _ as FreeOnDemand_Button,
  _ as FreeOnDemand_Button_Confirm,
  _ as FreeOnDemand_Button_disabled_ttip,
  _ as FreeOnDemand_Button_ttip,
  _ as FreeOnDemand_ConvertSuccess,
  _ as FreeOnDemand_Convert_Package,
  _ as FreeOnDemand_Convert_Store,
  _ as FreeOnDemand_Desc,
  _ as FreeOnDemand_Desc_NotPermitted,
  _ as FreeOnDemand_InlineOption,
  _ as FreeOnDemand_Package_Error,
  _ as FreeOnDemand_Radio,
  _ as FreeOnDemand_Radio_Free,
  _ as FreeOnDemand_Radio_FreeToPlay,
  _ as FreeOnDemand_Store_Error,
  _ as FreeOnDemand_Title,
  _ as PricingDashboard_ApplyConversion_Method,
  _ as PricingDashboard_ApplyGuidelines_Instructions_MultiOptions,
  _ as PricingDashboard_GuidelinesPickerDescription_New,
  _ as PricingDashboard_Method_SuggestedPrice,
  _ as PricingDashboard_Method_SuggestedPrice_ttip,
  _ as PricingDashboard_Select_Price,
  _ as PricingDashboard_Select_Price_button,
  _ as PricingDashboard_Select_Price_button_ttip,
  _ as PricingExplorer_Time_Disc,
  _ as PricingExplorer_Time_Title,
  _ as PricingGuideline_Default,
  _ as SinglePackagePricing_Right_Convert_Desc,
  _ as SinglePackagePricing_Right_Convert_Title,
  _ as SinglePackagePricing_Right_Custom_Desc,
  _ as SinglePackagePricing_Right_Edit,
  _ as SinglePackagePricing_Right_Edit_desc,
  _ as SinglePackagePricing_Right_FAQ,
  _ as SinglePackagePricing_Right_FAQ_switching,
  _ as SinglePackagePricing_Right_FAQ_switching_answer,
  _ as SinglePackagePricing_Right_FAQ_switching_answer_link,
  _ as SinglePackagePricing_Right_Help_Desc,
  _ as SinglePackagePricing_Right_Help_Title,
  _ as SinglePackagePricing_Right_Link,
  _ as SinglePricingPackage_Desc_1,
  _ as SinglePricingPackage_Desc_2,
  _ as SinglePricingPackage_Desc_2_Link,
  _ as SinglePricingPackage_Desc_3,
  _ as SinglePricingPackage_Intro_1,
  _ as SinglePricingPackage_Intro_2,
  _ as SinglePricingPackage_Intro_2a,
  _ as SinglePricingPackage_Intro_2b,
  _ as Tour_ConversionMethod_Desc1,
  _ as Tour_ConversionMethod_Desc2,
  _ as Tour_ConversionMethod_Desc3,
  _ as Tour_ConversionMethod_Link,
  _ as Tour_ConversionMethod_Title,
  _ as default,
  _ as dummy,
  _ as empty_no_trailing_comma,
};
