var _ = `알 수 없음`,
  _ = `미국 달러`,
  _ = `영국 파운드`,
  _ = `유로`,
  _ = `스위스 프랑`,
  _ = `러시아 루블`,
  _ = `폴란드 즈워티`,
  _ = `브라질 헤알`,
  _ = `일본 엔`,
  _ = `노르웨이 크로네`,
  _ = `인도네시아 루피아`,
  _ = `말레이시아 링깃`,
  _ = `필리핀 페소`,
  _ = `싱가폴 달러`,
  _ = `태국 바트`,
  _ = `베트남 동`,
  _ = `대한민국 원`,
  _ = `튀르키예 리라`,
  _ = `우크라이나 흐리브냐`,
  _ = `멕시코 페소`,
  _ = `캐나다 달러`,
  _ = `호주 달러`,
  _ = `뉴질랜드 달러`,
  _ = `중국 위안`,
  _ = `인도 루피`,
  _ = `칠레 페소`,
  _ = `페루 솔`,
  _ = `콜롬비아 페소`,
  _ = `남아프리카공화국 랜드`,
  _ = `홍콩 달러`,
  _ = `대만 달러`,
  _ = `사우디아라비아 리얄`,
  _ = `아랍에미리트 디르함`,
  _ = `아르헨티나 페소`,
  _ = `이스라엘 신 셰켈`,
  _ = `카자흐스탄 텡게`,
  _ = `쿠웨이트 디나르`,
  _ = `카타르 리알`,
  _ = `코스타리카 콜론`,
  _ = `우루과이 페소`,
  _ = `불가리아 레브`,
  _ = `스웨덴 크로나`,
  _ = `크로아티아 쿠나`,
  _ = `체코 코루나`,
  _ = `덴마크 크로네`,
  _ = `헝가리아 포린트`,
  _ = `루마니아 레우`,
  _ = `벨라루스 루블`,
  _ = `CIS 지역 - 아르메니아, 아제르바이잔, 벨라루스, 키르기스스탄, 몰도바, 타지키스탄, 투르크메니스탄, 우즈베키스탄에 거주하는 고객에게 표시됩니다.`,
  _ = `남아시아 국가 - 방글라데시, 부탄, 네팔, 파키스탄, 스리랑카의 고객에게 표시`,
  _ = `중남미 국가 - 아르헨티나, 벨리즈, 볼리비아, 에콰도르, 엘살바도르, 가이아나, 과테말라, 온두라스, 니카라과, 파나마, 파라과이, 수리남, 베네수엘라에 있는 고객에게 표시됩니다.`,
  _ = `중동 및 북아프리카 국가 - 알제리, 바레인, 이집트, 이라크, 요르단, 레바논, 리비아, 모로코, 오만, 팔레스타인, 수단, 튀니지, 튀르키예, 예멘에 있는 고객에게 표시됩니다.`,
  _ = `알 수 없음`,
  _ = `테스트용`,
  _ = {
    CurrencyCodeDescription_Unknown: _,
    CurrencyCodeDescription_USD: _,
    CurrencyCodeDescription_GBP: _,
    CurrencyCodeDescription_EUR: _,
    CurrencyCodeDescription_CHF: _,
    CurrencyCodeDescription_RUB: _,
    CurrencyCodeDescription_PLN: _,
    CurrencyCodeDescription_BRL: _,
    CurrencyCodeDescription_JPY: _,
    CurrencyCodeDescription_NOK: _,
    CurrencyCodeDescription_IDR: _,
    CurrencyCodeDescription_MYR: _,
    CurrencyCodeDescription_PHP: _,
    CurrencyCodeDescription_SGD: _,
    CurrencyCodeDescription_THB: _,
    CurrencyCodeDescription_VND: _,
    CurrencyCodeDescription_KRW: _,
    CurrencyCodeDescription_TRY: _,
    CurrencyCodeDescription_UAH: _,
    CurrencyCodeDescription_MXN: _,
    CurrencyCodeDescription_CAD: _,
    CurrencyCodeDescription_AUD: _,
    CurrencyCodeDescription_NZD: _,
    CurrencyCodeDescription_CNY: _,
    CurrencyCodeDescription_INR: _,
    CurrencyCodeDescription_CLP: _,
    CurrencyCodeDescription_PEN: _,
    CurrencyCodeDescription_COP: _,
    CurrencyCodeDescription_ZAR: _,
    CurrencyCodeDescription_HKD: _,
    CurrencyCodeDescription_TWD: _,
    CurrencyCodeDescription_SAR: _,
    CurrencyCodeDescription_AED: _,
    CurrencyCodeDescription_ARS: _,
    CurrencyCodeDescription_ILS: _,
    CurrencyCodeDescription_KZT: _,
    CurrencyCodeDescription_KWD: _,
    CurrencyCodeDescription_QAR: _,
    CurrencyCodeDescription_CRC: _,
    CurrencyCodeDescription_UYU: _,
    CurrencyCodeDescription_BGN: _,
    CurrencyCodeDescription_SEK: _,
    CurrencyCodeDescription_HRK: _,
    CurrencyCodeDescription_CZK: _,
    CurrencyCodeDescription_DKK: _,
    CurrencyCodeDescription_HUF: _,
    CurrencyCodeDescription_RON: _,
    CurrencyCodeDescription_BYN: _,
    Region_Pricing_Tooltip_CIS: _,
    Region_Pricing_Tooltip_SASIA: _,
    Region_Pricing_Tooltip_LATAM: _,
    Region_Pricing_Tooltip_MENA: _,
    Region_Pricing_Tooltip_Unknown: _,
    dummy: _,
  };
export {
  _ as CurrencyCodeDescription_AED,
  _ as CurrencyCodeDescription_ARS,
  _ as CurrencyCodeDescription_AUD,
  _ as CurrencyCodeDescription_BGN,
  _ as CurrencyCodeDescription_BRL,
  _ as CurrencyCodeDescription_BYN,
  _ as CurrencyCodeDescription_CAD,
  _ as CurrencyCodeDescription_CHF,
  _ as CurrencyCodeDescription_CLP,
  _ as CurrencyCodeDescription_CNY,
  _ as CurrencyCodeDescription_COP,
  _ as CurrencyCodeDescription_CRC,
  _ as CurrencyCodeDescription_CZK,
  _ as CurrencyCodeDescription_DKK,
  _ as CurrencyCodeDescription_EUR,
  _ as CurrencyCodeDescription_GBP,
  _ as CurrencyCodeDescription_HKD,
  _ as CurrencyCodeDescription_HRK,
  _ as CurrencyCodeDescription_HUF,
  _ as CurrencyCodeDescription_IDR,
  _ as CurrencyCodeDescription_ILS,
  _ as CurrencyCodeDescription_INR,
  _ as CurrencyCodeDescription_JPY,
  _ as CurrencyCodeDescription_KRW,
  _ as CurrencyCodeDescription_KWD,
  _ as CurrencyCodeDescription_KZT,
  _ as CurrencyCodeDescription_MXN,
  _ as CurrencyCodeDescription_MYR,
  _ as CurrencyCodeDescription_NOK,
  _ as CurrencyCodeDescription_NZD,
  _ as CurrencyCodeDescription_PEN,
  _ as CurrencyCodeDescription_PHP,
  _ as CurrencyCodeDescription_PLN,
  _ as CurrencyCodeDescription_QAR,
  _ as CurrencyCodeDescription_RON,
  _ as CurrencyCodeDescription_RUB,
  _ as CurrencyCodeDescription_SAR,
  _ as CurrencyCodeDescription_SEK,
  _ as CurrencyCodeDescription_SGD,
  _ as CurrencyCodeDescription_THB,
  _ as CurrencyCodeDescription_TRY,
  _ as CurrencyCodeDescription_TWD,
  _ as CurrencyCodeDescription_UAH,
  _ as CurrencyCodeDescription_USD,
  _ as CurrencyCodeDescription_UYU,
  _ as CurrencyCodeDescription_Unknown,
  _ as CurrencyCodeDescription_VND,
  _ as CurrencyCodeDescription_ZAR,
  _ as Region_Pricing_Tooltip_CIS,
  _ as Region_Pricing_Tooltip_LATAM,
  _ as Region_Pricing_Tooltip_MENA,
  _ as Region_Pricing_Tooltip_SASIA,
  _ as Region_Pricing_Tooltip_Unknown,
  _ as default,
  _ as dummy,
};
