var _ = `Tidak Diketahui`,
  _ = `Dolar AS`,
  _ = `Paun GB`,
  _ = `Euro`,
  _ = `Franc Switzerland`,
  _ = `Rubel Rusia`,
  _ = `Zloty Poland`,
  _ = `Real Brazil`,
  _ = `Yen Jepun`,
  _ = `Krone Norway`,
  _ = `Rupiah Indonesia`,
  _ = `Ringgit Malaysia`,
  _ = `Peso Filipina`,
  _ = `Dolar Singapura`,
  _ = `Baht Thai`,
  _ = `Dong Vietnam`,
  _ = `Won Korea`,
  _ = `Lira Turkiye`,
  _ = `Hryvnia Ukraine`,
  _ = `Peso Mexico`,
  _ = `Dolar Kanada`,
  _ = `Dolar Australia`,
  _ = `Dolar New Zealand`,
  _ = `Yuan Cina`,
  _ = `Rupee India`,
  _ = `Peso Chile`,
  _ = `Sol Peru`,
  _ = `Peso Colombia`,
  _ = `Rand Afrika Selatan`,
  _ = `Dolar Hong Kong`,
  _ = `Dolar Taiwan`,
  _ = `Riyal Arab Saudi`,
  _ = `Dirham Emiriyah`,
  _ = `Peso Argentina`,
  _ = `Shekel Baru Israel`,
  _ = `Tenge Kazakhstan`,
  _ = `Dinar Kuwait`,
  _ = `Riyal Qatar`,
  _ = `Colon Costa Rica`,
  _ = `Peso Uruguay`,
  _ = `Wilayah CIS – Dipaparkan kepada pelanggan di Armenia, Azerbaijan, Belarus, Georgia, Kyrgyzstan, Moldova, Tajikistan, Turkmenistan, Uzbekistan`,
  _ = `Negara Asia Selatan – Dipaparkan kepada pelanggan di Bangladesh, Bhutan, Nepal, Pakistan, Sri Lanka`,
  _ = `Negara Amerika Latin – Dipaparkan kepada pelanggan di Argentina, Belize, Bolivia, Ecuador, El Salvador, Guyana, Guatemala, Honduras, Nicaragua, Panama, Paraguay, Suriname, Venezuela`,
  _ = `Negara Timur Tengah dan Afrika Utara – Dipaparkan kepada pelanggan di Algeria, Bahrain, Mesir, Iraq, Jordan, Lubnan, Libya, Maghribi, Oman, Palestin, Sudan, Tunisia, Turkiye, Yaman`,
  _ = `Tidak Diketahui`,
  _ = `palsu`,
  _ = {
    CurrencyCodeDescription_Unknown: _,
    CurrencyCodeDescription_USD: _,
    CurrencyCodeDescription_GBP: _,
    CurrencyCodeDescription_EUR: _,
    CurrencyCodeDescription_CHF: _,
    CurrencyCodeDescription_RUB: _,
    CurrencyCodeDescription_PLN: _,
    CurrencyCodeDescription_BRL: _,
    CurrencyCodeDescription_JPY: _,
    CurrencyCodeDescription_NOK: _,
    CurrencyCodeDescription_IDR: _,
    CurrencyCodeDescription_MYR: _,
    CurrencyCodeDescription_PHP: _,
    CurrencyCodeDescription_SGD: _,
    CurrencyCodeDescription_THB: _,
    CurrencyCodeDescription_VND: _,
    CurrencyCodeDescription_KRW: _,
    CurrencyCodeDescription_TRY: _,
    CurrencyCodeDescription_UAH: _,
    CurrencyCodeDescription_MXN: _,
    CurrencyCodeDescription_CAD: _,
    CurrencyCodeDescription_AUD: _,
    CurrencyCodeDescription_NZD: _,
    CurrencyCodeDescription_CNY: _,
    CurrencyCodeDescription_INR: _,
    CurrencyCodeDescription_CLP: _,
    CurrencyCodeDescription_PEN: _,
    CurrencyCodeDescription_COP: _,
    CurrencyCodeDescription_ZAR: _,
    CurrencyCodeDescription_HKD: _,
    CurrencyCodeDescription_TWD: _,
    CurrencyCodeDescription_SAR: _,
    CurrencyCodeDescription_AED: _,
    CurrencyCodeDescription_ARS: _,
    CurrencyCodeDescription_ILS: _,
    CurrencyCodeDescription_KZT: _,
    CurrencyCodeDescription_KWD: _,
    CurrencyCodeDescription_QAR: _,
    CurrencyCodeDescription_CRC: _,
    CurrencyCodeDescription_UYU: _,
    Region_Pricing_Tooltip_CIS: _,
    Region_Pricing_Tooltip_SASIA: _,
    Region_Pricing_Tooltip_LATAM: _,
    Region_Pricing_Tooltip_MENA: _,
    Region_Pricing_Tooltip_Unknown: _,
    dummy: _,
  };
export {
  _ as CurrencyCodeDescription_AED,
  _ as CurrencyCodeDescription_ARS,
  _ as CurrencyCodeDescription_AUD,
  _ as CurrencyCodeDescription_BRL,
  _ as CurrencyCodeDescription_CAD,
  _ as CurrencyCodeDescription_CHF,
  _ as CurrencyCodeDescription_CLP,
  _ as CurrencyCodeDescription_CNY,
  _ as CurrencyCodeDescription_COP,
  _ as CurrencyCodeDescription_CRC,
  _ as CurrencyCodeDescription_EUR,
  _ as CurrencyCodeDescription_GBP,
  _ as CurrencyCodeDescription_HKD,
  _ as CurrencyCodeDescription_IDR,
  _ as CurrencyCodeDescription_ILS,
  _ as CurrencyCodeDescription_INR,
  _ as CurrencyCodeDescription_JPY,
  _ as CurrencyCodeDescription_KRW,
  _ as CurrencyCodeDescription_KWD,
  _ as CurrencyCodeDescription_KZT,
  _ as CurrencyCodeDescription_MXN,
  _ as CurrencyCodeDescription_MYR,
  _ as CurrencyCodeDescription_NOK,
  _ as CurrencyCodeDescription_NZD,
  _ as CurrencyCodeDescription_PEN,
  _ as CurrencyCodeDescription_PHP,
  _ as CurrencyCodeDescription_PLN,
  _ as CurrencyCodeDescription_QAR,
  _ as CurrencyCodeDescription_RUB,
  _ as CurrencyCodeDescription_SAR,
  _ as CurrencyCodeDescription_SGD,
  _ as CurrencyCodeDescription_THB,
  _ as CurrencyCodeDescription_TRY,
  _ as CurrencyCodeDescription_TWD,
  _ as CurrencyCodeDescription_UAH,
  _ as CurrencyCodeDescription_USD,
  _ as CurrencyCodeDescription_UYU,
  _ as CurrencyCodeDescription_Unknown,
  _ as CurrencyCodeDescription_VND,
  _ as CurrencyCodeDescription_ZAR,
  _ as Region_Pricing_Tooltip_CIS,
  _ as Region_Pricing_Tooltip_LATAM,
  _ as Region_Pricing_Tooltip_MENA,
  _ as Region_Pricing_Tooltip_SASIA,
  _ as Region_Pricing_Tooltip_Unknown,
  _ as default,
  _ as dummy,
};
