var _ = `文獻`,
  _ = `首頁`,
  _ = `新手上路`,
  _ = `商店狀態`,
  _ = `功能`,
  _ = `財務`,
  _ = `銷售與行銷`,
  _ = `Steamworks SDK`,
  _ = `網咖授權`,
  _ = `Steam VR`,
  _ = `查看全部`,
  _ = `管理員工具`,
  _ = `資源`,
  _ = `Steam VR`,
  _ = `Steam 網咖計畫`,
  _ = `Steamworks 討論區`,
  _ = `Steamworks 影片教學`,
  _ = `新聞與更新`,
  _ = `Steamworks 網誌`,
  _ = `Steam 網誌`,
  _ = `Steam VR 網誌`,
  _ = `Steam Deck 網誌`,
  _ = `Steamworks`,
  _ = `語言`,
  _ = `變更語言`,
  _ = `登出`,
  _ = `登入`,
  _ = `主控台`,
  _ = `SteamVR 定位`,
  _ = `應用程式與套件`,
  _ = `所有應用程式`,
  _ = `檢視套件`,
  _ = `組合包`,
  _ = `定價`,
  _ = `定價（新！）`,
  _ = `折扣管理`,
  _ = `特賣審核（新！）`,
  _ = `特賣與節慶活動報名`,
  _ = `Steam 新品節`,
  _ = `製作者首頁設定`,
  _ = `製作者首頁自訂網址設定`,
  _ = `行銷工具與資料`,
  _ = `每日特惠管理`,
  _ = `Steam Deck 相容性`,
  _ = `客服中心`,
  _ = `工具`,
  _ = `管理經濟`,
  _ = `查詢 Steam 序號`,
  _ = `封鎖 Steam 序號`,
  _ = `檢視 Steam 序號套件模板`,
  _ = `商店及 Steam 平台流量動向`,
  _ = `目錄建議行動`,
  _ = `在業界會議中 Meet Steam`,
  _ = `使用者與權限`,
  _ = `概覽`,
  _ = `公司詳細資料`,
  _ = `檢視應用程式`,
  _ = `管理使用者`,
  _ = `管理群組`,
  _ = `財務資訊`,
  _ = `文獻與協助`,
  _ = `前往開發者社群群組`,
  _ = `前往開發者討論區`,
  _ = `聯繫 Steam 發行團隊`,
  _ = `聯絡 Steamworks 客服`,
  _ = `Steamworks 開發者支援`,
  _ = `無所屬單位`,
  _ = `依應用程式名或 ID 搜尋`,
  _ = `檢視文獻`,
  _ = `檢視封存文獻庫`,
  _ = `套件詳細資料`,
  _ = `使用者歷史記錄`,
  _ = `使用者邀請歷史記錄`,
  _ = `郵寄地址`,
  _ = `預覽新文獻`,
  _ = `轉移應用程式`,
  _ = `分享應用程式`,
  _ = `直接購買`,
  _ = `檢視銀行付款詳細資料`,
  _ = `核對已提交的收據`,
  _ = `建立 / 管理收據`,
  _ = `商店管理員`,
  _ = `焦點`,
  _ = `首頁`,
  _ = `OEM 工具`,
  _ = `OEM 批量門票`,
  _ = `網咖計畫`,
  _ = `管理據點`,
  _ = `管理商用授權`,
  _ = `歷史使用量`,
  _ = `內容管控`,
  _ = `錢包儲值`,
  _ = `設定`,
  _ = `歷史動態`,
  _ = `儲值許可`,
  _ = `切換組織`,
  _ = `切換 Steamworks 組織`,
  _ = `您的 Steam 帳戶為多個 Steamworks 組織的成員。`,
  _ = `許多 Steamworks 功能只能依您目前所選組織的權限存取。`,
  _ = `請從下拉選單中選擇欲切換的組織：`,
  _ = `切換`,
  _ = `取消`,
  _ = `促銷`,
  _ = `遊戲`,
  _ = `應用程式`,
  _ = `工具`,
  _ = `試用版`,
  _ = `可下載內容（DLC）`,
  _ = `模組`,
  _ = `指南`,
  _ = `配置`,
  _ = `音樂`,
  _ = `插件`,
  _ = `硬體`,
  _ = `影片`,
  _ = `影集`,
  _ = `集數`,
  _ = `電影`,
  _ = `測試版`,
  _ = `季度通行證`,
  _ = `導覽`,
  _ = {
    Header_Global_Documentation: _,
    Header_Global_Documentation_Home: _,
    Header_Global_Documentation_GettingStarted: _,
    Header_Global_Documentation_StorePresence: _,
    Header_Global_Documentation_Features: _,
    Header_Global_Documentation_Finance: _,
    Header_Global_Documentation_SalesMarketing: _,
    Header_Global_Documentation_SteamworksSDK: _,
    Header_Global_Documentation_PCCafe: _,
    Header_Global_Documentation_SteamVR: _,
    Header_Global_Documentation_Seeall: _,
    Header_Nav_DocumentationAdmin: _,
    Header_Global_Resources: _,
    Header_Global_Resources_SteamVR: _,
    Header_Global_Resources_PCCafe: _,
    Header_Global_Resources_Discussions: _,
    Header_Global_Resources_VideoTutorials: _,
    Header_Global_News: _,
    Header_Global_News_Steamworks: _,
    Header_Global_News_Steam: _,
    Header_Global_News_SteamVR: _,
    Header_Global_News_SteamDeck: _,
    Steamworks_Logo_Label: _,
    global_menu_language: _,
    global_menu_change_language: _,
    global_menu_sign_out: _,
    global_menu_sign_in: _,
    Header_Nav_Dashboard: _,
    Header_Nav_Lighthouse: _,
    Header_Nav_AppsPackages: _,
    Header_Nav_AppsPackages_All: _,
    Header_Nav_AppsPackages_ViewPackages: _,
    Header_Nav_AppsPackages_Bundles: _,
    Header_Nav_AppsPackages_Pricing: _,
    Header_Nav_AppsPackages_PricingNew: _,
    Header_Nav_AppsPackages_SaleApproval: _,
    Header_Nav_AppsPackages_SaleApprovalNew: _,
    Header_Nav_AppsPackages_Events: _,
    Header_Nav_AppsPackages_NextFestRecaps: _,
    Header_Nav_AppsPackages_CreatorHome: _,
    Header_Nav_AppsPackages_CreatorHome_Vanity: _,
    Header_Nav_PublisherMarketingStats: _,
    Header_Nav_DailyDeal_Management: _,
    Header_Nav_SteamDeck_Compat: _,
    Header_Nav_Support: _,
    Header_Nav_Tools: _,
    Header_Nav_Tools_Economy: _,
    Header_Nav_Tools_QueryCDKey: _,
    Header_Nav_Tools_BanCDKeys: _,
    Header_Nav_Tools_CDKeyRestrictions: _,
    Header_Nav_Tools_NavTraffic: _,
    Header_Nav_Tools_HealthChecks: _,
    Header_Nav_Tools_MeetSteam: _,
    Header_Nav_UsersPermissions: _,
    Header_Nav_UsersPermissions_Overview: _,
    Header_Nav_UsersPermissions_CompanyDetails: _,
    Header_Nav_UsersPermissions_Applications: _,
    Header_Nav_UsersPermissions_Users: _,
    Header_Nav_UsersPermissions_Groups: _,
    Header_Nav_FinancialInfo: _,
    Header_Nav_DocumentationHelp: _,
    Header_Nav_DeveloperCommunity: _,
    Header_Nav_DeveloperForums: _,
    Header_Nav_Contact_Steam: _,
    Header_Nav_Contact_Dev_Support: _,
    Header_Nav_Contact_Dev_Support2: _,
    Header_Nav_Unaffiliated: _,
    Header_Search_By_Appid: _,
    Header_Nav_ViewDocumentation: _,
    Header_Nav_ViewDocumentationArchive: _,
    Header_Nav_PackageDetails: _,
    Header_Nav_UserGroupHistory: _,
    Header_Nav_UserInviteHistory: _,
    Header_Nav_MailingAddresses: _,
    Header_Nav_PreviewNewDocumentation: _,
    Header_Nav_TransferRequests: _,
    Header_Nav_ShareApplications: _,
    Header_Nav_DirectPurchasing: _,
    Header_Nav_DirectPurchasing_Config: _,
    Header_Nav_DirectPurchasing_OpenInvoices: _,
    Header_Nav_DirectPurchasing_CreateInvoices: _,
    Header_Nav_StoreAdmin: _,
    Header_Nav_StoreAdmin_Spotlights: _,
    Header_Nav_StoreAdmin_Frontpage: _,
    Header_Nav_OEM: _,
    Header_Nav_OEM_Ticket_Batches: _,
    Header_Nav_Sites: _,
    Header_Nav_Sites_Edit_Sites: _,
    Header_Nav_Sites_Current_Usage: _,
    Header_Nav_Sites_Historical_Usage: _,
    Header_Nav_Sites_Content_Control: _,
    Header_Nav_WalletFunding: _,
    Header_Nav_WalletFunding_Config: _,
    Header_Nav_WalletFunding_Usage: _,
    Header_Nav_WalletFunding_Approval: _,
    change_partner_link: _,
    change_partner_dialog_title: _,
    change_partner_dialog_desc_part1: _,
    change_partner_dialog_desc_part2: _,
    change_partner_dialog_desc_part3: _,
    change_partner_dialog_submit: _,
    change_partner_dialog_cancel: _,
    AppType_TitleCase_Advertising: _,
    AppType_TitleCase_Game: _,
    AppType_TitleCase_Application: _,
    AppType_TitleCase_Tool: _,
    AppType_TitleCase_Demo: _,
    AppType_TitleCase_DLC: _,
    AppType_TitleCase_Mod: _,
    AppType_TitleCase_Guide: _,
    AppType_TitleCase_Config: _,
    AppType_TitleCase_Music: _,
    AppType_TitleCase_PlugIn: _,
    AppType_TitleCase_Hardware: _,
    AppType_TitleCase_Video: _,
    AppType_TitleCase_Series: _,
    AppType_TitleCase_Episode: _,
    AppType_TitleCase_Movie: _,
    AppType_TitleCase_Beta: _,
    AppType_TitleCase_DLC_SeasonPass: _,
    Aria_Navigation: _,
  };
export {
  _ as AppType_TitleCase_Advertising,
  _ as AppType_TitleCase_Application,
  _ as AppType_TitleCase_Beta,
  _ as AppType_TitleCase_Config,
  _ as AppType_TitleCase_DLC,
  _ as AppType_TitleCase_DLC_SeasonPass,
  _ as AppType_TitleCase_Demo,
  _ as AppType_TitleCase_Episode,
  _ as AppType_TitleCase_Game,
  _ as AppType_TitleCase_Guide,
  _ as AppType_TitleCase_Hardware,
  _ as AppType_TitleCase_Mod,
  _ as AppType_TitleCase_Movie,
  _ as AppType_TitleCase_Music,
  _ as AppType_TitleCase_PlugIn,
  _ as AppType_TitleCase_Series,
  _ as AppType_TitleCase_Tool,
  _ as AppType_TitleCase_Video,
  _ as Aria_Navigation,
  _ as Header_Global_Documentation,
  _ as Header_Global_Documentation_Features,
  _ as Header_Global_Documentation_Finance,
  _ as Header_Global_Documentation_GettingStarted,
  _ as Header_Global_Documentation_Home,
  _ as Header_Global_Documentation_PCCafe,
  _ as Header_Global_Documentation_SalesMarketing,
  _ as Header_Global_Documentation_Seeall,
  _ as Header_Global_Documentation_SteamVR,
  _ as Header_Global_Documentation_SteamworksSDK,
  _ as Header_Global_Documentation_StorePresence,
  _ as Header_Global_News,
  _ as Header_Global_News_Steam,
  _ as Header_Global_News_SteamDeck,
  _ as Header_Global_News_SteamVR,
  _ as Header_Global_News_Steamworks,
  _ as Header_Global_Resources,
  _ as Header_Global_Resources_Discussions,
  _ as Header_Global_Resources_PCCafe,
  _ as Header_Global_Resources_SteamVR,
  _ as Header_Global_Resources_VideoTutorials,
  _ as Header_Nav_AppsPackages,
  _ as Header_Nav_AppsPackages_All,
  _ as Header_Nav_AppsPackages_Bundles,
  _ as Header_Nav_AppsPackages_CreatorHome,
  _ as Header_Nav_AppsPackages_CreatorHome_Vanity,
  _ as Header_Nav_AppsPackages_Events,
  _ as Header_Nav_AppsPackages_NextFestRecaps,
  _ as Header_Nav_AppsPackages_Pricing,
  _ as Header_Nav_AppsPackages_PricingNew,
  _ as Header_Nav_AppsPackages_SaleApproval,
  _ as Header_Nav_AppsPackages_SaleApprovalNew,
  _ as Header_Nav_AppsPackages_ViewPackages,
  _ as Header_Nav_Contact_Dev_Support,
  _ as Header_Nav_Contact_Dev_Support2,
  _ as Header_Nav_Contact_Steam,
  _ as Header_Nav_DailyDeal_Management,
  _ as Header_Nav_Dashboard,
  _ as Header_Nav_DeveloperCommunity,
  _ as Header_Nav_DeveloperForums,
  _ as Header_Nav_DirectPurchasing,
  _ as Header_Nav_DirectPurchasing_Config,
  _ as Header_Nav_DirectPurchasing_CreateInvoices,
  _ as Header_Nav_DirectPurchasing_OpenInvoices,
  _ as Header_Nav_DocumentationAdmin,
  _ as Header_Nav_DocumentationHelp,
  _ as Header_Nav_FinancialInfo,
  _ as Header_Nav_Lighthouse,
  _ as Header_Nav_MailingAddresses,
  _ as Header_Nav_OEM,
  _ as Header_Nav_OEM_Ticket_Batches,
  _ as Header_Nav_PackageDetails,
  _ as Header_Nav_PreviewNewDocumentation,
  _ as Header_Nav_PublisherMarketingStats,
  _ as Header_Nav_ShareApplications,
  _ as Header_Nav_Sites,
  _ as Header_Nav_Sites_Content_Control,
  _ as Header_Nav_Sites_Current_Usage,
  _ as Header_Nav_Sites_Edit_Sites,
  _ as Header_Nav_Sites_Historical_Usage,
  _ as Header_Nav_SteamDeck_Compat,
  _ as Header_Nav_StoreAdmin,
  _ as Header_Nav_StoreAdmin_Frontpage,
  _ as Header_Nav_StoreAdmin_Spotlights,
  _ as Header_Nav_Support,
  _ as Header_Nav_Tools,
  _ as Header_Nav_Tools_BanCDKeys,
  _ as Header_Nav_Tools_CDKeyRestrictions,
  _ as Header_Nav_Tools_Economy,
  _ as Header_Nav_Tools_HealthChecks,
  _ as Header_Nav_Tools_MeetSteam,
  _ as Header_Nav_Tools_NavTraffic,
  _ as Header_Nav_Tools_QueryCDKey,
  _ as Header_Nav_TransferRequests,
  _ as Header_Nav_Unaffiliated,
  _ as Header_Nav_UserGroupHistory,
  _ as Header_Nav_UserInviteHistory,
  _ as Header_Nav_UsersPermissions,
  _ as Header_Nav_UsersPermissions_Applications,
  _ as Header_Nav_UsersPermissions_CompanyDetails,
  _ as Header_Nav_UsersPermissions_Groups,
  _ as Header_Nav_UsersPermissions_Overview,
  _ as Header_Nav_UsersPermissions_Users,
  _ as Header_Nav_ViewDocumentation,
  _ as Header_Nav_ViewDocumentationArchive,
  _ as Header_Nav_WalletFunding,
  _ as Header_Nav_WalletFunding_Approval,
  _ as Header_Nav_WalletFunding_Config,
  _ as Header_Nav_WalletFunding_Usage,
  _ as Header_Search_By_Appid,
  _ as Steamworks_Logo_Label,
  _ as change_partner_dialog_cancel,
  _ as change_partner_dialog_desc_part1,
  _ as change_partner_dialog_desc_part2,
  _ as change_partner_dialog_desc_part3,
  _ as change_partner_dialog_submit,
  _ as change_partner_dialog_title,
  _ as change_partner_link,
  _ as default,
  _ as global_menu_change_language,
  _ as global_menu_language,
  _ as global_menu_sign_in,
  _ as global_menu_sign_out,
};
