var _ = `Okänd`,
  _ = `Amerikanska dollar`,
  _ = `Brittiska pund`,
  _ = `Euro`,
  _ = `Schweiziska franc`,
  _ = `Ryska rubler`,
  _ = `Polska zloty`,
  _ = `Brasilianska real`,
  _ = `Japanska yen`,
  _ = `Norska kronor`,
  _ = `Indonesiska rupier`,
  _ = `Malaysiska ringgit`,
  _ = `Filippinska peso`,
  _ = `Singaporianska dollar`,
  _ = `Thailändska baht`,
  _ = `Vietnamesiska dong`,
  _ = `Sydkoreanska won`,
  _ = `Turkiska lira`,
  _ = `Ukrainska hryvnia`,
  _ = `Mexikanska peso`,
  _ = `Kanadensiska dollar`,
  _ = `Australiska dollar`,
  _ = `Nyzeeländska dollar`,
  _ = `Kinesiska yuan`,
  _ = `Indiska rupier`,
  _ = `Chilenska peso`,
  _ = `Peruanska sol`,
  _ = `Colombianska peso`,
  _ = `Sydafrikanska rand`,
  _ = `Hongkongdollar`,
  _ = `Taiwanesiska dollar`,
  _ = `Saudiarabiska rial`,
  _ = `Emiratiska dirham`,
  _ = `Argentinska peso`,
  _ = `Israeliska nya shekel`,
  _ = `Kazakstanska tenge`,
  _ = `Kuwaitiska dinar`,
  _ = `Qatariska rial`,
  _ = `Costaricanska colón`,
  _ = `Uruguayanska peso`,
  _ = `Bulgariska lev`,
  _ = `Svenska kronor`,
  _ = `Kroatiska kuna`,
  _ = `Tjeckiska koruna`,
  _ = `Danska kronor`,
  _ = `Ungerska forint`,
  _ = `Rumänska leu`,
  _ = `Belarusiska rubel`,
  _ = `OSS-områden – visas för kunder i Armenien, Azerbajdzjan, Belarus, Kirgizistan, Tadzjikistan, Turkmenistan och Uzbekistan `,
  _ = `Länder i Sydasien – visas för kunder i Bangladesh, Bhutan, Nepal, Pakistan och Sri Lanka`,
  _ = `Länder i Latinamerika – visas för kunder i Argentina, Belize, Bolivia, Ecuador, El Salvador, Guyana, Guatemala, Honduras, Nicaragua, Panama, Paraguay, Surinam och Venezuela`,
  _ = `Länder i Mellanöstern och Nordafrika – visas för kunder i Algeriet, Bahrain, Egypten, Irak, Jemen, Jordanien, Libanon, Libyen, Marocko, Oman, Palestina, Sudan, Tunisien och Turkiet`,
  _ = `Inte fastställt`,
  _ = `dummy`,
  _ = {
    CurrencyCodeDescription_Unknown: _,
    CurrencyCodeDescription_USD: _,
    CurrencyCodeDescription_GBP: _,
    CurrencyCodeDescription_EUR: _,
    CurrencyCodeDescription_CHF: _,
    CurrencyCodeDescription_RUB: _,
    CurrencyCodeDescription_PLN: _,
    CurrencyCodeDescription_BRL: _,
    CurrencyCodeDescription_JPY: _,
    CurrencyCodeDescription_NOK: _,
    CurrencyCodeDescription_IDR: _,
    CurrencyCodeDescription_MYR: _,
    CurrencyCodeDescription_PHP: _,
    CurrencyCodeDescription_SGD: _,
    CurrencyCodeDescription_THB: _,
    CurrencyCodeDescription_VND: _,
    CurrencyCodeDescription_KRW: _,
    CurrencyCodeDescription_TRY: _,
    CurrencyCodeDescription_UAH: _,
    CurrencyCodeDescription_MXN: _,
    CurrencyCodeDescription_CAD: _,
    CurrencyCodeDescription_AUD: _,
    CurrencyCodeDescription_NZD: _,
    CurrencyCodeDescription_CNY: _,
    CurrencyCodeDescription_INR: _,
    CurrencyCodeDescription_CLP: _,
    CurrencyCodeDescription_PEN: _,
    CurrencyCodeDescription_COP: _,
    CurrencyCodeDescription_ZAR: _,
    CurrencyCodeDescription_HKD: _,
    CurrencyCodeDescription_TWD: _,
    CurrencyCodeDescription_SAR: _,
    CurrencyCodeDescription_AED: _,
    CurrencyCodeDescription_ARS: _,
    CurrencyCodeDescription_ILS: _,
    CurrencyCodeDescription_KZT: _,
    CurrencyCodeDescription_KWD: _,
    CurrencyCodeDescription_QAR: _,
    CurrencyCodeDescription_CRC: _,
    CurrencyCodeDescription_UYU: _,
    CurrencyCodeDescription_BGN: _,
    CurrencyCodeDescription_SEK: _,
    CurrencyCodeDescription_HRK: _,
    CurrencyCodeDescription_CZK: _,
    CurrencyCodeDescription_DKK: _,
    CurrencyCodeDescription_HUF: _,
    CurrencyCodeDescription_RON: _,
    CurrencyCodeDescription_BYN: _,
    Region_Pricing_Tooltip_CIS: _,
    Region_Pricing_Tooltip_SASIA: _,
    Region_Pricing_Tooltip_LATAM: _,
    Region_Pricing_Tooltip_MENA: _,
    Region_Pricing_Tooltip_Unknown: _,
    dummy: _,
  };
export {
  _ as CurrencyCodeDescription_AED,
  _ as CurrencyCodeDescription_ARS,
  _ as CurrencyCodeDescription_AUD,
  _ as CurrencyCodeDescription_BGN,
  _ as CurrencyCodeDescription_BRL,
  _ as CurrencyCodeDescription_BYN,
  _ as CurrencyCodeDescription_CAD,
  _ as CurrencyCodeDescription_CHF,
  _ as CurrencyCodeDescription_CLP,
  _ as CurrencyCodeDescription_CNY,
  _ as CurrencyCodeDescription_COP,
  _ as CurrencyCodeDescription_CRC,
  _ as CurrencyCodeDescription_CZK,
  _ as CurrencyCodeDescription_DKK,
  _ as CurrencyCodeDescription_EUR,
  _ as CurrencyCodeDescription_GBP,
  _ as CurrencyCodeDescription_HKD,
  _ as CurrencyCodeDescription_HRK,
  _ as CurrencyCodeDescription_HUF,
  _ as CurrencyCodeDescription_IDR,
  _ as CurrencyCodeDescription_ILS,
  _ as CurrencyCodeDescription_INR,
  _ as CurrencyCodeDescription_JPY,
  _ as CurrencyCodeDescription_KRW,
  _ as CurrencyCodeDescription_KWD,
  _ as CurrencyCodeDescription_KZT,
  _ as CurrencyCodeDescription_MXN,
  _ as CurrencyCodeDescription_MYR,
  _ as CurrencyCodeDescription_NOK,
  _ as CurrencyCodeDescription_NZD,
  _ as CurrencyCodeDescription_PEN,
  _ as CurrencyCodeDescription_PHP,
  _ as CurrencyCodeDescription_PLN,
  _ as CurrencyCodeDescription_QAR,
  _ as CurrencyCodeDescription_RON,
  _ as CurrencyCodeDescription_RUB,
  _ as CurrencyCodeDescription_SAR,
  _ as CurrencyCodeDescription_SEK,
  _ as CurrencyCodeDescription_SGD,
  _ as CurrencyCodeDescription_THB,
  _ as CurrencyCodeDescription_TRY,
  _ as CurrencyCodeDescription_TWD,
  _ as CurrencyCodeDescription_UAH,
  _ as CurrencyCodeDescription_USD,
  _ as CurrencyCodeDescription_UYU,
  _ as CurrencyCodeDescription_Unknown,
  _ as CurrencyCodeDescription_VND,
  _ as CurrencyCodeDescription_ZAR,
  _ as Region_Pricing_Tooltip_CIS,
  _ as Region_Pricing_Tooltip_LATAM,
  _ as Region_Pricing_Tooltip_MENA,
  _ as Region_Pricing_Tooltip_SASIA,
  _ as Region_Pricing_Tooltip_Unknown,
  _ as default,
  _ as dummy,
};
