var _ = `Vyberte níže cenu v USD`,
  _ = `Bezplatný`,
  _ = `Konvertovat na bezplatný...`,
  _ = `Tento balík bude pro zákazníky aktualizován na bezplatný.`,
  _ = `Tento balík může na bezplatný konvertovat pouze zaměstnanec podpory služby Steam. Využijte proto odkazu „Kontaktovat vydavatelské oddělení služby Steam“ v sekci „Dokumentace a nápověda“.`,
  _ = `Konvertovat balík na bezplatný?`,
  _ = `Tato akce změní balík na bezplatný, označí aplikaci tak, aby se mohla zobrazit v centru Free to play, a také změní zobrazení ceny na stránce v obchodu na text určený níže. Tuto akci nelze vzít zpět bez kontaktování podpory služby Steam.`,
  _ = `Tento balík může na bezplatný konvertovat pouze zaměstnanec podpory služby Steam. Kliknutím níže tedy vytvořte žádost na podporu.`,
  _ = `Vyberte text, který se má zobrazit místo ceny:`,
  _ = `„Free to play“ – Hra je zdarma ke stažení a hraní, ale zahrnuje volitelné nákupy (položky, měna, DLC nebo jiná forma monetizace).`,
  _ = `„Zdarma“ – Hra je zdarma ke stažení a hraní a nezahrnuje žádné nákupy ve hře ani placený obsah.`,
  _ = `Konvertovat na bezplatný`,
  _ = `Aktualizování stránky hry v obchodu, aby byla zahrnuta mezi bezplatnými. Vyžaduje zveřejnění změn stránky v obchodu.`,
  _ = `Konvertování balíku na bezplatný`,
  _ = `Konverze balíku na bezplatný byla úspěšná. Po zavření tohoto dialogového okna dojde k obnovení stránky.`,
  _ = `Nepodařilo se aktualizovat stránku aplikace v obchodu: %1$s`,
  _ = `Nepodařilo se změnit typ balíku: %1$s`,
  _ = `Metoda převodu (%1$s)`,
  _ = `Podrobnosti`,
  _ = `Z rozbalovací nabídky níže vyberte cenu, za jakou byste chtěli svůj produkt prodávat. Pro jakoukoli základní cenu Vám tento nástroj navrhne vhodnou regionální cenu založenou na informacích o prodejích titulů v podobné cenové kategorii. Mějte na vědomí, že pro některé země budou doporučené převody již zahrnovat DPH/GST/JCT, tedy daň z přidané hodnoty vybíranou daňovým úřadem příslušné země. Seznam zemí vybírajících DPH naleznete zde:`,
  _ = `Než ceny uložíte, znovu o nich popřemýšlejte a dvakrát je po sobě zkontrolujte, a to VE VŠECH MĚNÁCH. Navíc z rozličných důvodů našim partnerům nedoporučujeme, aby ceny svých produktů měnili během několika týdnů po jejich vydání. V případě nutnosti můžete zadat novou cenu před vydáním, avšak jakmile produkt vyjde, cenu už nezměníte. Pro více informací si přečtěte %1$s.`,
  _ = `dokumentaci zaměřenou na cenění a slevy`,
  _ = `Jakmile budete se svou cenou spokojeni, klikněte na tlačítko „Uložit“, pomocí kterého budou údaje odeslány společnosti Valve pro zpracování.`,
  _ = `Upravit v hromadném cenění`,
  _ = `Umožňuje upravit cenu tohoto balíku v nástroji pro hromadné cenění.`,
  _ = `Nápověda a pokyny`,
  _ = `Hledáte pomoc s oceněním svého titulu? Níže naleznete odkaz, který Vás vezme na stránku s užitečnými tipy a pokyny.`,
  _ = `Dokumentace pro cenění`,
  _ = `Časté dotazy`,
  _ = `Přecházíte na bezplatnou verzi?`,
  _ = `Pokud byla Vaše aplikace již vydána a Vy ji nyní chcete změnit z placené na bezplatnou, navštivte %1$s, kde se dozvíte více informací a budete moci zažádat o pomoc.`,
  _ = `tuto stránku`,
  _ = `Zadání vlastních cen`,
  _ = `Přímo do textových polí můžete zadat své vlastní ceny pro jednotlivé měny.`,
  _ = `Případně můžete použít toto tlačítko, které ceny pro jednotlivé měny vypočte na základě vybrané metody převodu a zadané vlastní ceny v USD.`,
  _ = `Cenová hladina`,
  _ = `Vyberte základní cenu v USD`,
  _ = `Otevře dialogové okno se seznamem častých cenových hladin a umožní jejich nastavení napříč všemi měnami níže.`,
  _ = `Převod s více proměnnými`,
  _ = `Převod pouze podle kupní síly`,
  _ = `Převod pouze podle směnného kurzu`,
  _ = `Poslední aktualizace:`,
  _ = `Metody převodu využívají veřejně dostupná data k lednu 2026.`,
  _ = `Jsou dostupné nové metody převodu`,
  _ = `Abychom Vám pomohli se správou cen napříč 37 různými měnami a 4 specifickými regiony, nabízíme několik rozdílných metod pro převod z Vaší základní ceny.`,
  _ = `Tento nástroj slouží pro zjednodušení procesu a doporučení cen – finální ceny jsou a vždy budou čistě na Vás.`,
  _ = `Chcete-li se dozvědět více o jednotlivých metodách, navštivte %1$s nebo výše klikněte na „Podrobnosti“.`,
  _ = `stránku zaměřenou na metody převodu`,
  _ = `Použít ceny dle metody převodu`,
  _ = `Abychom Vám pomohli se správou cen napříč 35 a více podporovanými měnami, nabízí tento nástroj volitelné metody převodu základní ceny v USD na ceny vhodné pro jednotlivé regiony.`,
  _ = `Vyberte níže cenu, abyste ji nastavili pro USD a použili převedené ceny pro všechny ostatní měny. Převod je založen na metodě vybrané výše.`,
  _ = `Ceny můžete zadat jednotlivě pro každou podporovanou měnu, nebo použít jednu z metod převodu služby Steam a převést cenu v USD do všech ostatních měn.`,
  _ = `Metody převodu pak lze použít dvěma způsoby:`,
  _ = `Vyberte z rozbalovací nabídky cenových hladin níže jednu z častých cen v USD a služba Steam na základě vybrané metody převodu vyplní ceny v ostatních měnách.`,
  _ = `Pokud chcete použít méně častou cenu v USD, zadejte ji do příslušného pole, klikněte na tlačítko „Převést ceny...“ a postupujte podle pokynů.`,
  _ = `Navrhovaná cena:`,
  _ = `Tato cena je navržena na základě metody převodu vybrané výše a ceny %1$s USD.`,
  _ = `dummy`,
  _ = ``,
  _ = {
    PricingGuideline_Default: _,
    FreeOnDemand_InlineOption: _,
    FreeOnDemand_Button: _,
    FreeOnDemand_Button_ttip: _,
    FreeOnDemand_Button_disabled_ttip: _,
    FreeOnDemand_Title: _,
    FreeOnDemand_Desc: _,
    FreeOnDemand_Desc_NotPermitted: _,
    FreeOnDemand_Radio: _,
    FreeOnDemand_Radio_FreeToPlay: _,
    FreeOnDemand_Radio_Free: _,
    FreeOnDemand_Button_Confirm: _,
    FreeOnDemand_Convert_Store: _,
    FreeOnDemand_Convert_Package: _,
    FreeOnDemand_ConvertSuccess: _,
    FreeOnDemand_Store_Error: _,
    FreeOnDemand_Package_Error: _,
    ConversionMethod_Title: _,
    ConversionMethod_Link: _,
    SinglePricingPackage_Desc_1: _,
    SinglePricingPackage_Desc_2: _,
    SinglePricingPackage_Desc_2_Link: _,
    SinglePricingPackage_Desc_3: _,
    SinglePackagePricing_Right_Edit: _,
    SinglePackagePricing_Right_Edit_desc: _,
    SinglePackagePricing_Right_Help_Title: _,
    SinglePackagePricing_Right_Help_Desc: _,
    SinglePackagePricing_Right_Link: _,
    SinglePackagePricing_Right_FAQ: _,
    SinglePackagePricing_Right_FAQ_switching: _,
    SinglePackagePricing_Right_FAQ_switching_answer: _,
    SinglePackagePricing_Right_FAQ_switching_answer_link: _,
    SinglePackagePricing_Right_Convert_Title: _,
    SinglePackagePricing_Right_Custom_Desc: _,
    SinglePackagePricing_Right_Convert_Desc: _,
    PricingDashboard_Select_Price: _,
    PricingDashboard_Select_Price_button: _,
    PricingDashboard_Select_Price_button_ttip: _,
    ConversionMethod_Nuanced: _,
    ConversionMethod_PPP: _,
    ConversionMethod_FX: _,
    PricingExplorer_Time_Title: _,
    PricingExplorer_Time_Disc: _,
    Tour_ConversionMethod_Title: _,
    Tour_ConversionMethod_Desc1: _,
    Tour_ConversionMethod_Desc2: _,
    Tour_ConversionMethod_Desc3: _,
    Tour_ConversionMethod_Link: _,
    PricingDashboard_ApplyConversion_Method: _,
    PricingDashboard_ApplyGuidelines_Instructions_MultiOptions: _,
    PricingDashboard_GuidelinesPickerDescription_New: _,
    SinglePricingPackage_Intro_1: _,
    SinglePricingPackage_Intro_2: _,
    SinglePricingPackage_Intro_2a: _,
    SinglePricingPackage_Intro_2b: _,
    PricingDashboard_Method_SuggestedPrice: _,
    PricingDashboard_Method_SuggestedPrice_ttip: _,
    dummy: _,
    empty_no_trailing_comma: ``,
  };
export {
  _ as ConversionMethod_FX,
  _ as ConversionMethod_Link,
  _ as ConversionMethod_Nuanced,
  _ as ConversionMethod_PPP,
  _ as ConversionMethod_Title,
  _ as FreeOnDemand_Button,
  _ as FreeOnDemand_Button_Confirm,
  _ as FreeOnDemand_Button_disabled_ttip,
  _ as FreeOnDemand_Button_ttip,
  _ as FreeOnDemand_ConvertSuccess,
  _ as FreeOnDemand_Convert_Package,
  _ as FreeOnDemand_Convert_Store,
  _ as FreeOnDemand_Desc,
  _ as FreeOnDemand_Desc_NotPermitted,
  _ as FreeOnDemand_InlineOption,
  _ as FreeOnDemand_Package_Error,
  _ as FreeOnDemand_Radio,
  _ as FreeOnDemand_Radio_Free,
  _ as FreeOnDemand_Radio_FreeToPlay,
  _ as FreeOnDemand_Store_Error,
  _ as FreeOnDemand_Title,
  _ as PricingDashboard_ApplyConversion_Method,
  _ as PricingDashboard_ApplyGuidelines_Instructions_MultiOptions,
  _ as PricingDashboard_GuidelinesPickerDescription_New,
  _ as PricingDashboard_Method_SuggestedPrice,
  _ as PricingDashboard_Method_SuggestedPrice_ttip,
  _ as PricingDashboard_Select_Price,
  _ as PricingDashboard_Select_Price_button,
  _ as PricingDashboard_Select_Price_button_ttip,
  _ as PricingExplorer_Time_Disc,
  _ as PricingExplorer_Time_Title,
  _ as PricingGuideline_Default,
  _ as SinglePackagePricing_Right_Convert_Desc,
  _ as SinglePackagePricing_Right_Convert_Title,
  _ as SinglePackagePricing_Right_Custom_Desc,
  _ as SinglePackagePricing_Right_Edit,
  _ as SinglePackagePricing_Right_Edit_desc,
  _ as SinglePackagePricing_Right_FAQ,
  _ as SinglePackagePricing_Right_FAQ_switching,
  _ as SinglePackagePricing_Right_FAQ_switching_answer,
  _ as SinglePackagePricing_Right_FAQ_switching_answer_link,
  _ as SinglePackagePricing_Right_Help_Desc,
  _ as SinglePackagePricing_Right_Help_Title,
  _ as SinglePackagePricing_Right_Link,
  _ as SinglePricingPackage_Desc_1,
  _ as SinglePricingPackage_Desc_2,
  _ as SinglePricingPackage_Desc_2_Link,
  _ as SinglePricingPackage_Desc_3,
  _ as SinglePricingPackage_Intro_1,
  _ as SinglePricingPackage_Intro_2,
  _ as SinglePricingPackage_Intro_2a,
  _ as SinglePricingPackage_Intro_2b,
  _ as Tour_ConversionMethod_Desc1,
  _ as Tour_ConversionMethod_Desc2,
  _ as Tour_ConversionMethod_Desc3,
  _ as Tour_ConversionMethod_Link,
  _ as Tour_ConversionMethod_Title,
  _ as default,
  _ as dummy,
  _ as empty_no_trailing_comma,
};
