var _ = `حدد السعر بالدولار الأمريكي من القائمة أدناه`,
  _ = `مجانية`,
  _ = `تعيين كمنتج مجاني...`,
  _ = `تحديث هذه الحزمة لتصبح مجانية للمستهلكين`,
  _ = `لا يمكن تحويل هذه الحزمة إلى مجانية إلا من خلال أحد ممثلي دعم Steam. يُرجى استخدام رابط "التواصل مع قسم نشر Steam" ضمن قسم "الوثائق والمساعدة" للحصول على الدعم.`,
  _ = `هل تريد تحويل الحزمة إلى مجانية؟`,
  _ = `سيؤدي هذا الإجراء إلى جعل الحزمة مجانية، وإضافة تطبيقك في مركز الألعاب المجانية، وتغيير طريقة عرض السعر بناءً على المصطلح الذي تختاره أدناه. علمًا بأن هذا التغيير لا يمكن التراجع عنه إلا عبر إرسال تذكرة إلى فريق دعم Steamworks.`,
  _ = `لا يمكن تحويل هذه الحزمة إلى مجانية إلا من خلال أحد ممثلي دعم Steam. انقر أدناه لإنشاء تذكرة دعم تتضمن تفاصيل طلبك.`,
  _ = `اختر النص المناسب لعرضه بدلًا من السعر:`,
  _ = `"مجانية للعب" - اللعبة مجانية للتحميل واللعب، ولكنها تتضمن عمليات شراء اختيارية داخل اللعبة (عناصر أو عملات أو DLC أو أساليب ربحية أخرى).`,
  _ = `"مجانية" - اللعبة مجانية بالكامل للتنزيل واللعب، ولا تحتوي على أي مشتريات داخل اللعبة أو محتويات مدفوعة.`,
  _ = `تحويل المنتج إلى مجاني`,
  _ = `تحديث صفحة متجر اللعبة لإدراجها ضمن فئة الألعاب المجانية. يتطلب الأمر نشر تغييرات المتجر.`,
  _ = `جارٍ تحويل الحزمة إلى مجانية`,
  _ = `تم التحويل إلى مجانية بنجاح. ستُعاد تحميل الصفحة عند إغلاق النافذة.`,
  _ = `تعذر تحديث صفحة التطبيق في المتجر: %1$s`,
  _ = `تعذر تغيير نوع الحزمة: %1$s`,
  _ = `طريقة التحويل (%1$s)`,
  _ = `عرض التفاصيل`,
  _ = `يُرجى اختيار السعر الذي ترغب في بيع منتجك به من القائمة المنسدلة أدناه. وبناءً على السعر الأساسي الذي تحدده، ستقترح هذه الأداة الأسعار الإقليمية المناسبة استنادًا إلى خبرتنا مع ألعاب أخرى في فئات سعرية مماثلة. يُرجى الملاحظة أن أسعار التحويل الموصى بها لبعض البلدان تشمل ضريبة القيمة المضافة وضريبة السلع والخدمات وضريبة الاستهلاك اليابانية. وتُعد هذه الضرائب ضرائب على القيمة المضافة، وهي مشابهة لضريبة المبيعات وتفرضها السلطات الضريبية. وفي الدول التي تشترط القوانين المعمول بها فرض ضريبة القيمة المضافة، فإنها تُحتسب ضمن الأسعار المعروضة ويتم تحصيلها عند الشراء من الدول المعنية. يمكن العثور على قائمة بالبلدان التي تُحصّل فيها ضريبة القيمة المضافة هنا:`,
  _ = `تأكد من التحقق من الأسعار بجميع العملات والتفكير مليًا في استراتيجية تسعير منتجك قبل المتابعة. ننصح الشركاء بعدم تغيير الأسعار خلال الأسابيع الأولى من إصدار اللعبة لأسباب متعددة. يمكنك تقديم طلب تسعير جديد قبل الإصدار إذا لزم الأمر، أما بعد توفر المنتج للجمهور، ستظل الأسعار كما هي دون تعديل. اطّلع على %1$s لمعرفة المزيد.`,
  _ = `وثائق التسعير والخصومات`,
  _ = `فور اعتمادك للسعر المناسب، اضغط على زر الحفظ لإرساله إلى فريق Valve بغرض التدقيق والاعتماد.`,
  _ = `التعديل من صفحة التسعير الشامل`,
  _ = `تعديل تسعير هذه الحزمة باستخدام أداة التسعير الشامل`,
  _ = `الدعم والإرشادات`,
  _ = `هل تحتاج إلى مساعدة أو اقتراحات لتسعير منتجك؟ ستجد في الأسفل رابطًا يتضمن بعض المعايير والإرشادات الشائعة.`,
  _ = `دليل التسعير`,
  _ = `الأسئلة الشائعة`,
  _ = `هل تود تحويل المنتج إلى مجاني؟`,
  _ = `إذا كانت لعبتك قد صدرت بالفعل وترغب في تحويلها من مدفوعة إلى مجانية، فانقر على %1$s لمعرفة المزيد وطلب المساعدة.`,
  _ = `هنا`,
  _ = `تعيين أسعار مخصصة`,
  _ = `يمكنك تحديد السعر الذي تراه مناسبًا لكل عملة عن طريق تعديل خانة النص المخصصة بشكل مباشر.`,
  _ = `يمكنك أيضًا استخدام هذا الزر لحساب قيمة كل عملة بناءً على طريقة التحويل المحددة وقيمة الدولار الأمريكي المخصصة التي أدخلتها.`,
  _ = `اختر من فئات التسعير`,
  _ = `حدد السعر الأساسي بالدولار الأمريكي`,
  _ = `افتح نافذة تتضمن مجموعة من فئات الأسعار الشائعة لتطبيقها على جميع العملات الموضحة أدناه.`,
  _ = `التحويل وفق عوامل متعددة`,
  _ = `التحويل وفق القوة الشرائية فقط`,
  _ = `التحويل وفق سعر الصرف فقط`,
  _ = `التحديث الأخير:`,
  _ = `صُممت طرق التحويل استنادًا إلى البيانات العامة الصادرة في يناير، 2026`,
  _ = `توفر طرق تحويل جديدة`,
  _ = `لمساعدتك في تسعير لعبتك بـ37 عملة مختلفة وعبر 4 مجموعات إقليمية، يوفر Steam الآن عدة طرق لتحويل السعر الأساسي الذي تختاره إلى أسعار مناسبة لكل منطقة`,
  _ = `لك الحرية المطلقة في اختيار الأسعار، حيث تقتصر وظيفة هذه الأدوات على تيسير عملية التسعير متى شئت الاعتماد عليها.`,
  _ = `يُرجى زيارة %1$s أو النقر على "عرض التفاصيل" أعلاه لمعرفة المزيد عن طرق التحويل المختلفة المتاحة.`,
  _ = `صفحة تفاصيل طريقة التحويل`,
  _ = `اعتماد الأسعار الناتجة عن طريقة التحويل`,
  _ = `لمساعدتك في تسعير منتجك بما يزيد على 35 عملة يدعمها Steam، توفر هذه الأداة طرق تحويل اختيارية لتحويل السعر الأساسي بالدولار الأمريكي إلى أسعار مناسبة لكل منطقة.`,
  _ = `اختر قيمة سعرية أدناه لتعيين السعر الأساسي بالدولار الأمريكي، وتطبيق الأسعار المعادِلة تلقائيًا على بقية العملات، بناءً على طريقة التحويل المحددة أعلاه.`,
  _ = `يمكنك تحديد الأسعار لكل عملة مدعومة على حدة، أو استخدام إحدى طرق التحويل التي يوفرها Steam لتحويل سعر الدولار الأمريكي إلى جميع العملات الأخرى.`,
  _ = `ثمة أسلوبان لاستخدام طرق التحويل المتاحة على Steam:`,
  _ = `اختر سعرًا شائعًا بالدولار الأمريكي من القائمة المنسدلة لفئات الأسعار أدناه، ليتولى Steam تحديث بقية العملات تلقائيًا وفقًا لطريقة التحويل المختارة.`,
  _ = `بالنسبة للأسعار غير الشائعة بالدولار الأمريكي، اكتب القيمة في خانة السعر بالدولار الأمريكي، ثم اضغط على زر "تحويل الأسعار..." واتبع التعليمات.`,
  _ = `سعر التحويل المقترح:`,
  _ = `هذا السعر مقترح بناءً على طريقة التحويل المحددة أعلاه وقيمة دولار أمريكي تعادل %1$s.`,
  _ = `تجريبي`,
  _ = {
    PricingGuideline_Default: _,
    FreeOnDemand_InlineOption: _,
    FreeOnDemand_Button: _,
    FreeOnDemand_Button_ttip: _,
    FreeOnDemand_Button_disabled_ttip: _,
    FreeOnDemand_Title: _,
    FreeOnDemand_Desc: _,
    FreeOnDemand_Desc_NotPermitted: _,
    FreeOnDemand_Radio: _,
    FreeOnDemand_Radio_FreeToPlay: _,
    FreeOnDemand_Radio_Free: _,
    FreeOnDemand_Button_Confirm: _,
    FreeOnDemand_Convert_Store: _,
    FreeOnDemand_Convert_Package: _,
    FreeOnDemand_ConvertSuccess: _,
    FreeOnDemand_Store_Error: _,
    FreeOnDemand_Package_Error: _,
    ConversionMethod_Title: _,
    ConversionMethod_Link: _,
    SinglePricingPackage_Desc_1: _,
    SinglePricingPackage_Desc_2: _,
    SinglePricingPackage_Desc_2_Link: _,
    SinglePricingPackage_Desc_3: _,
    SinglePackagePricing_Right_Edit: _,
    SinglePackagePricing_Right_Edit_desc: _,
    SinglePackagePricing_Right_Help_Title: _,
    SinglePackagePricing_Right_Help_Desc: _,
    SinglePackagePricing_Right_Link: _,
    SinglePackagePricing_Right_FAQ: _,
    SinglePackagePricing_Right_FAQ_switching: _,
    SinglePackagePricing_Right_FAQ_switching_answer: _,
    SinglePackagePricing_Right_FAQ_switching_answer_link: _,
    SinglePackagePricing_Right_Convert_Title: _,
    SinglePackagePricing_Right_Custom_Desc: _,
    SinglePackagePricing_Right_Convert_Desc: _,
    PricingDashboard_Select_Price: _,
    PricingDashboard_Select_Price_button: _,
    PricingDashboard_Select_Price_button_ttip: _,
    ConversionMethod_Nuanced: _,
    ConversionMethod_PPP: _,
    ConversionMethod_FX: _,
    PricingExplorer_Time_Title: _,
    PricingExplorer_Time_Disc: _,
    Tour_ConversionMethod_Title: _,
    Tour_ConversionMethod_Desc1: _,
    Tour_ConversionMethod_Desc2: _,
    Tour_ConversionMethod_Desc3: _,
    Tour_ConversionMethod_Link: _,
    PricingDashboard_ApplyConversion_Method: _,
    PricingDashboard_ApplyGuidelines_Instructions_MultiOptions: _,
    PricingDashboard_GuidelinesPickerDescription_New: _,
    SinglePricingPackage_Intro_1: _,
    SinglePricingPackage_Intro_2: _,
    SinglePricingPackage_Intro_2a: _,
    SinglePricingPackage_Intro_2b: _,
    PricingDashboard_Method_SuggestedPrice: _,
    PricingDashboard_Method_SuggestedPrice_ttip: _,
    dummy: _,
  };
export {
  _ as ConversionMethod_FX,
  _ as ConversionMethod_Link,
  _ as ConversionMethod_Nuanced,
  _ as ConversionMethod_PPP,
  _ as ConversionMethod_Title,
  _ as FreeOnDemand_Button,
  _ as FreeOnDemand_Button_Confirm,
  _ as FreeOnDemand_Button_disabled_ttip,
  _ as FreeOnDemand_Button_ttip,
  _ as FreeOnDemand_ConvertSuccess,
  _ as FreeOnDemand_Convert_Package,
  _ as FreeOnDemand_Convert_Store,
  _ as FreeOnDemand_Desc,
  _ as FreeOnDemand_Desc_NotPermitted,
  _ as FreeOnDemand_InlineOption,
  _ as FreeOnDemand_Package_Error,
  _ as FreeOnDemand_Radio,
  _ as FreeOnDemand_Radio_Free,
  _ as FreeOnDemand_Radio_FreeToPlay,
  _ as FreeOnDemand_Store_Error,
  _ as FreeOnDemand_Title,
  _ as PricingDashboard_ApplyConversion_Method,
  _ as PricingDashboard_ApplyGuidelines_Instructions_MultiOptions,
  _ as PricingDashboard_GuidelinesPickerDescription_New,
  _ as PricingDashboard_Method_SuggestedPrice,
  _ as PricingDashboard_Method_SuggestedPrice_ttip,
  _ as PricingDashboard_Select_Price,
  _ as PricingDashboard_Select_Price_button,
  _ as PricingDashboard_Select_Price_button_ttip,
  _ as PricingExplorer_Time_Disc,
  _ as PricingExplorer_Time_Title,
  _ as PricingGuideline_Default,
  _ as SinglePackagePricing_Right_Convert_Desc,
  _ as SinglePackagePricing_Right_Convert_Title,
  _ as SinglePackagePricing_Right_Custom_Desc,
  _ as SinglePackagePricing_Right_Edit,
  _ as SinglePackagePricing_Right_Edit_desc,
  _ as SinglePackagePricing_Right_FAQ,
  _ as SinglePackagePricing_Right_FAQ_switching,
  _ as SinglePackagePricing_Right_FAQ_switching_answer,
  _ as SinglePackagePricing_Right_FAQ_switching_answer_link,
  _ as SinglePackagePricing_Right_Help_Desc,
  _ as SinglePackagePricing_Right_Help_Title,
  _ as SinglePackagePricing_Right_Link,
  _ as SinglePricingPackage_Desc_1,
  _ as SinglePricingPackage_Desc_2,
  _ as SinglePricingPackage_Desc_2_Link,
  _ as SinglePricingPackage_Desc_3,
  _ as SinglePricingPackage_Intro_1,
  _ as SinglePricingPackage_Intro_2,
  _ as SinglePricingPackage_Intro_2a,
  _ as SinglePricingPackage_Intro_2b,
  _ as Tour_ConversionMethod_Desc1,
  _ as Tour_ConversionMethod_Desc2,
  _ as Tour_ConversionMethod_Desc3,
  _ as Tour_ConversionMethod_Link,
  _ as Tour_ConversionMethod_Title,
  _ as default,
  _ as dummy,
};
