var _ = `Información confidencial de Valve`,
  _ = `Esta página con acceso restringido contiene información confidencial de Valve. Debes tener un acuerdo de licencia o de confidencialidad con Valve que cubra dicha información para poder utilizar o acceder a esta página.`,
  _ = `Steamworks es el grupo de herramientas y servicios diseñados por <1>Valve</1> que te ayudarán a configurar, administrar y operar tu juego en <2>Steam</2>.`,
  _ = `Contactar al equipo de Soporte`,
  _ = `Error al cargar la información de precios, inténtalo de nuevo más tarde.`,
  _ = `Acerca de los precios regionales`,
  _ = `El precio de cada producto en Steam se especifica y muestra utilizando %1$s diferentes monedas y %2$s <1>regiones</1>. Steam ofrece herramientas que te ayudan a establecer y administrar el precio de tu juego a niveles adecuados para cada Mercado.`,
  _ = `Los precios que ingreses para tu juego en cada moneda y región dependen de ti.`,
  _ = `Para obtener más detalles sobre cómo fijar tu precio, consulta %1$s`,
  _ = `Documentación sobre fijación de precios`,
  _ = `Para fijar los precios de tu juego, ve a tu %1$s`,
  _ = `Visitar el menú principal de fijación de precios`,
  _ = `Para administrar la fijación de precios de tu juego, ve a tu panel de fijación de precios.`,
  _ = `Conversiones de moneda actualizadas por última vez el %1$s`,
  _ = `Herramienta de exploración de conversión de precios`,
  _ = `Esta herramienta muestra cómo funcionan tres métodos de conversión de precios y monedas:`,
  _ = `%1$s: Este método toma en cuenta varios factores para cada moneda, incluyendo el poder adquisitivo local, el costo esperado de bienes de entretenimiento comparables y la tasa de cambio.`,
  _ = `%1$s: Este método utiliza datos públicos sobre el poder adquisitivo de clientes dentro de un país o región determinados.`,
  _ = `%1$s: Este método utiliza una tasa de cambio de moneda simple en el momento indicado.`,
  _ = `Moneda base`,
  _ = `Precio base`,
  _ = `Método de conversión`,
  _ = `Moneda`,
  _ = `Conversión de variables múltiples`,
  _ = `Solo conversión basada en el poder adquisitivo`,
  _ = `Solo conversión basada en el tipo de cambio`,
  _ = `Precios específicos por región (todos presentados en dólares estadounidenses)`,
  _ = `Región`,
  _ = `prueba`,
  _ = `%1$s (%2$s) - Encuesta sobre contenido`,
  _ = `Encuesta sobre contenido`,
  _ = `%1$s (%2$s) - Encuestas sobre contenido`,
  _ = `Encuestas sobre contenido`,
  _ = `No hay una aplicación con este id. Verifica la dirección y vuelve a intentarlo.`,
  _ = `Permiso denegado`,
  _ = `No has iniciado sesión`,
  _ = `Proyecto SteamLearn`,
  _ = `Sin determinar`,
  _ = `Resumen`,
  _ = `Esta es una lista completa de las pruebas realizadas durante esta revisión, incluyendo sus resultados abajo.`,
  _ = `A continuación se presenta un resumen de las pruebas individuales y las clasificaciones de compatibilidad resultantes.`,
  _ = `A continuación se indican los resultados de las pruebas que determinan que este título es "Jugable".`,
  _ = `Propiedad`,
  _ = `Valor`,
  _ = `Descripción`,
  _ = `Esta es una vista previa de cómo verán los jugadores tu juego en la tienda. La presentación en la tienda puede cambiar en el futuro.`,
  _ = `Informes anteriores`,
  _ = `Resultados de las pruebas`,
  _ = `Resultado`,
  _ = `Prueba`,
  _ = `Comentarios`,
  _ = `Impacto en la clasificación`,
  _ = `Aprobada`,
  _ = `No aprobada`,
  _ = `No aprobada`,
  _ = `---`,
  _ = `Este es un informe histórico de %1$s`,
  _ = `Estás viendo el informe publicado`,
  _ = `Publicada: %1$s`,
  _ = `Notificada el: %1$s`,
  _ = `Ver documentación`,
  _ = `Publicar estos resultados`,
  _ = `¿Quieres publicar los resultados de compatibilidad?`,
  _ = `¿Estás seguro de que quieres publicar estos resultados? Estarán inmediatamente visibles en la tienda de Steam.`,
  _ = `Error desconocido. Inténtalo de nuevo`,
  _ = `Solicitud de prueba`,
  _ = `La solicitud está activa`,
  _ = `La solicitud está cerrada`,
  _ = `Ver detalles de la solicitud`,
  _ = `Discute este informe con el equipo de pruebas`,
  _ = `Escribe tus preguntas o comentarios aquí`,
  _ = `Describe aquí los cambios en tu nueva compilación.`,
  _ = `Si la compilación de tu juego en Steam se actualizó para solucionar los problemas indicados más arriba, selecciona una rama y vuelve a enviarla para su revisión.`,
  _ = `Selecciona una rama y envíala para una nueva revisión de compatibilidad con Steam\xA0Deck, la cual incluirá pruebas en Steam\xA0Machine.`,
  _ = `Enviar para una nueva revisión`,
  _ = `Si has hecho cambios en la compilación de tu juego después de la revisión anterior, puedes solicitar una nueva revisión de compatibilidad.`,
  _ = `Describe el motivo de tu solicitud para volver a revisar a continuación. Las razones comunes para una nueva revisión incluyen:`,
  _ = `Has hecho cambios en tu compilación para resolver las pruebas no aprobadas de una revisión de compatibilidad anterior. Describe los problemas específicos que crees haber resuelto.`,
  _ = `Enviaste, o enviarás, una nueva versión de tu juego, y quieres que se actualice el informe.`,
  _ = `Solicito una nueva prueba utilizando la rama "%1$s". La compilación del juego en Steam se actualizó para solucionar los problemas notificados.`,
  _ = `Historial de pruebas`,
  _ = `Presentación en la tienda`,
  _ = `Compatibilidad con el hardware: %1$s (%2$s)`,
  _ = `Publicada`,
  _ = `No publicada`,
  _ = `Historial`,
  _ = `Tiempo de ejecución recomendado`,
  _ = `Esta es la versión de tu juego (contenido/ejecutables) que se entregará a los clientes y que estos ejecutarán de manera predeterminada en Steam Deck.`,
  _ = `Formato de entrada esperado`,
  _ = `Requiere H.264`,
  _ = `Versión de Proton probada`,
  _ = `Id. de compilación de pruebas`,
  _ = `Depuración de RPO`,
  _ = `Depuración de FDM`,
  _ = `Activar TSO`,
  _ = `Tu juego se clasificó como "Desconocido" en %1$s porque las pruebas con dicho dispositivo están incompletas`,
  _ = `Tu juego no es compatible con %1$s en este momento`,
  _ = `Tu juego no es totalmente compatible con %1$s debido a ciertos problemas con Proton o el propio sistema de %1$s. Hemos tomado nota de estos problemas para intentar solucionarlos. Mientras tanto, tu juego no se iniciará ni se ejecutará correctamente en %1$s.`,
  _ = `Tu juego es "Jugable" en %1$s`,
  _ = `Tu juego se puede jugar en %1$s, pero los clientes deberán hacer un esfuerzo adicional para interactuar con él o configurarlo. Puedes corregir los problemas que se mencionan a continuación y volver a solicitar la revisión de compatibilidad.`,
  _ = `¡Tu juego está "Verificado en %1$s"!`,
  _ = `¡Felicidades! Tu juego funciona perfectamente en %1$s y aparecerá destacado como tal en la tienda de Steam y en las bibliotecas de Steam de los jugadores.`,
  _ = `¿Quieres compartir este objetivo con tus fans? Este enlace te llevará a una sofisticada página inicial que puedes utilizar: %1$s`,
  _ = `Tu juego no se ha probado en Steam Machine`,
  _ = `Tu juego no se ha probado en Steam Frame`,
  _ = `Esto hace que tu clasificación sea "Jugable".`,
  _ = `Esto hace que tu clasificación sea "No compatible".`,
  _ = `Esto aparece como un mensaje informativo para los clientes`,
  _ = `No válida`,
  _ = `Iniciar lanzador`,
  _ = `Lanzador`,
  _ = `Control del lanzador`,
  _ = `Texto del lanzador`,
  _ = `Teclado del lanzador`,
  _ = `Advertencias del dispositivo`,
  _ = `Inicio del juego`,
  _ = `Un jugador`,
  _ = `Multijugador local`,
  _ = `Multijugador en línea`,
  _ = `Antitrampas`,
  _ = `Antitrampas`,
  _ = `Antitrampas/multijugador`,
  _ = `Configuración predeterminada del control`,
  _ = `Teclado`,
  _ = `Glifos del control`,
  _ = `Rendimiento de configuración predeterminada`,
  _ = `Mostrar`,
  _ = `Salida de video`,
  _ = `Resolución nativa`,
  _ = `Legibilidad del texto`,
  _ = `Sonido`,
  _ = `Menú`,
  _ = `Guardado multiplataforma en la nube`,
  _ = `Modo sin conexión para un jugador`,
  _ = `Control externo (jugador principal)`,
  _ = `Control externo (multijugador local)`,
  _ = `Configuración inicial`,
  _ = `Configuración inicial con control`,
  _ = `Configuración inicial sin conexión`,
  _ = `Funcionalidad del juego`,
  _ = `RV`,
  _ = `Nota`,
  _ = `Cierre sin problemas`,
  _ = `Cierre sin problemas (lanzador)`,
  _ = `Entrada simultánea de control y mouse`,
  _ = `Funcionalidad auxiliar: editor de mapas`,
  _ = `Compatible con Limitador de fotogramas`,
  _ = `Foco en varias ventanas (automático)`,
  _ = `Foco en varias ventanas (manual)`,
  _ = `Software`,
  _ = `Entrada simultánea de control y mouse`,
  _ = `Entrada de texto`,
  _ = `Entrada de audio`,
  _ = `Reanudar del modo de suspensión`,
  _ = `Salida de pantalla ajustada`,
  _ = `Contenido y enlaces externos`,
  _ = `Eliminado`,
  _ = `Fuente compatible con todos los caracteres`,
  _ = `Configuraciones de pantalla guardados en cada dispositivo, no en la nube`,
  _ = `Configuración predeterminada del control`,
  _ = `Control predeterminado activado`,
  _ = `Guardado en la nube activado por defecto`,
  _ = `Periféricos (teclado)`,
  _ = `Periféricos (cámara web)`,
  _ = `Periféricos (guitarra USB)`,
  _ = `Compatibilidad con HDR`,
  _ = `Compatibilidad con SO`,
  _ = `Rendimiento de la configuración predeterminada (Steam Machine)`,
  _ = `Rendimiento de la transmisión de RV en Steam\xA0Machine`,
  _ = `Compatible con la transmisión de RV en Steam\xA0Machine`,
  _ = `Advertencias sobre el dispositivo (Steam\xA0Machine)`,
  _ = `Pantalla de Steam Machine`,
  _ = `Audio de Steam Machine`,
  _ = `Steam\xA0Machine`,
  _ = `SteamOS`,
  _ = `Steam Deck`,
  _ = `Steam Frame en modo autónomo`,
  _ = `Solicita una prueba en Steam Frame, la cual iniciará las pruebas para una clasificación de compatibilidad con %1$s.`,
  _ = `¡Te damos la bienvenida! Aquí puedes enviar tu título para una revisión de compatibilidad de tu título con Steam Frame en modo autónomo.`,
  _ = `Lista de autocomprobación de compatibilidad con Steam\xA0Frame en modo autónomo`,
  _ = `A continuación, enumeramos algunos de los criterios más importantes que verificamos al revisar la compatibilidad de un juego con Steam Frame. Completa el siguiente formulario, dinos cuál es la compilación o rama de tu juego que te gustaría que probáramos, y la agregaremos a nuestra cola de revisión. Cuando se complete la revisión, recibirás una notificación por correo electrónico con un resumen, y esta página se actualizará con los resultados detallados de la prueba.`,
  _ = `Para obtener más información sobre el proceso de prueba, consulta el %1$s.`,
  _ = `Proceso de revisión de compatibilidad autónoma de Steam Frame`,
  _ = `Estos son algunos de los artículos más importantes que analizaremos para poder asignar una clasificación de compatibilidad a tu juego. Para comenzar con el proceso de revisión de compatibilidad con Steam Frame, responde las siguientes preguntas de la mejor forma que puedas.`,
  _ = `Las solicitudes de prueba no están disponibles antes del lanzamiento del juego`,
  _ = `¿Proporcionará tu juego una gran experiencia a los jugadores de Steam Deck? Tenemos un proceso de revisión en el que nuestro equipo jugará y probará tu juego. Si la experiencia no presenta problemas para los jugadores en Steam Deck, tu juego recibirá la etiqueta de "Verificado para Steam Deck".`,
  _ = `¡Hola! Aquí puedes solicitar que se revise la compatibilidad de tu título con Steam Deck.`,
  _ = `A continuación, enumeramos algunos de los criterios más importantes que verificamos al revisar la compatibilidad de un juego con Steam Deck. Completa el siguiente formulario, dinos cuál es la compilación o rama de tu juego que te gustaría que probáramos, y la agregaremos a nuestra cola de revisión. Cuando se complete la revisión, recibirás una notificación por correo electrónico con un resumen, y esta página se actualizará con los resultados detallados de la prueba.`,
  _ = `Puedes enviar tu título incluso si no cumple con todos los criterios para obtener la clasificación "Verificado". Utilizamos esta información de autoevaluación para priorizar los títulos que hay que revisar, y para comunicar cualquier problema de compatibilidad con tu juego de la forma más clara posible.`,
  _ = `Para obtener más información acerca del proceso de prueba, consulta la documentación sobre el %1$s y las %2$s.`,
  _ = `Proceso de revisión de compatibilidad con Steam Deck`,
  _ = `recomendaciones adicionales para Steam\xA0Deck`,
  _ = `Lista de autocomprobación de compatibilidad con Steam Deck`,
  _ = `Estos son algunos de los artículos más importantes que analizaremos para poder asignar una clasificación de compatibilidad a tu juego. Para comenzar con el proceso de revisión de compatibilidad con Steam Deck, responde las siguientes preguntas de la mejor forma que puedas.`,
  _ = `En este momento, el proceso de revisión de compatibilidad con Steam Deck solo está disponible para juegos. No hay un proceso de revisión de compatibilidad para otros tipos de aplicaciones, como DLC, herramientas o bandas sonoras, salvo en casos excepcionales.`,
  _ = `Compatible con controles`,
  _ = `Entrada de texto`,
  _ = `Pantalla`,
  _ = `Funcionalidad`,
  _ = `Steam Cloud`,
  _ = `Lanzador`,
  _ = `Rama`,
  _ = `Hacer la prueba utilizando esta rama`,
  _ = `Marcar como listo para revisión...`,
  _ = `Esto indicará que tu compilación está lista para la revisión de compatibilidad con Steam Deck. Unos días después recibirás una notificación con los resultados por correo electrónico.`,
  _ = `Puedes dejar algunas notas a continuación para agilizar las pruebas o para proporcionar las credenciales de acceso a servidores de terceros para las pruebas.`,
  _ = `Ingresar las notas aquí`,
  _ = `Solicitud de ayuda para esta revisión`,
  _ = `Para obtener más información, consulta este informe de pruebas en el sitio de ayuda.`,
  _ = `Crea un ticket de soporte de revisión de compatibilidad con Steam Deck`,
  _ = `Incluye preguntas o comentarios para el equipo de pruebas cuando hagas un ticket de soporte.`,
  _ = `Si tienes preguntas específicas sobre el proceso de revisión de compatibilidad o los resultados para tu juego, escríbelos a continuación.`,
  _ = `Ten en cuenta que, si estás buscando que se vuelva a revisar tu título, será más eficiente si usas el botón "ENVIAR PARA VOLVER A REVISAR" a continuación en lugar de preguntar aquí.`,
  _ = `Tengo una pregunta o comentario sobre el informe de compatibilidad de Steam Deck: `,
  _ = `Sí, mi juego es totalmente compatible con controles: puedes acceder a todas las funciones a través de un control con la configuración predeterminada`,
  _ = `Sí, mi juego muestra las indicaciones correctas para controles de Steam Deck o Xbox cuando se refiere a la pulsación de botones de un control`,
  _ = `O mi juego no requiere ninguna entrada de texto o llama a las API de entrada de texto de Steam correctas cuando es necesario`,
  _ = `Mi juego no requiere ninguna entrada de texto`,
  _ = `Mi juego llama a las API apropiadas de teclado/entrada de texto de Steam cuando necesita la entrada de texto por parte de los usuarios`,
  _ = `Mi juego no actualiza las API de Steam cuando necesita la entrada de texto por parte de los usuarios`,
  _ = `Mi juego no incluye la opción de guardar archivos de juego`,
  _ = `Mi juego incluye la opción de guardar archivos de juego pero no usa Steam Cloud para ellos`,
  _ = `Mi juego utiliza Steam Cloud para guardar juegos; solo hay una compilación para Windows`,
  _ = `Mi juego utiliza Steam Cloud para guardar juegos y es compatible con la opción de guardar archivos multiplataformas (p. ej., Windows/Linux)`,
  _ = `Mi juego utiliza Steam Cloud para guardar juegos pero no es compatible con la opción de guardar archivos multiplataformas (p. ej., Windows/Linux).`,
  _ = `Sí, mi juego puede funcionar a 1280 × 800 (preferida) o a 1280 × 720.`,
  _ = `Sí, el carácter más pequeño que se muestra en pantalla dentro de mi juego es de 9 píxeles de altura o más a una resolución de 1280 × 800.`,
  _ = `O mi juego no tiene lanzador o su lanzador se puede utilizar completamente con un control.`,
  _ = `Ya sea que mi juego es compatible con Steam Cloud para guardar juegos, o mi juego no tiene la opción de guardar archivos.`,
  _ = `Ya sea que mi juego es compatible con la opción de guardar juegos multiplataforma, o mi juego solo se ejecuta en una sola plataforma (Linux/Windows).`,
  _ = `A menos que se indique lo contrario, probaremos tu versión de Windows a través de Proton.`,
  _ = `Si está disponible, probar mi versión de Linux en lugar de la de Windows.`,
  _ = `Mi juego no utiliza un lanzador ni una herramienta de configuración externa.`,
  _ = `Mi juego utiliza un lanzador y ese lanzador es totalmente compatible con controles.`,
  _ = `Mi juego utiliza un lanzador y ese lanzador no es totalmente funcional si el usuario solo tiene un control y no tiene ni teclado ni mouse.`,
  _ = `(Si bien el guardado multiplataforma no es necesario para la clasificación "Verificado", sí es muy valorado por algunos clientes que alternan entre juegos de PC en Windows y Steam Deck en Linux. Echa un vistazo a %1$s).`,
  _ = `documentación`,
  _ = `(La pantalla de Steam Deck es mucho más pequeña que la mayoría de las pantallas de PC. Si tu juego tiene texto pequeño, puede ser difícil o imposible para los clientes leer en la pantalla del Deck, incluso si el texto se puede leer con comodidad en un monitor tradicional).`,
  _ = `(La mayoría de Steam\xA0Decks no tienen un teclado conectado, por lo que los usuarios dependen de los teclados en pantalla para ingresar texto, y Steam proporciona las API para facilitar el uso de los teclados en pantalla integrados. Si los usuarios tienen que abrir el teclado manualmente, tu juego no podrá obtener la calificación de "Verificado". Consulta las %1$s).`,
  _ = `Recomendaciones sobre la entrada`,
  _ = `(Si tu juego utiliza un lanzador, este tiene los mismos requisitos para obtener la clasificación de "Verificado" que el juego en sí: debe ser totalmente utilizable solo con los controles integrados de Steam Deck, debe ser legible, etc. Si tu lanzador no cumple con estos requisitos, tu juego no podrá obtener la clasificación "Verificado", incluso si el juego en sí mismo lo fuera. Consulta las %1$s).`,
  _ = `Recomendaciones sobre el lanzador`,
  _ = `(Una gran parte de los clientes de Steam Deck también son clientes de PC de escritorio. No es necesario guardar en la nube para obtener la clasificación "Verificado", pero la opción es valiosa para los clientes: agregar compatibilidad con %1$s para que la opción de guardar juegos permita a los clientes guardar su juego en una PC de escritorio y reanudarlo en Steam Deck o viceversa).`,
  _ = `Steam Cloud`,
  _ = `(Nota: La compatibilidad total con control es necesaria para obtener la clasificación de "Verificado").`,
  _ = `Se agregó tu juego a nuestra cola de revisión.`,
  _ = `Revisaremos en breve tu juego y te informaremos si encontramos algún problema.`,
  _ = `Completa la revisión de tu compilación para Steam antes de solicitar la revisión de compatibilidad con el hardware.`,
  _ = `Tu juego no es compatible con Steam Deck en estos momentos`,
  _ = `Tu juego no es totalmente compatible con Steam Deck debido a ciertos problemas con Proton o el propio sistema de Steam Deck. Hemos encontrado estos problemas y estamos tratando de resolverlos. Mientras tanto, tu juego no se iniciará ni se ejecutará correctamente en Steam Deck.`,
  _ = `Tu juego es "Jugable" en Steam Deck`,
  _ = `Tu juego es compatible con Steam Deck, pero los clientes tendrán que esforzarse un poco más para jugar o configurarlo. Puedes corregir los problemas que se mencionan a continuación y volver a solicitar la revisión de compatibilidad con Steam Deck.`,
  _ = `Compilación`,
  _ = `En caso de estar disponible, probar la compilación de Android en lugar de la de Windows.`,
  _ = `Probar mi compilación de Windows`,
  _ = `Probar mi compilación de Linux`,
  _ = `¿Deberíamos probar la experiencia 2D o de RV (en caso de estar disponible)?`,
  _ = `2D`,
  _ = `RV`,
  _ = `No aplicable para juegos de %1$s`,
  _ = `Verificado, sin ningún uso de "Borrar estado de evaluación de rendimiento".`,
  _ = `Verificado, con al menos un uso de "Borrar estado de evaluación de rendimiento".`,
  _ = `Jugable, sin ningún uso de "Borrar estado de evaluación de rendimiento".`,
  _ = `Jugable, con al menos un uso de "Borrar estado de evaluación de rendimiento".`,
  _ = `No compatible`,
  _ = `No es un título de RV (no se aplica la evaluación)`,
  _ = `Interfaz de evaluación de rendimiento`,
  _ = `Utiliza la interfaz de evaluación de rendimiento para completar la respuesta a continuación. Consulta la %1$s para obtener más información.`,
  _ = `Documentación sobre rendimiento de RV`,
  _ = `Si tu juego tiene texto pequeño, puede ser difícil o imposible para los clientes leer en la pantalla del Frame, incluso si el texto se puede leer con comodidad en un monitor tradicional).`,
  _ = `(La mayoría de los Steam\xA0Frame no tienen un teclado conectado, por lo que los usuarios dependen de los teclados en pantalla para ingresar texto, y Steam proporciona las API para facilitar el uso de los teclados en pantalla integrados. Si los usuarios tienen que abrir el teclado manualmente, tu juego no podrá obtener la clasificación de "Verificado". Consulta la %1$s).`,
  _ = `Lista de verificación de compatibilidad con Steam Frame`,
  _ = `(Si tu juego utiliza un lanzador, este tiene los mismos requisitos para obtener la clasificación de "Verificado" que el juego en sí: debe ser totalmente utilizable solo con los controles integrados de Steam Deck, debe ser legible, etc. Si tu lanzador no cumple con estos requisitos, tu juego no podrá obtener la clasificación "Verificado", incluso si el juego en sí mismo lo fuera. Consulta las %1$s).`,
  _ = `(Una gran parte de los clientes de Steam Frame también son clientes de PC de escritorio. No es necesario guardar en la nube para obtener la clasificación "Verificado", pero la opción es valiosa para los clientes: agregar compatibilidad con %1$s para que la opción de guardar juegos permita a los clientes guardar su juego en una PC de escritorio y reanudarlo en Steam Frame o viceversa).`,
  _ = `(Si bien el guardado multiplataforma no es necesario para la clasificación "Verificado", sí es muy valorado por algunos clientes que alternan entre juegos de PC en Windows y Steam Frame en Linux. Consulta la %1$s).`,
  _ = `Sí, mi juego muestra las indicaciones correctas para controles de Steam Frame o Xbox cuando se refiere a la pulsación de botones de un control.`,
  _ = `Si el resultado de la evaluación del rendimiento anterior requería al menos un uso de "Borrar estado de evaluación de rendimiento", selecciona uno o más motivos a continuación.`,
  _ = `El rendimiento se degrada al iniciar el juego.`,
  _ = `El rendimiento se degrada durante las pantallas de carga.`,
  _ = `Otro (especificar)`,
  _ = `Estás solicitando una revisión de Android, pero %1$s no tiene ningún repositorio de Android.`,
  _ = `tu paquete Developer\xA0Comp`,
  _ = `dummy`,
  _ = {
    Valve_Confidential: _,
    Valve_Confidential_Description: _,
    Footer_Description: _,
    Footer_Sitemap_ContactSupport: _,
    PricingExplorer_LoadError: _,
    PricingExplorer_About_Title: _,
    PricingExplorer_About_Desc1: _,
    PricingExplorer_About_Desc2: _,
    PricingExplorer_About_Link1: _,
    PricingExplorer_About_LinkName1: _,
    PricingExplorer_About_Link2: _,
    PricingExplorer_About_LinkName2: _,
    PricingExplorer_About_Dash: _,
    PricingExplorer_About_LastUpdated: _,
    PricingExplorer_Explore_title: _,
    PricingExplorer_Explore_desc1: _,
    PricingExplorer_Explore_line1: _,
    PricingExplorer_Explore_line2: _,
    PricingExplorer_Explore_line3: _,
    PricingExplorer_Base: _,
    PricingExplorer_BasePrice: _,
    PricingExplorer_TableHeader: _,
    PricingExplorer_Column1: _,
    PricingExplorer_Column2: _,
    PricingExplorer_Column3: _,
    PricingExplorer_Column4: _,
    PricingExplorer_Regions_TableHeader: _,
    PricingExplorer_Regions_Column1: _,
    Pricing_Dummy: _,
    ContentSurvey_Title: _,
    ContentSurvey_Title_Default: _,
    ContentSurvey_History_Title: _,
    ContentSurvey_History_Title_Default: _,
    ContentSurvey_InvalidApp: _,
    PartnerSite_PermissionDenied: _,
    PartnerSite_NotLoggedIn: _,
    SteamLearn_Project: _,
    SteamLearn_Status_Fetch_Status_Unknown: _,
    SteamDeck_BuildReview_Status_Raw_Title: _,
    SteamDeck_BuildReview_Status_Raw_Description: _,
    SteamDeck_BuildReview_Status_TestProperties_Description: _,
    SteamDeck_BuildReview_Status_TestProperties_Playable: _,
    SteamDeck_BuildReview_Status_TestProperty_Name: _,
    SteamDeck_BuildReview_Status_TestProperty_Value: _,
    SteamDeck_BuildReview_Status_TestProperty_Desc: _,
    SteamDeck_BuildReview_Status_Description: _,
    SteamDeck_BuildReview_Header_History: _,
    SteamDeck_BuildReview_Header_Results: _,
    SteamDeck_BuildReview_Status_Raw_Result: _,
    SteamDeck_BuildReview_Status_Raw_Test: _,
    SteamDeck_BuildReview_Status_Raw_Comment: _,
    SteamDeck_BuildReview_Status_Raw_Impact: _,
    SteamDeck_BuildReview_Status_Pass: _,
    SteamDeck_BuildReview_Status_Fail: _,
    SteamDeck_BuildReview_Status_FailMinor: _,
    SteamDeck_BuildReview_Status_NotApplicable: `---`,
    SteamDeck_BuildReview_Viewing_Historical: _,
    SteamDeck_BuildReview_Viewing_Published: _,
    SteamDeck_BuildReview_PublishedOn: _,
    SteamDeck_BuildReview_ReportedOn: _,
    SteamDeck_BuildReview_Documentation: _,
    SteamDeck_BuildReview_PublishResults: _,
    SteamDeck_BuildReview_PublishDialog_Title: _,
    SteamDeck_BuildReview_PublishDialog_Body: _,
    SteamDeck_BuildReview_UnknownError: _,
    SteamDeck_BuildReview_Help_Request_Title: _,
    SteamDeck_BuildReview_RequestStatusActive: _,
    SteamDeck_BuildReview_RequestStatusClosed: _,
    SteamDeck_BuildReview_InReview_ViewTicket: _,
    SteamDeck_BuildReview_Create_HelpRequest: _,
    SteamDeck_BuildReview_Create_HelpRequest_NotesDefault: _,
    SteamDeck_BuildReview_Create_HelpRequest_NotesDefault_Rereview: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label_Machine: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Button: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_1: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2a: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2b: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Ticket_Content: _,
    SteamDeck_BuildReview_CompatibilityTests: _,
    SteamDeck_BuildReview_Status_Title: _,
    SteamDeck_HardwareCompatibility_Title: _,
    SteamDeck_AppLanding_Published: _,
    SteamDeck_AppLanding_Unpublished: _,
    SteamDeck_AppLanding_History: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RecommendedRuntime: _,
    SteamDeckVerified_TestDisplayName_TestPropertyDescription_RecommendedRuntime:
      _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_ExpectedInput: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RequiresH264: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TestedProtonVersion: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TestedBuildID: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RPODebug: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_FDMDebug: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TSOEnable: _,
    SteamHardware_BuildReview_Unknown_Title: _,
    SteamHardware_BuildReview_Unsupported_Title: _,
    SteamHardware_BuildReview_Unsupported_Description: _,
    SteamHardware_BuildReview_Playable_Title: _,
    SteamHardware_BuildReview_Playable_Description: _,
    SteamHardware_BuildReview_Verified_Title: _,
    SteamHardware_BuildReview_Verified_Description: _,
    SteamHardware_BuildReview_Verified_Share: _,
    SteamHardware_Machine_Unknown: _,
    SteamHardware_Frame_Unknown: _,
    SteamHardware_RatingImpact_Playable: _,
    SteamHardware_RatingImpact_Unsupported: _,
    SteamHardware_RatingImpact_Informational: _,
    SteamDeckVerified_TestDisplayName_0: _,
    SteamDeckVerified_TestDisplayName_1: _,
    SteamDeckVerified_TestDisplayName_2: _,
    SteamDeckVerified_TestDisplayName_3: _,
    SteamDeckVerified_TestDisplayName_4: _,
    SteamDeckVerified_TestDisplayName_5: _,
    SteamDeckVerified_TestDisplayName_6: _,
    SteamDeckVerified_TestDisplayName_7: _,
    SteamDeckVerified_TestDisplayName_8: _,
    SteamDeckVerified_TestDisplayName_9: _,
    SteamDeckVerified_TestDisplayName_10: _,
    SteamDeckVerified_TestDisplayName_11: _,
    SteamDeckVerified_TestDisplayName_12: _,
    SteamDeckVerified_TestDisplayName_13: _,
    SteamDeckVerified_TestDisplayName_14: _,
    SteamDeckVerified_TestDisplayName_15: _,
    SteamDeckVerified_TestDisplayName_16: _,
    SteamDeckVerified_TestDisplayName_17: _,
    SteamDeckVerified_TestDisplayName_18: _,
    SteamDeckVerified_TestDisplayName_19: _,
    SteamDeckVerified_TestDisplayName_20: _,
    SteamDeckVerified_TestDisplayName_21: _,
    SteamDeckVerified_TestDisplayName_22: _,
    SteamDeckVerified_TestDisplayName_23: _,
    SteamDeckVerified_TestDisplayName_24: _,
    SteamDeckVerified_TestDisplayName_25: _,
    SteamDeckVerified_TestDisplayName_26: _,
    SteamDeckVerified_TestDisplayName_27: _,
    SteamDeckVerified_TestDisplayName_29: _,
    SteamDeckVerified_TestDisplayName_30: _,
    SteamDeckVerified_TestDisplayName_31: _,
    SteamDeckVerified_TestDisplayName_32: _,
    SteamDeckVerified_TestDisplayName_33: `RV`,
    SteamDeckVerified_TestDisplayName_34: _,
    SteamDeckVerified_TestDisplayName_35: _,
    SteamDeckVerified_TestDisplayName_36: _,
    SteamDeckVerified_TestDisplayName_37: _,
    SteamDeckVerified_TestDisplayName_38: _,
    SteamDeckVerified_TestDisplayName_39: _,
    SteamDeckVerified_TestDisplayName_40: _,
    SteamDeckVerified_TestDisplayName_41: _,
    SteamDeckVerified_TestDisplayName_42: _,
    SteamDeckVerified_TestDisplayName_43: _,
    SteamDeckVerified_TestDisplayName_44: _,
    SteamDeckVerified_TestDisplayName_45: _,
    SteamDeckVerified_TestDisplayName_46: _,
    SteamDeckVerified_TestDisplayName_47: _,
    SteamDeckVerified_TestDisplayName_48: _,
    SteamDeckVerified_TestDisplayName_49: _,
    SteamDeckVerified_TestDisplayName_50: _,
    SteamDeckVerified_TestDisplayName_51: _,
    SteamDeckVerified_TestDisplayName_52: _,
    SteamDeckVerified_TestDisplayName_53: _,
    SteamDeckVerified_TestDisplayName_54: _,
    SteamDeckVerified_TestDisplayName_55: _,
    SteamDeckVerified_TestDisplayName_56: _,
    SteamDeckVerified_TestDisplayName_57: _,
    SteamDeckVerified_TestDisplayName_58: _,
    SteamDeckVerified_TestDisplayName_59: _,
    SteamDeckVerified_TestDisplayName_60: _,
    SteamDeckVerified_TestDisplayName_61: _,
    SteamDeckVerified_TestDisplayName_62: _,
    SteamDeckVerified_TestDisplayName_63: _,
    SteamDeckVerified_TestDisplayName_64: _,
    SteamDeckVerified_TestDisplayName_65: _,
    Compatibility_Tab_Steam_Machine: _,
    Compatibility_Tab_Steam_OS: _,
    Compatibility_Tab_Steam_Deck: _,
    Compatibility_Tab_Steam_Frame: _,
    SteamDeck_BuildReview_PleaseRequestTest: _,
    SteamFrame_BuildReview_Checklist_Intro_Header_V2: _,
    SteamFrame_BuildReview_PleaseConfirm_Title_V2: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P1: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P3: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P3_ReviewProcess: _,
    SteamFrame_BuildReview_PleaseConfirm_Description_V2: _,
    SteamDeck_TestRequest_BuildNotReleased: _,
    SteamDeck_BuildReview_Checklist_Intro: _,
    SteamDeck_BuildReview_Checklist_Intro_Header_V2: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P1: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P2: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3_ReviewProcess: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3_Additional: _,
    SteamDeck_BuildReview_PleaseConfirm_Title_V2: _,
    SteamDeck_BuildReview_PleaseConfirm_Description_V2: _,
    SteamDeck_BuildReview_AppTypeUnavailable: _,
    SteamDeck_BuildReview_Checklist_Input: _,
    SteamDeck_BuildReview_Checklist_Text: _,
    SteamDeck_BuildReview_Checklist_Display: _,
    SteamDeck_BuildReview_Checklist_Functionality: _,
    SteamDeck_BuildReview_Checklist_SteamCloud: _,
    SteamDeck_BuildReview_Checklist_Launcher: _,
    SteamDeck_BuildReview_Checklist_Branch: _,
    SteamDeck_BuildReview_Checklist_Branch_PleaseTest: _,
    SteamDeck_BuildReview_MarkReady_Button: _,
    SteamDeck_BuildReview_MarkReady_Description: _,
    SteamDeck_BuildReview_MarkReady_Notes: _,
    SteamDeck_BuildReview_MarkReady_NotesDefault: _,
    SteamDeck_BuildReview_HelpRequest_Link: _,
    SteamDeck_BuildReview_ViewMoreDetailsInHelp: _,
    SteamDeck_BuildReview_Create_HelpRequest_Title: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes_1: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes_2: _,
    SteamDeck_BuildReview_Create_HelpRequest_SupportTicketIntro: _,
    SteamDeck_BuildReview_Check_Controller: _,
    SteamDeck_BuildReview_Check_Icons: _,
    SteamDeck_BuildReview_Check_TextInput: _,
    SteamDeck_BuildReview_Check_TextInput_V2_NoTextEntry: _,
    SteamDeck_BuildReview_Check_TextInput_V2_YesSteamAPIs: _,
    SteamDeck_BuildReview_Check_TextInput_V2_NoSteamAPIs: _,
    SteamDeck_BuildReview_Check_Cloud_NoSaves: _,
    SteamDeck_BuildReview_Check_Cloud_YesSavesNoCloud: _,
    SteamDeck_BuildReview_Check_Cloud_SinglePlatform: _,
    SteamDeck_BuildReview_Check_Cloud_YesCrossSaves: _,
    SteamDeck_BuildReview_Check_Cloud_NoCrossSaves: _,
    SteamDeck_BuildReview_Check_Display1280: _,
    SteamDeck_BuildReview_Check_DisplayFont: _,
    SteamDeck_BuildReview_Check_FunctionalityLauncher: _,
    SteamDeck_BuildReview_Check_FunctionalityCloudSaves: _,
    SteamDeck_BuildReview_Check_FunctionalityCrossPlatformCloudSaves: _,
    SteamDeck_BuildReview_Check_TestLinuxBuild_Preamble: _,
    SteamDeck_BuildReview_Check_TestLinuxBuild: _,
    SteamDeck_BuildReview_Check_Launcher_V2_NoLauncher: _,
    SteamDeck_BuildReview_Check_Launcher_V2_ControllerSupport: _,
    SteamDeck_BuildReview_Check_Launcher_V2_NoControllerSupport: _,
    SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves: _,
    SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves_Documentation: _,
    SteamDeck_BuildReview_CheckNote_DisplayFont: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_InputRecommendations:
      _,
    SteamDeck_BuildReview_CheckNote_Launcher_V2_NoControllerSupport: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_LauncherRecommendations:
      _,
    SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud: _,
    SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud_SteamCloud: _,
    SteamDeck_BuildReview_CheckNote_FullController: _,
    SteamDeck_BuildReview_InReview_Title: _,
    SteamDeck_BuildReview_InReview_Description: _,
    SteamDeck_BuildReview_PleaseComplete: _,
    SteamDeck_BuildReview_Unsupported_Title: _,
    SteamDeck_BuildReview_Unsupported_Description: _,
    SteamDeck_BuildReview_NotMeetRequirements_Title: _,
    SteamDeck_BuildReview_NotMeetRequirements_Description: _,
    SteamFrame_BuildReview_Checklist_Build: _,
    SteamFrame_BuildReview_Build_Android: _,
    SteamFrame_BuildReview_Build_Windows: _,
    SteamFrame_BuildReview_Build_Linux: _,
    SteamFrame_BuildReview_Checklist_Dimension: _,
    SteamFrame_BuildReview_Dimension_2D: `2D`,
    SteamFrame_BuildReview_Dimension_VR: `RV`,
    SteamFrame_NotApplicableForDimension: _,
    SteamFrame_BuildReview_Check_VRPerformance_Verified_Without: _,
    SteamFrame_BuildReview_Check_VRPerformance_Verified_With: _,
    SteamFrame_BuildReview_Check_VRPerformance_Playable_Without: _,
    SteamFrame_BuildReview_Check_VRPerformance_Playable_With: _,
    SteamFrame_BuildReview_Check_VRPerformance_Unsupported: _,
    SteamFrame_BuildReview_Check_VRPerformance_NotApplicable: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_Title: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_Description: _,
    SteamFrame_BuildReview_VRPerformanceLink: _,
    SteamFrame_BuildReview_CheckNote_DisplayFont: _,
    SteamFrame_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs: _,
    SteamFrame_BuildReview_Compatibility_Checklist: _,
    SteamFrame_BuildReview_CheckNote_Launcher_V2_NoControllerSupport: _,
    SteamFrame_BuildReview_CheckNote_Cloud_YesSavesNoCloud: _,
    SteamFrame_BuildReview_CheckNote_Cloud_NoCrossSaves: _,
    SteamFrame_BuildReview_Check_Icons: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_StatusReason: _,
    SteamFrame_BuildReview_Check_VRPerformance_Startup: _,
    SteamFrame_BuildReview_Check_VRPerformance_Loading: _,
    SteamFrame_BuildReview_Check_VRPerformance_Other: _,
    SteamFrame_BuildReview_CheckNote_Missing_Android_License: _,
    SteamFrame_BuildReview_CheckNote_Missing_Android_License_Link: _,
    dummy: _,
  };
export {
  _ as Compatibility_Tab_Steam_Deck,
  _ as Compatibility_Tab_Steam_Frame,
  _ as Compatibility_Tab_Steam_Machine,
  _ as Compatibility_Tab_Steam_OS,
  _ as ContentSurvey_History_Title,
  _ as ContentSurvey_History_Title_Default,
  _ as ContentSurvey_InvalidApp,
  _ as ContentSurvey_Title,
  _ as ContentSurvey_Title_Default,
  _ as Footer_Description,
  _ as Footer_Sitemap_ContactSupport,
  _ as PartnerSite_NotLoggedIn,
  _ as PartnerSite_PermissionDenied,
  _ as PricingExplorer_About_Dash,
  _ as PricingExplorer_About_Desc1,
  _ as PricingExplorer_About_Desc2,
  _ as PricingExplorer_About_LastUpdated,
  _ as PricingExplorer_About_Link1,
  _ as PricingExplorer_About_Link2,
  _ as PricingExplorer_About_LinkName1,
  _ as PricingExplorer_About_LinkName2,
  _ as PricingExplorer_About_Title,
  _ as PricingExplorer_Base,
  _ as PricingExplorer_BasePrice,
  _ as PricingExplorer_Column1,
  _ as PricingExplorer_Column2,
  _ as PricingExplorer_Column3,
  _ as PricingExplorer_Column4,
  _ as PricingExplorer_Explore_desc1,
  _ as PricingExplorer_Explore_line1,
  _ as PricingExplorer_Explore_line2,
  _ as PricingExplorer_Explore_line3,
  _ as PricingExplorer_Explore_title,
  _ as PricingExplorer_LoadError,
  _ as PricingExplorer_Regions_Column1,
  _ as PricingExplorer_Regions_TableHeader,
  _ as PricingExplorer_TableHeader,
  _ as Pricing_Dummy,
  _ as SteamDeckVerified_TestDisplayName_0,
  _ as SteamDeckVerified_TestDisplayName_1,
  _ as SteamDeckVerified_TestDisplayName_10,
  _ as SteamDeckVerified_TestDisplayName_11,
  _ as SteamDeckVerified_TestDisplayName_12,
  _ as SteamDeckVerified_TestDisplayName_13,
  _ as SteamDeckVerified_TestDisplayName_14,
  _ as SteamDeckVerified_TestDisplayName_15,
  _ as SteamDeckVerified_TestDisplayName_16,
  _ as SteamDeckVerified_TestDisplayName_17,
  _ as SteamDeckVerified_TestDisplayName_18,
  _ as SteamDeckVerified_TestDisplayName_19,
  _ as SteamDeckVerified_TestDisplayName_2,
  _ as SteamDeckVerified_TestDisplayName_20,
  _ as SteamDeckVerified_TestDisplayName_21,
  _ as SteamDeckVerified_TestDisplayName_22,
  _ as SteamDeckVerified_TestDisplayName_23,
  _ as SteamDeckVerified_TestDisplayName_24,
  _ as SteamDeckVerified_TestDisplayName_25,
  _ as SteamDeckVerified_TestDisplayName_26,
  _ as SteamDeckVerified_TestDisplayName_27,
  _ as SteamDeckVerified_TestDisplayName_29,
  _ as SteamDeckVerified_TestDisplayName_3,
  _ as SteamDeckVerified_TestDisplayName_30,
  _ as SteamDeckVerified_TestDisplayName_31,
  _ as SteamDeckVerified_TestDisplayName_32,
  _ as SteamDeckVerified_TestDisplayName_33,
  _ as SteamDeckVerified_TestDisplayName_34,
  _ as SteamDeckVerified_TestDisplayName_35,
  _ as SteamDeckVerified_TestDisplayName_36,
  _ as SteamDeckVerified_TestDisplayName_37,
  _ as SteamDeckVerified_TestDisplayName_38,
  _ as SteamDeckVerified_TestDisplayName_39,
  _ as SteamDeckVerified_TestDisplayName_4,
  _ as SteamDeckVerified_TestDisplayName_40,
  _ as SteamDeckVerified_TestDisplayName_41,
  _ as SteamDeckVerified_TestDisplayName_42,
  _ as SteamDeckVerified_TestDisplayName_43,
  _ as SteamDeckVerified_TestDisplayName_44,
  _ as SteamDeckVerified_TestDisplayName_45,
  _ as SteamDeckVerified_TestDisplayName_46,
  _ as SteamDeckVerified_TestDisplayName_47,
  _ as SteamDeckVerified_TestDisplayName_48,
  _ as SteamDeckVerified_TestDisplayName_49,
  _ as SteamDeckVerified_TestDisplayName_5,
  _ as SteamDeckVerified_TestDisplayName_50,
  _ as SteamDeckVerified_TestDisplayName_51,
  _ as SteamDeckVerified_TestDisplayName_52,
  _ as SteamDeckVerified_TestDisplayName_53,
  _ as SteamDeckVerified_TestDisplayName_54,
  _ as SteamDeckVerified_TestDisplayName_55,
  _ as SteamDeckVerified_TestDisplayName_56,
  _ as SteamDeckVerified_TestDisplayName_57,
  _ as SteamDeckVerified_TestDisplayName_58,
  _ as SteamDeckVerified_TestDisplayName_59,
  _ as SteamDeckVerified_TestDisplayName_6,
  _ as SteamDeckVerified_TestDisplayName_60,
  _ as SteamDeckVerified_TestDisplayName_61,
  _ as SteamDeckVerified_TestDisplayName_62,
  _ as SteamDeckVerified_TestDisplayName_63,
  _ as SteamDeckVerified_TestDisplayName_64,
  _ as SteamDeckVerified_TestDisplayName_65,
  _ as SteamDeckVerified_TestDisplayName_7,
  _ as SteamDeckVerified_TestDisplayName_8,
  _ as SteamDeckVerified_TestDisplayName_9,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyDescription_RecommendedRuntime,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_ExpectedInput,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_FDMDebug,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RPODebug,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RecommendedRuntime,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RequiresH264,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TSOEnable,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TestedBuildID,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TestedProtonVersion,
  _ as SteamDeck_AppLanding_History,
  _ as SteamDeck_AppLanding_Published,
  _ as SteamDeck_AppLanding_Unpublished,
  _ as SteamDeck_BuildReview_AppTypeUnavailable,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves_Documentation,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud_SteamCloud,
  _ as SteamDeck_BuildReview_CheckNote_DisplayFont,
  _ as SteamDeck_BuildReview_CheckNote_FullController,
  _ as SteamDeck_BuildReview_CheckNote_Launcher_V2_NoControllerSupport,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_InputRecommendations,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_LauncherRecommendations,
  _ as SteamDeck_BuildReview_Check_Cloud_NoCrossSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_NoSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_SinglePlatform,
  _ as SteamDeck_BuildReview_Check_Cloud_YesCrossSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_YesSavesNoCloud,
  _ as SteamDeck_BuildReview_Check_Controller,
  _ as SteamDeck_BuildReview_Check_Display1280,
  _ as SteamDeck_BuildReview_Check_DisplayFont,
  _ as SteamDeck_BuildReview_Check_FunctionalityCloudSaves,
  _ as SteamDeck_BuildReview_Check_FunctionalityCrossPlatformCloudSaves,
  _ as SteamDeck_BuildReview_Check_FunctionalityLauncher,
  _ as SteamDeck_BuildReview_Check_Icons,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_ControllerSupport,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_NoControllerSupport,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_NoLauncher,
  _ as SteamDeck_BuildReview_Check_TestLinuxBuild,
  _ as SteamDeck_BuildReview_Check_TestLinuxBuild_Preamble,
  _ as SteamDeck_BuildReview_Check_TextInput,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_NoSteamAPIs,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_NoTextEntry,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_YesSteamAPIs,
  _ as SteamDeck_BuildReview_Checklist_Branch,
  _ as SteamDeck_BuildReview_Checklist_Branch_PleaseTest,
  _ as SteamDeck_BuildReview_Checklist_Display,
  _ as SteamDeck_BuildReview_Checklist_Functionality,
  _ as SteamDeck_BuildReview_Checklist_Input,
  _ as SteamDeck_BuildReview_Checklist_Intro,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P1,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P2,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3_Additional,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3_ReviewProcess,
  _ as SteamDeck_BuildReview_Checklist_Intro_Header_V2,
  _ as SteamDeck_BuildReview_Checklist_Launcher,
  _ as SteamDeck_BuildReview_Checklist_SteamCloud,
  _ as SteamDeck_BuildReview_Checklist_Text,
  _ as SteamDeck_BuildReview_CompatibilityTests,
  _ as SteamDeck_BuildReview_Create_HelpRequest,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_1,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2a,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2b,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes,
  _ as SteamDeck_BuildReview_Create_HelpRequest_NotesDefault,
  _ as SteamDeck_BuildReview_Create_HelpRequest_NotesDefault_Rereview,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes_1,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes_2,
  _ as SteamDeck_BuildReview_Create_HelpRequest_SupportTicketIntro,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Title,
  _ as SteamDeck_BuildReview_Documentation,
  _ as SteamDeck_BuildReview_Header_History,
  _ as SteamDeck_BuildReview_Header_Results,
  _ as SteamDeck_BuildReview_HelpRequest_Link,
  _ as SteamDeck_BuildReview_Help_Request_Title,
  _ as SteamDeck_BuildReview_InReview_Description,
  _ as SteamDeck_BuildReview_InReview_Title,
  _ as SteamDeck_BuildReview_InReview_ViewTicket,
  _ as SteamDeck_BuildReview_MarkReady_Button,
  _ as SteamDeck_BuildReview_MarkReady_Description,
  _ as SteamDeck_BuildReview_MarkReady_Notes,
  _ as SteamDeck_BuildReview_MarkReady_NotesDefault,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Description,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Button,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label_Machine,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Ticket_Content,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Title,
  _ as SteamDeck_BuildReview_PleaseComplete,
  _ as SteamDeck_BuildReview_PleaseConfirm_Description_V2,
  _ as SteamDeck_BuildReview_PleaseConfirm_Title_V2,
  _ as SteamDeck_BuildReview_PleaseRequestTest,
  _ as SteamDeck_BuildReview_PublishDialog_Body,
  _ as SteamDeck_BuildReview_PublishDialog_Title,
  _ as SteamDeck_BuildReview_PublishResults,
  _ as SteamDeck_BuildReview_PublishedOn,
  _ as SteamDeck_BuildReview_ReportedOn,
  _ as SteamDeck_BuildReview_RequestStatusActive,
  _ as SteamDeck_BuildReview_RequestStatusClosed,
  _ as SteamDeck_BuildReview_Status_Description,
  _ as SteamDeck_BuildReview_Status_Fail,
  _ as SteamDeck_BuildReview_Status_FailMinor,
  _ as SteamDeck_BuildReview_Status_NotApplicable,
  _ as SteamDeck_BuildReview_Status_Pass,
  _ as SteamDeck_BuildReview_Status_Raw_Comment,
  _ as SteamDeck_BuildReview_Status_Raw_Description,
  _ as SteamDeck_BuildReview_Status_Raw_Impact,
  _ as SteamDeck_BuildReview_Status_Raw_Result,
  _ as SteamDeck_BuildReview_Status_Raw_Test,
  _ as SteamDeck_BuildReview_Status_Raw_Title,
  _ as SteamDeck_BuildReview_Status_TestProperties_Description,
  _ as SteamDeck_BuildReview_Status_TestProperties_Playable,
  _ as SteamDeck_BuildReview_Status_TestProperty_Desc,
  _ as SteamDeck_BuildReview_Status_TestProperty_Name,
  _ as SteamDeck_BuildReview_Status_TestProperty_Value,
  _ as SteamDeck_BuildReview_Status_Title,
  _ as SteamDeck_BuildReview_UnknownError,
  _ as SteamDeck_BuildReview_Unsupported_Description,
  _ as SteamDeck_BuildReview_Unsupported_Title,
  _ as SteamDeck_BuildReview_ViewMoreDetailsInHelp,
  _ as SteamDeck_BuildReview_Viewing_Historical,
  _ as SteamDeck_BuildReview_Viewing_Published,
  _ as SteamDeck_HardwareCompatibility_Title,
  _ as SteamDeck_TestRequest_BuildNotReleased,
  _ as SteamFrame_BuildReview_Build_Android,
  _ as SteamFrame_BuildReview_Build_Linux,
  _ as SteamFrame_BuildReview_Build_Windows,
  _ as SteamFrame_BuildReview_CheckNote_Cloud_NoCrossSaves,
  _ as SteamFrame_BuildReview_CheckNote_Cloud_YesSavesNoCloud,
  _ as SteamFrame_BuildReview_CheckNote_DisplayFont,
  _ as SteamFrame_BuildReview_CheckNote_Launcher_V2_NoControllerSupport,
  _ as SteamFrame_BuildReview_CheckNote_Missing_Android_License,
  _ as SteamFrame_BuildReview_CheckNote_Missing_Android_License_Link,
  _ as SteamFrame_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs,
  _ as SteamFrame_BuildReview_Check_Icons,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Loading,
  _ as SteamFrame_BuildReview_Check_VRPerformance_NotApplicable,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Other,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Playable_With,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Playable_Without,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Startup,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Unsupported,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Verified_With,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Verified_Without,
  _ as SteamFrame_BuildReview_Checklist_Build,
  _ as SteamFrame_BuildReview_Checklist_Dimension,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P1,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P3,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P3_ReviewProcess,
  _ as SteamFrame_BuildReview_Checklist_Intro_Header_V2,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_Description,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_StatusReason,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_Title,
  _ as SteamFrame_BuildReview_Compatibility_Checklist,
  _ as SteamFrame_BuildReview_Dimension_2D,
  _ as SteamFrame_BuildReview_Dimension_VR,
  _ as SteamFrame_BuildReview_PleaseConfirm_Description_V2,
  _ as SteamFrame_BuildReview_PleaseConfirm_Title_V2,
  _ as SteamFrame_BuildReview_VRPerformanceLink,
  _ as SteamFrame_NotApplicableForDimension,
  _ as SteamHardware_BuildReview_Playable_Description,
  _ as SteamHardware_BuildReview_Playable_Title,
  _ as SteamHardware_BuildReview_Unknown_Title,
  _ as SteamHardware_BuildReview_Unsupported_Description,
  _ as SteamHardware_BuildReview_Unsupported_Title,
  _ as SteamHardware_BuildReview_Verified_Description,
  _ as SteamHardware_BuildReview_Verified_Share,
  _ as SteamHardware_BuildReview_Verified_Title,
  _ as SteamHardware_Frame_Unknown,
  _ as SteamHardware_Machine_Unknown,
  _ as SteamHardware_RatingImpact_Informational,
  _ as SteamHardware_RatingImpact_Playable,
  _ as SteamHardware_RatingImpact_Unsupported,
  _ as SteamLearn_Project,
  _ as SteamLearn_Status_Fetch_Status_Unknown,
  _ as Valve_Confidential,
  _ as Valve_Confidential_Description,
  _ as default,
  _ as dummy,
};
