var _ = `Unbekannt`,
  _ = `US-Dollar`,
  _ = `Britisches Pfund`,
  _ = `Euro`,
  _ = `Schweizer Franken`,
  _ = `Russischer Rubel`,
  _ = `Polnischer Złoty`,
  _ = `Brasilianischer Real`,
  _ = `Japanischer Yen`,
  _ = `Norwegische Krone`,
  _ = `Indonesische Rupiah`,
  _ = `Malaysischer Ringgit`,
  _ = `Philippinischer Peso`,
  _ = `Singapur-Dollar`,
  _ = `Thailändischer Baht`,
  _ = `Vietnamesischer Dong`,
  _ = `Südkoreanischer Won`,
  _ = `Türkische Lira`,
  _ = `Ukrainische Hrywnja`,
  _ = `Mexikanischer Peso`,
  _ = `Kanadischer Dollar`,
  _ = `Australischer Dollar`,
  _ = `Neuseeland-Dollar`,
  _ = `Chinesische Yuan`,
  _ = `Indische Rupie`,
  _ = `Chilenischer Peso`,
  _ = `Peruanischer Sol`,
  _ = `Kolumbianischer Peso`,
  _ = `Südafrikanischer Rand`,
  _ = `Hongkong-Dollar`,
  _ = `Taiwan-Dollar`,
  _ = `Saudi-Riyal`,
  _ = `Dirham der Vereinigten Arabischen Emirate`,
  _ = `Argentinischer Peso`,
  _ = `Israelischer Neuer Schekel`,
  _ = `Kasachischer Tenge`,
  _ = `Kuwait-Dinar`,
  _ = `Katar-Riyal`,
  _ = `Costa-Rica-Colón`,
  _ = `Uruguayischer Peso`,
  _ = `Bulgarischer Lew`,
  _ = `Schwedische Krone`,
  _ = `Kroatische Kuna`,
  _ = `Tschechische Krone`,
  _ = `Dänische Krone`,
  _ = `Ungarischer Forint`,
  _ = `Rumänischer Leu`,
  _ = `Belarussischer Rubel`,
  _ = `Länder aus Osteuropa, Vorder- und Zentralasien: Wird Kunden in Armenien, Aserbaidschan, Georgien, Kirgisistan, Republik Moldau, Tadschikistan, Turkmenien und Usbekistan und Weißrussland angezeigt.`,
  _ = `Südasiatische Länder: Wird Kunden aus Bangladesch, Bhutan, Nepal, Pakistan und Sri Lanka angezeigt.`,
  _ = `Lateinamerikanische Länder: Wird Kunden in Argentinien, Belize, Bolivien, Ecuador, El Salvador, Guyana, Guatemala, Honduras, Nicaragua, Panama, Paraguay, Surinam und Venezuela angezeigt.`,
  _ = `Länder des Nahen Ostens und Nordafrikas: Wird Kunden in Ägypten, Algerien, Bahrain, Irak, Jemen, Jordanien, Libanon, Libyen, Marokko, Oman, Palästina, Sudan, Tunesien und der Türkei angezeigt.`,
  _ = `Unbekannt`,
  _ = `dummy`,
  _ = {
    CurrencyCodeDescription_Unknown: _,
    CurrencyCodeDescription_USD: _,
    CurrencyCodeDescription_GBP: _,
    CurrencyCodeDescription_EUR: _,
    CurrencyCodeDescription_CHF: _,
    CurrencyCodeDescription_RUB: _,
    CurrencyCodeDescription_PLN: _,
    CurrencyCodeDescription_BRL: _,
    CurrencyCodeDescription_JPY: _,
    CurrencyCodeDescription_NOK: _,
    CurrencyCodeDescription_IDR: _,
    CurrencyCodeDescription_MYR: _,
    CurrencyCodeDescription_PHP: _,
    CurrencyCodeDescription_SGD: _,
    CurrencyCodeDescription_THB: _,
    CurrencyCodeDescription_VND: _,
    CurrencyCodeDescription_KRW: _,
    CurrencyCodeDescription_TRY: _,
    CurrencyCodeDescription_UAH: _,
    CurrencyCodeDescription_MXN: _,
    CurrencyCodeDescription_CAD: _,
    CurrencyCodeDescription_AUD: _,
    CurrencyCodeDescription_NZD: _,
    CurrencyCodeDescription_CNY: _,
    CurrencyCodeDescription_INR: _,
    CurrencyCodeDescription_CLP: _,
    CurrencyCodeDescription_PEN: _,
    CurrencyCodeDescription_COP: _,
    CurrencyCodeDescription_ZAR: _,
    CurrencyCodeDescription_HKD: _,
    CurrencyCodeDescription_TWD: _,
    CurrencyCodeDescription_SAR: _,
    CurrencyCodeDescription_AED: _,
    CurrencyCodeDescription_ARS: _,
    CurrencyCodeDescription_ILS: _,
    CurrencyCodeDescription_KZT: _,
    CurrencyCodeDescription_KWD: _,
    CurrencyCodeDescription_QAR: _,
    CurrencyCodeDescription_CRC: _,
    CurrencyCodeDescription_UYU: _,
    CurrencyCodeDescription_BGN: _,
    CurrencyCodeDescription_SEK: _,
    CurrencyCodeDescription_HRK: _,
    CurrencyCodeDescription_CZK: _,
    CurrencyCodeDescription_DKK: _,
    CurrencyCodeDescription_HUF: _,
    CurrencyCodeDescription_RON: _,
    CurrencyCodeDescription_BYN: _,
    Region_Pricing_Tooltip_CIS: _,
    Region_Pricing_Tooltip_SASIA: _,
    Region_Pricing_Tooltip_LATAM: _,
    Region_Pricing_Tooltip_MENA: _,
    Region_Pricing_Tooltip_Unknown: _,
    dummy: _,
  };
export {
  _ as CurrencyCodeDescription_AED,
  _ as CurrencyCodeDescription_ARS,
  _ as CurrencyCodeDescription_AUD,
  _ as CurrencyCodeDescription_BGN,
  _ as CurrencyCodeDescription_BRL,
  _ as CurrencyCodeDescription_BYN,
  _ as CurrencyCodeDescription_CAD,
  _ as CurrencyCodeDescription_CHF,
  _ as CurrencyCodeDescription_CLP,
  _ as CurrencyCodeDescription_CNY,
  _ as CurrencyCodeDescription_COP,
  _ as CurrencyCodeDescription_CRC,
  _ as CurrencyCodeDescription_CZK,
  _ as CurrencyCodeDescription_DKK,
  _ as CurrencyCodeDescription_EUR,
  _ as CurrencyCodeDescription_GBP,
  _ as CurrencyCodeDescription_HKD,
  _ as CurrencyCodeDescription_HRK,
  _ as CurrencyCodeDescription_HUF,
  _ as CurrencyCodeDescription_IDR,
  _ as CurrencyCodeDescription_ILS,
  _ as CurrencyCodeDescription_INR,
  _ as CurrencyCodeDescription_JPY,
  _ as CurrencyCodeDescription_KRW,
  _ as CurrencyCodeDescription_KWD,
  _ as CurrencyCodeDescription_KZT,
  _ as CurrencyCodeDescription_MXN,
  _ as CurrencyCodeDescription_MYR,
  _ as CurrencyCodeDescription_NOK,
  _ as CurrencyCodeDescription_NZD,
  _ as CurrencyCodeDescription_PEN,
  _ as CurrencyCodeDescription_PHP,
  _ as CurrencyCodeDescription_PLN,
  _ as CurrencyCodeDescription_QAR,
  _ as CurrencyCodeDescription_RON,
  _ as CurrencyCodeDescription_RUB,
  _ as CurrencyCodeDescription_SAR,
  _ as CurrencyCodeDescription_SEK,
  _ as CurrencyCodeDescription_SGD,
  _ as CurrencyCodeDescription_THB,
  _ as CurrencyCodeDescription_TRY,
  _ as CurrencyCodeDescription_TWD,
  _ as CurrencyCodeDescription_UAH,
  _ as CurrencyCodeDescription_USD,
  _ as CurrencyCodeDescription_UYU,
  _ as CurrencyCodeDescription_Unknown,
  _ as CurrencyCodeDescription_VND,
  _ as CurrencyCodeDescription_ZAR,
  _ as Region_Pricing_Tooltip_CIS,
  _ as Region_Pricing_Tooltip_LATAM,
  _ as Region_Pricing_Tooltip_MENA,
  _ as Region_Pricing_Tooltip_SASIA,
  _ as Region_Pricing_Tooltip_Unknown,
  _ as default,
  _ as dummy,
};
