var _ = `Επιλέξτε παρακάτω μια τιμή σε USD`,
  _ = `Δωρεάν`,
  _ = `Ορισμός σε δωρεάν…`,
  _ = `Ενημέρωση αυτού του πακέτου σε δωρεάν για τους πελάτες`,
  _ = `Αυτό το πακέτο μπορεί να οριστεί ως δωρεάν μόνο από έναν εκπρόσωπο της Υποστήριξης Steam. Χρησιμοποιήστε τον σύνδεσμο «Επικοινωνήστε με το τμήμα εκδόσεων Steam» κάτω από το «Τεκμηρίωση και βοήθεια» για βοήθεια.`,
  _ = `Μετατροπή πακέτου σε δωρεάν;`,
  _ = `Αυτό θα ρυθμίσει την τιμολόγηση του πακέτου σας σε δωρεάν, θα επισημάνει την εφαρμογή σας ώστε να μπορεί να εμφανίζεται στο Κέντρο «Δωρεάν για παίξιμο» και θα αλλάξει την εμφάνιση της τιμής με βάση τον όρο που θα επιλέξετε παρακάτω. Αυτή η αλλαγή δεν μπορεί να αντιστραφεί χωρίς καταχώριση δελτίου στην ομάδα Υποστήριξης Steamworks.`,
  _ = `Αυτό το πακέτο μπορεί να μετατραπεί σε δωρεάν μόνο από έναν εκπρόσωπο της Υποστήριξης Steam. Κάντε κλικ παρακάτω για να δημιουργήσετε ένα δελτίο αιτήματος υποστήριξης με λεπτομέρειες για το αίτημά σας.`,
  _ = `Επιλέξτε το κατάλληλο κείμενο για να εμφανίζεται αντί της τιμής:`,
  _ = `«Δωρεάν για παίξιμο» – Το παιχνίδι είναι δωρεάν για λήψη και παίξιμο, αλλά περιλαμβάνει προαιρετικές αγορές εντός παιχνιδιού (αντικείμενα, νόμισμα, DLC ή άλλο τρόπο δημιουργίας εσόδων).`,
  _ = `«Δωρεάν» – Το παιχνίδι είναι εντελώς δωρεάν για λήψη και παίξιμο. Δεν περιλαμβάνει αγορές εντός παιχνιδιού ή περιεχόμενο επί πληρωμή.`,
  _ = `Μετατροπή σε δωρεάν`,
  _ = `Γίνεται ενημέρωση της σελίδας Καταστήματος του παιχνιδιού για να περιλαμβάνεται στο είδος «δωρεάν». Απαιτείται δημοσίευση στο Κατάστημα.`,
  _ = `Γίνεται ενημέρωση πακέτου για να είναι δωρεάν`,
  _ = `Επιτυχής μετατροπή σε δωρεάν. Θα γίνει επαναφόρτωση της σελίδας όταν κλείσετε αυτό το παράθυρο διαλόγου.`,
  _ = `Αποτυχία ενημέρωσης σελίδας Καταστήματος της εφαρμογής: %1$s`,
  _ = `Αποτυχία αλλαγής τύπου πακέτου: %1$s`,
  _ = `Μέθοδος μετατροπής (%1$s)`,
  _ = `Εμφάνιση λεπτομερειών`,
  _ = `Από το αναπτυσσόμενο μενού παρακάτω, επιλέξτε την τιμή στην οποία θέλετε να πωλείται το προϊόν σας. Για κάθε βασική τιμή που θα επιλέξετε, το εργαλείο αυτό θα προτείνει ενδεδειγμένες τοπικές τιμές βάσει της εμπειρίας μας με άλλους τίτλους σε ανάλογες τιμές. Λάβετε υπόψη ότι οι προτεινόμενες μετατροπές ορισμένων χωρών συμπεριλαμβάνουν φόρους (VAT/GST/JCT). Οι φόροι αυτοί είναι φόροι προστιθέμενης αξίας, παρόμοια με τον φόρο πωλήσεων, που επιβάλλονται από τις φορολογικές αρχές. Σε χώρες όπου απαιτείται ΦΠΑ βάσει του ισχύοντος νόμου, συμπεριλαμβάνεται στις τιμές και εισπράττεται κατά την αγορά από τις χώρες όπου ισχύει. Μπορείτε να βρείτε εδώ τη λίστα χωρών όπου εισπράττεται ΦΠΑ:`,
  _ = `Πριν την υποβολή, ελέγξτε ενδελεχώς τις τιμές σας ΣΕ ΟΛΑ ΤΑ ΝΟΜΙΣΜΑΤΑ και σκεφτείτε προσεκτικά όσον αφορά το προϊόν σας. Για διάφορους λόγους, συνιστούμε οι συνεργάτες να μην τροποποιούν τις τιμές τους τις πρώτες εβδομάδες μετά την κυκλοφορία. Μπορείτε να υποβάλετε αίτημα για νέα τιμή πριν την κυκλοφορία εάν χρειάζεται, αλλά όταν το προϊόν σας κυκλοφορήσει, οι τιμές σας θα μείνουν ως έχουν. Δείτε την %1$s για να μάθετε περισσότερα.`,
  _ = `τεκμηρίωση για την τιμολόγηση και τις εκπτώσεις`,
  _ = `Όταν είστε ικανοποιημένοι με την τιμή που θέσατε, πατήστε το κουμπί «Αποθήκευση» για να τη στείλετε στη Valve προς έλεγχο και επεξεργασία.`,
  _ = `Επεξεργασία στη σελίδα μαζικής τιμολόγησης`,
  _ = `Επεξεργαστείτε την τιμολόγηση αυτού του πακέτου από το εργαλείο μαζικής τιμολόγησης`,
  _ = `Βοήθεια και οδηγίες`,
  _ = `Αναζητάτε βοήθεια ή προτάσεις σχετικά με την τιμολόγηση του τίτλου σας; Παρακάτω θα βρείτε έναν σύνδεσμο προς ορισμένες οδηγίες και πράγματα που πρέπει να λάβετε υπόψη.`,
  _ = `Τεκμηρίωση τιμολόγησης`,
  _ = `Συχνές ερωτήσεις`,
  _ = `Αλλαγή σε δωρεάν;`,
  _ = `Εάν το παιχνίδι σας έχει ήδη κυκλοφορήσει και χρειάζεται να κάνετε αλλαγή από επί πληρωμή σε δωρεάν, κάντε κλικ %1$s για να μάθετε περισσότερα και να ζητήσετε βοήθεια.`,
  _ = `εδώ`,
  _ = `Εισαγωγή προσαρμοσμένων τιμών`,
  _ = `Μπορείτε να εισαγάγετε τις δικές σας τιμές για κάθε νόμισμα με απευθείας επεξεργασία του πλαισίου κειμένου.`,
  _ = `Μπορείτε επίσης να χρησιμοποιήσετε αυτό το κουμπί για να υπολογίσετε κάθε νόμισμα βάσει της επιλεγμένης μεθόδου μετατροπής και της προσαρμοσμένης τιμής σε USD που έχετε εισαγάγει.`,
  _ = `Επιλέξτε από τις βαθμίδες τιμών`,
  _ = `Επιλέξτε τη βασική τιμή σε USD`,
  _ = `Ανοίγει ένα παράθυρο διαλόγου με ένα σύνολο από συνήθεις βαθμίδες τιμών που επιτρέπει τη ρύθμισή τους σε όλα τα παρακάτω νομίσματα.`,
  _ = `Μετατροπή βάσει πολλών μεταβλητών`,
  _ = `Μετατροπή μόνο βάσει αγοραστικής δύναμης`,
  _ = `Μετατροπή μόνο βάσει συναλλαγματικής ισοτιμίας`,
  _ = `Τελευταία ενημέρωση:`,
  _ = `Οι μέθοδοι μετατροπής δημιουργούνται χρησιμοποιώντας δημόσια δεδομένα από τον Ιανουάριο του 2026 και έπειτα.`,
  _ = `Νέες διαθέσιμες μέθοδοι μετατροπής`,
  _ = `Για να βοηθήσουμε με την τιμολόγηση του παιχνιδιού σας σε 37 διαφορετικά νομίσματα και 4 ομάδες περιοχών, το Steam πλέον προσφέρει ορισμένες διαφορετικές μεθόδους που βοηθούν στη μετατροπή της τιμής από τη βασική τιμή που επιθυμείτε.`,
  _ = `Η τιμολόγηση εξαρτάται εξ ολοκλήρου από εσάς. Αυτά τα εργαλεία έχουν σχεδιαστεί απλώς για να βοηθούν με την απλοποίηση της διαδικασίας, σε περίπτωση που το επιλέξετε.`,
  _ = `Επισκεφθείτε τη «%1$s» ή κάντε κλικ στην «Εμφάνιση λεπτομερειών» παραπάνω, για να μάθετε περισσότερα σχετικά με τις διαφορετικές μεθόδους μετατροπής που είναι διαθέσιμες.`,
  _ = `σελίδα λεπτομερειών μεθόδων μετατροπής`,
  _ = `Εφαρμογή τιμών μεθόδου μετατροπής`,
  _ = `Για να βοηθήσουμε στη διαχείριση της τιμολόγησης σε περισσότερα από 35 νομίσματα, την οποία υποστηρίζει το Steam, αυτό το εργαλείο προσφέρει προαιρετικές μεθόδους μετατροπής για το πώς να «μεταφράσετε» τη βασική τιμή σας (USD) σε επίπεδα κατάλληλα για κάθε περιοχή.`,
  _ = `Επιλέξτε μια τιμή παρακάτω για να την ορίσετε σε USD και να εφαρμόσετε τις μετατροπές τιμής σε όλα τα άλλα νομίσματα. Εξαρτάται από τη μέθοδο μετατροπής που επιλέχθηκε παραπάνω.`,
  _ = `Μπορείτε να εισαγάγετε τιμές για κάθε επιμέρους νόμισμα που υποστηρίζεται ή να χρησιμοποιήσετε μία από τις μεθόδους μετατροπής του Steam για να μετατρέψετε την τιμή USD σας σε όλα τα άλλα νομίσματα.`,
  _ = `Υπάρχουν δύο τρόποι για να χρησιμοποιήσετε τις μεθόδους μετατροπής του Steam:`,
  _ = `Επιλέξτε μια συνήθη τιμή σε USD από το παρακάτω αναπτυσσόμενο μενού βαθμίδων τιμών και το Steam θα συμπληρώσει τα υπόλοιπα νομίσματα βάσει της μεθόδου μετατροπής που επιλέχθηκε.`,
  _ = `Για μη συνήθεις τιμές σε USD, πληκτρολογήστε μια τιμή στο πεδίο τιμών USD. Στη συνέχεια, κάντε κλικ στο κουμπί «Μετατροπή τιμών…» και ακολουθήστε τις οδηγίες.`,
  _ = `Προτεινόμενη μετατροπή:`,
  _ = `Αυτή η τιμή προτείνεται βάσει της μεθόδου μετατροπής που επιλέχθηκε παραπάνω και της τιμής σε USD (%1$s).`,
  _ = `dummy`,
  _ = ``,
  _ = {
    PricingGuideline_Default: _,
    FreeOnDemand_InlineOption: _,
    FreeOnDemand_Button: _,
    FreeOnDemand_Button_ttip: _,
    FreeOnDemand_Button_disabled_ttip: _,
    FreeOnDemand_Title: _,
    FreeOnDemand_Desc: _,
    FreeOnDemand_Desc_NotPermitted: _,
    FreeOnDemand_Radio: _,
    FreeOnDemand_Radio_FreeToPlay: _,
    FreeOnDemand_Radio_Free: _,
    FreeOnDemand_Button_Confirm: _,
    FreeOnDemand_Convert_Store: _,
    FreeOnDemand_Convert_Package: _,
    FreeOnDemand_ConvertSuccess: _,
    FreeOnDemand_Store_Error: _,
    FreeOnDemand_Package_Error: _,
    ConversionMethod_Title: _,
    ConversionMethod_Link: _,
    SinglePricingPackage_Desc_1: _,
    SinglePricingPackage_Desc_2: _,
    SinglePricingPackage_Desc_2_Link: _,
    SinglePricingPackage_Desc_3: _,
    SinglePackagePricing_Right_Edit: _,
    SinglePackagePricing_Right_Edit_desc: _,
    SinglePackagePricing_Right_Help_Title: _,
    SinglePackagePricing_Right_Help_Desc: _,
    SinglePackagePricing_Right_Link: _,
    SinglePackagePricing_Right_FAQ: _,
    SinglePackagePricing_Right_FAQ_switching: _,
    SinglePackagePricing_Right_FAQ_switching_answer: _,
    SinglePackagePricing_Right_FAQ_switching_answer_link: _,
    SinglePackagePricing_Right_Convert_Title: _,
    SinglePackagePricing_Right_Custom_Desc: _,
    SinglePackagePricing_Right_Convert_Desc: _,
    PricingDashboard_Select_Price: _,
    PricingDashboard_Select_Price_button: _,
    PricingDashboard_Select_Price_button_ttip: _,
    ConversionMethod_Nuanced: _,
    ConversionMethod_PPP: _,
    ConversionMethod_FX: _,
    PricingExplorer_Time_Title: _,
    PricingExplorer_Time_Disc: _,
    Tour_ConversionMethod_Title: _,
    Tour_ConversionMethod_Desc1: _,
    Tour_ConversionMethod_Desc2: _,
    Tour_ConversionMethod_Desc3: _,
    Tour_ConversionMethod_Link: _,
    PricingDashboard_ApplyConversion_Method: _,
    PricingDashboard_ApplyGuidelines_Instructions_MultiOptions: _,
    PricingDashboard_GuidelinesPickerDescription_New: _,
    SinglePricingPackage_Intro_1: _,
    SinglePricingPackage_Intro_2: _,
    SinglePricingPackage_Intro_2a: _,
    SinglePricingPackage_Intro_2b: _,
    PricingDashboard_Method_SuggestedPrice: _,
    PricingDashboard_Method_SuggestedPrice_ttip: _,
    dummy: _,
    empty_no_trailing_comma: ``,
  };
export {
  _ as ConversionMethod_FX,
  _ as ConversionMethod_Link,
  _ as ConversionMethod_Nuanced,
  _ as ConversionMethod_PPP,
  _ as ConversionMethod_Title,
  _ as FreeOnDemand_Button,
  _ as FreeOnDemand_Button_Confirm,
  _ as FreeOnDemand_Button_disabled_ttip,
  _ as FreeOnDemand_Button_ttip,
  _ as FreeOnDemand_ConvertSuccess,
  _ as FreeOnDemand_Convert_Package,
  _ as FreeOnDemand_Convert_Store,
  _ as FreeOnDemand_Desc,
  _ as FreeOnDemand_Desc_NotPermitted,
  _ as FreeOnDemand_InlineOption,
  _ as FreeOnDemand_Package_Error,
  _ as FreeOnDemand_Radio,
  _ as FreeOnDemand_Radio_Free,
  _ as FreeOnDemand_Radio_FreeToPlay,
  _ as FreeOnDemand_Store_Error,
  _ as FreeOnDemand_Title,
  _ as PricingDashboard_ApplyConversion_Method,
  _ as PricingDashboard_ApplyGuidelines_Instructions_MultiOptions,
  _ as PricingDashboard_GuidelinesPickerDescription_New,
  _ as PricingDashboard_Method_SuggestedPrice,
  _ as PricingDashboard_Method_SuggestedPrice_ttip,
  _ as PricingDashboard_Select_Price,
  _ as PricingDashboard_Select_Price_button,
  _ as PricingDashboard_Select_Price_button_ttip,
  _ as PricingExplorer_Time_Disc,
  _ as PricingExplorer_Time_Title,
  _ as PricingGuideline_Default,
  _ as SinglePackagePricing_Right_Convert_Desc,
  _ as SinglePackagePricing_Right_Convert_Title,
  _ as SinglePackagePricing_Right_Custom_Desc,
  _ as SinglePackagePricing_Right_Edit,
  _ as SinglePackagePricing_Right_Edit_desc,
  _ as SinglePackagePricing_Right_FAQ,
  _ as SinglePackagePricing_Right_FAQ_switching,
  _ as SinglePackagePricing_Right_FAQ_switching_answer,
  _ as SinglePackagePricing_Right_FAQ_switching_answer_link,
  _ as SinglePackagePricing_Right_Help_Desc,
  _ as SinglePackagePricing_Right_Help_Title,
  _ as SinglePackagePricing_Right_Link,
  _ as SinglePricingPackage_Desc_1,
  _ as SinglePricingPackage_Desc_2,
  _ as SinglePricingPackage_Desc_2_Link,
  _ as SinglePricingPackage_Desc_3,
  _ as SinglePricingPackage_Intro_1,
  _ as SinglePricingPackage_Intro_2,
  _ as SinglePricingPackage_Intro_2a,
  _ as SinglePricingPackage_Intro_2b,
  _ as Tour_ConversionMethod_Desc1,
  _ as Tour_ConversionMethod_Desc2,
  _ as Tour_ConversionMethod_Desc3,
  _ as Tour_ConversionMethod_Link,
  _ as Tour_ConversionMethod_Title,
  _ as default,
  _ as dummy,
  _ as empty_no_trailing_comma,
};
