var _ = `Onbekend`,
  _ = `Amerikaanse dollar`,
  _ = `Britse pond`,
  _ = `Euro`,
  _ = `Zwitserse frank`,
  _ = `Russische roebel`,
  _ = `Poolse zloty`,
  _ = `Braziliaanse real`,
  _ = `Japanse yen`,
  _ = `Noorse kroon`,
  _ = `Indonesische roepia`,
  _ = `Maleisische ringgit`,
  _ = `Filipijnse peso`,
  _ = `Singaporese dollar`,
  _ = `Thaise baht`,
  _ = `Vietnamese dong`,
  _ = `Koreaanse won`,
  _ = `Turkse lira`,
  _ = `Oekraïense grivna`,
  _ = `Mexicaanse peso`,
  _ = `Canadese dollar`,
  _ = `Australische dollar`,
  _ = `Nieuw-Zeelandse dollar`,
  _ = `Chinese yuan`,
  _ = `Indiase roepie`,
  _ = `Chileense peso`,
  _ = `Peruviaanse sol`,
  _ = `Colombiaanse peso`,
  _ = `Zuid-Afrikaanse rand`,
  _ = `Hongkongse dollar`,
  _ = `Taiwanese dollar`,
  _ = `Saoedi-Arabische riyal`,
  _ = `VAE-dirham`,
  _ = `Argentijnse peso`,
  _ = `Israëlische nieuwe sjekel`,
  _ = `Kazachse tenge`,
  _ = `Koeweitse dinar`,
  _ = `Qatarese riyal`,
  _ = `Costa Ricaanse colon`,
  _ = `Uruguayaanse peso`,
  _ = `Bulgaarse lev`,
  _ = `Zweedse kroon`,
  _ = `Kroatische kuna`,
  _ = `Tsjechische kroon`,
  _ = `Deense kroon`,
  _ = `Hongaarse forint`,
  _ = `Roemeense leu`,
  _ = `Belarussische roebel`,
  _ = `GOS-landen: getoond aan klanten in Armenië, Azerbeidzjan, Belarus, Georgië, Kirgizië, Moldavië, Oezbekistan, Tadzjikistan en Turkmenistan.`,
  _ = `Zuid-Aziatische landen: getoond aan klanten in Bangladesh, Bhutan, Nepal, Pakistan en Sri Lanka`,
  _ = `Latijns-Amerikaanse landen: getoond aan klanten in Argentinië, Belize, Bolivia, Ecuador, El Salvador, Guyana, Guatemala, Honduras, Nicaragua, Panama, Paraguay, Suriname, Venezuela.`,
  _ = `Landen in het Midden-Oosten en Noord-Afrika: getoond aan klanten in Algerije, Bahrein, Egypte, Irak, Jemen, Jordanië, Libanon, Libië, Marokko, Oman, Palestina, Soedan, Tunesië, Turkije.`,
  _ = `Onbekend`,
  _ = `dummy`,
  _ = {
    CurrencyCodeDescription_Unknown: _,
    CurrencyCodeDescription_USD: _,
    CurrencyCodeDescription_GBP: _,
    CurrencyCodeDescription_EUR: _,
    CurrencyCodeDescription_CHF: _,
    CurrencyCodeDescription_RUB: _,
    CurrencyCodeDescription_PLN: _,
    CurrencyCodeDescription_BRL: _,
    CurrencyCodeDescription_JPY: _,
    CurrencyCodeDescription_NOK: _,
    CurrencyCodeDescription_IDR: _,
    CurrencyCodeDescription_MYR: _,
    CurrencyCodeDescription_PHP: _,
    CurrencyCodeDescription_SGD: _,
    CurrencyCodeDescription_THB: _,
    CurrencyCodeDescription_VND: _,
    CurrencyCodeDescription_KRW: _,
    CurrencyCodeDescription_TRY: _,
    CurrencyCodeDescription_UAH: _,
    CurrencyCodeDescription_MXN: _,
    CurrencyCodeDescription_CAD: _,
    CurrencyCodeDescription_AUD: _,
    CurrencyCodeDescription_NZD: _,
    CurrencyCodeDescription_CNY: _,
    CurrencyCodeDescription_INR: _,
    CurrencyCodeDescription_CLP: _,
    CurrencyCodeDescription_PEN: _,
    CurrencyCodeDescription_COP: _,
    CurrencyCodeDescription_ZAR: _,
    CurrencyCodeDescription_HKD: _,
    CurrencyCodeDescription_TWD: _,
    CurrencyCodeDescription_SAR: _,
    CurrencyCodeDescription_AED: _,
    CurrencyCodeDescription_ARS: _,
    CurrencyCodeDescription_ILS: _,
    CurrencyCodeDescription_KZT: _,
    CurrencyCodeDescription_KWD: _,
    CurrencyCodeDescription_QAR: _,
    CurrencyCodeDescription_CRC: _,
    CurrencyCodeDescription_UYU: _,
    CurrencyCodeDescription_BGN: _,
    CurrencyCodeDescription_SEK: _,
    CurrencyCodeDescription_HRK: _,
    CurrencyCodeDescription_CZK: _,
    CurrencyCodeDescription_DKK: _,
    CurrencyCodeDescription_HUF: _,
    CurrencyCodeDescription_RON: _,
    CurrencyCodeDescription_BYN: _,
    Region_Pricing_Tooltip_CIS: _,
    Region_Pricing_Tooltip_SASIA: _,
    Region_Pricing_Tooltip_LATAM: _,
    Region_Pricing_Tooltip_MENA: _,
    Region_Pricing_Tooltip_Unknown: _,
    dummy: _,
  };
export {
  _ as CurrencyCodeDescription_AED,
  _ as CurrencyCodeDescription_ARS,
  _ as CurrencyCodeDescription_AUD,
  _ as CurrencyCodeDescription_BGN,
  _ as CurrencyCodeDescription_BRL,
  _ as CurrencyCodeDescription_BYN,
  _ as CurrencyCodeDescription_CAD,
  _ as CurrencyCodeDescription_CHF,
  _ as CurrencyCodeDescription_CLP,
  _ as CurrencyCodeDescription_CNY,
  _ as CurrencyCodeDescription_COP,
  _ as CurrencyCodeDescription_CRC,
  _ as CurrencyCodeDescription_CZK,
  _ as CurrencyCodeDescription_DKK,
  _ as CurrencyCodeDescription_EUR,
  _ as CurrencyCodeDescription_GBP,
  _ as CurrencyCodeDescription_HKD,
  _ as CurrencyCodeDescription_HRK,
  _ as CurrencyCodeDescription_HUF,
  _ as CurrencyCodeDescription_IDR,
  _ as CurrencyCodeDescription_ILS,
  _ as CurrencyCodeDescription_INR,
  _ as CurrencyCodeDescription_JPY,
  _ as CurrencyCodeDescription_KRW,
  _ as CurrencyCodeDescription_KWD,
  _ as CurrencyCodeDescription_KZT,
  _ as CurrencyCodeDescription_MXN,
  _ as CurrencyCodeDescription_MYR,
  _ as CurrencyCodeDescription_NOK,
  _ as CurrencyCodeDescription_NZD,
  _ as CurrencyCodeDescription_PEN,
  _ as CurrencyCodeDescription_PHP,
  _ as CurrencyCodeDescription_PLN,
  _ as CurrencyCodeDescription_QAR,
  _ as CurrencyCodeDescription_RON,
  _ as CurrencyCodeDescription_RUB,
  _ as CurrencyCodeDescription_SAR,
  _ as CurrencyCodeDescription_SEK,
  _ as CurrencyCodeDescription_SGD,
  _ as CurrencyCodeDescription_THB,
  _ as CurrencyCodeDescription_TRY,
  _ as CurrencyCodeDescription_TWD,
  _ as CurrencyCodeDescription_UAH,
  _ as CurrencyCodeDescription_USD,
  _ as CurrencyCodeDescription_UYU,
  _ as CurrencyCodeDescription_Unknown,
  _ as CurrencyCodeDescription_VND,
  _ as CurrencyCodeDescription_ZAR,
  _ as Region_Pricing_Tooltip_CIS,
  _ as Region_Pricing_Tooltip_LATAM,
  _ as Region_Pricing_Tooltip_MENA,
  _ as Region_Pricing_Tooltip_SASIA,
  _ as Region_Pricing_Tooltip_Unknown,
  _ as default,
  _ as dummy,
};
