var _ = `ข้อมูลลับของ Valve`,
  _ = `หน้าเว็บแบบจำกัดสิทธิ์การเข้าถึงนี้มีข้อมูลลับของ Valve ดังนั้นคุณต้องลงนามในข้อตกลงการไม่เปิดเผยข้อมูล และ/หรือข้อตกลงใบอนุญาตสิทธิ์ที่ครอบคลุมถึงข้อมูลลับกับ Valve เพื่อใช้งานหรือเข้าถึงหน้านี้`,
  _ = `Steamworks คือชุดเครื่องมือและบริการที่ <1>Valve</1> สร้างขึ้น ซึ่งจะช่วยให้คุณกำหนดค่า จัดการ และดำเนินการกับเกมของคุณบน <2>Steam</2> ได้`,
  _ = `ติดต่อฝ่ายสนับสนุน`,
  _ = `ตรวจพบข้อผิดพลาดในการโหลดข้อมูลราคา โปรดลองใหม่ในอีกสักครู่`,
  _ = `เกี่ยวกับการกำหนดราคาตามภูมิภาค`,
  _ = `ราคาสำหรับแต่ละผลิตภัณฑ์บน Steam จะถูกกำหนดและแสดงโดยใช้ %1$sสกุลเงินและ%2$s <1>กลุ่มภูมิภาค</1> ที่แตกต่างกัน Steam มีเครื่องมือที่ช่วยให้คุณตั้งค่าและจัดการราคาของเกมของคุณให้อยู่ในระดับที่เหมาะสมสำหรับแต่ละตลาด`,
  _ = `โดยคุณสามารถกำหนดราคาเกมของคุณในแต่ละสกุลเงินและกลุ่มภูมิภาคได้ด้วยตนเอง`,
  _ = `หากต้องการรายละเอียดเพิ่มเติมเกี่ยวกับการจัดการการกำหนดราคาของคุณ โปรดอ่าน %1$s`,
  _ = `เอกสารการกำหนดราคา`,
  _ = `หากต้องการจัดการการกำหนดราคาเกมของคุณ โปรดไปที่ %1$s ของคุณ`,
  _ = `ไปที่กระดานรวมการกำหนดราคา`,
  _ = `หากต้องการจัดการการกำหนดราคาของเกมของคุณ โปรดไปที่กระดานรวมการกำหนดราคาของคุณ`,
  _ = `อัปเดตการแปลงสกุลเงินครั้งล่าสุดเมื่อ %1$s`,
  _ = `เครื่องมือสำรวจการแปลงราคา`,
  _ = `เครื่องมือนี้แสดงการทำงานของวิธีการแปลงราคาและสกุลเงิน 3 วิธี:`,
  _ = `%1$s - วิธีนี้คำนึงถึงปัจจัยหลายประการสำหรับแต่ละสกุลเงิน ซึ่งรวมถึงกำลังซื้อของลูกค้าในแต่ละประเทศและภูมิภาค ค่าใช้จ่ายที่คาดการณ์ไว้สำหรับสินค้าด้านความบันเทิงที่เทียบเคียงกันได้ในแต่ละตลาด และอัตราแลกเปลี่ยนเงินตรา`,
  _ = `%1$s - วิธีนี้ใช้ข้อมูลสาธารณะเกี่ยวกับกำลังซื้อของลูกค้าในประเทศและ/หรือภูมิภาคที่ระบุ`,
  _ = `%1$s - วิธีนี้ใช้อัตราแลกเปลี่ยนสกุลเงินแบบง่าย ๆ ในเวลาที่ระบุไว้`,
  _ = `สกุลเงินฐาน`,
  _ = `ราคาฐาน`,
  _ = `วิธีแปลง`,
  _ = `สกุลเงิน`,
  _ = `การแปลงแบบหลายตัวแปร`,
  _ = `การแปลงตามกำลังซื้อเท่านั้น`,
  _ = `การแปลงตามอัตราแลกเปลี่ยนเท่านั้น`,
  _ = `ราคาตามภูมิภาค (ทั้งหมดรายงานเป็นดอลลาร์สหรัฐ)`,
  _ = `ภูมิภาค`,
  _ = `ดัมมี่`,
  _ = `%1$s (%2$s) - แบบสำรวจเนื้อหา`,
  _ = `แบบสำรวจเนื้อหา`,
  _ = `%1$s (%2$s) - แบบสำรวจเนื้อหา`,
  _ = `แบบสำรวจเนื้อหา`,
  _ = `ไม่มีแอปที่มีไอดีนี้ โปรดตรวจสอบที่อยู่และลองอีกครั้ง`,
  _ = `สิทธิ์ถูกปฏิเสธ`,
  _ = `ไม่ได้เข้าสู่ระบบ`,
  _ = `ข้อมูลโดยรวม`,
  _ = `รายชื่อการทดสอบทั้งหมดที่ดำเนินการในช่วงการตรวจสอบนี้และผลลัพธ์ที่ได้มีดังต่อไปนี้`,
  _ = `ด้านล่างนี้คือข้อมูลสรุปของการทดสอบแต่ละรายการและผลการจัดประเภทความเข้ากันได้`,
  _ = `ผลการทดสอบที่ทำให้เกมนี้ได้รับการระบุว่า "เล่นได้" แสดงอยู่ที่ด้านล่าง`,
  _ = `คุณสมบัติ`,
  _ = `ค่า`,
  _ = `คำอธิบาย`,
  _ = `นี่คือตัวอย่างลักษณะที่จะแสดงบนร้านค้าให้ผู้เล่นที่กำลังดูเกมของคุณเห็น การนำเสนอบนร้านค้าอาจเปลี่ยนแปลงได้ในอนาคต`,
  _ = `รายงานที่ผ่านมา`,
  _ = `ผลการทดสอบ`,
  _ = `ผลลัพธ์`,
  _ = `การทดสอบ`,
  _ = `ความเห็น`,
  _ = `ผลกระทบต่อการจัดประเภท`,
  _ = `ผ่าน`,
  _ = `ไม่ผ่าน`,
  _ = `ไม่ผ่าน`,
  _ = `---`,
  _ = `นี่เป็นรายงานประวัติจาก %1$s`,
  _ = `กำลังดูรายงานที่เผยแพร่อยู่ในขณะนี้`,
  _ = `เผยแพร่เมื่อ: %1$s`,
  _ = `รายงานเมื่อ: %1$s`,
  _ = `ดูเอกสาร`,
  _ = `เผยแพร่ผลลัพธ์เหล่านี้`,
  _ = `คุณต้องการเผยแพร่ผลลัพธ์การตรวจสอบความเข้ากันได้หรือไม่?`,
  _ = `คุณแน่ใจหรือไม่ว่าต้องการเผยแพร่ผลลัพธ์เหล่านี้? ผลลัพธ์ดังกล่าวจะแสดงให้เห็นบนหน้าร้านค้า Steam ในทันที`,
  _ = `ข้อผิดพลาดที่ไม่ทราบสาเหตุ -- โปรดลองใหม่อีกครั้ง`,
  _ = `คำขอการทดสอบ`,
  _ = `คำขอเปิดอยู่`,
  _ = `คำขอปิดแล้ว`,
  _ = `ดูรายละเอียดคำขอ`,
  _ = `หารือเกี่ยวกับรายงานนี้กับทีมงานทดสอบ`,
  _ = `กรอกคำถามหรือข้อคิดเห็นที่นี่`,
  _ = `โปรดอธิบายเกี่ยวกับการเปลี่ยนแปลงที่เกิดขึ้นกับบิลด์ใหม่ของคุณที่นี่`,
  _ = `หากบิลด์เกมของคุณบน Steam ได้รับการอัปเดตเพื่อแก้ไขปัญหาที่ระบุไว้ข้างต้นแล้ว โปรดเลือกแบรนช์และส่งอีกครั้งเพื่อรับการตรวจสอบ`,
  _ = `โปรดเลือกแบรนช์และส่งเพื่อรับการตรวจสอบความเข้ากันได้กับ Steam Deck อีกครั้ง ซึ่งจะมีการทดสอบ Steam Machine รวมอยู่ด้วย`,
  _ = `ส่งเพื่อรับการตรวจสอบอีกครั้ง`,
  _ = `หากคุณได้เปลี่ยนแปลงบิลด์ของเกมของคุณหลังจากการตรวจสอบครั้งที่ผ่านมา คุณสามารถขอรับการตรวจสอบความเข้ากันได้อีกครั้ง`,
  _ = `โปรดอธิบายเหตุผลที่คุณส่งคำขอให้ตรวจสอบอีกครั้งด้านล่าง สาเหตุที่พบบ่อยในการตรวจสอบอีกครั้งได้แก่:`,
  _ = `คุณได้ทำการเปลี่ยนแปลงบิลด์ของคุณเพื่อแก้ไขปัญหาการทดสอบที่ล้มเหลวจากการตรวจสอบความเข้ากันได้ก่อนหน้านี้ โปรดอธิบายเกี่ยวกับปัญหาที่เฉพาะเจาะจงที่คุณเชื่อว่าได้รับการแก้ไขแล้ว`,
  _ = `คุณได้จัดส่งหรือจะจัดส่งเวอร์ชันใหม่ของเกมของคุณ และต้องการให้มีการอัปเดตรายงาน`,
  _ = `การขอให้ทดสอบซ้ำโดยใช้แบรนช์ "%1$s" บิลด์เกมบน Steam ได้รับการอัปเดตเพื่อแก้ไขปัญหาที่ได้รายงานไว้แล้ว`,
  _ = `ประวัติการทดสอบ`,
  _ = `แสดงร้านค้า`,
  _ = `ความเข้ากันได้กับฮาร์ดแวร์: %1$s (%2$s)`,
  _ = `เผยแพร่แล้ว`,
  _ = `ยังไม่ได้เผยแพร่`,
  _ = `ประวัติ`,
  _ = `รันไทม์ที่แนะนำ`,
  _ = `เกมของคุณ (เนื้อหา/ตัวโปรแกรม) เวอร์ชันนี้ จะได้รับการจัดส่งไปให้ลูกค้าใช้งานบน Steam Deck ตามค่าเริ่มต้น`,
  _ = `รูปแบบอินพุตที่คาดไว้`,
  _ = `จำเป็นต้องใช้ H.264`,
  _ = `เวอร์ชัน Proton ที่ทดสอบ`,
  _ = `ไอดีบิลด์ทดสอบ`,
  _ = `การดีบัก RPO`,
  _ = `การดีบัก FDM`,
  _ = `การเปิดใช้งาน TSO`,
  _ = `เกมของคุณได้รับการระบุเป็น "ไม่ระบุ" บน %1$s เนื่องจากการทดสอบกับ %1$s ยังไม่เสร็จสมบูรณ์`,
  _ = `เกมของคุณไม่สามารถเล่นบน %1$s ได้ในขณะนี้`,
  _ = `เกมของคุณไม่ได้รับการรองรับอย่างเต็มรูปแบบบน %1$s เนื่องจากปัญหาเกี่ยวกับ Proton หรือ %1$s เอง เราได้บันทึกปัญหาเหล่านี้ไว้แล้วและจะดำเนินการแก้ไขต่อไป ในระหว่างนี้ เกมของคุณจะไม่สามารถเปิดหรือเล่นบน %1$s ได้อย่างถูกต้อง`,
  _ = `เกมของคุณ "เล่นได้" บน %1$s`,
  _ = `เกมของคุณเล่นได้บน %1$s แต่ลูกค้าต้องดำเนินการหรือกำหนดค่าเพิ่มเติม คุณสามารถแก้ไขปัญหาที่อธิบายไว้ด้านล่างและส่งเกมกลับมาให้ตรวจสอบความเข้ากันได้ใหม่อีกครั้ง`,
  _ = `เกมของคุณได้รับการระบุว่า "%1$s Verified" แล้ว!`,
  _ = `ขอแสดงความยินดีด้วย! เกมของคุณมอบประสบการณ์การเล่นที่ดีเยี่ยมบน %1$s และจะได้รับการนำเสนอในลักษณะดังกล่าวภายในร้านค้า Steam รวมถึงภายในคลัง Steam ของผู้เล่นบน %1$s ด้วย`,
  _ = `หากคุณต้องการแจ้งความสำเร็จนี้ให้แฟน ๆ ของคุณทราบ คุณสามารถใช้ลิงก์ที่จะนำไปยังหน้ารองรับสุดหรูนี้ได้: %1$s`,
  _ = `เกมของคุณยังไม่ได้รับการทดสอบบน Steam Machine`,
  _ = `เกมของคุณยังไม่ได้รับการทดสอบบน Steam Frame`,
  _ = `การทดสอบนี้ทำให้เกมของคุณได้รับการจัดประเภทเป็น "เล่นได้"`,
  _ = `การทดสอบนี้ทำให้เกมของคุณได้รับการจัดประเภทเป็น "ไม่รองรับ"`,
  _ = `ข้อความนี้จะแสดงเป็นข้อมูลสำหรับลูกค้า`,
  _ = `ไม่ถูกต้อง`,
  _ = `การเปิดโปรแกรมเริ่ม`,
  _ = `โปรแกรมเริ่ม`,
  _ = `คอนโทรลเลอร์ที่ใช้กับโปรแกรมเริ่มได้`,
  _ = `ข้อความของโปรแกรมเริ่ม`,
  _ = `คีย์บอร์ดของโปรแกรมเริ่ม`,
  _ = `คำเตือนเกี่ยวกับอุปกรณ์`,
  _ = `การเปิดเกม`,
  _ = `ผู้เล่นคนเดียว`,
  _ = `ผู้เล่นหลายคนในเครือข่าย`,
  _ = `ผู้เล่นหลายคนออนไลน์`,
  _ = `ป้องกันการโกง`,
  _ = `ป้องกันการโกง`,
  _ = `ป้องกันการโกง/ผู้เล่นหลายคน`,
  _ = `การกำหนดค่าคอนโทรลเลอร์เริ่มต้น`,
  _ = `คีย์บอร์ด`,
  _ = `ภาพสัญลักษณ์ของคอนโทรลเลอร์`,
  _ = `ประสิทธิภาพการกำหนดค่าเริ่มต้น`,
  _ = `จอแสดงผล`,
  _ = `เอาต์พุตวิดีโอ`,
  _ = `ความละเอียดแบบเนทีฟ`,
  _ = `ความชัดเจนของข้อความ`,
  _ = `ระบบเสียง`,
  _ = `เมนู`,
  _ = `การบันทึกบนคลาวด์ข้ามแพลตฟอร์ม`,
  _ = `ผู้เล่นคนเดียวออฟไลน์`,
  _ = `คอนโทรลเลอร์ภายนอก (ผู้เล่นหลัก)`,
  _ = `คอนโทรลเลอร์ภายนอก (ผู้เล่นหลายคนในเครือข่าย)`,
  _ = `การตั้งค่าครั้งแรก`,
  _ = `การตั้งค่าคอนโทรลเลอร์ครั้งแรก`,
  _ = `การตั้งค่าออฟไลน์ครั้งแรก`,
  _ = `ฟังก์ชันการทำงานของเกม`,
  _ = `VR`,
  _ = `หมายเหตุ`,
  _ = `ออกจากระบบโดยราบรื่น`,
  _ = `ออกจากระบบโดยราบรื่น (โปรแกรมเริ่ม)`,
  _ = `อินพุตแบบต่อเนื่องจากเกมแพด/เมาส์`,
  _ = `ฟังก์ชันการทำงานเสริม: เครื่องมือแก้ไขแผนที่`,
  _ = `รองรับตัวจำกัดเฟรม`,
  _ = `การโฟกัสหลายหน้าต่าง (โดยอัตโนมัติ)`,
  _ = `การโฟกัสหลายหน้าต่าง (ด้วยตัวเอง)`,
  _ = `ซอฟต์แวร์`,
  _ = `อินพุตแบบต่อเนื่องจากเกมแพด/เมาส์`,
  _ = `อินพุตข้อความ`,
  _ = `อินพุตเสียง`,
  _ = `กลับมาทำงานต่อจากโหมดสลีป`,
  _ = `แสดงเอาต์พุตที่ปรับขนาดแล้ว`,
  _ = `ลิงก์/เนื้อหาภายนอก`,
  _ = `เลิกใช้แล้ว`,
  _ = `ฟอนต์รองรับอักขระทั้งหมด`,
  _ = `แสดงการตั้งค่าที่บันทึกไว้ในแต่ละอุปกรณ์ ไม่ใช่บนคลาวด์`,
  _ = `การกำหนดค่าคอนโทรลเลอร์เริ่มต้น`,
  _ = `เปิดใช้งานคอนโทรลเลอร์เริ่มต้น`,
  _ = `เปิดใช้งานบันทึกบนคลาวด์ตามค่าเริ่มต้น`,
  _ = `อุปกรณ์ต่อพ่วง (คีย์บอร์ด)`,
  _ = `อุปกรณ์ต่อพ่วง (เว็บแคม)`,
  _ = `อุปกรณ์ต่อพ่วง (กีตาร์ USB)`,
  _ = `รองรับ HDR`,
  _ = `การรองรับระบบปฏิบัติการ`,
  _ = `ประสิทธิภาพการกำหนดค่าเริ่มต้นของ Steam Machine`,
  _ = `ประสิทธิภาพการสตรีม VR ของ Steam Machine`,
  _ = `รองรับการสตรีม VR ของ Steam Machine`,
  _ = `คำเตือนเกี่ยวกับอุปกรณ์ Steam Machine`,
  _ = `จอแสดงผล Steam Machine`,
  _ = `เสียงบน Steam Machine`,
  _ = `Steam Machine`,
  _ = `SteamOS`,
  _ = `Steam Deck`,
  _ = `Steam Frame (สแตนด์อโลน)`,
  _ = `โปรดขอรับการทดสอบ Steam Deck ซึ่งจะเริ่มการทดสอบการจัดประเภทความเข้ากันได้กับ %1$s`,
  _ = `ยินดีต้อนรับ! คุณสามารถส่งเกมของคุณเข้ารับการตรวจสอบความเข้ากันได้กับ Steam Frame (สแตนด์อโลน) ได้ที่นี่`,
  _ = `รายการตรวจสอบความเข้ากันได้กับ Steam Frame (สแตนด์อโลน) ด้วยตนเอง`,
  _ = `เราได้ระบุเกณฑ์ที่สำคัญที่สุดที่บางส่วนที่เราใช้ในการตรวจสอบเกมสำหรับความเข้ากันได้กับ Steam Frame ที่ด้านล่างนี้ โปรดกรอกแบบฟอร์มด้านล่างและระบุบิลด์/แบรนช์ของเกมที่คุณต้องการทดสอบ และเราจะเพิ่มเกมไว้ในคิวการตรวจสอบของเรา เมื่อตรวจสอบเสร็จสมบูรณ์แล้ว คุณจะได้รับอีเมลแจ้งเตือนพร้อมสรุป และหน้านี้จะได้รับการอัปเดตพร้อมผลการทดสอบโดยละเอียด`,
  _ = `หากต้องการทราบข้อมูลเพิ่มเติมเกี่ยวกับกระบวนการตรวจสอบ โปรดอ่าน%1$s`,
  _ = `กระบวนการตรวจสอบความเข้ากันได้กับ Steam Frame (สแตนด์อโลน)`,
  _ = `รายการต่อไปนี้เป็นรายการที่สำคัญที่สุดบางส่วนที่เราจะใช้ในการตรวจสอบ เพื่อจัดประเภทความเข้ากันได้ให้กับเกมของคุณ หากต้องการเริ่มกระบวนการตรวจสอบความเข้ากันได้กับ Steam Deck โปรดตอบคำถามต่อไปนี้ให้สมบูรณ์ที่สุดเท่าที่จะทำได้`,
  _ = `ไม่สามารถขอรับการตรวจสอบได้ก่อนที่เกมจะวางจำหน่าย`,
  _ = `เกมของคุณจะมอบประสบการณ์การเล่นที่ดีบน Steam Deck ให้ผู้เล่นหรือไม่? เรามีกระบวนการตรวจสอบ โดยทีมงานของเราจะเล่นและทดสอบเกมของคุณ หากสามารถมอบประสบการณ์ที่ราบรื่นให้กับผู้เล่นที่เล่นบน Steam Deck ได้ เกมของคุณจะได้รับแท็ก "Steam Deck Verified"`,
  _ = `ยินดีต้อนรับ! คุณสามารถส่งเกมของคุณเข้ารับการตรวจสอบความเข้ากันได้กับ Steam Deck ได้ที่นี่`,
  _ = `เราได้ระบุเกณฑ์ที่สำคัญที่สุดที่บางส่วนที่เราใช้ในการตรวจสอบเกมสำหรับความเข้ากันได้กับ Steam Deck ที่ด้านล่างนี้ โปรดกรอกแบบฟอร์มด้านล่างและระบุบิลด์/แบรนช์ของเกมที่คุณต้องการทดสอบ และเราจะเพิ่มเกมไว้ในคิวการตรวจสอบของเรา เมื่อตรวจสอบเสร็จสมบูรณ์แล้ว คุณจะได้รับอีเมลแจ้งเตือนพร้อมสรุป และหน้านี้จะได้รับการอัปเดตพร้อมผลการทดสอบโดยละเอียด`,
  _ = `คุณสามารถส่งเกมของคุณได้ แม้ว่าเกมนั้นจะไม่ตรงตามเกณฑ์ทั้งหมดที่จะได้รับการจัดประเภทเป็น "เล่นได้ดี ก็ตาม เราใช้ข้อมูลจากการทดสอบด้วยตนเองนี้เพื่อจัดลำดับความสำคัญของเกมที่จะได้รับการตรวจสอบ รวมถึงเพื่อสื่อสารเกี่ยวกับปัญหาความเข้ากันได้กับเกมของคุณอย่างชัดเจนที่สุดเท่าที่จะเป็นไปได้`,
  _ = `หากต้องการทราบข้อมูลเพิ่มเติมเกี่ยวกับกระบวนการตรวจสอบ โปรดอ่าน%1$s และ%2$s`,
  _ = `กระบวนการตรวจสอบความเข้ากันได้กับ Steam Deck`,
  _ = `คำแนะนำเพิ่มเติมเกี่ยวกับ Steam Deck`,
  _ = `รายการตรวจสอบความเข้ากันได้กับ Steam Deck ด้วยตนเอง`,
  _ = `รายการต่อไปนี้เป็นรายการที่สำคัญที่สุดบางส่วนที่เราจะใช้ในการตรวจสอบ เพื่อจัดประเภทความเข้ากันได้กับ Steam Deck ให้เกมของคุณ หากต้องการเริ่มกระบวนการตรวจสอบความเข้ากันได้กับ Steam Deck โปรดตอบคำถามต่อไปนี้ให้สมบูรณ์ที่สุดเท่าที่จะทำได้`,
  _ = `ขณะนี้กระบวนการตรวจสอบความเข้ากันได้กับ Steam Deck สามารถใช้ได้กับเกมเท่านั้น ไม่มีกระบวนการตรวจสอบความเข้ากันได้สำหรับแอปประเภทอื่น ๆ เช่น เนื้อหาดาวน์โหลด เครื่องมือ หรือเพลงประกอบ ยกเว้นในกรณีพิเศษ`,
  _ = `การรองรับคอนโทรลเลอร์`,
  _ = `การกรอกข้อความ`,
  _ = `จอแสดงผล`,
  _ = `ฟังก์ชันการทำงาน`,
  _ = `Steam Cloud`,
  _ = `โปรแกรมเริ่ม`,
  _ = `แบรนช์`,
  _ = `โปรดทดสอบโดยใช้แบรนช์นี้`,
  _ = `ทำเครื่องหมายเป็นพร้อมสำหรับการตรวจสอบ...`,
  _ = `เมื่อทำเช่นนี้ บิลด์ของคุณจะมีเครื่องหมายว่าพร้อมสำหรับการตรวจสอบความเข้ากันได้กับ Steam Deck คุณจะได้รับแจ้งผลลัพธ์ทางอีเมลภายในสองสามวัน`,
  _ = `คุณสามารถกรอกหมายเหตุไว้ด้านล่างเพื่อช่วยเร่งการทดสอบ หรือให้ข้อมูลรับรองบัญชีการทดสอบแก่เซิร์ฟเวอร์การเข้าสู่ระบบภายนอกได้`,
  _ = `กรอกหมายเหตุที่นี่`,
  _ = `คำขอความช่วยเหลือสำหรับการตรวจสอบนี้`,
  _ = `หากต้องการรายละเอียดเพิ่มเติม โปรดดูรายงานการทดสอบได้ในไซต์ความช่วยเหลือ`,
  _ = `สร้างตั๋วเพื่อติดต่อฝ่ายสนับสนุนเกี่ยวกับการตรวจสอบความเข้ากันได้กับ Steam Deck`,
  _ = `โปรดกรอกคำถามหรือข้อคิดเห็นสำหรับทีมงานทดสอบเมื่อคุณเปิดตั๋วเพื่อติดต่อฝ่ายสนับสนุน`,
  _ = `หากคุณมีคำถามเกี่ยวกับกระบวนการตรวจสอบความเข้ากันได้หรือผลลัพธ์สำหรับเกมของคุณโดยเฉพาะ โปรดกรอกคำถามเหล่านั้นด้านล่าง`,
  _ = `โปรดทราบว่าหากคุณต้องการให้เกมของคุณได้รับการตรวจสอบอีกครั้ง ให้ใช้ปุ่ม "ส่งเพื่อรับการตรวจสอบอีกครั้ง" ด้านล่าง ซึ่งจะมีประสิทธิภาพมากกว่าการถามคำถามที่นี่`,
  _ = `ฉันมีคำถามหรือข้อคิดเห็นเกี่ยวกับรายงานความเข้ากันได้กับ Steam Deck: `,
  _ = `ใช่ เกมของฉันรองรับคอนโทรลเลอร์เต็มรูปแบบ: สามารถเข้าถึงฟังก์ชันการทำงานทั้งหมดผ่านคอนโทรลเลอร์ได้ โดยใช้การกำหนดค่าเริ่มต้น`,
  _ = `ใช่ เกมของฉันแสดงคำแนะนำเกี่ยวกับ Steam Deck หรือคอนโทรลเลอร์ Xbox ไว้ในเกม เมื่อพูดถึงการกดปุ่มบนคอนโทรลเลอร์`,
  _ = `เลือกอย่างใดอย่างหนึ่ง: เกมของฉันไม่กำหนดว่าต้องมีการกรอกข้อความ หรือเกมของฉันจะเรียกใช้ API การกรอกข้อความบน Steam ตามความเหมาะสมเมื่อจำเป็น`,
  _ = `เกมของฉันไม่กำหนดว่าต้องมีการกรอกข้อความ`,
  _ = `เกมของฉันจะเรียกใช้ API คีย์บอร์ด/การกรอกข้อความบน Steam ตามความเหมาะสมเมื่อจำเป็นต้องให้ผู้ใช้กรอกข้อความ`,
  _ = `เกมของฉันไม่ใช้ API บน Steam เมื่อจำเป็นต้องให้ผู้ใช้กรอกข้อความ`,
  _ = `เกมของฉันไม่มีไฟล์บันทึกเกม`,
  _ = `เกมของฉันมีไฟล์บันทึกเกมแต่ไม่ได้ใช้ Steam Cloud กับไฟล์เหล่านั้น`,
  _ = `เกมของฉันใช้ Steam Cloud สำหรับไฟล์บันทึกเกม แต่มีเพียงแค่บิลด์สำหรับ Windows เท่านั้น`,
  _ = `เกมของฉันใช้ Steam Cloud สำหรับการบันทึกเกม และรองรับไฟล์บันทึกแบบข้ามแพลตฟอร์ม (เช่น Windows/Linux)`,
  _ = `เกมของฉันใช้ Steam Cloud สำหรับการบันทึกเกม แต่ไม่รองรับไฟล์บันทึกแบบข้ามแพลตฟอร์ม (เช่น Windows/Linux)`,
  _ = `ใช่ เกมของฉันสามารถใช้งานที่ความละเอียด 1280x800 (แนะนำ) หรือ 1280x720`,
  _ = `ใช่ ฟอนต์ตัวอักษรที่เล็กที่สุดบนหน้าจอในเกมของฉันมีความสูงไม่ต่ำกว่า 9 พิกเซล ที่ความละเอียด 1280x800`,
  _ = `เลือกอย่างใดอย่างหนึ่ง: เกมของฉันไม่มีโปรแกรมเริ่ม หรือโปรแกรมเริ่มของเกมของฉันใช้กับคอนโทรลเลอร์ได้อย่างเต็มรูปแบบ`,
  _ = `เลือกอย่างใดอย่างหนึ่ง: เกมของฉันรองรับ Steam Cloud สำหรับไฟล์บันทึกเกม หรือเกมของฉันไม่มีไฟล์บันทึกเกม`,
  _ = `เลือกอย่างใดอย่างหนึ่ง: เกมของฉันรองรับการบันทึกเกมข้ามแพลตฟอร์ม หรือเกมของฉันใช้งานได้บนแพลตฟอร์มเดียว (Linux/Windows)`,
  _ = `หากไม่ได้ระบุไว้เป็นอย่างอื่น เราจะทดสอบบิลด์ Windows ของคุณ ซึ่งใช้งานภายใต้ Proton`,
  _ = `หากเป็นไปได้ ให้ทดสอบบิลด์ Linux ของฉันแทนที่จะใช้บิลด์ Windows ของฉัน`,
  _ = `เกมของฉันไม่ได้ใช้โปรแกรมเริ่มหรือเครื่องมือการกำหนดค่าภายนอก`,
  _ = `เกมของฉันใช้โปรแกรมเริ่ม และโปรแกรมเริ่มดังกล่าวรองรับคอนโทรลเลอร์อย่างเต็มรูปแบบ`,
  _ = `เกมของฉันใช้โปรแกรมเริ่ม และโปรแกรมเริ่มดังกล่าวจะไม่ทำงานอย่างเต็มรูปแบบถ้าผู้ใช้มีแต่คอนโทรลเลอร์ แต่ไม่มีคีย์บอร์ดหรือเมาส์`,
  _ = `(แม้ว่าการบันทึกแบบข้ามแพลตฟอร์มจะไม่จำเป็นสำหรับเกมประเภท "เล่นได้ดี" แต่ก็เป็นประโยชน์อย่างมากสำหรับลูกค้าที่อาจเล่นเกมบน PC ที่ใช้ Windows ในบางครั้ง และเล่นบน Steam Deck ที่ทำงานด้วยบิลด์ Linux แบบเนทีฟในบางครั้งด้วย โปรดอ่าน%1$s)`,
  _ = `เอกสาร`,
  _ = `(หน้าจอของ Steam Deck มีขนาดเล็กกว่าจอแสดงผลของ PC ส่วนใหญ่ ดังนั้นหากข้อความในเกมของคุณมีขนาดเล็ก เมื่อแสดงบน Steam Deck อาจทำให้ลูกค้าอ่านข้อความดังกล่าวได้ยากหรือไม่สามารถอ่านได้ แม้ว่าจะสามารถอ่านได้ง่ายบนจอภาพทั่วไปก็ตาม)`,
  _ = `(Steam Deck ส่วนใหญ่จะไม่เชื่อมต่อกับคีย์บอร์ด ดังนั้นลูกค้าจะอาศัยคีย์บอร์ดบนหน้าจอในการกรอกข้อความ และ Steam มี API ที่ทำให้การใช้งานคีย์บอร์ดบนหน้าจอภายในตัวนั้นเป็นเรื่องง่าย หากลูกค้าต้องเปิดคีย์บอร์ดด้วยตนเอง เกมของคุณจะไม่ได้รับการจัดประเภทเป็น "เล่นได้ดี" โปรดอ่าน%1$s)`,
  _ = `คำแนะนำเกี่ยวกับอินพุต`,
  _ = `(หากเกมของคุณใช้โปรแกรมเริ่ม โปรแกรมเริ่มดังกล่าวจะต้องมีคุณสมบัติครบถ้วนสำหรับการจัดให้เป็นเกมที่ "เล่นได้ดี" เช่นเดียวกับตัวเกมเอง: ต้องใช้ได้อย่างเต็มรูปแบบแม้ว่าจะใช้คอนโทรลเลอร์ที่มาในตัว Steam Deck เท่านั้น ต้องอ่านได้ชัดเจน ฯลฯ หากโปรแกรมเริ่มของคุณมีคุณสมบัติไม่ตรงตามเกณฑ์เหล่านี้ เกมของคุณก็จะไม่สามารถได้รับการจัดให้เป็นเกมที่ "เล่นได้ดี" ได้ แม้ว่าตัวเกมเองจะมีคุณสมบัติครบถ้วนก็ตาม โปรดอ่าน%1$s)`,
  _ = `คำแนะนำเกี่ยวกับโปรแกรมเริ่ม`,
  _ = `(ลูกค้าจำนวนมากที่ใช้ Steam Deck ก็เป็นลูกค้าที่ใช้เดสก์ท็อป PC ด้วยเช่นกัน แม้ว่าเกมจะไม่จำเป็นต้องมีบันทึกบน Cloud จึงจะได้รับการจัดให้เป็นเกมที่ "เล่นได้ดี" แต่บันทึกบน Cloud ก็เป็นประโยชน์ต่อลูกค้า: การเพิ่มการรองรับ %1$s สำหรับเกมจะช่วยให้ลูกค้าสามารถบันทึกเกมของตนไว้บนเดสก์ท็อปและเล่นต่อบน Steam Deck หรือในทางกลับกันได้)`,
  _ = `Steam Cloud`,
  _ = `(หมายเหตุ: ต้องมีการรองรับคอนโทรลเลอร์อย่างเต็มรูปแบบจึงจะได้รับการจัดประเภทเป็น "เล่นได้ดี)`,
  _ = `เกมของคุณได้เพิ่มเข้าไปในคิวการตรวจสอบของเราแล้ว`,
  _ = `เราจะตรวจสอบเกมของคุณในเร็ว ๆ นี้ และจะแจ้งให้คุณทราบหากมีปัญหาใด ๆ`,
  _ = `โปรดตรวจสอบบิลด์ของคุณบน Steam ให้เสร็จสมบูรณ์ก่อนส่งเพื่อรับการตรวจสอบความเข้ากันได้กับฮาร์ดแวร์`,
  _ = `เกมของคุณไม่สามารถเล่นบน Steam Deck ได้ในขณะนี้`,
  _ = `เกมของคุณไม่ได้รับการรองรับอย่างเต็มรูปแบบบน Steam Deck เนื่องจากปัญหาเกี่ยวกับ Proton หรือ Steam Deck เอง เราได้บันทึกปัญหาเหล่านี้ไว้แล้ว และจะดำเนินการแก้ไขต่อไป ในระหว่างนี้ เกมของคุณจะไม่สามารถเปิดหรือเล่นบน Steam Deck ได้อย่างถูกต้อง`,
  _ = `เกมของคุณ "เล่นได้" บน Steam Deck`,
  _ = `เกมของคุณเล่นได้บน Steam Deck แต่ลูกค้าต้องดำเนินการหรือกำหนดค่าเพิ่มเติม คุณสามารถแก้ไขปัญหาที่อธิบายไว้ด้านล่างและส่งเกมกลับมาให้ตรวจสอบความเข้ากันได้กับ Steam Deck ใหม่อีกครั้ง`,
  _ = `บิลด์`,
  _ = `หากเป็นไปได้ ให้ทดสอบบิลด์ Android ของฉันแทนที่จะใช้บิลด์ Windows ของฉัน`,
  _ = `ทดสอบบิลด์ Windows ของฉัน`,
  _ = `ทดสอบบิลด์ Linux ของฉัน`,
  _ = `เราควรทดสอบประสบการณ์ในรูปแบบ 2 มิติ หรือ VR (หากมี)?`,
  _ = `2 มิติ`,
  _ = `VR`,
  _ = `ไม่สามารถใช้ได้กับเกม %1$s`,
  _ = `VERIFIED (เล่นได้ดี) โดยไม่ใช้ "ล้างสถานะการประเมินประสิทธิภาพ"`,
  _ = `VERIFIED (เล่นได้ดี) โดยใช้ "ล้างสถานะการประเมินประสิทธิภาพ" อย่างน้อย 1 ครั้ง`,
  _ = `PLAYABLE (เล่นได้) โดยไม่ใช้ "ล้างสถานะการประเมินประสิทธิภาพ"`,
  _ = `PLAYABLE (เล่นได้) โดยใช้ "ล้างสถานะการประเมินประสิทธิภาพ" อย่างน้อย 1 ครั้ง`,
  _ = `ไม่รองรับ`,
  _ = `ไม่ใช่เกม VR (ไม่ต้องมีการประเมิน)`,
  _ = `โอเวอร์เลย์การประเมินประสิทธิภาพ`,
  _ = `ใช้โอเวอร์เลย์การประเมินประสิทธิภาพเพื่อกรอกคำตอบด้านล่าง ดูข้อมูลเพิ่มเติมใน%1$s`,
  _ = `เอกสารเกี่ยวกับประสิทธิภาพของ VR`,
  _ = `(หากข้อความในเกมของคุณมีขนาดเล็ก ก็อาจทำให้ลูกค้าอ่านข้อความดังกล่าวได้ยากหรือไม่สามารถอ่านได้เมื่อแสดงบน Steam Frame แม้ว่าจะสามารถอ่านได้ง่ายบนจอภาพทั่วไปก็ตาม)`,
  _ = `(Steam Frame ส่วนใหญ่จะไม่เชื่อมต่อกับคีย์บอร์ด ดังนั้นลูกค้าจะอาศัยคีย์บอร์ดบนหน้าจอในการกรอกข้อความ และ Steam มี API ที่ทำให้การใช้งานคีย์บอร์ดบนหน้าจอภายในตัวนั้นเป็นเรื่องง่าย หากลูกค้าต้องเปิดคีย์บอร์ดด้วยตนเอง เกมของคุณจะไม่ได้รับการจัดประเภทเป็น "เล่นได้ดี" โปรดอ่าน%1$s)`,
  _ = `รายการตรวจสอบความเข้ากันได้กับ Steam Frame`,
  _ = `(หากเกมของคุณใช้โปรแกรมเริ่ม โปรแกรมเริ่มดังกล่าวจะต้องมีคุณสมบัติครบถ้วนสำหรับการจัดให้เป็นเกมที่ "เล่นได้ดี" เช่นเดียวกับตัวเกมเอง: ต้องใช้ได้อย่างเต็มรูปแบบแม้ว่าจะใช้คอนโทรลเลอร์ที่มาในตัว Steam Frame เท่านั้น ต้องอ่านได้ชัดเจน ฯลฯ หากโปรแกรมเริ่มของคุณมีคุณสมบัติไม่ตรงตามเกณฑ์เหล่านี้ เกมของคุณก็จะไม่สามารถได้รับการจัดให้เป็นเกมที่ "เล่นได้ดี" ได้ แม้ว่าตัวเกมเองจะมีคุณสมบัติครบถ้วนก็ตาม โปรดอ่าน%1$s)`,
  _ = `(ลูกค้าจำนวนมากที่ใช้ Steam Frame ก็เป็นลูกค้าที่ใช้เดสก์ท็อป PC ด้วยเช่นกัน แม้ว่าเกมจะไม่จำเป็นต้องมีบันทึกบน Cloud จึงจะได้รับการจัดให้เป็นเกมที่ "เล่นได้ดี" แต่บันทึกบน Cloud ก็เป็นประโยชน์ต่อลูกค้า: การเพิ่มการรองรับ %1$s สำหรับเกมจะช่วยให้ลูกค้าสามารถบันทึกเกมของตนไว้บนเดสก์ท็อปและเล่นต่อบน Steam Frame หรือในทางกลับกันได้)`,
  _ = `(แม้ว่าการบันทึกแบบข้ามแพลตฟอร์มจะไม่จำเป็นสำหรับเกมประเภท "เล่นได้ดี" แต่ก็เป็นประโยชน์อย่างมากสำหรับลูกค้าที่อาจเล่นเกมบน PC ที่ใช้ Windows ในบางครั้ง และเล่นบน Steam Frame ที่ทำงานด้วยบิลด์ Linux แบบเนทีฟในบางครั้งด้วย โปรดอ่าน%1$s)`,
  _ = `ใช่ เกมของฉันแสดงคำแนะนำเกี่ยวกับ Steam Frame/Steam Deck หรือคอนโทรลเลอร์ Xbox ไว้ในเกม เมื่อพูดถึงการกดปุ่มบนคอนโทรลเลอร์`,
  _ = `หากผลลัพธ์ของการประเมินประสิทธิภาพข้างต้นจำเป็นต้องใช้ "ล้างสถานะการประเมินประสิทธิภาพ" อย่างน้อย 1 ครั้ง โปรดเลือกเหตุผลอย่างน้อย 1 ข้อด้านล่าง`,
  _ = `ประสิทธิภาพลดลงเมื่อเริ่มเกม`,
  _ = `ประสิทธิภาพลดลงขณะโหลดหน้าจอ`,
  _ = `อื่น ๆ (โปรดระบุ)`,
  _ = `คุณได้ส่งคำขอให้ตรวจสอบเวอร์ชัน Android แต่%1$sไม่ได้เป็นเจ้าของดีโป Android ใด ๆ`,
  _ = `แพ็กเกจของแถมสำหรับผู้พัฒนาของคุณ`,
  _ = `dummy`,
  _ = {
    Valve_Confidential: _,
    Valve_Confidential_Description: _,
    Footer_Description: _,
    Footer_Sitemap_ContactSupport: _,
    PricingExplorer_LoadError: _,
    PricingExplorer_About_Title: _,
    PricingExplorer_About_Desc1: _,
    PricingExplorer_About_Desc2: _,
    PricingExplorer_About_Link1: _,
    PricingExplorer_About_LinkName1: _,
    PricingExplorer_About_Link2: _,
    PricingExplorer_About_LinkName2: _,
    PricingExplorer_About_Dash: _,
    PricingExplorer_About_LastUpdated: _,
    PricingExplorer_Explore_title: _,
    PricingExplorer_Explore_desc1: _,
    PricingExplorer_Explore_line1: _,
    PricingExplorer_Explore_line2: _,
    PricingExplorer_Explore_line3: _,
    PricingExplorer_Base: _,
    PricingExplorer_BasePrice: _,
    PricingExplorer_TableHeader: _,
    PricingExplorer_Column1: _,
    PricingExplorer_Column2: _,
    PricingExplorer_Column3: _,
    PricingExplorer_Column4: _,
    PricingExplorer_Regions_TableHeader: _,
    PricingExplorer_Regions_Column1: _,
    Pricing_Dummy: _,
    ContentSurvey_Title: _,
    ContentSurvey_Title_Default: _,
    ContentSurvey_History_Title: _,
    ContentSurvey_History_Title_Default: _,
    ContentSurvey_InvalidApp: _,
    PartnerSite_PermissionDenied: _,
    PartnerSite_NotLoggedIn: _,
    SteamDeck_BuildReview_Status_Raw_Title: _,
    SteamDeck_BuildReview_Status_Raw_Description: _,
    SteamDeck_BuildReview_Status_TestProperties_Description: _,
    SteamDeck_BuildReview_Status_TestProperties_Playable: _,
    SteamDeck_BuildReview_Status_TestProperty_Name: _,
    SteamDeck_BuildReview_Status_TestProperty_Value: _,
    SteamDeck_BuildReview_Status_TestProperty_Desc: _,
    SteamDeck_BuildReview_Status_Description: _,
    SteamDeck_BuildReview_Header_History: _,
    SteamDeck_BuildReview_Header_Results: _,
    SteamDeck_BuildReview_Status_Raw_Result: _,
    SteamDeck_BuildReview_Status_Raw_Test: _,
    SteamDeck_BuildReview_Status_Raw_Comment: _,
    SteamDeck_BuildReview_Status_Raw_Impact: _,
    SteamDeck_BuildReview_Status_Pass: _,
    SteamDeck_BuildReview_Status_Fail: _,
    SteamDeck_BuildReview_Status_FailMinor: _,
    SteamDeck_BuildReview_Status_NotApplicable: `---`,
    SteamDeck_BuildReview_Viewing_Historical: _,
    SteamDeck_BuildReview_Viewing_Published: _,
    SteamDeck_BuildReview_PublishedOn: _,
    SteamDeck_BuildReview_ReportedOn: _,
    SteamDeck_BuildReview_Documentation: _,
    SteamDeck_BuildReview_PublishResults: _,
    SteamDeck_BuildReview_PublishDialog_Title: _,
    SteamDeck_BuildReview_PublishDialog_Body: _,
    SteamDeck_BuildReview_UnknownError: _,
    SteamDeck_BuildReview_Help_Request_Title: _,
    SteamDeck_BuildReview_RequestStatusActive: _,
    SteamDeck_BuildReview_RequestStatusClosed: _,
    SteamDeck_BuildReview_InReview_ViewTicket: _,
    SteamDeck_BuildReview_Create_HelpRequest: _,
    SteamDeck_BuildReview_Create_HelpRequest_NotesDefault: _,
    SteamDeck_BuildReview_Create_HelpRequest_NotesDefault_Rereview: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label_Machine: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Button: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_1: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2a: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2b: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Ticket_Content: _,
    SteamDeck_BuildReview_CompatibilityTests: _,
    SteamDeck_BuildReview_Status_Title: _,
    SteamDeck_HardwareCompatibility_Title: _,
    SteamDeck_AppLanding_Published: _,
    SteamDeck_AppLanding_Unpublished: _,
    SteamDeck_AppLanding_History: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RecommendedRuntime: _,
    SteamDeckVerified_TestDisplayName_TestPropertyDescription_RecommendedRuntime:
      _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_ExpectedInput: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RequiresH264: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TestedProtonVersion: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TestedBuildID: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RPODebug: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_FDMDebug: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TSOEnable: _,
    SteamHardware_BuildReview_Unknown_Title: _,
    SteamHardware_BuildReview_Unsupported_Title: _,
    SteamHardware_BuildReview_Unsupported_Description: _,
    SteamHardware_BuildReview_Playable_Title: _,
    SteamHardware_BuildReview_Playable_Description: _,
    SteamHardware_BuildReview_Verified_Title: _,
    SteamHardware_BuildReview_Verified_Description: _,
    SteamHardware_BuildReview_Verified_Share: _,
    SteamHardware_Machine_Unknown: _,
    SteamHardware_Frame_Unknown: _,
    SteamHardware_RatingImpact_Playable: _,
    SteamHardware_RatingImpact_Unsupported: _,
    SteamHardware_RatingImpact_Informational: _,
    SteamDeckVerified_TestDisplayName_0: _,
    SteamDeckVerified_TestDisplayName_1: _,
    SteamDeckVerified_TestDisplayName_2: _,
    SteamDeckVerified_TestDisplayName_3: _,
    SteamDeckVerified_TestDisplayName_4: _,
    SteamDeckVerified_TestDisplayName_5: _,
    SteamDeckVerified_TestDisplayName_6: _,
    SteamDeckVerified_TestDisplayName_7: _,
    SteamDeckVerified_TestDisplayName_8: _,
    SteamDeckVerified_TestDisplayName_9: _,
    SteamDeckVerified_TestDisplayName_10: _,
    SteamDeckVerified_TestDisplayName_11: _,
    SteamDeckVerified_TestDisplayName_12: _,
    SteamDeckVerified_TestDisplayName_13: _,
    SteamDeckVerified_TestDisplayName_14: _,
    SteamDeckVerified_TestDisplayName_15: _,
    SteamDeckVerified_TestDisplayName_16: _,
    SteamDeckVerified_TestDisplayName_17: _,
    SteamDeckVerified_TestDisplayName_18: _,
    SteamDeckVerified_TestDisplayName_19: _,
    SteamDeckVerified_TestDisplayName_20: _,
    SteamDeckVerified_TestDisplayName_21: _,
    SteamDeckVerified_TestDisplayName_22: _,
    SteamDeckVerified_TestDisplayName_23: _,
    SteamDeckVerified_TestDisplayName_24: _,
    SteamDeckVerified_TestDisplayName_25: _,
    SteamDeckVerified_TestDisplayName_26: _,
    SteamDeckVerified_TestDisplayName_27: _,
    SteamDeckVerified_TestDisplayName_29: _,
    SteamDeckVerified_TestDisplayName_30: _,
    SteamDeckVerified_TestDisplayName_31: _,
    SteamDeckVerified_TestDisplayName_32: _,
    SteamDeckVerified_TestDisplayName_33: `VR`,
    SteamDeckVerified_TestDisplayName_34: _,
    SteamDeckVerified_TestDisplayName_35: _,
    SteamDeckVerified_TestDisplayName_36: _,
    SteamDeckVerified_TestDisplayName_37: _,
    SteamDeckVerified_TestDisplayName_38: _,
    SteamDeckVerified_TestDisplayName_39: _,
    SteamDeckVerified_TestDisplayName_40: _,
    SteamDeckVerified_TestDisplayName_41: _,
    SteamDeckVerified_TestDisplayName_42: _,
    SteamDeckVerified_TestDisplayName_43: _,
    SteamDeckVerified_TestDisplayName_44: _,
    SteamDeckVerified_TestDisplayName_45: _,
    SteamDeckVerified_TestDisplayName_46: _,
    SteamDeckVerified_TestDisplayName_47: _,
    SteamDeckVerified_TestDisplayName_48: _,
    SteamDeckVerified_TestDisplayName_49: _,
    SteamDeckVerified_TestDisplayName_50: _,
    SteamDeckVerified_TestDisplayName_51: _,
    SteamDeckVerified_TestDisplayName_52: _,
    SteamDeckVerified_TestDisplayName_53: _,
    SteamDeckVerified_TestDisplayName_54: _,
    SteamDeckVerified_TestDisplayName_55: _,
    SteamDeckVerified_TestDisplayName_56: _,
    SteamDeckVerified_TestDisplayName_57: _,
    SteamDeckVerified_TestDisplayName_58: _,
    SteamDeckVerified_TestDisplayName_59: _,
    SteamDeckVerified_TestDisplayName_60: _,
    SteamDeckVerified_TestDisplayName_61: _,
    SteamDeckVerified_TestDisplayName_62: _,
    SteamDeckVerified_TestDisplayName_63: _,
    SteamDeckVerified_TestDisplayName_64: _,
    SteamDeckVerified_TestDisplayName_65: _,
    Compatibility_Tab_Steam_Machine: _,
    Compatibility_Tab_Steam_OS: _,
    Compatibility_Tab_Steam_Deck: _,
    Compatibility_Tab_Steam_Frame: _,
    SteamDeck_BuildReview_PleaseRequestTest: _,
    SteamFrame_BuildReview_Checklist_Intro_Header_V2: _,
    SteamFrame_BuildReview_PleaseConfirm_Title_V2: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P1: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P3: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P3_ReviewProcess: _,
    SteamFrame_BuildReview_PleaseConfirm_Description_V2: _,
    SteamDeck_TestRequest_BuildNotReleased: _,
    SteamDeck_BuildReview_Checklist_Intro: _,
    SteamDeck_BuildReview_Checklist_Intro_Header_V2: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P1: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P2: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3_ReviewProcess: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3_Additional: _,
    SteamDeck_BuildReview_PleaseConfirm_Title_V2: _,
    SteamDeck_BuildReview_PleaseConfirm_Description_V2: _,
    SteamDeck_BuildReview_AppTypeUnavailable: _,
    SteamDeck_BuildReview_Checklist_Input: _,
    SteamDeck_BuildReview_Checklist_Text: _,
    SteamDeck_BuildReview_Checklist_Display: _,
    SteamDeck_BuildReview_Checklist_Functionality: _,
    SteamDeck_BuildReview_Checklist_SteamCloud: _,
    SteamDeck_BuildReview_Checklist_Launcher: _,
    SteamDeck_BuildReview_Checklist_Branch: _,
    SteamDeck_BuildReview_Checklist_Branch_PleaseTest: _,
    SteamDeck_BuildReview_MarkReady_Button: _,
    SteamDeck_BuildReview_MarkReady_Description: _,
    SteamDeck_BuildReview_MarkReady_Notes: _,
    SteamDeck_BuildReview_MarkReady_NotesDefault: _,
    SteamDeck_BuildReview_HelpRequest_Link: _,
    SteamDeck_BuildReview_ViewMoreDetailsInHelp: _,
    SteamDeck_BuildReview_Create_HelpRequest_Title: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes_1: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes_2: _,
    SteamDeck_BuildReview_Create_HelpRequest_SupportTicketIntro: _,
    SteamDeck_BuildReview_Check_Controller: _,
    SteamDeck_BuildReview_Check_Icons: _,
    SteamDeck_BuildReview_Check_TextInput: _,
    SteamDeck_BuildReview_Check_TextInput_V2_NoTextEntry: _,
    SteamDeck_BuildReview_Check_TextInput_V2_YesSteamAPIs: _,
    SteamDeck_BuildReview_Check_TextInput_V2_NoSteamAPIs: _,
    SteamDeck_BuildReview_Check_Cloud_NoSaves: _,
    SteamDeck_BuildReview_Check_Cloud_YesSavesNoCloud: _,
    SteamDeck_BuildReview_Check_Cloud_SinglePlatform: _,
    SteamDeck_BuildReview_Check_Cloud_YesCrossSaves: _,
    SteamDeck_BuildReview_Check_Cloud_NoCrossSaves: _,
    SteamDeck_BuildReview_Check_Display1280: _,
    SteamDeck_BuildReview_Check_DisplayFont: _,
    SteamDeck_BuildReview_Check_FunctionalityLauncher: _,
    SteamDeck_BuildReview_Check_FunctionalityCloudSaves: _,
    SteamDeck_BuildReview_Check_FunctionalityCrossPlatformCloudSaves: _,
    SteamDeck_BuildReview_Check_TestLinuxBuild_Preamble: _,
    SteamDeck_BuildReview_Check_TestLinuxBuild: _,
    SteamDeck_BuildReview_Check_Launcher_V2_NoLauncher: _,
    SteamDeck_BuildReview_Check_Launcher_V2_ControllerSupport: _,
    SteamDeck_BuildReview_Check_Launcher_V2_NoControllerSupport: _,
    SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves: _,
    SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves_Documentation: _,
    SteamDeck_BuildReview_CheckNote_DisplayFont: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_InputRecommendations:
      _,
    SteamDeck_BuildReview_CheckNote_Launcher_V2_NoControllerSupport: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_LauncherRecommendations:
      _,
    SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud: _,
    SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud_SteamCloud: _,
    SteamDeck_BuildReview_CheckNote_FullController: _,
    SteamDeck_BuildReview_InReview_Title: _,
    SteamDeck_BuildReview_InReview_Description: _,
    SteamDeck_BuildReview_PleaseComplete: _,
    SteamDeck_BuildReview_Unsupported_Title: _,
    SteamDeck_BuildReview_Unsupported_Description: _,
    SteamDeck_BuildReview_NotMeetRequirements_Title: _,
    SteamDeck_BuildReview_NotMeetRequirements_Description: _,
    SteamFrame_BuildReview_Checklist_Build: _,
    SteamFrame_BuildReview_Build_Android: _,
    SteamFrame_BuildReview_Build_Windows: _,
    SteamFrame_BuildReview_Build_Linux: _,
    SteamFrame_BuildReview_Checklist_Dimension: _,
    SteamFrame_BuildReview_Dimension_2D: _,
    SteamFrame_BuildReview_Dimension_VR: `VR`,
    SteamFrame_NotApplicableForDimension: _,
    SteamFrame_BuildReview_Check_VRPerformance_Verified_Without: _,
    SteamFrame_BuildReview_Check_VRPerformance_Verified_With: _,
    SteamFrame_BuildReview_Check_VRPerformance_Playable_Without: _,
    SteamFrame_BuildReview_Check_VRPerformance_Playable_With: _,
    SteamFrame_BuildReview_Check_VRPerformance_Unsupported: _,
    SteamFrame_BuildReview_Check_VRPerformance_NotApplicable: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_Title: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_Description: _,
    SteamFrame_BuildReview_VRPerformanceLink: _,
    SteamFrame_BuildReview_CheckNote_DisplayFont: _,
    SteamFrame_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs: _,
    SteamFrame_BuildReview_Compatibility_Checklist: _,
    SteamFrame_BuildReview_CheckNote_Launcher_V2_NoControllerSupport: _,
    SteamFrame_BuildReview_CheckNote_Cloud_YesSavesNoCloud: _,
    SteamFrame_BuildReview_CheckNote_Cloud_NoCrossSaves: _,
    SteamFrame_BuildReview_Check_Icons: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_StatusReason: _,
    SteamFrame_BuildReview_Check_VRPerformance_Startup: _,
    SteamFrame_BuildReview_Check_VRPerformance_Loading: _,
    SteamFrame_BuildReview_Check_VRPerformance_Other: _,
    SteamFrame_BuildReview_CheckNote_Missing_Android_License: _,
    SteamFrame_BuildReview_CheckNote_Missing_Android_License_Link: _,
    dummy: _,
  };
export {
  _ as Compatibility_Tab_Steam_Deck,
  _ as Compatibility_Tab_Steam_Frame,
  _ as Compatibility_Tab_Steam_Machine,
  _ as Compatibility_Tab_Steam_OS,
  _ as ContentSurvey_History_Title,
  _ as ContentSurvey_History_Title_Default,
  _ as ContentSurvey_InvalidApp,
  _ as ContentSurvey_Title,
  _ as ContentSurvey_Title_Default,
  _ as Footer_Description,
  _ as Footer_Sitemap_ContactSupport,
  _ as PartnerSite_NotLoggedIn,
  _ as PartnerSite_PermissionDenied,
  _ as PricingExplorer_About_Dash,
  _ as PricingExplorer_About_Desc1,
  _ as PricingExplorer_About_Desc2,
  _ as PricingExplorer_About_LastUpdated,
  _ as PricingExplorer_About_Link1,
  _ as PricingExplorer_About_Link2,
  _ as PricingExplorer_About_LinkName1,
  _ as PricingExplorer_About_LinkName2,
  _ as PricingExplorer_About_Title,
  _ as PricingExplorer_Base,
  _ as PricingExplorer_BasePrice,
  _ as PricingExplorer_Column1,
  _ as PricingExplorer_Column2,
  _ as PricingExplorer_Column3,
  _ as PricingExplorer_Column4,
  _ as PricingExplorer_Explore_desc1,
  _ as PricingExplorer_Explore_line1,
  _ as PricingExplorer_Explore_line2,
  _ as PricingExplorer_Explore_line3,
  _ as PricingExplorer_Explore_title,
  _ as PricingExplorer_LoadError,
  _ as PricingExplorer_Regions_Column1,
  _ as PricingExplorer_Regions_TableHeader,
  _ as PricingExplorer_TableHeader,
  _ as Pricing_Dummy,
  _ as SteamDeckVerified_TestDisplayName_0,
  _ as SteamDeckVerified_TestDisplayName_1,
  _ as SteamDeckVerified_TestDisplayName_10,
  _ as SteamDeckVerified_TestDisplayName_11,
  _ as SteamDeckVerified_TestDisplayName_12,
  _ as SteamDeckVerified_TestDisplayName_13,
  _ as SteamDeckVerified_TestDisplayName_14,
  _ as SteamDeckVerified_TestDisplayName_15,
  _ as SteamDeckVerified_TestDisplayName_16,
  _ as SteamDeckVerified_TestDisplayName_17,
  _ as SteamDeckVerified_TestDisplayName_18,
  _ as SteamDeckVerified_TestDisplayName_19,
  _ as SteamDeckVerified_TestDisplayName_2,
  _ as SteamDeckVerified_TestDisplayName_20,
  _ as SteamDeckVerified_TestDisplayName_21,
  _ as SteamDeckVerified_TestDisplayName_22,
  _ as SteamDeckVerified_TestDisplayName_23,
  _ as SteamDeckVerified_TestDisplayName_24,
  _ as SteamDeckVerified_TestDisplayName_25,
  _ as SteamDeckVerified_TestDisplayName_26,
  _ as SteamDeckVerified_TestDisplayName_27,
  _ as SteamDeckVerified_TestDisplayName_29,
  _ as SteamDeckVerified_TestDisplayName_3,
  _ as SteamDeckVerified_TestDisplayName_30,
  _ as SteamDeckVerified_TestDisplayName_31,
  _ as SteamDeckVerified_TestDisplayName_32,
  _ as SteamDeckVerified_TestDisplayName_33,
  _ as SteamDeckVerified_TestDisplayName_34,
  _ as SteamDeckVerified_TestDisplayName_35,
  _ as SteamDeckVerified_TestDisplayName_36,
  _ as SteamDeckVerified_TestDisplayName_37,
  _ as SteamDeckVerified_TestDisplayName_38,
  _ as SteamDeckVerified_TestDisplayName_39,
  _ as SteamDeckVerified_TestDisplayName_4,
  _ as SteamDeckVerified_TestDisplayName_40,
  _ as SteamDeckVerified_TestDisplayName_41,
  _ as SteamDeckVerified_TestDisplayName_42,
  _ as SteamDeckVerified_TestDisplayName_43,
  _ as SteamDeckVerified_TestDisplayName_44,
  _ as SteamDeckVerified_TestDisplayName_45,
  _ as SteamDeckVerified_TestDisplayName_46,
  _ as SteamDeckVerified_TestDisplayName_47,
  _ as SteamDeckVerified_TestDisplayName_48,
  _ as SteamDeckVerified_TestDisplayName_49,
  _ as SteamDeckVerified_TestDisplayName_5,
  _ as SteamDeckVerified_TestDisplayName_50,
  _ as SteamDeckVerified_TestDisplayName_51,
  _ as SteamDeckVerified_TestDisplayName_52,
  _ as SteamDeckVerified_TestDisplayName_53,
  _ as SteamDeckVerified_TestDisplayName_54,
  _ as SteamDeckVerified_TestDisplayName_55,
  _ as SteamDeckVerified_TestDisplayName_56,
  _ as SteamDeckVerified_TestDisplayName_57,
  _ as SteamDeckVerified_TestDisplayName_58,
  _ as SteamDeckVerified_TestDisplayName_59,
  _ as SteamDeckVerified_TestDisplayName_6,
  _ as SteamDeckVerified_TestDisplayName_60,
  _ as SteamDeckVerified_TestDisplayName_61,
  _ as SteamDeckVerified_TestDisplayName_62,
  _ as SteamDeckVerified_TestDisplayName_63,
  _ as SteamDeckVerified_TestDisplayName_64,
  _ as SteamDeckVerified_TestDisplayName_65,
  _ as SteamDeckVerified_TestDisplayName_7,
  _ as SteamDeckVerified_TestDisplayName_8,
  _ as SteamDeckVerified_TestDisplayName_9,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyDescription_RecommendedRuntime,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_ExpectedInput,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_FDMDebug,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RPODebug,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RecommendedRuntime,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RequiresH264,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TSOEnable,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TestedBuildID,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TestedProtonVersion,
  _ as SteamDeck_AppLanding_History,
  _ as SteamDeck_AppLanding_Published,
  _ as SteamDeck_AppLanding_Unpublished,
  _ as SteamDeck_BuildReview_AppTypeUnavailable,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves_Documentation,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud_SteamCloud,
  _ as SteamDeck_BuildReview_CheckNote_DisplayFont,
  _ as SteamDeck_BuildReview_CheckNote_FullController,
  _ as SteamDeck_BuildReview_CheckNote_Launcher_V2_NoControllerSupport,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_InputRecommendations,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_LauncherRecommendations,
  _ as SteamDeck_BuildReview_Check_Cloud_NoCrossSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_NoSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_SinglePlatform,
  _ as SteamDeck_BuildReview_Check_Cloud_YesCrossSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_YesSavesNoCloud,
  _ as SteamDeck_BuildReview_Check_Controller,
  _ as SteamDeck_BuildReview_Check_Display1280,
  _ as SteamDeck_BuildReview_Check_DisplayFont,
  _ as SteamDeck_BuildReview_Check_FunctionalityCloudSaves,
  _ as SteamDeck_BuildReview_Check_FunctionalityCrossPlatformCloudSaves,
  _ as SteamDeck_BuildReview_Check_FunctionalityLauncher,
  _ as SteamDeck_BuildReview_Check_Icons,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_ControllerSupport,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_NoControllerSupport,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_NoLauncher,
  _ as SteamDeck_BuildReview_Check_TestLinuxBuild,
  _ as SteamDeck_BuildReview_Check_TestLinuxBuild_Preamble,
  _ as SteamDeck_BuildReview_Check_TextInput,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_NoSteamAPIs,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_NoTextEntry,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_YesSteamAPIs,
  _ as SteamDeck_BuildReview_Checklist_Branch,
  _ as SteamDeck_BuildReview_Checklist_Branch_PleaseTest,
  _ as SteamDeck_BuildReview_Checklist_Display,
  _ as SteamDeck_BuildReview_Checklist_Functionality,
  _ as SteamDeck_BuildReview_Checklist_Input,
  _ as SteamDeck_BuildReview_Checklist_Intro,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P1,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P2,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3_Additional,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3_ReviewProcess,
  _ as SteamDeck_BuildReview_Checklist_Intro_Header_V2,
  _ as SteamDeck_BuildReview_Checklist_Launcher,
  _ as SteamDeck_BuildReview_Checklist_SteamCloud,
  _ as SteamDeck_BuildReview_Checklist_Text,
  _ as SteamDeck_BuildReview_CompatibilityTests,
  _ as SteamDeck_BuildReview_Create_HelpRequest,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_1,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2a,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2b,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes,
  _ as SteamDeck_BuildReview_Create_HelpRequest_NotesDefault,
  _ as SteamDeck_BuildReview_Create_HelpRequest_NotesDefault_Rereview,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes_1,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes_2,
  _ as SteamDeck_BuildReview_Create_HelpRequest_SupportTicketIntro,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Title,
  _ as SteamDeck_BuildReview_Documentation,
  _ as SteamDeck_BuildReview_Header_History,
  _ as SteamDeck_BuildReview_Header_Results,
  _ as SteamDeck_BuildReview_HelpRequest_Link,
  _ as SteamDeck_BuildReview_Help_Request_Title,
  _ as SteamDeck_BuildReview_InReview_Description,
  _ as SteamDeck_BuildReview_InReview_Title,
  _ as SteamDeck_BuildReview_InReview_ViewTicket,
  _ as SteamDeck_BuildReview_MarkReady_Button,
  _ as SteamDeck_BuildReview_MarkReady_Description,
  _ as SteamDeck_BuildReview_MarkReady_Notes,
  _ as SteamDeck_BuildReview_MarkReady_NotesDefault,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Description,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Button,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label_Machine,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Ticket_Content,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Title,
  _ as SteamDeck_BuildReview_PleaseComplete,
  _ as SteamDeck_BuildReview_PleaseConfirm_Description_V2,
  _ as SteamDeck_BuildReview_PleaseConfirm_Title_V2,
  _ as SteamDeck_BuildReview_PleaseRequestTest,
  _ as SteamDeck_BuildReview_PublishDialog_Body,
  _ as SteamDeck_BuildReview_PublishDialog_Title,
  _ as SteamDeck_BuildReview_PublishResults,
  _ as SteamDeck_BuildReview_PublishedOn,
  _ as SteamDeck_BuildReview_ReportedOn,
  _ as SteamDeck_BuildReview_RequestStatusActive,
  _ as SteamDeck_BuildReview_RequestStatusClosed,
  _ as SteamDeck_BuildReview_Status_Description,
  _ as SteamDeck_BuildReview_Status_Fail,
  _ as SteamDeck_BuildReview_Status_FailMinor,
  _ as SteamDeck_BuildReview_Status_NotApplicable,
  _ as SteamDeck_BuildReview_Status_Pass,
  _ as SteamDeck_BuildReview_Status_Raw_Comment,
  _ as SteamDeck_BuildReview_Status_Raw_Description,
  _ as SteamDeck_BuildReview_Status_Raw_Impact,
  _ as SteamDeck_BuildReview_Status_Raw_Result,
  _ as SteamDeck_BuildReview_Status_Raw_Test,
  _ as SteamDeck_BuildReview_Status_Raw_Title,
  _ as SteamDeck_BuildReview_Status_TestProperties_Description,
  _ as SteamDeck_BuildReview_Status_TestProperties_Playable,
  _ as SteamDeck_BuildReview_Status_TestProperty_Desc,
  _ as SteamDeck_BuildReview_Status_TestProperty_Name,
  _ as SteamDeck_BuildReview_Status_TestProperty_Value,
  _ as SteamDeck_BuildReview_Status_Title,
  _ as SteamDeck_BuildReview_UnknownError,
  _ as SteamDeck_BuildReview_Unsupported_Description,
  _ as SteamDeck_BuildReview_Unsupported_Title,
  _ as SteamDeck_BuildReview_ViewMoreDetailsInHelp,
  _ as SteamDeck_BuildReview_Viewing_Historical,
  _ as SteamDeck_BuildReview_Viewing_Published,
  _ as SteamDeck_HardwareCompatibility_Title,
  _ as SteamDeck_TestRequest_BuildNotReleased,
  _ as SteamFrame_BuildReview_Build_Android,
  _ as SteamFrame_BuildReview_Build_Linux,
  _ as SteamFrame_BuildReview_Build_Windows,
  _ as SteamFrame_BuildReview_CheckNote_Cloud_NoCrossSaves,
  _ as SteamFrame_BuildReview_CheckNote_Cloud_YesSavesNoCloud,
  _ as SteamFrame_BuildReview_CheckNote_DisplayFont,
  _ as SteamFrame_BuildReview_CheckNote_Launcher_V2_NoControllerSupport,
  _ as SteamFrame_BuildReview_CheckNote_Missing_Android_License,
  _ as SteamFrame_BuildReview_CheckNote_Missing_Android_License_Link,
  _ as SteamFrame_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs,
  _ as SteamFrame_BuildReview_Check_Icons,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Loading,
  _ as SteamFrame_BuildReview_Check_VRPerformance_NotApplicable,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Other,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Playable_With,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Playable_Without,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Startup,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Unsupported,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Verified_With,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Verified_Without,
  _ as SteamFrame_BuildReview_Checklist_Build,
  _ as SteamFrame_BuildReview_Checklist_Dimension,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P1,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P3,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P3_ReviewProcess,
  _ as SteamFrame_BuildReview_Checklist_Intro_Header_V2,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_Description,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_StatusReason,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_Title,
  _ as SteamFrame_BuildReview_Compatibility_Checklist,
  _ as SteamFrame_BuildReview_Dimension_2D,
  _ as SteamFrame_BuildReview_Dimension_VR,
  _ as SteamFrame_BuildReview_PleaseConfirm_Description_V2,
  _ as SteamFrame_BuildReview_PleaseConfirm_Title_V2,
  _ as SteamFrame_BuildReview_VRPerformanceLink,
  _ as SteamFrame_NotApplicableForDimension,
  _ as SteamHardware_BuildReview_Playable_Description,
  _ as SteamHardware_BuildReview_Playable_Title,
  _ as SteamHardware_BuildReview_Unknown_Title,
  _ as SteamHardware_BuildReview_Unsupported_Description,
  _ as SteamHardware_BuildReview_Unsupported_Title,
  _ as SteamHardware_BuildReview_Verified_Description,
  _ as SteamHardware_BuildReview_Verified_Share,
  _ as SteamHardware_BuildReview_Verified_Title,
  _ as SteamHardware_Frame_Unknown,
  _ as SteamHardware_Machine_Unknown,
  _ as SteamHardware_RatingImpact_Informational,
  _ as SteamHardware_RatingImpact_Playable,
  _ as SteamHardware_RatingImpact_Unsupported,
  _ as Valve_Confidential,
  _ as Valve_Confidential_Description,
  _ as default,
  _ as dummy,
};
