var _ = `Không xác định`,
  _ = `Đô la (Mỹ)`,
  _ = `Bảng (Anh)`,
  _ = `Euro`,
  _ = `Franc (Thụy Sỹ)`,
  _ = `Rúp (Nga)`,
  _ = `Złoty (Ba Lan)`,
  _ = `Real (Brazil)`,
  _ = `Yên (Nhật)`,
  _ = `Krone (Na Uy)`,
  _ = `Rupiah (Indonesia)`,
  _ = `Ringgit (Malaysia)`,
  _ = `Peso (Philippines)`,
  _ = `Đô la (Singapore)`,
  _ = `Baht (Thái)`,
  _ = `Đồng (Việt Nam)`,
  _ = `Won (Hàn Quốc)`,
  _ = `Lira (Thổ Nhĩ Kỳ)`,
  _ = `Hryvnia (Ukraina)`,
  _ = `Peso (Mexico)`,
  _ = `Đô la (Canada)`,
  _ = `Đô la (Úc)`,
  _ = `Đô la (New Zealand)`,
  _ = `Nhân dân tệ (Trung Quốc)`,
  _ = `Rupee (Ấn Độ)`,
  _ = `Peso (Chile)`,
  _ = `Sol (Peru)`,
  _ = `Peso (Colombia)`,
  _ = `Rand (Nam Phi)`,
  _ = `Đô la (Hồng Kông)`,
  _ = `Tân Đài tệ (Đài Loan)`,
  _ = `Riyal (Ả Rập Saudi)`,
  _ = `Dirham (UAE)`,
  _ = `Peso (Argentina)`,
  _ = `Shekel mới (Israel)`,
  _ = `Tenge (Kazakhstan)`,
  _ = `Dinar (Kuwait)`,
  _ = `Rial (Qatar)`,
  _ = `Colon (Costa Rica)`,
  _ = `Peso (Uruguay)`,
  _ = `Lev (Bulgary)`,
  _ = `Krona (Thụy Điển)`,
  _ = `Kuna (Croatia)`,
  _ = `Koruna (CH Séc)`,
  _ = `Krone (Đan Mạch)`,
  _ = `Forint (Hungary)`,
  _ = `Leu (Rumani)`,
  _ = `Rúp (Belarus)`,
  _ = `Khu vực CIS - Hiển thị đến khách hàng tại Armenia, Azerbaijan, Belarus, Georgia, Kyrgyzstan, Moldova, Tajikistan, Turkmenistan, Uzbekistan`,
  _ = `Quốc gia Nam Á - Hiển thị đến khách hàng tại Bangladesh, Bhutan, Nepal, Pakistan, Sri Lanka`,
  _ = `Quốc gia Mỹ Latin - Hiển thị đến khách hàng tại Argentina, Belize, Bolivia, Ecuador, El Salvador, Guyana, Guatemala, Honduras, Nicaragua, Panama, Paraguay, Suriname, Venezuela`,
  _ = `Quốc gia Trung Đông và Bắc Phi - Hiển thị đến khách hàng tại Algeria, Bahrain, Ai Cập, Iraq, Jordan, Lebanon, Libya, Maroc, Oman, Palestine, Sudan, Tunisia, Thổ Nhĩ Kỳ, Yemen`,
  _ = `Không xác định`,
  _ = `dummy`,
  _ = {
    CurrencyCodeDescription_Unknown: _,
    CurrencyCodeDescription_USD: _,
    CurrencyCodeDescription_GBP: _,
    CurrencyCodeDescription_EUR: _,
    CurrencyCodeDescription_CHF: _,
    CurrencyCodeDescription_RUB: _,
    CurrencyCodeDescription_PLN: _,
    CurrencyCodeDescription_BRL: _,
    CurrencyCodeDescription_JPY: _,
    CurrencyCodeDescription_NOK: _,
    CurrencyCodeDescription_IDR: _,
    CurrencyCodeDescription_MYR: _,
    CurrencyCodeDescription_PHP: _,
    CurrencyCodeDescription_SGD: _,
    CurrencyCodeDescription_THB: _,
    CurrencyCodeDescription_VND: _,
    CurrencyCodeDescription_KRW: _,
    CurrencyCodeDescription_TRY: _,
    CurrencyCodeDescription_UAH: _,
    CurrencyCodeDescription_MXN: _,
    CurrencyCodeDescription_CAD: _,
    CurrencyCodeDescription_AUD: _,
    CurrencyCodeDescription_NZD: _,
    CurrencyCodeDescription_CNY: _,
    CurrencyCodeDescription_INR: _,
    CurrencyCodeDescription_CLP: _,
    CurrencyCodeDescription_PEN: _,
    CurrencyCodeDescription_COP: _,
    CurrencyCodeDescription_ZAR: _,
    CurrencyCodeDescription_HKD: _,
    CurrencyCodeDescription_TWD: _,
    CurrencyCodeDescription_SAR: _,
    CurrencyCodeDescription_AED: _,
    CurrencyCodeDescription_ARS: _,
    CurrencyCodeDescription_ILS: _,
    CurrencyCodeDescription_KZT: _,
    CurrencyCodeDescription_KWD: _,
    CurrencyCodeDescription_QAR: _,
    CurrencyCodeDescription_CRC: _,
    CurrencyCodeDescription_UYU: _,
    CurrencyCodeDescription_BGN: _,
    CurrencyCodeDescription_SEK: _,
    CurrencyCodeDescription_HRK: _,
    CurrencyCodeDescription_CZK: _,
    CurrencyCodeDescription_DKK: _,
    CurrencyCodeDescription_HUF: _,
    CurrencyCodeDescription_RON: _,
    CurrencyCodeDescription_BYN: _,
    Region_Pricing_Tooltip_CIS: _,
    Region_Pricing_Tooltip_SASIA: _,
    Region_Pricing_Tooltip_LATAM: _,
    Region_Pricing_Tooltip_MENA: _,
    Region_Pricing_Tooltip_Unknown: _,
    dummy: _,
  };
export {
  _ as CurrencyCodeDescription_AED,
  _ as CurrencyCodeDescription_ARS,
  _ as CurrencyCodeDescription_AUD,
  _ as CurrencyCodeDescription_BGN,
  _ as CurrencyCodeDescription_BRL,
  _ as CurrencyCodeDescription_BYN,
  _ as CurrencyCodeDescription_CAD,
  _ as CurrencyCodeDescription_CHF,
  _ as CurrencyCodeDescription_CLP,
  _ as CurrencyCodeDescription_CNY,
  _ as CurrencyCodeDescription_COP,
  _ as CurrencyCodeDescription_CRC,
  _ as CurrencyCodeDescription_CZK,
  _ as CurrencyCodeDescription_DKK,
  _ as CurrencyCodeDescription_EUR,
  _ as CurrencyCodeDescription_GBP,
  _ as CurrencyCodeDescription_HKD,
  _ as CurrencyCodeDescription_HRK,
  _ as CurrencyCodeDescription_HUF,
  _ as CurrencyCodeDescription_IDR,
  _ as CurrencyCodeDescription_ILS,
  _ as CurrencyCodeDescription_INR,
  _ as CurrencyCodeDescription_JPY,
  _ as CurrencyCodeDescription_KRW,
  _ as CurrencyCodeDescription_KWD,
  _ as CurrencyCodeDescription_KZT,
  _ as CurrencyCodeDescription_MXN,
  _ as CurrencyCodeDescription_MYR,
  _ as CurrencyCodeDescription_NOK,
  _ as CurrencyCodeDescription_NZD,
  _ as CurrencyCodeDescription_PEN,
  _ as CurrencyCodeDescription_PHP,
  _ as CurrencyCodeDescription_PLN,
  _ as CurrencyCodeDescription_QAR,
  _ as CurrencyCodeDescription_RON,
  _ as CurrencyCodeDescription_RUB,
  _ as CurrencyCodeDescription_SAR,
  _ as CurrencyCodeDescription_SEK,
  _ as CurrencyCodeDescription_SGD,
  _ as CurrencyCodeDescription_THB,
  _ as CurrencyCodeDescription_TRY,
  _ as CurrencyCodeDescription_TWD,
  _ as CurrencyCodeDescription_UAH,
  _ as CurrencyCodeDescription_USD,
  _ as CurrencyCodeDescription_UYU,
  _ as CurrencyCodeDescription_Unknown,
  _ as CurrencyCodeDescription_VND,
  _ as CurrencyCodeDescription_ZAR,
  _ as Region_Pricing_Tooltip_CIS,
  _ as Region_Pricing_Tooltip_LATAM,
  _ as Region_Pricing_Tooltip_MENA,
  _ as Region_Pricing_Tooltip_SASIA,
  _ as Region_Pricing_Tooltip_Unknown,
  _ as default,
  _ as dummy,
};
