var _ = `未知`,
  _ = `美元`,
  _ = `英镑`,
  _ = `欧元`,
  _ = `瑞士法郎`,
  _ = `俄罗斯卢布`,
  _ = `波兰兹罗提`,
  _ = `巴西雷亚尔`,
  _ = `日元`,
  _ = `挪威克朗`,
  _ = `印尼盾`,
  _ = `马来西亚林吉特`,
  _ = `菲律宾比索`,
  _ = `新加坡元`,
  _ = `泰铢`,
  _ = `越南盾`,
  _ = `韩元`,
  _ = `土耳其新里拉`,
  _ = `乌克兰格里夫纳`,
  _ = `墨西哥比索`,
  _ = `加拿大元`,
  _ = `澳大利亚元`,
  _ = `新西兰元`,
  _ = `人民币`,
  _ = `印度卢比`,
  _ = `智利比索`,
  _ = `秘鲁索尔`,
  _ = `哥伦比亚比索`,
  _ = `南非兰特`,
  _ = `港元`,
  _ = `新台币`,
  _ = `沙特里亚尔`,
  _ = `阿联酋迪拉姆`,
  _ = `阿根廷比索`,
  _ = `以色列新谢克尔`,
  _ = `哈萨克斯坦坚戈`,
  _ = `科威特第纳尔`,
  _ = `卡塔尔里亚尔`,
  _ = `哥斯达黎加科朗`,
  _ = `乌拉圭比索`,
  _ = `保加利亚列弗`,
  _ = `瑞典克朗`,
  _ = `克罗地亚库纳`,
  _ = `捷克克朗`,
  _ = `丹麦克朗`,
  _ = `匈牙利福林`,
  _ = `罗马尼亚列伊`,
  _ = `白俄罗斯卢布`,
  _ = `独联体地区 - 向亚美尼亚、阿塞拜疆、白俄罗斯、格鲁吉亚、吉尔吉斯斯坦、摩尔多瓦、塔吉克斯坦、土库曼斯坦、乌兹别克斯坦的顾客显示`,
  _ = `南亚国家 - 向孟加拉国、不丹、尼泊尔、巴基斯坦、斯里兰卡的顾客显示`,
  _ = `拉丁美洲国家 - 向阿根廷、伯利兹、玻利维亚、厄瓜多尔、萨尔瓦多、圭亚那、危地马拉、洪都拉斯、尼加拉瓜、巴拿马、巴拉圭、苏里南、委内瑞拉的顾客显示`,
  _ = `中东及北非国家 - 向阿尔及利亚、巴林、埃及、伊拉克、约旦、黎巴嫩、利比亚、摩洛哥、阿曼、巴勒斯坦、苏丹、突尼斯、土耳其、也门的顾客显示`,
  _ = `未知`,
  _ = `dummy`,
  _ = {
    CurrencyCodeDescription_Unknown: _,
    CurrencyCodeDescription_USD: _,
    CurrencyCodeDescription_GBP: _,
    CurrencyCodeDescription_EUR: _,
    CurrencyCodeDescription_CHF: _,
    CurrencyCodeDescription_RUB: _,
    CurrencyCodeDescription_PLN: _,
    CurrencyCodeDescription_BRL: _,
    CurrencyCodeDescription_JPY: _,
    CurrencyCodeDescription_NOK: _,
    CurrencyCodeDescription_IDR: _,
    CurrencyCodeDescription_MYR: _,
    CurrencyCodeDescription_PHP: _,
    CurrencyCodeDescription_SGD: _,
    CurrencyCodeDescription_THB: _,
    CurrencyCodeDescription_VND: _,
    CurrencyCodeDescription_KRW: _,
    CurrencyCodeDescription_TRY: _,
    CurrencyCodeDescription_UAH: _,
    CurrencyCodeDescription_MXN: _,
    CurrencyCodeDescription_CAD: _,
    CurrencyCodeDescription_AUD: _,
    CurrencyCodeDescription_NZD: _,
    CurrencyCodeDescription_CNY: _,
    CurrencyCodeDescription_INR: _,
    CurrencyCodeDescription_CLP: _,
    CurrencyCodeDescription_PEN: _,
    CurrencyCodeDescription_COP: _,
    CurrencyCodeDescription_ZAR: _,
    CurrencyCodeDescription_HKD: _,
    CurrencyCodeDescription_TWD: _,
    CurrencyCodeDescription_SAR: _,
    CurrencyCodeDescription_AED: _,
    CurrencyCodeDescription_ARS: _,
    CurrencyCodeDescription_ILS: _,
    CurrencyCodeDescription_KZT: _,
    CurrencyCodeDescription_KWD: _,
    CurrencyCodeDescription_QAR: _,
    CurrencyCodeDescription_CRC: _,
    CurrencyCodeDescription_UYU: _,
    CurrencyCodeDescription_BGN: _,
    CurrencyCodeDescription_SEK: _,
    CurrencyCodeDescription_HRK: _,
    CurrencyCodeDescription_CZK: _,
    CurrencyCodeDescription_DKK: _,
    CurrencyCodeDescription_HUF: _,
    CurrencyCodeDescription_RON: _,
    CurrencyCodeDescription_BYN: _,
    Region_Pricing_Tooltip_CIS: _,
    Region_Pricing_Tooltip_SASIA: _,
    Region_Pricing_Tooltip_LATAM: _,
    Region_Pricing_Tooltip_MENA: _,
    Region_Pricing_Tooltip_Unknown: _,
    dummy: _,
  };
export {
  _ as CurrencyCodeDescription_AED,
  _ as CurrencyCodeDescription_ARS,
  _ as CurrencyCodeDescription_AUD,
  _ as CurrencyCodeDescription_BGN,
  _ as CurrencyCodeDescription_BRL,
  _ as CurrencyCodeDescription_BYN,
  _ as CurrencyCodeDescription_CAD,
  _ as CurrencyCodeDescription_CHF,
  _ as CurrencyCodeDescription_CLP,
  _ as CurrencyCodeDescription_CNY,
  _ as CurrencyCodeDescription_COP,
  _ as CurrencyCodeDescription_CRC,
  _ as CurrencyCodeDescription_CZK,
  _ as CurrencyCodeDescription_DKK,
  _ as CurrencyCodeDescription_EUR,
  _ as CurrencyCodeDescription_GBP,
  _ as CurrencyCodeDescription_HKD,
  _ as CurrencyCodeDescription_HRK,
  _ as CurrencyCodeDescription_HUF,
  _ as CurrencyCodeDescription_IDR,
  _ as CurrencyCodeDescription_ILS,
  _ as CurrencyCodeDescription_INR,
  _ as CurrencyCodeDescription_JPY,
  _ as CurrencyCodeDescription_KRW,
  _ as CurrencyCodeDescription_KWD,
  _ as CurrencyCodeDescription_KZT,
  _ as CurrencyCodeDescription_MXN,
  _ as CurrencyCodeDescription_MYR,
  _ as CurrencyCodeDescription_NOK,
  _ as CurrencyCodeDescription_NZD,
  _ as CurrencyCodeDescription_PEN,
  _ as CurrencyCodeDescription_PHP,
  _ as CurrencyCodeDescription_PLN,
  _ as CurrencyCodeDescription_QAR,
  _ as CurrencyCodeDescription_RON,
  _ as CurrencyCodeDescription_RUB,
  _ as CurrencyCodeDescription_SAR,
  _ as CurrencyCodeDescription_SEK,
  _ as CurrencyCodeDescription_SGD,
  _ as CurrencyCodeDescription_THB,
  _ as CurrencyCodeDescription_TRY,
  _ as CurrencyCodeDescription_TWD,
  _ as CurrencyCodeDescription_UAH,
  _ as CurrencyCodeDescription_USD,
  _ as CurrencyCodeDescription_UYU,
  _ as CurrencyCodeDescription_Unknown,
  _ as CurrencyCodeDescription_VND,
  _ as CurrencyCodeDescription_ZAR,
  _ as Region_Pricing_Tooltip_CIS,
  _ as Region_Pricing_Tooltip_LATAM,
  _ as Region_Pricing_Tooltip_MENA,
  _ as Region_Pricing_Tooltip_SASIA,
  _ as Region_Pricing_Tooltip_Unknown,
  _ as default,
  _ as dummy,
};
