var _ = `Selecione um preço em USD abaixo`,
  _ = `Gratuito`,
  _ = `Definir como gratuito...`,
  _ = `Atualizar este pacote como gratuito para os clientes`,
  _ = `Este pacote só pode ser definido como gratuito por um representante do Suporte Steam. Use o link "Contactar equipa de publicação no Steam" em "Documentação e ajuda" para mais assistência.`,
  _ = `Mudar pacote para gratuito?`,
  _ = `Isto irá definir o seu pacote como gratuito, marcar a sua aplicação para que apareça na central de jogos Grátis para Jogar e alterar o preço exibido com base no termo que selecionar abaixo. Esta alteração não pode ser revertida a menos que envie um pedido à equipa de apoio do Steamworks.`,
  _ = `Este pacote só pode ser mudado para gratuito por um representante do Suporte Steam. Clique abaixo para criar um pedido de ajuda com os detalhes necessários.`,
  _ = `Selecione o texto apropriado a apresentar em vez do preço:`,
  _ = `"Grátis para Jogar" - O jogo pode ser transferido e jogado gratuitamente. No entanto, existe a opção para comprar conteúdo adicional (itens, moedas virtuais, DLCs ou outro tipo de monetização) dentro do jogo.`,
  _ = `"Gratuito" - É completamente grátis transferir e jogar o jogo. Não existe a opção para comprar conteúdo adicional dentro do jogo.`,
  _ = `Mudar para gratuito`,
  _ = `A atualizar a página do jogo na loja para ser incluída na categoria correspondente a jogos gratuitos. É necessário publicar a página.`,
  _ = `A atualizar o pacote para gratuito`,
  _ = `Conversão concluída. A página será atualizada quando fechar esta janela.`,
  _ = `Falha ao atualizar a página da aplicação na loja: %1$s`,
  _ = `Não foi possível mudar o tipo do pacote: %1$s`,
  _ = `Método de conversão (%1$s)`,
  _ = `Ver detalhes`,
  _ = `Utilizando a lista pendente abaixo, selecione a que preço pretende vender o seu produto. A partir do preço-base que selecionar, esta ferramenta irá sugerir preços regionais apropriados com base na nossa experiência com outros produtos a preços semelhantes. Tenha em atenção que as conversões recomendadas para certos países incluem IVA/VAT/GST/JCT, os impostos sobre o valor acrescentado cobrados pelas autoridades fiscais. Em países onde este tipo de imposto é exigido pela lei, o mesmo está incluído nos preços e é cobrado em compras efetuadas nos países aplicáveis. Uma lista de países onde este tipo de imposto é cobrado pode ser encontrada aqui:`,
  _ = `Antes de enviar, verifique os preços EM TODAS AS MOEDAS e pense cuidadosamente no seu produto. Por diversas razões, recomendamos aos nossos parceiros que não ajustem os seus preços nas primeiras semanas após o lançamento. Se necessário, pode enviar uma nova solicitação de preços antes do lançamento, mas assim que o seu produto estiver ativo, os seus preços manter-se-ão. Consulte a %1$s para mais informações.`,
  _ = `documentação sobre preços e descontos`,
  _ = `Assim que estiver contente com os seus preços, prima o botão Guardar para os enviar para a Valve para efeitos de revisão e processamento.`,
  _ = `Editar na página de precificação em massa`,
  _ = `Edite o preço deste pacote na ferramenta de precificação em massa.`,
  _ = `Ajuda e diretrizes`,
  _ = `Procura ajuda ou sugestões relativamente ao preço do seu título? Abaixo, encontra uma ligação para algumas considerações e diretrizes comuns.`,
  _ = `Documentação sobre preços`,
  _ = `Perguntas frequentes`,
  _ = `Gostaria que o seu jogo passasse a ser gratuito?`,
  _ = `Se o seu jogo já foi lançado e deseja que seja mudado de pago para gratuito, clique %1$s para mais informações e solicitar ajuda.`,
  _ = `aqui`,
  _ = `Introdução de preços personalizados`,
  _ = `Pode introduzir os seus próprios preços para cada moeda ao editar a caixa de texto diretamente.`,
  _ = `Também pode usar este botão para calcular cada moeda com base no método de conversão selecionado e no preço personalizado em USD que introduziu.`,
  _ = `Selecionar de patamares de preços`,
  _ = `Selecionar preço base em USD`,
  _ = `Clique neste botão para abrir uma janela com um conjunto dos patamares de preços mais comuns e assim defini-los em todas as moedas abaixo.`,
  _ = `Conversão com várias variáveis`,
  _ = `Conversão com base no poder de compra`,
  _ = `Conversão com base na taxa de câmbio`,
  _ = `Última atualização:`,
  _ = `Os métodos de conversão são gerados com base em dados públicos a partir de janeiro de 2026`,
  _ = `Novos métodos de conversão disponíveis`,
  _ = `Para ajudar a definir um preço para o seu jogo em 37 moedas distintas e 4 grupos de regiões, o Steam agora oferece novos métodos para auxiliar na conversão do seu preço⁠-⁠base desejado.`,
  _ = `O preço fica inteiramente ao seu critério. Estas ferramentas foram criadas apenas para ajudar a simplificar o processo, se assim o desejar.`,
  _ = `Visite a nossa %1$s ou clique em "Ver detalhes" acima para saber mais sobre os diferentes métodos de conversão disponíveis.`,
  _ = `página de detalhes dos métodos de conversão`,
  _ = `Aplicar preços de método de conversão`,
  _ = `Para ajudar a fazer a gestão de preços nas mais de 35 moedas diferentes disponíveis no Steam, esta ferramenta oferece métodos de conversão opcionais que permitem adaptar o seu preço base em USD para níveis adequados para cada região.`,
  _ = `Selecione um preço abaixo para o definir em USD e aplicar preços convertidos a todas as outras moedas. Depende do método de conversão selecionado acima.`,
  _ = `Pode introduzir preços para cada moeda disponível individualmente ou utilizar um dos métodos de conversão do Steam para converter o seu preço em USD para todas as outras moedas.`,
  _ = `Há duas formas de utilizar os métodos de conversão do Steam:`,
  _ = `Selecione um preço típico em USD no menu pendente de patamares de preços abaixo e o Steam irá preencher os campos das outras moedas de acordo com o método de conversão selecionado.`,
  _ = `Para preços atípicos em USD, introduza um valor no campo do preço em USD. Depois, clique no botão "Converter preços..." e siga as instruções.`,
  _ = `Conversões sugeridas:`,
  _ = `Este preço é sugerido com base no método de conversão selecionado acima e no preço em USD de %1$s.`,
  _ = `dummy`,
  _ = ``,
  _ = {
    PricingGuideline_Default: _,
    FreeOnDemand_InlineOption: _,
    FreeOnDemand_Button: _,
    FreeOnDemand_Button_ttip: _,
    FreeOnDemand_Button_disabled_ttip: _,
    FreeOnDemand_Title: _,
    FreeOnDemand_Desc: _,
    FreeOnDemand_Desc_NotPermitted: _,
    FreeOnDemand_Radio: _,
    FreeOnDemand_Radio_FreeToPlay: _,
    FreeOnDemand_Radio_Free: _,
    FreeOnDemand_Button_Confirm: _,
    FreeOnDemand_Convert_Store: _,
    FreeOnDemand_Convert_Package: _,
    FreeOnDemand_ConvertSuccess: _,
    FreeOnDemand_Store_Error: _,
    FreeOnDemand_Package_Error: _,
    ConversionMethod_Title: _,
    ConversionMethod_Link: _,
    SinglePricingPackage_Desc_1: _,
    SinglePricingPackage_Desc_2: _,
    SinglePricingPackage_Desc_2_Link: _,
    SinglePricingPackage_Desc_3: _,
    SinglePackagePricing_Right_Edit: _,
    SinglePackagePricing_Right_Edit_desc: _,
    SinglePackagePricing_Right_Help_Title: _,
    SinglePackagePricing_Right_Help_Desc: _,
    SinglePackagePricing_Right_Link: _,
    SinglePackagePricing_Right_FAQ: _,
    SinglePackagePricing_Right_FAQ_switching: _,
    SinglePackagePricing_Right_FAQ_switching_answer: _,
    SinglePackagePricing_Right_FAQ_switching_answer_link: _,
    SinglePackagePricing_Right_Convert_Title: _,
    SinglePackagePricing_Right_Custom_Desc: _,
    SinglePackagePricing_Right_Convert_Desc: _,
    PricingDashboard_Select_Price: _,
    PricingDashboard_Select_Price_button: _,
    PricingDashboard_Select_Price_button_ttip: _,
    ConversionMethod_Nuanced: _,
    ConversionMethod_PPP: _,
    ConversionMethod_FX: _,
    PricingExplorer_Time_Title: _,
    PricingExplorer_Time_Disc: _,
    Tour_ConversionMethod_Title: _,
    Tour_ConversionMethod_Desc1: _,
    Tour_ConversionMethod_Desc2: _,
    Tour_ConversionMethod_Desc3: _,
    Tour_ConversionMethod_Link: _,
    PricingDashboard_ApplyConversion_Method: _,
    PricingDashboard_ApplyGuidelines_Instructions_MultiOptions: _,
    PricingDashboard_GuidelinesPickerDescription_New: _,
    SinglePricingPackage_Intro_1: _,
    SinglePricingPackage_Intro_2: _,
    SinglePricingPackage_Intro_2a: _,
    SinglePricingPackage_Intro_2b: _,
    PricingDashboard_Method_SuggestedPrice: _,
    PricingDashboard_Method_SuggestedPrice_ttip: _,
    dummy: _,
    empty_no_trailing_comma: ``,
  };
export {
  _ as ConversionMethod_FX,
  _ as ConversionMethod_Link,
  _ as ConversionMethod_Nuanced,
  _ as ConversionMethod_PPP,
  _ as ConversionMethod_Title,
  _ as FreeOnDemand_Button,
  _ as FreeOnDemand_Button_Confirm,
  _ as FreeOnDemand_Button_disabled_ttip,
  _ as FreeOnDemand_Button_ttip,
  _ as FreeOnDemand_ConvertSuccess,
  _ as FreeOnDemand_Convert_Package,
  _ as FreeOnDemand_Convert_Store,
  _ as FreeOnDemand_Desc,
  _ as FreeOnDemand_Desc_NotPermitted,
  _ as FreeOnDemand_InlineOption,
  _ as FreeOnDemand_Package_Error,
  _ as FreeOnDemand_Radio,
  _ as FreeOnDemand_Radio_Free,
  _ as FreeOnDemand_Radio_FreeToPlay,
  _ as FreeOnDemand_Store_Error,
  _ as FreeOnDemand_Title,
  _ as PricingDashboard_ApplyConversion_Method,
  _ as PricingDashboard_ApplyGuidelines_Instructions_MultiOptions,
  _ as PricingDashboard_GuidelinesPickerDescription_New,
  _ as PricingDashboard_Method_SuggestedPrice,
  _ as PricingDashboard_Method_SuggestedPrice_ttip,
  _ as PricingDashboard_Select_Price,
  _ as PricingDashboard_Select_Price_button,
  _ as PricingDashboard_Select_Price_button_ttip,
  _ as PricingExplorer_Time_Disc,
  _ as PricingExplorer_Time_Title,
  _ as PricingGuideline_Default,
  _ as SinglePackagePricing_Right_Convert_Desc,
  _ as SinglePackagePricing_Right_Convert_Title,
  _ as SinglePackagePricing_Right_Custom_Desc,
  _ as SinglePackagePricing_Right_Edit,
  _ as SinglePackagePricing_Right_Edit_desc,
  _ as SinglePackagePricing_Right_FAQ,
  _ as SinglePackagePricing_Right_FAQ_switching,
  _ as SinglePackagePricing_Right_FAQ_switching_answer,
  _ as SinglePackagePricing_Right_FAQ_switching_answer_link,
  _ as SinglePackagePricing_Right_Help_Desc,
  _ as SinglePackagePricing_Right_Help_Title,
  _ as SinglePackagePricing_Right_Link,
  _ as SinglePricingPackage_Desc_1,
  _ as SinglePricingPackage_Desc_2,
  _ as SinglePricingPackage_Desc_2_Link,
  _ as SinglePricingPackage_Desc_3,
  _ as SinglePricingPackage_Intro_1,
  _ as SinglePricingPackage_Intro_2,
  _ as SinglePricingPackage_Intro_2a,
  _ as SinglePricingPackage_Intro_2b,
  _ as Tour_ConversionMethod_Desc1,
  _ as Tour_ConversionMethod_Desc2,
  _ as Tour_ConversionMethod_Desc3,
  _ as Tour_ConversionMethod_Link,
  _ as Tour_ConversionMethod_Title,
  _ as default,
  _ as dummy,
  _ as empty_no_trailing_comma,
};
