var _ = `Konfidensial Valve`,
  _ = `Halaman yang dibatasi ini berisi informasi konfidensial Valve. Kamu harus sudah terikat NDA/atau lisensi yang mencakup perizinan pengunaan informasi konfidensial Valve atau akses ke halaman ini.`,
  _ = `Steamworks merupakan kumpulan alat dan layanan yang dibuat oleh <1>Valve</1> untuk membantumu mengonfigurasi, mengelola, dan menjalankan game-mu di <2>Steam</2>.`,
  _ = `Hubungi Bantuan`,
  _ = `Eror Memuat Informasi Harga, silakan coba lagi nanti.`,
  _ = `Tentang Penentuan Harga Sesuai Wilayah`,
  _ = `Harga setiap produk di Steam ditentukan dan ditampilkan menggunakan %1$s mata uang berbeda dan %2$s <1>kelompok wilayah</1>. Steam menawarkan alat untuk membantu menetapkan dan mengelola harga game-mu pada tingkat yang sesuai untuk setiap pasar.`,
  _ = `Kamulah yang menentukan harga game-mu, serta setiap mata uang dan kelompok wilayahnya.`,
  _ = `Untuk rincian tentang mengelola harga, silakan lihat %1$s`,
  _ = `Dokumentasi Penentuan Harga`,
  _ = `Untuk mengelola harga game-mu, buka %1$s`,
  _ = `Kunjungi Dasbor Penentuan Harga`,
  _ = `Untuk mengelola harga game-mu, buka Dasbor Penentuan harga`,
  _ = `Konversi mata uang terakhir diperbarui pada %1$s`,
  _ = `Alat eksplorasi konversi harga`,
  _ = `Alat ini menunjukkan cara kerja tiga metode konversi harga dan mata uang:`,
  _ = `%1$s - Metode ini memperhitungkan beberapa faktor untuk setiap mata uang, termasuk daya beli lokal, perkiraan harga dari barang hiburan sebanding, dan nilai tukar.`,
  _ = `%1$s - Metode ini menggunakan data publik tentang daya beli rata-rata pelanggan di negara dan/atau wilayah tertentu.`,
  _ = `%1$s - Metode ini menggunakan nilai tukar sederhana yang sedang berlaku.`,
  _ = `Mata uang dasar`,
  _ = `Harga Dasar`,
  _ = `Metode Konversi`,
  _ = `Mata Uang`,
  _ = `Konversi multivariabel`,
  _ = `Konversi berdasarkan daya beli`,
  _ = `Konversi nilai tukar`,
  _ = `Harga Khusus Wilayah (semua dilaporkan dalam USD)`,
  _ = `Wilayah`,
  _ = `dummy`,
  _ = `%1$s (%2$s) - Survei Konten`,
  _ = `Survei Konten`,
  _ = `%1$s (%2$s) - Survei Konten`,
  _ = `Survei Konten`,
  _ = `Tidak ada aplikasi dengan ID ini. Periksa alamatnya dan coba lagi.`,
  _ = `Izin Ditolak`,
  _ = `Belum login`,
  _ = `SteamLearn`,
  _ = `Filter berdasarkan Proyek`,
  _ = `Buat Baru`,
  _ = `Daftar Proyek`,
  _ = `Proyek SteamLearn`,
  _ = `Jadwalkan`,
  _ = `Buat Proyek`,
  _ = `Nama Proyek`,
  _ = `Deskripsi Proyek`,
  _ = `Buat Proyek`,
  _ = `Edit Proyek`,
  _ = `OK`,
  _ = `Batal`,
  _ = `Nama Tidak Valid—kemungkinan sudah digunakan oleh proyek lain.`,
  _ = `Eror Tidak Diketahui—silakan coba lagi.`,
  _ = `Gagal mengedit proyek—silakan coba lagi.`,
  _ = `Tidak Ada Deskripsi`,
  _ = `Proyek %1$s`,
  _ = `Diselesaikan pada %1$s`,
  _ = `Durasi: %1$s`,
  _ = `Kerugian: %1$s, Akurasi: %2$s%`,
  _ = `Sedang Berlangsung`,
  _ = `Prapemrosesan baris: %1$s%`,
  _ = `Mengambil Metadata`,
  _ = `Membersihkan data lama`,
  _ = `Dibatalkan`,
  _ = `Menunggu AutoSnapshot`,
  _ = `Epoch %1$s/%2$s`,
  _ = `Dijadwalkan pada %1$s`,
  _ = `Tidak Diketahui`,
  _ = `Dibatalkan`,
  _ = `Eror`,
  _ = `%1$s tersisa`,
  _ = `Belum Terpublikasi`,
  _ = `Publikasikan`,
  _ = `Batal`,
  _ = `Edit`,
  _ = `Simpan Perubahan`,
  _ = `Buang Perubahan`,
  _ = `Ringkasan`,
  _ = `Daftar Sumber Data`,
  _ = `Tidak Ada Sumber Data yang dipilih untuk proyek ini.`,
  _ = `Tambahkan Sumber Data`,
  _ = `Pilih satu atau lebih dari satu Sumber Data`,
  _ = `Tambahkan 1 Sumber Data`,
  _ = `Tambahkan %1$s Sumber Data`,
  _ = `Hapus Sumber Data`,
  _ = `Perbarui Sumber Data`,
  _ = `Tabel Ringkas`,
  _ = `Eksternal`,
  _ = `ID akun`,
  _ = `AppID`,
  _ = `Pesan Pemasaran`,
  _ = `Ringkasan`,
  _ = `Daftar lengkap dari pengujian yang dilakukan selama peninjauan dan hasil-hasilnya ada di bawah.`,
  _ = `Berikut adalah ringkasan dari masing-masing pengujian dan rating kompatibilitas yang dihasilkan.`,
  _ = `Hasil pengujian yang menunjukkan bahwa game ini Dapat Dimainkan tercantum di bawah ini.`,
  _ = `Properti`,
  _ = `Nilai`,
  _ = `Deskripsi`,
  _ = `Ini adalah pratinjau tentang bagaimana game ini ditampilkan di toko saat pemain melihatnya. Tampilan di toko bisa berubah di masa yang akan datang.`,
  _ = `Laporan Sebelumnya`,
  _ = `Hasil Pengujian`,
  _ = `Hasil`,
  _ = `Uji`,
  _ = `Komentar`,
  _ = `Dampak terhadap Rating`,
  _ = `Lolos`,
  _ = `Gagal`,
  _ = `Gagal`,
  _ = `---`,
  _ = `Ini adalah riwayat laporan dari %1$s`,
  _ = `Melihat laporan yang dipublikasikan saat ini`,
  _ = `Dipublikasikan pada: %1$s`,
  _ = `Dilaporkan pada: %1$s`,
  _ = `Lihat Dokumentasi`,
  _ = `Publikasikan hasil-hasil ini`,
  _ = `Publikasikan Hasil Kompatibilitas?`,
  _ = `Apa kamu yakin ingin memublikasikan hasil-hasil ini? Hasil akan langsung terlihat di Toko Steam.`,
  _ = `Eror Tidak Diketahui — Silakan coba lagi`,
  _ = `Permintaan Pengujian`,
  _ = `Permintaan Aktif`,
  _ = `Permintaan Ditutup`,
  _ = `Lihat Rincian Permintaan`,
  _ = `Diskusikan laporan ini dengan tim penguji`,
  _ = `Masukkan pertanyaan atau komentar di sini`,
  _ = `Jelaskan perubahan pada build barumu di sini`,
  _ = `Jika build game-mu di Steam telah diperbarui untuk memperbaiki isu-isu yang disebutkan di atas, silakan pilih branch dan kirim ulang untuk peninjauan.`,
  _ = `Pilih branch dan kirim untuk peninjauan ulang kompatibilitas Steam Deck yang akan akan menyertakan pengujian Steam Machine.`,
  _ = `Kirim untuk Peninjauan Ulang`,
  _ = `Jika kamu melakukan perubahan pada build game-mu sejak peninjauan sebelumnya, kamu bisa meminta peninjauan kompatibilitas yang baru.`,
  _ = `Silakan deskripsikan alasan permintaan peninjauan ulang di bawah. Alasan umum untuk peninjauan ulang termasuk:`,
  _ = `Kamu sudah membuat perubahan di build-mu untuk memperbaiki kegagalan dalam pengujian kompatibilitas sebelumnya. Silakan deskripsikan kendala spesifik yang telah diperbaiki.`,
  _ = `Kamu telah mengirimkan, atau akan mengirimkan versi baru dari game-mu, dan ingin laporannya diperbarui.`,
  _ = `Meminta pengujian ulang menggunakan branch %1$s. Game build di Steam sudah diperbarui untuk memperbaiki kendala yang dilaporkan.`,
  _ = `Riwayat Pengujian`,
  _ = `Tampilan Toko`,
  _ = `Kompatibilias Hardware: %1$s (%2$s)`,
  _ = `Dipublikasikan`,
  _ = `Belum Dipublikasikan`,
  _ = `Riwayat`,
  _ = `Runtime yang Direkomendasikan`,
  _ = `Ini adalah versi game-mu (konten/executable) yang akan dikirimkan ke dan dijalankan oleh pelanggan secara default di Steam Deck.`,
  _ = `Format Input yang Diharapkan`,
  _ = `Memerlukan h264`,
  _ = `Versi Proton yang Diuji`,
  _ = `Pengujian ID Build`,
  _ = `Debug RPO`,
  _ = `Debug FDM`,
  _ = `TSO Diaktifkan`,
  _ = `Game-mu berstatus “Tidak Diketahui” di %1$s karena pengujian %1$s tidak lengkap`,
  _ = `Game-mu tidak dapat dimainkan di %1$s saat ini`,
  _ = `Game-mu tidak sepenuhnya didukung di %1$s karena isu terkait Proton atau %1$s sendiri. Kami telah mencatat isu-isu ini dan bekerja untuk memperbaikinya. Sementara itu, game-mu tidak akan bisa diluncurkan atau berjalan dengan baik di %1$s.`,
  _ = `Game-mu “Dapat Dimainkan” di %1$s`,
  _ = `Game-mu dapat dimainkan di %1$s, tapi pelanggan perlu berusaha ekstra untuk berinteraksi atau mengonfigurasikannya. Kamu dapat memperbaiki segala masalah yang dijelaskan di bawah ini dan kirim ulang untuk peninjauan kompatibilitas.`,
  _ = `Game-mu "%1$s Verified"!`,
  _ = `Selamat! Game-mu memberi pengalaman yang menyenangkan di %1$s dan akan ditampilkan demikian di Toko Steam dan dalam Perpustakaan Steam pemain di %1$s.`,
  _ = `Ingin berbagi pencapaian ini dengan penggemarmu? Berikut tautan ke laman landas keren yang dapat kamu gunakan: %1$s`,
  _ = `Game-mu belum diuji di Steam Machine`,
  _ = `Game-mu belum diuji di Steam Frame`,
  _ = `Ini menyebabkan rating berubah menjadi Dapat Dimainkan`,
  _ = `Ini menyebabkan rating berubah menjadi Tidak Didukung`,
  _ = `Ini ditampilkan sebagai pesan informatif kepada pelanggan`,
  _ = `Tidak Valid`,
  _ = `Peluncuran Awal`,
  _ = `Peluncur`,
  _ = `Kontroler Peluncur`,
  _ = `Teks Peluncur`,
  _ = `Keyboard Peluncur`,
  _ = `Peringatan Perangkat`,
  _ = `Pembuka Game`,
  _ = `Pemain Tunggal`,
  _ = `Multipemain Lokal`,
  _ = `Multipemain Online`,
  _ = `Anti-Cheat`,
  _ = `Anti-Cheat`,
  _ = `Anti-Cheat/Multipemain`,
  _ = `Konfigurasi Kontroler Default`,
  _ = `Keyboard`,
  _ = `Glif Kontroler`,
  _ = `Performa Konfigurasi Default`,
  _ = `Tampilan`,
  _ = `Output Video`,
  _ = `Resolusi Asli`,
  _ = `Keterbacaan Teks`,
  _ = `Audio`,
  _ = `Menu`,
  _ = `Penyimpanan Cloud Lintas Platform`,
  _ = `Pemain Tunggal Offline`,
  _ = `Kontroler Eksternal (Pemain Utama)`,
  _ = `Kontroler Eksternal (Multipemain Lokal)`,
  _ = `Pengaturan Pertama Kali`,
  _ = `Pengaturan Kontroler Pertama Kali`,
  _ = `Pengaturan Offline Pertama Kali`,
  _ = `Fungsionalitas Game`,
  _ = `VR`,
  _ = `Catatan`,
  _ = `Keluar Tanpa Masalah`,
  _ = `Keluar Tanpa Masalah (Peluncur)`,
  _ = `Input Gamepad/Mouse Serentak`,
  _ = `Fungsionalitas Bantuan: Editor Map`,
  _ = `Pembatas Bingkai Didukung`,
  _ = `Fokus Multijendela (Otomatis)`,
  _ = `Fokus Multijendela (Manual)`,
  _ = `Software`,
  _ = `Input Gamepad/Mouse bersamaan`,
  _ = `Input Teks`,
  _ = `Input Audio`,
  _ = `Lanjutkan dari Mode Tidur`,
  _ = `Output Tampilan Berskala`,
  _ = `Tautan/Konten Eksternal`,
  _ = `Dihentikan`,
  _ = `Fon Mendukung Semua Karakter`,
  _ = `Pengaturan Tampilan Disimpan per Perangkat, Bukan di Cloud`,
  _ = `Konfigurasi Kontroler Default`,
  _ = `Kontroler Default Diaktifkan`,
  _ = `Penyimpanan Cloud Diaktifkan secara Default`,
  _ = `Periferal (Keyboard)`,
  _ = `Periferal (Webcam)`,
  _ = `Periferal (USB Guitar)`,
  _ = `Dukungan HDR`,
  _ = `Dukungan OS`,
  _ = `Performa Konfigurasi Default Steam Machine`,
  _ = `Performa Streaming VR Steam Machine`,
  _ = `Dukungan Streaming VR Steam Machine`,
  _ = `Peringatan Perangkat Steam Machine`,
  _ = `Tampilan Steam Machine`,
  _ = `Audio Steam Machine`,
  _ = `Steam Machine`,
  _ = `SteamOS`,
  _ = `Steam Deck`,
  _ = `Steam Frame (Mandiri)`,
  _ = `Ajukan permintaan pengujian Steam Deck, yang akan memulai pengujian untuk rating kompatibilitas %1$s.`,
  _ = `Selamat datang! Kamu bisa mengirimkan game-mu untuk peninjauan kompatibilitas Headset Steam Frame (Mandiri) di sini.`,
  _ = `Peninjauan Mandiri Daftar Periksa Kompatibilitas Steam Frame (Mandiri)`,
  _ = `Berikut adalah beberapa kriteria terpenting yang kami periksa saat meninjau kompatibilitas game dengan Steam Frame. Silakan isi formulir di bawah ini dan beri tahu kami build/branch game mana yang ingin diuji, dan kami akan menambahkan game tersebut ke antrean peninjauan kami. Setelah peninjauan selesai, kamu akan menerima email pemberitahuan dengan ringkasan, dan halaman ini akan diperbarui dengan hasil pengujian yang terperinci.`,
  _ = `Untuk info lebih lanjut tentang proses pengujian, lihat %1$s.`,
  _ = `Proses Peninjauan Kompatibilitas Steam Frame (Mandiri)`,
  _ = `Berikut adalah hal-hal terpenting yang akan kami tinjau untuk memberikan rating kompatibilitas kepada game-mu. Untuk memulai proses peninjauan kompatibilitas Steam Frame, silakan jawab pertanyaan-pertanyaan berikut sebaik mungkin.`,
  _ = `Permintaan pengujian tidak tersedia sebelum game dirilis`,
  _ = `Apakah game-mu akan memberikan pengalaman yang luar biasa bagi para pemain di Steam Deck? Kami memiliki proses peninjauan di mana tim kami akan memainkan dan menguji game-mu. Jika pengalaman bermainnya lancar bagi para pemain di Steam Deck, game-mu akan mendapatkan tag "Terverifikasi Steam Deck".`,
  _ = `Selamat datang! Kamu bisa mengirimkan judul peninjauan kompatibilitas Steam Deck di sini.`,
  _ = `Berikut adalah beberapa kriteria terpenting yang kami periksa saat meninjau kompatibilitas game dengan Steam Deck. Silakan isi formulir di bawah ini dan beri tahu kami build/branch game mana yang ingin diuji, dan kami akan menambahkan game tersebut ke antrean peninjauan kami. Setelah peninjauan selesai, kamu akan menerima email pemberitahuan dengan ringkasan, dan halaman ini akan diperbarui dengan hasil pengujian yang terperinci.`,
  _ = `Kamu tetap dapat mengirimkan game-mu meskipun tidak memenuhi semua kriteria untuk mendapatkan rating Terverifikasi. Kami menggunakan informasi pengujian mandiri ini untuk memprioritaskan game yang akan ditinjau dan untuk mengkomunikasikan masalah kompatibilitas apa pun yang mungkin dimiliki game-mu sejelas mungkin.`,
  _ = `Untuk info lebih lanjut tentang proses pengujian, lihat %1$s dan %2$s.`,
  _ = `Proses Peninjauan Kompatibilitas Steam Deck`,
  _ = `rekomendasi tambahan untuk Steam Deck`,
  _ = `Peninjauan Mandiri Daftar Periksa Kompatibilitas Steam Deck`,
  _ = `Berikut adalah hal-hal terpenting yang akan kami tinjau untuk memberikan rating kompatibilitas kepada game-mu. Untuk memulai proses peninjauan kompatibilitas Deck, silakan jawab pertanyaan-pertanyaan berikut sebaik mungkin.`,
  _ = `Saat ini, proses peninjauan Kompatibilitas Steam Deck hanya tersedia untuk game dan tidak tersedia untuk jenis aplikasi lain seperti DLC, alat, atau soundtrack, kecuali dalam kasus tertentu.`,
  _ = `Dukungan Kontroler`,
  _ = `Entri Teks`,
  _ = `Tampilan`,
  _ = `Fungsionalitas`,
  _ = `Steam Cloud`,
  _ = `Peluncur`,
  _ = `Branch`,
  _ = `Silakan uji menggunakan branch ini`,
  _ = `Tandai sebagai siap untuk ditinjau...`,
  _ = `Ini akan menandai build-mu sebagai siap untuk peninjauan kompatibilitas Steam Deck. Kamu akan menerima pemberitahuan email tentang hasilnya dalam beberapa hari.`,
  _ = `Kamu dapat meninggalkan catatan di bawah untuk membantu mempercepat pengujian atau memberikan kredensial akun pengujian untuk server login pihak ketiga.`,
  _ = `Masukkan catatan di sini`,
  _ = `Permintaan bantuan untuk peninjauan ini`,
  _ = `Untuk rincian selengkapnya, lihat laporan pengujian ini di situs bantuan`,
  _ = `Buat tiket bantuan terkait peninjauan kompatibilitas Steam Deck`,
  _ = `Harap sertakan pertanyaan atau komentar untuk tim penguji ketika membuat tiket bantuan.`,
  _ = `Jika kamu punya pertanyaan spesifik tentang proses peninjauan kompatibilitas atau hasilnya untuk game-mu, silakan tuliskan di bawah ini.`,
  _ = `Perlu diingat bahwa jika kamu ingin game-mu ditinjau ulang, sebaiknya gunakan tombol "KIRIM UNTUK PENINJAUAN ULANG" di bawah ini daripada memintanya di sini.`,
  _ = `Saya punya pertanyaan atau komentar tentang laporan Kompatibilitas Steam Deck: `,
  _ = `Ya, game saya memiliki dukungan kontroler penuh: semua fungsi dapat diakses dengan kontroler menggunakan konfigurasi default.`,
  _ = `Ya, game saya menampilkan petunjuk kontroler Steam Deck atau Xbox dalam game ketika ada perintah untuk menekan tombol kontroler.`,
  _ = `Salah satunya: game saya tidak memerlukan input teks apa pun; atau memanggil API input teks Steam yang sesuai sesuai kebutuhan.`,
  _ = `Game saya tidak memerlukan input teks apa pun.`,
  _ = `Game saya memanggil API keyboard/input teks Steam saat input teks diperlukan.`,
  _ = `Game saya tidak menggunakan API Steam saat input teks diperlukan.`,
  _ = `Game saya tidak memiliki file penyimpanan.`,
  _ = `Game saya memiliki file penyimpanan, tapi tidak menggunakan Steam Cloud untuk itu.`,
  _ = `Game saya menggunakan Steam Cloud untuk menyimpan progres permainan; hanya ada build untuk Windows.`,
  _ = `Game saya menggunakan Steam Cloud untuk menyimpan progres permainan dan mendukung file penyimpanan lintas platform (cth. Windows/Linux).`,
  _ = `Game saya menggunakan Steam Cloud untuk menyimpan progres permainan, tapi tidak mendukung file penyimpanan lintas platform (cth. Windows/Linux).`,
  _ = `Ya, game saya dapat berjalan pada resolusi 1280 x 800 (diutamakan) atau 1280 x 720.`,
  _ = `Ya, ukuran fon terkecil di layar dalam game saya tidak pernah berukuran kurang dari 9 piksel pada resolusi 1280 x 800.`,
  _ = `Salah satunya: game saya tidak memiliki peluncur; atau peluncurnya dapat dinavigasi sepenuhnya dengan kontroler.`,
  _ = `Salah satunya: game saya mendukung Steam Cloud untuk menyimpan progres permainan; atau tidak memiliki file penyimpanan.`,
  _ = `Salah satunya: game saya mendukung penyimpanan progres permainan lintas platform; atau hanya berjalan di satu platform (Linux/Windows).`,
  _ = `Kecuali ditetapkan sebaliknya, kami akan menguji build Windows-mu dengan menjalankannya melalui Proton.`,
  _ = `Jika tersedia, uji build Linux saya alih-alih build Windows.`,
  _ = `Game saya tidak menggunakan peluncur atau alat konfigurasi eksternal.`,
  _ = `Game saya menggunakan peluncur dan peluncurnya memiliki dukungan kontroler penuh.`,
  _ = `Game saya menggunakan peluncur dan peluncurnya tidak berfungsi penuh jika pengguna hanya menggunakan kontroler, tanpa keyboard atau mouse.`,
  _ = `(Meskipun penyimpanan lintas platform tidak diharuskan untuk mendapatkan rating Terverifikasi, fungsi ini sangat berguna bagi pelanggan yang terkadang bermain di PC Windows dan terkadang di Steam Deck yang menjalankan build Linux native. Lihat %1$s.)`,
  _ = `dokumentasi`,
  _ = `(Layar Steam Deck jauh lebih kecil dibanding layar-layar PC lainnya. Jika game-mu memiliki teks berukuran kecil, maka akan sulit atau bahkan tidak mungkin untuk dibaca oleh pelanggan di layar Steam Deck, meskipun teksnya bisa dengan mudah dibaca di monitor biasa.)`,
  _ = `(Sebagian besar Steam Deck tidak terhubung dengan keyboard, sehingga pelanggan bergantung pada keyboard di layar untuk memasukkan teks, dan Steam menyediakan API untuk memudahkan penggunaan keyboard layar. Jika pelanggan perlu secara manual membuka keyboard, game-mu tidak akan mendapatkan rating Terverifikasi. Silakan lihat %1$s.)`,
  _ = `Rekomendasi Input`,
  _ = `(Jika game-mu menggunakan peluncur, peluncur tersebut harus memiliki persyaratan yang sama dengan game itu sendiri untuk mendapatkan rating Terverifikasi: Harus sepenuhnya dapat digunakan hanya dengan kontrol bawaan Steam Deck, harus dapat dibaca, dll. Jika peluncurmu tidak memenuhi persyaratan-persyaratan ini, game-mu tidak akan mendapatkan rating Terverifikasi, meskipun game itu sendiri memenuhi syarat. Silakan lihat %1$s.)`,
  _ = `Rekomendasi Peluncur`,
  _ = `(Sebagian besar pelanggan Steam Deck juga bermain di PC desktop. Penyimpanan Cloud tidak diperlukan untuk mendapatkan rating Terverifikasi, tapi sangat berguna bagi pengguna: Menambahkan dukungan %1$s untuk penyimpanan progres permainan memungkinkan pelanggan untuk menyimpan progres mereka di desktop dan kemudian melanjutkannya di Deck, atau sebaliknya.)`,
  _ = `Steam Cloud`,
  _ = `(Catatan: Dukungan kontroler penuh diperukan untuk mendapatkan rating Terverifikasi.)`,
  _ = `Game-mu telah ditambahkan ke antrean peninjauan kami`,
  _ = `Kami akan segera meninjau game-mu dan memberitahumu jika terdapat masalah.`,
  _ = `Silakan selesaikan peninjauan build Steam sebelum mengirimkannya untuk peninjauan kompatibilitas hardware.`,
  _ = `Game-mu tidak dapat dimainkan di Steam Deck saat ini`,
  _ = `Game-mu tidak sepenuhnya didukung di Steam Deck karena masalah pada Proton atau Steam Deck itu sendiri. Kami telah mencatat masalah ini dan sedang berupaya memperbaikinya. Sementara ini, game-mu tidak akan dapat diluncurkan atau berjalan dengan benar di Steam Deck.`,
  _ = `Game-mu “Dapat Dimainkan” di Steam Deck`,
  _ = `Game-mu dapat dimainkan di Steam Deck, tapi pelanggan perlu berusaha ekstra untuk berinteraksi atau mengonfigurasikannya. Kamu dapat mengirimkannya kembali untuk Peninjauan Kompatibilitas Steam Deck setelah memperbaiki masalah yang disebutkan di bawah ini.`,
  _ = `Build`,
  _ = `Jika tersedia, uji build Android saya alih-alih build Windows`,
  _ = `Uji build Windows saya`,
  _ = `Uji build Linux saya`,
  _ = `Apakah sebaiknya kami menguji pengalaman 2D atau VR (jika tersedia)?`,
  _ = `2D`,
  _ = `VR`,
  _ = `Tidak berlaku untuk game %1$s`,
  _ = `Verified, tanpa penggunaan "Hapus Status Penilaian Performa"`,
  _ = `Verified, dengan setidaknya satu kali penggunaan "Hapus Status Penilaian Performa"`,
  _ = `Playable, tanpa penggunaan "Hapus Status Penilaian Performa"`,
  _ = `Playable, dengan setidaknya satu kali penggunaan "Hapus Status Penilaian Performa"`,
  _ = `Unsupported (Tidak Kompatibel)`,
  _ = `Bukan game VR (penilaian tidak berlaku)`,
  _ = `Overlay Penilaian Performa`,
  _ = `Gunakan Overlay Penilaian Performa untuk menjawab pertanyaan di bawah. Lihat %1$s untuk info lebih lanjut.`,
  _ = `Dokumentasi Performa VR`,
  _ = `(Jika game-mu memiliki teks berukuran kecil, maka akan sulit atau bahkan tidak mungkin untuk dibaca oleh pelanggan di layar Steam Frame, meskipun teksnya bisa dengan mudah dibaca di monitor biasa.)`,
  _ = `(Sebagian besar Steam Frame tidak terhubung dengan keyboard, sehingga pelanggan bergantung pada keyboard di layar untuk memasukkan teks, dan Steam menyediakan API untuk memudahkan penggunaan keyboard layar. Jika pelanggan perlu secara manual membuka keyboard, game-mu tidak akan mendapatkan rating Terverifikasi. Silakan lihat %1$s.)`,
  _ = `Daftar periksa kompatibilitas Steam Frame`,
  _ = `(Jika game-mu menggunakan peluncur, peluncur tersebut harus memiliki persyaratan yang sama dengan game itu sendiri untuk mendapatkan rating Terverifikasi: Harus sepenuhnya dapat digunakan hanya dengan kontrol bawaan Steam Frame, harus dapat dibaca, dll. Jika peluncurmu tidak memenuhi persyaratan-persyaratan ini, game-mu tidak akan mendapatkan rating Terverifikasi, meskipun game itu sendiri memenuhi syarat. Silakan lihat %1$s.)`,
  _ = `(Sebagian besar pelanggan Steam Frame juga bermain di PC desktop. Penyimpanan Cloud tidak diperlukan untuk mendapatkan rating Terverifikasi, tapi sangat berguna bagi pengguna: Menambahkan dukungan %1$s untuk penyimpanan progres permainan memungkinkan pelanggan untuk menyimpan progres mereka di desktop dan kemudian melanjutkannya di Steam Frame, atau sebaliknya.)`,
  _ = `(Meskipun penyimpanan lintas platform tidak diharuskan untuk mendapatkan rating Terverifikasi, fungsi ini sangat berguna bagi pelanggan yang terkadang bermain di PC Windows dan terkadang di Steam Frame yang menjalankan build Linux native. Lihat %1$s.)`,
  _ = `Ya, game saya menampilkan petunjuk kontroler Steam Frame/Steam Deck atau Xbox dalam game ketika ada perintah untuk menekan tombol kontroler`,
  _ = `Jika hasil Penilaian Performa di atas memerlukan setidaknya satu kali penggunaan "Hapus Status Penilaian Performa", silakan pilih salah satu atau beberapa alasan di bawah ini.`,
  _ = `Performa menurun saat game dibuka`,
  _ = `Performa menurun saat pemuatan layar`,
  _ = `Lainnya (silakan sebutkan)`,
  _ = `Kamu meminta peninjauan untuk Android, tapi %1$s tidak memiliki depot Android.`,
  _ = `paket Dev Comp-mu`,
  _ = `dummy`,
  _ = {
    Valve_Confidential: _,
    Valve_Confidential_Description: _,
    Footer_Description: _,
    Footer_Sitemap_ContactSupport: _,
    PricingExplorer_LoadError: _,
    PricingExplorer_About_Title: _,
    PricingExplorer_About_Desc1: _,
    PricingExplorer_About_Desc2: _,
    PricingExplorer_About_Link1: _,
    PricingExplorer_About_LinkName1: _,
    PricingExplorer_About_Link2: _,
    PricingExplorer_About_LinkName2: _,
    PricingExplorer_About_Dash: _,
    PricingExplorer_About_LastUpdated: _,
    PricingExplorer_Explore_title: _,
    PricingExplorer_Explore_desc1: _,
    PricingExplorer_Explore_line1: _,
    PricingExplorer_Explore_line2: _,
    PricingExplorer_Explore_line3: _,
    PricingExplorer_Base: _,
    PricingExplorer_BasePrice: _,
    PricingExplorer_TableHeader: _,
    PricingExplorer_Column1: _,
    PricingExplorer_Column2: _,
    PricingExplorer_Column3: _,
    PricingExplorer_Column4: _,
    PricingExplorer_Regions_TableHeader: _,
    PricingExplorer_Regions_Column1: _,
    Pricing_Dummy: _,
    ContentSurvey_Title: _,
    ContentSurvey_Title_Default: _,
    ContentSurvey_History_Title: _,
    ContentSurvey_History_Title_Default: _,
    ContentSurvey_InvalidApp: _,
    PartnerSite_PermissionDenied: _,
    PartnerSite_NotLoggedIn: _,
    SteamLearn_Name: _,
    SteamLearn_FilterProject: _,
    SteamLearn_CreateNew: _,
    SteamLearn_GoToProjects: _,
    SteamLearn_Project: _,
    SteamLearn_Project_Schedule: _,
    SteamLearn_Project_CreateProject: _,
    SteamLearn_Project_Create_Name: _,
    SteamLearn_Project_Create_Desc: _,
    SteamLearn_Project_Create_Header: _,
    SteamLearn_Project_Edit_Guidance: _,
    SteamLearn_Project_Edit_Accept: `OK`,
    SteamLearn_Project_Edit_Cancel: _,
    SteamLearn_Project_Create_BadName: _,
    SteamLearn_Project_Create_Error: _,
    SteamLearn_Project_Edit_Error: _,
    SteamLearn_Config_NoDescription: _,
    SteamLearn_LiveTrain_Project: _,
    SteamLearn_Event_Completed: _,
    SteamLearn_Event_Duration: _,
    SteamLearn_Event_CompletedDetails: _,
    SteamLearn_Event_InProgress: _,
    SteamLearn_FetchStatus_Percent: _,
    SteamLearn_FetchStatus_Metadata: _,
    SteamLearn_FetchStatus_Cleanup: _,
    SteamLearn_FetchStatus_Canceled: _,
    SteamLearn_TrainStatus_WaitingOnASS: _,
    SteamLearn_TrainStatus_InProgress: _,
    SteamLearn_ScheduledTrain_Time: _,
    SteamLearn_Status_Fetch_Status_Unknown: _,
    SteamLearn_Status_Fetch_Status_Canceled: _,
    SteamLearn_Status_Fetch_Status_Error: _,
    SteamLearn_Status_Train_Fetch_TimeEstimate: _,
    SteamLearn_Header_Version_Unpublished: _,
    SteamLearn_Project_Publish_Accept: _,
    SteamLearn_Project_Publish_Cancel: _,
    SteamLearn_Edit: _,
    SteamLearn_Project_Save: _,
    SteamLearn_Project_Discard: _,
    SteamLearn_Project_Overview: _,
    SteamLearn_Config_DataSources: _,
    SteamLearn_Config_DataSources_None: _,
    SteamLearn_Config_DataSources_Add: _,
    SteamLearn_Config_DataSourcesDialog_Add: _,
    SteamLearn_Config_DataSourcesDialog_Add_1: _,
    SteamLearn_Config_DataSourcesDialog_Add_Multiple: _,
    SteamLearn_Config_DataSources_Remove: _,
    SteamLearn_Config_DataSources_Update: _,
    SteamLearn_Config_DataSource_Input_Preprocess_CompactTable: _,
    SteamLearn_DSKeyType_External: _,
    SteamLearn_DSKeyType_AccountID: _,
    SteamLearn_DSKeyType_AppID: _,
    SteamLearn_DSKeyType_MarketingMessageID: _,
    SteamDeck_BuildReview_Status_Raw_Title: _,
    SteamDeck_BuildReview_Status_Raw_Description: _,
    SteamDeck_BuildReview_Status_TestProperties_Description: _,
    SteamDeck_BuildReview_Status_TestProperties_Playable: _,
    SteamDeck_BuildReview_Status_TestProperty_Name: _,
    SteamDeck_BuildReview_Status_TestProperty_Value: _,
    SteamDeck_BuildReview_Status_TestProperty_Desc: _,
    SteamDeck_BuildReview_Status_Description: _,
    SteamDeck_BuildReview_Header_History: _,
    SteamDeck_BuildReview_Header_Results: _,
    SteamDeck_BuildReview_Status_Raw_Result: _,
    SteamDeck_BuildReview_Status_Raw_Test: `Uji`,
    SteamDeck_BuildReview_Status_Raw_Comment: _,
    SteamDeck_BuildReview_Status_Raw_Impact: _,
    SteamDeck_BuildReview_Status_Pass: _,
    SteamDeck_BuildReview_Status_Fail: _,
    SteamDeck_BuildReview_Status_FailMinor: _,
    SteamDeck_BuildReview_Status_NotApplicable: `---`,
    SteamDeck_BuildReview_Viewing_Historical: _,
    SteamDeck_BuildReview_Viewing_Published: _,
    SteamDeck_BuildReview_PublishedOn: _,
    SteamDeck_BuildReview_ReportedOn: _,
    SteamDeck_BuildReview_Documentation: _,
    SteamDeck_BuildReview_PublishResults: _,
    SteamDeck_BuildReview_PublishDialog_Title: _,
    SteamDeck_BuildReview_PublishDialog_Body: _,
    SteamDeck_BuildReview_UnknownError: _,
    SteamDeck_BuildReview_Help_Request_Title: _,
    SteamDeck_BuildReview_RequestStatusActive: _,
    SteamDeck_BuildReview_RequestStatusClosed: _,
    SteamDeck_BuildReview_InReview_ViewTicket: _,
    SteamDeck_BuildReview_Create_HelpRequest: _,
    SteamDeck_BuildReview_Create_HelpRequest_NotesDefault: _,
    SteamDeck_BuildReview_Create_HelpRequest_NotesDefault_Rereview: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label_Machine: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Button: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_1: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2a: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2b: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Ticket_Content: _,
    SteamDeck_BuildReview_CompatibilityTests: _,
    SteamDeck_BuildReview_Status_Title: _,
    SteamDeck_HardwareCompatibility_Title: _,
    SteamDeck_AppLanding_Published: _,
    SteamDeck_AppLanding_Unpublished: _,
    SteamDeck_AppLanding_History: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RecommendedRuntime: _,
    SteamDeckVerified_TestDisplayName_TestPropertyDescription_RecommendedRuntime:
      _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_ExpectedInput: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RequiresH264: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TestedProtonVersion: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TestedBuildID: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RPODebug: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_FDMDebug: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TSOEnable: _,
    SteamHardware_BuildReview_Unknown_Title: _,
    SteamHardware_BuildReview_Unsupported_Title: _,
    SteamHardware_BuildReview_Unsupported_Description: _,
    SteamHardware_BuildReview_Playable_Title: _,
    SteamHardware_BuildReview_Playable_Description: _,
    SteamHardware_BuildReview_Verified_Title: _,
    SteamHardware_BuildReview_Verified_Description: _,
    SteamHardware_BuildReview_Verified_Share: _,
    SteamHardware_Machine_Unknown: _,
    SteamHardware_Frame_Unknown: _,
    SteamHardware_RatingImpact_Playable: _,
    SteamHardware_RatingImpact_Unsupported: _,
    SteamHardware_RatingImpact_Informational: _,
    SteamDeckVerified_TestDisplayName_0: _,
    SteamDeckVerified_TestDisplayName_1: _,
    SteamDeckVerified_TestDisplayName_2: _,
    SteamDeckVerified_TestDisplayName_3: _,
    SteamDeckVerified_TestDisplayName_4: _,
    SteamDeckVerified_TestDisplayName_5: _,
    SteamDeckVerified_TestDisplayName_6: _,
    SteamDeckVerified_TestDisplayName_7: _,
    SteamDeckVerified_TestDisplayName_8: _,
    SteamDeckVerified_TestDisplayName_9: _,
    SteamDeckVerified_TestDisplayName_10: _,
    SteamDeckVerified_TestDisplayName_11: _,
    SteamDeckVerified_TestDisplayName_12: _,
    SteamDeckVerified_TestDisplayName_13: _,
    SteamDeckVerified_TestDisplayName_14: _,
    SteamDeckVerified_TestDisplayName_15: _,
    SteamDeckVerified_TestDisplayName_16: _,
    SteamDeckVerified_TestDisplayName_17: _,
    SteamDeckVerified_TestDisplayName_18: _,
    SteamDeckVerified_TestDisplayName_19: _,
    SteamDeckVerified_TestDisplayName_20: _,
    SteamDeckVerified_TestDisplayName_21: _,
    SteamDeckVerified_TestDisplayName_22: _,
    SteamDeckVerified_TestDisplayName_23: _,
    SteamDeckVerified_TestDisplayName_24: _,
    SteamDeckVerified_TestDisplayName_25: _,
    SteamDeckVerified_TestDisplayName_26: _,
    SteamDeckVerified_TestDisplayName_27: _,
    SteamDeckVerified_TestDisplayName_29: _,
    SteamDeckVerified_TestDisplayName_30: _,
    SteamDeckVerified_TestDisplayName_31: _,
    SteamDeckVerified_TestDisplayName_32: _,
    SteamDeckVerified_TestDisplayName_33: `VR`,
    SteamDeckVerified_TestDisplayName_34: _,
    SteamDeckVerified_TestDisplayName_35: _,
    SteamDeckVerified_TestDisplayName_36: _,
    SteamDeckVerified_TestDisplayName_37: _,
    SteamDeckVerified_TestDisplayName_38: _,
    SteamDeckVerified_TestDisplayName_39: _,
    SteamDeckVerified_TestDisplayName_40: _,
    SteamDeckVerified_TestDisplayName_41: _,
    SteamDeckVerified_TestDisplayName_42: _,
    SteamDeckVerified_TestDisplayName_43: _,
    SteamDeckVerified_TestDisplayName_44: _,
    SteamDeckVerified_TestDisplayName_45: _,
    SteamDeckVerified_TestDisplayName_46: _,
    SteamDeckVerified_TestDisplayName_47: _,
    SteamDeckVerified_TestDisplayName_48: _,
    SteamDeckVerified_TestDisplayName_49: _,
    SteamDeckVerified_TestDisplayName_50: _,
    SteamDeckVerified_TestDisplayName_51: _,
    SteamDeckVerified_TestDisplayName_52: _,
    SteamDeckVerified_TestDisplayName_53: _,
    SteamDeckVerified_TestDisplayName_54: _,
    SteamDeckVerified_TestDisplayName_55: _,
    SteamDeckVerified_TestDisplayName_56: _,
    SteamDeckVerified_TestDisplayName_57: _,
    SteamDeckVerified_TestDisplayName_58: _,
    SteamDeckVerified_TestDisplayName_59: _,
    SteamDeckVerified_TestDisplayName_60: _,
    SteamDeckVerified_TestDisplayName_61: _,
    SteamDeckVerified_TestDisplayName_62: _,
    SteamDeckVerified_TestDisplayName_63: _,
    SteamDeckVerified_TestDisplayName_64: _,
    SteamDeckVerified_TestDisplayName_65: _,
    Compatibility_Tab_Steam_Machine: _,
    Compatibility_Tab_Steam_OS: _,
    Compatibility_Tab_Steam_Deck: _,
    Compatibility_Tab_Steam_Frame: _,
    SteamDeck_BuildReview_PleaseRequestTest: _,
    SteamFrame_BuildReview_Checklist_Intro_Header_V2: _,
    SteamFrame_BuildReview_PleaseConfirm_Title_V2: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P1: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P3: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P3_ReviewProcess: _,
    SteamFrame_BuildReview_PleaseConfirm_Description_V2: _,
    SteamDeck_TestRequest_BuildNotReleased: _,
    SteamDeck_BuildReview_Checklist_Intro: _,
    SteamDeck_BuildReview_Checklist_Intro_Header_V2: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P1: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P2: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3_ReviewProcess: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3_Additional: _,
    SteamDeck_BuildReview_PleaseConfirm_Title_V2: _,
    SteamDeck_BuildReview_PleaseConfirm_Description_V2: _,
    SteamDeck_BuildReview_AppTypeUnavailable: _,
    SteamDeck_BuildReview_Checklist_Input: _,
    SteamDeck_BuildReview_Checklist_Text: _,
    SteamDeck_BuildReview_Checklist_Display: _,
    SteamDeck_BuildReview_Checklist_Functionality: _,
    SteamDeck_BuildReview_Checklist_SteamCloud: _,
    SteamDeck_BuildReview_Checklist_Launcher: _,
    SteamDeck_BuildReview_Checklist_Branch: _,
    SteamDeck_BuildReview_Checklist_Branch_PleaseTest: _,
    SteamDeck_BuildReview_MarkReady_Button: _,
    SteamDeck_BuildReview_MarkReady_Description: _,
    SteamDeck_BuildReview_MarkReady_Notes: _,
    SteamDeck_BuildReview_MarkReady_NotesDefault: _,
    SteamDeck_BuildReview_HelpRequest_Link: _,
    SteamDeck_BuildReview_ViewMoreDetailsInHelp: _,
    SteamDeck_BuildReview_Create_HelpRequest_Title: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes_1: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes_2: _,
    SteamDeck_BuildReview_Create_HelpRequest_SupportTicketIntro: _,
    SteamDeck_BuildReview_Check_Controller: _,
    SteamDeck_BuildReview_Check_Icons: _,
    SteamDeck_BuildReview_Check_TextInput: _,
    SteamDeck_BuildReview_Check_TextInput_V2_NoTextEntry: _,
    SteamDeck_BuildReview_Check_TextInput_V2_YesSteamAPIs: _,
    SteamDeck_BuildReview_Check_TextInput_V2_NoSteamAPIs: _,
    SteamDeck_BuildReview_Check_Cloud_NoSaves: _,
    SteamDeck_BuildReview_Check_Cloud_YesSavesNoCloud: _,
    SteamDeck_BuildReview_Check_Cloud_SinglePlatform: _,
    SteamDeck_BuildReview_Check_Cloud_YesCrossSaves: _,
    SteamDeck_BuildReview_Check_Cloud_NoCrossSaves: _,
    SteamDeck_BuildReview_Check_Display1280: _,
    SteamDeck_BuildReview_Check_DisplayFont: _,
    SteamDeck_BuildReview_Check_FunctionalityLauncher: _,
    SteamDeck_BuildReview_Check_FunctionalityCloudSaves: _,
    SteamDeck_BuildReview_Check_FunctionalityCrossPlatformCloudSaves: _,
    SteamDeck_BuildReview_Check_TestLinuxBuild_Preamble: _,
    SteamDeck_BuildReview_Check_TestLinuxBuild: _,
    SteamDeck_BuildReview_Check_Launcher_V2_NoLauncher: _,
    SteamDeck_BuildReview_Check_Launcher_V2_ControllerSupport: _,
    SteamDeck_BuildReview_Check_Launcher_V2_NoControllerSupport: _,
    SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves: _,
    SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves_Documentation: _,
    SteamDeck_BuildReview_CheckNote_DisplayFont: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_InputRecommendations:
      _,
    SteamDeck_BuildReview_CheckNote_Launcher_V2_NoControllerSupport: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_LauncherRecommendations:
      _,
    SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud: _,
    SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud_SteamCloud: _,
    SteamDeck_BuildReview_CheckNote_FullController: _,
    SteamDeck_BuildReview_InReview_Title: _,
    SteamDeck_BuildReview_InReview_Description: _,
    SteamDeck_BuildReview_PleaseComplete: _,
    SteamDeck_BuildReview_Unsupported_Title: _,
    SteamDeck_BuildReview_Unsupported_Description: _,
    SteamDeck_BuildReview_NotMeetRequirements_Title: _,
    SteamDeck_BuildReview_NotMeetRequirements_Description: _,
    SteamFrame_BuildReview_Checklist_Build: _,
    SteamFrame_BuildReview_Build_Android: _,
    SteamFrame_BuildReview_Build_Windows: _,
    SteamFrame_BuildReview_Build_Linux: _,
    SteamFrame_BuildReview_Checklist_Dimension: _,
    SteamFrame_BuildReview_Dimension_2D: `2D`,
    SteamFrame_BuildReview_Dimension_VR: `VR`,
    SteamFrame_NotApplicableForDimension: _,
    SteamFrame_BuildReview_Check_VRPerformance_Verified_Without: _,
    SteamFrame_BuildReview_Check_VRPerformance_Verified_With: _,
    SteamFrame_BuildReview_Check_VRPerformance_Playable_Without: _,
    SteamFrame_BuildReview_Check_VRPerformance_Playable_With: _,
    SteamFrame_BuildReview_Check_VRPerformance_Unsupported: _,
    SteamFrame_BuildReview_Check_VRPerformance_NotApplicable: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_Title: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_Description: _,
    SteamFrame_BuildReview_VRPerformanceLink: _,
    SteamFrame_BuildReview_CheckNote_DisplayFont: _,
    SteamFrame_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs: _,
    SteamFrame_BuildReview_Compatibility_Checklist: _,
    SteamFrame_BuildReview_CheckNote_Launcher_V2_NoControllerSupport: _,
    SteamFrame_BuildReview_CheckNote_Cloud_YesSavesNoCloud: _,
    SteamFrame_BuildReview_CheckNote_Cloud_NoCrossSaves: _,
    SteamFrame_BuildReview_Check_Icons: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_StatusReason: _,
    SteamFrame_BuildReview_Check_VRPerformance_Startup: _,
    SteamFrame_BuildReview_Check_VRPerformance_Loading: _,
    SteamFrame_BuildReview_Check_VRPerformance_Other: _,
    SteamFrame_BuildReview_CheckNote_Missing_Android_License: _,
    SteamFrame_BuildReview_CheckNote_Missing_Android_License_Link: _,
    dummy: _,
  };
export {
  _ as Compatibility_Tab_Steam_Deck,
  _ as Compatibility_Tab_Steam_Frame,
  _ as Compatibility_Tab_Steam_Machine,
  _ as Compatibility_Tab_Steam_OS,
  _ as ContentSurvey_History_Title,
  _ as ContentSurvey_History_Title_Default,
  _ as ContentSurvey_InvalidApp,
  _ as ContentSurvey_Title,
  _ as ContentSurvey_Title_Default,
  _ as Footer_Description,
  _ as Footer_Sitemap_ContactSupport,
  _ as PartnerSite_NotLoggedIn,
  _ as PartnerSite_PermissionDenied,
  _ as PricingExplorer_About_Dash,
  _ as PricingExplorer_About_Desc1,
  _ as PricingExplorer_About_Desc2,
  _ as PricingExplorer_About_LastUpdated,
  _ as PricingExplorer_About_Link1,
  _ as PricingExplorer_About_Link2,
  _ as PricingExplorer_About_LinkName1,
  _ as PricingExplorer_About_LinkName2,
  _ as PricingExplorer_About_Title,
  _ as PricingExplorer_Base,
  _ as PricingExplorer_BasePrice,
  _ as PricingExplorer_Column1,
  _ as PricingExplorer_Column2,
  _ as PricingExplorer_Column3,
  _ as PricingExplorer_Column4,
  _ as PricingExplorer_Explore_desc1,
  _ as PricingExplorer_Explore_line1,
  _ as PricingExplorer_Explore_line2,
  _ as PricingExplorer_Explore_line3,
  _ as PricingExplorer_Explore_title,
  _ as PricingExplorer_LoadError,
  _ as PricingExplorer_Regions_Column1,
  _ as PricingExplorer_Regions_TableHeader,
  _ as PricingExplorer_TableHeader,
  _ as Pricing_Dummy,
  _ as SteamDeckVerified_TestDisplayName_0,
  _ as SteamDeckVerified_TestDisplayName_1,
  _ as SteamDeckVerified_TestDisplayName_10,
  _ as SteamDeckVerified_TestDisplayName_11,
  _ as SteamDeckVerified_TestDisplayName_12,
  _ as SteamDeckVerified_TestDisplayName_13,
  _ as SteamDeckVerified_TestDisplayName_14,
  _ as SteamDeckVerified_TestDisplayName_15,
  _ as SteamDeckVerified_TestDisplayName_16,
  _ as SteamDeckVerified_TestDisplayName_17,
  _ as SteamDeckVerified_TestDisplayName_18,
  _ as SteamDeckVerified_TestDisplayName_19,
  _ as SteamDeckVerified_TestDisplayName_2,
  _ as SteamDeckVerified_TestDisplayName_20,
  _ as SteamDeckVerified_TestDisplayName_21,
  _ as SteamDeckVerified_TestDisplayName_22,
  _ as SteamDeckVerified_TestDisplayName_23,
  _ as SteamDeckVerified_TestDisplayName_24,
  _ as SteamDeckVerified_TestDisplayName_25,
  _ as SteamDeckVerified_TestDisplayName_26,
  _ as SteamDeckVerified_TestDisplayName_27,
  _ as SteamDeckVerified_TestDisplayName_29,
  _ as SteamDeckVerified_TestDisplayName_3,
  _ as SteamDeckVerified_TestDisplayName_30,
  _ as SteamDeckVerified_TestDisplayName_31,
  _ as SteamDeckVerified_TestDisplayName_32,
  _ as SteamDeckVerified_TestDisplayName_33,
  _ as SteamDeckVerified_TestDisplayName_34,
  _ as SteamDeckVerified_TestDisplayName_35,
  _ as SteamDeckVerified_TestDisplayName_36,
  _ as SteamDeckVerified_TestDisplayName_37,
  _ as SteamDeckVerified_TestDisplayName_38,
  _ as SteamDeckVerified_TestDisplayName_39,
  _ as SteamDeckVerified_TestDisplayName_4,
  _ as SteamDeckVerified_TestDisplayName_40,
  _ as SteamDeckVerified_TestDisplayName_41,
  _ as SteamDeckVerified_TestDisplayName_42,
  _ as SteamDeckVerified_TestDisplayName_43,
  _ as SteamDeckVerified_TestDisplayName_44,
  _ as SteamDeckVerified_TestDisplayName_45,
  _ as SteamDeckVerified_TestDisplayName_46,
  _ as SteamDeckVerified_TestDisplayName_47,
  _ as SteamDeckVerified_TestDisplayName_48,
  _ as SteamDeckVerified_TestDisplayName_49,
  _ as SteamDeckVerified_TestDisplayName_5,
  _ as SteamDeckVerified_TestDisplayName_50,
  _ as SteamDeckVerified_TestDisplayName_51,
  _ as SteamDeckVerified_TestDisplayName_52,
  _ as SteamDeckVerified_TestDisplayName_53,
  _ as SteamDeckVerified_TestDisplayName_54,
  _ as SteamDeckVerified_TestDisplayName_55,
  _ as SteamDeckVerified_TestDisplayName_56,
  _ as SteamDeckVerified_TestDisplayName_57,
  _ as SteamDeckVerified_TestDisplayName_58,
  _ as SteamDeckVerified_TestDisplayName_59,
  _ as SteamDeckVerified_TestDisplayName_6,
  _ as SteamDeckVerified_TestDisplayName_60,
  _ as SteamDeckVerified_TestDisplayName_61,
  _ as SteamDeckVerified_TestDisplayName_62,
  _ as SteamDeckVerified_TestDisplayName_63,
  _ as SteamDeckVerified_TestDisplayName_64,
  _ as SteamDeckVerified_TestDisplayName_65,
  _ as SteamDeckVerified_TestDisplayName_7,
  _ as SteamDeckVerified_TestDisplayName_8,
  _ as SteamDeckVerified_TestDisplayName_9,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyDescription_RecommendedRuntime,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_ExpectedInput,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_FDMDebug,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RPODebug,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RecommendedRuntime,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RequiresH264,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TSOEnable,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TestedBuildID,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TestedProtonVersion,
  _ as SteamDeck_AppLanding_History,
  _ as SteamDeck_AppLanding_Published,
  _ as SteamDeck_AppLanding_Unpublished,
  _ as SteamDeck_BuildReview_AppTypeUnavailable,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves_Documentation,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud_SteamCloud,
  _ as SteamDeck_BuildReview_CheckNote_DisplayFont,
  _ as SteamDeck_BuildReview_CheckNote_FullController,
  _ as SteamDeck_BuildReview_CheckNote_Launcher_V2_NoControllerSupport,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_InputRecommendations,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_LauncherRecommendations,
  _ as SteamDeck_BuildReview_Check_Cloud_NoCrossSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_NoSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_SinglePlatform,
  _ as SteamDeck_BuildReview_Check_Cloud_YesCrossSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_YesSavesNoCloud,
  _ as SteamDeck_BuildReview_Check_Controller,
  _ as SteamDeck_BuildReview_Check_Display1280,
  _ as SteamDeck_BuildReview_Check_DisplayFont,
  _ as SteamDeck_BuildReview_Check_FunctionalityCloudSaves,
  _ as SteamDeck_BuildReview_Check_FunctionalityCrossPlatformCloudSaves,
  _ as SteamDeck_BuildReview_Check_FunctionalityLauncher,
  _ as SteamDeck_BuildReview_Check_Icons,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_ControllerSupport,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_NoControllerSupport,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_NoLauncher,
  _ as SteamDeck_BuildReview_Check_TestLinuxBuild,
  _ as SteamDeck_BuildReview_Check_TestLinuxBuild_Preamble,
  _ as SteamDeck_BuildReview_Check_TextInput,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_NoSteamAPIs,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_NoTextEntry,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_YesSteamAPIs,
  _ as SteamDeck_BuildReview_Checklist_Branch,
  _ as SteamDeck_BuildReview_Checklist_Branch_PleaseTest,
  _ as SteamDeck_BuildReview_Checklist_Display,
  _ as SteamDeck_BuildReview_Checklist_Functionality,
  _ as SteamDeck_BuildReview_Checklist_Input,
  _ as SteamDeck_BuildReview_Checklist_Intro,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P1,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P2,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3_Additional,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3_ReviewProcess,
  _ as SteamDeck_BuildReview_Checklist_Intro_Header_V2,
  _ as SteamDeck_BuildReview_Checklist_Launcher,
  _ as SteamDeck_BuildReview_Checklist_SteamCloud,
  _ as SteamDeck_BuildReview_Checklist_Text,
  _ as SteamDeck_BuildReview_CompatibilityTests,
  _ as SteamDeck_BuildReview_Create_HelpRequest,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_1,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2a,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2b,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes,
  _ as SteamDeck_BuildReview_Create_HelpRequest_NotesDefault,
  _ as SteamDeck_BuildReview_Create_HelpRequest_NotesDefault_Rereview,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes_1,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes_2,
  _ as SteamDeck_BuildReview_Create_HelpRequest_SupportTicketIntro,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Title,
  _ as SteamDeck_BuildReview_Documentation,
  _ as SteamDeck_BuildReview_Header_History,
  _ as SteamDeck_BuildReview_Header_Results,
  _ as SteamDeck_BuildReview_HelpRequest_Link,
  _ as SteamDeck_BuildReview_Help_Request_Title,
  _ as SteamDeck_BuildReview_InReview_Description,
  _ as SteamDeck_BuildReview_InReview_Title,
  _ as SteamDeck_BuildReview_InReview_ViewTicket,
  _ as SteamDeck_BuildReview_MarkReady_Button,
  _ as SteamDeck_BuildReview_MarkReady_Description,
  _ as SteamDeck_BuildReview_MarkReady_Notes,
  _ as SteamDeck_BuildReview_MarkReady_NotesDefault,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Description,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Button,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label_Machine,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Ticket_Content,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Title,
  _ as SteamDeck_BuildReview_PleaseComplete,
  _ as SteamDeck_BuildReview_PleaseConfirm_Description_V2,
  _ as SteamDeck_BuildReview_PleaseConfirm_Title_V2,
  _ as SteamDeck_BuildReview_PleaseRequestTest,
  _ as SteamDeck_BuildReview_PublishDialog_Body,
  _ as SteamDeck_BuildReview_PublishDialog_Title,
  _ as SteamDeck_BuildReview_PublishResults,
  _ as SteamDeck_BuildReview_PublishedOn,
  _ as SteamDeck_BuildReview_ReportedOn,
  _ as SteamDeck_BuildReview_RequestStatusActive,
  _ as SteamDeck_BuildReview_RequestStatusClosed,
  _ as SteamDeck_BuildReview_Status_Description,
  _ as SteamDeck_BuildReview_Status_Fail,
  _ as SteamDeck_BuildReview_Status_FailMinor,
  _ as SteamDeck_BuildReview_Status_NotApplicable,
  _ as SteamDeck_BuildReview_Status_Pass,
  _ as SteamDeck_BuildReview_Status_Raw_Comment,
  _ as SteamDeck_BuildReview_Status_Raw_Description,
  _ as SteamDeck_BuildReview_Status_Raw_Impact,
  _ as SteamDeck_BuildReview_Status_Raw_Result,
  _ as SteamDeck_BuildReview_Status_Raw_Test,
  _ as SteamDeck_BuildReview_Status_Raw_Title,
  _ as SteamDeck_BuildReview_Status_TestProperties_Description,
  _ as SteamDeck_BuildReview_Status_TestProperties_Playable,
  _ as SteamDeck_BuildReview_Status_TestProperty_Desc,
  _ as SteamDeck_BuildReview_Status_TestProperty_Name,
  _ as SteamDeck_BuildReview_Status_TestProperty_Value,
  _ as SteamDeck_BuildReview_Status_Title,
  _ as SteamDeck_BuildReview_UnknownError,
  _ as SteamDeck_BuildReview_Unsupported_Description,
  _ as SteamDeck_BuildReview_Unsupported_Title,
  _ as SteamDeck_BuildReview_ViewMoreDetailsInHelp,
  _ as SteamDeck_BuildReview_Viewing_Historical,
  _ as SteamDeck_BuildReview_Viewing_Published,
  _ as SteamDeck_HardwareCompatibility_Title,
  _ as SteamDeck_TestRequest_BuildNotReleased,
  _ as SteamFrame_BuildReview_Build_Android,
  _ as SteamFrame_BuildReview_Build_Linux,
  _ as SteamFrame_BuildReview_Build_Windows,
  _ as SteamFrame_BuildReview_CheckNote_Cloud_NoCrossSaves,
  _ as SteamFrame_BuildReview_CheckNote_Cloud_YesSavesNoCloud,
  _ as SteamFrame_BuildReview_CheckNote_DisplayFont,
  _ as SteamFrame_BuildReview_CheckNote_Launcher_V2_NoControllerSupport,
  _ as SteamFrame_BuildReview_CheckNote_Missing_Android_License,
  _ as SteamFrame_BuildReview_CheckNote_Missing_Android_License_Link,
  _ as SteamFrame_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs,
  _ as SteamFrame_BuildReview_Check_Icons,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Loading,
  _ as SteamFrame_BuildReview_Check_VRPerformance_NotApplicable,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Other,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Playable_With,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Playable_Without,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Startup,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Unsupported,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Verified_With,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Verified_Without,
  _ as SteamFrame_BuildReview_Checklist_Build,
  _ as SteamFrame_BuildReview_Checklist_Dimension,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P1,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P3,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P3_ReviewProcess,
  _ as SteamFrame_BuildReview_Checklist_Intro_Header_V2,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_Description,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_StatusReason,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_Title,
  _ as SteamFrame_BuildReview_Compatibility_Checklist,
  _ as SteamFrame_BuildReview_Dimension_2D,
  _ as SteamFrame_BuildReview_Dimension_VR,
  _ as SteamFrame_BuildReview_PleaseConfirm_Description_V2,
  _ as SteamFrame_BuildReview_PleaseConfirm_Title_V2,
  _ as SteamFrame_BuildReview_VRPerformanceLink,
  _ as SteamFrame_NotApplicableForDimension,
  _ as SteamHardware_BuildReview_Playable_Description,
  _ as SteamHardware_BuildReview_Playable_Title,
  _ as SteamHardware_BuildReview_Unknown_Title,
  _ as SteamHardware_BuildReview_Unsupported_Description,
  _ as SteamHardware_BuildReview_Unsupported_Title,
  _ as SteamHardware_BuildReview_Verified_Description,
  _ as SteamHardware_BuildReview_Verified_Share,
  _ as SteamHardware_BuildReview_Verified_Title,
  _ as SteamHardware_Frame_Unknown,
  _ as SteamHardware_Machine_Unknown,
  _ as SteamHardware_RatingImpact_Informational,
  _ as SteamHardware_RatingImpact_Playable,
  _ as SteamHardware_RatingImpact_Unsupported,
  _ as SteamLearn_Config_DataSource_Input_Preprocess_CompactTable,
  _ as SteamLearn_Config_DataSources,
  _ as SteamLearn_Config_DataSourcesDialog_Add,
  _ as SteamLearn_Config_DataSourcesDialog_Add_1,
  _ as SteamLearn_Config_DataSourcesDialog_Add_Multiple,
  _ as SteamLearn_Config_DataSources_Add,
  _ as SteamLearn_Config_DataSources_None,
  _ as SteamLearn_Config_DataSources_Remove,
  _ as SteamLearn_Config_DataSources_Update,
  _ as SteamLearn_Config_NoDescription,
  _ as SteamLearn_CreateNew,
  _ as SteamLearn_DSKeyType_AccountID,
  _ as SteamLearn_DSKeyType_AppID,
  _ as SteamLearn_DSKeyType_External,
  _ as SteamLearn_DSKeyType_MarketingMessageID,
  _ as SteamLearn_Edit,
  _ as SteamLearn_Event_Completed,
  _ as SteamLearn_Event_CompletedDetails,
  _ as SteamLearn_Event_Duration,
  _ as SteamLearn_Event_InProgress,
  _ as SteamLearn_FetchStatus_Canceled,
  _ as SteamLearn_FetchStatus_Cleanup,
  _ as SteamLearn_FetchStatus_Metadata,
  _ as SteamLearn_FetchStatus_Percent,
  _ as SteamLearn_FilterProject,
  _ as SteamLearn_GoToProjects,
  _ as SteamLearn_Header_Version_Unpublished,
  _ as SteamLearn_LiveTrain_Project,
  _ as SteamLearn_Name,
  _ as SteamLearn_Project,
  _ as SteamLearn_Project_CreateProject,
  _ as SteamLearn_Project_Create_BadName,
  _ as SteamLearn_Project_Create_Desc,
  _ as SteamLearn_Project_Create_Error,
  _ as SteamLearn_Project_Create_Header,
  _ as SteamLearn_Project_Create_Name,
  _ as SteamLearn_Project_Discard,
  _ as SteamLearn_Project_Edit_Accept,
  _ as SteamLearn_Project_Edit_Cancel,
  _ as SteamLearn_Project_Edit_Error,
  _ as SteamLearn_Project_Edit_Guidance,
  _ as SteamLearn_Project_Overview,
  _ as SteamLearn_Project_Publish_Accept,
  _ as SteamLearn_Project_Publish_Cancel,
  _ as SteamLearn_Project_Save,
  _ as SteamLearn_Project_Schedule,
  _ as SteamLearn_ScheduledTrain_Time,
  _ as SteamLearn_Status_Fetch_Status_Canceled,
  _ as SteamLearn_Status_Fetch_Status_Error,
  _ as SteamLearn_Status_Fetch_Status_Unknown,
  _ as SteamLearn_Status_Train_Fetch_TimeEstimate,
  _ as SteamLearn_TrainStatus_InProgress,
  _ as SteamLearn_TrainStatus_WaitingOnASS,
  _ as Valve_Confidential,
  _ as Valve_Confidential_Description,
  _ as default,
  _ as dummy,
};
