var _ = `Desconhecida`,
  _ = `Dólar dos Estados Unidos`,
  _ = `Libra esterlina (Reino Unido)`,
  _ = `Euro`,
  _ = `Franco suíço`,
  _ = `Rublo russo`,
  _ = `Zlóti polaco`,
  _ = `Real do Brasil`,
  _ = `Iene japonês`,
  _ = `Coroa norueguesa`,
  _ = `Rupia indonésia`,
  _ = `Ringuite malaio`,
  _ = `Peso filipino`,
  _ = `Dólar da Singapura`,
  _ = `Baht tailandês`,
  _ = `Dong vietnamita`,
  _ = `Won sul-coreano`,
  _ = `Lira turca`,
  _ = `Grívnia ucraniana`,
  _ = `Peso mexicano`,
  _ = `Dólar canadiano`,
  _ = `Dólar australiano`,
  _ = `Dólar da Nova Zelândia`,
  _ = `Iuane renminbi (China)`,
  _ = `Rupia indiana`,
  _ = `Peso chileno`,
  _ = `Sol peruano`,
  _ = `Peso colombiano`,
  _ = `Rande sul-africano`,
  _ = `Dólar de Hong Kong`,
  _ = `Dólar taiwanês`,
  _ = `Rial saudita`,
  _ = `Dirame dos Emirados Árabes Unidos`,
  _ = `Peso argentino`,
  _ = `Novo shekel israelita`,
  _ = `Tengue do Cazaquistão`,
  _ = `Dinar do Kuwait`,
  _ = `Rial do Catar`,
  _ = `Colón da Costa Rica`,
  _ = `Peso uruguaio`,
  _ = `Lev (Bulgária)`,
  _ = `Coroa sueca`,
  _ = `Kuna (Croácia)`,
  _ = `Coroa checa`,
  _ = `Coroa dinamarquesa`,
  _ = `Forinte (Hungria)`,
  _ = `Leu romeno`,
  _ = `Rublo bielorrusso`,
  _ = `Territórios da Comunidade dos Estados Independentes - Apresentado a clientes em: Arménia, Azerbaijão, Bielorrússia, Geórgia, Moldávia, Quirguistão, Tajiquistão, Turquemenistão e Uzbequistão`,
  _ = `Países do Sul da Ásia - Apresentado a clientes em: Bangladesh, Butão, Nepal, Paquistão e Sri Lanka`,
  _ = `Países da América Latina - Apresentado a clientes em: Argentina, Belize, Bolívia, El Salvador, Equador, Guatemala, Guiana, Honduras, Nicarágua, Panamá, Paraguai, Suriname e Venezuela`,
  _ = `Países do Médio Oriente e Norte de África - Apresentado a clientes em: Argélia, Barém, Egito, Iémen, Iraque, Jordânia, Líbano, Líbia, Marrocos, Omã, Estado da Palestina, Sudão, Tunísia e Turquia`,
  _ = `Desconhecida`,
  _ = `dummy`,
  _ = {
    CurrencyCodeDescription_Unknown: _,
    CurrencyCodeDescription_USD: _,
    CurrencyCodeDescription_GBP: _,
    CurrencyCodeDescription_EUR: _,
    CurrencyCodeDescription_CHF: _,
    CurrencyCodeDescription_RUB: _,
    CurrencyCodeDescription_PLN: _,
    CurrencyCodeDescription_BRL: _,
    CurrencyCodeDescription_JPY: _,
    CurrencyCodeDescription_NOK: _,
    CurrencyCodeDescription_IDR: _,
    CurrencyCodeDescription_MYR: _,
    CurrencyCodeDescription_PHP: _,
    CurrencyCodeDescription_SGD: _,
    CurrencyCodeDescription_THB: _,
    CurrencyCodeDescription_VND: _,
    CurrencyCodeDescription_KRW: _,
    CurrencyCodeDescription_TRY: _,
    CurrencyCodeDescription_UAH: _,
    CurrencyCodeDescription_MXN: _,
    CurrencyCodeDescription_CAD: _,
    CurrencyCodeDescription_AUD: _,
    CurrencyCodeDescription_NZD: _,
    CurrencyCodeDescription_CNY: _,
    CurrencyCodeDescription_INR: _,
    CurrencyCodeDescription_CLP: _,
    CurrencyCodeDescription_PEN: _,
    CurrencyCodeDescription_COP: _,
    CurrencyCodeDescription_ZAR: _,
    CurrencyCodeDescription_HKD: _,
    CurrencyCodeDescription_TWD: _,
    CurrencyCodeDescription_SAR: _,
    CurrencyCodeDescription_AED: _,
    CurrencyCodeDescription_ARS: _,
    CurrencyCodeDescription_ILS: _,
    CurrencyCodeDescription_KZT: _,
    CurrencyCodeDescription_KWD: _,
    CurrencyCodeDescription_QAR: _,
    CurrencyCodeDescription_CRC: _,
    CurrencyCodeDescription_UYU: _,
    CurrencyCodeDescription_BGN: _,
    CurrencyCodeDescription_SEK: _,
    CurrencyCodeDescription_HRK: _,
    CurrencyCodeDescription_CZK: _,
    CurrencyCodeDescription_DKK: _,
    CurrencyCodeDescription_HUF: _,
    CurrencyCodeDescription_RON: _,
    CurrencyCodeDescription_BYN: _,
    Region_Pricing_Tooltip_CIS: _,
    Region_Pricing_Tooltip_SASIA: _,
    Region_Pricing_Tooltip_LATAM: _,
    Region_Pricing_Tooltip_MENA: _,
    Region_Pricing_Tooltip_Unknown: _,
    dummy: _,
  };
export {
  _ as CurrencyCodeDescription_AED,
  _ as CurrencyCodeDescription_ARS,
  _ as CurrencyCodeDescription_AUD,
  _ as CurrencyCodeDescription_BGN,
  _ as CurrencyCodeDescription_BRL,
  _ as CurrencyCodeDescription_BYN,
  _ as CurrencyCodeDescription_CAD,
  _ as CurrencyCodeDescription_CHF,
  _ as CurrencyCodeDescription_CLP,
  _ as CurrencyCodeDescription_CNY,
  _ as CurrencyCodeDescription_COP,
  _ as CurrencyCodeDescription_CRC,
  _ as CurrencyCodeDescription_CZK,
  _ as CurrencyCodeDescription_DKK,
  _ as CurrencyCodeDescription_EUR,
  _ as CurrencyCodeDescription_GBP,
  _ as CurrencyCodeDescription_HKD,
  _ as CurrencyCodeDescription_HRK,
  _ as CurrencyCodeDescription_HUF,
  _ as CurrencyCodeDescription_IDR,
  _ as CurrencyCodeDescription_ILS,
  _ as CurrencyCodeDescription_INR,
  _ as CurrencyCodeDescription_JPY,
  _ as CurrencyCodeDescription_KRW,
  _ as CurrencyCodeDescription_KWD,
  _ as CurrencyCodeDescription_KZT,
  _ as CurrencyCodeDescription_MXN,
  _ as CurrencyCodeDescription_MYR,
  _ as CurrencyCodeDescription_NOK,
  _ as CurrencyCodeDescription_NZD,
  _ as CurrencyCodeDescription_PEN,
  _ as CurrencyCodeDescription_PHP,
  _ as CurrencyCodeDescription_PLN,
  _ as CurrencyCodeDescription_QAR,
  _ as CurrencyCodeDescription_RON,
  _ as CurrencyCodeDescription_RUB,
  _ as CurrencyCodeDescription_SAR,
  _ as CurrencyCodeDescription_SEK,
  _ as CurrencyCodeDescription_SGD,
  _ as CurrencyCodeDescription_THB,
  _ as CurrencyCodeDescription_TRY,
  _ as CurrencyCodeDescription_TWD,
  _ as CurrencyCodeDescription_UAH,
  _ as CurrencyCodeDescription_USD,
  _ as CurrencyCodeDescription_UYU,
  _ as CurrencyCodeDescription_Unknown,
  _ as CurrencyCodeDescription_VND,
  _ as CurrencyCodeDescription_ZAR,
  _ as Region_Pricing_Tooltip_CIS,
  _ as Region_Pricing_Tooltip_LATAM,
  _ as Region_Pricing_Tooltip_MENA,
  _ as Region_Pricing_Tooltip_SASIA,
  _ as Region_Pricing_Tooltip_Unknown,
  _ as default,
  _ as dummy,
};
