var _ = `Conteúdo confidencial da Valve`,
  _ = `Esta página de acesso restrito contém informações confidenciais da Valve. Você precisa ter um contrato de confidencialidade e/ou licenciamento que cubra informações confidenciais da Valve para usar ou acessar esta página.`,
  _ = `O Steamworks é o conjunto de ferramentas e serviços criados pela <1>Valve</1> que ajudam você a configurar, gerenciar e operar o seu jogo no <2>Steam</2>.`,
  _ = `Entrar em contato com o suporte`,
  _ = `Erro ao carregar os dados de preços. Tente novamente mais tarde.`,
  _ = `Sobre preços regionais`,
  _ = `O preço de cada produto no Steam é especificado e exibido usando %1$s moedas diferentes e %2$s <1>grupos de regiões</1>. O Steam oferece ferramentas para ajudar você a definir e gerenciar o preço do seu jogo em níveis adequados para cada mercado.`,
  _ = `Você é quem decide os preços informados para o seu jogo em cada moeda e grupo de regiões.`,
  _ = `Para mais detalhes sobre como gerenciar os seus preços, consulte a %1$s.`,
  _ = `documentação sobre preços`,
  _ = `Para gerenciar os preços do seu jogo, acesse o %1$s.`,
  _ = `Acessar o painel de preços`,
  _ = `Para gerenciar os preços do seu jogo, acesse o painel de preços.`,
  _ = `Conversões de moeda atualizadas pela última vez em %1$s`,
  _ = `Ferramenta de exploração de conversão de preços`,
  _ = `Esta ferramenta demonstra como os três métodos de conversão de preços e moedas funcionam:`,
  _ = `%1$s: este método leva em consideração vários fatores para cada moeda, incluindo o poder de compra local, o custo esperado de bens de entretenimento comparáveis e a taxa de câmbio.`,
  _ = `%1$s: este método usa os dados públicos relativos ao poder de compra dos cidadãos de cada país e/ou região.`,
  _ = `%1$s: este método usa uma conversão cambial simples no momento indicado.`,
  _ = `Moeda base`,
  _ = `Preço base`,
  _ = `Método de conversão`,
  _ = `Moeda`,
  _ = `Conversão multivariável`,
  _ = `Conversão considerando apenas poder de compra`,
  _ = `Conversão cambial simples`,
  _ = `Preços de regiões específicas (todos em USD)`,
  _ = `Região`,
  _ = `dummy`,
  _ = `%1$s (%2$s) — Questionário de conteúdo`,
  _ = `Questionário de conteúdo`,
  _ = `%1$s (%2$s) — Questionários de conteúdo`,
  _ = `Questionários de conteúdo`,
  _ = `Não existe nenhum aplicativo associado a este ID. Verifique o endereço e tente novamente.`,
  _ = `Permissão negada`,
  _ = `Sessão não iniciada`,
  _ = `Cancelado`,
  _ = `Erro`,
  _ = `Publicar`,
  _ = `Cancelar`,
  _ = `Editar`,
  _ = `Salvar alterações`,
  _ = `Descartar alterações`,
  _ = `Visão geral`,
  _ = `Teste de inferência`,
  _ = `Resumo`,
  _ = `A lista completa de testes realizados durante a análise, bem como os seus resultados, está disponível abaixo.`,
  _ = `A seguir, um resumo dos testes individuais e as respectivas classificações de compatibilidade.`,
  _ = `Os resultados do teste que determinam este título como Jogável estão indicados abaixo.`,
  _ = `Propriedade`,
  _ = `Valor`,
  _ = `Descrição`,
  _ = `Aqui está uma prévia de como isso aparecerá na loja para os usuários que visualizarem o seu jogo. A apresentação na loja pode mudar no futuro.`,
  _ = `Relatórios passados`,
  _ = `Resultado do teste`,
  _ = `Resultado`,
  _ = `Teste`,
  _ = `Comentários`,
  _ = `Impacto na classificação`,
  _ = `Aprovado`,
  _ = `Falhou`,
  _ = `Falhou`,
  _ = `---`,
  _ = `Este e um relatório passado (%1$s)`,
  _ = `Visualizando o relatório atualmente publicado`,
  _ = `Publicado em: %1$s`,
  _ = `Relatório gerado em: %1$s`,
  _ = `Consultar documentação`,
  _ = `Publicar este resultado`,
  _ = `Publicar o resultado da análise de compatibilidade?`,
  _ = `Tem certeza de que deseja publicar o resultado? Ele poderá ser visto na Loja Steam imediatamente.`,
  _ = `Erro desconhecido. Tente novamente.`,
  _ = `Solicitação de teste`,
  _ = `Solicitação ativa`,
  _ = `Solicitação encerrada`,
  _ = `Ver detalhes da solicitação`,
  _ = `Discutir relatório com a equipe de testes`,
  _ = `Informe as perguntas ou os comentários aqui`,
  _ = `Descreva as alterações da nova versão aqui`,
  _ = `Caso a versão do seu jogo no Steam tenha sido atualizada para corrigir os problemas descritos acima, selecione um ramo e reenvie-o para análise.`,
  _ = `Selecione um ramo e envie para uma nova análise de compatibilidade com o Steam Deck, que incluirá testes com a Steam Machine.`,
  _ = `Solicitar reanálise`,
  _ = `Caso tenha realizado alterações na versão do jogo desde a última análise, é possível solicitar uma nova análise de compatibilidade.`,
  _ = `Descreva abaixo o motivo da solicitação de reanálise. Exemplos:`,
  _ = `Você realizou alterações na versão do jogo para resolver testes que não passaram em uma análise de compatibilidade passada. Neste caso, descreva os problemas que você acredita ter resolvido.`,
  _ = `Você lançou (ou lançará) uma nova versão do seu jogo e deseja a atualização do relatório.`,
  _ = `Desejo solicitar um novo teste com o ramo "%1$s". A versão do jogo no Steam foi atualizada para corrigir os problemas relatados.`,
  _ = `Histórico de testes`,
  _ = `Exibição na loja`,
  _ = `Compatibilidade com o hardware: %1$s (%2$s)`,
  _ = `Publicado`,
  _ = `Não publicado`,
  _ = `Histórico`,
  _ = `Ambiente de execução recomendado`,
  _ = `Esta é a versão do seu jogo (conteúdo/executáveis) que será entregue e executada pelos usuários por padrão no Steam Deck.`,
  _ = `Formato de entrada esperado`,
  _ = `Exige H.264`,
  _ = `Versão do Proton testada`,
  _ = `ID da versão de teste`,
  _ = `Depuração de RPO`,
  _ = `Depuração de FDM`,
  _ = `Ativação de TSO`,
  _ = `A compatibilidade do jogo é desconhecida no(a) %1$s porque os testes no dispositivo ainda não foram concluídos`,
  _ = `Atualmente, o jogo é incompatível com o(a) %1$s`,
  _ = `O jogo não é totalmente compatível com o(a) %1$s devido a problemas com o Proton ou com o dispositivo em si. Registramos esses problemas e estamos trabalhando para solucioná-los. Até lá, o seu jogo não poderá ser iniciado ou jogado corretamente no(a) %1$s.`,
  _ = `O seu jogo é "Jogável" no(a) %1$s`,
  _ = `O seu jogo é jogável no(a) %1$s, mas exige algum esforço extra da parte dos usuários para interação ou configuração. Você pode corrigir os problemas descritos abaixo e reenviá-lo para a análise de compatibilidade.`,
  _ = `O seu jogo foi "Aprovado no(a) %1$s"!`,
  _ = `Parabéns! O seu jogo oferece uma ótima experiência no(a) %1$s e será apresentado como tal na Loja Steam e nas Bibliotecas Steam de usuários no(a) %1$s.`,
  _ = `Gostaria de compartilhar este marco com os seus fãs? Aqui está um link para uma bela página promocional: %1$s `,
  _ = `O jogo não foi testado na Steam Machine.`,
  _ = `O jogo não foi testado no Steam Frame.`,
  _ = `Isto fez com que o seu título fosse classificado como "Jogável"`,
  _ = `Isto fez com que o seu título fosse classificado como "Incompatível"`,
  _ = `Isto é exibido como um aviso aos usuários.`,
  _ = `Inválido`,
  _ = `Execução do inicializador`,
  _ = `Inicializador`,
  _ = `Uso de controle no inicializador`,
  _ = `Texto do inicializador`,
  _ = `Uso de teclado no inicializador`,
  _ = `Alertas do dispositivo`,
  _ = `Execução do jogo`,
  _ = `Modo para um jogador`,
  _ = `Modo multijogador local`,
  _ = `Modo multijogador on-line`,
  _ = `Antitrapaça`,
  _ = `Antitrapaça`,
  _ = `Antitrapaça e multijogador`,
  _ = `Configuração de controle padrão`,
  _ = `Teclado`,
  _ = `Ícones do controle`,
  _ = `Desempenho da configuração padrão`,
  _ = `Exibição`,
  _ = `Saída de vídeo`,
  _ = `Resolução nativa`,
  _ = `Legibilidade de texto`,
  _ = `Som`,
  _ = `Menu`,
  _ = `Salvamento em nuvem multiplataforma`,
  _ = `Modo para um jogador off-line`,
  _ = `Uso de controle externo (jogador principal)`,
  _ = `Uso de controle externo (multijogador local)`,
  _ = `Configuração inicial`,
  _ = `Uso de controle na configuração inicial`,
  _ = `Configuração inicial off-line`,
  _ = `Funcionalidade do jogo`,
  _ = `RV`,
  _ = `Observação`,
  _ = `Encerramento limpo`,
  _ = `Encerramento limpo (inicializador)`,
  _ = `Entrada simultânea de controle e mouse`,
  _ = `Funcionalidade auxiliar: editor de mapas`,
  _ = `Compatível com o limitador de quadros`,
  _ = `Foco em múltiplas janelas (auto.)`,
  _ = `Foco em múltiplas janelas (manual)`,
  _ = `Software`,
  _ = `Entrada simultânea de controle e mouse`,
  _ = `Entrada de texto`,
  _ = `Entrada de áudio`,
  _ = `Retomada ao despertar o dispositivo`,
  _ = `Saída redimensionada`,
  _ = `Conteúdos e links externos`,
  _ = `Removido`,
  _ = `Fonte compatível com todos os caracteres`,
  _ = `Configurações de exibição armazenadas no dispositivo e não sincronizadas com a Nuvem`,
  _ = `Configuração de controle padrão`,
  _ = `Controle padrão ativado`,
  _ = `Salvamentos na nuvem ativados por padrão`,
  _ = `Periféricos (teclado)`,
  _ = `Periféricos (webcam)`,
  _ = `Periféricos (guitarra USB)`,
  _ = `Compatível com HDR`,
  _ = `Compatibilidade com SO`,
  _ = `Steam Machine: desempenho da configuração padrão`,
  _ = `Steam Machine: desempenho da transmissão de realidade virtual`,
  _ = `Steam Machine: compatibilidade com transmissão de realidade virtual`,
  _ = `Steam Machine: alertas do dispositivo`,
  _ = `Steam Machine: exibição`,
  _ = `Steam Machine: som`,
  _ = `Steam Machine`,
  _ = `SteamOS`,
  _ = `Steam Deck`,
  _ = `Steam Frame independente`,
  _ = `Solicite um teste no Steam Deck para dar início aos testes necessários à atribuição de uma classificação de compatibilidade com o dispositivo "%1$s".`,
  _ = `Boas-vindas! Aqui você pode enviar o seu título para a análise de compatibilidade do Steam Frame independente.`,
  _ = `Autoanálise da lista de compatibilidade com o Steam Frame`,
  _ = `Abaixo, enumeramos alguns dos critérios mais importantes que verificamos ao analisar a compatibilidade de um título com o Steam Frame. Preencha o formulário abaixo e informe qual versão ou ramo de seu jogo você gostaria que fosse testado e colocaremos o jogo na nossa fila para análise. Quando a análise for concluída, você receberá um e-mail de notificação com um resumo, e esta página será atualizada com o resultado detalhado do teste.`,
  _ = `Para mais informações sobre o processo de teste, consulte o artigo %1$s.`,
  _ = `Processo de análise de compatibilidade com o Steam Frame independente`,
  _ = `Esses são alguns dos itens mais importantes que serão analisados para atribuir uma classificação de compatibilidade ao seu jogo. Para iniciar o processo de análise de compatibilidade com o Steam Frame, responda às perguntas abaixo da melhor forma possível.`,
  _ = `Não é possível solicitar testes antes do lançamento do jogo`,
  _ = `O seu jogo oferecerá uma ótima experiência no Steam Deck? Temos um processo de análise no qual ele será jogado e testado pela nossa equipe. Se ele oferecer uma experiência de qualidade no Steam Deck, ele receberá a insígnia "Aprovado no Steam Deck".`,
  _ = `Boas-vindas! Aqui você pode enviar o seu título para a análise de compatibilidade do Steam Deck.`,
  _ = `Abaixo, enumeramos alguns dos critérios mais importantes que verificamos ao analisar a compatibilidade de um título com o Steam Deck. Preencha o formulário abaixo e informe qual versão ou ramo de seu jogo você gostaria que fosse testado e colocaremos o jogo em nossa fila para análise. Quando a análise for concluída, você receberá um e-mail de notificação com um resumo, e esta página será atualizada com o resultado detalhado do teste.`,
  _ = `Você pode enviar o seu título mesmo que ele não atenda a todos os critérios para ser categorizado como Aprovado. Usamos essas informações de autoteste para priorizar quais títulos analisar, assim como para comunicar qualquer problema de compatibilidade com o seu jogo da maneira mais clara possível.`,
  _ = `Para mais informações sobre o processo de teste, consulte o artigo %1$s e as recomendações em %2$s na documentação do Steamworks.`,
  _ = `Análise de compatibilidade com o Steam Deck e a Steam Machine`,
  _ = `Preparando o seu jogo para o Steam Deck e a Steam Machine`,
  _ = `Autoanálise da lista de compatibilidade com o Steam Deck`,
  _ = `Esses são alguns dos itens mais importantes que serão analisados para atribuir uma classificação de compatibilidade ao seu jogo. Para iniciar o processo de análise de compatibilidade com o Steam Deck, responda às perguntas abaixo da melhor forma possível.`,
  _ = `No momento, o processo de análise de compatibilidade com o Steam Deck é exclusivo para jogos. Não há análises para aplicativos de outros tipos (como conteúdos adicionais, ferramentas e trilhas sonoras), exceto em casos excepcionais.`,
  _ = `Compatibilidade com controles`,
  _ = `Entrada de texto`,
  _ = `Exibição`,
  _ = `Funcionalidade`,
  _ = `Nuvem Steam`,
  _ = `Inicializador`,
  _ = `Ramo`,
  _ = `Favor testar com este ramo`,
  _ = `Marcar como pronta para análise...`,
  _ = `Esta opção marcará a versão como pronta para a análise de compatibilidade com o Steam Deck. Você receberá uma notificação por e-mail em alguns dias com o resultado.`,
  _ = `Use o campo abaixo para deixar observações para agilizar o teste ou fornecer credenciais para uma conta de testes em servidores de terceiros.`,
  _ = `Informe as observações aqui`,
  _ = `Chamado associado a esta análise`,
  _ = `Para mais detalhes, consulte o relatório de testes no site de ajuda`,
  _ = `Abrir um chamado solicitando a análise de compatibilidade com o Steam Deck`,
  _ = `Inclua perguntas ou comentários para a equipe de testes no chamado.`,
  _ = `Caso tenha dúvidas específicas sobre o processo de análise de compatibilidade ou o resultado da análise para o seu jogo, preencha o campo abaixo.`,
  _ = `Caso deseje que o seu título passe por uma nova análise, o ideal é usar o botão "SOLICITAR REANÁLISE" abaixo em vez de usar este formulário.`,
  _ = `Tenho uma dúvida ou comentário a respeito do resultado do teste de compatibilidade com o Steam Deck: `,
  _ = `Sim, o meu jogo é totalmente compatível com controle: todas as funcionalidades são acessíveis com um controle usando a configuração padrão.`,
  _ = `Sim, o meu jogo exibe os ícones/rótulos dos botões de um controle do Steam Deck ou Xbox ao referir-se a botões de um controle.`,
  _ = `O meu jogo não exige entrada de texto ou chama a API de entrada de texto apropriada do Steam quando necessário.`,
  _ = `O meu jogo não exige entrada de texto.`,
  _ = `O meu jogo chama a API de teclado/entrada de texto apropriada do Steam quando a entrada de texto é necessária.`,
  _ = `O meu jogo não usa as APIs do Steam quando a entrada de texto é necessária.`,
  _ = `O meu jogo não salva dados.`,
  _ = `O meu jogo tem arquivos de salvamento, mas não os armazena na Nuvem Steam.`,
  _ = `O meu jogo armazena salvamentos na Nuvem Steam e apenas possui uma versão para Windows.`,
  _ = `O meu jogo armazena salvamentos na Nuvem Steam, e eles são multiplataforma (ou seja, funcionam com as versões do jogo para Windows e Linux).`,
  _ = `O meu jogo armazena salvamentos na Nuvem Steam, mas eles não são multiplataforma (ou seja, funcionam apenas com a versão do jogo para Windows ou Linux).`,
  _ = `Sim, o meu jogo roda na resolução de 1280x800 (preferencialmente) ou 1280x720.`,
  _ = `Sim, o menor caractere de fonte exibido pelo meu jogo na tela não tem menos de 9 pixels de altura ao usar a resolução de 1280x800.`,
  _ = `O meu jogo não usa um inicializador ou é possível controlar todas as suas opções com um controle.`,
  _ = `O meu jogo armazena salvamentos na Nuvem Steam OU o meu jogo não salva dados.`,
  _ = `O meu jogo armazena salvamentos na Nuvem Steam, e eles são multiplataforma OU o meu jogo está disponível em apenas uma plataforma (Linux ou Windows).`,
  _ = `A menos que seja indicado o contrário, será testada a sua versão para Windows com Proton.`,
  _ = `Caso disponível, testar a versão para Linux em vez de usar a versão para Windows.`,
  _ = `O meu jogo não usa um inicializador ou ferramenta externa de configuração.`,
  _ = `O meu jogo usa um inicializador, que pode ser controlado com um controle.`,
  _ = `O meu jogo usa um inicializador, que não funciona por completo apenas com um controle e requer um teclado e/ou mouse.`,
  _ = `(Apesar de salvamentos multiplataforma não serem obrigatórios para um jogo ser considerado Aprovado, eles são úteis para usuários que ora jogam em um computador com Windows, ora em um Steam Deck usando a versão nativa do jogo para Linux. Consulte a %1$s para detalhes.)`,
  _ = `documentação`,
  _ = `(A tela do Steam Deck é bem menor que a maioria das telas de computador. Caso o seu jogo tenha textos pequenos, a leitura deles na tela do Deck pode ser difícil — ou mesmo impossível —, mesmo se não houver problemas em um monitor tradicional.)`,
  _ = `(Poucos usuários usam um Steam Deck com um teclado conectado, portanto, a maioria depende de teclados virtuais para a entrada de texto. O Steam oferece APIs para facilitar o uso dos teclados virtuais do Steam Deck. Caso o usuário precise abrir o teclado manualmente, o jogo não será Aprovado. Consulte as %1$s para detalhes.)`,
  _ = `recomendações de entrada`,
  _ = `(Caso o seu jogo use um inicializador, ele também precisará passar nos testes para que o jogo seja Aprovado — ou seja, deve ser possível interagir com ambos usando os controles do Steam Deck, os textos devem ser legíveis etc. Caso o inicializador não atenda a esses requisitos, o jogo não será Aprovado, mesmo que o jogo em si os atenda. Consulte as %1$s para detalhes.)`,
  _ = `recomendações de inicializador`,
  _ = `(Uma boa parte dos usuários do Steam Deck também usam computadores tradicionais. Um jogo não precisa salvar dados na nuvem para ser Aprovado, mas usuários adorarão se o fizer: o armazenamento de salvamentos na %1$s permitirá que eles salvem o jogo no computador e continuem no Deck ou vice-versa.)`,
  _ = `Nuvem Steam`,
  _ = `(Observação: é necessário compatibilidade completa com controles para o jogo ser Aprovado.)`,
  _ = `O seu jogo foi adicionado à nossa fila para análise`,
  _ = `O jogo será analisado em breve, e avisaremos você caso haja algum problema.`,
  _ = `O jogo precisa passar pela análise de versão do Steam antes de enviá-lo para a análise de compatibilidade de hardware.`,
  _ = `Atualmente, o jogo é incompatível com o Steam Deck`,
  _ = `O jogo não é totalmente compatível com o Steam Deck devido a problemas com o Proton ou com o dispositivo em si. Registramos tais problemas e estamos trabalhando para solucioná-los. Até lá, o seu jogo não poderá ser iniciado ou jogado corretamente no Steam Deck.`,
  _ = `O seu jogo é "Jogável" no Steam Deck.`,
  _ = `O seu jogo é jogável no Steam Deck, mas exige algum esforço extra da parte dos usuários para interação ou configuração. Você pode corrigir os problemas descritos abaixo e reenviá-lo para a análise de compatibilidade com o Steam Deck.`,
  _ = `Versão`,
  _ = `Caso disponível, testar a versão para Android em vez de usar a versão para Windows.`,
  _ = `Testar a versão para Windows`,
  _ = `Testar a versão para Linux`,
  _ = `Devemos testar a experiência 2D ou de RV (se disponível)?`,
  _ = `2D`,
  _ = `RV`,
  _ = `Não aplicável para títulos %1$s`,
  _ = `Aprovado, sem uso de "Limpar estado da avaliação de desempenho"`,
  _ = `Aprovado, com pelo menos um uso de "Limpar estado da avaliação de desempenho"`,
  _ = `Jogável, sem uso de "Limpar estado da avaliação de desempenho"`,
  _ = `Jogável, com pelo menos um uso de "Limpar estado da avaliação de desempenho"`,
  _ = `Incompatível`,
  _ = `Não é um título de RV (a avaliação não se aplica)`,
  _ = `Sobreposição de avaliação de desempenho`,
  _ = `Use a sobreposição de avaliação de desempenho para preencher o questionário abaixo. Consulte a %1$s para mais informações.`,
  _ = `documentação sobre desempenho da RV`,
  _ = `(Caso o seu jogo tenha textos pequenos, a leitura deles na tela do Frame pode ser difícil — ou mesmo impossível —, mesmo se não houver problemas em um monitor tradicional.)`,
  _ = `(Poucos usuários usam um Steam Frame com um teclado conectado, portanto, a maioria depende de teclados virtuais para a entrada de texto. O Steam oferece APIs para facilitar o uso dos teclados virtuais. Caso o usuário precise abrir o teclado manualmente, o jogo não será Aprovado. Consulte as %1$s para detalhes.)`,
  _ = `Lista de compatibilidade com o Steam Frame`,
  _ = `(Caso o seu jogo use um inicializador, ele também precisará passar nos testes para que o jogo seja Aprovado — ou seja, deve ser possível interagir com ambos usando os controles do Steam Frame, os textos devem ser legíveis etc. Caso o inicializador não atenda a esses requisitos, o jogo não será Aprovado, mesmo que o jogo em si os atenda. Consulte as %1$s para detalhes.)`,
  _ = `(Uma boa parte dos usuários do Steam Frame também usam computadores tradicionais. Um jogo não precisa salvar dados na nuvem para ser Aprovado, mas usuários adorarão se o fizer: o armazenamento de salvamentos na %1$s permitirá que eles salvem o jogo no computador e continuem no Frame ou vice-versa.)`,
  _ = `(Apesar de salvamentos multiplataforma não serem obrigatórios para um jogo ser considerado Aprovado, eles são úteis para usuários que ora jogam em um computador com Windows, ora em um Steam Frame usando a versão nativa do jogo para Linux. Consulte a %1$s para detalhes.)`,
  _ = `Sim, o meu jogo exibe os ícones/rótulos dos botões de um controle do Steam Frame/Deck ou Xbox ao referir-se a botões de um controle.`,
  _ = `Caso o resultado da avaliação de desempenho acima tenha exigido pelo menos um uso de "Limpar estado da avaliação de desempenho", selecione um ou mais motivos abaixo.`,
  _ = `Desempenho comprometido na inicialização do jogo`,
  _ = `Desempenho comprometido em telas de carregamento`,
  _ = `Outro (especifique)`,
  _ = `Você está solicitando uma análise para a versão de Android, mas %1$s não possui nenhum depot do tipo "Android".`,
  _ = `o seu pacote complementar de desenvolvimento`,
  _ = `dummy`,
  _ = {
    Valve_Confidential: _,
    Valve_Confidential_Description: _,
    Footer_Description: _,
    Footer_Sitemap_ContactSupport: _,
    PricingExplorer_LoadError: _,
    PricingExplorer_About_Title: _,
    PricingExplorer_About_Desc1: _,
    PricingExplorer_About_Desc2: _,
    PricingExplorer_About_Link1: _,
    PricingExplorer_About_LinkName1: _,
    PricingExplorer_About_Link2: _,
    PricingExplorer_About_LinkName2: _,
    PricingExplorer_About_Dash: _,
    PricingExplorer_About_LastUpdated: _,
    PricingExplorer_Explore_title: _,
    PricingExplorer_Explore_desc1: _,
    PricingExplorer_Explore_line1: _,
    PricingExplorer_Explore_line2: _,
    PricingExplorer_Explore_line3: _,
    PricingExplorer_Base: _,
    PricingExplorer_BasePrice: _,
    PricingExplorer_TableHeader: _,
    PricingExplorer_Column1: _,
    PricingExplorer_Column2: _,
    PricingExplorer_Column3: _,
    PricingExplorer_Column4: _,
    PricingExplorer_Regions_TableHeader: _,
    PricingExplorer_Regions_Column1: _,
    Pricing_Dummy: _,
    ContentSurvey_Title: _,
    ContentSurvey_Title_Default: _,
    ContentSurvey_History_Title: _,
    ContentSurvey_History_Title_Default: _,
    ContentSurvey_InvalidApp: _,
    PartnerSite_PermissionDenied: _,
    PartnerSite_NotLoggedIn: _,
    SteamLearn_Status_Fetch_Status_Canceled: _,
    SteamLearn_Status_Fetch_Status_Error: _,
    SteamLearn_Project_Publish_Accept: _,
    SteamLearn_Project_Publish_Cancel: _,
    SteamLearn_Edit: _,
    SteamLearn_Project_Save: _,
    SteamLearn_Project_Discard: _,
    SteamLearn_Project_Overview: _,
    SteamLearn_Project_InferenceTester: _,
    SteamDeck_BuildReview_Status_Raw_Title: _,
    SteamDeck_BuildReview_Status_Raw_Description: _,
    SteamDeck_BuildReview_Status_TestProperties_Description: _,
    SteamDeck_BuildReview_Status_TestProperties_Playable: _,
    SteamDeck_BuildReview_Status_TestProperty_Name: _,
    SteamDeck_BuildReview_Status_TestProperty_Value: _,
    SteamDeck_BuildReview_Status_TestProperty_Desc: _,
    SteamDeck_BuildReview_Status_Description: _,
    SteamDeck_BuildReview_Header_History: _,
    SteamDeck_BuildReview_Header_Results: _,
    SteamDeck_BuildReview_Status_Raw_Result: _,
    SteamDeck_BuildReview_Status_Raw_Test: _,
    SteamDeck_BuildReview_Status_Raw_Comment: _,
    SteamDeck_BuildReview_Status_Raw_Impact: _,
    SteamDeck_BuildReview_Status_Pass: _,
    SteamDeck_BuildReview_Status_Fail: _,
    SteamDeck_BuildReview_Status_FailMinor: _,
    SteamDeck_BuildReview_Status_NotApplicable: `---`,
    SteamDeck_BuildReview_Viewing_Historical: _,
    SteamDeck_BuildReview_Viewing_Published: _,
    SteamDeck_BuildReview_PublishedOn: _,
    SteamDeck_BuildReview_ReportedOn: _,
    SteamDeck_BuildReview_Documentation: _,
    SteamDeck_BuildReview_PublishResults: _,
    SteamDeck_BuildReview_PublishDialog_Title: _,
    SteamDeck_BuildReview_PublishDialog_Body: _,
    SteamDeck_BuildReview_UnknownError: _,
    SteamDeck_BuildReview_Help_Request_Title: _,
    SteamDeck_BuildReview_RequestStatusActive: _,
    SteamDeck_BuildReview_RequestStatusClosed: _,
    SteamDeck_BuildReview_InReview_ViewTicket: _,
    SteamDeck_BuildReview_Create_HelpRequest: _,
    SteamDeck_BuildReview_Create_HelpRequest_NotesDefault: _,
    SteamDeck_BuildReview_Create_HelpRequest_NotesDefault_Rereview: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label_Machine: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Button: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_1: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2a: _,
    SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2b: _,
    SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Ticket_Content: _,
    SteamDeck_BuildReview_CompatibilityTests: _,
    SteamDeck_BuildReview_Status_Title: _,
    SteamDeck_HardwareCompatibility_Title: _,
    SteamDeck_AppLanding_Published: _,
    SteamDeck_AppLanding_Unpublished: _,
    SteamDeck_AppLanding_History: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RecommendedRuntime: _,
    SteamDeckVerified_TestDisplayName_TestPropertyDescription_RecommendedRuntime:
      _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_ExpectedInput: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RequiresH264: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TestedProtonVersion: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TestedBuildID: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_RPODebug: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_FDMDebug: _,
    SteamDeckVerified_TestDisplayName_TestPropertyName_TSOEnable: _,
    SteamHardware_BuildReview_Unknown_Title: _,
    SteamHardware_BuildReview_Unsupported_Title: _,
    SteamHardware_BuildReview_Unsupported_Description: _,
    SteamHardware_BuildReview_Playable_Title: _,
    SteamHardware_BuildReview_Playable_Description: _,
    SteamHardware_BuildReview_Verified_Title: _,
    SteamHardware_BuildReview_Verified_Description: _,
    SteamHardware_BuildReview_Verified_Share: _,
    SteamHardware_Machine_Unknown: _,
    SteamHardware_Frame_Unknown: _,
    SteamHardware_RatingImpact_Playable: _,
    SteamHardware_RatingImpact_Unsupported: _,
    SteamHardware_RatingImpact_Informational: _,
    SteamDeckVerified_TestDisplayName_0: _,
    SteamDeckVerified_TestDisplayName_1: _,
    SteamDeckVerified_TestDisplayName_2: _,
    SteamDeckVerified_TestDisplayName_3: _,
    SteamDeckVerified_TestDisplayName_4: _,
    SteamDeckVerified_TestDisplayName_5: _,
    SteamDeckVerified_TestDisplayName_6: _,
    SteamDeckVerified_TestDisplayName_7: _,
    SteamDeckVerified_TestDisplayName_8: _,
    SteamDeckVerified_TestDisplayName_9: _,
    SteamDeckVerified_TestDisplayName_10: _,
    SteamDeckVerified_TestDisplayName_11: _,
    SteamDeckVerified_TestDisplayName_12: _,
    SteamDeckVerified_TestDisplayName_13: _,
    SteamDeckVerified_TestDisplayName_14: _,
    SteamDeckVerified_TestDisplayName_15: _,
    SteamDeckVerified_TestDisplayName_16: _,
    SteamDeckVerified_TestDisplayName_17: _,
    SteamDeckVerified_TestDisplayName_18: _,
    SteamDeckVerified_TestDisplayName_19: _,
    SteamDeckVerified_TestDisplayName_20: _,
    SteamDeckVerified_TestDisplayName_21: _,
    SteamDeckVerified_TestDisplayName_22: `Som`,
    SteamDeckVerified_TestDisplayName_23: _,
    SteamDeckVerified_TestDisplayName_24: _,
    SteamDeckVerified_TestDisplayName_25: _,
    SteamDeckVerified_TestDisplayName_26: _,
    SteamDeckVerified_TestDisplayName_27: _,
    SteamDeckVerified_TestDisplayName_29: _,
    SteamDeckVerified_TestDisplayName_30: _,
    SteamDeckVerified_TestDisplayName_31: _,
    SteamDeckVerified_TestDisplayName_32: _,
    SteamDeckVerified_TestDisplayName_33: `RV`,
    SteamDeckVerified_TestDisplayName_34: _,
    SteamDeckVerified_TestDisplayName_35: _,
    SteamDeckVerified_TestDisplayName_36: _,
    SteamDeckVerified_TestDisplayName_37: _,
    SteamDeckVerified_TestDisplayName_38: _,
    SteamDeckVerified_TestDisplayName_39: _,
    SteamDeckVerified_TestDisplayName_40: _,
    SteamDeckVerified_TestDisplayName_41: _,
    SteamDeckVerified_TestDisplayName_42: _,
    SteamDeckVerified_TestDisplayName_43: _,
    SteamDeckVerified_TestDisplayName_44: _,
    SteamDeckVerified_TestDisplayName_45: _,
    SteamDeckVerified_TestDisplayName_46: _,
    SteamDeckVerified_TestDisplayName_47: _,
    SteamDeckVerified_TestDisplayName_48: _,
    SteamDeckVerified_TestDisplayName_49: _,
    SteamDeckVerified_TestDisplayName_50: _,
    SteamDeckVerified_TestDisplayName_51: _,
    SteamDeckVerified_TestDisplayName_52: _,
    SteamDeckVerified_TestDisplayName_53: _,
    SteamDeckVerified_TestDisplayName_54: _,
    SteamDeckVerified_TestDisplayName_55: _,
    SteamDeckVerified_TestDisplayName_56: _,
    SteamDeckVerified_TestDisplayName_57: _,
    SteamDeckVerified_TestDisplayName_58: _,
    SteamDeckVerified_TestDisplayName_59: _,
    SteamDeckVerified_TestDisplayName_60: _,
    SteamDeckVerified_TestDisplayName_61: _,
    SteamDeckVerified_TestDisplayName_62: _,
    SteamDeckVerified_TestDisplayName_63: _,
    SteamDeckVerified_TestDisplayName_64: _,
    SteamDeckVerified_TestDisplayName_65: _,
    Compatibility_Tab_Steam_Machine: _,
    Compatibility_Tab_Steam_OS: _,
    Compatibility_Tab_Steam_Deck: _,
    Compatibility_Tab_Steam_Frame: _,
    SteamDeck_BuildReview_PleaseRequestTest: _,
    SteamFrame_BuildReview_Checklist_Intro_Header_V2: _,
    SteamFrame_BuildReview_PleaseConfirm_Title_V2: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P1: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P3: _,
    SteamFrame_BuildReview_Checklist_Intro_Details_P3_ReviewProcess: _,
    SteamFrame_BuildReview_PleaseConfirm_Description_V2: _,
    SteamDeck_TestRequest_BuildNotReleased: _,
    SteamDeck_BuildReview_Checklist_Intro: _,
    SteamDeck_BuildReview_Checklist_Intro_Header_V2: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P1: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P2: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3_ReviewProcess: _,
    SteamDeck_BuildReview_Checklist_Intro_Details_P3_Additional: _,
    SteamDeck_BuildReview_PleaseConfirm_Title_V2: _,
    SteamDeck_BuildReview_PleaseConfirm_Description_V2: _,
    SteamDeck_BuildReview_AppTypeUnavailable: _,
    SteamDeck_BuildReview_Checklist_Input: _,
    SteamDeck_BuildReview_Checklist_Text: _,
    SteamDeck_BuildReview_Checklist_Display: _,
    SteamDeck_BuildReview_Checklist_Functionality: _,
    SteamDeck_BuildReview_Checklist_SteamCloud: _,
    SteamDeck_BuildReview_Checklist_Launcher: _,
    SteamDeck_BuildReview_Checklist_Branch: _,
    SteamDeck_BuildReview_Checklist_Branch_PleaseTest: _,
    SteamDeck_BuildReview_MarkReady_Button: _,
    SteamDeck_BuildReview_MarkReady_Description: _,
    SteamDeck_BuildReview_MarkReady_Notes: _,
    SteamDeck_BuildReview_MarkReady_NotesDefault: _,
    SteamDeck_BuildReview_HelpRequest_Link: _,
    SteamDeck_BuildReview_ViewMoreDetailsInHelp: _,
    SteamDeck_BuildReview_Create_HelpRequest_Title: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes_1: _,
    SteamDeck_BuildReview_Create_HelpRequest_Notes_2: _,
    SteamDeck_BuildReview_Create_HelpRequest_SupportTicketIntro: _,
    SteamDeck_BuildReview_Check_Controller: _,
    SteamDeck_BuildReview_Check_Icons: _,
    SteamDeck_BuildReview_Check_TextInput: _,
    SteamDeck_BuildReview_Check_TextInput_V2_NoTextEntry: _,
    SteamDeck_BuildReview_Check_TextInput_V2_YesSteamAPIs: _,
    SteamDeck_BuildReview_Check_TextInput_V2_NoSteamAPIs: _,
    SteamDeck_BuildReview_Check_Cloud_NoSaves: _,
    SteamDeck_BuildReview_Check_Cloud_YesSavesNoCloud: _,
    SteamDeck_BuildReview_Check_Cloud_SinglePlatform: _,
    SteamDeck_BuildReview_Check_Cloud_YesCrossSaves: _,
    SteamDeck_BuildReview_Check_Cloud_NoCrossSaves: _,
    SteamDeck_BuildReview_Check_Display1280: _,
    SteamDeck_BuildReview_Check_DisplayFont: _,
    SteamDeck_BuildReview_Check_FunctionalityLauncher: _,
    SteamDeck_BuildReview_Check_FunctionalityCloudSaves: _,
    SteamDeck_BuildReview_Check_FunctionalityCrossPlatformCloudSaves: _,
    SteamDeck_BuildReview_Check_TestLinuxBuild_Preamble: _,
    SteamDeck_BuildReview_Check_TestLinuxBuild: _,
    SteamDeck_BuildReview_Check_Launcher_V2_NoLauncher: _,
    SteamDeck_BuildReview_Check_Launcher_V2_ControllerSupport: _,
    SteamDeck_BuildReview_Check_Launcher_V2_NoControllerSupport: _,
    SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves: _,
    SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves_Documentation: _,
    SteamDeck_BuildReview_CheckNote_DisplayFont: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_InputRecommendations:
      _,
    SteamDeck_BuildReview_CheckNote_Launcher_V2_NoControllerSupport: _,
    SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_LauncherRecommendations:
      _,
    SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud: _,
    SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud_SteamCloud: _,
    SteamDeck_BuildReview_CheckNote_FullController: _,
    SteamDeck_BuildReview_InReview_Title: _,
    SteamDeck_BuildReview_InReview_Description: _,
    SteamDeck_BuildReview_PleaseComplete: _,
    SteamDeck_BuildReview_Unsupported_Title: _,
    SteamDeck_BuildReview_Unsupported_Description: _,
    SteamDeck_BuildReview_NotMeetRequirements_Title: _,
    SteamDeck_BuildReview_NotMeetRequirements_Description: _,
    SteamFrame_BuildReview_Checklist_Build: _,
    SteamFrame_BuildReview_Build_Android: _,
    SteamFrame_BuildReview_Build_Windows: _,
    SteamFrame_BuildReview_Build_Linux: _,
    SteamFrame_BuildReview_Checklist_Dimension: _,
    SteamFrame_BuildReview_Dimension_2D: `2D`,
    SteamFrame_BuildReview_Dimension_VR: `RV`,
    SteamFrame_NotApplicableForDimension: _,
    SteamFrame_BuildReview_Check_VRPerformance_Verified_Without: _,
    SteamFrame_BuildReview_Check_VRPerformance_Verified_With: _,
    SteamFrame_BuildReview_Check_VRPerformance_Playable_Without: _,
    SteamFrame_BuildReview_Check_VRPerformance_Playable_With: _,
    SteamFrame_BuildReview_Check_VRPerformance_Unsupported: _,
    SteamFrame_BuildReview_Check_VRPerformance_NotApplicable: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_Title: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_Description: _,
    SteamFrame_BuildReview_VRPerformanceLink: _,
    SteamFrame_BuildReview_CheckNote_DisplayFont: _,
    SteamFrame_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs: _,
    SteamFrame_BuildReview_Compatibility_Checklist: _,
    SteamFrame_BuildReview_CheckNote_Launcher_V2_NoControllerSupport: _,
    SteamFrame_BuildReview_CheckNote_Cloud_YesSavesNoCloud: _,
    SteamFrame_BuildReview_CheckNote_Cloud_NoCrossSaves: _,
    SteamFrame_BuildReview_Check_Icons: _,
    SteamFrame_BuildReview_Checklist_VRPerformance_StatusReason: _,
    SteamFrame_BuildReview_Check_VRPerformance_Startup: _,
    SteamFrame_BuildReview_Check_VRPerformance_Loading: _,
    SteamFrame_BuildReview_Check_VRPerformance_Other: _,
    SteamFrame_BuildReview_CheckNote_Missing_Android_License: _,
    SteamFrame_BuildReview_CheckNote_Missing_Android_License_Link: _,
    dummy: _,
  };
export {
  _ as Compatibility_Tab_Steam_Deck,
  _ as Compatibility_Tab_Steam_Frame,
  _ as Compatibility_Tab_Steam_Machine,
  _ as Compatibility_Tab_Steam_OS,
  _ as ContentSurvey_History_Title,
  _ as ContentSurvey_History_Title_Default,
  _ as ContentSurvey_InvalidApp,
  _ as ContentSurvey_Title,
  _ as ContentSurvey_Title_Default,
  _ as Footer_Description,
  _ as Footer_Sitemap_ContactSupport,
  _ as PartnerSite_NotLoggedIn,
  _ as PartnerSite_PermissionDenied,
  _ as PricingExplorer_About_Dash,
  _ as PricingExplorer_About_Desc1,
  _ as PricingExplorer_About_Desc2,
  _ as PricingExplorer_About_LastUpdated,
  _ as PricingExplorer_About_Link1,
  _ as PricingExplorer_About_Link2,
  _ as PricingExplorer_About_LinkName1,
  _ as PricingExplorer_About_LinkName2,
  _ as PricingExplorer_About_Title,
  _ as PricingExplorer_Base,
  _ as PricingExplorer_BasePrice,
  _ as PricingExplorer_Column1,
  _ as PricingExplorer_Column2,
  _ as PricingExplorer_Column3,
  _ as PricingExplorer_Column4,
  _ as PricingExplorer_Explore_desc1,
  _ as PricingExplorer_Explore_line1,
  _ as PricingExplorer_Explore_line2,
  _ as PricingExplorer_Explore_line3,
  _ as PricingExplorer_Explore_title,
  _ as PricingExplorer_LoadError,
  _ as PricingExplorer_Regions_Column1,
  _ as PricingExplorer_Regions_TableHeader,
  _ as PricingExplorer_TableHeader,
  _ as Pricing_Dummy,
  _ as SteamDeckVerified_TestDisplayName_0,
  _ as SteamDeckVerified_TestDisplayName_1,
  _ as SteamDeckVerified_TestDisplayName_10,
  _ as SteamDeckVerified_TestDisplayName_11,
  _ as SteamDeckVerified_TestDisplayName_12,
  _ as SteamDeckVerified_TestDisplayName_13,
  _ as SteamDeckVerified_TestDisplayName_14,
  _ as SteamDeckVerified_TestDisplayName_15,
  _ as SteamDeckVerified_TestDisplayName_16,
  _ as SteamDeckVerified_TestDisplayName_17,
  _ as SteamDeckVerified_TestDisplayName_18,
  _ as SteamDeckVerified_TestDisplayName_19,
  _ as SteamDeckVerified_TestDisplayName_2,
  _ as SteamDeckVerified_TestDisplayName_20,
  _ as SteamDeckVerified_TestDisplayName_21,
  _ as SteamDeckVerified_TestDisplayName_22,
  _ as SteamDeckVerified_TestDisplayName_23,
  _ as SteamDeckVerified_TestDisplayName_24,
  _ as SteamDeckVerified_TestDisplayName_25,
  _ as SteamDeckVerified_TestDisplayName_26,
  _ as SteamDeckVerified_TestDisplayName_27,
  _ as SteamDeckVerified_TestDisplayName_29,
  _ as SteamDeckVerified_TestDisplayName_3,
  _ as SteamDeckVerified_TestDisplayName_30,
  _ as SteamDeckVerified_TestDisplayName_31,
  _ as SteamDeckVerified_TestDisplayName_32,
  _ as SteamDeckVerified_TestDisplayName_33,
  _ as SteamDeckVerified_TestDisplayName_34,
  _ as SteamDeckVerified_TestDisplayName_35,
  _ as SteamDeckVerified_TestDisplayName_36,
  _ as SteamDeckVerified_TestDisplayName_37,
  _ as SteamDeckVerified_TestDisplayName_38,
  _ as SteamDeckVerified_TestDisplayName_39,
  _ as SteamDeckVerified_TestDisplayName_4,
  _ as SteamDeckVerified_TestDisplayName_40,
  _ as SteamDeckVerified_TestDisplayName_41,
  _ as SteamDeckVerified_TestDisplayName_42,
  _ as SteamDeckVerified_TestDisplayName_43,
  _ as SteamDeckVerified_TestDisplayName_44,
  _ as SteamDeckVerified_TestDisplayName_45,
  _ as SteamDeckVerified_TestDisplayName_46,
  _ as SteamDeckVerified_TestDisplayName_47,
  _ as SteamDeckVerified_TestDisplayName_48,
  _ as SteamDeckVerified_TestDisplayName_49,
  _ as SteamDeckVerified_TestDisplayName_5,
  _ as SteamDeckVerified_TestDisplayName_50,
  _ as SteamDeckVerified_TestDisplayName_51,
  _ as SteamDeckVerified_TestDisplayName_52,
  _ as SteamDeckVerified_TestDisplayName_53,
  _ as SteamDeckVerified_TestDisplayName_54,
  _ as SteamDeckVerified_TestDisplayName_55,
  _ as SteamDeckVerified_TestDisplayName_56,
  _ as SteamDeckVerified_TestDisplayName_57,
  _ as SteamDeckVerified_TestDisplayName_58,
  _ as SteamDeckVerified_TestDisplayName_59,
  _ as SteamDeckVerified_TestDisplayName_6,
  _ as SteamDeckVerified_TestDisplayName_60,
  _ as SteamDeckVerified_TestDisplayName_61,
  _ as SteamDeckVerified_TestDisplayName_62,
  _ as SteamDeckVerified_TestDisplayName_63,
  _ as SteamDeckVerified_TestDisplayName_64,
  _ as SteamDeckVerified_TestDisplayName_65,
  _ as SteamDeckVerified_TestDisplayName_7,
  _ as SteamDeckVerified_TestDisplayName_8,
  _ as SteamDeckVerified_TestDisplayName_9,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyDescription_RecommendedRuntime,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_ExpectedInput,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_FDMDebug,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RPODebug,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RecommendedRuntime,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_RequiresH264,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TSOEnable,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TestedBuildID,
  _ as SteamDeckVerified_TestDisplayName_TestPropertyName_TestedProtonVersion,
  _ as SteamDeck_AppLanding_History,
  _ as SteamDeck_AppLanding_Published,
  _ as SteamDeck_AppLanding_Unpublished,
  _ as SteamDeck_BuildReview_AppTypeUnavailable,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_NoCrossSaves_Documentation,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud,
  _ as SteamDeck_BuildReview_CheckNote_Cloud_YesSavesNoCloud_SteamCloud,
  _ as SteamDeck_BuildReview_CheckNote_DisplayFont,
  _ as SteamDeck_BuildReview_CheckNote_FullController,
  _ as SteamDeck_BuildReview_CheckNote_Launcher_V2_NoControllerSupport,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_InputRecommendations,
  _ as SteamDeck_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs_LauncherRecommendations,
  _ as SteamDeck_BuildReview_Check_Cloud_NoCrossSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_NoSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_SinglePlatform,
  _ as SteamDeck_BuildReview_Check_Cloud_YesCrossSaves,
  _ as SteamDeck_BuildReview_Check_Cloud_YesSavesNoCloud,
  _ as SteamDeck_BuildReview_Check_Controller,
  _ as SteamDeck_BuildReview_Check_Display1280,
  _ as SteamDeck_BuildReview_Check_DisplayFont,
  _ as SteamDeck_BuildReview_Check_FunctionalityCloudSaves,
  _ as SteamDeck_BuildReview_Check_FunctionalityCrossPlatformCloudSaves,
  _ as SteamDeck_BuildReview_Check_FunctionalityLauncher,
  _ as SteamDeck_BuildReview_Check_Icons,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_ControllerSupport,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_NoControllerSupport,
  _ as SteamDeck_BuildReview_Check_Launcher_V2_NoLauncher,
  _ as SteamDeck_BuildReview_Check_TestLinuxBuild,
  _ as SteamDeck_BuildReview_Check_TestLinuxBuild_Preamble,
  _ as SteamDeck_BuildReview_Check_TextInput,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_NoSteamAPIs,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_NoTextEntry,
  _ as SteamDeck_BuildReview_Check_TextInput_V2_YesSteamAPIs,
  _ as SteamDeck_BuildReview_Checklist_Branch,
  _ as SteamDeck_BuildReview_Checklist_Branch_PleaseTest,
  _ as SteamDeck_BuildReview_Checklist_Display,
  _ as SteamDeck_BuildReview_Checklist_Functionality,
  _ as SteamDeck_BuildReview_Checklist_Input,
  _ as SteamDeck_BuildReview_Checklist_Intro,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P1,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P2,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3_Additional,
  _ as SteamDeck_BuildReview_Checklist_Intro_Details_P3_ReviewProcess,
  _ as SteamDeck_BuildReview_Checklist_Intro_Header_V2,
  _ as SteamDeck_BuildReview_Checklist_Launcher,
  _ as SteamDeck_BuildReview_Checklist_SteamCloud,
  _ as SteamDeck_BuildReview_Checklist_Text,
  _ as SteamDeck_BuildReview_CompatibilityTests,
  _ as SteamDeck_BuildReview_Create_HelpRequest,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_1,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2a,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Desc_RereviewRequest_2b,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes,
  _ as SteamDeck_BuildReview_Create_HelpRequest_NotesDefault,
  _ as SteamDeck_BuildReview_Create_HelpRequest_NotesDefault_Rereview,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes_1,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Notes_2,
  _ as SteamDeck_BuildReview_Create_HelpRequest_SupportTicketIntro,
  _ as SteamDeck_BuildReview_Create_HelpRequest_Title,
  _ as SteamDeck_BuildReview_Documentation,
  _ as SteamDeck_BuildReview_Header_History,
  _ as SteamDeck_BuildReview_Header_Results,
  _ as SteamDeck_BuildReview_HelpRequest_Link,
  _ as SteamDeck_BuildReview_Help_Request_Title,
  _ as SteamDeck_BuildReview_InReview_Description,
  _ as SteamDeck_BuildReview_InReview_Title,
  _ as SteamDeck_BuildReview_InReview_ViewTicket,
  _ as SteamDeck_BuildReview_MarkReady_Button,
  _ as SteamDeck_BuildReview_MarkReady_Description,
  _ as SteamDeck_BuildReview_MarkReady_Notes,
  _ as SteamDeck_BuildReview_MarkReady_NotesDefault,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Description,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Button,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Label_Machine,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Resubmit_Ticket_Content,
  _ as SteamDeck_BuildReview_NotMeetRequirements_Title,
  _ as SteamDeck_BuildReview_PleaseComplete,
  _ as SteamDeck_BuildReview_PleaseConfirm_Description_V2,
  _ as SteamDeck_BuildReview_PleaseConfirm_Title_V2,
  _ as SteamDeck_BuildReview_PleaseRequestTest,
  _ as SteamDeck_BuildReview_PublishDialog_Body,
  _ as SteamDeck_BuildReview_PublishDialog_Title,
  _ as SteamDeck_BuildReview_PublishResults,
  _ as SteamDeck_BuildReview_PublishedOn,
  _ as SteamDeck_BuildReview_ReportedOn,
  _ as SteamDeck_BuildReview_RequestStatusActive,
  _ as SteamDeck_BuildReview_RequestStatusClosed,
  _ as SteamDeck_BuildReview_Status_Description,
  _ as SteamDeck_BuildReview_Status_Fail,
  _ as SteamDeck_BuildReview_Status_FailMinor,
  _ as SteamDeck_BuildReview_Status_NotApplicable,
  _ as SteamDeck_BuildReview_Status_Pass,
  _ as SteamDeck_BuildReview_Status_Raw_Comment,
  _ as SteamDeck_BuildReview_Status_Raw_Description,
  _ as SteamDeck_BuildReview_Status_Raw_Impact,
  _ as SteamDeck_BuildReview_Status_Raw_Result,
  _ as SteamDeck_BuildReview_Status_Raw_Test,
  _ as SteamDeck_BuildReview_Status_Raw_Title,
  _ as SteamDeck_BuildReview_Status_TestProperties_Description,
  _ as SteamDeck_BuildReview_Status_TestProperties_Playable,
  _ as SteamDeck_BuildReview_Status_TestProperty_Desc,
  _ as SteamDeck_BuildReview_Status_TestProperty_Name,
  _ as SteamDeck_BuildReview_Status_TestProperty_Value,
  _ as SteamDeck_BuildReview_Status_Title,
  _ as SteamDeck_BuildReview_UnknownError,
  _ as SteamDeck_BuildReview_Unsupported_Description,
  _ as SteamDeck_BuildReview_Unsupported_Title,
  _ as SteamDeck_BuildReview_ViewMoreDetailsInHelp,
  _ as SteamDeck_BuildReview_Viewing_Historical,
  _ as SteamDeck_BuildReview_Viewing_Published,
  _ as SteamDeck_HardwareCompatibility_Title,
  _ as SteamDeck_TestRequest_BuildNotReleased,
  _ as SteamFrame_BuildReview_Build_Android,
  _ as SteamFrame_BuildReview_Build_Linux,
  _ as SteamFrame_BuildReview_Build_Windows,
  _ as SteamFrame_BuildReview_CheckNote_Cloud_NoCrossSaves,
  _ as SteamFrame_BuildReview_CheckNote_Cloud_YesSavesNoCloud,
  _ as SteamFrame_BuildReview_CheckNote_DisplayFont,
  _ as SteamFrame_BuildReview_CheckNote_Launcher_V2_NoControllerSupport,
  _ as SteamFrame_BuildReview_CheckNote_Missing_Android_License,
  _ as SteamFrame_BuildReview_CheckNote_Missing_Android_License_Link,
  _ as SteamFrame_BuildReview_CheckNote_TextInput_V2_NoSteamAPIs,
  _ as SteamFrame_BuildReview_Check_Icons,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Loading,
  _ as SteamFrame_BuildReview_Check_VRPerformance_NotApplicable,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Other,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Playable_With,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Playable_Without,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Startup,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Unsupported,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Verified_With,
  _ as SteamFrame_BuildReview_Check_VRPerformance_Verified_Without,
  _ as SteamFrame_BuildReview_Checklist_Build,
  _ as SteamFrame_BuildReview_Checklist_Dimension,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P1,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P3,
  _ as SteamFrame_BuildReview_Checklist_Intro_Details_P3_ReviewProcess,
  _ as SteamFrame_BuildReview_Checklist_Intro_Header_V2,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_Description,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_StatusReason,
  _ as SteamFrame_BuildReview_Checklist_VRPerformance_Title,
  _ as SteamFrame_BuildReview_Compatibility_Checklist,
  _ as SteamFrame_BuildReview_Dimension_2D,
  _ as SteamFrame_BuildReview_Dimension_VR,
  _ as SteamFrame_BuildReview_PleaseConfirm_Description_V2,
  _ as SteamFrame_BuildReview_PleaseConfirm_Title_V2,
  _ as SteamFrame_BuildReview_VRPerformanceLink,
  _ as SteamFrame_NotApplicableForDimension,
  _ as SteamHardware_BuildReview_Playable_Description,
  _ as SteamHardware_BuildReview_Playable_Title,
  _ as SteamHardware_BuildReview_Unknown_Title,
  _ as SteamHardware_BuildReview_Unsupported_Description,
  _ as SteamHardware_BuildReview_Unsupported_Title,
  _ as SteamHardware_BuildReview_Verified_Description,
  _ as SteamHardware_BuildReview_Verified_Share,
  _ as SteamHardware_BuildReview_Verified_Title,
  _ as SteamHardware_Frame_Unknown,
  _ as SteamHardware_Machine_Unknown,
  _ as SteamHardware_RatingImpact_Informational,
  _ as SteamHardware_RatingImpact_Playable,
  _ as SteamHardware_RatingImpact_Unsupported,
  _ as SteamLearn_Edit,
  _ as SteamLearn_Project_Discard,
  _ as SteamLearn_Project_InferenceTester,
  _ as SteamLearn_Project_Overview,
  _ as SteamLearn_Project_Publish_Accept,
  _ as SteamLearn_Project_Publish_Cancel,
  _ as SteamLearn_Project_Save,
  _ as SteamLearn_Status_Fetch_Status_Canceled,
  _ as SteamLearn_Status_Fetch_Status_Error,
  _ as Valve_Confidential,
  _ as Valve_Confidential_Description,
  _ as default,
  _ as dummy,
};
