name: Track Steam Updates

on:
  workflow_dispatch:

concurrency:
  group: update
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 1
